"""Class 1 - Finance: coins and notes, saving, needs and wants, sharing and planning."""
from . import mcq


def coins(n, value, story_en, story_bn):
    """How much money is n coins of one value."""
    r = n * value
    wrong = [r + value, max(value, r - value) if r - value != r else r + 2 * value, n + value]
    opts = [str(r)] + [str(w) for w in wrong]
    if len(set(opts)) < 4:
        opts = [str(r), str(r + value), str(r + 2 * value), str(r + 3 * value)]
    return mcq(story_en, [f"Rs {o}" for o in opts], 0,
               f"{n} coins of Rs {value}: " + " + ".join([str(value)] * n) + f" = Rs {r}.",
               story_bn, [f"{o} টাকা" for o in opts],
               f"{value} টাকার {n}টি পয়সা: " + " + ".join([str(value)] * n) + f" = {r} টাকা।")


def change(price, paid, item_en, item_bn):
    r = paid - price
    opts = [r, r + 1, r + 2, max(1, r - 1) if r > 1 else r + 3]
    return mcq(f"A {item_en} costs Rs {price}. You pay with Rs {paid}. How much change do you get?",
               [f"Rs {o}" for o in opts], 0,
               f"Change = money paid - price = {paid} - {price} = Rs {r}.",
               f"একটি {item_bn}-এর দাম {price} টাকা। তুমি {paid} টাকা দিলে। কত টাকা ফেরত পাবে?",
               [f"{o} টাকা" for o in opts],
               f"ফেরত = দেওয়া টাকা - দাম = {paid} - {price} = {r} টাকা।")


ITEMS = (
    mcq("Dad gives you Rs 10 on Monday. You hide Rs 5 under your pillow instead of buying sweets. What did you just do?",
        ["You saved money for later", "You lost money", "You borrowed money", "You paid a bill"], 0,
        "Keeping money for later is saving - maybe for a bigger chocolate bar, or something you really need.",
        "সোমবার বাবা তোমাকে 10 টাকা দিলেন। তুমি মিষ্টি না কিনে 5 টাকা বালিশের নিচে লুকিয়ে রাখলে। তুমি কী করলে?",
        ["পরের জন্য টাকা জমালে", "টাকা হারালে", "টাকা ধার নিলে", "বিল মেটালে"],
        "পরের জন্য টাকা রেখে দেওয়াই সঞ্চয় - হয়তো আরও বড় চকলেটের জন্য, বা সত্যিই দরকারি কিছুর জন্য।"),
    mcq("What is a piggy bank for?", ["Keeping your saved coins safe", "Feeding a pig", "Playing football", "Cooking"], 0,
        "A piggy bank is a box where you drop coins to save them up.",
        "মাটির ভাঁড় (পিগি ব্যাংক) কীসের জন্য?", ["জমানো পয়সা নিরাপদে রাখতে", "শূকরকে খাওয়াতে", "ফুটবল খেলতে", "রান্না করতে"],
        "মাটির ভাঁড় এমন একটা বাক্স, যেখানে পয়সা ফেলে জমানো হয়।"),
    coins(3, 2, "You have 3 coins of Rs 2. How much money is that?", "তোমার কাছে 2 টাকার 3টি পয়সা। মোট কত টাকা?"),
    coins(4, 5, "You have 4 coins of Rs 5. How much money do you have?", "তোমার কাছে 5 টাকার 4টি পয়সা। তোমার কত টাকা আছে?"),
    coins(2, 10, "Two Rs 10 coins make how much?", "10 টাকার দুটি পয়সায় মোট কত?"),
    coins(5, 1, "Five Rs 1 coins make how much?", "1 টাকার পাঁচটি পয়সায় মোট কত?"),
    coins(3, 5, "You find three Rs 5 coins in your coat. How much did you find?", "কোটের পকেটে 5 টাকার তিনটি পয়সা পেলে। কত টাকা পেলে?"),
    coins(6, 2, "Grandma gives you six Rs 2 coins. How much is that?", "দিদিমা তোমাকে 2 টাকার ছয়টি পয়সা দিলেন। মোট কত?"),
    coins(2, 20, "You have two Rs 20 notes. How much money is that?", "তোমার কাছে 20 টাকার দুটি নোট। মোট কত টাকা?"),
    coins(4, 10, "Four Rs 10 coins make how much?", "10 টাকার চারটি পয়সায় মোট কত?"),
    change(7, 10, "pencil", "পেনসিল"),
    change(4, 5, "balloon", "বেলুন"),
    change(12, 20, "notebook", "খাতা"),
    change(15, 20, "toy car", "খেলনা গাড়ি"),
    change(6, 10, "ice lolly", "আইসক্রিম"),
    change(35, 50, "storybook", "গল্পের বই"),
    change(3, 5, "sweet", "লজেন্স"),
    change(18, 20, "ball", "বল"),
    mcq("Which is a NEED (something you must have)?", ["Food", "A new video game", "A third toy car", "A sticker"], 0,
        "Needs keep us alive and healthy: food, water, clothes, a home. Wants are nice extras.",
        "কোনটা প্রয়োজন (যা তোমার থাকতেই হবে)?", ["খাবার", "নতুন ভিডিও গেম", "তৃতীয় খেলনা গাড়ি", "একটা স্টিকার"],
        "প্রয়োজন আমাদের বাঁচায় আর সুস্থ রাখে: খাবার, জল, জামা, ঘর। চাওয়া হলো বাড়তি ভালো জিনিস।"),
    mcq("Which is a WANT (nice to have, but not needed)?", ["A toy robot", "Drinking water", "A warm coat in winter", "Medicine when you are ill"], 0,
        "A toy robot is fun, but you can live without it. Water, warm clothes and medicine are needs.",
        "কোনটা চাওয়া (থাকলে ভালো, কিন্তু দরকারি নয়)?", ["খেলনা রোবট", "খাওয়ার জল", "শীতে গরম কোট", "অসুখে ওষুধ"],
        "খেলনা রোবট মজার, কিন্তু তা ছাড়াও বাঁচা যায়। জল, গরম জামা আর ওষুধ প্রয়োজন।"),
    mcq("You want a Rs 50 football and have Rs 30. What can you do?", ["Save Rs 20 more first", "Take it without paying", "Cry loudly", "Buy it anyway with no money"], 0,
        "If you do not have enough, you save until you do. 30 + 20 = 50.",
        "তুমি 50 টাকার একটা ফুটবল চাও, আছে 30 টাকা। কী করতে পারো?", ["আগে আরও 20 টাকা জমাও", "টাকা না দিয়ে নিয়ে নাও", "জোরে কাঁদো", "টাকা ছাড়াই কিনে নাও"],
        "যথেষ্ট টাকা না থাকলে যতক্ষণ না হয় জমাও। 30 + 20 = 50।"),
    mcq("Where do grown-ups usually keep their money safe?", ["In a bank", "Under a tree", "In the river", "In a sandcastle"], 0,
        "Banks keep money safe and can even pay you a little extra (interest) for keeping it there.",
        "বড়রা সাধারণত টাকা কোথায় নিরাপদে রাখেন?", ["ব্যাংকে", "গাছের নিচে", "নদীতে", "বালির দুর্গে"],
        "ব্যাংক টাকা নিরাপদে রাখে, এমনকি রাখার জন্য একটু বাড়তি (সুদ) দিতেও পারে।"),
    mcq("Which is worth more: a Rs 10 note or a Rs 2 coin?", ["The Rs 10 note", "The Rs 2 coin", "They are equal", "Coins are always worth more"], 0,
        "Value is the number written on it, not its size: 10 is more than 2.",
        "কোনটার দাম বেশি: 10 টাকার নোট নাকি 2 টাকার পয়সা?", ["10 টাকার নোট", "2 টাকার পয়সা", "দুটো সমান", "পয়সার দাম সবসময় বেশি"],
        "দাম লেখা সংখ্যা দিয়ে, আকার দিয়ে নয়: 10, 2-এর চেয়ে বেশি।"),
    mcq("You have Rs 20. You buy a Rs 8 snack and a Rs 5 drink. How much is left?", ["Rs 7", "Rs 13", "Rs 12", "Rs 33"], 0,
        "Spent 8 + 5 = 13. Left: 20 - 13 = Rs 7.",
        "তোমার কাছে 20 টাকা। 8 টাকার একটা খাবার আর 5 টাকার একটা পানীয় কিনলে। কত বাকি?", ["7 টাকা", "13 টাকা", "12 টাকা", "33 টাকা"],
        "খরচ 8 + 5 = 13। বাকি: 20 - 13 = 7 টাকা।"),
    mcq("You save Rs 2 every day. How much after 5 days?", ["Rs 10", "Rs 7", "Rs 2", "Rs 25"], 0,
        "2 + 2 + 2 + 2 + 2 = Rs 10. Small savings add up!",
        "তুমি প্রতিদিন 2 টাকা জমাও। 5 দিন পরে কত হবে?", ["10 টাকা", "7 টাকা", "2 টাকা", "25 টাকা"],
        "2 + 2 + 2 + 2 + 2 = 10 টাকা। ছোট ছোট সঞ্চয় জমে বড় হয়!"),
    mcq("A friend lends you Rs 5. What should you do later?", ["Give the Rs 5 back", "Keep it forever", "Ask for more", "Forget about it"], 0,
        "Borrowed money must be returned. Paying back on time keeps trust.",
        "এক বন্ধু তোমাকে 5 টাকা ধার দিল। পরে তোমার কী করা উচিত?", ["5 টাকা ফেরত দেওয়া", "চিরকাল রেখে দেওয়া", "আরও চাওয়া", "ভুলে যাওয়া"],
        "ধার নেওয়া টাকা ফেরত দিতে হয়। সময়মতো শোধ করলে বিশ্বাস থাকে।"),
    mcq("Which costs more: a bicycle or a pencil?", ["A bicycle", "A pencil", "They cost the same", "Nothing has a price"], 0,
        "A bicycle takes much more material and work to make, so it costs much more.",
        "কোনটার দাম বেশি: সাইকেল নাকি পেনসিল?", ["সাইকেল", "পেনসিল", "দাম সমান", "কোনো জিনিসের দাম নেই"],
        "সাইকেল বানাতে অনেক বেশি উপাদান আর পরিশ্রম লাগে, তাই দাম অনেক বেশি।"),
    mcq("Why do people work?", ["To earn money for what they need", "To get tired only", "Because money grows on trees", "To lose money"], 0,
        "Work earns money, and money buys food, a home and other things we need.",
        "মানুষ কাজ করে কেন?", ["দরকারি জিনিসের জন্য টাকা রোজগার করতে", "শুধু ক্লান্ত হতে", "কারণ টাকা গাছে ধরে", "টাকা হারাতে"],
        "কাজ করে টাকা রোজগার হয়, আর টাকায় খাবার, ঘর আর অন্য দরকারি জিনিস কেনা যায়।"),
    mcq("Does money grow on trees?", ["No - it is earned by working", "Yes, on mango trees", "Yes, in the rainy season", "Only on Sundays"], 0,
        "Money does not grow on trees! People earn it by doing useful work.",
        "টাকা কি গাছে ধরে?", ["না - কাজ করে রোজগার করতে হয়", "হ্যাঁ, আমগাছে", "হ্যাঁ, বর্ষায়", "শুধু রবিবারে"],
        "টাকা গাছে ধরে না! মানুষ কাজের কাজ করে টাকা রোজগার করে।"),
    mcq("Your piggy bank has Rs 15 and you add Rs 5. How much now?", ["Rs 20", "Rs 10", "Rs 155", "Rs 25"], 0,
        "15 + 5 = Rs 20.",
        "তোমার ভাঁড়ে 15 টাকা, আরও 5 টাকা রাখলে। এখন কত?", ["20 টাকা", "10 টাকা", "155 টাকা", "25 টাকা"],
        "15 + 5 = 20 টাকা।"),
    mcq("Two friends share Rs 10 equally. How much does each get?", ["Rs 5", "Rs 10", "Rs 2", "Rs 20"], 0,
        "Sharing equally between 2: 10 ÷ 2 = Rs 5 each.",
        "দুই বন্ধু 10 টাকা সমানভাবে ভাগ করল। প্রত্যেকে কত পেল?", ["5 টাকা", "10 টাকা", "2 টাকা", "20 টাকা"],
        "2 জনের মধ্যে সমান ভাগ: 10 ÷ 2 = প্রত্যেকে 5 টাকা।"),
    mcq("You see two identical toys: one for Rs 20, one for Rs 15. Which is the better buy?", ["The Rs 15 toy", "The Rs 20 toy", "Both are the same deal", "Neither"], 0,
        "Same toy, lower price - you keep Rs 5 more.",
        "দুটি একই রকম খেলনা: একটা 20 টাকা, একটা 15 টাকা। কোনটা কেনা ভালো?", ["15 টাকার খেলনা", "20 টাকার খেলনা", "দুটো একই", "কোনোটাই না"],
        "একই খেলনা, কম দাম - তোমার হাতে আরও 5 টাকা থাকে।"),
    mcq("What is a price tag?", ["A label showing how much something costs", "A toy", "A game rule", "A kind of food"], 0,
        "The price tag tells you how much money you need to buy the item.",
        "দামের ট্যাগ (প্রাইস ট্যাগ) কী?", ["একটা লেবেল, যাতে জিনিসের দাম লেখা", "একটা খেলনা", "খেলার নিয়ম", "এক রকম খাবার"],
        "দামের ট্যাগ বলে দেয় জিনিসটা কিনতে কত টাকা লাগবে।"),
    mcq("Why is it good to save some money every week?", ["You will have money for something bigger or for emergencies", "Saving makes coins disappear", "It is not good", "Banks get angry"], 0,
        "Saving builds up money for big plans - or for surprises like a broken bicycle.",
        "প্রতি সপ্তাহে কিছু টাকা জমানো ভালো কেন?", ["বড় কিছু বা বিপদের জন্য টাকা থাকবে", "জমালে পয়সা উধাও হয়", "ভালো নয়", "ব্যাংক রেগে যায়"],
        "সঞ্চয় বড় পরিকল্পনার জন্য টাকা জমায় - বা ভাঙা সাইকেলের মতো আচমকা দরকারের জন্য।"),
    mcq("You have Rs 10 and want a Rs 4 sticker and a Rs 7 pen. Can you buy both?", ["No - together they cost Rs 11", "Yes, easily", "Yes, with Rs 5 left", "Yes, if you ask nicely"], 0,
        "4 + 7 = 11, which is more than 10. Choose one, or save Rs 1 more.",
        "তোমার কাছে 10 টাকা, চাও 4 টাকার স্টিকার আর 7 টাকার কলম। দুটোই কিনতে পারবে?", ["না - একসঙ্গে দাম 11 টাকা", "হ্যাঁ, সহজেই", "হ্যাঁ, 5 টাকা বাকি থাকবে", "হ্যাঁ, ভদ্রভাবে চাইলে"],
        "4 + 7 = 11, যা 10-এর বেশি। একটা বাছো, বা আরও 1 টাকা জমাও।"),
    mcq("A bridge builder must buy steel with the money they have. If steel costs more than their budget, what is the problem?", ["They cannot pay for it all", "Steel becomes free", "The bridge builds itself", "Nothing"], 0,
        "A budget is the money you have. Spending more than the budget means borrowing - just like in MODIS BridgeWorks.",
        "একজন সেতু-নির্মাতাকে হাতের টাকায় ইস্পাত কিনতে হবে। ইস্পাতের দাম বাজেটের বেশি হলে সমস্যা কী?", ["পুরোটা দাম দিতে পারবেন না", "ইস্পাত বিনামূল্যে হয়ে যায়", "সেতু নিজেই তৈরি হয়", "কিছুই না"],
        "বাজেট হলো হাতের টাকা। বাজেটের বেশি খরচ মানে ধার নেওয়া - ঠিক MODIS BridgeWorks-এর মতো।"),
    mcq("What is a budget?", ["A plan for how to use your money", "A kind of sweet", "A toy box", "A bank robber"], 0,
        "A budget says how much money you have and what you will spend it on.",
        "বাজেট কী?", ["টাকা কীভাবে খরচ করবে তার পরিকল্পনা", "এক রকম মিষ্টি", "খেলনার বাক্স", "ব্যাংক-ডাকাত"],
        "বাজেট বলে তোমার কত টাকা আছে আর কীসে খরচ করবে।"),
    mcq("You lose Rs 5 through a hole in your pocket. What could stop this?", ["Keep money in a safe purse or wallet", "Carry more money", "Make the hole bigger", "Spend it faster"], 0,
        "Keeping money in a safe place stops it getting lost.",
        "পকেটের ফুটো দিয়ে 5 টাকা হারিয়ে গেল। কী করলে এটা ঠেকানো যেত?", ["টাকা নিরাপদ পার্স বা মানিব্যাগে রাখা", "আরও টাকা বয়ে নেওয়া", "ফুটো আরও বড় করা", "আরও তাড়াতাড়ি খরচ করা"],
        "টাকা নিরাপদ জায়গায় রাখলে হারায় না।"),
    mcq("Which coin set makes Rs 10?", ["Rs 5 + Rs 5", "Rs 2 + Rs 2", "Rs 1 + Rs 5", "Rs 2 + Rs 5"], 0,
        "5 + 5 = 10. The others make 4, 6 and 7.",
        "কোন পয়সাগুলো মিলে 10 টাকা হয়?", ["5 টাকা + 5 টাকা", "2 টাকা + 2 টাকা", "1 টাকা + 5 টাকা", "2 টাকা + 5 টাকা"],
        "5 + 5 = 10। অন্যগুলোতে হয় 4, 6 আর 7।"),
    mcq("Which coin set makes Rs 7?", ["Rs 5 + Rs 2", "Rs 5 + Rs 1", "Rs 2 + Rs 2", "Rs 10 + Rs 2"], 0,
        "5 + 2 = 7.",
        "কোন পয়সাগুলো মিলে 7 টাকা হয়?", ["5 টাকা + 2 টাকা", "5 টাকা + 1 টাকা", "2 টাকা + 2 টাকা", "10 টাকা + 2 টাকা"],
        "5 + 2 = 7।"),
    mcq("If you spend all your pocket money on the first day, what happens for the rest of the week?", ["You have nothing left to spend", "More money appears", "The shop gives things free", "You get double money"], 0,
        "Spread your spending out - or you will have an empty pocket all week!",
        "প্রথম দিনেই সব হাতখরচ খরচ করে ফেললে সপ্তাহের বাকি দিন কী হবে?", ["খরচ করার কিছুই থাকবে না", "আরও টাকা হাজির হবে", "দোকান বিনামূল্যে জিনিস দেবে", "দ্বিগুণ টাকা পাবে"],
        "খরচ ছড়িয়ে করো - নইলে সারা সপ্তাহ পকেট ফাঁকা থাকবে!"),
    mcq("Your sister has Rs 12 and you have Rs 8. How much more does she have?", ["Rs 4", "Rs 20", "Rs 8", "Rs 12"], 0,
        "12 - 8 = Rs 4 more.",
        "তোমার বোনের কাছে 12 টাকা, তোমার কাছে 8 টাকা। তার কত বেশি আছে?", ["4 টাকা", "20 টাকা", "8 টাকা", "12 টাকা"],
        "12 - 8 = 4 টাকা বেশি।"),
    mcq("A toy costs Rs 30. You have saved Rs 18. How much more must you save?", ["Rs 12", "Rs 48", "Rs 18", "Rs 30"], 0,
        "30 - 18 = Rs 12 more.",
        "একটা খেলনার দাম 30 টাকা। তুমি জমিয়েছ 18 টাকা। আরও কত জমাতে হবে?", ["12 টাকা", "48 টাকা", "18 টাকা", "30 টাকা"],
        "30 - 18 = আরও 12 টাকা।"),
    mcq("Is it wise to buy something just because an advert says it is fun?", ["Think first: do you need it and can you afford it?", "Yes, always buy it at once", "Adverts are always right", "Buy two to be safe"], 0,
        "Adverts want you to buy. Smart shoppers stop and think before spending.",
        "বিজ্ঞাপন মজার বলেছে বলেই কিছু কেনা কি বুদ্ধিমানের কাজ?", ["আগে ভাবো: দরকার আছে কি, আর সামর্থ্য আছে কি?", "হ্যাঁ, সঙ্গে সঙ্গে কিনে ফেলো", "বিজ্ঞাপন সবসময় ঠিক", "নিশ্চিন্ত থাকতে দুটো কেনো"],
        "বিজ্ঞাপন চায় তুমি কেনো। বুদ্ধিমান ক্রেতা খরচের আগে থেমে ভাবে।"),
    mcq("Grandpa gives you Rs 20. You decide to save half. How much do you save?", ["Rs 10", "Rs 20", "Rs 5", "Rs 2"], 0,
        "Half of 20 is 10.",
        "দাদু তোমাকে 20 টাকা দিলেন। তুমি অর্ধেক জমানোর ঠিক করলে। কত জমাবে?", ["10 টাকা", "20 টাকা", "5 টাকা", "2 টাকা"],
        "20-এর অর্ধেক 10।"),
    mcq("Which helps you remember how much you spent?", ["Writing it down in a notebook", "Forgetting about it", "Throwing away receipts", "Guessing"], 0,
        "Writing down spending helps you see where your money goes.",
        "কত খরচ করেছ মনে রাখতে কী সাহায্য করে?", ["খাতায় লিখে রাখা", "ভুলে যাওয়া", "রসিদ ফেলে দেওয়া", "আন্দাজ করা"],
        "খরচ লিখে রাখলে বোঝা যায় টাকা কোথায় যাচ্ছে।"),
    mcq("A shop has a sign: '2 pens for Rs 10'. How much is one pen?", ["Rs 5", "Rs 10", "Rs 2", "Rs 20"], 0,
        "10 shared between 2 pens: Rs 5 each.",
        "দোকানে লেখা: '2টি কলম 10 টাকা'। একটা কলমের দাম কত?", ["5 টাকা", "10 টাকা", "2 টাকা", "20 টাকা"],
        "10 টাকা 2টি কলমে ভাগ: প্রতিটি 5 টাকা।"),
    mcq("Which is the best place to keep a big amount of savings?", ["A bank account", "A shoe left outside", "A paper bag in the rain", "Your school desk"], 0,
        "Banks are safe and keep a record of your money.",
        "অনেক সঞ্চয় রাখার সবচেয়ে ভালো জায়গা কোনটা?", ["ব্যাংক অ্যাকাউন্ট", "বাইরে রাখা জুতো", "বৃষ্টিতে কাগজের ব্যাগ", "স্কুলের ডেস্ক"],
        "ব্যাংক নিরাপদ আর তোমার টাকার হিসাব রাখে।"),
    mcq("If 1 apple costs Rs 3, how much do 3 apples cost?", ["Rs 9", "Rs 6", "Rs 3", "Rs 12"], 0,
        "3 + 3 + 3 = Rs 9.",
        "1টি আপেলের দাম 3 টাকা হলে 3টি আপেলের দাম কত?", ["9 টাকা", "6 টাকা", "3 টাকা", "12 টাকা"],
        "3 + 3 + 3 = 9 টাকা।"),
    mcq("What should you do if a shopkeeper gives you too much change by mistake?", ["Give the extra back", "Run away happily", "Keep quiet", "Ask for even more"], 0,
        "Being honest with money builds trust. The extra belongs to the shopkeeper.",
        "দোকানদার ভুল করে বেশি ফেরত দিলে কী করা উচিত?", ["বাড়তিটা ফেরত দেওয়া", "খুশিতে দৌড়ে পালানো", "চুপ করে থাকা", "আরও বেশি চাওয়া"],
        "টাকার ব্যাপারে সৎ থাকলে বিশ্বাস গড়ে ওঠে। বাড়তি টাকাটা দোকানদারের।"),
    mcq("You need Rs 25 for a book. You have one Rs 20 note and one Rs 5 coin. Is it enough?", ["Yes, exactly Rs 25", "No, Rs 5 short", "No, Rs 20 short", "Yes, with Rs 10 extra"], 0,
        "20 + 5 = 25. Exactly enough!",
        "একটা বইয়ের জন্য 25 টাকা লাগবে। তোমার কাছে 20 টাকার একটা নোট আর 5 টাকার একটা পয়সা। যথেষ্ট?", ["হ্যাঁ, ঠিক 25 টাকা", "না, 5 টাকা কম", "না, 20 টাকা কম", "হ্যাঁ, 10 টাকা বাড়তি"],
        "20 + 5 = 25। একদম ঠিকঠাক!"),
    mcq("What is pocket money?", ["Money given to children to spend or save", "Money found in the street", "Money for the bank only", "A toy coin"], 0,
        "Pocket money helps children learn to choose, spend and save.",
        "হাতখরচ কী?", ["শিশুদের খরচ বা জমানোর জন্য দেওয়া টাকা", "রাস্তায় পাওয়া টাকা", "শুধু ব্যাংকের টাকা", "খেলনার পয়সা"],
        "হাতখরচ শিশুদের বাছতে, খরচ করতে আর জমাতে শেখায়।"),
    mcq("A notebook costs Rs 10 at one shop and Rs 12 at another. How much do you save at the cheaper shop?", ["Rs 2", "Rs 22", "Rs 10", "Rs 12"], 0,
        "12 - 10 = Rs 2 saved.",
        "একটা খাতার দাম এক দোকানে 10 টাকা, আরেকটায় 12 টাকা। সস্তা দোকানে কত বাঁচে?", ["2 টাকা", "22 টাকা", "10 টাকা", "12 টাকা"],
        "12 - 10 = 2 টাকা বাঁচে।"),
    mcq("What does it mean to 'earn' money?", ["To get money for work you did", "To find it on the floor", "To take it from a friend", "To print it at home"], 0,
        "Earning means being paid for useful work - like helping in a garden or a shop.",
        "টাকা 'রোজগার' করা মানে কী?", ["কাজের বিনিময়ে টাকা পাওয়া", "মেঝেতে কুড়িয়ে পাওয়া", "বন্ধুর থেকে নিয়ে নেওয়া", "বাড়িতে ছাপানো"],
        "রোজগার মানে কাজের কাজ করে টাকা পাওয়া - যেমন বাগানে বা দোকানে সাহায্য করে।"),
    mcq("Why can't people print their own money at home?", ["Only the government may make money", "Printers are too small", "Paper is too expensive", "It is easy and allowed"], 0,
        "Money is made only by the country's central bank. Making your own is against the law.",
        "মানুষ বাড়িতে নিজের টাকা ছাপাতে পারে না কেন?", ["শুধু সরকারই টাকা বানাতে পারে", "প্রিন্টার খুব ছোট", "কাগজ খুব দামি", "এটা সহজ আর অনুমোদিত"],
        "টাকা শুধু দেশের কেন্দ্রীয় ব্যাংক বানায়। নিজে বানানো আইনবিরোধী।"),
    mcq("You saved Rs 3 on Monday, Rs 4 on Tuesday and Rs 3 on Wednesday. How much in all?", ["Rs 10", "Rs 7", "Rs 12", "Rs 9"], 0,
        "3 + 4 + 3 = Rs 10.",
        "সোমবার 3 টাকা, মঙ্গলবার 4 টাকা আর বুধবার 3 টাকা জমালে। মোট কত?", ["10 টাকা", "7 টাকা", "12 টাকা", "9 টাকা"],
        "3 + 4 + 3 = 10 টাকা।"),
    mcq("A family has Rs 100 for the week. Food costs Rs 70. How much is left for other things?", ["Rs 30", "Rs 170", "Rs 70", "Rs 100"], 0,
        "100 - 70 = Rs 30. Needs like food come first in a budget.",
        "একটি পরিবারের সপ্তাহের জন্য 100 টাকা। খাবারে লাগে 70 টাকা। অন্য জিনিসের জন্য কত বাকি?", ["30 টাকা", "170 টাকা", "70 টাকা", "100 টাকা"],
        "100 - 70 = 30 টাকা। বাজেটে খাবারের মতো প্রয়োজন আগে আসে।"),
    mcq("Which is a smart choice when you get birthday money?", ["Save some, spend some", "Spend it all in one minute", "Throw it away", "Hide it and forget where"], 0,
        "Saving some and spending some lets you enjoy now and plan for later.",
        "জন্মদিনে টাকা পেলে কোনটা বুদ্ধিমানের কাজ?", ["কিছু জমাও, কিছু খরচ করো", "এক মিনিটেই সব খরচ করো", "ফেলে দাও", "লুকিয়ে রেখে ভুলে যাও"],
        "কিছু জমালে আর কিছু খরচ করলে এখনও আনন্দ হয়, পরের পরিকল্পনাও হয়।"),
    mcq("Why do we pay for a bus ride?", ["The bus company pays the driver and for fuel", "Buses are free everywhere", "To make the bus heavier", "For no reason"], 0,
        "Fares pay for the driver's work, fuel and repairs - just like tolls pay for bridges.",
        "বাসে চড়তে ভাড়া দিই কেন?", ["বাস কোম্পানি চালকের মজুরি আর জ্বালানির খরচ দেয়", "সব জায়গায় বাস বিনামূল্যে", "বাস ভারী করতে", "কোনো কারণ নেই"],
        "ভাড়া দিয়ে চালকের কাজ, জ্বালানি আর মেরামতের খরচ ওঠে - যেমন টোল দিয়ে সেতুর খরচ ওঠে।"),
    mcq("What is a toll on a bridge?", ["A small payment to use the bridge", "A bridge troll", "A kind of brick", "A song"], 0,
        "Tolls are small fees from each driver. Together they pay back the cost of building the bridge.",
        "সেতুর টোল কী?", ["সেতু ব্যবহারের জন্য অল্প কিছু টাকা", "সেতুর দৈত্য", "এক রকম ইট", "একটা গান"],
        "টোল হলো প্রতিটি চালকের দেওয়া ছোট মাশুল। সব মিলিয়ে সেতু বানানোর খরচ উঠে আসে।"),
    mcq("A bridge toll is Rs 10 per car. 5 cars cross. How much toll is collected?", ["Rs 50", "Rs 15", "Rs 10", "Rs 5"], 0,
        "5 cars x Rs 10 = Rs 50.",
        "সেতুর টোল প্রতি গাড়ি 10 টাকা। 5টি গাড়ি পার হলো। কত টোল উঠল?", ["50 টাকা", "15 টাকা", "10 টাকা", "5 টাকা"],
        "5টি গাড়ি x 10 টাকা = 50 টাকা।"),
    mcq("If you lend your toy and your friend breaks it, what is fair?", ["They help fix or replace it", "Nothing", "You break their toy", "Shout at them"], 0,
        "When someone damages what they borrowed, the fair thing is to fix or replace it.",
        "তুমি খেলনা ধার দিলে আর বন্ধু ভেঙে ফেলল। কোনটা ন্যায্য?", ["সে সারাতে বা নতুন দিতে সাহায্য করবে", "কিছুই না", "তুমি তার খেলনা ভাঙবে", "তার দিকে চেঁচাবে"],
        "কেউ ধার নেওয়া জিনিস নষ্ট করলে সারিয়ে দেওয়া বা বদলে দেওয়াই ন্যায্য।"),
    mcq("You have Rs 9. Can you buy three Rs 3 erasers?", ["Yes, exactly", "No, Rs 3 short", "No, Rs 1 short", "Yes, with Rs 3 left"], 0,
        "3 x 3 = 9. Exactly enough.",
        "তোমার কাছে 9 টাকা। 3 টাকার তিনটি রাবার কিনতে পারবে?", ["হ্যাঁ, ঠিক ঠিক", "না, 3 টাকা কম", "না, 1 টাকা কম", "হ্যাঁ, 3 টাকা বাকি থাকবে"],
        "3 x 3 = 9। একদম ঠিক।"),
    mcq("Which is a good reason to save?", ["To buy a bicycle later", "To make coins heavier", "To fill the house with coins for fun", "Saving is never useful"], 0,
        "A clear goal, like a bicycle, makes saving easier and more fun.",
        "সঞ্চয়ের একটা ভালো কারণ কোনটা?", ["পরে সাইকেল কিনতে", "পয়সা ভারী করতে", "মজা করে ঘর পয়সায় ভরতে", "সঞ্চয় কখনো কাজের নয়"],
        "সাইকেলের মতো স্পষ্ট লক্ষ্য থাকলে জমানো সহজ আর মজার হয়।"),
    mcq("You buy a Rs 5 toffee every day. How much do you spend in a week (7 days)?", ["Rs 35", "Rs 12", "Rs 5", "Rs 57"], 0,
        "7 x 5 = Rs 35. Small daily treats add up to a lot!",
        "তুমি প্রতিদিন 5 টাকার একটা টফি কেনো। এক সপ্তাহে (7 দিন) কত খরচ?", ["35 টাকা", "12 টাকা", "5 টাকা", "57 টাকা"],
        "7 x 5 = 35 টাকা। রোজকার ছোট খরচ জমে অনেক হয়!"),
    mcq("Which helps you count lots of coins quickly?", ["Put them in groups of the same value", "Throw them in the air", "Count them in the dark", "Mix them with buttons"], 0,
        "Grouping coins (all the Rs 5s together, then the Rs 2s) makes counting easy.",
        "অনেক পয়সা তাড়াতাড়ি গুনতে কী সাহায্য করে?", ["একই দামের পয়সা দলে দলে সাজানো", "বাতাসে ছুড়ে দেওয়া", "অন্ধকারে গোনা", "বোতামের সঙ্গে মেশানো"],
        "পয়সা দলে সাজালে (সব 5 টাকা একসঙ্গে, তারপর 2 টাকা) গোনা সহজ হয়।"),
    mcq("A lemonade stand sells 4 cups at Rs 5 each. How much money comes in?", ["Rs 20", "Rs 9", "Rs 45", "Rs 5"], 0,
        "4 x 5 = Rs 20.",
        "লেবুর শরবতের দোকানে 5 টাকা করে 4 কাপ বিক্রি হলো। কত টাকা এলো?", ["20 টাকা", "9 টাকা", "45 টাকা", "5 টাকা"],
        "4 x 5 = 20 টাকা।"),
    mcq("If you borrow money from a bank, what usually happens?", ["You pay it back with a little extra (interest)", "You never pay it back", "The bank pays you", "It becomes yours for free"], 0,
        "Loans must be paid back, usually with interest - an extra charge for borrowing.",
        "ব্যাংক থেকে টাকা ধার নিলে সাধারণত কী হয়?", ["একটু বাড়তি (সুদ) সহ ফেরত দিতে হয়", "কখনো ফেরত দিতে হয় না", "ব্যাংক তোমাকে টাকা দেয়", "বিনামূল্যে তোমার হয়ে যায়"],
        "ঋণ ফেরত দিতে হয়, সাধারণত সুদসহ - ধার নেওয়ার জন্য বাড়তি মাশুল।"),
    mcq("Why do builders compare prices before buying bricks?", ["To get good bricks for less money", "To waste time", "Because all bricks are free", "To make bricks heavier"], 0,
        "Comparing prices helps you spend less and keep money for other parts of the job.",
        "ইট কেনার আগে নির্মাতারা দাম তুলনা করেন কেন?", ["কম টাকায় ভালো ইট পেতে", "সময় নষ্ট করতে", "কারণ সব ইট বিনামূল্যে", "ইট ভারী করতে"],
        "দাম তুলনা করলে কম খরচ হয় আর কাজের অন্য অংশের জন্য টাকা থাকে।"),
    mcq("You have Rs 50 and spend Rs 20. Then you earn Rs 10. How much now?", ["Rs 40", "Rs 30", "Rs 80", "Rs 60"], 0,
        "50 - 20 = 30, then 30 + 10 = Rs 40.",
        "তোমার কাছে 50 টাকা, খরচ করলে 20 টাকা। তারপর রোজগার করলে 10 টাকা। এখন কত?", ["40 টাকা", "30 টাকা", "80 টাকা", "60 টাকা"],
        "50 - 20 = 30, তারপর 30 + 10 = 40 টাকা।"),
    mcq("Which is NOT a way to get money honestly?", ["Taking someone else's purse", "Doing chores for pocket money", "Selling old toys", "Saving birthday money"], 0,
        "Taking what is not yours is stealing. Honest ways are working, selling and saving.",
        "কোনটা সৎভাবে টাকা পাওয়ার উপায় নয়?", ["অন্যের পার্স নিয়ে নেওয়া", "ঘরের কাজ করে হাতখরচ পাওয়া", "পুরোনো খেলনা বিক্রি করা", "জন্মদিনের টাকা জমানো"],
        "যা তোমার নয় তা নেওয়া চুরি। সৎ উপায় হলো কাজ, বিক্রি আর সঞ্চয়।"),
    mcq("What is a coin made of?", ["Metal", "Paper", "Chocolate", "Glass"], 0,
        "Coins are made of metal so they last a long time. Notes are made of special paper or plastic.",
        "পয়সা কী দিয়ে তৈরি?", ["ধাতু", "কাগজ", "চকলেট", "কাচ"],
        "পয়সা ধাতুর তৈরি, তাই অনেকদিন টেকে। নোট বিশেষ কাগজ বা প্লাস্টিকের।"),
    mcq("If each brick costs Rs 2, how much for 10 bricks?", ["Rs 20", "Rs 12", "Rs 10", "Rs 2"], 0,
        "10 x 2 = Rs 20.",
        "প্রতিটি ইটের দাম 2 টাকা হলে 10টি ইটের দাম কত?", ["20 টাকা", "12 টাকা", "10 টাকা", "2 টাকা"],
        "10 x 2 = 20 টাকা।"),
    mcq("A cheaper bridge that is still safe is good because...", ["It saves money for other useful things", "Cheap is always unsafe", "Money should be wasted", "Bridges should cost the most"], 0,
        "Saving money without losing safety means more money for schools, roads or another bridge.",
        "যে সেতু সস্তা কিন্তু তবুও নিরাপদ, সেটা ভালো কারণ...", ["অন্য দরকারি কাজের জন্য টাকা বাঁচে", "সস্তা সবসময় অনিরাপদ", "টাকা নষ্ট করা উচিত", "সেতুর দাম সবচেয়ে বেশি হওয়া উচিত"],
        "নিরাপত্তা না হারিয়ে টাকা বাঁচালে স্কুল, রাস্তা বা আরেকটা সেতুর জন্য বেশি টাকা থাকে।"),
    mcq("How many Rs 5 coins make Rs 20?", ["4", "5", "2", "10"], 0,
        "5 + 5 + 5 + 5 = 20, so 4 coins.",
        "5 টাকার কয়টি পয়সায় 20 টাকা হয়?", ["4", "5", "2", "10"],
        "5 + 5 + 5 + 5 = 20, তাই 4টি পয়সা।"),
    mcq("How many Rs 2 coins make Rs 10?", ["5", "2", "10", "8"], 0,
        "2 + 2 + 2 + 2 + 2 = 10, so 5 coins.",
        "2 টাকার কয়টি পয়সায় 10 টাকা হয়?", ["5", "2", "10", "8"],
        "2 + 2 + 2 + 2 + 2 = 10, তাই 5টি পয়সা।"),
    mcq("You want to buy a gift for Mum. What should you do first?", ["Check how much money you have", "Buy the most expensive thing", "Borrow lots of money", "Forget it"], 0,
        "Knowing your budget first helps you pick a gift you can afford.",
        "মায়ের জন্য উপহার কিনতে চাও। প্রথমে কী করবে?", ["দেখো তোমার কত টাকা আছে", "সবচেয়ে দামি জিনিসটা কেনো", "অনেক টাকা ধার করো", "ভুলে যাও"],
        "আগে বাজেট জানলে সামর্থ্যের মধ্যে উপহার বাছা যায়।"),
    mcq("Your class collects Rs 2 from each of 10 children for a picnic. How much is collected?", ["Rs 20", "Rs 12", "Rs 10", "Rs 2"], 0,
        "10 x 2 = Rs 20.",
        "পিকনিকের জন্য তোমার ক্লাসের 10 জন শিশুর প্রত্যেকের থেকে 2 টাকা করে তোলা হলো। কত উঠল?", ["20 টাকা", "12 টাকা", "10 টাকা", "2 টাকা"],
        "10 x 2 = 20 টাকা।"),
    mcq("If you keep Rs 10 in a box and do not touch it, after a month it is...", ["Still Rs 10", "Rs 20", "Rs 0", "Rs 100"], 0,
        "Money in a box stays the same. In a bank savings account it can grow a little with interest.",
        "একটা বাক্সে 10 টাকা রেখে না ছুঁলে এক মাস পরে তা হবে...", ["এখনো 10 টাকা", "20 টাকা", "0 টাকা", "100 টাকা"],
        "বাক্সের টাকা একই থাকে। ব্যাংকের সঞ্চয় অ্যাকাউন্টে সুদে একটু বাড়তে পারে।"),
    mcq("A toy shop gives 1 free sticker with every Rs 10 spent. You spend Rs 30. How many stickers?", ["3", "1", "10", "30"], 0,
        "30 has three tens, so 3 stickers.",
        "একটা খেলনার দোকান প্রতি 10 টাকা খরচে 1টা স্টিকার বিনামূল্যে দেয়। তুমি 30 টাকা খরচ করলে। কয়টি স্টিকার?", ["3", "1", "10", "30"],
        "30-এ তিনটি দশ, তাই 3টি স্টিকার।"),
    mcq("What is 'sharing'?", ["Giving part of what you have to others", "Keeping everything", "Hiding money", "Breaking toys"], 0,
        "Sharing means giving some to others - like splitting sweets fairly with a friend.",
        "'ভাগ করে নেওয়া' কী?", ["নিজের যা আছে তার কিছুটা অন্যকে দেওয়া", "সবকিছু রেখে দেওয়া", "টাকা লুকানো", "খেলনা ভাঙা"],
        "ভাগ করা মানে কিছুটা অন্যকে দেওয়া - যেমন বন্ধুর সঙ্গে মিষ্টি সমানভাবে ভাগ করা।"),
    mcq("Which costs more each month in a home?", ["Rent or food for the family", "One balloon", "A sticker", "A pencil"], 0,
        "Big needs like a home and food cost much more than small treats.",
        "একটা বাড়িতে প্রতি মাসে কোনটার খরচ বেশি?", ["পরিবারের ভাড়া বা খাবার", "একটা বেলুন", "একটা স্টিকার", "একটা পেনসিল"],
        "ঘর আর খাবারের মতো বড় প্রয়োজনের খরচ ছোট শখের চেয়ে অনেক বেশি।"),
    mcq("You found a toy you like for Rs 40, but you only have Rs 25. Which is the best plan?", ["Save for a few more weeks", "Ask the shop to give it free", "Take it secretly", "Give up saving forever"], 0,
        "Patience and saving get you there honestly: you need Rs 15 more.",
        "40 টাকার একটা পছন্দের খেলনা পেলে, কিন্তু আছে মাত্র 25 টাকা। সবচেয়ে ভালো পরিকল্পনা কোনটা?", ["আরও কয়েক সপ্তাহ জমাও", "দোকানকে বিনামূল্যে দিতে বলো", "লুকিয়ে নিয়ে নাও", "চিরকালের মতো জমানো ছেড়ে দাও"],
        "ধৈর্য আর সঞ্চয় সৎভাবে লক্ষ্যে পৌঁছায়: আর 15 টাকা লাগবে।"),
    mcq("Which is a coin and which is a note: Rs 2 and Rs 100?", ["Rs 2 is usually a coin, Rs 100 a note", "Both are coins", "Both are notes", "Rs 100 is a coin"], 0,
        "Small values are usually coins; bigger values are usually paper notes.",
        "2 টাকা আর 100 টাকা - কোনটা পয়সা আর কোনটা নোট?", ["2 টাকা সাধারণত পয়সা, 100 টাকা নোট", "দুটোই পয়সা", "দুটোই নোট", "100 টাকা পয়সা"],
        "ছোট মূল্য সাধারণত পয়সা; বড় মূল্য সাধারণত কাগজের নোট।"),
    mcq("Why should you not spend money on something you will not use?", ["It wastes money you could use for something better", "Spending is always good", "Shops need your money more", "Money is unlimited"], 0,
        "Money is limited. Spending it wisely gets you more of what really matters.",
        "যা ব্যবহার করবে না তাতে টাকা খরচ করা উচিত নয় কেন?", ["এতে টাকা নষ্ট হয়, যা ভালো কিছুতে লাগত", "খরচ সবসময় ভালো", "দোকানের তোমার টাকা বেশি দরকার", "টাকা অফুরন্ত"],
        "টাকা সীমিত। বুঝে খরচ করলে সত্যিই দরকারি জিনিস বেশি পাওয়া যায়।"),
    mcq("A bridge earns Rs 10 from each of 3 lorries every day. How much a day?", ["Rs 30", "Rs 13", "Rs 10", "Rs 3"], 0,
        "3 x 10 = Rs 30 a day from tolls.",
        "একটা সেতু প্রতিদিন 3টি লরির প্রত্যেকটি থেকে 10 টাকা আয় করে। দিনে কত?", ["30 টাকা", "13 টাকা", "10 টাকা", "3 টাকা"],
        "3 x 10 = দিনে 30 টাকা টোল।"),
    mcq("Which helps you spend wisely?", ["Making a list before shopping", "Buying everything you see", "Shopping when very hungry", "Never looking at prices"], 0,
        "A list keeps you focused on what you need and stops extra buying.",
        "বুঝে খরচ করতে কী সাহায্য করে?", ["কেনাকাটার আগে তালিকা বানানো", "যা দেখো সব কেনা", "খুব খিদে নিয়ে কেনাকাটা", "কখনো দাম না দেখা"],
        "তালিকা তোমাকে দরকারি জিনিসে মন রাখতে আর বাড়তি কেনা থামাতে সাহায্য করে।"),
    mcq("What is a 'saving goal'?", ["The thing you are saving money for", "A football goal", "A kind of coin", "A bank building"], 0,
        "A saving goal is your target - like 'Rs 100 for new shoes'.",
        "'সঞ্চয়ের লক্ষ্য' কী?", ["যে জিনিসের জন্য টাকা জমাচ্ছ", "ফুটবলের গোল", "এক রকম পয়সা", "ব্যাংকের ভবন"],
        "সঞ্চয়ের লক্ষ্য হলো তোমার নিশানা - যেমন 'নতুন জুতোর জন্য 100 টাকা'।"),
    mcq("If you save Rs 5 a week, how many weeks to save Rs 20?", ["4 weeks", "5 weeks", "20 weeks", "2 weeks"], 0,
        "5, 10, 15, 20 - four weeks.",
        "প্রতি সপ্তাহে 5 টাকা জমালে 20 টাকা জমাতে কত সপ্তাহ লাগবে?", ["4 সপ্তাহ", "5 সপ্তাহ", "20 সপ্তাহ", "2 সপ্তাহ"],
        "5, 10, 15, 20 - চার সপ্তাহ।"),
    mcq("A builder pays 2 workers Rs 50 each for a day's work. How much in all?", ["Rs 100", "Rs 52", "Rs 50", "Rs 25"], 0,
        "50 + 50 = Rs 100. Paying workers is part of the cost of every bridge.",
        "একজন নির্মাতা 2 জন শ্রমিককে এক দিনের কাজের জন্য প্রত্যেককে 50 টাকা দিলেন। মোট কত?", ["100 টাকা", "52 টাকা", "50 টাকা", "25 টাকা"],
        "50 + 50 = 100 টাকা। শ্রমিকের মজুরি প্রতিটি সেতুর খরচের অংশ।"),
    mcq("What happens if everyone in a family spends more than they earn?", ["They run out of money and may have to borrow", "They get richer", "Nothing ever", "Money appears from nowhere"], 0,
        "Spending more than you earn empties your savings. Budgets help avoid that.",
        "পরিবারের সবাই আয়ের চেয়ে বেশি খরচ করলে কী হয়?", ["টাকা ফুরিয়ে যায় আর ধার করতে হতে পারে", "তারা আরও ধনী হয়", "কখনো কিছু হয় না", "শূন্য থেকে টাকা আসে"],
        "আয়ের চেয়ে বেশি খরচ করলে সঞ্চয় ফুরিয়ে যায়। বাজেট তা এড়াতে সাহায্য করে।"),
    mcq("You trade 2 marbles for 1 sticker. How many stickers for 6 marbles?", ["3", "6", "2", "12"], 0,
        "Every 2 marbles get 1 sticker: 6 marbles make 3 pairs, so 3 stickers.",
        "তুমি 2টি মার্বেলের বদলে 1টি স্টিকার নাও। 6টি মার্বেলে কয়টি স্টিকার?", ["3", "6", "2", "12"],
        "প্রতি 2টি মার্বেলে 1টি স্টিকার: 6টি মার্বেলে 3 জোড়া, তাই 3টি স্টিকার।"),
    mcq("Which is a safe way to carry money to school?", ["In a zipped pocket or purse", "Holding it loosely in your hand all day", "Leaving it on the bus seat", "In an open bag in the rain"], 0,
        "A zipped pocket keeps money from falling out or getting lost.",
        "স্কুলে টাকা নেওয়ার নিরাপদ উপায় কোনটা?", ["চেন-লাগানো পকেট বা পার্সে", "সারাদিন আলগা হাতে ধরে", "বাসের সিটে ফেলে রেখে", "বৃষ্টিতে খোলা ব্যাগে"],
        "চেন-লাগানো পকেটে টাকা পড়ে যায় না বা হারায় না।"),
    mcq("A sweet costs Rs 2. How many sweets can you buy with Rs 10?", ["5", "2", "10", "8"], 0,
        "10 shared into groups of 2: five sweets.",
        "একটা লজেন্সের দাম 2 টাকা। 10 টাকায় কয়টি লজেন্স কেনা যায়?", ["5", "2", "10", "8"],
        "10-কে 2-এর দলে ভাগ: পাঁচটি লজেন্স।"),
    mcq("Why is it good to know the price before you buy?", ["So you know if you have enough money", "Prices are a secret", "It makes the item free", "So the shop can charge more"], 0,
        "Knowing the price helps you decide if you can afford it and if it is worth it.",
        "কেনার আগে দাম জানা ভালো কেন?", ["যাতে বোঝো যথেষ্ট টাকা আছে কিনা", "দাম একটা গোপন কথা", "এতে জিনিস বিনামূল্যে হয়", "যাতে দোকান বেশি নিতে পারে"],
        "দাম জানলে বোঝা যায় সামর্থ্য আছে কিনা আর জিনিসটা দামের যোগ্য কিনা।"),
    mcq("You earn Rs 5 by helping wash the car. You earn Rs 5 more by watering plants. How much did you earn?", ["Rs 10", "Rs 5", "Rs 15", "Rs 55"], 0,
        "5 + 5 = Rs 10 earned. Hard work pays!",
        "গাড়ি ধুতে সাহায্য করে 5 টাকা আর গাছে জল দিয়ে আরও 5 টাকা পেলে। মোট কত রোজগার?", ["10 টাকা", "5 টাকা", "15 টাকা", "55 টাকা"],
        "5 + 5 = 10 টাকা রোজগার। পরিশ্রমের দাম আছে!"),
    mcq("A bigger bridge costs more money. Who usually pays for a big public bridge?", ["The government, from taxes, or loans repaid by tolls", "One child's pocket money", "The fish in the river", "Nobody - bridges are free to build"], 0,
        "Big bridges are paid for with public money (taxes) or loans that tolls pay back over many years.",
        "বড় সেতুর খরচ বেশি। বড় সরকারি সেতুর খরচ সাধারণত কে দেয়?", ["সরকার, কর থেকে, বা টোলে শোধ হওয়া ঋণে", "একটি শিশুর হাতখরচ", "নদীর মাছ", "কেউ না - সেতু বানাতে টাকা লাগে না"],
        "বড় সেতুর খরচ আসে সরকারি টাকা (কর) বা এমন ঋণ থেকে, যা টোলে বহু বছর ধরে শোধ হয়।"),
    mcq("Which is the best thing to do with a torn note?", ["Ask a grown-up to change it at a bank", "Throw it away", "Eat it", "Draw on it"], 0,
        "Banks can exchange damaged notes for good ones.",
        "ছেঁড়া নোট নিয়ে সবচেয়ে ভালো কী করা যায়?", ["বড়দের বলো ব্যাংক থেকে বদলে আনতে", "ফেলে দাও", "খেয়ে ফেলো", "তাতে আঁকো"],
        "ব্যাংক নষ্ট নোট বদলে ভালো নোট দিতে পারে।"),
    mcq("Which costs less: 1 kg of rice for Rs 50 or 1 kg of the same rice for Rs 45?", ["Rs 45", "Rs 50", "They cost the same", "Rice is free"], 0,
        "Same rice, Rs 5 less.",
        "কোনটা কম দামি: 50 টাকায় 1 kg চাল নাকি একই চাল 45 টাকায় 1 kg?", ["45 টাকা", "50 টাকা", "দাম সমান", "চাল বিনামূল্যে"],
        "একই চাল, 5 টাকা কম।"),
    mcq("What do you call money you have left after buying what you need?", ["Savings or extra money", "A debt", "A loss", "A bill"], 0,
        "What is left over can be saved for later.",
        "দরকারি জিনিস কেনার পর হাতে যে টাকা থাকে তাকে কী বলে?", ["সঞ্চয় বা বাড়তি টাকা", "দেনা", "ক্ষতি", "বিল"],
        "যা বাকি থাকে তা পরের জন্য জমানো যায়।"),
)
