"""Class 1 - Physics: pushes, pulls, falling, rolling, floating, light, sound and balance."""
from . import mcq

ITEMS = (
    mcq("You push a toy car. Which way does it move?",
        ["Towards you", "Away from you, the way you pushed", "Straight up", "It does not move at all"], 1,
        "A push moves things away from you, in the direction you push. Pull, and they come towards you.",
        "তুমি একটি খেলনা গাড়ি ঠেললে। সেটি কোন দিকে যাবে?",
        ["তোমার দিকে", "তোমার থেকে দূরে, যেদিকে ঠেলেছ", "সোজা উপরে", "একটুও নড়বে না"],
        "ঠেললে জিনিস তোমার থেকে দূরে, যেদিকে ঠেলেছ সেদিকে যায়। টানলে তোমার দিকে আসে।"),
    mcq("Opening a drawer - is that a push or a pull?",
        ["A push", "A pull", "A jump", "A sneeze"], 1,
        "You bring the drawer towards you, so it is a pull. Closing it again is a push.",
        "ড্রয়ার খোলা - এটা ঠেলা নাকি টান?",
        ["ঠেলা", "টান", "লাফ", "হাঁচি"],
        "ড্রয়ারটি তুমি নিজের দিকে আনো, তাই এটা টান। আবার বন্ধ করা হলো ঠেলা।"),
    mcq("You drop a ball from your hand. Where does it go?",
        ["Up to the sky", "It floats in the air", "Down to the ground", "Sideways to the door"], 2,
        "The Earth pulls everything down. This pull is called gravity - even bridges must hold against it.",
        "হাত থেকে একটি বল ছেড়ে দিলে। সেটা কোথায় যাবে?",
        ["আকাশে উপরে", "বাতাসে ভেসে থাকবে", "নিচে মাটিতে", "পাশে দরজার দিকে"],
        "পৃথিবী সবকিছুকে নিচে টানে। এই টানের নাম মাধ্যাকর্ষণ - সেতুকেও এর বিরুদ্ধে দাঁড়িয়ে থাকতে হয়।"),
    mcq("Why does your toy car zoom on a tiled floor but stop quickly on Grandma's thick rug?",
        ["The rug is sleepy", "The rug rubs and grabs the wheels more", "Tiles are magic", "The car is scared of rugs"], 1,
        "Rubbing between two surfaces is called friction. A thick rug rubs much more than smooth tiles, so it "
        "slows the car down - like sticky velcro.",
        "খেলনা গাড়ি টাইলসের মেঝেতে জোরে ছোটে, কিন্তু দিদিমার মোটা কার্পেটে তাড়াতাড়ি থেমে যায় কেন?",
        ["কার্পেটের ঘুম পেয়েছে", "কার্পেট চাকাকে বেশি ঘষে আর আঁকড়ে ধরে", "টাইলস জাদুর", "গাড়ি কার্পেটকে ভয় পায়"],
        "দুটি তলের ঘষাকে বলে ঘর্ষণ। মোটা কার্পেট মসৃণ টাইলসের চেয়ে অনেক বেশি ঘষে, তাই গাড়ি ধীর হয় - যেন "
        "আঠালো ভেলক্রো।"),
    mcq("Which is easier to push across the floor?",
        ["An empty box", "A box full of books", "Both are exactly the same", "The floor itself"], 0,
        "Heavier things need a bigger push. The empty box is light, so a small push is enough.",
        "মেঝের উপর দিয়ে কোনটা ঠেলা সহজ?",
        ["খালি বাক্স", "বইভর্তি বাক্স", "দুটোই একদম সমান", "মেঝে নিজেই"],
        "ভারী জিনিসে বেশি ঠেলা লাগে। খালি বাক্স হালকা, তাই অল্প ঠেলাতেই চলে।"),
    mcq("A ball rolls down a slide. Why?",
        ["The slide is pushing it up", "Gravity pulls it down the slope", "The ball is hungry", "Wind from the moon"], 1,
        "On a slope, gravity pulls things downhill. That is why trains need strong engines to go uphill.",
        "একটি বল স্লাইড বেয়ে গড়িয়ে নামে। কেন?",
        ["স্লাইড তাকে উপরে ঠেলছে", "মাধ্যাকর্ষণ তাকে ঢাল বেয়ে নিচে টানে", "বলের খিদে পেয়েছে", "চাঁদের বাতাস"],
        "ঢালে মাধ্যাকর্ষণ জিনিসকে নিচের দিকে টানে। এজন্যই উপরে উঠতে ট্রেনের শক্তিশালী ইঞ্জিন লাগে।"),
    mcq("Which one will float in a bucket of water?",
        ["A stone", "A steel spoon", "A dry leaf", "A coin"], 2,
        "A dry leaf is light for its size, so water holds it up. Stones, spoons and coins sink.",
        "বালতির জলে কোনটা ভাসবে?",
        ["পাথর", "স্টিলের চামচ", "শুকনো পাতা", "পয়সা"],
        "শুকনো পাতা তার আকারের তুলনায় হালকা, তাই জল তাকে ভাসিয়ে রাখে। পাথর, চামচ আর পয়সা ডুবে যায়।"),
    mcq("You kick a football gently and then hard. Which kick sends it further?",
        ["The gentle kick", "The hard kick", "Both go the same distance", "Neither moves"], 1,
        "A bigger push (force) makes things move faster and further.",
        "তুমি ফুটবলে একবার আস্তে আর একবার জোরে লাথি দিলে। কোনটায় বল বেশি দূরে যাবে?",
        ["আস্তে লাথিতে", "জোরে লাথিতে", "দুটোতেই সমান দূরে", "কোনোটাতেই নড়বে না"],
        "বড় ঠেলা (বল) জিনিসকে দ্রুত আর বেশি দূরে নেয়।"),
    mcq("What makes a moving swing slow down and stop by itself?",
        ["Air and rubbing slow it down", "The swing gets bored", "The tree tells it to stop", "Nothing - it never stops"], 0,
        "Air pushes against the swing and the chains rub at the top. These small forces slowly steal its "
        "motion - so you need someone to push again!",
        "দুলতে থাকা দোলনা নিজে নিজে ধীর হয়ে থেমে যায় কেন?",
        ["বাতাস আর ঘষা তাকে ধীর করে", "দোলনার একঘেয়ে লাগে", "গাছ তাকে থামতে বলে", "কিছুই না - এটা কখনো থামে না"],
        "বাতাস দোলনার বিরুদ্ধে ঠেলে আর উপরে শিকল ঘষা খায়। এই ছোট বলগুলো ধীরে ধীরে তার গতি কেড়ে নেয় - তাই "
        "আবার কাউকে ঠেলতে হয়!"),
    mcq("Which wheel shape rolls best?",
        ["Square", "Triangle", "Circle", "Star"], 2,
        "A circle is the same height all the way round, so it rolls smoothly. A square wheel would go bump-bump-bump.",
        "কোন আকারের চাকা সবচেয়ে ভালো গড়ায়?",
        ["বর্গ", "ত্রিভুজ", "বৃত্ত", "তারা"],
        "বৃত্ত চারদিকে একই উঁচু, তাই মসৃণভাবে গড়ায়। বর্গাকার চাকা ধপ-ধপ-ধপ করে চলত।"),
    mcq("A magnet will pull which of these?",
        ["A wooden pencil", "An iron nail", "A plastic cup", "A paper boat"], 1,
        "Magnets pull iron and steel. Wood, plastic and paper are not pulled.",
        "চুম্বক এগুলোর মধ্যে কোনটাকে টানবে?",
        ["কাঠের পেনসিল", "লোহার পেরেক", "প্লাস্টিকের কাপ", "কাগজের নৌকা"],
        "চুম্বক লোহা আর ইস্পাতকে টানে। কাঠ, প্লাস্টিক আর কাগজকে টানে না।"),
    mcq("When is your shadow made?",
        ["When you block the light", "When you sing", "When it rains", "When you are asleep"], 0,
        "Light travels in straight lines. Your body stops some of it, and the dark patch behind you is your shadow.",
        "তোমার ছায়া কখন তৈরি হয়?",
        ["যখন তুমি আলো আটকাও", "যখন তুমি গান গাও", "যখন বৃষ্টি হয়", "যখন তুমি ঘুমাও"],
        "আলো সোজা পথে চলে। তোমার শরীর তার কিছুটা আটকায়, আর পেছনের অন্ধকার জায়গাটাই তোমার ছায়া।"),
    mcq("You see lightning first and hear the thunder later. Why?",
        ["Thunder is shy", "Light travels much faster than sound", "Your ears are slow", "Lightning is quieter"], 1,
        "Light is super fast; sound is much slower. So the flash reaches you first and the boom arrives later.",
        "বিদ্যুৎ চমক আগে দেখা যায় আর বাজের শব্দ পরে শোনা যায়। কেন?",
        ["বাজ লাজুক", "আলো শব্দের চেয়ে অনেক দ্রুত চলে", "তোমার কান ধীর", "বিদ্যুৎ চমক কম শব্দের"],
        "আলো ভীষণ দ্রুত; শব্দ অনেক ধীর। তাই ঝলক আগে পৌঁছায় আর গর্জন পরে আসে।"),
    mcq("You hit a drum. What makes the sound?",
        ["The drum skin shaking back and forth", "The drum being angry", "Colour of the drum", "The drum getting heavier"], 0,
        "Sounds are made by things shaking very fast. We call this shaking vibration.",
        "তুমি ঢোলে বাড়ি মারলে। শব্দ তৈরি করে কী?",
        ["ঢোলের চামড়ার এদিক-ওদিক কাঁপা", "ঢোলের রাগ", "ঢোলের রং", "ঢোল ভারী হয়ে যাওয়া"],
        "জিনিস খুব দ্রুত কাঁপলে শব্দ হয়। এই কাঁপাকে বলে কম্পন।"),
    mcq("Two friends sit on a see-saw. The heavier friend goes...",
        ["Up", "Down", "Sideways", "Nowhere, it is always level"], 1,
        "The heavier side pushes down more, so it sinks. To balance, the heavier friend can sit closer to the middle.",
        "দুই বন্ধু ঢেঁকিতে বসেছে। ভারী বন্ধু যায়...",
        ["উপরে", "নিচে", "পাশে", "কোথাও না, সবসময় সমান থাকে"],
        "ভারী দিক বেশি নিচে ঠেলে, তাই নেমে যায়। সমান করতে ভারী বন্ধু মাঝখানের কাছে বসতে পারে।"),
    mcq("How can a heavy dad and a light child balance on a see-saw?",
        ["Dad sits closer to the middle", "Dad sits at the very end", "Both stand up", "The child jumps off"], 0,
        "Sitting closer to the middle makes a heavy weight act less strongly. Bridge builders use the same "
        "trick to keep cantilevers balanced!",
        "ভারী বাবা আর হালকা শিশু কীভাবে ঢেঁকিতে সমান থাকবে?",
        ["বাবা মাঝখানের কাছে বসবেন", "বাবা একদম শেষে বসবেন", "দুজনেই দাঁড়িয়ে যাবে", "শিশু লাফিয়ে নেমে যাবে"],
        "মাঝখানের কাছে বসলে ভারী ওজনের প্রভাব কম হয়। সেতু-নির্মাতারাও ক্যান্টিলিভার সমান রাখতে এই কৌশল ব্যবহার করেন!"),
    mcq("Ice cream left in the sun becomes...",
        ["Harder", "A puddle - it melts", "A stone", "Bigger"], 1,
        "Heat from the sun melts the ice cream. Heat changes solids into liquids.",
        "রোদে রেখে দেওয়া আইসক্রিম হয়ে যায়...",
        ["আরও শক্ত", "গলে জল", "পাথর", "আরও বড়"],
        "সূর্যের তাপে আইসক্রিম গলে যায়। তাপ কঠিন জিনিসকে তরলে বদলায়।"),
    mcq("Which is the best way to stop a rolling ball?",
        ["Push it the same way it is going", "Push against it, the opposite way", "Shout at it", "Paint it red"], 1,
        "A push against the motion slows things down. That is how brakes stop trains too.",
        "গড়িয়ে চলা বল থামানোর সবচেয়ে ভালো উপায় কী?",
        ["যেদিকে যাচ্ছে সেদিকেই ঠেলা", "উল্টো দিকে, তার বিরুদ্ধে ঠেলা", "তার দিকে চিৎকার করা", "লাল রং করা"],
        "চলার বিরুদ্ধে ঠেলা দিলে জিনিস ধীর হয়। ট্রেনের ব্রেকও এভাবেই থামায়।"),
    mcq("Why do we put a rubber mat under a slippery bath?",
        ["To make it colourful", "Rubber grips the feet and stops slipping", "Rubber makes water warm", "To make the bath bigger"], 1,
        "Rubber gives lots of friction, so your feet grip instead of sliding.",
        "পিছল স্নানঘরে রাবারের মাদুর রাখা হয় কেন?",
        ["রঙিন করতে", "রাবার পা আঁকড়ে ধরে আর পিছলানো থামায়", "রাবার জল গরম করে", "স্নানঘর বড় করতে"],
        "রাবার অনেক ঘর্ষণ দেয়, তাই পা না পিছলে আঁকড়ে থাকে।"),
    mcq("Which falls to the ground more slowly?",
        ["A flat sheet of paper", "The same paper squashed into a ball", "They always land together", "Neither falls"], 0,
        "Air pushes up on the wide flat sheet much more, so it floats down slowly. The paper ball cuts through the air.",
        "কোনটা ধীরে মাটিতে পড়বে?",
        ["সমতল একটি কাগজ", "সেই কাগজ দলা পাকিয়ে বল করা", "সবসময় একসঙ্গে পড়ে", "কোনোটাই পড়ে না"],
        "চওড়া সমতল কাগজকে বাতাস বেশি ঠেলে উপরে রাখে, তাই ধীরে ভেসে নামে। কাগজের দলা বাতাস কেটে দ্রুত পড়ে।"),
    mcq("A bridge made of a single thin stick breaks when a toy truck crosses. What could help?",
        ["Use a thicker stick or more sticks", "Paint the stick", "Make the truck faster", "Clap loudly"], 0,
        "More or thicker material shares the weight, so each part carries less and does not break.",
        "একটা সরু কাঠির সেতু খেলনা ট্রাক যেতেই ভেঙে গেল। কী করলে সাহায্য হবে?",
        ["মোটা কাঠি বা বেশি কাঠি ব্যবহার করা", "কাঠিতে রং করা", "ট্রাককে আরও দ্রুত চালানো", "জোরে হাততালি দেওয়া"],
        "বেশি বা মোটা উপাদান ওজন ভাগ করে নেয়, তাই প্রতিটি অংশ কম বয় আর ভাঙে না।"),
    mcq("Which shape makes a strong frame that does not wobble?",
        ["Triangle", "Square", "Circle of string", "A wiggly line"], 0,
        "A triangle cannot be squashed out of shape. That is why bridges are full of triangles!",
        "কোন আকারে এমন মজবুত কাঠামো হয় যা নড়বড় করে না?",
        ["ত্রিভুজ", "বর্গ", "সুতোর বৃত্ত", "আঁকাবাঁকা রেখা"],
        "ত্রিভুজকে চেপে আকার বদলানো যায় না। এজন্যই সেতু ত্রিভুজে ভরা!"),
    mcq("You blow on a toy sailboat in a tub. What happens?",
        ["It moves away from you", "It sinks", "It moves towards you", "It turns into a fish"], 0,
        "Your breath pushes the sail, and the push moves the boat away from you.",
        "গামলায় খেলনা পালতোলা নৌকায় তুমি ফুঁ দিলে। কী হবে?",
        ["তোমার থেকে দূরে সরে যাবে", "ডুবে যাবে", "তোমার দিকে আসবে", "মাছ হয়ে যাবে"],
        "তোমার নিঃশ্বাস পালকে ঠেলে, আর সেই ঠেলা নৌকাকে তোমার থেকে দূরে নেয়।"),
    mcq("What do you need to see a book in a room?",
        ["Light", "Music", "A loud voice", "Cold air"], 0,
        "We see things when light bounces off them into our eyes. In total darkness you cannot read.",
        "ঘরে একটি বই দেখতে তোমার কী লাগবে?",
        ["আলো", "গান", "জোরে আওয়াজ", "ঠান্ডা বাতাস"],
        "আলো জিনিসে লেগে আমাদের চোখে এলে আমরা দেখি। পুরো অন্ধকারে পড়া যায় না।"),
    mcq("Which is the source of light?",
        ["The Sun", "The moon's own fire", "A mirror on its own", "A rock"], 0,
        "The Sun makes its own light. The Moon only shines because sunlight bounces off it.",
        "কোনটা আলোর উৎস?",
        ["সূর্য", "চাঁদের নিজের আগুন", "একা একটি আয়না", "পাথর"],
        "সূর্য নিজেই আলো তৈরি করে। চাঁদ শুধু তার গায়ে সূর্যের আলো ফিরে আসে বলে উজ্জ্বল দেখায়।"),
    mcq("A loud sound and a soft sound - what is different?",
        ["The loud one shakes the air more strongly", "The loud one is a different colour", "The soft one is heavier", "Nothing"], 0,
        "Bigger vibrations make louder sounds. Smaller vibrations make softer sounds.",
        "জোরে শব্দ আর আস্তে শব্দ - পার্থক্য কী?",
        ["জোরে শব্দ বাতাসকে বেশি জোরে কাঁপায়", "জোরে শব্দের রং আলাদা", "আস্তে শব্দ ভারী", "কিছুই না"],
        "বড় কম্পনে জোরে শব্দ হয়। ছোট কম্পনে আস্তে শব্দ হয়।"),
    mcq("Why does a kite need wind?",
        ["Wind pushes it up into the sky", "Wind makes it colourful", "Kites eat wind", "Wind makes the string longer"], 0,
        "Moving air pushes against the kite and holds it up while you pull the string.",
        "ঘুড়ির বাতাস লাগে কেন?",
        ["বাতাস তাকে ঠেলে আকাশে তোলে", "বাতাস তাকে রঙিন করে", "ঘুড়ি বাতাস খায়", "বাতাস সুতো লম্বা করে"],
        "চলমান বাতাস ঘুড়িকে ঠেলে উপরে রাখে, আর তুমি সুতো টেনে ধরো।"),
    mcq("You stretch a rubber band and let go. It...",
        ["Snaps back to its shape", "Stays stretched forever", "Turns into water", "Floats away"], 0,
        "Stretchy things are elastic: they pull back to their shape when you let go. Steel cables are a little "
        "elastic too.",
        "রাবার ব্যান্ড টেনে ছেড়ে দিলে সেটা...",
        ["আগের আকারে ফিরে আসে", "চিরকাল টানা থাকে", "জল হয়ে যায়", "ভেসে চলে যায়"],
        "টানলে বাড়ে এমন জিনিস স্থিতিস্থাপক: ছেড়ে দিলে আকারে ফিরে আসে। ইস্পাতের তারও একটু স্থিতিস্থাপক।"),
    mcq("A toy truck goes up a ramp. Which ramp is harder to climb?",
        ["A steep ramp", "A gentle ramp", "Both are the same", "A flat floor"], 0,
        "The steeper the slope, the harder gravity pulls back. That is why mountain railways twist around gently.",
        "খেলনা ট্রাক ঢাল বেয়ে উঠছে। কোন ঢালে ওঠা কঠিন?",
        ["খাড়া ঢাল", "মৃদু ঢাল", "দুটোই সমান", "সমতল মেঝে"],
        "ঢাল যত খাড়া, মাধ্যাকর্ষণ তত জোরে পিছনে টানে। এজন্যই পাহাড়ি রেলপথ ধীরে ধীরে ঘুরে ঘুরে ওঠে।"),
    mcq("Which pulls things towards the ground on Earth?",
        ["Gravity", "Music", "Colours", "Clouds"], 0,
        "Gravity is the invisible pull of the Earth. It gives everything its weight.",
        "পৃথিবীতে জিনিসকে মাটির দিকে কী টানে?",
        ["মাধ্যাকর্ষণ", "গান", "রং", "মেঘ"],
        "মাধ্যাকর্ষণ হলো পৃথিবীর অদৃশ্য টান। এর জন্যই সবকিছুর ওজন হয়।"),
    mcq("Why is it hard to walk on ice?",
        ["Ice has very little friction", "Ice is too hot", "Ice pulls your feet", "Ice is noisy"], 0,
        "Ice is very smooth, so it barely grips your shoes. With little friction, feet slide away.",
        "বরফের উপর হাঁটা কঠিন কেন?",
        ["বরফে ঘর্ষণ খুব কম", "বরফ খুব গরম", "বরফ পা টানে", "বরফ শব্দ করে"],
        "বরফ খুব মসৃণ, তাই জুতোকে প্রায় আঁকড়ে ধরে না। ঘর্ষণ কম হলে পা পিছলে যায়।"),
    mcq("You push a wall as hard as you can. What happens to the wall?",
        ["It stays still - it pushes back on you", "It falls over at once", "It flies away", "It shrinks"], 0,
        "When you push the wall, the wall pushes back just as hard. That is why your hands feel the push!",
        "তুমি দেয়ালে সব শক্তি দিয়ে ঠেললে। দেয়ালের কী হবে?",
        ["স্থির থাকবে - সে তোমাকে উল্টো ঠেলে", "সঙ্গে সঙ্গে পড়ে যাবে", "উড়ে যাবে", "ছোট হয়ে যাবে"],
        "তুমি দেয়াল ঠেললে দেয়ালও তোমাকে সমান জোরে উল্টো ঠেলে। এজন্যই হাতে ঠেলা টের পাও!"),
    mcq("You put a heavy stone on a paper bridge between two books. What happens?",
        ["The paper bends and the stone falls", "The paper gets stronger", "The stone floats", "The books fly"], 0,
        "Flat paper is too weak to hold a heavy stone. Fold it like a fan and it becomes much stronger!",
        "দুটি বইয়ের মাঝে কাগজের সেতুতে ভারী পাথর রাখলে। কী হবে?",
        ["কাগজ বেঁকে পাথর পড়ে যাবে", "কাগজ আরও শক্ত হবে", "পাথর ভাসবে", "বই উড়ে যাবে"],
        "সমতল কাগজ ভারী পাথর ধরার পক্ষে খুব দুর্বল। পাখার মতো ভাঁজ করলে অনেক বেশি শক্ত হয়!"),
    mcq("Why does a folded (zig-zag) paper bridge hold more coins than a flat one?",
        ["The folds make it stiff and hard to bend", "Folded paper is heavier", "Coins like folds", "It is magic paper"], 0,
        "Folds move paper away from the middle and make it deep, so it bends much less - just like deep "
        "bridge beams.",
        "ভাঁজ করা (আঁকাবাঁকা) কাগজের সেতু সমতলটার চেয়ে বেশি পয়সা ধরে কেন?",
        ["ভাঁজ তাকে শক্ত করে, বাঁকানো কঠিন হয়", "ভাঁজ করা কাগজ বেশি ভারী", "পয়সা ভাঁজ পছন্দ করে", "এটা জাদুর কাগজ"],
        "ভাঁজ কাগজকে গভীর করে, তাই অনেক কম বাঁকে - ঠিক গভীর সেতুর বিমের মতো।"),
    mcq("A spinning top stays up while it spins. When does it fall?",
        ["When it slows down", "When it spins fastest", "When it gets hungry", "Never"], 0,
        "Spinning keeps the top steady. As friction slows it, it wobbles and falls over.",
        "লাটিম ঘুরতে থাকলে খাড়া থাকে। কখন পড়ে যায়?",
        ["যখন ধীর হয়ে যায়", "যখন সবচেয়ে জোরে ঘোরে", "যখন খিদে পায়", "কখনো না"],
        "ঘোরা লাটিমকে স্থির রাখে। ঘর্ষণে ধীর হলে সে টলমল করে পড়ে যায়।"),
    mcq("Where is it hotter on a sunny day?",
        ["In the sunshine", "In the shade of a tree", "Both the same", "Under a cold fan"], 0,
        "The sun's light warms whatever it shines on. A tree's shade blocks the light, so it is cooler.",
        "রোদের দিনে কোথায় বেশি গরম?",
        ["রোদে", "গাছের ছায়ায়", "দুটোই সমান", "ঠান্ডা পাখার নিচে"],
        "সূর্যের আলো যেখানে পড়ে সেখানে গরম করে। গাছের ছায়া আলো আটকায়, তাই ঠান্ডা।"),
    mcq("Why do we wear dark clothes in winter and light clothes in summer?",
        ["Dark clothes soak up more of the sun's heat", "Light clothes are heavier", "Dark clothes are noisier", "No reason"], 0,
        "Dark colours absorb sunlight and get warm. Light colours bounce more of it away and stay cooler.",
        "শীতে গাঢ় রঙের আর গরমে হালকা রঙের জামা পরি কেন?",
        ["গাঢ় রং সূর্যের তাপ বেশি শুষে নেয়", "হালকা জামা বেশি ভারী", "গাঢ় জামা বেশি শব্দ করে", "কোনো কারণ নেই"],
        "গাঢ় রং সূর্যের আলো শুষে গরম হয়। হালকা রং বেশি আলো ফিরিয়ে দেয় আর ঠান্ডা থাকে।"),
    mcq("You let go of a balloon full of air without tying it. It...",
        ["Zooms around the room", "Stays still", "Turns into a ball", "Gets bigger"], 0,
        "Air rushes out of the back and pushes the balloon forward - the same idea as a rocket.",
        "বাঁধা ছাড়া বাতাসভরা বেলুন ছেড়ে দিলে সেটা...",
        ["ঘরময় সাঁই সাঁই করে ছোটে", "স্থির থাকে", "বল হয়ে যায়", "আরও বড় হয়"],
        "পেছন দিয়ে বাতাস বেরিয়ে বেলুনকে সামনে ঠেলে - রকেটেরও একই ধারণা।"),
    mcq("Which is heavier: 1 kg of cotton or 1 kg of iron?",
        ["The iron", "The cotton", "They weigh the same", "Cotton weighs nothing"], 2,
        "Both are 1 kg, so they weigh the same! The cotton just takes up much more space.",
        "কোনটা বেশি ভারী: 1 kg তুলো নাকি 1 kg লোহা?",
        ["লোহা", "তুলো", "দুটোর ওজন সমান", "তুলোর কোনো ওজন নেই"],
        "দুটোই 1 kg, তাই ওজন সমান! শুধু তুলো অনেক বেশি জায়গা নেয়।"),
    mcq("A tall tower of blocks falls easily. How can you make it steadier?",
        ["Make the bottom wider", "Put the biggest block on top", "Build it on a wobbly table", "Blow on it"], 0,
        "A wide base keeps the weight inside the bottom, so the tower does not tip. Real towers are wider at the bottom.",
        "ব্লকের উঁচু মিনার সহজে পড়ে যায়। কীভাবে আরও স্থির করবে?",
        ["নিচটা চওড়া করো", "সবচেয়ে বড় ব্লক উপরে রাখো", "নড়বড়ে টেবিলে বানাও", "তাতে ফুঁ দাও"],
        "চওড়া ভিত্তি ওজনকে নিচের মধ্যে রাখে, তাই মিনার উল্টায় না। আসল টাওয়ারও নিচে চওড়া।"),
    mcq("Your friend pulls one end of a rope and you pull the other. If you both pull equally, the rope...",
        ["Stays still", "Flies up", "Moves to the stronger side", "Turns into a snake"], 0,
        "Equal pulls in opposite directions cancel out, so nothing moves. Engineers call this balance.",
        "দড়ির এক প্রান্ত তোমার বন্ধু টানছে, অন্যটা তুমি। দুজনে সমান টানলে দড়ি...",
        ["স্থির থাকে", "উপরে উড়ে যায়", "শক্তিশালীর দিকে যায়", "সাপ হয়ে যায়"],
        "উল্টো দিকে সমান টান একে অপরকে কাটাকাটি করে, তাই কিছু নড়ে না। প্রকৌশলীরা একে বলেন ভারসাম্য।"),
    mcq("Which makes a sound when you blow across its top?",
        ["An empty bottle", "A brick", "A pillow", "A banana"], 0,
        "Blowing across the bottle makes the air inside vibrate, which makes a whistling sound.",
        "উপর দিয়ে ফুঁ দিলে কোনটায় শব্দ হয়?",
        ["খালি বোতল", "ইট", "বালিশ", "কলা"],
        "বোতলের মুখ দিয়ে ফুঁ দিলে ভেতরের বাতাস কাঁপে, তাতে বাঁশির মতো শব্দ হয়।"),
    mcq("You throw a ball up. What happens next?",
        ["It slows, stops and comes back down", "It keeps going to space", "It stops in the air forever", "It turns left"], 0,
        "Gravity pulls the ball back the whole time, so it slows down, stops at the top and falls.",
        "তুমি একটি বল উপরে ছুড়লে। তারপর কী হবে?",
        ["ধীর হয়ে থেমে আবার নিচে আসবে", "মহাকাশে চলতেই থাকবে", "চিরকাল বাতাসে থেমে থাকবে", "বাঁয়ে ঘুরবে"],
        "মাধ্যাকর্ষণ সারাক্ষণ বলকে পিছনে টানে, তাই সেটা ধীর হয়, উপরে থামে আর নিচে পড়ে।"),
    mcq("A bus stops suddenly. Which way do the passengers lean?",
        ["Forward", "Backward", "Up", "They do not move at all"], 0,
        "Moving bodies like to keep moving. When the bus stops, your body keeps going forward for a moment.",
        "বাস হঠাৎ থামল। যাত্রীরা কোন দিকে হেলে পড়ে?",
        ["সামনে", "পেছনে", "উপরে", "একটুও নড়ে না"],
        "চলমান শরীর চলতে থাকতে চায়। বাস থামলে তোমার শরীর মুহূর্তের জন্য সামনে এগোতে থাকে।"),
    mcq("Why are bicycle tyres made with bumpy patterns?",
        ["To grip the road better", "To look funny", "To make them lighter than air", "To make music"], 0,
        "The bumps (tread) grip the road and help push water away, so the bike does not slip.",
        "সাইকেলের টায়ারে খাঁজকাটা নকশা থাকে কেন?",
        ["রাস্তা ভালোভাবে আঁকড়ে ধরতে", "মজার দেখাতে", "বাতাসের চেয়ে হালকা করতে", "গান বাজাতে"],
        "খাঁজগুলো রাস্তা আঁকড়ে ধরে আর জল সরিয়ে দেয়, তাই সাইকেল পিছলায় না।"),
    mcq("Which is a pull?",
        ["Lifting a bucket from a well with a rope", "Kicking a ball", "Pressing a doorbell", "Pushing a pram"], 0,
        "Pulling the rope brings the bucket towards you. Kicking, pressing and pushing are pushes.",
        "কোনটা টান?",
        ["দড়ি দিয়ে কুয়ো থেকে বালতি তোলা", "বলে লাথি মারা", "কলিং বেল চাপা", "প্র্যাম ঠেলা"],
        "দড়ি টানলে বালতি তোমার দিকে আসে। লাথি, চাপা আর ঠেলা হলো ঠেলা।"),
    mcq("A heavy lorry crosses a wobbly wooden plank over a stream. What is the danger?",
        ["The plank may bend too much and break", "The plank becomes a boat", "The lorry gets lighter", "The stream stops"], 0,
        "A heavy load bends a beam. If it bends too much, it breaks - so bridges for lorries are made strong and deep.",
        "নালার উপর নড়বড়ে কাঠের তক্তা দিয়ে ভারী লরি যাচ্ছে। বিপদ কী?",
        ["তক্তা বেশি বেঁকে ভেঙে যেতে পারে", "তক্তা নৌকা হয়ে যাবে", "লরি হালকা হবে", "নালা থেমে যাবে"],
        "ভারী ভার বিমকে বাঁকায়। বেশি বাঁকলে ভাঙে - তাই লরির সেতু শক্ত আর গভীর করে বানানো হয়।"),
    mcq("Why does a boat made of steel float but a steel nail sinks?",
        ["The boat's shape holds lots of air and pushes away lots of water", "Boats are made of magic steel",
         "The nail is lighter", "Water dislikes nails"], 0,
        "A hollow boat pushes aside a lot of water, and the water pushes it up. A small solid nail cannot do that.",
        "ইস্পাতের নৌকা ভাসে কিন্তু ইস্পাতের পেরেক ডোবে কেন?",
        ["নৌকার আকার অনেক বাতাস ধরে আর অনেক জল সরায়", "নৌকা জাদুর ইস্পাতে তৈরি", "পেরেক বেশি হালকা", "জল পেরেক অপছন্দ করে"],
        "ফাঁপা নৌকা অনেক জল সরায়, আর জল তাকে উপরে ঠেলে। ছোট নিরেট পেরেক তা পারে না।"),
    mcq("You rub your hands together quickly. They feel...",
        ["Warm", "Wet", "Cold", "Heavy"], 0,
        "Rubbing (friction) turns motion into heat. That is why brakes get hot.",
        "দ্রুত দুই হাত ঘষলে হাত কেমন লাগে?",
        ["গরম", "ভেজা", "ঠান্ডা", "ভারী"],
        "ঘষা (ঘর্ষণ) গতিকে তাপে বদলায়। এজন্যই ব্রেক গরম হয়।"),
    mcq("Which object is easiest to roll?",
        ["A ball", "A book", "A brick", "A shoe"], 0,
        "Round things roll because they touch the floor at just one small spot at a time.",
        "কোন জিনিস গড়ানো সবচেয়ে সহজ?",
        ["বল", "বই", "ইট", "জুতো"],
        "গোল জিনিস গড়ায়, কারণ একবারে মেঝের মাত্র একটি ছোট জায়গা ছোঁয়।"),
    mcq("A glass falls on a hard floor and breaks, but falls on a pillow and stays whole. Why?",
        ["The pillow slows it down gently", "Pillows are made of glass", "Glass likes pillows", "The floor was angry"], 0,
        "A soft pillow stops the glass slowly, so the force on it is small. A hard floor stops it in an instant.",
        "কাচের গ্লাস শক্ত মেঝেতে পড়ে ভাঙে, কিন্তু বালিশে পড়লে আস্ত থাকে। কেন?",
        ["বালিশ তাকে আস্তে আস্তে থামায়", "বালিশ কাচের তৈরি", "কাচ বালিশ পছন্দ করে", "মেঝে রেগে ছিল"],
        "নরম বালিশ গ্লাসকে ধীরে থামায়, তাই তার উপর বল কম। শক্ত মেঝে এক মুহূর্তে থামিয়ে দেয়।"),
    mcq("Which helps you hear a friend far away in a park?",
        ["A paper cone around your mouth", "Whispering", "Covering your mouth", "Turning your back"], 0,
        "A cone sends your voice in one direction instead of spreading it everywhere.",
        "পার্কে দূরের বন্ধুকে শোনাতে কী সাহায্য করে?",
        ["মুখের সামনে কাগজের চোঙা", "ফিসফিস করা", "মুখ ঢেকে রাখা", "পিছন ফিরে দাঁড়ানো"],
        "চোঙা তোমার গলাকে চারদিকে না ছড়িয়ে এক দিকে পাঠায়।"),
    mcq("You leave a metal spoon in hot soup. Soon the handle feels...",
        ["Hot", "Cold", "Wet", "Sticky"], 0,
        "Metals let heat travel through them easily. That is why pan handles are often made of wood or plastic.",
        "গরম স্যুপে ধাতুর চামচ রেখে দিলে। একটু পরে হাতলটা কেমন লাগবে?",
        ["গরম", "ঠান্ডা", "ভেজা", "চটচটে"],
        "ধাতুর মধ্য দিয়ে তাপ সহজে চলে। এজন্যই কড়াইয়ের হাতল প্রায়ই কাঠ বা প্লাস্টিকের হয়।"),
    mcq("A see-saw with nobody on it is level. You sit on one end. That end goes...",
        ["Down", "Up", "Nowhere", "Round and round"], 0,
        "Your weight pushes that end down. The other end goes up.",
        "খালি ঢেঁকি সমান আছে। তুমি এক প্রান্তে বসলে। সেই প্রান্ত যাবে...",
        ["নিচে", "উপরে", "কোথাও না", "গোল গোল ঘুরবে"],
        "তোমার ওজন সেই প্রান্তকে নিচে ঠেলে। অন্য প্রান্ত উপরে ওঠে।"),
    mcq("Which can you hear through?",
        ["A wall, a little", "Outer space", "Nothing at all - sound only goes through air", "Only through glass"], 0,
        "Sound can travel through solids like walls and through water, not just air. Space has no air, so it is silent.",
        "কোনটার মধ্য দিয়ে শুনতে পাও?",
        ["দেয়ালের মধ্য দিয়ে, একটু", "মহাকাশের মধ্য দিয়ে", "কিছুর মধ্য দিয়েই না - শব্দ শুধু বাতাসে চলে", "শুধু কাচের মধ্য দিয়ে"],
        "শব্দ শুধু বাতাসে নয়, দেয়ালের মতো কঠিন জিনিস আর জলের মধ্য দিয়েও চলে। মহাকাশে বাতাস নেই, তাই সেখানে নীরব।"),
    mcq("Why do wheelbarrows have a wheel at the front?",
        ["Rolling is easier than dragging", "To look like a car", "To make it heavier", "To slow it down"], 0,
        "Dragging rubs a lot (much friction). A wheel rolls, so moving heavy loads becomes easy.",
        "ঠেলাগাড়ির সামনে চাকা থাকে কেন?",
        ["টেনে হিঁচড়ানোর চেয়ে গড়ানো সহজ", "গাড়ির মতো দেখাতে", "ভারী করতে", "ধীর করতে"],
        "টেনে হিঁচড়ালে অনেক ঘষা লাগে (বেশি ঘর্ষণ)। চাকা গড়ায়, তাই ভারী জিনিস নেওয়া সহজ হয়।"),
    mcq("A bridge sags a little when a car drives over it. Is that normal?",
        ["Yes, a little bending is normal", "No, bridges never move at all", "Only on Sundays", "Only for red cars"], 0,
        "All bridges bend a tiny bit under weight and spring back. Engineers make sure the bending stays small and safe.",
        "গাড়ি গেলে সেতু একটু ঝুলে যায়। এটা কি স্বাভাবিক?",
        ["হ্যাঁ, একটু বাঁকা স্বাভাবিক", "না, সেতু কখনোই নড়ে না", "শুধু রবিবারে", "শুধু লাল গাড়ির জন্য"],
        "সব সেতুই ভারে সামান্য বাঁকে আর আবার ফিরে আসে। প্রকৌশলীরা নিশ্চিত করেন বাঁকা যেন ছোট আর নিরাপদ থাকে।"),
    mcq("Where would a ball roll faster?",
        ["Down a smooth steep slope", "On a flat sandy beach", "Up a hill", "In thick mud"], 0,
        "A steep slope gives a strong gravity pull, and a smooth surface has little friction.",
        "বল কোথায় বেশি দ্রুত গড়াবে?",
        ["মসৃণ খাড়া ঢাল বেয়ে নিচে", "সমতল বালুকাময় সৈকতে", "পাহাড় বেয়ে উপরে", "ঘন কাদায়"],
        "খাড়া ঢালে মাধ্যাকর্ষণের টান জোরালো, আর মসৃণ তলে ঘর্ষণ কম।"),
    mcq("You press a sponge. It gets smaller. When you stop pressing, it...",
        ["Grows back", "Stays tiny", "Disappears", "Turns hard as rock"], 0,
        "A sponge is springy. When the push is gone, it springs back to its shape.",
        "স্পঞ্জ চাপলে ছোট হয়। চাপ থামালে সেটা...",
        ["আবার বড় হয়", "ছোটই থাকে", "উধাও হয়ে যায়", "পাথরের মতো শক্ত হয়"],
        "স্পঞ্জ স্প্রিংয়ের মতো। ঠেলা সরে গেলে আবার আকারে ফিরে আসে।"),
    mcq("What does a ramp help you do?",
        ["Lift heavy things up a little at a time", "Make things heavier", "Stop gravity", "Make noise"], 0,
        "A ramp lets you raise a load bit by bit with a smaller push, instead of lifting it straight up.",
        "ঢালু পথ (র‍্যাম্প) কী করতে সাহায্য করে?",
        ["ভারী জিনিস একটু একটু করে উপরে তুলতে", "জিনিস ভারী করতে", "মাধ্যাকর্ষণ থামাতে", "শব্দ করতে"],
        "র‍্যাম্পে সোজা উপরে না তুলে কম ঠেলায় অল্প অল্প করে ভার তোলা যায়।"),
    mcq("Which is the strongest push?",
        ["A big strong wind in a storm", "A feather landing", "A butterfly's wing", "A whisper"], 0,
        "Storm winds push very hard - strong enough to bend trees. Bridges must be built to stand them.",
        "কোনটা সবচেয়ে জোরালো ঠেলা?",
        ["ঝড়ের বড় জোরালো বাতাস", "পালক নেমে আসা", "প্রজাপতির ডানা", "ফিসফিস"],
        "ঝড়ের বাতাস খুব জোরে ঠেলে - গাছ বাঁকিয়ে দেওয়ার মতো। সেতুকে তা সামলানোর মতো করে বানাতে হয়।"),
    mcq("Why do we see ourselves in a mirror?",
        ["Light bounces off the mirror back to our eyes", "The mirror takes a photo", "There is a twin inside", "The mirror glows"], 0,
        "A smooth shiny mirror bounces light back neatly, so you see your reflection.",
        "আয়নায় নিজেকে দেখি কেন?",
        ["আলো আয়নায় লেগে আমাদের চোখে ফিরে আসে", "আয়না ছবি তোলে", "ভেতরে একটা যমজ আছে", "আয়না জ্বলে"],
        "মসৃণ চকচকে আয়না আলোকে ঠিকমতো ফিরিয়ে দেয়, তাই তুমি তোমার প্রতিবিম্ব দেখো।"),
    mcq("A toy car runs out of push and stops. To start it again you must...",
        ["Push or pull it", "Look at it", "Sing to it", "Wait for it to go alone"], 0,
        "Things at rest stay at rest until a push or pull gets them moving.",
        "খেলনা গাড়ির ঠেলা ফুরিয়ে থেমে গেল। আবার চালাতে তোমাকে...",
        ["ঠেলতে বা টানতে হবে", "তাকিয়ে থাকতে হবে", "গান শোনাতে হবে", "একা চলার জন্য অপেক্ষা করতে হবে"],
        "স্থির জিনিস স্থিরই থাকে, যতক্ষণ না কোনো ঠেলা বা টান তাকে চালায়।"),
    mcq("A water slide is wet. Why does that make you go faster?",
        ["Water makes it slippery - less friction", "Water pushes you from behind", "Wet makes you lighter", "It does not change anything"], 0,
        "Water makes the surface slippery, so there is less rubbing and you slide faster. Splash!",
        "জলের স্লাইড ভেজা। তাতে তুমি দ্রুত যাও কেন?",
        ["জল তাকে পিছল করে - ঘর্ষণ কম", "জল পেছন থেকে ঠেলে", "ভেজা হলে তুমি হালকা হও", "কিছুই বদলায় না"],
        "জল তলকে পিছল করে, তাই ঘষা কম আর তুমি দ্রুত পিছলে যাও। ঝপাৎ!"),
    mcq("Which can stretch without breaking?",
        ["A rubber band", "A biscuit", "A glass", "A chalk stick"], 0,
        "Rubber is stretchy. Biscuits, glass and chalk are brittle - they snap instead.",
        "কোনটা না ভেঙে টেনে লম্বা করা যায়?",
        ["রাবার ব্যান্ড", "বিস্কুট", "কাচ", "চকের কাঠি"],
        "রাবার টানলে বাড়ে। বিস্কুট, কাচ আর চক ভঙ্গুর - বাড়ার বদলে ভেঙে যায়।"),
    mcq("Your dog pulls on its lead while you hold it. What do you feel?",
        ["A pull in your hand", "A push in your back", "Nothing", "A tickle on your nose"], 0,
        "The dog pulls the lead, and the tight lead pulls your hand. A tight rope or cable always pulls.",
        "তুমি ধরে থাকার সময় কুকুর তার দড়ি টানছে। তুমি কী টের পাও?",
        ["হাতে একটা টান", "পিঠে একটা ঠেলা", "কিছুই না", "নাকে সুড়সুড়ি"],
        "কুকুর দড়ি টানে, আর টানটান দড়ি তোমার হাত টানে। টানটান দড়ি বা তার সবসময় টানে।"),
    mcq("Which material lets light pass through so you can see behind it?",
        ["Clear glass", "Wood", "A brick", "A metal plate"], 0,
        "Clear glass is transparent: light goes through it. Wood, bricks and metal block light.",
        "কোন উপাদানের মধ্য দিয়ে আলো যায়, তাই পেছনটা দেখা যায়?",
        ["স্বচ্ছ কাচ", "কাঠ", "ইট", "ধাতুর পাত"],
        "স্বচ্ছ কাচের মধ্য দিয়ে আলো যায়। কাঠ, ইট আর ধাতু আলো আটকায়।"),
    mcq("Why do trains run on smooth steel rails?",
        ["Smooth rails let wheels roll easily", "Rails make trains colourful", "Rails make trains fly", "Rails are soft"], 0,
        "Hard smooth rails and wheels roll with very little friction, so one engine can pull many wagons.",
        "ট্রেন মসৃণ ইস্পাতের লাইনে চলে কেন?",
        ["মসৃণ লাইনে চাকা সহজে গড়ায়", "লাইন ট্রেনকে রঙিন করে", "লাইন ট্রেনকে ওড়ায়", "লাইন নরম"],
        "শক্ত মসৃণ লাইন আর চাকা খুব কম ঘর্ষণে গড়ায়, তাই একটি ইঞ্জিন অনেক ওয়াগন টানতে পারে।"),
    mcq("If you hang a heavy bag on a thin string, the string may...",
        ["Snap", "Get shorter", "Turn into a rope", "Glow"], 0,
        "Too much pull breaks a thin string. Use a thicker rope, or more strings, to share the pull.",
        "সরু সুতোয় ভারী ব্যাগ ঝোলালে সুতোটা...",
        ["ছিঁড়ে যেতে পারে", "ছোট হয়ে যেতে পারে", "দড়ি হয়ে যেতে পারে", "জ্বলতে পারে"],
        "বেশি টানে সরু সুতো ছেঁড়ে। টান ভাগ করতে মোটা দড়ি বা বেশি সুতো ব্যবহার করো।"),
    mcq("Which goes faster: a snail or a cheetah?",
        ["The cheetah", "The snail", "Both are equally fast", "Neither moves"], 0,
        "Speed is how far something goes in a certain time. A cheetah covers far more ground every second.",
        "কে দ্রুত চলে: শামুক নাকি চিতা?",
        ["চিতা", "শামুক", "দুজনেই সমান দ্রুত", "কেউ নড়ে না"],
        "গতি হলো নির্দিষ্ট সময়ে কতটা পথ যায়। চিতা প্রতি সেকেন্ডে অনেক বেশি পথ পেরোয়।"),
    mcq("A heavy box sits on the floor. What stops it from falling through?",
        ["The floor pushes up on it", "The box holds its breath", "Air under the box", "Nothing - it is falling slowly"], 0,
        "The floor pushes up exactly as hard as the box pushes down. In bridges these upward pushes are called reactions.",
        "মেঝেতে একটি ভারী বাক্স রাখা। কী তাকে মেঝে ভেদ করে পড়তে দেয় না?",
        ["মেঝে তাকে উপরে ঠেলে", "বাক্স দম আটকে রাখে", "বাক্সের নিচের বাতাস", "কিছু না - ধীরে পড়ছে"],
        "বাক্স যত জোরে নিচে ঠেলে, মেঝে ঠিক তত জোরে উপরে ঠেলে। সেতুতে এই উপরের ঠেলাকে বলে প্রতিক্রিয়া।"),
    mcq("You sit on a swing and a friend pushes. To go higher, the friend should push...",
        ["At the right moment, each time you swing back", "Any time at random", "Only once", "From the side"], 0,
        "Pushing in step with the swing adds up each time. That is resonance - and why wind in rhythm can shake a bridge.",
        "তুমি দোলনায় বসে, বন্ধু ঠেলছে। আরও উঁচুতে যেতে বন্ধুকে ঠেলতে হবে...",
        ["ঠিক সময়ে, প্রতিবার তুমি পেছনে ফিরলে", "যখন খুশি এলোমেলোভাবে", "শুধু একবার", "পাশ থেকে"],
        "দোলার তালে তালে ঠেলা প্রতিবার যোগ হয়। একেই বলে অনুনাদ - এজন্যই তালে তালে বাতাস সেতু কাঁপাতে পারে।"),
    mcq("Which is a good material for a toy bridge that must hold a lot?",
        ["Strong wooden sticks", "Wet paper", "Jelly", "Soap bubbles"], 0,
        "Wood is strong and stiff. Wet paper, jelly and bubbles cannot hold weight.",
        "অনেক ভার ধরতে হবে এমন খেলনা সেতুর জন্য ভালো উপাদান কোনটা?",
        ["শক্ত কাঠের কাঠি", "ভেজা কাগজ", "জেলি", "সাবানের বুদবুদ"],
        "কাঠ শক্ত আর দৃঢ়। ভেজা কাগজ, জেলি আর বুদবুদ ওজন ধরতে পারে না।"),
    mcq("When you jump, why do you come back down?",
        ["Gravity pulls you back to the ground", "Your shoes are heavy", "The sky pushes you", "You decide to"], 0,
        "Gravity always pulls you down, so every jump ends with a landing.",
        "লাফ দিলে আবার নিচে নামো কেন?",
        ["মাধ্যাকর্ষণ তোমাকে মাটিতে টেনে আনে", "তোমার জুতো ভারী", "আকাশ তোমাকে ঠেলে", "তুমি নিজেই ঠিক করো"],
        "মাধ্যাকর্ষণ সবসময় তোমাকে নিচে টানে, তাই প্রতিটি লাফ শেষ হয় মাটিতে নেমে।"),
    mcq("A marble rolls on a table and falls off the edge. Then it...",
        ["Falls to the floor", "Keeps rolling in the air", "Goes back up", "Stops in the air"], 0,
        "Once nothing holds it up, gravity pulls it down to the floor.",
        "টেবিলে একটি মার্বেল গড়িয়ে কিনারা থেকে পড়ে গেল। তারপর সেটা...",
        ["মেঝেতে পড়ে", "বাতাসে গড়াতেই থাকে", "আবার উপরে ওঠে", "বাতাসে থেমে থাকে"],
        "কিছু তাকে ধরে না রাখলে মাধ্যাকর্ষণ তাকে মেঝেতে টেনে নামায়।"),
    mcq("Which is quieter?",
        ["A mouse squeak", "A lion roar", "A train horn", "Thunder"], 0,
        "A mouse makes tiny vibrations, so its sound is soft. Roars, horns and thunder shake the air hard.",
        "কোনটা বেশি আস্তে?",
        ["ইঁদুরের চিঁ চিঁ", "সিংহের গর্জন", "ট্রেনের হর্ন", "বাজ"],
        "ইঁদুর খুব ছোট কম্পন তৈরি করে, তাই তার শব্দ আস্তে। গর্জন, হর্ন আর বাজ বাতাসকে জোরে কাঁপায়।"),
    mcq("A cart is easy to push on a road but hard on sand. Why?",
        ["Wheels sink into sand and it rubs more", "Sand is lighter", "Roads are wet", "Sand pushes the cart forward"], 0,
        "Soft sand lets wheels sink in, so they must climb out all the time. That takes a much bigger push.",
        "ঠেলাগাড়ি রাস্তায় ঠেলা সহজ কিন্তু বালিতে কঠিন। কেন?",
        ["চাকা বালিতে বসে যায় আর বেশি ঘষা লাগে", "বালি হালকা", "রাস্তা ভেজা", "বালি গাড়িকে সামনে ঠেলে"],
        "নরম বালিতে চাকা ডেবে যায়, তাই সারাক্ষণ উঠে আসতে হয়। তাতে অনেক বেশি ঠেলা লাগে।"),
    mcq("Which helps a heavy ship float?",
        ["Water pushing up on it", "Its shiny paint", "Its loud horn", "Birds on top"], 0,
        "Water pushes up on anything in it. A ship is shaped to push aside enough water to be held up.",
        "ভারী জাহাজকে ভাসতে কী সাহায্য করে?",
        ["জল তাকে উপরে ঠেলে", "তার চকচকে রং", "তার জোরালো ভেঁপু", "উপরে বসা পাখি"],
        "জল তার মধ্যের সবকিছুকে উপরে ঠেলে। জাহাজের আকার এমন যে যথেষ্ট জল সরিয়ে ভেসে থাকে।"),
    mcq("A tall thin glass falls over more easily than a short wide bowl. Why?",
        ["The glass has a narrow bottom", "Glass is naughty", "Bowls are glued", "The bowl is taller"], 0,
        "Tall things with a narrow base tip easily. Wide, low things are steady.",
        "লম্বা সরু গ্লাস খাটো চওড়া বাটির চেয়ে সহজে উল্টে পড়ে কেন?",
        ["গ্লাসের তলা সরু", "গ্লাস দুষ্টু", "বাটি আঠা দিয়ে লাগানো", "বাটি বেশি লম্বা"],
        "সরু ভিত্তির লম্বা জিনিস সহজে উল্টায়। চওড়া, নিচু জিনিস স্থির থাকে।"),
    mcq("What happens to a puddle on a hot sunny day?",
        ["It slowly dries up", "It gets deeper", "It freezes", "It turns into milk"], 0,
        "The sun's heat turns the water into invisible water vapour that floats into the air.",
        "গরম রোদের দিনে কাদাজলের ডোবার কী হয়?",
        ["ধীরে ধীরে শুকিয়ে যায়", "আরও গভীর হয়", "জমে বরফ হয়", "দুধ হয়ে যায়"],
        "সূর্যের তাপ জলকে অদৃশ্য জলীয় বাষ্পে বদলায়, যা বাতাসে ভেসে যায়।"),
    mcq("Two magnets push each other away. This happens when...",
        ["The same ends face each other", "They are made of wood", "They are far apart", "It is raining"], 0,
        "Magnets have two ends, north and south. Like ends push apart; opposite ends pull together.",
        "দুটি চুম্বক একে অপরকে দূরে ঠেলে। এটা হয় যখন...",
        ["একই প্রান্ত মুখোমুখি থাকে", "সেগুলো কাঠের তৈরি", "অনেক দূরে থাকে", "বৃষ্টি হয়"],
        "চুম্বকের দুটি প্রান্ত, উত্তর আর দক্ষিণ। একই প্রান্ত দূরে ঠেলে; উল্টো প্রান্ত কাছে টানে।"),
    mcq("You carry a full school bag on one shoulder. You lean to the other side. Why?",
        ["To keep your balance", "To look cool", "To make the bag lighter", "No reason"], 0,
        "Leaning the other way keeps your weight over your feet, so you do not tip over.",
        "এক কাঁধে ভরা স্কুলব্যাগ নিয়ে তুমি অন্য দিকে হেলে পড়ো। কেন?",
        ["ভারসাম্য রাখতে", "কেতা দেখাতে", "ব্যাগ হালকা করতে", "কোনো কারণ নেই"],
        "উল্টো দিকে হেলে থাকলে তোমার ওজন পায়ের উপরে থাকে, তাই উল্টে পড়ো না।"),
    mcq("What makes a paper windmill spin?",
        ["Moving air pushing its blades", "The colour of the paper", "Its stick", "Gravity alone"], 0,
        "Wind pushes the slanted blades, and the pushes turn the windmill round.",
        "কাগজের ঘূর্ণি (উইন্ডমিল) ঘোরে কীসে?",
        ["চলমান বাতাস তার পাখা ঠেলে", "কাগজের রং", "তার কাঠি", "শুধু মাধ্যাকর্ষণ"],
        "বাতাস হেলানো পাখাগুলো ঠেলে, আর সেই ঠেলায় ঘূর্ণি ঘোরে।"),
    mcq("A heavy ball and a light ball roll at the same speed. Which is harder to stop?",
        ["The heavy ball", "The light ball", "They are equally easy", "Neither can be stopped"], 0,
        "A heavy moving thing carries more 'oomph' (momentum), so stopping it needs a bigger push. Heavy "
        "trains need long distances to stop.",
        "একটি ভারী আর একটি হালকা বল একই গতিতে গড়াচ্ছে। কোনটা থামানো কঠিন?",
        ["ভারী বল", "হালকা বল", "দুটোই সমান সহজ", "কোনোটাই থামানো যায় না"],
        "চলমান ভারী জিনিসের 'জোর' (ভরবেগ) বেশি, তাই থামাতে বড় ঠেলা লাগে। ভারী ট্রেনের থামতে অনেক পথ লাগে।"),
    mcq("Why do builders put a crossbar (diagonal) on a square gate?",
        ["To make triangles so the gate cannot sag", "To hang clothes", "To make it heavier", "For decoration only"], 0,
        "A diagonal turns the wobbly square into two strong triangles, so the gate keeps its shape.",
        "বর্গাকার গেটে নির্মাতারা আড়াআড়ি দণ্ড (কর্ণ) লাগান কেন?",
        ["ত্রিভুজ বানাতে, যাতে গেট ঝুলে না পড়ে", "জামা ঝোলাতে", "ভারী করতে", "শুধু সাজাতে"],
        "কর্ণ নড়বড়ে বর্গকে দুটি মজবুত ত্রিভুজে বদলায়, তাই গেট তার আকার রাখে।"),
    mcq("You push a door near the hinges and then at the handle. Where is it easier?",
        ["At the handle, far from the hinges", "Near the hinges", "Both are the same", "On the top edge only"], 0,
        "Pushing far from the turning point gives a bigger turning effect. That is why handles are far from hinges.",
        "তুমি দরজা একবার কবজার কাছে আর একবার হাতলে ঠেললে। কোথায় সহজ?",
        ["হাতলে, কবজা থেকে দূরে", "কবজার কাছে", "দুটোই সমান", "শুধু উপরের কিনারায়"],
        "ঘোরার বিন্দু থেকে দূরে ঠেললে ঘোরানোর প্রভাব বড় হয়। এজন্যই হাতল কবজা থেকে দূরে থাকে।"),
    mcq("A rope bridge in the jungle swings when you walk on it. What would make it steadier?",
        ["Tying it tight with extra ropes to the sides", "Jumping on it", "Making it longer and looser", "Painting it"], 0,
        "Extra side ropes hold the bridge in place and stop it swinging. Real bridges add bracing for the same reason.",
        "জঙ্গলের দড়ির সেতু হাঁটলে দোলে। কী করলে বেশি স্থির হবে?",
        ["বাড়তি দড়ি দিয়ে দুই পাশে টানটান করে বাঁধা", "তার উপর লাফানো", "আরও লম্বা আর ঢিলা করা", "রং করা"],
        "পাশের বাড়তি দড়ি সেতুকে জায়গায় ধরে রাখে আর দোলা থামায়। আসল সেতুও একই কারণে ঠেকনা যোগ করে।"),
    mcq("Which happens when you pour water on a slope?",
        ["It flows downhill", "It flows uphill", "It stays in one place", "It jumps sideways"], 0,
        "Gravity pulls water down the slope. That is why rivers flow from hills to the sea.",
        "ঢালে জল ঢাললে কী হয়?",
        ["নিচের দিকে বয়ে যায়", "উপরের দিকে বয়ে যায়", "এক জায়গায় থাকে", "পাশে লাফিয়ে যায়"],
        "মাধ্যাকর্ষণ জলকে ঢাল বেয়ে নিচে টানে। এজন্যই নদী পাহাড় থেকে সাগরে বয়।"),
    mcq("A bridge builder tests a new bridge before people use it. Why?",
        ["To check it is strong enough and safe", "To make it pretty", "To waste time", "Builders like driving"], 0,
        "Testing with heavy loads first proves the bridge is safe. In MODIS BridgeWorks, TEST and RUN do just that.",
        "মানুষ ব্যবহারের আগে সেতু-নির্মাতা নতুন সেতু পরীক্ষা করেন। কেন?",
        ["যথেষ্ট শক্ত আর নিরাপদ কিনা দেখতে", "সুন্দর করতে", "সময় নষ্ট করতে", "নির্মাতারা গাড়ি চালাতে ভালোবাসেন"],
        "আগে ভারী ভারে পরীক্ষা করলে প্রমাণ হয় সেতু নিরাপদ। MODIS BridgeWorks-এ 'পরীক্ষা' আর 'চালাও' ঠিক তাই করে।"),
    mcq("What do you feel when a strong wind blows against you?",
        ["A push", "A pull from the front", "Nothing", "A spin"], 0,
        "Moving air pushes on everything in its way - you, trees, kites and bridges.",
        "জোরালো বাতাস তোমার গায়ে লাগলে কী টের পাও?",
        ["একটা ঠেলা", "সামনে থেকে টান", "কিছুই না", "একটা ঘূর্ণি"],
        "চলমান বাতাস পথের সবকিছুকে ঠেলে - তোমাকে, গাছকে, ঘুড়িকে আর সেতুকেও।"),
    mcq("Why is a bridge's middle part often the bendiest?",
        ["It is furthest from the supports", "It is painted thinner", "Cars drive faster there", "The middle is always broken"], 0,
        "The middle has the longest distance to any support, so it bends the most - like a ruler held at both ends.",
        "সেতুর মাঝের অংশ প্রায়ই সবচেয়ে বেশি বাঁকে কেন?",
        ["এটা সাপোর্ট থেকে সবচেয়ে দূরে", "এখানে রং পাতলা", "এখানে গাড়ি দ্রুত চলে", "মাঝখান সবসময় ভাঙা"],
        "মাঝখান থেকে যেকোনো সাপোর্ট সবচেয়ে দূরে, তাই সবচেয়ে বেশি বাঁকে - দুই প্রান্তে ধরা স্কেলের মতো।"),
    mcq("A heavy toy goes down a slide faster than a light one?",
        ["No - on a smooth slide they go about the same speed", "Yes, always much faster", "Heavy toys go up", "Light toys stop"], 0,
        "Without much air or rubbing, gravity speeds heavy and light things up in the same way. Surprise!",
        "ভারী খেলনা কি হালকাটার চেয়ে দ্রুত স্লাইড বেয়ে নামে?",
        ["না - মসৃণ স্লাইডে প্রায় একই গতিতে নামে", "হ্যাঁ, সবসময় অনেক দ্রুত", "ভারী খেলনা উপরে যায়", "হালকা খেলনা থেমে যায়"],
        "বাতাস বা ঘষা বেশি না থাকলে মাধ্যাকর্ষণ ভারী আর হালকা জিনিসকে একইভাবে দ্রুত করে। অবাক কাণ্ড!"),
    mcq("You stand on one leg. Why is it harder than standing on two?",
        ["Your base is smaller, so balance is harder", "One leg is lazy", "Gravity is stronger", "Your shoes are slippery"], 0,
        "Two feet spread apart make a wider base. A small base makes it easy to tip over.",
        "এক পায়ে দাঁড়ানো দুই পায়ের চেয়ে কঠিন কেন?",
        ["ভিত্তি ছোট, তাই ভারসাম্য কঠিন", "এক পা অলস", "মাধ্যাকর্ষণ বেশি", "জুতো পিছল"],
        "দুই পা ছড়ানো থাকলে ভিত্তি চওড়া হয়। ছোট ভিত্তিতে সহজে উল্টে পড়া যায়।"),
    mcq("Which travels in a straight line?",
        ["Light from a torch", "A snake", "A bouncing ball", "A spinning top"], 0,
        "Light goes in straight lines - point a torch and see its straight beam.",
        "কোনটা সোজা পথে চলে?",
        ["টর্চের আলো", "সাপ", "লাফানো বল", "ঘুরন্ত লাটিম"],
        "আলো সোজা পথে চলে - টর্চ জ্বেলে তার সোজা রশ্মি দেখো।"),
    mcq("What is the job of a bridge?",
        ["To carry people and vehicles safely over a gap", "To stop rivers flowing", "To scare birds", "To make shade only"], 0,
        "A bridge carries loads across a gap - a river, a valley or a road - and passes the weight safely to the ground.",
        "সেতুর কাজ কী?",
        ["মানুষ আর গাড়িকে নিরাপদে ফাঁক পার করানো", "নদীর স্রোত থামানো", "পাখি তাড়ানো", "শুধু ছায়া দেওয়া"],
        "সেতু ফাঁক - নদী, উপত্যকা বা রাস্তা - পেরিয়ে ভার বয় আর ওজনকে নিরাপদে মাটিতে পৌঁছে দেয়।"),
    mcq("You squeeze a plastic bottle. What did you do to it?",
        ["Pushed on it from the sides", "Pulled it apart", "Heated it", "Made it float"], 0,
        "Squeezing is pushing inwards. Engineers call a squeezing force compression.",
        "তুমি প্লাস্টিকের বোতল চেপে ধরলে। তার সঙ্গে কী করলে?",
        ["দুই পাশ থেকে ঠেললে", "টেনে আলাদা করলে", "গরম করলে", "ভাসিয়ে দিলে"],
        "চেপে ধরা মানে ভেতরের দিকে ঠেলা। প্রকৌশলীরা চেপে ধরার বলকে বলেন চাপ।"),
    mcq("You pull both ends of a rope apart. The rope is being...",
        ["Stretched (pulled)", "Squeezed", "Melted", "Painted"], 0,
        "Pulling the ends apart stretches the rope. Engineers call this tension - cables in bridges work this way.",
        "দড়ির দুই প্রান্ত দুই দিকে টানলে দড়ির কী হচ্ছে?",
        ["টেনে লম্বা হচ্ছে (টান)", "চাপা খাচ্ছে", "গলে যাচ্ছে", "রং হচ্ছে"],
        "দুই প্রান্ত টানলে দড়ি টানটান হয়। প্রকৌশলীরা একে বলেন টান - সেতুর তারও এভাবেই কাজ করে।"),
    mcq("Why does a parachute fall slowly?",
        ["Its big shape catches lots of air", "It is lighter than a feather", "Parachutes love the sky", "It has an engine"], 0,
        "The wide canopy pushes against lots of air, and the air pushes back up, slowing the fall.",
        "প্যারাসুট ধীরে নামে কেন?",
        ["তার বড় আকার অনেক বাতাস ধরে", "সেটা পালকের চেয়ে হালকা", "প্যারাসুট আকাশ ভালোবাসে", "তাতে ইঞ্জিন আছে"],
        "চওড়া ছাতা অনেক বাতাসের বিরুদ্ধে ঠেলে, আর বাতাস উল্টো উপরে ঠেলে পতন ধীর করে।"),
    mcq("A heavy truck and a bicycle cross a bridge. Which puts more weight on it?",
        ["The truck", "The bicycle", "Both the same", "Neither"], 0,
        "The truck is far heavier, so the bridge must hold a much bigger load when it crosses.",
        "একটি ভারী ট্রাক আর একটি সাইকেল সেতু পার হচ্ছে। কোনটা বেশি ওজন চাপায়?",
        ["ট্রাক", "সাইকেল", "দুটোই সমান", "কোনোটাই না"],
        "ট্রাক অনেক বেশি ভারী, তাই সে পার হওয়ার সময় সেতুকে অনেক বড় ভার ধরতে হয়।"),
    mcq("Which of these is a force?",
        ["A push", "A colour", "A smell", "A number"], 0,
        "A force is a push or a pull. Forces make things start, stop, speed up, slow down or change shape.",
        "এগুলোর মধ্যে কোনটা বল?",
        ["একটা ঠেলা", "একটা রং", "একটা গন্ধ", "একটা সংখ্যা"],
        "বল হলো ঠেলা বা টান। বল জিনিসকে চালু করে, থামায়, দ্রুত বা ধীর করে, বা আকার বদলায়।"),
)
