"""Class 1 - Math: counting, adding, taking away, shapes, comparing, patterns and measuring."""
from . import mcq


def add(a, b, thing_en, thing_bn, story_en, story_bn):
    """A friendly adding question with three wrong answers close to the right one."""
    r = a + b
    return mcq(story_en.format(a=a, b=b), [str(r), str(r + 1), str(r - 1), str(r + 2)], 0,
               f"{a} + {b} = {r} {thing_en}. Count on {b} from {a}: you land on {r}.",
               story_bn.format(a=a, b=b), [str(r), str(r + 1), str(r - 1), str(r + 2)],
               f"{a} + {b} = {r}টি {thing_bn}। {a} থেকে আরও {b} গুনে এগোলে {r}-এ পৌঁছাও।")


def sub(a, b, thing_en, thing_bn, story_en, story_bn):
    r = a - b
    return mcq(story_en.format(a=a, b=b), [str(r), str(r + 1), str(r + 2), str(max(0, r - 1)) if r > 1 else str(r + 3)], 0,
               f"{a} - {b} = {r} {thing_en}. Take {b} away from {a} and {r} are left.",
               story_bn.format(a=a, b=b), [str(r), str(r + 1), str(r + 2), str(max(0, r - 1)) if r > 1 else str(r + 3)],
               f"{a} - {b} = {r}টি {thing_bn}। {a} থেকে {b}টি সরালে {r}টি থাকে।")


ITEMS = (
    mcq("A bridge pillar needs 5 giant stone blocks, and a sneaky river monster eats 2. How many are left?",
        ["3", "2", "7", "5"], 0,
        "5 - 2 = 3 blocks. (And one very full, very angry river monster.)",
        "একটি সেতুর স্তম্ভে 5টি বিশাল পাথরের ব্লক লাগে, আর এক দুষ্টু নদী-দানব 2টি খেয়ে ফেলল। কতগুলো বাকি?",
        ["3", "2", "7", "5"],
        "5 - 2 = 3টি ব্লক। (আর একটা পেট-ভরা, খুব রাগী নদী-দানব।)"),
    add(2, 3, "trucks", "ট্রাক", "2 trucks are on a bridge and 3 more drive on. How many trucks are on the bridge now?",
        "সেতুতে 2টি ট্রাক আছে, আরও 3টি উঠল। এখন সেতুতে কয়টি ট্রাক?"),
    add(4, 4, "wheels", "চাকা", "A toy car has 4 wheels. A second toy car has {b} wheels too. How many wheels altogether?",
        "একটি খেলনা গাড়ির 4টি চাকা। দ্বিতীয় খেলনা গাড়িরও {b}টি চাকা। মোট কয়টি চাকা?"),
    add(6, 2, "birds", "পাখি", "{a} birds sit on a bridge rail. {b} more land. How many birds now?",
        "সেতুর রেলিংয়ে {a}টি পাখি বসে আছে। আরও {b}টি এসে বসল। এখন কয়টি পাখি?"),
    add(3, 5, "bricks", "ইট", "You have {a} bricks and a friend gives you {b}. How many bricks do you have?",
        "তোমার {a}টি ইট আছে, বন্ধু তোমাকে আরও {b}টি দিল। তোমার কয়টি ইট হলো?"),
    add(7, 3, "ducks", "হাঁস", "{a} ducks swim under a bridge, then {b} more swim in. How many ducks?",
        "সেতুর নিচে {a}টি হাঁস সাঁতার কাটছে, তারপর আরও {b}টি এল। মোট কয়টি হাঁস?"),
    add(5, 5, "fingers", "আঙুল", "One hand has {a} fingers. Two hands have {a} + {b}. How many fingers?",
        "এক হাতে {a}টি আঙুল। দুই হাতে {a} + {b}। মোট কয়টি আঙুল?"),
    add(8, 1, "cars", "গাড়ি", "{a} cars wait at the bridge. {b} more car joins the queue. How many cars wait?",
        "সেতুর সামনে {a}টি গাড়ি অপেক্ষা করছে। আরও {b}টি গাড়ি লাইনে দাঁড়াল। কয়টি গাড়ি অপেক্ষা করছে?"),
    add(9, 2, "nails", "পেরেক", "A builder has {a} nails and finds {b} more. How many nails?",
        "এক মিস্ত্রির কাছে {a}টি পেরেক, আরও {b}টি পেলেন। কয়টি পেরেক হলো?"),
    add(6, 6, "eggs", "ডিম", "Two boxes each hold {a} eggs. How many eggs in both boxes?",
        "দুটি বাক্সের প্রতিটিতে {a}টি ডিম। দুই বাক্সে মোট কয়টি ডিম?"),
    add(10, 5, "planks", "তক্তা", "A bridge has {a} planks. The builder adds {b} more. How many planks?",
        "একটি সেতুতে {a}টি তক্তা। মিস্ত্রি আরও {b}টি লাগালেন। কয়টি তক্তা হলো?"),
    add(12, 3, "kites", "ঘুড়ি", "{a} kites fly in the sky and {b} more go up. How many kites fly?",
        "আকাশে {a}টি ঘুড়ি উড়ছে, আরও {b}টি উঠল। কয়টি ঘুড়ি উড়ছে?"),
    add(4, 7, "apples", "আপেল", "There are {a} red apples and {b} green apples. How many apples?",
        "{a}টি লাল আপেল আর {b}টি সবুজ আপেল আছে। মোট কয়টি আপেল?"),
    add(11, 4, "buses", "বাস", "{a} buses cross the bridge in the morning and {b} in the evening. How many buses in all?",
        "সকালে {a}টি বাস সেতু পার হলো আর সন্ধ্যায় {b}টি। মোট কয়টি বাস?"),
    add(8, 8, "legs", "পা", "A spider has {a} legs. Two spiders have {a} + {b} legs. How many legs?",
        "একটি মাকড়সার {a}টি পা। দুটি মাকড়সার {a} + {b}টি পা। মোট কয়টি পা?"),
    sub(10, 3, "balloons", "বেলুন", "You have {a} balloons and {b} pop. How many are left?",
        "তোমার {a}টি বেলুন ছিল, {b}টি ফেটে গেল। কয়টি বাকি?"),
    sub(8, 5, "sweets", "মিষ্টি", "You have {a} sweets and eat {b}. How many are left?",
        "তোমার {a}টি মিষ্টি ছিল, {b}টি খেয়ে ফেললে। কয়টি বাকি?"),
    sub(9, 4, "boats", "নৌকা", "{a} boats are at the river bank. {b} sail away. How many are still there?",
        "নদীর পাড়ে {a}টি নৌকা ছিল। {b}টি ভেসে চলে গেল। কয়টি এখনো আছে?"),
    sub(7, 7, "cookies", "কুকি", "There are {a} cookies and your brother eats all {b}. How many are left?",
        "{a}টি কুকি ছিল, তোমার ভাই {b}টিই খেয়ে ফেলল। কয়টি বাকি?"),
    sub(12, 2, "cones", "কোন", "{a} traffic cones stand on a bridge. Workers take {b} away. How many remain?",
        "সেতুতে {a}টি ট্রাফিক কোন দাঁড় করানো। শ্রমিকরা {b}টি সরিয়ে নিলেন। কয়টি রইল?"),
    sub(15, 5, "fish", "মাছ", "{a} fish swim in a pond. A heron catches {b}. How many fish now?",
        "পুকুরে {a}টি মাছ সাঁতার কাটছে। একটি বক {b}টি ধরল। এখন কয়টি মাছ?"),
    sub(6, 1, "pencils", "পেনসিল", "You have {a} pencils and lose {b}. How many do you have?",
        "তোমার {a}টি পেনসিল ছিল, {b}টি হারালে। এখন কয়টি আছে?"),
    sub(11, 6, "trains", "ট্রেন", "{a} trains are in the station. {b} leave. How many trains are still in the station?",
        "স্টেশনে {a}টি ট্রেন ছিল। {b}টি ছেড়ে গেল। কয়টি ট্রেন এখনো স্টেশনে?"),
    sub(14, 4, "beads", "পুঁতি", "A string has {a} beads and {b} fall off. How many beads stay on?",
        "একটি সুতোয় {a}টি পুঁতি, {b}টি খুলে পড়ল। কয়টি পুঁতি রইল?"),
    sub(20, 10, "steps", "ধাপ", "A ladder has {a} steps. You climb {b}. How many more steps to the top?",
        "একটি মইয়ে {a}টি ধাপ। তুমি {b}টি উঠেছ। মাথায় পৌঁছাতে আর কয়টি ধাপ?"),
    mcq("Which number comes just after 9?", ["10", "8", "19", "90"], 0,
        "Counting goes 7, 8, 9, 10. After 9 comes 10.",
        "9-এর ঠিক পরে কোন সংখ্যা?", ["10", "8", "19", "90"],
        "গোনা চলে 7, 8, 9, 10। 9-এর পরে আসে 10।"),
    mcq("Which number comes just before 5?", ["4", "6", "3", "15"], 0,
        "1, 2, 3, 4, 5 - the number before 5 is 4.",
        "5-এর ঠিক আগে কোন সংখ্যা?", ["4", "6", "3", "15"],
        "1, 2, 3, 4, 5 - 5-এর আগের সংখ্যা 4।"),
    mcq("Which is the biggest number?", ["18", "8", "11", "15"], 0,
        "18 has 1 ten and 8 ones - more than 15, 11 or 8.",
        "কোনটা সবচেয়ে বড় সংখ্যা?", ["18", "8", "11", "15"],
        "18-এ 1টি দশ আর 8টি এক - 15, 11 বা 8-এর চেয়ে বেশি।"),
    mcq("Which is the smallest number?", ["3", "13", "30", "33"], 0,
        "3 is less than 13, 30 and 33.",
        "কোনটা সবচেয়ে ছোট সংখ্যা?", ["3", "13", "30", "33"],
        "3, 13, 30 আর 33-এর চেয়ে কম।"),
    mcq("How many sides does a triangle have?", ["3", "4", "5", "0"], 0,
        "Tri means three. A triangle has 3 sides and 3 corners - the bridge builder's favourite shape!",
        "ত্রিভুজের কয়টি বাহু?", ["3", "4", "5", "0"],
        "'ত্রি' মানে তিন। ত্রিভুজের 3টি বাহু আর 3টি কোণ - সেতু-নির্মাতার প্রিয় আকার!"),
    mcq("How many sides does a square have?", ["4", "3", "5", "6"], 0,
        "A square has 4 equal sides and 4 corners.",
        "বর্গের কয়টি বাহু?", ["4", "3", "5", "6"],
        "বর্গের 4টি সমান বাহু আর 4টি কোণ।"),
    mcq("A circle has how many corners?", ["0", "1", "2", "4"], 0,
        "A circle is perfectly round - no corners at all. That is why wheels are circles.",
        "বৃত্তের কয়টি কোণ?", ["0", "1", "2", "4"],
        "বৃত্ত একদম গোল - কোনো কোণ নেই। এজন্যই চাকা বৃত্তাকার।"),
    mcq("What shape is a pizza (before you cut it)?", ["Circle", "Square", "Triangle", "Star"], 0,
        "A whole round pizza is a circle. Cut a slice and you get a triangle-like shape!",
        "কাটার আগে পিৎজার আকার কী?", ["বৃত্ত", "বর্গ", "ত্রিভুজ", "তারা"],
        "আস্ত গোল পিৎজা একটা বৃত্ত। এক টুকরো কাটলে প্রায় ত্রিভুজের মতো আকার পাও!"),
    mcq("What comes next? 2, 4, 6, 8, ...", ["10", "9", "12", "7"], 0,
        "The pattern adds 2 each time: 8 + 2 = 10.",
        "এরপর কী আসবে? 2, 4, 6, 8, ...", ["10", "9", "12", "7"],
        "নকশাটা প্রতিবার 2 যোগ করে: 8 + 2 = 10।"),
    mcq("What comes next? 5, 10, 15, 20, ...", ["25", "21", "30", "22"], 0,
        "Counting in fives: 20 + 5 = 25.",
        "এরপর কী আসবে? 5, 10, 15, 20, ...", ["25", "21", "30", "22"],
        "পাঁচ পাঁচ করে গোনা: 20 + 5 = 25।"),
    mcq("What comes next? red, blue, red, blue, ...", ["red", "green", "blue", "yellow"], 0,
        "The colours take turns: red, blue, red, blue, red.",
        "এরপর কী আসবে? লাল, নীল, লাল, নীল, ...", ["লাল", "সবুজ", "নীল", "হলুদ"],
        "রংগুলো পালা করে আসে: লাল, নীল, লাল, নীল, লাল।"),
    mcq("Which is longer: a bus or a bicycle?", ["A bus", "A bicycle", "They are the same", "Neither has a length"], 0,
        "A bus is many metres long; a bicycle is under 2 metres.",
        "কোনটা বেশি লম্বা: বাস নাকি সাইকেল?", ["বাস", "সাইকেল", "দুটো সমান", "কোনোটারই দৈর্ঘ্য নেই"],
        "বাস অনেক মিটার লম্বা; সাইকেল 2 মিটারের কম।"),
    mcq("Which is heavier: an elephant or a cat?", ["The elephant", "The cat", "Same weight", "Cats weigh more on Mondays"], 0,
        "An elephant weighs as much as dozens of cars. A cat is light enough to pick up.",
        "কোনটা বেশি ভারী: হাতি নাকি বিড়াল?", ["হাতি", "বিড়াল", "ওজন সমান", "সোমবারে বিড়াল বেশি ভারী"],
        "একটি হাতির ওজন ডজনখানেক গাড়ির সমান। বিড়াল এত হালকা যে কোলে তোলা যায়।"),
    mcq("A bridge has 3 pillars on each side of a river. How many pillars in all?", ["6", "3", "5", "9"], 0,
        "3 + 3 = 6 pillars.",
        "একটি সেতুর নদীর প্রতিটি পাশে 3টি করে স্তম্ভ। মোট কয়টি স্তম্ভ?", ["6", "3", "5", "9"],
        "3 + 3 = 6টি স্তম্ভ।"),
    mcq("How many days are in one week?", ["7", "5", "10", "12"], 0,
        "Monday to Sunday is 7 days.",
        "এক সপ্তাহে কয় দিন?", ["7", "5", "10", "12"],
        "সোমবার থেকে রবিবার 7 দিন।"),
    mcq("Half of 10 sweets is...", ["5", "2", "10", "20"], 0,
        "Halving shares into 2 equal parts: 10 shared by 2 friends is 5 each.",
        "10টি মিষ্টির অর্ধেক হলো...", ["5", "2", "10", "20"],
        "অর্ধেক মানে সমান 2 ভাগ: 10টি 2 বন্ধুর মধ্যে ভাগ করলে প্রত্যেকে 5টি।"),
    mcq("Double 4 is...", ["8", "6", "4", "16"], 0,
        "Double means two lots of: 4 + 4 = 8.",
        "4-এর দ্বিগুণ হলো...", ["8", "6", "4", "16"],
        "দ্বিগুণ মানে দুবার: 4 + 4 = 8।"),
    mcq("A cake is cut into 2 equal pieces. Each piece is...", ["One half", "One third", "One quarter", "The whole cake"], 0,
        "2 equal parts are halves. Each piece is one half.",
        "একটি কেক সমান 2 টুকরো করা হলো। প্রতিটি টুকরো হলো...", ["অর্ধেক", "এক-তৃতীয়াংশ", "এক-চতুর্থাংশ", "পুরো কেক"],
        "সমান 2 ভাগের প্রতিটি অর্ধেক।"),
    mcq("How many tens are in 30?", ["3", "30", "10", "0"], 0,
        "30 = 10 + 10 + 10, so 3 tens.",
        "30-এ কয়টি দশ আছে?", ["3", "30", "10", "0"],
        "30 = 10 + 10 + 10, তাই 3টি দশ।"),
    mcq("In the number 14, the 1 means...", ["1 ten", "1 one", "14 tens", "Nothing"], 0,
        "14 is 1 ten and 4 ones: 10 + 4.",
        "14 সংখ্যায় 1 মানে...", ["1টি দশ", "1টি এক", "14টি দশ", "কিছুই না"],
        "14 হলো 1টি দশ আর 4টি এক: 10 + 4।"),
    mcq("You see 3 cars, then 3 more, then 3 more. How many cars?", ["9", "6", "12", "3"], 0,
        "3 + 3 + 3 = 9. Three groups of three!",
        "তুমি 3টি গাড়ি দেখলে, তারপর আরও 3টি, তারপর আরও 3টি। মোট কয়টি গাড়ি?", ["9", "6", "12", "3"],
        "3 + 3 + 3 = 9। তিনটে করে তিন দল!"),
    mcq("Which shape is a road sign that says STOP in many countries?", ["Octagon (8 sides)", "Circle", "Triangle", "Square"], 0,
        "A STOP sign usually has 8 sides - an octagon - so drivers know it even from far away.",
        "অনেক দেশে 'থামো' (STOP) লেখা রাস্তার চিহ্ন কোন আকারের?", ["অষ্টভুজ (8 বাহু)", "বৃত্ত", "ত্রিভুজ", "বর্গ"],
        "থামার চিহ্নের সাধারণত 8টি বাহু থাকে - অষ্টভুজ - যাতে চালকরা দূর থেকেও চিনতে পারেন।"),
    mcq("You have 2 coins of 5 rupees. How much money is that?", ["10 rupees", "7 rupees", "5 rupees", "25 rupees"], 0,
        "5 + 5 = 10 rupees.",
        "তোমার কাছে 5 টাকার 2টি পয়সা আছে। মোট কত টাকা?", ["10 টাকা", "7 টাকা", "5 টাকা", "25 টাকা"],
        "5 + 5 = 10 টাকা।"),
    mcq("Which is taller: a 3-storey house or a 10-storey building?", ["The 10-storey building", "The 3-storey house", "Same height", "Houses have no height"], 0,
        "10 floors stacked up are much taller than 3 floors.",
        "কোনটা বেশি উঁচু: 3 তলা বাড়ি নাকি 10 তলা ভবন?", ["10 তলা ভবন", "3 তলা বাড়ি", "উচ্চতা সমান", "বাড়ির উচ্চতা হয় না"],
        "10টি তলা উপর-উপর সাজালে 3 তলার চেয়ে অনেক উঁচু হয়।"),
    mcq("A bridge is 20 steps long. You have walked 12 steps. How many steps are left?", ["8", "12", "32", "10"], 0,
        "20 - 12 = 8 steps to the other side.",
        "একটি সেতু 20 পা লম্বা। তুমি 12 পা হেঁটেছ। আর কয় পা বাকি?", ["8", "12", "32", "10"],
        "20 - 12 = 8 পা হাঁটলে ওপারে পৌঁছাবে।"),
    mcq("What time is it when the long hand points at 12 and the short hand at 3?", ["3 o'clock", "12 o'clock", "6 o'clock", "9 o'clock"], 0,
        "The short hand shows the hour (3). The long hand at 12 means exactly 'o'clock'.",
        "বড় কাঁটা 12-এ আর ছোট কাঁটা 3-এ থাকলে কটা বাজে?", ["3টা", "12টা", "6টা", "9টা"],
        "ছোট কাঁটা ঘণ্টা দেখায় (3)। বড় কাঁটা 12-এ মানে ঠিক ঘণ্টা পূর্ণ।"),
    mcq("Which number is even?", ["8", "7", "3", "5"], 0,
        "Even numbers can be shared into 2 equal groups: 8 = 4 + 4.",
        "কোন সংখ্যাটি জোড়?", ["8", "7", "3", "5"],
        "জোড় সংখ্যা সমান 2 দলে ভাগ করা যায়: 8 = 4 + 4।"),
    mcq("Which number is odd?", ["9", "4", "10", "6"], 0,
        "9 cannot be split into 2 equal groups - one is always left over. That makes it odd.",
        "কোন সংখ্যাটি বিজোড়?", ["9", "4", "10", "6"],
        "9-কে সমান 2 দলে ভাগ করা যায় না - একটা সবসময় বাড়তি থাকে। তাই এটা বিজোড়।"),
    mcq("A truss bridge has 4 triangles. Each triangle has 3 sides. If no sides are shared, how many sides?", ["12", "7", "4", "10"], 0,
        "4 groups of 3: 3 + 3 + 3 + 3 = 12. (Real bridges share sides, so they need fewer beams!)",
        "একটি ট্রাস সেতুতে 4টি ত্রিভুজ। প্রতিটির 3টি বাহু। কোনো বাহু ভাগ না হলে মোট কয়টি বাহু?", ["12", "7", "4", "10"],
        "3 করে 4 দল: 3 + 3 + 3 + 3 = 12। (আসল সেতুতে বাহু ভাগাভাগি হয়, তাই কম বিম লাগে!)"),
    mcq("Count by tens: 10, 20, 30, ... What comes after 50?", ["60", "51", "55", "70"], 0,
        "Counting in tens: 50 + 10 = 60.",
        "দশ দশ করে গোনো: 10, 20, 30, ... 50-এর পরে কী?", ["60", "51", "55", "70"],
        "দশ দশ করে: 50 + 10 = 60।"),
    mcq("Which is more: 2 tens or 15 ones?", ["2 tens (20)", "15 ones", "They are equal", "Neither"], 0,
        "2 tens is 20, which is more than 15.",
        "কোনটা বেশি: 2টি দশ নাকি 15টি এক?", ["2টি দশ (20)", "15টি এক", "দুটো সমান", "কোনোটাই না"],
        "2টি দশ মানে 20, যা 15-এর চেয়ে বেশি।"),
    mcq("A worker carries 2 bags each trip. How many bags after 5 trips?", ["10", "7", "5", "12"], 0,
        "2 + 2 + 2 + 2 + 2 = 10 bags.",
        "একজন শ্রমিক প্রতি বারে 2টি বস্তা বয়। 5 বারে কয়টি বস্তা?", ["10", "7", "5", "12"],
        "2 + 2 + 2 + 2 + 2 = 10টি বস্তা।"),
    mcq("Which shape has 3 corners?", ["Triangle", "Square", "Circle", "Rectangle"], 0,
        "A triangle has 3 corners and 3 sides.",
        "কোন আকারের 3টি কোণ?", ["ত্রিভুজ", "বর্গ", "বৃত্ত", "আয়তক্ষেত্র"],
        "ত্রিভুজের 3টি কোণ আর 3টি বাহু।"),
    mcq("A door is usually which shape?", ["Rectangle", "Circle", "Triangle", "Star"], 0,
        "Most doors are rectangles: 4 sides, 4 square corners, taller than they are wide.",
        "দরজা সাধারণত কোন আকারের?", ["আয়তক্ষেত্র", "বৃত্ত", "ত্রিভুজ", "তারা"],
        "বেশিরভাগ দরজা আয়তক্ষেত্র: 4টি বাহু, 4টি সমকোণ, চওড়ার চেয়ে লম্বা বেশি।"),
    mcq("You measure a table with your hand: 6 hands long. Your dad measures: 4 hands. Why different?", ["Dad's hands are bigger", "The table shrank", "Dad cannot count", "Tables change size"], 0,
        "Bigger hands fit fewer times. That is why we use a ruler with the same units for everyone.",
        "তুমি হাত দিয়ে টেবিল মাপলে: 6 হাত। বাবা মাপলেন: 4 হাত। আলাদা কেন?", ["বাবার হাত বড়", "টেবিল ছোট হয়ে গেছে", "বাবা গুনতে পারেন না", "টেবিলের মাপ বদলায়"],
        "বড় হাত কম বার আঁটে। এজন্যই আমরা সবার জন্য একই এককের স্কেল ব্যবহার করি।"),
    mcq("Which is the best tool to measure how long a pencil is?", ["A ruler", "A clock", "A cup", "A scale for weighing"], 0,
        "A ruler measures length in centimetres. Clocks measure time; scales measure weight.",
        "একটি পেনসিল কতটা লম্বা মাপতে সবচেয়ে ভালো যন্ত্র কোনটা?", ["স্কেল (রুলার)", "ঘড়ি", "কাপ", "ওজন মাপার দাঁড়িপাল্লা"],
        "রুলার সেন্টিমিটারে দৈর্ঘ্য মাপে। ঘড়ি সময় মাপে; দাঁড়িপাল্লা ওজন মাপে।"),
    mcq("Which holds more water: a bucket or a cup?", ["A bucket", "A cup", "Both the same", "Neither holds water"], 0,
        "A bucket has a much bigger capacity than a cup.",
        "কোনটায় বেশি জল ধরে: বালতি নাকি কাপ?", ["বালতি", "কাপ", "দুটোতেই সমান", "কোনোটাতেই জল ধরে না"],
        "বালতির ধারণক্ষমতা কাপের চেয়ে অনেক বেশি।"),
    mcq("There are 4 seats in each row of a small bus, and 3 rows. How many seats?", ["12", "7", "10", "16"], 0,
        "3 rows of 4: 4 + 4 + 4 = 12 seats.",
        "একটি ছোট বাসের প্রতি সারিতে 4টি আসন, মোট 3টি সারি। কয়টি আসন?", ["12", "7", "10", "16"],
        "4 করে 3 সারি: 4 + 4 + 4 = 12টি আসন।"),
    mcq("How many wheels do 3 bicycles have?", ["6", "3", "9", "4"], 0,
        "Each bicycle has 2 wheels: 2 + 2 + 2 = 6.",
        "3টি সাইকেলের কয়টি চাকা?", ["6", "3", "9", "4"],
        "প্রতিটি সাইকেলের 2টি চাকা: 2 + 2 + 2 = 6।"),
    mcq("You have 10 marbles and give 5 to a friend. Now you both have...", ["The same - 5 each", "You have more", "Your friend has more", "Nobody has any"], 0,
        "10 - 5 = 5, and your friend has 5. Fair and equal!",
        "তোমার 10টি মার্বেল, তুমি বন্ধুকে 5টি দিলে। এখন তোমাদের দুজনের...", ["সমান - 5টি করে", "তোমার বেশি", "বন্ধুর বেশি", "কারো নেই"],
        "10 - 5 = 5, আর বন্ধুরও 5টি। ন্যায্য আর সমান!"),
    mcq("A builder needs 9 planks but has only 6. How many more does he need?", ["3", "15", "6", "2"], 0,
        "6 + 3 = 9, so 3 more planks are needed.",
        "এক মিস্ত্রির 9টি তক্তা দরকার, কিন্তু আছে মাত্র 6টি। আর কয়টি লাগবে?", ["3", "15", "6", "2"],
        "6 + 3 = 9, তাই আরও 3টি তক্তা লাগবে।"),
    mcq("Which shape can roll down a ramp?", ["A ball (sphere)", "A cube", "A pyramid", "A book"], 0,
        "A sphere is round all over, so it rolls. A cube's flat faces make it slide or stop.",
        "কোন আকার ঢাল বেয়ে গড়াতে পারে?", ["বল (গোলক)", "ঘনক", "পিরামিড", "বই"],
        "গোলক সব দিকে গোল, তাই গড়ায়। ঘনকের সমতল তল তাকে পিছলে দেয় বা থামিয়ে দেয়।"),
    mcq("What shape is a dice (a cube) face?", ["Square", "Circle", "Triangle", "Oval"], 0,
        "A cube has 6 faces and each face is a square.",
        "একটি লুডোর ছক্কার (ঘনক) প্রতিটি তল কোন আকারের?", ["বর্গ", "বৃত্ত", "ত্রিভুজ", "ডিম্বাকার"],
        "ঘনকের 6টি তল, আর প্রতিটি তল বর্গাকার।"),
    mcq("Which is the same as 7 + 3?", ["3 + 7", "7 - 3", "7 + 4", "10 + 3"], 0,
        "Adding works in any order: 7 + 3 = 3 + 7 = 10.",
        "কোনটা 7 + 3-এর সমান?", ["3 + 7", "7 - 3", "7 + 4", "10 + 3"],
        "যোগ যেকোনো ক্রমে করা যায়: 7 + 3 = 3 + 7 = 10।"),
    mcq("If 5 + ? = 9, what is the missing number?", ["4", "14", "5", "3"], 0,
        "5 + 4 = 9. Count up from 5 to 9: four steps.",
        "যদি 5 + ? = 9 হয়, হারানো সংখ্যাটি কী?", ["4", "14", "5", "3"],
        "5 + 4 = 9। 5 থেকে 9 পর্যন্ত গুনলে চার ধাপ।"),
    mcq("A bridge has a lamp every 2 metres. How many lamps on a 10-metre bridge, not counting the start?", ["5", "10", "2", "20"], 0,
        "Lamps at 2, 4, 6, 8 and 10 metres: 5 lamps.",
        "একটি সেতুতে প্রতি 2 মিটারে একটি বাতি। 10 মিটারের সেতুতে, শুরুর জায়গা বাদে, কয়টি বাতি?", ["5", "10", "2", "20"],
        "2, 4, 6, 8 আর 10 মিটারে বাতি: 5টি।"),
    mcq("Which is the heaviest load for a toy bridge?", ["4 big stones", "1 feather", "2 leaves", "a sheet of paper"], 0,
        "Big stones weigh much more than feathers, leaves or paper.",
        "খেলনা সেতুর জন্য কোনটা সবচেয়ে ভারী ভার?", ["4টি বড় পাথর", "1টি পালক", "2টি পাতা", "একটি কাগজ"],
        "বড় পাথরের ওজন পালক, পাতা বা কাগজের চেয়ে অনেক বেশি।"),
    mcq("You count the legs of 2 chairs. Each chair has 4. How many legs?", ["8", "6", "4", "2"], 0,
        "4 + 4 = 8 legs.",
        "তুমি 2টি চেয়ারের পা গুনলে। প্রতিটির 4টি। মোট কয়টি পা?", ["8", "6", "4", "2"],
        "4 + 4 = 8টি পা।"),
    mcq("Which is a quarter (one fourth) of 8 sweets?", ["2", "4", "8", "1"], 0,
        "Share 8 into 4 equal groups: 2 in each group.",
        "8টি মিষ্টির এক-চতুর্থাংশ কত?", ["2", "4", "8", "1"],
        "8টি সমান 4 দলে ভাগ করো: প্রতি দলে 2টি।"),
    mcq("17 is how many more than 10?", ["7", "17", "27", "10"], 0,
        "17 - 10 = 7.",
        "17, 10-এর চেয়ে কত বেশি?", ["7", "17", "27", "10"],
        "17 - 10 = 7।"),
    mcq("A crane lifts 3 beams in the morning and 3 in the afternoon. How many beams in the day?", ["6", "9", "3", "33"], 0,
        "3 + 3 = 6 beams.",
        "একটি ক্রেন সকালে 3টি আর বিকেলে 3টি বিম তুলল। সারাদিনে কয়টি বিম?", ["6", "9", "3", "33"],
        "3 + 3 = 6টি বিম।"),
    mcq("Which pair adds up to 10?", ["6 and 4", "5 and 3", "7 and 4", "2 and 9"], 0,
        "6 + 4 = 10. Number bonds to 10 are super useful!",
        "কোন জোড়ার যোগফল 10?", ["6 আর 4", "5 আর 3", "7 আর 4", "2 আর 9"],
        "6 + 4 = 10। 10-এর সংখ্যা-জোড় খুব কাজের!"),
    mcq("Which pair adds up to 20?", ["12 and 8", "10 and 5", "15 and 6", "9 and 9"], 0,
        "12 + 8 = 20.",
        "কোন জোড়ার যোগফল 20?", ["12 আর 8", "10 আর 5", "15 আর 6", "9 আর 9"],
        "12 + 8 = 20।"),
    mcq("How many corners does a rectangle have?", ["4", "3", "2", "0"], 0,
        "A rectangle has 4 corners, each a square corner (right angle).",
        "আয়তক্ষেত্রের কয়টি কোণ?", ["4", "3", "2", "0"],
        "আয়তক্ষেত্রের 4টি কোণ, প্রতিটি সমকোণ।"),
    mcq("A snail moves 2 cm each minute. How far in 4 minutes?", ["8 cm", "6 cm", "2 cm", "4 cm"], 0,
        "2 + 2 + 2 + 2 = 8 cm. Slow but steady!",
        "একটি শামুক প্রতি মিনিটে 2 cm এগোয়। 4 মিনিটে কত দূর?", ["8 cm", "6 cm", "2 cm", "4 cm"],
        "2 + 2 + 2 + 2 = 8 cm। ধীর কিন্তু অবিচল!"),
    mcq("Which number is ten more than 23?", ["33", "24", "13", "230"], 0,
        "Ten more changes the tens digit: 23 + 10 = 33.",
        "23-এর চেয়ে দশ বেশি কোন সংখ্যা?", ["33", "24", "13", "230"],
        "দশ বেশি মানে দশকের অঙ্ক বদলায়: 23 + 10 = 33।"),
    mcq("A bridge sign says the bridge can hold 10 tonnes. A truck weighs 12 tonnes. Should it cross?", ["No - it is too heavy", "Yes, easily", "Yes, if it drives fast", "Only at night"], 0,
        "12 is more than 10, so the truck is too heavy. Weight limits keep bridges safe.",
        "সেতুর বোর্ডে লেখা সেতু 10 টন ধরতে পারে। একটি ট্রাকের ওজন 12 টন। ট্রাকটি কি পার হবে?", ["না - খুব ভারী", "হ্যাঁ, সহজেই", "হ্যাঁ, জোরে চালালে", "শুধু রাতে"],
        "12, 10-এর চেয়ে বেশি, তাই ট্রাকটি খুব ভারী। ওজনসীমা সেতুকে নিরাপদ রাখে।"),
    mcq("There are 5 red cars and 3 blue cars. How many more red cars than blue?", ["2", "8", "5", "3"], 0,
        "5 - 3 = 2 more red cars.",
        "5টি লাল গাড়ি আর 3টি নীল গাড়ি আছে। নীলের চেয়ে লাল কয়টি বেশি?", ["2", "8", "5", "3"],
        "5 - 3 = 2টি লাল গাড়ি বেশি।"),
    mcq("What shape do you get if you cut a square from corner to corner?", ["Two triangles", "Two circles", "Two squares", "A star"], 0,
        "A diagonal cut splits a square into 2 triangles - just what a bridge diagonal does!",
        "একটি বর্গকে এক কোণ থেকে উল্টো কোণে কাটলে কী আকার পাও?", ["দুটি ত্রিভুজ", "দুটি বৃত্ত", "দুটি বর্গ", "একটি তারা"],
        "কর্ণ বরাবর কাটলে বর্গ 2টি ত্রিভুজে ভাগ হয় - সেতুর কর্ণ ঠিক এটাই করে!"),
    mcq("You have 3 boxes with 2 toys in each. How many toys?", ["6", "5", "3", "9"], 0,
        "2 + 2 + 2 = 6 toys.",
        "তোমার 3টি বাক্সের প্রতিটিতে 2টি খেলনা। মোট কয়টি খেলনা?", ["6", "5", "3", "9"],
        "2 + 2 + 2 = 6টি খেলনা।"),
    mcq("You save 1 rupee every day for a week. How much do you save?", ["7 rupees", "1 rupee", "10 rupees", "14 rupees"], 0,
        "A week has 7 days, so 7 x 1 = 7 rupees.",
        "তুমি এক সপ্তাহ ধরে প্রতিদিন 1 টাকা জমালে। কত জমল?", ["7 টাকা", "1 টাকা", "10 টাকা", "14 টাকা"],
        "এক সপ্তাহে 7 দিন, তাই 7 x 1 = 7 টাকা।"),
    mcq("A bridge has 2 lanes and each lane holds 5 cars in a jam. How many cars?", ["10", "7", "5", "25"], 0,
        "5 + 5 = 10 cars.",
        "একটি সেতুর 2টি লেন, যানজটে প্রতি লেনে 5টি গাড়ি। মোট কয়টি গাড়ি?", ["10", "7", "5", "25"],
        "5 + 5 = 10টি গাড়ি।"),
    mcq("What number is shown by 1 ten and 9 ones?", ["19", "91", "10", "9"], 0,
        "10 + 9 = 19.",
        "1টি দশ আর 9টি এক দিয়ে কোন সংখ্যা?", ["19", "91", "10", "9"],
        "10 + 9 = 19।"),
    mcq("Which shape has no straight sides?", ["Circle", "Triangle", "Square", "Rectangle"], 0,
        "A circle's edge curves all the way round.",
        "কোন আকারের কোনো সোজা বাহু নেই?", ["বৃত্ত", "ত্রিভুজ", "বর্গ", "আয়তক্ষেত্র"],
        "বৃত্তের কিনারা পুরোটা জুড়েই বাঁকা।"),
    mcq("A train has 1 engine and 6 wagons. How many parts in the train?", ["7", "6", "5", "16"], 0,
        "1 + 6 = 7.",
        "একটি ট্রেনে 1টি ইঞ্জিন আর 6টি ওয়াগন। ট্রেনে মোট কয়টি অংশ?", ["7", "6", "5", "16"],
        "1 + 6 = 7।"),
    mcq("Which is bigger: 1 metre or 1 centimetre?", ["1 metre", "1 centimetre", "They are the same", "Neither has a size"], 0,
        "1 metre = 100 centimetres - about one big step.",
        "কোনটা বড়: 1 মিটার নাকি 1 সেন্টিমিটার?", ["1 মিটার", "1 সেন্টিমিটার", "দুটো সমান", "কোনোটারই মাপ নেই"],
        "1 মিটার = 100 সেন্টিমিটার - প্রায় একটা বড় পা।"),
    mcq("Count the triangles in this: a square cut by both diagonals (an X).", ["4", "2", "1", "8"], 0,
        "Two diagonals crossing in a square make 4 small triangles meeting in the middle.",
        "একটি বর্গকে দুই কর্ণ দিয়ে (X আকারে) কাটলে কয়টি ছোট ত্রিভুজ হয়?", ["4", "2", "1", "8"],
        "বর্গে দুটি কর্ণ কাটাকাটি করলে মাঝখানে মেলা 4টি ছোট ত্রিভুজ হয়।"),
    mcq("A pond has 8 frogs. 3 jump out and 2 jump in. How many frogs now?", ["7", "8", "5", "13"], 0,
        "8 - 3 = 5, then 5 + 2 = 7 frogs.",
        "একটি পুকুরে 8টি ব্যাঙ। 3টি লাফিয়ে বেরিয়ে গেল আর 2টি লাফিয়ে ঢুকল। এখন কয়টি ব্যাঙ?", ["7", "8", "5", "13"],
        "8 - 3 = 5, তারপর 5 + 2 = 7টি ব্যাঙ।"),
    mcq("Which is the correct order from smallest to biggest?", ["2, 5, 9", "9, 5, 2", "5, 2, 9", "2, 9, 5"], 0,
        "Smallest first: 2, then 5, then 9.",
        "ছোট থেকে বড় সঠিক ক্রম কোনটা?", ["2, 5, 9", "9, 5, 2", "5, 2, 9", "2, 9, 5"],
        "আগে সবচেয়ে ছোট: 2, তারপর 5, তারপর 9।"),
    mcq("Sam is 6 years old. His sister is 2 years older. How old is his sister?", ["8", "4", "6", "62"], 0,
        "Older means add: 6 + 2 = 8.",
        "স্যামের বয়স 6 বছর। তার বোন 2 বছরের বড়। বোনের বয়স কত?", ["8", "4", "6", "62"],
        "বড় মানে যোগ: 6 + 2 = 8।"),
    mcq("A bridge is built in 3 equal parts, each 5 metres long. How long is the bridge?", ["15 metres", "8 metres", "5 metres", "35 metres"], 0,
        "5 + 5 + 5 = 15 metres.",
        "একটি সেতু সমান 3 অংশে বানানো, প্রতিটি 5 মিটার লম্বা। সেতুটি কত লম্বা?", ["15 মিটার", "8 মিটার", "5 মিটার", "35 মিটার"],
        "5 + 5 + 5 = 15 মিটার।"),
    mcq("Which shape is the face of a brick?", ["Rectangle", "Circle", "Triangle", "Heart"], 0,
        "Bricks are box shapes, and most of their faces are rectangles.",
        "ইটের তল কোন আকারের?", ["আয়তক্ষেত্র", "বৃত্ত", "ত্রিভুজ", "হৃদয়"],
        "ইট বাক্সের মতো, আর তার বেশিরভাগ তল আয়তক্ষেত্র।"),
    mcq("13 cars cross a bridge, then 10 more. How many cars crossed?", ["23", "3", "13", "31"], 0,
        "13 + 10 = 23. Adding 10 makes the tens digit go up by 1.",
        "13টি গাড়ি সেতু পার হলো, তারপর আরও 10টি। মোট কয়টি গাড়ি পার হলো?", ["23", "3", "13", "31"],
        "13 + 10 = 23। 10 যোগ করলে দশকের অঙ্ক 1 বাড়ে।"),
    mcq("Which number is missing? 11, 12, __, 14", ["13", "15", "10", "31"], 0,
        "Counting by ones: 11, 12, 13, 14.",
        "কোন সংখ্যাটি নেই? 11, 12, __, 14", ["13", "15", "10", "31"],
        "এক এক করে গোনা: 11, 12, 13, 14।"),
    mcq("A clever bridge uses 3 triangles that share sides and needs 7 beams. A careless one uses 9. How many beams does the clever one save?", ["2", "16", "7", "9"], 0,
        "9 - 7 = 2 beams saved. Fewer beams means less cost - the secret of a cheap, strong bridge!",
        "একটি চতুর সেতু ভাগাভাগি বাহুর 3টি ত্রিভুজে 7টি বিম ব্যবহার করে। একটি অগোছালো সেতু ব্যবহার করে 9টি। চতুরটি কয়টি বিম বাঁচায়?", ["2", "16", "7", "9"],
        "9 - 7 = 2টি বিম বাঁচে। কম বিম মানে কম খরচ - সস্তা আর মজবুত সেতুর রহস্য!"),
)
