"""Class 1 - Chemistry: materials and what they are like, mixing, melting, drying and rust."""
from . import mcq

ITEMS = (
    mcq("What happens when you leave your iron toy shovel out in the rain all week?",
        ["It turns reddish-brown and crusty - rust", "It turns into gold", "It grows bigger", "It becomes a plant"], 0,
        "Iron plus water plus air makes rust. That is why steel bridges are painted - to keep the rain off.",
        "লোহার খেলনা বেলচা পুরো সপ্তাহ বৃষ্টিতে বাইরে রেখে দিলে কী হয়?",
        ["লালচে-বাদামি খসখসে হয়ে যায় - মরচে", "সোনা হয়ে যায়", "আরও বড় হয়", "গাছ হয়ে যায়"],
        "লোহা, জল আর বাতাস মিলে মরচে হয়। এজন্যই ইস্পাতের সেতু রং করা হয় - বৃষ্টি থেকে বাঁচাতে।"),
    mcq("You stir a spoon of sugar into water. Where does the sugar go?",
        ["It dissolves and spreads through the water", "It flies away", "It turns into stones", "It sinks and stays a lump forever"], 0,
        "Sugar dissolves: it breaks into tiny bits you cannot see. Taste the water - it is sweet!",
        "জলে এক চামচ চিনি নেড়ে দিলে চিনি কোথায় যায়?",
        ["গলে জলের মধ্যে ছড়িয়ে পড়ে", "উড়ে যায়", "পাথর হয়ে যায়", "তলায় চিরকাল দলা হয়ে থাকে"],
        "চিনি দ্রবীভূত হয়: এমন ছোট ছোট কণায় ভাঙে যা দেখা যায় না। জলটা চেখে দেখো - মিষ্টি!"),
    mcq("Sand mixed in water and left alone for a while...",
        ["Settles at the bottom", "Disappears", "Becomes sugar", "Floats to the top"], 0,
        "Sand does not dissolve. It is heavier than water, so it sinks to the bottom.",
        "জলে বালি মিশিয়ে কিছুক্ষণ রেখে দিলে...",
        ["তলায় থিতিয়ে পড়ে", "উধাও হয়ে যায়", "চিনি হয়ে যায়", "উপরে ভেসে ওঠে"],
        "বালি দ্রবীভূত হয় না। এটা জলের চেয়ে ভারী, তাই তলায় ডুবে যায়।"),
    mcq("Which of these is made of wood?",
        ["A pencil", "A spoon made of steel", "A glass bottle", "A plastic bucket"], 0,
        "Most pencils are made of wood from trees, with graphite in the middle for writing.",
        "এগুলোর মধ্যে কোনটা কাঠের তৈরি?",
        ["পেনসিল", "ইস্পাতের চামচ", "কাচের বোতল", "প্লাস্টিকের বালতি"],
        "বেশিরভাগ পেনসিল গাছের কাঠে তৈরি, মাঝে লেখার জন্য গ্রাফাইট থাকে।"),
    mcq("Ice is left on a plate in a warm room. It becomes...",
        ["Water", "Sand", "Smoke", "Bigger ice"], 0,
        "Warmth melts ice into water. Ice and water are the same stuff, just solid and liquid.",
        "গরম ঘরে প্লেটে বরফ রেখে দিলে সেটা হয়ে যায়...",
        ["জল", "বালি", "ধোঁয়া", "আরও বড় বরফ"],
        "উষ্ণতায় বরফ গলে জল হয়। বরফ আর জল একই জিনিস, শুধু একটা কঠিন আর একটা তরল।"),
    mcq("Water put in the freezer becomes...",
        ["Ice", "Juice", "Steam", "Air"], 0,
        "Very cold makes water freeze into solid ice.",
        "ফ্রিজারে জল রাখলে তা হয়ে যায়...",
        ["বরফ", "রস", "বাষ্প", "বাতাস"],
        "খুব ঠান্ডায় জল জমে কঠিন বরফ হয়।"),
    mcq("A kettle of water boils. What comes out of the spout?",
        ["Steam - water as a gas", "Smoke from fire", "Ice", "Milk"], 0,
        "Boiling turns water into a gas called steam. Careful - it is very hot!",
        "কেটলির জল ফুটছে। নল দিয়ে কী বেরোয়?",
        ["বাষ্প - গ্যাস অবস্থার জল", "আগুনের ধোঁয়া", "বরফ", "দুধ"],
        "ফোটালে জল বাষ্প নামের গ্যাসে বদলায়। সাবধান - খুব গরম!"),
    mcq("Which material is hard?",
        ["A stone", "A pillow", "A sponge", "Cotton wool"], 0,
        "Stone is hard: you cannot easily press or scratch it. That is why old bridges were built of stone.",
        "কোন উপাদান শক্ত?",
        ["পাথর", "বালিশ", "স্পঞ্জ", "তুলো"],
        "পাথর শক্ত: সহজে চাপা বা আঁচড় কাটা যায় না। এজন্যই পুরোনো সেতু পাথরে বানানো হতো।"),
    mcq("Which material is soft and squashy?",
        ["A sponge", "A brick", "A steel rod", "A marble"], 0,
        "A sponge squashes when you press it and springs back.",
        "কোন উপাদান নরম আর চাপলে বসে যায়?",
        ["স্পঞ্জ", "ইট", "ইস্পাতের রড", "মার্বেল"],
        "স্পঞ্জ চাপলে বসে যায় আর আবার ফিরে আসে।"),
    mcq("Which material can you see through?",
        ["Clear glass", "Wood", "Cardboard", "Brick"], 0,
        "Clear glass is transparent - light goes straight through, so you can see the other side.",
        "কোন উপাদানের মধ্য দিয়ে দেখা যায়?",
        ["স্বচ্ছ কাচ", "কাঠ", "কার্ডবোর্ড", "ইট"],
        "স্বচ্ছ কাচের মধ্য দিয়ে আলো সোজা যায়, তাই ওপাশটা দেখা যায়।"),
    mcq("Which one is shiny?",
        ["A new steel spoon", "A lump of mud", "A woolly sock", "A piece of bread"], 0,
        "Metals like steel are shiny because their smooth surface bounces light well.",
        "কোনটা চকচকে?",
        ["নতুন ইস্পাতের চামচ", "কাদার দলা", "উলের মোজা", "এক টুকরো পাউরুটি"],
        "ইস্পাতের মতো ধাতু চকচকে, কারণ তার মসৃণ তল আলো ভালোভাবে ফিরিয়ে দেয়।"),
    mcq("Mud is a mix of...",
        ["Soil and water", "Sugar and milk", "Glass and air", "Steel and oil"], 0,
        "Add water to soil and you get sticky, squishy mud.",
        "কাদা কী কী মিশে তৈরি?",
        ["মাটি আর জল", "চিনি আর দুধ", "কাচ আর বাতাস", "ইস্পাত আর তেল"],
        "মাটিতে জল মেশালে আঠালো, নরম কাদা হয়।"),
    mcq("Wet mud left in the hot sun becomes...",
        ["Hard and cracked", "A river", "Softer every hour", "Chocolate"], 0,
        "The sun dries out the water, and the dry mud shrinks and cracks.",
        "ভেজা কাদা কড়া রোদে রেখে দিলে হয়ে যায়...",
        ["শক্ত আর ফাটা", "নদী", "প্রতি ঘণ্টায় আরও নরম", "চকলেট"],
        "রোদ জল শুকিয়ে দেয়, আর শুকনো কাদা কুঁচকে ফেটে যায়।"),
    mcq("Why do builders bake clay bricks in a hot oven (kiln)?",
        ["To make them hard and strong", "To make them smell nice", "To make them soft", "To make them float"], 0,
        "Baking changes clay so it becomes hard and does not melt back into mud in the rain.",
        "নির্মাতারা মাটির ইট গরম চুল্লিতে (ভাটায়) পোড়ান কেন?",
        ["শক্ত আর মজবুত করতে", "সুগন্ধ করতে", "নরম করতে", "ভাসাতে"],
        "পোড়ালে মাটি বদলে শক্ত হয়ে যায়, আর বৃষ্টিতে আবার কাদা হয়ে গলে না।"),
    mcq("Which material comes from trees?",
        ["Paper", "Glass", "Steel", "Plastic"], 0,
        "Paper is made from wood pulp, which comes from trees. Recycle paper to save trees!",
        "কোন উপাদান গাছ থেকে আসে?",
        ["কাগজ", "কাচ", "ইস্পাত", "প্লাস্টিক"],
        "কাগজ তৈরি হয় কাঠের মণ্ড থেকে, যা গাছ থেকে আসে। গাছ বাঁচাতে কাগজ পুনর্ব্যবহার করো!"),
    mcq("Which is a liquid?",
        ["Milk", "A stone", "A spoon", "A book"], 0,
        "Liquids flow and take the shape of their container - like milk in a glass.",
        "কোনটা তরল?",
        ["দুধ", "পাথর", "চামচ", "বই"],
        "তরল বয়ে যায় আর পাত্রের আকার নেয় - যেমন গ্লাসে দুধ।"),
    mcq("Which is a solid?",
        ["A wooden block", "Juice", "Steam", "Water"], 0,
        "Solids keep their own shape. A wooden block stays a block wherever you put it.",
        "কোনটা কঠিন?",
        ["কাঠের ব্লক", "রস", "বাষ্প", "জল"],
        "কঠিন জিনিস নিজের আকার রাখে। কাঠের ব্লক যেখানেই রাখো, ব্লকই থাকে।"),
    mcq("What is in a blown-up balloon?",
        ["Air - a gas", "Water", "Sand", "Nothing at all"], 0,
        "Air is a gas. You cannot see it, but it fills the balloon and pushes it out.",
        "ফোলানো বেলুনের ভেতরে কী থাকে?",
        ["বাতাস - একটা গ্যাস", "জল", "বালি", "কিছুই না"],
        "বাতাস একটা গ্যাস। দেখা যায় না, কিন্তু বেলুন ভরে বাইরের দিকে ঠেলে।"),
    mcq("Chocolate in a warm hand becomes...",
        ["Soft and melty", "Harder", "Frozen", "A stone"], 0,
        "Your warm hand melts the chocolate. Many solids melt when they get warm.",
        "গরম হাতে চকলেট হয়ে যায়...",
        ["নরম আর গলা গলা", "আরও শক্ত", "জমাট বরফ", "পাথর"],
        "তোমার গরম হাত চকলেট গলিয়ে দেয়। অনেক কঠিন জিনিস গরমে গলে যায়।"),
    mcq("Why do we use soap to wash hands?",
        ["Soap helps lift dirt and germs off", "Soap makes hands bigger", "Soap is a food", "Soap makes water cold"], 0,
        "Soap grabs grease and dirt so water can wash them away.",
        "হাত ধুতে সাবান ব্যবহার করি কেন?",
        ["সাবান ময়লা আর জীবাণু তুলে দেয়", "সাবান হাত বড় করে", "সাবান খাবার", "সাবান জল ঠান্ডা করে"],
        "সাবান তেল-ময়লা আঁকড়ে ধরে, যাতে জল তা ধুয়ে নিতে পারে।"),
    mcq("Oil and water poured in one glass...",
        ["Do not mix - oil floats on top", "Mix into one", "Turn into milk", "Both disappear"], 0,
        "Oil does not mix with water. It is lighter, so it floats as a layer on top.",
        "একটি গ্লাসে তেল আর জল ঢাললে...",
        ["মেশে না - তেল উপরে ভাসে", "মিশে এক হয়ে যায়", "দুধ হয়ে যায়", "দুটোই উধাও হয়"],
        "তেল জলের সঙ্গে মেশে না। এটা হালকা, তাই উপরে স্তর হয়ে ভাসে।"),
    mcq("Which material is a metal?",
        ["Iron", "Wood", "Rubber", "Wool"], 0,
        "Iron is a metal: hard, strong, shiny when new and pulled by magnets.",
        "কোন উপাদান ধাতু?",
        ["লোহা", "কাঠ", "রাবার", "উল"],
        "লোহা একটা ধাতু: শক্ত, মজবুত, নতুন অবস্থায় চকচকে, আর চুম্বক একে টানে।"),
    mcq("Why are raincoats made of plastic and not paper?",
        ["Plastic keeps water out; paper gets soggy", "Paper is too strong", "Plastic is tastier", "Paper is too shiny"], 0,
        "Plastic is waterproof. Paper soaks up water and tears.",
        "রেইনকোট কাগজের না হয়ে প্লাস্টিকের হয় কেন?",
        ["প্লাস্টিক জল আটকায়; কাগজ ভিজে নেতিয়ে যায়", "কাগজ খুব শক্ত", "প্লাস্টিক বেশি সুস্বাদু", "কাগজ খুব চকচকে"],
        "প্লাস্টিক জলরোধী। কাগজ জল শুষে ছিঁড়ে যায়।"),
    mcq("Salt stirred into warm water...",
        ["Dissolves - the water tastes salty", "Turns into ice", "Floats as a lump", "Becomes sand"], 0,
        "Salt dissolves just like sugar. Sea water is salty because salt is dissolved in it.",
        "গরম জলে নুন নেড়ে দিলে...",
        ["গলে যায় - জলের স্বাদ নোনতা হয়", "বরফ হয়ে যায়", "দলা হয়ে ভাসে", "বালি হয়ে যায়"],
        "নুন চিনির মতোই দ্রবীভূত হয়। সাগরের জল নোনতা কারণ তাতে নুন গলে আছে।"),
    mcq("What does cement do when it is mixed with water and left to dry?",
        ["It sets hard like stone", "It turns into water", "It floats away", "It stays runny forever"], 0,
        "Cement reacts with water and hardens. Builders use it to glue bricks and make concrete.",
        "সিমেন্ট জলে মিশিয়ে শুকোতে দিলে কী করে?",
        ["পাথরের মতো শক্ত হয়ে জমে", "জল হয়ে যায়", "ভেসে চলে যায়", "চিরকাল পাতলা থাকে"],
        "সিমেন্ট জলের সঙ্গে বিক্রিয়া করে শক্ত হয়। নির্মাতারা ইট জোড়া আর কংক্রিট বানাতে এটা ব্যবহার করেন।"),
    mcq("Which material is stretchy?",
        ["Rubber", "Glass", "Stone", "Chalk"], 0,
        "Rubber stretches and springs back. Glass, stone and chalk break instead.",
        "কোন উপাদান টানলে লম্বা হয়?",
        ["রাবার", "কাচ", "পাথর", "চক"],
        "রাবার টানলে লম্বা হয় আর আবার ফিরে আসে। কাচ, পাথর আর চক তার বদলে ভাঙে।"),
    mcq("A cut apple left out turns brown. What changed it?",
        ["Air reacting with the apple", "The apple got sleepy", "Light painted it", "It got colder"], 0,
        "Air reacts with the cut apple and turns it brown - a tiny chemical change.",
        "কাটা আপেল বাইরে রেখে দিলে বাদামি হয়ে যায়। কী তাকে বদলায়?",
        ["বাতাস আপেলের সঙ্গে বিক্রিয়া করে", "আপেলের ঘুম পেয়েছে", "আলো রং করেছে", "ঠান্ডা হয়েছে"],
        "বাতাস কাটা আপেলের সঙ্গে বিক্রিয়া করে বাদামি করে দেয় - একটা ছোট্ট রাসায়নিক পরিবর্তন।"),
    mcq("Which of these can you mould into a shape with your hands?",
        ["Clay", "A steel bar", "A glass", "A stone"], 0,
        "Soft clay can be squeezed and shaped. When dried or baked, it keeps that shape.",
        "এগুলোর মধ্যে কোনটা হাত দিয়ে আকার দেওয়া যায়?",
        ["মাটি (কাদামাটি)", "ইস্পাতের দণ্ড", "কাচ", "পাথর"],
        "নরম কাদামাটি চেপে আকার দেওয়া যায়। শুকোলে বা পোড়ালে সেই আকার রাখে।"),
    mcq("Why do we keep matches away from children?",
        ["They can start fires that burn", "They are too cold", "They make water", "They are sticky"], 0,
        "Burning is a chemical change that gives heat and flames. It must only be done by grown-ups, carefully.",
        "দেশলাই শিশুদের থেকে দূরে রাখি কেন?",
        ["আগুন লাগিয়ে পুড়িয়ে দিতে পারে", "খুব ঠান্ডা", "জল তৈরি করে", "আঠালো"],
        "পোড়া একটা রাসায়নিক পরিবর্তন, যাতে তাপ আর শিখা হয়। শুধু বড়রাই সাবধানে এটা করবেন।"),
    mcq("Wet clothes on a sunny line become dry. Where did the water go?",
        ["Into the air as water vapour", "Into the ground through the clothes peg", "It turned into cloth", "Back into the tap"], 0,
        "The sun warms the water and it evaporates - it turns into invisible vapour in the air.",
        "রোদে দড়িতে ভেজা কাপড় শুকিয়ে যায়। জল কোথায় গেল?",
        ["জলীয় বাষ্প হয়ে বাতাসে", "ক্লিপ দিয়ে মাটিতে", "কাপড় হয়ে গেল", "আবার কলে ফিরে গেল"],
        "সূর্য জল গরম করে আর তা বাষ্পীভূত হয় - বাতাসে অদৃশ্য বাষ্প হয়ে যায়।"),
    mcq("Which material is best for a cooking pot that goes on a stove?",
        ["Metal", "Paper", "Plastic bag", "Wax"], 0,
        "Metal does not burn or melt on a stove and passes heat to the food.",
        "চুলার উপর বসানো রান্নার হাঁড়ির জন্য কোন উপাদান সবচেয়ে ভালো?",
        ["ধাতু", "কাগজ", "প্লাস্টিকের ব্যাগ", "মোম"],
        "ধাতু চুলায় পোড়ে না বা গলে না, আর খাবারে তাপ পৌঁছে দেয়।"),
    mcq("A candle burns. What happens to the wax?",
        ["It melts and slowly gets used up", "It grows taller", "It turns into ice", "Nothing"], 0,
        "The flame melts the wax and burns it, so the candle gets shorter.",
        "মোমবাতি জ্বলছে। মোমের কী হয়?",
        ["গলে ধীরে ধীরে ফুরিয়ে যায়", "আরও লম্বা হয়", "বরফ হয়ে যায়", "কিছুই না"],
        "শিখা মোম গলিয়ে পোড়ায়, তাই মোমবাতি ছোট হয়ে আসে।"),
    mcq("Why do we paint iron gates?",
        ["To stop them rusting", "To make them heavier", "To make them softer", "To make them grow"], 0,
        "Paint keeps water and air away from the iron, so rust cannot start.",
        "লোহার গেট রং করি কেন?",
        ["মরচে ধরা ঠেকাতে", "ভারী করতে", "নরম করতে", "বড় করতে"],
        "রং লোহা থেকে জল আর বাতাস দূরে রাখে, তাই মরচে শুরু হতে পারে না।"),
    mcq("Which of these melts in the sun first?",
        ["An ice lolly", "A rock", "A spoon", "A brick"], 0,
        "Ice melts at a low temperature. Rocks, spoons and bricks need far more heat.",
        "রোদে কোনটা আগে গলবে?",
        ["আইসক্রিমের কাঠি (আইস ললি)", "পাথর", "চামচ", "ইট"],
        "বরফ কম তাপমাত্রায় গলে। পাথর, চামচ আর ইটে অনেক বেশি তাপ লাগে।"),
    mcq("What do you get when you mix blue and yellow paint?",
        ["Green", "Red", "Black", "Pink"], 0,
        "Mixing colours makes new colours. Blue and yellow make green.",
        "নীল আর হলুদ রং মেশালে কী পাও?",
        ["সবুজ", "লাল", "কালো", "গোলাপি"],
        "রং মেশালে নতুন রং হয়। নীল আর হলুদে সবুজ হয়।"),
    mcq("Which material is waterproof?",
        ["A rubber boot", "A cotton towel", "Tissue paper", "A sponge"], 0,
        "Rubber does not let water through, so your feet stay dry.",
        "কোন উপাদান জলরোধী?",
        ["রাবারের বুট", "সুতির তোয়ালে", "টিস্যু পেপার", "স্পঞ্জ"],
        "রাবার জল ঢুকতে দেয় না, তাই পা শুকনো থাকে।"),
    mcq("Which material soaks up water?",
        ["A towel", "A plastic plate", "A glass", "A steel bowl"], 0,
        "Towels are absorbent: they have tiny spaces that suck up water.",
        "কোন উপাদান জল শুষে নেয়?",
        ["তোয়ালে", "প্লাস্টিকের প্লেট", "কাচ", "ইস্পাতের বাটি"],
        "তোয়ালে শোষক: তার ছোট ছোট ফাঁক জল টেনে নেয়।"),
    mcq("Where does rain water come from?",
        ["Clouds made of tiny water drops", "Taps in the sky", "The moon", "Trees spraying water"], 0,
        "Clouds are made of tiny drops of water. When drops join and get heavy, they fall as rain.",
        "বৃষ্টির জল কোথা থেকে আসে?",
        ["ছোট ছোট জলকণায় তৈরি মেঘ থেকে", "আকাশের কল থেকে", "চাঁদ থেকে", "গাছের জল ছিটানো থেকে"],
        "মেঘ ছোট ছোট জলকণায় তৈরি। কণাগুলো জুড়ে ভারী হলে বৃষ্টি হয়ে পড়ে।"),
    mcq("Why do we put food in the fridge?",
        ["Cold keeps food fresh longer", "To make it heavier", "To make it hot", "To make it colourful"], 0,
        "Cold slows down the changes that make food go bad.",
        "খাবার ফ্রিজে রাখি কেন?",
        ["ঠান্ডায় খাবার বেশিদিন টাটকা থাকে", "ভারী করতে", "গরম করতে", "রঙিন করতে"],
        "ঠান্ডা সেইসব পরিবর্তন ধীর করে, যা খাবার নষ্ট করে।"),
    mcq("Bread put in a toaster comes out...",
        ["Brown and crunchy", "Frozen", "Wet", "As flour again"], 0,
        "Heat changes the bread - it browns and becomes crunchy. You cannot turn toast back into bread!",
        "টোস্টারে পাউরুটি দিলে বেরিয়ে আসে...",
        ["বাদামি আর মুচমুচে হয়ে", "জমাট হয়ে", "ভেজা হয়ে", "আবার আটা হয়ে"],
        "তাপ পাউরুটিকে বদলে দেয় - বাদামি আর মুচমুচে হয়। টোস্টকে আর পাউরুটিতে ফেরানো যায় না!"),
    mcq("Which change can be undone?",
        ["Ice melting into water (freeze it again)", "Toast burning", "Paper burning", "An egg being boiled"], 0,
        "Melted ice can be frozen again. Burning and cooking make new stuff that cannot go back.",
        "কোন পরিবর্তন আবার ফিরিয়ে আনা যায়?",
        ["বরফ গলে জল হওয়া (আবার জমাও)", "টোস্ট পুড়ে যাওয়া", "কাগজ পুড়ে যাওয়া", "ডিম সেদ্ধ হওয়া"],
        "গলা বরফ আবার জমানো যায়। পোড়া আর রান্না নতুন জিনিস তৈরি করে, যা আর ফেরে না।"),
    mcq("Glue is put between two pieces of paper. When it dries, it...",
        ["Holds them together", "Pushes them apart", "Turns into water", "Makes them float"], 0,
        "Glue dries and sticks things together. Builders use cement and mortar to glue bricks.",
        "দুটি কাগজের মাঝে আঠা লাগানো হলো। শুকোলে সেটা...",
        ["দুটিকে জুড়ে রাখে", "দূরে ঠেলে দেয়", "জল হয়ে যায়", "ভাসিয়ে দেয়"],
        "আঠা শুকিয়ে জিনিস জুড়ে দেয়। নির্মাতারা ইট জুড়তে সিমেন্ট আর মশলা ব্যবহার করেন।"),
    mcq("Which material breaks easily if dropped?",
        ["Glass", "Rubber ball", "Woollen hat", "Plastic toy duck"], 0,
        "Glass is brittle: it does not bend - it shatters.",
        "কোন উপাদান পড়ে গেলে সহজে ভাঙে?",
        ["কাচ", "রাবারের বল", "উলের টুপি", "প্লাস্টিকের খেলনা হাঁস"],
        "কাচ ভঙ্গুর: বাঁকে না - টুকরো টুকরো হয়ে যায়।"),
    mcq("Why are bridges often made of steel and concrete, not wood alone?",
        ["Steel and concrete are much stronger and last longer", "Wood is too heavy", "Steel is softer", "Concrete floats"], 0,
        "Steel and concrete carry big loads and last for many years. Wood is great too, but for smaller bridges.",
        "সেতু প্রায়ই শুধু কাঠের না হয়ে ইস্পাত আর কংক্রিটের হয় কেন?",
        ["ইস্পাত আর কংক্রিট অনেক বেশি শক্ত আর টেকসই", "কাঠ খুব ভারী", "ইস্পাত বেশি নরম", "কংক্রিট ভাসে"],
        "ইস্পাত আর কংক্রিট বড় ভার বয় আর বহু বছর টেকে। কাঠও দারুণ, তবে ছোট সেতুর জন্য।"),
    mcq("What is concrete made from?",
        ["Cement, sand, stones and water", "Sugar and flour", "Wool and cotton", "Glass and plastic"], 0,
        "Mix cement, sand, gravel and water and it sets into hard concrete.",
        "কংক্রিট কী দিয়ে তৈরি?",
        ["সিমেন্ট, বালি, পাথরকুচি আর জল", "চিনি আর আটা", "উল আর তুলো", "কাচ আর প্লাস্টিক"],
        "সিমেন্ট, বালি, পাথরকুচি আর জল মেশালে তা জমে শক্ত কংক্রিট হয়।"),
    mcq("A puddle of water freezes on a very cold night. In the morning it is...",
        ["Slippery ice", "Hot water", "Sand", "Steam"], 0,
        "Freezing turns liquid water into solid ice - watch your step!",
        "খুব ঠান্ডা রাতে জলের ডোবা জমে যায়। সকালে সেটা...",
        ["পিছল বরফ", "গরম জল", "বালি", "বাষ্প"],
        "জমে গেলে তরল জল কঠিন বরফ হয় - সাবধানে পা ফেলো!"),
    mcq("Which smells when it goes bad?",
        ["Old milk", "A metal spoon", "A glass marble", "A stone"], 0,
        "Tiny living things grow in old milk and change it, making a sour smell.",
        "কোনটা নষ্ট হলে গন্ধ ছাড়ে?",
        ["পুরোনো দুধ", "ধাতুর চামচ", "কাচের মার্বেল", "পাথর"],
        "পুরোনো দুধে ছোট্ট জীবাণু বাড়ে আর তাকে বদলে দেয়, তাতে টক গন্ধ হয়।"),
    mcq("Why is a metal slide hot on a sunny afternoon?",
        ["Metal heats up quickly in the sun", "Metal makes its own fire", "Slides are electric", "Children rubbed it"], 0,
        "Metal soaks up the sun's heat and passes it to your skin quickly - test it before sliding!",
        "রোদের বিকেলে ধাতুর স্লাইড গরম থাকে কেন?",
        ["ধাতু রোদে দ্রুত গরম হয়", "ধাতু নিজে আগুন তৈরি করে", "স্লাইড বৈদ্যুতিক", "বাচ্চারা ঘষেছে"],
        "ধাতু সূর্যের তাপ শুষে নেয় আর দ্রুত তোমার ত্বকে পৌঁছে দেয় - নামার আগে ছুঁয়ে দেখো!"),
    mcq("Which material is light enough to float in water?",
        ["Cork", "Iron", "Stone", "Glass marble"], 0,
        "Cork is full of tiny air pockets, so it is very light and floats.",
        "কোন উপাদান এত হালকা যে জলে ভাসে?",
        ["কর্ক (ছিপি)", "লোহা", "পাথর", "কাচের মার্বেল"],
        "কর্কে ছোট ছোট বাতাসের থলি ভরা, তাই খুব হালকা আর ভাসে।"),
    mcq("Why do we recycle cans and bottles?",
        ["To use the material again and make less rubbish", "To make them heavier", "Because they are alive", "To make them smell"], 0,
        "Recycling melts old cans and bottles to make new ones, saving materials and energy.",
        "ক্যান আর বোতল পুনর্ব্যবহার করি কেন?",
        ["উপাদান আবার ব্যবহার করতে আর আবর্জনা কমাতে", "ভারী করতে", "কারণ সেগুলো জীবন্ত", "গন্ধ বানাতে"],
        "পুনর্ব্যবহারে পুরোনো ক্যান আর বোতল গলিয়ে নতুন বানানো হয়, তাতে উপাদান আর শক্তি বাঁচে।"),
    mcq("A biscuit left in damp air becomes...",
        ["Soft and soggy", "Harder and crunchier", "Frozen", "A rock"], 0,
        "The biscuit soaks up water from damp air and loses its crunch.",
        "ভেজা বাতাসে বিস্কুট রেখে দিলে হয়ে যায়...",
        ["নরম আর নেতানো", "আরও শক্ত আর মুচমুচে", "জমাট", "পাথর"],
        "বিস্কুট ভেজা বাতাস থেকে জল শুষে নেয় আর মুচমুচে ভাব হারায়।"),
    mcq("Which one is a natural material?",
        ["Wool from a sheep", "Plastic", "Glass", "Nylon"], 0,
        "Wool comes straight from sheep. Plastic, glass and nylon are made in factories.",
        "কোনটা প্রাকৃতিক উপাদান?",
        ["ভেড়ার উল", "প্লাস্টিক", "কাচ", "নাইলন"],
        "উল সরাসরি ভেড়া থেকে আসে। প্লাস্টিক, কাচ আর নাইলন কারখানায় তৈরি।"),
    mcq("Why do we not leave iron nails in a glass of water?",
        ["They will rust", "They will melt", "They will grow", "They will float"], 0,
        "Water and air make iron rust. Rusty nails become weak and crumbly.",
        "লোহার পেরেক জলের গ্লাসে রাখি না কেন?",
        ["মরচে ধরবে", "গলে যাবে", "বড় হবে", "ভাসবে"],
        "জল আর বাতাস লোহায় মরচে ধরায়। মরচে-ধরা পেরেক দুর্বল আর ঝুরঝুরে হয়ে যায়।"),
    mcq("Sand and pebbles mixed in a bowl - how can you separate them?",
        ["Shake them through a sieve", "Add sugar", "Freeze them", "Blow on them"], 0,
        "A sieve lets small sand grains fall through and keeps the big pebbles on top.",
        "বাটিতে বালি আর নুড়ি মেশানো - কীভাবে আলাদা করবে?",
        ["চালুনিতে ঝাঁকিয়ে", "চিনি দিয়ে", "জমিয়ে", "ফুঁ দিয়ে"],
        "চালুনি ছোট বালিকণা নিচে পড়তে দেয় আর বড় নুড়ি উপরে রাখে।"),
    mcq("Which material can bend and spring back - good for a fishing rod?",
        ["Bamboo", "Glass", "Chalk", "Biscuit"], 0,
        "Bamboo is strong and springy, so it bends without breaking. People even build scaffolds with it.",
        "কোন উপাদান বেঁকে আবার ফিরে আসে - মাছ ধরার ছিপের জন্য ভালো?",
        ["বাঁশ", "কাচ", "চক", "বিস্কুট"],
        "বাঁশ শক্ত আর স্প্রিংয়ের মতো, তাই না ভেঙে বাঁকে। মানুষ এ দিয়ে ভারাও বানায়।"),
    mcq("A sandcastle stays up when the sand is a little wet. Why?",
        ["A little water makes sand grains stick together", "Water makes sand heavier only", "Wet sand is magic", "Dry sand is too sticky"], 0,
        "A little water forms tiny bridges between grains and holds them together. Too much water washes it away!",
        "একটু ভেজা বালিতে বালির দুর্গ দাঁড়িয়ে থাকে। কেন?",
        ["একটু জল বালির দানাগুলোকে জুড়ে দেয়", "জল শুধু বালিকে ভারী করে", "ভেজা বালি জাদুর", "শুকনো বালি খুব আঠালো"],
        "একটু জল দানাগুলোর মাঝে ছোট্ট সেতু বানিয়ে জুড়ে রাখে। বেশি জলে আবার ধুয়ে যায়!"),
    mcq("Which material is used to make windows?",
        ["Glass", "Wood only", "Brick", "Cloth"], 0,
        "Glass lets light in and keeps rain and wind out.",
        "জানালা বানাতে কোন উপাদান ব্যবহার হয়?",
        ["কাচ", "শুধু কাঠ", "ইট", "কাপড়"],
        "কাচ আলো ঢুকতে দেয় আর বৃষ্টি-বাতাস আটকায়।"),
    mcq("What do bees make that people eat?",
        ["Honey", "Butter", "Salt", "Cheese"], 0,
        "Bees turn flower nectar into honey and keep it in wax honeycombs.",
        "মৌমাছি এমন কী তৈরি করে যা মানুষ খায়?",
        ["মধু", "মাখন", "নুন", "পনির"],
        "মৌমাছি ফুলের রস থেকে মধু বানায় আর মোমের মৌচাকে রাখে।"),
    mcq("Lemon juice tastes...",
        ["Sour", "Sweet like sugar", "Salty like the sea", "Like nothing"], 0,
        "Lemon juice is an acid, and acids taste sour.",
        "লেবুর রসের স্বাদ...",
        ["টক", "চিনির মতো মিষ্টি", "সাগরের মতো নোনতা", "কোনো স্বাদ নেই"],
        "লেবুর রস একটা অম্ল (অ্যাসিড), আর অম্লের স্বাদ টক।"),
    mcq("Which material is a good choice for a warm winter jumper?",
        ["Wool", "Glass", "Paper", "Steel"], 0,
        "Wool traps warm air between its fibres and keeps you cosy.",
        "শীতের গরম সোয়েটারের জন্য কোন উপাদান ভালো?",
        ["উল", "কাচ", "কাগজ", "ইস্পাত"],
        "উল তার আঁশের মাঝে গরম বাতাস আটকে রাখে আর তোমাকে আরামে রাখে।"),
    mcq("A steel bridge has orange spots after many rainy years. What are they?",
        ["Rust - it needs repainting", "Flowers growing", "Orange juice", "Sunlight"], 0,
        "Rust spots show the paint has worn away. Engineers repaint bridges so the steel stays strong.",
        "অনেক বর্ষার পর ইস্পাতের সেতুতে কমলা দাগ। সেগুলো কী?",
        ["মরচে - আবার রং করতে হবে", "ফুল ফুটছে", "কমলার রস", "রোদ"],
        "মরচের দাগ মানে রং উঠে গেছে। ইস্পাত শক্ত রাখতে প্রকৌশলীরা সেতু আবার রং করেন।"),
    mcq("Which is the hardest to squash?",
        ["A steel ball", "A marshmallow", "A balloon", "A bread roll"], 0,
        "Steel is very hard and strong, so it hardly squashes at all.",
        "কোনটা চেপে ছোট করা সবচেয়ে কঠিন?",
        ["ইস্পাতের বল", "মার্শম্যালো", "বেলুন", "পাউরুটির রোল"],
        "ইস্পাত খুব শক্ত আর মজবুত, তাই প্রায় চাপে বসেই না।"),
    mcq("Why does an ice cube float in a drink?",
        ["Ice is a little lighter than the same amount of water", "Ice is filled with sugar", "Drinks push ice up because they are fizzy only", "Ice is made of air"], 0,
        "When water freezes it spreads out a little, so ice is lighter than water and floats.",
        "পানীয়তে বরফের টুকরো ভাসে কেন?",
        ["সমান পরিমাণ জলের চেয়ে বরফ একটু হালকা", "বরফ চিনিতে ভরা", "শুধু ফেনা হলেই পানীয় বরফ ঠেলে", "বরফ বাতাসে তৈরি"],
        "জল জমলে একটু ছড়িয়ে যায়, তাই বরফ জলের চেয়ে হালকা আর ভাসে।"),
    mcq("A shiny new coin turns dull and dark over the years. Why?",
        ["Air slowly reacts with the metal", "It got tired", "Someone painted it", "Coins grow old hair"], 0,
        "Air slowly changes the metal's surface. Polishing removes this dull layer.",
        "চকচকে নতুন পয়সা বছরের পর বছর ম্লান আর কালচে হয়ে যায়। কেন?",
        ["বাতাস ধীরে ধীরে ধাতুর সঙ্গে বিক্রিয়া করে", "পয়সা ক্লান্ত হয়েছে", "কেউ রং করেছে", "পয়সার বুড়ো চুল গজায়"],
        "বাতাস ধীরে ধীরে ধাতুর উপরিভাগ বদলায়। ঘষে পরিষ্কার করলে এই ম্লান স্তর ওঠে।"),
    mcq("Which material would be best for a bridge over a river that must last 100 years?",
        ["Strong steel and concrete, well protected", "Paper", "Cardboard", "Ice"], 0,
        "Long-lasting bridges use strong materials and protect them from water and rust.",
        "100 বছর টিকতে হবে এমন নদীর সেতুর জন্য কোন উপাদান সবচেয়ে ভালো?",
        ["ভালোভাবে সুরক্ষিত শক্ত ইস্পাত আর কংক্রিট", "কাগজ", "কার্ডবোর্ড", "বরফ"],
        "দীর্ঘস্থায়ী সেতু শক্ত উপাদান ব্যবহার করে আর তাকে জল আর মরচে থেকে বাঁচায়।"),
    mcq("You blow bubbles with soapy water. What is inside each bubble?",
        ["Air from your breath", "Water only", "Soap only", "Nothing at all"], 0,
        "A bubble is a thin skin of soapy water holding a pocket of air.",
        "সাবান-জলে বুদবুদ ওড়ালে। প্রতিটি বুদবুদের ভেতরে কী?",
        ["তোমার নিঃশ্বাসের বাতাস", "শুধু জল", "শুধু সাবান", "কিছুই না"],
        "বুদবুদ হলো সাবান-জলের একটা পাতলা আবরণ, যার ভেতরে বাতাস আটকে থাকে।"),
    mcq("Which is NOT a metal?",
        ["Wood", "Copper", "Iron", "Aluminium"], 0,
        "Copper, iron and aluminium are metals. Wood comes from trees.",
        "কোনটা ধাতু নয়?",
        ["কাঠ", "তামা", "লোহা", "অ্যালুমিনিয়াম"],
        "তামা, লোহা আর অ্যালুমিনিয়াম ধাতু। কাঠ আসে গাছ থেকে।"),
    mcq("Why do we put a lid on a pot of hot soup to keep it warm?",
        ["The lid stops heat and steam escaping", "The lid makes soup heavier", "Lids are cold", "The lid adds salt"], 0,
        "A lid traps the hot steam and warm air, so the soup cools down more slowly.",
        "গরম স্যুপ গরম রাখতে হাঁড়িতে ঢাকনা দিই কেন?",
        ["ঢাকনা তাপ আর বাষ্প বেরোতে দেয় না", "ঢাকনা স্যুপ ভারী করে", "ঢাকনা ঠান্ডা", "ঢাকনা নুন যোগ করে"],
        "ঢাকনা গরম বাষ্প আর উষ্ণ বাতাস আটকায়, তাই স্যুপ ধীরে ঠান্ডা হয়।"),
    mcq("Which of these makes fizzy bubbles when mixed?",
        ["Baking soda and vinegar", "Sand and stones", "Water and ice", "Salt and pepper"], 0,
        "Baking soda and vinegar react and make a gas - lots of fizzy bubbles! A fun chemical change.",
        "এগুলোর কোনটা মেশালে ফেনিল বুদবুদ ওঠে?",
        ["বেকিং সোডা আর ভিনেগার", "বালি আর পাথর", "জল আর বরফ", "নুন আর গোলমরিচ"],
        "বেকিং সোডা আর ভিনেগার বিক্রিয়া করে গ্যাস তৈরি করে - অনেক ফেনিল বুদবুদ! একটা মজার রাসায়নিক পরিবর্তন।"),
    mcq("A plastic toy left in very hot sun for days may become...",
        ["Faded and brittle", "Stronger than steel", "Gold", "Bigger"], 0,
        "Strong sunlight slowly breaks plastic down, so it fades and cracks.",
        "প্লাস্টিকের খেলনা কয়েকদিন কড়া রোদে পড়ে থাকলে হয়ে যেতে পারে...",
        ["বিবর্ণ আর ভঙ্গুর", "ইস্পাতের চেয়ে শক্ত", "সোনা", "আরও বড়"],
        "কড়া রোদ ধীরে ধীরে প্লাস্টিক ভেঙে দেয়, তাই রং ফিকে হয় আর ফাটে।"),
    mcq("Which is the best for writing on a blackboard?",
        ["Chalk", "A steel nail", "Butter", "Water"], 0,
        "Chalk is soft and crumbly, so it leaves a powdery mark on the board.",
        "ব্ল্যাকবোর্ডে লেখার জন্য কোনটা সবচেয়ে ভালো?",
        ["চক", "ইস্পাতের পেরেক", "মাখন", "জল"],
        "চক নরম আর ঝুরঝুরে, তাই বোর্ডে গুঁড়োর দাগ রেখে যায়।"),
    mcq("Why does a wet floor dry faster when a fan is on?",
        ["Moving air carries the water vapour away", "The fan sucks water up into it", "Fans make water heavier", "It does not dry faster"], 0,
        "Moving air takes away the damp air above the floor, so more water can evaporate.",
        "পাখা চললে ভেজা মেঝে তাড়াতাড়ি শুকায় কেন?",
        ["চলমান বাতাস জলীয় বাষ্প সরিয়ে নেয়", "পাখা জল টেনে নেয়", "পাখা জলকে ভারী করে", "তাড়াতাড়ি শুকায় না"],
        "চলমান বাতাস মেঝের উপরের ভেজা বাতাস সরিয়ে নেয়, তাই আরও জল বাষ্পীভূত হতে পারে।"),
    mcq("Which is a mixture you can see the parts of?",
        ["A fruit salad", "Sugar water", "Salt water", "Air"], 0,
        "In a fruit salad you can still see each fruit. In sugar water the sugar is hidden.",
        "কোন মিশ্রণে আলাদা অংশগুলো দেখা যায়?",
        ["ফলের সালাদ", "চিনি-জল", "নুন-জল", "বাতাস"],
        "ফলের সালাদে প্রতিটি ফল আলাদা দেখা যায়। চিনি-জলে চিনি লুকিয়ে থাকে।"),
    mcq("Why are bricks laid with mortar between them?",
        ["Mortar sticks the bricks together and fills the gaps", "To make bricks softer", "To make the wall shiny", "To let water in"], 0,
        "Mortar (cement, sand and water) hardens and glues bricks into one strong wall.",
        "ইটের মাঝে মশলা দিয়ে গাঁথা হয় কেন?",
        ["মশলা ইটগুলোকে জুড়ে ফাঁক ভরে দেয়", "ইট নরম করতে", "দেয়াল চকচকে করতে", "জল ঢুকতে দিতে"],
        "মশলা (সিমেন্ট, বালি আর জল) শক্ত হয়ে ইটগুলোকে জুড়ে একটা মজবুত দেয়াল বানায়।"),
    mcq("Which material can be pulled thin into wires?",
        ["Copper", "Glass", "Clay", "Chalk"], 0,
        "Copper can be stretched into long thin wires that carry electricity.",
        "কোন উপাদান টেনে সরু তার বানানো যায়?",
        ["তামা", "কাচ", "কাদামাটি", "চক"],
        "তামা টেনে লম্বা সরু তার বানানো যায়, যা বিদ্যুৎ বয়।"),
    mcq("What happens to butter in a hot pan?",
        ["It melts", "It freezes", "It turns into bread", "It gets harder"], 0,
        "The heat of the pan melts the solid butter into a liquid.",
        "গরম কড়াইয়ে মাখনের কী হয়?",
        ["গলে যায়", "জমে যায়", "পাউরুটি হয়ে যায়", "আরও শক্ত হয়"],
        "কড়াইয়ের তাপ কঠিন মাখনকে গলিয়ে তরল করে।"),
    mcq("Why do we keep paint tins closed?",
        ["Air dries the paint out", "Paint runs away", "Tins get lonely", "Paint gets colder"], 0,
        "Paint dries when its liquid part escapes into the air. A closed lid keeps it wet.",
        "রঙের কৌটো বন্ধ রাখি কেন?",
        ["বাতাস রং শুকিয়ে দেয়", "রং পালিয়ে যায়", "কৌটো একা লাগে", "রং ঠান্ডা হয়"],
        "রঙের তরল অংশ বাতাসে বেরিয়ে গেলে রং শুকিয়ে যায়। বন্ধ ঢাকনা তাকে ভেজা রাখে।"),
    mcq("Which of these will rust?",
        ["An iron chain left outside", "A plastic chair", "A glass jar", "A wooden stick"], 0,
        "Only iron and steel rust. Plastic, glass and wood do not rust.",
        "এগুলোর কোনটায় মরচে ধরবে?",
        ["বাইরে পড়ে থাকা লোহার শিকল", "প্লাস্টিকের চেয়ার", "কাচের বয়াম", "কাঠের লাঠি"],
        "শুধু লোহা আর ইস্পাতে মরচে ধরে। প্লাস্টিক, কাচ আর কাঠে মরচে ধরে না।"),
    mcq("Why do builders keep cement bags dry?",
        ["Water makes cement set hard in the bag", "Dry cement is heavier", "Wet bags are pretty", "Cement eats water"], 0,
        "Cement starts to harden as soon as it gets wet. A wet bag turns into a useless lump!",
        "নির্মাতারা সিমেন্টের বস্তা শুকনো রাখেন কেন?",
        ["জলে সিমেন্ট বস্তার মধ্যেই জমে শক্ত হয়ে যায়", "শুকনো সিমেন্ট বেশি ভারী", "ভেজা বস্তা সুন্দর", "সিমেন্ট জল খায়"],
        "সিমেন্ট ভিজলেই শক্ত হতে শুরু করে। ভেজা বস্তা একটা অকেজো দলা হয়ে যায়!"),
    mcq("Which material lets electricity flow through it?",
        ["Copper wire", "A rubber band", "A plastic ruler", "A wooden spoon"], 0,
        "Metals like copper carry electricity. Rubber, plastic and wood block it - that is why wires are covered in plastic.",
        "কোন উপাদানের মধ্য দিয়ে বিদ্যুৎ চলে?",
        ["তামার তার", "রাবার ব্যান্ড", "প্লাস্টিকের স্কেল", "কাঠের চামচ"],
        "তামার মতো ধাতু বিদ্যুৎ বয়। রাবার, প্লাস্টিক আর কাঠ তা আটকায় - তাই তার প্লাস্টিকে মোড়া থাকে।"),
    mcq("Why is a wooden spoon good for stirring hot soup?",
        ["Wood does not get hot quickly in your hand", "Wood melts the soup", "Wood is magnetic", "Wood makes soup sweet"], 0,
        "Wood does not pass heat well, so the handle stays cool.",
        "গরম স্যুপ নাড়তে কাঠের চামচ ভালো কেন?",
        ["কাঠ হাতে তাড়াতাড়ি গরম হয় না", "কাঠ স্যুপ গলায়", "কাঠ চুম্বক", "কাঠ স্যুপ মিষ্টি করে"],
        "কাঠ তাপ ভালো বয় না, তাই হাতল ঠান্ডা থাকে।"),
    mcq("Water drops appear on the outside of a cold glass of juice. Where did they come from?",
        ["Water vapour in the air turned back into drops", "The glass leaked", "The juice jumped out", "It rained inside"], 0,
        "Cold glass cools the air next to it, and the invisible vapour in the air turns into tiny drops.",
        "ঠান্ডা রসের গ্লাসের বাইরে জলের ফোঁটা দেখা যায়। কোথা থেকে এলো?",
        ["বাতাসের জলীয় বাষ্প আবার ফোঁটা হয়েছে", "গ্লাস ফুটো", "রস লাফিয়ে বেরিয়েছে", "ঘরের ভেতরে বৃষ্টি হয়েছে"],
        "ঠান্ডা গ্লাস পাশের বাতাসকে ঠান্ডা করে, আর বাতাসের অদৃশ্য বাষ্প ছোট ছোট ফোঁটা হয়ে যায়।"),
    mcq("Which material is strongest for holding a heavy load in a rope?",
        ["Steel wire rope", "Paper string", "Wool thread", "Spaghetti"], 0,
        "Steel wire is extremely strong when pulled - that is why big bridges hang from steel cables.",
        "ভারী ভার ধরার দড়ির জন্য কোন উপাদান সবচেয়ে শক্ত?",
        ["ইস্পাতের তারের দড়ি", "কাগজের সুতো", "উলের সুতো", "স্প্যাগেটি"],
        "ইস্পাতের তার টানলে ভীষণ শক্ত - এজন্যই বড় সেতু ইস্পাতের তার থেকে ঝোলে।"),
    mcq("Why do we wash our hands after playing in mud?",
        ["Mud can carry germs", "Mud is made of soap", "Mud is too clean", "Hands get heavier"], 0,
        "Soil can carry tiny germs. Washing with soap keeps us healthy.",
        "কাদায় খেলার পর হাত ধুই কেন?",
        ["কাদায় জীবাণু থাকতে পারে", "কাদা সাবানে তৈরি", "কাদা খুব পরিষ্কার", "হাত ভারী হয়ে যায়"],
        "মাটিতে ছোট্ট জীবাণু থাকতে পারে। সাবান দিয়ে ধুলে আমরা সুস্থ থাকি।"),
    mcq("Which happens when you heat water in a pan for a long time?",
        ["The water level goes down as it boils away", "The water grows", "The water turns into sand", "Nothing ever changes"], 0,
        "Boiling turns water into steam, which floats away, so less water is left.",
        "কড়াইয়ে অনেকক্ষণ জল গরম করলে কী হয়?",
        ["ফুটে উবে গিয়ে জল কমে যায়", "জল বাড়তে থাকে", "জল বালি হয়ে যায়", "কিছুই কখনো বদলায় না"],
        "ফোটালে জল বাষ্প হয়ে উড়ে যায়, তাই কম জল বাকি থাকে।"),
    mcq("Which material is see-through, waterproof and strong enough for a fish tank?",
        ["Thick glass", "Paper", "Wood", "Wool"], 0,
        "Thick glass lets you see the fish, keeps water in and is strong enough to hold it.",
        "কোন উপাদান স্বচ্ছ, জলরোধী আর মাছের অ্যাকোয়ারিয়ামের জন্য যথেষ্ট শক্ত?",
        ["মোটা কাচ", "কাগজ", "কাঠ", "উল"],
        "মোটা কাচে মাছ দেখা যায়, জল আটকে থাকে আর তা ধরে রাখার মতো শক্ত।"),
    mcq("A sugar cube put in hot tea disappears faster than in cold water. Why?",
        ["Heat makes things dissolve faster", "Tea eats sugar", "Cold water is sweet already", "Sugar is scared of tea"], 0,
        "Warm water moves faster and breaks the sugar apart more quickly.",
        "চিনির কিউব গরম চায়ে ঠান্ডা জলের চেয়ে তাড়াতাড়ি মিলিয়ে যায়। কেন?",
        ["তাপে জিনিস তাড়াতাড়ি দ্রবীভূত হয়", "চা চিনি খায়", "ঠান্ডা জল আগেই মিষ্টি", "চিনি চাকে ভয় পায়"],
        "গরম জল দ্রুত নড়াচড়া করে আর চিনিকে তাড়াতাড়ি ভেঙে দেয়।"),
    mcq("Why do roads have black tar on top?",
        ["Tar is waterproof and holds the stones together", "Tar makes roads soft like beds", "Tar makes cars fly", "Tar is a kind of paint for fun"], 0,
        "Tar (bitumen) is sticky and waterproof. It glues the stones together and keeps rain out of the road.",
        "রাস্তার উপরে কালো আলকাতরা থাকে কেন?",
        ["আলকাতরা জলরোধী আর পাথরগুলো জুড়ে রাখে", "আলকাতরা রাস্তাকে বিছানার মতো নরম করে", "আলকাতরা গাড়ি ওড়ায়", "মজার জন্য এক রকম রং"],
        "আলকাতরা (বিটুমেন) আঠালো আর জলরোধী। এটা পাথরগুলো জুড়ে দেয় আর রাস্তায় বৃষ্টির জল ঢুকতে দেয় না।"),
    mcq("Which material comes from under the ground?",
        ["Coal and stone", "Wool", "Cotton", "Leather"], 0,
        "Coal and stone are dug out of the ground. Wool, cotton and leather come from animals and plants.",
        "কোন উপাদান মাটির নিচ থেকে আসে?",
        ["কয়লা আর পাথর", "উল", "তুলো", "চামড়া"],
        "কয়লা আর পাথর মাটি খুঁড়ে তোলা হয়। উল, তুলো আর চামড়া আসে প্রাণী আর গাছ থেকে।"),
    mcq("Why does iron need special care near the sea?",
        ["Salty sea air makes it rust faster", "Sea air makes iron gold", "Fish eat iron", "The sea is too cold"], 0,
        "Salt speeds up rusting. Bridges by the sea get extra paint and protection.",
        "সমুদ্রের কাছে লোহার বাড়তি যত্ন লাগে কেন?",
        ["নোনা সমুদ্র-বাতাসে তাড়াতাড়ি মরচে ধরে", "সমুদ্রের বাতাস লোহাকে সোনা করে", "মাছ লোহা খায়", "সমুদ্র খুব ঠান্ডা"],
        "নুন মরচে ধরা দ্রুত করে। সমুদ্রের ধারের সেতুতে বাড়তি রং আর সুরক্ষা দেওয়া হয়।"),
    mcq("Mixing flour and water and baking it makes...",
        ["Bread or chapati", "Glass", "Steel", "Rubber"], 0,
        "Heat changes the dough into bread - a change you cannot undo.",
        "আটা আর জল মিশিয়ে সেঁকলে তৈরি হয়...",
        ["পাউরুটি বা রুটি", "কাচ", "ইস্পাত", "রাবার"],
        "তাপ মাখা আটাকে রুটিতে বদলায় - এমন পরিবর্তন যা আর ফেরানো যায় না।"),
    mcq("Why do builders wet concrete for several days after pouring it?",
        ["So it hardens slowly and becomes strong without cracking", "To wash it away", "To make it float", "Concrete gets thirsty for fun"], 0,
        "Concrete needs water to harden properly. Keeping it damp (curing) makes it stronger and stops cracks.",
        "ঢালার পরে কয়েকদিন নির্মাতারা কংক্রিট ভিজিয়ে রাখেন কেন?",
        ["যাতে ধীরে শক্ত হয়ে না ফেটে মজবুত হয়", "ধুয়ে ফেলতে", "ভাসাতে", "মজা করে কংক্রিটের তেষ্টা পায়"],
        "ঠিকমতো শক্ত হতে কংক্রিটের জল লাগে। ভেজা রাখলে (কিওরিং) আরও মজবুত হয় আর ফাটে না।"),
    mcq("Which can you make by melting sand at a very high temperature?",
        ["Glass", "Wood", "Wool", "Paper"], 0,
        "Glass is made by melting sand in a very hot furnace and letting it cool.",
        "খুব উঁচু তাপমাত্রায় বালি গলিয়ে কী বানানো যায়?",
        ["কাচ", "কাঠ", "উল", "কাগজ"],
        "খুব গরম চুল্লিতে বালি গলিয়ে ঠান্ডা করে কাচ বানানো হয়।"),
    mcq("A balloon left in a hot car may pop. Why?",
        ["Heat makes the air inside spread out", "Cars hate balloons", "Heat makes the balloon thicker", "The balloon gets hungry"], 0,
        "Warm air expands (takes up more room). The balloon stretches until it pops.",
        "গরম গাড়িতে রাখা বেলুন ফেটে যেতে পারে। কেন?",
        ["তাপে ভেতরের বাতাস ছড়িয়ে পড়ে", "গাড়ি বেলুন অপছন্দ করে", "তাপে বেলুন মোটা হয়", "বেলুনের খিদে পায়"],
        "উষ্ণ বাতাস প্রসারিত হয় (বেশি জায়গা নেয়)। বেলুন টেনে বাড়তে বাড়তে ফেটে যায়।"),
    mcq("Which is a gas?",
        ["The air we breathe", "Juice", "Ice", "A rock"], 0,
        "Air is a mix of gases. It spreads out to fill any space.",
        "কোনটা গ্যাস?",
        ["যে বাতাসে আমরা শ্বাস নিই", "রস", "বরফ", "পাথর"],
        "বাতাস কয়েকটি গ্যাসের মিশ্রণ। এটা যেকোনো জায়গা ভরে ছড়িয়ে পড়ে।"),
    mcq("Why do steel railway lines have small gaps between them?",
        ["Steel grows a little longer when it gets hot", "To let trains jump", "To save steel only", "To let grass grow"], 0,
        "Heat makes steel expand. Little gaps give it room, so the rails do not bend on hot days. Bridges have them too!",
        "ইস্পাতের রেললাইনের মাঝে ছোট ফাঁক থাকে কেন?",
        ["গরমে ইস্পাত একটু লম্বা হয়", "ট্রেন লাফাতে পারে বলে", "শুধু ইস্পাত বাঁচাতে", "ঘাস জন্মাতে দিতে"],
        "তাপে ইস্পাত প্রসারিত হয়। ছোট ফাঁক জায়গা দেয়, তাই গরম দিনে লাইন বাঁকে না। সেতুতেও এমন থাকে!"),
    mcq("Which material is light, does not rust and is used for soft-drink cans?",
        ["Aluminium", "Iron", "Stone", "Clay"], 0,
        "Aluminium is a light metal that does not rust like iron - perfect for cans and aeroplanes.",
        "কোন উপাদান হালকা, মরচে ধরে না আর কোমল পানীয়ের ক্যানে ব্যবহার হয়?",
        ["অ্যালুমিনিয়াম", "লোহা", "পাথর", "কাদামাটি"],
        "অ্যালুমিনিয়াম হালকা ধাতু, লোহার মতো মরচে ধরে না - ক্যান আর উড়োজাহাজের জন্য দারুণ।"),
    mcq("What do we call stuff that everything is made of?",
        ["Materials (matter)", "Colours", "Sounds", "Wishes"], 0,
        "Everything around us is made of materials - wood, metal, plastic, glass, water and air.",
        "যা দিয়ে সবকিছু তৈরি, তাকে কী বলি?",
        ["উপাদান (পদার্থ)", "রং", "শব্দ", "ইচ্ছা"],
        "আমাদের চারপাশের সবকিছু উপাদানে তৈরি - কাঠ, ধাতু, প্লাস্টিক, কাচ, জল আর বাতাস।"),
    mcq("You squeeze an orange. What do you get?",
        ["Juice - a liquid", "Sand", "Steam", "A stone"], 0,
        "Squeezing breaks open the tiny juice sacs and the liquid juice runs out.",
        "কমলা চিপলে কী পাও?",
        ["রস - একটা তরল", "বালি", "বাষ্প", "পাথর"],
        "চিপলে ছোট ছোট রসের থলি ফেটে যায় আর তরল রস বেরিয়ে আসে।"),
    mcq("Which would make the strongest small bridge for toy cars?",
        ["Wooden ice-cream sticks glued in triangles", "Loose leaves", "Wet tissues", "Jelly cubes"], 0,
        "Stiff wooden sticks glued into triangles make a strong, light frame - a real truss bridge in miniature!",
        "খেলনা গাড়ির জন্য কোনটা দিয়ে সবচেয়ে মজবুত ছোট সেতু হবে?",
        ["আঠা দিয়ে ত্রিভুজে জোড়া আইসক্রিমের কাঠি", "আলগা পাতা", "ভেজা টিস্যু", "জেলির টুকরো"],
        "শক্ত কাঠের কাঠি ত্রিভুজে জুড়লে মজবুত, হালকা কাঠামো হয় - ছোট্ট একটা আসল ট্রাস সেতু!"),
)
