"""Class 1 - Biology: living things, our body, animals, plants and staying healthy."""
from . import mcq

ITEMS = (
    mcq("Why do birds have light, hollow bones instead of heavy solid ones?",
        ["So they are light enough to fly", "So they can swim deep", "To make noise", "Because they are always hungry"], 0,
        "Hollow bones are strong but light - otherwise flapping into the sky would be like lifting a sack of rocks!",
        "পাখির হাড় ভারী নিরেট না হয়ে হালকা আর ফাঁপা কেন?",
        ["যাতে উড়তে পারার মতো হালকা হয়", "যাতে গভীরে সাঁতার কাটতে পারে", "শব্দ করতে", "কারণ তাদের সবসময় খিদে পায়"],
        "ফাঁপা হাড় মজবুত কিন্তু হালকা - নইলে আকাশে ওড়া হতো পাথরের বস্তা তোলার মতো!"),
    mcq("Which of these is a living thing?", ["A tree", "A rock", "A spoon", "A cloud"], 0,
        "Living things grow, need food and water, and make young ones. A tree does all of these.",
        "এগুলোর মধ্যে কোনটা জীবন্ত?", ["গাছ", "পাথর", "চামচ", "মেঘ"],
        "জীবন্ত জিনিস বড় হয়, খাবার আর জল চায়, আর বাচ্চা জন্ম দেয়। গাছ এসবই করে।"),
    mcq("What do plants need to grow?", ["Sunlight, water and air", "Only chocolate", "Darkness and sand only", "Plastic"], 0,
        "Plants make their food using sunlight, water and air. They also take minerals from the soil.",
        "গাছের বাড়তে কী লাগে?", ["সূর্যের আলো, জল আর বাতাস", "শুধু চকলেট", "শুধু অন্ধকার আর বালি", "প্লাস্টিক"],
        "গাছ সূর্যের আলো, জল আর বাতাস দিয়ে নিজের খাবার তৈরি করে। মাটি থেকে খনিজও নেয়।"),
    mcq("Which part of a plant holds it in the ground?", ["The roots", "The flower", "The leaf", "The fruit"], 0,
        "Roots grip the soil and drink water - like a building's foundation.",
        "গাছের কোন অংশ তাকে মাটিতে ধরে রাখে?", ["শিকড়", "ফুল", "পাতা", "ফল"],
        "শিকড় মাটি আঁকড়ে ধরে আর জল টানে - যেন একটা বাড়ির ভিত।"),
    mcq("What do our bones do?", ["Hold our body up and protect us", "Help us smell", "Make us taste food", "Nothing"], 0,
        "Our skeleton is our body's frame, like the steel frame of a building. The skull protects the brain.",
        "আমাদের হাড় কী করে?", ["শরীরকে খাড়া রাখে আর রক্ষা করে", "গন্ধ নিতে সাহায্য করে", "খাবারের স্বাদ দেয়", "কিছুই না"],
        "আমাদের কঙ্কাল শরীরের কাঠামো, যেন বাড়ির ইস্পাতের কাঠামো। মাথার খুলি মস্তিষ্ক রক্ষা করে।"),
    mcq("Which sense do you use to hear a bird sing?", ["Hearing (ears)", "Taste (tongue)", "Smell (nose)", "Touch (skin)"], 0,
        "Ears catch sounds. We have five senses: sight, hearing, smell, taste and touch.",
        "পাখির গান শুনতে কোন ইন্দ্রিয় ব্যবহার করো?", ["শ্রবণ (কান)", "স্বাদ (জিভ)", "ঘ্রাণ (নাক)", "স্পর্শ (ত্বক)"],
        "কান শব্দ ধরে। আমাদের পাঁচটি ইন্দ্রিয়: দেখা, শোনা, ঘ্রাণ, স্বাদ আর স্পর্শ।"),
    mcq("A baby cow is called a...", ["Calf", "Kitten", "Puppy", "Chick"], 0,
        "Baby cows are calves; kittens are baby cats, puppies are baby dogs, chicks are baby hens.",
        "গরুর বাচ্চাকে বলে...", ["বাছুর", "বিড়ালছানা", "কুকুরছানা", "মুরগির ছানা"],
        "গরুর বাচ্চা বাছুর; বিড়ালছানা বিড়ালের, কুকুরছানা কুকুরের, আর ছানা মুরগির বাচ্চা।"),
    mcq("Which animal lives in water?", ["Fish", "Lion", "Cow", "Camel"], 0,
        "Fish breathe through gills and live in water.",
        "কোন প্রাণী জলে থাকে?", ["মাছ", "সিংহ", "গরু", "উট"],
        "মাছ কানকো দিয়ে শ্বাস নেয় আর জলে থাকে।"),
    mcq("Why must we brush our teeth?", ["To keep them clean and stop holes", "To make them longer", "To change their colour to blue", "Teeth do not need care"], 0,
        "Brushing removes food and germs that make holes (cavities) in teeth.",
        "আমাদের দাঁত মাজতে হয় কেন?", ["পরিষ্কার রাখতে আর গর্ত ঠেকাতে", "লম্বা করতে", "নীল রং করতে", "দাঁতের যত্ন লাগে না"],
        "দাঁত মাজলে খাবার আর জীবাণু সরে, যা দাঁতে গর্ত (ক্যাভিটি) করে।"),
    mcq("Which food helps you grow strong?", ["Fruit, vegetables, milk and lentils", "Only sweets", "Only crisps", "Only fizzy drinks"], 0,
        "A healthy mix of foods gives your body what it needs to grow and play.",
        "কোন খাবার তোমাকে বড় আর শক্ত হতে সাহায্য করে?", ["ফল, সবজি, দুধ আর ডাল", "শুধু মিষ্টি", "শুধু চিপস", "শুধু ফেনাওয়ালা পানীয়"],
        "নানা রকম স্বাস্থ্যকর খাবার শরীরকে বাড়তে আর খেলতে যা লাগে তা দেয়।"),
    mcq("Which animal has a long neck to reach tall trees?", ["Giraffe", "Rabbit", "Snake", "Penguin"], 0,
        "A giraffe's long neck lets it eat leaves high up that other animals cannot reach.",
        "উঁচু গাছ নাগাল পেতে কোন প্রাণীর লম্বা গলা?", ["জিরাফ", "খরগোশ", "সাপ", "পেঙ্গুইন"],
        "জিরাফের লম্বা গলায় সে উঁচুর পাতা খায়, যা অন্য প্রাণী নাগাল পায় না।"),
    mcq("What does a caterpillar turn into?", ["A butterfly", "A fish", "A bird", "A frog"], 0,
        "A caterpillar wraps itself in a cocoon (chrysalis) and comes out as a butterfly.",
        "শুঁয়োপোকা কীসে বদলে যায়?", ["প্রজাপতি", "মাছ", "পাখি", "ব্যাঙ"],
        "শুঁয়োপোকা নিজেকে গুটির মধ্যে মুড়ে নেয় আর প্রজাপতি হয়ে বেরোয়।"),
    mcq("What does a tadpole grow into?", ["A frog", "A fish", "A snake", "A duck"], 0,
        "Tadpoles live in water, grow legs, lose their tail and become frogs.",
        "ব্যাঙাচি বড় হয়ে কী হয়?", ["ব্যাঙ", "মাছ", "সাপ", "হাঁস"],
        "ব্যাঙাচি জলে থাকে, পা গজায়, লেজ খসে যায় আর ব্যাঙ হয়।"),
    mcq("Which part of a plant makes seeds?", ["The flower", "The root", "The stem only", "The soil"], 0,
        "Flowers make seeds, and seeds grow into new plants.",
        "গাছের কোন অংশ বীজ তৈরি করে?", ["ফুল", "শিকড়", "শুধু কাণ্ড", "মাটি"],
        "ফুল বীজ তৈরি করে, আর বীজ থেকে নতুন গাছ হয়।"),
    mcq("Why do we feel cold and shiver?", ["Shivering makes our muscles warm us up", "We are happy", "We are hungry", "Shivering cools us"], 0,
        "Shaking muscles make heat. It is the body's way of warming up.",
        "আমরা ঠান্ডা লাগলে কাঁপি কেন?", ["কাঁপলে পেশি আমাদের গরম করে", "আমরা খুশি", "আমাদের খিদে পায়", "কাঁপলে ঠান্ডা হই"],
        "কাঁপা পেশি তাপ তৈরি করে। এটা শরীরের গরম হওয়ার উপায়।"),
    mcq("Which of these is NOT alive?", ["A toy robot", "A cat", "A mango tree", "A ladybird"], 0,
        "A toy robot can move with batteries, but it does not grow, eat or have babies.",
        "এগুলোর কোনটা জীবন্ত নয়?", ["খেলনা রোবট", "বিড়াল", "আমগাছ", "লেডিবার্ড পোকা"],
        "খেলনা রোবট ব্যাটারিতে নড়তে পারে, কিন্তু বড় হয় না, খায় না, বাচ্চাও হয় না।"),
    mcq("What do we breathe in to stay alive?", ["Air (oxygen)", "Water", "Sand", "Smoke"], 0,
        "Our lungs take oxygen from the air. We need it every moment.",
        "বেঁচে থাকতে আমরা কী শ্বাসে নিই?", ["বাতাস (অক্সিজেন)", "জল", "বালি", "ধোঁয়া"],
        "আমাদের ফুসফুস বাতাস থেকে অক্সিজেন নেয়। প্রতি মুহূর্তে এটা লাগে।"),
    mcq("Which organ pumps blood around your body?", ["The heart", "The nose", "The ear", "The hair"], 0,
        "Your heart is a strong muscle that pumps blood all day and night.",
        "কোন অঙ্গ শরীরে রক্ত পাম্প করে?", ["হৃৎপিণ্ড", "নাক", "কান", "চুল"],
        "হৃৎপিণ্ড একটি শক্তিশালী পেশি, দিনরাত রক্ত পাম্প করে।"),
    mcq("Which animal gives us wool?", ["Sheep", "Fish", "Hen", "Snake"], 0,
        "Sheep grow thick woolly coats, and the wool is cut off to make warm clothes.",
        "কোন প্রাণী আমাদের উল দেয়?", ["ভেড়া", "মাছ", "মুরগি", "সাপ"],
        "ভেড়ার গায়ে ঘন উল জন্মায়, তা কেটে গরম কাপড় বানানো হয়।"),
    mcq("Which animal gives us eggs to eat?", ["Hen", "Cow", "Goat", "Horse"], 0,
        "Hens lay eggs. Cows and goats give milk.",
        "কোন প্রাণী আমাদের খাওয়ার ডিম দেয়?", ["মুরগি", "গরু", "ছাগল", "ঘোড়া"],
        "মুরগি ডিম পাড়ে। গরু আর ছাগল দুধ দেয়।"),
    mcq("Why do leaves turn towards a window?", ["Plants grow towards light", "They want to go outside", "Wind pulls them", "They are scared of the dark"], 0,
        "Plants need light to make food, so they bend towards it.",
        "পাতা জানালার দিকে ঘোরে কেন?", ["গাছ আলোর দিকে বাড়ে", "বাইরে যেতে চায়", "বাতাস টানে", "অন্ধকারকে ভয় পায়"],
        "খাবার তৈরিতে গাছের আলো লাগে, তাই আলোর দিকে বেঁকে যায়।"),
    mcq("Why do we wash fruit before eating it?", ["To remove dirt and germs", "To make it bigger", "To change its taste to salty", "No reason"], 0,
        "Washing removes dirt, germs and sprays from the skin of fruit.",
        "খাওয়ার আগে ফল ধুই কেন?", ["ময়লা আর জীবাণু সরাতে", "বড় করতে", "স্বাদ নোনতা করতে", "কোনো কারণ নেই"],
        "ধুলে ফলের খোসার ময়লা, জীবাণু আর ওষুধ সরে যায়।"),
    mcq("Which animal can fly?", ["Eagle", "Elephant", "Crocodile", "Goat"], 0,
        "Eagles have big wings and hollow bones, perfect for flying.",
        "কোন প্রাণী উড়তে পারে?", ["ঈগল", "হাতি", "কুমির", "ছাগল"],
        "ঈগলের বড় ডানা আর ফাঁপা হাড়, ওড়ার জন্য একদম ঠিক।"),
    mcq("What do cows mainly eat?", ["Grass", "Meat", "Fish", "Stones"], 0,
        "Cows are plant-eaters (herbivores). They chew grass for hours.",
        "গরু মূলত কী খায়?", ["ঘাস", "মাংস", "মাছ", "পাথর"],
        "গরু তৃণভোজী। ঘণ্টার পর ঘণ্টা ঘাস চিবোয়।"),
    mcq("Which animal eats meat?", ["Lion", "Cow", "Rabbit", "Deer"], 0,
        "Lions are meat-eaters (carnivores). Cows, rabbits and deer eat plants.",
        "কোন প্রাণী মাংস খায়?", ["সিংহ", "গরু", "খরগোশ", "হরিণ"],
        "সিংহ মাংসাশী। গরু, খরগোশ আর হরিণ গাছপালা খায়।"),
    mcq("How many legs does an insect have?", ["6", "4", "8", "2"], 0,
        "Insects like ants, bees and beetles have 6 legs. Spiders have 8 - they are not insects!",
        "একটি পোকার (কীটপতঙ্গ) কয়টি পা?", ["6", "4", "8", "2"],
        "পিঁপড়ে, মৌমাছি আর গুবরে পোকার মতো পতঙ্গের 6টি পা। মাকড়সার 8টি - তারা পতঙ্গ নয়!"),
    mcq("Why do we sleep at night?", ["To rest and let the body grow and repair", "Because the sun is noisy", "To get hungry", "Sleeping is not needed"], 0,
        "Sleep lets your body rest, grow and get ready for a new day.",
        "আমরা রাতে ঘুমাই কেন?", ["বিশ্রাম নিতে আর শরীরকে বাড়তে ও সারাতে দিতে", "সূর্য খুব শব্দ করে বলে", "খিদে পেতে", "ঘুমের দরকার নেই"],
        "ঘুম শরীরকে বিশ্রাম দেয়, বাড়তে দেয় আর নতুন দিনের জন্য তৈরি করে।"),
    mcq("Which part of your body helps you bend your arm?", ["Elbow", "Nose", "Ear", "Chin"], 0,
        "The elbow is a joint - a hinge where two bones meet so your arm can bend.",
        "শরীরের কোন অংশ হাত ভাঁজ করতে সাহায্য করে?", ["কনুই", "নাক", "কান", "চিবুক"],
        "কনুই একটা সন্ধি - কবজার মতো জায়গা, যেখানে দুটি হাড় মেলে, তাই হাত ভাঁজ হয়।"),
    mcq("Where does a bird usually lay its eggs?", ["In a nest", "In a cupboard", "In the river", "Underground in a tunnel always"], 0,
        "Birds build nests of twigs, grass and mud to keep their eggs safe and warm.",
        "পাখি সাধারণত কোথায় ডিম পাড়ে?", ["বাসায়", "আলমারিতে", "নদীতে", "সবসময় মাটির নিচের সুড়ঙ্গে"],
        "পাখি ডালপালা, ঘাস আর কাদা দিয়ে বাসা বানায়, যাতে ডিম নিরাপদ আর গরম থাকে।"),
    mcq("Which animal builds dams across rivers with sticks?", ["Beaver", "Cat", "Parrot", "Goldfish"], 0,
        "Beavers are nature's builders: they stack logs and mud to make dams and homes.",
        "কোন প্রাণী কাঠি দিয়ে নদীতে বাঁধ বানায়?", ["বিভার", "বিড়াল", "টিয়া", "সোনালি মাছ"],
        "বিভার প্রকৃতির মিস্ত্রি: কাঠের গুঁড়ি আর কাদা সাজিয়ে বাঁধ আর বাসা বানায়।"),
    mcq("What do bees collect from flowers?", ["Nectar and pollen", "Stones", "Water only", "Leaves"], 0,
        "Bees drink sweet nectar to make honey and carry pollen that helps flowers make seeds.",
        "মৌমাছি ফুল থেকে কী সংগ্রহ করে?", ["মধুরস আর পরাগরেণু", "পাথর", "শুধু জল", "পাতা"],
        "মৌমাছি মিষ্টি মধুরস খেয়ে মধু বানায়, আর পরাগরেণু বয়ে নিয়ে ফুলকে বীজ তৈরিতে সাহায্য করে।"),
    mcq("Why do cats have whiskers?", ["To feel their way in the dark", "To look like grandpa", "To catch fish", "To brush their teeth"], 0,
        "Whiskers sense tiny air movements and nearby objects, helping cats move in the dark.",
        "বিড়ালের গোঁফ থাকে কেন?", ["অন্ধকারে পথ বুঝতে", "দাদুর মতো দেখাতে", "মাছ ধরতে", "দাঁত মাজতে"],
        "গোঁফ বাতাসের সামান্য নড়াচড়া আর কাছের জিনিস টের পায়, তাই বিড়াল অন্ধকারে চলতে পারে।"),
    mcq("Which grows from a seed?", ["A plant", "A stone", "A car", "A cup"], 0,
        "Plant a seed, water it, give it light - a plant grows!",
        "বীজ থেকে কী জন্মায়?", ["গাছ", "পাথর", "গাড়ি", "কাপ"],
        "বীজ পুঁতে জল আর আলো দাও - গাছ জন্মাবে!"),
    mcq("What covers and protects your body?", ["Skin", "Shoes only", "Hair only", "A shell"], 0,
        "Skin is your body's waterproof, stretchy cover that keeps germs out.",
        "কী তোমার শরীর ঢেকে রক্ষা করে?", ["ত্বক", "শুধু জুতো", "শুধু চুল", "খোলস"],
        "ত্বক শরীরের জলরোধী, স্থিতিস্থাপক আবরণ, যা জীবাণু আটকায়।"),
    mcq("Which animal has a shell to carry its home?", ["Snail", "Dog", "Horse", "Monkey"], 0,
        "A snail's hard shell protects its soft body wherever it goes.",
        "কোন প্রাণী খোলসে তার বাড়ি বয়ে নিয়ে বেড়ায়?", ["শামুক", "কুকুর", "ঘোড়া", "বানর"],
        "শামুকের শক্ত খোলস তার নরম শরীরকে যেখানেই যাক রক্ষা করে।"),
    mcq("Why do we drink water every day?", ["Our body needs water to work", "To float", "To make us heavier only", "We do not need water"], 0,
        "Most of your body is water. Drinking keeps you healthy, especially when it is hot.",
        "আমরা প্রতিদিন জল খাই কেন?", ["শরীর চালাতে জল লাগে", "ভাসতে", "শুধু ভারী হতে", "আমাদের জল লাগে না"],
        "তোমার শরীরের বেশিরভাগটাই জল। জল খেলে সুস্থ থাকো, বিশেষ করে গরমে।"),
    mcq("Which part of the plant is usually green and makes food?", ["The leaf", "The root", "The seed", "The bark"], 0,
        "Leaves are green food factories: they use sunlight to make sugar for the plant.",
        "গাছের কোন অংশ সাধারণত সবুজ আর খাবার তৈরি করে?", ["পাতা", "শিকড়", "বীজ", "বাকল"],
        "পাতা সবুজ খাদ্য-কারখানা: সূর্যের আলো দিয়ে গাছের জন্য চিনি তৈরি করে।"),
    mcq("How does a fish breathe under water?", ["With gills", "With a nose like ours", "It holds its breath forever", "Through its tail"], 0,
        "Gills take oxygen out of the water as it flows through them.",
        "মাছ জলের নিচে কীভাবে শ্বাস নেয়?", ["কানকো দিয়ে", "আমাদের মতো নাক দিয়ে", "চিরকাল দম আটকে রাখে", "লেজ দিয়ে"],
        "কানকোর মধ্য দিয়ে জল বয়ে যাওয়ার সময় কানকো জল থেকে অক্সিজেন নেয়।"),
    mcq("Which helps a duck swim?", ["Webbed feet", "Long ears", "Sharp claws", "A trunk"], 0,
        "Webbed feet act like paddles, pushing water back so the duck moves forward.",
        "হাঁসকে সাঁতারে কী সাহায্য করে?", ["জোড়া-পর্দার পা", "লম্বা কান", "ধারালো নখ", "শুঁড়"],
        "পর্দাযুক্ত পা বৈঠার মতো কাজ করে, জল পেছনে ঠেলে হাঁসকে সামনে নেয়।"),
    mcq("What is the hardest part of your body?", ["Tooth enamel", "Ear lobe", "Nose tip", "Eyelid"], 0,
        "The enamel on your teeth is the hardest material in your body - harder than bone!",
        "তোমার শরীরের সবচেয়ে শক্ত অংশ কোনটা?", ["দাঁতের এনামেল", "কানের লতি", "নাকের ডগা", "চোখের পাতা"],
        "দাঁতের এনামেল শরীরের সবচেয়ে শক্ত উপাদান - হাড়ের চেয়েও শক্ত!"),
    mcq("Why do some animals sleep through winter?", ["To save energy when food is scarce", "Because they are lazy", "To grow wings", "To avoid baths"], 0,
        "Hibernating animals slow their bodies down to survive the cold months without much food.",
        "কিছু প্রাণী সারা শীত ঘুমিয়ে কাটায় কেন?", ["খাবার কম থাকলে শক্তি বাঁচাতে", "কারণ তারা অলস", "ডানা গজাতে", "স্নান এড়াতে"],
        "শীতঘুমে প্রাণীরা শরীর ধীর করে কম খাবারে ঠান্ডা মাসগুলো টিকে থাকে।"),
    mcq("Which body part do you use to smell a flower?", ["Nose", "Ears", "Feet", "Knees"], 0,
        "Your nose detects smells floating in the air.",
        "ফুলের গন্ধ নিতে কোন অঙ্গ ব্যবহার করো?", ["নাক", "কান", "পা", "হাঁটু"],
        "নাক বাতাসে ভাসা গন্ধ টের পায়।"),
    mcq("What helps a camel live in the hot desert?", ["It can go a long time without drinking", "It has gills", "It loves snow", "It eats sand"], 0,
        "Camels store fat in their humps and use water very carefully, so they survive in deserts.",
        "উট গরম মরুভূমিতে কীভাবে বাঁচে?", ["অনেকদিন জল না খেয়ে থাকতে পারে", "তার কানকো আছে", "তুষার ভালোবাসে", "বালি খায়"],
        "উট কুঁজে চর্বি জমায় আর খুব হিসাব করে জল খরচ করে, তাই মরুভূমিতে টিকে থাকে।"),
    mcq("What do baby mammals drink first?", ["Their mother's milk", "Juice", "Tea", "Rain only"], 0,
        "Mammals like cows, cats and humans feed their babies with milk.",
        "স্তন্যপায়ী প্রাণীর বাচ্চারা প্রথমে কী খায়?", ["মায়ের দুধ", "রস", "চা", "শুধু বৃষ্টির জল"],
        "গরু, বিড়াল আর মানুষের মতো স্তন্যপায়ীরা বাচ্চাদের দুধ খাওয়ায়।"),
    mcq("Why do we cover our mouth when we sneeze?", ["To stop spreading germs", "To make the sneeze louder", "To catch the sneeze for later", "No reason"], 0,
        "Sneezes spray tiny drops with germs. Covering your mouth protects others.",
        "হাঁচির সময় মুখ ঢাকি কেন?", ["জীবাণু ছড়ানো ঠেকাতে", "হাঁচি জোরে করতে", "হাঁচি পরে রাখার জন্য ধরে রাখতে", "কোনো কারণ নেই"],
        "হাঁচিতে জীবাণুসহ ছোট ছোট ফোঁটা ছিটকে যায়। মুখ ঢাকলে অন্যরা সুরক্ষিত থাকে।"),
    mcq("Which animal has stripes?", ["Zebra", "Elephant", "Cow", "Pigeon"], 0,
        "Zebras have black and white stripes - every zebra's pattern is different!",
        "কোন প্রাণীর গায়ে ডোরা দাগ?", ["জেব্রা", "হাতি", "গরু", "পায়রা"],
        "জেব্রার গায়ে সাদা-কালো ডোরা - প্রতিটি জেব্রার নকশা আলাদা!"),
    mcq("Which grows taller every year?", ["A young tree", "A rock", "A table", "A brick wall"], 0,
        "Trees keep growing a little each year. Rocks, tables and walls do not grow.",
        "কোনটা প্রতি বছর আরও লম্বা হয়?", ["ছোট গাছ", "পাথর", "টেবিল", "ইটের দেয়াল"],
        "গাছ প্রতি বছর একটু একটু বাড়ে। পাথর, টেবিল আর দেয়াল বাড়ে না।"),
    mcq("Why does a spider build a web?", ["To catch insects to eat", "To dry its clothes", "To sleep in a hammock", "To play music"], 0,
        "A spider's sticky web traps flying insects. Spider silk is incredibly strong for its weight.",
        "মাকড়সা জাল বোনে কেন?", ["খাওয়ার জন্য পোকা ধরতে", "জামা শুকাতে", "দোলনায় ঘুমাতে", "গান বাজাতে"],
        "মাকড়সার আঠালো জাল উড়ন্ত পোকা আটকায়। ওজনের তুলনায় মাকড়সার রেশম ভীষণ শক্ত।"),
    mcq("Which of these helps you stand tall?", ["Your backbone (spine)", "Your eyebrows", "Your fingernails", "Your hair"], 0,
        "Your backbone is a column of small bones - like a strong pillar holding up your body.",
        "এগুলোর কোনটা তোমাকে সোজা দাঁড়াতে সাহায্য করে?", ["মেরুদণ্ড", "ভুরু", "নখ", "চুল"],
        "মেরুদণ্ড ছোট ছোট হাড়ের একটা স্তম্ভ - যেন শরীর ধরে রাখা একটা মজবুত খুঁটি।"),
    mcq("Where do polar bears live?", ["In the icy Arctic", "In the hot desert", "In the rainforest", "Under the sea"], 0,
        "Polar bears have thick fur and fat to keep warm on the Arctic ice.",
        "মেরু ভালুক কোথায় থাকে?", ["বরফের সুমেরু অঞ্চলে", "গরম মরুভূমিতে", "বৃষ্টি-অরণ্যে", "সমুদ্রের নিচে"],
        "মেরু ভালুকের ঘন লোম আর চর্বি সুমেরুর বরফে তাকে গরম রাখে।"),
    mcq("Which animal can change its colour to hide?", ["Chameleon", "Cow", "Horse", "Sheep"], 0,
        "Chameleons can change colour to blend in, stay warm or show their mood.",
        "কোন প্রাণী লুকাতে রং বদলাতে পারে?", ["গিরগিটি", "গরু", "ঘোড়া", "ভেড়া"],
        "গিরগিটি মিশে যেতে, গরম থাকতে বা মেজাজ দেখাতে রং বদলাতে পারে।"),
    mcq("What do you need to wear on a very sunny day?", ["A hat and sun cream", "A raincoat", "Ice skates", "A scarf over your eyes"], 0,
        "A hat and sun cream protect your skin from strong sunlight.",
        "খুব রোদের দিনে কী পরা দরকার?", ["টুপি আর সানস্ক্রিন", "রেইনকোট", "বরফে স্কেট করার জুতো", "চোখের উপর মাফলার"],
        "টুপি আর সানস্ক্রিন কড়া রোদ থেকে ত্বক রক্ষা করে।"),
    mcq("Why do trees help us?", ["They give us fresh air (oxygen) and shade", "They make noise", "They block all light", "They eat our food"], 0,
        "Trees take in carbon dioxide and give out oxygen. They also give shade, fruit and wood.",
        "গাছ আমাদের কীভাবে সাহায্য করে?", ["টাটকা বাতাস (অক্সিজেন) আর ছায়া দেয়", "শব্দ করে", "সব আলো আটকায়", "আমাদের খাবার খায়"],
        "গাছ কার্বন ডাই-অক্সাইড নেয় আর অক্সিজেন দেয়। ছায়া, ফল আর কাঠও দেয়।"),
    mcq("Which of these is a fruit?", ["Mango", "Carrot", "Potato", "Onion"], 0,
        "A mango grows from a flower and holds a seed - that makes it a fruit.",
        "এগুলোর মধ্যে কোনটা ফল?", ["আম", "গাজর", "আলু", "পেঁয়াজ"],
        "আম ফুল থেকে জন্মায় আর ভেতরে বীজ থাকে - তাই এটা ফল।"),
    mcq("Which of these is a root we eat?", ["Carrot", "Apple", "Banana", "Grape"], 0,
        "A carrot is the root of the carrot plant. Yum!",
        "এগুলোর কোনটা আমরা শিকড় হিসেবে খাই?", ["গাজর", "আপেল", "কলা", "আঙুর"],
        "গাজর হলো গাজর গাছের শিকড়। খেতে দারুণ!"),
    mcq("How do frogs catch flies?", ["With a long sticky tongue", "With a net", "By barking", "By flying after them"], 0,
        "A frog flicks out its long sticky tongue super fast to grab insects.",
        "ব্যাঙ মাছি ধরে কীভাবে?", ["লম্বা আঠালো জিভ দিয়ে", "জাল দিয়ে", "ঘেউ ঘেউ করে", "পেছনে উড়ে গিয়ে"],
        "ব্যাঙ ভীষণ দ্রুত তার লম্বা আঠালো জিভ ছুড়ে পোকা ধরে।"),
    mcq("Which animal is the biggest on land?", ["Elephant", "Mouse", "Cat", "Rabbit"], 0,
        "Elephants are the largest land animals - a strong bridge is needed if one wants to cross!",
        "স্থলে কোন প্রাণী সবচেয়ে বড়?", ["হাতি", "ইঁদুর", "বিড়াল", "খরগোশ"],
        "হাতি স্থলের সবচেয়ে বড় প্রাণী - একটা পার হতে চাইলে মজবুত সেতু লাগবে!"),
    mcq("What happens to your heart when you run fast?", ["It beats faster", "It stops", "It gets smaller", "Nothing at all"], 0,
        "Running muscles need more oxygen, so the heart pumps faster to send more blood.",
        "জোরে দৌড়ালে হৃৎপিণ্ডের কী হয়?", ["দ্রুত ধুকপুক করে", "থেমে যায়", "ছোট হয়ে যায়", "কিছুই না"],
        "দৌড়ানো পেশির বেশি অক্সিজেন লাগে, তাই হৃৎপিণ্ড দ্রুত পাম্প করে বেশি রক্ত পাঠায়।"),
    mcq("Which helps a tortoise stay safe?", ["Its hard shell", "Its speed", "Its long neck for running", "Its wings"], 0,
        "A tortoise is slow, so its strong shell is its armour. It tucks inside when danger comes.",
        "কচ্ছপকে নিরাপদ রাখে কী?", ["তার শক্ত খোলস", "তার গতি", "দৌড়ানোর লম্বা গলা", "তার ডানা"],
        "কচ্ছপ ধীর, তাই শক্ত খোলসই তার বর্ম। বিপদ এলে ভেতরে ঢুকে পড়ে।"),
    mcq("Which animal makes silk?", ["Silkworm", "Cow", "Fish", "Goat"], 0,
        "Silkworms spin cocoons of silk thread, which people use to make silk cloth.",
        "কোন প্রাণী রেশম তৈরি করে?", ["রেশমপোকা", "গরু", "মাছ", "ছাগল"],
        "রেশমপোকা রেশমের সুতো দিয়ে গুটি বোনে, যা দিয়ে মানুষ রেশমের কাপড় বানায়।"),
    mcq("How many teeth does an adult usually have?", ["32", "10", "100", "5"], 0,
        "Grown-ups usually have 32 teeth. Children have 20 milk teeth.",
        "একজন প্রাপ্তবয়স্কের সাধারণত কয়টি দাঁত?", ["32", "10", "100", "5"],
        "বড়দের সাধারণত 32টি দাঁত। শিশুদের 20টি দুধদাঁত।"),
    mcq("Why do we get hungry?", ["Our body needs food for energy", "Our stomach is bored", "We sleep too much", "Because of the moon"], 0,
        "Food is the body's fuel. Hunger tells you it is time to refuel.",
        "আমাদের খিদে পায় কেন?", ["শক্তির জন্য শরীরের খাবার লাগে", "পেটের একঘেয়ে লাগে", "বেশি ঘুমাই বলে", "চাঁদের জন্য"],
        "খাবার শরীরের জ্বালানি। খিদে জানিয়ে দেয় আবার জ্বালানি ভরার সময় হয়েছে।"),
    mcq("Which of these lays eggs?", ["Crocodile", "Cow", "Dog", "Elephant"], 0,
        "Crocodiles lay eggs in nests by the river. Cows, dogs and elephants give birth to babies.",
        "এগুলোর কোনটা ডিম পাড়ে?", ["কুমির", "গরু", "কুকুর", "হাতি"],
        "কুমির নদীর ধারে বাসায় ডিম পাড়ে। গরু, কুকুর আর হাতি বাচ্চা জন্ম দেয়।"),
    mcq("Why do owls hunt at night?", ["They see very well in the dark", "They are afraid of the sun", "Mice only come out in the morning", "They cannot fly in the day"], 0,
        "Owls have huge eyes and super hearing, perfect for finding food in the dark.",
        "পেঁচা রাতে শিকার করে কেন?", ["অন্ধকারে খুব ভালো দেখে", "সূর্যকে ভয় পায়", "ইঁদুর শুধু সকালে বেরোয়", "দিনে উড়তে পারে না"],
        "পেঁচার বিশাল চোখ আর দারুণ শ্রবণশক্তি, অন্ধকারে খাবার খোঁজার জন্য একদম ঠিক।"),
    mcq("Which helps you taste food?", ["Your tongue", "Your elbow", "Your hair", "Your knee"], 0,
        "Your tongue has thousands of taste buds for sweet, sour, salty and bitter.",
        "খাবারের স্বাদ নিতে কী সাহায্য করে?", ["জিভ", "কনুই", "চুল", "হাঁটু"],
        "তোমার জিভে মিষ্টি, টক, নোনতা আর তেতোর জন্য হাজার হাজার স্বাদকোরক আছে।"),
    mcq("Which animal hops and carries its baby in a pouch?", ["Kangaroo", "Dog", "Horse", "Pig"], 0,
        "Baby kangaroos (joeys) grow inside their mother's pouch.",
        "কোন প্রাণী লাফিয়ে চলে আর থলিতে বাচ্চা বয়?", ["ক্যাঙারু", "কুকুর", "ঘোড়া", "শূকর"],
        "ক্যাঙারুর বাচ্চা (জোয়ি) মায়ের থলির ভেতরে বড় হয়।"),
    mcq("What happens to a plant with no water for many days?", ["It wilts and may die", "It grows faster", "It turns blue", "It flies away"], 0,
        "Without water, a plant droops (wilts) and cannot make food.",
        "অনেকদিন জল না পেলে গাছের কী হয়?", ["নেতিয়ে পড়ে মরে যেতে পারে", "দ্রুত বাড়ে", "নীল হয়ে যায়", "উড়ে যায়"],
        "জল ছাড়া গাছ নেতিয়ে পড়ে আর খাবার তৈরি করতে পারে না।"),
    mcq("Which part of the body holds the brain?", ["The skull", "The knee", "The foot", "The stomach"], 0,
        "The skull is a hard bony helmet that protects your brain.",
        "শরীরের কোন অংশে মস্তিষ্ক থাকে?", ["মাথার খুলি", "হাঁটু", "পা", "পেট"],
        "খুলি হলো শক্ত হাড়ের হেলমেট, যা মস্তিষ্ক রক্ষা করে।"),
    mcq("Which animal is known for building strong hexagon-shaped wax cells?", ["Honeybee", "Cow", "Snake", "Owl"], 0,
        "Bees build honeycombs of hexagons - a shape that uses little wax and stays strong. Engineers copy it!",
        "কোন প্রাণী মজবুত ষড়ভুজ আকারের মোমের ঘর বানাতে বিখ্যাত?", ["মৌমাছি", "গরু", "সাপ", "পেঁচা"],
        "মৌমাছি ষড়ভুজের মৌচাক বানায় - এমন আকার যাতে কম মোম লাগে আর মজবুত থাকে। প্রকৌশলীরা এটা নকল করেন!"),
    mcq("Why do we exercise?", ["To keep our body and heart strong", "To get dirty only", "To sleep less", "Exercise is bad"], 0,
        "Running, jumping and playing make muscles, bones and heart stronger.",
        "আমরা ব্যায়াম করি কেন?", ["শরীর আর হৃৎপিণ্ড শক্ত রাখতে", "শুধু নোংরা হতে", "কম ঘুমাতে", "ব্যায়াম খারাপ"],
        "দৌড়ানো, লাফানো আর খেলা পেশি, হাড় আর হৃৎপিণ্ডকে শক্ত করে।"),
    mcq("Which of these needs food to live?", ["A rabbit", "A rock", "A chair", "A pencil"], 0,
        "All living things need food. A rabbit eats grass and carrots.",
        "এগুলোর কোনটার বাঁচতে খাবার লাগে?", ["খরগোশ", "পাথর", "চেয়ার", "পেনসিল"],
        "সব জীবের খাবার লাগে। খরগোশ ঘাস আর গাজর খায়।"),
    mcq("Which body part helps you walk?", ["Legs", "Ears", "Eyebrows", "Lips"], 0,
        "Legs with strong bones and muscles carry you around - like the pillars of a bridge.",
        "কোন অঙ্গ হাঁটতে সাহায্য করে?", ["পা", "কান", "ভুরু", "ঠোঁট"],
        "শক্ত হাড় আর পেশির পা তোমাকে বয়ে নিয়ে বেড়ায় - সেতুর স্তম্ভের মতো।"),
    mcq("What is a group of fish called?", ["A school", "A herd", "A flock", "A pack"], 0,
        "Fish swim together in a school. Cows form herds, birds form flocks, wolves form packs.",
        "মাছের দলকে কী বলে?", ["ঝাঁক", "পাল (গরুর)", "দঙ্গল", "নেকড়ের দল"],
        "মাছ একসঙ্গে ঝাঁকে সাঁতার কাটে। গরু পালে থাকে, পাখি দঙ্গলে, নেকড়ে দলে।"),
    mcq("Which helps an elephant drink water?", ["Its trunk", "Its tail", "Its ears", "Its toenails"], 0,
        "An elephant sucks water into its trunk and squirts it into its mouth.",
        "হাতিকে জল খেতে কী সাহায্য করে?", ["তার শুঁড়", "তার লেজ", "তার কান", "তার পায়ের নখ"],
        "হাতি শুঁড়ে জল টেনে নিয়ে মুখে ছিটিয়ে দেয়।"),
    mcq("Why are flowers colourful and sweet-smelling?", ["To attract bees and butterflies", "To scare birds", "To hide from the sun", "For no reason"], 0,
        "Bright colours and smells invite insects, which carry pollen from flower to flower.",
        "ফুল রঙিন আর সুগন্ধি কেন?", ["মৌমাছি আর প্রজাপতিকে টানতে", "পাখি তাড়াতে", "সূর্য থেকে লুকাতে", "কোনো কারণ নেই"],
        "উজ্জ্বল রং আর গন্ধ পোকাদের ডাকে, যারা এক ফুল থেকে আরেক ফুলে পরাগরেণু নিয়ে যায়।"),
    mcq("Which is a good habit before eating?", ["Washing hands with soap", "Playing in mud", "Licking the floor", "Petting a frog"], 0,
        "Clean hands keep germs out of your food and your tummy.",
        "খাওয়ার আগে কোনটা ভালো অভ্যাস?", ["সাবান দিয়ে হাত ধোয়া", "কাদায় খেলা", "মেঝে চাটা", "ব্যাঙকে আদর করা"],
        "পরিষ্কার হাত তোমার খাবার আর পেট থেকে জীবাণু দূরে রাখে।"),
    mcq("What does a seed need first to start growing?", ["Water and warmth", "Loud music", "Ice", "Darkness forever"], 0,
        "With water and warmth, a seed wakes up (germinates) and sends out a root and a shoot.",
        "বীজের অঙ্কুরিত হতে প্রথমে কী লাগে?", ["জল আর উষ্ণতা", "জোরে গান", "বরফ", "চিরকাল অন্ধকার"],
        "জল আর উষ্ণতা পেলে বীজ জেগে ওঠে (অঙ্কুরিত হয়) আর শিকড় ও কাণ্ড বের করে।"),
    mcq("Which animal is a bird that cannot fly?", ["Penguin", "Sparrow", "Eagle", "Parrot"], 0,
        "Penguins are birds, but they use their wings as flippers to swim instead of fly.",
        "কোন পাখি উড়তে পারে না?", ["পেঙ্গুইন", "চড়ুই", "ঈগল", "টিয়া"],
        "পেঙ্গুইন পাখি, কিন্তু ডানা দিয়ে ওড়ার বদলে পাখনার মতো সাঁতার কাটে।"),
    mcq("Where does a rabbit live?", ["In a burrow under the ground", "In a nest on a tree", "In the sea", "In a beehive"], 0,
        "Rabbits dig burrows - tunnels under the ground - to stay safe.",
        "খরগোশ কোথায় থাকে?", ["মাটির নিচে গর্তে", "গাছের বাসায়", "সমুদ্রে", "মৌচাকে"],
        "খরগোশ নিরাপদে থাকতে গর্ত খোঁড়ে - মাটির নিচের সুড়ঙ্গ।"),
    mcq("Why do we have muscles?", ["To move our bones", "To smell", "To see colours", "To grow hair"], 0,
        "Muscles pull on bones to make them move - like cables pulling on a bridge.",
        "আমাদের পেশি থাকে কেন?", ["হাড় নাড়াতে", "গন্ধ নিতে", "রং দেখতে", "চুল গজাতে"],
        "পেশি হাড় টেনে নাড়ায় - যেমন তার সেতুকে টানে।"),
    mcq("Which of these is a vegetable?", ["Spinach", "Chocolate", "Candy floss", "Biscuit"], 0,
        "Spinach is a leafy vegetable full of goodness.",
        "এগুলোর কোনটা সবজি?", ["পালং শাক", "চকলেট", "হাওয়াই মিঠাই", "বিস্কুট"],
        "পালং শাক পাতাওয়ালা সবজি, পুষ্টিতে ভরা।"),
    mcq("How do plants drink water?", ["Through their roots", "Through their flowers", "Through a straw", "They do not drink"], 0,
        "Roots soak up water from the soil, and it travels up the stem to the leaves.",
        "গাছ কীভাবে জল খায়?", ["শিকড় দিয়ে", "ফুল দিয়ে", "স্ট্র দিয়ে", "গাছ জল খায় না"],
        "শিকড় মাটি থেকে জল শুষে নেয়, আর তা কাণ্ড বেয়ে পাতায় ওঠে।"),
    mcq("Which animal is a reptile?", ["Lizard", "Dog", "Sparrow", "Cow"], 0,
        "Reptiles like lizards, snakes and crocodiles have dry scaly skin.",
        "কোন প্রাণী সরীসৃপ?", ["টিকটিকি", "কুকুর", "চড়ুই", "গরু"],
        "টিকটিকি, সাপ আর কুমিরের মতো সরীসৃপের শুকনো আঁশওয়ালা চামড়া।"),
    mcq("What keeps a dog warm?", ["Its fur", "Its tail only", "Its bark", "Its shadow"], 0,
        "Fur traps warm air next to the skin, like a cosy coat.",
        "কুকুরকে গরম রাখে কী?", ["তার লোম", "শুধু তার লেজ", "তার ঘেউ ঘেউ", "তার ছায়া"],
        "লোম ত্বকের পাশে গরম বাতাস আটকে রাখে, আরামদায়ক কোটের মতো।"),
    mcq("Which animal sleeps hanging upside down?", ["Bat", "Cow", "Fish", "Hen"], 0,
        "Bats hang upside down from their feet to rest - and drop into flight easily.",
        "কোন প্রাণী উল্টো ঝুলে ঘুমায়?", ["বাদুড়", "গরু", "মাছ", "মুরগি"],
        "বাদুড় পা দিয়ে উল্টো ঝুলে বিশ্রাম নেয় - আর সহজেই উড়তে নেমে পড়ে।"),
    mcq("How do birds keep their eggs warm?", ["They sit on them", "They put them in the fridge", "They bury them in snow", "They leave them in the rain"], 0,
        "Birds sit on their eggs so their body heat keeps the chicks growing inside.",
        "পাখি কীভাবে ডিম গরম রাখে?", ["ডিমের উপর বসে", "ফ্রিজে রেখে", "তুষারে পুঁতে", "বৃষ্টিতে ফেলে রেখে"],
        "পাখি ডিমের উপর বসে, যাতে শরীরের তাপে ভেতরের ছানা বাড়তে থাকে।"),
    mcq("Which animal is known as the 'ship of the desert'?", ["Camel", "Whale", "Dolphin", "Penguin"], 0,
        "Camels carry people and loads across deserts, like ships cross the sea.",
        "কোন প্রাণীকে 'মরুভূমির জাহাজ' বলা হয়?", ["উট", "তিমি", "ডলফিন", "পেঙ্গুইন"],
        "উট মরুভূমি পেরিয়ে মানুষ আর মাল বয়, যেমন জাহাজ সমুদ্র পেরোয়।"),
    mcq("Which part of the tree is the hard outer covering?", ["Bark", "Leaf", "Petal", "Fruit"], 0,
        "Bark is the tree's tough skin that protects it from insects and weather.",
        "গাছের শক্ত বাইরের আবরণ কোনটা?", ["বাকল", "পাতা", "পাপড়ি", "ফল"],
        "বাকল গাছের শক্ত চামড়া, যা পোকা আর আবহাওয়া থেকে রক্ষা করে।"),
    mcq("What do you call a young frog with a tail that lives in water?", ["Tadpole", "Puppy", "Kitten", "Foal"], 0,
        "A tadpole is a baby frog. It breathes with gills until it grows lungs.",
        "জলে থাকা লেজওয়ালা ছোট ব্যাঙকে কী বলে?", ["ব্যাঙাচি", "কুকুরছানা", "বিড়ালছানা", "ঘোড়ার বাচ্চা"],
        "ব্যাঙাচি হলো ব্যাঙের বাচ্চা। ফুসফুস না হওয়া পর্যন্ত কানকো দিয়ে শ্বাস নেয়।"),
    mcq("Why do people wear helmets on bikes?", ["To protect the head if they fall", "To look tall", "To keep hair dry only", "Helmets are for decoration"], 0,
        "A helmet is a hard shell that spreads out a bump and protects your brain - like a skull outside your skull!",
        "মানুষ সাইকেলে হেলমেট পরে কেন?", ["পড়ে গেলে মাথা রক্ষা করতে", "লম্বা দেখাতে", "শুধু চুল শুকনো রাখতে", "হেলমেট শুধু সাজের জন্য"],
        "হেলমেট একটা শক্ত খোলস, যা ধাক্কা ছড়িয়ে দেয় আর মস্তিষ্ক রক্ষা করে - খুলির বাইরে আরেকটা খুলি!"),
    mcq("What do roots and building foundations have in common?", ["Both hold things firmly in the ground", "Both are green", "Both grow flowers", "Both are made of steel"], 0,
        "Roots anchor a tree; foundations anchor a building or bridge. Without them, both would topple.",
        "শিকড় আর বাড়ির ভিতের মধ্যে মিল কী?", ["দুটোই জিনিসকে মাটিতে শক্ত করে ধরে রাখে", "দুটোই সবুজ", "দুটোতেই ফুল ফোটে", "দুটোই ইস্পাতের"],
        "শিকড় গাছকে নোঙর করে; ভিত বাড়ি বা সেতুকে নোঙর করে। এগুলো না থাকলে দুটোই উল্টে পড়ত।"),
    mcq("Which animal has 8 arms and lives in the sea?", ["Octopus", "Starfish with 5", "Crab", "Whale"], 0,
        "Octo means eight. An octopus has eight long arms with suckers.",
        "কোন প্রাণীর 8টি বাহু আর সমুদ্রে থাকে?", ["অক্টোপাস", "5 বাহুর তারামাছ", "কাঁকড়া", "তিমি"],
        "'অক্টো' মানে আট। অক্টোপাসের চোষকওয়ালা আটটি লম্বা বাহু।"),
    mcq("Why do leaves fall from some trees in autumn?", ["The tree rests for winter and saves water", "The wind is angry", "Leaves get bored", "Birds pull them"], 0,
        "Many trees drop their leaves before winter to save water and energy, and grow new ones in spring.",
        "শরতে কিছু গাছের পাতা ঝরে পড়ে কেন?", ["শীতের জন্য গাছ বিশ্রাম নেয় আর জল বাঁচায়", "বাতাস রেগে যায়", "পাতাদের একঘেয়ে লাগে", "পাখিরা টানে"],
        "অনেক গাছ শীতের আগে জল আর শক্তি বাঁচাতে পাতা ঝরিয়ে দেয়, আর বসন্তে নতুন পাতা গজায়।"),
    mcq("What is the best way to stay healthy?", ["Eat well, sleep well, play and keep clean", "Eat only sweets", "Never go outside", "Stay up all night"], 0,
        "Good food, sleep, exercise and washing hands keep your body strong.",
        "সুস্থ থাকার সবচেয়ে ভালো উপায় কী?", ["ভালো খাও, ভালো ঘুমাও, খেলো আর পরিষ্কার থাকো", "শুধু মিষ্টি খাও", "কখনো বাইরে যেয়ো না", "সারারাত জেগে থাকো"],
        "ভালো খাবার, ঘুম, ব্যায়াম আর হাত ধোয়া শরীরকে শক্ত রাখে।"),
    mcq("Which animal walks on the ceiling without falling?", ["A gecko (house lizard)", "A cow", "A dog", "A horse"], 0,
        "Geckos have millions of tiny hairs on their toes that cling to surfaces.",
        "কোন প্রাণী না পড়ে ছাদে হাঁটে?", ["টিকটিকি", "গরু", "কুকুর", "ঘোড়া"],
        "টিকটিকির পায়ের আঙুলে লাখ লাখ ছোট্ট রোম, যা তলে আটকে থাকে।"),
    mcq("Which is the right order of growing up?", ["Baby, child, adult", "Adult, baby, child", "Child, adult, baby", "Baby, adult, child"], 0,
        "People grow from babies into children and then into adults.",
        "বড় হওয়ার সঠিক ক্রম কোনটা?", ["শিশু, কিশোর, প্রাপ্তবয়স্ক", "প্রাপ্তবয়স্ক, শিশু, কিশোর", "কিশোর, প্রাপ্তবয়স্ক, শিশু", "শিশু, প্রাপ্তবয়স্ক, কিশোর"],
        "মানুষ শিশু থেকে কিশোর আর তারপর প্রাপ্তবয়স্ক হয়।"),
    mcq("Which helps a woodpecker find food?", ["Its strong beak drills into tree bark", "Its long legs", "Its swimming fins", "Its loud moo"], 0,
        "A woodpecker hammers its tough beak into bark to find insects - its skull is built like a shock absorber!",
        "কাঠঠোকরাকে খাবার খুঁজতে কী সাহায্য করে?", ["শক্ত ঠোঁটে গাছের বাকল ফুটো করে", "লম্বা পা", "সাঁতারের পাখনা", "জোরে হাম্বা"],
        "কাঠঠোকরা শক্ত ঠোঁট দিয়ে বাকলে ঠুকে পোকা খোঁজে - তার খুলি ধাক্কা-শোষকের মতো বানানো!"),
    mcq("What does a plant give out that we breathe?", ["Oxygen", "Smoke", "Sand", "Salt"], 0,
        "Plants make oxygen while making food. Every breath you take thanks a plant!",
        "গাছ কী ছাড়ে যা আমরা শ্বাসে নিই?", ["অক্সিজেন", "ধোঁয়া", "বালি", "নুন"],
        "খাবার তৈরির সময় গাছ অক্সিজেন তৈরি করে। তোমার প্রতিটি নিঃশ্বাসে গাছকে ধন্যবাদ!"),
    mcq("Which is a sea animal?", ["Dolphin", "Cow", "Goat", "Camel"], 0,
        "Dolphins live in the sea but breathe air through a blowhole on top of their head.",
        "কোনটা সামুদ্রিক প্রাণী?", ["ডলফিন", "গরু", "ছাগল", "উট"],
        "ডলফিন সমুদ্রে থাকে কিন্তু মাথার উপরের ছিদ্র দিয়ে বাতাসে শ্বাস নেয়।"),
    mcq("What do we call animals that eat both plants and meat?", ["Omnivores", "Herbivores", "Carnivores", "Vegetables"], 0,
        "Omnivores, like bears and people, eat both plants and meat.",
        "যে প্রাণী গাছপালা আর মাংস দুই-ই খায় তাদের কী বলে?", ["সর্বভুক", "তৃণভোজী", "মাংসাশী", "সবজি"],
        "সর্বভুক, যেমন ভালুক আর মানুষ, গাছপালা আর মাংস দুই-ই খায়।"),
)
