"""Class 1 - Commercials: shops and markets, buyers and sellers, goods, deliveries and adverts."""
from . import mcq

ITEMS = (
    mcq("Why does the shopkeeper put sweets right next to the checkout where you wait in line?",
        ["To tempt you while you are bored waiting", "Because sweets like queues", "To keep them cold", "By accident"], 0,
        "It is called impulse marketing: things placed where you wait are easy to grab without planning.",
        "দোকানদার লজেন্স ঠিক বিল-কাউন্টারের পাশে রাখেন, যেখানে তুমি লাইনে দাঁড়াও। কেন?",
        ["অপেক্ষার একঘেয়েমিতে লোভ দেখাতে", "কারণ লজেন্স লাইন ভালোবাসে", "ঠান্ডা রাখতে", "ভুল করে"],
        "একে বলে আচমকা কেনার কৌশল: যেখানে অপেক্ষা করো সেখানে রাখা জিনিস পরিকল্পনা ছাড়াই হাতে তুলে নেওয়া সহজ।"),
    mcq("What is a shop?", ["A place where things are sold", "A place to sleep", "A kind of tree", "A river"], 0,
        "A shop sells goods to people who want to buy them.",
        "দোকান কী?", ["যেখানে জিনিস বিক্রি হয়", "ঘুমানোর জায়গা", "এক রকম গাছ", "একটা নদী"],
        "দোকান সেইসব মানুষকে জিনিস বিক্রি করে যারা কিনতে চায়।"),
    mcq("The person who buys something is called a...", ["Customer (buyer)", "Seller", "Driver", "Doctor"], 0,
        "A customer buys; a seller (shopkeeper) sells.",
        "যে কিছু কেনে তাকে বলে...", ["ক্রেতা (খদ্দের)", "বিক্রেতা", "চালক", "ডাক্তার"],
        "খদ্দের কেনে; বিক্রেতা (দোকানদার) বেচে।"),
    mcq("The person who sells things in a shop is the...", ["Shopkeeper", "Customer", "Postman", "Pilot"], 0,
        "The shopkeeper sells goods and takes the money.",
        "দোকানে যে জিনিস বেচে সে হলো...", ["দোকানদার", "খদ্দের", "ডাকপিয়ন", "পাইলট"],
        "দোকানদার জিনিস বিক্রি করে আর টাকা নেন।"),
    mcq("Where can you buy fresh fruit and vegetables from many sellers?", ["A market", "A library", "A hospital", "A bus stop"], 0,
        "A market has many stalls selling fresh food side by side.",
        "অনেক বিক্রেতার কাছ থেকে টাটকা ফল আর সবজি কোথায় কেনা যায়?", ["বাজারে", "লাইব্রেরিতে", "হাসপাতালে", "বাসস্টপে"],
        "বাজারে পাশাপাশি অনেক দোকানে টাটকা খাবার বিক্রি হয়।"),
    mcq("What is 'trading' or 'swapping'?", ["Giving something to get something else", "Breaking toys", "Sleeping", "Painting"], 0,
        "Trading means swapping: your marble for a friend's sticker. Long ago, people traded before money existed.",
        "'বিনিময়' বা 'অদলবদল' কী?", ["কিছু দিয়ে অন্য কিছু নেওয়া", "খেলনা ভাঙা", "ঘুমানো", "রং করা"],
        "বিনিময় মানে অদলবদল: তোমার মার্বেল বন্ধুর স্টিকারের বদলে। অনেক আগে টাকা আসার আগে মানুষ বিনিময় করত।"),
    mcq("A farmer grows mangoes and sells them at the market. What is the farmer?", ["A seller (producer)", "A customer", "A bridge", "A teacher"], 0,
        "The farmer produces mangoes and sells them - a producer and a seller.",
        "একজন চাষি আম ফলিয়ে বাজারে বিক্রি করেন। চাষি কী?", ["বিক্রেতা (উৎপাদক)", "খদ্দের", "সেতু", "শিক্ষক"],
        "চাষি আম উৎপাদন করে বিক্রি করেন - উৎপাদক আর বিক্রেতা দুই-ই।"),
    mcq("How do vegetables get from farms to city shops?", ["Trucks carry them along roads and over bridges", "They walk", "They fly by themselves", "They grow in the shop"], 0,
        "Delivery trucks carry goods. Good roads and strong bridges keep shops full.",
        "সবজি খামার থেকে শহরের দোকানে কীভাবে আসে?", ["ট্রাক রাস্তা আর সেতু দিয়ে বয়ে আনে", "হেঁটে আসে", "নিজেরাই উড়ে আসে", "দোকানেই জন্মায়"],
        "ডেলিভারি ট্রাক মাল বয়ে আনে। ভালো রাস্তা আর মজবুত সেতু দোকান ভরা রাখে।"),
    mcq("What is an advert (advertisement)?", ["A message telling people about something to buy", "A type of food", "A school rule", "A game of football"], 0,
        "Adverts on TV, posters and phones tell you about products and try to make you want them.",
        "বিজ্ঞাপন কী?", ["কেনার মতো জিনিস সম্পর্কে মানুষকে জানানো বার্তা", "এক রকম খাবার", "স্কুলের নিয়ম", "ফুটবল খেলা"],
        "টিভি, পোস্টার আর ফোনে বিজ্ঞাপন জিনিসের কথা জানায় আর তা কিনতে ইচ্ছা জাগাতে চায়।"),
    mcq("Why do shops put colourful pictures on their boxes?", ["To catch your eye and make you want to buy", "To make the box heavier", "Because boxes are sad", "To hide the price"], 0,
        "Bright packaging grabs attention on a busy shelf.",
        "দোকানের বাক্সে রঙিন ছবি থাকে কেন?", ["চোখ টানতে আর কেনার ইচ্ছা জাগাতে", "বাক্স ভারী করতে", "কারণ বাক্সের মন খারাপ", "দাম লুকাতে"],
        "ঝলমলে মোড়ক ভিড়ের তাকে নজর কাড়ে।"),
    mcq("A shop has run out of milk. We say the milk is...", ["Sold out", "Free", "Cheaper", "Bigger"], 0,
        "Sold out means every one has been bought. The shop must order more.",
        "একটা দোকানে দুধ শেষ। আমরা বলি দুধ...", ["ফুরিয়ে গেছে (বিক্রি শেষ)", "বিনামূল্যে", "সস্তা", "বড়"],
        "বিক্রি শেষ মানে সবগুলো বিক্রি হয়ে গেছে। দোকানকে আরও আনাতে হবে।"),
    mcq("What do you get from the shop to show what you paid?", ["A receipt", "A ticket to the moon", "A sticker only", "Nothing"], 0,
        "A receipt lists what you bought and how much you paid.",
        "কত টাকা দিলে তা দেখাতে দোকান থেকে কী পাও?", ["রসিদ", "চাঁদে যাওয়ার টিকিট", "শুধু স্টিকার", "কিছুই না"],
        "রসিদে লেখা থাকে কী কিনলে আর কত দিলে।"),
    mcq("You set up a lemonade stand. What do you need to sell?", ["Lemonade and cups", "A bridge", "A train", "A rocket"], 0,
        "Your product is lemonade - you need lemons, water, sugar, cups and a sign!",
        "তুমি একটা শরবতের দোকান দিলে। বিক্রির জন্য কী লাগবে?", ["শরবত আর কাপ", "একটা সেতু", "একটা ট্রেন", "একটা রকেট"],
        "তোমার পণ্য হলো শরবত - লাগবে লেবু, জল, চিনি, কাপ আর একটা সাইনবোর্ড!"),
    mcq("Why would a lemonade stand sell more on a hot day?", ["People are thirsty and want a cold drink", "Lemons are bigger on hot days", "Cups are cheaper", "Nobody buys on hot days"], 0,
        "More people want lemonade when it is hot - demand goes up.",
        "গরমের দিনে শরবতের দোকানে বিক্রি বেশি হবে কেন?", ["মানুষের তেষ্টা পায় আর ঠান্ডা পানীয় চায়", "গরমে লেবু বড় হয়", "কাপ সস্তা হয়", "গরমে কেউ কেনে না"],
        "গরমে বেশি মানুষ শরবত চায় - চাহিদা বাড়ে।"),
    mcq("A sign says 'OPEN 9 to 5'. When can you shop there?", ["Between 9 in the morning and 5 in the evening", "Only at midnight", "Never", "Only on the moon"], 0,
        "Opening hours tell you when the shop is open for customers.",
        "একটা বোর্ডে লেখা 'খোলা 9টা থেকে 5টা'। সেখানে কখন কেনাকাটা করা যায়?", ["সকাল 9টা থেকে বিকেল 5টার মধ্যে", "শুধু মাঝরাতে", "কখনো না", "শুধু চাঁদে"],
        "খোলার সময় জানায় দোকান খদ্দেরদের জন্য কখন খোলা।"),
    mcq("Why do people stand in a queue at a shop?", ["To be served fairly, one by one", "To play a game", "To sleep", "To dance"], 0,
        "A queue makes sure everyone gets their turn in order.",
        "দোকানে মানুষ লাইনে দাঁড়ায় কেন?", ["একে একে ন্যায্যভাবে পরিষেবা পেতে", "খেলা খেলতে", "ঘুমাতে", "নাচতে"],
        "লাইন নিশ্চিত করে সবাই ক্রমানুসারে পালা পায়।"),
    mcq("What does 'SALE' on a shop window usually mean?", ["Some prices are lower than usual", "Everything is more expensive", "The shop is closed forever", "Nothing is for sale"], 0,
        "A sale means discounts - things cost less for a while.",
        "দোকানের জানালায় 'সেল' লেখা থাকলে সাধারণত কী বোঝায়?", ["কিছু জিনিসের দাম সাধারণের চেয়ে কম", "সব কিছুর দাম বেশি", "দোকান চিরতরে বন্ধ", "কিছুই বিক্রির জন্য নয়"],
        "সেল মানে ছাড় - কিছু সময়ের জন্য জিনিসের দাম কম।"),
    mcq("Who makes bread for a bakery shop?", ["A baker", "A pilot", "A painter of walls", "A fisherman"], 0,
        "Bakers bake bread and cakes, and the bakery sells them.",
        "বেকারির দোকানের জন্য পাউরুটি কে বানান?", ["বেকার (রুটিওয়ালা)", "পাইলট", "দেয়াল রং-মিস্ত্রি", "জেলে"],
        "বেকার পাউরুটি আর কেক বানান, আর বেকারি তা বিক্রি করে।"),
    mcq("A bakery van crosses a bridge every morning. Why does the bridge matter to the bakery?", ["It is the way to reach customers in the village", "Vans like bridges", "It makes bread rise", "It does not matter"], 0,
        "No bridge, no delivery - and no fresh bread for the village! (That is Level 1 of MODIS BridgeWorks.)",
        "একটা বেকারির ভ্যান প্রতি সকালে সেতু পার হয়। বেকারির কাছে সেতুর গুরুত্ব কী?", ["গ্রামের খদ্দেরদের কাছে পৌঁছানোর পথ", "ভ্যান সেতু ভালোবাসে", "পাউরুটি ফোলায়", "কোনো গুরুত্ব নেই"],
        "সেতু নেই তো ডেলিভারি নেই - গ্রামে টাটকা রুটিও নেই! (এটাই MODIS BridgeWorks-এর লেভেল 1।)"),
    mcq("If many people want a toy but there are only a few, what may happen to its price?", ["It may go up", "It becomes free", "It always goes down", "It disappears"], 0,
        "When lots of people want something rare, sellers can ask a higher price.",
        "অনেক মানুষ একটা খেলনা চায় কিন্তু আছে মাত্র কয়েকটা। দামের কী হতে পারে?", ["বাড়তে পারে", "বিনামূল্যে হয়ে যায়", "সবসময় কমে", "উধাও হয়ে যায়"],
        "অনেকে কোনো দুর্লভ জিনিস চাইলে বিক্রেতা বেশি দাম চাইতে পারেন।"),
    mcq("A shop buys a pen for Rs 5 and sells it for Rs 7. How much more does it get than it paid?", ["Rs 2", "Rs 12", "Rs 7", "Rs 5"], 0,
        "7 - 5 = Rs 2. That extra is called profit - it pays the shopkeeper for their work.",
        "একটা দোকান 5 টাকায় কলম কিনে 7 টাকায় বেচে। যা দিয়েছিল তার চেয়ে কত বেশি পায়?", ["2 টাকা", "12 টাকা", "7 টাকা", "5 টাকা"],
        "7 - 5 = 2 টাকা। এই বাড়তিটাকে বলে লাভ - এতে দোকানদারের কাজের দাম ওঠে।"),
    mcq("What do we call goods brought from another country?", ["Imports", "Homework", "Exports", "Weather"], 0,
        "Imports come in from other countries; exports are sent out to other countries.",
        "অন্য দেশ থেকে আনা জিনিসকে কী বলে?", ["আমদানি", "বাড়ির কাজ", "রপ্তানি", "আবহাওয়া"],
        "আমদানি অন্য দেশ থেকে আসে; রপ্তানি অন্য দেশে পাঠানো হয়।"),
    mcq("A big ship carries containers of goods. Where does it unload them?", ["At a port (harbour)", "In a desert", "On a mountain top", "In a classroom"], 0,
        "Ports have cranes that lift containers off ships onto trucks and trains.",
        "একটা বড় জাহাজ মালের কন্টেইনার বয়। কোথায় নামায়?", ["বন্দরে", "মরুভূমিতে", "পাহাড়ের চূড়ায়", "ক্লাসরুমে"],
        "বন্দরে ক্রেন জাহাজ থেকে কন্টেইনার তুলে ট্রাক আর ট্রেনে নামায়।"),
    mcq("Why do shops keep the most popular items easy to reach?", ["So customers find and buy them quickly", "To hide them", "To make them dusty", "Because they are heavy"], 0,
        "Easy-to-find items sell faster - shops plan their shelves carefully.",
        "দোকান সবচেয়ে জনপ্রিয় জিনিস হাতের নাগালে রাখে কেন?", ["যাতে খদ্দের তাড়াতাড়ি খুঁজে কিনতে পারে", "লুকাতে", "ধুলো জমাতে", "কারণ ওগুলো ভারী"],
        "সহজে পাওয়া জিনিস দ্রুত বিক্রি হয় - দোকান তাক সাজায় ভেবেচিন্তে।"),
    mcq("What is a 'brand'?", ["A name or logo that shows who made a product", "A kind of fruit", "A type of brick", "A school subject"], 0,
        "Brands help you recognise who made something - and companies work hard to make you trust theirs.",
        "'ব্র্যান্ড' কী?", ["একটা নাম বা লোগো, যা দেখায় কে পণ্যটা বানিয়েছে", "এক রকম ফল", "এক রকম ইট", "একটা স্কুলের বিষয়"],
        "ব্র্যান্ড চিনিয়ে দেয় কে কোনো জিনিস বানিয়েছে - আর কোম্পানিগুলো চায় তুমি তাদেরটায় ভরসা করো।"),
    mcq("You sell 3 drawings for Rs 5 each. How much do you earn?", ["Rs 15", "Rs 8", "Rs 5", "Rs 35"], 0,
        "3 x 5 = Rs 15. You are a little business!",
        "তুমি 5 টাকা করে 3টি ছবি বিক্রি করলে। কত রোজগার হলো?", ["15 টাকা", "8 টাকা", "5 টাকা", "35 টাকা"],
        "3 x 5 = 15 টাকা। তুমি এক ছোট্ট ব্যবসায়ী!"),
    mcq("What does a delivery driver do?", ["Brings goods to shops and homes", "Bakes cakes", "Teaches maths", "Builds bridges"], 0,
        "Delivery drivers move goods from warehouses to shops and homes.",
        "ডেলিভারি চালক কী করেন?", ["দোকান আর বাড়িতে জিনিস পৌঁছে দেন", "কেক বানান", "অঙ্ক শেখান", "সেতু বানান"],
        "ডেলিভারি চালক গুদাম থেকে দোকান আর বাড়িতে মাল পৌঁছে দেন।"),
    mcq("What is a warehouse?", ["A big building where goods are stored", "A small house for one person", "A warm swimming pool", "A shop for wares only on Sundays"], 0,
        "Warehouses store lots of goods until they are sent to shops.",
        "গুদাম (ওয়্যারহাউস) কী?", ["বড় ভবন, যেখানে মাল রাখা হয়", "একজনের ছোট বাড়ি", "গরম সুইমিং পুল", "শুধু রবিবারের দোকান"],
        "গুদামে দোকানে পাঠানোর আগে অনেক মাল জমা থাকে।"),
    mcq("A shop sells 10 ice creams on a cold day and 50 on a hot day. When should it order more ice cream?", ["Before hot days", "Before cold days", "Never", "Only at night"], 0,
        "Planning for busy times keeps the freezer full when customers want it most.",
        "একটা দোকান ঠান্ডা দিনে 10টি আর গরম দিনে 50টি আইসক্রিম বেচে। কখন বেশি আইসক্রিম আনানো উচিত?", ["গরমের দিনের আগে", "ঠান্ডার দিনের আগে", "কখনো না", "শুধু রাতে"],
        "ভিড়ের সময়ের জন্য পরিকল্পনা করলে খদ্দের যখন সবচেয়ে বেশি চায় তখন ফ্রিজ ভরা থাকে।"),
    mcq("Why do street sellers shout about their goods?", ["To tell people what they are selling", "Because they are angry", "To scare birds", "To practise singing only"], 0,
        "Calling out is the oldest kind of advertising!",
        "ফেরিওয়ালা তার জিনিসের কথা হেঁকে বলেন কেন?", ["মানুষকে জানাতে কী বিক্রি করছেন", "কারণ তিনি রেগে আছেন", "পাখি তাড়াতে", "শুধু গান অনুশীলন করতে"],
        "হাঁক দেওয়া বিজ্ঞাপনের সবচেয়ে পুরোনো রূপ!"),
    mcq("What does a price sticker 'Rs 20' on a toy mean?", ["You must pay Rs 20 to buy it", "The toy weighs 20 kg", "It is 20 years old", "You get Rs 20"], 0,
        "The price is how much money the seller wants in exchange for the toy.",
        "খেলনায় 'Rs 20' দামের স্টিকার মানে কী?", ["কিনতে 20 টাকা দিতে হবে", "খেলনার ওজন 20 kg", "খেলনাটার বয়স 20 বছর", "তুমি 20 টাকা পাবে"],
        "দাম হলো খেলনার বদলে বিক্রেতা যত টাকা চান।"),
    mcq("A fruit seller has 20 mangoes and sells 15. How many are left to sell?", ["5", "35", "15", "20"], 0,
        "20 - 15 = 5 mangoes left in stock.",
        "একজন ফলওয়ালার 20টি আম ছিল, 15টি বিক্রি হলো। বেচার জন্য কয়টি বাকি?", ["5", "35", "15", "20"],
        "20 - 15 = 5টি আম মজুত বাকি।"),
    mcq("What is 'stock' in a shop?", ["The goods the shop has ready to sell", "A cooking soup", "A tree trunk", "A wooden stick"], 0,
        "Stock is everything on the shelves and in the storeroom waiting to be sold.",
        "দোকানে 'মজুত' (স্টক) কী?", ["দোকানে বিক্রির জন্য রাখা জিনিস", "রান্নার স্যুপ", "গাছের গুঁড়ি", "কাঠের লাঠি"],
        "মজুত হলো তাকে আর গুদামঘরে বিক্রির অপেক্ষায় থাকা সবকিছু।"),
    mcq("Which helps a new shop get customers?", ["Telling people about it with signs and adverts", "Hiding the door", "Closing every day", "Selling nothing"], 0,
        "People must know a shop exists before they can visit it.",
        "নতুন দোকানে খদ্দের পেতে কী সাহায্য করে?", ["বোর্ড আর বিজ্ঞাপনে মানুষকে জানানো", "দরজা লুকিয়ে রাখা", "রোজ বন্ধ রাখা", "কিছুই না বেচা"],
        "দোকানে যাওয়ার আগে মানুষকে জানতে হবে দোকানটা আছে।"),
    mcq("Why are bigger packs sometimes cheaper per piece?", ["Selling more at once saves the shop work and packaging", "Big packs are magic", "Small packs are made of gold", "They are never cheaper"], 0,
        "Bulk packs save packaging and handling, so each piece can cost a little less.",
        "বড় প্যাকে কখনো কখনো প্রতি টুকরো সস্তা কেন?", ["একসঙ্গে বেশি বেচলে দোকানের খাটুনি আর মোড়ক বাঁচে", "বড় প্যাক জাদুর", "ছোট প্যাক সোনার তৈরি", "কখনো সস্তা হয় না"],
        "বড় প্যাকে মোড়ক আর নাড়াচাড়া কম লাগে, তাই প্রতি টুকরোর দাম একটু কম হতে পারে।"),
    mcq("You trade your apple for your friend's banana. Did any money change hands?", ["No - it was a swap (barter)", "Yes, Rs 100", "Yes, a bank paid", "Only coins"], 0,
        "Swapping goods directly without money is called barter.",
        "তুমি তোমার আপেল বন্ধুর কলার সঙ্গে বদল করলে। কোনো টাকা হাতবদল হলো?", ["না - এটা অদলবদল (বিনিময়)", "হ্যাঁ, 100 টাকা", "হ্যাঁ, ব্যাংক দিল", "শুধু পয়সা"],
        "টাকা ছাড়া সরাসরি জিনিস বদলকে বলে বিনিময়।"),
    mcq("Why did people invent money instead of always swapping?", ["Swapping is hard when the other person does not want your thing", "Money tastes better", "Swapping is illegal", "People did not like apples"], 0,
        "If the baker wants shoes but you only have fish, swapping fails. Money works with everyone.",
        "সবসময় অদলবদল না করে মানুষ টাকা আবিষ্কার করল কেন?", ["অন্যজন তোমার জিনিস না চাইলে বিনিময় কঠিন", "টাকার স্বাদ ভালো", "বিনিময় বেআইনি", "মানুষ আপেল পছন্দ করত না"],
        "রুটিওয়ালা জুতো চান অথচ তোমার আছে শুধু মাছ - বিনিময় অচল। টাকা সবার সঙ্গে চলে।"),
    mcq("A toy shop is next to a school. Why might that be a good spot?", ["Many children and parents walk past", "Schools sell toys", "Toys like lessons", "It is never a good spot"], 0,
        "Shops do well where lots of their customers pass by.",
        "একটা খেলনার দোকান স্কুলের পাশে। এটা ভালো জায়গা হতে পারে কেন?", ["অনেক শিশু আর অভিভাবক পাশ দিয়ে যায়", "স্কুল খেলনা বেচে", "খেলনা পড়া ভালোবাসে", "কখনো ভালো জায়গা নয়"],
        "যেখানে অনেক খদ্দের পাশ দিয়ে যায়, সেখানে দোকান ভালো চলে।"),
    mcq("What is a customer's 'complaint'?", ["Telling the shop something was wrong", "Saying thank you", "Paying more", "Singing a song"], 0,
        "If a toy is broken when you buy it, you can complain and ask the shop to fix or change it.",
        "খদ্দেরের 'অভিযোগ' কী?", ["দোকানকে জানানো যে কিছু ভুল ছিল", "ধন্যবাদ বলা", "বেশি টাকা দেওয়া", "গান গাওয়া"],
        "কেনার সময় খেলনা ভাঙা থাকলে অভিযোগ করে দোকানকে সারাতে বা বদলাতে বলতে পারো।"),
    mcq("Which shop sells medicine?", ["A pharmacy (chemist)", "A bakery", "A toy shop", "A shoe shop"], 0,
        "A pharmacy sells medicines, often with a pharmacist to help.",
        "কোন দোকান ওষুধ বেচে?", ["ওষুধের দোকান (ফার্মেসি)", "বেকারি", "খেলনার দোকান", "জুতোর দোকান"],
        "ফার্মেসি ওষুধ বিক্রি করে, প্রায়ই একজন ফার্মাসিস্ট সাহায্য করেন।"),
    mcq("A bridge is closed for repairs. What happens to delivery trucks?", ["They take a longer road around", "They jump over the river", "They stop forever", "Nothing changes"], 0,
        "A closed bridge means detours - deliveries take longer and cost more fuel.",
        "মেরামতের জন্য একটা সেতু বন্ধ। ডেলিভারি ট্রাকের কী হয়?", ["ঘুরে লম্বা রাস্তায় যায়", "নদীর উপর দিয়ে লাফায়", "চিরকাল থেমে থাকে", "কিছুই বদলায় না"],
        "সেতু বন্ধ মানে ঘুরপথ - ডেলিভারিতে বেশি সময় আর বেশি জ্বালানি লাগে।"),
    mcq("Why do shopkeepers smile and say thank you?", ["Happy customers come back again", "It is a rule of maths", "To get a sticker", "No reason"], 0,
        "Good service makes customers want to return - that keeps a shop in business.",
        "দোকানদার হেসে ধন্যবাদ বলেন কেন?", ["খুশি খদ্দের আবার ফিরে আসে", "এটা অঙ্কের নিয়ম", "স্টিকার পেতে", "কোনো কারণ নেই"],
        "ভালো ব্যবহার খদ্দেরকে আবার আসতে উৎসাহিত করে - তাতেই দোকান চলে।"),
    mcq("Which of these is a service, not a thing you take home?", ["A haircut", "A bag of rice", "A toy car", "A pencil"], 0,
        "A service is work someone does for you, like cutting hair or fixing a bike.",
        "এগুলোর কোনটা পরিষেবা, বাড়ি নিয়ে যাওয়ার জিনিস নয়?", ["চুল কাটা", "এক বস্তা চাল", "খেলনা গাড়ি", "পেনসিল"],
        "পরিষেবা হলো কারো তোমার জন্য করা কাজ, যেমন চুল কাটা বা সাইকেল সারানো।"),
    mcq("A shop gives a free balloon with each pair of shoes. Why?", ["To make customers happy and choose that shop", "Balloons are expensive", "Shoes need balloons", "By mistake"], 0,
        "Small gifts encourage customers to buy from that shop.",
        "একটা দোকান প্রতি জোড়া জুতোর সঙ্গে একটা বেলুন বিনামূল্যে দেয়। কেন?", ["খদ্দেরকে খুশি করে সেই দোকান বাছাতে", "বেলুন খুব দামি", "জুতোর বেলুন লাগে", "ভুল করে"],
        "ছোট উপহার খদ্দেরকে সেই দোকান থেকে কিনতে উৎসাহ দেয়।"),
    mcq("You make 10 paper flowers and sell 6. How many are still for sale?", ["4", "16", "6", "10"], 0,
        "10 - 6 = 4 flowers.",
        "তুমি 10টি কাগজের ফুল বানিয়ে 6টি বিক্রি করলে। কয়টি এখনো বিক্রির জন্য?", ["4", "16", "6", "10"],
        "10 - 6 = 4টি ফুল।"),
    mcq("What is a factory?", ["A place where things are made in large numbers", "A place to swim", "A shop for fruit only", "A park"], 0,
        "Factories use machines and workers to make many products, like cars or biscuits.",
        "কারখানা কী?", ["যেখানে অনেক সংখ্যায় জিনিস তৈরি হয়", "সাঁতারের জায়গা", "শুধু ফলের দোকান", "একটা পার্ক"],
        "কারখানায় যন্ত্র আর শ্রমিক মিলে গাড়ি বা বিস্কুটের মতো অনেক পণ্য বানায়।"),
    mcq("Which is the right order for a biscuit?", ["Factory makes it, truck delivers it, shop sells it, you eat it", "You eat it, factory makes it", "Shop makes it, factory eats it", "Truck bakes it"], 0,
        "Goods travel along a chain: made, moved, sold, used.",
        "একটা বিস্কুটের সঠিক ক্রম কোনটা?", ["কারখানা বানায়, ট্রাক পৌঁছায়, দোকান বেচে, তুমি খাও", "তুমি খাও, কারখানা বানায়", "দোকান বানায়, কারখানা খায়", "ট্রাক সেঁকে"],
        "জিনিস একটা শিকল ধরে চলে: তৈরি, পরিবহন, বিক্রি, ব্যবহার।"),
    mcq("What does 'free delivery' mean?", ["The shop brings it to you without charging for the trip", "The item is free", "You must carry it yourself", "Delivery costs double"], 0,
        "You still pay for the item, but not for bringing it to your home.",
        "'বিনামূল্যে ডেলিভারি' মানে কী?", ["দোকান বাড়তি ভাড়া ছাড়া তোমার কাছে পৌঁছে দেয়", "জিনিসটা বিনামূল্যে", "নিজে বয়ে আনতে হবে", "ডেলিভারির খরচ দ্বিগুণ"],
        "জিনিসের দাম দিতে হয়, কিন্তু বাড়ি পর্যন্ত আনার ভাড়া লাগে না।"),
    mcq("Why do sellers keep their stalls clean and tidy?", ["Customers like buying from clean places", "Dirt is more expensive", "To make goods heavier", "Because of the moon"], 0,
        "A clean, tidy stall looks trustworthy and attracts buyers.",
        "বিক্রেতারা দোকান পরিষ্কার-পরিচ্ছন্ন রাখেন কেন?", ["খদ্দের পরিষ্কার জায়গা থেকে কিনতে পছন্দ করে", "ময়লা বেশি দামি", "জিনিস ভারী করতে", "চাঁদের জন্য"],
        "পরিষ্কার, গোছানো দোকান বিশ্বাসযোগ্য দেখায় আর ক্রেতা টানে।"),
    mcq("A fisherman catches 30 fish and sells them all at Rs 2 each. How much does he get?", ["Rs 60", "Rs 32", "Rs 30", "Rs 15"], 0,
        "30 x 2 = Rs 60.",
        "একজন জেলে 30টি মাছ ধরে 2 টাকা করে সব বেচলেন। কত পেলেন?", ["60 টাকা", "32 টাকা", "30 টাকা", "15 টাকা"],
        "30 x 2 = 60 টাকা।"),
    mcq("Which helps you know if a shop is selling at a fair price?", ["Compare prices at other shops", "Close your eyes", "Pay whatever they say without looking", "Ask a pigeon"], 0,
        "Comparing prices helps you find a fair deal.",
        "দোকান ন্যায্য দামে বেচছে কিনা বুঝতে কী সাহায্য করে?", ["অন্য দোকানের দাম তুলনা করা", "চোখ বন্ধ করা", "না দেখে যা বলে তাই দেওয়া", "পায়রাকে জিজ্ঞাসা করা"],
        "দাম তুলনা করলে ন্যায্য দর খুঁজে পাওয়া যায়।"),
    mcq("A toll booth on a bridge collects money from drivers. Is this buying a thing or a service?", ["A service - using the bridge", "A thing to take home", "A toy", "Food"], 0,
        "Tolls pay for the service of crossing safely on a well-kept bridge.",
        "সেতুর টোল বুথ চালকদের থেকে টাকা নেয়। এটা কি জিনিস কেনা নাকি পরিষেবা?", ["পরিষেবা - সেতু ব্যবহার", "বাড়ি নেওয়ার জিনিস", "খেলনা", "খাবার"],
        "টোল দেওয়া হয় ভালোভাবে রক্ষণাবেক্ষণ করা সেতুতে নিরাপদে পার হওয়ার পরিষেবার জন্য।"),
    mcq("Why might a shop close down?", ["Not enough customers buy from it", "It has too many happy customers", "It sells too much", "Shops never close"], 0,
        "If a shop earns less than it spends, it cannot keep going.",
        "একটা দোকান বন্ধ হয়ে যেতে পারে কেন?", ["যথেষ্ট খদ্দের সেখান থেকে কেনে না", "অনেক খুশি খদ্দের আছে", "খুব বেশি বিক্রি হয়", "দোকান কখনো বন্ধ হয় না"],
        "দোকানের আয় খরচের চেয়ে কম হলে চালিয়ে যাওয়া যায় না।"),
    mcq("A sign says 'Buy 1, get 1 free'. You want 2 juice boxes at Rs 10. How much do you pay?", ["Rs 10", "Rs 20", "Rs 0", "Rs 5"], 0,
        "Pay for 1 (Rs 10) and get the second free.",
        "লেখা আছে 'একটা কিনলে একটা ফ্রি'। তুমি 10 টাকার 2টি জুসের বাক্স চাও। কত দেবে?", ["10 টাকা", "20 টাকা", "0 টাকা", "5 টাকা"],
        "1টির দাম (10 টাকা) দাও, দ্বিতীয়টি বিনামূল্যে।"),
    mcq("Who decides the price of things in a shop?", ["The shopkeeper, thinking about costs and what buyers will pay", "The customer alone", "The weather", "A cat"], 0,
        "Sellers set prices to cover their costs and earn a little, while staying fair for buyers.",
        "দোকানে জিনিসের দাম কে ঠিক করেন?", ["দোকানদার, খরচ আর ক্রেতা কত দেবে ভেবে", "শুধু খদ্দের", "আবহাওয়া", "একটা বিড়াল"],
        "বিক্রেতা খরচ মিটিয়ে একটু লাভ রাখতে দাম ঠিক করেন, ক্রেতার জন্য ন্যায্য রেখে।"),
    mcq("Why do toy adverts often appear during children's TV shows?", ["Because children watching are the people they want to reach", "Toys like TV", "By accident", "To teach maths"], 0,
        "Companies show adverts where their buyers are watching. Clever - so think before you ask for it!",
        "শিশুদের টিভি অনুষ্ঠানের সময় প্রায়ই খেলনার বিজ্ঞাপন আসে কেন?", ["যে শিশুরা দেখছে তারাই কোম্পানির লক্ষ্য", "খেলনা টিভি ভালোবাসে", "ভুল করে", "অঙ্ক শেখাতে"],
        "কোম্পানি বিজ্ঞাপন দেখায় যেখানে তাদের ক্রেতা দেখছে। চালাক - তাই চাওয়ার আগে ভেবো!"),
    mcq("A market stall sells 5 coconuts in the morning and 7 in the afternoon. How many in the day?", ["12", "2", "57", "10"], 0,
        "5 + 7 = 12 coconuts.",
        "বাজারের একটা দোকানে সকালে 5টি আর বিকেলে 7টি নারকেল বিক্রি হলো। দিনে কয়টি?", ["12", "2", "57", "10"],
        "5 + 7 = 12টি নারকেল।"),
    mcq("What is a 'shopping trolley' for?", ["Carrying the things you want to buy around the shop", "Racing", "Sleeping in", "Cooking"], 0,
        "A trolley holds your items while you shop - easier than carrying everything!",
        "'শপিং ট্রলি' কীসের জন্য?", ["দোকানে ঘুরতে ঘুরতে কেনার জিনিস বয়ে নিতে", "দৌড় প্রতিযোগিতা", "ঘুমাতে", "রান্না করতে"],
        "কেনাকাটার সময় ট্রলি তোমার জিনিস ধরে রাখে - সব হাতে বয়ে নেওয়ার চেয়ে সহজ!"),
    mcq("Why do farmers sell more vegetables at harvest time?", ["They have lots of fresh crops ready", "Vegetables grow in shops then", "Nobody eats at other times", "Farmers are bored"], 0,
        "At harvest time supply is high, so markets are full and prices are often lower.",
        "ফসল তোলার সময় চাষিরা বেশি সবজি বেচেন কেন?", ["তখন অনেক টাটকা ফসল তৈরি থাকে", "তখন দোকানে সবজি জন্মায়", "অন্য সময় কেউ খায় না", "চাষিদের একঘেয়ে লাগে"],
        "ফসলের সময় জোগান বেশি, তাই বাজার ভরা থাকে আর দাম প্রায়ই কম হয়।"),
    mcq("Which job helps goods cross a river where there is no bridge?", ["A ferry operator", "A baker", "A painter", "A dentist"], 0,
        "Ferries carry people and goods across water. A bridge does the same job every minute of the day.",
        "যেখানে সেতু নেই, সেখানে মাল নদী পার করাতে কোন কাজ সাহায্য করে?", ["ফেরি-চালক", "রুটিওয়ালা", "রং-মিস্ত্রি", "দাঁতের ডাক্তার"],
        "ফেরি জল পেরিয়ে মানুষ আর মাল বয়। সেতু দিনের প্রতিটি মিনিট একই কাজ করে।"),
    mcq("You open a stall and nobody comes. What could you try?", ["Make a bright sign and tell people", "Hide the stall", "Raise the price a lot", "Close your eyes"], 0,
        "Letting people know you exist is the first step of any business.",
        "তুমি একটা দোকান খুললে কিন্তু কেউ এল না। কী চেষ্টা করতে পারো?", ["উজ্জ্বল বোর্ড বানাও আর মানুষকে জানাও", "দোকান লুকিয়ে রাখো", "দাম অনেক বাড়াও", "চোখ বন্ধ করো"],
        "তুমি আছ তা মানুষকে জানানোই যেকোনো ব্যবসার প্রথম ধাপ।"),
    mcq("What does 'cash' mean?", ["Notes and coins you can hold", "A kind of bird", "A cash register sound", "A toy"], 0,
        "Cash is physical money. People can also pay with cards or phones.",
        "'নগদ' মানে কী?", ["হাতে ধরা যায় এমন নোট আর পয়সা", "এক রকম পাখি", "ক্যাশ মেশিনের শব্দ", "একটা খেলনা"],
        "নগদ হলো হাতে ধরা টাকা। মানুষ কার্ড বা ফোন দিয়েও দাম দিতে পারে।"),
    mcq("Which can people use to pay instead of cash?", ["A bank card or a phone app", "A leaf", "A smile only", "A rock"], 0,
        "Cards and phone apps move money from your bank account to the shop's.",
        "নগদের বদলে মানুষ কী দিয়ে দাম দিতে পারে?", ["ব্যাংক কার্ড বা ফোনের অ্যাপ", "একটা পাতা", "শুধু হাসি", "একটা পাথর"],
        "কার্ড আর ফোনের অ্যাপ তোমার ব্যাংক অ্যাকাউন্ট থেকে দোকানের অ্যাকাউন্টে টাকা পাঠায়।"),
    mcq("A shop orders 40 notebooks and sells 25. How many are left in stock?", ["15", "65", "25", "40"], 0,
        "40 - 25 = 15 notebooks.",
        "একটা দোকান 40টি খাতা আনিয়ে 25টি বেচল। মজুত কয়টি বাকি?", ["15", "65", "25", "40"],
        "40 - 25 = 15টি খাতা।"),
    mcq("Why is honesty important for a shopkeeper?", ["Customers trust honest shops and return", "Lying makes more friends", "It is not important", "Honest shops close"], 0,
        "Fair weights and true prices build trust - and trust brings customers back.",
        "দোকানদারের সৎ হওয়া জরুরি কেন?", ["খদ্দের সৎ দোকানে ভরসা করে আর ফিরে আসে", "মিথ্যায় বেশি বন্ধু হয়", "জরুরি নয়", "সৎ দোকান বন্ধ হয়ে যায়"],
        "ঠিক ওজন আর সত্যি দাম বিশ্বাস গড়ে - আর বিশ্বাস খদ্দেরকে ফিরিয়ে আনে।"),
    mcq("A scale in a shop is used to...", ["Weigh goods like rice and vegetables", "Measure time", "Play music", "Count people"], 0,
        "Shops weigh loose goods so you pay for exactly the amount you get.",
        "দোকানের দাঁড়িপাল্লা ব্যবহার হয়...", ["চাল আর সবজির মতো জিনিস ওজন করতে", "সময় মাপতে", "গান বাজাতে", "মানুষ গুনতে"],
        "দোকানে খোলা জিনিস ওজন করা হয়, যাতে যতটা পাও ঠিক ততটার দাম দাও।"),
    mcq("Rice costs Rs 40 per kg. How much for 2 kg?", ["Rs 80", "Rs 42", "Rs 40", "Rs 20"], 0,
        "2 x 40 = Rs 80.",
        "চালের দাম প্রতি kg 40 টাকা। 2 kg-এর দাম কত?", ["80 টাকা", "42 টাকা", "40 টাকা", "20 টাকা"],
        "2 x 40 = 80 টাকা।"),
    mcq("What is a 'shop assistant'?", ["A person who helps customers in a shop", "A robot that eats goods", "A kind of shelf", "The shop's cat"], 0,
        "Shop assistants help you find things, answer questions and take payment.",
        "'দোকানের সহকারী' কে?", ["যিনি দোকানে খদ্দেরদের সাহায্য করেন", "যে রোবট মাল খায়", "এক রকম তাক", "দোকানের বিড়াল"],
        "সহকারী জিনিস খুঁজে দেন, প্রশ্নের উত্তর দেন আর দাম নেন।"),
    mcq("Why do shops sell umbrellas at the door on rainy days?", ["People suddenly need them when it rains", "Umbrellas are heavy", "To block the door", "Because umbrellas like rain"], 0,
        "Selling what people need right now, right where they see it, is smart business.",
        "বৃষ্টির দিনে দোকান দরজার কাছে ছাতা বেচে কেন?", ["বৃষ্টি হলে হঠাৎ মানুষের দরকার হয়", "ছাতা ভারী", "দরজা আটকাতে", "কারণ ছাতা বৃষ্টি ভালোবাসে"],
        "মানুষের এখনই যা দরকার তা চোখের সামনে বেচা বুদ্ধিমান ব্যবসা।"),
    mcq("A train carries 10 wagons of coal to a power station. What is this called?", ["Freight transport (moving goods)", "A holiday", "A race", "Cooking"], 0,
        "Moving goods by train, truck or ship is called freight. MODIS BridgeWorks Levels 2, 4 and 9 are all about freight!",
        "একটা ট্রেন বিদ্যুৎকেন্দ্রে 10 ওয়াগন কয়লা নিয়ে যায়। একে কী বলে?", ["মাল পরিবহন", "ছুটি", "দৌড় প্রতিযোগিতা", "রান্না"],
        "ট্রেন, ট্রাক বা জাহাজে মাল বয়ে নেওয়াকে বলে মাল পরিবহন। MODIS BridgeWorks-এর লেভেল 2, 4 আর 9 মাল পরিবহন নিয়েই!"),
    mcq("You sell cookies at Rs 3 each and sell 4. Your ingredients cost Rs 5. How much did you earn after costs?", ["Rs 7", "Rs 12", "Rs 5", "Rs 17"], 0,
        "Money in: 4 x 3 = 12. Minus costs 5: Rs 7 profit.",
        "তুমি 3 টাকা করে 4টি কুকি বেচলে। উপকরণে খরচ 5 টাকা। খরচ বাদে কত আয় হলো?", ["7 টাকা", "12 টাকা", "5 টাকা", "17 টাকা"],
        "আয়: 4 x 3 = 12। খরচ 5 বাদ: 7 টাকা লাভ।"),
    mcq("What does a 'Closed' sign on a shop door mean?", ["You cannot buy there right now", "Everything is free", "Go in anyway", "The shop has moved to the moon"], 0,
        "Closed means the shop is not serving customers at the moment.",
        "দোকানের দরজায় 'বন্ধ' লেখা মানে কী?", ["এখন সেখানে কেনা যাবে না", "সব কিছু বিনামূল্যে", "তবুও ঢুকে পড়ো", "দোকান চাঁদে চলে গেছে"],
        "বন্ধ মানে দোকান এখন খদ্দেরদের পরিষেবা দিচ্ছে না।"),
    mcq("A toy has a 'Made in Japan' label. What does it tell you?", ["Where the toy was made", "Who owns your house", "The toy's price", "The toy's age"], 0,
        "Labels show where goods were made. Many goods travel across the world before reaching you.",
        "একটা খেলনায় 'জাপানে তৈরি' লেবেল। এটা কী জানায়?", ["খেলনাটা কোথায় তৈরি হয়েছে", "তোমার বাড়ির মালিক কে", "খেলনার দাম", "খেলনার বয়স"],
        "লেবেল জানায় জিনিস কোথায় তৈরি। অনেক জিনিস তোমার কাছে পৌঁছানোর আগে পৃথিবী ঘুরে আসে।"),
    mcq("Which is the best way to carry home many groceries?", ["A strong reusable bag", "In your pockets only", "Juggling them", "In your mouth"], 0,
        "A strong bag carries more and can be used again and again.",
        "অনেক বাজার বাড়ি নেওয়ার সবচেয়ে ভালো উপায় কোনটা?", ["একটা শক্ত, বারবার ব্যবহারযোগ্য ব্যাগ", "শুধু পকেটে", "লোফালুফি করে", "মুখে করে"],
        "শক্ত ব্যাগে বেশি ধরে আর বারবার ব্যবহার করা যায়।"),
    mcq("Why are some foods sold in tins or packets?", ["To keep them fresh and safe for longer", "To make them heavier", "To hide them", "Because shops love metal"], 0,
        "Packaging protects food from air, dirt and germs so it lasts longer.",
        "কিছু খাবার টিন বা প্যাকেটে বিক্রি হয় কেন?", ["বেশিদিন টাটকা আর নিরাপদ রাখতে", "ভারী করতে", "লুকাতে", "কারণ দোকান ধাতু ভালোবাসে"],
        "মোড়ক খাবারকে বাতাস, ময়লা আর জীবাণু থেকে বাঁচায়, তাই বেশিদিন টেকে।"),
    mcq("What does the 'best before' date on food tell you?", ["Until when the food is at its best", "The baker's birthday", "The price", "The weight"], 0,
        "After that date the food may not taste as good. Always check it!",
        "খাবারের গায়ে 'এর আগে সেরা' তারিখ কী জানায়?", ["কোন দিন পর্যন্ত খাবার সবচেয়ে ভালো থাকে", "রুটিওয়ালার জন্মদিন", "দাম", "ওজন"],
        "সেই তারিখের পরে খাবারের স্বাদ ততটা ভালো না-ও থাকতে পারে। সবসময় দেখে নিও!"),
    mcq("A shop sells 3 kinds of ice cream. Another sells 10 kinds. Why might people prefer the second?", ["More choice", "It is further away", "It is always closed", "It sells no ice cream"], 0,
        "More choice helps customers find exactly what they like.",
        "একটা দোকানে 3 রকম আইসক্রিম, আরেকটায় 10 রকম। মানুষ দ্বিতীয়টা পছন্দ করতে পারে কেন?", ["বেশি বাছাই", "সেটা বেশি দূরে", "সবসময় বন্ধ থাকে", "কোনো আইসক্রিম বেচে না"],
        "বেশি বাছাই থাকলে খদ্দের ঠিক নিজের পছন্দটা পায়।"),
    mcq("Two shops sell the same bread. One is far, one is near. Both cost Rs 30. Which do you choose?", ["The near one - same price, less walking", "The far one", "Neither", "Both at once"], 0,
        "When price and quality are the same, convenience decides.",
        "দুটো দোকানে একই পাউরুটি। একটা দূরে, একটা কাছে। দুটোরই দাম 30 টাকা। কোনটা বাছবে?", ["কাছেরটা - একই দাম, কম হাঁটা", "দূরেরটা", "কোনোটাই না", "একসঙ্গে দুটোই"],
        "দাম আর মান এক হলে সুবিধাই সিদ্ধান্ত নেয়।"),
    mcq("A bridge lets farmers reach the town market in 10 minutes instead of 1 hour. What happens to their business?", ["They can sell more and keep food fresher", "They sell less", "Nothing", "Their crops shrink"], 0,
        "Faster trips mean fresher produce, more trips and more sales - bridges help whole towns grow.",
        "একটা সেতুর জন্য চাষিরা 1 ঘণ্টার বদলে 10 মিনিটে শহরের বাজারে পৌঁছান। তাঁদের ব্যবসার কী হয়?", ["বেশি বেচতে পারেন আর খাবার বেশি টাটকা থাকে", "কম বেচেন", "কিছুই না", "ফসল ছোট হয়ে যায়"],
        "দ্রুত যাতায়াত মানে টাটকা ফসল, বেশি যাতায়াত আর বেশি বিক্রি - সেতু পুরো শহরকে বাড়তে সাহায্য করে।"),
    mcq("What is a 'stall'?", ["A small open shop, often in a market", "A broken car", "A horse's bed only", "A tall tower"], 0,
        "Market stalls are small shops set up on tables or carts.",
        "'স্টল' কী?", ["ছোট খোলা দোকান, প্রায়ই বাজারে", "ভাঙা গাড়ি", "শুধু ঘোড়ার বিছানা", "উঁচু টাওয়ার"],
        "বাজারের স্টল হলো টেবিল বা গাড়িতে বসানো ছোট দোকান।"),
    mcq("Your stall sells pencils at Rs 4. A friend's stall sells the same for Rs 3. What might customers do?", ["Buy from your friend", "Buy from you only", "Buy from nobody", "Pay you Rs 10"], 0,
        "Customers often choose the lower price for the same thing. That is called competition.",
        "তোমার দোকানে পেনসিল 4 টাকা। বন্ধুর দোকানে একই পেনসিল 3 টাকা। খদ্দেররা কী করতে পারে?", ["বন্ধুর থেকে কিনবে", "শুধু তোমার থেকে কিনবে", "কারো থেকেই কিনবে না", "তোমাকে 10 টাকা দেবে"],
        "একই জিনিসে খদ্দের প্রায়ই কম দাম বাছে। একে বলে প্রতিযোগিতা।"),
    mcq("What is a 'customer queue number'?", ["A number that shows whose turn it is", "The shop's phone number", "A price", "A date"], 0,
        "Ticket numbers keep busy counters fair: everyone is served in order.",
        "'খদ্দেরের লাইন নম্বর' কী?", ["একটা নম্বর, যা দেখায় কার পালা", "দোকানের ফোন নম্বর", "একটা দাম", "একটা তারিখ"],
        "টোকেন নম্বর ভিড়ের কাউন্টারকে ন্যায্য রাখে: সবাই ক্রমে পরিষেবা পায়।"),
    mcq("A lorry carries 100 boxes and delivers 20 at each shop. How many shops can it fill?", ["5", "20", "100", "120"], 0,
        "100 shared into groups of 20: 5 shops.",
        "একটা লরি 100টি বাক্স বয় আর প্রতি দোকানে 20টি দেয়। কয়টি দোকানে দিতে পারবে?", ["5", "20", "100", "120"],
        "100-কে 20-এর দলে ভাগ: 5টি দোকান।"),
    mcq("Why do sellers weigh fruit in front of you?", ["So you can see it is fair", "To exercise", "To scare the fruit", "Because fruit is shy"], 0,
        "Weighing openly shows you get what you pay for.",
        "বিক্রেতা তোমার সামনে ফল ওজন করেন কেন?", ["যাতে দেখো ন্যায্য হচ্ছে", "ব্যায়াম করতে", "ফলকে ভয় দেখাতে", "কারণ ফল লাজুক"],
        "সবার সামনে ওজন করলে বোঝা যায় যা দাম দিচ্ছ তাই পাচ্ছ।"),
    mcq("Which is a good name for a shop that sells shoes?", ["Happy Feet Shoes", "Fresh Fish Corner", "Bread and Butter Bakery", "Sky Rockets Ltd"], 0,
        "A good shop name tells people what it sells.",
        "জুতোর দোকানের জন্য কোন নামটা ভালো?", ["খুশি পা জুতোঘর", "টাটকা মাছের কোণ", "রুটি-মাখন বেকারি", "আকাশ রকেট লিমিটেড"],
        "ভালো দোকানের নাম জানিয়ে দেয় দোকানে কী বিক্রি হয়।"),
    mcq("A shop is always crowded at 5 pm. What could the shopkeeper do?", ["Have more helpers at 5 pm", "Close at 5 pm", "Hide at 5 pm", "Turn off the lights"], 0,
        "More helpers at busy times keep queues short and customers happy.",
        "একটা দোকানে বিকেল 5টায় সবসময় ভিড়। দোকানদার কী করতে পারেন?", ["5টায় বেশি সহকারী রাখা", "5টায় বন্ধ করা", "5টায় লুকিয়ে থাকা", "বাতি নিভিয়ে দেওয়া"],
        "ভিড়ের সময় বেশি সহকারী থাকলে লাইন ছোট থাকে আর খদ্দের খুশি থাকে।"),
    mcq("What is a 'shopping list' for?", ["To remember what to buy", "To decorate the fridge", "To count stars", "To draw on"], 0,
        "A list helps you buy what you need and avoid forgetting - or overspending.",
        "'বাজারের তালিকা' কীসের জন্য?", ["কী কিনতে হবে মনে রাখতে", "ফ্রিজ সাজাতে", "তারা গুনতে", "আঁকিবুঁকি করতে"],
        "তালিকা দরকারি জিনিস কিনতে আর ভুলে যাওয়া - বা বেশি খরচ - এড়াতে সাহায্য করে।"),
    mcq("A shop sells a cake for Rs 50 that cost Rs 40 to make. What is its profit?", ["Rs 10", "Rs 90", "Rs 50", "Rs 40"], 0,
        "Profit = selling price - cost = 50 - 40 = Rs 10.",
        "একটা দোকান 40 টাকায় বানানো কেক 50 টাকায় বেচে। লাভ কত?", ["10 টাকা", "90 টাকা", "50 টাকা", "40 টাকা"],
        "লাভ = বিক্রয়মূল্য - খরচ = 50 - 40 = 10 টাকা।"),
    mcq("What happens if a shop sells a cake for less than it cost to make?", ["The shop loses money", "The shop gets rich", "Nothing", "The cake grows"], 0,
        "Selling below cost is a loss. Shops cannot do that for long.",
        "যে দামে কেক বানানো তার চেয়ে কমে বেচলে দোকানের কী হয়?", ["দোকানের লোকসান হয়", "দোকান ধনী হয়", "কিছুই না", "কেক বড় হয়"],
        "খরচের কমে বেচলে লোকসান। দোকান বেশিদিন এটা পারে না।"),
    mcq("A town gets a new bridge. Shops on the far side get...", ["More customers from across the river", "Fewer customers", "No change at all", "Washed away"], 0,
        "Bridges connect people to shops, so trade grows on both sides.",
        "একটা শহরে নতুন সেতু হলো। ওপারের দোকানগুলো পায়...", ["নদীর এপার থেকে বেশি খদ্দের", "কম খদ্দের", "কোনো পরিবর্তন নেই", "ভেসে যায়"],
        "সেতু মানুষকে দোকানের সঙ্গে জোড়ে, তাই দুই পারেই বেচাকেনা বাড়ে।"),
    mcq("Who checks that shop scales are honest?", ["Government inspectors", "The customers' pets", "Nobody ever", "The shop's lights"], 0,
        "Inspectors test scales so that 1 kg in every shop really is 1 kg.",
        "দোকানের দাঁড়িপাল্লা সৎ কিনা কে পরীক্ষা করেন?", ["সরকারি পরিদর্শক", "খদ্দেরদের পোষা প্রাণী", "কেউ কখনো না", "দোকানের বাতি"],
        "পরিদর্শকরা দাঁড়িপাল্লা পরীক্ষা করেন, যাতে প্রতিটি দোকানে 1 kg সত্যিই 1 kg হয়।"),
    mcq("A child sells old toys at a garage sale. What is the child doing?", ["Running a tiny business", "Stealing", "Building a bridge", "Cooking"], 0,
        "Selling things you no longer need is a small business - and helps someone else get a bargain.",
        "এক শিশু বাড়ির সামনে পুরোনো খেলনা বিক্রি করছে। শিশুটি কী করছে?", ["এক ছোট্ট ব্যবসা চালাচ্ছে", "চুরি করছে", "সেতু বানাচ্ছে", "রান্না করছে"],
        "যে জিনিস আর লাগে না তা বেচা এক ছোট্ট ব্যবসা - আর অন্য কেউ সস্তায় ভালো জিনিস পায়।"),
    mcq("Which is a 'customer'?", ["A person buying vegetables at a stall", "The stall's table", "The vegetables", "The weighing scale"], 0,
        "The customer is the person who buys.",
        "কে 'খদ্দের'?", ["স্টল থেকে সবজি কেনা মানুষ", "স্টলের টেবিল", "সবজিগুলো", "দাঁড়িপাল্লা"],
        "খদ্দের হলো যে মানুষ কেনে।"),
    mcq("Why do shops display prices clearly?", ["So customers can decide quickly and trust the shop", "To confuse people", "Because it is pretty", "To make goods heavier"], 0,
        "Clear prices make shopping easy and fair.",
        "দোকান দাম স্পষ্ট করে দেখায় কেন?", ["যাতে খদ্দের দ্রুত সিদ্ধান্ত নিতে আর দোকানে ভরসা করতে পারে", "মানুষকে বিভ্রান্ত করতে", "কারণ সুন্দর লাগে", "জিনিস ভারী করতে"],
        "স্পষ্ট দাম কেনাকাটা সহজ আর ন্যায্য করে।"),
    mcq("A truck can carry 10 sacks per trip. How many trips for 30 sacks?", ["3", "10", "30", "300"], 0,
        "30 shared into 10s: 3 trips. Planning trips saves fuel and time.",
        "একটা ট্রাক প্রতি যাত্রায় 10 বস্তা বয়। 30 বস্তার জন্য কয়টি যাত্রা?", ["3", "10", "30", "300"],
        "30-কে 10-এ ভাগ: 3টি যাত্রা। যাত্রার পরিকল্পনা জ্বালানি আর সময় বাঁচায়।"),
    mcq("What is a 'shop window' display for?", ["Showing goods to people walking past", "Keeping rain out only", "Hiding the shopkeeper", "Storing rubbish"], 0,
        "A nice window display invites passers-by to come in.",
        "দোকানের জানালার সাজসজ্জা কীসের জন্য?", ["পথচারীদের জিনিস দেখাতে", "শুধু বৃষ্টি আটকাতে", "দোকানদারকে লুকাতে", "আবর্জনা রাখতে"],
        "সুন্দর জানালার সাজ পথচারীদের ভেতরে আসতে ডাকে।"),
    mcq("If a shop doubles its price, what might happen to how many people buy?", ["Fewer people may buy", "Everyone buys more", "Nothing ever changes", "The shop gives it free"], 0,
        "Higher prices usually mean fewer buyers. Sellers must find a fair balance.",
        "একটা দোকান দাম দ্বিগুণ করলে কতজন কেনে তার কী হতে পারে?", ["কম মানুষ কিনতে পারে", "সবাই বেশি কেনে", "কখনো কিছু বদলায় না", "দোকান বিনামূল্যে দেয়"],
        "বেশি দাম সাধারণত মানে কম ক্রেতা। বিক্রেতাকে ন্যায্য ভারসাম্য খুঁজতে হয়।"),
    mcq("What is 'trade' between two towns?", ["Buying and selling goods between them", "A football match", "A shared holiday", "A river"], 0,
        "Towns trade: one sells rice, the other sells cloth. Roads and bridges make it possible.",
        "দুটি শহরের মধ্যে 'বাণিজ্য' কী?", ["তাদের মধ্যে জিনিস কেনাবেচা", "একটা ফুটবল ম্যাচ", "একসঙ্গে ছুটি", "একটা নদী"],
        "শহরগুলো বাণিজ্য করে: একটা চাল বেচে, অন্যটা কাপড়। রাস্তা আর সেতু তা সম্ভব করে।"),
    mcq("A potter makes 6 pots a day and sells them all. How many pots in 5 days?", ["30", "11", "6", "65"], 0,
        "6 x 5 = 30 pots - steady work builds a business.",
        "একজন কুমোর দিনে 6টি হাঁড়ি বানিয়ে সব বেচেন। 5 দিনে কয়টি হাঁড়ি?", ["30", "11", "6", "65"],
        "6 x 5 = 30টি হাঁড়ি - নিয়মিত কাজে ব্যবসা গড়ে ওঠে।"),
    mcq("Why do toll bridges show their prices on a big board before the booth?", ["So drivers know the charge before they arrive", "To block the road", "To make the bridge taller", "For decoration only"], 0,
        "Clear prices in advance are fair to customers - drivers can decide to pay or take another road.",
        "টোল সেতু বুথের আগে বড় বোর্ডে দাম দেখায় কেন?", ["যাতে চালকরা পৌঁছানোর আগেই মাশুল জানেন", "রাস্তা আটকাতে", "সেতু উঁচু করতে", "শুধু সাজাতে"],
        "আগে থেকে স্পষ্ট দাম খদ্দেরের প্রতি ন্যায্য - চালক ঠিক করতে পারেন দেবেন নাকি অন্য রাস্তা নেবেন।"),
)
