"""Class 2 - Commercials: running a small stall, costs and profit, supply and demand,
advertising, delivery and fair trade."""
from . import mcq


def profit(cost, price, n, item_en, item_bn):
    each = price - cost
    r = each * n
    o = []
    for x in (r, price * n, cost * n, r + n, 2 * r, r + 1):
        if x not in o and len(o) < 4:
            o.append(x)
    return mcq(f"You make {item_en} for Rs {cost} each and sell them for Rs {price}. You sell {n}. What is your profit?",
               [f"Rs {x}" for x in o], 0,
               f"Profit on each = {price} - {cost} = Rs {each}. For {n}: {each} x {n} = Rs {r}.",
               f"তুমি প্রতিটি {cost} টাকায় {item_bn} বানিয়ে {price} টাকায় বেচো। {n}টি বেচলে। লাভ কত?",
               [f"{x} টাকা" for x in o],
               f"প্রতিটিতে লাভ = {price} - {cost} = {each} টাকা। {n}টিতে: {each} x {n} = {r} টাকা।")


ITEMS = (
    profit(5, 8, 10, "paper fans", "কাগজের পাখা"),
    profit(10, 15, 6, "bracelets", "ব্রেসলেট"),
    profit(3, 5, 20, "cups of lemonade", "কাপ শরবত"),
    profit(20, 30, 4, "clay pots", "মাটির হাঁড়ি"),
    profit(12, 20, 5, "bookmarks sets", "বুকমার্কের সেট"),
    profit(8, 10, 15, "cookies packs", "কুকির প্যাকেট"),
    profit(25, 40, 3, "painted tiles", "রং করা টালি"),
    profit(6, 9, 12, "seed packets", "বীজের প্যাকেট"),
    mcq("What is 'profit'?", ["Money left after paying all costs", "All the money a shop takes in", "Money borrowed", "A kind of tax"], 0,
        "Profit = money from sales - costs. It rewards the seller for their work and risk.",
        "'লাভ' কী?", ["সব খরচ মিটিয়ে যে টাকা থাকে", "দোকানে আসা সব টাকা", "ধার নেওয়া টাকা", "এক রকম কর"],
        "লাভ = বিক্রির টাকা - খরচ। এটা বিক্রেতার পরিশ্রম আর ঝুঁকির পুরস্কার।"),
    mcq("What is a 'loss'?", ["When costs are bigger than the money from sales", "When you find extra money", "A kind of discount", "A free gift"], 0,
        "If it costs more to make than you sell it for, you make a loss.",
        "'লোকসান' কী?", ["যখন খরচ বিক্রির টাকার চেয়ে বেশি", "যখন বাড়তি টাকা পাও", "এক রকম ছাড়", "বিনামূল্যের উপহার"],
        "বেচার দামের চেয়ে বানানোর খরচ বেশি হলে লোকসান হয়।"),
    mcq("What is 'revenue' (or sales)?", ["All the money that comes in from selling", "Only the profit", "Money spent on rent", "A bank loan"], 0,
        "Revenue is the total from sales before costs are taken away.",
        "'আয়' (বা বিক্রি) কী?", ["বিক্রি থেকে আসা সব টাকা", "শুধু লাভ", "ভাড়ায় খরচের টাকা", "ব্যাংক ঋণ"],
        "খরচ বাদ দেওয়ার আগে বিক্রি থেকে আসা মোট টাকাই আয়।"),
    mcq("A stall sells 30 drinks at Rs 10 each. What is its revenue?", ["Rs 300", "Rs 40", "Rs 30", "Rs 3"], 0,
        "30 x 10 = Rs 300.",
        "একটা স্টল 10 টাকা করে 30টি পানীয় বেচল। আয় কত?", ["300 টাকা", "40 টাকা", "30 টাকা", "3 টাকা"],
        "30 x 10 = 300 টাকা।"),
    mcq("The same stall spent Rs 180 on ingredients and cups. What is its profit?", ["Rs 120", "Rs 480", "Rs 300", "Rs 180"], 0,
        "Profit = 300 - 180 = Rs 120.",
        "সেই স্টল উপকরণ আর কাপে 180 টাকা খরচ করেছে। লাভ কত?", ["120 টাকা", "480 টাকা", "300 টাকা", "180 টাকা"],
        "লাভ = 300 - 180 = 120 টাকা।"),
    mcq("What is 'demand'?", ["How much people want to buy something", "How much is made", "The shop's address", "A type of coin"], 0,
        "When many people want something, demand is high.",
        "'চাহিদা' কী?", ["মানুষ কোনো কিছু কতটা কিনতে চায়", "কতটা তৈরি হয়", "দোকানের ঠিকানা", "এক রকম পয়সা"],
        "অনেক মানুষ কিছু চাইলে চাহিদা বেশি।"),
    mcq("What is 'supply'?", ["How much of something is available to sell", "How much people want", "A shop's name", "A price tag"], 0,
        "Supply is the amount sellers have ready.",
        "'জোগান' কী?", ["বিক্রির জন্য কোনো কিছু কতটা পাওয়া যায়", "মানুষ কতটা চায়", "দোকানের নাম", "দামের ট্যাগ"],
        "জোগান হলো বিক্রেতাদের হাতে তৈরি পরিমাণ।"),
    mcq("Umbrellas are wanted by many on a rainy day, but the shop has few. What may happen to the price?", ["It may rise", "It may fall to zero", "It stays the same forever", "Umbrellas become free"], 0,
        "High demand and low supply push prices up.",
        "বৃষ্টির দিনে অনেকে ছাতা চায়, কিন্তু দোকানে কম আছে। দামের কী হতে পারে?", ["বাড়তে পারে", "শূন্যে নামতে পারে", "চিরকাল একই থাকে", "ছাতা বিনামূল্যে হয়"],
        "বেশি চাহিদা আর কম জোগান দাম বাড়িয়ে দেয়।"),
    mcq("A farm has a huge mango harvest and the market is full of mangoes. What may happen to mango prices?", ["They may fall", "They may rise a lot", "Mangoes vanish", "Nothing at all"], 0,
        "Plenty of supply with the same demand pushes prices down.",
        "একটা খামারে আমের বিশাল ফলন আর বাজার আমে ভরা। আমের দামের কী হতে পারে?", ["কমতে পারে", "অনেক বাড়তে পারে", "আম উধাও হয়", "কিছুই না"],
        "চাহিদা একই থেকে জোগান বেশি হলে দাম কমে।"),
    mcq("What is a 'customer'?", ["Someone who buys goods or services", "The shop's owner", "A delivery van", "A price"], 0,
        "Without customers, a business cannot earn.",
        "'খদ্দের' কে?", ["যে পণ্য বা পরিষেবা কেনে", "দোকানের মালিক", "ডেলিভারি ভ্যান", "একটা দাম"],
        "খদ্দের ছাড়া ব্যবসা আয় করতে পারে না।"),
    mcq("What is a 'product'?", ["Something made to be sold", "A customer", "A bank", "A road"], 0,
        "Toys, bread and shoes are products.",
        "'পণ্য' কী?", ["বিক্রির জন্য তৈরি জিনিস", "একজন খদ্দের", "একটা ব্যাংক", "একটা রাস্তা"],
        "খেলনা, পাউরুটি আর জুতো পণ্য।"),
    mcq("What is a 'service'?", ["Work done for someone, like cleaning or repairs", "A thing you keep", "A coin", "A shelf"], 0,
        "Haircuts, bus rides and bridge tolls are services.",
        "'পরিষেবা' কী?", ["কারো জন্য করা কাজ, যেমন পরিষ্কার বা মেরামত", "যে জিনিস রেখে দাও", "একটা পয়সা", "একটা তাক"],
        "চুল কাটা, বাসে চড়া আর সেতুর টোল পরিষেবা।"),
    mcq("Why do businesses advertise?", ["To tell people about their products and attract customers", "To waste paper", "To scare competitors", "Because it is free"], 0,
        "Adverts spread the word - but they cost money, so businesses choose them carefully.",
        "ব্যবসা বিজ্ঞাপন দেয় কেন?", ["পণ্যের কথা জানাতে আর খদ্দের টানতে", "কাগজ নষ্ট করতে", "প্রতিযোগীদের ভয় দেখাতে", "কারণ বিনামূল্যে"],
        "বিজ্ঞাপন খবর ছড়ায় - কিন্তু টাকা লাগে, তাই ব্যবসা ভেবেচিন্তে বাছে।"),
    mcq("Which is an example of an advert?", ["A poster saying 'Fresh bread at Raju's Bakery!'", "A loaf of bread", "A bakery oven", "A baker's apron"], 0,
        "Posters, TV ads, signs and online ads tell people about products.",
        "কোনটা বিজ্ঞাপনের উদাহরণ?", ["'রাজুর বেকারিতে টাটকা রুটি!' লেখা পোস্টার", "একটা পাউরুটি", "বেকারির উনুন", "রুটিওয়ালার অ্যাপ্রন"],
        "পোস্টার, টিভির বিজ্ঞাপন, সাইনবোর্ড আর অনলাইন বিজ্ঞাপন মানুষকে পণ্যের কথা জানায়।"),
    mcq("An advert says 'The best toy in the world!'. What should a smart shopper think?", ["Adverts try to persuade - check for yourself", "It must be true", "Buy ten", "Adverts never exaggerate"], 0,
        "Adverts show the best side. Look at reviews, prices and what you really need.",
        "বিজ্ঞাপনে লেখা 'বিশ্বের সেরা খেলনা!'। বুদ্ধিমান ক্রেতা কী ভাববে?", ["বিজ্ঞাপন রাজি করাতে চায় - নিজে যাচাই করো", "এটা নিশ্চয়ই সত্যি", "দশটা কেনো", "বিজ্ঞাপন কখনো বাড়িয়ে বলে না"],
        "বিজ্ঞাপন ভালো দিকটাই দেখায়। মতামত, দাম আর নিজের প্রয়োজন দেখো।"),
    mcq("What is 'competition' between shops?", ["Shops trying to win the same customers", "Shops working together always", "A running race", "A shop closing"], 0,
        "Competition pushes shops to offer better prices, quality and service.",
        "দোকানের মধ্যে 'প্রতিযোগিতা' কী?", ["একই খদ্দেরদের পেতে দোকানগুলোর চেষ্টা", "সবসময় একসঙ্গে কাজ করা", "দৌড় প্রতিযোগিতা", "দোকান বন্ধ হওয়া"],
        "প্রতিযোগিতা দোকানকে ভালো দাম, মান আর পরিষেবা দিতে চাপ দেয়।"),
    mcq("Two tea stalls stand side by side. How can one attract more customers?", ["Better tea, friendly service or a fair price", "Shouting rude words", "Closing early", "Hiding the sign"], 0,
        "Quality, service and price help a business stand out.",
        "পাশাপাশি দুটো চায়ের দোকান। একটা কীভাবে বেশি খদ্দের টানতে পারে?", ["ভালো চা, আন্তরিক ব্যবহার বা ন্যায্য দাম", "অভদ্র কথা চেঁচিয়ে", "তাড়াতাড়ি বন্ধ করে", "বোর্ড লুকিয়ে"],
        "মান, ব্যবহার আর দাম ব্যবসাকে আলাদা করে তোলে।"),
    mcq("What does a 'delivery' service do?", ["Brings goods to the customer", "Makes goods", "Paints shops", "Counts money only"], 0,
        "Deliveries move goods from shops or warehouses to homes.",
        "'ডেলিভারি' পরিষেবা কী করে?", ["খদ্দেরের কাছে মাল পৌঁছে দেয়", "মাল তৈরি করে", "দোকান রং করে", "শুধু টাকা গোনে"],
        "ডেলিভারি দোকান বা গুদাম থেকে বাড়িতে মাল পৌঁছায়।"),
    mcq("A delivery van makes 6 stops and leaves 8 parcels at each. How many parcels?", ["48", "14", "6", "68"], 0,
        "6 x 8 = 48 parcels.",
        "একটা ডেলিভারি ভ্যান 6 জায়গায় থামে আর প্রতিটিতে 8টি পার্সেল দেয়। মোট কয়টি পার্সেল?", ["48", "14", "6", "68"],
        "6 x 8 = 48টি পার্সেল।"),
    mcq("A bridge cuts a delivery trip from 40 km to 10 km. How many km are saved per trip?", ["30 km", "50 km", "10 km", "4 km"], 0,
        "40 - 10 = 30 km saved - less fuel, less time, cheaper deliveries.",
        "একটা সেতু ডেলিভারির পথ 40 km থেকে 10 km করে দিল। প্রতি যাত্রায় কত km বাঁচে?", ["30 km", "50 km", "10 km", "4 km"],
        "40 - 10 = 30 km বাঁচে - কম জ্বালানি, কম সময়, সস্তা ডেলিভারি।"),
    mcq("Why do goods cost more in a remote village with no bridge?", ["Transport takes longer and costs more", "Villagers like paying more", "Goods are better there", "They do not"], 0,
        "Long, difficult trips add transport costs to the price of every item.",
        "সেতু নেই এমন দূরের গ্রামে জিনিসের দাম বেশি কেন?", ["পরিবহনে বেশি সময় আর খরচ লাগে", "গ্রামবাসী বেশি দিতে ভালোবাসে", "সেখানে জিনিস ভালো", "দাম বেশি নয়"],
        "লম্বা, কঠিন যাত্রা প্রতিটি জিনিসের দামে পরিবহন খরচ যোগ করে।"),
    mcq("What is a 'market stall' rent?", ["Money paid to use the stall space", "Money customers pay", "A tax on sweets", "A delivery fee"], 0,
        "Rent is a cost the stall owner pays whether they sell a lot or a little.",
        "বাজারের স্টলের 'ভাড়া' কী?", ["স্টলের জায়গা ব্যবহারের জন্য দেওয়া টাকা", "খদ্দেরের দেওয়া টাকা", "মিষ্টির উপর কর", "ডেলিভারি ফি"],
        "ভাড়া এমন খরচ, যা বিক্রি বেশি হোক বা কম, স্টল-মালিককে দিতে হয়।"),
    mcq("A stall's rent is Rs 50 a day. It makes Rs 30 profit before rent. What happens?", ["It loses Rs 20 a day", "It makes Rs 80", "It makes Rs 30", "It breaks even"], 0,
        "30 - 50 = -20: a loss of Rs 20 a day. It must sell more or cut costs.",
        "একটা স্টলের ভাড়া দিনে 50 টাকা। ভাড়ার আগে লাভ 30 টাকা। কী হয়?", ["দিনে 20 টাকা লোকসান", "80 টাকা লাভ", "30 টাকা লাভ", "লাভ-লোকসান সমান"],
        "30 - 50 = -20: দিনে 20 টাকা লোকসান। বেশি বেচতে বা খরচ কমাতে হবে।"),
    mcq("What does 'break even' mean?", ["Money in equals costs - no profit, no loss", "Breaking a product", "Making a huge profit", "Closing the shop"], 0,
        "At break-even, sales just cover costs.",
        "'লাভ-লোকসান সমান' (ব্রেক-ইভেন) মানে কী?", ["আয় খরচের সমান - লাভও নেই, লোকসানও নেই", "পণ্য ভেঙে ফেলা", "বিশাল লাভ", "দোকান বন্ধ করা"],
        "ব্রেক-ইভেনে বিক্রি ঠিক খরচটুকু মেটায়।"),
    mcq("A bridge toll company earns Rs 500 a day and pays Rs 500 a day in costs. It is...", ["Breaking even", "Making a profit", "Making a loss", "Closed"], 0,
        "Income = costs, so no profit and no loss.",
        "একটা সেতু-টোল কোম্পানি দিনে 500 টাকা আয় করে আর দিনে 500 টাকা খরচ করে। এটা...", ["লাভ-লোকসান সমান", "লাভ করছে", "লোকসান করছে", "বন্ধ"],
        "আয় = খরচ, তাই লাভও নেই, লোকসানও নেই।"),
    mcq("What is 'stock'?", ["Goods a shop has ready to sell", "A soup only", "The shop owner", "The customers"], 0,
        "Shops keep stock so customers can buy straight away.",
        "'মজুত' কী?", ["দোকানে বিক্রির জন্য তৈরি মাল", "শুধু একটা স্যুপ", "দোকানের মালিক", "খদ্দেররা"],
        "দোকান মজুত রাখে, যাতে খদ্দের সঙ্গে সঙ্গে কিনতে পারে।"),
    mcq("Why is keeping too much stock a problem?", ["It ties up money and may spoil or go out of fashion", "It makes the shop lighter", "Stock pays rent", "It is never a problem"], 0,
        "Unsold stock is money sitting on shelves, and food can go bad.",
        "বেশি মজুত রাখা সমস্যা কেন?", ["টাকা আটকে থাকে আর মাল নষ্ট বা পুরোনো হয়ে যেতে পারে", "দোকান হালকা হয়", "মজুত ভাড়া দেয়", "কখনো সমস্যা নয়"],
        "অবিক্রীত মজুত মানে তাকে বসে থাকা টাকা, আর খাবার নষ্ট হতে পারে।"),
    mcq("Why is keeping too little stock a problem?", ["Customers find nothing to buy and go elsewhere", "It saves too much money", "Shelves get heavy", "It is never a problem"], 0,
        "Empty shelves lose sales.",
        "কম মজুত রাখা সমস্যা কেন?", ["খদ্দের কেনার কিছু না পেয়ে অন্য দোকানে যায়", "খুব বেশি টাকা বাঁচে", "তাক ভারী হয়", "কখনো সমস্যা নয়"],
        "খালি তাক বিক্রি হারায়।"),
    mcq("What is a 'supplier'?", ["A business that sells goods to other businesses", "A customer at a shop", "A bridge", "A coin"], 0,
        "A bakery's flour supplier sells flour to the bakery.",
        "'সরবরাহকারী' কে?", ["যে ব্যবসা অন্য ব্যবসাকে মাল বেচে", "দোকানের খদ্দের", "একটা সেতু", "একটা পয়সা"],
        "বেকারির আটা-সরবরাহকারী বেকারিকে আটা বেচে।"),
    mcq("A steel company sells beams to a bridge builder. The steel company is the builder's...", ["Supplier", "Customer", "Competitor", "Teacher"], 0,
        "The builder buys from the supplier.",
        "একটা ইস্পাত কোম্পানি সেতু-নির্মাতাকে বিম বেচে। ইস্পাত কোম্পানি নির্মাতার...", ["সরবরাহকারী", "খদ্দের", "প্রতিযোগী", "শিক্ষক"],
        "নির্মাতা সরবরাহকারীর থেকে কেনেন।"),
    mcq("What is 'wholesale'?", ["Selling large amounts, often to shops, at a lower price each", "Selling one item to a customer", "Giving things free", "A broken sale"], 0,
        "Shops buy wholesale in bulk and sell retail, one by one.",
        "'পাইকারি' কী?", ["অনেক পরিমাণে, প্রায়ই দোকানকে, প্রতিটি কম দামে বেচা", "একজন খদ্দেরকে একটা জিনিস বেচা", "বিনামূল্যে দেওয়া", "ভাঙা সেল"],
        "দোকান পাইকারি দামে একসঙ্গে অনেক কেনে আর খুচরো, একটা একটা করে বেচে।"),
    mcq("A shop buys 10 pens wholesale for Rs 50 and sells each for Rs 8. What is the profit if all sell?", ["Rs 30", "Rs 80", "Rs 50", "Rs 3"], 0,
        "Revenue 10 x 8 = 80; cost 50; profit 80 - 50 = Rs 30.",
        "একটা দোকান পাইকারি 50 টাকায় 10টি কলম কিনে প্রতিটি 8 টাকায় বেচে। সব বিক্রি হলে লাভ কত?", ["30 টাকা", "80 টাকা", "50 টাকা", "3 টাকা"],
        "আয় 10 x 8 = 80; খরচ 50; লাভ 80 - 50 = 30 টাকা।"),
    mcq("What is 'retail'?", ["Selling goods to the final customer", "Buying in huge bulk", "Making goods in a factory", "Shipping by sea"], 0,
        "Retail shops sell directly to people like you.",
        "'খুচরো বিক্রি' কী?", ["শেষ খদ্দেরকে মাল বেচা", "বিশাল পরিমাণে কেনা", "কারখানায় মাল বানানো", "সমুদ্রে জাহাজে পাঠানো"],
        "খুচরো দোকান সরাসরি তোমার মতো মানুষকে বেচে।"),
    mcq("Why do toy shops sell more in the festival season?", ["Demand rises because many people buy gifts", "Toys get cheaper then", "Shops are closed other times", "No reason"], 0,
        "Seasonal demand: shops stock up before busy times.",
        "উৎসবের মরসুমে খেলনার দোকানে বিক্রি বেশি কেন?", ["অনেকে উপহার কেনে, তাই চাহিদা বাড়ে", "তখন খেলনা সস্তা হয়", "অন্য সময় দোকান বন্ধ থাকে", "কোনো কারণ নেই"],
        "মরসুমি চাহিদা: ভিড়ের সময়ের আগে দোকান মজুত বাড়ায়।"),
    mcq("A company puts its logo on every product. What is it building?", ["A brand people recognise", "A bridge", "A loan", "A tax"], 0,
        "A strong brand helps customers remember and trust a company.",
        "একটা কোম্পানি প্রতিটি পণ্যে তার লোগো দেয়। কী গড়ে তুলছে?", ["মানুষ চেনে এমন ব্র্যান্ড", "একটা সেতু", "একটা ঋণ", "একটা কর"],
        "শক্তিশালী ব্র্যান্ড খদ্দেরকে কোম্পানি মনে রাখতে আর ভরসা করতে সাহায্য করে।"),
    mcq("What is 'packaging' for?", ["Protecting goods and showing information about them", "Making goods heavier", "Hiding prices", "Nothing"], 0,
        "Packaging keeps goods safe in transport and tells you what is inside.",
        "'মোড়ক' কীসের জন্য?", ["মাল রক্ষা আর তার তথ্য দেখানো", "মাল ভারী করা", "দাম লুকানো", "কিছুই না"],
        "মোড়ক পরিবহনে মাল নিরাপদ রাখে আর ভেতরে কী আছে জানায়।"),
    mcq("Why do some shops use paper bags instead of plastic?", ["Paper breaks down more easily and is better for the environment", "Paper is waterproof", "Plastic is illegal everywhere", "Paper is heavier"], 0,
        "Many businesses choose greener packaging to reduce litter.",
        "কিছু দোকান প্লাস্টিকের বদলে কাগজের ব্যাগ ব্যবহার করে কেন?", ["কাগজ সহজে নষ্ট হয়ে মিশে যায়, পরিবেশের জন্য ভালো", "কাগজ জলরোধী", "প্লাস্টিক সব জায়গায় বেআইনি", "কাগজ বেশি ভারী"],
        "আবর্জনা কমাতে অনেক ব্যবসা পরিবেশবান্ধব মোড়ক বাছে।"),
    mcq("A customer returns a broken toy with the receipt. What should a good shop do?", ["Replace it or give the money back", "Shout at the customer", "Keep the money and the toy", "Close the shop"], 0,
        "Fair returns keep customers loyal.",
        "এক খদ্দের রসিদসহ ভাঙা খেলনা ফেরত আনলেন। ভালো দোকানের কী করা উচিত?", ["বদলে দেওয়া বা টাকা ফেরত দেওয়া", "খদ্দেরের দিকে চেঁচানো", "টাকা আর খেলনা দুটোই রাখা", "দোকান বন্ধ করা"],
        "ন্যায্য ফেরত নীতি খদ্দেরকে অনুগত রাখে।"),
    mcq("What is 'quality'?", ["How good and well made something is", "How many there are", "Its price only", "Its colour only"], 0,
        "High quality means it works well and lasts.",
        "'মান' কী?", ["জিনিসটা কতটা ভালো আর ভালোভাবে তৈরি", "কতগুলো আছে", "শুধু তার দাম", "শুধু তার রং"],
        "উচ্চমান মানে ভালো কাজ করে আর টেকে।"),
    mcq("A builder uses cheap, poor-quality bolts on a bridge to save money. What is the risk?", ["The bridge may fail, costing far more", "Nothing at all", "Bolts get stronger", "The bridge gets prettier"], 0,
        "Saving a little on quality can cost a lot later - in repairs, salvage and safety.",
        "একজন নির্মাতা টাকা বাঁচাতে সেতুতে সস্তা, নিম্নমানের বল্টু ব্যবহার করলেন। ঝুঁকি কী?", ["সেতু ভেঙে আরও অনেক বেশি খরচ হতে পারে", "কিছুই না", "বল্টু আরও শক্ত হয়", "সেতু আরও সুন্দর হয়"],
        "মানে সামান্য বাঁচালে পরে অনেক খরচ হতে পারে - মেরামত, উদ্ধার আর নিরাপত্তায়।"),
    mcq("What is a 'market'?", ["A place where buyers and sellers meet to trade", "A bridge", "A bank vault", "A library"], 0,
        "Markets can be streets full of stalls - or websites.",
        "'বাজার' কী?", ["যেখানে ক্রেতা আর বিক্রেতা বেচাকেনায় মেলে", "একটা সেতু", "ব্যাংকের ভল্ট", "লাইব্রেরি"],
        "বাজার হতে পারে স্টলে ভরা রাস্তা - বা ওয়েবসাইট।"),
    mcq("What is 'online shopping'?", ["Buying things using the internet", "Shopping on a rope", "Shopping in a line", "Shopping at night only"], 0,
        "You order on a website or app and the goods are delivered.",
        "'অনলাইন কেনাকাটা' কী?", ["ইন্টারনেটে জিনিস কেনা", "দড়ির উপর কেনাকাটা", "লাইনে দাঁড়িয়ে কেনাকাটা", "শুধু রাতে কেনাকাটা"],
        "ওয়েবসাইট বা অ্যাপে অর্ডার দিলে জিনিস পৌঁছে যায়।"),
    mcq("Why do online shops depend on good roads and bridges?", ["Parcels must be delivered by vans and trucks", "Websites live on bridges", "Bridges have internet", "They do not"], 0,
        "Every online order still travels by road, rail or sea to reach you.",
        "অনলাইন দোকান ভালো রাস্তা আর সেতুর উপর নির্ভর করে কেন?", ["পার্সেল ভ্যান আর ট্রাকে পৌঁছাতে হয়", "ওয়েবসাইট সেতুতে থাকে", "সেতুতে ইন্টারনেট আছে", "নির্ভর করে না"],
        "প্রতিটি অনলাইন অর্ডারও রাস্তা, রেল বা সমুদ্রপথে তোমার কাছে আসে।"),
    mcq("A shop buys a toy for Rs 60 and wants Rs 20 profit. What price should it charge?", ["Rs 80", "Rs 40", "Rs 60", "Rs 20"], 0,
        "Price = cost + profit = 60 + 20 = Rs 80.",
        "একটা দোকান 60 টাকায় একটা খেলনা কিনে 20 টাকা লাভ চায়। কত দাম রাখবে?", ["80 টাকা", "40 টাকা", "60 টাকা", "20 টাকা"],
        "দাম = খরচ + লাভ = 60 + 20 = 80 টাকা।"),
    mcq("What is a 'discount'?", ["An amount taken off the normal price", "An extra charge", "A tax", "A delivery"], 0,
        "A Rs 10 discount on a Rs 50 item means you pay Rs 40.",
        "'ছাড়' কী?", ["সাধারণ দাম থেকে কমানো অঙ্ক", "বাড়তি মাশুল", "একটা কর", "একটা ডেলিভারি"],
        "50 টাকার জিনিসে 10 টাকা ছাড় মানে দেবে 40 টাকা।"),
    mcq("A Rs 120 shirt has a Rs 30 discount. What do you pay?", ["Rs 90", "Rs 150", "Rs 30", "Rs 120"], 0,
        "120 - 30 = Rs 90.",
        "120 টাকার জামায় 30 টাকা ছাড়। কত দেবে?", ["90 টাকা", "150 টাকা", "30 টাকা", "120 টাকা"],
        "120 - 30 = 90 টাকা।"),
    mcq("Why do shops give discounts?", ["To attract buyers or sell off old stock", "Because they love losing money", "It is the law", "To make goods heavier"], 0,
        "Discounts can bring customers in and clear shelves for new stock.",
        "দোকান ছাড় দেয় কেন?", ["ক্রেতা টানতে বা পুরোনো মজুত বেচতে", "কারণ লোকসান ভালোবাসে", "এটা আইন", "মাল ভারী করতে"],
        "ছাড় খদ্দের টানে আর নতুন মজুতের জন্য তাক খালি করে।"),
    mcq("What is a 'loyalty card'?", ["A card that rewards customers who keep coming back", "A bank loan card", "A birthday card", "A ticket for a bus"], 0,
        "Points or free items reward repeat customers.",
        "'লয়্যালটি কার্ড' কী?", ["যে কার্ড বারবার আসা খদ্দেরকে পুরস্কার দেয়", "ব্যাংক ঋণের কার্ড", "জন্মদিনের কার্ড", "বাসের টিকিট"],
        "পয়েন্ট বা বিনামূল্যের জিনিস নিয়মিত খদ্দেরকে পুরস্কার দেয়।"),
    mcq("A café gives a free coffee after 9 paid ones. You buy 18. How many free coffees do you get?", ["2", "9", "1", "18"], 0,
        "Every 9 paid earns 1 free: 18 ÷ 9 = 2.",
        "একটা ক্যাফে 9টি কেনা কফির পর 1টি বিনামূল্যে দেয়। তুমি 18টি কিনলে। কয়টি বিনামূল্যে পাবে?", ["2", "9", "1", "18"],
        "প্রতি 9টি কেনায় 1টি ফ্রি: 18 ÷ 9 = 2।"),
    mcq("What does an 'entrepreneur' do?", ["Starts and runs a new business", "Only buys things", "Builds roads only", "Works in a bank only"], 0,
        "Entrepreneurs spot a need, take a risk and build a business to meet it.",
        "'উদ্যোক্তা' কী করেন?", ["নতুন ব্যবসা শুরু করে চালান", "শুধু জিনিস কেনেন", "শুধু রাস্তা বানান", "শুধু ব্যাংকে কাজ করেন"],
        "উদ্যোক্তা একটা প্রয়োজন খুঁজে, ঝুঁকি নিয়ে তা মেটানোর ব্যবসা গড়েন।"),
    mcq("You notice many students want cold water after sports. What business idea fits?", ["A cold-water stall near the playground", "A snow-boot shop", "A heater shop", "A kite shop in a cave"], 0,
        "Good businesses meet a real need where customers are.",
        "তুমি দেখলে খেলার পরে অনেক ছাত্র ঠান্ডা জল চায়। কোন ব্যবসার ধারণা মানায়?", ["খেলার মাঠের কাছে ঠান্ডা জলের স্টল", "বরফের বুটের দোকান", "হিটারের দোকান", "গুহায় ঘুড়ির দোকান"],
        "ভালো ব্যবসা যেখানে খদ্দের সেখানেই আসল প্রয়োজন মেটায়।"),
    mcq("What is a 'risk' in business?", ["The chance of losing money if things go wrong", "A guaranteed profit", "A type of coin", "A free gift"], 0,
        "Every business takes risks - like making lemonade on a day it rains.",
        "ব্যবসায় 'ঝুঁকি' কী?", ["কিছু ভুল হলে টাকা হারানোর সম্ভাবনা", "নিশ্চিত লাভ", "এক রকম পয়সা", "বিনামূল্যের উপহার"],
        "প্রতিটি ব্যবসা ঝুঁকি নেয় - যেমন বৃষ্টির দিনে শরবত বানানো।"),
    mcq("How can a lemonade seller reduce the risk of a rainy day?", ["Also sell hot tea", "Make more lemonade", "Close forever", "Raise prices to Rs 1000"], 0,
        "Selling different products spreads the risk.",
        "শরবতওয়ালা বৃষ্টির দিনের ঝুঁকি কীভাবে কমাতে পারেন?", ["গরম চা-ও বেচে", "আরও শরবত বানিয়ে", "চিরতরে বন্ধ করে", "দাম 1000 টাকা করে"],
        "নানা রকম পণ্য বেচলে ঝুঁকি ভাগ হয়ে যায়।"),
    mcq("What is 'trade' between countries?", ["Buying and selling goods across borders", "A football match", "A shared holiday", "A bridge"], 0,
        "Countries sell what they make well and buy what others make well.",
        "দেশের মধ্যে 'বাণিজ্য' কী?", ["সীমান্তের এপার-ওপার জিনিস কেনাবেচা", "ফুটবল ম্যাচ", "একসঙ্গে ছুটি", "একটা সেতু"],
        "দেশগুলো যা ভালো বানায় তা বেচে, অন্যরা যা ভালো বানায় তা কেনে।"),
    mcq("Goods sold to another country are called...", ["Exports", "Imports", "Loans", "Taxes"], 0,
        "Exports go out; imports come in.",
        "অন্য দেশে বেচা জিনিসকে বলে...", ["রপ্তানি", "আমদানি", "ঋণ", "কর"],
        "রপ্তানি বাইরে যায়; আমদানি ভেতরে আসে।"),
    mcq("Why do ports need strong cranes and bridges nearby?", ["To move heavy containers to trucks and trains", "For fishing", "For decoration", "To store water"], 0,
        "Trade needs a smooth chain from ship to road and rail.",
        "বন্দরের কাছে শক্তিশালী ক্রেন আর সেতু লাগে কেন?", ["ভারী কন্টেইনার ট্রাক আর ট্রেনে তুলতে", "মাছ ধরতে", "সাজসজ্জার জন্য", "জল জমাতে"],
        "বাণিজ্যের জন্য জাহাজ থেকে রাস্তা আর রেল পর্যন্ত মসৃণ শিকল লাগে।"),
    mcq("What is a 'receipt'?", ["Proof of what you bought and paid", "A cooking recipe", "A price tag", "A loan"], 0,
        "Keep receipts in case you need to return something.",
        "'রসিদ' কী?", ["কী কিনলে আর কত দিলে তার প্রমাণ", "রান্নার প্রণালী", "দামের ট্যাগ", "একটা ঋণ"],
        "কিছু ফেরত দিতে লাগতে পারে, তাই রসিদ রেখে দাও।"),
    mcq("What does 'cash register' (till) do?", ["Records sales and holds the money", "Bakes bread", "Delivers parcels", "Builds shelves"], 0,
        "The till adds up prices and keeps a record of every sale.",
        "'ক্যাশ রেজিস্টার' কী করে?", ["বিক্রি লিখে রাখে আর টাকা রাখে", "রুটি সেঁকে", "পার্সেল পৌঁছায়", "তাক বানায়"],
        "ক্যাশ মেশিন দাম যোগ করে আর প্রতিটি বিক্রির হিসাব রাখে।"),
    mcq("What is a 'barcode' for?", ["A machine reads it to find the product and price", "Decoration", "To hold the box shut", "It is a toy"], 0,
        "Scanning barcodes makes checkout fast and keeps stock records accurate.",
        "'বারকোড' কীসের জন্য?", ["যন্ত্র পড়ে পণ্য আর দাম খুঁজে নেয়", "সাজসজ্জার জন্য", "বাক্স বন্ধ রাখতে", "এটা খেলনা"],
        "বারকোড স্ক্যান বিল দ্রুত করে আর মজুতের হিসাব সঠিক রাখে।"),
    mcq("A shopkeeper counts 45 apples in the morning and 12 at closing. How many were sold?", ["33", "57", "45", "12"], 0,
        "45 - 12 = 33 apples sold.",
        "একজন দোকানদার সকালে 45টি আপেল গুনলেন আর বন্ধের সময় 12টি। কয়টি বিক্রি হলো?", ["33", "57", "45", "12"],
        "45 - 12 = 33টি আপেল বিক্রি।"),
    mcq("If each of those 33 apples sold for Rs 6, what was the revenue?", ["Rs 198", "Rs 39", "Rs 33", "Rs 180"], 0,
        "33 x 6 = Rs 198.",
        "সেই 33টি আপেলের প্রতিটি 6 টাকায় বিক্রি হলে আয় কত?", ["198 টাকা", "39 টাকা", "33 টাকা", "180 টাকা"],
        "33 x 6 = 198 টাকা।"),
    mcq("What is a 'price list'?", ["A list showing the prices of goods", "A list of customers", "A shopping trolley", "A loan form"], 0,
        "Clear price lists help customers choose and trust the shop.",
        "'দামের তালিকা' কী?", ["মালের দাম দেখানো তালিকা", "খদ্দেরদের তালিকা", "শপিং ট্রলি", "ঋণের ফর্ম"],
        "স্পষ্ট দামের তালিকা খদ্দেরকে বাছতে আর দোকানে ভরসা করতে সাহায্য করে।"),
    mcq("A toll bridge charges Rs 10 for cars and Rs 40 for trucks. 20 cars and 5 trucks cross. Total toll?", ["Rs 400", "Rs 250", "Rs 50", "Rs 600"], 0,
        "Cars: 20 x 10 = 200. Trucks: 5 x 40 = 200. Total Rs 400.",
        "একটা টোল সেতু গাড়ির জন্য 10 টাকা আর ট্রাকের জন্য 40 টাকা নেয়। 20টি গাড়ি আর 5টি ট্রাক পার হলো। মোট টোল?", ["400 টাকা", "250 টাকা", "50 টাকা", "600 টাকা"],
        "গাড়ি: 20 x 10 = 200। ট্রাক: 5 x 40 = 200। মোট 400 টাকা।"),
    mcq("Why do trucks pay a higher bridge toll than cars?", ["They are heavier and wear the bridge more", "Trucks are richer", "Trucks are faster", "No reason"], 0,
        "Heavier vehicles cause more wear, so they pay more for maintenance.",
        "ট্রাক গাড়ির চেয়ে বেশি টোল দেয় কেন?", ["ভারী বলে সেতুর ক্ষয় বেশি করে", "ট্রাক বেশি ধনী", "ট্রাক বেশি দ্রুত", "কোনো কারণ নেই"],
        "ভারী গাড়ি বেশি ক্ষয় করে, তাই রক্ষণাবেক্ষণের জন্য বেশি দেয়।"),
    mcq("What is 'customer service'?", ["Helping customers before and after they buy", "Selling only", "Delivering bridges", "Counting stock"], 0,
        "Friendly help and fixing problems keep customers happy.",
        "'গ্রাহক পরিষেবা' কী?", ["কেনার আগে আর পরে খদ্দেরকে সাহায্য", "শুধু বিক্রি", "সেতু পৌঁছে দেওয়া", "মজুত গোনা"],
        "আন্তরিক সাহায্য আর সমস্যার সমাধান খদ্দেরকে খুশি রাখে।"),
    mcq("A bakery sells 20 loaves a day. How many in a week (7 days)?", ["140", "27", "120", "70"], 0,
        "20 x 7 = 140 loaves.",
        "একটা বেকারি দিনে 20টি পাউরুটি বেচে। এক সপ্তাহে (7 দিন) কয়টি?", ["140", "27", "120", "70"],
        "20 x 7 = 140টি পাউরুটি।"),
    mcq("Why do businesses keep a record of what sells best?", ["To order more of the popular items", "To decorate the walls", "To confuse staff", "It is not useful"], 0,
        "Knowing best sellers helps businesses plan stock and earn more.",
        "কোনটা সবচেয়ে বেশি বিক্রি হয় তার হিসাব ব্যবসা রাখে কেন?", ["জনপ্রিয় জিনিস বেশি আনাতে", "দেয়াল সাজাতে", "কর্মীদের বিভ্রান্ত করতে", "কাজের নয়"],
        "সেরা বিক্রির জিনিস জানলে মজুত পরিকল্পনা আর বেশি আয় হয়।"),
    mcq("What does 'fair trade' mean?", ["Paying farmers and workers a fair price for their work", "Trading at a fair (funfair)", "Free goods", "Cheapest price always"], 0,
        "Fair trade helps producers earn enough to live well.",
        "'ন্যায্য বাণিজ্য' মানে কী?", ["চাষি আর শ্রমিকদের কাজের ন্যায্য দাম দেওয়া", "মেলায় বেচাকেনা", "বিনামূল্যের মাল", "সবসময় সবচেয়ে কম দাম"],
        "ন্যায্য বাণিজ্য উৎপাদকদের ভালোভাবে বাঁচার মতো আয় করতে সাহায্য করে।"),
    mcq("A company makes 100 toys a day and sells 80. What happens to the extra 20?", ["They go into stock", "They disappear", "They are eaten", "They become money by themselves"], 0,
        "Unsold toys become stock for the next day - too much and it must slow production.",
        "একটা কোম্পানি দিনে 100টি খেলনা বানায় আর 80টি বেচে। বাড়তি 20টির কী হয়?", ["মজুতে যায়", "উধাও হয়", "খাওয়া হয়", "নিজে থেকে টাকা হয়ে যায়"],
        "অবিক্রীত খেলনা পরদিনের মজুত হয় - বেশি হলে উৎপাদন কমাতে হয়।"),
    mcq("What is a 'shop sign' for?", ["Telling people the shop's name and what it sells", "Keeping rain out", "Holding the roof", "Counting money"], 0,
        "A clear sign helps customers find you.",
        "দোকানের 'সাইনবোর্ড' কীসের জন্য?", ["দোকানের নাম আর কী বেচে জানাতে", "বৃষ্টি আটকাতে", "ছাদ ধরে রাখতে", "টাকা গুনতে"],
        "স্পষ্ট সাইনবোর্ড খদ্দেরকে তোমায় খুঁজে পেতে সাহায্য করে।"),
    mcq("A fruit seller's mangoes go bad after 3 days. What should he do on day 2 if many are left?", ["Lower the price to sell them quickly", "Raise the price", "Hide them", "Wait until they rot"], 0,
        "Selling cheaper is better than throwing food away.",
        "একজন ফলওয়ালার আম 3 দিনে নষ্ট হয়ে যায়। দ্বিতীয় দিনে অনেক বাকি থাকলে কী করা উচিত?", ["দাম কমিয়ে তাড়াতাড়ি বেচা", "দাম বাড়ানো", "লুকিয়ে রাখা", "পচা পর্যন্ত অপেক্ষা করা"],
        "খাবার ফেলে দেওয়ার চেয়ে সস্তায় বেচা ভালো।"),
    mcq("Why do businesses employ workers?", ["To get more work done than one person could", "To spend money for fun", "It is required for all", "Workers pay the business"], 0,
        "More hands make more products and serve more customers.",
        "ব্যবসা শ্রমিক নিয়োগ করে কেন?", ["একজনের চেয়ে বেশি কাজ করাতে", "মজা করে টাকা খরচ করতে", "সবার জন্য বাধ্যতামূলক", "শ্রমিকরা ব্যবসাকে টাকা দেয়"],
        "বেশি হাতে বেশি পণ্য তৈরি হয় আর বেশি খদ্দের সেবা পায়।"),
    mcq("A bridge-building company wins a contract worth Rs 10 lakh. Its costs are Rs 8 lakh. Profit?", ["Rs 2 lakh", "Rs 18 lakh", "Rs 8 lakh", "Rs 10 lakh"], 0,
        "10 - 8 = Rs 2 lakh. (1 lakh = 1,00,000.)",
        "একটা সেতু-নির্মাণ কোম্পানি 10 লাখ টাকার চুক্তি পেল। খরচ 8 লাখ টাকা। লাভ?", ["2 লাখ টাকা", "18 লাখ টাকা", "8 লাখ টাকা", "10 লাখ টাকা"],
        "10 - 8 = 2 লাখ টাকা। (1 লাখ = 1,00,000।)"),
    mcq("What is a 'contract'?", ["A written agreement about work and payment", "A kind of bridge", "A coin", "A toy"], 0,
        "Contracts say what will be built, by when, and for how much.",
        "'চুক্তি' কী?", ["কাজ আর পারিশ্রমিক নিয়ে লিখিত সমঝোতা", "এক রকম সেতু", "একটা পয়সা", "একটা খেলনা"],
        "চুক্তিতে লেখা থাকে কী বানানো হবে, কবে, আর কত টাকায়।"),
    mcq("Why do builders give a 'quote' before starting?", ["To tell the customer how much the job will cost", "To sing", "To show a poem", "To confuse"], 0,
        "A quote (estimate) lets the customer compare and plan their budget.",
        "কাজ শুরুর আগে নির্মাতারা 'দরপত্র' দেন কেন?", ["খদ্দেরকে জানাতে কাজে কত খরচ হবে", "গান গাইতে", "কবিতা দেখাতে", "বিভ্রান্ত করতে"],
        "দরপত্র (আনুমানিক খরচ) খদ্দেরকে তুলনা আর বাজেট পরিকল্পনায় সাহায্য করে।"),
    mcq("Three builders quote Rs 50,000, Rs 45,000 and Rs 60,000 for the same safe job. Which is cheapest?", ["Rs 45,000", "Rs 50,000", "Rs 60,000", "They are equal"], 0,
        "45,000 is the lowest - but check quality and safety too!",
        "একই নিরাপদ কাজের জন্য তিনজন নির্মাতা 50,000, 45,000 আর 60,000 টাকা দর দিলেন। কোনটা সবচেয়ে সস্তা?", ["45,000 টাকা", "50,000 টাকা", "60,000 টাকা", "সব সমান"],
        "45,000 সবচেয়ে কম - তবে মান আর নিরাপত্তাও যাচাই করো!"),
    mcq("What is 'transport cost'?", ["Money spent moving goods from place to place", "The price of a bus toy", "A shop's rent", "A tax on sweets"], 0,
        "Fuel, drivers, tolls and vehicle wear all add up to transport cost.",
        "'পরিবহন খরচ' কী?", ["এক জায়গা থেকে আরেক জায়গায় মাল নিতে যে টাকা লাগে", "খেলনা বাসের দাম", "দোকানের ভাড়া", "মিষ্টির উপর কর"],
        "জ্বালানি, চালক, টোল আর গাড়ির ক্ষয় মিলে পরিবহন খরচ।"),
    mcq("A truck delivers 50 sacks and the trip costs Rs 500. What is the transport cost per sack?", ["Rs 10", "Rs 50", "Rs 500", "Rs 550"], 0,
        "500 ÷ 50 = Rs 10 per sack.",
        "একটা ট্রাক 50 বস্তা পৌঁছাল আর যাত্রায় খরচ 500 টাকা। প্রতি বস্তায় পরিবহন খরচ কত?", ["10 টাকা", "50 টাকা", "500 টাকা", "550 টাকা"],
        "500 ÷ 50 = প্রতি বস্তায় 10 টাকা।"),
    mcq("If the truck could carry 100 sacks for the same Rs 500 trip, the cost per sack would be...", ["Rs 5", "Rs 10", "Rs 50", "Rs 100"], 0,
        "500 ÷ 100 = Rs 5. Bigger loads per trip lower the cost per item - if the bridge can carry them!",
        "একই 500 টাকার যাত্রায় ট্রাক 100 বস্তা নিতে পারলে প্রতি বস্তার খরচ হতো...", ["5 টাকা", "10 টাকা", "50 টাকা", "100 টাকা"],
        "500 ÷ 100 = 5 টাকা। প্রতি যাত্রায় বড় বোঝা প্রতি জিনিসের খরচ কমায় - যদি সেতু তা বইতে পারে!"),
    mcq("What is a 'franchise' like a chain of tea shops?", ["Many shops using the same brand and way of working", "A single home kitchen", "A government office", "A bridge toll"], 0,
        "Chain shops share a name, menu and style in many places.",
        "চায়ের দোকানের চেইনের মতো 'ফ্র্যাঞ্চাইজ' কী?", ["একই ব্র্যান্ড আর কাজের ধরন মেনে চলা অনেক দোকান", "একটা বাড়ির রান্নাঘর", "সরকারি অফিস", "সেতুর টোল"],
        "চেইন দোকান অনেক জায়গায় একই নাম, মেনু আর ধরন ভাগ করে।"),
    mcq("Which is a good business habit?", ["Keeping promises to customers and suppliers", "Missing every deadline", "Hiding prices", "Never paying suppliers"], 0,
        "Reliability builds a good reputation, which brings more business.",
        "কোনটা ব্যবসার ভালো অভ্যাস?", ["খদ্দের আর সরবরাহকারীকে দেওয়া কথা রাখা", "প্রতিটি সময়সীমা ফস্কানো", "দাম লুকানো", "কখনো সরবরাহকারীর পাওনা না দেওয়া"],
        "নির্ভরযোগ্যতা সুনাম গড়ে, আর সুনাম আরও ব্যবসা আনে।"),
    mcq("A bus company charges Rs 15 a ticket and carries 40 people a trip. How much per trip?", ["Rs 600", "Rs 55", "Rs 400", "Rs 150"], 0,
        "40 x 15 = Rs 600.",
        "একটা বাস কোম্পানি টিকিটপ্রতি 15 টাকা নেয় আর প্রতি যাত্রায় 40 জন বয়। প্রতি যাত্রায় কত?", ["600 টাকা", "55 টাকা", "400 টাকা", "150 টাকা"],
        "40 x 15 = 600 টাকা।"),
    mcq("Why might a bus company stop running a route?", ["Too few passengers to cover the costs", "Too many happy passengers", "Roads are too smooth", "Buses are free"], 0,
        "If fares do not cover fuel, drivers and repairs, the route loses money.",
        "একটা বাস কোম্পানি একটা রুট বন্ধ করে দিতে পারে কেন?", ["খরচ মেটানোর মতো যাত্রী খুব কম", "অনেক খুশি যাত্রী", "রাস্তা খুব মসৃণ", "বাস বিনামূল্যে"],
        "ভাড়ায় জ্বালানি, চালক আর মেরামতের খরচ না উঠলে রুটে লোকসান হয়।"),
    mcq("A new bridge brings 3 times more visitors to a town market. What may happen to the market's sales?", ["They may rise", "They may fall", "Nothing changes", "The market disappears"], 0,
        "More visitors usually means more buyers.",
        "নতুন সেতু একটা শহরের বাজারে 3 গুণ বেশি মানুষ আনল। বাজারের বিক্রির কী হতে পারে?", ["বাড়তে পারে", "কমতে পারে", "কিছুই বদলায় না", "বাজার উধাও হয়"],
        "বেশি দর্শনার্থী মানে সাধারণত বেশি ক্রেতা।"),
    mcq("What is a 'stall plan'?", ["A simple plan of what to sell, prices, costs and where", "A map of the stars", "A drawing of a horse", "A shopping bag"], 0,
        "Even a small stall works better with a plan.",
        "'স্টলের পরিকল্পনা' কী?", ["কী বেচবে, দাম, খরচ আর কোথায় - তার সহজ পরিকল্পনা", "তারার মানচিত্র", "ঘোড়ার ছবি", "বাজারের ব্যাগ"],
        "ছোট স্টলও পরিকল্পনা থাকলে ভালো চলে।"),
    mcq("You sell bracelets: 10 on Monday, 15 on Tuesday, 5 on Wednesday. On which day did you sell the most?", ["Tuesday", "Monday", "Wednesday", "All equal"], 0,
        "15 is the biggest number.",
        "তুমি ব্রেসলেট বেচো: সোমবার 10টি, মঙ্গলবার 15টি, বুধবার 5টি। কোন দিন সবচেয়ে বেশি বিক্রি?", ["মঙ্গলবার", "সোমবার", "বুধবার", "সব সমান"],
        "15 সবচেয়ে বড় সংখ্যা।"),
    mcq("In that week (10, 15, 5 bracelets), how many did you sell in all?", ["30", "25", "20", "15"], 0,
        "10 + 15 + 5 = 30.",
        "সেই সপ্তাহে (10, 15, 5টি ব্রেসলেট) মোট কয়টি বেচলে?", ["30", "25", "20", "15"],
        "10 + 15 + 5 = 30।"),
    mcq("Why do many shops open near train stations and bus stops?", ["Lots of people pass by every day", "Trains buy goods", "Rent is always free there", "It is quieter"], 0,
        "Busy places mean more possible customers.",
        "অনেক দোকান রেলস্টেশন আর বাসস্টপের কাছে খোলে কেন?", ["প্রতিদিন অনেক মানুষ পাশ দিয়ে যায়", "ট্রেন মাল কেনে", "সেখানে ভাড়া সবসময় বিনামূল্যে", "জায়গাটা বেশি শান্ত"],
        "ব্যস্ত জায়গা মানে বেশি সম্ভাব্য খদ্দের।"),
    mcq("A shop sells 12 eggs in a box for Rs 72. What is the price per egg?", ["Rs 6", "Rs 12", "Rs 84", "Rs 60"], 0,
        "72 ÷ 12 = Rs 6 per egg.",
        "একটা দোকান 12টি ডিমের বাক্স 72 টাকায় বেচে। প্রতি ডিমের দাম কত?", ["6 টাকা", "12 টাকা", "84 টাকা", "60 টাকা"],
        "72 ÷ 12 = প্রতি ডিম 6 টাকা।"),
    mcq("Loose eggs cost Rs 7 each. Is the box of 12 for Rs 72 cheaper?", ["Yes - Rs 6 each instead of Rs 7", "No - loose is cheaper", "They are the same", "Eggs are free"], 0,
        "Buying the box saves Rs 1 per egg: Rs 12 in total.",
        "খোলা ডিম প্রতিটি 7 টাকা। 72 টাকায় 12টির বাক্স কি সস্তা?", ["হ্যাঁ - 7 টাকার বদলে প্রতিটি 6 টাকা", "না - খোলা সস্তা", "দুটো সমান", "ডিম বিনামূল্যে"],
        "বাক্স কিনলে প্রতি ডিমে 1 টাকা বাঁচে: মোট 12 টাকা।"),
    mcq("What happens to a business that treats customers badly?", ["Customers leave and sales fall", "Sales grow", "Nothing", "It gets free stock"], 0,
        "Word spreads fast - good service builds a business, bad service breaks it.",
        "যে ব্যবসা খদ্দেরের সঙ্গে খারাপ ব্যবহার করে তার কী হয়?", ["খদ্দের চলে যায় আর বিক্রি কমে", "বিক্রি বাড়ে", "কিছুই না", "বিনামূল্যে মজুত পায়"],
        "খবর দ্রুত ছড়ায় - ভালো ব্যবহার ব্যবসা গড়ে, খারাপ ব্যবহার ভাঙে।"),
    mcq("A town builds a bridge and charges Rs 5 toll. 400 people cross a day. Daily toll income?", ["Rs 2000", "Rs 405", "Rs 400", "Rs 80"], 0,
        "400 x 5 = Rs 2000 a day.",
        "একটা শহর সেতু বানিয়ে 5 টাকা টোল নেয়। দিনে 400 জন পার হন। দৈনিক টোল আয়?", ["2000 টাকা", "405 টাকা", "400 টাকা", "80 টাকা"],
        "400 x 5 = দিনে 2000 টাকা।"),
)
