"""Class 2 - Finance: earning, saving goals, spending plans, banks, borrowing and giving."""
from . import mcq


def total(n, price, item_en, item_bn):
    r = n * price
    o = [r, r + price, r - price, r + 2 * price]
    return mcq(f"One {item_en} costs Rs {price}. How much do {n} cost?", [f"Rs {x}" for x in o], 0,
               f"{n} x Rs {price} = Rs {r}.",
               f"একটি {item_bn}-এর দাম {price} টাকা। {n}টির দাম কত?", [f"{x} টাকা" for x in o],
               f"{n} x {price} টাকা = {r} টাকা।")


def weeks(goal, per, thing_en, thing_bn):
    r = -(-goal // per)
    o = [r, r + 1, r - 1, r + 2] if r > 1 else [r, r + 1, r + 2, r + 3]
    return mcq(f"You save Rs {per} a week for a Rs {goal} {thing_en}. How many weeks until you can buy it?",
               [str(x) for x in o], 0,
               f"Rs {goal} ÷ Rs {per} a week = {goal / per:g}, so {r} weeks.",
               f"তুমি {goal} টাকার একটি {thing_bn}-এর জন্য সপ্তাহে {per} টাকা জমাও। কত সপ্তাহে কিনতে পারবে?",
               [str(x) for x in o],
               f"{goal} টাকা ÷ সপ্তাহে {per} টাকা = {goal / per:g}, তাই {r} সপ্তাহ।")


ITEMS = (
    total(4, 12, "notebook", "খাতা"),
    total(3, 25, "pen set", "কলমের সেট"),
    total(5, 8, "banana", "কলা"),
    total(6, 15, "toy car", "খেলনা গাড়ি"),
    total(2, 45, "storybook", "গল্পের বই"),
    total(7, 10, "bus ticket", "বাসের টিকিট"),
    total(3, 30, "kg of rice", "কেজি চাল"),
    total(4, 20, "bag of cement", "বস্তা সিমেন্ট"),
    weeks(60, 10, "football", "ফুটবল"),
    weeks(100, 20, "bicycle bell and lights set", "সাইকেলের ঘণ্টি-বাতির সেট"),
    weeks(45, 5, "board game", "বোর্ড গেম"),
    weeks(90, 15, "school bag", "স্কুলব্যাগ"),
    weeks(50, 10, "kite and reel", "ঘুড়ি-লাটাই"),
    weeks(120, 30, "pair of shoes", "জোড়া জুতো"),
    weeks(80, 20, "paint box", "রঙের বাক্স"),
    mcq("What is income?", ["Money that comes in, like wages or pocket money", "Money you spend", "Money you owe", "A shop"], 0,
        "Income is money you receive. Spending (expenses) is money going out.",
        "আয় কী?", ["যে টাকা আসে, যেমন মজুরি বা হাতখরচ", "যে টাকা খরচ করো", "যে টাকা ধার আছে", "একটা দোকান"],
        "আয় হলো যে টাকা পাও। খরচ হলো যে টাকা বেরিয়ে যায়।"),
    mcq("What is an expense?", ["Money spent on something", "Money you earn", "A free gift", "A type of coin"], 0,
        "Expenses are what you pay out: food, rent, toys, bus fares.",
        "খরচ কী?", ["কোনো কিছুতে খরচ করা টাকা", "রোজগারের টাকা", "বিনামূল্যের উপহার", "এক রকম পয়সা"],
        "খরচ হলো যা দিয়ে দাও: খাবার, ভাড়া, খেলনা, বাসভাড়া।"),
    mcq("If your income is Rs 50 and your expenses are Rs 35, how much can you save?", ["Rs 15", "Rs 85", "Rs 35", "Rs 50"], 0,
        "Savings = income - expenses = 50 - 35 = Rs 15.",
        "তোমার আয় 50 টাকা আর খরচ 35 টাকা হলে কত জমাতে পারো?", ["15 টাকা", "85 টাকা", "35 টাকা", "50 টাকা"],
        "সঞ্চয় = আয় - খরচ = 50 - 35 = 15 টাকা।"),
    mcq("What happens if expenses are bigger than income?", ["You run short and may need to borrow", "You get richer", "Nothing", "Money doubles"], 0,
        "Spending more than you earn uses up savings or leads to debt.",
        "খরচ আয়ের চেয়ে বেশি হলে কী হয়?", ["টাকা কম পড়ে আর ধার করতে হতে পারে", "আরও ধনী হও", "কিছুই না", "টাকা দ্বিগুণ হয়"],
        "আয়ের চেয়ে বেশি খরচ করলে সঞ্চয় ফুরোয় বা দেনা হয়।"),
    mcq("A bank pays you a little extra for keeping your money there. What is it called?", ["Interest", "A fine", "A tax", "Change"], 0,
        "Interest is the reward for saving in a bank - and the cost of borrowing from one.",
        "ব্যাংক টাকা রাখার জন্য তোমাকে একটু বাড়তি দেয়। একে কী বলে?", ["সুদ", "জরিমানা", "কর", "খুচরো"],
        "সুদ হলো ব্যাংকে জমানোর পুরস্কার - আর ব্যাংক থেকে ধার নেওয়ার খরচ।"),
    mcq("You save Rs 100 in a bank that pays Rs 5 interest a year. How much after 1 year?", ["Rs 105", "Rs 100", "Rs 95", "Rs 150"], 0,
        "100 + 5 = Rs 105. Your money grew by itself!",
        "তুমি এমন ব্যাংকে 100 টাকা রাখলে, যা বছরে 5 টাকা সুদ দেয়। 1 বছর পরে কত হবে?", ["105 টাকা", "100 টাকা", "95 টাকা", "150 টাকা"],
        "100 + 5 = 105 টাকা। তোমার টাকা নিজে থেকেই বাড়ল!"),
    mcq("You borrow Rs 100 and must pay Rs 10 interest. How much do you pay back?", ["Rs 110", "Rs 100", "Rs 90", "Rs 10"], 0,
        "Borrowed amount + interest = 100 + 10 = Rs 110.",
        "তুমি 100 টাকা ধার নিলে আর 10 টাকা সুদ দিতে হবে। মোট কত ফেরত দেবে?", ["110 টাকা", "100 টাকা", "90 টাকা", "10 টাকা"],
        "ধার + সুদ = 100 + 10 = 110 টাকা।"),
    mcq("Why does borrowing cost extra?", ["The lender wants a reward for waiting for their money", "Banks are greedy only", "Money gets heavier", "It does not"], 0,
        "Interest pays the lender for letting you use their money now.",
        "ধার নিলে বাড়তি দিতে হয় কেন?", ["টাকা ফেরতের অপেক্ষার জন্য ঋণদাতা পুরস্কার চান", "শুধু ব্যাংকের লোভ", "টাকা ভারী হয়", "দিতে হয় না"],
        "সুদ ঋণদাতাকে দেয় তাঁর টাকা এখন ব্যবহার করতে দেওয়ার জন্য।"),
    mcq("Which loan is cheaper: 2% interest or 0.5% interest?", ["0.5%", "2%", "They are the same", "Neither has a cost"], 0,
        "A lower interest rate means less extra to pay - like the government loan in MODIS BridgeWorks.",
        "কোন ঋণ সস্তা: 2% সুদ নাকি 0.5% সুদ?", ["0.5%", "2%", "দুটো সমান", "কোনোটারই খরচ নেই"],
        "কম সুদের হার মানে কম বাড়তি দিতে হয় - যেমন MODIS BridgeWorks-এর সরকারি ঋণ।"),
    mcq("Why does writing down a saving goal help?", ["It reminds you what you are saving for and keeps you going", "It makes coins heavier", "Shops give discounts for lists", "It does not help"], 0,
        "Writing down a goal like 'Rs 200 for a cricket bat' helps you keep saving.",
        "সঞ্চয়ের লক্ষ্য লিখে রাখলে কেন সাহায্য হয়?", ["মনে করায় কীসের জন্য জমাচ্ছ আর চালিয়ে যেতে উৎসাহ দেয়", "পয়সা ভারী করে", "তালিকা থাকলে দোকান ছাড় দেয়", "সাহায্য হয় না"],
        "'ক্রিকেট ব্যাটের জন্য 200 টাকা'-র মতো লক্ষ্য লিখে রাখলে জমানো চালিয়ে যেতে সুবিধা হয়।"),
    mcq("Which is a good way to track your savings?", ["Keep a chart and add each amount", "Guess every month", "Never count", "Spend it to check"], 0,
        "A savings chart shows your progress and keeps you motivated.",
        "সঞ্চয়ের হিসাব রাখার ভালো উপায় কোনটা?", ["একটা চার্ট রেখে প্রতিবার যোগ করা", "প্রতি মাসে আন্দাজ করা", "কখনো না গোনা", "খরচ করে দেখা"],
        "সঞ্চয়ের চার্ট অগ্রগতি দেখায় আর উৎসাহ জোগায়।"),
    mcq("A family plan says: Rs 60 food, Rs 25 travel, Rs 15 savings out of Rs 100. What is this plan called?", ["A budget", "A receipt", "A loan", "A toll"], 0,
        "A budget splits income into spending and saving before the money is used.",
        "একটি পরিবারের পরিকল্পনা: 100 টাকার মধ্যে খাবারে 60, যাতায়াতে 25, সঞ্চয়ে 15 টাকা। একে কী বলে?", ["বাজেট", "রসিদ", "ঋণ", "টোল"],
        "বাজেট খরচের আগেই আয়কে খরচ আর সঞ্চয়ে ভাগ করে।"),
    mcq("In that budget (Rs 60 food, Rs 25 travel, Rs 15 savings), what is spent on food and travel together?", ["Rs 85", "Rs 75", "Rs 40", "Rs 100"], 0,
        "60 + 25 = Rs 85.",
        "সেই বাজেটে (খাবার 60, যাতায়াত 25, সঞ্চয় 15 টাকা) খাবার আর যাতায়াতে একসঙ্গে কত খরচ?", ["85 টাকা", "75 টাকা", "40 টাকা", "100 টাকা"],
        "60 + 25 = 85 টাকা।"),
    mcq("Why should needs come before wants in a budget?", ["Needs keep us safe and healthy", "Wants are always bad", "Needs are cheaper always", "It does not matter"], 0,
        "Pay for food, home and school first; then use what is left for treats or saving.",
        "বাজেটে চাওয়ার আগে প্রয়োজন কেন আসা উচিত?", ["প্রয়োজন আমাদের নিরাপদ আর সুস্থ রাখে", "চাওয়া সবসময় খারাপ", "প্রয়োজন সবসময় সস্তা", "কিছু যায় আসে না"],
        "আগে খাবার, ঘর আর স্কুলের খরচ দাও; তারপর যা বাকি থাকে তা শখ বা সঞ্চয়ে।"),
    mcq("Which is a need for a bridge builder's team?", ["Safety helmets", "Fancy sunglasses", "A video game", "Balloons"], 0,
        "Safety equipment is a must on any building site.",
        "সেতু-নির্মাতার দলের জন্য কোনটা প্রয়োজন?", ["নিরাপত্তা হেলমেট", "শৌখিন রোদচশমা", "ভিডিও গেম", "বেলুন"],
        "যেকোনো নির্মাণস্থলে নিরাপত্তার সরঞ্জাম আবশ্যক।"),
    mcq("You get Rs 30 for your birthday. You save Rs 20 and spend the rest. How much do you spend?", ["Rs 10", "Rs 20", "Rs 50", "Rs 30"], 0,
        "30 - 20 = Rs 10 to spend.",
        "জন্মদিনে 30 টাকা পেলে। 20 টাকা জমিয়ে বাকিটা খরচ করলে। কত খরচ করলে?", ["10 টাকা", "20 টাকা", "50 টাকা", "30 টাকা"],
        "30 - 20 = খরচের জন্য 10 টাকা।"),
    mcq("A shirt was Rs 200 and is now Rs 150 in a sale. How much do you save?", ["Rs 50", "Rs 350", "Rs 150", "Rs 200"], 0,
        "200 - 150 = Rs 50 saved.",
        "একটা জামার দাম ছিল 200 টাকা, সেলে এখন 150 টাকা। কত বাঁচবে?", ["50 টাকা", "350 টাকা", "150 টাকা", "200 টাকা"],
        "200 - 150 = 50 টাকা বাঁচে।"),
    mcq("Is a sale price always a good deal?", ["Only if you really need the item", "Yes, always buy in a sale", "No, sales are illegal", "Only on Mondays"], 0,
        "Buying something you do not need is still spending - even at half price.",
        "সেলের দাম কি সবসময় ভালো সুযোগ?", ["শুধু যদি জিনিসটা সত্যিই দরকার হয়", "হ্যাঁ, সেলে সবসময় কেনো", "না, সেল বেআইনি", "শুধু সোমবারে"],
        "দরকার নেই এমন জিনিস কেনা খরচই - অর্ধেক দামেও।"),
    mcq("You lend your friend Rs 20. Your friend pays back Rs 10. How much is still owed?", ["Rs 10", "Rs 30", "Rs 20", "Rs 0"], 0,
        "20 - 10 = Rs 10 still owed.",
        "তুমি বন্ধুকে 20 টাকা ধার দিলে। বন্ধু 10 টাকা ফেরত দিল। আর কত বাকি?", ["10 টাকা", "30 টাকা", "20 টাকা", "0 টাকা"],
        "20 - 10 = আরও 10 টাকা বাকি।"),
    mcq("What is a 'debt'?", ["Money you owe to someone", "Money in your pocket", "A gift", "A savings jar"], 0,
        "A debt must be paid back - often with interest.",
        "'দেনা' কী?", ["কাউকে যে টাকা দেওয়া বাকি", "পকেটের টাকা", "উপহার", "সঞ্চয়ের বয়াম"],
        "দেনা শোধ করতে হয় - প্রায়ই সুদসহ।"),
    mcq("Why is it good to pay back a loan on time?", ["People and banks trust you to borrow again", "It makes the loan bigger", "Banks give it free", "It does not matter"], 0,
        "Paying on time builds a good record (good credit).",
        "সময়মতো ঋণ শোধ করা ভালো কেন?", ["মানুষ আর ব্যাংক আবার ধার দিতে ভরসা করে", "ঋণ বড় হয়", "ব্যাংক বিনামূল্যে দেয়", "কিছু যায় আসে না"],
        "সময়মতো শোধ করলে ভালো সুনাম (ভালো ক্রেডিট) তৈরি হয়।"),
    mcq("You do 3 chores and earn Rs 15 each. How much did you earn?", ["Rs 45", "Rs 18", "Rs 15", "Rs 30"], 0,
        "3 x 15 = Rs 45.",
        "তুমি 3টি ঘরের কাজ করে প্রতিটিতে 15 টাকা পেলে। মোট কত রোজগার?", ["45 টাকা", "18 টাকা", "15 টাকা", "30 টাকা"],
        "3 x 15 = 45 টাকা।"),
    mcq("What is 'giving' or 'charity'?", ["Sharing money or time to help others", "Hiding money", "Borrowing", "Selling"], 0,
        "Many families set aside a little to help people in need.",
        "'দান' কী?", ["অন্যদের সাহায্যে টাকা বা সময় ভাগ করা", "টাকা লুকানো", "ধার নেওয়া", "বিক্রি করা"],
        "অনেক পরিবার অভাবীদের সাহায্যে একটু আলাদা করে রাখে।"),
    mcq("A child splits Rs 30 into three jars: save, spend, share - equally. How much in each jar?", ["Rs 10", "Rs 3", "Rs 30", "Rs 15"], 0,
        "30 ÷ 3 = Rs 10 each.",
        "এক শিশু 30 টাকা তিনটি বয়ামে সমান ভাগ করল: জমাও, খরচ করো, ভাগ করো। প্রতিটিতে কত?", ["10 টাকা", "3 টাকা", "30 টাকা", "15 টাকা"],
        "30 ÷ 3 = প্রতিটিতে 10 টাকা।"),
    mcq("Which is safer for big amounts: a bank or a box under the bed?", ["A bank", "A box under the bed", "Both are equally safe", "Neither"], 0,
        "Banks protect money from theft and fire and keep records.",
        "বেশি টাকার জন্য কোনটা নিরাপদ: ব্যাংক নাকি খাটের নিচের বাক্স?", ["ব্যাংক", "খাটের নিচের বাক্স", "দুটোই সমান নিরাপদ", "কোনোটাই না"],
        "ব্যাংক টাকাকে চুরি আর আগুন থেকে রক্ষা করে আর হিসাব রাখে।"),
    mcq("What is a bank account?", ["A record of your money kept by a bank", "A bank's building", "A coin", "A type of loan only"], 0,
        "Your account shows how much you have put in and taken out.",
        "ব্যাংক অ্যাকাউন্ট কী?", ["ব্যাংকের রাখা তোমার টাকার হিসাব", "ব্যাংকের ভবন", "একটা পয়সা", "শুধু এক রকম ঋণ"],
        "অ্যাকাউন্ট দেখায় তুমি কত জমা দিয়েছ আর কত তুলেছ।"),
    mcq("Putting money into a bank account is called a...", ["Deposit", "Withdrawal", "Loan", "Toll"], 0,
        "Deposit = put in. Withdrawal = take out.",
        "ব্যাংক অ্যাকাউন্টে টাকা রাখাকে বলে...", ["জমা", "উত্তোলন", "ঋণ", "টোল"],
        "জমা = রাখা। উত্তোলন = তোলা।"),
    mcq("Taking money out of a bank account is called a...", ["Withdrawal", "Deposit", "Saving", "Profit"], 0,
        "You withdraw money when you need cash.",
        "ব্যাংক অ্যাকাউন্ট থেকে টাকা তোলাকে বলে...", ["উত্তোলন", "জমা", "সঞ্চয়", "লাভ"],
        "নগদ দরকার হলে টাকা তোলো।"),
    mcq("You have Rs 200 in the bank. You withdraw Rs 50. What is your balance?", ["Rs 150", "Rs 250", "Rs 50", "Rs 200"], 0,
        "Balance = 200 - 50 = Rs 150.",
        "ব্যাংকে তোমার 200 টাকা। তুমি 50 টাকা তুললে। জমা কত রইল?", ["150 টাকা", "250 টাকা", "50 টাকা", "200 টাকা"],
        "অবশিষ্ট = 200 - 50 = 150 টাকা।"),
    mcq("You have Rs 150 in the bank and deposit Rs 40. What is your balance now?", ["Rs 190", "Rs 110", "Rs 40", "Rs 150"], 0,
        "150 + 40 = Rs 190.",
        "ব্যাংকে তোমার 150 টাকা, তুমি 40 টাকা জমা দিলে। এখন কত?", ["190 টাকা", "110 টাকা", "40 টাকা", "150 টাকা"],
        "150 + 40 = 190 টাকা।"),
    mcq("Why do people keep a little money for emergencies?", ["For surprises like illness or repairs", "To buy sweets", "To throw away", "To show friends"], 0,
        "An emergency fund means a surprise cost does not become a crisis.",
        "মানুষ বিপদের জন্য একটু টাকা রাখে কেন?", ["অসুখ বা মেরামতের মতো আচমকা খরচের জন্য", "মিষ্টি কিনতে", "ফেলে দিতে", "বন্ধুদের দেখাতে"],
        "বিপদের তহবিল থাকলে আচমকা খরচ সংকট হয়ে ওঠে না।"),
    mcq("A bridge needs repairs every year. Why does the owner keep money aside for that?", ["Maintenance is a regular cost of owning a bridge", "Repairs are free", "Bridges never break", "To pay the river"], 0,
        "In MODIS BridgeWorks, upkeep costs 3% of the build cost every year.",
        "একটা সেতুর প্রতি বছর মেরামত লাগে। মালিক এর জন্য টাকা আলাদা রাখেন কেন?", ["রক্ষণাবেক্ষণ সেতুর মালিকানার নিয়মিত খরচ", "মেরামত বিনামূল্যে", "সেতু কখনো ভাঙে না", "নদীকে দিতে"],
        "MODIS BridgeWorks-এ রক্ষণাবেক্ষণে প্রতি বছর নির্মাণ-খরচের 3% লাগে।"),
    mcq("Which gives you more money in a year: saving Rs 10 a week or Rs 30 a month?", ["Rs 10 a week (Rs 520 a year)", "Rs 30 a month (Rs 360 a year)", "They are equal", "Neither"], 0,
        "52 weeks x 10 = Rs 520; 12 months x 30 = Rs 360.",
        "বছরে কোনটায় বেশি টাকা: সপ্তাহে 10 টাকা নাকি মাসে 30 টাকা জমানো?", ["সপ্তাহে 10 টাকা (বছরে 520 টাকা)", "মাসে 30 টাকা (বছরে 360 টাকা)", "দুটো সমান", "কোনোটাই না"],
        "52 সপ্তাহ x 10 = 520 টাকা; 12 মাস x 30 = 360 টাকা।"),
    mcq("What does 'afford' mean?", ["To have enough money to pay for something", "To borrow", "To sell", "To give away"], 0,
        "If you can afford it, you can pay without going short on needs.",
        "'সামর্থ্য থাকা' মানে কী?", ["কোনো কিছুর দাম দেওয়ার মতো যথেষ্ট টাকা থাকা", "ধার নেওয়া", "বিক্রি করা", "দিয়ে দেওয়া"],
        "সামর্থ্য থাকলে প্রয়োজনে টান না ফেলেই দাম দিতে পারো।"),
    mcq("You have Rs 75. A game costs Rs 90. Can you afford it?", ["No, you are Rs 15 short", "Yes, with Rs 15 left", "Yes, exactly", "No, Rs 90 short"], 0,
        "90 - 75 = Rs 15 more needed.",
        "তোমার কাছে 75 টাকা। একটা খেলার দাম 90 টাকা। কিনতে পারবে?", ["না, 15 টাকা কম", "হ্যাঁ, 15 টাকা বাকি থাকবে", "হ্যাঁ, ঠিক ঠিক", "না, 90 টাকা কম"],
        "90 - 75 = আরও 15 টাকা লাগবে।"),
    mcq("Two shops sell the same pencil box: Rs 60 and Rs 72. How much cheaper is the first?", ["Rs 12", "Rs 132", "Rs 60", "Rs 22"], 0,
        "72 - 60 = Rs 12.",
        "দুটো দোকানে একই পেনসিল বাক্স: 60 টাকা আর 72 টাকা। প্রথমটা কত সস্তা?", ["12 টাকা", "132 টাকা", "60 টাকা", "22 টাকা"],
        "72 - 60 = 12 টাকা।"),
    mcq("Why do grown-ups compare prices before big purchases?", ["To get the best value for their money", "To waste time", "Shops ask them to", "No reason"], 0,
        "A little checking can save a lot of money on big items.",
        "বড় কেনাকাটার আগে বড়রা দাম তুলনা করেন কেন?", ["টাকার সেরা মূল্য পেতে", "সময় নষ্ট করতে", "দোকান বলে বলে", "কোনো কারণ নেই"],
        "বড় জিনিসে একটু যাচাই অনেক টাকা বাঁচাতে পারে।"),
    mcq("What is 'value for money'?", ["Getting a good amount of use or quality for the price", "Paying the most possible", "Buying anything cheap", "Never spending"], 0,
        "A slightly dearer pair of shoes that lasts twice as long can be better value.",
        "'টাকার মূল্য পাওয়া' কী?", ["দামের তুলনায় ভালো ব্যবহার বা মান পাওয়া", "যতটা সম্ভব বেশি দাম দেওয়া", "যেকোনো সস্তা জিনিস কেনা", "কখনো খরচ না করা"],
        "একটু দামি জুতো যদি দ্বিগুণ টেকে, তা বেশি মূল্যবান হতে পারে।"),
    mcq("A cheap toy breaks in a day. A Rs 20 dearer toy lasts a year. Which is better value?", ["The one that lasts a year", "The cheap one", "Both the same", "Neither"], 0,
        "Cost per day of use is far lower for the toy that lasts.",
        "একটা সস্তা খেলনা এক দিনেই ভাঙে। 20 টাকা দামি খেলনা এক বছর টেকে। কোনটা বেশি মূল্যবান?", ["যেটা এক বছর টেকে", "সস্তাটা", "দুটো সমান", "কোনোটাই না"],
        "যেটা টেকে তার প্রতি দিনের ব্যবহারের খরচ অনেক কম।"),
    mcq("A bridge built with very cheap, weak material breaks in a storm. What does that teach?", ["Cheapest is not always best - safety matters", "Storms are cheap", "Always spend the most", "Nothing"], 0,
        "Good engineers find the lowest cost that is still safe - not the lowest cost at any risk.",
        "খুব সস্তা, দুর্বল উপাদানের সেতু ঝড়ে ভেঙে গেল। এ থেকে কী শিখি?", ["সবচেয়ে সস্তা সবসময় সেরা নয় - নিরাপত্তা জরুরি", "ঝড় সস্তা", "সবসময় সবচেয়ে বেশি খরচ করো", "কিছুই না"],
        "ভালো প্রকৌশলীরা নিরাপদ থেকেই সবচেয়ে কম খরচ খোঁজেন - যেকোনো ঝুঁকিতে সবচেয়ে কম নয়।"),
    mcq("What does a wage mean?", ["Money paid for work, often by the hour or day", "A gift from a friend", "A bank loan", "A shop price"], 0,
        "Workers earn wages for their time and effort.",
        "মজুরি মানে কী?", ["কাজের জন্য দেওয়া টাকা, প্রায়ই ঘণ্টা বা দিন হিসেবে", "বন্ধুর উপহার", "ব্যাংক ঋণ", "দোকানের দাম"],
        "শ্রমিকরা সময় আর পরিশ্রমের জন্য মজুরি পান।"),
    mcq("A worker earns Rs 300 a day. How much in 5 days?", ["Rs 1500", "Rs 305", "Rs 600", "Rs 1000"], 0,
        "5 x 300 = Rs 1500.",
        "একজন শ্রমিক দিনে 300 টাকা পান। 5 দিনে কত?", ["1500 টাকা", "305 টাকা", "600 টাকা", "1000 টাকা"],
        "5 x 300 = 1500 টাকা।"),
    mcq("Why do people pay taxes?", ["To pay for things everyone shares, like roads, schools and bridges", "To buy toys", "Because it is fun", "To give banks money"], 0,
        "Taxes fund public services. Many bridges are paid for with tax money.",
        "মানুষ কর দেয় কেন?", ["রাস্তা, স্কুল আর সেতুর মতো সবার জিনিসের খরচ মেটাতে", "খেলনা কিনতে", "কারণ মজার", "ব্যাংককে টাকা দিতে"],
        "কর থেকে জনসেবার খরচ আসে। অনেক সেতু কর-এর টাকায় তৈরি।"),
    mcq("You buy 2 pens at Rs 15 and 1 notebook at Rs 20. What is the total?", ["Rs 50", "Rs 35", "Rs 45", "Rs 30"], 0,
        "2 x 15 = 30, plus 20 = Rs 50.",
        "15 টাকা করে 2টি কলম আর 20 টাকার 1টি খাতা কিনলে। মোট কত?", ["50 টাকা", "35 টাকা", "45 টাকা", "30 টাকা"],
        "2 x 15 = 30, সঙ্গে 20 = 50 টাকা।"),
    mcq("You pay Rs 100 for things costing Rs 50. What is your change?", ["Rs 50", "Rs 150", "Rs 100", "Rs 0"], 0,
        "100 - 50 = Rs 50.",
        "50 টাকার জিনিসের জন্য 100 টাকা দিলে। কত ফেরত পাবে?", ["50 টাকা", "150 টাকা", "100 টাকা", "0 টাকা"],
        "100 - 50 = 50 টাকা।"),
    mcq("What does it mean to 'invest' money?", ["Use money now to earn more later", "Hide money under a bed", "Throw money away", "Borrow money for sweets"], 0,
        "Building a toll bridge is an investment: you spend first, then tolls pay you back over years.",
        "টাকা 'বিনিয়োগ' করা মানে কী?", ["পরে বেশি পেতে এখন টাকা ব্যবহার করা", "খাটের নিচে টাকা লুকানো", "টাকা ফেলে দেওয়া", "মিষ্টির জন্য ধার করা"],
        "টোল সেতু বানানো একটা বিনিয়োগ: আগে খরচ, তারপর বছরের পর বছর টোলে টাকা ফেরত।"),
    mcq("A toll bridge costs Rs 1,000 to build and earns Rs 100 a year. How many years to earn back the cost (ignoring upkeep)?", ["10 years", "1 year", "100 years", "5 years"], 0,
        "1000 ÷ 100 = 10 years. This is called the payback time.",
        "একটা টোল সেতু বানাতে 1,000 টাকা লাগে আর বছরে 100 টাকা আয় হয়। খরচ ফেরত আসতে কত বছর (রক্ষণাবেক্ষণ বাদে)?", ["10 বছর", "1 বছর", "100 বছর", "5 বছর"],
        "1000 ÷ 100 = 10 বছর। একে বলে খরচ ফেরতের সময়।"),
    mcq("If the same bridge earns Rs 200 a year, how many years to pay back Rs 1,000?", ["5 years", "10 years", "2 years", "20 years"], 0,
        "1000 ÷ 200 = 5 years. More income means faster payback.",
        "একই সেতু বছরে 200 টাকা আয় করলে 1,000 টাকা ফেরত আসতে কত বছর?", ["5 বছর", "10 বছর", "2 বছর", "20 বছর"],
        "1000 ÷ 200 = 5 বছর। বেশি আয় মানে দ্রুত খরচ ফেরত।"),
    mcq("Which is a smart money habit?", ["Saving a part of every income", "Spending everything at once", "Never checking prices", "Borrowing for every treat"], 0,
        "Saving a fixed part each time builds savings without much effort.",
        "কোনটা টাকার ব্যাপারে বুদ্ধিমান অভ্যাস?", ["প্রতিটি আয়ের একটা অংশ জমানো", "সব একসঙ্গে খরচ করা", "কখনো দাম না দেখা", "প্রতিটি শখে ধার করা"],
        "প্রতিবার নির্দিষ্ট অংশ জমালে খুব কষ্ট ছাড়াই সঞ্চয় হয়।"),
    mcq("You found Rs 10 on the school floor. What is the honest thing to do?", ["Give it to the teacher to find the owner", "Keep it secretly", "Spend it quickly", "Hide it in your shoe"], 0,
        "Returning lost money is honest - one day it may be yours that is lost.",
        "স্কুলের মেঝেতে 10 টাকা পেলে। সৎ কাজ কোনটা?", ["মালিক খুঁজতে শিক্ষককে দেওয়া", "লুকিয়ে রেখে দেওয়া", "তাড়াতাড়ি খরচ করা", "জুতোয় লুকানো"],
        "হারানো টাকা ফেরত দেওয়া সততা - একদিন তোমার টাকাও হারাতে পারে।"),
    mcq("A piggy bank has 5 coins of Rs 10 and 4 coins of Rs 5. How much in total?", ["Rs 70", "Rs 50", "Rs 20", "Rs 90"], 0,
        "5 x 10 = 50 and 4 x 5 = 20; 50 + 20 = Rs 70.",
        "একটা ভাঁড়ে 10 টাকার 5টি আর 5 টাকার 4টি পয়সা। মোট কত?", ["70 টাকা", "50 টাকা", "20 টাকা", "90 টাকা"],
        "5 x 10 = 50 আর 4 x 5 = 20; 50 + 20 = 70 টাকা।"),
    mcq("You want to buy something that costs Rs 500 but you earn Rs 50 a week. What is a sensible plan?", ["Save for 10 weeks", "Borrow Rs 500 at high interest today", "Give up forever", "Ask a stranger"], 0,
        "500 ÷ 50 = 10 weeks of saving - no interest to pay!",
        "500 টাকার একটা জিনিস কিনতে চাও, কিন্তু সপ্তাহে রোজগার 50 টাকা। বুদ্ধিমান পরিকল্পনা কোনটা?", ["10 সপ্তাহ জমাও", "আজই চড়া সুদে 500 টাকা ধার করো", "চিরতরে হাল ছাড়ো", "অচেনা কাউকে বলো"],
        "500 ÷ 50 = 10 সপ্তাহ জমানো - কোনো সুদ দিতে হবে না!"),
    mcq("Why can borrowing to build a bridge still be a good idea?", ["Tolls can pay back the loan and leave a profit", "Loans are free", "Bridges print money", "It is never a good idea"], 0,
        "If the bridge earns more than the loan costs, borrowing lets you build sooner.",
        "সেতু বানাতে ধার করাও কেন ভালো হতে পারে?", ["টোল ঋণ শোধ করে লাভও রাখতে পারে", "ঋণ বিনামূল্যে", "সেতু টাকা ছাপে", "কখনোই ভালো নয়"],
        "সেতু যদি ঋণের খরচের চেয়ে বেশি আয় করে, ধার নিলে তাড়াতাড়ি বানানো যায়।"),
    mcq("Which is NOT a way to save money?", ["Buying things you will never use", "Switching off lights", "Mending clothes", "Comparing prices"], 0,
        "Buying unused things wastes money. The others all save money.",
        "কোনটা টাকা বাঁচানোর উপায় নয়?", ["কখনো ব্যবহার হবে না এমন জিনিস কেনা", "বাতি নিভিয়ে রাখা", "জামা সেলাই করে নেওয়া", "দাম তুলনা করা"],
        "অব্যবহৃত জিনিস কিনলে টাকা নষ্ট হয়। বাকিগুলো সবই টাকা বাঁচায়।"),
    mcq("Why does switching off lights save money?", ["The family pays less for electricity", "Lights get angry", "Bulbs grow", "It does not"], 0,
        "Electricity costs money; using less makes the bill smaller.",
        "বাতি নিভিয়ে রাখলে টাকা বাঁচে কেন?", ["পরিবারের বিদ্যুতের বিল কম হয়", "বাতি রেগে যায়", "বাল্ব বড় হয়", "বাঁচে না"],
        "বিদ্যুতের দাম আছে; কম ব্যবহার করলে বিল কমে।"),
    mcq("What is a bill?", ["A note showing how much you must pay for a service", "A bird's beak only", "A coin", "A savings box"], 0,
        "Electricity, water and phone companies send bills for what you used.",
        "বিল কী?", ["কোনো পরিষেবার জন্য কত দিতে হবে তা লেখা কাগজ", "শুধু পাখির ঠোঁট", "একটা পয়সা", "সঞ্চয়ের বাক্স"],
        "বিদ্যুৎ, জল আর ফোন কোম্পানি যা ব্যবহার করেছ তার বিল পাঠায়।"),
    mcq("A water bill is Rs 120 a month. How much for 3 months?", ["Rs 360", "Rs 123", "Rs 240", "Rs 40"], 0,
        "3 x 120 = Rs 360.",
        "জলের বিল মাসে 120 টাকা। 3 মাসে কত?", ["360 টাকা", "123 টাকা", "240 টাকা", "40 টাকা"],
        "3 x 120 = 360 টাকা।"),
    mcq("Why might a family save for a long time to buy a house?", ["Houses cost much more than one month's income", "Houses are cheap", "Banks forbid buying", "It is quick"], 0,
        "Big purchases need long-term saving - or a loan paid back over many years.",
        "একটা পরিবার বাড়ি কিনতে অনেকদিন জমায় কেন?", ["বাড়ির দাম এক মাসের আয়ের চেয়ে অনেক বেশি", "বাড়ি সস্তা", "ব্যাংক কিনতে দেয় না", "এটা তাড়াতাড়ি হয়"],
        "বড় কেনাকাটায় দীর্ঘ সঞ্চয় লাগে - বা বহু বছরে শোধ হওয়া ঋণ।"),
    mcq("What is 'spending wisely'?", ["Buying what you need at a good price", "Buying everything you see", "Never buying anything", "Spending only borrowed money"], 0,
        "Wise spending balances needs, wants and saving.",
        "'বুঝে খরচ করা' কী?", ["ভালো দামে দরকারি জিনিস কেনা", "যা দেখো সব কেনা", "কখনো কিছু না কেনা", "শুধু ধারের টাকা খরচ করা"],
        "বুঝে খরচ প্রয়োজন, চাওয়া আর সঞ্চয়ের মধ্যে ভারসাম্য রাখে।"),
    mcq("You save Rs 25 every week. How much after 4 weeks?", ["Rs 100", "Rs 29", "Rs 75", "Rs 125"], 0,
        "4 x 25 = Rs 100.",
        "তুমি প্রতি সপ্তাহে 25 টাকা জমাও। 4 সপ্তাহ পরে কত?", ["100 টাকা", "29 টাকা", "75 টাকা", "125 টাকা"],
        "4 x 25 = 100 টাকা।"),
    mcq("A shop offers 'pay later'. What should you remember?", ["You still have to pay, sometimes with extra", "It is free", "You never pay", "The shop pays you"], 0,
        "Buy-now-pay-later is borrowing. Make sure you can pay on time.",
        "একটা দোকান 'পরে দাম দাও' সুবিধা দেয়। কী মনে রাখবে?", ["দাম দিতেই হবে, কখনো বাড়তিসহ", "এটা বিনামূল্যে", "কখনো দিতে হবে না", "দোকান তোমাকে দেয়"],
        "এখন কিনে পরে দাম দেওয়াও ধার। সময়মতো দিতে পারবে কিনা নিশ্চিত হও।"),
    mcq("What is a 'loan'?", ["Money borrowed that must be paid back", "A gift", "Your income", "A sale"], 0,
        "Loans help you buy now, but you pay back later, usually with interest.",
        "'ঋণ' কী?", ["ধার নেওয়া টাকা, যা ফেরত দিতে হয়", "একটা উপহার", "তোমার আয়", "একটা সেল"],
        "ঋণে এখন কেনা যায়, কিন্তু পরে ফেরত দিতে হয়, সাধারণত সুদসহ।"),
    mcq("Who usually gives loans to build big bridges?", ["Banks and governments", "Children", "Shopkeepers only", "Birds"], 0,
        "Banks and governments lend large amounts for big projects and get paid back over years.",
        "বড় সেতু বানাতে সাধারণত কে ঋণ দেয়?", ["ব্যাংক আর সরকার", "শিশুরা", "শুধু দোকানদার", "পাখিরা"],
        "ব্যাংক আর সরকার বড় প্রকল্পে অনেক টাকা ধার দেয় আর বহু বছরে ফেরত পায়।"),
    mcq("Your income is Rs 80. You decide to save one quarter. How much do you save?", ["Rs 20", "Rs 40", "Rs 8", "Rs 60"], 0,
        "A quarter of 80 is 80 ÷ 4 = Rs 20.",
        "তোমার আয় 80 টাকা। এক-চতুর্থাংশ জমানোর ঠিক করলে। কত জমাবে?", ["20 টাকা", "40 টাকা", "8 টাকা", "60 টাকা"],
        "80-এর এক-চতুর্থাংশ = 80 ÷ 4 = 20 টাকা।"),
    mcq("Which costs more in a month: Rs 5 snacks every day or a Rs 100 book once?", ["Rs 5 every day (about Rs 150)", "The Rs 100 book", "They are equal", "Neither costs anything"], 0,
        "30 days x Rs 5 = Rs 150 - small daily costs add up!",
        "এক মাসে কোনটার খরচ বেশি: রোজ 5 টাকার জলখাবার নাকি একবার 100 টাকার বই?", ["রোজ 5 টাকা (প্রায় 150 টাকা)", "100 টাকার বই", "দুটো সমান", "কোনোটারই খরচ নেই"],
        "30 দিন x 5 টাকা = 150 টাকা - রোজকার ছোট খরচ জমে বড় হয়!"),
    mcq("What does a piggy bank teach?", ["Patience - small coins grow into a big amount", "How to cook", "How to run", "How to sing"], 0,
        "Watching savings grow coin by coin teaches patience and planning.",
        "মাটির ভাঁড় কী শেখায়?", ["ধৈর্য - ছোট পয়সা জমে বড় অঙ্ক হয়", "রান্না করা", "দৌড়ানো", "গান গাওয়া"],
        "পয়সায় পয়সায় সঞ্চয় বাড়তে দেখা ধৈর্য আর পরিকল্পনা শেখায়।"),
    mcq("A bridge builder has Rs 1,000 and needs Rs 1,200. What is the shortfall?", ["Rs 200", "Rs 2,200", "Rs 1,000", "Rs 1,200"], 0,
        "Shortfall = needed - have = 1200 - 1000 = Rs 200. That gap is what a loan or a grant must cover.",
        "একজন সেতু-নির্মাতার কাছে 1,000 টাকা, লাগবে 1,200 টাকা। ঘাটতি কত?", ["200 টাকা", "2,200 টাকা", "1,000 টাকা", "1,200 টাকা"],
        "ঘাটতি = দরকার - আছে = 1200 - 1000 = 200 টাকা। এই ফাঁকটাই ঋণ বা অনুদানে মেটাতে হয়।"),
    mcq("What is a 'grant'?", ["Money given for a purpose that you do not pay back", "A loan with interest", "A fine", "A price tag"], 0,
        "Grants help pay for useful things - like the Civil Grants you earn in the BridgeWorks Academy!",
        "'অনুদান' কী?", ["কোনো উদ্দেশ্যে দেওয়া টাকা, যা ফেরত দিতে হয় না", "সুদসহ ঋণ", "জরিমানা", "দামের ট্যাগ"],
        "অনুদান দরকারি কাজের খরচ মেটাতে সাহায্য করে - যেমন ব্রিজওয়ার্কস একাডেমিতে অর্জিত সিভিল অনুদান!"),
    mcq("Which is better for building a bridge: a grant or a loan of the same size?", ["A grant - it does not need paying back", "A loan - interest is fun", "They are the same", "Neither helps"], 0,
        "A grant is free money for the project; a loan must be repaid with interest.",
        "সেতু বানাতে একই অঙ্কের অনুদান নাকি ঋণ - কোনটা ভালো?", ["অনুদান - ফেরত দিতে হয় না", "ঋণ - সুদ মজার", "দুটো একই", "কোনোটাই সাহায্য করে না"],
        "অনুদান প্রকল্পের জন্য বিনামূল্যের টাকা; ঋণ সুদসহ শোধ করতে হয়।"),
    mcq("A cake costs Rs 120 to bake and the family saves Rs 30 by baking it at home instead of buying. What did a bought cake cost?", ["Rs 150", "Rs 90", "Rs 120", "Rs 30"], 0,
        "Bought price = home cost + saving = 120 + 30 = Rs 150.",
        "বাড়িতে কেক বানাতে 120 টাকা লাগে, আর কেনার বদলে বানিয়ে পরিবার 30 টাকা বাঁচায়। কেনা কেকের দাম কত ছিল?", ["150 টাকা", "90 টাকা", "120 টাকা", "30 টাকা"],
        "কেনা দাম = বাড়ির খরচ + সঞ্চয় = 120 + 30 = 150 টাকা।"),
    mcq("What is 'pocket money' best used for?", ["Learning to plan, save and spend", "Throwing away", "Hiding forever", "Paying rent"], 0,
        "Pocket money is practice for managing money as a grown-up.",
        "'হাতখরচ' কীসে সবচেয়ে ভালো কাজে লাগে?", ["পরিকল্পনা, সঞ্চয় আর খরচ শেখায়", "ফেলে দেওয়ায়", "চিরকাল লুকিয়ে রাখায়", "বাড়িভাড়া দেওয়ায়"],
        "হাতখরচ বড় হয়ে টাকা সামলানোর অনুশীলন।"),
    mcq("A bus pass costs Rs 300 a month. Single tickets cost Rs 20 each. You take 20 trips a month. Which is cheaper?", ["The bus pass", "Single tickets", "Both cost the same", "Walking costs more"], 0,
        "20 x 20 = Rs 400 for tickets, more than the Rs 300 pass.",
        "বাস পাস মাসে 300 টাকা। একক টিকিট প্রতিটি 20 টাকা। তুমি মাসে 20 বার যাতায়াত করো। কোনটা সস্তা?", ["বাস পাস", "একক টিকিট", "দুটোর খরচ সমান", "হাঁটায় বেশি খরচ"],
        "টিকিটে 20 x 20 = 400 টাকা, যা 300 টাকার পাসের চেয়ে বেশি।"),
    mcq("If you take only 10 trips a month, which is cheaper: the Rs 300 pass or Rs 20 tickets?", ["Tickets (Rs 200)", "The pass", "Both the same", "Neither"], 0,
        "10 x 20 = Rs 200, less than the Rs 300 pass. The best choice depends on how much you use it!",
        "মাসে মাত্র 10 বার যাতায়াত করলে কোনটা সস্তা: 300 টাকার পাস নাকি 20 টাকার টিকিট?", ["টিকিট (200 টাকা)", "পাস", "দুটো সমান", "কোনোটাই না"],
        "10 x 20 = 200 টাকা, 300 টাকার পাসের চেয়ে কম। কতটা ব্যবহার করো তার উপর সেরা বাছাই নির্ভর করে!"),
    mcq("A country builds a bridge using public money. Who benefits?", ["Everyone who uses it and the businesses it connects", "Only the builder", "Nobody", "Only fish"], 0,
        "Public bridges help travel, trade and jobs for whole communities.",
        "একটা দেশ জনগণের টাকায় সেতু বানাল। কারা উপকৃত হয়?", ["যারা ব্যবহার করে আর যে ব্যবসাগুলো জুড়ে যায়, সবাই", "শুধু নির্মাতা", "কেউ না", "শুধু মাছ"],
        "সরকারি সেতু পুরো সমাজের যাতায়াত, বাণিজ্য আর কাজে সাহায্য করে।"),
    mcq("Which coin set makes Rs 50 with the fewest coins?", ["Two Rs 20 and one Rs 10", "Fifty Rs 1", "Ten Rs 5", "Twenty-five Rs 2"], 0,
        "20 + 20 + 10 = 50 with just 3 coins.",
        "সবচেয়ে কম পয়সায় 50 টাকা কোন সেটে হয়?", ["20 টাকার দুটি আর 10 টাকার একটি", "1 টাকার পঞ্চাশটি", "5 টাকার দশটি", "2 টাকার পঁচিশটি"],
        "20 + 20 + 10 = মাত্র 3টি পয়সায় 50।"),
    mcq("What is a 'shopping budget' for a picnic?", ["The most you plan to spend on the picnic", "A list of games", "A map", "A cake"], 0,
        "Setting a budget first helps you pick food and drinks that fit.",
        "পিকনিকের 'কেনাকাটার বাজেট' কী?", ["পিকনিকে সর্বোচ্চ যত খরচের পরিকল্পনা", "খেলার তালিকা", "একটা মানচিত্র", "একটা কেক"],
        "আগে বাজেট ঠিক করলে তার মধ্যে খাবার আর পানীয় বাছা যায়।"),
    mcq("A picnic budget is Rs 200. Food costs Rs 140. How much is left for drinks?", ["Rs 60", "Rs 340", "Rs 140", "Rs 80"], 0,
        "200 - 140 = Rs 60.",
        "পিকনিকের বাজেট 200 টাকা। খাবারে 140 টাকা। পানীয়ের জন্য কত বাকি?", ["60 টাকা", "340 টাকা", "140 টাকা", "80 টাকা"],
        "200 - 140 = 60 টাকা।"),
    mcq("Why do people say 'a penny saved is a penny earned'?", ["Not spending money is like earning it", "Pennies are heavy", "Saving is useless", "Banks say so"], 0,
        "Every rupee you do not waste stays yours - just like a rupee you earn.",
        "মানুষ কেন বলে 'একটা পয়সা বাঁচানো মানে একটা পয়সা রোজগার'?", ["খরচ না করা টাকা রোজগারের মতোই", "পয়সা ভারী", "সঞ্চয় অকেজো", "ব্যাংক বলে"],
        "যে টাকা নষ্ট করো না তা তোমারই থাকে - রোজগারের টাকার মতো।"),
    mcq("Your goal is Rs 150 and you have Rs 90. What fraction of the goal have you saved?", ["3/5", "1/2", "2/3", "1/5"], 0,
        "90 out of 150 = 3/5 (because 90 ÷ 30 = 3 and 150 ÷ 30 = 5).",
        "তোমার লক্ষ্য 150 টাকা আর আছে 90 টাকা। লক্ষ্যের কত ভগ্নাংশ জমেছে?", ["3/5", "1/2", "2/3", "1/5"],
        "150-এর মধ্যে 90 = 3/5 (কারণ 90 ÷ 30 = 3 আর 150 ÷ 30 = 5)।"),
    mcq("Which helps you avoid losing money to tricks?", ["Never sharing PINs or passwords", "Telling everyone your PIN", "Writing your PIN on your card", "Clicking every prize message"], 0,
        "Keep PINs secret. Real banks never ask for them by phone or message.",
        "প্রতারণায় টাকা হারানো এড়াতে কী সাহায্য করে?", ["কখনো পিন বা পাসওয়ার্ড কাউকে না বলা", "সবাইকে পিন বলা", "কার্ডে পিন লিখে রাখা", "পুরস্কারের প্রতিটি বার্তায় ক্লিক করা"],
        "পিন গোপন রাখো। আসল ব্যাংক কখনো ফোন বা বার্তায় পিন চায় না।"),
    mcq("A shop says 'Win Rs 1,00,000! Just send Rs 500 first.' What is this probably?", ["A scam (a trick)", "A real prize", "A bank loan", "A government grant"], 0,
        "Real prizes never ask you to pay first. If it sounds too good to be true, it probably is.",
        "একটা বার্তায় লেখা 'জিতুন 1,00,000 টাকা! শুধু আগে 500 টাকা পাঠান।' এটা সম্ভবত কী?", ["প্রতারণা (একটা ফাঁদ)", "আসল পুরস্কার", "ব্যাংক ঋণ", "সরকারি অনুদান"],
        "আসল পুরস্কার কখনো আগে টাকা চায় না। বিশ্বাস করা কঠিন রকম ভালো শোনালে সম্ভবত ফাঁদ।"),
    mcq("What is the difference between price and cost?", ["Price is what a seller asks; cost is what it took to make or what you pay", "They are colours", "Price is always zero", "No difference ever"], 0,
        "A baker's cost might be Rs 20 per cake; the price she sells it for might be Rs 30.",
        "দাম আর খরচের পার্থক্য কী?", ["দাম হলো বিক্রেতা যা চান; খরচ হলো বানাতে যা লেগেছে বা তুমি যা দাও", "এগুলো রং", "দাম সবসময় শূন্য", "কোনো পার্থক্যই নেই"],
        "একজন রুটিওয়ালির প্রতি কেকে খরচ হয়তো 20 টাকা; তিনি বিক্রি করেন হয়তো 30 টাকায়।"),
    mcq("A road toll is Rs 25 each way. How much for a return trip?", ["Rs 50", "Rs 25", "Rs 75", "Rs 0"], 0,
        "There and back: 2 x 25 = Rs 50.",
        "একটা রাস্তার টোল প্রতি দিকে 25 টাকা। যাওয়া-আসায় কত?", ["50 টাকা", "25 টাকা", "75 টাকা", "0 টাকা"],
        "যাওয়া আর আসা: 2 x 25 = 50 টাকা।"),
    mcq("Why do businesses keep records of money in and out?", ["To know if they are making a profit", "For decoration", "To confuse customers", "It is not needed"], 0,
        "Records show income, costs and profit - and help plan ahead.",
        "ব্যবসা আয়-ব্যয়ের হিসাব রাখে কেন?", ["লাভ হচ্ছে কিনা জানতে", "সাজসজ্জার জন্য", "খদ্দেরকে বিভ্রান্ত করতে", "দরকার নেই"],
        "হিসাব আয়, খরচ আর লাভ দেখায় - আর সামনের পরিকল্পনায় সাহায্য করে।"),
    mcq("A worker earns Rs 2,000 a week. She saves Rs 500. What fraction does she save?", ["One quarter", "One half", "One third", "All of it"], 0,
        "500 is a quarter of 2000 (2000 ÷ 4 = 500).",
        "একজন শ্রমিক সপ্তাহে 2,000 টাকা আয় করে 500 টাকা জমান। কত ভগ্নাংশ জমান?", ["এক-চতুর্থাংশ", "অর্ধেক", "এক-তৃতীয়াংশ", "পুরোটা"],
        "500 হলো 2000-এর এক-চতুর্থাংশ (2000 ÷ 4 = 500)।"),
)
