"""Class 2 - Biology: habitats, food chains, life cycles, the human body and healthy living."""
from . import mcq

ITEMS = (
    mcq("What is a habitat?", ["The natural home of a plant or animal", "A kind of hat", "A school bag", "A type of food"], 0,
        "A habitat gives a living thing food, water and shelter - like a pond for a frog.",
        "আবাসস্থল কী?", ["গাছ বা প্রাণীর প্রাকৃতিক বাসস্থান", "এক রকম টুপি", "স্কুলব্যাগ", "এক রকম খাবার"],
        "আবাসস্থল জীবকে খাবার, জল আর আশ্রয় দেয় - যেমন ব্যাঙের জন্য পুকুর।"),
    mcq("Which habitat is very dry with little rain?", ["Desert", "Rainforest", "Pond", "Ocean"], 0,
        "Deserts get very little rain. Cacti and camels are well suited to them.",
        "কোন আবাসস্থল খুব শুকনো, বৃষ্টি খুব কম?", ["মরুভূমি", "বৃষ্টি-অরণ্য", "পুকুর", "মহাসাগর"],
        "মরুভূমিতে খুব কম বৃষ্টি হয়। ক্যাকটাস আর উট সেখানে মানিয়ে নেয়।"),
    mcq("Why does a cactus have thick stems?", ["To store water", "To scare birds", "To look green", "To float"], 0,
        "Thick fleshy stems hold water for the long dry months.",
        "ক্যাকটাসের কাণ্ড মোটা কেন?", ["জল জমিয়ে রাখতে", "পাখি তাড়াতে", "সবুজ দেখাতে", "ভাসতে"],
        "মোটা রসালো কাণ্ড লম্বা শুকনো মাসগুলোর জন্য জল ধরে রাখে।"),
    mcq("Why does a cactus have spines instead of big leaves?", ["To lose less water and keep animals away", "To catch fish", "To make shade", "For decoration"], 0,
        "Spines lose much less water than wide leaves and protect the plant from thirsty animals.",
        "ক্যাকটাসের বড় পাতার বদলে কাঁটা কেন?", ["কম জল হারাতে আর প্রাণী দূরে রাখতে", "মাছ ধরতে", "ছায়া দিতে", "সাজসজ্জার জন্য"],
        "চওড়া পাতার চেয়ে কাঁটায় অনেক কম জল হারায়, আর তৃষ্ণার্ত প্রাণী থেকে গাছ বাঁচে।"),
    mcq("What is a food chain?", ["Who eats whom, starting from plants", "A chain made of food for decoration", "A line at a shop", "A kind of necklace"], 0,
        "Example: grass -> grasshopper -> frog -> snake. Energy passes along the chain.",
        "খাদ্যশৃঙ্খল কী?", ["কে কাকে খায়, গাছ থেকে শুরু করে", "সাজানোর জন্য খাবারের শিকল", "দোকানের লাইন", "এক রকম হার"],
        "উদাহরণ: ঘাস -> ফড়িং -> ব্যাঙ -> সাপ। শক্তি শৃঙ্খল ধরে এগোয়।"),
    mcq("Food chains almost always start with...", ["A green plant", "A lion", "A rock", "A human"], 0,
        "Plants make their own food from sunlight, so they are the producers at the start of a chain.",
        "খাদ্যশৃঙ্খল প্রায় সবসময় শুরু হয়...", ["সবুজ গাছ দিয়ে", "সিংহ দিয়ে", "পাথর দিয়ে", "মানুষ দিয়ে"],
        "গাছ সূর্যালোক থেকে নিজের খাবার বানায়, তাই শৃঙ্খলের শুরুতে উৎপাদক।"),
    mcq("In grass -> rabbit -> fox, what does the rabbit eat?", ["Grass", "Fox", "Nothing", "Rocks"], 0,
        "The arrow means 'is eaten by': grass is eaten by the rabbit, the rabbit by the fox.",
        "ঘাস -> খরগোশ -> শিয়াল শৃঙ্খলে খরগোশ কী খায়?", ["ঘাস", "শিয়াল", "কিছুই না", "পাথর"],
        "তীর মানে 'যাকে খায়': ঘাস খরগোশ খায়, খরগোশকে শিয়াল।"),
    mcq("An animal that hunts other animals is called a...", ["Predator", "Prey", "Plant", "Producer"], 0,
        "Predators hunt; prey are hunted. An owl is a predator; a mouse is its prey.",
        "যে প্রাণী অন্য প্রাণী শিকার করে তাকে বলে...", ["শিকারি", "শিকার", "উদ্ভিদ", "উৎপাদক"],
        "শিকারি শিকার করে; শিকার হয় শিকারের প্রাণী। পেঁচা শিকারি; ইঁদুর তার শিকার।"),
    mcq("Which is the life cycle of a butterfly?", ["Egg, caterpillar, chrysalis, butterfly", "Butterfly, egg, frog", "Seed, tree, butterfly", "Chick, hen, egg, caterpillar"], 0,
        "This big change in shape is called metamorphosis.",
        "প্রজাপতির জীবনচক্র কোনটা?", ["ডিম, শুঁয়োপোকা, গুটি, প্রজাপতি", "প্রজাপতি, ডিম, ব্যাঙ", "বীজ, গাছ, প্রজাপতি", "ছানা, মুরগি, ডিম, শুঁয়োপোকা"],
        "আকারের এই বড় পরিবর্তনকে বলে রূপান্তর।"),
    mcq("Which is the life cycle of a frog?", ["Egg (spawn), tadpole, froglet, frog", "Seed, frog, tree", "Egg, chick, hen", "Caterpillar, frog"], 0,
        "Frog spawn hatches into tadpoles, which grow legs and become frogs.",
        "ব্যাঙের জীবনচক্র কোনটা?", ["ডিম, ব্যাঙাচি, ছোট ব্যাঙ, ব্যাঙ", "বীজ, ব্যাঙ, গাছ", "ডিম, ছানা, মুরগি", "শুঁয়োপোকা, ব্যাঙ"],
        "ব্যাঙের ডিম ফুটে ব্যাঙাচি হয়, পা গজিয়ে ব্যাঙ হয়।"),
    mcq("What does a seed need to germinate (start growing)?", ["Water, warmth and air", "Darkness only", "Salt", "Loud noise"], 0,
        "Most seeds wake up with water, warmth and air. Light becomes important once leaves grow.",
        "বীজের অঙ্কুরোদ্গমে কী লাগে?", ["জল, উষ্ণতা আর বাতাস", "শুধু অন্ধকার", "নুন", "জোরে আওয়াজ"],
        "বেশিরভাগ বীজ জল, উষ্ণতা আর বাতাসে জেগে ওঠে। পাতা গজালে আলো জরুরি হয়।"),
    mcq("How do some seeds travel far from the parent plant?", ["Wind, water or animals carry them", "They walk", "They drive", "They never move"], 0,
        "Dandelion seeds fly on the wind, coconuts float, and burrs stick to animal fur.",
        "কিছু বীজ মূল গাছ থেকে দূরে যায় কীভাবে?", ["বাতাস, জল বা প্রাণী বয়ে নিয়ে যায়", "হেঁটে যায়", "গাড়ি চালিয়ে যায়", "কখনো নড়ে না"],
        "ড্যান্ডেলিয়নের বীজ বাতাসে ওড়ে, নারকেল ভাসে, আর চোরকাঁটা প্রাণীর লোমে আটকে যায়।"),
    mcq("Why do plants need to spread their seeds far away?", ["So the new plants have space, light and water", "To get rid of them", "Because seeds are heavy", "For no reason"], 0,
        "If all seeds fell under the parent, they would compete for light and water.",
        "গাছকে বীজ দূরে ছড়াতে হয় কেন?", ["যাতে নতুন গাছ জায়গা, আলো আর জল পায়", "ঝামেলা দূর করতে", "কারণ বীজ ভারী", "কোনো কারণ নেই"],
        "সব বীজ মূল গাছের নিচে পড়লে আলো আর জলের জন্য প্রতিযোগিতা হতো।"),
    mcq("What is the stem of a plant for?", ["Holding the plant up and carrying water", "Making seeds", "Catching insects", "Making noise"], 0,
        "The stem is like a pillar with pipes inside, carrying water up from the roots.",
        "গাছের কাণ্ড কীসের জন্য?", ["গাছকে খাড়া রাখতে আর জল বইতে", "বীজ বানাতে", "পোকা ধরতে", "শব্দ করতে"],
        "কাণ্ড যেন ভেতরে পাইপওয়ালা একটা খুঁটি, শিকড় থেকে জল উপরে তোলে।"),
    mcq("Celery left in coloured water turns that colour at the top. What does it show?", ["Water travels up the stem", "Celery likes paint", "Colour falls from the sky", "Leaves make colour"], 0,
        "The coloured water climbs through tiny tubes in the stem to the leaves.",
        "রঙিন জলে রাখা সেলেরির মাথা সেই রঙের হয়ে যায়। এতে কী বোঝা যায়?", ["জল কাণ্ড বেয়ে উপরে ওঠে", "সেলেরি রং পছন্দ করে", "আকাশ থেকে রং পড়ে", "পাতা রং বানায়"],
        "রঙিন জল কাণ্ডের ছোট ছোট নল বেয়ে পাতা পর্যন্ত ওঠে।"),
    mcq("How many bones does an adult human have?", ["206", "26", "2006", "60"], 0,
        "Babies have about 300 bones; many join together as we grow, leaving 206.",
        "একজন প্রাপ্তবয়স্ক মানুষের কয়টি হাড়?", ["206", "26", "2006", "60"],
        "শিশুদের প্রায় 300টি হাড়; বড় হতে হতে অনেকগুলো জুড়ে 206টি থাকে।"),
    mcq("Which is the longest bone in your body?", ["The thigh bone (femur)", "A finger bone", "The skull", "A rib"], 0,
        "The femur runs from hip to knee. Its hollow tube shape makes it strong but light.",
        "শরীরের সবচেয়ে লম্বা হাড় কোনটা?", ["উরুর হাড় (ফিমার)", "আঙুলের হাড়", "খুলি", "পাঁজরের হাড়"],
        "ফিমার কোমর থেকে হাঁটু পর্যন্ত। ফাঁপা নলের আকার একে শক্ত কিন্তু হালকা রাখে।"),
    mcq("What protects your heart and lungs?", ["Your ribcage", "Your skull", "Your kneecap", "Your toes"], 0,
        "The ribs form a strong, springy cage around your chest.",
        "তোমার হৃৎপিণ্ড আর ফুসফুস রক্ষা করে কী?", ["পাঁজর", "খুলি", "হাঁটুর বাটি", "পায়ের আঙুল"],
        "পাঁজরের হাড়গুলো বুকের চারপাশে একটা শক্ত, স্থিতিস্থাপক খাঁচা বানায়।"),
    mcq("Muscles work by...", ["Pulling on bones (they can only pull)", "Pushing bones only", "Melting", "Glowing"], 0,
        "Muscles shorten to pull. To bend and straighten an arm you need two muscles working in pairs - like cables.",
        "পেশি কাজ করে...", ["হাড় টেনে (পেশি শুধু টানতে পারে)", "শুধু হাড় ঠেলে", "গলে", "জ্বলে"],
        "পেশি ছোট হয়ে টানে। হাত ভাঁজ আর সোজা করতে জোড়ায় দুটি পেশি লাগে - তারের মতো।"),
    mcq("Where do your lungs get oxygen from?", ["The air you breathe in", "Food", "Water you drink", "Sunlight on the skin"], 0,
        "Breathing in fills your lungs with air; oxygen passes into your blood.",
        "ফুসফুস অক্সিজেন পায় কোথা থেকে?", ["শ্বাসে নেওয়া বাতাস থেকে", "খাবার থেকে", "খাওয়ার জল থেকে", "ত্বকে রোদ থেকে"],
        "শ্বাস নিলে ফুসফুস বাতাসে ভরে; অক্সিজেন রক্তে চলে যায়।"),
    mcq("What carries oxygen around your body?", ["Blood", "Bones", "Hair", "Skin"], 0,
        "Your heart pumps blood through tubes called blood vessels to every part of you.",
        "শরীরে অক্সিজেন বয়ে বেড়ায় কী?", ["রক্ত", "হাড়", "চুল", "ত্বক"],
        "হৃৎপিণ্ড রক্তনালী নামের নল দিয়ে শরীরের প্রতিটি অংশে রক্ত পাম্প করে।"),
    mcq("Which food group helps you grow and repair your body?", ["Proteins (beans, eggs, fish, lentils)", "Sweets", "Fizzy drinks", "Crisps"], 0,
        "Proteins are the building blocks your body uses for muscles and repairs.",
        "কোন খাদ্যগোষ্ঠী শরীর বাড়াতে আর মেরামত করতে সাহায্য করে?", ["প্রোটিন (শিম, ডিম, মাছ, ডাল)", "মিষ্টি", "ফেনাওয়ালা পানীয়", "চিপস"],
        "প্রোটিন হলো সেই ইট, যা দিয়ে শরীর পেশি বানায় আর মেরামত করে।"),
    mcq("Which food gives you quick energy?", ["Rice, bread and potatoes (carbohydrates)", "Salt only", "Water only", "Vitamins only"], 0,
        "Carbohydrates are your body's main fuel.",
        "কোন খাবার দ্রুত শক্তি দেয়?", ["ভাত, রুটি আর আলু (শর্করা)", "শুধু নুন", "শুধু জল", "শুধু ভিটামিন"],
        "শর্করা শরীরের প্রধান জ্বালানি।"),
    mcq("Why do we need fruit and vegetables?", ["Vitamins and minerals keep us healthy", "They make us sleepy", "They are only for colour", "We do not need them"], 0,
        "Vitamins and minerals help eyes, skin, bones and fighting germs.",
        "ফল আর সবজি কেন দরকার?", ["ভিটামিন আর খনিজ আমাদের সুস্থ রাখে", "ঘুম পাওয়ায়", "শুধু রঙের জন্য", "দরকার নেই"],
        "ভিটামিন আর খনিজ চোখ, ত্বক, হাড় আর জীবাণুর সঙ্গে লড়াইয়ে সাহায্য করে।"),
    mcq("Milk and cheese help build strong...", ["Bones and teeth", "Hair only", "Nails only", "Eyelashes"], 0,
        "They contain calcium, which bones and teeth are made of.",
        "দুধ আর পনির শক্ত করতে সাহায্য করে...", ["হাড় আর দাঁত", "শুধু চুল", "শুধু নখ", "চোখের পাতার লোম"],
        "এতে ক্যালসিয়াম আছে, যা দিয়ে হাড় আর দাঁত তৈরি।"),
    mcq("Why can too many sweets be bad for you?", ["Sugar can cause tooth decay and too much weight", "Sweets make you taller", "Sweets have no taste", "They are always healthy"], 0,
        "A little is fine; lots of sugar harms teeth and health.",
        "বেশি মিষ্টি খারাপ হতে পারে কেন?", ["চিনিতে দাঁত ক্ষয় আর অতিরিক্ত ওজন হতে পারে", "মিষ্টিতে লম্বা হও", "মিষ্টির স্বাদ নেই", "সবসময় স্বাস্থ্যকর"],
        "অল্প ঠিক আছে; বেশি চিনি দাঁত আর স্বাস্থ্যের ক্ষতি করে।"),
    mcq("What are germs?", ["Tiny living things that can make us ill", "Big animals", "A type of fruit", "Shiny stones"], 0,
        "Germs like bacteria and viruses are too small to see. Washing hands stops them spreading.",
        "জীবাণু কী?", ["ছোট্ট জীব, যা আমাদের অসুস্থ করতে পারে", "বড় প্রাণী", "এক রকম ফল", "চকচকে পাথর"],
        "ব্যাকটেরিয়া আর ভাইরাসের মতো জীবাণু দেখার পক্ষে খুব ছোট। হাত ধুলে ছড়ানো থামে।"),
    mcq("What does exercise do for your heart?", ["Makes it stronger", "Makes it smaller", "Stops it", "Nothing"], 0,
        "The heart is a muscle; exercise trains it to pump more blood with each beat.",
        "ব্যায়াম হৃৎপিণ্ডের কী করে?", ["আরও শক্তিশালী করে", "ছোট করে", "থামিয়ে দেয়", "কিছুই না"],
        "হৃৎপিণ্ড একটা পেশি; ব্যায়াম তাকে প্রতিটি স্পন্দনে বেশি রক্ত পাম্প করতে শেখায়।"),
    mcq("Which animal group has feathers?", ["Birds", "Fish", "Mammals", "Insects"], 0,
        "Only birds have feathers. They keep birds warm and help them fly.",
        "কোন প্রাণীগোষ্ঠীর পালক আছে?", ["পাখি", "মাছ", "স্তন্যপায়ী", "পতঙ্গ"],
        "শুধু পাখির পালক থাকে। পালক পাখিকে গরম রাখে আর উড়তে সাহায্য করে।"),
    mcq("Which animal group has hair or fur and feeds its babies milk?", ["Mammals", "Birds", "Reptiles", "Fish"], 0,
        "Dogs, cows, whales and humans are all mammals.",
        "কোন প্রাণীগোষ্ঠীর চুল বা লোম আছে আর বাচ্চাদের দুধ খাওয়ায়?", ["স্তন্যপায়ী", "পাখি", "সরীসৃপ", "মাছ"],
        "কুকুর, গরু, তিমি আর মানুষ সবাই স্তন্যপায়ী।"),
    mcq("A whale lives in the sea. Is it a fish?", ["No - it is a mammal that breathes air", "Yes, a big fish", "It is a bird", "It is a plant"], 0,
        "Whales breathe air through a blowhole and feed their babies milk.",
        "তিমি সমুদ্রে থাকে। এটা কি মাছ?", ["না - এটা বাতাসে শ্বাস নেওয়া স্তন্যপায়ী", "হ্যাঁ, বড় মাছ", "এটা পাখি", "এটা গাছ"],
        "তিমি মাথার ছিদ্র দিয়ে বাতাসে শ্বাস নেয় আর বাচ্চাদের দুধ খাওয়ায়।"),
    mcq("Which animal group lives in water and land and has moist skin?", ["Amphibians (like frogs)", "Birds", "Mammals", "Insects"], 0,
        "Amphibians like frogs and newts start life in water and can later live on land.",
        "কোন প্রাণীগোষ্ঠী জল আর ডাঙা দুটোতেই থাকে আর ত্বক ভেজা?", ["উভচর (যেমন ব্যাঙ)", "পাখি", "স্তন্যপায়ী", "পতঙ্গ"],
        "ব্যাঙ আর নিউটের মতো উভচর জলে জীবন শুরু করে আর পরে ডাঙায় থাকতে পারে।"),
    mcq("Which has a backbone?", ["A dog", "A worm", "A jellyfish", "A snail"], 0,
        "Animals with backbones are vertebrates. Worms, jellyfish and snails have none.",
        "কোনটার মেরুদণ্ড আছে?", ["কুকুর", "কেঁচো", "জেলিফিশ", "শামুক"],
        "মেরুদণ্ডওয়ালা প্রাণী মেরুদণ্ডী। কেঁচো, জেলিফিশ আর শামুকের নেই।"),
    mcq("How do earthworms help the soil?", ["They mix it and let air and water in", "They make it dry", "They eat all the plants", "They harden it"], 0,
        "Worm tunnels let air and water reach roots, and their waste feeds the soil.",
        "কেঁচো মাটিকে কীভাবে সাহায্য করে?", ["মাটি মিশিয়ে বাতাস আর জল ঢুকতে দেয়", "মাটি শুকনো করে", "সব গাছ খেয়ে ফেলে", "মাটি শক্ত করে"],
        "কেঁচোর সুড়ঙ্গে বাতাস আর জল শিকড়ে পৌঁছায়, আর তাদের মল মাটিকে উর্বর করে।"),
    mcq("What do bees do for flowers?", ["Carry pollen so seeds can form", "Eat the petals", "Water them", "Paint them"], 0,
        "Pollination by bees lets plants make fruit and seeds. Many foods depend on bees!",
        "মৌমাছি ফুলের জন্য কী করে?", ["পরাগরেণু বয়ে বীজ তৈরিতে সাহায্য করে", "পাপড়ি খায়", "জল দেয়", "রং করে"],
        "মৌমাছির পরাগায়নে গাছ ফল আর বীজ বানায়। অনেক খাবার মৌমাছির উপর নির্ভর করে!"),
    mcq("Why do some birds fly to warmer places in winter?", ["To find food and warmth", "To see the sea", "To visit friends", "They get bored"], 0,
        "This long journey is called migration.",
        "শীতে কিছু পাখি গরম জায়গায় উড়ে যায় কেন?", ["খাবার আর উষ্ণতা খুঁজতে", "সমুদ্র দেখতে", "বন্ধুদের সঙ্গে দেখা করতে", "একঘেয়ে লাগে"],
        "এই লম্বা যাত্রাকে বলে পরিযান।"),
    mcq("What is camouflage?", ["Colours or patterns that help an animal hide", "A loud call", "A type of nest", "A sharp tooth"], 0,
        "A tiger's stripes blend into tall grass; a stick insect looks like a twig.",
        "ছদ্মবেশ কী?", ["রং বা নকশা, যা প্রাণীকে লুকাতে সাহায্য করে", "জোরালো ডাক", "এক রকম বাসা", "ধারালো দাঁত"],
        "বাঘের ডোরা লম্বা ঘাসে মিশে যায়; কাঠি-পোকা দেখতে ডালের মতো।"),
    mcq("Why does a polar bear have white fur?", ["To blend in with the snow", "To stay cool", "To look clean", "To scare fish"], 0,
        "White fur hides the bear on snow and ice so it can sneak up on seals.",
        "মেরু ভালুকের লোম সাদা কেন?", ["বরফের সঙ্গে মিশে যেতে", "ঠান্ডা থাকতে", "পরিষ্কার দেখাতে", "মাছ ভয় দেখাতে"],
        "সাদা লোম ভালুককে বরফে লুকিয়ে রাখে, তাই সে চুপিচুপি সিলের কাছে যেতে পারে।"),
    mcq("Which plant part do we eat when we eat potatoes?", ["A swollen underground stem (tuber)", "The flower", "The leaf", "The seed pod"], 0,
        "Potatoes are tubers - underground stems that store food for the plant.",
        "আলু খেলে গাছের কোন অংশ খাই?", ["মাটির নিচের ফোলা কাণ্ড (কন্দ)", "ফুল", "পাতা", "বীজের খোসা"],
        "আলু হলো কন্দ - মাটির নিচের কাণ্ড, যা গাছের জন্য খাবার জমায়।"),
    mcq("Which plant part do we eat when we eat spinach?", ["Leaves", "Roots", "Seeds", "Flowers"], 0,
        "Spinach and lettuce are leafy vegetables.",
        "পালং শাক খেলে গাছের কোন অংশ খাই?", ["পাতা", "শিকড়", "বীজ", "ফুল"],
        "পালং শাক আর লেটুস পাতাওয়ালা সবজি।"),
    mcq("What do green leaves need to make food for the plant?", ["Sunlight, water and carbon dioxide", "Salt and sugar", "Darkness", "Soil only"], 0,
        "This process is called photosynthesis. It also gives out oxygen.",
        "গাছের খাবার বানাতে সবুজ পাতার কী লাগে?", ["সূর্যালোক, জল আর কার্বন ডাই-অক্সাইড", "নুন আর চিনি", "অন্ধকার", "শুধু মাটি"],
        "এই প্রক্রিয়ার নাম সালোকসংশ্লেষ। এতে অক্সিজেনও বেরোয়।"),
    mcq("A plant kept in a dark cupboard for a week turns...", ["Pale and weak", "Bright green", "Bigger and stronger", "Blue"], 0,
        "Without light the plant cannot make food or its green colour.",
        "এক সপ্তাহ অন্ধকার আলমারিতে রাখা গাছ হয়ে যায়...", ["ফ্যাকাশে আর দুর্বল", "উজ্জ্বল সবুজ", "বড় আর শক্ত", "নীল"],
        "আলো ছাড়া গাছ খাবার বা সবুজ রং বানাতে পারে না।"),
    mcq("How do fish move through water?", ["By swishing their tails and fins", "By walking", "By flying", "By rolling"], 0,
        "A fish's body is streamlined, and its tail pushes water back to move forward.",
        "মাছ জলে কীভাবে চলে?", ["লেজ আর পাখনা নেড়ে", "হেঁটে", "উড়ে", "গড়িয়ে"],
        "মাছের শরীর মসৃণ লম্বাটে, আর লেজ জল পেছনে ঠেলে সামনে এগোয়।"),
    mcq("Why are fish shaped like a long smooth torpedo?", ["Water flows past them easily", "To look pretty", "To be heavy", "To sink"], 0,
        "A streamlined shape reduces drag. Engineers shape bridge decks and trains the same way.",
        "মাছের আকার লম্বা মসৃণ টর্পেডোর মতো কেন?", ["জল সহজে পাশ দিয়ে বয়ে যায়", "সুন্দর দেখাতে", "ভারী হতে", "ডুবতে"],
        "মসৃণ লম্বাটে আকার বাধা কমায়। প্রকৌশলীরা সেতুর ডেক আর ট্রেনের আকারও এভাবে দেন।"),
    mcq("What does a spider use to make its web?", ["Silk from its own body", "Grass", "String from humans", "Mud"], 0,
        "Spider silk is amazingly strong and stretchy for its weight.",
        "মাকড়সা জাল বোনে কী দিয়ে?", ["নিজের শরীরের রেশম দিয়ে", "ঘাস দিয়ে", "মানুষের সুতো দিয়ে", "কাদা দিয়ে"],
        "মাকড়সার রেশম ওজনের তুলনায় আশ্চর্য রকম শক্ত আর স্থিতিস্থাপক।"),
    mcq("How is a spider's web like a suspension bridge?", ["Strong threads hold weight by pulling (tension)", "Both are made of wood", "Both float", "They are not alike"], 0,
        "Both use thin strands working in tension to carry loads across a gap.",
        "মাকড়সার জাল ঝুলন্ত সেতুর মতো কীভাবে?", ["শক্ত সুতো টেনে (টানে) ভার ধরে", "দুটোই কাঠের", "দুটোই ভাসে", "একরকম নয়"],
        "দুটোই সরু সুতো ব্যবহার করে, যা টানে থেকে ফাঁক পেরিয়ে ভার বয়।"),
    mcq("Which sense organ is the biggest?", ["Skin", "Eyes", "Nose", "Ears"], 0,
        "Your skin covers your whole body and feels touch, heat, cold and pain.",
        "কোন ইন্দ্রিয় সবচেয়ে বড়?", ["ত্বক", "চোখ", "নাক", "কান"],
        "তোমার ত্বক পুরো শরীর ঢেকে রাখে আর স্পর্শ, গরম, ঠান্ডা আর ব্যথা টের পায়।"),
    mcq("Why do we have two eyes, not one?", ["To judge distance better", "One is a spare only", "To see in the dark", "To look funny"], 0,
        "Two eyes see slightly different views, and the brain combines them to judge depth.",
        "আমাদের একটা নয়, দুটো চোখ কেন?", ["দূরত্ব ভালোভাবে বুঝতে", "একটা শুধু বাড়তি", "অন্ধকারে দেখতে", "মজার দেখাতে"],
        "দুই চোখ একটু আলাদা দৃশ্য দেখে, মস্তিষ্ক তা মিলিয়ে গভীরতা বোঝে।"),
    mcq("Which part of your body controls everything you do?", ["The brain", "The stomach", "The knee", "The hair"], 0,
        "Your brain sends messages along nerves to every part of your body.",
        "শরীরের কোন অংশ তোমার সবকিছু নিয়ন্ত্রণ করে?", ["মস্তিষ্ক", "পাকস্থলী", "হাঁটু", "চুল"],
        "মস্তিষ্ক স্নায়ু দিয়ে শরীরের প্রতিটি অংশে বার্তা পাঠায়।"),
    mcq("Where does food go after you swallow it?", ["Down to your stomach", "Into your lungs", "Into your brain", "Into your bones"], 0,
        "Food travels down a tube to the stomach, where it is broken down.",
        "গিলে ফেলার পর খাবার কোথায় যায়?", ["নিচে পাকস্থলীতে", "ফুসফুসে", "মস্তিষ্কে", "হাড়ে"],
        "খাবার একটা নল বেয়ে পাকস্থলীতে যায়, সেখানে ভাঙা হয়।"),
    mcq("Why should we chew food well?", ["To break it into small pieces for digestion", "To make it louder", "To keep it whole", "To make it cold"], 0,
        "Chewing starts digestion and makes food easier to swallow and break down.",
        "খাবার ভালো করে চিবোনো উচিত কেন?", ["হজমের জন্য ছোট টুকরো করতে", "শব্দ করতে", "আস্ত রাখতে", "ঠান্ডা করতে"],
        "চিবোনো হজম শুরু করে আর খাবার গেলা আর ভাঙা সহজ করে।"),
    mcq("What do baby teeth do around age 6?", ["Fall out and adult teeth grow", "Turn into gold", "Grow longer forever", "Nothing"], 0,
        "Milk teeth make way for bigger, permanent teeth.",
        "প্রায় 6 বছর বয়সে দুধদাঁতের কী হয়?", ["পড়ে যায় আর স্থায়ী দাঁত গজায়", "সোনা হয়ে যায়", "চিরকাল লম্বা হয়", "কিছুই না"],
        "দুধদাঁত বড়, স্থায়ী দাঁতের জন্য জায়গা ছেড়ে দেয়।"),
    mcq("Which animal is an insect?", ["Ant", "Spider", "Worm", "Snail"], 0,
        "Insects have 6 legs and 3 body parts. Spiders have 8 legs.",
        "কোন প্রাণী পতঙ্গ?", ["পিঁপড়ে", "মাকড়সা", "কেঁচো", "শামুক"],
        "পতঙ্গের 6টি পা আর 3টি দেহাংশ। মাকড়সার 8টি পা।"),
    mcq("How do ants carry loads much heavier than themselves?", ["They are very strong for their tiny size", "They use wheels", "They are magnetic", "They never carry anything"], 0,
        "Small animals are strong for their size; some ants carry 10 to 50 times their own weight!",
        "পিঁপড়ে নিজের চেয়ে অনেক ভারী বোঝা বয় কীভাবে?", ["ছোট্ট আকারের তুলনায় খুব শক্তিশালী", "চাকা ব্যবহার করে", "চুম্বক", "কখনো কিছু বয় না"],
        "ছোট প্রাণী আকারের তুলনায় শক্তিশালী; কিছু পিঁপড়ে নিজের ওজনের 10 থেকে 50 গুণ বয়!"),
    mcq("How do ants build bridges across gaps?", ["They link their bodies together", "With sticks and glue", "With steel", "They never do"], 0,
        "Army ants grip each other to form living bridges for their colony - teamwork engineering!",
        "পিঁপড়ে ফাঁক পেরোতে সেতু বানায় কীভাবে?", ["নিজেদের শরীর একে অপরের সঙ্গে জুড়ে", "কাঠি আর আঠা দিয়ে", "ইস্পাত দিয়ে", "কখনো বানায় না"],
        "সৈনিক পিঁপড়েরা একে অপরকে আঁকড়ে ধরে দলের জন্য জীবন্ত সেতু বানায় - দলগত প্রকৌশল!"),
    mcq("What do tadpoles breathe with at first?", ["Gills", "Lungs", "Nose only", "Skin only"], 0,
        "Young tadpoles have gills like fish. Later, as frogs, they breathe with lungs and skin.",
        "ব্যাঙাচি প্রথমে কী দিয়ে শ্বাস নেয়?", ["কানকো", "ফুসফুস", "শুধু নাক", "শুধু ত্বক"],
        "ছোট ব্যাঙাচির মাছের মতো কানকো থাকে। পরে ব্যাঙ হয়ে ফুসফুস আর ত্বক দিয়ে শ্বাস নেয়।"),
    mcq("Why do trees in a forest grow tall?", ["To reach the sunlight above other plants", "To touch the clouds for fun", "To scare birds", "Because roots push them"], 0,
        "In a crowded forest, plants compete for light, so many grow tall.",
        "বনের গাছ লম্বা হয় কেন?", ["অন্য গাছের উপরে আলো পেতে", "মজা করে মেঘ ছুঁতে", "পাখি তাড়াতে", "কারণ শিকড় ঠেলে"],
        "ভিড়ের বনে গাছেরা আলোর জন্য প্রতিযোগিতা করে, তাই অনেকেই লম্বা হয়।"),
    mcq("Why do tall trees have wide roots and thick trunks at the bottom?", ["To stay standing in strong winds", "To store toys", "To look heavy", "For birds to sit"], 0,
        "Like a tower, a tree needs a strong wide base so the wind cannot tip it over.",
        "লম্বা গাছের নিচে চওড়া শিকড় আর মোটা গুঁড়ি কেন?", ["জোরালো বাতাসে দাঁড়িয়ে থাকতে", "খেলনা রাখতে", "ভারী দেখাতে", "পাখির বসার জন্য"],
        "টাওয়ারের মতো, গাছেরও শক্ত চওড়া ভিত লাগে, যাতে বাতাস উল্টাতে না পারে।"),
    mcq("What do we call animals that are active at night?", ["Nocturnal", "Diurnal", "Hibernating", "Migrating"], 0,
        "Owls, bats and foxes are nocturnal - they sleep in the day.",
        "যে প্রাণীরা রাতে সক্রিয়, তাদের কী বলে?", ["নিশাচর", "দিবাচর", "শীতঘুমের প্রাণী", "পরিযায়ী"],
        "পেঁচা, বাদুড় আর শিয়াল নিশাচর - দিনে ঘুমায়।"),
    mcq("What happens to your body when you are scared?", ["Your heart beats faster to get ready to run", "You grow taller", "Your hair turns blue", "Nothing"], 0,
        "Fear prepares your body for action - the heart pumps faster to feed your muscles.",
        "ভয় পেলে শরীরের কী হয়?", ["দৌড়ানোর জন্য তৈরি হতে হৃৎপিণ্ড দ্রুত চলে", "লম্বা হয়ে যাও", "চুল নীল হয়", "কিছুই না"],
        "ভয় শরীরকে কাজের জন্য তৈরি করে - পেশিকে খাওয়াতে হৃৎপিণ্ড দ্রুত পাম্প করে।"),
    mcq("Which helps keep your body temperature down when you are hot?", ["Sweating", "Shivering", "Sleeping in a coat", "Eating ice cream only"], 0,
        "Sweat evaporates from your skin and takes heat away with it.",
        "গরম লাগলে শরীরের তাপমাত্রা কমাতে কী সাহায্য করে?", ["ঘাম", "কাঁপুনি", "কোট পরে ঘুমানো", "শুধু আইসক্রিম খাওয়া"],
        "ঘাম ত্বক থেকে বাষ্প হয়ে তাপ সরিয়ে নেয়।"),
    mcq("What is the normal human body temperature?", ["About 37 °C", "About 0 °C", "About 100 °C", "About 10 °C"], 0,
        "A healthy body stays near 37 °C. A higher temperature is a fever.",
        "মানুষের শরীরের স্বাভাবিক তাপমাত্রা কত?", ["প্রায় 37 °C", "প্রায় 0 °C", "প্রায় 100 °C", "প্রায় 10 °C"],
        "সুস্থ শরীর 37 °C-এর কাছাকাছি থাকে। এর বেশি হলে জ্বর।"),
    mcq("Why do we have eyebrows?", ["To stop sweat and rain running into our eyes", "To hear better", "To smell", "For no reason"], 0,
        "Eyebrows guide sweat and water to the sides, away from your eyes.",
        "আমাদের ভুরু থাকে কেন?", ["ঘাম আর বৃষ্টির জল চোখে গড়িয়ে পড়া ঠেকাতে", "ভালো শুনতে", "গন্ধ নিতে", "কোনো কারণ নেই"],
        "ভুরু ঘাম আর জলকে চোখ থেকে দূরে পাশে সরিয়ে দেয়।"),
    mcq("Which helps you balance?", ["Parts inside your ears", "Your eyelashes", "Your fingernails", "Your teeth"], 0,
        "Tiny fluid-filled tubes in your inner ear sense movement and tilt.",
        "ভারসাম্য রাখতে কী সাহায্য করে?", ["কানের ভেতরের অংশ", "চোখের পাতার লোম", "নখ", "দাঁত"],
        "অন্তঃকর্ণের তরলে ভরা ছোট নলগুলো নড়াচড়া আর হেলে পড়া টের পায়।"),
    mcq("Which is a renewable natural material from plants?", ["Bamboo", "Plastic", "Steel", "Glass"], 0,
        "Bamboo regrows quickly and is strong - it is even used for scaffolding and bridges.",
        "উদ্ভিদ থেকে আসা কোন প্রাকৃতিক উপাদান নবায়নযোগ্য?", ["বাঁশ", "প্লাস্টিক", "ইস্পাত", "কাচ"],
        "বাঁশ তাড়াতাড়ি আবার জন্মায় আর শক্ত - ভারা আর সেতুতেও ব্যবহার হয়।"),
    mcq("What do mushrooms belong to?", ["Fungi", "Animals", "Plants that make food from light", "Rocks"], 0,
        "Fungi get food from rotting material; they cannot make food from sunlight.",
        "ব্যাঙের ছাতা কোন গোষ্ঠীর?", ["ছত্রাক", "প্রাণী", "আলো থেকে খাবার বানানো উদ্ভিদ", "পাথর"],
        "ছত্রাক পচা জিনিস থেকে খাবার পায়; সূর্যালোক থেকে খাবার বানাতে পারে না।"),
    mcq("What do decomposers like fungi and worms do?", ["Break down dead things into soil", "Eat only living animals", "Make sunlight", "Build nests"], 0,
        "Decomposers recycle dead leaves and animals back into nutrients for new plants.",
        "ছত্রাক আর কেঁচোর মতো বিয়োজকরা কী করে?", ["মৃত জিনিস ভেঙে মাটিতে মেশায়", "শুধু জীবন্ত প্রাণী খায়", "সূর্যালোক বানায়", "বাসা বানায়"],
        "বিয়োজক ঝরা পাতা আর মৃত প্রাণীকে নতুন গাছের পুষ্টিতে ফিরিয়ে দেয়।"),
    mcq("Why do wooden bridges need protection from some fungi and insects?", ["They can rot or eat the wood and weaken it", "They make wood shiny", "They paint it", "They make it heavier"], 0,
        "Rot fungi and termites can weaken timber, so it is treated and kept dry.",
        "কাঠের সেতুকে কিছু ছত্রাক আর পোকা থেকে রক্ষা করতে হয় কেন?", ["এরা কাঠ পচাতে বা খেয়ে দুর্বল করতে পারে", "কাঠ চকচকে করে", "রং করে", "ভারী করে"],
        "পচন-ছত্রাক আর উইপোকা কাঠ দুর্বল করতে পারে, তাই কাঠ রাসায়নিকে সুরক্ষিত আর শুকনো রাখা হয়।"),
    mcq("Which animal eats wood and can damage wooden buildings?", ["Termite", "Butterfly", "Goldfish", "Penguin"], 0,
        "Termites chew through wood. Builders treat timber to keep them out.",
        "কোন প্রাণী কাঠ খায় আর কাঠের ভবনের ক্ষতি করতে পারে?", ["উইপোকা", "প্রজাপতি", "সোনালি মাছ", "পেঙ্গুইন"],
        "উইপোকা কাঠ চিবিয়ে ফেলে। নির্মাতারা তাদের ঠেকাতে কাঠে রাসায়নিক দেন।"),
    mcq("What do roots do besides holding the plant?", ["Take in water and minerals", "Make flowers", "Catch flies", "Make sounds"], 0,
        "Roots soak up water and minerals from the soil and send them up the stem.",
        "গাছ ধরে রাখা ছাড়া শিকড় আর কী করে?", ["জল আর খনিজ নেয়", "ফুল বানায়", "মাছি ধরে", "শব্দ করে"],
        "শিকড় মাটি থেকে জল আর খনিজ শুষে কাণ্ড দিয়ে উপরে পাঠায়।"),
    mcq("Why do riverbanks with plant roots wash away less in floods?", ["Roots hold the soil together", "Roots push water back", "Plants drink all the river", "They do not"], 0,
        "A mat of roots binds soil like steel bars in concrete - engineers plant banks near bridges for this reason.",
        "শিকড়ওয়ালা নদীর পাড় বন্যায় কম ভাঙে কেন?", ["শিকড় মাটি জুড়ে ধরে রাখে", "শিকড় জল পেছনে ঠেলে", "গাছ পুরো নদী খেয়ে ফেলে", "কম ভাঙে না"],
        "শিকড়ের জাল মাটিকে কংক্রিটের রডের মতো বাঁধে - এজন্যই সেতুর কাছের পাড়ে গাছ লাগানো হয়।"),
    mcq("Which animal sheds its skin as it grows?", ["Snake", "Dog", "Cow", "Hen"], 0,
        "Snakes grow a new skin underneath and wriggle out of the old one.",
        "কোন প্রাণী বড় হতে হতে খোলস ছাড়ে?", ["সাপ", "কুকুর", "গরু", "মুরগি"],
        "সাপের নিচে নতুন চামড়া গজায় আর পুরোনোটা থেকে মোচড় দিয়ে বেরিয়ে আসে।"),
    mcq("Why do people wash cuts and cover them with a plaster?", ["To keep germs out while it heals", "To make it bigger", "To hide it from friends", "To make it itch"], 0,
        "Cleaning removes germs; a covering keeps new ones out while skin repairs itself.",
        "কাটা জায়গা ধুয়ে প্লাস্টার লাগানো হয় কেন?", ["সারার সময় জীবাণু আটকাতে", "বড় করতে", "বন্ধুদের থেকে লুকাতে", "চুলকানি বাড়াতে"],
        "পরিষ্কার করলে জীবাণু সরে; ঢাকা থাকলে ত্বক সারার সময় নতুন জীবাণু ঢোকে না।"),
    mcq("What is a vaccine for?", ["To help your body learn to fight a disease", "To make you sleepy", "To grow taller", "To change your eye colour"], 0,
        "Vaccines train your body's defences so you do not get very ill from certain germs.",
        "টিকা কীসের জন্য?", ["শরীরকে রোগের সঙ্গে লড়তে শেখাতে", "ঘুম পাওয়াতে", "লম্বা হতে", "চোখের রং বদলাতে"],
        "টিকা শরীরের প্রতিরক্ষাকে শেখায়, যাতে কিছু জীবাণুতে খুব অসুস্থ না হও।"),
    mcq("Which animal can live without drinking water for a long time in the desert?", ["Camel", "Frog", "Fish", "Duck"], 0,
        "Camels conserve water so well that they can go days without drinking.",
        "মরুভূমিতে কোন প্রাণী অনেকদিন জল না খেয়ে থাকতে পারে?", ["উট", "ব্যাঙ", "মাছ", "হাঁস"],
        "উট এত ভালোভাবে জল বাঁচায় যে কয়েকদিন না খেয়ে থাকতে পারে।"),
    mcq("Why do elephants flap their big ears?", ["To cool down", "To fly", "To hear the moon", "To clean them"], 0,
        "Big ears full of blood vessels release heat when flapped - a natural air conditioner.",
        "হাতি তার বড় কান নাড়ায় কেন?", ["ঠান্ডা হতে", "উড়তে", "চাঁদের কথা শুনতে", "কান পরিষ্কার করতে"],
        "রক্তনালীতে ভরা বড় কান নাড়ালে তাপ বেরিয়ে যায় - প্রাকৃতিক এসি।"),
    mcq("Which part of a bird's body is like an aeroplane's wing?", ["Its wing", "Its beak", "Its feet", "Its eyes"], 0,
        "Engineers studied bird wings to design aeroplanes - this copying of nature is called biomimicry.",
        "পাখির শরীরের কোন অংশ উড়োজাহাজের ডানার মতো?", ["তার ডানা", "তার ঠোঁট", "তার পা", "তার চোখ"],
        "প্রকৌশলীরা পাখির ডানা দেখে উড়োজাহাজ নকশা করেছেন - প্রকৃতিকে এভাবে নকল করাকে বলে জৈব-অনুকরণ।"),
    mcq("A beaver's dam is built from...", ["Branches, logs and mud", "Steel and concrete", "Plastic bottles", "Ice only"], 0,
        "Beavers are expert builders who block streams to make safe ponds.",
        "বিভারের বাঁধ তৈরি...", ["ডাল, গুঁড়ি আর কাদা দিয়ে", "ইস্পাত আর কংক্রিট দিয়ে", "প্লাস্টিকের বোতল দিয়ে", "শুধু বরফ দিয়ে"],
        "বিভার দক্ষ নির্মাতা, নালা আটকে নিরাপদ পুকুর বানায়।"),
    mcq("What is the main job of a bird's nest?", ["To keep eggs and chicks safe and warm", "To store food for winter", "To catch rain", "To sleep in all year"], 0,
        "Nests protect eggs and chicks from cold and predators.",
        "পাখির বাসার প্রধান কাজ কী?", ["ডিম আর ছানাকে নিরাপদ আর গরম রাখা", "শীতের খাবার জমানো", "বৃষ্টির জল ধরা", "সারা বছর ঘুমানো"],
        "বাসা ডিম আর ছানাকে ঠান্ডা আর শিকারির হাত থেকে বাঁচায়।"),
    mcq("Which of these is a mammal that flies?", ["Bat", "Eagle", "Butterfly", "Bee"], 0,
        "Bats are the only mammals that can truly fly.",
        "এগুলোর কোনটা উড়তে পারা স্তন্যপায়ী?", ["বাদুড়", "ঈগল", "প্রজাপতি", "মৌমাছি"],
        "বাদুড়ই একমাত্র স্তন্যপায়ী, যে সত্যিই উড়তে পারে।"),
    mcq("How do bats find their way in the dark?", ["Echoes of their squeaks", "Torches", "Smelling the stars", "They do not fly at night"], 0,
        "Bats make high squeaks and listen for echoes - called echolocation.",
        "বাদুড় অন্ধকারে পথ খোঁজে কীভাবে?", ["নিজের চিঁ চিঁ শব্দের প্রতিধ্বনি শুনে", "টর্চ দিয়ে", "তারার গন্ধ শুঁকে", "রাতে ওড়েই না"],
        "বাদুড় উঁচু শব্দ করে আর প্রতিধ্বনি শোনে - একে বলে প্রতিধ্বনি-নির্ণয়।"),
    mcq("What helps a giraffe's long neck carry blood all the way up to its head?", ["A very strong, powerful heart", "Its tail", "Its spots", "Gravity pushing up"], 0,
        "A giraffe's heart is huge and pumps at high pressure to reach its brain.",
        "জিরাফের লম্বা গলার উপর পর্যন্ত মাথায় রক্ত পৌঁছাতে কী সাহায্য করে?", ["খুব শক্তিশালী হৃৎপিণ্ড", "তার লেজ", "তার ছোপ", "মাধ্যাকর্ষণ উপরে ঠেলে"],
        "জিরাফের হৃৎপিণ্ড বিশাল আর উচ্চ চাপে পাম্প করে মস্তিষ্কে রক্ত পৌঁছায়।"),
    mcq("Why are there fewer big predators than plant-eaters?", ["Energy is lost at each step of the food chain", "Predators are lazy", "Plants eat predators", "It is random"], 0,
        "Each link passes on only part of the energy, so each level supports fewer animals.",
        "তৃণভোজীর চেয়ে বড় শিকারি কম কেন?", ["খাদ্যশৃঙ্খলের প্রতি ধাপে শক্তি হারায়", "শিকারিরা অলস", "গাছ শিকারি খায়", "এলোমেলো"],
        "প্রতিটি ধাপ শক্তির শুধু একটা অংশ দেয়, তাই প্রতিটি স্তরে কম প্রাণী টিকে থাকে।"),
    mcq("Which helps protect wildlife near a new bridge?", ["Planning paths for animals and protecting the river", "Cutting all trees", "Dumping waste", "Loud music"], 0,
        "Good engineers plan for animals too - with underpasses, careful building and clean rivers.",
        "নতুন সেতুর কাছে বন্যপ্রাণী রক্ষায় কী সাহায্য করে?", ["প্রাণীদের পথ পরিকল্পনা আর নদী রক্ষা", "সব গাছ কেটে ফেলা", "আবর্জনা ফেলা", "জোরে গান"],
        "ভালো প্রকৌশলীরা প্রাণীদের কথাও ভাবেন - নিচ দিয়ে পথ, সাবধানে নির্মাণ আর পরিষ্কার নদী দিয়ে।"),
    mcq("What is pollution?", ["Harmful waste in air, water or land", "Fresh air", "Clean water", "Healthy soil"], 0,
        "Smoke, litter and dirty water are pollution. It harms living things.",
        "দূষণ কী?", ["বাতাস, জল বা মাটিতে ক্ষতিকর বর্জ্য", "টাটকা বাতাস", "পরিষ্কার জল", "সুস্থ মাটি"],
        "ধোঁয়া, আবর্জনা আর নোংরা জল দূষণ। এটা জীবের ক্ষতি করে।"),
    mcq("Why are trees planted along busy roads?", ["They clean the air and give shade", "To block traffic", "To feed cars", "To make noise"], 0,
        "Trees absorb some pollution, give shade and make streets pleasant.",
        "ব্যস্ত রাস্তার ধারে গাছ লাগানো হয় কেন?", ["বাতাস পরিষ্কার করে আর ছায়া দেয়", "যানজট আটকাতে", "গাড়ি খাওয়াতে", "শব্দ করতে"],
        "গাছ কিছুটা দূষণ শোষে, ছায়া দেয় আর রাস্তাকে মনোরম করে।"),
    mcq("What is a 'seedling'?", ["A very young plant", "An old tree", "A type of fruit", "A dead leaf"], 0,
        "When a seed sprouts, the tiny new plant is a seedling.",
        "'চারাগাছ' কী?", ["খুব ছোট নতুন গাছ", "পুরোনো গাছ", "এক রকম ফল", "মরা পাতা"],
        "বীজ থেকে অঙ্কুর বেরোলে ছোট্ট নতুন গাছটাই চারাগাছ।"),
    mcq("Which part of a flower is usually colourful to attract insects?", ["Petals", "Roots", "Stem", "Seeds inside the soil"], 0,
        "Bright petals act like a sign saying 'nectar here!'.",
        "ফুলের কোন অংশ সাধারণত পোকা টানতে রঙিন হয়?", ["পাপড়ি", "শিকড়", "কাণ্ড", "মাটির নিচের বীজ"],
        "উজ্জ্বল পাপড়ি যেন সাইনবোর্ড - 'এখানে মধুরস!'।"),
    mcq("What do we call it when a caterpillar becomes a butterfly?", ["Metamorphosis", "Photosynthesis", "Migration", "Hibernation"], 0,
        "Metamorphosis means a big change in body shape during the life cycle.",
        "শুঁয়োপোকা প্রজাপতি হলে তাকে কী বলি?", ["রূপান্তর", "সালোকসংশ্লেষ", "পরিযান", "শীতঘুম"],
        "রূপান্তর মানে জীবনচক্রে শরীরের আকারের বড় পরিবর্তন।"),
    mcq("Which animal hibernates in winter in cold countries?", ["Bear", "Cow", "Pigeon", "Goldfish in a warm tank"], 0,
        "Many bears sleep through the winter, living on stored body fat.",
        "ঠান্ডা দেশে শীতে কোন প্রাণী শীতঘুম দেয়?", ["ভালুক", "গরু", "পায়রা", "গরম অ্যাকোয়ারিয়ামের সোনালি মাছ"],
        "অনেক ভালুক শরীরে জমানো চর্বিতে বেঁচে পুরো শীত ঘুমিয়ে কাটায়।"),
    mcq("Why does an owl's soft feathers help it hunt?", ["It flies silently", "It flies faster", "It glows", "It swims"], 0,
        "Soft fringed feathers muffle the sound of wing beats, so prey does not hear it coming.",
        "পেঁচার নরম পালক শিকারে সাহায্য করে কীভাবে?", ["নিঃশব্দে ওড়ে", "দ্রুত ওড়ে", "জ্বলে", "সাঁতার কাটে"],
        "নরম ঝালরওয়ালা পালক ডানার শব্দ চেপে দেয়, তাই শিকার টের পায় না।"),
    mcq("Which helps a plant climb up a wall or pole?", ["Tendrils that coil around supports", "Wheels", "Wings", "Fins"], 0,
        "Climbing plants like peas and grapes wrap tendrils around supports to reach light.",
        "দেয়াল বা খুঁটি বেয়ে উঠতে গাছকে কী সাহায্য করে?", ["আকর্ষ, যা সাপোর্ট পেঁচিয়ে ধরে", "চাকা", "ডানা", "পাখনা"],
        "মটর আর আঙুরের মতো লতানো গাছ আলো পেতে আকর্ষ দিয়ে সাপোর্ট পেঁচিয়ে ধরে।"),
    mcq("Your hand has 27 bones. Why so many?", ["So it can bend and grip in many ways", "To make it heavy", "To store food", "By accident"], 0,
        "Many small bones and joints let your hand do delicate and strong jobs.",
        "তোমার হাতে 27টি হাড়। এত বেশি কেন?", ["যাতে নানাভাবে বাঁকতে আর আঁকড়ে ধরতে পারে", "ভারী করতে", "খাবার জমাতে", "ভুল করে"],
        "অনেক ছোট হাড় আর সন্ধি হাতকে সূক্ষ্ম আর জোরালো দুই রকম কাজ করতে দেয়।"),
    mcq("What joins bones together at joints?", ["Ligaments (tough bands)", "Glue", "Hair", "Blood only"], 0,
        "Ligaments hold bones together; tendons join muscles to bones.",
        "সন্ধিতে হাড়গুলোকে কী জুড়ে রাখে?", ["লিগামেন্ট (শক্ত ফিতে)", "আঠা", "চুল", "শুধু রক্ত"],
        "লিগামেন্ট হাড় জুড়ে রাখে; টেন্ডন পেশিকে হাড়ের সঙ্গে জোড়ে।"),
    mcq("A knee joint works most like a...", ["Hinge on a door", "Ball", "Wheel", "Spring only"], 0,
        "The knee bends one way, like a hinge. The shoulder is a ball-and-socket joint that turns many ways.",
        "হাঁটুর সন্ধি সবচেয়ে বেশি কাজ করে...", ["দরজার কবজার মতো", "বলের মতো", "চাকার মতো", "শুধু স্প্রিংয়ের মতো"],
        "হাঁটু কবজার মতো এক দিকে ভাঁজ হয়। কাঁধ বল-সকেট সন্ধি, নানা দিকে ঘোরে।"),
    mcq("Which animal has a skeleton on the outside?", ["Crab", "Cat", "Human", "Horse"], 0,
        "Crabs and insects have an exoskeleton - a hard outer shell that protects and supports them.",
        "কোন প্রাণীর কঙ্কাল বাইরে?", ["কাঁকড়া", "বিড়াল", "মানুষ", "ঘোড়া"],
        "কাঁকড়া আর পতঙ্গের বহিঃকঙ্কাল - একটা শক্ত বাইরের খোলস, যা রক্ষা আর সাপোর্ট দেয়।"),
    mcq("How many hours of sleep do young children need each night?", ["About 9 to 12 hours", "About 1 hour", "About 3 hours", "None"], 0,
        "Growing bodies and brains need plenty of sleep.",
        "ছোট শিশুদের রাতে কত ঘণ্টা ঘুম দরকার?", ["প্রায় 9 থেকে 12 ঘণ্টা", "প্রায় 1 ঘণ্টা", "প্রায় 3 ঘণ্টা", "একদম না"],
        "বাড়ন্ত শরীর আর মস্তিষ্কের অনেক ঘুম দরকার।"),
    mcq("Which of these is a healthy drink for every day?", ["Water", "Fizzy cola", "Energy drink", "Syrup"], 0,
        "Water keeps you hydrated without sugar.",
        "প্রতিদিনের জন্য স্বাস্থ্যকর পানীয় কোনটা?", ["জল", "ফেনাওয়ালা কোলা", "এনার্জি ড্রিংক", "শরবতের সিরাপ"],
        "চিনি ছাড়াই জল তোমাকে সজল রাখে।"),
    mcq("What are the tiny building blocks of all living things called?", ["Cells", "Bricks", "Atoms only", "Seeds"], 0,
        "Every plant and animal is built from cells, like a building from bricks.",
        "সব জীবের ছোট্ট গঠন-একককে কী বলে?", ["কোষ", "ইট", "শুধু পরমাণু", "বীজ"],
        "প্রতিটি গাছ আর প্রাণী কোষ দিয়ে তৈরি, যেমন ভবন ইট দিয়ে।"),
    mcq("A plant's cell walls make it stand up straight. What would happen without them?", ["It would flop over", "It would grow faster", "It would turn into a tree", "Nothing"], 0,
        "Stiff cell walls work like a frame - like the beams of a bridge.",
        "গাছের কোষপ্রাচীর তাকে সোজা দাঁড় করায়। এগুলো না থাকলে কী হতো?", ["নেতিয়ে পড়ত", "দ্রুত বাড়ত", "বড় গাছ হতো", "কিছুই না"],
        "শক্ত কোষপ্রাচীর কাঠামোর মতো কাজ করে - সেতুর বিমের মতো।"),
)
