"""Class 2 - Chemistry: solids, liquids and gases, changes of state, mixtures and building materials."""
from . import mcq

ITEMS = (
    mcq("What are the three main states of matter?", ["Solid, liquid and gas", "Hot, cold and warm", "Big, small and tiny", "Red, blue and green"], 0,
        "Everything is a solid (keeps its shape), a liquid (flows) or a gas (spreads everywhere).",
        "পদার্থের তিনটি প্রধান অবস্থা কী কী?", ["কঠিন, তরল আর গ্যাস", "গরম, ঠান্ডা আর উষ্ণ", "বড়, ছোট আর ক্ষুদ্র", "লাল, নীল আর সবুজ"],
        "সবকিছু হয় কঠিন (আকার রাখে), তরল (বয়ে যায়) নয়তো গ্যাস (সবখানে ছড়ায়)।"),
    mcq("What do we call it when a liquid turns into a gas?", ["Evaporation", "Freezing", "Melting", "Sinking"], 0,
        "Puddles drying in the sun is evaporation: water becomes water vapour.",
        "তরল গ্যাসে বদলালে তাকে কী বলি?", ["বাষ্পীভবন", "জমে যাওয়া", "গলন", "ডুবে যাওয়া"],
        "রোদে ডোবা শুকিয়ে যাওয়াই বাষ্পীভবন: জল জলীয় বাষ্প হয়।"),
    mcq("What do we call it when a gas turns back into a liquid?", ["Condensation", "Evaporation", "Melting", "Burning"], 0,
        "Steam hitting a cold mirror turns back into water drops - condensation.",
        "গ্যাস আবার তরলে বদলালে তাকে কী বলি?", ["ঘনীভবন", "বাষ্পীভবন", "গলন", "দহন"],
        "ঠান্ডা আয়নায় বাষ্প লাগলে আবার জলের ফোঁটা হয় - ঘনীভবন।"),
    mcq("What do we call it when a solid turns into a liquid?", ["Melting", "Freezing", "Condensing", "Boiling"], 0,
        "Ice melting into water, butter melting in a pan - solid to liquid.",
        "কঠিন তরলে বদলালে তাকে কী বলি?", ["গলন", "জমে যাওয়া", "ঘনীভবন", "ফোটা"],
        "বরফ গলে জল, কড়াইয়ে মাখন গলা - কঠিন থেকে তরল।"),
    mcq("What do we call it when a liquid turns into a solid?", ["Freezing (solidifying)", "Evaporating", "Melting", "Dissolving"], 0,
        "Water in the freezer becomes ice; melted wax cools into a solid candle.",
        "তরল কঠিনে বদলালে তাকে কী বলি?", ["জমে যাওয়া (কঠিনীভবন)", "বাষ্পীভবন", "গলন", "দ্রবীভবন"],
        "ফ্রিজারে জল বরফ হয়; গলা মোম ঠান্ডা হয়ে কঠিন মোমবাতি হয়।"),
    mcq("At what temperature does pure water boil at sea level?", ["100 °C", "0 °C", "50 °C", "10 °C"], 0,
        "Water boils at 100 degrees Celsius and freezes at 0 degrees Celsius.",
        "সমুদ্রপৃষ্ঠে বিশুদ্ধ জল কত তাপমাত্রায় ফোটে?", ["100 °C", "0 °C", "50 °C", "10 °C"],
        "জল 100 ডিগ্রি সেলসিয়াসে ফোটে আর 0 ডিগ্রি সেলসিয়াসে জমে।"),
    mcq("Why does a liquid take the shape of its container?", ["Its particles can slide past each other", "It is always cold", "It is magnetic", "It has no weight"], 0,
        "In a liquid the tiny particles are close but free to move, so it flows to fill the bottom of any container.",
        "তরল পাত্রের আকার নেয় কেন?", ["তার কণাগুলো একে অপরের পাশ দিয়ে পিছলে যেতে পারে", "এটা সবসময় ঠান্ডা", "এটা চুম্বক", "এর ওজন নেই"],
        "তরলে ছোট কণাগুলো কাছাকাছি কিন্তু নড়তে পারে, তাই যেকোনো পাত্রের তলা ভরে বয়ে যায়।"),
    mcq("Why does a solid keep its shape?", ["Its particles are held tightly in place", "It is always wet", "It is very hot", "It has no particles"], 0,
        "In a solid the particles are locked together, so it keeps its own shape.",
        "কঠিন তার আকার রাখে কেন?", ["তার কণাগুলো শক্ত করে জায়গায় আটকানো", "এটা সবসময় ভেজা", "এটা খুব গরম", "এতে কোনো কণা নেই"],
        "কঠিনে কণাগুলো একসঙ্গে আটকানো, তাই নিজের আকার রাখে।"),
    mcq("Why does a smell spread through a whole room?", ["Gas particles spread out everywhere", "The smell walks", "Walls push it", "Smells are solids"], 0,
        "Gases spread to fill all the space they can. That is why you smell cooking from the next room.",
        "একটা গন্ধ পুরো ঘরে ছড়িয়ে পড়ে কেন?", ["গ্যাসের কণা সবখানে ছড়ায়", "গন্ধ হাঁটে", "দেয়াল ঠেলে", "গন্ধ কঠিন"],
        "গ্যাস যত জায়গা পায় তা ভরে ছড়িয়ে পড়ে। এজন্যই পাশের ঘর থেকে রান্নার গন্ধ পাও।"),
    mcq("You leave a glass of water out for a week. The water level goes down. Why?", ["Water evaporated into the air", "Someone drank it secretly every night", "The glass absorbed it", "Water sank through the table"], 0,
        "Even without boiling, water slowly evaporates at room temperature.",
        "এক গ্লাস জল এক সপ্তাহ বাইরে রেখে দিলে জল কমে যায়। কেন?", ["জল বাষ্প হয়ে বাতাসে মিশেছে", "কেউ রোজ রাতে লুকিয়ে খেয়েছে", "গ্লাস শুষে নিয়েছে", "জল টেবিল ভেদ করে নেমেছে"],
        "না ফুটিয়েও ঘরের তাপমাত্রায় জল ধীরে ধীরে বাষ্পীভূত হয়।"),
    mcq("How can you get salt back from salty water?", ["Let the water evaporate", "Freeze it", "Shake it", "Add more water"], 0,
        "When the water evaporates, the salt is left behind as crystals - that is how sea salt is made.",
        "নোনা জল থেকে কীভাবে আবার নুন পাওয়া যায়?", ["জল বাষ্পীভূত হতে দাও", "জমিয়ে দাও", "ঝাঁকাও", "আরও জল দাও"],
        "জল বাষ্প হয়ে গেলে নুন দানা হয়ে পড়ে থাকে - সামুদ্রিক নুন এভাবেই তৈরি হয়।"),
    mcq("Muddy water is poured through a filter paper. What comes through?", ["Cleaner water", "The mud", "Nothing", "Sand only"], 0,
        "The filter traps the solid bits of mud and lets the water pass.",
        "কাদাজল ফিল্টার পেপারে ঢালা হলো। কী বেরিয়ে আসে?", ["পরিষ্কার জল", "কাদা", "কিছুই না", "শুধু বালি"],
        "ফিল্টার কাদার কঠিন কণা আটকায় আর জল যেতে দেয়।"),
    mcq("Which can be separated with a magnet?", ["Iron filings from sand", "Salt from water", "Sugar from tea", "Sand from water"], 0,
        "A magnet pulls the iron out and leaves the sand behind.",
        "কোনটা চুম্বক দিয়ে আলাদা করা যায়?", ["বালি থেকে লোহার গুঁড়ো", "জল থেকে নুন", "চা থেকে চিনি", "জল থেকে বালি"],
        "চুম্বক লোহা টেনে বের করে আর বালি পড়ে থাকে।"),
    mcq("What is a solution?", ["A mixture where one thing dissolves in another", "A broken glass", "A frozen block", "A pile of stones"], 0,
        "Salt water and sugar water are solutions: the solid has dissolved and you cannot see it.",
        "দ্রবণ কী?", ["এমন মিশ্রণ, যেখানে একটা জিনিস অন্যটায় গলে যায়", "ভাঙা কাচ", "জমাট টুকরো", "পাথরের স্তূপ"],
        "নুন-জল আর চিনি-জল দ্রবণ: কঠিনটা গলে গেছে, দেখা যায় না।"),
    mcq("What makes sugar dissolve faster in water?", ["Stirring and using warm water", "Using ice cubes", "Leaving it still", "Adding sand"], 0,
        "Stirring and warmth help the water break the sugar apart faster.",
        "কী করলে চিনি জলে দ্রুত গলে?", ["নাড়ানো আর গরম জল ব্যবহার", "বরফের টুকরো দেওয়া", "স্থির রাখা", "বালি মেশানো"],
        "নাড়ালে আর গরম করলে জল দ্রুত চিনি ভেঙে দেয়।"),
    mcq("Steel is mostly made from which metal?", ["Iron", "Gold", "Silver", "Copper"], 0,
        "Steel is iron with a little carbon added, which makes it much stronger.",
        "ইস্পাত মূলত কোন ধাতু থেকে তৈরি?", ["লোহা", "সোনা", "রুপো", "তামা"],
        "ইস্পাত হলো লোহা, তাতে সামান্য কার্বন মেশানো, যা একে অনেক বেশি শক্ত করে।"),
    mcq("Why is steel used for bridges instead of pure iron?", ["Steel is stronger and tougher", "Iron is too shiny", "Iron floats", "Steel is softer"], 0,
        "Adding carbon to iron makes steel - strong in pulling and pushing, and tough enough not to shatter.",
        "সেতুতে খাঁটি লোহার বদলে ইস্পাত ব্যবহার হয় কেন?", ["ইস্পাত বেশি শক্ত আর টেকসই", "লোহা খুব চকচকে", "লোহা ভাসে", "ইস্পাত বেশি নরম"],
        "লোহায় কার্বন মেশালে ইস্পাত হয় - টানে আর ঠেলায় শক্ত, আর না ভাঙার মতো টেকসই।"),
    mcq("What do we call a metal made by mixing metals together, like steel or brass?", ["An alloy", "A liquid", "A gas", "A rock"], 0,
        "Alloys combine metals (or a metal and carbon) to get better properties.",
        "ইস্পাত বা পিতলের মতো ধাতু মিশিয়ে তৈরি ধাতুকে কী বলে?", ["সংকর ধাতু", "তরল", "গ্যাস", "পাথর"],
        "সংকর ধাতু ভালো গুণ পেতে ধাতু (বা ধাতু আর কার্বন) মেশায়।"),
    mcq("Which material does NOT rust?", ["Plastic", "Iron", "Steel without paint", "An iron nail"], 0,
        "Only iron and steel rust. Plastic never rusts.",
        "কোন উপাদানে মরচে ধরে না?", ["প্লাস্টিক", "লোহা", "রং ছাড়া ইস্পাত", "লোহার পেরেক"],
        "শুধু লোহা আর ইস্পাতে মরচে ধরে। প্লাস্টিকে কখনো ধরে না।"),
    mcq("What two things does iron need to rust?", ["Water and oxygen (air)", "Sugar and salt", "Light and sound", "Heat and noise"], 0,
        "Rust forms when iron meets both water and oxygen. Keep either away and rust slows down.",
        "লোহায় মরচে ধরতে কোন দুটি জিনিস লাগে?", ["জল আর অক্সিজেন (বাতাস)", "চিনি আর নুন", "আলো আর শব্দ", "তাপ আর আওয়াজ"],
        "লোহা জল আর অক্সিজেন দুটোর সংস্পর্শে এলে মরচে হয়। যেকোনো একটা দূরে রাখলে মরচে ধীর হয়।"),
    mcq("Which coating protects steel from rust?", ["Paint or a layer of zinc", "Sugar syrup", "Salt", "Mud"], 0,
        "Paint keeps water out. A zinc coating (galvanising) even protects scratched spots.",
        "কোন আবরণ ইস্পাতকে মরচে থেকে বাঁচায়?", ["রং বা দস্তার স্তর", "চিনির রস", "নুন", "কাদা"],
        "রং জল আটকায়। দস্তার আবরণ (গ্যালভানাইজিং) আঁচড় লাগা জায়গাও রক্ষা করে।"),
    mcq("What is concrete mainly good at?", ["Being squeezed (compression)", "Being pulled (tension)", "Floating", "Bending like rubber"], 0,
        "Concrete is very strong when pushed but cracks when pulled. That is why steel bars are put inside it.",
        "কংক্রিট মূলত কীসে ভালো?", ["চাপ সহ্য করায়", "টান সহ্য করায়", "ভাসায়", "রাবারের মতো বাঁকায়"],
        "কংক্রিট ঠেলায় খুব শক্ত কিন্তু টানে ফাটে। তাই এর ভেতরে ইস্পাতের রড দেওয়া হয়।"),
    mcq("Why are steel bars (rebar) put inside concrete?", ["Steel takes the pulling forces concrete cannot", "To make it shiny", "To make it lighter", "To make it rust"], 0,
        "Reinforced concrete: concrete handles squeezing, steel handles pulling - a perfect team.",
        "কংক্রিটের ভেতরে ইস্পাতের রড দেওয়া হয় কেন?", ["কংক্রিট যে টান সইতে পারে না, ইস্পাত তা নেয়", "চকচকে করতে", "হালকা করতে", "মরচে ধরাতে"],
        "রিইনফোর্সড কংক্রিট: কংক্রিট চাপ সামলায়, ইস্পাত টান সামলায় - নিখুঁত জুটি।"),
    mcq("Wood comes from trees. What is it made of?", ["Long fibres (cellulose) glued together", "Melted metal", "Glass crystals", "Pure water"], 0,
        "Wood fibres run along the trunk, so wood is strongest along the grain.",
        "কাঠ গাছ থেকে আসে। এটা কী দিয়ে তৈরি?", ["একসঙ্গে জোড়া লম্বা আঁশ (সেলুলোজ)", "গলা ধাতু", "কাচের দানা", "খাঁটি জল"],
        "কাঠের আঁশ গুঁড়ি বরাবর চলে, তাই কাঠ আঁশের দিক বরাবর সবচেয়ে শক্ত।"),
    mcq("Which material burns easily?", ["Dry wood", "Stone", "Steel", "Glass"], 0,
        "Wood is a fuel. That is why wooden bridges need protection from fire.",
        "কোন উপাদান সহজে পোড়ে?", ["শুকনো কাঠ", "পাথর", "ইস্পাত", "কাচ"],
        "কাঠ একটা জ্বালানি। এজন্যই কাঠের সেতুকে আগুন থেকে রক্ষা করতে হয়।"),
    mcq("What is left after wood burns?", ["Ash and smoke", "More wood", "Water only", "Gold"], 0,
        "Burning changes wood into ash, smoke and gases - a change that cannot be reversed.",
        "কাঠ পুড়ে গেলে কী থাকে?", ["ছাই আর ধোঁয়া", "আরও কাঠ", "শুধু জল", "সোনা"],
        "পোড়া কাঠকে ছাই, ধোঁয়া আর গ্যাসে বদলায় - এমন পরিবর্তন যা ফেরানো যায় না।"),
    mcq("A fire needs fuel, heat and...", ["Oxygen", "Water", "Sand", "Ice"], 0,
        "Take away oxygen (cover it with a blanket or sand) and a fire goes out.",
        "আগুনের জন্য লাগে জ্বালানি, তাপ আর...", ["অক্সিজেন", "জল", "বালি", "বরফ"],
        "অক্সিজেন সরিয়ে নিলে (কম্বল বা বালি দিয়ে ঢাকলে) আগুন নিভে যায়।"),
    mcq("Which is a reversible change?", ["Melting chocolate", "Burning paper", "Cooking an egg", "Baking a cake"], 0,
        "Melted chocolate sets again when it cools. Burning and cooking cannot be undone.",
        "কোনটা ফেরানো যায় এমন পরিবর্তন?", ["চকলেট গলানো", "কাগজ পোড়ানো", "ডিম রান্না", "কেক সেঁকা"],
        "গলা চকলেট ঠান্ডা হলে আবার জমে যায়। পোড়ানো আর রান্না ফেরানো যায় না।"),
    mcq("Which is an irreversible change?", ["Rusting iron", "Freezing water", "Melting ice", "Dissolving sugar"], 0,
        "Rust is a new substance; it does not turn back into shiny iron by itself.",
        "কোনটা ফেরানো যায় না এমন পরিবর্তন?", ["লোহায় মরচে ধরা", "জল জমানো", "বরফ গলানো", "চিনি গলানো"],
        "মরচে একটা নতুন পদার্থ; নিজে থেকে আর চকচকে লোহায় ফেরে না।"),
    mcq("Why do we keep cooking oil away from the stove flame?", ["Oil can catch fire", "Oil turns into water", "Oil freezes", "Oil gets heavy"], 0,
        "Hot oil is flammable. Never pour water on an oil fire - cover it instead.",
        "রান্নার তেল চুলার আগুন থেকে দূরে রাখি কেন?", ["তেলে আগুন ধরে যেতে পারে", "তেল জল হয়ে যায়", "তেল জমে যায়", "তেল ভারী হয়"],
        "গরম তেল দাহ্য। তেলের আগুনে কখনো জল ঢেলো না - বরং ঢেকে দাও।"),
    mcq("Glass is made from melting...", ["Sand", "Wood", "Wool", "Plastic"], 0,
        "Sand melted at about 1500 °C and cooled becomes glass.",
        "কাচ তৈরি হয় গলিয়ে...", ["বালি", "কাঠ", "উল", "প্লাস্টিক"],
        "প্রায় 1500 °C-এ বালি গলিয়ে ঠান্ডা করলে কাচ হয়।"),
    mcq("Plastic is mostly made from...", ["Oil (petroleum)", "Trees only", "Rocks only", "Sea water"], 0,
        "Most plastics are made from chemicals in crude oil.",
        "প্লাস্টিক বেশিরভাগই তৈরি হয়...", ["তেল (পেট্রোলিয়াম) থেকে", "শুধু গাছ থেকে", "শুধু পাথর থেকে", "সমুদ্রের জল থেকে"],
        "বেশিরভাগ প্লাস্টিক অপরিশোধিত তেলের রাসায়নিক থেকে তৈরি।"),
    mcq("Why is plastic litter a problem in rivers and seas?", ["It takes hundreds of years to break down and harms animals", "It is too heavy", "It dissolves too fast", "It makes water clean"], 0,
        "Plastic lasts a very long time and animals can swallow it or get tangled.",
        "নদী আর সমুদ্রে প্লাস্টিকের আবর্জনা সমস্যা কেন?", ["ভাঙতে শত শত বছর লাগে আর প্রাণীর ক্ষতি করে", "খুব ভারী", "খুব দ্রুত গলে যায়", "জল পরিষ্কার করে"],
        "প্লাস্টিক অনেকদিন টেকে আর প্রাণীরা তা গিলে ফেলতে বা জড়িয়ে যেতে পারে।"),
    mcq("What happens to clay when it is fired in a kiln?", ["It becomes hard pottery or brick", "It turns into water", "It becomes soft", "It disappears"], 0,
        "High heat changes clay permanently into hard ceramic.",
        "ভাটায় পোড়ালে কাদামাটির কী হয়?", ["শক্ত মৃৎপাত্র বা ইট হয়", "জল হয়ে যায়", "নরম হয়ে যায়", "উধাও হয়"],
        "উচ্চ তাপ কাদামাটিকে স্থায়ীভাবে শক্ত সিরামিকে বদলায়।"),
    mcq("Which is the hardest natural material?", ["Diamond", "Chalk", "Wood", "Ice"], 0,
        "Diamond is so hard it is used on saw blades to cut stone and concrete.",
        "কোনটা সবচেয়ে শক্ত প্রাকৃতিক উপাদান?", ["হীরে", "চক", "কাঠ", "বরফ"],
        "হীরে এত শক্ত যে পাথর আর কংক্রিট কাটার করাতে ব্যবহার হয়।"),
    mcq("Mortar between bricks is made of cement, sand and...", ["Water", "Sugar", "Oil", "Milk"], 0,
        "Water starts the chemical reaction that makes cement harden.",
        "ইটের মাঝের মশলা তৈরি হয় সিমেন্ট, বালি আর...", ["জল দিয়ে", "চিনি দিয়ে", "তেল দিয়ে", "দুধ দিয়ে"],
        "জল সেই রাসায়নিক বিক্রিয়া শুরু করে, যাতে সিমেন্ট শক্ত হয়।"),
    mcq("Why do builders add gravel (small stones) to concrete instead of using only cement?", ["Stones add strength and stop too much shrinking and cracking", "Stones make it soft", "Cement is too strong", "Gravel makes it float"], 0,
        "Pure cement paste shrinks and cracks like dry mud. Stones and sand give bulk and strength.",
        "নির্মাতারা শুধু সিমেন্টের বদলে কংক্রিটে পাথরকুচি দেন কেন?", ["পাথর শক্তি বাড়ায় আর বেশি কুঁচকে ফাটা ঠেকায়", "পাথর নরম করে", "সিমেন্ট খুব শক্ত", "পাথরকুচি ভাসায়"],
        "খাঁটি সিমেন্টের লেই শুকনো কাদার মতো কুঁচকে ফাটে। পাথর আর বালি আয়তন আর শক্তি দেয়।"),
    mcq("A shiny metal spoon left in salty water for weeks may...", ["Corrode or rust", "Turn into wood", "Grow bigger", "Melt"], 0,
        "Salty water speeds up corrosion of many metals.",
        "নোনা জলে কয়েক সপ্তাহ রাখা চকচকে ধাতুর চামচ...", ["ক্ষয়ে যেতে বা মরচে ধরতে পারে", "কাঠ হয়ে যেতে পারে", "বড় হতে পারে", "গলে যেতে পারে"],
        "নোনা জল অনেক ধাতুর ক্ষয় দ্রুত করে।"),
    mcq("Which property makes copper good for electric wires?", ["It conducts electricity well", "It is see-through", "It is soft like cotton", "It floats"], 0,
        "Copper lets electricity flow easily and can be pulled into thin wires.",
        "তামার কোন গুণ বৈদ্যুতিক তারের জন্য ভালো?", ["বিদ্যুৎ ভালো পরিবহন করে", "স্বচ্ছ", "তুলোর মতো নরম", "ভাসে"],
        "তামা সহজে বিদ্যুৎ চলতে দেয় আর টেনে সরু তার বানানো যায়।"),
    mcq("Why are pan handles often plastic or wood?", ["They are insulators - they do not get hot quickly", "They are cheaper than air", "They conduct heat best", "They are magnetic"], 0,
        "Insulators slow heat flow, so you can hold the handle safely.",
        "কড়াইয়ের হাতল প্রায়ই প্লাস্টিক বা কাঠের হয় কেন?", ["এরা অন্তরক - তাড়াতাড়ি গরম হয় না", "বাতাসের চেয়ে সস্তা", "তাপ সবচেয়ে ভালো পরিবহন করে", "চুম্বক"],
        "অন্তরক তাপের প্রবাহ ধীর করে, তাই হাতল নিরাপদে ধরা যায়।"),
    mcq("What do we call materials that let heat move through them easily?", ["Conductors", "Insulators", "Liquids only", "Gases only"], 0,
        "Metals are good heat conductors.",
        "যে উপাদানের মধ্য দিয়ে তাপ সহজে চলে তাকে কী বলি?", ["পরিবাহী", "অন্তরক", "শুধু তরল", "শুধু গ্যাস"],
        "ধাতু ভালো তাপ পরিবাহী।"),
    mcq("Why does a metal railing feel colder than a wooden bench on a cold morning?", ["Metal carries heat away from your hand faster", "Metal is always below zero", "Wood is heated inside", "Metal is wet"], 0,
        "Both are the same temperature, but metal conducts heat away from your hand much faster.",
        "ঠান্ডা সকালে ধাতুর রেলিং কাঠের বেঞ্চের চেয়ে বেশি ঠান্ডা লাগে কেন?", ["ধাতু তোমার হাত থেকে দ্রুত তাপ সরিয়ে নেয়", "ধাতু সবসময় শূন্যের নিচে", "কাঠ ভেতরে গরম করা", "ধাতু ভেজা"],
        "দুটোর তাপমাত্রা একই, কিন্তু ধাতু তোমার হাত থেকে অনেক দ্রুত তাপ সরিয়ে নেয়।"),
    mcq("What happens to most materials when they get hot?", ["They expand (get a little bigger)", "They shrink to nothing", "They turn blue", "Nothing"], 0,
        "Heat makes particles move more and spread out. Bridges and rails have gaps to allow for this.",
        "গরম হলে বেশিরভাগ উপাদানের কী হয়?", ["প্রসারিত হয় (একটু বড় হয়)", "সংকুচিত হয়ে উধাও হয়", "নীল হয়ে যায়", "কিছুই না"],
        "তাপে কণাগুলো বেশি নড়ে আর ছড়িয়ে পড়ে। সেতু আর রেললাইনে এর জন্য ফাঁক রাখা হয়।"),
    mcq("A tight jar lid can be loosened by running hot water over it. Why?", ["The metal lid expands more than the glass", "Water is slippery only", "Heat melts the glass", "It makes the jar smaller"], 0,
        "Metal expands more than glass when heated, so the lid loosens.",
        "শক্ত বয়ামের ঢাকনা গরম জলে ধরলে আলগা হয়। কেন?", ["ধাতুর ঢাকনা কাচের চেয়ে বেশি প্রসারিত হয়", "জল শুধু পিছল", "তাপে কাচ গলে", "বয়াম ছোট হয়ে যায়"],
        "গরমে ধাতু কাচের চেয়ে বেশি প্রসারিত হয়, তাই ঢাকনা আলগা হয়।"),
    mcq("What do we call air with a lot of water vapour in it?", ["Humid", "Dry", "Frozen", "Solid"], 0,
        "Humid air feels sticky and slows drying. Wood gets weaker when it soaks up moisture.",
        "যে বাতাসে অনেক জলীয় বাষ্প থাকে তাকে কী বলি?", ["আর্দ্র", "শুকনো", "জমাট", "কঠিন"],
        "আর্দ্র বাতাস চটচটে লাগে আর শুকানো ধীর করে। আর্দ্রতা শুষলে কাঠ দুর্বল হয়।"),
    mcq("Why do wooden bridges get weaker in wet, humid places?", ["Wood soaks up water and softens or rots", "Water makes wood harder", "Wood rusts", "Humidity is magnetic"], 0,
        "Wet wood loses strength and can rot. In MODIS BridgeWorks, timber keeps only 70% of its strength in humid levels.",
        "ভেজা, আর্দ্র জায়গায় কাঠের সেতু দুর্বল হয় কেন?", ["কাঠ জল শুষে নরম হয় বা পচে", "জল কাঠকে শক্ত করে", "কাঠে মরচে ধরে", "আর্দ্রতা চুম্বক"],
        "ভেজা কাঠ শক্তি হারায় আর পচতে পারে। MODIS BridgeWorks-এ আর্দ্র লেভেলে কাঠ শক্তির মাত্র 70% রাখে।"),
    mcq("Which of these is a natural fibre?", ["Cotton", "Nylon", "Polyester", "Acrylic"], 0,
        "Cotton grows on plants. Nylon, polyester and acrylic are made in factories.",
        "এগুলোর কোনটা প্রাকৃতিক আঁশ?", ["তুলো", "নাইলন", "পলিয়েস্টার", "অ্যাক্রিলিক"],
        "তুলো গাছে জন্মায়। নাইলন, পলিয়েস্টার আর অ্যাক্রিলিক কারখানায় তৈরি।"),
    mcq("Why do steel bridges near the sea need more care?", ["Salt in the air speeds up rust", "Seagulls eat steel", "Waves are hot", "Sand is magnetic"], 0,
        "Salt spray makes corrosion faster, so coastal steel needs thicker protection.",
        "সমুদ্রের কাছের ইস্পাতের সেতুর বেশি যত্ন লাগে কেন?", ["বাতাসের নুন মরচে দ্রুত করে", "গাঙচিল ইস্পাত খায়", "ঢেউ গরম", "বালি চুম্বক"],
        "নোনা জলকণা ক্ষয় দ্রুত করে, তাই উপকূলের ইস্পাতে মোটা সুরক্ষা লাগে।"),
    mcq("Vinegar and lemon juice taste sour because they are...", ["Acids", "Metals", "Gases", "Solids"], 0,
        "Acids taste sour. Strong acids can also eat away at stone and concrete over time.",
        "ভিনেগার আর লেবুর রস টক কারণ এরা...", ["অম্ল (অ্যাসিড)", "ধাতু", "গ্যাস", "কঠিন"],
        "অম্লের স্বাদ টক। জোরালো অম্ল সময়ের সঙ্গে পাথর আর কংক্রিটও ক্ষয় করতে পারে।"),
    mcq("Soap feels slippery because it is a...", ["Base (alkali)", "Acid", "Metal", "Gas"], 0,
        "Bases (alkalis) like soap feel slippery. Acids and bases are chemical opposites.",
        "সাবান পিছল লাগে কারণ এটা একটা...", ["ক্ষার", "অম্ল", "ধাতু", "গ্যাস"],
        "সাবানের মতো ক্ষার পিছল লাগে। অম্ল আর ক্ষার রাসায়নিকভাবে বিপরীত।"),
    mcq("Why must cement be kept dry until it is used?", ["Water makes it start hardening", "It melts in water", "Water makes it explode", "It turns into sugar"], 0,
        "Cement reacts with water and sets. A wet bag turns into a useless rock.",
        "ব্যবহারের আগে পর্যন্ত সিমেন্ট শুকনো রাখতে হয় কেন?", ["জলে এটা শক্ত হতে শুরু করে", "জলে গলে যায়", "জলে বিস্ফোরণ হয়", "চিনি হয়ে যায়"],
        "সিমেন্ট জলের সঙ্গে বিক্রিয়া করে জমে যায়। ভেজা বস্তা একটা অকেজো পাথর হয়ে যায়।"),
    mcq("Which material is best for a bridge cable that must pull with great force?", ["Steel wire", "Wool", "Paper", "Chalk"], 0,
        "Steel wire is extremely strong in tension - perfect for bridge cables.",
        "যে সেতুর তারকে বিশাল জোরে টানতে হবে, তার জন্য কোন উপাদান সবচেয়ে ভালো?", ["ইস্পাতের তার", "উল", "কাগজ", "চক"],
        "ইস্পাতের তার টানে ভীষণ শক্ত - সেতুর তারের জন্য একদম ঠিক।"),
    mcq("What is the main gas in the air we breathe?", ["Nitrogen", "Oxygen", "Carbon dioxide", "Helium"], 0,
        "Air is about 78% nitrogen and 21% oxygen. We need the oxygen part.",
        "আমাদের শ্বাসের বাতাসে প্রধান গ্যাস কোনটা?", ["নাইট্রোজেন", "অক্সিজেন", "কার্বন ডাই-অক্সাইড", "হিলিয়াম"],
        "বাতাসে প্রায় 78% নাইট্রোজেন আর 21% অক্সিজেন। আমাদের দরকার অক্সিজেন অংশটা।"),
    mcq("Which gas do we breathe out more of than we breathe in?", ["Carbon dioxide", "Oxygen", "Helium", "Hydrogen"], 0,
        "Our bodies use oxygen and make carbon dioxide, which we breathe out.",
        "কোন গ্যাস আমরা নেওয়ার চেয়ে বেশি ছাড়ি?", ["কার্বন ডাই-অক্সাইড", "অক্সিজেন", "হিলিয়াম", "হাইড্রোজেন"],
        "শরীর অক্সিজেন ব্যবহার করে কার্বন ডাই-অক্সাইড তৈরি করে, যা আমরা ছাড়ি।"),
    mcq("Party balloons that float up are filled with...", ["Helium", "Water", "Sand", "Carbon dioxide"], 0,
        "Helium is lighter than air, so helium balloons float up.",
        "যে পার্টির বেলুন উপরে ভেসে ওঠে তাতে ভরা থাকে...", ["হিলিয়াম", "জল", "বালি", "কার্বন ডাই-অক্সাইড"],
        "হিলিয়াম বাতাসের চেয়ে হালকা, তাই হিলিয়াম বেলুন ভেসে ওঠে।"),
    mcq("Fizzy drinks have bubbles of which gas?", ["Carbon dioxide", "Oxygen", "Helium", "Steam"], 0,
        "Carbon dioxide is dissolved in the drink under pressure; opening the bottle lets it bubble out.",
        "ফেনাওয়ালা পানীয়তে কোন গ্যাসের বুদবুদ থাকে?", ["কার্বন ডাই-অক্সাইড", "অক্সিজেন", "হিলিয়াম", "বাষ্প"],
        "চাপে কার্বন ডাই-অক্সাইড পানীয়তে গলানো থাকে; বোতল খুললে বুদবুদ হয়ে বেরোয়।"),
    mcq("Why does a fizzy drink go flat if left open?", ["The gas escapes into the air", "The drink freezes", "Sugar eats the bubbles", "It gets heavier"], 0,
        "Without the cap, the dissolved carbon dioxide slowly escapes.",
        "খোলা রেখে দিলে ফেনাওয়ালা পানীয় পানসে হয়ে যায় কেন?", ["গ্যাস বাতাসে বেরিয়ে যায়", "পানীয় জমে যায়", "চিনি বুদবুদ খায়", "ভারী হয়ে যায়"],
        "ঢাকনা না থাকলে গলে থাকা কার্বন ডাই-অক্সাইড ধীরে বেরিয়ে যায়।"),
    mcq("What is 'matter'?", ["Anything that has mass and takes up space", "Only liquids", "Only things you can see", "Only living things"], 0,
        "Rocks, water, air and you are all matter.",
        "'পদার্থ' কী?", ["যার ভর আছে আর জায়গা নেয়", "শুধু তরল", "শুধু যা দেখা যায়", "শুধু জীবন্ত জিনিস"],
        "পাথর, জল, বাতাস আর তুমি - সবই পদার্থ।"),
    mcq("Which has the biggest gaps between its particles?", ["A gas", "A solid", "A liquid", "A rock"], 0,
        "Gas particles are far apart and zoom around - that is why gases can be squashed.",
        "কোনটার কণাগুলোর মাঝে ফাঁক সবচেয়ে বেশি?", ["গ্যাস", "কঠিন", "তরল", "পাথর"],
        "গ্যাসের কণাগুলো অনেক দূরে দূরে আর ছুটে বেড়ায় - তাই গ্যাস চেপে ছোট করা যায়।"),
    mcq("You can squash air in a bicycle pump but not water. Why?", ["Gas particles have space between them; liquid particles are close together", "Water is a solid", "Air is heavier", "Pumps hate water"], 0,
        "Liquids are hard to compress because their particles are already touching.",
        "সাইকেলের পাম্পে বাতাস চেপে ছোট করা যায়, জল নয়। কেন?", ["গ্যাসের কণার মাঝে ফাঁক আছে; তরলের কণা কাছাকাছি", "জল কঠিন", "বাতাস ভারী", "পাম্প জল অপছন্দ করে"],
        "তরল চেপে ছোট করা কঠিন, কারণ তার কণাগুলো আগে থেকেই ছুঁয়ে আছে।"),
    mcq("Which is a mixture you can separate by picking out the parts?", ["Nuts and raisins", "Salt water", "Sugar water", "Air"], 0,
        "In nuts and raisins you can see and pick each part. In solutions the parts are hidden.",
        "কোন মিশ্রণ অংশগুলো বেছে আলাদা করা যায়?", ["বাদাম আর কিশমিশ", "নুন-জল", "চিনি-জল", "বাতাস"],
        "বাদাম আর কিশমিশে প্রতিটি অংশ দেখা আর বাছা যায়। দ্রবণে অংশগুলো লুকানো থাকে।"),
    mcq("Why do pearls of dew form on grass on cool mornings?", ["Water vapour in the air condenses on cold grass", "Grass sweats", "It rained secretly", "Clouds sit on the grass"], 0,
        "Cool grass chills the air touching it, and vapour turns into droplets - condensation.",
        "ঠান্ডা সকালে ঘাসে শিশিরের ফোঁটা জমে কেন?", ["বাতাসের জলীয় বাষ্প ঠান্ডা ঘাসে ঘনীভূত হয়", "ঘাস ঘামে", "লুকিয়ে বৃষ্টি হয়েছে", "মেঘ ঘাসে বসে"],
        "ঠান্ডা ঘাস তার সংস্পর্শের বাতাস ঠান্ডা করে, আর বাষ্প ফোঁটা হয় - ঘনীভবন।"),
    mcq("Rain, clouds, rivers and the sea are all part of the...", ["Water cycle", "Bicycle", "Food chain", "Life of a rock only"], 0,
        "Water evaporates, condenses into clouds, falls as rain and flows back to the sea - over and over.",
        "বৃষ্টি, মেঘ, নদী আর সমুদ্র - সবই কীসের অংশ?", ["জলচক্র", "সাইকেল", "খাদ্যশৃঙ্খল", "শুধু পাথরের জীবন"],
        "জল বাষ্প হয়, মেঘে ঘনীভূত হয়, বৃষ্টি হয়ে পড়ে আর বয়ে সমুদ্রে ফেরে - বারবার।"),
    mcq("Why do roads crack after many hot days and cold nights?", ["Heating and cooling make them expand and shrink again and again", "Cars bite them", "The moon pulls them", "Rain is too heavy"], 0,
        "Repeated expanding and shrinking makes materials tired and cracked over time.",
        "অনেক গরম দিন আর ঠান্ডা রাতের পর রাস্তা ফাটে কেন?", ["গরম-ঠান্ডায় বারবার প্রসারণ আর সংকোচন হয়", "গাড়ি কামড়ায়", "চাঁদ টানে", "বৃষ্টি খুব ভারী"],
        "বারবার প্রসারণ আর সংকোচনে সময়ের সঙ্গে উপাদান ক্লান্ত হয়ে ফাটে।"),
    mcq("Water that gets into a crack and freezes can...", ["Widen the crack, because ice takes more space", "Glue it shut", "Make the rock softer only", "Nothing"], 0,
        "Water expands when it freezes and pushes cracks apart. This breaks rocks and damages roads.",
        "ফাটলে ঢোকা জল জমে গেলে...", ["ফাটল আরও চওড়া করে, কারণ বরফ বেশি জায়গা নেয়", "আঠার মতো জুড়ে দেয়", "শুধু পাথর নরম করে", "কিছুই না"],
        "জল জমে গেলে প্রসারিত হয়ে ফাটল ঠেলে চওড়া করে। এতে পাথর ভাঙে আর রাস্তা নষ্ট হয়।"),
    mcq("Which material is waterproof and used to cover bridge decks under the road?", ["A waterproof membrane (like bitumen)", "Paper", "Cotton cloth", "Bread"], 0,
        "A waterproof layer stops rain soaking into the concrete and rusting the steel inside.",
        "কোন জলরোধী উপাদান রাস্তার নিচে সেতুর ডেক ঢাকতে ব্যবহার হয়?", ["জলরোধী পর্দা (যেমন বিটুমেন)", "কাগজ", "সুতির কাপড়", "পাউরুটি"],
        "জলরোধী স্তর বৃষ্টির জল কংক্রিটে ঢুকে ভেতরের ইস্পাতে মরচে ধরানো আটকায়।"),
    mcq("What is the solid left in a kettle in places with hard water?", ["Limescale (chalky minerals)", "Sugar", "Rust only", "Gold dust"], 0,
        "Hard water has dissolved minerals. When it boils away, the chalky minerals are left behind.",
        "খর জলের জায়গায় কেটলিতে কোন কঠিন পদার্থ জমে?", ["চুনের স্তর (খড়িমাটির মতো খনিজ)", "চিনি", "শুধু মরচে", "সোনার গুঁড়ো"],
        "খর জলে খনিজ গলে থাকে। ফুটে জল উবে গেলে খড়িমাটির মতো খনিজ পড়ে থাকে।"),
    mcq("Chalk fizzes in vinegar. What is happening?", ["An acid is reacting and making a gas", "Chalk is melting from heat", "Vinegar is freezing", "Nothing"], 0,
        "Acid reacts with chalk (a carbonate) and gives off carbon dioxide bubbles. Acid rain damages limestone buildings this way.",
        "ভিনেগারে চক বুদবুদ ছাড়ে। কী ঘটছে?", ["অম্ল বিক্রিয়া করে গ্যাস তৈরি করছে", "তাপে চক গলছে", "ভিনেগার জমছে", "কিছুই না"],
        "অম্ল চকের (কার্বনেট) সঙ্গে বিক্রিয়া করে কার্বন ডাই-অক্সাইডের বুদবুদ ছাড়ে। অম্লবৃষ্টি চুনাপাথরের ভবন এভাবেই নষ্ট করে।"),
    mcq("Why are old statues sometimes worn away in cities?", ["Acid rain slowly dissolves the stone", "Pigeons polish them", "People hug them too much", "They shrink in winter only"], 0,
        "Pollution makes rain slightly acidic, which eats away limestone and marble over the years.",
        "শহরে পুরোনো মূর্তি কখনো কখনো ক্ষয়ে যায় কেন?", ["অম্লবৃষ্টি ধীরে ধীরে পাথর গলায়", "পায়রা ঘষে চকচকে করে", "মানুষ খুব জড়িয়ে ধরে", "শুধু শীতে ছোট হয়"],
        "দূষণ বৃষ্টিকে সামান্য অম্লীয় করে, যা বছরের পর বছর চুনাপাথর আর মার্বেল ক্ষয় করে।"),
    mcq("Which is the best material for a non-stick, heat-proof oven glove?", ["Thick cloth with an insulating layer", "Thin metal foil", "Wet paper", "Plastic bag"], 0,
        "Thick insulating fabric slows heat getting to your hand.",
        "উনুনের জন্য তাপরোধী দস্তানায় কোন উপাদান সবচেয়ে ভালো?", ["অন্তরক স্তরসহ মোটা কাপড়", "পাতলা ধাতুর পাত", "ভেজা কাগজ", "প্লাস্টিকের ব্যাগ"],
        "মোটা অন্তরক কাপড় হাত পর্যন্ত তাপ পৌঁছানো ধীর করে।"),
    mcq("Which is a sign that a chemical change happened?", ["A new colour, gas bubbles or a smell appear", "It just got smaller", "It moved", "It was painted"], 0,
        "New substances often show up as colour changes, fizzing, heat or new smells.",
        "রাসায়নিক পরিবর্তন হয়েছে তার একটা চিহ্ন কোনটা?", ["নতুন রং, গ্যাসের বুদবুদ বা গন্ধ দেখা দেয়", "শুধু ছোট হয়েছে", "সরে গেছে", "রং করা হয়েছে"],
        "নতুন পদার্থ প্রায়ই রং বদল, বুদবুদ, তাপ বা নতুন গন্ধে ধরা পড়ে।"),
    mcq("Why does bread go mouldy if kept too long?", ["Tiny fungi grow on it", "It rusts", "It melts", "Bread is magnetic"], 0,
        "Mould is a fungus that feeds on old bread, especially in warm, damp places.",
        "বেশিদিন রাখলে পাউরুটিতে ছাতা পড়ে কেন?", ["ছোট ছোট ছত্রাক জন্মায়", "মরচে ধরে", "গলে যায়", "পাউরুটি চুম্বক"],
        "ছাতা এক রকম ছত্রাক, যা পুরোনো পাউরুটি খেয়ে বাড়ে, বিশেষ করে গরম, ভেজা জায়গায়।"),
    mcq("Which is the best way to keep a bridge's steel strong for 100 years?", ["Protect it with paint and inspect it regularly", "Leave it bare in the rain", "Cover it in salt", "Wash it with vinegar"], 0,
        "Coatings plus regular inspection and repainting stop rust before it weakens the steel.",
        "সেতুর ইস্পাত 100 বছর মজবুত রাখার সবচেয়ে ভালো উপায় কোনটা?", ["রং দিয়ে রক্ষা করা আর নিয়মিত পরিদর্শন", "বৃষ্টিতে খালি রেখে দেওয়া", "নুনে ঢেকে রাখা", "ভিনেগারে ধোয়া"],
        "আবরণ আর নিয়মিত পরিদর্শন ও রং করা ইস্পাত দুর্বল হওয়ার আগেই মরচে থামায়।"),
    mcq("Wet sand is heavier than dry sand. Why?", ["Water fills the gaps between the grains", "Wet sand has more sand", "Water is lighter than air", "It is not heavier"], 0,
        "Water sits in the spaces between grains and adds its own weight.",
        "ভেজা বালি শুকনো বালির চেয়ে ভারী। কেন?", ["দানাগুলোর মাঝের ফাঁক জলে ভরে যায়", "ভেজা বালিতে বেশি বালি", "জল বাতাসের চেয়ে হালকা", "ভারী নয়"],
        "জল দানার মাঝের ফাঁকে বসে নিজের ওজন যোগ করে।"),
    mcq("What is a 'crystal'?", ["A solid with particles in a neat repeating pattern", "A liquid that glows", "A type of gas", "A soft powder only"], 0,
        "Salt, sugar, snowflakes and diamonds are crystals.",
        "'কেলাস' (ক্রিস্টাল) কী?", ["এমন কঠিন, যার কণাগুলো সুন্দর পুনরাবৃত্ত নকশায় সাজানো", "এক রকম জ্বলন্ত তরল", "এক রকম গ্যাস", "শুধু নরম গুঁড়ো"],
        "নুন, চিনি, তুষারকণা আর হীরে কেলাস।"),
    mcq("Which material would you choose for a bridge in a very wet jungle?", ["Treated, protected timber or galvanised steel", "Untreated paper", "Cardboard", "Sugar blocks"], 0,
        "In wet places you need materials that resist rot and rust, or that are protected from them.",
        "খুব ভেজা জঙ্গলে সেতুর জন্য কোন উপাদান বাছবে?", ["রাসায়নিকে সুরক্ষিত কাঠ বা দস্তা-লেপা ইস্পাত", "সুরক্ষাহীন কাগজ", "কার্ডবোর্ড", "চিনির টুকরো"],
        "ভেজা জায়গায় এমন উপাদান লাগে যা পচা আর মরচে ঠেকায়, বা তা থেকে সুরক্ষিত।"),
    mcq("What makes an ice cube melt faster?", ["Putting it somewhere warm", "Putting it in the freezer", "Wrapping it in thick wool", "Keeping it in the shade in winter"], 0,
        "More heat from the surroundings melts ice faster. Wool would actually slow melting!",
        "কী করলে বরফের টুকরো দ্রুত গলে?", ["গরম জায়গায় রাখলে", "ফ্রিজারে রাখলে", "মোটা উলে মুড়লে", "শীতে ছায়ায় রাখলে"],
        "চারপাশ থেকে বেশি তাপ পেলে বরফ দ্রুত গলে। উলে মুড়লে উল্টে গলা ধীর হয়!"),
    mcq("What is 'oxygen' needed for in burning?", ["The fuel combines with it to release heat", "It puts fires out", "It makes smoke disappear", "Nothing"], 0,
        "Burning is a reaction between fuel and oxygen that gives out heat and light.",
        "পোড়ায় 'অক্সিজেন' কীসের জন্য লাগে?", ["জ্বালানি এর সঙ্গে মিলে তাপ ছাড়ে", "আগুন নেভায়", "ধোঁয়া উধাও করে", "কিছুই না"],
        "দহন হলো জ্বালানি আর অক্সিজেনের বিক্রিয়া, যাতে তাপ আর আলো বেরোয়।"),
    mcq("Why do builders mix lime or cement with soil to make stronger ground for roads?", ["The chemicals bind the soil grains together", "It makes the soil wetter", "It feeds the worms", "It makes the road colourful"], 0,
        "Stabilised soil is harder and carries heavy trucks without sinking.",
        "রাস্তার জন্য মাটি শক্ত করতে নির্মাতারা মাটিতে চুন বা সিমেন্ট মেশান কেন?", ["রাসায়নিক মাটির দানাগুলো জুড়ে দেয়", "মাটি ভেজা করে", "কেঁচোদের খাওয়ায়", "রাস্তা রঙিন করে"],
        "স্থিত মাটি শক্ত হয় আর না বসে ভারী ট্রাক বইতে পারে।"),
    mcq("Rubber gloves protect an electrician because rubber is...", ["An electrical insulator", "A great conductor", "Magnetic", "Waterproof only"], 0,
        "Rubber does not let electricity pass, keeping the electrician safe.",
        "রাবারের দস্তানা বিদ্যুৎ-মিস্ত্রিকে রক্ষা করে কারণ রাবার...", ["বিদ্যুৎ অন্তরক", "দারুণ পরিবাহী", "চুম্বক", "শুধু জলরোধী"],
        "রাবার বিদ্যুৎ যেতে দেয় না, তাই মিস্ত্রি নিরাপদ থাকেন।"),
    mcq("What is 'evaporation' used for in salt farms by the sea?", ["Letting the sun dry sea water to leave salt", "Freezing the sea", "Making the sea deeper", "Catching fish"], 0,
        "Shallow pools of sea water are left in the sun; the water evaporates and salt remains.",
        "সমুদ্রের ধারে নুনখামারে 'বাষ্পীভবন' কাজে লাগে কীভাবে?", ["সূর্য সমুদ্রের জল শুকিয়ে নুন রেখে যায়", "সমুদ্র জমাতে", "সমুদ্র গভীর করতে", "মাছ ধরতে"],
        "অগভীর পুকুরে সমুদ্রের জল রোদে রাখা হয়; জল উবে যায় আর নুন থাকে।"),
    mcq("Which change happens when you mix flour, water and yeast and wait?", ["The dough rises as gas is made", "The dough turns to stone", "It freezes", "Nothing"], 0,
        "Yeast is alive and makes carbon dioxide gas, which puffs up the dough.",
        "ময়দা, জল আর ইস্ট মিশিয়ে অপেক্ষা করলে কী পরিবর্তন হয়?", ["গ্যাস তৈরি হয়ে মাখা ময়দা ফুলে ওঠে", "মাখা ময়দা পাথর হয়", "জমে যায়", "কিছুই না"],
        "ইস্ট জীবন্ত আর কার্বন ডাই-অক্সাইড গ্যাস তৈরি করে, যা মাখা ময়দা ফুলিয়ে দেয়।"),
    mcq("Why do we store petrol in sealed cans away from heat?", ["It evaporates easily and its vapour can catch fire", "It freezes in sunlight", "It turns into water", "It is heavy"], 0,
        "Petrol vapour is highly flammable. Sealed cans and cool places keep it safe.",
        "পেট্রল তাপ থেকে দূরে বন্ধ ক্যানে রাখি কেন?", ["সহজে বাষ্প হয় আর তার বাষ্পে আগুন ধরতে পারে", "রোদে জমে যায়", "জল হয়ে যায়", "ভারী"],
        "পেট্রলের বাষ্প খুব দাহ্য। বন্ধ ক্যান আর ঠান্ডা জায়গা নিরাপদ রাখে।"),
    mcq("A cold drink can 'sweats' on a warm day. Is the can leaking?", ["No - water vapour from the air is condensing on it", "Yes, always", "The drink is evaporating through the metal", "The can is melting"], 0,
        "The cold can cools the air around it, and vapour condenses into drops on the outside.",
        "গরম দিনে ঠান্ডা পানীয়ের ক্যান 'ঘামে'। ক্যান কি ফুটো?", ["না - বাতাসের জলীয় বাষ্প এতে ঘনীভূত হচ্ছে", "হ্যাঁ, সবসময়", "পানীয় ধাতু ভেদ করে উবে যাচ্ছে", "ক্যান গলছে"],
        "ঠান্ডা ক্যান চারপাশের বাতাস ঠান্ডা করে, আর বাষ্প বাইরে ফোঁটা হয়ে জমে।"),
    mcq("Why is gold used in jewellery for thousands of years?", ["It does not rust or tarnish and stays shiny", "It is the cheapest metal", "It is magnetic", "It floats"], 0,
        "Gold barely reacts with air or water, so it stays bright for centuries.",
        "হাজার হাজার বছর ধরে গয়নায় সোনা ব্যবহার হয় কেন?", ["মরচে বা কালচে পড়ে না, চকচকে থাকে", "সবচেয়ে সস্তা ধাতু", "চুম্বক", "ভাসে"],
        "সোনা বাতাস বা জলের সঙ্গে প্রায় বিক্রিয়াই করে না, তাই শতাব্দী ধরে উজ্জ্বল থাকে।"),
    mcq("Which word means 'easily catches fire'?", ["Flammable", "Waterproof", "Transparent", "Magnetic"], 0,
        "Flammable materials like paper, wood and petrol burn easily.",
        "কোন শব্দের মানে 'সহজে আগুন ধরে'?", ["দাহ্য", "জলরোধী", "স্বচ্ছ", "চৌম্বক"],
        "কাগজ, কাঠ আর পেট্রলের মতো দাহ্য উপাদান সহজে পোড়ে।"),
    mcq("Which material is both strong and light, used in bikes and aeroplanes?", ["Aluminium alloy", "Lead", "Clay", "Chalk"], 0,
        "Aluminium alloys are light and strong and do not rust like iron.",
        "কোন উপাদান শক্ত আর হালকা দুই-ই, সাইকেল আর উড়োজাহাজে ব্যবহার হয়?", ["অ্যালুমিনিয়াম সংকর", "সীসা", "কাদামাটি", "চক"],
        "অ্যালুমিনিয়াম সংকর হালকা, শক্ত আর লোহার মতো মরচে ধরে না।"),
    mcq("Steam from a kettle is invisible right at the spout. The white cloud a little further away is...", ["Tiny water droplets after the steam cools", "Smoke", "Dust", "Ice"], 0,
        "True steam is invisible gas; as it cools it condenses into tiny visible droplets.",
        "কেটলির নলের ঠিক মুখে বাষ্প অদৃশ্য। একটু দূরের সাদা মেঘটা হলো...", ["বাষ্প ঠান্ডা হয়ে তৈরি ছোট ছোট জলকণা", "ধোঁয়া", "ধুলো", "বরফ"],
        "আসল বাষ্প অদৃশ্য গ্যাস; ঠান্ডা হলে তা ঘনীভূত হয়ে দেখা যায় এমন ছোট কণা হয়।"),
    mcq("What do we call it when a solid seems to vanish into a liquid, like salt in soup?", ["Dissolving", "Melting", "Freezing", "Burning"], 0,
        "Dissolving is different from melting: the salt is still there, spread out in the water.",
        "নুন স্যুপে যেমন মিশে যায়, কঠিন যখন তরলে মিলিয়ে যায় বলে মনে হয়, তাকে কী বলি?", ["দ্রবীভবন", "গলন", "জমে যাওয়া", "দহন"],
        "দ্রবীভবন গলনের থেকে আলাদা: নুন তখনও আছে, জলে ছড়িয়ে আছে।"),
    mcq("Why does a puddle dry faster on a windy day?", ["Wind carries away the water vapour", "Wind pushes water underground", "Wind is hot always", "It does not"], 0,
        "Moving air removes the damp air above the puddle, so more water can evaporate.",
        "হাওয়ার দিনে ডোবা দ্রুত শুকায় কেন?", ["বাতাস জলীয় বাষ্প সরিয়ে নেয়", "বাতাস জল মাটির নিচে ঠেলে", "বাতাস সবসময় গরম", "শুকায় না"],
        "চলমান বাতাস ডোবার উপরের ভেজা বাতাস সরায়, তাই আরও জল বাষ্প হতে পারে।"),
    mcq("A sugar cube and powdered sugar are put in water. Which dissolves faster?", ["Powdered sugar", "The sugar cube", "Both the same", "Neither dissolves"], 0,
        "Tiny pieces have more surface touching the water, so they dissolve faster.",
        "এক টুকরো চিনির কিউব আর গুঁড়ো চিনি জলে দেওয়া হলো। কোনটা দ্রুত গলবে?", ["গুঁড়ো চিনি", "চিনির কিউব", "দুটোই সমান", "কোনোটাই গলবে না"],
        "ছোট কণার বেশি তল জল ছোঁয়, তাই দ্রুত গলে।"),
    mcq("Which property describes how hard it is to scratch a material?", ["Hardness", "Colour", "Smell", "Taste"], 0,
        "Hardness tells us how well a material resists scratches and dents.",
        "একটা উপাদানে আঁচড় কাটা কতটা কঠিন, তা কোন গুণ বর্ণনা করে?", ["কাঠিন্য", "রং", "গন্ধ", "স্বাদ"],
        "কাঠিন্য জানায় উপাদান কতটা ভালোভাবে আঁচড় আর টোল ঠেকায়।"),
    mcq("Which property describes a material that can be bent without breaking?", ["Flexible", "Brittle", "Transparent", "Soluble"], 0,
        "Flexible materials bend. Brittle materials snap.",
        "কোন গুণ এমন উপাদান বর্ণনা করে যা না ভেঙে বাঁকানো যায়?", ["নমনীয়", "ভঙ্গুর", "স্বচ্ছ", "দ্রাব্য"],
        "নমনীয় উপাদান বাঁকে। ভঙ্গুর উপাদান ভেঙে যায়।"),
    mcq("Which word describes something that dissolves?", ["Soluble", "Insoluble", "Opaque", "Rigid"], 0,
        "Sugar and salt are soluble in water; sand and chalk are insoluble.",
        "যা দ্রবীভূত হয়, তাকে কোন শব্দে বলে?", ["দ্রাব্য", "অদ্রাব্য", "অস্বচ্ছ", "অনমনীয়"],
        "চিনি আর নুন জলে দ্রাব্য; বালি আর চক অদ্রাব্য।"),
    mcq("Rubbish is sorted into paper, plastic, glass and metal at a recycling centre. Why?", ["Each material is recycled in its own way", "To make the bins pretty", "Because they hate each other", "To make more rubbish"], 0,
        "Glass is melted, paper is pulped, metals are melted separately - so they must be sorted first.",
        "পুনর্ব্যবহার কেন্দ্রে আবর্জনা কাগজ, প্লাস্টিক, কাচ আর ধাতুতে বাছাই হয়। কেন?", ["প্রতিটি উপাদান নিজের মতো করে পুনর্ব্যবহৃত হয়", "বিন সুন্দর করতে", "কারণ তারা একে অপরকে অপছন্দ করে", "আরও আবর্জনা বানাতে"],
        "কাচ গলানো হয়, কাগজ মণ্ড করা হয়, ধাতু আলাদা করে গলানো হয় - তাই আগে বাছাই করতে হয়।"),
    mcq("Old steel from a broken bridge can be...", ["Melted and made into new steel", "Only thrown away", "Turned into wood", "Eaten"], 0,
        "Steel is one of the most recycled materials - that is part of the 'salvage' you recover in MODIS BridgeWorks!",
        "ভাঙা সেতুর পুরোনো ইস্পাত দিয়ে...", ["গলিয়ে নতুন ইস্পাত বানানো যায়", "শুধু ফেলে দেওয়া যায়", "কাঠ বানানো যায়", "খাওয়া যায়"],
        "ইস্পাত সবচেয়ে বেশি পুনর্ব্যবহৃত উপাদানের একটি - MODIS BridgeWorks-এ যে 'উদ্ধার-মূল্য' পাও তার অংশ এটাই!"),
    mcq("Which is the best reason to use recycled steel?", ["It saves energy and raw materials", "It is weaker", "It is always rusty", "It cannot be used for bridges"], 0,
        "Recycling steel uses much less energy than making it from iron ore.",
        "পুনর্ব্যবহৃত ইস্পাত ব্যবহারের সবচেয়ে ভালো কারণ কোনটা?", ["শক্তি আর কাঁচামাল বাঁচে", "এটা দুর্বল", "সবসময় মরচে ধরা", "সেতুতে ব্যবহার করা যায় না"],
        "আকরিক থেকে বানানোর চেয়ে পুনর্ব্যবহারে অনেক কম শক্তি লাগে।"),
    mcq("What is iron ore?", ["Rock containing iron that is dug from the ground", "A type of wood", "A gas", "A plastic"], 0,
        "Iron ore is mined and heated in a blast furnace to get iron, which becomes steel.",
        "লোহার আকরিক কী?", ["মাটি খুঁড়ে তোলা লোহাযুক্ত পাথর", "এক রকম কাঠ", "একটা গ্যাস", "একটা প্লাস্টিক"],
        "লোহার আকরিক খনি থেকে তুলে মারুত চুল্লিতে গরম করে লোহা পাওয়া হয়, যা পরে ইস্পাত হয়।"),
    mcq("A hot steel bar glows red. What happens when it cools?", ["It stops glowing and becomes hard again", "It turns into water", "It becomes wood", "It glows brighter"], 0,
        "Very hot metal gives off light. As it cools, it goes dark and hardens.",
        "গরম ইস্পাতের দণ্ড লাল হয়ে জ্বলে। ঠান্ডা হলে কী হয়?", ["জ্বলা থামে আর আবার শক্ত হয়", "জল হয়ে যায়", "কাঠ হয়ে যায়", "আরও উজ্জ্বল হয়"],
        "খুব গরম ধাতু আলো ছড়ায়। ঠান্ডা হলে অন্ধকার হয়ে শক্ত হয়।"),
    mcq("Which is safest to put out a small fire in a frying pan?", ["Cover it with a lid", "Pour water on it", "Blow on it", "Fan it"], 0,
        "A lid cuts off oxygen. Water on hot oil can splash and spread the fire.",
        "ফ্রাইপ্যানের ছোট আগুন নেভানোর সবচেয়ে নিরাপদ উপায় কোনটা?", ["ঢাকনা দিয়ে ঢেকে দাও", "জল ঢালো", "ফুঁ দাও", "হাওয়া করো"],
        "ঢাকনা অক্সিজেন বন্ধ করে। গরম তেলে জল ঢাললে ছিটকে আগুন ছড়াতে পারে।"),
)
