"""Class 2 - Physics: forces in action, simple machines, bridge shapes, sound, light and heat."""
from . import mcq

ITEMS = (
    mcq("Which bridge shape pushes its weight outwards into the river banks, like a curved rainbow?",
        ["An arch bridge", "A rope swing", "A flat plank", "A see-saw"], 0,
        "An arch turns the weight into a push along its curve and down into strong ground at each end. Romans built arches 2000 years ago!",
        "কোন সেতুর আকার রংধনুর মতো বাঁকা হয়ে ওজন নদীর পাড়ের দিকে ঠেলে দেয়?",
        ["খিলান সেতু", "দড়ির দোলনা", "সমতল তক্তা", "ঢেঁকি"],
        "খিলান ওজনকে তার বাঁক বরাবর ঠেলায় বদলে দুই প্রান্তের শক্ত মাটিতে নামায়। রোমানরা 2000 বছর আগে খিলান বানাত!"),
    mcq("In a suspension bridge, the road hangs from...", ["Cables hanging from tall towers", "Balloons", "Trees", "The clouds"], 0,
        "Huge cables run over tall towers, and smaller cables hang down to hold the road.",
        "ঝুলন্ত সেতুতে রাস্তা ঝোলে...", ["উঁচু টাওয়ার থেকে ঝোলা তার থেকে", "বেলুন থেকে", "গাছ থেকে", "মেঘ থেকে"],
        "বিশাল তার উঁচু টাওয়ারের উপর দিয়ে যায়, আর ছোট তারগুলো নেমে রাস্তা ধরে রাখে।"),
    mcq("What simple machine is a see-saw?", ["A lever", "A pulley", "A screw", "A wheel"], 0,
        "A lever is a bar that turns around a point called the pivot (fulcrum).",
        "ঢেঁকি কোন সরল যন্ত্র?", ["লিভার", "কপিকল", "স্ক্রু", "চাকা"],
        "লিভার হলো একটা দণ্ড, যা পিভট (আলম্ব) নামের বিন্দুকে ঘিরে ঘোরে।"),
    mcq("A pulley helps you...", ["Lift heavy things by pulling down on a rope", "Make music", "Cook food", "Keep warm"], 0,
        "A rope over a wheel lets you pull down to lift up - easier, because you can use your weight.",
        "কপিকল তোমাকে সাহায্য করে...", ["দড়ি নিচে টেনে ভারী জিনিস তুলতে", "গান বানাতে", "রান্না করতে", "গরম থাকতে"],
        "চাকার উপর দিয়ে যাওয়া দড়ি নিচে টানলে জিনিস উপরে ওঠে - সহজ, কারণ নিজের ওজন কাজে লাগাতে পারো।"),
    mcq("You use a long stick to lift a heavy rock. Where should the small stone (pivot) go?", ["Close to the rock", "Far from the rock", "On top of the rock", "Nowhere"], 0,
        "Pivot near the load and push far away: a small push lifts a big weight. That is leverage!",
        "লম্বা লাঠি দিয়ে ভারী পাথর তুলবে। ছোট পাথরটা (পিভট) কোথায় রাখবে?", ["ভারী পাথরের কাছে", "ভারী পাথর থেকে দূরে", "পাথরের উপরে", "কোথাও না"],
        "ভারের কাছে পিভট আর দূর থেকে ঠেলা: অল্প ঠেলায় বড় ওজন ওঠে। এটাই লিভারের জোর!"),
    mcq("Which is a wheel and axle?", ["A door knob", "A ladder", "A nail", "A plate"], 0,
        "Turning the big knob turns the small rod inside - a wheel and axle makes turning easier.",
        "কোনটা চাকা ও অক্ষদণ্ড?", ["দরজার হাতল (নব)", "মই", "পেরেক", "থালা"],
        "বড় হাতল ঘোরালে ভেতরের ছোট দণ্ড ঘোরে - চাকা ও অক্ষদণ্ড ঘোরানো সহজ করে।"),
    mcq("A ramp is also called...", ["An inclined plane", "A flat floor", "A wheel", "A lever"], 0,
        "An inclined plane is a slope. Pushing a load up a long slope needs less force than lifting it straight up.",
        "র‍্যাম্পের আরেক নাম...", ["আনত তল", "সমতল মেঝে", "চাকা", "লিভার"],
        "আনত তল মানে ঢাল। লম্বা ঢাল বেয়ে ভার ঠেলতে সোজা তোলার চেয়ে কম বল লাগে।"),
    mcq("Which ramp needs the smallest push to get a cart to the top?", ["A long gentle ramp", "A short steep ramp", "A vertical wall", "No ramp"], 0,
        "A gentle ramp is longer but needs less push at every step - the same trick mountain roads use.",
        "কোন র‍্যাম্পে গাড়ি উপরে তুলতে সবচেয়ে কম ঠেলা লাগে?", ["লম্বা মৃদু র‍্যাম্প", "ছোট খাড়া র‍্যাম্প", "খাড়া দেয়াল", "র‍্যাম্প ছাড়া"],
        "মৃদু র‍্যাম্প লম্বা, কিন্তু প্রতি পদে কম ঠেলা লাগে - পাহাড়ি রাস্তাও এই কৌশল নেয়।"),
    mcq("A screw is really an inclined plane wrapped around...", ["A rod", "A ball", "A box", "A flame"], 0,
        "The spiral thread on a screw is a ramp wound round a rod, so turning it drives it in with great force.",
        "স্ক্রু আসলে একটা আনত তল, যা পেঁচানো থাকে...", ["একটা দণ্ডের চারপাশে", "একটা বলের চারপাশে", "একটা বাক্সের চারপাশে", "একটা শিখার চারপাশে"],
        "স্ক্রুর প্যাঁচানো খাঁজ দণ্ডের চারপাশে মোড়ানো ঢাল, তাই ঘোরালে বিশাল জোরে ঢুকে যায়।"),
    mcq("An axe splits wood easily because its edge is a...", ["Wedge", "Wheel", "Pulley", "Spring"], 0,
        "A wedge is a thin edge that pushes things apart. Knives and teeth are wedges too!",
        "কুড়ুল সহজে কাঠ চেরে কারণ তার ধার একটা...", ["গোঁজ (ওয়েজ)", "চাকা", "কপিকল", "স্প্রিং"],
        "গোঁজ হলো সরু ধার, যা জিনিসকে দুই ভাগে ঠেলে দেয়। ছুরি আর দাঁতও গোঁজ!"),
    mcq("A thick plank and a thin plank of the same wood span a stream. Which bends less?", ["The thick plank", "The thin plank", "They bend the same", "Neither bends ever"], 0,
        "Thicker beams are much stiffer. Doubling the thickness makes a plank about 8 times stiffer!",
        "একই কাঠের একটা মোটা আর একটা পাতলা তক্তা নালার উপর রাখা। কোনটা কম বাঁকবে?", ["মোটা তক্তা", "পাতলা তক্তা", "দুটোই সমান বাঁকবে", "কোনোটাই কখনো বাঁকে না"],
        "মোটা বিম অনেক বেশি দৃঢ়। পুরুত্ব দ্বিগুণ করলে তক্তা প্রায় 8 গুণ দৃঢ় হয়!"),
    mcq("A plank lying flat or standing on its edge - which way is stiffer for a bridge?", ["On its edge (tall)", "Lying flat", "Both the same", "Upside down only"], 0,
        "Standing on edge makes it deep. Depth fights bending far better than width - that is why beams are tall.",
        "একটা তক্তা চ্যাপ্টা করে শোয়ানো নাকি কিনারায় দাঁড় করানো - সেতুর জন্য কোনটা বেশি দৃঢ়?", ["কিনারায় দাঁড় করানো (উঁচু)", "চ্যাপ্টা শোয়ানো", "দুটোই সমান", "শুধু উল্টো করে"],
        "কিনারায় দাঁড় করালে গভীর হয়। গভীরতা প্রস্থের চেয়ে অনেক ভালোভাবে বাঁকা ঠেকায় - এজন্যই বিম উঁচু হয়।"),
    mcq("What does a spring do when you squash it and let go?", ["Pushes back to its shape", "Stays squashed", "Melts", "Disappears"], 0,
        "Springs store the push and give it back. Car suspensions use springs for a smooth ride.",
        "স্প্রিং চেপে ছেড়ে দিলে কী করে?", ["ঠেলে আগের আকারে ফেরে", "চাপা থাকে", "গলে যায়", "উধাও হয়"],
        "স্প্রিং ঠেলা জমিয়ে রাখে আর ফিরিয়ে দেয়। গাড়ির সাসপেনশন মসৃণ চলার জন্য স্প্রিং ব্যবহার করে।"),
    mcq("Which pushes harder on the floor: you standing on one foot or on two?", ["The same total weight - but one foot presses harder per spot", "Two feet push double weight", "One foot weighs nothing", "Standing has no push"], 0,
        "Your weight is the same either way. On one foot it is squeezed onto a smaller area, so the pressure is bigger.",
        "কোনটায় মেঝেতে বেশি চাপ: এক পায়ে দাঁড়ানো নাকি দুই পায়ে?", ["মোট ওজন একই - কিন্তু এক পায়ে প্রতি জায়গায় বেশি চাপ", "দুই পায়ে দ্বিগুণ ওজন", "এক পায়ের ওজন শূন্য", "দাঁড়ালে কোনো চাপ নেই"],
        "দুইভাবেই তোমার ওজন একই। এক পায়ে তা ছোট জায়গায় চাপে, তাই চাপ বেশি।"),
    mcq("Why do camels and snowshoes have big flat feet?", ["To spread weight and not sink", "To run faster on roads", "To look funny", "To dig holes"], 0,
        "Big feet spread the weight over more area, so they do not sink into sand or snow. Bridge pillars stand on wide footings for the same reason.",
        "উট আর বরফে হাঁটার জুতোর পা বড় চ্যাপ্টা কেন?", ["ওজন ছড়িয়ে দিয়ে না ডুবতে", "রাস্তায় দ্রুত দৌড়াতে", "মজার দেখাতে", "গর্ত খুঁড়তে"],
        "বড় পা ওজন বেশি জায়গায় ছড়িয়ে দেয়, তাই বালি বা বরফে ডোবে না। সেতুর স্তম্ভও একই কারণে চওড়া ভিতে দাঁড়ায়।"),
    mcq("A big drum and a small drum: which makes the lower, deeper sound?", ["The big drum", "The small drum", "Both the same", "Drums make no sound"], 0,
        "Bigger things vibrate more slowly, giving a lower pitch.",
        "বড় ঢোল আর ছোট ঢোল: কোনটায় নিচু, গম্ভীর শব্দ হয়?", ["বড় ঢোল", "ছোট ঢোল", "দুটোই সমান", "ঢোলে শব্দ হয় না"],
        "বড় জিনিস ধীরে কাঁপে, তাতে নিচু তীক্ষ্ণতার শব্দ হয়।"),
    mcq("A tight guitar string and a loose one: which gives the higher note?", ["The tight string", "The loose string", "Both the same", "Neither"], 0,
        "Tighter strings vibrate faster, making a higher pitch.",
        "টানটান গিটারের তার আর ঢিলা তার: কোনটায় উঁচু সুর হয়?", ["টানটান তার", "ঢিলা তার", "দুটোই সমান", "কোনোটাই না"],
        "টানটান তার দ্রুত কাঁপে, তাতে উঁচু সুর হয়।"),
    mcq("What is an echo?", ["A sound bouncing back from a wall or hill", "A new animal", "A light", "A quiet whisper"], 0,
        "Shout towards a cliff and the sound reflects back to you a moment later.",
        "প্রতিধ্বনি কী?", ["দেয়াল বা পাহাড়ে লেগে ফিরে আসা শব্দ", "একটা নতুন প্রাণী", "একটা আলো", "চুপিচুপি ফিসফিস"],
        "পাহাড়ের দিকে চেঁচালে শব্দ প্রতিফলিত হয়ে একটু পরে তোমার কাছে ফিরে আসে।"),
    mcq("When is your shadow the longest?", ["Early morning or late evening", "At noon", "Never", "At midnight in the sun"], 0,
        "When the sun is low in the sky, shadows stretch out long. At noon the sun is high and shadows are short.",
        "তোমার ছায়া কখন সবচেয়ে লম্বা?", ["ভোরে বা সন্ধ্যার আগে", "দুপুরে", "কখনো না", "মাঝরাতের রোদে"],
        "সূর্য আকাশে নিচে থাকলে ছায়া লম্বা হয়। দুপুরে সূর্য উঁচুতে, ছায়া ছোট।"),
    mcq("A mirror shows your right hand as...", ["Looking like a left hand", "A foot", "Upside down", "Invisible"], 0,
        "A mirror flips left and right, so your raised right hand looks like a left hand in the reflection.",
        "আয়নায় তোমার ডান হাত দেখায়...", ["বাঁ হাতের মতো", "পায়ের মতো", "উল্টো করে", "অদৃশ্য"],
        "আয়না ডান-বাঁ উল্টে দেয়, তাই তোলা ডান হাত প্রতিবিম্বে বাঁ হাতের মতো দেখায়।"),
    mcq("Which material lets only some light through (frosted glass, tissue paper)?", ["Translucent", "Transparent", "Opaque", "Magnetic"], 0,
        "Transparent: all light through. Translucent: some light, blurry view. Opaque: no light.",
        "কোন উপাদান কিছুটা আলো যেতে দেয় (ঘষা কাচ, টিস্যু পেপার)?", ["অর্ধস্বচ্ছ", "স্বচ্ছ", "অস্বচ্ছ", "চৌম্বক"],
        "স্বচ্ছ: সব আলো যায়। অর্ধস্বচ্ছ: কিছু আলো, ঝাপসা দেখা যায়। অস্বচ্ছ: কোনো আলো যায় না।"),
    mcq("Why do we see a rainbow after rain?", ["Sunlight is split into colours by water drops", "Someone painted the sky", "Clouds are coloured", "The rain is coloured"], 0,
        "White sunlight is a mix of colours. Raindrops bend each colour a different amount and spread them out.",
        "বৃষ্টির পরে রংধনু দেখি কেন?", ["জলকণা সূর্যের আলোকে রঙে ভাগ করে", "কেউ আকাশ রং করেছে", "মেঘ রঙিন", "বৃষ্টি রঙিন"],
        "সাদা সূর্যালোক অনেক রঙের মিশ্রণ। বৃষ্টির ফোঁটা প্রতিটি রংকে আলাদা মাত্রায় বাঁকিয়ে ছড়িয়ে দেয়।"),
    mcq("How many colours do we usually name in a rainbow?", ["7", "3", "12", "2"], 0,
        "Red, orange, yellow, green, blue, indigo and violet - 7 colours.",
        "রংধনুতে আমরা সাধারণত কয়টি রঙের নাম বলি?", ["7", "3", "12", "2"],
        "লাল, কমলা, হলুদ, সবুজ, নীল, আসমানি আর বেগুনি - 7টি রং।"),
    mcq("Which keeps a cup of tea hot longer?", ["A cup with a lid in a woollen cover", "An open metal plate", "A cup by an open window", "A cup in the fridge"], 0,
        "Lids and wool stop heat escaping. Materials that slow heat are called insulators.",
        "কোনটায় চা বেশিক্ষণ গরম থাকে?", ["উলের ঢাকনায় মোড়া ঢাকনাওয়ালা কাপ", "খোলা ধাতুর থালা", "খোলা জানালার পাশের কাপ", "ফ্রিজের কাপ"],
        "ঢাকনা আর উল তাপ বেরোতে দেয় না। যে উপাদান তাপ ধীর করে তাদের বলে অন্তরক।"),
    mcq("Which travels fastest?", ["Light", "Sound", "A car", "A running cheetah"], 0,
        "Light is the fastest thing there is - about 300,000 kilometres every second!",
        "কোনটা সবচেয়ে দ্রুত চলে?", ["আলো", "শব্দ", "গাড়ি", "দৌড়ানো চিতা"],
        "আলো সবচেয়ে দ্রুত - প্রতি সেকেন্ডে প্রায় 3,00,000 কিলোমিটার!"),
    mcq("A heavy box is easier to slide on rollers (round logs). Why?", ["Rolling has much less friction than sliding", "Logs push it", "The box gets lighter", "Logs are magnetic"], 0,
        "Ancient builders moved giant stones on log rollers. Rolling beats dragging!",
        "গোল গুঁড়ির উপর ভারী বাক্স সরানো সহজ। কেন?", ["গড়ানোয় ঘষার চেয়ে অনেক কম ঘর্ষণ", "গুঁড়ি তাকে ঠেলে", "বাক্স হালকা হয়", "গুঁড়ি চুম্বক"],
        "প্রাচীন নির্মাতারা গুঁড়ির রোলারে বিশাল পাথর সরাতেন। গড়ানো টানাহেঁচড়াকে হারায়!"),
    mcq("A heavy cart and a light cart are pushed with the same force. Which speeds up faster?", ["The light cart", "The heavy cart", "Both equally", "Neither moves"], 0,
        "The same push makes a lighter thing speed up more. Heavy things need bigger pushes.",
        "একটা ভারী আর একটা হালকা গাড়ি একই জোরে ঠেলা হলো। কোনটা দ্রুত গতি পায়?", ["হালকা গাড়ি", "ভারী গাড়ি", "দুটোই সমান", "কোনোটাই নড়ে না"],
        "একই ঠেলায় হালকা জিনিস বেশি গতি পায়। ভারী জিনিসে বড় ঠেলা লাগে।"),
    mcq("Why is it hard to stop a heavy train quickly?", ["It carries a lot of moving 'oomph' (momentum)", "Trains have no brakes", "Rails are sticky", "It is easy"], 0,
        "Momentum is mass times speed. A heavy, fast train has huge momentum and needs a long distance to stop.",
        "ভারী ট্রেন দ্রুত থামানো কঠিন কেন?", ["তার চলার জোর (ভরবেগ) অনেক বেশি", "ট্রেনের ব্রেক নেই", "লাইন আঠালো", "এটা সহজ"],
        "ভরবেগ হলো ভর গুণ গতি। ভারী, দ্রুত ট্রেনের বিশাল ভরবেগ, থামতে অনেক পথ লাগে।"),
    mcq("Iron filings near a magnet line up in a pattern. What does the pattern show?", ["The magnet's invisible force field", "Wind", "Water", "Nothing"], 0,
        "The filings follow the magnetic field lines that spread from one pole to the other.",
        "চুম্বকের কাছে লোহার গুঁড়ো একটা নকশায় সাজে। নকশাটা কী দেখায়?", ["চুম্বকের অদৃশ্য বলক্ষেত্র", "বাতাস", "জল", "কিছুই না"],
        "গুঁড়োগুলো এক মেরু থেকে অন্য মেরুতে ছড়ানো চৌম্বক বলরেখা মেনে সাজে।"),
    mcq("A compass needle always points...", ["North (and south)", "At the nearest tree", "Up", "Wherever it likes"], 0,
        "A compass needle is a tiny magnet that lines up with the Earth's magnetic field.",
        "কম্পাসের কাঁটা সবসময় নির্দেশ করে...", ["উত্তর (আর দক্ষিণ)", "কাছের গাছকে", "উপরে", "যেদিকে খুশি"],
        "কম্পাসের কাঁটা একটা ছোট্ট চুম্বক, যা পৃথিবীর চৌম্বকক্ষেত্রের সঙ্গে সারিবদ্ধ হয়।"),
    mcq("Why do skyscrapers and tall bridges sway a little in strong wind?", ["They are built to bend slightly instead of snapping", "They are made of jelly", "They are dancing", "They never sway"], 0,
        "A tiny sway is safe and planned. Being a little flexible stops tall structures from cracking.",
        "জোরালো বাতাসে গগনচুম্বী ভবন আর উঁচু সেতু একটু দোলে কেন?", ["ভেঙে না গিয়ে সামান্য বাঁকার মতো করে বানানো", "জেলির তৈরি", "নাচছে", "কখনো দোলে না"],
        "সামান্য দোলা নিরাপদ আর পরিকল্পিত। একটু নমনীয় হলে উঁচু কাঠামো ফাটে না।"),
    mcq("A ball is dropped from a high window and a low window. Which hits the ground faster?", ["From the high window", "From the low window", "Both at the same speed", "Neither"], 0,
        "The longer it falls, the more time gravity has to speed it up.",
        "একটা বল উঁচু জানালা আর নিচু জানালা থেকে ফেলা হলো। কোনটা বেশি গতিতে মাটিতে লাগবে?", ["উঁচু জানালা থেকে", "নিচু জানালা থেকে", "দুটোই সমান গতিতে", "কোনোটাই না"],
        "যত বেশি পড়ে, মাধ্যাকর্ষণ তত বেশি সময় পায় গতি বাড়াতে।"),
    mcq("Which is a good way to make a paper tower stronger?", ["Roll the paper into tubes", "Wet the paper", "Tear it in half", "Crumple it into a ball"], 0,
        "Tubes are hard to bend and buckle. Steel towers are often hollow tubes for the same reason.",
        "কাগজের মিনার আরও মজবুত করার ভালো উপায় কোনটা?", ["কাগজ গুটিয়ে নল বানাও", "কাগজ ভেজাও", "ছিঁড়ে অর্ধেক করো", "দলা পাকিয়ে বল করো"],
        "নল বাঁকানো আর বাকল করানো কঠিন। একই কারণে ইস্পাতের টাওয়ার প্রায়ই ফাঁপা নল দিয়ে তৈরি।"),
    mcq("When you jump on a trampoline, why do you bounce up?", ["The springy mat stretches and pushes you back", "The trampoline is magic", "Gravity turns off", "The air lifts you"], 0,
        "Your weight stretches the mat; the stretched mat pushes back and throws you up.",
        "ট্রাম্পোলিনে লাফালে উপরে ছিটকে ওঠো কেন?", ["স্প্রিংয়ের মতো মাদুর টানটান হয়ে তোমাকে ফিরিয়ে ঠেলে", "ট্রাম্পোলিন জাদুর", "মাধ্যাকর্ষণ বন্ধ হয়ে যায়", "বাতাস তোমাকে তোলে"],
        "তোমার ওজন মাদুরকে টানে; টানটান মাদুর উল্টো ঠেলে তোমাকে উপরে ছুড়ে দেয়।"),
    mcq("A rope pulled tight between two posts can hold up a hanging lamp. The rope is in...", ["Tension (being pulled)", "Compression (being squeezed)", "Melting", "Freezing"], 0,
        "Ropes and cables only work when pulled tight - that is tension.",
        "দুটি খুঁটির মাঝে টানটান দড়ি একটা ঝোলানো বাতি ধরে রাখতে পারে। দড়িটা আছে...", ["টানে", "চাপে", "গলছে", "জমছে"],
        "দড়ি আর তার শুধু টানটান থাকলেই কাজ করে - একে বলে টান।"),
    mcq("A pillar holding up a roof is being...", ["Squeezed (compression)", "Pulled (tension)", "Twisted only", "Nothing at all"], 0,
        "The roof's weight pushes down on the pillar and the ground pushes up: the pillar is squeezed.",
        "ছাদ ধরে থাকা স্তম্ভের কী হচ্ছে?", ["চাপ খাচ্ছে", "টান খাচ্ছে", "শুধু মোচড় খাচ্ছে", "কিছুই না"],
        "ছাদের ওজন স্তম্ভকে নিচে ঠেলে আর মাটি উপরে ঠেলে: স্তম্ভ চাপে থাকে।"),
    mcq("What happens to a long thin stick if you squeeze its ends together hard?", ["It bends sideways and snaps", "It gets longer", "It turns into a rope", "Nothing ever"], 0,
        "Long thin things squeezed at the ends bow out sideways. Engineers call this buckling.",
        "লম্বা সরু কাঠির দুই প্রান্ত জোরে কাছে চাপলে কী হয়?", ["পাশে বেঁকে ভেঙে যায়", "লম্বা হয়ে যায়", "দড়ি হয়ে যায়", "কখনো কিছু হয় না"],
        "লম্বা সরু জিনিস প্রান্তে চাপলে পাশে বেঁকে যায়। প্রকৌশলীরা একে বলেন বাকলিং।"),
    mcq("Which is the shortest stick and so the hardest to buckle?", ["A short thick stick", "A long thin stick", "A long thin wire", "A long noodle"], 0,
        "Short and thick sticks resist buckling far better than long thin ones.",
        "কোনটা সবচেয়ে ছোট, তাই বাকল করানো সবচেয়ে কঠিন?", ["ছোট মোটা কাঠি", "লম্বা সরু কাঠি", "লম্বা সরু তার", "লম্বা নুডল"],
        "ছোট আর মোটা কাঠি লম্বা সরুগুলোর চেয়ে অনেক ভালোভাবে বাকলিং ঠেকায়।"),
    mcq("Where is it easier to pedal a bicycle?", ["On a flat road", "Up a steep hill", "On deep sand", "In thick mud"], 0,
        "On the flat you do not fight gravity, and the hard road has little rolling resistance.",
        "সাইকেল চালানো কোথায় সহজ?", ["সমতল রাস্তায়", "খাড়া পাহাড়ে", "গভীর বালিতে", "ঘন কাদায়"],
        "সমতলে মাধ্যাকর্ষণের সঙ্গে লড়তে হয় না, আর শক্ত রাস্তায় গড়ানোর বাধা কম।"),
    mcq("What does a seat belt do in a car that suddenly stops?", ["Holds you so you do not keep moving forward", "Makes the car faster", "Plays music", "Keeps you warm"], 0,
        "Your body wants to keep moving when the car stops. The belt stops you safely.",
        "গাড়ি হঠাৎ থামলে সিটবেল্ট কী করে?", ["তোমাকে ধরে রাখে, যাতে সামনে ছিটকে না যাও", "গাড়ি দ্রুত করে", "গান বাজায়", "গরম রাখে"],
        "গাড়ি থামলে তোমার শরীর চলতে চায়। বেল্ট নিরাপদে তোমাকে থামায়।"),
    mcq("A heavy door with the handle near the hinge would be...", ["Hard to open", "Easy to open", "Impossible to close", "Lighter"], 0,
        "Turning effect = force x distance from the hinge. A handle near the hinge gives little turning effect.",
        "কবজার কাছে হাতলওয়ালা ভারী দরজা হবে...", ["খুলতে কঠিন", "খুলতে সহজ", "বন্ধ করা অসম্ভব", "হালকা"],
        "ঘোরানোর প্রভাব = বল x কবজা থেকে দূরত্ব। কবজার কাছে হাতল হলে ঘোরানোর প্রভাব কম।"),
    mcq("Which is a source of sound?", ["A ringing bell", "A shadow", "A mirror", "A rainbow"], 0,
        "A bell vibrates when struck, making sound waves.",
        "কোনটা শব্দের উৎস?", ["বাজতে থাকা ঘণ্টা", "ছায়া", "আয়না", "রংধনু"],
        "ঘণ্টায় আঘাত করলে তা কাঁপে আর শব্দতরঙ্গ তৈরি হয়।"),
    mcq("Why do we hear a train coming before we see it around a bend?", ["Sound travels around corners and through the ground", "Light is slower", "Our eyes are closed", "Trains are invisible"], 0,
        "Sound spreads around obstacles and even travels along the rails. Light goes in straight lines.",
        "বাঁকের ওপাশে ট্রেন দেখার আগে শব্দ শুনি কেন?", ["শব্দ কোণ ঘুরে আর মাটি দিয়ে চলে", "আলো ধীর", "আমাদের চোখ বন্ধ", "ট্রেন অদৃশ্য"],
        "শব্দ বাধা ঘুরে ছড়িয়ে পড়ে, এমনকি রেললাইন বরাবরও চলে। আলো সোজা পথে চলে।"),
    mcq("Which is the best insulator to keep ice from melting in a lunch box?", ["A foam (polystyrene) box", "A thin metal tin", "An open plate", "A wet cloth in the sun"], 0,
        "Foam is full of trapped air, which slows heat from getting in.",
        "টিফিন বাক্সে বরফ গলা ঠেকাতে সবচেয়ে ভালো অন্তরক কোনটা?", ["ফোমের (থার্মোকল) বাক্স", "পাতলা ধাতুর টিন", "খোলা থালা", "রোদে ভেজা কাপড়"],
        "ফোমে বাতাস আটকানো থাকে, যা তাপকে ঢুকতে ধীর করে।"),
    mcq("A toy boat is pushed by wind on its sail. Which way does it go?", ["The way the wind blows", "Against the wind always", "Straight down", "Up into the air"], 0,
        "The wind pushes the sail, so the boat moves along with the wind.",
        "খেলনা নৌকার পালে বাতাস ঠেলছে। নৌকা কোন দিকে যাবে?", ["যেদিকে বাতাস বইছে", "সবসময় বাতাসের উল্টো দিকে", "সোজা নিচে", "উপরে বাতাসে"],
        "বাতাস পালকে ঠেলে, তাই নৌকা বাতাসের সঙ্গে চলে।"),
    mcq("Why do tall bridge towers often get thicker at the bottom?", ["The bottom carries the weight of everything above", "To look like a tree", "Thick bottoms are cheaper", "Wind blows only at the top"], 0,
        "Each part of a tower holds up everything above it, so the bottom carries the most.",
        "উঁচু সেতুর টাওয়ার প্রায়ই নিচে মোটা হয় কেন?", ["নিচের অংশ উপরের সবকিছুর ওজন বয়", "গাছের মতো দেখাতে", "মোটা তলা সস্তা", "বাতাস শুধু উপরে বয়"],
        "টাওয়ারের প্রতিটি অংশ তার উপরের সবকিছু ধরে রাখে, তাই নিচের অংশ সবচেয়ে বেশি বয়।"),
    mcq("You push a swing gently many times at the right moment. The swing goes...", ["Higher and higher", "Lower and lower", "Sideways", "It stops"], 0,
        "Small pushes in time with the swing add up. This is resonance - great for swings, dangerous for bridges in wind!",
        "ঠিক সময়ে বহুবার আস্তে দোলনা ঠেললে দোলনা যায়...", ["আরও উঁচুতে", "আরও নিচুতে", "পাশে", "থেমে যায়"],
        "দোলার তালে ছোট ছোট ঠেলা যোগ হয়। এটাই অনুনাদ - দোলনার জন্য দারুণ, বাতাসে সেতুর জন্য বিপজ্জনক!"),
    mcq("Soldiers marching in step are told to break step on a bridge. Why?", ["Marching in step can shake the bridge in rhythm", "Bridges dislike music", "To walk faster", "To save shoes"], 0,
        "Many feet stamping in rhythm could match the bridge's natural swing and build up big wobbles.",
        "সৈন্যদের তালে তালে মার্চ করতে করতে সেতুতে উঠলে তাল ভাঙতে বলা হয়। কেন?", ["তালে তালে মার্চ সেতুকে তালে কাঁপাতে পারে", "সেতু গান অপছন্দ করে", "দ্রুত হাঁটতে", "জুতো বাঁচাতে"],
        "অনেক পায়ের তালে তালে আঘাত সেতুর স্বাভাবিক দোলার সঙ্গে মিলে বড় কাঁপুনি তৈরি করতে পারে।"),
    mcq("What makes a hot-air balloon rise?", ["Hot air inside is lighter than the cooler air outside", "A rope pulls it", "Birds lift it", "It is filled with water"], 0,
        "Heating air makes it spread out and become lighter, so the balloon floats up.",
        "গরম-বাতাসের বেলুন উপরে ওঠে কীসে?", ["ভেতরের গরম বাতাস বাইরের ঠান্ডা বাতাসের চেয়ে হালকা", "দড়ি টানে", "পাখিরা তোলে", "জলে ভরা"],
        "বাতাস গরম করলে ছড়িয়ে হালকা হয়, তাই বেলুন ভেসে ওঠে।"),
    mcq("Two equal weights hang on a balance, one on each side, at the same distance. The balance...", ["Stays level", "Tips left", "Tips right", "Spins"], 0,
        "Equal weights at equal distances balance exactly.",
        "একটা দাঁড়িপাল্লার দুই পাশে সমান দূরত্বে দুটি সমান ওজন ঝোলানো। পাল্লা...", ["সমান থাকে", "বাঁয়ে হেলে", "ডানে হেলে", "ঘোরে"],
        "সমান দূরত্বে সমান ওজন একদম ভারসাম্য রাখে।"),
    mcq("Which object has the most friction when you slide it on the floor?", ["A rubber mat", "An ice cube", "A plastic tray", "A glass marble"], 0,
        "Rubber grips the floor strongly. Ice is slippery; trays and marbles slide or roll easily.",
        "মেঝেতে ঘষে সরালে কোন জিনিসে সবচেয়ে বেশি ঘর্ষণ?", ["রাবারের মাদুর", "বরফের টুকরো", "প্লাস্টিকের ট্রে", "কাচের মার্বেল"],
        "রাবার মেঝে জোরে আঁকড়ে ধরে। বরফ পিছল; ট্রে আর মার্বেল সহজে পিছলায় বা গড়ায়।"),
    mcq("Why do we oil a squeaky door hinge?", ["Oil reduces friction so it moves smoothly and quietly", "Oil makes it heavier", "Oil glues it shut", "Oil makes it squeak louder"], 0,
        "Oil makes surfaces slippery, cutting friction - and the squeak.",
        "কবজা ক্যাঁচক্যাঁচ করলে তেল দিই কেন?", ["তেল ঘর্ষণ কমায়, তাই মসৃণ আর নিঃশব্দে নড়ে", "তেল ভারী করে", "তেল আঠার মতো আটকে দেয়", "তেল আওয়াজ বাড়ায়"],
        "তেল তলকে পিছল করে ঘর্ষণ কমায় - আর ক্যাঁচক্যাঁচও।"),
    mcq("A car's brakes get hot after a long downhill drive. Why?", ["Friction turns the car's motion into heat", "The sun heats them", "The engine pushes heat there", "Brakes are always hot"], 0,
        "Brakes rub to slow the car, turning moving energy into heat. Long hills make lots of heat.",
        "লম্বা উৎরাই নামার পর গাড়ির ব্রেক গরম হয়ে যায়। কেন?", ["ঘর্ষণ গাড়ির গতিকে তাপে বদলায়", "সূর্য গরম করে", "ইঞ্জিন সেখানে তাপ ঠেলে দেয়", "ব্রেক সবসময় গরম"],
        "ব্রেক ঘষে গাড়ি ধীর করে, চলার শক্তিকে তাপে বদলায়। লম্বা উৎরাইয়ে অনেক তাপ হয়।"),
    mcq("Which wheel would roll farthest after one push on a smooth floor?", ["A smooth, round, heavy wheel", "A square wheel", "A wheel with a flat side", "A wheel stuck in glue"], 0,
        "A smooth round wheel loses little energy to bumps and friction, so it rolls far.",
        "মসৃণ মেঝেতে একবার ঠেলায় কোন চাকা সবচেয়ে দূরে গড়াবে?", ["মসৃণ, গোল, ভারী চাকা", "বর্গাকার চাকা", "এক পাশ চ্যাপ্টা চাকা", "আঠায় আটকানো চাকা"],
        "মসৃণ গোল চাকা ঝাঁকুনি আর ঘর্ষণে কম শক্তি হারায়, তাই দূরে গড়ায়।"),
    mcq("A clock pendulum swings back and forth. A longer pendulum swings...", ["More slowly", "Faster", "Not at all", "In circles"], 0,
        "Longer pendulums take more time for each swing. Bridges also have a 'swing time' that depends on their size and stiffness.",
        "ঘড়ির দোলক এদিক-ওদিক দোলে। লম্বা দোলক দোলে...", ["আরও ধীরে", "আরও দ্রুত", "একদম না", "বৃত্তে"],
        "লম্বা দোলকের প্রতিটি দোলায় বেশি সময় লাগে। সেতুরও একটা 'দোলার সময়' আছে, যা তার আকার আর দৃঢ়তার উপর নির্ভর করে।"),
    mcq("Which helps a heavy truck stop on a wet road?", ["Driving slowly and braking early", "Driving faster", "Turning off the lights", "Honking loudly"], 0,
        "Wet roads have less grip, so stopping takes longer. Slow down and brake earlier.",
        "ভেজা রাস্তায় ভারী ট্রাক থামাতে কী সাহায্য করে?", ["ধীরে চালানো আর আগে ব্রেক করা", "আরও জোরে চালানো", "বাতি নিভিয়ে দেওয়া", "জোরে হর্ন দেওয়া"],
        "ভেজা রাস্তায় আঁকড়ে ধরা কম, তাই থামতে বেশি সময় লাগে। গতি কমাও আর আগে ব্রেক করো।"),
    mcq("Which bridge would be best to cross a very long, wide river?", ["A suspension bridge with tall towers and cables", "A single short plank", "A rope for climbing", "A stepping-stone path"], 0,
        "Suspension bridges can span the longest gaps - over 1 kilometre between towers!",
        "খুব লম্বা, চওড়া নদী পার হতে কোন সেতু সবচেয়ে ভালো?", ["উঁচু টাওয়ার আর তারসহ ঝুলন্ত সেতু", "একটা ছোট তক্তা", "চড়ার জন্য একটা দড়ি", "ধাপে ধাপে পাথরের পথ"],
        "ঝুলন্ত সেতু সবচেয়ে লম্বা ফাঁক পেরোতে পারে - টাওয়ারের মাঝে 1 কিলোমিটারেরও বেশি!"),
    mcq("A beam bridge is simply...", ["A straight beam resting on supports at each end", "A curved arch", "A tunnel", "A ferry boat"], 0,
        "The simplest bridge: a beam across a gap, like a log over a stream.",
        "বিম সেতু হলো শুধু...", ["দুই প্রান্তে সাপোর্টের উপর রাখা একটা সোজা বিম", "একটা বাঁকা খিলান", "একটা সুড়ঙ্গ", "একটা ফেরি নৌকা"],
        "সবচেয়ে সহজ সেতু: ফাঁকের উপর একটা বিম, যেমন নালার উপর একটা গুঁড়ি।"),
    mcq("A truss bridge is strong because it is made of...", ["Many triangles", "Many circles", "Wet paper", "Loose string"], 0,
        "Triangles cannot change shape, so a truss of triangles is strong and light - like the bridges you build in MODIS BridgeWorks.",
        "ট্রাস সেতু মজবুত কারণ এটা তৈরি...", ["অনেক ত্রিভুজ দিয়ে", "অনেক বৃত্ত দিয়ে", "ভেজা কাগজ দিয়ে", "আলগা সুতো দিয়ে"],
        "ত্রিভুজ আকার বদলাতে পারে না, তাই ত্রিভুজের ট্রাস মজবুত আর হালকা - যেমন MODIS BridgeWorks-এ তুমি বানাও।"),
    mcq("Why do we see lightning as a straight-ish bright line from far away?", ["Light travels in straight lines to our eyes", "Lightning bends towards us", "It is painted", "Our eyes make it"], 0,
        "Light from the flash travels straight to us, so we see where it happened instantly.",
        "দূর থেকে বিদ্যুৎ চমক প্রায় সোজা উজ্জ্বল রেখার মতো দেখি কেন?", ["আলো সোজা পথে আমাদের চোখে আসে", "বিদ্যুৎ আমাদের দিকে বাঁকে", "রং করা", "আমাদের চোখ বানায়"],
        "ঝলকের আলো সোজা আমাদের কাছে আসে, তাই কোথায় হয়েছে সঙ্গে সঙ্গে দেখি।"),
    mcq("You count 3 seconds between lightning and thunder. Is the storm near or far?", ["About 1 kilometre away", "Right above you", "On the moon", "It is not a storm"], 0,
        "Sound travels about 1 kilometre in 3 seconds. Count the seconds to measure the distance!",
        "বিদ্যুৎ চমক আর বাজের মাঝে 3 সেকেন্ড গুনলে। ঝড় কাছে নাকি দূরে?", ["প্রায় 1 কিলোমিটার দূরে", "ঠিক মাথার উপরে", "চাঁদে", "এটা ঝড় নয়"],
        "শব্দ 3 সেকেন্ডে প্রায় 1 কিলোমিটার যায়। সেকেন্ড গুনে দূরত্ব মাপো!"),
    mcq("A kite string is pulled tight by the wind. If the string breaks, the kite...", ["Is blown away by the wind", "Flies higher on the spot", "Falls straight up", "Stops in the air"], 0,
        "The string held the kite against the wind. Without it, the wind carries the kite away.",
        "বাতাসে ঘুড়ির সুতো টানটান। সুতো ছিঁড়ে গেলে ঘুড়ি...", ["বাতাসে উড়ে চলে যায়", "একই জায়গায় আরও উঁচুতে ওড়ে", "সোজা উপরে পড়ে", "বাতাসে থেমে থাকে"],
        "সুতো ঘুড়িকে বাতাসের বিরুদ্ধে ধরে রেখেছিল। সুতো ছাড়া বাতাস ঘুড়িকে উড়িয়ে নিয়ে যায়।"),
    mcq("Which is the right unit to measure the length of a bridge?", ["Metres", "Kilograms", "Litres", "Seconds"], 0,
        "Length is measured in metres (or kilometres for very long bridges).",
        "সেতুর দৈর্ঘ্য মাপার সঠিক একক কোনটা?", ["মিটার", "কিলোগ্রাম", "লিটার", "সেকেন্ড"],
        "দৈর্ঘ্য মাপা হয় মিটারে (খুব লম্বা সেতুর জন্য কিলোমিটারে)।"),
    mcq("Which unit measures how heavy a truck is?", ["Tonnes (or kilograms)", "Metres", "Litres", "Hours"], 0,
        "1 tonne = 1000 kilograms. Bridge signs show weight limits in tonnes.",
        "ট্রাক কতটা ভারী তা কোন এককে মাপা হয়?", ["টন (বা কিলোগ্রাম)", "মিটার", "লিটার", "ঘণ্টা"],
        "1 টন = 1000 কিলোগ্রাম। সেতুর বোর্ডে ওজনসীমা টনে লেখা থাকে।"),
    mcq("A thick wall of snow keeps an igloo warm inside. Why?", ["Snow is full of trapped air, a good insulator", "Snow is hot", "Snow makes fire", "Igloos have heaters inside the walls"], 0,
        "Packed snow traps air, which slows heat escaping - surprising but true!",
        "বরফের মোটা দেয়াল ইগলুর ভেতর গরম রাখে। কেন?", ["বরফে বাতাস আটকানো থাকে, যা ভালো অন্তরক", "বরফ গরম", "বরফ আগুন বানায়", "ইগলুর দেয়ালে হিটার থাকে"],
        "ঠাসা বরফ বাতাস আটকে রাখে, যা তাপ বেরোনো ধীর করে - অবাক হলেও সত্যি!"),
    mcq("What is 'gravity' pulling you towards when you stand on the ground?", ["The centre of the Earth", "The sun only", "The sky", "The nearest wall"], 0,
        "Earth's gravity pulls everything towards its centre - that is 'down' everywhere on the planet.",
        "মাটিতে দাঁড়ালে মাধ্যাকর্ষণ তোমাকে কোন দিকে টানে?", ["পৃথিবীর কেন্দ্রের দিকে", "শুধু সূর্যের দিকে", "আকাশের দিকে", "কাছের দেয়ালের দিকে"],
        "পৃথিবীর মাধ্যাকর্ষণ সবকিছুকে কেন্দ্রের দিকে টানে - পৃথিবীর সব জায়গায় সেটাই 'নিচে'।"),
    mcq("Astronauts on the Moon can jump very high. Why?", ["The Moon's gravity is much weaker than Earth's", "They have springs in their shoes", "There is wind on the Moon", "They are very light people"], 0,
        "The Moon pulls about 6 times less than the Earth, so a jump goes much higher.",
        "চাঁদে নভোচারীরা অনেক উঁচুতে লাফাতে পারেন। কেন?", ["চাঁদের মাধ্যাকর্ষণ পৃথিবীর চেয়ে অনেক কম", "জুতোয় স্প্রিং আছে", "চাঁদে বাতাস আছে", "তাঁরা খুব হালকা মানুষ"],
        "চাঁদ পৃথিবীর চেয়ে প্রায় 6 গুণ কম টানে, তাই লাফ অনেক উঁচুতে যায়।"),
    mcq("A loaded truck makes a wooden bridge sag in the middle. What would reduce the sag?", ["Add a support (pillar) in the middle", "Make the truck faster", "Paint the bridge", "Remove one side support"], 0,
        "A middle support halves the span, and shorter spans bend far less.",
        "ভরা ট্রাকে কাঠের সেতুর মাঝখান ঝুলে পড়ে। কী করলে ঝোলা কমবে?", ["মাঝখানে একটা স্তম্ভ দেওয়া", "ট্রাককে দ্রুত চালানো", "সেতু রং করা", "এক পাশের সাপোর্ট সরানো"],
        "মাঝখানের সাপোর্ট স্প্যান অর্ধেক করে, আর ছোট স্প্যান অনেক কম বাঁকে।"),
    mcq("Which simple machine helps lift a car to change a tyre?", ["A jack (a screw or lever)", "A mirror", "A drum", "A pencil"], 0,
        "A car jack uses a screw or lever so a small push lifts a heavy car slowly.",
        "টায়ার বদলাতে গাড়ি তুলতে কোন সরল যন্ত্র সাহায্য করে?", ["জ্যাক (স্ক্রু বা লিভার)", "আয়না", "ঢোল", "পেনসিল"],
        "গাড়ির জ্যাক স্ক্রু বা লিভার ব্যবহার করে, তাই অল্প ঠেলায় ভারী গাড়ি ধীরে ওঠে।"),
    mcq("Why does a basketball bounce higher than a ball of clay?", ["The basketball is springy and gives back the energy", "Clay is lighter", "Basketballs are hotter", "Clay is magnetic"], 0,
        "The basketball squashes and springs back. Clay squashes and stays squashed, keeping the energy as heat.",
        "বাস্কেটবল মাটির বলের চেয়ে বেশি লাফায় কেন?", ["বাস্কেটবল স্থিতিস্থাপক আর শক্তি ফিরিয়ে দেয়", "মাটি হালকা", "বাস্কেটবল বেশি গরম", "মাটি চুম্বক"],
        "বাস্কেটবল চেপে আবার ফিরে আসে। মাটির বল চেপে চাপাই থাকে, শক্তি তাপ হয়ে যায়।"),
    mcq("Which sound is higher pitched?", ["A bird's tweet", "A lion's roar", "A big drum", "Thunder"], 0,
        "Small fast vibrations make high sounds, like a bird's tweet.",
        "কোন শব্দের তীক্ষ্ণতা বেশি (উঁচু সুর)?", ["পাখির কিচিরমিচির", "সিংহের গর্জন", "বড় ঢোল", "বাজ"],
        "ছোট দ্রুত কম্পনে উঁচু শব্দ হয়, যেমন পাখির ডাক।"),
    mcq("Water in a hose shoots out further when you squeeze the end. Why?", ["The same water must rush out through a smaller hole, faster", "Squeezing adds water", "The hose gets longer", "Gravity stops"], 0,
        "A smaller opening makes the water speed up - a lesson in pressure and flow.",
        "পাইপের মুখ চেপে ধরলে জল আরও দূরে ছিটকে যায়। কেন?", ["একই জল ছোট ছিদ্র দিয়ে আরও দ্রুত বেরোয়", "চাপলে জল বাড়ে", "পাইপ লম্বা হয়", "মাধ্যাকর্ষণ থেমে যায়"],
        "ছোট মুখে জলের গতি বাড়ে - চাপ আর প্রবাহের একটা শিক্ষা।"),
    mcq("The water at the bottom of a deep tank pushes harder than at the top. Why?", ["All the water above presses down on it", "Bottom water is hotter", "Fish push it", "It does not"], 0,
        "Deeper water carries the weight of all the water above. That is why dams are thicker at the bottom.",
        "গভীর ট্যাংকের তলার জল উপরের চেয়ে বেশি জোরে ঠেলে। কেন?", ["উপরের সব জল তাকে নিচে চাপে", "তলার জল বেশি গরম", "মাছ ঠেলে", "ঠেলে না"],
        "গভীর জল উপরের সব জলের ওজন বয়। এজন্যই বাঁধ নিচে মোটা হয়।"),
    mcq("Which travels through space from the Sun to Earth?", ["Light and heat", "Sound", "Wind", "Rain"], 0,
        "Light and heat cross empty space. Sound needs air or something to travel through.",
        "কোনটা মহাকাশ পেরিয়ে সূর্য থেকে পৃথিবীতে আসে?", ["আলো আর তাপ", "শব্দ", "বাতাস", "বৃষ্টি"],
        "আলো আর তাপ শূন্য মহাকাশ পেরোয়। শব্দের চলার জন্য বাতাস বা কিছু লাগে।"),
    mcq("A swing hangs from two chains. Each chain is...", ["Pulled tight (in tension)", "Squeezed", "Melted", "Floating"], 0,
        "The seat's weight pulls on the chains - like hangers on a suspension bridge.",
        "একটা দোলনা দুটি শিকল থেকে ঝোলে। প্রতিটি শিকল...", ["টানটান (টানে)", "চাপা খাচ্ছে", "গলে গেছে", "ভাসছে"],
        "আসনের ওজন শিকলগুলোকে টানে - ঝুলন্ত সেতুর ঝোলানো তারের মতো।"),
    mcq("What helps a sailing ship move without an engine?", ["Wind pushing the sails", "Fish pulling it", "Gravity pulling forward", "Magnets"], 0,
        "Sails catch the wind's push. For centuries, ships crossed oceans this way.",
        "ইঞ্জিন ছাড়া পালতোলা জাহাজ চলে কীসে?", ["বাতাস পাল ঠেলে", "মাছ টানে", "মাধ্যাকর্ষণ সামনে টানে", "চুম্বক"],
        "পাল বাতাসের ঠেলা ধরে। শতাব্দী ধরে জাহাজ এভাবেই সমুদ্র পেরিয়েছে।"),
    mcq("Why is a bridge deck often made slightly curved upwards in the middle?", ["So it does not look or become saggy when loaded", "To make cars jump", "For skateboarding", "It is a mistake"], 0,
        "Builders add a small upward curve (camber) so that under weight the deck ends up nearly flat - and rain runs off.",
        "সেতুর ডেক প্রায়ই মাঝখানে একটু উপরের দিকে বাঁকানো হয় কেন?", ["যাতে ভার পড়লে ঝুলে পড়া না দেখায় বা না হয়", "গাড়ি লাফাতে", "স্কেটবোর্ডের জন্য", "এটা একটা ভুল"],
        "নির্মাতারা সামান্য উপরের দিকে বাঁক (ক্যাম্বার) দেন, যাতে ভারে ডেক প্রায় সমতল হয় - আর বৃষ্টির জল গড়িয়ে যায়।"),
    mcq("Which is a non-contact force (it works without touching)?", ["Magnetism", "A kick", "A push with your hand", "Friction"], 0,
        "Magnets pull iron from a distance. Gravity is another non-contact force.",
        "কোনটা স্পর্শহীন বল (না ছুঁয়েই কাজ করে)?", ["চুম্বকত্ব", "লাথি", "হাত দিয়ে ঠেলা", "ঘর্ষণ"],
        "চুম্বক দূর থেকে লোহা টানে। মাধ্যাকর্ষণও একটা স্পর্শহীন বল।"),
    mcq("Two magnets pull together when...", ["Opposite poles (north and south) face each other", "The same poles face each other", "They are made of wood", "They are wet"], 0,
        "North pulls south. North pushes north, and south pushes south.",
        "দুটি চুম্বক কাছে টানে যখন...", ["উল্টো মেরু (উত্তর আর দক্ষিণ) মুখোমুখি", "একই মেরু মুখোমুখি", "কাঠের তৈরি", "ভেজা"],
        "উত্তর দক্ষিণকে টানে। উত্তর উত্তরকে ঠেলে, দক্ষিণ দক্ষিণকে ঠেলে।"),
    mcq("Why do roads have gentle curves instead of sharp corners on fast highways?", ["Fast cars need gentle turns to stay on the road", "To make roads longer for fun", "Sharp corners are expensive paint", "No reason"], 0,
        "Turning sharply at high speed needs a huge sideways grip. Gentle curves keep cars safe.",
        "দ্রুতগতির মহাসড়কে তীক্ষ্ণ বাঁকের বদলে মৃদু বাঁক থাকে কেন?", ["দ্রুত গাড়ির রাস্তায় থাকতে মৃদু বাঁক লাগে", "মজা করে রাস্তা লম্বা করতে", "তীক্ষ্ণ কোণে দামি রং লাগে", "কোনো কারণ নেই"],
        "দ্রুতগতিতে তীক্ষ্ণ বাঁক নিতে পাশের দিকে বিশাল আঁকড়ে ধরা লাগে। মৃদু বাঁক গাড়িকে নিরাপদ রাখে।"),
    mcq("A heavier bucket on a pulley needs...", ["A bigger pull on the rope", "A smaller pull", "No pull", "A push from above"], 0,
        "A heavier load needs more force. Using two pulleys can share the load and halve the pull.",
        "কপিকলে ভারী বালতি তুলতে লাগে...", ["দড়িতে বেশি টান", "কম টান", "কোনো টান না", "উপর থেকে ঠেলা"],
        "ভারী ভারে বেশি বল লাগে। দুটি কপিকল ব্যবহার করলে ভার ভাগ হয়ে টান অর্ধেক হতে পারে।"),
    mcq("What is the job of a bridge's foundation?", ["To pass the bridge's weight safely into the ground", "To hold flags", "To store water", "To make the bridge shiny"], 0,
        "Foundations spread the huge weight of a bridge into firm ground or rock so it does not sink.",
        "সেতুর ভিতের কাজ কী?", ["সেতুর ওজন নিরাপদে মাটিতে পৌঁছে দেওয়া", "পতাকা ধরা", "জল জমানো", "সেতু চকচকে করা"],
        "ভিত সেতুর বিশাল ওজন শক্ত মাটি বা পাথরে ছড়িয়ে দেয়, যাতে সেতু বসে না যায়।"),
    mcq("Which is the best way to keep a tent from blowing away?", ["Tie it to pegs with tight ropes", "Leave it loose", "Put it on ice", "Fill it with balloons"], 0,
        "Tight guy ropes pull the tent down and sideways against the wind - the same idea as bridge stay cables.",
        "তাঁবু উড়ে যাওয়া ঠেকানোর সবচেয়ে ভালো উপায় কোনটা?", ["টানটান দড়িতে খুঁটির সঙ্গে বাঁধা", "আলগা রেখে দেওয়া", "বরফের উপর রাখা", "বেলুনে ভরা"],
        "টানটান দড়ি বাতাসের বিরুদ্ধে তাঁবুকে নিচে আর পাশে টানে - সেতুর ঠেকনা-তারেরও একই ধারণা।"),
    mcq("You blow over the top of a strip of paper. The paper...", ["Rises up", "Falls down", "Catches fire", "Gets wet"], 0,
        "Fast-moving air over the paper has lower pressure, so the paper lifts - like a plane's wing.",
        "একটা কাগজের ফালির উপর দিয়ে ফুঁ দিলে কাগজটা...", ["উপরে ওঠে", "নিচে পড়ে", "আগুন ধরে", "ভিজে যায়"],
        "কাগজের উপরে দ্রুত চলা বাতাসের চাপ কম, তাই কাগজ ওঠে - উড়োজাহাজের ডানার মতো।"),
    mcq("A hammer pulls out a nail using its claw. The hammer is acting as a...", ["Lever", "Wheel", "Wedge only", "Spring"], 0,
        "The hammer turns about its head on the wood: a small pull on the long handle gives a big pull on the nail.",
        "হাতুড়ি তার নখর দিয়ে পেরেক টেনে তোলে। হাতুড়ি তখন কাজ করছে...", ["লিভার হিসেবে", "চাকা হিসেবে", "শুধু গোঁজ হিসেবে", "স্প্রিং হিসেবে"],
        "হাতুড়ি কাঠের উপর মাথাকে ঘিরে ঘোরে: লম্বা হাতলে অল্প টান পেরেকে বড় টান দেয়।"),
    mcq("Why do cyclists bend low on fast downhill rides?", ["To push through less air", "To look at the road better", "To rest their legs", "Because the handle is low"], 0,
        "Bending low makes a smaller shape, so the air pushes back less (less drag).",
        "দ্রুত উৎরাই নামার সময় সাইকেল-চালকরা নিচু হয়ে ঝোঁকেন কেন?", ["কম বাতাস ঠেলে এগোতে", "রাস্তা ভালো দেখতে", "পা বিশ্রাম দিতে", "কারণ হাতল নিচু"],
        "নিচু হলে আকার ছোট হয়, তাই বাতাস কম উল্টো ঠেলে (কম টান)।"),
    mcq("Which bridge would likely sway most in a strong wind?", ["A long, light, narrow footbridge", "A short, heavy, wide bridge", "A tunnel", "A bridge buried underground"], 0,
        "Long, light and narrow structures are easier for the wind to shake. Engineers add stiffness or dampers.",
        "জোরালো বাতাসে কোন সেতু সবচেয়ে বেশি দুলতে পারে?", ["লম্বা, হালকা, সরু হাঁটার সেতু", "ছোট, ভারী, চওড়া সেতু", "একটা সুড়ঙ্গ", "মাটির নিচে পোঁতা সেতু"],
        "লম্বা, হালকা আর সরু কাঠামো বাতাসে সহজে কাঁপে। প্রকৌশলীরা দৃঢ়তা বা ড্যাম্পার যোগ করেন।"),
    mcq("What happens to the height of a ball's bounce each time it bounces?", ["It gets lower each time", "It gets higher", "It stays exactly the same forever", "It bounces sideways"], 0,
        "Each bounce loses a little energy to heat and sound, so the ball bounces lower and lower.",
        "প্রতিবার লাফানোর সময় বলের লাফের উচ্চতার কী হয়?", ["প্রতিবার কমে", "বাড়ে", "চিরকাল একদম একই থাকে", "পাশে লাফায়"],
        "প্রতিটি লাফে একটু শক্তি তাপ আর শব্দে হারায়, তাই বল ক্রমশ কম উঁচুতে লাফায়।"),
    mcq("Which is a contact force?", ["Friction", "Gravity", "Magnetism", "Static electricity from a distance"], 0,
        "Friction only works where two surfaces touch.",
        "কোনটা স্পর্শ-বল?", ["ঘর্ষণ", "মাধ্যাকর্ষণ", "চুম্বকত্ব", "দূর থেকে স্থির তড়িৎ"],
        "ঘর্ষণ শুধু যেখানে দুটি তল ছোঁয় সেখানে কাজ করে।"),
    mcq("You rub a balloon on your hair and it sticks to the wall. What caused this?", ["Static electricity", "Glue", "Water", "Magnetism"], 0,
        "Rubbing moves tiny charges onto the balloon, and charged things can stick to walls.",
        "চুলে বেলুন ঘষলে তা দেয়ালে আটকে যায়। কী এর কারণ?", ["স্থির তড়িৎ", "আঠা", "জল", "চুম্বকত্ব"],
        "ঘষলে ছোট ছোট আধান বেলুনে চলে আসে, আর আধানযুক্ত জিনিস দেয়ালে আটকে থাকতে পারে।"),
    mcq("A roller coaster car speeds up going down a slope and slows going up. Why?", ["Gravity speeds it downhill and slows it uphill", "The driver presses a pedal", "Wind pushes it", "The rails are magnetic"], 0,
        "Going down, height turns into speed; going up, speed turns back into height.",
        "রোলার কোস্টারের গাড়ি ঢাল বেয়ে নামতে গতি বাড়ায় আর উঠতে ধীর হয়। কেন?", ["মাধ্যাকর্ষণ নামার সময় গতি বাড়ায় আর ওঠার সময় কমায়", "চালক প্যাডেল চাপেন", "বাতাস ঠেলে", "লাইন চুম্বক"],
        "নামার সময় উচ্চতা গতিতে বদলায়; ওঠার সময় গতি আবার উচ্চতায় বদলায়।"),
    mcq("Why are tyres filled with air?", ["Air is springy and cushions bumps", "Air makes tyres heavy", "Air is a fuel", "To make them float"], 0,
        "Squashed air pushes back like a spring, giving a smoother ride and gripping the road.",
        "টায়ারে বাতাস ভরা হয় কেন?", ["বাতাস স্প্রিংয়ের মতো ঝাঁকুনি সামলায়", "বাতাস টায়ার ভারী করে", "বাতাস জ্বালানি", "ভাসাতে"],
        "চাপা বাতাস স্প্রিংয়ের মতো উল্টো ঠেলে, তাতে চলা মসৃণ হয় আর রাস্তা আঁকড়ে থাকে।"),
    mcq("A crane lifts steel beams to the top of a bridge. Which simple machines does it use?", ["Pulleys and levers", "Mirrors", "Drums", "Rainbows"], 0,
        "Cranes use pulleys (ropes over wheels) and long arms (levers) to lift huge weights.",
        "একটা ক্রেন ইস্পাতের বিম সেতুর উপরে তোলে। কোন সরল যন্ত্র ব্যবহার করে?", ["কপিকল আর লিভার", "আয়না", "ঢোল", "রংধনু"],
        "ক্রেন বিশাল ওজন তুলতে কপিকল (চাকার উপর দড়ি) আর লম্বা বাহু (লিভার) ব্যবহার করে।"),
    mcq("Which is NOT a simple machine?", ["A computer", "A lever", "A pulley", "A wedge"], 0,
        "The six simple machines are lever, wheel and axle, pulley, inclined plane, wedge and screw.",
        "কোনটা সরল যন্ত্র নয়?", ["কম্পিউটার", "লিভার", "কপিকল", "গোঁজ"],
        "ছয়টি সরল যন্ত্র: লিভার, চাকা ও অক্ষদণ্ড, কপিকল, আনত তল, গোঁজ আর স্ক্রু।"),
    mcq("A bridge in a cold country has a small gap where it meets the road. What is it for?", ["To let the bridge grow and shrink with heat and cold", "To let rain fall through for fun", "To trap cars", "It is a crack"], 0,
        "Bridges expand on hot days and shrink on cold days. Expansion joints give them room.",
        "ঠান্ডা দেশের একটা সেতু যেখানে রাস্তার সঙ্গে মেলে সেখানে ছোট ফাঁক। এটা কীসের জন্য?", ["গরম-ঠান্ডায় সেতুর বাড়া-কমার জায়গা দিতে", "মজা করে বৃষ্টি পড়তে দিতে", "গাড়ি আটকাতে", "এটা একটা ফাটল"],
        "সেতু গরমে প্রসারিত আর ঠান্ডায় সংকুচিত হয়। সম্প্রসারণ-জোড় সেই জায়গা দেয়।"),
    mcq("If you push a toy car twice as hard, it usually goes...", ["Faster and further", "Slower", "Backwards", "Nowhere"], 0,
        "A bigger force gives a bigger speed-up.",
        "খেলনা গাড়িকে দ্বিগুণ জোরে ঠেললে সাধারণত যায়...", ["আরও দ্রুত আর দূরে", "আরও ধীরে", "পেছনে", "কোথাও না"],
        "বড় বলে বেশি গতি বাড়ে।"),
    mcq("Why does a stone sink but a large log float?", ["The log is lighter for its size than water", "The stone is shy", "Logs are hollow always", "Water pulls stones down"], 0,
        "What matters is how heavy something is for its size (density). Wood is less dense than water; stone is denser.",
        "পাথর ডোবে কিন্তু বড় কাঠের গুঁড়ি ভাসে কেন?", ["গুঁড়ি তার আকারের তুলনায় জলের চেয়ে হালকা", "পাথর লাজুক", "গুঁড়ি সবসময় ফাঁপা", "জল পাথরকে নিচে টানে"],
        "আকারের তুলনায় জিনিস কতটা ভারী (ঘনত্ব) সেটাই আসল। কাঠের ঘনত্ব জলের চেয়ে কম; পাথরের বেশি।"),
    mcq("Which is the best tool to find which of two parcels is heavier?", ["A balance scale", "A ruler", "A thermometer", "A clock"], 0,
        "A balance tips towards the heavier side.",
        "দুটি পার্সেলের কোনটা বেশি ভারী জানতে সবচেয়ে ভালো যন্ত্র কোনটা?", ["দাঁড়িপাল্লা", "স্কেল (রুলার)", "থার্মোমিটার", "ঘড়ি"],
        "দাঁড়িপাল্লা ভারী দিকে হেলে পড়ে।"),
    mcq("A thermometer measures...", ["How hot or cold something is", "How long it is", "How heavy it is", "How fast it goes"], 0,
        "Temperature is measured in degrees Celsius with a thermometer.",
        "থার্মোমিটার মাপে...", ["কিছু কতটা গরম বা ঠান্ডা", "কতটা লম্বা", "কতটা ভারী", "কত দ্রুত চলে"],
        "থার্মোমিটার দিয়ে ডিগ্রি সেলসিয়াসে তাপমাত্রা মাপা হয়।"),
    mcq("Why do builders use cranes instead of carrying steel by hand?", ["Machines multiply force so huge loads can be lifted", "Hands are too clean", "Cranes are cheaper than gloves", "Steel is too light to carry"], 0,
        "Simple machines trade a long pull for a big lift - no one can lift a 10-tonne beam by hand!",
        "নির্মাতারা হাতে না বয়ে ক্রেনে ইস্পাত তোলেন কেন?", ["যন্ত্র বল বাড়িয়ে দেয়, তাই বিশাল ভার তোলা যায়", "হাত খুব পরিষ্কার", "ক্রেন দস্তানার চেয়ে সস্তা", "ইস্পাত বইতে খুব হালকা"],
        "সরল যন্ত্র লম্বা টানের বদলে বড় তোলা দেয় - 10 টনের বিম কেউ হাতে তুলতে পারে না!"),
)
