"""Class 2 - Math: numbers to 100, place value, adding and taking away, times tables,
sharing, fractions, shapes, measuring, time and money."""
from . import mcq


def _opts(r, near=(1, 10, -1)):
    """The right answer plus three different close wrong answers."""
    out = [r]
    for d in near + (2, -2, 3, 5, -10):
        if len(out) == 4:
            break
        w = r + d
        if w >= 0 and w not in out:
            out.append(w)
    return [str(o) for o in out]


def story(q_en, q_bn, r, ex_en, ex_bn, near=(1, 10, -1)):
    o = _opts(r, near)
    return mcq(q_en, o, 0, ex_en, q_bn, o, ex_bn)


def add(a, b, q_en, q_bn):
    return story(q_en.format(a=a, b=b), q_bn.format(a=a, b=b), a + b,
                 f"{a} + {b} = {a + b}. Add the tens, then the ones.",
                 f"{a} + {b} = {a + b}। আগে দশকগুলো, তারপর এককগুলো যোগ করো।")


def sub(a, b, q_en, q_bn):
    return story(q_en.format(a=a, b=b), q_bn.format(a=a, b=b), a - b,
                 f"{a} - {b} = {a - b}. Check: {a - b} + {b} = {a}.",
                 f"{a} - {b} = {a - b}। মিলিয়ে দেখো: {a - b} + {b} = {a}।")


def mul(a, b, q_en, q_bn):
    return story(q_en.format(a=a, b=b), q_bn.format(a=a, b=b), a * b,
                 f"{a} groups of {b}: {a} x {b} = {a * b}.",
                 f"{b} করে {a} দল: {a} x {b} = {a * b}।", near=(b, -b, 1))


def div(total, each, q_en, q_bn):
    return story(q_en.format(t=total, e=each), q_bn.format(t=total, e=each), total // each,
                 f"{total} ÷ {each} = {total // each}, because {total // each} x {each} = {total}.",
                 f"{total} ÷ {each} = {total // each}, কারণ {total // each} x {each} = {total}।", near=(1, -1, 2))


ITEMS = (
    add(23, 14, "A bridge crew lays {a} planks before lunch and {b} after. How many planks?",
        "একদল মিস্ত্রি দুপুরের আগে {a}টি আর পরে {b}টি তক্তা বসাল। মোট কয়টি তক্তা?"),
    add(35, 22, "{a} cars cross in the morning and {b} at night. How many cars?",
        "সকালে {a}টি গাড়ি আর রাতে {b}টি গাড়ি পার হলো। মোট কয়টি গাড়ি?"),
    add(41, 37, "A school has {a} boys and {b} girls in Class 2. How many children?",
        "একটা স্কুলের দ্বিতীয় শ্রেণিতে {a} জন ছেলে আর {b} জন মেয়ে। মোট কতজন শিশু?"),
    add(28, 15, "You read {a} pages on Monday and {b} on Tuesday. How many pages?",
        "সোমবার {a} পৃষ্ঠা আর মঙ্গলবার {b} পৃষ্ঠা পড়লে। মোট কত পৃষ্ঠা?"),
    add(46, 29, "A train carries {a} people in one coach and {b} in another. How many people?",
        "একটা ট্রেনের এক কামরায় {a} জন আর আরেকটায় {b} জন। মোট কতজন?"),
    add(57, 18, "A shop sells {a} mangoes and {b} oranges. How many fruits?",
        "একটা দোকানে {a}টি আম আর {b}টি কমলা বিক্রি হলো। মোট কয়টি ফল?"),
    add(64, 25, "A wall has {a} red bricks and {b} grey bricks. How many bricks?",
        "একটা দেয়ালে {a}টি লাল আর {b}টি ধূসর ইট। মোট কয়টি ইট?"),
    add(19, 19, "Two lorries each carry {a} bags of cement. How many bags?",
        "দুটি লরির প্রতিটিতে {a} বস্তা সিমেন্ট। মোট কত বস্তা?"),
    add(38, 45, "A farmer picks {a} kg of rice and then {b} kg more. How many kg?",
        "একজন চাষি {a} kg ধান তুলে তারপর আরও {b} kg তুললেন। মোট কত kg?"),
    add(52, 39, "{a} birds sit on a cable and {b} more join. How many birds?",
        "একটা তারে {a}টি পাখি বসে, আরও {b}টি এসে বসল। মোট কয়টি পাখি?"),
    sub(65, 23, "A bridge needs {a} bolts. {b} are already in. How many still to fit?",
        "একটা সেতুতে {a}টি বল্টু লাগবে। {b}টি লাগানো হয়ে গেছে। আর কয়টি লাগাতে হবে?"),
    sub(80, 35, "You have Rs {a} and spend Rs {b}. How much is left?",
        "তোমার কাছে {a} টাকা, খরচ করলে {b} টাকা। কত বাকি?"),
    sub(94, 41, "A road is {a} m long. {b} m is finished. How many metres are left?",
        "একটা রাস্তা {a} m লম্বা। {b} m শেষ হয়েছে। আর কত মিটার বাকি?"),
    sub(72, 28, "A tank holds {a} litres. {b} litres are used. How many litres remain?",
        "একটা ট্যাংকে {a} লিটার জল ধরে। {b} লিটার খরচ হলো। কত লিটার বাকি?"),
    sub(50, 17, "{a} cones line a bridge. Workers remove {b}. How many cones are left?",
        "সেতু বরাবর {a}টি কোন সাজানো। শ্রমিকরা {b}টি সরালেন। কয়টি রইল?"),
    sub(86, 59, "A crane can lift {a} tonnes. A beam weighs {b} tonnes. How many more tonnes could it lift?",
        "একটা ক্রেন {a} টন তুলতে পারে। একটা বিমের ওজন {b} টন। আর কত টন তুলতে পারত?"),
    sub(100, 45, "A bridge is 100 m long. A walker has gone {b} m. How far is left?",
        "একটা সেতু 100 m লম্বা। একজন পথচারী {b} m গেছেন। আর কত দূর বাকি?"),
    sub(61, 24, "There were {a} sweets in a jar. {b} were eaten. How many remain?",
        "একটা বয়ামে {a}টি লজেন্স ছিল। {b}টি খাওয়া হলো। কয়টি রইল?"),
    sub(43, 19, "A train had {a} passengers. {b} got off. How many are on the train now?",
        "একটা ট্রেনে {a} জন যাত্রী ছিল। {b} জন নামলেন। এখন ট্রেনে কতজন?"),
    sub(77, 38, "A builder had {a} tiles and used {b}. How many tiles are left?",
        "এক মিস্ত্রির {a}টি টালি ছিল, {b}টি ব্যবহার করলেন। কয়টি বাকি?"),
    mul(3, 5, "{a} trucks each carry {b} beams. How many beams?",
        "{a}টি ট্রাকের প্রতিটি {b}টি বিম বয়। মোট কয়টি বিম?"),
    mul(4, 10, "{a} boxes hold {b} nails each. How many nails?",
        "{a}টি বাক্সের প্রতিটিতে {b}টি পেরেক। মোট কয়টি পেরেক?"),
    mul(6, 5, "A bridge has {a} spans, each {b} m long. How long is the bridge?",
        "একটা সেতুর {a}টি স্প্যান, প্রতিটি {b} m লম্বা। সেতুটি কত লম্বা?"),
    mul(8, 10, "{a} bags each hold {b} kg of sand. How many kg?",
        "{a}টি বস্তার প্রতিটিতে {b} kg বালি। মোট কত kg?"),
    mul(9, 5, "{a} coins of Rs {b}. How many rupees?",
        "{b} টাকার {a}টি পয়সা। মোট কত টাকা?"),
    mul(3, 10, "A train has {a} wagons with {b} tonnes in each. How many tonnes?",
        "একটা ট্রেনে {a}টি ওয়াগন, প্রতিটিতে {b} টন। মোট কত টন?"),
    mul(4, 3, "A truss has {a} triangles. Each has {b} sides. How many sides if none are shared?",
        "একটা ট্রাসে {a}টি ত্রিভুজ। প্রতিটির {b}টি বাহু। কোনোটা ভাগ না হলে মোট কয়টি বাহু?"),
    mul(10, 10, "{a} buses each carry {b} children. How many children?",
        "{a}টি বাসের প্রতিটি {b} জন শিশু বয়। মোট কতজন শিশু?"),
    mul(7, 5, "{a} days of saving Rs {b}. How much is saved?",
        "{a} দিন ধরে {b} টাকা করে জমালে কত জমবে?"),
    div(20, 5, "{t} sweets shared equally by {e} friends. How many each?",
        "{t}টি লজেন্স {e} বন্ধুর মধ্যে সমান ভাগ করা হলো। প্রত্যেকে কয়টি?"),
    div(30, 10, "{t} bricks packed in stacks of {e}. How many stacks?",
        "{t}টি ইট {e}টি করে স্তূপে সাজানো। কয়টি স্তূপ?"),
    div(40, 5, "A {t} m bridge has a lamp every {e} m. How many lamp gaps?",
        "{t} m সেতুতে প্রতি {e} m-এ একটা বাতি। কয়টি বাতির ফাঁক?"),
    div(24, 4, "{t} wheels are shared among cars with {e} wheels each. How many cars?",
        "{t}টি চাকা {e}টি চাকাওয়ালা গাড়িগুলোতে ভাগ হলো। কয়টি গাড়ি?"),
    div(50, 10, "Rs {t} paid in Rs {e} notes. How many notes?",
        "{t} টাকা {e} টাকার নোটে দেওয়া হলো। কয়টি নোট?"),
    div(16, 4, "{t} children make teams of {e}. How many teams?",
        "{t} জন শিশু {e} জনের দল বানাল। কয়টি দল?"),
    div(35, 5, "A truck carries {e} tonnes per trip. How many trips for {t} tonnes?",
        "একটা ট্রাক প্রতি যাত্রায় {e} টন বয়। {t} টনের জন্য কয়টি যাত্রা?"),
    mcq("In 47, what is the value of the 4?", ["40", "4", "47", "400"], 0,
        "47 = 4 tens + 7 ones, so the 4 means 40.",
        "47-এ 4-এর মান কত?", ["40", "4", "47", "400"],
        "47 = 4টি দশ + 7টি এক, তাই 4 মানে 40।"),
    mcq("Which number is 6 tens and 3 ones?", ["63", "36", "9", "603"], 0,
        "6 tens = 60, plus 3 = 63.",
        "6টি দশ আর 3টি এক মিলে কোন সংখ্যা?", ["63", "36", "9", "603"],
        "6টি দশ = 60, সঙ্গে 3 = 63।"),
    mcq("Which is the greatest number?", ["91", "19", "89", "90"], 0,
        "91 has 9 tens and 1 one - more than 90, 89 and 19.",
        "কোনটা সবচেয়ে বড় সংখ্যা?", ["91", "19", "89", "90"],
        "91-এ 9টি দশ আর 1টি এক - 90, 89 আর 19-এর চেয়ে বেশি।"),
    mcq("Which sign makes this true: 58 __ 85?", ["<", ">", "=", "+"], 0,
        "58 is less than 85, so 58 < 85.",
        "কোন চিহ্ন বসালে এটা সত্যি হয়: 58 __ 85?", ["<", ">", "=", "+"],
        "58, 85-এর চেয়ে কম, তাই 58 < 85।"),
    mcq("Round 47 to the nearest ten.", ["50", "40", "45", "47"], 0,
        "47 is closer to 50 than to 40.",
        "47-কে নিকটতম দশকে আসন্ন করো।", ["50", "40", "45", "47"],
        "47, 40-এর চেয়ে 50-এর বেশি কাছে।"),
    mcq("Count in 5s: 15, 20, 25, __", ["30", "26", "35", "28"], 0,
        "Adding 5 each time: 25 + 5 = 30.",
        "পাঁচ পাঁচ করে গোনো: 15, 20, 25, __", ["30", "26", "35", "28"],
        "প্রতিবার 5 যোগ: 25 + 5 = 30।"),
    mcq("What is one half of 30?", ["15", "10", "60", "20"], 0,
        "Halve means split into 2 equal parts: 30 ÷ 2 = 15.",
        "30-এর অর্ধেক কত?", ["15", "10", "60", "20"],
        "অর্ধেক মানে সমান 2 ভাগ: 30 ÷ 2 = 15।"),
    mcq("What is one quarter of 20?", ["5", "4", "10", "80"], 0,
        "A quarter is 1 of 4 equal parts: 20 ÷ 4 = 5.",
        "20-এর এক-চতুর্থাংশ কত?", ["5", "4", "10", "80"],
        "এক-চতুর্থাংশ মানে সমান 4 ভাগের 1 ভাগ: 20 ÷ 4 = 5।"),
    mcq("What is one third of 12?", ["4", "3", "6", "36"], 0,
        "A third is 1 of 3 equal parts: 12 ÷ 3 = 4.",
        "12-এর এক-তৃতীয়াংশ কত?", ["4", "3", "6", "36"],
        "এক-তৃতীয়াংশ মানে সমান 3 ভাগের 1 ভাগ: 12 ÷ 3 = 4।"),
    mcq("A pizza is cut into 4 equal slices. You eat 2. What fraction did you eat?", ["One half", "One quarter", "One third", "All of it"], 0,
        "2 out of 4 equal slices is 2/4 = 1/2.",
        "একটা পিৎজা সমান 4 টুকরো করা হলো। তুমি 2টি খেলে। কত ভগ্নাংশ খেলে?", ["অর্ধেক", "এক-চতুর্থাংশ", "এক-তৃতীয়াংশ", "পুরোটা"],
        "সমান 4 টুকরোর 2টি = 2/4 = 1/2।"),
    mcq("Which shape has 6 square faces?", ["Cube", "Cone", "Cylinder", "Sphere"], 0,
        "A cube (like a dice) has 6 square faces, 12 edges and 8 corners.",
        "কোন আকারের 6টি বর্গাকার তল?", ["ঘনক", "শঙ্কু", "চোঙ (সিলিন্ডার)", "গোলক"],
        "ঘনকের (লুডোর ছক্কার মতো) 6টি বর্গাকার তল, 12টি ধার আর 8টি কোণ।"),
    mcq("Which 3D shape is a tin of beans?", ["Cylinder", "Cube", "Cone", "Pyramid"], 0,
        "A cylinder has two flat circle ends and one curved side - like a tin or a bridge pier.",
        "বিনের টিন কোন ত্রিমাত্রিক আকার?", ["চোঙ (সিলিন্ডার)", "ঘনক", "শঙ্কু", "পিরামিড"],
        "চোঙের দুই প্রান্তে সমতল বৃত্ত আর একটা বাঁকা পাশ - টিন বা সেতুর স্তম্ভের মতো।"),
    mcq("Which 3D shape is an ice-cream cone?", ["Cone", "Cube", "Cylinder", "Sphere"], 0,
        "A cone has one circle face and comes to a point.",
        "আইসক্রিমের কোন কোন ত্রিমাত্রিক আকার?", ["শঙ্কু", "ঘনক", "চোঙ", "গোলক"],
        "শঙ্কুর একটা বৃত্তাকার তল আর একদিকে সূচালো।"),
    mcq("How many corners (vertices) does a cube have?", ["8", "6", "4", "12"], 0,
        "A cube has 8 corners: 4 on top and 4 underneath.",
        "একটা ঘনকের কয়টি কোণ (শীর্ষবিন্দু)?", ["8", "6", "4", "12"],
        "ঘনকের 8টি কোণ: উপরে 4টি আর নিচে 4টি।"),
    mcq("A shape is symmetrical if...", ["One half is a mirror image of the other", "It is red", "It is very big", "It has no sides"], 0,
        "Fold it along the line of symmetry and both halves match.",
        "একটা আকার প্রতিসম হয় যদি...", ["এক অর্ধেক অন্যটির আয়না-প্রতিবিম্ব হয়", "লাল হয়", "খুব বড় হয়", "কোনো বাহু না থাকে"],
        "প্রতিসাম্য রেখা বরাবর ভাঁজ করলে দুই অর্ধেক মিলে যায়।"),
    mcq("Many bridges look symmetrical. Why do engineers like that?", ["Loads are shared evenly on both sides", "It saves paint", "It is a law of colours", "Birds prefer it"], 0,
        "A symmetrical bridge carries weight evenly, so neither side is overloaded.",
        "অনেক সেতু প্রতিসম দেখায়। প্রকৌশলীরা এটা পছন্দ করেন কেন?", ["দুই পাশে ভার সমানভাবে ভাগ হয়", "রং বাঁচে", "এটা রঙের নিয়ম", "পাখিরা পছন্দ করে"],
        "প্রতিসম সেতু ওজন সমানভাবে বয়, তাই কোনো দিকে অতিরিক্ত ভার পড়ে না।"),
    mcq("How many centimetres are in 1 metre?", ["100", "10", "1000", "60"], 0,
        "1 m = 100 cm.",
        "1 মিটারে কত সেন্টিমিটার?", ["100", "10", "1000", "60"],
        "1 m = 100 cm।"),
    mcq("How many grams are in 1 kilogram?", ["1000", "100", "10", "60"], 0,
        "1 kg = 1000 g.",
        "1 কিলোগ্রামে কত গ্রাম?", ["1000", "100", "10", "60"],
        "1 kg = 1000 g।"),
    mcq("Which is the best unit to measure the water in a bucket?", ["Litres", "Metres", "Kilograms", "Hours"], 0,
        "Capacity is measured in litres (l) and millilitres (ml).",
        "বালতির জল মাপার সবচেয়ে ভালো একক কোনটা?", ["লিটার", "মিটার", "কিলোগ্রাম", "ঘণ্টা"],
        "ধারণক্ষমতা মাপা হয় লিটার (l) আর মিলিলিটারে (ml)।"),
    mcq("A beam is 3 m long. Another is 250 cm long. Which is longer?", ["The 3 m beam", "The 250 cm beam", "They are equal", "You cannot compare them"], 0,
        "3 m = 300 cm, which is more than 250 cm.",
        "একটা বিম 3 m লম্বা। আরেকটা 250 cm লম্বা। কোনটা বেশি লম্বা?", ["3 m বিম", "250 cm বিম", "দুটো সমান", "তুলনা করা যায় না"],
        "3 m = 300 cm, যা 250 cm-এর বেশি।"),
    mcq("What time is half past 4?", ["4:30", "4:15", "3:30", "4:45"], 0,
        "Half past means 30 minutes after the hour.",
        "সাড়ে 4টা মানে কটা?", ["4:30", "4:15", "3:30", "4:45"],
        "সাড়ে মানে ঘণ্টার পর 30 মিনিট।"),
    mcq("What time is quarter past 7?", ["7:15", "7:45", "7:30", "6:15"], 0,
        "A quarter of an hour is 15 minutes.",
        "সোয়া 7টা মানে কটা?", ["7:15", "7:45", "7:30", "6:15"],
        "এক ঘণ্টার এক-চতুর্থাংশ 15 মিনিট।"),
    mcq("What time is quarter to 9?", ["8:45", "9:15", "9:45", "8:15"], 0,
        "Quarter to 9 is 15 minutes before 9 o'clock.",
        "পৌনে 9টা মানে কটা?", ["8:45", "9:15", "9:45", "8:15"],
        "পৌনে 9টা হলো 9টা বাজার 15 মিনিট আগে।"),
    mcq("A bus leaves at 2:00 and the trip takes 30 minutes. When does it arrive?", ["2:30", "3:00", "2:03", "1:30"], 0,
        "2:00 + 30 minutes = 2:30.",
        "একটা বাস 2:00-এ ছাড়ে আর যাত্রায় 30 মিনিট লাগে। কখন পৌঁছায়?", ["2:30", "3:00", "2:03", "1:30"],
        "2:00 + 30 মিনিট = 2:30।"),
    mcq("How many days are in 2 weeks?", ["14", "7", "12", "21"], 0,
        "1 week = 7 days, so 2 weeks = 14 days.",
        "2 সপ্তাহে কত দিন?", ["14", "7", "12", "21"],
        "1 সপ্তাহ = 7 দিন, তাই 2 সপ্তাহ = 14 দিন।"),
    mcq("A tally shows ||||| ||| . What number is that?", ["8", "5", "3", "53"], 0,
        "A full group of 5 plus 3 more = 8.",
        "একটা ট্যালিতে দেখাচ্ছে ||||| ||| । সংখ্যাটি কত?", ["8", "5", "3", "53"],
        "5-এর একটা পূর্ণ দল আর আরও 3 = 8।"),
    mcq("In a class vote: bus 12, train 9, bike 5. How many more chose bus than bike?", ["7", "17", "3", "21"], 0,
        "12 - 5 = 7.",
        "ক্লাসের ভোটে: বাস 12, ট্রেন 9, সাইকেল 5। সাইকেলের চেয়ে বাস কতজন বেশি বেছেছে?", ["7", "17", "3", "21"],
        "12 - 5 = 7।"),
    mcq("In the same vote (bus 12, train 9, bike 5), how many children voted?", ["26", "21", "17", "12"], 0,
        "12 + 9 + 5 = 26.",
        "একই ভোটে (বাস 12, ট্রেন 9, সাইকেল 5) মোট কতজন শিশু ভোট দিল?", ["26", "21", "17", "12"],
        "12 + 9 + 5 = 26।"),
    mcq("What is the missing number? 4 x __ = 20", ["5", "4", "16", "24"], 0,
        "4 x 5 = 20.",
        "হারানো সংখ্যাটি কত? 4 x __ = 20", ["5", "4", "16", "24"],
        "4 x 5 = 20।"),
    mcq("What is the missing number? __ - 15 = 30", ["45", "15", "35", "25"], 0,
        "Add back: 30 + 15 = 45.",
        "হারানো সংখ্যাটি কত? __ - 15 = 30", ["45", "15", "35", "25"],
        "ফিরিয়ে যোগ করো: 30 + 15 = 45।"),
    mcq("Which multiplication matches 5 + 5 + 5 + 5?", ["4 x 5", "5 x 5", "4 + 5", "5 x 1"], 0,
        "Four groups of five: 4 x 5 = 20.",
        "5 + 5 + 5 + 5 কোন গুণের সমান?", ["4 x 5", "5 x 5", "4 + 5", "5 x 1"],
        "পাঁচের চারটি দল: 4 x 5 = 20।"),
    mcq("Is 3 x 4 the same as 4 x 3?", ["Yes, both are 12", "No, 3 x 4 is bigger", "No, 4 x 3 is bigger", "Only on weekends"], 0,
        "Multiplication can be done in any order: 3 x 4 = 4 x 3 = 12.",
        "3 x 4 কি 4 x 3-এর সমান?", ["হ্যাঁ, দুটোই 12", "না, 3 x 4 বড়", "না, 4 x 3 বড়", "শুধু ছুটির দিনে"],
        "গুণ যেকোনো ক্রমে করা যায়: 3 x 4 = 4 x 3 = 12।"),
    mcq("Which numbers are all in the 2 times table?", ["2, 4, 6, 8", "2, 3, 4, 5", "5, 10, 15, 21", "1, 3, 5, 7"], 0,
        "The 2 times table counts in twos: 2, 4, 6, 8, 10...",
        "কোন সংখ্যাগুলো সবই 2-এর নামতায় আছে?", ["2, 4, 6, 8", "2, 3, 4, 5", "5, 10, 15, 21", "1, 3, 5, 7"],
        "2-এর নামতা দুই দুই করে গোনে: 2, 4, 6, 8, 10...।"),
    mcq("Numbers in the 10 times table always end in...", ["0", "5", "1", "2"], 0,
        "10, 20, 30, 40... they all end in 0.",
        "10-এর নামতার সংখ্যাগুলো সবসময় শেষ হয়...", ["0 দিয়ে", "5 দিয়ে", "1 দিয়ে", "2 দিয়ে"],
        "10, 20, 30, 40... সবগুলো 0 দিয়ে শেষ।"),
    mcq("Numbers in the 5 times table end in...", ["0 or 5", "1 or 2", "3 or 4", "7 or 9"], 0,
        "5, 10, 15, 20, 25... end in 5 or 0.",
        "5-এর নামতার সংখ্যাগুলো শেষ হয়...", ["0 বা 5 দিয়ে", "1 বা 2 দিয়ে", "3 বা 4 দিয়ে", "7 বা 9 দিয়ে"],
        "5, 10, 15, 20, 25... শেষ হয় 5 বা 0 দিয়ে।"),
    mcq("A rectangle garden is 6 m long and 4 m wide. How far is it all the way round?", ["20 m", "10 m", "24 m", "14 m"], 0,
        "Perimeter = 6 + 4 + 6 + 4 = 20 m.",
        "একটা আয়তাকার বাগান 6 m লম্বা আর 4 m চওড়া। চারপাশ ঘুরে কত দূর?", ["20 m", "10 m", "24 m", "14 m"],
        "পরিসীমা = 6 + 4 + 6 + 4 = 20 m।"),
    mcq("A square fence has sides of 5 m. How long is the whole fence?", ["20 m", "10 m", "25 m", "15 m"], 0,
        "4 sides x 5 m = 20 m.",
        "একটা বর্গাকার বেড়ার প্রতিটি বাহু 5 m। পুরো বেড়া কত লম্বা?", ["20 m", "10 m", "25 m", "15 m"],
        "4টি বাহু x 5 m = 20 m।"),
    mcq("Which angle is a right angle (a square corner)?", ["The corner of a book", "The tip of a pencil", "The edge of a ball", "A wavy line"], 0,
        "A right angle is a quarter turn, like the corner of a book or a door frame.",
        "কোন কোণটা সমকোণ (বর্গাকার কোণ)?", ["বইয়ের কোণ", "পেনসিলের ডগা", "বলের কিনারা", "ঢেউখেলানো রেখা"],
        "সমকোণ হলো এক-চতুর্থাংশ ঘোরা, বইয়ের কোণ বা দরজার ফ্রেমের মতো।"),
    mcq("How many right angles are in a full turn?", ["4", "2", "1", "3"], 0,
        "A full turn is 4 quarter turns.",
        "একটা পূর্ণ ঘোরায় কয়টি সমকোণ?", ["4", "2", "1", "3"],
        "পূর্ণ ঘোরা হলো 4টি এক-চতুর্থাংশ ঘোরা।"),
    mcq("You face north and turn a quarter turn clockwise. Which way do you face?", ["East", "West", "South", "North"], 0,
        "Clockwise from north: east, south, west.",
        "তুমি উত্তরমুখী, ঘড়ির কাঁটার দিকে এক-চতুর্থাংশ ঘুরলে। এখন কোন দিকে মুখ?", ["পূর্ব", "পশ্চিম", "দক্ষিণ", "উত্তর"],
        "উত্তর থেকে ঘড়ির কাঁটার দিকে: পূর্ব, দক্ষিণ, পশ্চিম।"),
    mcq("A bag of cement weighs 25 kg. How much do 2 bags weigh?", ["50 kg", "27 kg", "25 kg", "52 kg"], 0,
        "25 + 25 = 50 kg.",
        "এক বস্তা সিমেন্টের ওজন 25 kg। 2 বস্তার ওজন কত?", ["50 kg", "27 kg", "25 kg", "52 kg"],
        "25 + 25 = 50 kg।"),
    mcq("A bridge limit is 40 tonnes. A truck weighs 25 tonnes and carries 20 tonnes. Is it safe?", ["No - 45 tonnes is over the limit", "Yes - 25 is under 40", "Yes - 20 is under 40", "Only if it drives fast"], 0,
        "Total weight counts: 25 + 20 = 45 tonnes, which is more than 40.",
        "একটা সেতুর ওজনসীমা 40 টন। একটা ট্রাকের ওজন 25 টন আর সে 20 টন বইছে। নিরাপদ?", ["না - 45 টন সীমার বেশি", "হ্যাঁ - 25, 40-এর কম", "হ্যাঁ - 20, 40-এর কম", "শুধু জোরে চালালে"],
        "মোট ওজন ধরতে হয়: 25 + 20 = 45 টন, যা 40-এর বেশি।"),
    mcq("Which coins make exactly Rs 35?", ["Rs 20 + Rs 10 + Rs 5", "Rs 20 + Rs 20", "Rs 10 + Rs 10 + Rs 10", "Rs 20 + Rs 5 + Rs 5"], 0,
        "20 + 10 + 5 = 35.",
        "কোন পয়সাগুলো মিলে ঠিক 35 টাকা হয়?", ["20 টাকা + 10 টাকা + 5 টাকা", "20 টাকা + 20 টাকা", "10 টাকা + 10 টাকা + 10 টাকা", "20 টাকা + 5 টাকা + 5 টাকা"],
        "20 + 10 + 5 = 35।"),
    mcq("You buy a Rs 45 book with a Rs 50 note. What is your change?", ["Rs 5", "Rs 95", "Rs 10", "Rs 15"], 0,
        "50 - 45 = Rs 5.",
        "50 টাকার নোট দিয়ে 45 টাকার বই কিনলে। কত ফেরত পাবে?", ["5 টাকা", "95 টাকা", "10 টাকা", "15 টাকা"],
        "50 - 45 = 5 টাকা।"),
    mcq("What comes next? 3, 6, 9, 12, __", ["15", "13", "14", "18"], 0,
        "Counting in threes: 12 + 3 = 15.",
        "এরপর কী? 3, 6, 9, 12, __", ["15", "13", "14", "18"],
        "তিন তিন করে: 12 + 3 = 15।"),
    mcq("What comes next? 100, 90, 80, __", ["70", "60", "79", "81"], 0,
        "Counting back in tens.",
        "এরপর কী? 100, 90, 80, __", ["70", "60", "79", "81"],
        "দশ দশ করে পিছনে গোনা।"),
    mcq("Which number is halfway between 20 and 30?", ["25", "24", "26", "50"], 0,
        "20, 21, 22, 23, 24, 25 ... 30 - 25 is in the middle.",
        "20 আর 30-এর ঠিক মাঝখানে কোন সংখ্যা?", ["25", "24", "26", "50"],
        "20, 21, 22, 23, 24, 25 ... 30 - 25 মাঝখানে।"),
    mcq("A train leaves with 60 people. 25 get off and 15 get on. How many now?", ["50", "40", "70", "35"], 0,
        "60 - 25 = 35, then 35 + 15 = 50.",
        "একটা ট্রেন 60 জন নিয়ে ছাড়ল। 25 জন নামলেন আর 15 জন উঠলেন। এখন কতজন?", ["50", "40", "70", "35"],
        "60 - 25 = 35, তারপর 35 + 15 = 50।"),
    mcq("A bridge has 2 towers, each with 4 cables. How many cables?", ["8", "6", "4", "2"], 0,
        "2 x 4 = 8 cables.",
        "একটা সেতুর 2টি টাওয়ার, প্রতিটিতে 4টি তার। মোট কয়টি তার?", ["8", "6", "4", "2"],
        "2 x 4 = 8টি তার।"),
    mcq("A clock shows 3:00. What time will it be in 2 hours?", ["5:00", "1:00", "3:02", "6:00"], 0,
        "3 + 2 = 5 o'clock.",
        "ঘড়িতে 3:00। 2 ঘণ্টা পরে কটা বাজবে?", ["5:00", "1:00", "3:02", "6:00"],
        "3 + 2 = 5টা।"),
    mcq("Which is heaviest?", ["2 kg", "1500 g", "1 kg", "900 g"], 0,
        "2 kg = 2000 g, the most of these.",
        "কোনটা সবচেয়ে ভারী?", ["2 kg", "1500 g", "1 kg", "900 g"],
        "2 kg = 2000 g, এগুলোর মধ্যে সবচেয়ে বেশি।"),
    mcq("Which is longest?", ["1 m", "90 cm", "50 cm", "99 cm"], 0,
        "1 m = 100 cm, longer than 99 cm.",
        "কোনটা সবচেয়ে লম্বা?", ["1 m", "90 cm", "50 cm", "99 cm"],
        "1 m = 100 cm, 99 cm-এর চেয়ে লম্বা।"),
    mcq("A jug holds 2 litres. How many jugs fill a 10-litre bucket?", ["5", "2", "10", "20"], 0,
        "10 ÷ 2 = 5 jugs.",
        "একটা জগে 2 লিটার ধরে। 10 লিটারের বালতি ভরতে কয় জগ?", ["5", "2", "10", "20"],
        "10 ÷ 2 = 5 জগ।"),
    mcq("Which fraction is bigger?", ["1/2", "1/4", "1/3", "1/10"], 0,
        "Sharing a cake between fewer people gives bigger pieces: 1/2 is the biggest.",
        "কোন ভগ্নাংশ বড়?", ["1/2", "1/4", "1/3", "1/10"],
        "কম জনের মধ্যে কেক ভাগ করলে টুকরো বড় হয়: 1/2 সবচেয়ে বড়।"),
    mcq("How many quarters make a whole?", ["4", "2", "3", "1"], 0,
        "4 quarters = 1 whole.",
        "কয়টি এক-চতুর্থাংশ মিলে একটা পূর্ণ হয়?", ["4", "2", "3", "1"],
        "4টি এক-চতুর্থাংশ = 1টি পূর্ণ।"),
    mcq("A 12 m beam is cut in half. How long is each piece?", ["6 m", "12 m", "24 m", "3 m"], 0,
        "12 ÷ 2 = 6 m.",
        "একটা 12 m বিম অর্ধেক কাটা হলো। প্রতিটি টুকরো কত লম্বা?", ["6 m", "12 m", "24 m", "3 m"],
        "12 ÷ 2 = 6 m।"),
    mcq("A 16 m beam is cut into 4 equal pieces. How long is each?", ["4 m", "12 m", "8 m", "20 m"], 0,
        "16 ÷ 4 = 4 m. (In MODIS BridgeWorks Level 1, beams can be up to 8 m!)",
        "একটা 16 m বিম সমান 4 টুকরো করা হলো। প্রতিটি কত লম্বা?", ["4 m", "12 m", "8 m", "20 m"],
        "16 ÷ 4 = 4 m। (MODIS BridgeWorks-এর লেভেল 1-এ বিম 8 m পর্যন্ত হতে পারে!)"),
    mcq("Which number sentence is true?", ["7 + 8 = 15", "7 + 8 = 16", "7 + 8 = 14", "7 + 8 = 78"], 0,
        "7 + 8: 7 + 3 = 10, then 10 + 5 = 15.",
        "কোন সংখ্যা-বাক্যটি সত্যি?", ["7 + 8 = 15", "7 + 8 = 16", "7 + 8 = 14", "7 + 8 = 78"],
        "7 + 8: 7 + 3 = 10, তারপর 10 + 5 = 15।"),
    mcq("A shape has 5 sides. What is it called?", ["Pentagon", "Hexagon", "Octagon", "Square"], 0,
        "Penta means five. A hexagon has 6, an octagon 8.",
        "একটা আকারের 5টি বাহু। একে কী বলে?", ["পঞ্চভুজ", "ষড়ভুজ", "অষ্টভুজ", "বর্গ"],
        "'পঞ্চ' মানে পাঁচ। ষড়ভুজের 6টি, অষ্টভুজের 8টি।"),
    mcq("A shape has 6 sides, like a honeycomb cell. What is it?", ["Hexagon", "Pentagon", "Triangle", "Circle"], 0,
        "Bees use hexagons because they fit together with no gaps and use little wax.",
        "মৌচাকের ঘরের মতো একটা আকারের 6টি বাহু। এটা কী?", ["ষড়ভুজ", "পঞ্চভুজ", "ত্রিভুজ", "বৃত্ত"],
        "মৌমাছি ষড়ভুজ ব্যবহার করে, কারণ ফাঁক ছাড়া জোড়া লাগে আর কম মোম লাগে।"),
    mcq("How many triangles are in a truss made of 5 triangles in a row, plus 1 more on top?", ["6", "5", "10", "15"], 0,
        "5 + 1 = 6 triangles.",
        "সারিতে 5টি ত্রিভুজের একটা ট্রাস আর উপরে আরও 1টি। মোট কয়টি ত্রিভুজ?", ["6", "5", "10", "15"],
        "5 + 1 = 6টি ত্রিভুজ।"),
    mcq("A worker earns Rs 10 an hour and works 8 hours. How much does he earn?", ["Rs 80", "Rs 18", "Rs 10", "Rs 108"], 0,
        "8 x 10 = Rs 80.",
        "একজন শ্রমিক ঘণ্টায় 10 টাকা পান আর 8 ঘণ্টা কাজ করেন। কত পান?", ["80 টাকা", "18 টাকা", "10 টাকা", "108 টাকা"],
        "8 x 10 = 80 টাকা।"),
    mcq("Which is the best estimate of a door's height?", ["2 m", "2 cm", "20 m", "200 km"], 0,
        "A door is about 2 metres tall - taller than most people.",
        "একটা দরজার উচ্চতার সবচেয়ে ভালো আন্দাজ কোনটা?", ["2 m", "2 cm", "20 m", "200 km"],
        "একটা দরজা প্রায় 2 মিটার উঁচু - বেশিরভাগ মানুষের চেয়ে লম্বা।"),
    mcq("You have 3 shirts and 2 shorts. How many different outfits (1 shirt + 1 shorts)?", ["6", "5", "3", "2"], 0,
        "Each of 3 shirts goes with 2 shorts: 3 x 2 = 6 outfits.",
        "তোমার 3টি জামা আর 2টি হাফপ্যান্ট। কয় রকম পোশাক হয় (1 জামা + 1 প্যান্ট)?", ["6", "5", "3", "2"],
        "3টি জামার প্রতিটি 2টি প্যান্টের সঙ্গে: 3 x 2 = 6 রকম।"),
)
