"""Class 3 - Commercials: how prices are set, costs of making and moving goods, supply chains,
markets and competition, marketing, customers, and how bridges help trade."""
from . import mcq


def margin(cost, price, n, item_en, item_bn):
    each = price - cost
    r = each * n
    o = list(dict.fromkeys([r, price * n, cost * n, r + n, r * 2, r + 1]))[:4]
    return mcq(f"A stall buys {item_en} at Rs {cost} each and sells them at Rs {price}. It sells {n}. Profit?",
               [f"Rs {x}" for x in o], 0,
               f"Profit each = {price} - {cost} = Rs {each}; x {n} = Rs {r}.",
               f"একটা স্টল প্রতিটি {cost} টাকায় {item_bn} কিনে {price} টাকায় বেচে। {n}টি বেচল। লাভ?",
               [f"{x} টাকা" for x in o],
               f"প্রতিটিতে লাভ = {price} - {cost} = {each} টাকা; x {n} = {r} টাকা।")


ITEMS = (
    margin(12, 18, 25, "notebooks", "খাতা"),
    margin(30, 45, 12, "lunch boxes", "টিফিন বাক্স"),
    margin(8, 15, 40, "samosas", "শিঙাড়া"),
    margin(50, 80, 9, "school bags", "স্কুলব্যাগ"),
    margin(5, 9, 60, "glasses of sugarcane juice", "গ্লাস আখের রস"),
    margin(150, 200, 6, "pairs of sandals", "জোড়া চপ্পল"),
    margin(20, 26, 30, "bottles of water", "বোতল জল"),
    margin(70, 95, 8, "umbrellas", "ছাতা"),
    mcq("What three things decide a fair selling price?", ["Cost, what customers will pay and what competitors charge", "The weather only", "The colour of the shop", "The seller's age"], 0,
        "Sellers cover costs, earn some profit and stay competitive.",
        "ন্যায্য বিক্রয়মূল্য কোন তিনটি জিনিস ঠিক করে?", ["খরচ, খদ্দের কত দেবে আর প্রতিযোগীরা কত নেয়", "শুধু আবহাওয়া", "দোকানের রং", "বিক্রেতার বয়স"],
        "বিক্রেতা খরচ মেটান, কিছু লাভ রাখেন আর প্রতিযোগিতায় টিকে থাকেন।"),
    mcq("What is a 'supply chain'?", ["All the steps that bring a product from raw materials to the customer", "A metal chain in a shop", "A line of customers", "A bank loan"], 0,
        "Farm or mine -> factory -> warehouse -> shop -> you. Trucks, trains, ships and bridges link each step.",
        "'সরবরাহ শৃঙ্খল' কী?", ["কাঁচামাল থেকে খদ্দের পর্যন্ত পণ্য আনার সব ধাপ", "দোকানের ধাতুর শিকল", "খদ্দেরদের লাইন", "ব্যাংক ঋণ"],
        "খামার বা খনি -> কারখানা -> গুদাম -> দোকান -> তুমি। ট্রাক, ট্রেন, জাহাজ আর সেতু প্রতিটি ধাপ জোড়ে।"),
    mcq("What happens to a supply chain when a key bridge is closed?", ["Deliveries are delayed and costs rise", "Nothing changes", "Goods get cheaper", "Shops get more stock"], 0,
        "Detours add time and fuel, and shops may run short.",
        "একটা গুরুত্বপূর্ণ সেতু বন্ধ হলে সরবরাহ শৃঙ্খলের কী হয়?", ["ডেলিভারি দেরি হয় আর খরচ বাড়ে", "কিছুই বদলায় না", "মাল সস্তা হয়", "দোকানে বেশি মজুত আসে"],
        "ঘুরপথে সময় আর জ্বালানি বাড়ে, আর দোকানে টান পড়তে পারে।"),
    mcq("What are 'raw materials'?", ["Natural materials used to make products, like cotton, iron ore or wood", "Finished toys", "Money", "Customers"], 0,
        "Raw materials are turned into products in factories.",
        "'কাঁচামাল' কী?", ["পণ্য বানাতে ব্যবহৃত প্রাকৃতিক উপাদান, যেমন তুলো, লোহার আকরিক বা কাঠ", "তৈরি খেলনা", "টাকা", "খদ্দের"],
        "কাঁচামাল কারখানায় পণ্যে বদলায়।"),
    mcq("What does a factory add to raw materials?", ["Work and machines that turn them into useful products", "Nothing", "Water only", "Rain"], 0,
        "Turning iron ore into steel beams adds value.",
        "কারখানা কাঁচামালে কী যোগ করে?", ["শ্রম আর যন্ত্র, যা তাকে দরকারি পণ্যে বদলায়", "কিছুই না", "শুধু জল", "বৃষ্টি"],
        "লোহার আকরিককে ইস্পাতের বিমে বদলানো মূল্য যোগ করে।"),
    mcq("What does 'adding value' mean?", ["Making something worth more by working on it", "Adding numbers", "Painting a price tag", "Giving it away"], 0,
        "Wood is worth more as a chair than as a log.",
        "'মূল্য সংযোজন' মানে কী?", ["কাজ করে কোনো কিছুর দাম বাড়ানো", "সংখ্যা যোগ করা", "দামের ট্যাগ রং করা", "দিয়ে দেওয়া"],
        "গুঁড়ির চেয়ে চেয়ার হিসেবে কাঠের দাম বেশি।"),
    mcq("Which costs are part of making a toy car?", ["Materials, workers' wages, factory power and transport", "Only the paint", "Only the shop's rent", "Nothing"], 0,
        "All these costs must be covered by the selling price.",
        "খেলনা গাড়ি বানানোর খরচের অংশ কোনগুলো?", ["উপাদান, শ্রমিকের মজুরি, কারখানার বিদ্যুৎ আর পরিবহন", "শুধু রং", "শুধু দোকানের ভাড়া", "কিছুই না"],
        "এই সব খরচ বিক্রয়মূল্য দিয়ে মেটাতে হয়।"),
    mcq("A factory makes 100 toys for Rs 2,000 in total. What is the cost of each toy?", ["Rs 20", "Rs 200", "Rs 2", "Rs 100"], 0,
        "2000 ÷ 100 = Rs 20 per toy.",
        "একটা কারখানা মোট 2,000 টাকায় 100টি খেলনা বানায়। প্রতিটি খেলনার খরচ কত?", ["20 টাকা", "200 টাকা", "2 টাকা", "100 টাকা"],
        "2000 ÷ 100 = প্রতি খেলনা 20 টাকা।"),
    mcq("If the factory makes 200 toys and the total cost rises only to Rs 3,000, the cost per toy...", ["Falls to Rs 15", "Rises to Rs 30", "Stays at Rs 20", "Becomes zero"], 0,
        "3000 ÷ 200 = 15. Making more often lowers the cost of each - called economies of scale.",
        "কারখানা 200টি খেলনা বানালে আর মোট খরচ বেড়ে মাত্র 3,000 টাকা হলে প্রতি খেলনার খরচ...", ["কমে 15 টাকা", "বেড়ে 30 টাকা", "20 টাকাই থাকে", "শূন্য হয়"],
        "3000 ÷ 200 = 15। বেশি বানালে প্রায়ই প্রতিটির খরচ কমে - একে বলে বৃহদায়তনের সাশ্রয়।"),
    mcq("What is a 'market' in business?", ["All the people who might buy a product", "Only a street with stalls", "A bank", "A factory"], 0,
        "The market for school bags is all the students and parents who might buy one.",
        "ব্যবসায় 'বাজার' কী?", ["যারা একটা পণ্য কিনতে পারে সেই সব মানুষ", "শুধু স্টলওয়ালা রাস্তা", "একটা ব্যাংক", "একটা কারখানা"],
        "স্কুলব্যাগের বাজার হলো সব ছাত্রছাত্রী আর অভিভাবক, যারা একটা কিনতে পারেন।"),
    mcq("What is 'market research'?", ["Finding out what customers want before selling", "Shopping for fun", "Counting coins", "Painting a shop"], 0,
        "Surveys and questions help a business make what people will buy.",
        "'বাজার গবেষণা' কী?", ["বিক্রির আগে খদ্দের কী চায় তা খুঁজে বের করা", "মজা করে কেনাকাটা", "পয়সা গোনা", "দোকান রং করা"],
        "সমীক্ষা আর প্রশ্ন ব্যবসাকে এমন জিনিস বানাতে সাহায্য করে যা মানুষ কিনবে।"),
    mcq("You ask 30 classmates what snack they want at a sale: 18 say fruit cups. What should you sell most?", ["Fruit cups", "Something nobody chose", "Nothing", "Only drinks"], 0,
        "Your survey shows demand - stock what most people want.",
        "সেলে কোন জলখাবার চায় তা 30 জন সহপাঠীকে জিজ্ঞাসা করলে: 18 জন বলল ফলের কাপ। কী বেশি বেচবে?", ["ফলের কাপ", "যা কেউ বাছেনি", "কিছুই না", "শুধু পানীয়"],
        "তোমার সমীক্ষা চাহিদা দেখায় - বেশিরভাগ মানুষ যা চায় তা মজুত করো।"),
    mcq("What is a 'target customer'?", ["The kind of person a product is mainly made for", "A customer who throws darts", "Any random person", "The shop owner"], 0,
        "Toy makers target children and parents; tractor makers target farmers.",
        "'লক্ষ্য খদ্দের' কে?", ["যে ধরনের মানুষের জন্য পণ্যটা মূলত বানানো", "যে খদ্দের ডার্ট ছোড়ে", "যেকোনো এলোমেলো মানুষ", "দোকানের মালিক"],
        "খেলনা-নির্মাতার লক্ষ্য শিশু আর অভিভাবক; ট্রাক্টর-নির্মাতার লক্ষ্য চাষি।"),
    mcq("What is 'marketing'?", ["Everything a business does to tell people about and sell its product", "Only building a market", "Buying raw materials", "Paying tax"], 0,
        "Marketing includes product, price, place and promotion.",
        "'বিপণন' কী?", ["পণ্যের কথা জানাতে আর বেচতে ব্যবসার করা সব কিছু", "শুধু বাজার বানানো", "কাঁচামাল কেনা", "কর দেওয়া"],
        "বিপণনে থাকে পণ্য, দাম, জায়গা আর প্রচার।"),
    mcq("What is a 'slogan'?", ["A short catchy phrase that helps people remember a brand", "A loud noise", "A price", "A receipt"], 0,
        "A good slogan sticks in your head.",
        "'স্লোগান' কী?", ["ছোট আকর্ষণীয় বাক্য, যা ব্র্যান্ড মনে রাখতে সাহায্য করে", "জোরালো শব্দ", "একটা দাম", "রসিদ"],
        "ভালো স্লোগান মনে গেঁথে যায়।"),
    mcq("Why do companies put adverts on buses and trains?", ["Many people see them every day as they travel", "Buses need decoration", "It makes buses faster", "It is free"], 0,
        "Busy routes carry thousands of potential customers.",
        "কোম্পানি বাস আর ট্রেনে বিজ্ঞাপন দেয় কেন?", ["যাতায়াতে প্রতিদিন অনেক মানুষ দেখে", "বাসের সাজসজ্জা দরকার", "বাস দ্রুত চলে", "এটা বিনামূল্যে"],
        "ব্যস্ত পথে হাজার হাজার সম্ভাব্য খদ্দের যাতায়াত করে।"),
    mcq("A shop's advert costs Rs 500 and brings 50 extra customers who each give Rs 20 profit. Was it worth it?", ["Yes - Rs 1,000 profit for Rs 500", "No - it lost money", "It broke even exactly", "Cannot tell at all"], 0,
        "50 x 20 = 1,000 profit; minus 500 advert = Rs 500 gain.",
        "একটা দোকানের বিজ্ঞাপনে 500 টাকা খরচ, এনেছে 50 জন বাড়তি খদ্দের, প্রত্যেকে 20 টাকা লাভ দেন। কি লাভজনক?", ["হ্যাঁ - 500 টাকায় 1,000 টাকা লাভ", "না - টাকা হারিয়েছে", "ঠিক লাভ-লোকসান সমান", "একদম বলা যায় না"],
        "50 x 20 = 1,000 লাভ; বিজ্ঞাপনের 500 বাদে 500 টাকা লাভ।"),
    mcq("What is 'competition' good for customers?", ["It pushes sellers to offer better prices and quality", "It makes everything expensive", "It closes all shops", "Nothing"], 0,
        "When shops compete, customers usually win.",
        "'প্রতিযোগিতা' খদ্দেরের জন্য কীসে ভালো?", ["বিক্রেতাদের ভালো দাম আর মান দিতে চাপ দেয়", "সব দামি করে", "সব দোকান বন্ধ করে", "কিছুতেই না"],
        "দোকান প্রতিযোগিতা করলে সাধারণত খদ্দেরই জেতে।"),
    mcq("What is a 'monopoly'?", ["When only one company sells a product, with no competition", "A board game only", "A big shop", "A bank"], 0,
        "Without competition, a monopoly might charge high prices - so governments often regulate them.",
        "'একচেটিয়া' (মনোপলি) কী?", ["যখন কেবল একটা কোম্পানি একটা পণ্য বেচে, প্রতিযোগিতা ছাড়া", "শুধু একটা বোর্ড-খেলা", "একটা বড় দোকান", "একটা ব্যাংক"],
        "প্রতিযোগিতা না থাকলে একচেটিয়া কোম্পানি চড়া দাম নিতে পারে - তাই সরকার প্রায়ই নিয়ন্ত্রণ করে।"),
    mcq("The only bridge across a river charges a toll. Why might the government set the toll limit?", ["To stop unfairly high prices when there is no other route", "To make the bridge heavier", "To close the bridge", "No reason"], 0,
        "Rules protect users of a monopoly service.",
        "নদীর উপর একমাত্র সেতু টোল নেয়। সরকার টোলের সীমা ঠিক করে দিতে পারে কেন?", ["অন্য পথ না থাকলে অন্যায্য চড়া দাম ঠেকাতে", "সেতু ভারী করতে", "সেতু বন্ধ করতে", "কোনো কারণ নেই"],
        "নিয়ম একচেটিয়া পরিষেবার ব্যবহারকারীদের রক্ষা করে।"),
    mcq("What does 'logistics' mean?", ["Planning how to move and store goods efficiently", "A type of logic puzzle only", "Cooking", "Painting"], 0,
        "Logistics decides which trucks, trains or ships carry what, when - like Level 9 in MODIS BridgeWorks.",
        "'লজিস্টিকস' মানে কী?", ["দক্ষতার সঙ্গে মাল সরানো আর রাখার পরিকল্পনা", "শুধু এক রকম যুক্তির ধাঁধা", "রান্না", "রং করা"],
        "লজিস্টিকস ঠিক করে কোন ট্রাক, ট্রেন বা জাহাজ কী, কখন বইবে - MODIS BridgeWorks-এর লেভেল 9-এর মতো।"),
    mcq("Which usually costs least per tonne to move heavy goods over long distances?", ["Rail or ship", "Small vans", "Motorbikes", "Carrying by hand"], 0,
        "Trains and ships carry huge loads with little fuel per tonne.",
        "লম্বা দূরত্বে ভারী মাল সরাতে প্রতি টনে সাধারণত কোনটায় খরচ সবচেয়ে কম?", ["রেল বা জাহাজ", "ছোট ভ্যান", "মোটরসাইকেল", "হাতে বয়ে"],
        "ট্রেন আর জাহাজ প্রতি টনে কম জ্বালানিতে বিশাল বোঝা বয়।"),
    mcq("Which is usually fastest for a small urgent parcel across a city?", ["A motorbike or van courier", "A cargo ship", "A freight train", "A barge"], 0,
        "Small, flexible vehicles beat big ones for short urgent trips.",
        "শহর জুড়ে ছোট জরুরি পার্সেলের জন্য সাধারণত কোনটা সবচেয়ে দ্রুত?", ["মোটরসাইকেল বা ভ্যান কুরিয়ার", "মালবাহী জাহাজ", "মালগাড়ি", "বার্জ"],
        "ছোট জরুরি যাত্রায় ছোট, নমনীয় বাহন বড়গুলোকে হারায়।"),
    mcq("A company must move 1000 tonnes cheaply and has 3 days. Which is sensible?", ["Rail or barge", "100 motorbikes", "Aeroplane", "Carrying by hand"], 0,
        "Plenty of time and a huge load suit slow, cheap, high-capacity transport.",
        "একটা কোম্পানিকে 3 দিনে সস্তায় 1000 টন সরাতে হবে। কোনটা বুদ্ধিমানের?", ["রেল বা বার্জ", "100টি মোটরসাইকেল", "উড়োজাহাজ", "হাতে বয়ে"],
        "হাতে যথেষ্ট সময় আর বিশাল বোঝা হলে ধীর, সস্তা, বেশি ধারণক্ষমতার পরিবহন মানায়।"),
    mcq("What is a 'warehouse' for in a supply chain?", ["Storing goods between the factory and shops", "Selling to customers only", "Making products", "Banking"], 0,
        "Warehouses hold stock so shops can be refilled quickly.",
        "সরবরাহ শৃঙ্খলে 'গুদাম' কীসের জন্য?", ["কারখানা আর দোকানের মাঝে মাল রাখা", "শুধু খদ্দেরকে বেচা", "পণ্য বানানো", "ব্যাংকিং"],
        "গুদাম মজুত রাখে, যাতে দোকান দ্রুত আবার ভরা যায়।"),
    mcq("Why are big warehouses often built near highways, railways and bridges?", ["Goods can be moved in and out quickly", "Land is always free there", "For the view", "They are not"], 0,
        "Good transport links save time and money.",
        "বড় গুদাম প্রায়ই মহাসড়ক, রেলপথ আর সেতুর কাছে বানানো হয় কেন?", ["মাল দ্রুত আনা-নেওয়া যায়", "সেখানে জমি সবসময় বিনামূল্যে", "দৃশ্যের জন্য", "বানানো হয় না"],
        "ভালো যোগাযোগ সময় আর টাকা বাঁচায়।"),
    mcq("What is a 'customer review'?", ["A customer's opinion about a product or service", "A shop inspection by police", "A price list", "A receipt"], 0,
        "Good reviews attract new customers; bad ones warn them.",
        "'খদ্দেরের মতামত' (রিভিউ) কী?", ["পণ্য বা পরিষেবা নিয়ে একজন খদ্দেরের মত", "পুলিশের দোকান পরিদর্শন", "দামের তালিকা", "রসিদ"],
        "ভালো মতামত নতুন খদ্দের টানে; খারাপ মতামত সতর্ক করে।"),
    mcq("Why do businesses care about their reputation?", ["Trust brings customers back and attracts new ones", "Reputation costs nothing", "It is not important", "Only for banks"], 0,
        "A good name takes years to build and moments to lose.",
        "ব্যবসা নিজের সুনাম নিয়ে ভাবে কেন?", ["বিশ্বাস খদ্দেরকে ফিরিয়ে আনে আর নতুনদের টানে", "সুনামের দাম নেই", "জরুরি নয়", "শুধু ব্যাংকের জন্য"],
        "সুনাম গড়তে বছর লাগে, হারাতে মুহূর্ত।"),
    mcq("What is 'quality control'?", ["Checking products to make sure they meet standards", "Controlling customers", "Setting prices", "Painting boxes"], 0,
        "Steel for bridges is tested for strength before it leaves the factory.",
        "'মান নিয়ন্ত্রণ' কী?", ["পণ্য মান অনুযায়ী আছে কিনা যাচাই", "খদ্দের নিয়ন্ত্রণ", "দাম ঠিক করা", "বাক্স রং করা"],
        "সেতুর ইস্পাত কারখানা ছাড়ার আগে শক্তির জন্য পরীক্ষা করা হয়।"),
    mcq("Why is quality control especially important for bridge parts?", ["A faulty part could make the bridge unsafe", "Bridges do not need quality", "Only colour matters", "It is cheaper to skip it"], 0,
        "Safety-critical products need careful testing.",
        "সেতুর অংশে মান নিয়ন্ত্রণ বিশেষ জরুরি কেন?", ["একটা ত্রুটিপূর্ণ অংশ সেতুকে অনিরাপদ করতে পারে", "সেতুর মান লাগে না", "শুধু রং জরুরি", "বাদ দেওয়া সস্তা"],
        "নিরাপত্তা-সংবেদনশীল পণ্যে সাবধানী পরীক্ষা লাগে।"),
    mcq("What is a 'guarantee' (warranty)?", ["A promise to repair or replace a product if it breaks within a time", "A free product", "A tax", "A loan"], 0,
        "Warranties give customers confidence in quality.",
        "'গ্যারান্টি' (ওয়ারেন্টি) কী?", ["নির্দিষ্ট সময়ের মধ্যে পণ্য ভাঙলে সারানো বা বদলে দেওয়ার প্রতিশ্রুতি", "বিনামূল্যের পণ্য", "কর", "ঋণ"],
        "ওয়ারেন্টি খদ্দেরকে মানের ব্যাপারে আস্থা দেয়।"),
    mcq("What is an 'invoice'?", ["A bill sent by a seller asking to be paid", "A receipt after paying only", "A loan", "A type of shop"], 0,
        "Businesses send invoices to customers and suppliers send invoices to businesses.",
        "'চালান' (ইনভয়েস) কী?", ["বিক্রেতার পাঠানো বিল, যাতে টাকা চাওয়া হয়", "শুধু দাম দেওয়ার পরের রসিদ", "ঋণ", "এক রকম দোকান"],
        "ব্যবসা খদ্দেরকে আর সরবরাহকারী ব্যবসাকে চালান পাঠায়।"),
    mcq("A builder's invoice lists steel Rs 5,000, labour Rs 3,000 and transport Rs 1,000. Total?", ["Rs 9,000", "Rs 8,000", "Rs 6,000", "Rs 15,000"], 0,
        "5000 + 3000 + 1000 = 9,000.",
        "একজন নির্মাতার চালানে ইস্পাত 5,000, শ্রম 3,000 আর পরিবহন 1,000 টাকা। মোট?", ["9,000 টাকা", "8,000 টাকা", "6,000 টাকা", "15,000 টাকা"],
        "5000 + 3000 + 1000 = 9,000।"),
    mcq("What is 'cash flow' in a business?", ["Money coming in and going out over time", "Water in a shop", "A kind of river", "Only profit"], 0,
        "A business can be profitable but still run out of cash if payments come late.",
        "ব্যবসায় 'নগদ প্রবাহ' কী?", ["সময়ের সঙ্গে আসা আর যাওয়া টাকা", "দোকানের জল", "এক রকম নদী", "শুধু লাভ"],
        "লাভজনক ব্যবসাও দেরিতে টাকা এলে নগদ-সংকটে পড়তে পারে।"),
    mcq("Why do businesses offer 'pay within 30 days' to other businesses?", ["It helps customers who need time before their own money comes in", "To lose money", "It is required for toys", "No reason"], 0,
        "Trade credit keeps business flowing, but sellers must watch their own cash.",
        "ব্যবসা অন্য ব্যবসাকে '30 দিনের মধ্যে দাম দাও' সুবিধা দেয় কেন?", ["নিজেদের টাকা আসার আগে যাদের সময় লাগে, তাদের সাহায্য করে", "টাকা হারাতে", "খেলনার জন্য বাধ্যতামূলক", "কোনো কারণ নেই"],
        "বাণিজ্যিক ধার ব্যবসা সচল রাখে, তবে বিক্রেতাকে নিজের নগদ খেয়াল রাখতে হয়।"),
    mcq("What is a 'franchise'?", ["Permission to run a business using another company's brand and system", "A free shop", "A government office", "A loan"], 0,
        "The franchise owner pays the brand a fee and follows its rules.",
        "'ফ্র্যাঞ্চাইজ' কী?", ["অন্য কোম্পানির ব্র্যান্ড আর পদ্ধতিতে ব্যবসা চালানোর অনুমতি", "বিনামূল্যের দোকান", "সরকারি অফিস", "ঋণ"],
        "ফ্র্যাঞ্চাইজ-মালিক ব্র্যান্ডকে ফি দেন আর তার নিয়ম মানেন।"),
    mcq("What is an 'online marketplace'?", ["A website where many sellers offer goods to buyers", "A street market at night", "A bank", "A factory"], 0,
        "Many small businesses now sell through online marketplaces.",
        "'অনলাইন মার্কেটপ্লেস' কী?", ["যে ওয়েবসাইটে অনেক বিক্রেতা ক্রেতাদের মাল দেন", "রাতের রাস্তার বাজার", "ব্যাংক", "কারখানা"],
        "অনেক ছোট ব্যবসা এখন অনলাইন মার্কেটপ্লেসে বেচে।"),
    mcq("Why must online sellers think about delivery costs?", ["Delivery adds to the cost of each order", "Delivery is always free for sellers", "Customers pay nothing", "It does not matter"], 0,
        "Shipping is part of the real cost of selling online.",
        "অনলাইন বিক্রেতাদের ডেলিভারি খরচ নিয়ে ভাবতে হয় কেন?", ["ডেলিভারি প্রতিটি অর্ডারের খরচে যোগ হয়", "বিক্রেতার জন্য ডেলিভারি সবসময় বিনামূল্যে", "খদ্দের কিছুই দেন না", "কিছু যায় আসে না"],
        "পাঠানোর খরচ অনলাইনে বেচার আসল খরচের অংশ।"),
    mcq("A bakery sells 200 loaves a week at Rs 30 each. Weekly revenue?", ["Rs 6,000", "Rs 230", "Rs 600", "Rs 60,000"], 0,
        "200 x 30 = 6,000.",
        "একটা বেকারি সপ্তাহে 30 টাকা করে 200টি পাউরুটি বেচে। সাপ্তাহিক আয়?", ["6,000 টাকা", "230 টাকা", "600 টাকা", "60,000 টাকা"],
        "200 x 30 = 6,000।"),
    mcq("If that bakery's weekly costs are Rs 4,500, what is its weekly profit?", ["Rs 1,500", "Rs 10,500", "Rs 4,500", "Rs 6,000"], 0,
        "6000 - 4500 = 1,500.",
        "সেই বেকারির সাপ্তাহিক খরচ 4,500 টাকা হলে সাপ্তাহিক লাভ কত?", ["1,500 টাকা", "10,500 টাকা", "4,500 টাকা", "6,000 টাকা"],
        "6000 - 4500 = 1,500।"),
    mcq("What is a 'shopkeeper's margin'?", ["The difference between buying price and selling price", "The edge of the shop", "A shelf", "A type of tax"], 0,
        "Margin pays for rent, wages and profit.",
        "'দোকানদারের মার্জিন' কী?", ["কেনা দাম আর বেচা দামের পার্থক্য", "দোকানের কিনারা", "একটা তাক", "এক রকম কর"],
        "মার্জিন থেকে ভাড়া, মজুরি আর লাভ আসে।"),
    mcq("Why might a new shop charge low prices at first?", ["To attract customers and get known", "To lose money forever", "Because prices must start low by law", "No reason"], 0,
        "An opening offer helps a business build customers - but it must reach profit later.",
        "নতুন দোকান শুরুতে কম দাম রাখতে পারে কেন?", ["খদ্দের টানতে আর পরিচিত হতে", "চিরকাল টাকা হারাতে", "আইনে কম দামে শুরু করতে হয়", "কোনো কারণ নেই"],
        "উদ্বোধনী ছাড় খদ্দের গড়তে সাহায্য করে - তবে পরে লাভে পৌঁছাতে হয়।"),
    mcq("What does 'retail price' mean?", ["The price a shop charges the final customer", "The factory price", "The wholesale price", "A free price"], 0,
        "Retail prices include the shop's margin.",
        "'খুচরো দাম' মানে কী?", ["দোকান শেষ খদ্দেরের থেকে যে দাম নেয়", "কারখানার দাম", "পাইকারি দাম", "বিনামূল্যের দাম"],
        "খুচরো দামে দোকানের মার্জিন থাকে।"),
    mcq("What does 'wholesale price' mean?", ["The lower price paid by shops buying in bulk", "The price for one item in a shop", "A sale price", "A tax"], 0,
        "Shops buy wholesale and sell retail.",
        "'পাইকারি দাম' মানে কী?", ["দোকান একসঙ্গে অনেক কেনার সময় যে কম দাম দেয়", "দোকানে একটা জিনিসের দাম", "সেলের দাম", "কর"],
        "দোকান পাইকারি দামে কেনে আর খুচরো দামে বেচে।"),
    mcq("A shop buys 50 kites wholesale for Rs 1,000 and sells each for Rs 35. Profit if all sell?", ["Rs 750", "Rs 1,750", "Rs 1,000", "Rs 35"], 0,
        "Revenue 50 x 35 = 1,750; minus cost 1,000 = Rs 750.",
        "একটা দোকান পাইকারি 1,000 টাকায় 50টি ঘুড়ি কিনে প্রতিটি 35 টাকায় বেচে। সব বিক্রি হলে লাভ?", ["750 টাকা", "1,750 টাকা", "1,000 টাকা", "35 টাকা"],
        "আয় 50 x 35 = 1,750; খরচ 1,000 বাদ = 750 টাকা।"),
    mcq("What happens to sales of ice cream when the price goes up a lot?", ["They usually fall", "They always rise", "Nothing changes", "Ice cream disappears"], 0,
        "Higher prices put some customers off.",
        "আইসক্রিমের দাম অনেক বাড়লে বিক্রির কী হয়?", ["সাধারণত কমে", "সবসময় বাড়ে", "কিছুই বদলায় না", "আইসক্রিম উধাও হয়"],
        "বেশি দাম কিছু খদ্দেরকে দূরে সরায়।"),
    mcq("Why do toll bridges sometimes charge less at night?", ["To spread traffic out from busy times", "Night is free", "Bridges are weaker in the day", "No reason"], 0,
        "Different prices at different times can reduce jams - like congestion charging.",
        "টোল সেতু কখনো রাতে কম টোল নেয় কেন?", ["ব্যস্ত সময় থেকে যানবাহন ছড়িয়ে দিতে", "রাত বিনামূল্যে", "দিনে সেতু দুর্বল", "কোনো কারণ নেই"],
        "সময়ভেদে ভিন্ন দাম যানজট কমাতে পারে - যানজট-মাশুলের মতো।"),
    mcq("What is 'customer loyalty'?", ["Customers choosing the same business again and again", "Customers never buying", "Customers complaining", "Customers stealing"], 0,
        "Loyal customers are valuable - businesses reward them.",
        "'খদ্দেরের আনুগত্য' কী?", ["খদ্দের বারবার একই ব্যবসা বাছেন", "খদ্দের কখনো কেনেন না", "খদ্দের অভিযোগ করেন", "খদ্দের চুরি করেন"],
        "অনুগত খদ্দের মূল্যবান - ব্যবসা তাদের পুরস্কার দেয়।"),
    mcq("What is 'packaging' design for?", ["Protecting goods and attracting buyers", "Hiding the product", "Making it heavier", "Raising tax"], 0,
        "Good packaging keeps products safe and stands out on shelves.",
        "মোড়কের নকশা কীসের জন্য?", ["মাল রক্ষা আর ক্রেতা আকর্ষণ", "পণ্য লুকানো", "ভারী করা", "কর বাড়ানো"],
        "ভালো মোড়ক পণ্য নিরাপদ রাখে আর তাকে আলাদা করে তোলে।"),
    mcq("Why are many companies using less plastic packaging?", ["Customers and laws want less waste", "Plastic is too cheap", "Paper is magic", "Packaging is banned"], 0,
        "Greener packaging cuts pollution and can attract customers.",
        "অনেক কোম্পানি কম প্লাস্টিকের মোড়ক ব্যবহার করছে কেন?", ["খদ্দের আর আইন কম বর্জ্য চায়", "প্লাস্টিক খুব সস্তা", "কাগজ জাদুর", "মোড়ক নিষিদ্ধ"],
        "পরিবেশবান্ধব মোড়ক দূষণ কমায় আর খদ্দের টানতে পারে।"),
    mcq("What is an 'export'?", ["A product sold to another country", "A product bought from another country", "A local sale", "A gift"], 0,
        "Exports bring money into a country.",
        "'রপ্তানি' কী?", ["অন্য দেশে বেচা পণ্য", "অন্য দেশ থেকে কেনা পণ্য", "স্থানীয় বিক্রি", "উপহার"],
        "রপ্তানি দেশে টাকা আনে।"),
    mcq("What is an 'import'?", ["A product bought from another country", "A product sold abroad", "A tax", "A coin"], 0,
        "Imports bring in goods a country does not make enough of.",
        "'আমদানি' কী?", ["অন্য দেশ থেকে কেনা পণ্য", "বিদেশে বেচা পণ্য", "কর", "পয়সা"],
        "আমদানি এমন জিনিস আনে, যা দেশ যথেষ্ট বানায় না।"),
    mcq("Why do ports, rail lines and bridges matter for exports?", ["Goods must reach ships and borders quickly and cheaply", "They are decorations", "They make goods heavier", "They do not matter"], 0,
        "Good infrastructure helps a country's businesses sell abroad.",
        "রপ্তানির জন্য বন্দর, রেলপথ আর সেতু জরুরি কেন?", ["মালকে দ্রুত আর সস্তায় জাহাজ আর সীমান্তে পৌঁছাতে হয়", "এগুলো সাজসজ্জা", "মাল ভারী করে", "জরুরি নয়"],
        "ভালো পরিকাঠামো দেশের ব্যবসাকে বিদেশে বেচতে সাহায্য করে।"),
    mcq("What is a 'tariff'?", ["A tax on imported goods", "A free gift", "A type of bridge", "A discount"], 0,
        "Tariffs make imports dearer, which can protect local businesses.",
        "'শুল্ক' (ট্যারিফ) কী?", ["আমদানি মালের উপর কর", "বিনামূল্যের উপহার", "এক রকম সেতু", "ছাড়"],
        "শুল্ক আমদানিকে দামি করে, যা স্থানীয় ব্যবসাকে রক্ষা করতে পারে।"),
    mcq("What is a 'start-up'?", ["A new young business", "A car engine", "An old factory", "A bank vault"], 0,
        "Start-ups often begin small with a new idea.",
        "'স্টার্ট-আপ' কী?", ["নতুন তরুণ ব্যবসা", "গাড়ির ইঞ্জিন", "পুরোনো কারখানা", "ব্যাংকের ভল্ট"],
        "স্টার্ট-আপ প্রায়ই নতুন ধারণা নিয়ে ছোট আকারে শুরু হয়।"),
    mcq("What is a 'business plan'?", ["A written plan of what a business will sell, its costs, prices and goals", "A drawing of a shop", "A loan only", "A shopping list"], 0,
        "Banks and investors read business plans before lending - like the Business Plan screen in MODIS BridgeWorks.",
        "'ব্যবসার পরিকল্পনা' কী?", ["ব্যবসা কী বেচবে, খরচ, দাম আর লক্ষ্যের লিখিত পরিকল্পনা", "দোকানের ছবি", "শুধু ঋণ", "বাজারের তালিকা"],
        "ঋণ দেওয়ার আগে ব্যাংক আর বিনিয়োগকারীরা ব্যবসার পরিকল্পনা পড়েন - MODIS BridgeWorks-এর ব্যবসার-পরিকল্পনার পর্দার মতো।"),
    mcq("Why does a bank want to see a business plan before giving a loan?", ["To check the business can repay", "To copy the idea", "To decorate the bank", "No reason"], 0,
        "Lenders want evidence that income will cover repayments.",
        "ঋণ দেওয়ার আগে ব্যাংক ব্যবসার পরিকল্পনা দেখতে চায় কেন?", ["ব্যবসা শোধ করতে পারবে কিনা যাচাই করতে", "ধারণা নকল করতে", "ব্যাংক সাজাতে", "কোনো কারণ নেই"],
        "ঋণদাতা প্রমাণ চান যে আয় দিয়ে কিস্তি মিটবে।"),
    mcq("What is 'overhead' in a business?", ["Regular running costs like rent, electricity and insurance", "The roof only", "Profit", "A sale"], 0,
        "Overheads must be paid even when sales are slow.",
        "ব্যবসায় 'উপরি খরচ' কী?", ["ভাড়া, বিদ্যুৎ আর বিমার মতো নিয়মিত চালানোর খরচ", "শুধু ছাদ", "লাভ", "একটা সেল"],
        "বিক্রি কম হলেও উপরি খরচ দিতে হয়।"),
    mcq("A café's overheads are Rs 20,000 a month. It makes Rs 25 profit per meal before overheads. How many meals to break even?", ["800", "500", "1000", "200"], 0,
        "20,000 ÷ 25 = 800 meals.",
        "একটা ক্যাফের উপরি খরচ মাসে 20,000 টাকা। উপরি খরচের আগে প্রতি খাবারে লাভ 25 টাকা। লাভ-লোকসান সমান করতে কতটি খাবার?", ["800", "500", "1000", "200"],
        "20,000 ÷ 25 = 800টি খাবার।"),
    mcq("What is 'stock rotation' in a food shop?", ["Selling older items first so nothing goes out of date", "Spinning the shelves", "Hiding old food", "Throwing new food away"], 0,
        "First in, first out reduces waste.",
        "খাবারের দোকানে 'মজুত ঘোরানো' কী?", ["পুরোনো জিনিস আগে বেচা, যাতে কিছু মেয়াদ না পেরোয়", "তাক ঘোরানো", "পুরোনো খাবার লুকানো", "নতুন খাবার ফেলে দেওয়া"],
        "আগে এলে আগে যাবে - এতে অপচয় কমে।"),
    mcq("Why might a shop give food close to its date to a food bank?", ["To help people in need instead of wasting it", "To lose customers", "Because it is poisonous", "No reason"], 0,
        "Donating surplus food helps the community and cuts waste.",
        "মেয়াদের কাছাকাছি খাবার দোকান কেন খাদ্য-ব্যাংকে দিতে পারে?", ["নষ্ট না করে অভাবীদের সাহায্য করতে", "খদ্দের হারাতে", "কারণ এটা বিষাক্ত", "কোনো কারণ নেই"],
        "বাড়তি খাবার দান সমাজকে সাহায্য করে আর অপচয় কমায়।"),
    mcq("What is 'social responsibility' for a business?", ["Caring about people, community and the environment, not just profit", "Only making money", "Ignoring customers", "Avoiding tax"], 0,
        "Many businesses support local schools, causes and green projects.",
        "ব্যবসার 'সামাজিক দায়িত্ব' কী?", ["শুধু লাভ নয়, মানুষ, সমাজ আর পরিবেশের কথা ভাবা", "শুধু টাকা রোজগার", "খদ্দের উপেক্ষা", "কর এড়ানো"],
        "অনেক ব্যবসা স্থানীয় স্কুল, ভালো কাজ আর পরিবেশ-প্রকল্পে সাহায্য করে।"),
    mcq("A construction company donates to a village footbridge camp. How can this help the company too?", ["It builds trust and a good reputation", "It makes steel cheaper", "It avoids all taxes", "It does not help"], 0,
        "Giving back builds goodwill with customers and communities.",
        "একটা নির্মাণ কোম্পানি গ্রামের হাঁটার সেতুর শিবিরে দান করল। এতে কোম্পানিরও কী উপকার?", ["বিশ্বাস আর সুনাম গড়ে", "ইস্পাত সস্তা হয়", "সব কর এড়ায়", "উপকার হয় না"],
        "সমাজকে ফিরিয়ে দিলে খদ্দের আর সমাজের সঙ্গে সদিচ্ছা গড়ে ওঠে।"),
    mcq("What is a 'sponsor'?", ["A business that pays to support an event or team in return for publicity", "A customer", "A thief", "A tax collector"], 0,
        "Sponsors help pay for events and get their name shown.",
        "'পৃষ্ঠপোষক' (স্পনসর) কে?", ["প্রচারের বিনিময়ে কোনো অনুষ্ঠান বা দলকে টাকা দেওয়া ব্যবসা", "খদ্দের", "চোর", "কর-আদায়কারী"],
        "পৃষ্ঠপোষক অনুষ্ঠানের খরচে সাহায্য করে আর তাদের নাম দেখানো হয়।"),
    mcq("A school fair sells 120 tickets at Rs 25. Costs are Rs 1,200. Profit for the school library?", ["Rs 1,800", "Rs 3,000", "Rs 1,200", "Rs 600"], 0,
        "Revenue 120 x 25 = 3,000; minus 1,200 = 1,800.",
        "একটা স্কুলমেলায় 25 টাকায় 120টি টিকিট বিক্রি হলো। খরচ 1,200 টাকা। স্কুল-লাইব্রেরির জন্য লাভ?", ["1,800 টাকা", "3,000 টাকা", "1,200 টাকা", "600 টাকা"],
        "আয় 120 x 25 = 3,000; 1,200 বাদ = 1,800।"),
    mcq("Why do businesses train their workers?", ["Skilled workers do better, safer work", "Training is a waste", "To slow work down", "It is required for fun"], 0,
        "Training improves quality, safety and speed.",
        "ব্যবসা কর্মীদের প্রশিক্ষণ দেয় কেন?", ["দক্ষ কর্মী ভালো আর নিরাপদ কাজ করেন", "প্রশিক্ষণ অপচয়", "কাজ ধীর করতে", "মজার জন্য বাধ্যতামূলক"],
        "প্রশিক্ষণ মান, নিরাপত্তা আর গতি বাড়ায়।"),
    mcq("What is a 'deadline' in a business contract?", ["The date by which work must be finished", "A broken line", "A type of bridge", "A price"], 0,
        "Late work can bring penalties - like the time limits in some MODIS BridgeWorks levels.",
        "ব্যবসার চুক্তিতে 'সময়সীমা' কী?", ["যে তারিখের মধ্যে কাজ শেষ করতে হবে", "ভাঙা রেখা", "এক রকম সেতু", "একটা দাম"],
        "দেরির কাজে জরিমানা হতে পারে - MODIS BridgeWorks-এর কিছু লেভেলের সময়সীমার মতো।"),
    mcq("A freight company promises delivery in 24 hours. Why must it plan trucks, trains and barges carefully?", ["To meet the deadline at the lowest cost", "To use as many trucks as possible", "To waste fuel", "Planning is not needed"], 0,
        "Smart mixes of transport meet deadlines cheaply - the challenge of Level 9.",
        "একটা মালবাহী কোম্পানি 24 ঘণ্টায় পৌঁছানোর প্রতিশ্রুতি দেয়। ট্রাক, ট্রেন আর বার্জ সাবধানে পরিকল্পনা করতে হয় কেন?", ["সবচেয়ে কম খরচে সময়সীমা মানতে", "যত বেশি সম্ভব ট্রাক ব্যবহার করতে", "জ্বালানি নষ্ট করতে", "পরিকল্পনা দরকার নেই"],
        "পরিবহনের বুদ্ধিমান মিশ্রণ সস্তায় সময়সীমা মেটায় - লেভেল 9-এর চ্যালেঞ্জ।"),
    mcq("What is 'productivity'?", ["How much is produced for the time and effort used", "How many shops exist", "A price list", "A tax"], 0,
        "Better tools and training raise productivity.",
        "'উৎপাদনশীলতা' কী?", ["ব্যবহৃত সময় আর পরিশ্রমে কতটা উৎপাদন হয়", "কতগুলো দোকান আছে", "দামের তালিকা", "কর"],
        "ভালো যন্ত্র আর প্রশিক্ষণ উৎপাদনশীলতা বাড়ায়।"),
    mcq("A worker builds 4 metres of fence an hour; with a new tool, 6 metres. By how much did productivity rise?", ["2 metres an hour (50% more)", "6 metres an hour", "10 metres an hour", "It fell"], 0,
        "6 - 4 = 2 m more each hour; 2 ÷ 4 = 50% more.",
        "একজন কর্মী ঘণ্টায় 4 মিটার বেড়া বানান; নতুন যন্ত্রে 6 মিটার। উৎপাদনশীলতা কত বাড়ল?", ["ঘণ্টায় 2 মিটার (50% বেশি)", "ঘণ্টায় 6 মিটার", "ঘণ্টায় 10 মিটার", "কমে গেছে"],
        "6 - 4 = প্রতি ঘণ্টায় 2 m বেশি; 2 ÷ 4 = 50% বেশি।"),
    mcq("Why do many shops open on festival days even though staff want holidays?", ["Demand is high and many people shop then", "It is required by law", "No customers come", "To close early"], 0,
        "Businesses balance customer demand with staff needs - often with extra pay.",
        "কর্মীরা ছুটি চাইলেও অনেক দোকান উৎসবের দিনে খোলা থাকে কেন?", ["চাহিদা বেশি আর তখন অনেকে কেনাকাটা করে", "আইনে বাধ্যতামূলক", "কোনো খদ্দের আসে না", "তাড়াতাড়ি বন্ধ করতে"],
        "ব্যবসা খদ্দেরের চাহিদা আর কর্মীদের প্রয়োজনের মধ্যে ভারসাম্য রাখে - প্রায়ই বাড়তি বেতন দিয়ে।"),
    mcq("A bridge opens and a village's farmers can now sell to a city market. What happens to their income?", ["It can grow because they reach more buyers", "It falls", "Nothing", "They stop farming"], 0,
        "Access to bigger markets raises incomes - one of the biggest benefits of rural bridges.",
        "একটা সেতু খুলল আর গ্রামের চাষিরা এখন শহরের বাজারে বেচতে পারেন। তাঁদের আয়ের কী হয়?", ["বেশি ক্রেতার কাছে পৌঁছানোয় বাড়তে পারে", "কমে", "কিছুই না", "চাষ থামিয়ে দেন"],
        "বড় বাজারে পৌঁছালে আয় বাড়ে - গ্রামের সেতুর সবচেয়ে বড় উপকারের একটি।"),
    mcq("What is a 'cooperative'?", ["A business owned and run by its members, who share the benefits", "A single owner shop", "A bank robbery", "A government tax"], 0,
        "Farmers' cooperatives buy seeds and sell crops together to get better prices.",
        "'সমবায়' কী?", ["সদস্যদের মালিকানা আর পরিচালনার ব্যবসা, যাঁরা সুবিধা ভাগ করেন", "একক মালিকের দোকান", "ব্যাংক ডাকাতি", "সরকারি কর"],
        "চাষিদের সমবায় একসঙ্গে বীজ কেনে আর ফসল বেচে ভালো দাম পায়।"),
    mcq("Why do farmers in a cooperative get better prices?", ["Together they sell larger amounts and bargain better", "They sell nothing", "Cooperatives are illegal", "Prices are fixed at zero"], 0,
        "Bigger, shared deals give small farmers more power.",
        "সমবায়ে চাষিরা ভালো দাম পান কেন?", ["একসঙ্গে বেশি পরিমাণ বেচে ভালো দরাদরি করেন", "কিছুই বেচেন না", "সমবায় বেআইনি", "দাম শূন্যে বাঁধা"],
        "বড়, যৌথ চুক্তি ছোট চাষিদের বেশি ক্ষমতা দেয়।"),
    mcq("What is a 'price war'?", ["Competing shops keep cutting prices to win customers", "A war about prices only in history", "Raising all prices", "A tax"], 0,
        "Customers gain short-term, but businesses can lose money.",
        "'দামের লড়াই' কী?", ["প্রতিযোগী দোকান খদ্দের পেতে বারবার দাম কমায়", "ইতিহাসে শুধু দাম নিয়ে যুদ্ধ", "সব দাম বাড়ানো", "কর"],
        "খদ্দের সাময়িক লাভবান হন, কিন্তু ব্যবসা টাকা হারাতে পারে।"),
    mcq("What does 'out of stock' mean?", ["The shop has none of that item left", "The item is free", "The item is new", "The shop is closed"], 0,
        "Good stock planning avoids disappointing customers.",
        "'মজুত শেষ' মানে কী?", ["দোকানে সেই জিনিস আর একটাও নেই", "জিনিসটা বিনামূল্যে", "জিনিসটা নতুন", "দোকান বন্ধ"],
        "ভালো মজুত-পরিকল্পনা খদ্দেরকে হতাশ হতে দেয় না।"),
    mcq("A shop sells 15 umbrellas a day in the rainy season. How many should it stock for a 30-day month?", ["About 450", "About 15", "About 45", "About 4500"], 0,
        "15 x 30 = 450.",
        "একটা দোকান বর্ষায় দিনে 15টি ছাতা বেচে। 30 দিনের মাসের জন্য কত মজুত রাখা উচিত?", ["প্রায় 450", "প্রায় 15", "প্রায় 45", "প্রায় 4500"],
        "15 x 30 = 450।"),
    mcq("What is the main reason a bridge is built with tolls rather than for free?", ["Tolls pay back the cost and fund maintenance", "To annoy drivers", "Tolls make the bridge stronger", "Free bridges are illegal"], 0,
        "The users of a bridge help pay for it over time.",
        "টোল-ছাড়া না করে টোলসহ সেতু বানানোর প্রধান কারণ কী?", ["টোল খরচ শোধ করে আর রক্ষণাবেক্ষণের টাকা দেয়", "চালকদের বিরক্ত করতে", "টোল সেতু শক্ত করে", "বিনামূল্যের সেতু বেআইনি"],
        "সেতুর ব্যবহারকারীরা সময়ের সঙ্গে তার খরচ দিতে সাহায্য করেন।"),
    mcq("Which helps a small business sell more without spending much?", ["Happy customers telling their friends", "Expensive TV adverts only", "Closing on busy days", "Hiding prices"], 0,
        "Word of mouth is free and powerful advertising.",
        "কোনটা ছোট ব্যবসাকে কম খরচে বেশি বেচতে সাহায্য করে?", ["খুশি খদ্দের বন্ধুদের বলে", "শুধু দামি টিভি বিজ্ঞাপন", "ব্যস্ত দিনে বন্ধ রাখা", "দাম লুকানো"],
        "মুখে মুখে প্রচার বিনামূল্যের আর শক্তিশালী বিজ্ঞাপন।"),
    mcq("Why do businesses compare their costs each month?", ["To spot rising costs early and fix them", "To waste paper", "To confuse workers", "No reason"], 0,
        "Watching costs keeps a business healthy.",
        "ব্যবসা প্রতি মাসে খরচ তুলনা করে কেন?", ["বাড়তে থাকা খরচ আগেই ধরে ঠিক করতে", "কাগজ নষ্ট করতে", "কর্মীদের বিভ্রান্ত করতে", "কোনো কারণ নেই"],
        "খরচে নজর রাখলে ব্যবসা সুস্থ থাকে।"),
    margin(40, 55, 20, "torches", "টর্চ"),
    margin(10, 14, 75, "pencil boxes", "পেনসিল-বাক্স"),
    margin(250, 320, 5, "helmets", "হেলমেট"),
    margin(6, 10, 90, "cups of tea", "কাপ চা"),
    mcq("What is a 'receipt'?", ["Proof that you paid for something", "A bill you have not paid yet", "A shopping list", "A recipe"], 0,
        "Keep receipts in case you need to return or exchange an item.",
        "'রসিদ' কী?", ["কোনো কিছুর দাম দেওয়ার প্রমাণ", "এখনো না-মেটানো বিল", "বাজারের তালিকা", "রান্নার প্রণালী"],
        "জিনিস ফেরত বা বদলের দরকার হলে রসিদ রেখে দাও।"),
    mcq("What is a 'bulk discount'?", ["A lower price for each item when you buy many", "A higher price for big items", "A free item for nothing", "A tax on large orders"], 0,
        "Builders buying 1,000 bags of cement pay less per bag than someone buying one.",
        "'একসঙ্গে কেনার ছাড়' কী?", ["অনেক কিনলে প্রতিটির কম দাম", "বড় জিনিসের বেশি দাম", "এমনি বিনামূল্যের জিনিস", "বড় অর্ডারে কর"],
        "1,000 বস্তা সিমেন্ট কেনা নির্মাতা একটা কেনা মানুষের চেয়ে প্রতি বস্তায় কম দেন।"),
    mcq("Cement costs Rs 400 a bag, or Rs 380 a bag for 100 bags or more. How much is saved on 100 bags?", ["Rs 2,000", "Rs 20", "Rs 380", "Rs 4,000"], 0,
        "Saving 20 per bag x 100 = Rs 2,000.",
        "সিমেন্টের দাম বস্তাপ্রতি 400 টাকা, কিন্তু 100 বা বেশি বস্তায় 380 টাকা। 100 বস্তায় কত বাঁচে?", ["2,000 টাকা", "20 টাকা", "380 টাকা", "4,000 টাকা"],
        "বস্তাপ্রতি 20 বাঁচে x 100 = 2,000 টাকা।"),
    mcq("What is a 'supplier'?", ["A business that provides goods or materials to another business", "A customer", "A shop thief", "A judge"], 0,
        "A bridge builder's suppliers sell it steel, cement and bolts.",
        "'সরবরাহকারী' কে?", ["যে ব্যবসা অন্য ব্যবসাকে মাল বা উপাদান দেয়", "খদ্দের", "দোকান-চোর", "বিচারক"],
        "সেতু-নির্মাতার সরবরাহকারীরা তাকে ইস্পাত, সিমেন্ট আর বোল্ট বেচে।"),
    mcq("Why is it risky to depend on only one supplier?", ["If it has a problem, your work stops", "One supplier is always cheaper", "Suppliers never have problems", "It is not risky"], 0,
        "Having backup suppliers keeps projects on time.",
        "মাত্র একজন সরবরাহকারীর উপর নির্ভর করা ঝুঁকির কেন?", ["তার সমস্যা হলে তোমার কাজ থেমে যায়", "একজন সরবরাহকারী সবসময় সস্তা", "সরবরাহকারীর কখনো সমস্যা হয় না", "ঝুঁকি নেই"],
        "বিকল্প সরবরাহকারী রাখলে প্রকল্প সময়মতো চলে।"),
    mcq("What does 'demand' mean in business?", ["How much of a product people want to buy", "A shouted order", "The factory size", "A government rule"], 0,
        "Demand for umbrellas rises in the rainy season.",
        "ব্যবসায় 'চাহিদা' মানে কী?", ["মানুষ একটা পণ্য কতটা কিনতে চায়", "চিৎকার করে দেওয়া হুকুম", "কারখানার আকার", "সরকারি নিয়ম"],
        "বর্ষায় ছাতার চাহিদা বাড়ে।"),
    mcq("What does 'supply' mean in business?", ["How much of a product sellers offer for sale", "A school supply shop only", "What customers want", "A bank deposit"], 0,
        "When supply is short and demand is high, prices tend to rise.",
        "ব্যবসায় 'জোগান' মানে কী?", ["বিক্রেতারা একটা পণ্য কতটা বেচতে দেন", "শুধু স্কুল-সামগ্রীর দোকান", "খদ্দের কী চায়", "ব্যাংকে জমা"],
        "জোগান কম আর চাহিদা বেশি হলে দাম বাড়ার ঝোঁক থাকে।"),
    mcq("After a flood breaks the road, vegetables in town get dearer. Why?", ["Less supply reaches town while people still need food", "Vegetables grew bigger", "Shops got lazy", "Demand fell"], 0,
        "Broken transport cuts supply - repairing bridges and roads brings prices back down.",
        "বন্যায় রাস্তা ভাঙার পর শহরে সবজির দাম বাড়ে। কেন?", ["মানুষের খাবার লাগলেও শহরে কম জোগান পৌঁছায়", "সবজি বড় হয়েছে", "দোকান অলস হয়েছে", "চাহিদা কমেছে"],
        "যাতায়াত ভাঙলে জোগান কমে - সেতু আর রাস্তা সারালে দাম আবার নামে।"),
)
