"""Class 3 - Physics: forces in newtons, friction and air resistance, magnets, simple circuits,
light and shadows, sound, Earth and space, and how structures stay up."""
from . import mcq

ITEMS = (
    mcq("What is the unit we use to measure force?", ["Newton (N)", "Metre (m)", "Kilogram (kg)", "Litre (l)"], 0,
        "Forces are measured in newtons, named after Isaac Newton. An apple weighs about 1 N.",
        "বল মাপার একক কী?", ["নিউটন (N)", "মিটার (m)", "কিলোগ্রাম (kg)", "লিটার (l)"],
        "বল মাপা হয় নিউটনে, আইজ্যাক নিউটনের নামে। একটা আপেলের ওজন প্রায় 1 N।"),
    mcq("Which tool measures force?", ["A force meter (newton meter)", "A ruler", "A thermometer", "A clock"], 0,
        "A force meter has a spring inside: the bigger the pull, the more the spring stretches.",
        "কোন যন্ত্র বল মাপে?", ["বলমাপক যন্ত্র (নিউটন মিটার)", "রুলার", "থার্মোমিটার", "ঘড়ি"],
        "বলমাপকের ভেতরে স্প্রিং থাকে: টান যত বড়, স্প্রিং তত লম্বা হয়।"),
    mcq("A 1 kg bag of sugar weighs about...", ["10 N", "1 N", "100 N", "0 N"], 0,
        "On Earth each kilogram is pulled down with about 10 newtons (more exactly 9.81 N).",
        "1 kg চিনির ব্যাগের ওজন প্রায়...", ["10 N", "1 N", "100 N", "0 N"],
        "পৃথিবীতে প্রতি কিলোগ্রাম প্রায় 10 নিউটনে নিচে টানা হয় (আরও ঠিকভাবে 9.81 N)।"),
    mcq("What is the difference between mass and weight?", ["Mass is how much stuff; weight is the pull of gravity on it", "They are always the same word", "Weight is measured in metres", "Mass changes on the Moon"], 0,
        "Your mass is the same on the Moon, but your weight is about 6 times smaller there.",
        "ভর আর ওজনের পার্থক্য কী?", ["ভর হলো কত পদার্থ; ওজন হলো তার উপর মাধ্যাকর্ষণের টান", "দুটো সবসময় একই শব্দ", "ওজন মিটারে মাপা হয়", "চাঁদে ভর বদলায়"],
        "চাঁদে তোমার ভর একই থাকে, কিন্তু ওজন সেখানে প্রায় 6 গুণ কম।"),
    mcq("A 20 tonne truck weighs about how many newtons on a bridge?", ["200,000 N", "20 N", "2,000 N", "20,000,000 N"], 0,
        "20 tonnes = 20,000 kg; x 10 N per kg = 200,000 N (200 kN). That is what the bridge must hold.",
        "20 টনের একটা ট্রাক সেতুর উপর প্রায় কত নিউটন ওজন দেয়?", ["2,00,000 N", "20 N", "2,000 N", "2,00,00,000 N"],
        "20 টন = 20,000 kg; প্রতি kg-এ 10 N গুণ করলে 2,00,000 N (200 kN)। সেতুকে এটাই ধরতে হয়।"),
    mcq("Two forces of 10 N pull in opposite directions on a box. What happens?", ["The box stays still - the forces balance", "It moves left fast", "It moves right fast", "It flies up"], 0,
        "Balanced forces cancel. A bridge that stands still has all its forces balanced.",
        "একটা বাক্সকে 10 N-এর দুটি বল উল্টো দিকে টানছে। কী হয়?", ["বাক্স স্থির থাকে - বলগুলো ভারসাম্যে", "জোরে বাঁয়ে যায়", "জোরে ডানে যায়", "উপরে ওড়ে"],
        "সমান বল একে অপরকে কাটাকাটি করে। যে সেতু স্থির দাঁড়িয়ে আছে, তার সব বল ভারসাম্যে।"),
    mcq("A box is pushed with 15 N to the right and 5 N to the left. What is the overall force?", ["10 N to the right", "20 N to the right", "10 N to the left", "0 N"], 0,
        "Subtract opposite forces: 15 - 5 = 10 N towards the bigger push.",
        "একটা বাক্সকে ডানে 15 N আর বাঁয়ে 5 N ঠেলা হচ্ছে। মোট বল কত?", ["ডানে 10 N", "ডানে 20 N", "বাঁয়ে 10 N", "0 N"],
        "উল্টো বল বিয়োগ করো: 15 - 5 = বড় ঠেলার দিকে 10 N।"),
    mcq("Unbalanced forces on an object make it...", ["Change speed or direction", "Stay exactly the same", "Disappear", "Get colder"], 0,
        "A net force speeds things up, slows them down or turns them.",
        "কোনো বস্তুর উপর অসাম্য বল তাকে...", ["গতি বা দিক বদলায়", "একদম একই রাখে", "উধাও করে", "ঠান্ডা করে"],
        "নিট বল জিনিসের গতি বাড়ায়, কমায় বা দিক ঘোরায়।"),
    mcq("What is air resistance?", ["Friction from air pushing against moving things", "Air making things heavier", "Wind turning off", "A kind of magnet"], 0,
        "Air resistance (drag) slows parachutes, cyclists and even trains at high speed.",
        "বায়ুর বাধা কী?", ["চলন্ত জিনিসের বিরুদ্ধে বাতাসের ঠেলা থেকে ঘর্ষণ", "বাতাস জিনিসকে ভারী করে", "বাতাস বন্ধ হওয়া", "এক রকম চুম্বক"],
        "বায়ুর বাধা (টান) প্যারাসুট, সাইকেল-চালক, এমনকি দ্রুতগতির ট্রেনকেও ধীর করে।"),
    mcq("Which shape has the least air resistance?", ["A pointed, streamlined shape", "A flat square sheet facing the wind", "An open umbrella", "A parachute"], 0,
        "Streamlined shapes let air flow smoothly around them.",
        "কোন আকারে বায়ুর বাধা সবচেয়ে কম?", ["সূচালো, মসৃণ লম্বাটে আকার", "বাতাসের মুখোমুখি সমতল বর্গ পাত", "খোলা ছাতা", "প্যারাসুট"],
        "মসৃণ লম্বাটে আকারে বাতাস চারপাশ দিয়ে সহজে বয়ে যায়।"),
    mcq("Water resistance slows a swimmer. How do fish reduce it?", ["Smooth, streamlined bodies", "Spiky skin", "Square shapes", "Swimming backwards"], 0,
        "Smooth, pointed bodies cut through water with less drag.",
        "জলের বাধা সাঁতারুকে ধীর করে। মাছ কীভাবে তা কমায়?", ["মসৃণ, লম্বাটে শরীর", "কাঁটাওয়ালা চামড়া", "বর্গাকার আকার", "পেছনে সাঁতার কেটে"],
        "মসৃণ, সূচালো শরীর কম বাধায় জল কেটে এগোয়।"),
    mcq("Which surface gives the most friction for a shoe?", ["Rough rubber on concrete", "Socks on a polished floor", "Ice skates on ice", "A wet plastic slide"], 0,
        "Rough surfaces and rubber grip strongly.",
        "জুতোর জন্য কোন তলে সবচেয়ে বেশি ঘর্ষণ?", ["কংক্রিটে খসখসে রাবার", "পালিশ করা মেঝেতে মোজা", "বরফে আইস-স্কেট", "ভেজা প্লাস্টিকের স্লাইড"],
        "খসখসে তল আর রাবার জোরে আঁকড়ে ধরে।"),
    mcq("Why is friction useful for car brakes?", ["Rubbing pads slow the wheels", "It makes the car lighter", "It makes the engine louder", "It is not useful"], 0,
        "Brake pads press on spinning discs; the friction turns motion into heat.",
        "গাড়ির ব্রেকে ঘর্ষণ কাজে লাগে কেন?", ["ঘষা প্যাড চাকা ধীর করে", "গাড়ি হালকা করে", "ইঞ্জিন জোরে চলে", "কাজে লাগে না"],
        "ব্রেক প্যাড ঘুরন্ত চাকতিতে চাপ দেয়; ঘর্ষণ গতিকে তাপে বদলায়।"),
    mcq("When is friction a nuisance?", ["It wears out machine parts and wastes energy", "When walking on a dry path", "When writing with a pencil", "When striking a match"], 0,
        "In engines, friction causes wear and heat, so we use oil and bearings.",
        "ঘর্ষণ কখন অসুবিধা?", ["যন্ত্রাংশ ক্ষয় করে আর শক্তি নষ্ট করে", "শুকনো পথে হাঁটার সময়", "পেনসিলে লেখার সময়", "দেশলাই জ্বালানোর সময়"],
        "ইঞ্জিনে ঘর্ষণ ক্ষয় আর তাপ ঘটায়, তাই তেল আর বিয়ারিং ব্যবহার হয়।"),
    mcq("What are ball bearings for?", ["To let parts roll smoothly with little friction", "To make noise", "To add weight", "To glue parts"], 0,
        "Rolling balls replace sliding, cutting friction - wheels and bridge bearings use the idea.",
        "বল বিয়ারিং কীসের জন্য?", ["কম ঘর্ষণে অংশগুলো মসৃণভাবে গড়াতে দিতে", "শব্দ করতে", "ওজন বাড়াতে", "অংশ জুড়তে"],
        "গড়ানো বল পিছলানোর জায়গা নেয়, ঘর্ষণ কমায় - চাকা আর সেতুর বিয়ারিং এই ধারণা নেয়।"),
    mcq("Which part of a magnet is strongest?", ["The poles (ends)", "The middle", "The painted part", "All parts are equal"], 0,
        "Magnetic force is strongest at the north and south poles.",
        "চুম্বকের কোন অংশ সবচেয়ে শক্তিশালী?", ["মেরু (প্রান্ত)", "মাঝখান", "রং করা অংশ", "সব অংশ সমান"],
        "চৌম্বক বল উত্তর আর দক্ষিণ মেরুতে সবচেয়ে বেশি।"),
    mcq("Which of these metals is attracted to a magnet?", ["Iron", "Aluminium", "Copper", "Gold"], 0,
        "Iron, nickel and cobalt (and steel) are magnetic; most other metals are not.",
        "এই ধাতুগুলোর কোনটাকে চুম্বক টানে?", ["লোহা", "অ্যালুমিনিয়াম", "তামা", "সোনা"],
        "লোহা, নিকেল আর কোবাল্ট (আর ইস্পাত) চৌম্বক; বেশিরভাগ অন্য ধাতু নয়।"),
    mcq("How can scrapyards lift cars with a giant magnet?", ["Car bodies contain lots of steel", "Cars are made of wood", "Magnets lift anything", "The cars are empty"], 0,
        "Steel is magnetic, so an electromagnet can lift whole car bodies.",
        "ভাঙারিখানা বিশাল চুম্বকে গাড়ি তোলে কীভাবে?", ["গাড়ির কাঠামোয় অনেক ইস্পাত থাকে", "গাড়ি কাঠের তৈরি", "চুম্বক যেকোনো কিছু তোলে", "গাড়িগুলো ফাঁকা"],
        "ইস্পাত চৌম্বক, তাই তড়িৎচুম্বক পুরো গাড়ির কাঠামো তুলতে পারে।"),
    mcq("What is an electromagnet?", ["A magnet made by electricity flowing through a coil", "A magnet made of plastic", "A battery", "A light bulb"], 0,
        "Switch the current on and it is a magnet; switch it off and the magnetism stops.",
        "তড়িৎচুম্বক কী?", ["কুণ্ডলীতে বিদ্যুৎ চালিয়ে তৈরি চুম্বক", "প্লাস্টিকের চুম্বক", "ব্যাটারি", "বাল্ব"],
        "বিদ্যুৎ চালু করলে চুম্বক; বন্ধ করলে চুম্বকত্বও থামে।"),
    mcq("Maglev trains float above the track using...", ["Powerful magnets", "Wings", "Balloons", "Springs only"], 0,
        "Magnetic levitation lifts the train, so there is no wheel friction - like the maglev in MODIS BridgeWorks Level 10!",
        "ম্যাগলেভ ট্রেন লাইনের উপর ভাসে কীসের সাহায্যে?", ["শক্তিশালী চুম্বক", "ডানা", "বেলুন", "শুধু স্প্রিং"],
        "চৌম্বক ভাসমানতা ট্রেন তোলে, তাই চাকার ঘর্ষণ নেই - MODIS BridgeWorks-এর লেভেল 10-এর ম্যাগলেভের মতো!"),
    mcq("What does a simple circuit need to light a bulb?", ["A battery, wires and a bulb in a complete loop", "Only a bulb", "Only wires", "Water"], 0,
        "Electricity flows only around a complete, unbroken loop.",
        "বাল্ব জ্বালাতে সরল বর্তনীতে কী লাগে?", ["সম্পূর্ণ লুপে ব্যাটারি, তার আর বাল্ব", "শুধু বাল্ব", "শুধু তার", "জল"],
        "বিদ্যুৎ শুধু সম্পূর্ণ, অবিচ্ছিন্ন লুপেই চলে।"),
    mcq("What does a switch do in a circuit?", ["Opens or closes the loop", "Makes electricity", "Changes the bulb colour", "Stores water"], 0,
        "Switch off = gap in the loop, so no current flows.",
        "বর্তনীতে সুইচ কী করে?", ["লুপ খোলে বা বন্ধ করে", "বিদ্যুৎ তৈরি করে", "বাল্বের রং বদলায়", "জল জমায়"],
        "সুইচ বন্ধ = লুপে ফাঁক, তাই কোনো বিদ্যুৎ চলে না।"),
    mcq("Which material would complete a circuit and light the bulb?", ["A metal paper clip", "A rubber band", "A wooden stick", "A plastic straw"], 0,
        "Metals are conductors; rubber, wood and plastic are insulators.",
        "কোন উপাদান বর্তনী পূর্ণ করে বাল্ব জ্বালাবে?", ["ধাতুর পেপার ক্লিপ", "রাবার ব্যান্ড", "কাঠের কাঠি", "প্লাস্টিকের স্ট্র"],
        "ধাতু পরিবাহী; রাবার, কাঠ আর প্লাস্টিক অন্তরক।"),
    mcq("Why must we never play with mains electricity sockets?", ["Mains electricity can kill", "Sockets are hot", "It wastes paper", "It is boring"], 0,
        "Batteries are safe for experiments; mains electricity is dangerous.",
        "বাড়ির মূল বিদ্যুতের সকেট নিয়ে কখনো খেলা উচিত নয় কেন?", ["মূল বিদ্যুৎ প্রাণঘাতী হতে পারে", "সকেট গরম", "কাগজ নষ্ট হয়", "এটা বিরক্তিকর"],
        "পরীক্ষার জন্য ব্যাটারি নিরাপদ; বাড়ির মূল বিদ্যুৎ বিপজ্জনক।"),
    mcq("Adding a second battery to a simple bulb circuit usually makes the bulb...", ["Brighter", "Dimmer", "Go out", "Change shape"], 0,
        "More batteries push more current through the bulb.",
        "সরল বাল্ব-বর্তনীতে দ্বিতীয় ব্যাটারি যোগ করলে সাধারণত বাল্ব হয়...", ["আরও উজ্জ্বল", "আরও ম্লান", "নিভে যায়", "আকার বদলায়"],
        "বেশি ব্যাটারি বাল্বের মধ্য দিয়ে বেশি বিদ্যুৎ ঠেলে।"),
    mcq("Light travels...", ["In straight lines", "In circles", "Only at night", "Around corners easily"], 0,
        "That is why shadows have sharp edges and you cannot see around a corner.",
        "আলো চলে...", ["সোজা পথে", "বৃত্তে", "শুধু রাতে", "সহজে কোণ ঘুরে"],
        "এজন্যই ছায়ার কিনারা স্পষ্ট আর কোণের ওপাশে দেখা যায় না।"),
    mcq("A shadow forms when...", ["An opaque object blocks light", "Light passes through glass", "A mirror reflects light", "It is completely dark"], 0,
        "Opaque objects stop light, leaving a dark shape behind them.",
        "ছায়া তৈরি হয় যখন...", ["অস্বচ্ছ বস্তু আলো আটকায়", "আলো কাচ ভেদ করে", "আয়না আলো প্রতিফলিত করে", "একদম অন্ধকার"],
        "অস্বচ্ছ বস্তু আলো থামায়, পেছনে একটা অন্ধকার আকার রেখে যায়।"),
    mcq("You move a torch closer to a toy. Its shadow on the wall gets...", ["Bigger", "Smaller", "Brighter", "Disappears"], 0,
        "Closer to the light, the toy blocks more of the light spreading out, so the shadow grows.",
        "টর্চ একটা খেলনার কাছে আনলে দেয়ালে তার ছায়া হয়...", ["বড়", "ছোট", "উজ্জ্বল", "উধাও"],
        "আলোর কাছে খেলনা ছড়ানো আলোর বেশিটা আটকায়, তাই ছায়া বড় হয়।"),
    mcq("What is reflection?", ["Light bouncing off a surface", "Light being made", "Light going dark", "Light turning into sound"], 0,
        "Mirrors and shiny surfaces reflect light neatly; rough surfaces scatter it.",
        "প্রতিফলন কী?", ["তলে লেগে আলো ফিরে আসা", "আলো তৈরি হওয়া", "আলো অন্ধকার হওয়া", "আলো শব্দে বদলানো"],
        "আয়না আর চকচকে তল আলো সুন্দরভাবে প্রতিফলিত করে; খসখসে তল ছড়িয়ে দেয়।"),
    mcq("Why are road signs and cyclists' vests made reflective?", ["They bounce car headlights back so drivers see them", "To keep warm", "To look heavy", "To stop rain"], 0,
        "Reflective material sends light back towards its source - the driver's eyes.",
        "রাস্তার চিহ্ন আর সাইকেল-চালকের জ্যাকেট প্রতিফলক কেন?", ["গাড়ির হেডলাইট ফিরিয়ে দেয়, তাই চালক দেখতে পান", "গরম থাকতে", "ভারী দেখাতে", "বৃষ্টি আটকাতে"],
        "প্রতিফলক উপাদান আলোকে উৎসের দিকে - চালকের চোখে - ফেরত পাঠায়।"),
    mcq("Why should you never look straight at the Sun?", ["Its strong light can damage your eyes", "It is too far away", "It is cold", "It makes you sneeze only"], 0,
        "Even sunglasses do not make it safe to stare at the Sun.",
        "কখনো সরাসরি সূর্যের দিকে তাকানো উচিত নয় কেন?", ["এর জোরালো আলো চোখের ক্ষতি করতে পারে", "এটা খুব দূরে", "এটা ঠান্ডা", "শুধু হাঁচি হয়"],
        "রোদচশমা পরেও সূর্যের দিকে তাকিয়ে থাকা নিরাপদ নয়।"),
    mcq("Sound travels as...", ["Vibrations passing through a material", "Light beams", "Tiny balls", "Magnetism"], 0,
        "Vibrations pass from particle to particle through air, water or solids.",
        "শব্দ চলে...", ["উপাদানের মধ্য দিয়ে যাওয়া কম্পন হিসেবে", "আলোর রশ্মি হিসেবে", "ছোট ছোট বল হিসেবে", "চুম্বকত্ব হিসেবে"],
        "কম্পন কণা থেকে কণায় বাতাস, জল বা কঠিনের মধ্য দিয়ে চলে।"),
    mcq("Why can you hear a train coming by putting your ear near the rail (only in a safe experiment!)?", ["Sound travels well through steel", "Rails shout", "Steel blocks sound", "Trains are silent in air"], 0,
        "Sound travels faster and further through solids like steel than through air. Never do this on a real railway!",
        "রেললাইনে কান রাখলে আসা ট্রেনের শব্দ শোনা যায় কেন (শুধু নিরাপদ পরীক্ষায়!)?", ["ইস্পাতের মধ্য দিয়ে শব্দ ভালো চলে", "লাইন চেঁচায়", "ইস্পাত শব্দ আটকায়", "বাতাসে ট্রেন নীরব"],
        "বাতাসের চেয়ে ইস্পাতের মতো কঠিনে শব্দ দ্রুত আর দূরে যায়। আসল রেলপথে কখনো এটা করো না!"),
    mcq("Sound gets quieter as it travels further because...", ["The vibrations spread out and lose energy", "It turns into light", "It speeds up", "It gets heavier"], 0,
        "The energy spreads over a bigger area, so each bit of air shakes less.",
        "শব্দ যত দূরে যায় তত আস্তে হয় কারণ...", ["কম্পন ছড়িয়ে শক্তি হারায়", "আলো হয়ে যায়", "গতি বাড়ে", "ভারী হয়"],
        "শক্তি বড় জায়গায় ছড়ায়, তাই বাতাসের প্রতিটি অংশ কম কাঁপে।"),
    mcq("Why do people wear ear defenders on noisy building sites?", ["Very loud sounds can damage hearing", "To keep warm only", "To listen to music", "To look tall"], 0,
        "Ear protection absorbs much of the sound energy before it reaches the ear.",
        "কোলাহলপূর্ণ নির্মাণস্থলে মানুষ কান-সুরক্ষা পরে কেন?", ["খুব জোরালো শব্দ শ্রবণশক্তির ক্ষতি করতে পারে", "শুধু গরম থাকতে", "গান শুনতে", "লম্বা দেখাতে"],
        "কান-সুরক্ষা কানে পৌঁছানোর আগেই শব্দশক্তির বেশিরভাগ শুষে নেয়।"),
    mcq("Why do we have day and night?", ["The Earth spins once every 24 hours", "The Sun turns off", "The Moon blocks the Sun daily", "Clouds cover the sky"], 0,
        "The half of Earth facing the Sun has day; the other half has night.",
        "দিন আর রাত হয় কেন?", ["পৃথিবী 24 ঘণ্টায় একবার ঘোরে", "সূর্য নিভে যায়", "চাঁদ রোজ সূর্য ঢাকে", "মেঘ আকাশ ঢাকে"],
        "পৃথিবীর যে অর্ধেক সূর্যের দিকে সেখানে দিন; অন্য অর্ধেকে রাত।"),
    mcq("How long does the Earth take to go once around the Sun?", ["About 365 days (1 year)", "1 day", "1 month", "10 years"], 0,
        "One trip around the Sun is one year.",
        "পৃথিবীর একবার সূর্য প্রদক্ষিণ করতে কত সময় লাগে?", ["প্রায় 365 দিন (1 বছর)", "1 দিন", "1 মাস", "10 বছর"],
        "সূর্যকে একবার ঘুরে আসা মানে এক বছর।"),
    mcq("The Moon shines at night because...", ["It reflects sunlight", "It burns like the Sun", "It is covered in lamps", "It is made of ice that glows"], 0,
        "The Moon has no light of its own.",
        "রাতে চাঁদ উজ্জ্বল দেখায় কারণ...", ["সে সূর্যের আলো প্রতিফলিত করে", "সূর্যের মতো জ্বলে", "বাতিতে ঢাকা", "জ্বলন্ত বরফে তৈরি"],
        "চাঁদের নিজের কোনো আলো নেই।"),
    mcq("The Sun appears to rise in the...", ["East", "West", "North", "South"], 0,
        "As the Earth spins, the Sun appears to rise in the east and set in the west.",
        "সূর্য উঠতে দেখা যায়...", ["পূর্বে", "পশ্চিমে", "উত্তরে", "দক্ষিণে"],
        "পৃথিবী ঘোরে বলে সূর্য পূর্বে উঠতে আর পশ্চিমে অস্ত যেতে দেখা যায়।"),
    mcq("Why does a tall thin tower sway more in wind than a short wide one?", ["It is less stiff and the wind acts high up", "It is heavier", "Wind only blows on tall things", "It does not"], 0,
        "Height gives the wind a long lever; slenderness makes it flexible.",
        "বাতাসে লম্বা সরু টাওয়ার খাটো চওড়াটার চেয়ে বেশি দোলে কেন?", ["কম দৃঢ় আর বাতাস উঁচুতে কাজ করে", "বেশি ভারী", "বাতাস শুধু লম্বা জিনিসে বয়", "দোলে না"],
        "উচ্চতা বাতাসকে লম্বা লিভার দেয়; সরু হলে নমনীয় হয়।"),
    mcq("Why do builders put diagonal braces in a tall frame?", ["Triangles stop it leaning and swaying", "To hang lights", "To make it heavier only", "For decoration"], 0,
        "Diagonals turn wobbly rectangles into stiff triangles.",
        "নির্মাতারা লম্বা কাঠামোয় কর্ণ-ঠেকনা দেন কেন?", ["ত্রিভুজ হেলে পড়া আর দোলা থামায়", "বাতি ঝোলাতে", "শুধু ভারী করতে", "সাজসজ্জার জন্য"],
        "কর্ণ নড়বড়ে আয়তক্ষেত্রকে দৃঢ় ত্রিভুজে বদলায়।"),
    mcq("A beam bridge gets weaker the longer it is. Why?", ["Longer spans bend much more under the same load", "Long beams are lighter", "Cars drive faster on them", "It does not"], 0,
        "Bending grows quickly with span length, so long spans need deeper beams, trusses or cables.",
        "বিম সেতু যত লম্বা তত দুর্বল। কেন?", ["লম্বা স্প্যান একই ভারে অনেক বেশি বাঁকে", "লম্বা বিম হালকা", "এতে গাড়ি দ্রুত চলে", "দুর্বল হয় না"],
        "স্প্যানের দৈর্ঘ্যের সঙ্গে বাঁকা দ্রুত বাড়ে, তাই লম্বা স্প্যানে গভীর বিম, ট্রাস বা তার লাগে।"),
    mcq("Which bridge type is best for very long gaps like wide straits?", ["Suspension or cable-stayed bridge", "A single wooden plank", "A stepping-stone path", "A rope swing"], 0,
        "Steel cables in tension can carry the deck over hundreds or thousands of metres.",
        "চওড়া প্রণালীর মতো খুব লম্বা ফাঁকের জন্য কোন সেতু সবচেয়ে ভালো?", ["ঝুলন্ত বা তার-ঝোলানো সেতু", "একটা কাঠের তক্তা", "পাথরের ধাপের পথ", "দড়ির দোলনা"],
        "টানে থাকা ইস্পাতের তার শত শত বা হাজার হাজার মিটার পেরিয়ে ডেক বইতে পারে।"),
    mcq("In an arch bridge, the stones of the arch are mostly...", ["Squeezed (in compression)", "Pulled apart (in tension)", "Floating", "Twisted only"], 0,
        "Arches carry loads by pushing along their curve. Stone is great at being squeezed.",
        "খিলান সেতুর খিলানের পাথরগুলো বেশিরভাগ...", ["চাপে (সংকোচনে) থাকে", "টানে (প্রসারণে) থাকে", "ভাসে", "শুধু মোচড় খায়"],
        "খিলান বাঁক বরাবর ঠেলে ভার বয়। পাথর চাপ সহ্যে দারুণ।"),
    mcq("What do the ends of an arch need?", ["Strong supports (abutments) to push against", "Nothing at all", "Wheels", "Balloons"], 0,
        "An arch pushes outwards at its feet; strong abutments stop it spreading.",
        "খিলানের দুই প্রান্তে কী লাগে?", ["ঠেলার জন্য শক্ত সাপোর্ট (অ্যাবাটমেন্ট)", "কিছুই না", "চাকা", "বেলুন"],
        "খিলান পায়ের কাছে বাইরের দিকে ঠেলে; শক্ত অ্যাবাটমেন্ট ছড়িয়ে পড়া থামায়।"),
    mcq("A cantilever is a beam that is...", ["Fixed at one end only, sticking out", "Supported at both ends", "Hanging from cables only", "Floating on water"], 0,
        "Balconies, diving boards and the arms of Level 3's girder are cantilevers.",
        "ক্যান্টিলিভার এমন বিম যা...", ["শুধু এক প্রান্তে আটকানো, বাইরে বেরিয়ে থাকে", "দুই প্রান্তে ভর দেওয়া", "শুধু তার থেকে ঝোলানো", "জলে ভাসমান"],
        "বারান্দা, ডাইভিং বোর্ড আর লেভেল 3-এর গার্ডারের বাহু ক্যান্টিলিভার।"),
    mcq("Where does a diving board bend the most?", ["At the far, free end", "At the fixed end", "Exactly in the middle", "It never bends"], 0,
        "The free end moves the most; but the fixed end has the biggest bending force (moment).",
        "ডাইভিং বোর্ড কোথায় সবচেয়ে বেশি বাঁকে?", ["দূরের মুক্ত প্রান্তে", "আটকানো প্রান্তে", "ঠিক মাঝখানে", "কখনো বাঁকে না"],
        "মুক্ত প্রান্ত সবচেয়ে বেশি সরে; কিন্তু আটকানো প্রান্তে বাঁকানোর বল (ভ্রামক) সবচেয়ে বড়।"),
    mcq("Why are steel I-beams shaped like the letter I?", ["Material far from the middle resists bending best", "It is easy to write", "To save paint", "For decoration"], 0,
        "Wide flanges top and bottom do most of the work; the thin web joins them.",
        "ইস্পাতের আই-বিম ইংরেজি I অক্ষরের মতো কেন?", ["মাঝখান থেকে দূরের উপাদান বাঁকা সবচেয়ে ভালো ঠেকায়", "লেখা সহজ", "রং বাঁচাতে", "সাজসজ্জার জন্য"],
        "উপর-নিচের চওড়া ফ্ল্যাঞ্জ বেশিরভাগ কাজ করে; পাতলা ওয়েব তাদের জোড়ে।"),
    mcq("You squeeze a long drinking straw from both ends. It suddenly bends in the middle. What is this?", ["Buckling", "Melting", "Stretching", "Rusting"], 0,
        "Long thin things squeezed along their length bow sideways and fold - buckling.",
        "লম্বা স্ট্র দুই প্রান্ত থেকে চাপলে হঠাৎ মাঝখানে বেঁকে যায়। এটা কী?", ["বাকলিং", "গলন", "প্রসারণ", "মরচে"],
        "লম্বা সরু জিনিস দৈর্ঘ্য বরাবর চাপলে পাশে বেঁকে ভাঁজ হয় - বাকলিং।"),
    mcq("Cut that straw in half and squeeze again. It is now...", ["Much harder to buckle", "Easier to buckle", "Exactly the same", "Weightless"], 0,
        "Halving the length makes it about 4 times stronger against buckling.",
        "স্ট্র অর্ধেক কেটে আবার চাপলে এখন সেটা...", ["বাকল করানো অনেক কঠিন", "বাকল করানো সহজ", "একদম একই", "ওজনহীন"],
        "দৈর্ঘ্য অর্ধেক করলে বাকলিংয়ের বিরুদ্ধে প্রায় 4 গুণ শক্ত হয়।"),
    mcq("Which pushes harder on the ground: a 50 kg person in trainers or in high heels?", ["The same weight, but high heels press harder on each spot", "Trainers push more weight", "High heels weigh nothing", "Neither pushes"], 0,
        "Same weight on a smaller area means higher pressure.",
        "কোনটা মাটিতে বেশি চাপ দেয়: স্নিকারে 50 kg-এর মানুষ নাকি হাই-হিলে?", ["ওজন একই, কিন্তু হাই-হিল প্রতি জায়গায় বেশি চাপ দেয়", "স্নিকার বেশি ওজন ঠেলে", "হাই-হিলের ওজন নেই", "কোনোটাই ঠেলে না"],
        "একই ওজন ছোট জায়গায় মানে বেশি চাপ।"),
    mcq("Why do tractors have wide tyres?", ["To spread their weight so they do not sink in soft soil", "To go faster on roads", "To look big", "To float on water"], 0,
        "Wide tyres lower the pressure on the ground.",
        "ট্রাক্টরের টায়ার চওড়া কেন?", ["ওজন ছড়িয়ে নরম মাটিতে না ডুবতে", "রাস্তায় দ্রুত চলতে", "বড় দেখাতে", "জলে ভাসতে"],
        "চওড়া টায়ার মাটির উপর চাপ কমায়।"),
    mcq("Why do bridge piers stand on big wide footings?", ["To spread the huge load so the ground does not sink", "To store water", "To look strong only", "For fish to hide"], 0,
        "Spreading the force over a big area keeps the pressure safe for the soil.",
        "সেতুর স্তম্ভ বড় চওড়া পাদভিত্তিতে দাঁড়ায় কেন?", ["বিশাল ভার ছড়িয়ে মাটি বসে যাওয়া ঠেকাতে", "জল জমাতে", "শুধু শক্ত দেখাতে", "মাছের লুকোনোর জন্য"],
        "বড় জায়গায় বল ছড়ালে মাটির জন্য চাপ নিরাপদ থাকে।"),
    mcq("A sharp knife cuts better than a blunt one because...", ["Its thin edge puts big pressure on a tiny area", "It is heavier", "It is colder", "It is longer"], 0,
        "The same push on a smaller area gives higher pressure.",
        "ধারালো ছুরি ভোঁতাটার চেয়ে ভালো কাটে কারণ...", ["সরু ধার ছোট জায়গায় বড় চাপ দেয়", "এটা ভারী", "এটা ঠান্ডা", "এটা লম্বা"],
        "একই ঠেলা ছোট জায়গায় দিলে চাপ বেশি হয়।"),
    mcq("What makes a boat float?", ["The water pushes up (upthrust) as much as the boat's weight", "The boat is lighter than air", "Fish hold it up", "The sail lifts it"], 0,
        "The boat sinks until it pushes aside water weighing as much as itself.",
        "নৌকা ভাসে কীসে?", ["জল নৌকার ওজনের সমান উপরের দিকে ঠেলে (প্লবতা)", "নৌকা বাতাসের চেয়ে হালকা", "মাছ ধরে রাখে", "পাল তোলে"],
        "নৌকা ততটা ডোবে যতক্ষণ না নিজের ওজনের সমান জল সরায়।"),
    mcq("Why does a loaded ship sit lower in the water?", ["It is heavier, so it must push aside more water", "The water gets lighter", "The sea gets deeper", "It does not"], 0,
        "More weight needs more upthrust, so the ship sinks deeper.",
        "বোঝাই জাহাজ জলে বেশি ডুবে থাকে কেন?", ["বেশি ভারী, তাই বেশি জল সরাতে হয়", "জল হালকা হয়", "সমুদ্র গভীর হয়", "ডোবে না"],
        "বেশি ওজনে বেশি প্লবতা লাগে, তাই জাহাজ বেশি ডোবে।"),
    mcq("Which of these stores energy you can use later?", ["A stretched rubber band", "A shadow", "An echo", "A reflection"], 0,
        "Stretched or squashed things store elastic energy.",
        "এগুলোর কোনটা পরে ব্যবহারের জন্য শক্তি জমিয়ে রাখে?", ["টানা রাবার ব্যান্ড", "ছায়া", "প্রতিধ্বনি", "প্রতিবিম্ব"],
        "টানা বা চাপা জিনিস স্থিতিস্থাপক শক্তি জমায়।"),
    mcq("A ball on a high shelf has energy because of its height. This is called...", ["Potential energy", "Sound energy", "Light energy", "No energy"], 0,
        "If it falls, that stored energy turns into movement (kinetic energy).",
        "উঁচু তাকে রাখা বলের উচ্চতার জন্য শক্তি আছে। একে বলে...", ["স্থিতিশক্তি", "শব্দশক্তি", "আলোকশক্তি", "কোনো শক্তি নেই"],
        "পড়লে সেই জমানো শক্তি গতিশক্তিতে বদলায়।"),
    mcq("Energy of movement is called...", ["Kinetic energy", "Potential energy", "Chemical energy", "Nuclear energy"], 0,
        "Anything moving has kinetic energy - faster and heavier means more.",
        "গতির শক্তিকে বলে...", ["গতিশক্তি", "স্থিতিশক্তি", "রাসায়নিক শক্তি", "পারমাণবিক শক্তি"],
        "চলমান যেকোনো কিছুর গতিশক্তি আছে - দ্রুত আর ভারী হলে বেশি।"),
    mcq("Food gives your body which kind of energy?", ["Chemical energy", "Sound energy", "Magnetic energy", "Light energy"], 0,
        "Your body releases the chemical energy stored in food.",
        "খাবার শরীরকে কোন ধরনের শক্তি দেয়?", ["রাসায়নিক শক্তি", "শব্দশক্তি", "চৌম্বক শক্তি", "আলোকশক্তি"],
        "শরীর খাবারে জমা রাসায়নিক শক্তি মুক্ত করে।"),
    mcq("A solar panel turns sunlight into...", ["Electricity", "Water", "Sound", "Wood"], 0,
        "Solar panels convert light energy into electrical energy - clean power.",
        "সৌর প্যানেল সূর্যালোককে বদলায়...", ["বিদ্যুতে", "জলে", "শব্দে", "কাঠে"],
        "সৌর প্যানেল আলোকশক্তিকে বৈদ্যুতিক শক্তিতে বদলায় - পরিষ্কার শক্তি।"),
    mcq("A wind turbine turns the energy of moving air into...", ["Electricity", "Ice", "Petrol", "Sand"], 0,
        "The wind spins the blades, which turn a generator.",
        "বায়ুকল চলমান বাতাসের শক্তিকে বদলায়...", ["বিদ্যুতে", "বরফে", "পেট্রলে", "বালিতে"],
        "বাতাস পাখা ঘোরায়, যা জেনারেটর ঘোরায়।"),
    mcq("Which is a renewable energy source?", ["Sunlight", "Coal", "Oil", "Natural gas"], 0,
        "Renewable sources like sun, wind and flowing water will not run out.",
        "কোনটা নবায়নযোগ্য শক্তির উৎস?", ["সূর্যালোক", "কয়লা", "তেল", "প্রাকৃতিক গ্যাস"],
        "সূর্য, বাতাস আর প্রবাহিত জলের মতো নবায়নযোগ্য উৎস ফুরোবে না।"),
    mcq("Why do roads have speed humps near schools?", ["To make cars slow down", "To make cars jump for fun", "To drain rain only", "To save fuel"], 0,
        "Slower cars need much less distance to stop - safer for children.",
        "স্কুলের কাছে রাস্তায় স্পিড-ব্রেকার থাকে কেন?", ["গাড়ির গতি কমাতে", "মজা করে গাড়ি লাফাতে", "শুধু বৃষ্টির জল সরাতে", "জ্বালানি বাঁচাতে"],
        "ধীর গাড়ির থামতে অনেক কম পথ লাগে - শিশুদের জন্য নিরাপদ।"),
    mcq("A car at double the speed needs about how much more distance to brake?", ["About 4 times as much", "The same", "Half as much", "About 2 times as much only"], 0,
        "Braking distance grows with the square of speed: 2 x speed = 4 x distance.",
        "দ্বিগুণ গতির গাড়ির ব্রেক কষে থামতে প্রায় কত বেশি পথ লাগে?", ["প্রায় 4 গুণ", "একই", "অর্ধেক", "শুধু প্রায় 2 গুণ"],
        "ব্রেকের দূরত্ব গতির বর্গ অনুপাতে বাড়ে: 2 x গতি = 4 x দূরত্ব।"),
    mcq("What is speed?", ["How far something travels in a certain time", "How heavy something is", "How hot it is", "How loud it is"], 0,
        "Speed = distance ÷ time, for example metres per second or kilometres per hour.",
        "গতি কী?", ["নির্দিষ্ট সময়ে কোনো কিছু কত দূর যায়", "কতটা ভারী", "কতটা গরম", "কতটা জোরে শব্দ"],
        "গতি = দূরত্ব ÷ সময়, যেমন মিটার প্রতি সেকেন্ড বা কিলোমিটার প্রতি ঘণ্টা।"),
    mcq("A bus travels 60 km in 1 hour. What is its speed?", ["60 km/h", "1 km/h", "120 km/h", "30 km/h"], 0,
        "60 km ÷ 1 hour = 60 km per hour.",
        "একটা বাস 1 ঘণ্টায় 60 km যায়। গতি কত?", ["60 km/h", "1 km/h", "120 km/h", "30 km/h"],
        "60 km ÷ 1 ঘণ্টা = ঘণ্টায় 60 km।"),
    mcq("A cyclist rides 30 km in 2 hours. What is her speed?", ["15 km/h", "60 km/h", "32 km/h", "28 km/h"], 0,
        "30 ÷ 2 = 15 km/h.",
        "একজন সাইকেল-চালক 2 ঘণ্টায় 30 km যান। গতি কত?", ["15 km/h", "60 km/h", "32 km/h", "28 km/h"],
        "30 ÷ 2 = 15 km/h।"),
    mcq("Which is faster: 20 metres per second or 20 kilometres per hour?", ["20 metres per second", "20 km per hour", "They are equal", "Neither moves"], 0,
        "20 m/s = 72 km/h, much faster than 20 km/h.",
        "কোনটা দ্রুত: সেকেন্ডে 20 মিটার নাকি ঘণ্টায় 20 কিলোমিটার?", ["সেকেন্ডে 20 মিটার", "ঘণ্টায় 20 km", "দুটো সমান", "কোনোটাই চলে না"],
        "20 m/s = 72 km/h, যা 20 km/h-এর চেয়ে অনেক দ্রুত।"),
    mcq("Why do rockets need a huge force to lift off?", ["They must beat the pull of Earth's gravity on their great weight", "Air is heavy", "Rockets are made of stone", "To make noise"], 0,
        "The engines must push down harder than the rocket's weight to accelerate upwards.",
        "রকেট উৎক্ষেপণে বিশাল বল লাগে কেন?", ["বিশাল ওজনের উপর পৃথিবীর মাধ্যাকর্ষণকে হারাতে হয়", "বাতাস ভারী", "রকেট পাথরের তৈরি", "শব্দ করতে"],
        "উপরে ত্বরণ পেতে ইঞ্জিনকে রকেটের ওজনের চেয়ে জোরে নিচে ঠেলতে হয়।"),
    mcq("When you push off a wall in a swimming pool, the wall pushes you...", ["Away with an equal force", "Not at all", "Towards it", "Downwards"], 0,
        "Every push has an equal and opposite push back (Newton's third law).",
        "সুইমিং পুলে দেয়ালে ঠেলা দিলে দেয়াল তোমাকে ঠেলে...", ["সমান বলে দূরে", "একদম না", "তার দিকে", "নিচের দিকে"],
        "প্রতিটি ঠেলার সমান আর বিপরীত ঠেলা থাকে (নিউটনের তৃতীয় সূত্র)।"),
    mcq("A bridge pushes down on its supports. The supports push...", ["Up on the bridge with equal force", "Down too", "Sideways only", "Nothing"], 0,
        "These upward pushes are called reactions - the blue arrows in MODIS BridgeWorks.",
        "সেতু তার সাপোর্টকে নিচে ঠেলে। সাপোর্ট ঠেলে...", ["সমান বলে সেতুকে উপরে", "তারাও নিচে", "শুধু পাশে", "কিছুই না"],
        "এই উপরের ঠেলাকে বলে প্রতিক্রিয়া - MODIS BridgeWorks-এর নীল তীর।"),
    mcq("What does a pulley with two wheels (a block and tackle) do?", ["Lets you lift a load with less pull", "Makes the load heavier", "Stops the rope", "Makes noise"], 0,
        "Sharing the load between more rope sections means each needs less pull - but you pull further.",
        "দুই চাকার কপিকল (ব্লক ও ট্যাকল) কী করে?", ["কম টানে ভার তোলা যায়", "ভার ভারী করে", "দড়ি থামায়", "শব্দ করে"],
        "দড়ির বেশি অংশে ভার ভাগ হলে প্রতিটিতে কম টান লাগে - কিন্তু বেশি দূর টানতে হয়।"),
    mcq("Why does a crane have a heavy counterweight at the back?", ["To balance the load so it does not tip over", "To make it slower", "For decoration", "To store fuel"], 0,
        "Like a see-saw, the counterweight balances the load's turning effect.",
        "ক্রেনের পেছনে ভারী পাল্টা-ওজন থাকে কেন?", ["ভারের সঙ্গে ভারসাম্য রেখে উল্টে পড়া ঠেকাতে", "ধীর করতে", "সাজসজ্জার জন্য", "জ্বালানি রাখতে"],
        "ঢেঁকির মতো, পাল্টা-ওজন ভারের ঘোরানোর প্রভাবকে সমান করে।"),
    mcq("A see-saw has a 20 kg child 2 m from the middle. Where must a 40 kg adult sit to balance?", ["1 m from the middle", "2 m from the middle", "4 m from the middle", "At the very middle"], 0,
        "Balance: 20 x 2 = 40 x 1. Weight x distance must be equal on both sides.",
        "একটা ঢেঁকির মাঝখান থেকে 2 m দূরে 20 kg-এর শিশু। 40 kg-এর বড় মানুষকে সমান করতে কোথায় বসতে হবে?", ["মাঝখান থেকে 1 m", "মাঝখান থেকে 2 m", "মাঝখান থেকে 4 m", "একদম মাঝখানে"],
        "ভারসাম্য: 20 x 2 = 40 x 1। দুই দিকে ওজন x দূরত্ব সমান হতে হবে।"),
    mcq("Why do long bridges have joints that let them move a little?", ["Steel grows in heat and shrinks in cold", "To let cars bounce", "To save steel", "For drainage only"], 0,
        "Expansion joints give room for thermal expansion so the bridge does not crack.",
        "লম্বা সেতুতে একটু নড়ার মতো জোড় থাকে কেন?", ["গরমে ইস্পাত বাড়ে আর ঠান্ডায় কমে", "গাড়ি লাফাতে", "ইস্পাত বাঁচাতে", "শুধু জল নিষ্কাশনের জন্য"],
        "সম্প্রসারণ-জোড় তাপীয় প্রসারণের জায়গা দেয়, তাই সেতু ফাটে না।"),
    mcq("What happens to the air pressure as you climb a high mountain?", ["It gets lower", "It gets higher", "It stays the same", "It turns into water"], 0,
        "There is less air above you pressing down, so pressure falls.",
        "উঁচু পাহাড়ে উঠতে থাকলে বায়ুচাপের কী হয়?", ["কমে", "বাড়ে", "একই থাকে", "জল হয়ে যায়"],
        "উপরে চাপ দেওয়ার মতো বাতাস কম, তাই চাপ কমে।"),
    mcq("Why do your ears 'pop' in an aeroplane?", ["The air pressure changes as it climbs or descends", "Engines are noisy", "Seats are hard", "Windows open"], 0,
        "Your ears adjust to the new air pressure with a small pop.",
        "উড়োজাহাজে কান 'পট' করে ওঠে কেন?", ["ওঠা-নামায় বায়ুচাপ বদলায়", "ইঞ্জিনের শব্দ", "আসন শক্ত", "জানালা খোলে"],
        "কান নতুন বায়ুচাপের সঙ্গে মানিয়ে নিতে একটা ছোট পট শব্দ করে।"),
    mcq("A drinking straw works because...", ["You lower the air pressure inside and outside air pushes the drink up", "The straw pulls the drink", "Drinks love straws", "Gravity points up"], 0,
        "Sucking removes air; the atmosphere pushes the drink up into your mouth.",
        "স্ট্র কাজ করে কারণ...", ["ভেতরের বায়ুচাপ কমাও আর বাইরের বাতাস পানীয় উপরে ঠেলে", "স্ট্র পানীয় টানে", "পানীয় স্ট্র ভালোবাসে", "মাধ্যাকর্ষণ উপরের দিকে"],
        "চুষলে বাতাস সরে; বায়ুমণ্ডল পানীয়কে মুখে ঠেলে তোলে।"),
    mcq("Why do mountain roads zig-zag (switchbacks)?", ["To make the slope gentler for vehicles", "To make the trip shorter", "To confuse drivers", "For fun only"], 0,
        "A longer, gentler road needs less force to climb - like a ramp.",
        "পাহাড়ি রাস্তা আঁকাবাঁকা হয় কেন?", ["গাড়ির জন্য ঢাল মৃদু করতে", "যাত্রা ছোট করতে", "চালককে বিভ্রান্ত করতে", "শুধু মজার জন্য"],
        "লম্বা, মৃদু রাস্তায় উঠতে কম বল লাগে - র‍্যাম্পের মতো।"),
    mcq("A train struggles up a steep hill. What could help it?", ["A second engine or fewer wagons", "More wagons", "Turning off the engine", "Wet rails"], 0,
        "More pulling force or less weight to pull - exactly the choices in MODIS BridgeWorks Level 2.",
        "একটা ট্রেন খাড়া পাহাড়ে উঠতে হিমশিম খাচ্ছে। কী সাহায্য করবে?", ["দ্বিতীয় ইঞ্জিন বা কম ওয়াগন", "আরও ওয়াগন", "ইঞ্জিন বন্ধ করা", "ভেজা লাইন"],
        "বেশি টানার বল বা কম ওজন - ঠিক MODIS BridgeWorks-এর লেভেল 2-এর বাছাই।"),
    mcq("Why do train wheels slip more on wet rails?", ["Water reduces friction (grip)", "Water makes trains heavier", "Rails get hotter", "They do not"], 0,
        "Wet steel has much less grip. In the game, grip falls from 0.30 to 0.18 in the rain.",
        "ভেজা লাইনে ট্রেনের চাকা বেশি পিছলায় কেন?", ["জল ঘর্ষণ (আঁকড়ে ধরা) কমায়", "জল ট্রেন ভারী করে", "লাইন গরম হয়", "পিছলায় না"],
        "ভেজা ইস্পাতে আঁকড়ে ধরা অনেক কম। খেলায় বৃষ্টিতে তা 0.30 থেকে 0.18-এ নামে।"),
    mcq("What is the Earth's natural magnet good for?", ["Compasses point north so we can navigate", "Making rain", "Holding the Moon only", "Nothing"], 0,
        "Sailors and hikers have used compasses for centuries.",
        "পৃথিবীর প্রাকৃতিক চুম্বক কী কাজে লাগে?", ["কম্পাস উত্তর দেখায়, তাই দিক খুঁজে চলা যায়", "বৃষ্টি তৈরি", "শুধু চাঁদ ধরে রাখা", "কিছুই না"],
        "নাবিক আর পর্যটক শতাব্দী ধরে কম্পাস ব্যবহার করছেন।"),
    mcq("A light bulb turns electrical energy into...", ["Light and heat", "Sound only", "Water", "Food"], 0,
        "Old bulbs make lots of heat; LEDs make more light and less heat.",
        "বাল্ব বৈদ্যুতিক শক্তিকে বদলায়...", ["আলো আর তাপে", "শুধু শব্দে", "জলে", "খাবারে"],
        "পুরোনো বাল্ব অনেক তাপ দেয়; এলইডি বেশি আলো আর কম তাপ দেয়।"),
    mcq("Why are LED bulbs better for the environment?", ["They use much less electricity for the same light", "They are heavier", "They are made of wood", "They give no light"], 0,
        "Less electricity means less fuel burned at power stations.",
        "এলইডি বাল্ব পরিবেশের জন্য ভালো কেন?", ["একই আলোয় অনেক কম বিদ্যুৎ লাগে", "এগুলো ভারী", "কাঠের তৈরি", "আলো দেয় না"],
        "কম বিদ্যুৎ মানে বিদ্যুৎকেন্দ্রে কম জ্বালানি পোড়ে।"),
    mcq("What does a 'newton meter' reading of 50 N mean when a bag hangs from it?", ["The bag weighs 50 N (about 5 kg)", "The bag is 50 cm long", "The bag costs Rs 50", "Nothing"], 0,
        "Weight in newtons ÷ 10 gives roughly the mass in kg.",
        "একটা ব্যাগ ঝোলানো নিউটন মিটারে 50 N দেখালে মানে কী?", ["ব্যাগের ওজন 50 N (প্রায় 5 kg)", "ব্যাগ 50 cm লম্বা", "ব্যাগের দাম 50 টাকা", "কিছুই না"],
        "নিউটনে ওজন ÷ 10 মোটামুটি kg-এ ভর দেয়।"),
    mcq("Which structure shape is strongest for its weight in a toy test?", ["A triangular truss", "A flat sheet", "A loose square frame", "A single straw"], 0,
        "Triangles share loads along their members, so trusses are strong and light.",
        "খেলনার পরীক্ষায় ওজনের তুলনায় কোন কাঠামোর আকার সবচেয়ে শক্ত?", ["ত্রিভুজাকার ট্রাস", "সমতল পাত", "আলগা বর্গাকার কাঠামো", "একটা স্ট্র"],
        "ত্রিভুজ সদস্য বরাবর ভার ভাগ করে, তাই ট্রাস শক্ত আর হালকা।"),
    mcq("In a truss, the members are either pushed or...", ["Pulled", "Melted", "Painted", "Spun"], 0,
        "Truss members carry tension (pulling) or compression (pushing).",
        "ট্রাসে সদস্যরা হয় ঠেলা খায় নয়তো...", ["টানা খায়", "গলে", "রং হয়", "ঘোরে"],
        "ট্রাসের সদস্য টান বা চাপ বয়।"),
    mcq("Why is a rope useless as a pillar?", ["A rope cannot be pushed - it just goes slack", "Ropes are too heavy", "Ropes are too short", "Ropes are magnetic"], 0,
        "Ropes and cables only work in tension. In the game, cables go grey (slack) if pushed.",
        "দড়ি খুঁটি হিসেবে অকেজো কেন?", ["দড়িকে ঠেলা যায় না - ঢিলা হয়ে যায়", "দড়ি খুব ভারী", "দড়ি খুব ছোট", "দড়ি চুম্বক"],
        "দড়ি আর তার শুধু টানে কাজ করে। খেলায় ঠেললে তার ধূসর (ঢিলা) হয়ে যায়।"),
    mcq("What keeps the planets going around the Sun?", ["The Sun's gravity", "Wind in space", "Magnets", "Rockets"], 0,
        "Gravity pulls the planets towards the Sun and keeps them in orbit.",
        "কী গ্রহগুলোকে সূর্যের চারপাশে ঘোরায়?", ["সূর্যের মাধ্যাকর্ষণ", "মহাকাশের বাতাস", "চুম্বক", "রকেট"],
        "মাধ্যাকর্ষণ গ্রহগুলোকে সূর্যের দিকে টানে আর কক্ষপথে রাখে।"),
    mcq("Why do astronauts float inside a space station?", ["They are falling around the Earth together with the station", "There is no gravity at all in space", "They are very light", "They hold balloons"], 0,
        "The station and the astronauts fall around Earth together, so they feel weightless.",
        "মহাকাশ স্টেশনে নভোচারীরা ভাসেন কেন?", ["স্টেশনের সঙ্গে একসঙ্গে পৃথিবীর চারপাশে পড়ছেন", "মহাকাশে একদম মাধ্যাকর্ষণ নেই", "তাঁরা খুব হালকা", "বেলুন ধরে আছেন"],
        "স্টেশন আর নভোচারীরা একসঙ্গে পৃথিবীর চারপাশে পড়ছেন, তাই ওজনহীন লাগে।"),
    mcq("A parachute opens and the skydiver slows down. What force increased?", ["Air resistance", "Gravity", "Magnetism", "Friction with the ground"], 0,
        "The big canopy catches much more air, so drag grows until it nearly balances weight.",
        "প্যারাসুট খুললে স্কাইডাইভার ধীর হন। কোন বল বেড়েছে?", ["বায়ুর বাধা", "মাধ্যাকর্ষণ", "চুম্বকত্ব", "মাটির সঙ্গে ঘর্ষণ"],
        "বড় ছাতা অনেক বেশি বাতাস ধরে, তাই টান বাড়তে বাড়তে প্রায় ওজনের সমান হয়।"),
    mcq("Why does a heavy truck need stronger brakes than a car?", ["It has more momentum to stop", "It is shorter", "Trucks are slower always", "It does not"], 0,
        "More mass at the same speed means more momentum and energy to remove.",
        "ভারী ট্রাকের গাড়ির চেয়ে শক্তিশালী ব্রেক লাগে কেন?", ["থামানোর মতো বেশি ভরবেগ", "এটা ছোট", "ট্রাক সবসময় ধীর", "লাগে না"],
        "একই গতিতে বেশি ভর মানে বেশি ভরবেগ আর শক্তি সরাতে হয়।"),
    mcq("A heavier bridge needs stronger supports because...", ["Its own weight is part of the load", "Heavy bridges are faster", "Supports like weight", "It does not"], 0,
        "A bridge must carry itself as well as the traffic - engineers call this dead load.",
        "ভারী সেতুর শক্তিশালী সাপোর্ট লাগে কারণ...", ["তার নিজের ওজনও ভারের অংশ", "ভারী সেতু দ্রুত", "সাপোর্ট ওজন ভালোবাসে", "লাগে না"],
        "সেতুকে যানবাহনের সঙ্গে নিজেকেও বইতে হয় - প্রকৌশলীরা একে বলেন মৃত ভার।"),
    mcq("Which helps a building survive an earthquake?", ["Flexible joints and strong bracing", "Heavy loose bricks on top", "Glass walls only", "No foundations"], 0,
        "Bracing resists shaking; flexibility and isolation let the building move without breaking.",
        "ভূমিকম্পে ভবন টিকতে কী সাহায্য করে?", ["নমনীয় জোড় আর শক্ত ঠেকনা", "উপরে ভারী আলগা ইট", "শুধু কাচের দেয়াল", "ভিত ছাড়া"],
        "ঠেকনা কাঁপুনি ঠেকায়; নমনীয়তা আর আইসোলেশন ভবনকে না ভেঙে নড়তে দেয়।"),
    mcq("Why do ships have a round bottom (hull) shape?", ["Water flows around it easily and it stays upright", "To look nice", "To catch fish", "To be heavier"], 0,
        "Streamlined hulls reduce drag, and a low heavy bottom keeps the ship stable.",
        "জাহাজের তলা (খোল) গোল আকারের কেন?", ["জল সহজে চারপাশ দিয়ে বয় আর জাহাজ সোজা থাকে", "সুন্দর দেখাতে", "মাছ ধরতে", "ভারী হতে"],
        "মসৃণ খোল বাধা কমায়, আর নিচু ভারী তলা জাহাজকে স্থির রাখে।"),
    mcq("A heavy object on a table pushes down. Why doesn't it fall through?", ["The table pushes back up with an equal force", "Tables are magnetic", "Gravity stops", "Air holds it"], 0,
        "The table's structure squeezes slightly and pushes back - just like a bridge deck.",
        "টেবিলের উপর ভারী জিনিস নিচে ঠেলে। তবু পড়ে যায় না কেন?", ["টেবিল সমান বলে উপরে ঠেলে", "টেবিল চুম্বক", "মাধ্যাকর্ষণ থামে", "বাতাস ধরে রাখে"],
        "টেবিলের কাঠামো সামান্য চাপে বসে উল্টো ঠেলে - সেতুর ডেকের মতো।"),
    mcq("A spring stretches 2 cm for every 10 N. How far does it stretch with 30 N?", ["6 cm", "2 cm", "30 cm", "3 cm"], 0,
        "Stretch grows in step with force: 30 N is 3 x 10 N, so 3 x 2 cm = 6 cm.",
        "একটা স্প্রিং প্রতি 10 N-এ 2 cm লম্বা হয়। 30 N-এ কত লম্বা হবে?", ["6 cm", "2 cm", "30 cm", "3 cm"],
        "বলের সঙ্গে সমান তালে প্রসারণ বাড়ে: 30 N = 3 x 10 N, তাই 3 x 2 cm = 6 cm।"),
    mcq("Why do steel cables on a bridge stretch a tiny bit when a bus crosses?", ["The extra load pulls them harder, like a spring", "Cables are made of rubber", "The bus is magnetic", "They do not stretch at all"], 0,
        "Every material stretches a little under load and springs back when the load is gone.",
        "বাস পার হলে সেতুর ইস্পাতের তার সামান্য লম্বা হয় কেন?", ["বাড়তি ভার স্প্রিংয়ের মতো তাদের জোরে টানে", "তার রাবারের তৈরি", "বাস চুম্বক", "একদম লম্বা হয় না"],
        "প্রতিটি উপাদান ভারে একটু লম্বা হয় আর ভার সরে গেলে ফিরে আসে।"),
    mcq("Which of these is a non-contact force that pulls everything with mass?", ["Gravity", "Friction", "Air resistance", "A kick"], 0,
        "Gravity acts across empty space - between the Earth and the Moon, or a bridge and the ground.",
        "এগুলোর কোনটা ভরযুক্ত সবকিছুকে টানা স্পর্শহীন বল?", ["মাধ্যাকর্ষণ", "ঘর্ষণ", "বায়ুর বাধা", "লাথি"],
        "মাধ্যাকর্ষণ শূন্য জায়গা পেরিয়েও কাজ করে - পৃথিবী আর চাঁদের মধ্যে, বা সেতু আর মাটির মধ্যে।"),
)
