"""Class 3 - Finance: budgets, unit prices and best buys, simple interest in whole rupees,
bank accounts, loans versus grants, giving, insurance and avoiding scams."""
from . import mcq


def unit(total, n, item_en, item_bn):
    r = total // n
    o = [r, r + 1, total, n]
    o = list(dict.fromkeys(o))
    while len(o) < 4:
        o.append(r + len(o) + 1)
    return mcq(f"A pack of {n} {item_en} costs Rs {total}. What is the price of one?",
               [f"Rs {x}" for x in o], 0,
               f"Price of one = total ÷ number = {total} ÷ {n} = Rs {r}.",
               f"{n}টি {item_bn}-এর একটা প্যাকেটের দাম {total} টাকা। একটির দাম কত?",
               [f"{x} টাকা" for x in o],
               f"একটির দাম = মোট ÷ সংখ্যা = {total} ÷ {n} = {r} টাকা।")


def interest(p, rate, years):
    i = p * rate * years // 100
    o = [i, p * rate // 100, i + p, i * 2 if i * 2 != p * rate // 100 else i + 10]
    o = list(dict.fromkeys(o))
    while len(o) < 4:
        o.append(i + 5 * len(o))
    yrs_en = "year" if years == 1 else "years"
    yrs_bn = "বছর"
    return mcq(f"You save Rs {p} in a bank paying {rate}% simple interest a year. How much interest after {years} {yrs_en}?",
               [f"Rs {x}" for x in o], 0,
               f"{rate}% of Rs {p} is Rs {p * rate // 100} a year; for {years} {yrs_en}: Rs {i}.",
               f"তুমি এমন ব্যাংকে {p} টাকা রাখলে, যা বছরে {rate}% সরল সুদ দেয়। {years} {yrs_bn} পরে সুদ কত?",
               [f"{x} টাকা" for x in o],
               f"{p} টাকার {rate}% = বছরে {p * rate // 100} টাকা; {years} {yrs_bn}ে: {i} টাকা।")


ITEMS = (
    unit(60, 5, "pencils", "পেনসিল"),
    unit(120, 6, "juice boxes", "জুসের বাক্স"),
    unit(90, 10, "erasers", "রাবার"),
    unit(144, 12, "eggs", "ডিম"),
    unit(200, 4, "notebooks", "খাতা"),
    unit(75, 3, "mangoes", "আম"),
    unit(250, 5, "bags of sand", "বস্তা বালি"),
    unit(480, 8, "steel bolts packs", "ইস্পাতের বল্টুর প্যাকেট"),
    interest(100, 5, 1),
    interest(200, 10, 1),
    interest(500, 4, 2),
    interest(1000, 5, 3),
    interest(300, 10, 2),
    interest(400, 5, 4),
    interest(800, 2, 5),
    interest(1000, 2, 10),
    mcq("Pack A: 4 pens for Rs 40. Pack B: 6 pens for Rs 54. Which is the better buy?", ["Pack B (Rs 9 each)", "Pack A (Rs 10 each)", "They are the same", "Neither"], 0,
        "Compare the price of one: 40 ÷ 4 = 10; 54 ÷ 6 = 9.",
        "প্যাক A: 40 টাকায় 4টি কলম। প্যাক B: 54 টাকায় 6টি কলম। কোনটা কেনা ভালো?", ["প্যাক B (প্রতিটি 9 টাকা)", "প্যাক A (প্রতিটি 10 টাকা)", "দুটো একই", "কোনোটাই না"],
        "একটির দাম তুলনা করো: 40 ÷ 4 = 10; 54 ÷ 6 = 9।"),
    mcq("A 2 kg bag of rice costs Rs 100; a 5 kg bag costs Rs 225. Which is cheaper per kg?", ["The 5 kg bag (Rs 45 a kg)", "The 2 kg bag (Rs 50 a kg)", "Both the same", "Cannot tell"], 0,
        "100 ÷ 2 = 50; 225 ÷ 5 = 45 per kg.",
        "2 kg চালের ব্যাগ 100 টাকা; 5 kg-এর ব্যাগ 225 টাকা। প্রতি kg-এ কোনটা সস্তা?", ["5 kg-এর ব্যাগ (প্রতি kg 45 টাকা)", "2 kg-এর ব্যাগ (প্রতি kg 50 টাকা)", "দুটো সমান", "বলা যায় না"],
        "100 ÷ 2 = 50; 225 ÷ 5 = প্রতি kg 45।"),
    mcq("Is the bigger pack always the better buy?", ["Only if the price per item is lower and you will use it all", "Yes, always", "No, never", "Only on Mondays"], 0,
        "A cheap-per-kg bag that goes stale before you finish it wastes money.",
        "বড় প্যাক কি সবসময় কেনা ভালো?", ["শুধু যদি প্রতি জিনিসের দাম কম হয় আর পুরোটা ব্যবহার করো", "হ্যাঁ, সবসময়", "না, কখনোই না", "শুধু সোমবারে"],
        "প্রতি kg-এ সস্তা ব্যাগ শেষ করার আগে নষ্ট হলে টাকা নষ্ট।"),
    mcq("What is 'simple interest'?", ["Interest worked out only on the money you first put in", "Interest that is always zero", "A bank's building", "A kind of loan you never repay"], 0,
        "Simple interest = principal x rate x time ÷ 100.",
        "'সরল সুদ' কী?", ["শুধু প্রথমে রাখা টাকার উপর হিসাব করা সুদ", "সবসময় শূন্য সুদ", "ব্যাংকের ভবন", "এক রকম ঋণ যা কখনো শোধ হয় না"],
        "সরল সুদ = আসল x হার x সময় ÷ 100।"),
    mcq("What is the 'principal'?", ["The amount of money first saved or borrowed", "The school head teacher only", "The interest", "The bank's name"], 0,
        "In money, the principal is the starting amount.",
        "'আসল' (প্রিন্সিপাল) কী?", ["প্রথমে জমানো বা ধার নেওয়া টাকার পরিমাণ", "শুধু স্কুলের প্রধান শিক্ষক", "সুদ", "ব্যাংকের নাম"],
        "টাকার হিসাবে আসল হলো শুরুর পরিমাণ।"),
    mcq("You borrow Rs 1000 at 10% simple interest for 1 year. How much do you pay back in total?", ["Rs 1100", "Rs 1010", "Rs 100", "Rs 2000"], 0,
        "Interest = 10% of 1000 = 100; total = 1000 + 100 = Rs 1100.",
        "তুমি 1 বছরের জন্য 10% সরল সুদে 1000 টাকা ধার নিলে। মোট কত ফেরত দেবে?", ["1100 টাকা", "1010 টাকা", "100 টাকা", "2000 টাকা"],
        "সুদ = 1000-এর 10% = 100; মোট = 1000 + 100 = 1100 টাকা।"),
    mcq("Which costs less to borrow Rs 1000 for a year: 2% or 0.5% interest?", ["0.5% (Rs 5)", "2% (Rs 20)", "Both the same", "Neither has a cost"], 0,
        "2% of 1000 = Rs 20; 0.5% of 1000 = Rs 5. Lower rate, lower cost.",
        "এক বছরের জন্য 1000 টাকা ধার নিতে কোনটায় খরচ কম: 2% নাকি 0.5% সুদ?", ["0.5% (5 টাকা)", "2% (20 টাকা)", "দুটো সমান", "কোনোটারই খরচ নেই"],
        "1000-এর 2% = 20 টাকা; 0.5% = 5 টাকা। কম হার, কম খরচ।"),
    mcq("What is the difference between a grant and a loan?", ["A grant is not paid back; a loan is paid back with interest", "They are the same", "A loan is a gift", "A grant has more interest"], 0,
        "Grants are gifts for a purpose - like the Civil Grants you earn in the Academy.",
        "অনুদান আর ঋণের পার্থক্য কী?", ["অনুদান ফেরত দিতে হয় না; ঋণ সুদসহ ফেরত দিতে হয়", "দুটো একই", "ঋণ একটা উপহার", "অনুদানে সুদ বেশি"],
        "অনুদান উদ্দেশ্যভিত্তিক উপহার - একাডেমিতে অর্জিত সিভিল অনুদানের মতো।"),
    mcq("A bridge costs Rs 1200 but the budget is Rs 1000. A grant of Rs 150 is used first. How much must be borrowed?", ["Rs 50", "Rs 200", "Rs 150", "Rs 0"], 0,
        "Shortfall 200 - grant 150 = Rs 50 loan. Grants shrink loans!",
        "একটা সেতুর খরচ 1200 টাকা কিন্তু বাজেট 1000 টাকা। আগে 150 টাকার অনুদান ব্যবহার হলো। কত ধার নিতে হবে?", ["50 টাকা", "200 টাকা", "150 টাকা", "0 টাকা"],
        "ঘাটতি 200 - অনুদান 150 = 50 টাকা ঋণ। অনুদান ঋণ ছোট করে!"),
    mcq("What is a 'savings account'?", ["A bank account that keeps your money safe and may pay interest", "A loan", "A shop", "A piggy bank made of glass"], 0,
        "It is for money you do not need to spend straight away.",
        "'সঞ্চয়ী অ্যাকাউন্ট' কী?", ["যে ব্যাংক অ্যাকাউন্ট টাকা নিরাপদ রাখে আর সুদ দিতে পারে", "একটা ঋণ", "একটা দোকান", "কাচের মাটির ভাঁড়"],
        "এটা সেই টাকার জন্য, যা এখনই খরচের দরকার নেই।"),
    mcq("What is a 'bank statement'?", ["A list of all money paid in and out of your account", "A speech by a bank", "A loan form", "A coin collection"], 0,
        "Checking your statement helps you spot mistakes or fraud.",
        "'ব্যাংক স্টেটমেন্ট' কী?", ["তোমার অ্যাকাউন্টে জমা আর তোলা সব টাকার তালিকা", "ব্যাংকের বক্তৃতা", "ঋণের ফর্ম", "পয়সার সংগ্রহ"],
        "স্টেটমেন্ট মিলিয়ে দেখলে ভুল বা প্রতারণা ধরা পড়ে।"),
    mcq("Your account has Rs 500. You deposit Rs 250 and withdraw Rs 300. Balance?", ["Rs 450", "Rs 1050", "Rs 550", "Rs 50"], 0,
        "500 + 250 - 300 = Rs 450.",
        "তোমার অ্যাকাউন্টে 500 টাকা। 250 টাকা জমা দিয়ে 300 টাকা তুললে। অবশিষ্ট?", ["450 টাকা", "1050 টাকা", "550 টাকা", "50 টাকা"],
        "500 + 250 - 300 = 450 টাকা।"),
    mcq("What is a PIN?", ["A secret number to use your bank card", "A sewing pin", "A price tag", "A bank address"], 0,
        "Never share your PIN - not even with friends.",
        "পিন (PIN) কী?", ["ব্যাংক কার্ড ব্যবহারের গোপন নম্বর", "সেলাইয়ের পিন", "দামের ট্যাগ", "ব্যাংকের ঠিকানা"],
        "পিন কখনো কাউকে বলো না - বন্ধুকেও না।"),
    mcq("A message says your bank needs your PIN to 'unlock your account'. What should you do?", ["Ignore it and tell a parent - banks never ask for PINs", "Send the PIN quickly", "Post it online", "Reply with your password"], 0,
        "This is a scam. Real banks never ask for your PIN or password.",
        "একটা বার্তায় লেখা অ্যাকাউন্ট 'খুলতে' ব্যাংকের তোমার পিন লাগবে। কী করবে?", ["উপেক্ষা করো আর অভিভাবককে বলো - ব্যাংক কখনো পিন চায় না", "তাড়াতাড়ি পিন পাঠাও", "অনলাইনে পোস্ট করো", "পাসওয়ার্ড দিয়ে উত্তর দাও"],
        "এটা প্রতারণা। আসল ব্যাংক কখনো পিন বা পাসওয়ার্ড চায় না।"),
    mcq("What is 'insurance'?", ["Paying a small amount regularly so you get help if something bad happens", "A free toy", "A bank loan", "A type of tax only"], 0,
        "Many people share the risk; those who suffer a loss are paid from the pool.",
        "'বিমা' কী?", ["নিয়মিত অল্প টাকা দেওয়া, যাতে খারাপ কিছু হলে সাহায্য পাও", "বিনামূল্যের খেলনা", "ব্যাংক ঋণ", "শুধু এক রকম কর"],
        "অনেকে ঝুঁকি ভাগ করে নেয়; যার ক্ষতি হয় তাকে সেই তহবিল থেকে টাকা দেওয়া হয়।"),
    mcq("Why do bridge companies buy insurance?", ["To pay for repairs if floods, storms or accidents cause damage", "To make bridges heavier", "To avoid building", "It is not useful"], 0,
        "Insurance protects against rare but very expensive events.",
        "সেতু-কোম্পানি বিমা কেনে কেন?", ["বন্যা, ঝড় বা দুর্ঘটনায় ক্ষতি হলে মেরামতের খরচ মেটাতে", "সেতু ভারী করতে", "নির্মাণ এড়াতে", "কাজের নয়"],
        "বিমা বিরল কিন্তু খুব ব্যয়বহুল ঘটনা থেকে রক্ষা করে।"),
    mcq("What is a 'donation'?", ["Money or goods given freely to help a good cause", "A loan", "A fine", "A sale"], 0,
        "Donations fund schools, clinics, relief and bridges - like the Donation Camps in this game.",
        "'দান' কী?", ["ভালো কাজে সাহায্যের জন্য স্বেচ্ছায় দেওয়া টাকা বা জিনিস", "একটা ঋণ", "জরিমানা", "বিক্রি"],
        "দান স্কুল, চিকিৎসালয়, ত্রাণ আর সেতুর খরচ জোগায় - এই খেলার দান-শিবিরের মতো।"),
    mcq("A class collects Rs 5 from each of 40 students for a flood relief camp. How much is collected?", ["Rs 200", "Rs 45", "Rs 400", "Rs 40"], 0,
        "40 x 5 = Rs 200. Small gifts from many people add up!",
        "একটা ক্লাস বন্যাত্রাণ শিবিরের জন্য 40 জন ছাত্রছাত্রীর প্রত্যেকের থেকে 5 টাকা তুলল। কত উঠল?", ["200 টাকা", "45 টাকা", "400 টাকা", "40 টাকা"],
        "40 x 5 = 200 টাকা। অনেক মানুষের ছোট দান মিলে বড় হয়!"),
    mcq("A camp needs Rs 1000. It has Rs 650. How much more is needed?", ["Rs 350", "Rs 1650", "Rs 650", "Rs 450"], 0,
        "1000 - 650 = Rs 350.",
        "একটা শিবিরের 1000 টাকা লাগবে। আছে 650 টাকা। আর কত লাগবে?", ["350 টাকা", "1650 টাকা", "650 টাকা", "450 টাকা"],
        "1000 - 650 = 350 টাকা।"),
    mcq("Why should you check that a charity is real before giving?", ["Fake charities steal donations", "Real ones pay you back", "Charities are all the same", "No need"], 0,
        "Give through registered, trusted organisations.",
        "দান করার আগে দাতব্য সংস্থা আসল কিনা দেখা উচিত কেন?", ["ভুয়া সংস্থা দান চুরি করে", "আসলগুলো টাকা ফেরত দেয়", "সব সংস্থা একই", "দরকার নেই"],
        "নিবন্ধিত, বিশ্বস্ত সংস্থার মাধ্যমে দান করো।"),
    mcq("A family earns Rs 30,000 a month and spends Rs 27,000. How much can they save each month?", ["Rs 3,000", "Rs 57,000", "Rs 27,000", "Rs 30,000"], 0,
        "30,000 - 27,000 = Rs 3,000.",
        "একটা পরিবার মাসে 30,000 টাকা আয় করে আর 27,000 টাকা খরচ করে। প্রতি মাসে কত জমাতে পারে?", ["3,000 টাকা", "57,000 টাকা", "27,000 টাকা", "30,000 টাকা"],
        "30,000 - 27,000 = 3,000 টাকা।"),
    mcq("At Rs 3,000 a month, how much would that family save in a year?", ["Rs 36,000", "Rs 3,012", "Rs 30,000", "Rs 3,600"], 0,
        "12 x 3,000 = Rs 36,000.",
        "মাসে 3,000 টাকা হলে সেই পরিবার বছরে কত জমাবে?", ["36,000 টাকা", "3,012 টাকা", "30,000 টাকা", "3,600 টাকা"],
        "12 x 3,000 = 36,000 টাকা।"),
    mcq("What is a 'fixed cost'?", ["A cost that stays the same each month, like rent", "A cost that changes every day", "A free item", "A sale price"], 0,
        "Rent and loan payments are fixed; food and fuel can vary.",
        "'স্থির খরচ' কী?", ["যে খরচ প্রতি মাসে একই থাকে, যেমন ভাড়া", "যে খরচ রোজ বদলায়", "বিনামূল্যের জিনিস", "সেলের দাম"],
        "ভাড়া আর ঋণের কিস্তি স্থির; খাবার আর জ্বালানি বদলাতে পারে।"),
    mcq("What is a 'variable cost'?", ["A cost that changes with how much you use", "A cost that never changes", "A gift", "A savings account"], 0,
        "Electricity and fuel bills go up when you use more.",
        "'পরিবর্তনশীল খরচ' কী?", ["যে খরচ ব্যবহার অনুযায়ী বদলায়", "যে খরচ কখনো বদলায় না", "উপহার", "সঞ্চয়ী অ্যাকাউন্ট"],
        "বেশি ব্যবহার করলে বিদ্যুৎ আর জ্বালানির বিল বাড়ে।"),
    mcq("A bridge's yearly upkeep is 3% of its Rs 10,000 build cost. How much is that?", ["Rs 300", "Rs 30", "Rs 3,000", "Rs 103"], 0,
        "3% of 10,000 = 3 x 100 = Rs 300 a year. (MODIS BridgeWorks uses exactly this rule.)",
        "একটা সেতুর বার্ষিক রক্ষণাবেক্ষণ তার 10,000 টাকা নির্মাণ-খরচের 3%। কত হয়?", ["300 টাকা", "30 টাকা", "3,000 টাকা", "103 টাকা"],
        "10,000-এর 3% = 3 x 100 = বছরে 300 টাকা। (MODIS BridgeWorks ঠিক এই নিয়ম ব্যবহার করে।)"),
    mcq("What does 'percent' mean?", ["Out of 100", "Out of 10", "Out of 1000", "A type of coin"], 0,
        "10% means 10 out of every 100.",
        "'শতাংশ' মানে কী?", ["প্রতি 100-এ", "প্রতি 10-এ", "প্রতি 1000-এ", "এক রকম পয়সা"],
        "10% মানে প্রতি 100-এ 10।"),
    mcq("What is 10% of Rs 250?", ["Rs 25", "Rs 2.50", "Rs 10", "Rs 50"], 0,
        "10% = one tenth: 250 ÷ 10 = 25.",
        "250 টাকার 10% কত?", ["25 টাকা", "2.50 টাকা", "10 টাকা", "50 টাকা"],
        "10% = এক-দশমাংশ: 250 ÷ 10 = 25।"),
    mcq("What is 50% of Rs 80?", ["Rs 40", "Rs 50", "Rs 8", "Rs 130"], 0,
        "50% = half: 80 ÷ 2 = 40.",
        "80 টাকার 50% কত?", ["40 টাকা", "50 টাকা", "8 টাকা", "130 টাকা"],
        "50% = অর্ধেক: 80 ÷ 2 = 40।"),
    mcq("What is 25% of Rs 200?", ["Rs 50", "Rs 25", "Rs 75", "Rs 100"], 0,
        "25% = a quarter: 200 ÷ 4 = 50.",
        "200 টাকার 25% কত?", ["50 টাকা", "25 টাকা", "75 টাকা", "100 টাকা"],
        "25% = এক-চতুর্থাংশ: 200 ÷ 4 = 50।"),
    mcq("A Rs 400 bicycle helmet has 10% off. What is the new price?", ["Rs 360", "Rs 390", "Rs 40", "Rs 440"], 0,
        "10% of 400 = 40 off; 400 - 40 = Rs 360.",
        "400 টাকার সাইকেল-হেলমেটে 10% ছাড়। নতুন দাম কত?", ["360 টাকা", "390 টাকা", "40 টাকা", "440 টাকা"],
        "400-এর 10% = 40 ছাড়; 400 - 40 = 360 টাকা।"),
    mcq("What is 'tax'?", ["Money people and businesses pay to the government for public services", "A shop's profit", "A loan from a friend", "A free gift"], 0,
        "Taxes pay for roads, schools, hospitals and many bridges.",
        "'কর' কী?", ["জনসেবার জন্য মানুষ আর ব্যবসা সরকারকে যে টাকা দেয়", "দোকানের লাভ", "বন্ধুর ঋণ", "বিনামূল্যের উপহার"],
        "কর থেকে রাস্তা, স্কুল, হাসপাতাল আর অনেক সেতুর খরচ আসে।"),
    mcq("A Rs 100 item has Rs 5 sales tax added. What do you pay?", ["Rs 105", "Rs 95", "Rs 100", "Rs 150"], 0,
        "100 + 5 = 105.",
        "100 টাকার জিনিসে 5 টাকা বিক্রয়কর যোগ হলো। কত দেবে?", ["105 টাকা", "95 টাকা", "100 টাকা", "150 টাকা"],
        "100 + 5 = 105।"),
    mcq("What is an 'emergency fund'?", ["Savings kept for unexpected problems", "Money for sweets", "A loan", "A lottery ticket"], 0,
        "It protects you from needing a costly loan when something goes wrong.",
        "'জরুরি তহবিল' কী?", ["অপ্রত্যাশিত সমস্যার জন্য রাখা সঞ্চয়", "মিষ্টির টাকা", "ঋণ", "লটারির টিকিট"],
        "কিছু খারাপ হলে এটা তোমাকে দামি ঋণ নেওয়া থেকে বাঁচায়।"),
    mcq("Why is a lottery a poor way to plan for the future?", ["Almost everyone who buys a ticket loses money", "Lotteries always pay", "Banks prefer lotteries", "It is the safest plan"], 0,
        "The chance of winning is tiny; saving steadily is far more reliable.",
        "লটারি ভবিষ্যৎ পরিকল্পনার খারাপ উপায় কেন?", ["টিকিট কেনা প্রায় সবাই টাকা হারায়", "লটারি সবসময় টাকা দেয়", "ব্যাংক লটারি পছন্দ করে", "এটাই সবচেয়ে নিরাপদ পরিকল্পনা"],
        "জেতার সম্ভাবনা খুব কম; নিয়মিত সঞ্চয় অনেক বেশি নির্ভরযোগ্য।"),
    mcq("What is a 'wage slip' (payslip)?", ["A paper showing how much a worker earned and what was taken off", "A bus ticket", "A loan form", "A shopping list"], 0,
        "It shows pay before and after tax and other deductions.",
        "'বেতনের রসিদ' (পে-স্লিপ) কী?", ["কাগজ, যাতে লেখা কর্মী কত আয় করলেন আর কত কাটা গেল", "বাসের টিকিট", "ঋণের ফর্ম", "বাজারের তালিকা"],
        "এতে কর আর অন্য কাটার আগে আর পরের বেতন দেখায়।"),
    mcq("A worker earns Rs 500 a day and works 22 days a month. Monthly pay?", ["Rs 11,000", "Rs 522", "Rs 5,500", "Rs 10,500"], 0,
        "22 x 500 = Rs 11,000.",
        "একজন শ্রমিক দিনে 500 টাকা পান আর মাসে 22 দিন কাজ করেন। মাসিক বেতন?", ["11,000 টাকা", "522 টাকা", "5,500 টাকা", "10,500 টাকা"],
        "22 x 500 = 11,000 টাকা।"),
    mcq("Which is better value: a Rs 300 umbrella lasting 3 years or a Rs 100 one lasting 6 months?", ["The Rs 300 one (Rs 100 a year vs Rs 200 a year)", "The Rs 100 one", "They are equal", "Neither"], 0,
        "Cost per year: 300 ÷ 3 = 100; 100 ÷ 0.5 = 200.",
        "কোনটা বেশি মূল্যবান: 3 বছর টেকা 300 টাকার ছাতা নাকি 6 মাস টেকা 100 টাকার ছাতা?", ["300 টাকারটা (বছরে 100 বনাম 200 টাকা)", "100 টাকারটা", "দুটো সমান", "কোনোটাই না"],
        "বছরপ্রতি খরচ: 300 ÷ 3 = 100; 100 ÷ 0.5 = 200।"),
    mcq("What does 'credit' mean when buying?", ["Buying now and paying later", "Paying in cash immediately", "Getting it free", "Returning goods"], 0,
        "Credit is a form of borrowing - you may pay interest if you pay late.",
        "কেনার সময় 'ধারে কেনা' (ক্রেডিট) মানে কী?", ["এখন কিনে পরে দাম দেওয়া", "সঙ্গে সঙ্গে নগদে দেওয়া", "বিনামূল্যে পাওয়া", "জিনিস ফেরত দেওয়া"],
        "ক্রেডিট এক রকম ধার - দেরিতে দিলে সুদ লাগতে পারে।"),
    mcq("Why can a credit card be risky?", ["It is easy to spend more than you can repay, and interest builds up", "Cards are heavy", "It is always free", "Shops refuse them"], 0,
        "Unpaid credit card balances can grow fast with high interest.",
        "ক্রেডিট কার্ড ঝুঁকিপূর্ণ হতে পারে কেন?", ["শোধ করার সামর্থ্যের বেশি খরচ করা সহজ, আর সুদ জমে", "কার্ড ভারী", "সবসময় বিনামূল্যে", "দোকান নেয় না"],
        "শোধ না করা ক্রেডিট কার্ডের বকেয়া চড়া সুদে দ্রুত বাড়ে।"),
    mcq("What is 'saving for retirement'?", ["Saving during working years for when you stop working", "Saving for a toy", "Spending everything now", "A school subject"], 0,
        "Starting early lets interest help your savings grow for decades.",
        "'অবসরের জন্য সঞ্চয়' কী?", ["কাজের বছরগুলোয় জমানো, কাজ থামানোর পরের জন্য", "খেলনার জন্য জমানো", "এখনই সব খরচ করা", "একটা স্কুলের বিষয়"],
        "তাড়াতাড়ি শুরু করলে সুদ কয়েক দশক ধরে সঞ্চয় বাড়াতে সাহায্য করে।"),
    mcq("You plan a class trip: bus Rs 1,200, food Rs 800, tickets Rs 600. Total budget?", ["Rs 2,600", "Rs 2,000", "Rs 1,800", "Rs 3,000"], 0,
        "1200 + 800 + 600 = 2,600.",
        "তুমি ক্লাসের ভ্রমণ পরিকল্পনা করছ: বাস 1,200, খাবার 800, টিকিট 600 টাকা। মোট বাজেট?", ["2,600 টাকা", "2,000 টাকা", "1,800 টাকা", "3,000 টাকা"],
        "1200 + 800 + 600 = 2,600।"),
    mcq("If 26 students share that Rs 2,600 equally, how much does each pay?", ["Rs 100", "Rs 26", "Rs 1,000", "Rs 260"], 0,
        "2600 ÷ 26 = 100.",
        "26 জন ছাত্রছাত্রী সেই 2,600 টাকা সমানভাবে ভাগ করলে প্রত্যেকে কত দেবে?", ["100 টাকা", "26 টাকা", "1,000 টাকা", "260 টাকা"],
        "2600 ÷ 26 = 100।"),
    mcq("What is 'profit sharing' in a school stall?", ["Dividing the profit fairly among the helpers or a cause", "Keeping all profit secret", "Losing money", "Paying tax only"], 0,
        "Many school stalls share profit with a charity or class fund.",
        "স্কুল-স্টলে 'লাভ ভাগ' কী?", ["সাহায্যকারী বা কোনো ভালো কাজের মধ্যে লাভ ন্যায্যভাবে ভাগ", "সব লাভ গোপন রাখা", "টাকা হারানো", "শুধু কর দেওয়া"],
        "অনেক স্কুল-স্টল লাভ কোনো দাতব্য সংস্থা বা ক্লাস-তহবিলের সঙ্গে ভাগ করে।"),
    mcq("A stall makes Rs 600 profit and gives half to a relief camp. How much is donated?", ["Rs 300", "Rs 600", "Rs 1200", "Rs 60"], 0,
        "Half of 600 is 300.",
        "একটা স্টল 600 টাকা লাভ করে অর্ধেক ত্রাণ-শিবিরে দিল। কত দান হলো?", ["300 টাকা", "600 টাকা", "1200 টাকা", "60 টাকা"],
        "600-এর অর্ধেক 300।"),
    mcq("Why do governments sometimes give low-interest loans for public projects?", ["To make useful projects like bridges affordable", "To lose money on purpose", "To stop building", "Banks force them"], 0,
        "Cheaper borrowing helps build roads, bridges and schools that benefit everyone.",
        "সরকার কখনো জনপ্রকল্পে কম সুদে ঋণ দেয় কেন?", ["সেতুর মতো দরকারি প্রকল্প সাধ্যের মধ্যে আনতে", "ইচ্ছে করে টাকা হারাতে", "নির্মাণ থামাতে", "ব্যাংক বাধ্য করে"],
        "সস্তা ঋণ সবার উপকারী রাস্তা, সেতু আর স্কুল বানাতে সাহায্য করে।"),
    mcq("A loan of Rs 500 must be repaid in 5 equal monthly parts (no interest). How much each month?", ["Rs 100", "Rs 50", "Rs 500", "Rs 105"], 0,
        "500 ÷ 5 = Rs 100 a month. Equal payments are called instalments.",
        "500 টাকার একটা ঋণ সমান 5টি মাসিক কিস্তিতে (সুদ ছাড়া) শোধ করতে হবে। প্রতি মাসে কত?", ["100 টাকা", "50 টাকা", "500 টাকা", "105 টাকা"],
        "500 ÷ 5 = মাসে 100 টাকা। সমান পরিশোধকে কিস্তি বলে।"),
    mcq("What is an 'instalment'?", ["One of several equal payments to repay something", "A kind of furniture", "A shop", "A free gift"], 0,
        "Loans and some purchases are paid back in instalments.",
        "'কিস্তি' কী?", ["কিছু শোধ করার কয়েকটি সমান পরিশোধের একটি", "এক রকম আসবাব", "একটা দোকান", "বিনামূল্যের উপহার"],
        "ঋণ আর কিছু কেনাকাটা কিস্তিতে শোধ করা হয়।"),
    mcq("Why do businesses keep their money in a bank instead of a drawer?", ["It is safer and easier to pay suppliers and staff", "Drawers are illegal", "Banks give free shops", "It is not safer"], 0,
        "Banks protect money and make payments simple.",
        "ব্যবসা টাকা ড্রয়ারে না রেখে ব্যাংকে রাখে কেন?", ["বেশি নিরাপদ আর সরবরাহকারী ও কর্মীদের দেওয়া সহজ", "ড্রয়ার বেআইনি", "ব্যাংক বিনামূল্যে দোকান দেয়", "বেশি নিরাপদ নয়"],
        "ব্যাংক টাকা রক্ষা করে আর লেনদেন সহজ করে।"),
    mcq("What does it mean to 'budget' for a bridge?", ["Plan how much each part will cost and keep within the total", "Spend whatever you like", "Borrow as much as possible", "Ignore costs"], 0,
        "A budget keeps the project affordable - in MODIS BridgeWorks the top bar shows cost against budget.",
        "একটা সেতুর জন্য 'বাজেট করা' মানে কী?", ["প্রতিটি অংশের খরচ পরিকল্পনা করে মোটের মধ্যে থাকা", "যা খুশি খরচ করা", "যত পারো ধার করা", "খরচ উপেক্ষা করা"],
        "বাজেট প্রকল্পকে সাধ্যের মধ্যে রাখে - MODIS BridgeWorks-এ উপরের বার বাজেটের পাশে খরচ দেখায়।"),
    mcq("Which saves the most money over time?", ["Repairing small problems early", "Waiting until things break badly", "Never checking anything", "Buying the cheapest weak parts"], 0,
        "Fixing a little rust is cheap; replacing a rusted beam is expensive.",
        "সময়ের সঙ্গে কোনটায় সবচেয়ে বেশি টাকা বাঁচে?", ["ছোট সমস্যা আগেভাগে সারানো", "খারাপভাবে ভাঙা পর্যন্ত অপেক্ষা", "কখনো কিছু না দেখা", "সবচেয়ে সস্তা দুর্বল অংশ কেনা"],
        "সামান্য মরচে সারানো সস্তা; মরচে-ধরা বিম বদলানো দামি।"),
    mcq("A toll bridge earns Rs 50 a day. How much in a 30-day month?", ["Rs 1,500", "Rs 80", "Rs 150", "Rs 15,000"], 0,
        "30 x 50 = 1,500.",
        "একটা টোল সেতু দিনে 50 টাকা আয় করে। 30 দিনের মাসে কত?", ["1,500 টাকা", "80 টাকা", "150 টাকা", "15,000 টাকা"],
        "30 x 50 = 1,500।"),
    mcq("If the bridge costs Rs 300 a month to maintain, what is its monthly profit from Rs 1,500 tolls?", ["Rs 1,200", "Rs 1,800", "Rs 300", "Rs 1,500"], 0,
        "1500 - 300 = 1,200.",
        "সেতুর রক্ষণাবেক্ষণে মাসে 300 টাকা লাগলে 1,500 টাকা টোল থেকে মাসিক লাভ কত?", ["1,200 টাকা", "1,800 টাকা", "300 টাকা", "1,500 টাকা"],
        "1500 - 300 = 1,200।"),
    mcq("What is an 'investment'?", ["Spending money now hoping to earn more later", "Hiding money", "A lost coin", "A free toy"], 0,
        "Buying tools for a business or building a toll bridge are investments.",
        "'বিনিয়োগ' কী?", ["পরে বেশি পাওয়ার আশায় এখন টাকা খরচ", "টাকা লুকানো", "হারানো পয়সা", "বিনামূল্যের খেলনা"],
        "ব্যবসার যন্ত্রপাতি কেনা বা টোল সেতু বানানো বিনিয়োগ।"),
    mcq("Why is every investment risky?", ["It might earn less than hoped or even lose money", "It always doubles", "Banks guarantee it", "It is not risky"], 0,
        "Plan carefully and never invest money you cannot afford to lose.",
        "প্রতিটি বিনিয়োগ ঝুঁকিপূর্ণ কেন?", ["আশার চেয়ে কম আয় হতে পারে বা টাকা হারাতেও পারে", "সবসময় দ্বিগুণ হয়", "ব্যাংক নিশ্চয়তা দেয়", "ঝুঁকিপূর্ণ নয়"],
        "সাবধানে পরিকল্পনা করো আর এমন টাকা বিনিয়োগ কোরো না যা হারানো সামলাতে পারবে না।"),
    mcq("What is the 'payback time' of a project?", ["How long it takes for income to repay the cost", "The day of the repair", "The time a bank closes", "A school break"], 0,
        "A Rs 1,000 bridge earning Rs 250 a year has a payback time of 4 years.",
        "একটা প্রকল্পের 'খরচ ফেরতের সময়' কী?", ["আয় দিয়ে খরচ শোধ হতে কত সময় লাগে", "মেরামতের দিন", "ব্যাংক বন্ধের সময়", "স্কুলের ছুটি"],
        "বছরে 250 টাকা আয় করা 1,000 টাকার সেতুর খরচ ফেরতের সময় 4 বছর।"),
    mcq("A Rs 2,000 project earns Rs 500 a year. Payback time?", ["4 years", "2 years", "5 years", "10 years"], 0,
        "2000 ÷ 500 = 4 years.",
        "2,000 টাকার একটা প্রকল্প বছরে 500 টাকা আয় করে। খরচ ফেরতের সময়?", ["4 বছর", "2 বছর", "5 বছর", "10 বছর"],
        "2000 ÷ 500 = 4 বছর।"),
    mcq("What is 'net' income?", ["Income after costs (or tax) are taken away", "Income before costs", "Money caught in a net", "A loan"], 0,
        "Net = what is left; gross = the total before anything is taken off.",
        "'নিট' আয় কী?", ["খরচ (বা কর) বাদ দেওয়ার পরের আয়", "খরচের আগের আয়", "জালে ধরা টাকা", "একটা ঋণ"],
        "নিট = যা বাকি থাকে; মোট (গ্রস) = কিছু কাটার আগের পুরোটা।"),
    mcq("A shop sells Rs 5,000 of goods and its costs are Rs 3,500. What is its net profit?", ["Rs 1,500", "Rs 8,500", "Rs 3,500", "Rs 5,000"], 0,
        "5000 - 3500 = 1,500.",
        "একটা দোকান 5,000 টাকার মাল বেচল আর খরচ 3,500 টাকা। নিট লাভ কত?", ["1,500 টাকা", "8,500 টাকা", "3,500 টাকা", "5,000 টাকা"],
        "5000 - 3500 = 1,500।"),
    mcq("Why do people say 'don't put all your eggs in one basket' about money?", ["Spread savings so one problem cannot lose everything", "Eggs are expensive", "Baskets break", "Banks hate eggs"], 0,
        "Spreading risk is called diversification.",
        "টাকা নিয়ে মানুষ কেন বলে 'সব ডিম এক ঝুড়িতে রেখো না'?", ["সঞ্চয় ছড়িয়ে রাখো, যাতে একটা সমস্যায় সব না হারাও", "ডিম দামি", "ঝুড়ি ভাঙে", "ব্যাংক ডিম অপছন্দ করে"],
        "ঝুঁকি ছড়িয়ে দেওয়াকে বৈচিত্র্যকরণ বলে।"),
    mcq("A child earns Rs 50 a week and spends Rs 35. After 4 weeks, how much is saved?", ["Rs 60", "Rs 200", "Rs 140", "Rs 15"], 0,
        "Saves 50 - 35 = 15 a week; 4 x 15 = 60.",
        "একটি শিশু সপ্তাহে 50 টাকা আয় করে আর 35 টাকা খরচ করে। 4 সপ্তাহ পরে কত জমে?", ["60 টাকা", "200 টাকা", "140 টাকা", "15 টাকা"],
        "সপ্তাহে জমে 50 - 35 = 15; 4 x 15 = 60।"),
    mcq("Which is a sensible way to spend a Civil Grant in the game?", ["Use it to avoid a costly loan or give it to a good cause", "Ignore it forever", "Throw it away", "It cannot be used"], 0,
        "Grants cover shortfalls before loans, and Donation Camps turn them into community projects.",
        "খেলায় সিভিল অনুদান খরচের বুদ্ধিমান উপায় কোনটা?", ["দামি ঋণ এড়াতে ব্যবহার করা বা ভালো কাজে দান", "চিরকাল উপেক্ষা করা", "ফেলে দেওয়া", "ব্যবহার করা যায় না"],
        "অনুদান ঋণের আগে ঘাটতি মেটায়, আর দান-শিবির তাকে সমাজের প্রকল্পে বদলায়।"),
    mcq("What is a 'receipt' useful for at home?", ["Checking spending and returning faulty goods", "Lighting a fire", "Making paper planes", "Nothing"], 0,
        "Receipts help families track spending and claim refunds.",
        "বাড়িতে 'রসিদ' কী কাজে লাগে?", ["খরচ মিলিয়ে দেখা আর ত্রুটিপূর্ণ জিনিস ফেরত দেওয়া", "আগুন জ্বালানো", "কাগজের উড়োজাহাজ বানানো", "কিছুই না"],
        "রসিদ পরিবারকে খরচের হিসাব রাখতে আর টাকা ফেরত চাইতে সাহায্য করে।"),
    mcq("If prices go up but your pocket money stays the same, what happens?", ["You can buy less with it", "You can buy more", "Nothing", "Prices go down"], 0,
        "Rising prices (inflation) mean each rupee buys less.",
        "দাম বাড়ল কিন্তু হাতখরচ একই থাকলে কী হয়?", ["সেই টাকায় কম কেনা যায়", "বেশি কেনা যায়", "কিছুই না", "দাম কমে"],
        "দাম বাড়লে (মুদ্রাস্ফীতি) প্রতিটি টাকায় কম কেনা যায়।"),
    mcq("What is 'inflation'?", ["Prices of things rising over time", "Blowing up balloons only", "Prices falling", "Free money"], 0,
        "A sweet that cost Rs 1 long ago may cost Rs 5 today.",
        "'মুদ্রাস্ফীতি' কী?", ["সময়ের সঙ্গে জিনিসের দাম বাড়া", "শুধু বেলুন ফোলানো", "দাম কমা", "বিনামূল্যের টাকা"],
        "অনেক আগে যে লজেন্স 1 টাকা ছিল, আজ তা 5 টাকা হতে পারে।"),
    mcq("Why does saving in a bank with interest help against inflation?", ["Interest helps your money keep up with rising prices", "Banks stop inflation", "Money in banks never changes", "It does not help"], 0,
        "If interest is at least as high as inflation, your savings keep their buying power.",
        "সুদসহ ব্যাংকে জমালে মুদ্রাস্ফীতির বিরুদ্ধে সাহায্য হয় কেন?", ["সুদ তোমার টাকাকে দাম বাড়ার সঙ্গে তাল রাখতে সাহায্য করে", "ব্যাংক মুদ্রাস্ফীতি থামায়", "ব্যাংকের টাকা কখনো বদলায় না", "সাহায্য হয় না"],
        "সুদ মুদ্রাস্ফীতির সমান বা বেশি হলে সঞ্চয়ের ক্রয়ক্ষমতা অটুট থাকে।"),
    mcq("A Rs 10,000 bridge plan needs Rs 2,000 more. A government loan at 0.5% for 1 year costs how much interest on Rs 2,000?", ["Rs 10", "Rs 40", "Rs 100", "Rs 1"], 0,
        "0.5% of 2000 = 2000 x 0.5 ÷ 100 = Rs 10.",
        "10,000 টাকার একটা সেতু-পরিকল্পনায় আরও 2,000 টাকা লাগবে। 1 বছরের জন্য 0.5% সরকারি ঋণে 2,000 টাকার সুদ কত?", ["10 টাকা", "40 টাকা", "100 টাকা", "1 টাকা"],
        "2000-এর 0.5% = 2000 x 0.5 ÷ 100 = 10 টাকা।"),
    mcq("The same Rs 2,000 from a bank at 2% for 1 year costs how much interest?", ["Rs 40", "Rs 10", "Rs 200", "Rs 4"], 0,
        "2% of 2000 = 40 - four times the government loan's cost.",
        "একই 2,000 টাকা ব্যাংক থেকে 2%-এ 1 বছরের জন্য নিলে সুদ কত?", ["40 টাকা", "10 টাকা", "200 টাকা", "4 টাকা"],
        "2000-এর 2% = 40 - সরকারি ঋণের খরচের চার গুণ।"),
    mcq("What is a 'cheque'?", ["A written order telling a bank to pay someone", "A chess move", "A price tag", "A coin"], 0,
        "Cheques are less common now, but still used for some payments.",
        "'চেক' কী?", ["কাউকে টাকা দিতে ব্যাংককে লিখিত নির্দেশ", "দাবার চাল", "দামের ট্যাগ", "একটা পয়সা"],
        "চেক এখন কম ব্যবহার হয়, তবে কিছু লেনদেনে এখনো চলে।"),
    mcq("What is 'online banking'?", ["Managing your bank account using the internet", "Banking on a rope", "Paying with coins only", "A bank in a boat"], 0,
        "Always use secure apps and never share passwords.",
        "'অনলাইন ব্যাংকিং' কী?", ["ইন্টারনেটে ব্যাংক অ্যাকাউন্ট পরিচালনা", "দড়ির উপর ব্যাংকিং", "শুধু পয়সায় দাম দেওয়া", "নৌকায় ব্যাংক"],
        "সবসময় সুরক্ষিত অ্যাপ ব্যবহার করো আর পাসওয়ার্ড কাউকে দিয়ো না।"),
    mcq("A website offers a phone worth Rs 20,000 for Rs 500. What is most likely?", ["It is a scam", "It is a real bargain", "It is a government grant", "Phones are cheap"], 0,
        "If it seems too good to be true, it probably is. Buy from trusted shops.",
        "একটা ওয়েবসাইট 20,000 টাকার ফোন 500 টাকায় দিচ্ছে। সবচেয়ে সম্ভাব্য কী?", ["এটা প্রতারণা", "এটা আসল সুযোগ", "এটা সরকারি অনুদান", "ফোন সস্তা"],
        "বিশ্বাস করা কঠিন রকম ভালো মনে হলে সম্ভবত ফাঁদ। বিশ্বস্ত দোকান থেকে কেনো।"),
    mcq("Why is it good to talk with your family about money?", ["You learn how to plan, save and avoid mistakes", "Money talk is rude", "It wastes time", "It is not good"], 0,
        "Learning money skills early helps for life.",
        "পরিবারের সঙ্গে টাকা নিয়ে কথা বলা ভালো কেন?", ["পরিকল্পনা, সঞ্চয় আর ভুল এড়ানো শেখা যায়", "টাকার কথা অভদ্রতা", "সময় নষ্ট", "ভালো নয়"],
        "তাড়াতাড়ি টাকার দক্ষতা শিখলে সারাজীবন কাজে লাগে।"),
    mcq("Which helps a business grow?", ["Reinvesting some profit into better tools or more stock", "Spending all profit on treats", "Never paying workers", "Closing early every day"], 0,
        "Putting profit back into the business builds it up over time.",
        "কোনটা ব্যবসা বাড়াতে সাহায্য করে?", ["লাভের কিছুটা ভালো যন্ত্র বা বেশি মজুতে আবার লাগানো", "সব লাভ শখে খরচ", "কখনো কর্মীদের বেতন না দেওয়া", "রোজ তাড়াতাড়ি বন্ধ করা"],
        "লাভ ব্যবসায় ফিরিয়ে দিলে সময়ের সঙ্গে ব্যবসা বড় হয়।"),
    mcq("Rs 3 a day saved for 100 days makes...", ["Rs 300", "Rs 103", "Rs 30", "Rs 3,000"], 0,
        "100 x 3 = 300.",
        "100 দিন ধরে দিনে 3 টাকা জমালে হয়...", ["300 টাকা", "103 টাকা", "30 টাকা", "3,000 টাকা"],
        "100 x 3 = 300।"),
    mcq("What is the best way to stop impulse buying?", ["Wait a day before buying something you did not plan", "Buy faster", "Carry more cash", "Shop when bored"], 0,
        "A short wait often shows you did not really need it.",
        "হঠাৎ কেনা থামানোর সবচেয়ে ভালো উপায় কী?", ["অপরিকল্পিত কিছু কেনার আগে একদিন অপেক্ষা", "আরও তাড়াতাড়ি কেনা", "বেশি নগদ রাখা", "একঘেয়ে লাগলে কেনাকাটা"],
        "অল্প অপেক্ষাতেই প্রায়ই বোঝা যায় আসলে দরকার ছিল না।"),
    mcq("A relief bridge kit costs Rs 80,000. If 400 people each give Rs 200, is the target reached?", ["Yes, exactly Rs 80,000", "No, short by Rs 200", "No, short by Rs 40,000", "Yes, with Rs 8,000 extra"], 0,
        "400 x 200 = 80,000. Together, many small gifts build big things.",
        "একটা ত্রাণ-সেতু কিটের দাম 80,000 টাকা। 400 জন প্রত্যেকে 200 টাকা দিলে কি লক্ষ্য পূরণ হয়?", ["হ্যাঁ, ঠিক 80,000 টাকা", "না, 200 টাকা কম", "না, 40,000 টাকা কম", "হ্যাঁ, 8,000 টাকা বাড়তি"],
        "400 x 200 = 80,000। অনেক ছোট দান মিলে বড় কাজ হয়।"),
    mcq("What is 'financial literacy'?", ["Knowing how to manage money well", "Reading storybooks about money", "Counting coins fast only", "Owning a bank"], 0,
        "It means understanding saving, spending, borrowing, giving and risk.",
        "'আর্থিক সাক্ষরতা' কী?", ["টাকা ভালোভাবে সামলাতে জানা", "টাকা নিয়ে গল্পের বই পড়া", "শুধু দ্রুত পয়সা গোনা", "একটা ব্যাংকের মালিক হওয়া"],
        "এর মানে সঞ্চয়, খরচ, ধার, দান আর ঝুঁকি বোঝা।"),
    unit(350, 7, "bus tickets", "বাসের টিকিট"),
    unit(96, 8, "cupcakes", "কাপকেক"),
    interest(600, 5, 2),
    interest(250, 4, 3),
    mcq("What is a 'deposit' when you rent a room or a tool?", ["Money held as a promise, returned if nothing is damaged", "A gift to the owner", "A tax", "A loan you never repay"], 0,
        "A deposit protects the owner; you get it back if you return things in good condition.",
        "ঘর বা যন্ত্র ভাড়া নিলে 'জামানত' কী?", ["প্রতিশ্রুতি হিসেবে রাখা টাকা, কিছু নষ্ট না হলে ফেরত", "মালিককে উপহার", "একটা কর", "যে ঋণ কখনো শোধ হয় না"],
        "জামানত মালিককে রক্ষা করে; ভালো অবস্থায় ফেরত দিলে টাকা ফেরত পাও।"),
    mcq("Why do builders keep a 'contingency' amount in a bridge budget?", ["To pay for surprises like bad weather or price rises", "To buy sweets", "To pay fines on purpose", "It is not needed"], 0,
        "A contingency (often 5-10%) stops surprises from pushing the project over budget.",
        "নির্মাতারা সেতুর বাজেটে 'আপৎকালীন' টাকা রাখেন কেন?", ["খারাপ আবহাওয়া বা দামবৃদ্ধির মতো আচমকা খরচ মেটাতে", "মিষ্টি কিনতে", "ইচ্ছে করে জরিমানা দিতে", "দরকার নেই"],
        "আপৎকালীন অঙ্ক (প্রায়ই 5-10%) আচমকা খরচে প্রকল্পকে বাজেটের বাইরে যেতে দেয় না।"),
    mcq("A bridge budget is Rs 10,000 with a 10% contingency. How much is kept for surprises?", ["Rs 1,000", "Rs 100", "Rs 10", "Rs 11,000"], 0,
        "10% of 10,000 = 1,000.",
        "একটা সেতুর বাজেট 10,000 টাকা, তাতে 10% আপৎকালীন। আচমকা খরচের জন্য কত রাখা হলো?", ["1,000 টাকা", "100 টাকা", "10 টাকা", "11,000 টাকা"],
        "10,000-এর 10% = 1,000।"),
    mcq("Which is a fair way to share a group prize of Rs 90 among 3 team members who worked equally?", ["Rs 30 each", "Rs 90 to one person", "Rs 10 each", "Keep it all for the captain"], 0,
        "Equal work, equal share: 90 ÷ 3 = 30.",
        "সমান কাজ করা দলের 3 জন সদস্যের মধ্যে 90 টাকার পুরস্কার ভাগের ন্যায্য উপায় কোনটা?", ["প্রত্যেকে 30 টাকা", "একজনকে 90 টাকা", "প্রত্যেকে 10 টাকা", "সবটা অধিনায়কের"],
        "সমান কাজ, সমান ভাগ: 90 ÷ 3 = 30।"),
)
