"""Class 3 - Chemistry: rocks and soils, building stone, fossils, changes of state and the
water cycle, dissolving and separating, and how building materials behave."""
from . import mcq

ITEMS = (
    mcq("Which rock is very hard and often used for bridge piers and kerbs?", ["Granite", "Chalk", "Clay", "Sandstone that crumbles"], 0,
        "Granite is a tough igneous rock made from cooled magma - strong in compression and hard-wearing.",
        "কোন পাথর খুব শক্ত আর প্রায়ই সেতুর স্তম্ভ আর রাস্তার কিনারায় ব্যবহার হয়?", ["গ্রানাইট", "চক", "কাদামাটি", "ঝুরঝুরে বেলেপাথর"],
        "গ্রানাইট ঠান্ডা ম্যাগমা থেকে তৈরি শক্ত আগ্নেয় শিলা - চাপে মজবুত আর ক্ষয়রোধী।"),
    mcq("How are igneous rocks formed?", ["Hot melted rock (magma) cools and hardens", "Layers of sand press together", "Heat and pressure change other rocks", "Shells dissolve"], 0,
        "Igneous rocks like granite and basalt come from volcanoes or magma underground.",
        "আগ্নেয় শিলা কীভাবে তৈরি হয়?", ["গরম গলা পাথর (ম্যাগমা) ঠান্ডা হয়ে শক্ত হয়", "বালির স্তর চাপে জোড়া লাগে", "তাপ আর চাপে অন্য শিলা বদলায়", "খোলস গলে যায়"],
        "গ্রানাইট আর ব্যাসল্টের মতো আগ্নেয় শিলা আসে আগ্নেয়গিরি বা মাটির নিচের ম্যাগমা থেকে।"),
    mcq("How are sedimentary rocks like sandstone formed?", ["Layers of sand, mud or shells are pressed together over a long time", "Lava cools quickly", "Ice melts", "Lightning strikes"], 0,
        "Sediments settle in layers and slowly cement into rock - fossils are often found in them.",
        "বেলেপাথরের মতো পাললিক শিলা কীভাবে তৈরি হয়?", ["বালি, কাদা বা খোলসের স্তর দীর্ঘ সময় ধরে চাপে জোড়া লাগে", "লাভা দ্রুত ঠান্ডা হয়", "বরফ গলে", "বজ্রপাত হয়"],
        "পলি স্তরে স্তরে জমে ধীরে ধীরে শিলা হয় - এতে প্রায়ই জীবাশ্ম পাওয়া যায়।"),
    mcq("Marble is a metamorphic rock. What does that mean?", ["It was changed by heat and pressure from another rock (limestone)", "It came straight from a volcano", "It is made of wood", "It is a liquid"], 0,
        "Heat and pressure deep underground transform limestone into marble.",
        "মার্বেল রূপান্তরিত শিলা। এর মানে কী?", ["অন্য শিলা (চুনাপাথর) থেকে তাপ আর চাপে বদলে তৈরি", "সরাসরি আগ্নেয়গিরি থেকে এসেছে", "কাঠের তৈরি", "এটা তরল"],
        "মাটির গভীরে তাপ আর চাপ চুনাপাথরকে মার্বেলে বদলায়।"),
    mcq("What is a fossil?", ["The remains or print of a living thing preserved in rock", "A shiny crystal", "A new rock from a volcano", "A type of soil"], 0,
        "Fossils form when plants or animals are buried in sediment that slowly turns to rock.",
        "জীবাশ্ম কী?", ["শিলায় সংরক্ষিত কোনো জীবের দেহাবশেষ বা ছাপ", "চকচকে কেলাস", "আগ্নেয়গিরির নতুন শিলা", "এক রকম মাটি"],
        "গাছ বা প্রাণী পলিতে চাপা পড়লে আর সেই পলি ধীরে শিলা হলে জীবাশ্ম তৈরি হয়।"),
    mcq("Soil is made of...", ["Tiny bits of rock, rotted plants and animals, air and water", "Only sand", "Only water", "Plastic"], 0,
        "Soil mixes broken rock with humus (dead plant matter), air and water.",
        "মাটি তৈরি হয়...", ["পাথরের ছোট কণা, পচা গাছ আর প্রাণী, বাতাস আর জল দিয়ে", "শুধু বালি দিয়ে", "শুধু জল দিয়ে", "প্লাস্টিক দিয়ে"],
        "মাটিতে ভাঙা পাথর, হিউমাস (মৃত উদ্ভিদাংশ), বাতাস আর জল মেশানো থাকে।"),
    mcq("Which soil lets water drain through fastest?", ["Sandy soil", "Clay soil", "Concrete", "Rock"], 0,
        "Sand grains are big with large gaps, so water runs through quickly.",
        "কোন মাটির মধ্য দিয়ে জল সবচেয়ে দ্রুত নেমে যায়?", ["বেলে মাটি", "এঁটেল মাটি", "কংক্রিট", "পাথর"],
        "বালির দানা বড় আর ফাঁক বেশি, তাই জল দ্রুত বয়ে যায়।"),
    mcq("Which soil holds lots of water and becomes sticky?", ["Clay soil", "Sandy soil", "Gravel", "Chalk pieces"], 0,
        "Clay has tiny particles and tiny gaps, so it holds water and swells.",
        "কোন মাটি অনেক জল ধরে আর আঠালো হয়?", ["এঁটেল মাটি", "বেলে মাটি", "নুড়ি", "চকের টুকরো"],
        "এঁটেল মাটির কণা খুব ছোট আর ফাঁকও ছোট, তাই জল ধরে ফুলে ওঠে।"),
    mcq("Why do engineers test the soil before building a bridge?", ["To know if it can carry the weight without sinking", "To grow flowers", "To find gold", "For fun"], 0,
        "Soft or wet soil may need deeper foundations or piles down to firm rock.",
        "সেতু বানানোর আগে প্রকৌশলীরা মাটি পরীক্ষা করেন কেন?", ["না বসে ওজন বইতে পারবে কিনা জানতে", "ফুল ফোটাতে", "সোনা খুঁজতে", "মজার জন্য"],
        "নরম বা ভেজা মাটিতে গভীর ভিত বা শক্ত পাথর পর্যন্ত পাইল লাগতে পারে।"),
    mcq("What are 'piles' under a bridge?", ["Long columns driven deep into the ground to reach firm layers", "Heaps of sand", "Stacks of money", "Piles of leaves"], 0,
        "Piles carry loads down through soft soil to strong rock or dense ground.",
        "সেতুর নিচের 'পাইল' কী?", ["শক্ত স্তরে পৌঁছাতে মাটির গভীরে পোঁতা লম্বা স্তম্ভ", "বালির স্তূপ", "টাকার গাদা", "পাতার স্তূপ"],
        "পাইল নরম মাটি পেরিয়ে শক্ত পাথর বা ঘন মাটিতে ভার পৌঁছে দেয়।"),
    mcq("Which rock fizzes with vinegar?", ["Limestone (and chalk)", "Granite", "Slate", "Basalt"], 0,
        "Limestone is calcium carbonate; acids react with it and give off carbon dioxide.",
        "কোন পাথর ভিনেগারে বুদবুদ ছাড়ে?", ["চুনাপাথর (আর চক)", "গ্রানাইট", "স্লেট", "ব্যাসল্ট"],
        "চুনাপাথর ক্যালসিয়াম কার্বনেট; অম্ল এর সঙ্গে বিক্রিয়া করে কার্বন ডাই-অক্সাইড ছাড়ে।"),
    mcq("Slate is used for roofs because it...", ["Splits into thin flat waterproof sheets", "Is soft and squashy", "Floats", "Dissolves in rain"], 0,
        "Slate splits neatly into thin layers that keep rain out.",
        "স্লেট ছাদে ব্যবহার হয় কারণ এটা...", ["পাতলা চ্যাপ্টা জলরোধী পাতে ভাগ হয়", "নরম আর চাপলে বসে", "ভাসে", "বৃষ্টিতে গলে যায়"],
        "স্লেট সুন্দরভাবে পাতলা স্তরে ভাগ হয়, যা বৃষ্টি আটকায়।"),
    mcq("Cement is made mainly by heating...", ["Limestone and clay", "Sugar and salt", "Wood and wool", "Sand and glass"], 0,
        "Limestone and clay are heated in a kiln and ground into grey powder.",
        "সিমেন্ট মূলত তৈরি হয় গরম করে...", ["চুনাপাথর আর কাদামাটি", "চিনি আর নুন", "কাঠ আর উল", "বালি আর কাচ"],
        "চুনাপাথর আর কাদামাটি চুল্লিতে গরম করে গুঁড়িয়ে ধূসর পাউডার বানানো হয়।"),
    mcq("What is the difference between cement and concrete?", ["Cement is the glue; concrete is cement plus sand, stones and water", "They are the same", "Concrete is a metal", "Cement is a liquid metal"], 0,
        "Cement on its own is a powder; mixed with aggregate and water it makes concrete.",
        "সিমেন্ট আর কংক্রিটের পার্থক্য কী?", ["সিমেন্ট হলো আঠা; কংক্রিট হলো সিমেন্ট, বালি, পাথরকুচি আর জল", "দুটো একই", "কংক্রিট একটা ধাতু", "সিমেন্ট তরল ধাতু"],
        "সিমেন্ট একা একটা পাউডার; পাথরকুচি আর জলে মেশালে কংক্রিট হয়।"),
    mcq("Why does fresh concrete get warm as it sets?", ["The chemical reaction with water gives out heat", "The sun heats it only", "Builders heat it", "It does not"], 0,
        "Cement hardening is an exothermic reaction - it releases heat.",
        "তাজা কংক্রিট জমার সময় গরম হয় কেন?", ["জলের সঙ্গে রাসায়নিক বিক্রিয়ায় তাপ বেরোয়", "শুধু সূর্য গরম করে", "নির্মাতারা গরম করেন", "গরম হয় না"],
        "সিমেন্ট শক্ত হওয়া একটা তাপোৎপাদী বিক্রিয়া - তাপ ছাড়ে।"),
    mcq("What is 'mortar' used for?", ["Sticking bricks or stones together", "Painting walls", "Making glass", "Cooking rice"], 0,
        "Mortar is cement or lime, sand and water - the glue between bricks.",
        "'মশলা' (মর্টার) কীসে ব্যবহার হয়?", ["ইট বা পাথর জুড়তে", "দেয়াল রং করতে", "কাচ বানাতে", "ভাত রান্না করতে"],
        "মশলা হলো সিমেন্ট বা চুন, বালি আর জল - ইটের মাঝের আঠা।"),
    mcq("Why must bricks be fired (baked) and not just dried?", ["Firing makes them hard and water-resistant", "To change their colour only", "Firing makes them float", "It does not matter"], 0,
        "Sun-dried mud bricks soften in rain; fired bricks last for centuries.",
        "ইট শুধু শুকানো নয়, পোড়াতে হয় কেন?", ["পোড়ালে শক্ত আর জলরোধী হয়", "শুধু রং বদলাতে", "পোড়ালে ভাসে", "কিছু যায় আসে না"],
        "রোদে শুকানো কাদার ইট বৃষ্টিতে নরম হয়; পোড়া ইট শতাব্দী টেকে।"),
    mcq("Which change of state happens when steam touches a cold window?", ["Condensation", "Melting", "Freezing", "Burning"], 0,
        "Water vapour cools and turns back into liquid drops.",
        "বাষ্প ঠান্ডা জানালায় লাগলে কোন অবস্থান্তর হয়?", ["ঘনীভবন", "গলন", "জমে যাওয়া", "দহন"],
        "জলীয় বাষ্প ঠান্ডা হয়ে আবার তরল ফোঁটা হয়।"),
    mcq("What makes washing dry faster?", ["Warmth, wind and spreading it out", "Folding it in a pile", "Keeping it in a dark box", "Adding more water"], 0,
        "Heat, moving air and a big surface area speed up evaporation.",
        "কী করলে কাপড় তাড়াতাড়ি শুকায়?", ["উষ্ণতা, বাতাস আর ছড়িয়ে দেওয়া", "গাদা করে ভাঁজ রাখা", "অন্ধকার বাক্সে রাখা", "আরও জল দেওয়া"],
        "তাপ, চলমান বাতাস আর বড় তল বাষ্পীভবন দ্রুত করে।"),
    mcq("In the water cycle, what happens after water evaporates from the sea?", ["The vapour rises, cools and condenses into clouds", "It turns into salt", "It sinks to the sea floor", "It disappears for ever"], 0,
        "Clouds form, rain falls, rivers flow back to the sea - and round it goes.",
        "জলচক্রে সমুদ্র থেকে জল বাষ্পীভূত হওয়ার পর কী হয়?", ["বাষ্প উঠে ঠান্ডা হয়ে মেঘে ঘনীভূত হয়", "নুন হয়ে যায়", "সমুদ্রের তলায় ডোবে", "চিরতরে উধাও হয়"],
        "মেঘ হয়, বৃষ্টি পড়ে, নদী আবার সমুদ্রে বয় - আর এভাবেই ঘোরে।"),
    mcq("What is 'precipitation' in the water cycle?", ["Water falling as rain, snow or hail", "Water rising as vapour", "Water in a tap", "Water freezing in a fridge"], 0,
        "Precipitation is any water falling from clouds.",
        "জলচক্রে 'অধঃক্ষেপণ' কী?", ["বৃষ্টি, তুষার বা শিলা হয়ে জল পড়া", "বাষ্প হয়ে জল ওঠা", "কলের জল", "ফ্রিজে জল জমা"],
        "মেঘ থেকে যেকোনো রূপে জল পড়াকে অধঃক্ষেপণ বলে।"),
    mcq("Why do bridges over rivers need to be designed for floods?", ["Heavy rain makes rivers rise and push hard on piers", "Floods are rare everywhere", "Water is light", "Fish push bridges"], 0,
        "Flood water carries great force and debris, so piers and decks must be strong and high enough.",
        "নদীর সেতুকে বন্যার কথা ভেবে নকশা করতে হয় কেন?", ["ভারী বৃষ্টিতে নদী ফুলে স্তম্ভে জোরে ঠেলে", "সব জায়গায় বন্যা বিরল", "জল হালকা", "মাছ সেতু ঠেলে"],
        "বন্যার জল বিশাল জোর আর ভাসমান আবর্জনা বয়, তাই স্তম্ভ আর ডেক যথেষ্ট শক্ত আর উঁচু হতে হয়।"),
    mcq("Salt water and pure water: which freezes at a lower temperature?", ["Salt water", "Pure water", "Both at exactly 0 °C", "Neither ever freezes"], 0,
        "Salt lowers the freezing point. That is why salt is spread on icy roads and bridges.",
        "নোনা জল আর বিশুদ্ধ জল: কোনটা কম তাপমাত্রায় জমে?", ["নোনা জল", "বিশুদ্ধ জল", "দুটোই ঠিক 0 °C-এ", "কোনোটাই কখনো জমে না"],
        "নুন হিমাঙ্ক কমায়। এজন্যই বরফে ঢাকা রাস্তা আর সেতুতে নুন ছড়ানো হয়।"),
    mcq("Why can road salt be bad for steel and concrete bridges?", ["Salt speeds up rusting of the steel inside", "Salt makes concrete float", "Salt is too heavy", "It is never bad"], 0,
        "Salty water soaks into concrete and attacks the steel bars. Bridges need protection and washing.",
        "রাস্তার নুন ইস্পাত আর কংক্রিটের সেতুর জন্য খারাপ হতে পারে কেন?", ["নুন ভেতরের ইস্পাতের মরচে দ্রুত করে", "নুন কংক্রিট ভাসায়", "নুন খুব ভারী", "কখনো খারাপ নয়"],
        "নোনা জল কংক্রিটে ঢুকে ইস্পাতের রড আক্রমণ করে। সেতুর সুরক্ষা আর ধোয়া লাগে।"),
    mcq("How can you separate sand from water?", ["Filter it", "Use a magnet", "Freeze it", "Stir it"], 0,
        "Filter paper traps sand grains and lets water through.",
        "জল থেকে বালি কীভাবে আলাদা করবে?", ["ছেঁকে (ফিল্টার করে)", "চুম্বক দিয়ে", "জমিয়ে", "নেড়ে"],
        "ফিল্টার পেপার বালির দানা আটকায় আর জল যেতে দেয়।"),
    mcq("How can you separate salt from salt water?", ["Evaporate the water", "Filter it", "Use a magnet", "Use a sieve"], 0,
        "Dissolved salt passes through filters; evaporating the water leaves it behind.",
        "নোনা জল থেকে নুন কীভাবে আলাদা করবে?", ["জল বাষ্পীভূত করে", "ছেঁকে", "চুম্বক দিয়ে", "চালুনি দিয়ে"],
        "গলে থাকা নুন ফিল্টার দিয়ে চলে যায়; জল উবে গেলে নুন পড়ে থাকে।"),
    mcq("How can you separate pebbles from sand?", ["Use a sieve", "Evaporate them", "Dissolve them", "Use a thermometer"], 0,
        "A sieve with the right hole size keeps the pebbles and lets the sand fall through.",
        "বালি থেকে নুড়ি কীভাবে আলাদা করবে?", ["চালুনি দিয়ে", "বাষ্পীভূত করে", "গলিয়ে", "থার্মোমিটার দিয়ে"],
        "ঠিক মাপের ছিদ্রের চালুনি নুড়ি রাখে আর বালি নিচে পড়তে দেয়।"),
    mcq("Builders grade gravel by size for concrete. Which tool do they use?", ["Sieves of different sizes", "A magnet", "A thermometer", "A clock"], 0,
        "A stack of sieves sorts stones into sizes for strong concrete mixes.",
        "কংক্রিটের জন্য নির্মাতারা পাথরকুচি মাপ অনুযায়ী বাছেন। কোন যন্ত্র ব্যবহার করেন?", ["নানা মাপের চালুনি", "চুম্বক", "থার্মোমিটার", "ঘড়ি"],
        "চালুনির থাক মজবুত কংক্রিটের জন্য পাথর মাপ অনুযায়ী আলাদা করে।"),
    mcq("What do we call a liquid that something dissolves in?", ["A solvent", "A solute", "A solid", "A crystal"], 0,
        "In sugar water, water is the solvent and sugar is the solute.",
        "যে তরলে কিছু দ্রবীভূত হয় তাকে কী বলি?", ["দ্রাবক", "দ্রাব", "কঠিন", "কেলাস"],
        "চিনি-জলে জল দ্রাবক আর চিনি দ্রাব।"),
    mcq("What do we call the thing that dissolves, like sugar in tea?", ["The solute", "The solvent", "The container", "The filter"], 0,
        "The solute dissolves into the solvent to make a solution.",
        "যা দ্রবীভূত হয়, যেমন চায়ে চিনি, তাকে কী বলি?", ["দ্রাব", "দ্রাবক", "পাত্র", "ছাঁকনি"],
        "দ্রাব দ্রাবকে গলে দ্রবণ তৈরি করে।"),
    mcq("You keep adding sugar to water and stirring. Eventually...", ["No more dissolves - it is saturated", "It turns into ice", "The water disappears", "The sugar turns into salt"], 0,
        "A saturated solution cannot dissolve any more solute at that temperature.",
        "জলে বারবার চিনি দিয়ে নাড়তে থাকলে শেষে...", ["আর গলে না - দ্রবণ সম্পৃক্ত", "বরফ হয়ে যায়", "জল উধাও হয়", "চিনি নুন হয়ে যায়"],
        "সম্পৃক্ত দ্রবণ সেই তাপমাত্রায় আর দ্রাব গলাতে পারে না।"),
    mcq("Oil paint does not wash off with water. What do painters clean brushes with?", ["A different solvent such as white spirit", "Salt", "Sand", "Ice"], 0,
        "Different substances dissolve in different solvents.",
        "তেলরং জলে ধোয় না। রং-মিস্ত্রিরা তুলি কী দিয়ে পরিষ্কার করেন?", ["হোয়াইট স্পিরিটের মতো অন্য দ্রাবক", "নুন", "বালি", "বরফ"],
        "ভিন্ন পদার্থ ভিন্ন দ্রাবকে গলে।"),
    mcq("What happens to iron when it rusts?", ["It slowly reacts with oxygen and water to make a new flaky substance", "It melts", "It turns into gold", "It grows stronger"], 0,
        "Rust (iron oxide) is weak and flaky, so rusting weakens steel structures.",
        "মরচে ধরলে লোহার কী হয়?", ["অক্সিজেন আর জলের সঙ্গে ধীরে বিক্রিয়ায় নতুন ঝুরঝুরে পদার্থ হয়", "গলে যায়", "সোনা হয়", "আরও শক্ত হয়"],
        "মরচে (আয়রন অক্সাইড) দুর্বল আর ঝুরঝুরে, তাই মরচে ইস্পাতের কাঠামো দুর্বল করে।"),
    mcq("Nails in three tubes: one in dry air, one in plain water, one in salty water. Which rusts most?", ["The one in salty water", "The one in dry air", "The one in plain water", "None rusts"], 0,
        "Salt speeds rusting; dry air with no water barely rusts.",
        "তিনটি নলে পেরেক: একটা শুকনো বাতাসে, একটা সাধারণ জলে, একটা নোনা জলে। কোনটায় সবচেয়ে বেশি মরচে?", ["নোনা জলেরটায়", "শুকনো বাতাসেরটায়", "সাধারণ জলেরটায়", "কোনোটাতেই না"],
        "নুন মরচে দ্রুত করে; জল ছাড়া শুকনো বাতাসে প্রায় মরচে ধরে না।"),
    mcq("What is 'galvanising'?", ["Coating steel with zinc to stop rust", "Painting wood blue", "Melting glass", "Freezing water"], 0,
        "Zinc protects steel - even when scratched, the zinc corrodes first.",
        "'গ্যালভানাইজিং' কী?", ["মরচে ঠেকাতে ইস্পাতে দস্তার প্রলেপ", "কাঠ নীল রং করা", "কাচ গলানো", "জল জমানো"],
        "দস্তা ইস্পাতকে রক্ষা করে - আঁচড় লাগলেও আগে দস্তা ক্ষয় হয়।"),
    mcq("Which property makes rubber good for car tyres?", ["Flexible, grippy and waterproof", "Brittle and see-through", "Magnetic", "Soluble in water"], 0,
        "Rubber bends, grips the road and keeps air in.",
        "রাবারের কোন গুণ গাড়ির টায়ারের জন্য ভালো?", ["নমনীয়, আঁকড়ে ধরে আর জলরোধী", "ভঙ্গুর আর স্বচ্ছ", "চৌম্বক", "জলে দ্রাব্য"],
        "রাবার বাঁকে, রাস্তা আঁকড়ে ধরে আর বাতাস আটকে রাখে।"),
    mcq("Which property makes glass good for windows?", ["Transparent and waterproof", "Flexible like rubber", "Magnetic", "Absorbent"], 0,
        "Glass lets light in and keeps rain out, though it is brittle.",
        "কাচের কোন গুণ জানালার জন্য ভালো?", ["স্বচ্ছ আর জলরোধী", "রাবারের মতো নমনীয়", "চৌম্বক", "শোষক"],
        "কাচ আলো ঢুকতে দেয় আর বৃষ্টি আটকায়, যদিও ভঙ্গুর।"),
    mcq("Which property makes steel good for bridge beams?", ["Very strong in tension and compression", "See-through", "Soft and squashy", "Dissolves in rain"], 0,
        "Steel can be pulled and pushed hard without breaking.",
        "ইস্পাতের কোন গুণ সেতুর বিমের জন্য ভালো?", ["টানে আর চাপে খুব শক্ত", "স্বচ্ছ", "নরম আর চাপলে বসে", "বৃষ্টিতে গলে"],
        "ইস্পাতকে না ভেঙে জোরে টানা আর ঠেলা যায়।"),
    mcq("A material that cannot be scratched easily is described as...", ["Hard", "Soft", "Flexible", "Transparent"], 0,
        "Diamond and steel are hard; chalk and wax are soft.",
        "যে উপাদানে সহজে আঁচড় কাটা যায় না তাকে বলে...", ["কঠিন", "নরম", "নমনীয়", "স্বচ্ছ"],
        "হীরে আর ইস্পাত কঠিন; চক আর মোম নরম।"),
    mcq("Why is wood a good material for a small footbridge in a park?", ["It is light, strong enough and easy to work with", "It never rots", "It is magnetic", "It is see-through"], 0,
        "Timber is cheap and easy to cut and join - great for short, light spans if protected from rot.",
        "পার্কের ছোট হাঁটার সেতুর জন্য কাঠ ভালো কেন?", ["হালকা, যথেষ্ট শক্ত আর কাজ করা সহজ", "কখনো পচে না", "চৌম্বক", "স্বচ্ছ"],
        "কাঠ সস্তা আর কাটা-জোড়া সহজ - পচন থেকে রক্ষা করলে ছোট, হালকা স্প্যানের জন্য দারুণ।"),
    mcq("What is 'plywood'?", ["Thin wood layers glued with the grain crossing", "Wood from one huge tree slice", "Plastic painted like wood", "Wood soaked in water"], 0,
        "Crossing the grain makes plywood strong in every direction and less likely to split.",
        "'প্লাইউড' কী?", ["আঁশ আড়াআড়ি রেখে আঠায় জোড়া পাতলা কাঠের স্তর", "এক বিশাল গাছের একটা টুকরো", "কাঠের মতো রং করা প্লাস্টিক", "জলে ভেজানো কাঠ"],
        "আঁশ আড়াআড়ি থাকলে প্লাইউড সব দিকে শক্ত হয় আর সহজে ফাটে না।"),
    mcq("Why do people treat wooden fence posts with special chemicals?", ["To stop rot and insects", "To make them taller", "To make them magnetic", "To make them float"], 0,
        "Preservatives protect wood from fungi and termites.",
        "মানুষ কাঠের বেড়ার খুঁটিতে বিশেষ রাসায়নিক দেয় কেন?", ["পচন আর পোকা ঠেকাতে", "লম্বা করতে", "চৌম্বক করতে", "ভাসাতে"],
        "সংরক্ষক কাঠকে ছত্রাক আর উইপোকা থেকে রক্ষা করে।"),
    mcq("Which change is a chemical change?", ["Burning wood", "Melting ice", "Dissolving sugar", "Cutting paper"], 0,
        "Burning makes new substances (ash, smoke, gases) and cannot be undone.",
        "কোন পরিবর্তন রাসায়নিক পরিবর্তন?", ["কাঠ পোড়ানো", "বরফ গলানো", "চিনি গলানো", "কাগজ কাটা"],
        "পোড়ানো নতুন পদার্থ (ছাই, ধোঁয়া, গ্যাস) তৈরি করে আর ফেরানো যায় না।"),
    mcq("Which change is a physical change?", ["Ice melting", "An egg frying", "Iron rusting", "Wood burning"], 0,
        "Melting changes only the state; it is still water.",
        "কোন পরিবর্তন ভৌত পরিবর্তন?", ["বরফ গলা", "ডিম ভাজা", "লোহায় মরচে", "কাঠ পোড়া"],
        "গলনে শুধু অবস্থা বদলায়; এটা তখনও জল।"),
    mcq("Which is the best sign that a chemical reaction happened when concrete sets?", ["It becomes a hard new material and cannot go back", "It gets wet", "It changes colour only when painted", "It gets lighter only"], 0,
        "Setting concrete forms new crystals - it never turns back into powder and water.",
        "কংক্রিট জমার সময় রাসায়নিক বিক্রিয়া হয়েছে তার সেরা চিহ্ন কোনটা?", ["এটা শক্ত নতুন উপাদান হয় আর আগের অবস্থায় ফেরে না", "ভিজে যায়", "শুধু রং করলে রং বদলায়", "শুধু হালকা হয়"],
        "জমা কংক্রিটে নতুন কেলাস তৈরি হয় - আর কখনো পাউডার আর জলে ফেরে না।"),
    mcq("What is 'erosion'?", ["Wearing away of rock and soil by water, wind or ice", "Rocks growing", "Volcanoes erupting", "Sand dissolving into sugar"], 0,
        "Rivers erode banks over time - a danger to bridge foundations.",
        "'ক্ষয়' (ভূমিক্ষয়) কী?", ["জল, বাতাস বা বরফে পাথর আর মাটি ক্ষয়ে যাওয়া", "পাথর বড় হওয়া", "আগ্নেয়গিরি উদ্গিরণ", "বালি গলে চিনি হওয়া"],
        "সময়ের সঙ্গে নদী পাড় ক্ষয় করে - সেতুর ভিতের জন্য বিপদ।"),
    mcq("What is 'scour' at a bridge?", ["Fast water digging away soil around the piers", "Cleaning the deck", "Painting the rails", "Birds nesting"], 0,
        "Scour can undermine foundations - engineers protect piers with rocks and deep footings.",
        "সেতুতে 'স্কাওয়ার' কী?", ["দ্রুত স্রোত স্তম্ভের চারপাশের মাটি খুঁড়ে নেয়", "ডেক পরিষ্কার", "রেলিং রং", "পাখির বাসা"],
        "স্কাওয়ার ভিত ক্ষয় করতে পারে - প্রকৌশলীরা পাথর আর গভীর পাদভিত্তি দিয়ে স্তম্ভ রক্ষা করেন।"),
    mcq("What is 'weathering'?", ["Rocks breaking down because of rain, heat, cold and plants", "Watching the weather", "Painting a house", "Rocks melting into lava"], 0,
        "Freezing water, acid rain and plant roots slowly break rocks apart.",
        "'আবহবিকার' কী?", ["বৃষ্টি, তাপ, ঠান্ডা আর গাছের কারণে পাথর ভাঙা", "আবহাওয়া দেখা", "বাড়ি রং করা", "পাথর গলে লাভা হওয়া"],
        "জমে যাওয়া জল, অম্লবৃষ্টি আর গাছের শিকড় ধীরে পাথর ভাঙে।"),
    mcq("Why are old stone bridges sometimes damaged by plant roots?", ["Roots grow into cracks and push stones apart", "Roots eat stone", "Plants make stones heavier", "They are not"], 0,
        "Growing roots wedge cracks wider - maintenance crews remove plants from old bridges.",
        "পুরোনো পাথরের সেতু কখনো গাছের শিকড়ে নষ্ট হয় কেন?", ["শিকড় ফাটলে ঢুকে পাথর দুই দিকে ঠেলে", "শিকড় পাথর খায়", "গাছ পাথর ভারী করে", "নষ্ট হয় না"],
        "বাড়ন্ত শিকড় ফাটল চওড়া করে - রক্ষণাবেক্ষণ দল পুরোনো সেতু থেকে গাছ সরায়।"),
    mcq("What is the solid form of carbon dioxide called?", ["Dry ice", "Snow", "Glass", "Chalk"], 0,
        "Dry ice is very cold (-78 °C) and turns straight into gas without melting.",
        "কার্বন ডাই-অক্সাইডের কঠিন রূপকে কী বলে?", ["শুকনো বরফ", "তুষার", "কাচ", "চক"],
        "শুকনো বরফ খুব ঠান্ডা (-78 °C) আর না গলে সরাসরি গ্যাস হয়ে যায়।"),
    mcq("When a solid turns straight into a gas, it is called...", ["Sublimation", "Melting", "Condensation", "Freezing"], 0,
        "Dry ice and mothballs sublime.",
        "কঠিন সরাসরি গ্যাসে বদলালে তাকে বলে...", ["ঊর্ধ্বপাতন", "গলন", "ঘনীভবন", "জমে যাওয়া"],
        "শুকনো বরফ আর ন্যাপথালিন ঊর্ধ্বপাতিত হয়।"),
    mcq("Which has the highest melting point?", ["Iron (about 1538 °C)", "Ice (0 °C)", "Chocolate (about 34 °C)", "Butter (about 35 °C)"], 0,
        "Metals like iron need furnace heat to melt.",
        "কোনটার গলনাঙ্ক সবচেয়ে বেশি?", ["লোহা (প্রায় 1538 °C)", "বরফ (0 °C)", "চকলেট (প্রায় 34 °C)", "মাখন (প্রায় 35 °C)"],
        "লোহার মতো ধাতু গলাতে চুল্লির তাপ লাগে।"),
    mcq("Why are steel beams fire-protected in buildings?", ["Steel gets weaker when very hot", "Steel burns like paper", "Fire makes steel heavier", "They are not"], 0,
        "Steel does not burn, but it loses much of its strength at high temperatures.",
        "ভবনে ইস্পাতের বিমকে আগুন থেকে সুরক্ষা দেওয়া হয় কেন?", ["খুব গরমে ইস্পাত দুর্বল হয়", "ইস্পাত কাগজের মতো পোড়ে", "আগুনে ইস্পাত ভারী হয়", "দেওয়া হয় না"],
        "ইস্পাত পোড়ে না, কিন্তু উচ্চ তাপমাত্রায় শক্তির অনেকটা হারায়।"),
    mcq("What is an 'alloy'?", ["A mixture of a metal with other elements", "A pure gas", "A type of wood", "A rock"], 0,
        "Steel (iron + carbon), brass (copper + zinc) and bronze (copper + tin) are alloys.",
        "'সংকর ধাতু' কী?", ["অন্য মৌলের সঙ্গে ধাতুর মিশ্রণ", "বিশুদ্ধ গ্যাস", "এক রকম কাঠ", "একটা পাথর"],
        "ইস্পাত (লোহা + কার্বন), পিতল (তামা + দস্তা) আর ব্রোঞ্জ (তামা + টিন) সংকর ধাতু।"),
    mcq("Stainless steel does not rust easily because it contains...", ["Chromium", "Sugar", "Salt", "Water"], 0,
        "Chromium forms a thin protective layer on the surface.",
        "মরচে-রোধী ইস্পাতে সহজে মরচে ধরে না কারণ এতে আছে...", ["ক্রোমিয়াম", "চিনি", "নুন", "জল"],
        "ক্রোমিয়াম তলের উপর একটা পাতলা রক্ষাকারী স্তর তৈরি করে।"),
    mcq("Which metal is liquid at room temperature?", ["Mercury", "Iron", "Copper", "Aluminium"], 0,
        "Mercury is the only common metal that is liquid at room temperature - and it is poisonous.",
        "কোন ধাতু ঘরের তাপমাত্রায় তরল?", ["পারদ", "লোহা", "তামা", "অ্যালুমিনিয়াম"],
        "পারদই একমাত্র সাধারণ ধাতু যা ঘরের তাপমাত্রায় তরল - আর বিষাক্ত।"),
    mcq("Why are copper pipes used for water?", ["Copper does not rust and is easy to bend and join", "Copper is magnetic", "Copper is see-through", "Copper dissolves in water"], 0,
        "Copper resists corrosion and can be shaped easily.",
        "জলের পাইপে তামা ব্যবহার হয় কেন?", ["তামায় মরচে ধরে না আর বাঁকানো-জোড়া সহজ", "তামা চৌম্বক", "তামা স্বচ্ছ", "তামা জলে গলে"],
        "তামা ক্ষয় ঠেকায় আর সহজে আকার দেওয়া যায়।"),
    mcq("What happens when you mix water and cement powder?", ["A paste forms that slowly hardens", "Nothing ever", "It catches fire", "It turns into glass immediately"], 0,
        "The paste sets within hours and gains strength over weeks.",
        "জল আর সিমেন্টের গুঁড়ো মেশালে কী হয়?", ["একটা লেই হয়, যা ধীরে শক্ত হয়", "কখনো কিছু হয় না", "আগুন ধরে", "সঙ্গে সঙ্গে কাচ হয়"],
        "লেই কয়েক ঘণ্টায় জমে আর কয়েক সপ্তাহে শক্তি বাড়ায়।"),
    mcq("Why is too much water bad in a concrete mix?", ["It makes the concrete weaker", "It makes it stronger", "It makes it see-through", "It makes it magnetic"], 0,
        "Extra water leaves tiny holes as it dries, so the concrete is weaker - builders measure water carefully.",
        "কংক্রিটের মিশ্রণে বেশি জল খারাপ কেন?", ["কংক্রিট দুর্বল হয়", "আরও শক্ত হয়", "স্বচ্ছ হয়", "চৌম্বক হয়"],
        "বাড়তি জল শুকিয়ে ছোট ছোট ছিদ্র রাখে, তাই কংক্রিট দুর্বল - নির্মাতারা মেপে জল দেন।"),
    mcq("What is a 'mixture'?", ["Two or more substances mixed but not chemically joined", "One pure substance", "A chemical reaction", "A single element"], 0,
        "In a mixture, each part keeps its own properties and can be separated.",
        "'মিশ্রণ' কী?", ["দুই বা বেশি পদার্থ মেশানো কিন্তু রাসায়নিকভাবে যুক্ত নয়", "একটা বিশুদ্ধ পদার্থ", "রাসায়নিক বিক্রিয়া", "একটা মৌল"],
        "মিশ্রণে প্রতিটি অংশ নিজের গুণ রাখে আর আলাদা করা যায়।"),
    mcq("Is air a mixture or a single substance?", ["A mixture of gases", "A single pure gas", "A liquid", "A metal"], 0,
        "Air is mostly nitrogen and oxygen, with a little argon, carbon dioxide and water vapour.",
        "বাতাস কি মিশ্রণ নাকি একক পদার্থ?", ["গ্যাসের মিশ্রণ", "একটা বিশুদ্ধ গ্যাস", "তরল", "ধাতু"],
        "বাতাস মূলত নাইট্রোজেন আর অক্সিজেন, সঙ্গে অল্প আর্গন, কার্বন ডাই-অক্সাইড আর জলীয় বাষ্প।"),
    mcq("How can you grow bigger salt crystals?", ["Let a strong salt solution evaporate slowly", "Freeze salt water quickly", "Boil it dry in seconds", "Add sand"], 0,
        "Slow evaporation gives crystals time to grow large.",
        "কীভাবে বড় নুনের কেলাস তৈরি করা যায়?", ["ঘন নুন-দ্রবণ ধীরে বাষ্পীভূত হতে দাও", "নোনা জল দ্রুত জমাও", "কয়েক সেকেন্ডে ফুটিয়ে শুকাও", "বালি মেশাও"],
        "ধীর বাষ্পীভবন কেলাসকে বড় হওয়ার সময় দেয়।"),
    mcq("Why does a can of fizzy drink spray when shaken and opened?", ["Shaking frees gas bubbles that rush out when the pressure drops", "The drink is angry", "Cans are magnetic", "Shaking adds sugar"], 0,
        "Dissolved carbon dioxide escapes quickly when the can is opened.",
        "ঝাঁকিয়ে খুললে ফেনাওয়ালা পানীয়ের ক্যান ছিটকে ওঠে কেন?", ["ঝাঁকুনিতে গ্যাসের বুদবুদ মুক্ত হয়, চাপ কমলে ছুটে বেরোয়", "পানীয় রেগে যায়", "ক্যান চুম্বক", "ঝাঁকুনিতে চিনি বাড়ে"],
        "ক্যান খুললে গলে থাকা কার্বন ডাই-অক্সাইড দ্রুত বেরিয়ে যায়।"),
    mcq("Which gas do plants take in to make food?", ["Carbon dioxide", "Oxygen", "Helium", "Nitrogen only"], 0,
        "Plants use carbon dioxide, water and light to make sugar, giving out oxygen.",
        "খাবার তৈরিতে গাছ কোন গ্যাস নেয়?", ["কার্বন ডাই-অক্সাইড", "অক্সিজেন", "হিলিয়াম", "শুধু নাইট্রোজেন"],
        "গাছ কার্বন ডাই-অক্সাইড, জল আর আলো দিয়ে চিনি বানায়, অক্সিজেন ছাড়ে।"),
    mcq("Which metal is used to make most soft-drink cans and is easily recycled?", ["Aluminium", "Gold", "Lead", "Mercury"], 0,
        "Aluminium can be recycled again and again, saving lots of energy.",
        "বেশিরভাগ কোমল পানীয়ের ক্যান কোন ধাতুতে তৈরি আর সহজে পুনর্ব্যবহার করা যায়?", ["অ্যালুমিনিয়াম", "সোনা", "সীসা", "পারদ"],
        "অ্যালুমিনিয়াম বারবার পুনর্ব্যবহার করা যায়, অনেক শক্তি বাঁচে।"),
    mcq("What is 'biodegradable'?", ["Able to be broken down naturally by living things", "Made of metal", "Lasts forever", "Magnetic"], 0,
        "Paper and food waste are biodegradable; most plastics are not.",
        "'জৈব-বিয়োজ্য' কী?", ["জীবের দ্বারা প্রাকৃতিকভাবে ভেঙে মিশে যেতে পারে", "ধাতুর তৈরি", "চিরকাল টেকে", "চৌম্বক"],
        "কাগজ আর খাবারের বর্জ্য জৈব-বিয়োজ্য; বেশিরভাগ প্লাস্টিক নয়।"),
    mcq("Why do builders mix lime or cement into weak soil under a road?", ["It binds the soil and makes it stronger", "To make it softer", "To grow grass", "To make it wet"], 0,
        "Soil stabilisation turns weak soil into a firm base for heavy traffic.",
        "নির্মাতারা রাস্তার নিচের দুর্বল মাটিতে চুন বা সিমেন্ট মেশান কেন?", ["মাটি বেঁধে শক্ত করে", "নরম করতে", "ঘাস জন্মাতে", "ভেজা করতে"],
        "মাটি স্থিতিকরণ দুর্বল মাটিকে ভারী যানবাহনের জন্য শক্ত ভিত বানায়।"),
    mcq("Why does a puddle on a road dry faster in summer?", ["Higher temperature speeds evaporation", "Summer water is lighter", "Roads drink water", "It does not"], 0,
        "Warm water molecules escape into the air faster.",
        "গরমকালে রাস্তার ডোবা তাড়াতাড়ি শুকায় কেন?", ["উচ্চ তাপমাত্রা বাষ্পীভবন দ্রুত করে", "গরমের জল হালকা", "রাস্তা জল খায়", "শুকায় না"],
        "গরম জলের অণু তাড়াতাড়ি বাতাসে পালায়।"),
    mcq("What is 'boiling point'?", ["The temperature at which a liquid boils", "The point on a map", "The coldest temperature", "The weight of water"], 0,
        "Water boils at 100 °C at sea level; less on a high mountain.",
        "'স্ফুটনাঙ্ক' কী?", ["যে তাপমাত্রায় তরল ফোটে", "মানচিত্রের একটা বিন্দু", "সবচেয়ে ঠান্ডা তাপমাত্রা", "জলের ওজন"],
        "সমুদ্রপৃষ্ঠে জল 100 °C-এ ফোটে; উঁচু পাহাড়ে কম তাপমাত্রায়।"),
    mcq("What is 'melting point'?", ["The temperature at which a solid melts", "The middle of a bridge", "The weight of ice", "The speed of melting"], 0,
        "Ice melts at 0 °C; iron at about 1538 °C.",
        "'গলনাঙ্ক' কী?", ["যে তাপমাত্রায় কঠিন গলে", "সেতুর মাঝখান", "বরফের ওজন", "গলার গতি"],
        "বরফ 0 °C-এ গলে; লোহা প্রায় 1538 °C-এ।"),
    mcq("Which is a natural material used in construction?", ["Stone", "Plastic", "Nylon", "Polystyrene"], 0,
        "Stone, timber and clay come from nature; plastics are made in factories.",
        "নির্মাণে ব্যবহৃত কোনটা প্রাকৃতিক উপাদান?", ["পাথর", "প্লাস্টিক", "নাইলন", "পলিস্টাইরিন"],
        "পাথর, কাঠ আর কাদামাটি প্রকৃতি থেকে আসে; প্লাস্টিক কারখানায় তৈরি।"),
    mcq("Which is a man-made material?", ["Concrete", "Granite", "Wood", "Wool"], 0,
        "Concrete is made by people from natural ingredients.",
        "কোনটা মানুষের তৈরি উপাদান?", ["কংক্রিট", "গ্রানাইট", "কাঠ", "উল"],
        "কংক্রিট মানুষ প্রাকৃতিক উপকরণ থেকে বানায়।"),
    mcq("Why do roads use small stones mixed with tar (asphalt)?", ["Stones carry the load; tar glues them and keeps water out", "Tar is sweet", "Stones make it soft", "For colour only"], 0,
        "Asphalt is a mixture designed to be strong, flexible and waterproof.",
        "রাস্তায় আলকাতরায় মেশানো ছোট পাথর (অ্যাসফল্ট) ব্যবহার হয় কেন?", ["পাথর ভার বয়; আলকাতরা জোড়ে আর জল আটকায়", "আলকাতরা মিষ্টি", "পাথর নরম করে", "শুধু রঙের জন্য"],
        "অ্যাসফল্ট শক্ত, নমনীয় আর জলরোধী হওয়ার মতো করে বানানো মিশ্রণ।"),
    mcq("What happens to tar (asphalt) on a very hot day?", ["It softens", "It freezes", "It turns to glass", "It evaporates instantly"], 0,
        "Bitumen softens in heat - that is why roads can rut in very hot weather.",
        "খুব গরম দিনে আলকাতরার (অ্যাসফল্ট) কী হয়?", ["নরম হয়", "জমে যায়", "কাচ হয়", "সঙ্গে সঙ্গে উবে যায়"],
        "তাপে বিটুমেন নরম হয় - এজন্যই খুব গরমে রাস্তায় চাকার দাগ বসে যেতে পারে।"),
    mcq("Which material is a good thermal insulator for a house roof?", ["Glass wool or foam", "Thin metal sheet only", "Wet cloth", "Copper"], 0,
        "Insulation traps air and slows heat flow, keeping homes cooler or warmer.",
        "বাড়ির ছাদের জন্য কোন উপাদান ভালো তাপ-অন্তরক?", ["কাচের উল বা ফোম", "শুধু পাতলা ধাতুর পাত", "ভেজা কাপড়", "তামা"],
        "অন্তরণ বাতাস আটকে তাপপ্রবাহ ধীর করে, বাড়ি ঠান্ডা বা গরম রাখে।"),
    mcq("Why do potters glaze pots?", ["To make them waterproof and shiny", "To make them heavier", "To make them magnetic", "To make them soft"], 0,
        "A glaze melts into a glassy coat in the kiln.",
        "কুমোররা হাঁড়িতে চকচকে প্রলেপ (গ্লেজ) দেন কেন?", ["জলরোধী আর চকচকে করতে", "ভারী করতে", "চৌম্বক করতে", "নরম করতে"],
        "গ্লেজ চুল্লিতে গলে কাচের মতো আবরণ হয়।"),
    mcq("Which liquid is thickest (most viscous)?", ["Honey", "Water", "Milk", "Juice"], 0,
        "Viscous liquids flow slowly. Honey is much thicker than water.",
        "কোন তরল সবচেয়ে ঘন (সান্দ্র)?", ["মধু", "জল", "দুধ", "রস"],
        "সান্দ্র তরল ধীরে বয়। মধু জলের চেয়ে অনেক ঘন।"),
    mcq("Why does honey flow faster when warmed?", ["Heat makes it less thick (less viscous)", "Heat makes it heavier", "Warm honey is a gas", "It does not"], 0,
        "Warmer liquids usually flow more easily.",
        "গরম করলে মধু দ্রুত বয় কেন?", ["তাপে কম ঘন (কম সান্দ্র) হয়", "তাপে ভারী হয়", "গরম মধু গ্যাস", "বয় না"],
        "উষ্ণ তরল সাধারণত সহজে বয়।"),
    mcq("A metal spoon in hot tea gets hot; a plastic spoon does not. Metal is a good...", ["Conductor of heat", "Insulator", "Solvent", "Fuel"], 0,
        "Heat travels easily through metals.",
        "গরম চায়ে ধাতুর চামচ গরম হয়; প্লাস্টিকেরটা হয় না। ধাতু একটা ভালো...", ["তাপ পরিবাহী", "অন্তরক", "দ্রাবক", "জ্বালানি"],
        "ধাতুর মধ্য দিয়ে তাপ সহজে চলে।"),
    mcq("Why is sand mixed into mortar and concrete?", ["It fills gaps and adds bulk and strength", "It makes it sweet", "It dissolves the cement", "It is decoration"], 0,
        "Sand is a fine aggregate that makes the mix stronger and cheaper.",
        "মশলা আর কংক্রিটে বালি মেশানো হয় কেন?", ["ফাঁক ভরে আর আয়তন ও শক্তি বাড়ায়", "মিষ্টি করে", "সিমেন্ট গলায়", "সাজসজ্জা"],
        "বালি সূক্ষ্ম পাথরকুচি, যা মিশ্রণকে শক্ত আর সস্তা করে।"),
    mcq("Which of these is a fuel?", ["Coal", "Sand", "Glass", "Salt"], 0,
        "Fuels like coal, wood and petrol release energy when burned.",
        "এগুলোর কোনটা জ্বালানি?", ["কয়লা", "বালি", "কাচ", "নুন"],
        "কয়লা, কাঠ আর পেট্রলের মতো জ্বালানি পোড়ালে শক্তি দেয়।"),
    mcq("What is smoke mostly made of?", ["Tiny bits of unburned material and gases", "Pure water", "Salt", "Steel"], 0,
        "Smoke shows incomplete burning and can harm lungs.",
        "ধোঁয়া মূলত কী দিয়ে তৈরি?", ["না-পোড়া উপাদানের ছোট কণা আর গ্যাস", "বিশুদ্ধ জল", "নুন", "ইস্পাত"],
        "ধোঁয়া অসম্পূর্ণ দহন দেখায় আর ফুসফুসের ক্ষতি করতে পারে।"),
    mcq("Why are steel bridges painted in several layers?", ["Each layer adds protection against water and air", "To make them heavier", "For a rainbow look only", "Paint is a fuel"], 0,
        "Primer, middle and top coats together keep rust away for years.",
        "ইস্পাতের সেতু কয়েক স্তর রং করা হয় কেন?", ["প্রতিটি স্তর জল আর বাতাস থেকে বাড়তি সুরক্ষা দেয়", "ভারী করতে", "শুধু রংধনুর মতো দেখাতে", "রং জ্বালানি"],
        "প্রাইমার, মাঝের আর উপরের প্রলেপ মিলে বছরের পর বছর মরচে দূরে রাখে।"),
    mcq("What is 'quarrying'?", ["Digging stone out of the ground", "Melting metal", "Growing trees", "Making glass"], 0,
        "Quarries supply stone, sand and gravel for buildings, roads and bridges.",
        "'খাদান' কী?", ["মাটি থেকে পাথর খুঁড়ে তোলা", "ধাতু গলানো", "গাছ লাগানো", "কাচ বানানো"],
        "খাদান ভবন, রাস্তা আর সেতুর জন্য পাথর, বালি আর পাথরকুচি জোগায়।"),
    mcq("Which word describes something that lets water pass through?", ["Permeable", "Waterproof", "Opaque", "Rigid"], 0,
        "Sandy soil and sponges are permeable; plastic sheets are not.",
        "যার মধ্য দিয়ে জল যেতে পারে তাকে কোন শব্দে বলে?", ["ভেদ্য", "জলরোধী", "অস্বচ্ছ", "অনমনীয়"],
        "বেলে মাটি আর স্পঞ্জ ভেদ্য; প্লাস্টিকের পাত নয়।"),
    mcq("Why do bridge decks have drains?", ["To remove rain water so it does not soak in and cause damage", "To catch fish", "To store water", "For decoration"], 0,
        "Standing water speeds corrosion and freezing damage; drains carry it away.",
        "সেতুর ডেকে জলনিকাশি থাকে কেন?", ["বৃষ্টির জল সরাতে, যাতে ভিজে ক্ষতি না করে", "মাছ ধরতে", "জল জমাতে", "সাজসজ্জার জন্য"],
        "জমা জল ক্ষয় আর জমে-যাওয়ার ক্ষতি দ্রুত করে; নিকাশি তা সরিয়ে দেয়।"),
    mcq("What is 'limescale'?", ["Chalky minerals left by hard water", "A type of fish", "A metal", "Rust"], 0,
        "When hard water evaporates or boils, dissolved minerals are left as a crust.",
        "'চুনের আস্তর' (লাইমস্কেল) কী?", ["খর জলের রেখে যাওয়া খড়িমাটির মতো খনিজ", "এক রকম মাছ", "একটা ধাতু", "মরচে"],
        "খর জল উবে গেলে বা ফুটলে গলে থাকা খনিজ আস্তর হয়ে থাকে।"),
    mcq("Which rock is soft enough to write with?", ["Chalk", "Granite", "Marble", "Basalt"], 0,
        "Chalk is a soft form of limestone.",
        "কোন পাথর দিয়ে লেখা যায় এমন নরম?", ["চক", "গ্রানাইট", "মার্বেল", "ব্যাসল্ট"],
        "চক চুনাপাথরের একটা নরম রূপ।"),
    mcq("Pumice is a volcanic rock that can float. Why?", ["It is full of tiny gas bubbles", "It is made of wood", "It is magnetic", "It is hot"], 0,
        "Trapped gas bubbles make pumice lighter than water.",
        "পিউমিস আগ্নেয় শিলা, অথচ ভাসে। কেন?", ["ছোট ছোট গ্যাসের বুদবুদে ভরা", "কাঠের তৈরি", "চৌম্বক", "গরম"],
        "আটকে থাকা গ্যাসের বুদবুদ পিউমিসকে জলের চেয়ে হালকা করে।"),
    mcq("Why is lightweight concrete sometimes used in long bridge decks?", ["Less weight means less load on the supports", "It is shinier", "It is magnetic", "It is always cheaper"], 0,
        "A lighter deck reduces the bridge's own dead load, so beams and piers can be smaller.",
        "লম্বা সেতুর ডেকে কখনো হালকা কংক্রিট ব্যবহার হয় কেন?", ["কম ওজন মানে সাপোর্টে কম ভার", "এটা বেশি চকচকে", "চৌম্বক", "সবসময় সস্তা"],
        "হালকা ডেক সেতুর নিজের মৃত ভার কমায়, তাই বিম আর স্তম্ভ ছোট হতে পারে।"),
    mcq("What is 'corrosion'?", ["Slow damage of metals by chemical reactions with their surroundings", "Melting", "Painting", "Polishing"], 0,
        "Rusting is the corrosion of iron and steel.",
        "'ক্ষয়' (করোশন) কী?", ["চারপাশের সঙ্গে রাসায়নিক বিক্রিয়ায় ধাতুর ধীর ক্ষতি", "গলন", "রং করা", "পালিশ করা"],
        "মরচে হলো লোহা আর ইস্পাতের ক্ষয়।"),
    mcq("Which is the best way to keep a bike chain from rusting?", ["Keep it oiled and dry", "Leave it in the rain", "Wash it with salt water", "Paint it with jam"], 0,
        "Oil keeps water and air off the metal.",
        "সাইকেলের চেনে মরচে ঠেকানোর সেরা উপায় কোনটা?", ["তেল দিয়ে শুকনো রাখা", "বৃষ্টিতে ফেলে রাখা", "নোনা জলে ধোয়া", "জ্যাম দিয়ে রং করা"],
        "তেল ধাতু থেকে জল আর বাতাস দূরে রাখে।"),
    mcq("Why do cold drinks taste flat faster when warm?", ["Gases dissolve less in warm liquids", "Warm drinks have more sugar", "Cold drinks have no gas", "It is the cup's fault"], 0,
        "Warmth lets dissolved carbon dioxide escape more quickly.",
        "গরম হলে ঠান্ডা পানীয় তাড়াতাড়ি পানসে লাগে কেন?", ["উষ্ণ তরলে গ্যাস কম দ্রবীভূত থাকে", "গরম পানীয়তে বেশি চিনি", "ঠান্ডা পানীয়তে গ্যাস নেই", "কাপের দোষ"],
        "উষ্ণতায় গলে থাকা কার্বন ডাই-অক্সাইড দ্রুত বেরিয়ে যায়।"),
    mcq("A recycled steel beam is...", ["Just as useful as new steel", "Always weaker", "Made of plastic", "Unsafe for bridges"], 0,
        "Steel can be melted and reused many times without losing quality.",
        "পুনর্ব্যবহৃত ইস্পাতের বিম...", ["নতুন ইস্পাতের মতোই কাজের", "সবসময় দুর্বল", "প্লাস্টিকের তৈরি", "সেতুর জন্য অনিরাপদ"],
        "ইস্পাত মান না হারিয়ে বহুবার গলিয়ে আবার ব্যবহার করা যায়।"),
    mcq("Which rock is made from layers of tiny sea shells?", ["Limestone", "Granite", "Basalt", "Obsidian"], 0,
        "Limestone forms from the shells and skeletons of sea creatures pressed together.",
        "কোন পাথর ছোট ছোট সামুদ্রিক খোলসের স্তর থেকে তৈরি?", ["চুনাপাথর", "গ্রানাইট", "ব্যাসল্ট", "অবসিডিয়ান"],
        "চুনাপাথর সামুদ্রিক প্রাণীর খোলস আর কঙ্কাল চাপে জমে তৈরি হয়।"),
    mcq("Why do builders check that sand for concrete is clean and not salty?", ["Dirt weakens the mix and salt rusts the steel", "Clean sand is heavier", "Salty sand is sweeter", "It does not matter"], 0,
        "Good concrete needs clean ingredients; sea sand must be washed before use.",
        "নির্মাতারা কংক্রিটের বালি পরিষ্কার আর নোনা নয় কিনা দেখেন কেন?", ["ময়লা মিশ্রণ দুর্বল করে আর নুন ইস্পাতে মরচে ধরায়", "পরিষ্কার বালি বেশি ভারী", "নোনা বালি বেশি মিষ্টি", "কিছু যায় আসে না"],
        "ভালো কংক্রিটে পরিষ্কার উপকরণ লাগে; সমুদ্রের বালি ব্যবহারের আগে ধুতে হয়।"),
    mcq("What do we call rock that is hot and liquid underground?", ["Magma", "Lava ice", "Sandstone", "Chalk"], 0,
        "Underground it is magma; when it erupts onto the surface it is called lava.",
        "মাটির নিচের গরম তরল পাথরকে কী বলি?", ["ম্যাগমা", "লাভা-বরফ", "বেলেপাথর", "চক"],
        "মাটির নিচে এটা ম্যাগমা; উপরে বেরিয়ে এলে তাকে বলে লাভা।"),
    mcq("Why does a wet wooden plank feel heavier than a dry one?", ["Wood soaks up water into its tiny pores", "Water makes wood denser metal", "Wet wood shrinks", "It does not"], 0,
        "Wood is full of tiny tubes that fill with water - and wet wood is also weaker.",
        "ভেজা কাঠের তক্তা শুকনোটার চেয়ে ভারী লাগে কেন?", ["কাঠ তার ছোট ছোট ছিদ্রে জল শুষে নেয়", "জলে কাঠ ঘন ধাতু হয়", "ভেজা কাঠ ছোট হয়", "ভারী লাগে না"],
        "কাঠ ছোট ছোট নলে ভরা, যা জলে ভরে যায় - আর ভেজা কাঠ দুর্বলও।"),
    mcq("Which of these is reversible: making ice cubes or baking bricks?", ["Making ice cubes", "Baking bricks", "Both", "Neither"], 0,
        "Ice melts back into water; a fired brick can never turn back into soft clay.",
        "কোনটা ফেরানো যায়: বরফের টুকরো বানানো নাকি ইট পোড়ানো?", ["বরফের টুকরো বানানো", "ইট পোড়ানো", "দুটোই", "কোনোটাই না"],
        "বরফ গলে আবার জল হয়; পোড়া ইট কখনো আর নরম কাদামাটিতে ফেরে না।"),
    mcq("Why are some roads made of concrete instead of asphalt?", ["Concrete lasts longer under very heavy traffic", "Concrete is always cheaper", "Asphalt is illegal", "Concrete is softer"], 0,
        "Concrete costs more at first but carries heavy trucks for longer with fewer repairs.",
        "কিছু রাস্তা অ্যাসফল্টের বদলে কংক্রিটে বানানো হয় কেন?", ["খুব ভারী যানবাহনে কংক্রিট বেশিদিন টেকে", "কংক্রিট সবসময় সস্তা", "অ্যাসফল্ট বেআইনি", "কংক্রিট বেশি নরম"],
        "কংক্রিটের শুরুর খরচ বেশি, কিন্তু কম মেরামতে বেশিদিন ভারী ট্রাক বয়।"),
)
