"""Class 3 - Biology: plant parts and what they need, skeletons and muscles, nutrition,
teeth, animal groups, adaptation, and nature's engineering."""
from . import mcq

ITEMS = (
    mcq("What are the four main parts of a flowering plant?", ["Roots, stem, leaves and flowers", "Wheels, doors, roof and windows", "Head, arms, legs and tail", "Bark only"], 0,
        "Each part has a job: anchor and drink, support and carry, make food, make seeds.",
        "সপুষ্পক উদ্ভিদের চারটি প্রধান অংশ কী?", ["শিকড়, কাণ্ড, পাতা আর ফুল", "চাকা, দরজা, ছাদ আর জানালা", "মাথা, হাত, পা আর লেজ", "শুধু বাকল"],
        "প্রতিটি অংশের কাজ আছে: আঁকড়ে ধরা আর জল টানা, ধরে রাখা আর বহন, খাবার তৈরি, বীজ তৈরি।"),
    mcq("What does the stem do?", ["Holds the plant up and carries water and food", "Makes seeds", "Catches sunlight only", "Smells nice"], 0,
        "The stem is the plant's pillar and pipeline.",
        "কাণ্ড কী করে?", ["গাছকে খাড়া রাখে আর জল ও খাবার বয়", "বীজ তৈরি করে", "শুধু সূর্যালোক ধরে", "সুগন্ধ ছড়ায়"],
        "কাণ্ড গাছের খুঁটি আর পাইপলাইন।"),
    mcq("What do plants need to stay healthy?", ["Light, water, air, warmth and nutrients from the soil", "Only darkness", "Only salt", "Only music"], 0,
        "Missing any of these makes a plant weak, pale or wilted.",
        "সুস্থ থাকতে গাছের কী লাগে?", ["আলো, জল, বাতাস, উষ্ণতা আর মাটির পুষ্টি", "শুধু অন্ধকার", "শুধু নুন", "শুধু গান"],
        "এর যেকোনোটা না পেলে গাছ দুর্বল, ফ্যাকাশে বা নেতিয়ে পড়ে।"),
    mcq("What is pollination?", ["Moving pollen from one flower to another", "Watering a plant", "Cutting a stem", "Picking fruit"], 0,
        "Insects, birds and wind carry pollen so flowers can make seeds.",
        "পরাগায়ন কী?", ["এক ফুল থেকে আরেক ফুলে পরাগরেণু নেওয়া", "গাছে জল দেওয়া", "কাণ্ড কাটা", "ফল পাড়া"],
        "পোকা, পাখি আর বাতাস পরাগরেণু বয়, তাই ফুল বীজ বানাতে পারে।"),
    mcq("After a flower is pollinated, what grows?", ["Seeds, often inside a fruit", "More roots only", "A new stem from the petals", "Nothing"], 0,
        "The fruit protects the seeds and helps spread them.",
        "ফুলের পরাগায়নের পর কী বাড়ে?", ["বীজ, প্রায়ই ফলের ভেতরে", "শুধু আরও শিকড়", "পাপড়ি থেকে নতুন কাণ্ড", "কিছুই না"],
        "ফল বীজকে রক্ষা করে আর ছড়াতে সাহায্য করে।"),
    mcq("How do animals help spread seeds?", ["They eat fruit and drop seeds elsewhere, or carry them on fur", "They plant them with spades", "They never do", "They eat all seeds"], 0,
        "Birds, monkeys and even ants are seed carriers.",
        "প্রাণী কীভাবে বীজ ছড়াতে সাহায্য করে?", ["ফল খেয়ে অন্য জায়গায় বীজ ফেলে, বা লোমে বয়ে নেয়", "কোদাল দিয়ে লাগায়", "কখনো করে না", "সব বীজ খেয়ে ফেলে"],
        "পাখি, বানর, এমনকি পিঁপড়েও বীজ বয়ে বেড়ায়।"),
    mcq("What do we call an animal skeleton inside the body?", ["Endoskeleton", "Exoskeleton", "Shell", "Fur"], 0,
        "Humans, dogs and fish have endoskeletons; insects have exoskeletons.",
        "শরীরের ভেতরের কঙ্কালকে কী বলি?", ["অন্তঃকঙ্কাল", "বহিঃকঙ্কাল", "খোলস", "লোম"],
        "মানুষ, কুকুর আর মাছের অন্তঃকঙ্কাল; পোকার বহিঃকঙ্কাল।"),
    mcq("Which animals have no skeleton at all?", ["Worms and jellyfish", "Dogs", "Birds", "Fish"], 0,
        "Their bodies are supported by fluid inside or by water around them.",
        "কোন প্রাণীর একদম কঙ্কাল নেই?", ["কেঁচো আর জেলিফিশ", "কুকুর", "পাখি", "মাছ"],
        "তাদের শরীর ভেতরের তরল বা চারপাশের জলে ভর দিয়ে থাকে।"),
    mcq("What are the three jobs of the skeleton?", ["Support, protection and movement", "Eating, sleeping and singing", "Seeing, hearing and smelling", "Breathing only"], 0,
        "Bones hold you up, guard organs and give muscles something to pull on.",
        "কঙ্কালের তিনটি কাজ কী?", ["ভর দেওয়া, রক্ষা আর নড়াচড়া", "খাওয়া, ঘুম আর গান", "দেখা, শোনা আর ঘ্রাণ", "শুধু শ্বাস"],
        "হাড় তোমাকে খাড়া রাখে, অঙ্গ রক্ষা করে আর পেশিকে টানার জায়গা দেয়।"),
    mcq("Muscles work in pairs. When your biceps contracts, what happens to your arm?", ["It bends", "It straightens", "It falls off", "Nothing"], 0,
        "Biceps pulls to bend; triceps pulls to straighten. Muscles can only pull, never push.",
        "পেশি জোড়ায় কাজ করে। বাইসেপস সংকুচিত হলে হাতের কী হয়?", ["ভাঁজ হয়", "সোজা হয়", "খসে পড়ে", "কিছুই না"],
        "বাইসেপস টেনে ভাঁজ করে; ট্রাইসেপস টেনে সোজা করে। পেশি শুধু টানতে পারে, ঠেলতে নয়।"),
    mcq("Why are pairs of muscles like the cables on a bridge?", ["Both can only pull (work in tension)", "Both are made of steel", "Both can push hard", "They are not alike"], 0,
        "Muscles and cables pull. Bones and towers are the parts that get pushed.",
        "জোড়া পেশি সেতুর তারের মতো কেন?", ["দুটোই শুধু টানতে পারে (টানে কাজ করে)", "দুটোই ইস্পাতের", "দুটোই জোরে ঠেলতে পারে", "একরকম নয়"],
        "পেশি আর তার টানে। হাড় আর টাওয়ার ঠেলা খায়।"),
    mcq("Which bones protect your brain?", ["Skull", "Ribs", "Pelvis", "Femur"], 0,
        "The skull is a strong, curved bony case - curves are strong, like an arch.",
        "কোন হাড় তোমার মস্তিষ্ক রক্ষা করে?", ["খুলি", "পাঁজর", "শ্রোণি", "ফিমার"],
        "খুলি একটা শক্ত, বাঁকা হাড়ের খোল - বাঁক শক্ত, খিলানের মতো।"),
    mcq("Why are long bones like the femur hollow tubes rather than solid?", ["A tube is strong but light", "To store sweets", "Hollow bones are softer", "They are solid"], 0,
        "A hollow tube resists bending almost as well as a solid rod but weighs much less - engineers use tubes too.",
        "ফিমারের মতো লম্বা হাড় নিরেট না হয়ে ফাঁপা নল কেন?", ["নল শক্ত কিন্তু হালকা", "মিষ্টি রাখতে", "ফাঁপা হাড় নরম", "এগুলো নিরেট"],
        "ফাঁপা নল নিরেট দণ্ডের প্রায় সমান বাঁকা ঠেকায় কিন্তু অনেক হালকা - প্রকৌশলীরাও নল ব্যবহার করেন।"),
    mcq("What are the main food groups?", ["Carbohydrates, proteins, fats, vitamins, minerals and fibre", "Sweets, crisps and fizzy drinks", "Only fruit", "Only meat"], 0,
        "A balanced diet includes a little of each.",
        "প্রধান খাদ্যগোষ্ঠী কী কী?", ["শর্করা, প্রোটিন, চর্বি, ভিটামিন, খনিজ আর আঁশ", "মিষ্টি, চিপস আর ফেনাওয়ালা পানীয়", "শুধু ফল", "শুধু মাংস"],
        "সুষম খাদ্যে প্রতিটির কিছুটা থাকে।"),
    mcq("What does fibre (in vegetables and whole grains) do?", ["Helps food move through your gut", "Makes bones glow", "Gives instant energy only", "Nothing"], 0,
        "Fibre keeps your digestion healthy.",
        "আঁশ (সবজি আর গোটা শস্যে) কী করে?", ["খাবারকে পেটের ভেতর দিয়ে চলতে সাহায্য করে", "হাড় উজ্জ্বল করে", "শুধু সঙ্গে সঙ্গে শক্তি দেয়", "কিছুই না"],
        "আঁশ হজম সুস্থ রাখে।"),
    mcq("What are fats needed for?", ["Storing energy and keeping warm", "Making bones only", "Seeing in the dark", "Nothing - avoid them all"], 0,
        "Some fat is healthy; too much is not.",
        "চর্বি কীসের জন্য দরকার?", ["শক্তি জমাতে আর গরম থাকতে", "শুধু হাড় বানাতে", "অন্ধকারে দেখতে", "কিছুর জন্য না - সব এড়াও"],
        "কিছুটা চর্বি স্বাস্থ্যকর; বেশি নয়।"),
    mcq("Which vitamin does sunlight help your skin make?", ["Vitamin D", "Vitamin C", "Vitamin A", "Vitamin K"], 0,
        "Vitamin D helps your body use calcium to build strong bones.",
        "সূর্যালোক ত্বককে কোন ভিটামিন তৈরিতে সাহায্য করে?", ["ভিটামিন D", "ভিটামিন C", "ভিটামিন A", "ভিটামিন K"],
        "ভিটামিন D শরীরকে মজবুত হাড় গড়তে ক্যালসিয়াম ব্যবহারে সাহায্য করে।"),
    mcq("Oranges and lemons are rich in which vitamin?", ["Vitamin C", "Vitamin D", "Vitamin B12", "Vitamin K"], 0,
        "Vitamin C helps heal cuts and keeps gums healthy.",
        "কমলা আর লেবুতে কোন ভিটামিন বেশি?", ["ভিটামিন C", "ভিটামিন D", "ভিটামিন B12", "ভিটামিন K"],
        "ভিটামিন C ক্ষত সারাতে আর মাড়ি সুস্থ রাখতে সাহায্য করে।"),
    mcq("What are the front cutting teeth called?", ["Incisors", "Molars", "Canines", "Wisdom teeth"], 0,
        "Incisors cut, canines tear, molars grind.",
        "সামনের কাটার দাঁতকে কী বলে?", ["কর্তন দাঁত", "পেষণ দাঁত", "ছেদন দাঁত (শ্বদন্ত)", "আক্কেল দাঁত"],
        "কর্তন দাঁত কাটে, শ্বদন্ত ছেঁড়ে, পেষণ দাঁত পেষে।"),
    mcq("Which teeth grind food at the back of your mouth?", ["Molars", "Incisors", "Canines", "Milk teeth only"], 0,
        "Molars have wide bumpy tops for crushing food.",
        "মুখের পেছনে কোন দাঁত খাবার পেষে?", ["পেষণ দাঁত", "কর্তন দাঁত", "শ্বদন্ত", "শুধু দুধদাঁত"],
        "পেষণ দাঁতের চওড়া এবড়োখেবড়ো মাথা খাবার গুঁড়ো করে।"),
    mcq("Why do meat-eating animals like lions have long sharp canines?", ["To grip and tear meat", "To eat grass", "To look friendly", "To drink water"], 0,
        "Teeth match the diet: herbivores have flat grinding teeth.",
        "সিংহের মতো মাংসাশীর লম্বা ধারালো শ্বদন্ত কেন?", ["মাংস আঁকড়ে ধরে ছিঁড়তে", "ঘাস খেতে", "বন্ধুসুলভ দেখাতে", "জল খেতে"],
        "দাঁত খাবারের সঙ্গে মেলে: তৃণভোজীর চ্যাপ্টা পেষণ দাঁত।"),
    mcq("What causes tooth decay?", ["Bacteria turning sugar into acid that attacks enamel", "Drinking water", "Eating vegetables", "Sleeping"], 0,
        "Brushing twice a day and less sugar protect your teeth.",
        "দাঁত ক্ষয়ের কারণ কী?", ["জীবাণু চিনিকে অম্লে বদলায়, যা এনামেল আক্রমণ করে", "জল খাওয়া", "সবজি খাওয়া", "ঘুমানো"],
        "দিনে দুবার দাঁত মাজা আর কম চিনি দাঁত রক্ষা করে।"),
    mcq("What do we call animals with a backbone?", ["Vertebrates", "Invertebrates", "Plants", "Fungi"], 0,
        "Fish, amphibians, reptiles, birds and mammals are all vertebrates.",
        "মেরুদণ্ডওয়ালা প্রাণীদের কী বলি?", ["মেরুদণ্ডী", "অমেরুদণ্ডী", "উদ্ভিদ", "ছত্রাক"],
        "মাছ, উভচর, সরীসৃপ, পাখি আর স্তন্যপায়ী সবাই মেরুদণ্ডী।"),
    mcq("Which group has dry scaly skin and lays eggs on land?", ["Reptiles", "Amphibians", "Mammals", "Fish"], 0,
        "Snakes, lizards, turtles and crocodiles are reptiles.",
        "কোন গোষ্ঠীর শুকনো আঁশওয়ালা চামড়া আর ডাঙায় ডিম পাড়ে?", ["সরীসৃপ", "উভচর", "স্তন্যপায়ী", "মাছ"],
        "সাপ, টিকটিকি, কচ্ছপ আর কুমির সরীসৃপ।"),
    mcq("What is an adaptation?", ["A feature that helps a living thing survive where it lives", "A kind of food", "A house", "A sickness"], 0,
        "Thick fur in the cold and long roots in the desert are adaptations.",
        "অভিযোজন কী?", ["যে বৈশিষ্ট্য জীবকে তার বাসস্থানে টিকে থাকতে সাহায্য করে", "এক রকম খাবার", "একটা বাড়ি", "একটা অসুখ"],
        "ঠান্ডায় ঘন লোম আর মরুভূমিতে লম্বা শিকড় অভিযোজন।"),
    mcq("Why do desert plants often have very long roots?", ["To reach water deep underground", "To hold rocks", "To catch insects", "For decoration"], 0,
        "Some desert roots go down tens of metres to find water.",
        "মরুভূমির গাছের প্রায়ই খুব লম্বা শিকড় কেন?", ["মাটির গভীরের জল পেতে", "পাথর ধরতে", "পোকা ধরতে", "সাজসজ্জার জন্য"],
        "কিছু মরু-শিকড় জল খুঁজতে দশ দশ মিটার নিচে যায়।"),
    mcq("Why do Arctic foxes have small ears?", ["To lose less heat in the cold", "To hear better", "To look cute only", "To swim"], 0,
        "Big ears lose heat; desert foxes have big ears to cool down.",
        "সুমেরুর শিয়ালের কান ছোট কেন?", ["ঠান্ডায় কম তাপ হারাতে", "ভালো শুনতে", "শুধু মিষ্টি দেখাতে", "সাঁতার কাটতে"],
        "বড় কানে তাপ বেরোয়; মরুভূমির শিয়ালের ঠান্ডা হতে বড় কান।"),
    mcq("A duck's feathers are oily. Why?", ["To keep water out and stay warm and floaty", "To smell nice", "To be heavier", "For no reason"], 0,
        "Oil makes feathers waterproof.",
        "হাঁসের পালক তৈলাক্ত কেন?", ["জল আটকে গরম আর ভাসমান থাকতে", "সুগন্ধ ছড়াতে", "ভারী হতে", "কোনো কারণ নেই"],
        "তেল পালককে জলরোধী করে।"),
    mcq("How is a bird's nest like a good building?", ["It is woven for strength and lined for warmth", "It is made of steel", "It floats", "It has wheels"], 0,
        "Birds interlock twigs - like a woven mesh - so the nest holds its shape.",
        "পাখির বাসা একটা ভালো ভবনের মতো কীভাবে?", ["শক্তির জন্য বোনা আর উষ্ণতার জন্য আস্তরণ দেওয়া", "ইস্পাতের তৈরি", "ভাসে", "চাকা আছে"],
        "পাখি ডালপালা জড়িয়ে বোনে - বোনা জালের মতো - তাই বাসা আকার রাখে।"),
    mcq("Termite mounds stay cool inside the hot desert. What can engineers learn?", ["Clever air channels can cool buildings without machines", "Termites use air conditioners", "Mud is always cold", "Nothing"], 0,
        "Some real buildings copy termite mound ventilation to save energy.",
        "গরম মরুভূমিতেও উইয়ের ঢিবির ভেতর ঠান্ডা থাকে। প্রকৌশলীরা কী শিখতে পারেন?", ["চতুর বায়ুপথ যন্ত্র ছাড়াই ভবন ঠান্ডা রাখতে পারে", "উইপোকা এসি ব্যবহার করে", "কাদা সবসময় ঠান্ডা", "কিছুই না"],
        "কিছু আসল ভবন শক্তি বাঁচাতে উইয়ের ঢিবির বায়ু-চলাচল নকল করে।"),
    mcq("Why are honeycomb cells hexagons?", ["They fit together with no gaps and use the least wax", "Bees cannot count", "Circles are too strong", "For colour"], 0,
        "Hexagons tile perfectly and are strong - engineers use honeycomb panels in planes and bridges.",
        "মৌচাকের ঘর ষড়ভুজ কেন?", ["ফাঁক ছাড়া জোড়া লাগে আর সবচেয়ে কম মোম লাগে", "মৌমাছি গুনতে পারে না", "বৃত্ত খুব শক্ত", "রঙের জন্য"],
        "ষড়ভুজ নিখুঁতভাবে জোড়ে আর শক্ত - প্রকৌশলীরা উড়োজাহাজ আর সেতুতে মৌচাক-প্যানেল ব্যবহার করেন।"),
    mcq("What is biomimicry?", ["Copying nature's designs to solve human problems", "Painting animals", "Feeding pets", "A type of fossil"], 0,
        "Velcro copied burrs; bullet trains copied a kingfisher's beak.",
        "জৈব-অনুকরণ কী?", ["মানুষের সমস্যা মেটাতে প্রকৃতির নকশা নকল করা", "প্রাণী রং করা", "পোষ্যকে খাওয়ানো", "এক রকম জীবাশ্ম"],
        "ভেলক্রো চোরকাঁটা নকল করেছে; বুলেট ট্রেন মাছরাঙার ঠোঁট নকল করেছে।"),
    mcq("Why did engineers copy a kingfisher's beak for a high-speed train's nose?", ["It cuts through air smoothly, reducing noise and drag", "Kingfishers are fast swimmers only", "For colour", "To catch fish"], 0,
        "The pointed shape lets the train leave tunnels quietly and use less power.",
        "দ্রুতগতির ট্রেনের নাকের জন্য প্রকৌশলীরা মাছরাঙার ঠোঁট নকল করলেন কেন?", ["মসৃণভাবে বাতাস কাটে, শব্দ আর বাধা কমায়", "মাছরাঙা শুধু দ্রুত সাঁতারু", "রঙের জন্য", "মাছ ধরতে"],
        "সূচালো আকার ট্রেনকে নিঃশব্দে সুড়ঙ্গ থেকে বেরোতে আর কম শক্তি খরচ করতে দেয়।"),
    mcq("What is a 'producer' in a food chain?", ["A green plant that makes its own food", "An animal that hunts", "A decomposer", "A rock"], 0,
        "Producers capture the Sun's energy that the whole chain depends on.",
        "খাদ্যশৃঙ্খলে 'উৎপাদক' কী?", ["নিজের খাবার বানানো সবুজ গাছ", "শিকারি প্রাণী", "বিয়োজক", "একটা পাথর"],
        "উৎপাদক সূর্যের শক্তি ধরে, যার উপর পুরো শৃঙ্খল নির্ভর করে।"),
    mcq("What is a 'consumer'?", ["An animal that eats other living things", "A plant", "Sunlight", "Water"], 0,
        "Herbivores, carnivores and omnivores are all consumers.",
        "'খাদক' কী?", ["যে প্রাণী অন্য জীব খায়", "একটা গাছ", "সূর্যালোক", "জল"],
        "তৃণভোজী, মাংসাশী আর সর্বভুক সবাই খাদক।"),
    mcq("If all the frogs in a pond disappeared, what might happen to the number of flies?", ["It might increase", "It might decrease", "It stays the same for sure", "Flies vanish too"], 0,
        "Fewer predators means more prey survive - food chains are linked.",
        "একটা পুকুরের সব ব্যাঙ উধাও হলে মাছির সংখ্যার কী হতে পারে?", ["বাড়তে পারে", "কমতে পারে", "নিশ্চিত একই থাকে", "মাছিও উধাও হয়"],
        "শিকারি কমলে বেশি শিকার বাঁচে - খাদ্যশৃঙ্খল জোড়া।"),
    mcq("Why do we have hair in our noses?", ["To trap dust and germs", "To smell colours", "To look funny", "To keep warm only"], 0,
        "Nose hairs and mucus filter the air before it reaches your lungs.",
        "নাকে লোম থাকে কেন?", ["ধুলো আর জীবাণু আটকাতে", "রঙের গন্ধ নিতে", "মজার দেখাতে", "শুধু গরম থাকতে"],
        "নাকের লোম আর শ্লেষ্মা ফুসফুসে পৌঁছানোর আগে বাতাস ছাঁকে।"),
    mcq("What happens when you breathe in?", ["Your chest gets bigger and air fills your lungs", "Your lungs empty", "Your heart stops", "Your bones grow"], 0,
        "Muscles under the lungs (the diaphragm) pull down to draw air in.",
        "শ্বাস নিলে কী হয়?", ["বুক বড় হয় আর ফুসফুস বাতাসে ভরে", "ফুসফুস খালি হয়", "হৃৎপিণ্ড থামে", "হাড় বাড়ে"],
        "ফুসফুসের নিচের পেশি (মধ্যচ্ছদা) নিচে টেনে বাতাস টানে।"),
    mcq("What is your pulse?", ["The beat of blood pushed by your heart, felt at your wrist or neck", "The sound of your stomach", "Your breathing rate", "Your temperature"], 0,
        "Count beats for one minute to find your heart rate.",
        "নাড়ি (পালস) কী?", ["হৃৎপিণ্ডের ঠেলা রক্তের স্পন্দন, কবজি বা ঘাড়ে টের পাওয়া যায়", "পেটের শব্দ", "শ্বাসের হার", "তাপমাত্রা"],
        "এক মিনিট ধরে স্পন্দন গুনলে হৃৎস্পন্দনের হার পাবে।"),
    mcq("What happens to your pulse after running?", ["It gets faster", "It stops", "It gets slower", "It disappears"], 0,
        "Muscles need more oxygen, so the heart beats faster.",
        "দৌড়ানোর পর নাড়ির কী হয়?", ["দ্রুত হয়", "থেমে যায়", "ধীর হয়", "উধাও হয়"],
        "পেশির বেশি অক্সিজেন লাগে, তাই হৃৎপিণ্ড দ্রুত স্পন্দিত হয়।"),
    mcq("Which organ cleans your blood and makes urine?", ["Kidneys", "Lungs", "Heart", "Skin"], 0,
        "Two kidneys filter waste and extra water out of the blood.",
        "কোন অঙ্গ রক্ত পরিষ্কার করে মূত্র তৈরি করে?", ["বৃক্ক (কিডনি)", "ফুসফুস", "হৃৎপিণ্ড", "ত্বক"],
        "দুটি বৃক্ক রক্ত থেকে বর্জ্য আর বাড়তি জল ছেঁকে বের করে।"),
    mcq("Where is most food digested and absorbed into the blood?", ["The small intestine", "The mouth", "The lungs", "The bones"], 0,
        "The small intestine is long and lined with tiny finger-like villi that absorb nutrients.",
        "বেশিরভাগ খাবার কোথায় হজম হয়ে রক্তে শোষিত হয়?", ["ক্ষুদ্রান্ত্রে", "মুখে", "ফুসফুসে", "হাড়ে"],
        "ক্ষুদ্রান্ত্র লম্বা আর ছোট আঙুলের মতো ভিলাইয়ে ঢাকা, যা পুষ্টি শোষে।"),
    mcq("What do germs called bacteria need to grow?", ["Warmth, food and moisture", "Ice", "Salt only", "Darkness only"], 0,
        "That is why food is kept cold and dry, and kitchens are kept clean.",
        "ব্যাকটেরিয়া নামের জীবাণুর বাড়তে কী লাগে?", ["উষ্ণতা, খাবার আর আর্দ্রতা", "বরফ", "শুধু নুন", "শুধু অন্ধকার"],
        "এজন্যই খাবার ঠান্ডা আর শুকনো রাখা হয়, রান্নাঘর পরিষ্কার রাখা হয়।"),
    mcq("Are all bacteria harmful?", ["No - many are helpful, like those in yogurt and our gut", "Yes, all are dangerous", "Bacteria are not alive", "Only in water"], 0,
        "Good bacteria help digestion and make foods like yogurt and cheese.",
        "সব ব্যাকটেরিয়া কি ক্ষতিকর?", ["না - অনেকগুলো উপকারী, যেমন দই আর আমাদের পেটের গুলো", "হ্যাঁ, সবই বিপজ্জনক", "ব্যাকটেরিয়া জীবন্ত নয়", "শুধু জলে"],
        "উপকারী ব্যাকটেরিয়া হজমে সাহায্য করে আর দই আর পনিরের মতো খাবার বানায়।"),
    mcq("What is a 'carnivore'?", ["An animal that eats only or mostly meat", "A plant-eater", "A plant", "A fungus"], 0,
        "Lions, sharks and eagles are carnivores.",
        "'মাংসাশী' কী?", ["যে প্রাণী শুধু বা মূলত মাংস খায়", "তৃণভোজী", "উদ্ভিদ", "ছত্রাক"],
        "সিংহ, হাঙর আর ঈগল মাংসাশী।"),
    mcq("What is a 'herbivore'?", ["An animal that eats only plants", "A meat-eater", "A predator", "A decomposer"], 0,
        "Cows, elephants and rabbits are herbivores.",
        "'তৃণভোজী' কী?", ["যে প্রাণী শুধু উদ্ভিদ খায়", "মাংসাশী", "শিকারি", "বিয়োজক"],
        "গরু, হাতি আর খরগোশ তৃণভোজী।"),
    mcq("Why do many plants have thorns?", ["To stop animals eating them", "To catch rain", "To make seeds", "To look shiny"], 0,
        "Thorns are a defence adaptation.",
        "অনেক গাছে কাঁটা থাকে কেন?", ["প্রাণীদের খাওয়া ঠেকাতে", "বৃষ্টি ধরতে", "বীজ বানাতে", "চকচকে দেখাতে"],
        "কাঁটা একটা প্রতিরক্ষামূলক অভিযোজন।"),
    mcq("Mangrove trees grow in salty water at the coast. How do they help people?", ["Their roots protect coasts from storms and waves", "They make the sea sweet", "They stop all rain", "They do not help"], 0,
        "Mangrove forests like the Sundarbans soak up storm surges and shelter fish.",
        "ম্যানগ্রোভ গাছ উপকূলের নোনা জলে জন্মায়। এরা মানুষের কী উপকার করে?", ["শিকড় ঝড় আর ঢেউ থেকে উপকূল রক্ষা করে", "সমুদ্র মিষ্টি করে", "সব বৃষ্টি থামায়", "উপকার করে না"],
        "সুন্দরবনের মতো ম্যানগ্রোভ বন ঝড়ের জলোচ্ছ্বাস শুষে নেয় আর মাছের আশ্রয় দেয়।"),
    mcq("Why do some mangrove roots stick up out of the mud?", ["To breathe air, because the mud has little oxygen", "To catch fish", "To look scary", "To hold birds"], 0,
        "These breathing roots are called pneumatophores.",
        "কিছু ম্যানগ্রোভের শিকড় কাদা থেকে উপরে বেরিয়ে থাকে কেন?", ["বাতাসে শ্বাস নিতে, কারণ কাদায় অক্সিজেন কম", "মাছ ধরতে", "ভয় দেখাতে", "পাখি ধরতে"],
        "এই শ্বাসমূলকে বলে নিউম্যাটোফোর।"),
    mcq("What is 'germination'?", ["When a seed starts to grow", "When a plant dies", "When fruit ripens", "When leaves fall"], 0,
        "The seed swells, a root pushes down and a shoot pushes up.",
        "'অঙ্কুরোদ্গম' কী?", ["বীজ যখন বাড়তে শুরু করে", "গাছ যখন মরে", "ফল যখন পাকে", "পাতা যখন ঝরে"],
        "বীজ ফোলে, শিকড় নিচে আর কাণ্ড উপরে ঠেলে বেরোয়।"),
    mcq("A seed grows in the dark but then turns pale. What is missing?", ["Light", "Water", "Air", "Soil"], 0,
        "Seeds can sprout using stored food, but seedlings need light to make food and turn green.",
        "অন্ধকারে একটা বীজ গজালো কিন্তু পরে ফ্যাকাশে হয়ে গেল। কী নেই?", ["আলো", "জল", "বাতাস", "মাটি"],
        "জমানো খাবারে বীজ অঙ্কুরিত হতে পারে, কিন্তু চারার খাবার বানাতে আর সবুজ হতে আলো লাগে।"),
    mcq("Which animal changes completely as it grows (complete metamorphosis)?", ["Butterfly", "Dog", "Human", "Elephant"], 0,
        "Egg, larva, pupa, adult - each looks completely different.",
        "কোন প্রাণী বড় হতে হতে পুরোপুরি বদলে যায় (সম্পূর্ণ রূপান্তর)?", ["প্রজাপতি", "কুকুর", "মানুষ", "হাতি"],
        "ডিম, শূককীট, মূককীট, পূর্ণাঙ্গ - প্রতিটি দেখতে সম্পূর্ণ আলাদা।"),
    mcq("What is the life cycle of a hen?", ["Egg, chick, adult hen", "Seed, plant, hen", "Tadpole, chick, hen", "Caterpillar, hen"], 0,
        "Chicks hatch from eggs and grow into adults.",
        "মুরগির জীবনচক্র কী?", ["ডিম, ছানা, পূর্ণবয়স্ক মুরগি", "বীজ, গাছ, মুরগি", "ব্যাঙাচি, ছানা, মুরগি", "শুঁয়োপোকা, মুরগি"],
        "ডিম ফুটে ছানা বেরোয় আর বড় হয়ে পূর্ণবয়স্ক হয়।"),
    mcq("Why should we not pick wild flowers in protected parks?", ["They may be rare and are needed by insects and other animals", "They are made of plastic", "They grow back instantly", "No reason"], 0,
        "Protecting plants protects the whole habitat.",
        "সংরক্ষিত পার্কে বুনো ফুল তোলা উচিত নয় কেন?", ["এগুলো দুর্লভ হতে পারে আর পোকা ও অন্য প্রাণীর দরকার", "এগুলো প্লাস্টিকের", "সঙ্গে সঙ্গে আবার গজায়", "কোনো কারণ নেই"],
        "গাছ রক্ষা করলে পুরো আবাসস্থল রক্ষা পায়।"),
    mcq("Why do builders try to protect trees and rivers when building a bridge?", ["Habitats for plants and animals should not be destroyed", "Trees pay tolls", "Rivers are bridges", "They do not need to"], 0,
        "Good engineering plans around nature - sometimes with wildlife crossings and careful timing.",
        "সেতু বানানোর সময় নির্মাতারা গাছ আর নদী রক্ষার চেষ্টা করেন কেন?", ["উদ্ভিদ আর প্রাণীর আবাসস্থল নষ্ট করা উচিত নয়", "গাছ টোল দেয়", "নদী সেতু", "দরকার নেই"],
        "ভালো প্রকৌশল প্রকৃতিকে ঘিরে পরিকল্পনা করে - কখনো বন্যপ্রাণী পারাপারের পথ আর সাবধানী সময় বেছে।"),
    mcq("What are 'wildlife bridges' (green bridges)?", ["Bridges covered in plants that let animals cross busy roads", "Bridges made of animals", "Bridges painted green only", "Bridges for zoos"], 0,
        "They connect forests split by highways, so animals can move safely.",
        "'বন্যপ্রাণী সেতু' (সবুজ সেতু) কী?", ["গাছপালায় ঢাকা সেতু, যা দিয়ে প্রাণীরা ব্যস্ত রাস্তা পার হয়", "প্রাণী দিয়ে তৈরি সেতু", "শুধু সবুজ রং করা সেতু", "চিড়িয়াখানার সেতু"],
        "এগুলো মহাসড়কে ভাগ হওয়া বনকে জুড়ে দেয়, যাতে প্রাণীরা নিরাপদে চলাচল করতে পারে।"),
    mcq("Which sense helps a snake find warm-blooded prey in the dark?", ["Heat-sensing pits on its face", "Big ears", "Long eyelashes", "A trunk"], 0,
        "Some snakes 'see' body heat with special pits near their nose.",
        "অন্ধকারে উষ্ণ-রক্তের শিকার খুঁজতে সাপকে কোন ইন্দ্রিয় সাহায্য করে?", ["মুখের তাপ-বোধক গর্ত", "বড় কান", "লম্বা চোখের পাতা", "শুঁড়"],
        "কিছু সাপ নাকের কাছের বিশেষ গর্তে শরীরের তাপ 'দেখে'।"),
    mcq("Why do some animals live in groups (herds, flocks, schools)?", ["For safety from predators and help finding food", "Because they are lonely only", "To make noise", "They never do"], 0,
        "Many eyes spot danger sooner; teamwork helps find food.",
        "কিছু প্রাণী দলে থাকে (পাল, ঝাঁক) কেন?", ["শিকারি থেকে নিরাপত্তা আর খাবার খুঁজতে সাহায্যের জন্য", "শুধু একা লাগে বলে", "শব্দ করতে", "কখনো থাকে না"],
        "অনেক চোখ আগে বিপদ দেখে; দলগত কাজে খাবার খোঁজা সহজ।"),
    mcq("What is a 'food web'?", ["Many food chains linked together", "A spider's web of food", "A shop", "A recipe"], 0,
        "Most animals eat more than one thing, so chains join into a web.",
        "'খাদ্যজাল' কী?", ["অনেক খাদ্যশৃঙ্খল একসঙ্গে জোড়া", "খাবারের মাকড়সা-জাল", "একটা দোকান", "রান্নার প্রণালী"],
        "বেশিরভাগ প্রাণী একাধিক জিনিস খায়, তাই শৃঙ্খলগুলো জুড়ে জাল হয়।"),
    mcq("How do plants respond to touch, like the 'touch-me-not' (Mimosa)?", ["Its leaves fold up quickly", "It runs away", "It sings", "It does nothing"], 0,
        "Mimosa leaves fold when touched - maybe to scare away animals.",
        "লজ্জাবতী (ছুঁইমুই) গাছ ছুঁলে কী করে?", ["পাতা দ্রুত গুটিয়ে যায়", "পালিয়ে যায়", "গান গায়", "কিছুই করে না"],
        "লজ্জাবতীর পাতা ছুঁলে গুটিয়ে যায় - হয়তো প্রাণী তাড়াতে।"),
    mcq("What do sunflowers do during the day when young?", ["Turn to follow the Sun", "Close their petals", "Sink into the soil", "Change colour to blue"], 0,
        "Young sunflowers track the Sun across the sky.",
        "ছোট অবস্থায় সূর্যমুখী দিনের বেলা কী করে?", ["সূর্যকে অনুসরণ করে ঘোরে", "পাপড়ি বন্ধ করে", "মাটিতে ডুবে যায়", "নীল রং হয়"],
        "ছোট সূর্যমুখী আকাশ জুড়ে সূর্যকে অনুসরণ করে।"),
    mcq("Why is drinking clean water so important?", ["Dirty water can carry germs that cause disease", "Clean water tastes salty", "Dirty water is healthier", "It is not important"], 0,
        "Safe water prevents illnesses like cholera and typhoid.",
        "পরিষ্কার জল খাওয়া এত জরুরি কেন?", ["নোংরা জলে রোগের জীবাণু থাকতে পারে", "পরিষ্কার জল নোনতা", "নোংরা জল বেশি স্বাস্থ্যকর", "জরুরি নয়"],
        "নিরাপদ জল কলেরা আর টাইফয়েডের মতো অসুখ ঠেকায়।"),
    mcq("A clean-water pipe bridge to a village mainly helps people's...", ["Health", "Hair colour", "Height only", "Shoe size"], 0,
        "Clean drinking water is one of the biggest improvements to health any project can make.",
        "গ্রামে বিশুদ্ধ জলের পাইপ-সেতু মূলত মানুষের কোন জিনিসে সাহায্য করে?", ["স্বাস্থ্য", "চুলের রং", "শুধু উচ্চতা", "জুতোর মাপ"],
        "বিশুদ্ধ খাবার জল যেকোনো প্রকল্পের সবচেয়ে বড় স্বাস্থ্য-উন্নতির একটি।"),
    mcq("Which part of an eye lets light in?", ["The pupil", "The eyelash", "The eyebrow", "The eyelid"], 0,
        "The pupil gets bigger in dim light and smaller in bright light.",
        "চোখের কোন অংশ আলো ঢুকতে দেয়?", ["তারারন্ধ্র (পিউপিল)", "চোখের পাতার লোম", "ভুরু", "চোখের পাতা"],
        "অল্প আলোয় তারারন্ধ্র বড় আর উজ্জ্বল আলোয় ছোট হয়।"),
    mcq("Why do we blink?", ["To keep our eyes clean and moist", "To see colours", "To sleep", "To hear"], 0,
        "Each blink spreads tears that wash away dust.",
        "আমরা চোখ পিটপিট করি কেন?", ["চোখ পরিষ্কার আর ভেজা রাখতে", "রং দেখতে", "ঘুমাতে", "শুনতে"],
        "প্রতিটি পলক অশ্রু ছড়িয়ে ধুলো ধুয়ে দেয়।"),
    mcq("What do earthworms eat?", ["Dead leaves and plant matter in soil", "Rocks", "Mice", "Plastic"], 0,
        "Worms recycle dead plants into rich soil.",
        "কেঁচো কী খায়?", ["মাটির মরা পাতা আর উদ্ভিদাংশ", "পাথর", "ইঁদুর", "প্লাস্টিক"],
        "কেঁচো মরা গাছপালাকে উর্বর মাটিতে বদলায়।"),
    mcq("What is compost?", ["Rotted plant and food waste used to feed soil", "A type of rock", "A plastic", "A metal"], 0,
        "Composting turns waste into natural fertiliser.",
        "কম্পোস্ট কী?", ["মাটিকে খাওয়াতে ব্যবহৃত পচা উদ্ভিদ আর খাবারের বর্জ্য", "এক রকম পাথর", "একটা প্লাস্টিক", "একটা ধাতু"],
        "কম্পোস্ট বর্জ্যকে প্রাকৃতিক সারে বদলায়।"),
    mcq("Why do some trees lose their leaves in a dry season?", ["To save water", "Because leaves are tired", "To make more shade", "Wind steals them"], 0,
        "Leaves lose water; dropping them helps the tree survive drought.",
        "শুকনো মরসুমে কিছু গাছ পাতা ঝরায় কেন?", ["জল বাঁচাতে", "পাতা ক্লান্ত বলে", "বেশি ছায়া দিতে", "বাতাস চুরি করে"],
        "পাতা দিয়ে জল বেরোয়; পাতা ঝরিয়ে গাছ খরা টিকে থাকে।"),
    mcq("What do we call the tiny holes on leaves that let gases in and out?", ["Stomata", "Roots", "Petals", "Bark"], 0,
        "Stomata let carbon dioxide in and oxygen and water vapour out.",
        "পাতার যে ছোট ছিদ্র দিয়ে গ্যাস ঢোকে-বেরোয় তাকে কী বলি?", ["পত্ররন্ধ্র", "শিকড়", "পাপড়ি", "বাকল"],
        "পত্ররন্ধ্র কার্বন ডাই-অক্সাইড ঢুকতে আর অক্সিজেন ও জলীয় বাষ্প বেরোতে দেয়।"),
    mcq("A spider silk thread is very strong for its size. What could engineers use a material like it for?", ["Light, strong cables", "Heavy bricks", "Glass windows", "Soft pillows"], 0,
        "Scientists are trying to make artificial spider silk for ropes and cables.",
        "মাকড়সার রেশমের সুতো আকারের তুলনায় খুব শক্ত। প্রকৌশলীরা এমন উপাদান কীসে ব্যবহার করতে পারেন?", ["হালকা, শক্ত তারে", "ভারী ইটে", "কাচের জানালায়", "নরম বালিশে"],
        "বিজ্ঞানীরা দড়ি আর তারের জন্য কৃত্রিম মাকড়সা-রেশম বানানোর চেষ্টা করছেন।"),
    mcq("Why do giraffes have long legs and necks?", ["To reach high leaves and see far", "To swim", "To dig", "To hide underground"], 0,
        "Their height lets them eat leaves other animals cannot reach.",
        "জিরাফের লম্বা পা আর গলা কেন?", ["উঁচুর পাতা নাগাল পেতে আর দূরে দেখতে", "সাঁতার কাটতে", "গর্ত খুঁড়তে", "মাটির নিচে লুকাতে"],
        "উচ্চতা তাদের এমন পাতা খেতে দেয়, যা অন্য প্রাণী নাগাল পায় না।"),
    mcq("What is 'hibernation'?", ["A deep winter sleep to save energy", "Flying south", "Building a nest", "Shedding skin"], 0,
        "Hibernating animals slow their heartbeat and breathing.",
        "'শীতঘুম' কী?", ["শক্তি বাঁচাতে শীতের গভীর ঘুম", "দক্ষিণে উড়ে যাওয়া", "বাসা বানানো", "খোলস ছাড়া"],
        "শীতঘুমের প্রাণীরা হৃৎস্পন্দন আর শ্বাস ধীর করে।"),
    mcq("What is 'migration'?", ["A long seasonal journey to find food or warmth", "Sleeping all winter", "Changing colour", "Growing fur"], 0,
        "Birds, whales and butterflies migrate thousands of kilometres.",
        "'পরিযান' কী?", ["খাবার বা উষ্ণতার খোঁজে মরসুমি লম্বা যাত্রা", "সারা শীত ঘুমানো", "রং বদলানো", "লোম গজানো"],
        "পাখি, তিমি আর প্রজাপতি হাজার হাজার কিলোমিটার পরিযান করে।"),
    mcq("What is the job of white blood cells?", ["Fight germs", "Carry oxygen", "Make bones", "Digest food"], 0,
        "White blood cells defend your body against infection.",
        "শ্বেত রক্তকণিকার কাজ কী?", ["জীবাণুর সঙ্গে লড়াই", "অক্সিজেন বহন", "হাড় বানানো", "খাবার হজম"],
        "শ্বেত রক্তকণিকা সংক্রমণ থেকে শরীরকে রক্ষা করে।"),
    mcq("What do red blood cells carry?", ["Oxygen", "Food only", "Germs", "Bones"], 0,
        "Red cells carry oxygen from the lungs to every part of the body.",
        "লোহিত রক্তকণিকা কী বয়?", ["অক্সিজেন", "শুধু খাবার", "জীবাণু", "হাড়"],
        "লোহিত কণিকা ফুসফুস থেকে শরীরের প্রতিটি অংশে অক্সিজেন বয়।"),
    mcq("Why does a cut stop bleeding after a while?", ["Blood clots to seal the wound", "The blood runs out", "Skin glues itself instantly", "It never stops"], 0,
        "Platelets in blood form a clot, then a scab protects the healing skin.",
        "কিছুক্ষণ পরে কাটা জায়গার রক্ত পড়া থামে কেন?", ["রক্ত জমাট বেঁধে ক্ষত বন্ধ করে", "রক্ত ফুরিয়ে যায়", "ত্বক সঙ্গে সঙ্গে নিজে জুড়ে যায়", "কখনো থামে না"],
        "রক্তের অণুচক্রিকা জমাট বাঁধে, তারপর মামড়ি সারতে থাকা ত্বক রক্ষা করে।"),
    mcq("Which helps a cactus survive in the desert?", ["A waxy skin that stops water loss", "Big thin leaves", "Shallow tiny roots only", "Bright flowers all year"], 0,
        "The waxy coating seals water in.",
        "মরুভূমিতে টিকে থাকতে ক্যাকটাসকে কী সাহায্য করে?", ["মোমের মতো ত্বক, যা জল হারানো থামায়", "বড় পাতলা পাতা", "শুধু অগভীর ছোট শিকড়", "সারা বছর উজ্জ্বল ফুল"],
        "মোমের মতো আবরণ জল আটকে রাখে।"),
    mcq("Which animal is a mammal that lays eggs?", ["Platypus", "Cow", "Dog", "Whale"], 0,
        "The platypus and echidna are rare egg-laying mammals.",
        "কোন স্তন্যপায়ী ডিম পাড়ে?", ["প্লাটিপাস", "গরু", "কুকুর", "তিমি"],
        "প্লাটিপাস আর একিডনা বিরল ডিম-পাড়া স্তন্যপায়ী।"),
    mcq("How do bones grow and stay strong?", ["Eating calcium, getting vitamin D and exercising", "Sitting still all day", "Only drinking fizzy drinks", "Sleeping in the sun only"], 0,
        "Bones are living tissue that grows stronger with use and good food.",
        "হাড় কীভাবে বাড়ে আর শক্ত থাকে?", ["ক্যালসিয়াম খেয়ে, ভিটামিন D পেয়ে আর ব্যায়াম করে", "সারাদিন বসে থেকে", "শুধু ফেনাওয়ালা পানীয় খেয়ে", "শুধু রোদে ঘুমিয়ে"],
        "হাড় জীবন্ত কলা, ব্যবহার আর ভালো খাবারে শক্ত হয়।"),
    mcq("Why can a broken bone heal?", ["Bone is living tissue that rebuilds itself", "Doctors glue it with steel only", "Bones are made of plastic", "It cannot heal"], 0,
        "A cast holds the bone still while new bone grows across the break.",
        "ভাঙা হাড় জোড়া লাগে কেন?", ["হাড় জীবন্ত কলা, নিজে নিজে আবার গড়ে ওঠে", "ডাক্তার শুধু ইস্পাতের আঠায় জোড়েন", "হাড় প্লাস্টিকের", "জোড়া লাগে না"],
        "প্লাস্টার হাড়কে স্থির রাখে, আর ভাঙা জায়গা জুড়ে নতুন হাড় গজায়।"),
    mcq("What is a joint?", ["A place where two bones meet", "A type of food", "A muscle", "A tooth"], 0,
        "Joints like knees, elbows and hips let your skeleton move.",
        "সন্ধি কী?", ["যেখানে দুটি হাড় মেলে", "এক রকম খাবার", "একটা পেশি", "একটা দাঁত"],
        "হাঁটু, কনুই আর কোমরের মতো সন্ধি কঙ্কালকে নড়তে দেয়।"),
    mcq("How is the human knee like a bridge bearing?", ["Both let parts move smoothly while carrying heavy loads", "Both are made of steel", "Both are painted", "They are not alike"], 0,
        "Smooth cartilage and fluid let the knee move under your weight, like a bearing.",
        "মানুষের হাঁটু সেতুর বিয়ারিংয়ের মতো কীভাবে?", ["দুটোই ভারী ভার বইতে বইতে অংশগুলো মসৃণভাবে নড়তে দেয়", "দুটোই ইস্পাতের", "দুটোই রং করা", "একরকম নয়"],
        "মসৃণ তরুণাস্থি আর তরল হাঁটুকে তোমার ওজন নিয়েও নড়তে দেয়, বিয়ারিংয়ের মতো।"),
    mcq("Why do people need a balanced diet instead of only one food?", ["Different foods give different nutrients", "One food is always enough", "Variety makes us heavier only", "No reason"], 0,
        "No single food contains everything the body needs.",
        "শুধু একটা খাবারের বদলে সুষম খাদ্য কেন দরকার?", ["ভিন্ন খাবার ভিন্ন পুষ্টি দেয়", "একটা খাবারই সবসময় যথেষ্ট", "বৈচিত্র্য শুধু ভারী করে", "কোনো কারণ নেই"],
        "শরীরের যা দরকার সব কোনো একটা খাবারে থাকে না।"),
    mcq("Which of these animals breathes through its skin as well as lungs?", ["Frog", "Lion", "Eagle", "Snake"], 0,
        "Frogs' thin moist skin lets oxygen pass through.",
        "এগুলোর কোন প্রাণী ফুসফুসের সঙ্গে ত্বক দিয়েও শ্বাস নেয়?", ["ব্যাঙ", "সিংহ", "ঈগল", "সাপ"],
        "ব্যাঙের পাতলা ভেজা ত্বক দিয়ে অক্সিজেন ঢুকতে পারে।"),
    mcq("What is the main job of leaves?", ["Making food by photosynthesis", "Holding the plant in soil", "Making seeds", "Carrying water down"], 0,
        "Leaves are the plant's food factories.",
        "পাতার প্রধান কাজ কী?", ["সালোকসংশ্লেষে খাবার তৈরি", "মাটিতে গাছ ধরে রাখা", "বীজ তৈরি", "নিচে জল বয়ে নেওয়া"],
        "পাতা গাছের খাদ্য-কারখানা।"),
    mcq("What gives leaves their green colour?", ["Chlorophyll", "Paint", "Water", "Soil"], 0,
        "Chlorophyll captures sunlight for photosynthesis.",
        "পাতার সবুজ রং আসে কোথা থেকে?", ["ক্লোরোফিল", "রং", "জল", "মাটি"],
        "ক্লোরোফিল সালোকসংশ্লেষের জন্য সূর্যালোক ধরে।"),
    mcq("Why do roots of big trees spread wide near the surface?", ["To anchor the tree against wind and catch rain water", "To trip people", "To store toys", "To make shade"], 0,
        "Wide roots act like a broad foundation.",
        "বড় গাছের শিকড় মাটির কাছে চওড়া ছড়ায় কেন?", ["বাতাসের বিরুদ্ধে গাছ নোঙর করতে আর বৃষ্টির জল ধরতে", "মানুষকে হোঁচট খাওয়াতে", "খেলনা রাখতে", "ছায়া দিতে"],
        "চওড়া শিকড় চওড়া ভিতের মতো কাজ করে।"),
    mcq("What does a vet do for farm animals?", ["Keeps them healthy and treats illness", "Sells them only", "Builds their barns", "Paints them"], 0,
        "Healthy animals mean healthy food and farms.",
        "পশু-চিকিৎসক খামারের প্রাণীদের জন্য কী করেন?", ["সুস্থ রাখেন আর অসুখের চিকিৎসা করেন", "শুধু বেচেন", "গোয়ালঘর বানান", "রং করেন"],
        "সুস্থ প্রাণী মানে স্বাস্থ্যকর খাবার আর খামার।"),
    mcq("Why do we cook meat and eggs thoroughly?", ["Heat kills harmful bacteria", "To make them colder", "To add sugar", "No reason"], 0,
        "Cooking makes food safe and easier to digest.",
        "মাংস আর ডিম ভালো করে রান্না করি কেন?", ["তাপ ক্ষতিকর ব্যাকটেরিয়া মারে", "ঠান্ডা করতে", "চিনি যোগ করতে", "কোনো কারণ নেই"],
        "রান্না খাবারকে নিরাপদ আর সহজপাচ্য করে।"),
    mcq("What is a 'species'?", ["A group of living things that can breed together", "A single animal", "A type of rock", "A food"], 0,
        "Lions are one species; tigers are another.",
        "'প্রজাতি' কী?", ["একসঙ্গে বংশবৃদ্ধি করতে পারে এমন জীবের দল", "একটা প্রাণী", "এক রকম পাথর", "একটা খাবার"],
        "সিংহ একটা প্রজাতি; বাঘ আরেকটা।"),
    mcq("What does 'endangered' mean?", ["At risk of dying out", "Very common", "Dangerous to people", "Living in danger zones only"], 0,
        "Tigers and many sea turtles are endangered; protecting habitats helps them.",
        "'বিপন্ন' মানে কী?", ["বিলুপ্ত হওয়ার ঝুঁকিতে", "খুব সাধারণ", "মানুষের জন্য বিপজ্জনক", "শুধু বিপদ-অঞ্চলে বাস করে"],
        "বাঘ আর অনেক সামুদ্রিক কচ্ছপ বিপন্ন; আবাসস্থল রক্ষা তাদের সাহায্য করে।"),
    mcq("What does 'extinct' mean?", ["No longer alive anywhere on Earth", "Sleeping", "Hiding", "Very rare"], 0,
        "Dinosaurs and dodos are extinct.",
        "'বিলুপ্ত' মানে কী?", ["পৃথিবীর কোথাও আর জীবিত নেই", "ঘুমিয়ে আছে", "লুকিয়ে আছে", "খুব দুর্লভ"],
        "ডাইনোসর আর ডোডো বিলুপ্ত।"),
    mcq("Trees planted on riverbanks help bridges because...", ["Their roots stop the banks wearing away", "Trees hold up the bridge deck", "Leaves paint the bridge", "They do not help"], 0,
        "Stable banks protect bridge foundations from erosion - one of the Donation Camps!",
        "নদীর পাড়ে লাগানো গাছ সেতুকে সাহায্য করে কারণ...", ["শিকড় পাড় ক্ষয়ে যাওয়া থামায়", "গাছ সেতুর ডেক ধরে রাখে", "পাতা সেতু রং করে", "সাহায্য করে না"],
        "স্থির পাড় সেতুর ভিতকে ক্ষয় থেকে রক্ষা করে - এটা দান-শিবিরের একটা!"),
    mcq("Why do woodpeckers not get headaches from hammering trees?", ["Their skull and tongue bones absorb the shocks", "They wear helmets", "They hit softly", "They do get headaches"], 0,
        "Spongy bone and a special tongue bone act like shock absorbers - ideas used in helmet design.",
        "গাছে ঠোকর দিয়েও কাঠঠোকরার মাথাব্যথা হয় না কেন?", ["খুলি আর জিভের হাড় ধাক্কা শুষে নেয়", "হেলমেট পরে", "আস্তে ঠোকর দেয়", "মাথাব্যথা হয়"],
        "স্পঞ্জের মতো হাড় আর বিশেষ জিভ-হাড় ধাক্কা-শোষকের মতো কাজ করে - হেলমেটের নকশায় এই ধারণা ব্যবহার হয়।"),
    mcq("What does a leaf need from the air to make food?", ["Carbon dioxide", "Oxygen only", "Nitrogen only", "Smoke"], 0,
        "Leaves take in carbon dioxide through tiny pores and give out oxygen.",
        "খাবার বানাতে পাতার বাতাস থেকে কী লাগে?", ["কার্বন ডাই-অক্সাইড", "শুধু অক্সিজেন", "শুধু নাইট্রোজেন", "ধোঁয়া"],
        "পাতা ছোট ছিদ্র দিয়ে কার্বন ডাই-অক্সাইড নেয় আর অক্সিজেন ছাড়ে।"),
    mcq("Why do people wear seatbelts and helmets?", ["To protect bones and organs in a crash", "To look smart", "To keep warm", "It is not useful"], 0,
        "Protective gear spreads and slows the forces on your body.",
        "মানুষ সিটবেল্ট আর হেলমেট পরে কেন?", ["দুর্ঘটনায় হাড় আর অঙ্গ রক্ষা করতে", "স্মার্ট দেখাতে", "গরম থাকতে", "কাজের নয়"],
        "সুরক্ষা-সরঞ্জাম শরীরের উপর বল ছড়িয়ে দেয় আর ধীর করে।"),
    mcq("How do fish stay up in the water without sinking?", ["Many have an air-filled swim bladder", "They hold their breath", "They flap wings", "They sit on rocks"], 0,
        "The swim bladder works like a built-in float.",
        "মাছ না ডুবে জলে ভেসে থাকে কীভাবে?", ["অনেকের বাতাসভরা পটকা (সন্তরণ-থলি) আছে", "দম আটকে রাখে", "ডানা ঝাপটায়", "পাথরে বসে"],
        "পটকা যেন শরীরের ভেতরের একটা ভাসা।"),
    mcq("Which animal can regrow a lost tail?", ["Lizard", "Dog", "Horse", "Cow"], 0,
        "Many lizards drop their tail to escape and grow a new one.",
        "কোন প্রাণী হারানো লেজ আবার গজাতে পারে?", ["টিকটিকি", "কুকুর", "ঘোড়া", "গরু"],
        "অনেক টিকটিকি পালাতে লেজ খসিয়ে দেয় আর নতুন লেজ গজায়।"),
    mcq("What does a plant's flower turn into after pollination?", ["A fruit containing seeds", "A root", "A leaf", "A stem"], 0,
        "The base of the flower swells into a fruit.",
        "পরাগায়নের পর গাছের ফুল কীসে বদলায়?", ["বীজসহ ফলে", "শিকড়ে", "পাতায়", "কাণ্ডে"],
        "ফুলের গোড়া ফুলে ফল হয়।"),
    mcq("Why is exercise good for your bones as well as muscles?", ["Bones get stronger when they carry loads", "Exercise melts bones", "Bones do not change", "Exercise makes bones hollow"], 0,
        "Like a structure tested again and again, bones build up where they are loaded.",
        "ব্যায়াম পেশির মতো হাড়ের জন্যও ভালো কেন?", ["ভার বইলে হাড় শক্ত হয়", "ব্যায়ামে হাড় গলে", "হাড় বদলায় না", "ব্যায়ামে হাড় ফাঁপা হয়"],
        "বারবার পরীক্ষা হওয়া কাঠামোর মতো, হাড় যেখানে ভার পড়ে সেখানে মজবুত হয়।"),
)
