"""Class 4 - Physics: speed and motion, simple machines (levers, pulleys, ramps, wheels), springs,
floating and sinking, energy changes, heat, light, sound and electricity - with bridge examples."""
from . import mcq


def speed(d, t, who_en, who_bn):
    v = d // t
    o = list(dict.fromkeys([v, d * t, d + t, v * 2, v + 5]))[:4]
    return mcq(f"{who_en} travels {d} km in {t} hours at a steady speed. What is its speed?",
               [f"{x} km/h" for x in o], 0,
               f"Speed = distance ÷ time = {d} ÷ {t} = {v} km/h.",
               f"{who_bn} একটানা গতিতে {t} ঘণ্টায় {d} km যায়। তার গতি কত?",
               [f"{x} km/h" for x in o],
               f"গতি = দূরত্ব ÷ সময় = {d} ÷ {t} = {v} km/h।")


def trip(v, t, who_en, who_bn):
    d = v * t
    o = list(dict.fromkeys([d, v + t, v // t if v % t == 0 else v - t, d * 2, d + 10]))[:4]
    return mcq(f"{who_en} moves at {v} km/h for {t} hours. How far does it go?",
               [f"{x} km" for x in o], 0,
               f"Distance = speed x time = {v} x {t} = {d} km.",
               f"{who_bn} {v} km/h গতিতে {t} ঘণ্টা চলে। কত দূর যায়?",
               [f"{x} km" for x in o],
               f"দূরত্ব = গতি x সময় = {v} x {t} = {d} km।")


def seesaw(w1, d1, d2):
    w2 = w1 * d1 // d2
    o = list(dict.fromkeys([w2, w1, w1 + d2, w2 * 2, w2 + 10]))[:4]
    return mcq(f"On a balanced seesaw, a {w1} kg child sits {d1} m from the middle. How heavy must a child {d2} m from the middle on the other side be?",
               [f"{x} kg" for x in o], 0,
               f"Balance: weight x distance is equal on both sides. {w1} x {d1} = {w1 * d1}; {w1 * d1} ÷ {d2} = {w2} kg.",
               f"ভারসাম্যে থাকা ঢেঁকি-দোলনায় {w1} kg-এর এক শিশু মাঝখান থেকে {d1} m দূরে বসে। অন্য দিকে মাঝখান থেকে {d2} m দূরের শিশুর ওজন কত হতে হবে?",
               [f"{x} kg" for x in o],
               f"ভারসাম্য: দুই দিকে ওজন x দূরত্ব সমান। {w1} x {d1} = {w1 * d1}; {w1 * d1} ÷ {d2} = {w2} kg।")


ITEMS = (
    speed(120, 2, "A bus", "একটা বাস"),
    speed(300, 5, "A goods train", "একটা মালগাড়ি"),
    speed(45, 3, "A cyclist", "একজন সাইকেল-আরোহী"),
    speed(640, 8, "A cargo ship", "একটা মালবাহী জাহাজ"),
    speed(18, 3, "A walking group", "হাঁটার একটা দল"),
    speed(420, 6, "A truck on a highway", "মহাসড়কে একটা ট্রাক"),
    trip(60, 4, "A car", "একটা গাড়ি"),
    trip(80, 3, "An express train", "একটা এক্সপ্রেস ট্রেন"),
    trip(12, 5, "A river barge", "নদীর একটা বার্জ"),
    trip(25, 2, "A delivery scooter", "একটা ডেলিভারি স্কুটার"),
    seesaw(30, 2, 3),
    seesaw(40, 3, 4),
    seesaw(20, 3, 2),
    seesaw(25, 4, 5),
    mcq("What does 'speed' tell us?", ["How far something travels in a certain time", "How heavy it is", "How hot it is", "What colour it is"], 0,
        "Speed is distance divided by time, often in km/h or m/s.",
        "'গতি' আমাদের কী জানায়?", ["নির্দিষ্ট সময়ে কোনো কিছু কত দূর যায়", "সেটা কত ভারী", "সেটা কত গরম", "তার রং কী"],
        "গতি হলো দূরত্ব ভাগ সময়, প্রায়ই km/h বা m/s-এ।"),
    mcq("Which unit is a speed?", ["km/h", "kg", "litre", "newton"], 0,
        "km/h means kilometres travelled in each hour.",
        "কোনটা গতির একক?", ["km/h", "kg", "লিটার", "নিউটন"],
        "km/h মানে প্রতি ঘণ্টায় কত কিলোমিটার যাওয়া।"),
    mcq("Why do many bridges have speed limit signs?", ["Slower vehicles put less sudden force on the bridge and are safer", "To make traffic jams for fun", "Bridges are always slippery", "Signs make bridges stronger"], 0,
        "Fast, heavy braking and bouncing add extra force; speed limits also prevent crashes.",
        "অনেক সেতুতে গতিসীমার ফলক থাকে কেন?", ["ধীর গাড়ি সেতুতে কম আকস্মিক বল দেয় আর নিরাপদ", "মজা করে যানজট বানাতে", "সেতু সবসময় পিছল", "ফলক সেতু শক্ত করে"],
        "দ্রুত, জোরালো ব্রেক আর লাফানো বাড়তি বল যোগ করে; গতিসীমা দুর্ঘটনাও ঠেকায়।"),
    mcq("What is a 'lever'?", ["A stiff bar that turns on a pivot to make lifting easier", "A kind of rope", "A wheel", "A battery"], 0,
        "A crowbar, a seesaw and scissors are all levers.",
        "'লিভার' কী?", ["একটা শক্ত দণ্ড, যা একটা আলম্বের উপর ঘুরে তোলা সহজ করে", "এক রকম দড়ি", "চাকা", "ব্যাটারি"],
        "শাবল, ঢেঁকি-দোলনা আর কাঁচি - সবই লিভার।"),
    mcq("What is the 'fulcrum' (pivot) of a lever?", ["The point it turns around", "The heavy load", "The handle grip", "The paint"], 0,
        "Moving the fulcrum nearer the load makes lifting easier.",
        "লিভারের 'আলম্ব' (ফালক্রাম) কী?", ["যে বিন্দুর চারপাশে এটা ঘোরে", "ভারী বোঝা", "হাতলের মুঠি", "রং"],
        "আলম্বকে বোঝার কাছে সরালে তোলা সহজ হয়।"),
    mcq("To lift a heavy rock with a long bar, where should the pivot go?", ["Close to the rock", "Close to your hands", "Exactly in the middle always", "Far behind you"], 0,
        "A long handle on your side and a short side by the load multiplies your force.",
        "লম্বা দণ্ড দিয়ে ভারী পাথর তুলতে আলম্ব কোথায় রাখা উচিত?", ["পাথরের কাছে", "তোমার হাতের কাছে", "সবসময় ঠিক মাঝখানে", "তোমার অনেক পেছনে"],
        "তোমার দিকে লম্বা হাতল আর বোঝার দিকে ছোট অংশ তোমার বলকে বহুগুণ করে।"),
    mcq("Which of these is a lever?", ["A bottle opener", "A pillow", "A balloon", "A sponge"], 0,
        "A bottle opener pivots on the cap's edge to lift it off.",
        "এগুলোর কোনটা লিভার?", ["বোতল খোলার যন্ত্র", "বালিশ", "বেলুন", "স্পঞ্জ"],
        "বোতল-খোলা ঢাকনার কিনারায় ঘুরে ঢাকনা তুলে দেয়।"),
    mcq("What is a 'pulley'?", ["A wheel with a rope that helps lift loads", "A type of lever made of glass", "A heavy stone", "A spring"], 0,
        "Cranes on bridge sites use pulleys to lift steel beams.",
        "'কপিকল' (পুলি) কী?", ["দড়িসহ একটা চাকা, যা বোঝা তুলতে সাহায্য করে", "কাচের তৈরি এক রকম লিভার", "ভারী পাথর", "স্প্রিং"],
        "সেতু-নির্মাণস্থলের ক্রেন কপিকল দিয়ে ইস্পাতের বিম তোলে।"),
    mcq("How does a single fixed pulley help when lifting a bucket from a well?", ["You pull down instead of lifting up, which is easier", "It halves the weight", "It makes the bucket lighter", "It does nothing at all"], 0,
        "A single fixed pulley changes the direction of the force - you can use your body weight.",
        "কুয়ো থেকে বালতি তুলতে একটা স্থির কপিকল কীভাবে সাহায্য করে?", ["উপরে তোলার বদলে নিচে টানো, যা সহজ", "ওজন অর্ধেক করে", "বালতি হালকা করে", "কিছুই করে না"],
        "একটা স্থির কপিকল বলের দিক বদলায় - তুমি শরীরের ওজন কাজে লাগাতে পারো।"),
    mcq("Why do cranes use many pulleys together?", ["More pulleys let a smaller pull lift a heavier load", "They look nice", "Ropes need company", "To make the load heavier"], 0,
        "With more pulleys the rope is pulled further but with less force.",
        "ক্রেন অনেক কপিকল একসঙ্গে ব্যবহার করে কেন?", ["বেশি কপিকলে কম টানে বেশি ভারী বোঝা ওঠে", "দেখতে সুন্দর", "দড়ির সঙ্গী লাগে", "বোঝা ভারী করতে"],
        "বেশি কপিকলে দড়ি বেশি দূর টানতে হয়, কিন্তু কম বলে।"),
    mcq("What is a ramp (inclined plane) good for?", ["Moving heavy things up with less force", "Making things fall faster", "Stopping wheels", "Making noise"], 0,
        "A gentle ramp is longer but needs less push - that is why bridge approaches slope gently.",
        "ঢাল (আনত তল) কীসের জন্য ভালো?", ["কম বলে ভারী জিনিস উপরে তোলা", "জিনিস দ্রুত ফেলা", "চাকা থামানো", "শব্দ করা"],
        "মৃদু ঢাল লম্বা, কিন্তু কম ঠেলা লাগে - তাই সেতুর সংযোগপথ ধীরে ঢালু হয়।"),
    mcq("Which ramp needs the least push to roll a barrel up to a 1 m high truck?", ["A long gentle ramp", "A short steep ramp", "A vertical wall", "No ramp at all"], 0,
        "A longer ramp spreads the work over more distance, so each push is smaller.",
        "1 m উঁচু ট্রাকে একটা পিপে গড়িয়ে তুলতে কোন ঢালে সবচেয়ে কম ঠেলা লাগে?", ["লম্বা মৃদু ঢাল", "ছোট খাড়া ঢাল", "খাড়া দেওয়াল", "কোনো ঢাল নয়"],
        "লম্বা ঢাল কাজকে বেশি দূরত্বে ছড়িয়ে দেয়, তাই প্রতিটি ঠেলা ছোট হয়।"),
    mcq("Why do mountain roads zig-zag?", ["Zig-zags make the slope gentler for vehicles", "Drivers like turning", "Straight roads are illegal", "To make the trip shorter"], 0,
        "Each zig-zag is a ramp - longer but easier to climb.",
        "পাহাড়ি রাস্তা আঁকাবাঁকা হয় কেন?", ["আঁকাবাঁকা পথ গাড়ির জন্য ঢাল মৃদু করে", "চালকেরা বাঁক নিতে ভালোবাসেন", "সোজা রাস্তা বেআইনি", "যাত্রা ছোট করতে"],
        "প্রতিটি বাঁক একটা ঢাল - লম্বা, কিন্তু চড়া সহজ।"),
    mcq("A screw is really...", ["A ramp wrapped around a rod", "A tiny pulley", "A spring", "A magnet"], 0,
        "Turning a screw pushes it in along its spiral ramp - a big holding force from a small twist.",
        "স্ক্রু আসলে...", ["একটা দণ্ডের চারপাশে জড়ানো ঢাল", "ছোট্ট কপিকল", "স্প্রিং", "চুম্বক"],
        "স্ক্রু ঘোরালে তা প্যাঁচানো ঢাল ধরে ভেতরে ঢোকে - ছোট মোচড়ে বড় ধরে-রাখার বল।"),
    mcq("What is a 'wedge'?", ["A thick-to-thin shape that splits or holds things", "A round wheel", "A long rope", "A light bulb"], 0,
        "An axe head and a door stop are wedges.",
        "'গোঁজ' (ওয়েজ) কী?", ["মোটা থেকে সরু আকার, যা জিনিস চেরে বা আটকে রাখে", "গোল চাকা", "লম্বা দড়ি", "বাল্ব"],
        "কুড়ুলের মাথা আর দরজা-আটকানো গোঁজ দুটোই ওয়েজ।"),
    mcq("Why are wheels so useful?", ["They roll, which has much less friction than sliding", "They are heavy", "They make noise", "They stop motion"], 0,
        "Rolling a heavy load on wheels is far easier than dragging it.",
        "চাকা এত উপকারী কেন?", ["গড়ায়, যাতে পিছলানোর চেয়ে অনেক কম ঘর্ষণ", "ভারী", "শব্দ করে", "গতি থামায়"],
        "চাকায় ভারী বোঝা গড়ানো টেনে নেওয়ার চেয়ে অনেক সহজ।"),
    mcq("What is a 'wheel and axle'?", ["A wheel fixed to a rod so turning one turns the other", "Two separate wheels", "A flat ramp", "A pulley rope"], 0,
        "A steering wheel and a door knob are wheel-and-axle machines.",
        "'চাকা ও অক্ষদণ্ড' কী?", ["একটা দণ্ডে আটকানো চাকা, যাতে একটা ঘোরালে অন্যটাও ঘোরে", "দুটো আলাদা চাকা", "সমতল ঢাল", "কপিকলের দড়ি"],
        "স্টিয়ারিং-চাকা আর দরজার নব হলো চাকা-ও-অক্ষদণ্ড যন্ত্র।"),
    mcq("What do all 'simple machines' do?", ["Make work easier by changing the size or direction of a force", "Create energy from nothing", "Make things heavier", "Remove friction completely"], 0,
        "Machines trade distance for force - they never give free energy.",
        "সব 'সরল যন্ত্র' কী করে?", ["বলের মাপ বা দিক বদলে কাজ সহজ করে", "শূন্য থেকে শক্তি তৈরি করে", "জিনিস ভারী করে", "ঘর্ষণ পুরো দূর করে"],
        "যন্ত্র দূরত্বের বিনিময়ে বল দেয় - কখনো বিনামূল্যে শক্তি দেয় না।"),
    mcq("What happens to a spring when you hang a heavier weight on it?", ["It stretches more", "It shrinks", "It stays the same", "It turns into a magnet"], 0,
        "Double the weight, roughly double the stretch - until the spring is overloaded.",
        "স্প্রিংয়ে ভারী ওজন ঝোলালে কী হয়?", ["বেশি লম্বা হয়", "ছোট হয়", "একই থাকে", "চুম্বক হয়ে যায়"],
        "ওজন দ্বিগুণ করলে লম্বা হওয়াও মোটামুটি দ্বিগুণ - যতক্ষণ না স্প্রিং অতিরিক্ত ভারে পড়ে।"),
    mcq("A spring stretches 2 cm with 10 N. About how much with 30 N?", ["6 cm", "2 cm", "30 cm", "3 cm"], 0,
        "Three times the force gives three times the stretch: 3 x 2 = 6 cm.",
        "10 N-এ একটা স্প্রিং 2 cm লম্বা হয়। 30 N-এ মোটামুটি কত?", ["6 cm", "2 cm", "30 cm", "3 cm"],
        "তিন গুণ বলে তিন গুণ লম্বা: 3 x 2 = 6 cm।"),
    mcq("What happens if you overload a spring far too much?", ["It stays permanently stretched and is damaged", "It gets stronger", "It shrinks back perfectly forever", "It becomes heavier"], 0,
        "Every material has a limit; beyond it, it does not spring back. Bridge members have limits too.",
        "স্প্রিংয়ে অনেক বেশি বোঝা চাপালে কী হয়?", ["স্থায়ীভাবে লম্বা হয়ে নষ্ট হয়", "আরও শক্ত হয়", "চিরকাল নিখুঁতভাবে ফিরে আসে", "ভারী হয়"],
        "প্রতিটি উপাদানের একটা সীমা আছে; তার পরে আর ফিরে আসে না। সেতুর অংশেরও সীমা আছে।"),
    mcq("Why do cars and trains have springs (suspension)?", ["To soak up bumps for a smoother, safer ride", "To make them faster", "To hold the paint", "To light the lamps"], 0,
        "Springs and shock absorbers cushion bumps on roads and bridge joints.",
        "গাড়ি আর ট্রেনে স্প্রিং (সাসপেনশন) থাকে কেন?", ["ঝাঁকুনি শুষে মসৃণ, নিরাপদ যাত্রার জন্য", "দ্রুত চলতে", "রং ধরে রাখতে", "বাতি জ্বালাতে"],
        "স্প্রিং আর শক-অ্যাবজর্বার রাস্তা আর সেতুর জোড়ের ঝাঁকুনি সামলায়।"),
    mcq("Why does a big steel ship float?", ["Its hollow shape pushes aside lots of water, which pushes it up", "Steel is lighter than water", "Ships are full of helium", "The sea is magnetic"], 0,
        "A solid steel block sinks, but a hollow hull displaces enough water to float.",
        "বড় ইস্পাতের জাহাজ ভাসে কেন?", ["ফাঁপা আকার অনেক জল সরায়, যা তাকে উপরে ঠেলে", "ইস্পাত জলের চেয়ে হালকা", "জাহাজ হিলিয়ামে ভরা", "সমুদ্র চুম্বকীয়"],
        "শক্ত ইস্পাতের টুকরো ডোবে, কিন্তু ফাঁপা খোল যথেষ্ট জল সরিয়ে ভাসে।"),
    mcq("What is the upward push of water on a floating object called?", ["Upthrust (buoyancy)", "Gravity", "Friction", "Magnetism"], 0,
        "Upthrust balances the object's weight when it floats.",
        "ভাসমান বস্তুর উপর জলের উপরমুখী ঠেলাকে কী বলে?", ["প্লবতা (উৎপ্লাবন)", "মাধ্যাকর্ষণ", "ঘর্ষণ", "চুম্বকত্ব"],
        "ভাসার সময় প্লবতা বস্তুর ওজনকে ভারসাম্যে রাখে।"),
    mcq("Why does a loaded boat sit lower in the water?", ["It must push aside more water to balance the extra weight", "Water gets heavier", "The boat shrinks", "Gravity stops"], 0,
        "More weight needs more upthrust, so the boat sinks deeper until it balances.",
        "বোঝাই নৌকা জলে নিচু হয়ে বসে কেন?", ["বাড়তি ওজন সামলাতে বেশি জল সরাতে হয়", "জল ভারী হয়", "নৌকা ছোট হয়", "মাধ্যাকর্ষণ থামে"],
        "বেশি ওজনে বেশি প্লবতা লাগে, তাই নৌকা ভারসাম্য না পাওয়া পর্যন্ত গভীরে বসে।"),
    mcq("Why do boats have a line showing the maximum safe load?", ["Overloaded boats can sink or tip over", "For decoration", "To show the speed", "To measure rain"], 0,
        "Like a bridge's weight limit, a load line keeps boats safe.",
        "নৌকায় সর্বোচ্চ নিরাপদ বোঝার দাগ থাকে কেন?", ["অতিরিক্ত বোঝাই নৌকা ডুবতে বা উল্টে যেতে পারে", "সাজসজ্জার জন্য", "গতি দেখাতে", "বৃষ্টি মাপতে"],
        "সেতুর ওজন-সীমার মতো, বোঝার দাগ নৌকাকে নিরাপদ রাখে।"),
    mcq("Some bridges float on pontoons. What are pontoons?", ["Hollow floats that hold up the bridge deck", "Steel cables", "Concrete towers", "Tunnels"], 0,
        "Army engineers can build pontoon bridges quickly across rivers.",
        "কিছু সেতু পন্টুনের উপর ভাসে। পন্টুন কী?", ["ফাঁপা ভাসমান খোল, যা সেতুর পাটাতন ধরে রাখে", "ইস্পাতের তার", "কংক্রিটের টাওয়ার", "সুড়ঙ্গ"],
        "সেনা প্রকৌশলীরা নদীর উপর দ্রুত পন্টুন-সেতু বানাতে পারেন।"),
    mcq("What is 'energy'?", ["The ability to do work or make things change", "A type of food only", "A colour", "A kind of metal"], 0,
        "Energy makes things move, heat up, light up and make sound.",
        "'শক্তি' কী?", ["কাজ করার বা কোনো কিছু বদলানোর সামর্থ্য", "শুধু এক রকম খাবার", "একটা রং", "এক রকম ধাতু"],
        "শক্তি জিনিসকে চালায়, গরম করে, আলো দেয় আর শব্দ তৈরি করে।"),
    mcq("What kind of energy does a moving truck have?", ["Movement (kinetic) energy", "Sound energy only", "No energy", "Chemical energy only"], 0,
        "Moving things have kinetic energy - faster and heavier means more.",
        "চলন্ত ট্রাকের কী ধরনের শক্তি থাকে?", ["গতিশক্তি", "শুধু শব্দশক্তি", "কোনো শক্তি নেই", "শুধু রাসায়নিক শক্তি"],
        "চলমান জিনিসের গতিশক্তি থাকে - দ্রুত আর ভারী হলে বেশি।"),
    mcq("What energy does a book on a high shelf have because of its height?", ["Stored (potential) energy", "Sound energy", "Light energy", "No energy at all"], 0,
        "If it falls, that stored energy turns into movement.",
        "উঁচু তাকে রাখা বইয়ের উচ্চতার জন্য কী শক্তি থাকে?", ["সঞ্চিত (স্থিতি) শক্তি", "শব্দশক্তি", "আলোকশক্তি", "কোনো শক্তি নেই"],
        "পড়ে গেলে সেই সঞ্চিত শক্তি গতিতে বদলায়।"),
    mcq("What energy is stored in food, fuel and batteries?", ["Chemical energy", "Sound energy", "Kinetic energy", "Magnetic energy"], 0,
        "Burning fuel or digesting food releases chemical energy.",
        "খাবার, জ্বালানি আর ব্যাটারিতে কী শক্তি জমা থাকে?", ["রাসায়নিক শক্তি", "শব্দশক্তি", "গতিশক্তি", "চুম্বকশক্তি"],
        "জ্বালানি পোড়ালে বা খাবার হজম করলে রাসায়নিক শক্তি বেরোয়।"),
    mcq("A torch changes battery energy into...", ["Light (and a little heat)", "Sound only", "Food", "Water"], 0,
        "Energy changes form but is never destroyed.",
        "টর্চ ব্যাটারির শক্তিকে বদলায়...", ["আলোতে (আর সামান্য তাপে)", "শুধু শব্দে", "খাবারে", "জলে"],
        "শক্তির রূপ বদলায়, কিন্তু কখনো ধ্বংস হয় না।"),
    mcq("A wind turbine changes wind's movement energy into...", ["Electrical energy", "Chemical energy in food", "Ice", "Magnetism only"], 0,
        "Wind spins the blades, which turn a generator.",
        "বায়ুকল বাতাসের গতিশক্তিকে বদলায়...", ["বিদ্যুৎশক্তিতে", "খাবারের রাসায়নিক শক্তিতে", "বরফে", "শুধু চুম্বকত্বে"],
        "বাতাস ব্লেড ঘোরায়, যা জেনারেটর ঘোরায়।"),
    mcq("Which of these power sources will never run out?", ["Wind", "Coal", "Diesel", "Kerosene"], 0,
        "Wind, sunlight and flowing water are renewable; coal and oil take millions of years to form.",
        "এই শক্তির উৎসগুলোর কোনটা কখনো ফুরোবে না?", ["বাতাস", "কয়লা", "ডিজেল", "কেরোসিন"],
        "বাতাস, সূর্যালোক আর প্রবাহিত জল নবায়নযোগ্য; কয়লা আর তেল তৈরি হতে লক্ষ লক্ষ বছর লাগে।"),
    mcq("Why do some bridges have solar panels for their lights?", ["They use free, clean sunlight energy", "Panels hold the bridge up", "To make it heavier", "They scare birds"], 0,
        "Solar lighting cuts running costs and pollution.",
        "কিছু সেতুর বাতির জন্য সৌর প্যানেল থাকে কেন?", ["বিনামূল্যের, পরিষ্কার সূর্যালোকের শক্তি ব্যবহার করে", "প্যানেল সেতু ধরে রাখে", "ভারী করতে", "পাখি তাড়াতে"],
        "সৌর-আলো চালানোর খরচ আর দূষণ কমায়।"),
    mcq("What is the difference between heat and temperature?", ["Temperature is how hot; heat is energy that flows from hot to cold", "They are exactly the same", "Heat is measured with a ruler", "Temperature is a kind of energy store in kg"], 0,
        "A bathtub of warm water holds more heat than a cup of hotter tea.",
        "তাপ আর তাপমাত্রার পার্থক্য কী?", ["তাপমাত্রা হলো কত গরম; তাপ হলো গরম থেকে ঠান্ডায় যাওয়া শক্তি", "দুটো একদম এক", "তাপ রুলারে মাপা হয়", "তাপমাত্রা kg-এ এক রকম শক্তির ভান্ডার"],
        "এক বালতি গরম জলে এক কাপ বেশি গরম চায়ের চেয়ে বেশি তাপ থাকে।"),
    mcq("Which way does heat always flow on its own?", ["From hotter to colder", "From colder to hotter", "Upwards only", "It never flows"], 0,
        "A hot cup cools down as heat flows into the cooler air.",
        "তাপ নিজে থেকে সবসময় কোন দিকে যায়?", ["বেশি গরম থেকে ঠান্ডার দিকে", "ঠান্ডা থেকে গরমের দিকে", "শুধু উপরে", "কখনো যায় না"],
        "গরম কাপ ঠান্ডা হয়, কারণ তাপ শীতল বাতাসে চলে যায়।"),
    mcq("Which is a good conductor of heat?", ["Copper", "Wood", "Wool", "Plastic foam"], 0,
        "Metals carry heat quickly - that is why cooking pots are metal.",
        "কোনটা তাপের ভালো পরিবাহী?", ["তামা", "কাঠ", "পশম", "প্লাস্টিক ফোম"],
        "ধাতু দ্রুত তাপ বয় - তাই রান্নার পাত্র ধাতুর।"),
    mcq("Why do pan handles often have wooden or plastic grips?", ["They are insulators that keep heat from your hand", "They are better conductors", "They are heavier", "They look shiny"], 0,
        "Insulators slow heat flow and protect you from burns.",
        "কড়াইয়ের হাতলে প্রায়ই কাঠ বা প্লাস্টিকের মুঠি থাকে কেন?", ["অন্তরক, তাই হাতে তাপ আসতে দেয় না", "বেশি ভালো পরিবাহী", "বেশি ভারী", "চকচকে দেখায়"],
        "অন্তরক তাপপ্রবাহ ধীর করে আর পোড়া থেকে বাঁচায়।"),
    mcq("Why do steel bridges have 'expansion joints'?", ["Steel grows longer in heat and needs room to move", "To let water drain only", "For decoration", "To make cars bounce"], 0,
        "Without gaps, a hot bridge could push and bend itself.",
        "ইস্পাতের সেতুতে 'প্রসারণ-জোড়' থাকে কেন?", ["গরমে ইস্পাত লম্বা হয় আর সরার জায়গা লাগে", "শুধু জল বেরোতে", "সাজসজ্জার জন্য", "গাড়ি লাফাতে"],
        "ফাঁক না থাকলে গরম সেতু নিজেকে ঠেলে বাঁকিয়ে ফেলতে পারত।"),
    mcq("Why do railway tracks have small gaps between rails (in older lines)?", ["To let the rails expand in hot weather", "To save steel", "To make a clicking sound for fun", "Because workers ran out of rail"], 0,
        "Hot rails expand; without gaps they could buckle.",
        "(পুরোনো লাইনে) রেললাইনের মাঝে ছোট ফাঁক থাকে কেন?", ["গরমে রেলকে প্রসারিত হতে দিতে", "ইস্পাত বাঁচাতে", "মজার খটখট শব্দের জন্য", "কর্মীদের রেল ফুরিয়ে গিয়েছিল"],
        "গরম রেল প্রসারিত হয়; ফাঁক না থাকলে বেঁকে যেতে পারে।"),
    mcq("Why do power lines sag more on hot summer days?", ["The wires expand and get longer in heat", "Birds sit on them", "They get heavier", "Electricity pulls them down"], 0,
        "Engineers leave slack so wires do not snap when they shrink in winter.",
        "গরমের দিনে বিদ্যুতের তার বেশি ঝুলে থাকে কেন?", ["তাপে তার প্রসারিত হয়ে লম্বা হয়", "পাখি বসে", "ভারী হয়", "বিদ্যুৎ নিচে টানে"],
        "প্রকৌশলীরা ঢিল রাখেন, যাতে শীতে সংকুচিত হলে তার না ছেঁড়ে।"),
    mcq("What does a thermometer measure?", ["Temperature", "Weight", "Speed", "Length"], 0,
        "Temperature is often measured in degrees Celsius (°C).",
        "থার্মোমিটার কী মাপে?", ["তাপমাত্রা", "ওজন", "গতি", "দৈর্ঘ্য"],
        "তাপমাত্রা প্রায়ই ডিগ্রি সেলসিয়াসে (°C) মাপা হয়।"),
    mcq("A pot of water reads 100 °C and is bubbling hard. What is happening?", ["It is boiling and turning into steam", "It is freezing", "It is melting", "It is turning into ice"], 0,
        "At sea level pure water boils at 100 °C and freezes at 0 °C.",
        "এক হাঁড়ি জলের তাপমাত্রা 100 °C আর জোরে বুদবুদ উঠছে। কী হচ্ছে?", ["ফুটছে আর বাষ্পে বদলাচ্ছে", "জমছে", "গলছে", "বরফ হচ্ছে"],
        "সমুদ্রতলে বিশুদ্ধ জল 100 °C-এ ফোটে আর 0 °C-এ জমে।"),
    mcq("How does light travel?", ["In straight lines", "In circles", "Only around corners", "It does not travel"], 0,
        "That is why shadows form - light cannot bend around solid objects.",
        "আলো কীভাবে চলে?", ["সরলরেখায়", "বৃত্তে", "শুধু কোণ ঘুরে", "চলে না"],
        "তাই ছায়া হয় - আলো শক্ত বস্তুর চারপাশে বাঁকতে পারে না।"),
    mcq("What happens when light hits a mirror?", ["It bounces off (reflects)", "It disappears", "It turns into sound", "It gets heavier"], 0,
        "Reflection lets us see ourselves - and helps drivers see around bends with road mirrors.",
        "আলো আয়নায় পড়লে কী হয়?", ["প্রতিফলিত হয়ে ফিরে আসে", "উধাও হয়", "শব্দে বদলায়", "ভারী হয়"],
        "প্রতিফলনে আমরা নিজেদের দেখি - আর রাস্তার আয়না চালকদের বাঁকের ওপারে দেখতে সাহায্য করে।"),
    mcq("Why do road signs and bridge barriers have reflective strips?", ["They bounce headlight beams back to drivers at night", "They glow by themselves forever", "They are heavier", "To make noise"], 0,
        "Reflectors make hazards visible in the dark.",
        "রাস্তার ফলক আর সেতুর রেলিংয়ে প্রতিফলক ফালি থাকে কেন?", ["রাতে হেডলাইটের আলো চালকের দিকে ফিরিয়ে দেয়", "নিজে থেকে চিরকাল জ্বলে", "বেশি ভারী", "শব্দ করতে"],
        "প্রতিফলক অন্ধকারে বিপদ দৃশ্যমান করে।"),
    mcq("Why does a straw look bent in a glass of water?", ["Light bends as it passes from water into air", "The straw really bends", "Water is magnetic", "Your eyes are tired"], 0,
        "This bending of light is called refraction.",
        "জলের গ্লাসে স্ট্র বাঁকা দেখায় কেন?", ["জল থেকে বাতাসে যাওয়ার সময় আলো বাঁকে", "স্ট্র সত্যিই বাঁকে", "জল চুম্বকীয়", "তোমার চোখ ক্লান্ত"],
        "আলোর এই বাঁকাকে প্রতিসরণ বলে।"),
    mcq("What splits white sunlight into rainbow colours?", ["A prism or raindrops", "A mirror only", "A magnet", "A spring"], 0,
        "White light is a mix of colours that bend by different amounts.",
        "সাদা সূর্যালোককে রামধনুর রঙে ভাগ করে কী?", ["প্রিজম বা বৃষ্টির ফোঁটা", "শুধু আয়না", "চুম্বক", "স্প্রিং"],
        "সাদা আলো রঙের মিশ্রণ, যারা ভিন্ন মাত্রায় বাঁকে।"),
    mcq("What is sound?", ["Vibrations travelling through air, water or solids", "A kind of light", "A metal", "A magnet"], 0,
        "A drum skin vibrates and pushes the air back and forth.",
        "শব্দ কী?", ["বাতাস, জল বা কঠিনের মধ্য দিয়ে চলা কম্পন", "এক রকম আলো", "ধাতু", "চুম্বক"],
        "ঢোলের চামড়া কাঁপে আর বাতাসকে সামনে-পেছনে ঠেলে।"),
    mcq("Can sound travel through empty space?", ["No - it needs something to vibrate through", "Yes, faster than light", "Only at night", "Only through glass"], 0,
        "In space there is no air, so astronauts use radios.",
        "শব্দ কি ফাঁকা মহাকাশ দিয়ে যেতে পারে?", ["না - কম্পনের জন্য কোনো মাধ্যম লাগে", "হ্যাঁ, আলোর চেয়ে দ্রুত", "শুধু রাতে", "শুধু কাচ দিয়ে"],
        "মহাকাশে বাতাস নেই, তাই মহাকাশচারীরা রেডিও ব্যবহার করেন।"),
    mcq("What makes a sound high-pitched?", ["Fast vibrations", "Slow vibrations", "Loud vibrations only", "No vibrations"], 0,
        "A short, tight string vibrates fast and sounds high.",
        "শব্দ তীক্ষ্ণ (উঁচু সুরের) হয় কীসে?", ["দ্রুত কম্পনে", "ধীর কম্পনে", "শুধু জোরালো কম্পনে", "কম্পন ছাড়া"],
        "ছোট, টানটান তার দ্রুত কাঁপে আর উঁচু শোনায়।"),
    mcq("What makes a sound louder?", ["Bigger vibrations", "Smaller vibrations", "Colder air", "A darker room"], 0,
        "Hitting a drum harder makes bigger vibrations and a louder sound.",
        "শব্দ জোরালো হয় কীসে?", ["বড় কম্পনে", "ছোট কম্পনে", "ঠান্ডা বাতাসে", "অন্ধকার ঘরে"],
        "ঢোলে জোরে মারলে বড় কম্পন হয় আর শব্দ জোরালো হয়।"),
    mcq("Why can you hear a train coming by putting your ear near the rail (never do it on a live line!)?", ["Sound travels faster and further through steel than air", "Rails are magnets", "Trains whisper", "Steel stores sound"], 0,
        "Solids carry sound well - but stay safely away from real railway tracks.",
        "রেলে কান রাখলে আসন্ন ট্রেনের শব্দ শোনা যায় কেন (চালু লাইনে কখনো কোরো না!)?", ["ইস্পাতের মধ্য দিয়ে শব্দ বাতাসের চেয়ে দ্রুত আর দূরে যায়", "রেল চুম্বক", "ট্রেন ফিসফিস করে", "ইস্পাত শব্দ জমিয়ে রাখে"],
        "কঠিন পদার্থ ভালো শব্দ বয় - তবে আসল রেললাইন থেকে নিরাপদ দূরে থাকো।"),
    mcq("Why are noise barriers built beside busy highways and bridges?", ["To block traffic sound from nearby homes", "To stop the wind completely", "To hold up the bridge", "To make cars faster"], 0,
        "Walls reflect and absorb sound to protect neighbours.",
        "ব্যস্ত মহাসড়ক আর সেতুর পাশে শব্দ-প্রতিরোধক দেওয়াল বানানো হয় কেন?", ["কাছের বাড়িতে যানবাহনের শব্দ আটকাতে", "বাতাস পুরো থামাতে", "সেতু ধরে রাখতে", "গাড়ি দ্রুত চালাতে"],
        "দেওয়াল শব্দ প্রতিফলিত আর শোষণ করে প্রতিবেশীদের রক্ষা করে।"),
    mcq("Why does an empty room echo more than a furnished one?", ["Bare hard walls reflect sound; soft furniture absorbs it", "Empty rooms make their own sound", "Furniture creates echoes", "Echoes need carpets"], 0,
        "Engineers add soft panels in tunnels and halls to cut echoes.",
        "খালি ঘরে আসবাব-ভরা ঘরের চেয়ে বেশি প্রতিধ্বনি হয় কেন?", ["খালি শক্ত দেওয়াল শব্দ প্রতিফলিত করে; নরম আসবাব শোষণ করে", "খালি ঘর নিজে শব্দ তৈরি করে", "আসবাব প্রতিধ্বনি বানায়", "প্রতিধ্বনির জন্য কার্পেট লাগে"],
        "সুড়ঙ্গ আর হলঘরে প্রতিধ্বনি কমাতে প্রকৌশলীরা নরম প্যানেল লাগান।"),
    mcq("What does an electric circuit need for a bulb to light?", ["A complete loop from the battery through the bulb and back", "A broken wire", "Only a bulb", "A magnet"], 0,
        "Electricity flows only around a complete circuit.",
        "বাল্ব জ্বালাতে বৈদ্যুতিক বর্তনীর কী দরকার?", ["ব্যাটারি থেকে বাল্ব হয়ে আবার ফিরে আসা সম্পূর্ণ পথ", "ভাঙা তার", "শুধু বাল্ব", "চুম্বক"],
        "বিদ্যুৎ কেবল সম্পূর্ণ বর্তনীতে প্রবাহিত হয়।"),
    mcq("All the lamps on a footbridge share one switch. What happens when it is turned off?", ["The circuit opens and all the lamps go out", "Only one lamp goes out", "The lamps get brighter", "The wires store the light"], 0,
        "A switch opens or closes the loop; an open loop stops the current.",
        "একটা হাঁটার সেতুর সব বাতি একটা সুইচে চলে। সুইচ বন্ধ করলে কী হয়?", ["বর্তনী খুলে যায় আর সব বাতি নেভে", "শুধু একটা বাতি নেভে", "বাতি আরও উজ্জ্বল হয়", "তার আলো জমিয়ে রাখে"],
        "সুইচ পথ খোলে বা বন্ধ করে; খোলা পথ বিদ্যুৎ থামায়।"),
    mcq("Which material is an electrical insulator?", ["Rubber", "Copper", "Iron", "Aluminium"], 0,
        "Rubber and plastic cover wires to keep electricity inside.",
        "কোন উপাদান বিদ্যুৎ-অন্তরক?", ["রবার", "তামা", "লোহা", "অ্যালুমিনিয়াম"],
        "রবার আর প্লাস্টিক তার ঢেকে বিদ্যুৎকে ভেতরে রাখে।"),
    mcq("Why are electric wires made of copper inside?", ["Copper conducts electricity very well", "Copper is cheapest of all things", "Copper is an insulator", "Copper is magnetic"], 0,
        "Good conductors let current flow easily.",
        "বিদ্যুতের তারের ভেতরটা তামার হয় কেন?", ["তামা খুব ভালো বিদ্যুৎ পরিবহন করে", "তামা সবচেয়ে সস্তা জিনিস", "তামা অন্তরক", "তামা চুম্বকীয়"],
        "ভালো পরিবাহী বিদ্যুৎকে সহজে বইতে দেয়।"),
    mcq("Why must you never touch electric cables with wet hands?", ["Water can carry electricity into your body", "Water makes cables cold", "Cables get rusty", "It is just impolite"], 0,
        "Electricity and water are a dangerous mix.",
        "ভেজা হাতে কখনো বৈদ্যুতিক তার ছোঁবে না কেন?", ["জল বিদ্যুৎকে তোমার শরীরে বয়ে আনতে পারে", "জল তার ঠান্ডা করে", "তারে মরচে ধরে", "শুধু অভদ্রতা"],
        "বিদ্যুৎ আর জল বিপজ্জনক মিশ্রণ।"),
    mcq("Adding a second battery in a line to a bulb circuit usually makes the bulb...", ["Brighter", "Dimmer", "Go out", "Change colour to blue"], 0,
        "More batteries push more current through the bulb.",
        "বাল্বের বর্তনীতে লাইনে আরেকটা ব্যাটারি যোগ করলে সাধারণত বাল্ব...", ["আরও উজ্জ্বল হয়", "আরও ম্লান হয়", "নিভে যায়", "নীল রঙের হয়"],
        "বেশি ব্যাটারি বাল্বে বেশি বিদ্যুৎ ঠেলে।"),
    mcq("What is the main danger of lightning to tall bridges?", ["A huge electric current can strike the highest point", "It makes them wet", "It freezes them", "It has no danger"], 0,
        "Lightning conductors give the current a safe path to the ground.",
        "উঁচু সেতুর জন্য বজ্রপাতের প্রধান বিপদ কী?", ["বিশাল বিদ্যুৎ-প্রবাহ সবচেয়ে উঁচু জায়গায় আঘাত করতে পারে", "ভিজিয়ে দেয়", "জমিয়ে দেয়", "কোনো বিপদ নেই"],
        "বজ্রনিরোধক দণ্ড বিদ্যুৎকে মাটিতে যাওয়ার নিরাপদ পথ দেয়।"),
    mcq("What does a lightning conductor on a tall tower do?", ["Carries lightning safely down to the ground", "Attracts rain", "Makes electricity for lamps", "Holds the tower up"], 0,
        "A thick metal strip runs from the top to deep in the ground.",
        "উঁচু টাওয়ারে বজ্রনিরোধক দণ্ড কী করে?", ["বজ্রকে নিরাপদে মাটিতে নামিয়ে দেয়", "বৃষ্টি টানে", "বাতির জন্য বিদ্যুৎ বানায়", "টাওয়ার ধরে রাখে"],
        "উপর থেকে মাটির গভীর পর্যন্ত মোটা ধাতুর পাত থাকে।"),
    mcq("Which pole of a magnet attracts the north pole of another magnet?", ["South pole", "North pole", "Both poles equally repel", "Neither"], 0,
        "Opposite poles attract; like poles repel.",
        "চুম্বকের কোন মেরু অন্য চুম্বকের উত্তর মেরুকে আকর্ষণ করে?", ["দক্ষিণ মেরু", "উত্তর মেরু", "দুই মেরুই সমানভাবে বিকর্ষণ করে", "কোনোটাই না"],
        "বিপরীত মেরু আকর্ষণ করে; সমমেরু বিকর্ষণ করে।"),
    mcq("How do scrapyards lift old cars with magnets?", ["Using electromagnets that can be switched on and off", "With fridge magnets", "With wooden magnets", "Magnets cannot lift cars"], 0,
        "An electromagnet is a coil of wire that becomes magnetic when current flows.",
        "লোহা-লক্কড়ের ভাগাড়ে চুম্বক দিয়ে পুরোনো গাড়ি তোলে কীভাবে?", ["চালু-বন্ধ করা যায় এমন তড়িৎচুম্বক দিয়ে", "ফ্রিজের চুম্বক দিয়ে", "কাঠের চুম্বক দিয়ে", "চুম্বক গাড়ি তুলতে পারে না"],
        "তড়িৎচুম্বক হলো তারের কুণ্ডলী, যা বিদ্যুৎ চললে চুম্বক হয়।"),
    mcq("Why does a heavy truck take longer to stop than a bicycle at the same speed?", ["It has much more movement energy to get rid of", "Trucks have no brakes", "Bicycles are magnetic", "Roads favour bicycles"], 0,
        "More mass means more energy and a longer braking distance - keep well back from trucks.",
        "একই গতিতে ভারী ট্রাক থামতে সাইকেলের চেয়ে বেশি সময় নেয় কেন?", ["তার ঝেড়ে ফেলার মতো অনেক বেশি গতিশক্তি", "ট্রাকে ব্রেক নেই", "সাইকেল চুম্বকীয়", "রাস্তা সাইকেলের পক্ষে"],
        "বেশি ভর মানে বেশি শক্তি আর লম্বা ব্রেকিং-দূরত্ব - ট্রাক থেকে দূরে থাকো।"),
    mcq("Why do roads have more friction-giving rough surfaces before a sharp bend or a bridge?", ["To help tyres grip so vehicles can slow safely", "To make cars bounce for fun", "To wear tyres out", "To make noise"], 0,
        "Rough anti-skid surfaces shorten stopping distances.",
        "তীক্ষ্ণ বাঁক বা সেতুর আগে রাস্তায় বেশি ঘর্ষণের খসখসে তল থাকে কেন?", ["টায়ার আঁকড়ে ধরে যাতে গাড়ি নিরাপদে ধীর হয়", "মজায় গাড়ি লাফাতে", "টায়ার ক্ষয় করতে", "শব্দ করতে"],
        "খসখসে পিছল-রোধী তল থামার দূরত্ব কমায়।"),
    mcq("What is 'gravity'?", ["The pull that attracts objects towards each other, like Earth pulling us down", "A push from the wind", "A kind of magnet only for iron", "Friction on ice"], 0,
        "Gravity gives everything weight - bridges must hold up the weight of themselves and their traffic.",
        "'মাধ্যাকর্ষণ' কী?", ["যে টান বস্তুকে পরস্পরের দিকে টানে, যেমন পৃথিবী আমাদের নিচে টানে", "বাতাসের ঠেলা", "শুধু লোহার জন্য এক রকম চুম্বক", "বরফের উপর ঘর্ষণ"],
        "মাধ্যাকর্ষণ সব কিছুকে ওজন দেয় - সেতুকে নিজের আর যানবাহনের ওজন ধরে রাখতে হয়।"),
    mcq("Why does a parachute make a person fall slowly?", ["Its big canopy creates lots of air resistance", "It removes gravity", "It is full of helium", "It is magnetic"], 0,
        "Air pushes up on the large surface, slowing the fall.",
        "প্যারাশুট মানুষকে ধীরে নামায় কেন?", ["তার বড় ছাতা অনেক বায়ুর বাধা তৈরি করে", "মাধ্যাকর্ষণ সরিয়ে দেয়", "হিলিয়ামে ভরা", "চুম্বকীয়"],
        "বাতাস বড় তলে উপরে ঠেলে পতন ধীর করে।"),
    mcq("Why are tall bridges tested in wind tunnels before being built?", ["To check strong winds will not shake them dangerously", "To dry the paint", "To test the lights", "To count cars"], 0,
        "Engineers test models so the real bridge stays steady in storms.",
        "উঁচু সেতু বানানোর আগে বায়ু-সুড়ঙ্গে পরীক্ষা করা হয় কেন?", ["প্রবল বাতাস যেন বিপজ্জনকভাবে না কাঁপায় তা যাচাই করতে", "রং শুকাতে", "বাতি পরীক্ষা করতে", "গাড়ি গুনতে"],
        "প্রকৌশলীরা মডেল পরীক্ষা করেন, যাতে ঝড়ে আসল সেতু স্থির থাকে।"),
    mcq("What happens when a soldier troop marches in step across a small bridge?", ["The rhythm can make the bridge sway more and more", "Nothing at all", "The bridge gets lighter", "Soldiers float"], 0,
        "Matching rhythm can build up big wobbles (resonance), so troops break step on bridges.",
        "সৈন্যদল তালে তালে পা ফেলে ছোট সেতু পার হলে কী হয়?", ["ছন্দ সেতুকে ক্রমশ বেশি দোলাতে পারে", "কিছুই না", "সেতু হালকা হয়", "সৈন্যরা ভাসে"],
        "মিলে যাওয়া ছন্দ বড় দোলা জমাতে পারে (অনুনাদ), তাই সেতুতে সৈন্যরা তাল ভেঙে হাঁটে।"),
    mcq("A pendulum swings back and forth. What makes it slow down and stop?", ["Air resistance and friction at the pivot", "Magnetism", "Light", "Sound"], 0,
        "Friction turns its movement energy into a little heat.",
        "একটা দোলক সামনে-পেছনে দোলে। কীসে সেটা ধীর হয়ে থামে?", ["বায়ুর বাধা আর আলম্বের ঘর্ষণে", "চুম্বকত্বে", "আলোয়", "শব্দে"],
        "ঘর্ষণ তার গতিশক্তিকে সামান্য তাপে বদলায়।"),
    mcq("Which is the best way to measure the length of a bridge model?", ["A measuring tape or ruler", "A thermometer", "A scale for weight", "A clock"], 0,
        "Measure in metres or centimetres.",
        "সেতুর মডেলের দৈর্ঘ্য মাপার সবচেয়ে ভালো উপায় কোনটা?", ["মাপার ফিতে বা রুলার", "থার্মোমিটার", "ওজনের দাঁড়িপাল্লা", "ঘড়ি"],
        "মিটার বা সেন্টিমিটারে মাপো।"),
    mcq("A bridge is 2 km long. How many metres is that?", ["2,000 m", "200 m", "20 m", "20,000 m"], 0,
        "1 km = 1,000 m, so 2 km = 2,000 m.",
        "একটা সেতু 2 km লম্বা। তা কত মিটার?", ["2,000 m", "200 m", "20 m", "20,000 m"],
        "1 km = 1,000 m, তাই 2 km = 2,000 m।"),
    mcq("How many seconds are in a minute?", ["60", "100", "30", "24"], 0,
        "60 seconds = 1 minute; 60 minutes = 1 hour.",
        "এক মিনিটে কত সেকেন্ড?", ["60", "100", "30", "24"],
        "60 সেকেন্ড = 1 মিনিট; 60 মিনিট = 1 ঘণ্টা।"),
    mcq("Why do scientists repeat an experiment several times?", ["To check the results are reliable", "To waste time", "Because the first try is always wrong", "To use more materials"], 0,
        "Repeating tests catches mistakes - engineers test bridges many times too.",
        "বিজ্ঞানীরা একটা পরীক্ষা কয়েকবার করেন কেন?", ["ফলাফল নির্ভরযোগ্য কিনা যাচাই করতে", "সময় নষ্ট করতে", "প্রথমবার সবসময় ভুল হয়", "বেশি উপাদান খরচ করতে"],
        "পরীক্ষা বারবার করলে ভুল ধরা পড়ে - প্রকৌশলীরাও সেতু বহুবার পরীক্ষা করেন।"),
    mcq("What is a 'fair test' in science?", ["Changing only one thing at a time and keeping everything else the same", "Changing everything at once", "Guessing the answer", "Asking a friend"], 0,
        "If you test bridge shapes, use the same material and load for each.",
        "বিজ্ঞানে 'ন্যায্য পরীক্ষা' কী?", ["একবারে শুধু একটা জিনিস বদলানো আর বাকি সব একই রাখা", "একসঙ্গে সব বদলানো", "উত্তর অনুমান করা", "বন্ধুকে জিজ্ঞাসা করা"],
        "সেতুর আকার পরীক্ষা করলে প্রতিটিতে একই উপাদান আর বোঝা ব্যবহার করো।"),
    mcq("You test which paper bridge holds the most coins. What should stay the same in each test?", ["The paper type, the gap and how coins are added", "Nothing", "Only the colour", "Only the day of the week"], 0,
        "Change just the shape; keep everything else fixed so the result is fair.",
        "কোন কাগজের সেতু সবচেয়ে বেশি পয়সা ধরে তা পরীক্ষা করছ। প্রতিটি পরীক্ষায় কী একই রাখা উচিত?", ["কাগজের ধরন, ফাঁক আর পয়সা রাখার পদ্ধতি", "কিছুই না", "শুধু রং", "শুধু সপ্তাহের দিন"],
        "শুধু আকার বদলাও; বাকি সব স্থির রাখো, যাতে ফলাফল ন্যায্য হয়।"),
    mcq("A folded zig-zag paper bridge holds more coins than a flat one. Why?", ["Folds make the paper much stiffer against bending", "Folding makes paper heavier", "Coins like zig-zags", "Flat paper is magnetic"], 0,
        "Shape gives strength - just like trusses and I-beams.",
        "ভাঁজ করা আঁকাবাঁকা কাগজের সেতু সমতলের চেয়ে বেশি পয়সা ধরে। কেন?", ["ভাঁজ কাগজকে বাঁকার বিরুদ্ধে অনেক শক্ত করে", "ভাঁজে কাগজ ভারী হয়", "পয়সা আঁকাবাঁকা পছন্দ করে", "সমতল কাগজ চুম্বকীয়"],
        "আকারই শক্তি দেয় - ঠিক ট্রাস আর I-বিমের মতো।"),
    mcq("Why does a rolled-up newspaper make a strong post?", ["A tube shape resists bending and squashing well", "Paper turns to steel", "Ink is very strong", "It does not"], 0,
        "Tubes are strong for their weight - bridge towers and bicycle frames use tubes.",
        "পাকানো খবরের কাগজ শক্ত খুঁটি হয় কেন?", ["নল-আকার বাঁকা আর চ্যাপ্টা হওয়া ভালো ঠেকায়", "কাগজ ইস্পাত হয়ে যায়", "কালি খুব শক্ত", "হয় না"],
        "নল ওজনের তুলনায় শক্ত - সেতুর টাওয়ার আর সাইকেলের কাঠামো নল ব্যবহার করে।"),
    mcq("Why do bridge decks get very hot in the summer sun?", ["Dark surfaces absorb lots of light energy as heat", "Cars heat them only", "Bridges are electric", "The river heats them"], 0,
        "Dark colours absorb light; light colours reflect more.",
        "গরমকালের রোদে সেতুর পাটাতন খুব গরম হয় কেন?", ["গাঢ় তল অনেক আলোকশক্তি তাপ হিসেবে শোষণ করে", "শুধু গাড়ি গরম করে", "সেতু বৈদ্যুতিক", "নদী গরম করে"],
        "গাঢ় রং আলো শোষণ করে; হালকা রং বেশি প্রতিফলিত করে।"),
    mcq("Why do you see lightning before you hear its thunder?", ["Light travels much faster than sound", "Thunder starts later", "Ears are slower than eyes", "Clouds block sound"], 0,
        "Count the seconds between flash and bang: every 3 seconds is about 1 km away.",
        "বজ্রের শব্দ শোনার আগে বিদ্যুৎ-চমক দেখা যায় কেন?", ["আলো শব্দের চেয়ে অনেক দ্রুত চলে", "বজ্রের শব্দ পরে শুরু হয়", "কান চোখের চেয়ে ধীর", "মেঘ শব্দ আটকায়"],
        "চমক আর শব্দের মাঝে সেকেন্ড গোনো: প্রতি 3 সেকেন্ডে প্রায় 1 km দূরে।"),
    mcq("Why is it hard to walk on an icy bridge?", ["Ice has very little friction, so shoes slip", "Ice is magnetic", "Ice pushes you up", "Bridges tilt in winter"], 0,
        "In cold countries, grit and salt are spread on bridges to add grip.",
        "বরফে ঢাকা সেতুতে হাঁটা কঠিন কেন?", ["বরফে ঘর্ষণ খুব কম, তাই জুতো পিছলায়", "বরফ চুম্বকীয়", "বরফ উপরে ঠেলে", "শীতে সেতু হেলে যায়"],
        "ঠান্ডা দেশে আঁকড়ে ধরার জন্য সেতুতে কাঁকর আর লবণ ছড়ানো হয়।"),
    mcq("How does a compass help bridge surveyors?", ["Its magnetic needle points north to show direction", "It measures weight", "It measures heat", "It lights the way"], 0,
        "Surveyors use direction and distance to plan exactly where a bridge will go.",
        "কম্পাস সেতু-জরিপকারীদের কীভাবে সাহায্য করে?", ["চুম্বকীয় কাঁটা উত্তর দেখিয়ে দিক বোঝায়", "ওজন মাপে", "তাপ মাপে", "পথ আলোকিত করে"],
        "জরিপকারীরা দিক আর দূরত্ব দিয়ে ঠিক করেন সেতু কোথায় হবে।"),
    mcq("Why does a wheelbarrow make carrying bricks easier?", ["It is a lever with the wheel as the pivot, plus rolling wheels", "It removes the bricks' weight", "It is magnetic", "It pulls the bricks by itself"], 0,
        "The load sits near the wheel, so your lift on the long handles is small.",
        "ঠেলাগাড়ি (হুইলব্যারো) ইট বওয়া সহজ করে কেন?", ["চাকাকে আলম্ব করে এটা একটা লিভার, সঙ্গে গড়ানো চাকা", "ইটের ওজন সরিয়ে দেয়", "চুম্বকীয়", "নিজেই ইট টানে"],
        "বোঝা চাকার কাছে থাকে, তাই লম্বা হাতলে তোমার তোলা কম লাগে।"),
)
