"""Class 4 - Commercials: cost-plus pricing, break-even, freight costs by tonne and kilometre,
stock and re-ordering, contracts and tenders, customer service, branding, trade fairs,
online selling and how transport links grow local business."""
from . import mcq


def _o(r, *alts):
    return list(dict.fromkeys([r, *alts, r + 10, r * 2, r + 1]))[:4]


def costplus(cost, markup, item_en, item_bn):
    add = cost * markup // 100
    r = cost + add
    o = _o(r, add, cost, cost + markup)
    return mcq(f"{item_en} cost Rs {cost:,} to make. The seller adds a {markup}% mark-up. What is the selling price?",
               [f"Rs {x:,}" for x in o], 0,
               f"Mark-up = {markup}% of {cost:,} = Rs {add:,}; price = {cost:,} + {add:,} = Rs {r:,}. This is cost-plus pricing.",
               f"{item_bn} বানাতে {cost:,} টাকা লাগে। বিক্রেতা {markup}% মুনাফা যোগ করেন। বিক্রয়মূল্য কত?",
               [f"{x:,} টাকা" for x in o],
               f"মুনাফা = {cost:,}-এর {markup}% = {add:,} টাকা; দাম = {cost:,} + {add:,} = {r:,} টাকা। একে বলে খরচ-যোগ মূল্যনির্ধারণ।")


def freight(tonnes, km, rate):
    r = tonnes * km * rate
    o = _o(r, tonnes * km, tonnes * rate + km, r // 10)
    return mcq(f"A transporter charges Rs {rate} per tonne per km. What does it cost to carry {tonnes} tonnes of steel {km} km to a bridge site?",
               [f"Rs {x:,}" for x in o], 0,
               f"{tonnes} t x {km} km x Rs {rate} = Rs {r:,}.",
               f"একজন পরিবহণকারী প্রতি টন প্রতি km-এ {rate} টাকা নেন। {tonnes} টন ইস্পাত {km} km দূরে সেতুর জায়গায় নিতে কত খরচ?",
               [f"{x:,} টাকা" for x in o],
               f"{tonnes} টন x {km} km x {rate} টাকা = {r:,} টাকা।")


def breakeven(fixed, price, var):
    each = price - var
    r = fixed // each
    o = _o(r, fixed // price, fixed // var if var else r + 5, r + 50)
    return mcq(f"A tea stall has fixed costs of Rs {fixed:,} a month. Each cup sells for Rs {price} and costs Rs {var} to make. How many cups to break even?",
               [f"{x:,}" for x in o], 0,
               f"Each cup earns {price} - {var} = Rs {each} towards fixed costs; {fixed:,} ÷ {each} = {r:,} cups.",
               f"একটা চায়ের দোকানের মাসিক স্থির খরচ {fixed:,} টাকা। প্রতি কাপ {price} টাকায় বিক্রি হয় আর বানাতে {var} টাকা লাগে। লাভ-লোকসান সমান করতে কত কাপ?",
               [f"{x:,}" for x in o],
               f"প্রতি কাপে স্থির খরচের জন্য {price} - {var} = {each} টাকা ওঠে; {fixed:,} ÷ {each} = {r:,} কাপ।")


def reorder(daily, lead, safety):
    r = daily * lead + safety
    o = _o(r, daily * lead, daily + lead + safety, r - safety * 2 if r > safety * 2 else r + 20)
    return mcq(f"A hardware shop sells {daily} bags of cement a day. New stock takes {lead} days to arrive and it keeps {safety} bags spare. At what stock level should it re-order?",
               [f"{x:,} bags" for x in o], 0,
               f"Re-order level = daily sales x delivery days + safety stock = {daily} x {lead} + {safety} = {r:,} bags.",
               f"একটা হার্ডওয়্যারের দোকান দিনে {daily} বস্তা সিমেন্ট বেচে। নতুন মাল আসতে {lead} দিন লাগে আর {safety} বস্তা বাড়তি রাখে। মজুত কত হলে আবার অর্ডার দেবে?",
               [f"{x:,} বস্তা" for x in o],
               f"পুনঃঅর্ডার স্তর = দৈনিক বিক্রি x ডেলিভারির দিন + নিরাপত্তা-মজুত = {daily} x {lead} + {safety} = {r:,} বস্তা।")


ITEMS = (
    costplus(200, 25, "Clay pots", "মাটির হাঁড়ি"),
    costplus(1200, 20, "Bridge model kits", "সেতুর মডেল-কিট"),
    costplus(80, 50, "Hand-made notebooks", "হাতে তৈরি খাতা"),
    costplus(450, 40, "Bamboo stools", "বাঁশের মোড়া"),
    costplus(2500, 10, "Steel railings (per metre)", "ইস্পাতের রেলিং (প্রতি মিটার)"),
    costplus(60, 30, "Jars of pickle", "আচারের বয়াম"),
    freight(10, 50, 4), freight(20, 120, 3), freight(5, 300, 5), freight(40, 80, 2), freight(15, 200, 3),
    breakeven(6000, 15, 5), breakeven(9000, 20, 8), breakeven(4500, 12, 3), breakeven(12000, 25, 10),
    reorder(20, 5, 30), reorder(35, 4, 50), reorder(12, 7, 20), reorder(50, 3, 100),
    mcq("What is 'cost-plus' pricing?", ["Adding a fixed percentage on top of what it costs to make", "Selling below cost", "Copying a rival's price exactly", "Charging whatever you feel like each day"], 0,
        "It makes sure every sale covers its cost and earns a margin.",
        "'খরচ-যোগ' মূল্যনির্ধারণ কী?", ["তৈরির খরচের উপর একটা নির্দিষ্ট শতাংশ যোগ করা", "খরচের কম দামে বেচা", "প্রতিযোগীর দাম হুবহু নকল", "রোজ ইচ্ছেমতো দাম নেওয়া"],
        "এতে প্রতিটি বিক্রি খরচ মেটায় আর মার্জিন দেয়।"),
    mcq("What is 'competitive pricing'?", ["Setting prices close to what rival sellers charge", "Always charging double", "Giving everything away", "Never changing prices"], 0,
        "If rivals sell at Rs 50, a much higher price may lose customers.",
        "'প্রতিযোগিতামূলক মূল্যনির্ধারণ' কী?", ["প্রতিযোগী বিক্রেতাদের দামের কাছাকাছি দাম রাখা", "সবসময় দ্বিগুণ দাম নেওয়া", "সব বিনামূল্যে দেওয়া", "কখনো দাম না বদলানো"],
        "প্রতিযোগীরা 50 টাকায় বেচলে অনেক বেশি দামে খদ্দের হারাতে পারো।"),
    mcq("What does 'break-even' mean?", ["Sales exactly cover all costs - no profit, no loss", "The shop is broken", "Making a huge profit", "Losing everything"], 0,
        "Every sale after break-even adds profit.",
        "'লাভ-লোকসান সমতা' (ব্রেক-ইভন) মানে কী?", ["বিক্রি ঠিক সব খরচ মেটায় - লাভও নেই, ক্ষতিও নেই", "দোকান ভেঙে গেছে", "বিশাল লাভ", "সব হারানো"],
        "সমতার পরে প্রতিটি বিক্রি লাভ যোগ করে।"),
    mcq("What does 'freight' mean?", ["Goods carried by truck, train, ship or plane", "A scary feeling", "A passenger ticket", "A type of bridge"], 0,
        "Freight costs depend on weight, distance and speed.",
        "'মালবহন' (ফ্রেইট) মানে কী?", ["ট্রাক, ট্রেন, জাহাজ বা বিমানে বয়ে নেওয়া মাল", "ভয়ের অনুভূতি", "যাত্রীর টিকিট", "এক রকম সেতু"],
        "মালবহনের খরচ ওজন, দূরত্ব আর গতির উপর নির্ভর করে।"),
    mcq("Why is rail usually cheaper per tonne-km than road for heavy, long trips?", ["One locomotive pulls many wagons with little friction on steel rails", "Trains use no fuel", "Roads are always closed", "Rail is always faster"], 0,
        "Steel wheels on steel rails roll very easily.",
        "লম্বা, ভারী যাত্রায় প্রতি টন-km-এ রেল সাধারণত সড়কের চেয়ে সস্তা কেন?", ["একটা ইঞ্জিন ইস্পাতের লাইনে কম ঘর্ষণে অনেক ওয়াগন টানে", "ট্রেনে জ্বালানি লাগে না", "রাস্তা সবসময় বন্ধ", "রেল সবসময় দ্রুত"],
        "ইস্পাতের লাইনে ইস্পাতের চাকা খুব সহজে গড়ায়।"),
    mcq("Why do trucks still carry goods for the 'last mile'?", ["Trucks can reach shops and sites that railways cannot", "Trucks are cheapest for everything", "Trains cannot carry goods", "Rules forbid trains"], 0,
        "Rail or ship for the long haul, trucks for the final delivery - that is intermodal transport.",
        "'শেষ মাইলের' জন্য এখনো ট্রাক মাল বয় কেন?", ["রেল যেখানে পৌঁছায় না সেই দোকান আর জায়গায় ট্রাক পৌঁছায়", "সব কিছুর জন্য ট্রাক সস্তা", "ট্রেন মাল বইতে পারে না", "নিয়মে ট্রেন নিষিদ্ধ"],
        "লম্বা পথে রেল বা জাহাজ, শেষ ডেলিভারিতে ট্রাক - একে বলে বহুমাধ্যম পরিবহন।"),
    mcq("What is a 'container' in shipping?", ["A standard-sized steel box that moves easily between ship, train and truck", "A glass jar", "A small parcel", "A fuel tank"], 0,
        "Standard containers made world trade much faster and cheaper.",
        "জাহাজি পরিবহনে 'কনটেনার' কী?", ["মাপমতো ইস্পাতের বাক্স, যা জাহাজ, ট্রেন আর ট্রাকে সহজে বদলানো যায়", "কাচের বয়াম", "ছোট পার্সেল", "জ্বালানির ট্যাংক"],
        "মাপমতো কনটেনার বিশ্ববাণিজ্যকে অনেক দ্রুত আর সস্তা করেছে।"),
    mcq("A truck carries 10 tonnes and a train wagon 60 tonnes. How many trucks equal one wagon?", ["6", "60", "10", "50"], 0,
        "60 ÷ 10 = 6 trucks - and 6 drivers, 6 engines, much more fuel.",
        "একটা ট্রাক 10 টন আর একটা রেল-ওয়াগন 60 টন বয়। কতগুলো ট্রাক একটা ওয়াগনের সমান?", ["6", "60", "10", "50"],
        "60 ÷ 10 = 6টি ট্রাক - আর 6 জন চালক, 6টি ইঞ্জিন, অনেক বেশি জ্বালানি।"),
    mcq("Why do trucks often return empty after a delivery, and why is that costly?", ["No goods to carry back, but fuel and wages are still paid", "Trucks prefer being empty", "It is cheaper empty", "It never happens"], 0,
        "Smart firms find a return load to cut costs - called backhauling.",
        "ডেলিভারির পরে ট্রাক প্রায়ই খালি ফেরে কেন, আর তা খরচসাপেক্ষ কেন?", ["ফেরার মাল নেই, কিন্তু জ্বালানি আর মজুরি তবু দিতে হয়", "ট্রাক খালি থাকতে ভালোবাসে", "খালিতে সস্তা", "কখনো হয় না"],
        "বুদ্ধিমান সংস্থা খরচ কমাতে ফেরার মাল খোঁজে - একে বলে ব্যাকহলিং।"),
    mcq("What is 'stock' (inventory)?", ["Goods a business holds ready to sell or use", "Soup made from bones", "A type of share only", "A loan"], 0,
        "Too little stock loses sales; too much ties up cash.",
        "'মজুত' (ইনভেন্টরি) কী?", ["বেচা বা ব্যবহারের জন্য ব্যবসার রাখা মাল", "হাড়ের স্যুপ", "শুধু এক রকম শেয়ার", "ঋণ"],
        "কম মজুতে বিক্রি হারায়; বেশি মজুতে টাকা আটকে থাকে।"),
    mcq("Why is having far too much stock a problem?", ["Money is tied up and goods may spoil or go out of fashion", "Shops love full shelves only", "It is never a problem", "It makes stock cheaper"], 0,
        "Cement can harden, food can spoil and styles can change.",
        "অনেক বেশি মজুত থাকা সমস্যা কেন?", ["টাকা আটকে থাকে আর মাল নষ্ট বা পুরোনো ফ্যাশন হতে পারে", "দোকান শুধু ভরা তাক ভালোবাসে", "কখনো সমস্যা নয়", "মজুত সস্তা হয়"],
        "সিমেন্ট জমে যেতে পারে, খাবার পচতে পারে আর রুচি বদলাতে পারে।"),
    mcq("What is 'safety stock'?", ["Extra stock kept in case of late deliveries or sudden demand", "Stock locked in a safe", "Stock of helmets only", "Broken stock"], 0,
        "A small buffer prevents running out.",
        "'নিরাপত্তা-মজুত' কী?", ["দেরিতে ডেলিভারি বা হঠাৎ চাহিদার জন্য রাখা বাড়তি মাল", "সিন্দুকে রাখা মাল", "শুধু হেলমেটের মজুত", "ভাঙা মাল"],
        "ছোট একটা বাড়তি ভান্ডার মাল ফুরোতে দেয় না।"),
    mcq("What is a 'penalty clause' in a contract?", ["A rule that the builder pays money if work is late", "A football rule", "A free bonus", "A tax refund"], 0,
        "It encourages work to finish on time.",
        "চুক্তিতে 'জরিমানার ধারা' কী?", ["কাজ দেরি হলে নির্মাতাকে টাকা দিতে হবে এমন নিয়ম", "ফুটবলের নিয়ম", "বিনামূল্যের বোনাস", "করের ফেরত"],
        "এটা সময়মতো কাজ শেষ করতে উৎসাহ দেয়।"),
    mcq("A contract has a Rs 5,000-a-day late penalty. The bridge is 4 days late. Penalty?", ["Rs 20,000", "Rs 5,004", "Rs 9,000", "Rs 1,250"], 0,
        "5,000 x 4 = 20,000.",
        "একটা চুক্তিতে দেরির জন্য দিনে 5,000 টাকা জরিমানা। সেতু 4 দিন দেরিতে শেষ হলো। জরিমানা কত?", ["20,000 টাকা", "5,004 টাকা", "9,000 টাকা", "1,250 টাকা"],
        "5,000 x 4 = 20,000।"),
    mcq("What is a 'tender'?", ["A formal offer to do a job at a stated price", "Soft meat", "A train car", "A type of bolt"], 0,
        "Companies submit tenders; the client picks the best safe, fair offer.",
        "'দরপত্র' (টেন্ডার) কী?", ["নির্দিষ্ট দামে কাজ করার আনুষ্ঠানিক প্রস্তাব", "নরম মাংস", "রেলের কামরা", "এক রকম বল্টু"],
        "কোম্পানিগুলো দরপত্র দেয়; গ্রাহক সেরা নিরাপদ, ন্যায্য প্রস্তাব বাছেন।"),
    mcq("What is a 'quotation' (quote)?", ["A price a seller offers for goods or work before you agree", "A famous saying only", "A bill already paid", "A tax"], 0,
        "Get several quotes to compare value.",
        "'দরপ্রস্তাব' (কোটেশন) কী?", ["রাজি হওয়ার আগে বিক্রেতার দেওয়া মাল বা কাজের দাম", "শুধু বিখ্যাত উক্তি", "আগেই মেটানো বিল", "কর"],
        "মূল্য তুলনা করতে কয়েকটা দরপ্রস্তাব নাও।"),
    mcq("A customer complains their new torch does not work. What is the best response?", ["Listen politely, apologise and replace or fix it", "Argue loudly", "Ignore them", "Blame the customer"], 0,
        "Solving problems fairly protects the shop's reputation.",
        "একজন খদ্দের অভিযোগ করলেন তাঁর নতুন টর্চ চলছে না। সেরা উত্তর কী?", ["ভদ্রভাবে শোনো, দুঃখপ্রকাশ করো আর বদলে দাও বা সারাও", "জোরে তর্ক করো", "উপেক্ষা করো", "খদ্দেরকে দোষ দাও"],
        "ন্যায্যভাবে সমস্যার সমাধান দোকানের সুনাম রক্ষা করে।"),
    mcq("What is a 'logo'?", ["A small design or symbol that represents a business", "A long contract", "A loan", "A warehouse"], 0,
        "Logos help customers spot a brand quickly.",
        "'লোগো' কী?", ["একটা ব্যবসাকে বোঝায় এমন ছোট নকশা বা প্রতীক", "লম্বা চুক্তি", "ঋণ", "গুদাম"],
        "লোগো খদ্দেরকে দ্রুত ব্র্যান্ড চিনতে সাহায্য করে।"),
    mcq("What is a 'trade fair'?", ["An event where businesses show products to buyers", "A fair game", "A tax office", "A bridge opening"], 0,
        "Construction trade fairs show new machines and materials.",
        "'বাণিজ্যমেলা' কী?", ["যে অনুষ্ঠানে ব্যবসাগুলো ক্রেতাদের পণ্য দেখায়", "ন্যায্য খেলা", "কর-অফিস", "সেতুর উদ্বোধন"],
        "নির্মাণ-বাণিজ্যমেলায় নতুন যন্ত্র আর উপাদান দেখানো হয়।"),
    mcq("Why do craftspeople bring goods to a big city fair?", ["They meet many more buyers than in their village", "Fairs are always free", "To avoid customers", "No reason"], 0,
        "A new bridge or rail link can make reaching fairs far easier.",
        "কারিগরেরা বড় শহরের মেলায় মাল নিয়ে আসেন কেন?", ["গ্রামের চেয়ে অনেক বেশি ক্রেতার সঙ্গে দেখা হয়", "মেলা সবসময় বিনামূল্যে", "খদ্দের এড়াতে", "কোনো কারণ নেই"],
        "নতুন সেতু বা রেলপথ মেলায় পৌঁছানো অনেক সহজ করে।"),
    mcq("What is 'e-commerce'?", ["Buying and selling over the internet", "Electric cars only", "A type of bridge", "Selling only in markets"], 0,
        "Small sellers can now reach customers across the country.",
        "'ই-কমার্স' কী?", ["ইন্টারনেটে কেনাবেচা", "শুধু বৈদ্যুতিক গাড়ি", "এক রকম সেতু", "শুধু বাজারে বেচা"],
        "ছোট বিক্রেতারা এখন দেশজুড়ে খদ্দেরের কাছে পৌঁছাতে পারেন।"),
    mcq("Why do online shops show photos and honest descriptions?", ["Customers cannot touch goods, so they rely on clear information", "Photos are required for tax", "To hide faults", "No reason"], 0,
        "Misleading listings lead to returns and bad reviews.",
        "অনলাইন দোকান ছবি আর সৎ বিবরণ দেখায় কেন?", ["খদ্দের মাল ছুঁতে পারেন না, তাই স্পষ্ট তথ্যের উপর ভরসা করেন", "করের জন্য ছবি বাধ্যতামূলক", "ত্রুটি লুকাতে", "কোনো কারণ নেই"],
        "বিভ্রান্তিকর বিবরণে ফেরত আর খারাপ মতামত আসে।"),
    mcq("What is a 'return policy'?", ["Rules for giving back a product for a refund or exchange", "A trip home", "A tax rule", "A loan repayment"], 0,
        "A clear return policy builds customer trust.",
        "'ফেরত-নীতি' কী?", ["টাকা ফেরত বা বদলের জন্য পণ্য ফেরানোর নিয়ম", "বাড়ি ফেরা", "করের নিয়ম", "ঋণ শোধ"],
        "স্পষ্ট ফেরত-নীতি খদ্দেরের আস্থা গড়ে।"),
    mcq("What is 'cash on delivery'?", ["Paying when the parcel arrives", "Paying a year later", "Never paying", "Paying the driver a bribe"], 0,
        "It reassures new customers who do not yet trust a seller.",
        "'ক্যাশ অন ডেলিভারি' কী?", ["পার্সেল পৌঁছালে দাম দেওয়া", "এক বছর পরে দাম দেওয়া", "কখনো না দেওয়া", "চালককে ঘুষ দেওয়া"],
        "যে নতুন খদ্দের এখনো বিক্রেতাকে বিশ্বাস করেন না, তাঁকে এটা আশ্বস্ত করে।"),
    mcq("What does a 'delivery time promise' mean for a seller?", ["They must plan stock and transport so goods arrive on time", "Nothing", "They can deliver whenever", "Customers pay double"], 0,
        "Missed promises cost customers.",
        "বিক্রেতার জন্য 'ডেলিভারির সময়ের প্রতিশ্রুতি' মানে কী?", ["মাল সময়মতো পৌঁছাতে মজুত আর পরিবহন পরিকল্পনা করতে হবে", "কিছুই না", "যখন খুশি পৌঁছানো যায়", "খদ্দের দ্বিগুণ দেন"],
        "প্রতিশ্রুতি ভাঙলে খদ্দের হারায়।"),
    mcq("A courier delivers 120 parcels a day with 4 vans. How many parcels per van?", ["30", "40", "24", "480"], 0,
        "120 ÷ 4 = 30.",
        "একটা কুরিয়ার 4টি ভ্যানে দিনে 120টি পার্সেল পৌঁছায়। প্রতি ভ্যানে কয়টি?", ["30", "40", "24", "480"],
        "120 ÷ 4 = 30।"),
    mcq("A new bridge cuts a delivery route from 60 km to 20 km. Fuel costs Rs 10 per km. Saving per trip?", ["Rs 400", "Rs 200", "Rs 600", "Rs 40"], 0,
        "40 km saved x Rs 10 = Rs 400 every trip.",
        "একটা নতুন সেতু ডেলিভারির পথ 60 km থেকে 20 km করল। জ্বালানি km-প্রতি 10 টাকা। প্রতি যাত্রায় সাশ্রয়?", ["400 টাকা", "200 টাকা", "600 টাকা", "40 টাকা"],
        "40 km বাঁচল x 10 টাকা = প্রতি যাত্রায় 400 টাকা।"),
    mcq("Using that Rs 400 saving, a firm makes 2 trips a day for 25 days. Monthly saving?", ["Rs 20,000", "Rs 10,000", "Rs 800", "Rs 1,000"], 0,
        "400 x 2 x 25 = 20,000. Bridges boost business!",
        "সেই 400 টাকার সাশ্রয়ে একটা সংস্থা 25 দিন দিনে 2বার যায়। মাসিক সাশ্রয়?", ["20,000 টাকা", "10,000 টাকা", "800 টাকা", "1,000 টাকা"],
        "400 x 2 x 25 = 20,000। সেতু ব্যবসা বাড়ায়!"),
    mcq("What is a 'distribution centre'?", ["A big warehouse that sorts and sends goods to many shops", "A shop for one customer", "A school", "A bank"], 0,
        "Goods arrive in bulk and leave in smaller mixed loads.",
        "'বণ্টন-কেন্দ্র' কী?", ["বড় গুদাম, যা মাল বাছাই করে বহু দোকানে পাঠায়", "এক খদ্দেরের দোকান", "স্কুল", "ব্যাংক"],
        "মাল একসঙ্গে আসে আর ছোট মিশ্র বোঝায় বেরোয়।"),
    mcq("Why are distribution centres often near highway junctions?", ["Trucks can reach many towns quickly from there", "Land is magic there", "For the noise", "No reason"], 0,
        "Location decides how fast and cheaply goods move.",
        "বণ্টন-কেন্দ্র প্রায়ই মহাসড়কের সংযোগস্থলের কাছে হয় কেন?", ["সেখান থেকে ট্রাক দ্রুত অনেক শহরে পৌঁছায়", "সেখানের জমি জাদুর", "শব্দের জন্য", "কোনো কারণ নেই"],
        "অবস্থান ঠিক করে মাল কত দ্রুত আর সস্তায় চলবে।"),
    mcq("What is 'perishable' cargo?", ["Goods that spoil quickly, like fish, milk and flowers", "Steel beams", "Bricks", "Coal"], 0,
        "Perishables need fast transport, sometimes refrigerated.",
        "'পচনশীল' মাল কী?", ["যে মাল দ্রুত নষ্ট হয়, যেমন মাছ, দুধ আর ফুল", "ইস্পাতের বিম", "ইট", "কয়লা"],
        "পচনশীল মালের দ্রুত পরিবহন লাগে, কখনো হিমায়িত।"),
    mcq("A fisherman's catch spoils in 6 hours. The old road takes 5 hours to market; a new bridge cuts it to 2. Why does this matter?", ["Fish arrives fresh, sells for more and less is wasted", "It does not matter", "Fish swim faster", "Markets close at night"], 0,
        "Faster links raise incomes for farmers and fishers.",
        "একজন জেলের মাছ 6 ঘণ্টায় নষ্ট হয়। পুরোনো রাস্তায় বাজারে যেতে 5 ঘণ্টা; নতুন সেতুতে 2 ঘণ্টা। এর গুরুত্ব কী?", ["মাছ টাটকা পৌঁছায়, বেশি দামে বিকোয় আর কম নষ্ট হয়", "গুরুত্ব নেই", "মাছ দ্রুত সাঁতরায়", "রাতে বাজার বন্ধ"],
        "দ্রুত যোগাযোগ চাষি আর জেলেদের আয় বাড়ায়।"),
    mcq("What is a 'cold chain'?", ["Keeping goods cold all the way from producer to buyer", "A chain made of ice", "A winter sale", "A bicycle chain"], 0,
        "Vaccines, milk and frozen food need a cold chain.",
        "'শীতল শৃঙ্খল' (কোল্ড চেইন) কী?", ["উৎপাদক থেকে ক্রেতা পর্যন্ত মাল ঠান্ডা রাখা", "বরফের শিকল", "শীতের সেল", "সাইকেলের চেন"],
        "টিকা, দুধ আর হিমায়িত খাবারে শীতল শৃঙ্খল লাগে।"),
    mcq("What is a 'middleman' in trade?", ["Someone who buys from producers and sells to shops or customers", "A person standing in the middle of a bridge", "A referee", "A bank manager"], 0,
        "Middlemen add services like transport and storage, but too many raise prices.",
        "বাণিজ্যে 'মধ্যস্বত্বভোগী' কে?", ["যে উৎপাদকের থেকে কিনে দোকান বা খদ্দেরকে বেচে", "সেতুর মাঝখানে দাঁড়ানো লোক", "রেফারি", "ব্যাংক-ম্যানেজার"],
        "মধ্যস্বত্বভোগীরা পরিবহন আর মজুতের মতো পরিষেবা যোগ করে, কিন্তু বেশি হলে দাম বাড়ে।"),
    mcq("How can better roads and bridges help farmers get fairer prices?", ["They can reach more buyers directly and compare prices", "Roads set prices", "Bridges buy crops", "They cannot"], 0,
        "More choice of buyers means more bargaining power.",
        "ভালো রাস্তা আর সেতু চাষিদের ন্যায্য দাম পেতে কীভাবে সাহায্য করে?", ["সরাসরি বেশি ক্রেতার কাছে পৌঁছে দাম তুলনা করতে পারেন", "রাস্তা দাম ঠিক করে", "সেতু ফসল কেনে", "পারে না"],
        "বেশি ক্রেতা মানে বেশি দরাদরির ক্ষমতা।"),
    mcq("What is 'demand forecasting'?", ["Estimating how much customers will want in the future", "Predicting the weather only", "Guessing lottery numbers", "Counting coins"], 0,
        "Shops use past sales and seasons to plan stock.",
        "'চাহিদার পূর্বাভাস' কী?", ["ভবিষ্যতে খদ্দের কতটা চাইবেন তার আন্দাজ", "শুধু আবহাওয়ার পূর্বাভাস", "লটারির নম্বর আন্দাজ", "পয়সা গোনা"],
        "দোকান পুরোনো বিক্রি আর মরসুম দেখে মজুতের পরিকল্পনা করে।"),
    mcq("A sweet shop sold 200 boxes last Diwali, and sales grow about 10% a year. About how many to prepare this Diwali?", ["220", "210", "200", "300"], 0,
        "10% of 200 = 20; 200 + 20 = 220.",
        "একটা মিষ্টির দোকান গত দিওয়ালিতে 200 বাক্স বেচেছিল, আর বিক্রি বছরে প্রায় 10% বাড়ে। এ বছর প্রায় কত বানাবে?", ["220", "210", "200", "300"],
        "200-এর 10% = 20; 200 + 20 = 220।"),
    mcq("Why do umbrella sellers order lots of stock before the monsoon?", ["Demand rises sharply in the rainy season", "Umbrellas are cheaper in rain", "Rules force them", "Umbrellas melt in summer"], 0,
        "Seasonal demand must be planned ahead.",
        "বর্ষার আগে ছাতা-বিক্রেতারা অনেক মাল অর্ডার করেন কেন?", ["বর্ষায় চাহিদা হঠাৎ অনেক বাড়ে", "বৃষ্টিতে ছাতা সস্তা", "নিয়মে বাধ্য", "গরমে ছাতা গলে"],
        "মরসুমি চাহিদার পরিকল্পনা আগে থেকে করতে হয়।"),
    mcq("What is a 'unique selling point' (USP)?", ["What makes your product different and better than rivals'", "A single sale", "A price tag", "A shop sign"], 0,
        "A footbridge kit that needs no tools could be a USP.",
        "'অনন্য বিক্রয়-বৈশিষ্ট্য' (ইউএসপি) কী?", ["যা তোমার পণ্যকে প্রতিযোগীদের চেয়ে আলাদা আর ভালো করে", "একটা মাত্র বিক্রি", "দামের ট্যাগ", "দোকানের সাইনবোর্ড"],
        "যন্ত্র ছাড়াই জোড়া যায় এমন হাঁটার সেতুর কিট একটা ইউএসপি হতে পারে।"),
    mcq("What is 'after-sales service'?", ["Help, repairs and support after a product is bought", "Selling something again", "A second shop", "A discount before buying"], 0,
        "Bridge builders inspect and maintain bridges after handing them over.",
        "'বিক্রয়-পরবর্তী পরিষেবা' কী?", ["কেনার পরে সাহায্য, মেরামত আর সহায়তা", "আবার কিছু বেচা", "দ্বিতীয় দোকান", "কেনার আগের ছাড়"],
        "সেতু-নির্মাতারা হস্তান্তরের পরেও সেতু পরিদর্শন আর রক্ষণাবেক্ষণ করেন।"),
    mcq("What is a 'maintenance contract' for a bridge?", ["An agreement to inspect and repair the bridge regularly for years", "A one-day paint job", "A toll ticket", "A loan form"], 0,
        "Regular care is far cheaper than rebuilding a failed bridge.",
        "সেতুর 'রক্ষণাবেক্ষণ-চুক্তি' কী?", ["বছরের পর বছর নিয়মিত পরিদর্শন আর মেরামতের সমঝোতা", "এক দিনের রঙের কাজ", "টোলের টিকিট", "ঋণের ফর্ম"],
        "নিয়মিত যত্ন ভেঙে পড়া সেতু আবার বানানোর চেয়ে অনেক সস্তা।"),
    mcq("What does 'quality standard' mean for steel sold to bridge builders?", ["It meets agreed tests for strength and safety", "It looks shiny", "It is the cheapest", "It is the heaviest"], 0,
        "Certified materials come with test certificates.",
        "সেতু-নির্মাতাদের বেচা ইস্পাতের জন্য 'মানের মাপকাঠি' মানে কী?", ["শক্তি আর নিরাপত্তার জন্য সম্মত পরীক্ষায় উত্তীর্ণ", "চকচকে দেখায়", "সবচেয়ে সস্তা", "সবচেয়ে ভারী"],
        "প্রত্যয়িত উপাদানের সঙ্গে পরীক্ষার শংসাপত্র থাকে।"),
    mcq("What is a 'sample' in business?", ["A small amount given so buyers can try before ordering", "A large order", "A refund", "A fine"], 0,
        "Builders test cement samples before buying in bulk.",
        "ব্যবসায় 'নমুনা' কী?", ["অর্ডারের আগে পরখ করার জন্য দেওয়া অল্প পরিমাণ", "বড় অর্ডার", "টাকা ফেরত", "জরিমানা"],
        "নির্মাতারা একসঙ্গে বেশি কেনার আগে সিমেন্টের নমুনা পরীক্ষা করেন।"),
    mcq("What is 'market share'?", ["The part of all sales in a market that one business has", "Shares in a stock market only", "Space in a market stall", "A shared lunch"], 0,
        "If 3 of every 10 bridges are built by one firm, its share is 30%.",
        "'বাজারের অংশ' (মার্কেট শেয়ার) কী?", ["একটা বাজারের মোট বিক্রির যে অংশ একটা ব্যবসার", "শুধু শেয়ারবাজারের শেয়ার", "বাজারের স্টলের জায়গা", "ভাগ করা দুপুরের খাবার"],
        "প্রতি 10টি সেতুর 3টি একটা সংস্থা বানালে তার অংশ 30%।"),
    mcq("A town has 200 sales of bicycles a month; your shop sells 50. What is your market share?", ["25%", "50%", "20%", "4%"], 0,
        "50 ÷ 200 x 100 = 25%.",
        "একটা শহরে মাসে 200টি সাইকেল বিক্রি হয়; তোমার দোকান বেচে 50টি। তোমার বাজার-অংশ কত?", ["25%", "50%", "20%", "4%"],
        "50 ÷ 200 x 100 = 25%।"),
    mcq("What is 'advertising budget'?", ["Money planned for promoting products", "Money for building only", "A tax", "A loan"], 0,
        "Track which adverts bring customers to spend it wisely.",
        "'বিজ্ঞাপন-বাজেট' কী?", ["পণ্যের প্রচারের জন্য পরিকল্পিত টাকা", "শুধু নির্মাণের টাকা", "কর", "ঋণ"],
        "কোন বিজ্ঞাপন খদ্দের আনে তা দেখে বুদ্ধি করে খরচ করো।"),
    mcq("Which advert is most likely to reach farmers in a rural area?", ["Posters at the local market and radio", "A city billboard far away", "An advert on a plane", "A magazine in another language"], 0,
        "Pick channels your target customers actually see.",
        "গ্রামাঞ্চলের চাষিদের কাছে কোন বিজ্ঞাপন পৌঁছানোর সম্ভাবনা সবচেয়ে বেশি?", ["স্থানীয় হাটের পোস্টার আর রেডিও", "দূরের শহরের বিলবোর্ড", "বিমানের বিজ্ঞাপন", "অন্য ভাষার পত্রিকা"],
        "লক্ষ্য খদ্দের যে মাধ্যম আসলে দেখেন, সেটাই বাছো।"),
    mcq("What is 'honest advertising'?", ["Making only true claims about a product", "Saying anything to sell", "Hiding the price", "Copying rivals' adverts"], 0,
        "False claims break the law and destroy trust.",
        "'সৎ বিজ্ঞাপন' কী?", ["পণ্য নিয়ে শুধু সত্যি দাবি করা", "বেচার জন্য যা খুশি বলা", "দাম লুকানো", "প্রতিযোগীর বিজ্ঞাপন নকল"],
        "মিথ্যা দাবি আইন ভাঙে আর আস্থা নষ্ট করে।"),
    mcq("A cement advert says 'never cracks, ever'. Why should a builder be careful?", ["No material is perfect - check tests and standards, not just slogans", "Adverts are always true", "Cement cannot crack", "Builders never read adverts"], 0,
        "Engineers trust test data, not marketing words.",
        "একটা সিমেন্টের বিজ্ঞাপন বলছে 'কখনো ফাটে না'। নির্মাতার সাবধান হওয়া উচিত কেন?", ["কোনো উপাদান নিখুঁত নয় - শুধু স্লোগান নয়, পরীক্ষা আর মান দেখো", "বিজ্ঞাপন সবসময় সত্যি", "সিমেন্ট ফাটতে পারে না", "নির্মাতারা কখনো বিজ্ঞাপন পড়েন না"],
        "প্রকৌশলীরা বিপণনের কথায় নয়, পরীক্ষার তথ্যে ভরসা করেন।"),
    mcq("What does 'MRP' printed on a packet mean in India?", ["Maximum Retail Price - shops must not charge more", "Minimum price", "Manufacturer's profit", "A brand name"], 0,
        "Shops may sell below MRP but never above it.",
        "ভারতে প্যাকেটে ছাপা 'এমআরপি' মানে কী?", ["সর্বোচ্চ খুচরো মূল্য - দোকান এর বেশি নিতে পারে না", "সর্বনিম্ন দাম", "নির্মাতার লাভ", "ব্র্যান্ডের নাম"],
        "দোকান এমআরপি-র কমে বেচতে পারে, কিন্তু কখনো বেশিতে নয়।"),
    mcq("A shopkeeper charges Rs 25 for a drink with MRP Rs 20. What should a customer do?", ["Politely point out the MRP; report it if they refuse", "Pay double happily", "Steal the drink", "Shout at other customers"], 0,
        "Consumer laws protect buyers from overcharging.",
        "একজন দোকানদার এমআরপি 20 টাকার পানীয়ে 25 টাকা নিচ্ছেন। খদ্দেরের কী করা উচিত?", ["ভদ্রভাবে এমআরপি দেখাও; না মানলে অভিযোগ করো", "খুশি মনে দ্বিগুণ দাও", "পানীয় চুরি করো", "অন্য খদ্দেরদের উপর চেঁচাও"],
        "ক্রেতা-সুরক্ষা আইন বাড়তি দাম থেকে ক্রেতাদের রক্ষা করে।"),
    mcq("Why do bridge users count as 'customers' of the bridge?", ["They use its service and often pay tolls or taxes for it", "They do not", "Only trucks count", "Only the builder counts"], 0,
        "Good bridges serve their users safely and reliably.",
        "সেতুর ব্যবহারকারীরা সেতুর 'খদ্দের' কেন?", ["তাঁরা তার পরিষেবা নেন আর প্রায়ই টোল বা কর দেন", "নন", "শুধু ট্রাক গোনা হয়", "শুধু নির্মাতা গোনা হয়"],
        "ভালো সেতু ব্যবহারকারীদের নিরাপদে আর নির্ভরযোগ্যভাবে পরিষেবা দেয়।"),
    mcq("What is a 'partnership' business?", ["A business owned by two or more people who share profits", "A business with no owners", "A government department", "A school club only"], 0,
        "Partners share the work, the money and the risks.",
        "'অংশীদারি' ব্যবসা কী?", ["দুই বা বেশি মানুষের মালিকানার ব্যবসা, যাঁরা লাভ ভাগ করেন", "মালিকহীন ব্যবসা", "সরকারি দপ্তর", "শুধু স্কুলের ক্লাব"],
        "অংশীদারেরা কাজ, টাকা আর ঝুঁকি ভাগ করেন।"),
    mcq("Two partners invest Rs 3,000 and Rs 1,000 and agree to share profit in that ratio. Profit is Rs 800. What does the first get?", ["Rs 600", "Rs 400", "Rs 200", "Rs 750"], 0,
        "Ratio 3 : 1 = 4 parts; 800 ÷ 4 = 200; 3 x 200 = 600.",
        "দুই অংশীদার 3,000 আর 1,000 টাকা বিনিয়োগ করে সেই অনুপাতে লাভ ভাগের কথা দিলেন। লাভ 800 টাকা। প্রথমজন কত পাবেন?", ["600 টাকা", "400 টাকা", "200 টাকা", "750 টাকা"],
        "অনুপাত 3 : 1 = 4 ভাগ; 800 ÷ 4 = 200; 3 x 200 = 600।"),
    mcq("What is 'wastage' in a business?", ["Materials lost or spoiled that cannot be sold or used", "Profit", "Wages", "Tax"], 0,
        "Cutting steel carefully reduces off-cut wastage.",
        "ব্যবসায় 'অপচয়' কী?", ["যে উপাদান হারায় বা নষ্ট হয় আর বেচা বা ব্যবহার করা যায় না", "লাভ", "মজুরি", "কর"],
        "সাবধানে ইস্পাত কাটলে কাটা-টুকরোর অপচয় কমে।"),
    mcq("A builder orders 100 m of cable and 8 m is wasted in cutting. What percent is wasted?", ["8%", "92%", "80%", "0.8%"], 0,
        "8 out of 100 = 8%.",
        "একজন নির্মাতা 100 m তার অর্ডার করলেন আর কাটতে গিয়ে 8 m নষ্ট হলো। কত শতাংশ অপচয়?", ["8%", "92%", "80%", "0.8%"],
        "100-এর মধ্যে 8 = 8%।"),
    mcq("Why do builders order slightly more material than the exact plan shows?", ["To cover wastage, breakage and small changes", "To waste money", "To sell it on the street", "No reason"], 0,
        "A small allowance (often 5-10%) avoids work stopping while waiting for more.",
        "নির্মাতারা পরিকল্পনার ঠিক মাপের চেয়ে একটু বেশি উপাদান অর্ডার করেন কেন?", ["অপচয়, ভাঙা আর ছোট পরিবর্তন সামলাতে", "টাকা নষ্ট করতে", "রাস্তায় বেচতে", "কোনো কারণ নেই"],
        "ছোট বাড়তি (প্রায়ই 5-10%) আরও মালের অপেক্ষায় কাজ থামা আটকায়।"),
    mcq("What is 'customer feedback'?", ["Comments from customers about what they liked or did not", "Food for customers", "A refund", "A delivery"], 0,
        "Feedback helps businesses improve.",
        "'খদ্দেরের প্রতিক্রিয়া' কী?", ["খদ্দেরের মন্তব্য, কী ভালো লেগেছে আর কী লাগেনি", "খদ্দেরের খাবার", "টাকা ফেরত", "ডেলিভারি"],
        "প্রতিক্রিয়া ব্যবসাকে উন্নত হতে সাহায্য করে।"),
    mcq("Players say a game level is too hard. What would a smart game business do?", ["Study the feedback and adjust or add help", "Ignore all players", "Make it harder", "Delete the game"], 0,
        "Listening to users - like adding the Help screen and Academy - makes better products.",
        "খেলোয়াড়েরা বলছেন একটা লেভেল খুব কঠিন। বুদ্ধিমান গেম-ব্যবসা কী করবে?", ["প্রতিক্রিয়া বুঝে বদলাবে বা সাহায্য যোগ করবে", "সব খেলোয়াড়কে উপেক্ষা", "আরও কঠিন করবে", "খেলা মুছে দেবে"],
        "ব্যবহারকারীদের কথা শোনা - যেমন সাহায্য-পর্দা আর অ্যাকাডেমি যোগ করা - ভালো পণ্য তৈরি করে।"),
    mcq("Why do businesses near a new bridge often grow?", ["More people and goods pass by, bringing more customers", "Bridges pay shops directly", "Rents fall to zero", "They do not"], 0,
        "Petrol pumps, eateries and shops spring up along new routes.",
        "নতুন সেতুর কাছের ব্যবসা প্রায়ই বাড়ে কেন?", ["বেশি মানুষ আর মাল পাশ দিয়ে যায়, বেশি খদ্দের আসে", "সেতু সরাসরি দোকানকে টাকা দেয়", "ভাড়া শূন্যে নামে", "বাড়ে না"],
        "নতুন পথে পেট্রল পাম্প, খাবারের দোকান আর অন্য দোকান গজিয়ে ওঠে।"),
    mcq("What is 'logistics cost' as part of a product's price?", ["The cost of storing and moving it to the customer", "The factory's paint", "The shop's music", "The logo design"], 0,
        "Cheaper transport links lower prices for everyone.",
        "পণ্যের দামের অংশ হিসেবে 'লজিস্টিকস খরচ' কী?", ["খদ্দের পর্যন্ত মাল রাখা আর সরানোর খরচ", "কারখানার রং", "দোকানের গান", "লোগোর নকশা"],
        "সস্তা যোগাযোগ সবার জন্য দাম কমায়।"),
    costplus(300, 15, "Brass door handles", "পিতলের দরজার হাতল"),
    costplus(900, 35, "Folding ladders", "ভাঁজ করা মই"),
    costplus(40, 25, "Paper kites", "কাগজের ঘুড়ি"),
    freight(8, 150, 4), freight(25, 60, 5), freight(12, 400, 2),
    breakeven(3000, 10, 4), breakeven(15000, 30, 15), breakeven(8000, 18, 8),
    reorder(15, 6, 25), reorder(40, 2, 60), reorder(8, 10, 15),
    mcq("A tea stall pays Rs 5,000 rent and Rs 3 of milk and leaves per cup. Which cost is fixed?", ["The Rs 5,000 rent", "The Rs 3 per cup", "Both are fixed", "Neither"], 0,
        "Rent stays the same however many cups are sold; ingredients rise with every cup (variable).",
        "একটা চায়ের দোকান 5,000 টাকা ভাড়া দেয় আর প্রতি কাপে 3 টাকার দুধ-পাতা লাগে। কোন খরচটা স্থির?", ["5,000 টাকার ভাড়া", "কাপপ্রতি 3 টাকা", "দুটোই স্থির", "কোনোটাই না"],
        "যত কাপই বিক্রি হোক ভাড়া একই থাকে; উপাদান প্রতিটি কাপে বাড়ে (পরিবর্তনশীল)।"),
    mcq("A bakery doubles the loaves it bakes. Which cost roughly doubles too?", ["Flour, yeast and gas for baking", "The shop's monthly rent", "The yearly licence fee", "The sign above the door"], 0,
        "Costs that grow with output are variable costs.",
        "একটা বেকারি দ্বিগুণ পাউরুটি সেঁকল। কোন খরচও মোটামুটি দ্বিগুণ হবে?", ["ময়দা, ইস্ট আর সেঁকার গ্যাস", "দোকানের মাসিক ভাড়া", "বার্ষিক লাইসেন্স ফি", "দরজার উপরের সাইনবোর্ড"],
        "উৎপাদনের সঙ্গে বাড়া খরচই পরিবর্তনশীল খরচ।"),
    mcq("Why should a bridge contract be written down and signed, not just spoken?", ["Both sides know exactly what was agreed if a dispute comes up", "Writing makes it cheaper", "Spoken deals are illegal everywhere", "Signatures make bridges stronger"], 0,
        "A clear written contract avoids arguments about work, price and dates.",
        "সেতুর চুক্তি মুখে না বলে লিখে সই করা উচিত কেন?", ["বিবাদ হলে দুই পক্ষই ঠিক কী সম্মত হয়েছিল জানে", "লিখলে সস্তা হয়", "মুখের চুক্তি সব জায়গায় বেআইনি", "সইয়ে সেতু শক্ত হয়"],
        "স্পষ্ট লিখিত চুক্তি কাজ, দাম আর তারিখ নিয়ে তর্ক এড়ায়।"),
    mcq("Two shops sell the same rice at the same price. One has friendly, helpful staff. Which will customers usually choose?", ["The friendly, helpful shop", "The rude shop", "Neither ever", "Whichever is further away"], 0,
        "When prices match, service decides.",
        "দুটো দোকান একই চাল একই দামে বেচে। একটায় বন্ধুসুলভ, সাহায্যকারী কর্মী। খদ্দেরেরা সাধারণত কোনটা বাছেন?", ["বন্ধুসুলভ, সাহায্যকারী দোকান", "রূঢ় দোকান", "কোনোটাই কখনো না", "যেটা বেশি দূরে"],
        "দাম সমান হলে পরিষেবাই ঠিক করে।"),
    mcq("Why might people pay a little more for a well-known brand of helmet?", ["They trust its name for quality and safety", "Brands are always cheaper", "Logos protect heads", "No reason"], 0,
        "A good reputation is valuable - but always check safety marks too.",
        "মানুষ নামী ব্র্যান্ডের হেলমেটের জন্য একটু বেশি দাম দিতে পারেন কেন?", ["মান আর নিরাপত্তার জন্য সেই নামে ভরসা করেন", "ব্র্যান্ড সবসময় সস্তা", "লোগো মাথা রক্ষা করে", "কোনো কারণ নেই"],
        "সুনাম মূল্যবান - তবে সবসময় নিরাপত্তা-চিহ্নও দেখো।"),
    mcq("Which of these is a consumer right?", ["To get safe products and true information about them", "To take goods without paying", "To never pay tax", "To set the shop's prices"], 0,
        "Consumers also have the right to choose and to complain.",
        "এগুলোর কোনটা ভোক্তার অধিকার?", ["নিরাপদ পণ্য আর তার সম্পর্কে সত্যি তথ্য পাওয়া", "দাম না দিয়ে মাল নেওয়া", "কখনো কর না দেওয়া", "দোকানের দাম ঠিক করা"],
        "ভোক্তার বাছাই আর অভিযোগ জানানোর অধিকারও আছে।"),
    mcq("A shop's sales rise from Rs 40,000 to Rs 50,000 a month after the bridge opens. By what percent did sales grow?", ["25%", "10%", "20%", "50%"], 0,
        "Rise 10,000 on 40,000: 10,000 ÷ 40,000 x 100 = 25%.",
        "সেতু খোলার পর একটা দোকানের মাসিক বিক্রি 40,000 থেকে 50,000 টাকা হলো। বিক্রি কত শতাংশ বাড়ল?", ["25%", "10%", "20%", "50%"],
        "40,000-এ 10,000 বাড়ল: 10,000 ÷ 40,000 x 100 = 25%।"),
    mcq("A café stamps a card each visit and gives the 10th tea free. Why?", ["To reward regular customers so they keep coming back", "Because tea is free anyway", "To track workers", "It is a train ticket"], 0,
        "Rewards encourage customers to keep coming back.",
        "একটা ক্যাফে প্রতিবার কার্ডে ছাপ দেয় আর 10ম চা বিনামূল্যে দেয়। কেন?", ["নিয়মিত খদ্দেরদের পুরস্কার দিতে, যাতে তাঁরা ফিরে আসেন", "চা এমনিতেই বিনামূল্যে", "কর্মীদের খোঁজ রাখতে", "এটা ট্রেনের টিকিট"],
        "পুরস্কার খদ্দেরদের বারবার ফিরে আসতে উৎসাহ দেয়।"),
)
