"""Class 4 - Finance: percentages, discounts, wages and payslips, simple interest over years,
monthly budgets, tax, inflation, value that falls over time, project estimates with contingency,
equal instalments, safe digital money and honest dealing."""
from . import mcq


def _o(r, *alts):
    out = list(dict.fromkeys([r, *alts, r + 10, r * 2, r + 1]))
    return out[:4]


def pct(p, amount, q_en, q_bn):
    r = amount * p // 100
    o = _o(r, amount - r, p, amount + r)
    return mcq(q_en.format(p=p, a=amount), [f"Rs {x:,}" for x in o], 0,
               f"{p}% of {amount:,} = {amount:,} x {p} ÷ 100 = Rs {r:,}.",
               q_bn.format(p=p, a=amount), [f"{x:,} টাকা" for x in o],
               f"{amount:,}-এর {p}% = {amount:,} x {p} ÷ 100 = {r:,} টাকা।")


def sale(price, p, item_en, item_bn):
    off = price * p // 100
    r = price - off
    o = _o(r, off, price, price + off)
    return mcq(f"{item_en} costs Rs {price:,}. The shop gives {p}% off. What do you pay?",
               [f"Rs {x:,}" for x in o], 0,
               f"Discount = {p}% of {price:,} = Rs {off:,}; {price:,} - {off:,} = Rs {r:,}.",
               f"{item_bn}-এর দাম {price:,} টাকা। দোকান {p}% ছাড় দেয়। তুমি কত দেবে?",
               [f"{x:,} টাকা" for x in o],
               f"ছাড় = {price:,}-এর {p}% = {off:,} টাকা; {price:,} - {off:,} = {r:,} টাকা।")


def si(P, r, t):
    i = P * r * t // 100
    o = _o(i, P * r // 100, P + i, i * t)
    return mcq(f"Rs {P:,} is saved at {r}% simple interest a year. How much interest after {t} years?",
               [f"Rs {x:,}" for x in o], 0,
               f"Interest = P x R x T ÷ 100 = {P:,} x {r} x {t} ÷ 100 = Rs {i:,}. Total becomes Rs {P + i:,}.",
               f"{P:,} টাকা বছরে {r}% সরল সুদে জমানো হলো। {t} বছর পরে সুদ কত?",
               [f"{x:,} টাকা" for x in o],
               f"সুদ = আসল x হার x সময় ÷ 100 = {P:,} x {r} x {t} ÷ 100 = {i:,} টাকা। মোট হয় {P + i:,} টাকা।")


def wage(rate, days, bonus):
    r = rate * days + bonus
    o = _o(r, rate * days, rate + days + bonus, r - bonus * 2 if r > bonus * 2 else r + 50)
    return mcq(f"A site worker earns Rs {rate} a day, works {days} days and gets a Rs {bonus} safety bonus. Total pay?",
               [f"Rs {x:,}" for x in o], 0,
               f"{rate} x {days} = Rs {rate * days:,}; plus bonus {bonus} = Rs {r:,}.",
               f"একজন নির্মাণ-কর্মী দিনে {rate} টাকা পান, {days} দিন কাজ করেন আর {bonus} টাকা নিরাপত্তা-বোনাস পান। মোট বেতন?",
               [f"{x:,} টাকা" for x in o],
               f"{rate} x {days} = {rate * days:,} টাকা; বোনাস {bonus} যোগ করে = {r:,} টাকা।")


def contingency(cost, p):
    extra = cost * p // 100
    r = cost + extra
    o = _o(r, extra, cost, cost - extra)
    return mcq(f"A footbridge is estimated at Rs {cost:,}. Planners add {p}% contingency for surprises. What is the total budget?",
               [f"Rs {x:,}" for x in o], 0,
               f"{p}% of {cost:,} = Rs {extra:,}; {cost:,} + {extra:,} = Rs {r:,}. Contingency covers price rises and surprises.",
               f"একটা হাঁটার সেতুর আনুমানিক খরচ {cost:,} টাকা। পরিকল্পকেরা আকস্মিক খরচের জন্য {p}% যোগ করেন। মোট বাজেট কত?",
               [f"{x:,} টাকা" for x in o],
               f"{cost:,}-এর {p}% = {extra:,} টাকা; {cost:,} + {extra:,} = {r:,} টাকা। আকস্মিক-তহবিল দামবৃদ্ধি আর অপ্রত্যাশিত খরচ সামলায়।")


def instal(loan, interest, months):
    total = loan + interest
    r = total // months
    o = _o(r, loan // months, total, r * 2)
    return mcq(f"A shop owner borrows Rs {loan:,} and must repay it with Rs {interest:,} interest in {months} equal monthly instalments. How much each month?",
               [f"Rs {x:,}" for x in o], 0,
               f"Total to repay = {loan:,} + {interest:,} = Rs {total:,}; ÷ {months} = Rs {r:,} a month.",
               f"একজন দোকানদার {loan:,} টাকা ধার নিলেন; {interest:,} টাকা সুদসহ {months}টি সমান মাসিক কিস্তিতে শোধ করতে হবে। প্রতি মাসে কত?",
               [f"{x:,} টাকা" for x in o],
               f"মোট শোধ = {loan:,} + {interest:,} = {total:,} টাকা; ÷ {months} = মাসে {r:,} টাকা।")


ITEMS = (
    pct(10, 500, "What is {p}% of Rs {a}?", "{a} টাকার {p}% কত?"),
    pct(25, 800, "A family saves {p}% of Rs {a} pocket money. How much is saved?", "একটা পরিবার {a} টাকার {p}% জমায়। কত জমল?"),
    pct(50, 1200, "Half ({p}%) of a Rs {a} prize goes to a donation camp. How much is that?", "{a} টাকার পুরস্কারের অর্ধেক ({p}%) দানশিবিরে যায়। তা কত?"),
    pct(20, 1500, "A builder spends {p}% of a Rs {a} budget on bolts. How much?", "একজন নির্মাতা {a} টাকার বাজেটের {p}% বল্টুতে খরচ করেন। কত?"),
    pct(5, 2000, "A {p}% tax is added to a Rs {a} bill. How much is the tax?", "{a} টাকার বিলে {p}% কর যোগ হলো। কর কত?"),
    pct(75, 400, "{p}% of a Rs {a} grant has been spent. How much is spent?", "{a} টাকার অনুদানের {p}% খরচ হয়েছে। কত খরচ হলো?"),
    pct(30, 900, "A shop keeps {p}% of Rs {a} sales as profit. How much profit?", "একটা দোকান {a} টাকার বিক্রির {p}% লাভ রাখে। লাভ কত?"),
    pct(15, 600, "A tip of {p}% is given on a Rs {a} meal. How much is the tip?", "{a} টাকার খাবারে {p}% বকশিশ দেওয়া হলো। বকশিশ কত?"),
    sale(800, 25, "A school bag", "একটা স্কুলব্যাগ"),
    sale(1200, 10, "A cricket bat", "একটা ক্রিকেট ব্যাট"),
    sale(2500, 20, "A bicycle helmet set", "একটা সাইকেল-হেলমেট সেট"),
    sale(600, 50, "A pair of shoes in the end-of-season sale", "মরসুম-শেষের সেলে এক জোড়া জুতো"),
    sale(4000, 15, "A tool kit", "একটা যন্ত্রপাতির বাক্স"),
    si(1000, 5, 2), si(2000, 4, 3), si(5000, 6, 2), si(1500, 10, 4), si(800, 5, 5),
    wage(400, 6, 200), wage(550, 5, 300), wage(350, 7, 150), wage(600, 4, 250),
    contingency(20000, 10), contingency(50000, 10), contingency(80000, 15), contingency(12000, 20),
    instal(6000, 600, 6), instal(10000, 1000, 10), instal(12000, 1200, 12), instal(4500, 300, 4),
    mcq("What does 'per cent' (%) mean?", ["Out of 100", "Out of 10", "Out of 1,000", "Times 100"], 0,
        "25% means 25 out of every 100.",
        "'শতাংশ' (%) মানে কী?", ["প্রতি 100-এ", "প্রতি 10-এ", "প্রতি 1,000-এ", "100 গুণ"],
        "25% মানে প্রতি 100-এ 25।"),
    mcq("Which is the same as 50%?", ["One half", "One quarter", "One tenth", "Twice"], 0,
        "50 out of 100 = 1/2.",
        "কোনটা 50%-এর সমান?", ["অর্ধেক", "এক-চতুর্থাংশ", "এক-দশমাংশ", "দ্বিগুণ"],
        "100-এর মধ্যে 50 = 1/2।"),
    mcq("Which is the same as 25%?", ["One quarter", "One half", "One third", "One fifth"], 0,
        "25 out of 100 = 1/4.",
        "কোনটা 25%-এর সমান?", ["এক-চতুর্থাংশ", "অর্ধেক", "এক-তৃতীয়াংশ", "এক-পঞ্চমাংশ"],
        "100-এর মধ্যে 25 = 1/4।"),
    mcq("Quick way to find 10% of any amount?", ["Divide it by 10", "Multiply by 10", "Add 10", "Subtract 10"], 0,
        "10% of Rs 340 = Rs 34. From 10% you can build 5%, 20% and more.",
        "যেকোনো পরিমাণের 10% বের করার দ্রুত উপায়?", ["10 দিয়ে ভাগ করো", "10 দিয়ে গুণ করো", "10 যোগ করো", "10 বিয়োগ করো"],
        "340 টাকার 10% = 34 টাকা। 10% থেকে 5%, 20% আর আরও বের করা যায়।"),
    mcq("Shop A sells a Rs 1,000 fan at 20% off. Shop B sells it for Rs 850. Which is cheaper?", ["Shop A (Rs 800)", "Shop B (Rs 850)", "Both cost the same", "Cannot tell"], 0,
        "20% of 1,000 = 200, so Shop A charges 800 - Rs 50 less than B.",
        "দোকান A 1,000 টাকার পাখায় 20% ছাড় দেয়। দোকান B সেটা 850 টাকায় বেচে। কোনটা সস্তা?", ["দোকান A (800 টাকা)", "দোকান B (850 টাকা)", "দুটোর দাম সমান", "বলা যায় না"],
        "1,000-এর 20% = 200, তাই দোকান A নেয় 800 - B-র চেয়ে 50 টাকা কম।"),
    mcq("A 'Buy 2, get 1 free' offer on Rs 60 notebooks. What do 3 notebooks cost?", ["Rs 120", "Rs 180", "Rs 60", "Rs 90"], 0,
        "You pay for 2: 2 x 60 = 120. Each costs Rs 40 effectively.",
        "60 টাকার খাতায় '2টি কিনলে 1টি ফ্রি' অফার। 3টি খাতার দাম কত?", ["120 টাকা", "180 টাকা", "60 টাকা", "90 টাকা"],
        "2টির দাম দাও: 2 x 60 = 120। কার্যত প্রতিটি 40 টাকা।"),
    mcq("Why should you think before buying something just because it is on sale?", ["A discount only saves money if you actually need it", "Sales are always bad", "Sale items are free", "Shops lose money on every sale"], 0,
        "Spending Rs 300 on something unneeded is not saving Rs 100!",
        "শুধু সেলে আছে বলে কিছু কেনার আগে ভাবা উচিত কেন?", ["ছাড়ে টাকা বাঁচে শুধু যদি সত্যিই দরকার হয়", "সেল সবসময় খারাপ", "সেলের জিনিস বিনামূল্যে", "প্রতি সেলে দোকান টাকা হারায়"],
        "অদরকারি জিনিসে 300 টাকা খরচ করা 100 টাকা বাঁচানো নয়!"),
    mcq("What is a 'payslip'?", ["A paper showing your pay, deductions and what you receive", "A slippery floor", "A loan form", "A shopping list"], 0,
        "Check your payslip to make sure you were paid correctly.",
        "'বেতনপত্র' (পে-স্লিপ) কী?", ["তোমার বেতন, কাটা অংশ আর হাতে পাওয়া টাকা দেখানো কাগজ", "পিছল মেঝে", "ঋণের ফর্ম", "বাজারের তালিকা"],
        "ঠিকমতো বেতন পেয়েছ কিনা বেতনপত্র দেখে মিলিয়ে নাও।"),
    mcq("What are 'deductions' on a payslip?", ["Amounts taken off pay, like tax or savings into a fund", "Extra gifts", "Overtime pay", "Bonuses"], 0,
        "Gross pay minus deductions = net (take-home) pay.",
        "বেতনপত্রে 'কাটা অংশ' কী?", ["বেতন থেকে কেটে নেওয়া অর্থ, যেমন কর বা তহবিলে সঞ্চয়", "বাড়তি উপহার", "ওভারটাইম বেতন", "বোনাস"],
        "মোট বেতন বিয়োগ কাটা অংশ = নিট (হাতে পাওয়া) বেতন।"),
    mcq("Gross pay is Rs 15,000 and deductions are Rs 1,800. What is the take-home pay?", ["Rs 13,200", "Rs 16,800", "Rs 1,800", "Rs 15,000"], 0,
        "15,000 - 1,800 = 13,200.",
        "মোট বেতন 15,000 টাকা আর কাটা অংশ 1,800 টাকা। হাতে কত আসে?", ["13,200 টাকা", "16,800 টাকা", "1,800 টাকা", "15,000 টাকা"],
        "15,000 - 1,800 = 13,200।"),
    mcq("What is 'overtime' pay?", ["Extra pay for working beyond normal hours", "Pay for being late", "A fine", "A loan"], 0,
        "Often paid at a higher rate, like 1.5 times the normal hourly pay.",
        "'ওভারটাইম' বেতন কী?", ["স্বাভাবিক সময়ের বেশি কাজের জন্য বাড়তি বেতন", "দেরিতে আসার বেতন", "জরিমানা", "ঋণ"],
        "প্রায়ই বেশি হারে দেওয়া হয়, যেমন স্বাভাবিক ঘণ্টাপ্রতি বেতনের 1.5 গুণ।"),
    mcq("A worker earns Rs 80 an hour and Rs 120 an hour for overtime. They work 8 normal hours and 2 overtime hours. Pay?", ["Rs 880", "Rs 800", "Rs 1,000", "Rs 960"], 0,
        "8 x 80 = 640; 2 x 120 = 240; total 880.",
        "একজন কর্মী ঘণ্টায় 80 টাকা আর ওভারটাইমে ঘণ্টায় 120 টাকা পান। 8 ঘণ্টা স্বাভাবিক আর 2 ঘণ্টা ওভারটাইম করলেন। বেতন?", ["880 টাকা", "800 টাকা", "1,000 টাকা", "960 টাকা"],
        "8 x 80 = 640; 2 x 120 = 240; মোট 880।"),
    mcq("Why must workers be paid fairly and on time?", ["They depend on wages for food, rent and family needs", "Late pay is a reward", "It does not matter", "Workers do not need money"], 0,
        "Fair, prompt pay is the law and builds a loyal, skilled team.",
        "কর্মীদের ন্যায্য আর সময়মতো বেতন দিতে হবে কেন?", ["খাবার, ভাড়া আর পরিবারের প্রয়োজনে তাঁরা বেতনের উপর নির্ভর করেন", "দেরিতে বেতন পুরস্কার", "কিছু যায় আসে না", "কর্মীদের টাকা লাগে না"],
        "ন্যায্য আর সময়মতো বেতন আইন, আর এতে অনুগত, দক্ষ দল গড়ে ওঠে।"),
    mcq("What is a 'monthly budget'?", ["A plan of expected income and spending for a month", "A bank robbery plan", "A list of friends", "A diary of the weather"], 0,
        "Budgets help make sure money lasts the whole month.",
        "'মাসিক বাজেট' কী?", ["এক মাসের প্রত্যাশিত আয় আর খরচের পরিকল্পনা", "ব্যাংক ডাকাতির পরিকল্পনা", "বন্ধুদের তালিকা", "আবহাওয়ার ডায়েরি"],
        "বাজেট নিশ্চিত করে যে টাকা গোটা মাস চলবে।"),
    mcq("A family earns Rs 20,000 a month and spends Rs 17,500. What is left to save?", ["Rs 2,500", "Rs 3,500", "Rs 37,500", "Rs 17,500"], 0,
        "20,000 - 17,500 = 2,500.",
        "একটা পরিবার মাসে 20,000 টাকা আয় করে আর 17,500 টাকা খরচ করে। জমানোর জন্য কত বাকি?", ["2,500 টাকা", "3,500 টাকা", "37,500 টাকা", "17,500 টাকা"],
        "20,000 - 17,500 = 2,500।"),
    mcq("If spending is more than income every month, what happens?", ["Savings run out or debts build up", "You get richer", "Nothing", "The bank gives free money"], 0,
        "Cut spending or raise income before debts pile up.",
        "প্রতি মাসে খরচ আয়ের চেয়ে বেশি হলে কী হয়?", ["সঞ্চয় ফুরোয় বা ঋণ জমে", "তুমি ধনী হও", "কিছুই না", "ব্যাংক বিনামূল্যে টাকা দেয়"],
        "ঋণ জমার আগে খরচ কমাও বা আয় বাড়াও।"),
    mcq("Which is a 'fixed' monthly cost?", ["Rent", "Eating out", "Cinema tickets", "Gifts"], 0,
        "Fixed costs stay the same each month; variable costs change.",
        "কোনটা 'স্থির' মাসিক খরচ?", ["বাড়িভাড়া", "বাইরে খাওয়া", "সিনেমার টিকিট", "উপহার"],
        "স্থির খরচ প্রতি মাসে একই থাকে; পরিবর্তনশীল খরচ বদলায়।"),
    mcq("Which is a 'variable' cost for a household?", ["Electricity used", "Fixed rent", "A fixed loan instalment", "School fees fixed for the year"], 0,
        "Using fewer lights and fans lowers the bill.",
        "পরিবারের জন্য কোনটা 'পরিবর্তনশীল' খরচ?", ["ব্যবহৃত বিদ্যুৎ", "স্থির বাড়িভাড়া", "স্থির ঋণের কিস্তি", "বছরের জন্য স্থির স্কুলের বেতন"],
        "কম বাতি আর পাখা চালালে বিল কমে।"),
    mcq("What is GST in India?", ["A tax added to the price of most goods and services", "A type of bank", "A free gift", "A bridge company"], 0,
        "Goods and Services Tax is collected by sellers and paid to the government.",
        "ভারতে জিএসটি কী?", ["বেশিরভাগ পণ্য আর পরিষেবার দামে যোগ হওয়া কর", "এক রকম ব্যাংক", "বিনামূল্যের উপহার", "সেতু-কোম্পানি"],
        "পণ্য ও পরিষেবা কর বিক্রেতারা আদায় করে সরকারকে দেন।"),
    mcq("A Rs 1,000 item has 18% GST. What is the total price?", ["Rs 1,180", "Rs 1,018", "Rs 1,800", "Rs 820"], 0,
        "18% of 1,000 = 180; 1,000 + 180 = 1,180.",
        "1,000 টাকার জিনিসে 18% জিএসটি। মোট দাম কত?", ["1,180 টাকা", "1,018 টাকা", "1,800 টাকা", "820 টাকা"],
        "1,000-এর 18% = 180; 1,000 + 180 = 1,180।"),
    mcq("Why is avoiding tax wrong?", ["It takes money from schools, hospitals and roads that everyone uses", "It helps the country", "Tax is optional", "It is not wrong"], 0,
        "Honest tax pays for shared services - and evasion is illegal.",
        "কর ফাঁকি দেওয়া অন্যায় কেন?", ["সবাই যে স্কুল, হাসপাতাল আর রাস্তা ব্যবহার করে তার টাকা কেড়ে নেয়", "দেশের উপকার করে", "কর ইচ্ছাধীন", "অন্যায় নয়"],
        "সৎভাবে দেওয়া কর যৌথ পরিষেবার খরচ মেটায় - আর ফাঁকি বেআইনি।"),
    mcq("Why does money kept under a mattress lose value over time?", ["Inflation means it buys less each year", "Mattresses eat money", "The notes get heavier", "It does not"], 0,
        "Savings that earn interest can keep up better with rising prices.",
        "তোশকের নিচে রাখা টাকার মূল্য সময়ের সঙ্গে কমে কেন?", ["মুদ্রাস্ফীতিতে প্রতি বছর তা দিয়ে কম কেনা যায়", "তোশক টাকা খায়", "নোট ভারী হয়", "কমে না"],
        "সুদ পাওয়া সঞ্চয় বাড়তে থাকা দামের সঙ্গে ভালো তাল রাখে।"),
    mcq("Why do bridge budgets planned years ahead include extra for price rises?", ["Steel, cement and wages usually cost more by the time work starts", "Prices always fall", "To waste money", "Budgets never change"], 0,
        "Allowing for inflation stops a project running out of money halfway.",
        "বছরখানেক আগে থেকে পরিকল্পিত সেতুর বাজেটে দামবৃদ্ধির জন্য বাড়তি রাখা হয় কেন?", ["কাজ শুরুর সময় ইস্পাত, সিমেন্ট আর মজুরির দাম সাধারণত বেড়ে যায়", "দাম সবসময় কমে", "টাকা নষ্ট করতে", "বাজেট কখনো বদলায় না"],
        "মুদ্রাস্ফীতি হিসেবে রাখলে প্রকল্প মাঝপথে টাকার অভাবে আটকায় না।"),
    mcq("A truck bought for Rs 10 lakh is worth Rs 8 lakh after a year. What is this fall in value called?", ["Depreciation", "Interest", "Profit", "Inflation"], 0,
        "Machines and vehicles lose value as they age and wear.",
        "10 লাখ টাকায় কেনা একটা ট্রাকের দাম এক বছর পরে 8 লাখ। এই মূল্য কমাকে কী বলে?", ["অবচয়", "সুদ", "লাভ", "মুদ্রাস্ফীতি"],
        "যন্ত্র আর গাড়ি পুরোনো আর ক্ষয় হলে দাম হারায়।"),
    mcq("A crane worth Rs 50,000 loses Rs 5,000 of value each year. What is it worth after 3 years?", ["Rs 35,000", "Rs 45,000", "Rs 15,000", "Rs 40,000"], 0,
        "3 x 5,000 = 15,000 lost; 50,000 - 15,000 = 35,000.",
        "50,000 টাকার একটা ক্রেন প্রতি বছর 5,000 টাকা মূল্য হারায়। 3 বছর পরে দাম কত?", ["35,000 টাকা", "45,000 টাকা", "15,000 টাকা", "40,000 টাকা"],
        "3 x 5,000 = 15,000 কমল; 50,000 - 15,000 = 35,000।"),
    mcq("What is a 'fixed deposit'?", ["Money locked in a bank for a set time, usually earning higher interest", "Money spent at once", "A fixed price in a shop", "A broken ATM"], 0,
        "You get more interest for promising not to withdraw early.",
        "'স্থায়ী আমানত' (ফিক্সড ডিপোজিট) কী?", ["নির্দিষ্ট সময়ের জন্য ব্যাংকে আটকে রাখা টাকা, সাধারণত বেশি সুদে", "একবারে খরচ করা টাকা", "দোকানের স্থির দাম", "নষ্ট এটিএম"],
        "আগে না তোলার প্রতিশ্রুতির জন্য বেশি সুদ পাও।"),
    mcq("Which earns more in one year on Rs 10,000: 4% or 7% interest?", ["7% - it gives Rs 700 instead of Rs 400", "4%", "Both the same", "Neither earns anything"], 0,
        "Higher rate, more interest - but check the risk and rules too.",
        "10,000 টাকায় এক বছরে কোনটায় বেশি আয়: 4% না 7% সুদ?", ["7% - 400 টাকার বদলে 700 টাকা দেয়", "4%", "দুটোই সমান", "কোনোটাতেই আয় নেই"],
        "বেশি হার, বেশি সুদ - তবে ঝুঁকি আর নিয়মও দেখো।"),
    mcq("What is UPI used for?", ["Sending and receiving money instantly from a phone", "Measuring rainfall", "Building bridges", "Cooking food"], 0,
        "UPI makes digital payments quick - but it must be used carefully.",
        "ইউপিআই কীসের জন্য ব্যবহার হয়?", ["ফোন থেকে সঙ্গে সঙ্গে টাকা পাঠানো আর পাওয়া", "বৃষ্টি মাপা", "সেতু বানানো", "রান্না করা"],
        "ইউপিআই ডিজিটাল লেনদেন দ্রুত করে - তবে সাবধানে ব্যবহার করতে হয়।"),
    mcq("Someone calls saying 'Tell me your UPI PIN so I can send you a prize.' What should you do?", ["Never share it - hang up and tell a trusted adult", "Share it quickly", "Share half of it", "Post it online"], 0,
        "You never need a PIN to RECEIVE money. Anyone asking is a scammer.",
        "কেউ ফোন করে বলল, 'পুরস্কার পাঠাতে তোমার ইউপিআই পিন বলো।' কী করবে?", ["কখনো বলবে না - ফোন রেখে বিশ্বস্ত বড়দের জানাও", "তাড়াতাড়ি বলো", "অর্ধেকটা বলো", "অনলাইনে পোস্ট করো"],
        "টাকা পেতে কখনো পিন লাগে না। যে চায় সে প্রতারক।"),
    mcq("A message says your bank account will close unless you click a link. What is safest?", ["Do not click; contact the bank using its official number", "Click it at once", "Reply with your password", "Forward it to everyone"], 0,
        "Fake 'urgent' messages are a common trick called phishing.",
        "একটা বার্তা বলছে লিঙ্কে ক্লিক না করলে তোমার ব্যাংক-অ্যাকাউন্ট বন্ধ হবে। সবচেয়ে নিরাপদ কী?", ["ক্লিক কোরো না; ব্যাংকের সরকারি নম্বরে যোগাযোগ করো", "এখনই ক্লিক করো", "পাসওয়ার্ড দিয়ে উত্তর দাও", "সবাইকে পাঠাও"],
        "ভুয়ো 'জরুরি' বার্তা একটা সাধারণ ফাঁদ, একে বলে ফিশিং।"),
    mcq("Why is it safer to scan the shop's QR code yourself than to scan one sent by a stranger?", ["A stranger's QR code may be set to take money from you", "Shop codes are prettier", "There is no difference", "Strangers' codes are faster"], 0,
        "Check the name that appears before you pay.",
        "অচেনা লোকের পাঠানো কিউআর কোডের চেয়ে দোকানের কিউআর কোড নিজে স্ক্যান করা নিরাপদ কেন?", ["অচেনার কোড তোমার থেকে টাকা কেটে নেওয়ার জন্য বানানো হতে পারে", "দোকানের কোড সুন্দর", "কোনো পার্থক্য নেই", "অচেনার কোড দ্রুত"],
        "দাম দেওয়ার আগে যে নাম দেখায় তা মিলিয়ে নাও।"),
    mcq("In MODIS BridgeWorks, why does the game never ask for real card or bank details?", ["Real money is never collected in the game - only game money and Civil Grants", "It forgot to ask", "Cards are illegal", "It wants them later"], 0,
        "Any game or app asking children for card details is a warning sign.",
        "MODIS BridgeWorks-এ খেলাটা কখনো আসল কার্ড বা ব্যাংকের তথ্য চায় না কেন?", ["খেলায় আসল টাকা কখনো নেওয়া হয় না - শুধু খেলার টাকা আর সিভিল গ্রান্ট", "চাইতে ভুলে গেছে", "কার্ড বেআইনি", "পরে চাইবে"],
        "কোনো খেলা বা অ্যাপ শিশুদের কাছে কার্ডের তথ্য চাইলে সেটা সতর্কসংকেত।"),
    mcq("What is a 'loan instalment'?", ["One of the regular payments to repay a loan", "The whole loan at once", "A free gift", "A bank holiday"], 0,
        "Instalments spread the repayment over months.",
        "'ঋণের কিস্তি' কী?", ["ঋণ শোধের নিয়মিত পেমেন্টগুলোর একটা", "একবারে পুরো ঋণ", "বিনামূল্যের উপহার", "ব্যাংকের ছুটি"],
        "কিস্তি শোধকে কয়েক মাসে ছড়িয়ে দেয়।"),
    mcq("Why is it important to repay loans on time?", ["Late payments add fines and make lenders trust you less", "Late is better", "Lenders forget", "It does not matter"], 0,
        "A good repayment record makes future loans easier and cheaper.",
        "সময়মতো ঋণ শোধ করা জরুরি কেন?", ["দেরিতে জরিমানা লাগে আর ঋণদাতার আস্থা কমে", "দেরি ভালো", "ঋণদাতা ভুলে যায়", "কিছু যায় আসে না"],
        "ভালো শোধের রেকর্ড ভবিষ্যতের ঋণ সহজ আর সস্তা করে।"),
    mcq("Why is a Civil Grant in BridgeWorks better than a loan for the same amount?", ["Grants do not have to be repaid and have no interest", "Grants cost more", "Loans are free", "There is no difference"], 0,
        "Earn grants through the Academy and they cover shortfalls before any loan is needed.",
        "BridgeWorks-এ একই পরিমাণের ঋণের চেয়ে সিভিল গ্রান্ট ভালো কেন?", ["অনুদান শোধ করতে হয় না আর সুদ নেই", "অনুদানে খরচ বেশি", "ঋণ বিনামূল্যে", "কোনো পার্থক্য নেই"],
        "অ্যাকাডেমি থেকে অনুদান অর্জন করো, ঋণের আগেই তা ঘাটতি মেটায়।"),
    mcq("A village needs Rs 60,000 for a footbridge. It has a Rs 45,000 grant. How much more is needed?", ["Rs 15,000", "Rs 105,000", "Rs 45,000", "Rs 25,000"], 0,
        "60,000 - 45,000 = 15,000 - this is the shortfall a loan or donations must cover.",
        "একটা গ্রামের হাঁটার সেতুর জন্য 60,000 টাকা লাগবে। 45,000 টাকার অনুদান আছে। আর কত লাগবে?", ["15,000 টাকা", "1,05,000 টাকা", "45,000 টাকা", "25,000 টাকা"],
        "60,000 - 45,000 = 15,000 - এই ঘাটতি ঋণ বা দানে মেটাতে হবে।"),
    mcq("What is 'profit margin' as a percentage?", ["Profit divided by selling price, x 100", "Price x 100", "Cost + price", "Number of customers"], 0,
        "Selling at Rs 200 with Rs 50 profit = 25% margin.",
        "শতাংশে 'লাভের মার্জিন' কী?", ["লাভ ভাগ বিক্রয়মূল্য, x 100", "দাম x 100", "খরচ + দাম", "খদ্দেরের সংখ্যা"],
        "200 টাকায় বেচে 50 টাকা লাভ = 25% মার্জিন।"),
    mcq("An item is bought for Rs 400 and sold for Rs 500. What is the profit as a percentage of the cost?", ["25%", "20%", "100%", "50%"], 0,
        "Profit 100; 100 ÷ 400 x 100 = 25%.",
        "একটা জিনিস 400 টাকায় কিনে 500 টাকায় বেচা হলো। খরচের শতাংশে লাভ কত?", ["25%", "20%", "100%", "50%"],
        "লাভ 100; 100 ÷ 400 x 100 = 25%।"),
    mcq("An item bought for Rs 500 is sold for Rs 450. What happened?", ["A loss of Rs 50 (10%)", "A profit of Rs 50", "No change", "A profit of 10%"], 0,
        "Selling below cost is a loss: 50 ÷ 500 = 10%.",
        "500 টাকায় কেনা জিনিস 450 টাকায় বেচা হলো। কী হলো?", ["50 টাকা (10%) ক্ষতি", "50 টাকা লাভ", "কোনো পরিবর্তন নয়", "10% লাভ"],
        "খরচের কম দামে বেচলে ক্ষতি: 50 ÷ 500 = 10%।"),
    mcq("What is 'insurance' for a bridge builder?", ["Paying a small regular amount so big losses (fire, flood, accidents) are covered", "A free bridge", "A loan with no interest", "A tax refund"], 0,
        "Insurance shares risk so one disaster does not ruin a business.",
        "সেতু-নির্মাতার জন্য 'বিমা' কী?", ["নিয়মিত ছোট অঙ্ক দিয়ে বড় ক্ষতি (আগুন, বন্যা, দুর্ঘটনা) সামলানো", "বিনামূল্যের সেতু", "সুদহীন ঋণ", "করের ফেরত"],
        "বিমা ঝুঁকি ভাগ করে, যাতে একটা বিপর্যয়ে ব্যবসা ধ্বংস না হয়।"),
    mcq("What is a 'premium' in insurance?", ["The regular payment made to the insurance company", "The money paid out after a loss", "A prize", "A discount"], 0,
        "You pay premiums; if something insured goes wrong, the insurer pays a claim.",
        "বিমায় 'প্রিমিয়াম' কী?", ["বিমা কোম্পানিকে দেওয়া নিয়মিত পেমেন্ট", "ক্ষতির পরে পাওয়া টাকা", "পুরস্কার", "ছাড়"],
        "তুমি প্রিমিয়াম দাও; বিমা-করা কিছুর ক্ষতি হলে বিমাকারী দাবির টাকা দেয়।"),
    mcq("What does 'credit' mean when you buy something?", ["Buying now and paying later", "Paying in cash immediately", "Getting it free", "Returning it"], 0,
        "Credit is useful but can be costly if not repaid on time.",
        "কিছু কেনার সময় 'ধারে' মানে কী?", ["এখন কিনে পরে দাম দেওয়া", "এখনই নগদে দাম দেওয়া", "বিনামূল্যে পাওয়া", "ফেরত দেওয়া"],
        "ধার কাজের, কিন্তু সময়মতো শোধ না করলে দামি হতে পারে।"),
    mcq("Rs 100 is shared among 4 friends in the ratio 1 : 1 : 1 : 2. How much does the biggest share get?", ["Rs 40", "Rs 25", "Rs 20", "Rs 50"], 0,
        "Total parts = 5; each part = 20; 2 parts = 40.",
        "100 টাকা 4 বন্ধুর মধ্যে 1 : 1 : 1 : 2 অনুপাতে ভাগ হলো। সবচেয়ে বড় ভাগে কত?", ["40 টাকা", "25 টাকা", "20 টাকা", "50 টাকা"],
        "মোট ভাগ = 5; প্রতি ভাগ = 20; 2 ভাগ = 40।"),
    mcq("A bridge toll raises Rs 2,000 a day. How much in a 30-day month?", ["Rs 60,000", "Rs 6,000", "Rs 2,030", "Rs 600,000"], 0,
        "2,000 x 30 = 60,000 - money that repays the bridge's loan and pays for upkeep.",
        "একটা সেতুর টোলে দিনে 2,000 টাকা ওঠে। 30 দিনের মাসে কত?", ["60,000 টাকা", "6,000 টাকা", "2,030 টাকা", "6,00,000 টাকা"],
        "2,000 x 30 = 60,000 - যা সেতুর ঋণ শোধ আর রক্ষণাবেক্ষণে যায়।"),
    mcq("A bridge cost Rs 12 lakh and its toll earns Rs 2 lakh a year after costs. How many years to earn back the cost?", ["6 years", "2 years", "12 years", "24 years"], 0,
        "12 ÷ 2 = 6 years. This is called the payback period.",
        "একটা সেতুর খরচ 12 লাখ টাকা আর খরচ বাদে টোল থেকে বছরে 2 লাখ টাকা আয়। খরচ উঠতে কত বছর?", ["6 বছর", "2 বছর", "12 বছর", "24 বছর"],
        "12 ÷ 2 = 6 বছর। একে বলে খরচ ফেরতের সময়।"),
    mcq("Why do businesses keep written records of every rupee in and out?", ["To know if they are making money and to pay the right tax", "For decoration", "To confuse customers", "It is not needed"], 0,
        "Good records catch mistakes and theft early.",
        "ব্যবসা প্রতিটি টাকার আসা-যাওয়ার লিখিত হিসাব রাখে কেন?", ["লাভ হচ্ছে কিনা জানতে আর সঠিক কর দিতে", "সাজসজ্জার জন্য", "খদ্দেরদের বিভ্রান্ত করতে", "দরকার নেই"],
        "ভালো হিসাব ভুল আর চুরি আগেভাগে ধরে।"),
    mcq("What is a 'bribe'?", ["Money or gifts given to make someone break rules or act unfairly", "A tip for good service", "A tax", "A bank deposit"], 0,
        "Bribes are illegal and can lead to unsafe bridges if inspections are skipped.",
        "'ঘুষ' কী?", ["নিয়ম ভাঙাতে বা অন্যায় করাতে দেওয়া টাকা বা উপহার", "ভালো পরিষেবার বকশিশ", "কর", "ব্যাংকে জমা"],
        "ঘুষ বেআইনি, আর পরিদর্শন বাদ গেলে সেতু অনিরাপদ হতে পারে।"),
    mcq("A supplier offers you cheap, weak steel and a secret cash gift to use it on a bridge. What should you do?", ["Refuse and report it - safety and honesty come first", "Accept quietly", "Take the gift only", "Use half the weak steel"], 0,
        "Weak materials can make a bridge collapse. Never trade safety for money.",
        "একজন সরবরাহকারী তোমাকে সেতুতে সস্তা, দুর্বল ইস্পাত ব্যবহারের জন্য গোপনে নগদ উপহার দিতে চায়। কী করবে?", ["প্রত্যাখ্যান করে জানিয়ে দাও - নিরাপত্তা আর সততা আগে", "চুপচাপ নাও", "শুধু উপহারটা নাও", "অর্ধেক দুর্বল ইস্পাত ব্যবহার করো"],
        "দুর্বল উপাদানে সেতু ভেঙে পড়তে পারে। টাকার জন্য কখনো নিরাপত্তার সঙ্গে আপস কোরো না।"),
    mcq("Why do governments ask several companies to bid (tender) for a bridge job?", ["Competition gets a good price and fair choice", "To waste time", "To pick the most expensive", "Tenders are secret gifts"], 0,
        "Open tenders reduce corruption and save public money.",
        "সরকার সেতুর কাজে কয়েকটা কোম্পানিকে দরপত্র দিতে বলে কেন?", ["প্রতিযোগিতায় ভালো দাম আর ন্যায্য বাছাই হয়", "সময় নষ্ট করতে", "সবচেয়ে দামিটা বাছতে", "দরপত্র গোপন উপহার"],
        "খোলা দরপত্র দুর্নীতি কমায় আর জনগণের টাকা বাঁচায়।"),
    mcq("Three companies bid Rs 9 lakh, Rs 8 lakh and Rs 7 lakh. The Rs 7 lakh bid uses unsafe materials. Which should win?", ["Rs 8 lakh, if it is safe and meets all standards", "Rs 7 lakh because cheapest always wins", "Rs 9 lakh because dearest is best", "None ever"], 0,
        "Choose the best value that is safe - not just the lowest price.",
        "তিনটি কোম্পানি 9 লাখ, 8 লাখ আর 7 লাখ টাকার দর দিল। 7 লাখের দরে অনিরাপদ উপাদান। কে জিতবে?", ["8 লাখ, যদি নিরাপদ আর সব মান মানে", "7 লাখ, কারণ সবচেয়ে সস্তাই জেতে", "9 লাখ, কারণ সবচেয়ে দামিই সেরা", "কেউ কখনো নয়"],
        "নিরাপদ এমন সেরা মূল্য বাছো - শুধু সবচেয়ে কম দাম নয়।"),
    mcq("A donation camp collects Rs 4,800 from 60 students. What is the average gift?", ["Rs 80", "Rs 60", "Rs 48", "Rs 800"], 0,
        "4,800 ÷ 60 = 80.",
        "একটা দানশিবির 60 জন ছাত্রছাত্রীর কাছ থেকে 4,800 টাকা তুলল। গড় দান কত?", ["80 টাকা", "60 টাকা", "48 টাকা", "800 টাকা"],
        "4,800 ÷ 60 = 80।"),
    mcq("Why do good charities publish how they spent donations?", ["So donors can trust the money did real good", "To show off", "It is not needed", "To hide spending"], 0,
        "Transparency builds trust - always check before giving real money.",
        "ভালো দাতব্য সংস্থা দানের টাকা কীভাবে খরচ হলো তা প্রকাশ করে কেন?", ["যাতে দাতারা ভরসা করতে পারেন যে টাকা সত্যিই কাজে লেগেছে", "দেখানোর জন্য", "দরকার নেই", "খরচ লুকাতে"],
        "স্বচ্ছতা আস্থা গড়ে - আসল টাকা দেওয়ার আগে সবসময় যাচাই করো।"),
    mcq("Rs 500 saved each month for a year makes how much (without interest)?", ["Rs 6,000", "Rs 5,000", "Rs 500", "Rs 60,000"], 0,
        "500 x 12 = 6,000. Small regular saving adds up!",
        "প্রতি মাসে 500 টাকা জমালে এক বছরে (সুদ ছাড়া) কত হয়?", ["6,000 টাকা", "5,000 টাকা", "500 টাকা", "60,000 টাকা"],
        "500 x 12 = 6,000। ছোট নিয়মিত সঞ্চয় জমে বড় হয়!"),
    mcq("You want a Rs 3,600 bicycle and can save Rs 300 a month. How many months?", ["12", "10", "6", "36"], 0,
        "3,600 ÷ 300 = 12 months.",
        "তুমি 3,600 টাকার সাইকেল চাও আর মাসে 300 টাকা জমাতে পারো। কত মাস লাগবে?", ["12", "10", "6", "36"],
        "3,600 ÷ 300 = 12 মাস।"),
    mcq("Which is the best reason to keep an emergency fund?", ["Unexpected costs like repairs or illness can be paid without borrowing", "To buy sweets", "To show friends", "Banks require it for games"], 0,
        "Many experts suggest saving a few months of expenses.",
        "জরুরি তহবিল রাখার সবচেয়ে ভালো কারণ কোনটা?", ["মেরামত বা অসুখের মতো আকস্মিক খরচ ধার ছাড়াই মেটানো যায়", "মিষ্টি কিনতে", "বন্ধুদের দেখাতে", "খেলার জন্য ব্যাংক চায়"],
        "অনেক বিশেষজ্ঞ কয়েক মাসের খরচ জমিয়ে রাখার পরামর্শ দেন।"),
    mcq("A bank pays 6% a year. A friend promises 50% a month 'guaranteed'. What is most likely?", ["The friend's offer is a scam", "The friend is a genius", "Banks are cheating", "Both are equally safe"], 0,
        "Promises of huge, guaranteed returns are a classic warning sign.",
        "একটা ব্যাংক বছরে 6% দেয়। এক বন্ধু মাসে 50% 'নিশ্চিত' দেওয়ার কথা দিল। সবচেয়ে সম্ভাব্য কী?", ["বন্ধুর প্রস্তাব প্রতারণা", "বন্ধু প্রতিভাবান", "ব্যাংক ঠকাচ্ছে", "দুটোই সমান নিরাপদ"],
        "বিশাল, নিশ্চিত লাভের প্রতিশ্রুতি একটা পুরোনো সতর্কসংকেত।"),
    mcq("What is the difference between 'saving' and 'investing'?", ["Saving keeps money safe; investing puts it to work for growth, with some risk", "They are the same", "Investing is always safe", "Saving always loses money"], 0,
        "Building a bridge is an investment - it costs now and pays back for decades.",
        "'সঞ্চয়' আর 'বিনিয়োগ'-এর পার্থক্য কী?", ["সঞ্চয় টাকা নিরাপদ রাখে; বিনিয়োগ কিছু ঝুঁকিসহ বাড়ার জন্য টাকা খাটায়", "দুটো একই", "বিনিয়োগ সবসময় নিরাপদ", "সঞ্চয়ে সবসময় টাকা কমে"],
        "সেতু বানানো একটা বিনিয়োগ - এখন খরচ, কিন্তু দশকের পর দশক ফেরত দেয়।"),
    pct(40, 2500, "A bridge club spends {p}% of its Rs {a} fund on a model kit. How much?", "একটা সেতু-ক্লাব তার {a} টাকার তহবিলের {p}% মডেল-কিটে খরচ করে। কত?"),
    pct(12, 5000, "A bank charges {p}% on a Rs {a} loan for a year. What is the interest?", "একটা ব্যাংক {a} টাকার ঋণে বছরে {p}% নেয়। সুদ কত?"),
    sale(1500, 30, "A pair of safety boots", "এক জোড়া সুরক্ষা-বুট"),
    sale(350, 20, "A geometry box", "একটা জ্যামিতি-বাক্স"),
    si(3000, 8, 2), si(2500, 4, 4),
    wage(500, 6, 100), wage(450, 3, 75),
    instal(9000, 900, 9),
    contingency(30000, 5),
    mcq("Prices in a market rose so Rs 200 of vegetables now cost Rs 210. By what percent did prices rise?", ["5%", "10%", "2%", "21%"], 0,
        "Rise 10 on 200: 10 ÷ 200 x 100 = 5%. This general rise in prices is inflation.",
        "বাজারে দাম বেড়ে 200 টাকার সবজির দাম এখন 210 টাকা। দাম কত শতাংশ বাড়ল?", ["5%", "10%", "2%", "21%"],
        "200-এ 10 বাড়ল: 10 ÷ 200 x 100 = 5%। দামের এই সাধারণ বৃদ্ধিই মুদ্রাস্ফীতি।"),
    mcq("Which public things in your town are mostly paid for by taxes?", ["Roads, bridges, government schools and hospitals", "Private toys", "Your own bicycle", "Sweets in a shop"], 0,
        "Everyone chips in through taxes for things everyone shares.",
        "তোমার শহরের কোন জনসাধারণের জিনিস মূলত কর থেকে তৈরি হয়?", ["রাস্তা, সেতু, সরকারি স্কুল আর হাসপাতাল", "ব্যক্তিগত খেলনা", "তোমার নিজের সাইকেল", "দোকানের মিষ্টি"],
        "সবাই যা ভাগ করে ব্যবহার করে, তার জন্য সবাই কর দিয়ে অংশ নেয়।"),
    mcq("Why is a bank savings account safer than keeping lots of cash at home?", ["Cash at home can be lost, stolen or burned; the bank keeps it safe and pays interest", "Banks hide money forever", "Home cash earns more interest", "There is no difference"], 0,
        "Bank deposits are also protected by insurance up to a limit.",
        "বাড়িতে অনেক নগদ রাখার চেয়ে ব্যাংকের সঞ্চয়ী অ্যাকাউন্ট নিরাপদ কেন?", ["বাড়ির নগদ হারাতে, চুরি বা পুড়তে পারে; ব্যাংক নিরাপদে রাখে আর সুদ দেয়", "ব্যাংক চিরকাল টাকা লুকিয়ে রাখে", "বাড়ির নগদে বেশি সুদ", "কোনো পার্থক্য নেই"],
        "ব্যাংকের আমানত একটা সীমা পর্যন্ত বিমাতেও সুরক্ষিত।"),
)
