"""Class 4 - Biology: digestion, heart, blood and lungs, senses, grouping living things,
food webs, micro-organisms and hygiene, flowers and seeds, rivers and wildlife around bridges,
and staying healthy and safe on a building site."""
from . import mcq


def pulse(beats, secs):
    per_min = beats * (60 // secs)
    o = list(dict.fromkeys([per_min, beats, beats + 60, per_min * 2, per_min + 10]))[:4]
    return mcq(f"A worker counts {beats} heartbeats in {secs} seconds. What is the pulse per minute?",
               [str(x) for x in o], 0,
               f"60 seconds is {60 // secs} lots of {secs} seconds, so {beats} x {60 // secs} = {per_min} beats a minute.",
               f"একজন কর্মী {secs} সেকেন্ডে {beats}টি হৃৎস্পন্দন গুনলেন। মিনিটে নাড়ির গতি কত?",
               [str(x) for x in o],
               f"60 সেকেন্ডে {secs} সেকেন্ডের {60 // secs}টি ভাগ, তাই {beats} x {60 // secs} = মিনিটে {per_min}টি স্পন্দন।")


def water(people, litres, days):
    total = people * litres * days
    o = list(dict.fromkeys([total, people * litres, total + people, people + litres + days]))[:4]
    return mcq(f"Each of {people} bridge workers needs {litres} litres of drinking water a day on a hot site. How much for {days} days?",
               [f"{x} litres" for x in o], 0,
               f"{people} x {litres} = {people * litres} litres a day; x {days} days = {total} litres. Staying hydrated prevents heat illness.",
               f"গরম নির্মাণস্থলে {people} জন সেতু-কর্মীর প্রত্যেকের দিনে {litres} লিটার খাবার জল লাগে। {days} দিনে কত?",
               [f"{x} লিটার" for x in o],
               f"{people} x {litres} = দিনে {people * litres} লিটার; x {days} দিন = {total} লিটার। পর্যাপ্ত জল খেলে গরমজনিত অসুস্থতা এড়ানো যায়।")


ITEMS = (
    pulse(20, 15), pulse(18, 15), pulse(25, 15), pulse(12, 10), pulse(36, 30),
    water(10, 3, 5), water(25, 4, 3), water(8, 5, 6),
    mcq("What is the job of the digestive system?", ["Breaking food into tiny parts the body can use", "Pumping blood", "Breathing air", "Seeing light"], 0,
        "Digestion turns a meal into nutrients small enough to pass into the blood.",
        "পরিপাকতন্ত্রের কাজ কী?", ["খাবারকে শরীর ব্যবহার করতে পারে এমন ছোট অংশে ভাঙা", "রক্ত পাম্প করা", "শ্বাস নেওয়া", "আলো দেখা"],
        "পরিপাক খাবারকে রক্তে যাওয়ার মতো ছোট পুষ্টিতে বদলায়।"),
    mcq("Where does digestion begin?", ["In the mouth", "In the stomach", "In the lungs", "In the heart"], 0,
        "Teeth chew and saliva starts breaking down starch.",
        "পরিপাক কোথায় শুরু হয়?", ["মুখে", "পাকস্থলীতে", "ফুসফুসে", "হৃৎপিণ্ডে"],
        "দাঁত চিবোয় আর লালা শ্বেতসার ভাঙতে শুরু করে।"),
    mcq("Which tube carries food from the mouth to the stomach?", ["The gullet (oesophagus)", "The windpipe", "A blood vessel", "The spine"], 0,
        "Muscles squeeze food down - it even works upside down!",
        "কোন নল মুখ থেকে পাকস্থলীতে খাবার নেয়?", ["অন্ননালী", "শ্বাসনালী", "রক্তনালী", "মেরুদণ্ড"],
        "পেশি চেপে খাবার নিচে নামায় - উল্টো হয়ে থাকলেও কাজ করে!"),
    mcq("What does the stomach do with food?", ["Churns it with acid and juices", "Pumps it into the lungs", "Turns it into bone", "Nothing"], 0,
        "Stomach acid also kills many germs in food.",
        "পাকস্থলী খাবারের সঙ্গে কী করে?", ["অ্যাসিড আর রস দিয়ে মন্থন করে", "ফুসফুসে পাম্প করে", "হাড়ে বদলায়", "কিছুই না"],
        "পাকস্থলীর অ্যাসিড খাবারের অনেক জীবাণুও মারে।"),
    mcq("Where are most nutrients absorbed into the blood?", ["The small intestine", "The large intestine", "The mouth", "The kidneys"], 0,
        "The small intestine is about 6 m long, folded up inside you.",
        "বেশিরভাগ পুষ্টি কোথায় রক্তে শোষিত হয়?", ["ক্ষুদ্রান্ত্রে", "বৃহদন্ত্রে", "মুখে", "বৃক্কে"],
        "ক্ষুদ্রান্ত্র প্রায় 6 m লম্বা, তোমার ভেতরে ভাঁজ হয়ে আছে।"),
    mcq("What does the large intestine mainly take back from leftover food?", ["Water", "Bone", "Air", "Blood"], 0,
        "What remains leaves the body as waste.",
        "বৃহদন্ত্র অবশিষ্ট খাবার থেকে প্রধানত কী ফেরত নেয়?", ["জল", "হাড়", "বাতাস", "রক্ত"],
        "যা বাকি থাকে, তা বর্জ্য হিসেবে শরীর থেকে বেরোয়।"),
    mcq("Why is fibre (from vegetables and whole grains) good for us?", ["It keeps the digestive system moving well", "It builds muscle only", "It gives sugar rush", "It is not good"], 0,
        "Fibre helps prevent constipation.",
        "আঁশ (সবজি আর গোটা শস্য থেকে) আমাদের জন্য ভালো কেন?", ["পরিপাকতন্ত্র ঠিকঠাক চালু রাখে", "শুধু পেশি গড়ে", "হঠাৎ চিনি দেয়", "ভালো নয়"],
        "আঁশ কোষ্ঠকাঠিন্য ঠেকাতে সাহায্য করে।"),
    mcq("What is the heart's job?", ["Pumping blood around the body", "Digesting food", "Thinking", "Making bones"], 0,
        "Your heart beats about 100,000 times a day.",
        "হৃৎপিণ্ডের কাজ কী?", ["সারা শরীরে রক্ত পাম্প করা", "খাবার হজম করা", "চিন্তা করা", "হাড় তৈরি করা"],
        "তোমার হৃৎপিণ্ড দিনে প্রায় 1,00,000 বার স্পন্দিত হয়।"),
    mcq("What does blood carry around the body?", ["Oxygen and nutrients, and it takes away waste", "Only water", "Only food lumps", "Air bubbles"], 0,
        "Blood is the body's delivery and waste-collection service - like a city's roads and bridges.",
        "রক্ত সারা শরীরে কী বয়ে নেয়?", ["অক্সিজেন আর পুষ্টি, আর বর্জ্য সরিয়ে আনে", "শুধু জল", "শুধু খাবারের দলা", "বাতাসের বুদবুদ"],
        "রক্ত শরীরের ডেলিভারি আর বর্জ্য-সংগ্রহ পরিষেবা - শহরের রাস্তা আর সেতুর মতো।"),
    mcq("Which blood vessels carry blood away from the heart?", ["Arteries", "Veins", "Nerves", "Tendons"], 0,
        "Arteries have thick walls to handle high pressure.",
        "কোন রক্তনালী হৃৎপিণ্ড থেকে রক্ত দূরে নিয়ে যায়?", ["ধমনি", "শিরা", "স্নায়ু", "কণ্ডরা"],
        "উচ্চ চাপ সামলাতে ধমনির দেওয়াল মোটা।"),
    mcq("Which blood vessels bring blood back to the heart?", ["Veins", "Arteries", "Muscles", "Bones"], 0,
        "Veins have valves so blood does not flow backwards.",
        "কোন রক্তনালী রক্ত হৃৎপিণ্ডে ফেরায়?", ["শিরা", "ধমনি", "পেশি", "হাড়"],
        "শিরায় কপাটিকা থাকে, যাতে রক্ত উল্টো দিকে না যায়।"),
    mcq("What are the tiniest blood vessels called?", ["Capillaries", "Arteries", "Veins", "Ribs"], 0,
        "Capillaries are thinner than a hair and reach every cell.",
        "সবচেয়ে ক্ষুদ্র রক্তনালীকে কী বলে?", ["কৈশিক জালিকা", "ধমনি", "শিরা", "পাঁজর"],
        "কৈশিক জালিকা চুলের চেয়েও সরু আর প্রতিটি কোষে পৌঁছায়।"),
    mcq("Why does your heart beat faster when you climb stairs?", ["Muscles need more oxygen, so more blood is pumped", "The heart gets cold", "Stairs are magnetic", "To make noise"], 0,
        "Exercise raises the pulse; regular exercise makes the heart stronger.",
        "সিঁড়ি চড়লে হৃৎস্পন্দন দ্রুত হয় কেন?", ["পেশির বেশি অক্সিজেন লাগে, তাই বেশি রক্ত পাম্প হয়", "হৃৎপিণ্ড ঠান্ডা হয়", "সিঁড়ি চুম্বকীয়", "শব্দ করতে"],
        "ব্যায়ামে নাড়ি দ্রুত হয়; নিয়মিত ব্যায়াম হৃৎপিণ্ডকে শক্ত করে।"),
    mcq("Where can you feel your pulse easily?", ["On the inside of your wrist", "On your elbow bone", "On your hair", "On your fingernail"], 0,
        "Press gently with two fingers - not your thumb.",
        "কোথায় সহজে নাড়ি অনুভব করা যায়?", ["কবজির ভেতরের দিকে", "কনুইয়ের হাড়ে", "চুলে", "নখে"],
        "দুটো আঙুল দিয়ে আলতো চাপো - বুড়ো আঙুল নয়।"),
    mcq("What is the job of the lungs?", ["Taking oxygen into the blood and getting rid of carbon dioxide", "Pumping blood", "Digesting food", "Holding up the body"], 0,
        "Tiny air sacs pass oxygen into capillaries.",
        "ফুসফুসের কাজ কী?", ["রক্তে অক্সিজেন নেওয়া আর কার্বন ডাই-অক্সাইড বের করা", "রক্ত পাম্প করা", "খাবার হজম", "শরীর ধরে রাখা"],
        "ছোট্ট বায়ুথলি কৈশিক জালিকায় অক্সিজেন পাঠায়।"),
    mcq("What protects the heart and lungs?", ["The rib cage", "The skull", "The kneecap", "The hip bone"], 0,
        "Ribs form a strong, springy cage - a natural truss!",
        "হৃৎপিণ্ড আর ফুসফুস কে রক্ষা করে?", ["পাঁজরের খাঁচা", "মাথার খুলি", "হাঁটুর বাটি", "কোমরের হাড়"],
        "পাঁজর একটা শক্ত, স্থিতিস্থাপক খাঁচা - প্রাকৃতিক ট্রাস!"),
    mcq("Which muscle under the lungs helps you breathe?", ["The diaphragm", "The biceps", "The heart", "The tongue"], 0,
        "When the diaphragm pulls down, air rushes into the lungs.",
        "ফুসফুসের নিচের কোন পেশি শ্বাস নিতে সাহায্য করে?", ["মধ্যচ্ছদা", "বাইসেপ", "হৃৎপিণ্ড", "জিভ"],
        "মধ্যচ্ছদা নিচে নামলে বাতাস ফুসফুসে ঢোকে।"),
    mcq("Why is smoking harmful?", ["It damages the lungs and heart", "It makes lungs stronger", "It cleans the air", "It is not harmful"], 0,
        "Smoke clogs the air sacs and harms blood vessels.",
        "ধূমপান ক্ষতিকর কেন?", ["ফুসফুস আর হৃৎপিণ্ডের ক্ষতি করে", "ফুসফুস শক্ত করে", "বাতাস পরিষ্কার করে", "ক্ষতিকর নয়"],
        "ধোঁয়া বায়ুথলি বন্ধ করে আর রক্তনালীর ক্ষতি করে।"),
    mcq("Why do workers cutting concrete wear dust masks?", ["Fine dust can damage the lungs", "Masks keep faces warm", "To hide their faces", "Dust is good for lungs"], 0,
        "Concrete and stone dust contain tiny particles that harm lungs over time.",
        "কংক্রিট কাটার কর্মীরা ধুলোর মুখোশ পরেন কেন?", ["সূক্ষ্ম ধুলো ফুসফুসের ক্ষতি করতে পারে", "মুখ গরম রাখতে", "মুখ লুকাতে", "ধুলো ফুসফুসের জন্য ভালো"],
        "কংক্রিট আর পাথরের ধুলোয় ক্ষুদ্র কণা থাকে, যা ধীরে ধীরে ফুসফুসের ক্ষতি করে।"),
    mcq("Which part of the body controls all the others?", ["The brain", "The stomach", "The hand", "The skin"], 0,
        "The brain sends and receives messages through nerves.",
        "শরীরের কোন অঙ্গ বাকি সবাইকে নিয়ন্ত্রণ করে?", ["মস্তিষ্ক", "পাকস্থলী", "হাত", "ত্বক"],
        "মস্তিষ্ক স্নায়ুর মাধ্যমে বার্তা পাঠায় আর পায়।"),
    mcq("How do messages travel from your fingers to your brain?", ["Along nerves", "Through blood only", "Through bones", "Through air"], 0,
        "Nerves carry tiny electrical signals very fast.",
        "আঙুল থেকে মস্তিষ্কে বার্তা যায় কীভাবে?", ["স্নায়ু বরাবর", "শুধু রক্ত দিয়ে", "হাড় দিয়ে", "বাতাস দিয়ে"],
        "স্নায়ু খুব দ্রুত ছোট্ট বৈদ্যুতিক সংকেত বয়।"),
    mcq("Why do construction workers wear hard hats?", ["To protect the skull and brain from falling objects", "To keep hair tidy", "To look taller", "For the sun only"], 0,
        "Even a small bolt dropped from height can cause serious injury.",
        "নির্মাণ-কর্মীরা শক্ত টুপি (হেলমেট) পরেন কেন?", ["পড়ন্ত জিনিস থেকে খুলি আর মস্তিষ্ক রক্ষা করতে", "চুল পরিপাটি রাখতে", "লম্বা দেখাতে", "শুধু রোদের জন্য"],
        "উঁচু থেকে পড়া ছোট একটা বল্টুও গুরুতর আঘাত করতে পারে।"),
    mcq("How do our eyes see things?", ["Light enters the eye and the brain makes a picture", "Eyes shoot out light", "Eyes hear sounds", "Eyes smell colours"], 0,
        "Light bounces off objects into our eyes.",
        "আমাদের চোখ কীভাবে দেখে?", ["আলো চোখে ঢোকে আর মস্তিষ্ক ছবি তৈরি করে", "চোখ আলো ছোড়ে", "চোখ শব্দ শোনে", "চোখ রঙের গন্ধ পায়"],
        "আলো বস্তু থেকে প্রতিফলিত হয়ে চোখে আসে।"),
    mcq("What does the pupil (black centre of the eye) do in bright light?", ["Gets smaller to let in less light", "Gets bigger", "Turns blue", "Closes forever"], 0,
        "In the dark it widens to collect more light.",
        "উজ্জ্বল আলোয় তারারন্ধ্র (চোখের কালো মাঝখান) কী করে?", ["ছোট হয়ে কম আলো ঢুকতে দেয়", "বড় হয়", "নীল হয়", "চিরকাল বন্ধ হয়"],
        "অন্ধকারে বেশি আলো ধরতে চওড়া হয়।"),
    mcq("Why do welders wear dark face shields?", ["The welding light is so bright it can damage eyes", "To look scary", "To keep warm", "To see in the dark"], 0,
        "Welding arcs give off strong light and invisible UV rays.",
        "ঝালাইকারীরা কালো মুখ-ঢাকনা পরেন কেন?", ["ঝালাইয়ের আলো এত উজ্জ্বল যে চোখের ক্ষতি করতে পারে", "ভয় দেখাতে", "গরম থাকতে", "অন্ধকারে দেখতে"],
        "ঝালাইয়ের শিখা জোরালো আলো আর অদৃশ্য অতিবেগুনি রশ্মি ছাড়ে।"),
    mcq("How do we hear sounds?", ["Vibrations enter the ear and the eardrum passes them on to the brain", "Ears make sounds", "The nose hears", "Eyes hear"], 0,
        "The eardrum vibrates like a drum skin.",
        "আমরা কীভাবে শব্দ শুনি?", ["কম্পন কানে ঢোকে আর কানের পর্দা তা মস্তিষ্কে পাঠায়", "কান শব্দ তৈরি করে", "নাক শোনে", "চোখ শোনে"],
        "কানের পর্দা ঢোলের চামড়ার মতো কাঁপে।"),
    mcq("Why do workers using loud drills wear ear defenders?", ["Very loud noise can permanently damage hearing", "To listen to music", "To keep ears clean", "Drills are quiet"], 0,
        "Hearing damage from noise cannot be undone.",
        "জোরালো ড্রিল চালানো কর্মীরা কান-রক্ষাকারী পরেন কেন?", ["খুব জোরালো শব্দ স্থায়ীভাবে শ্রবণশক্তির ক্ষতি করতে পারে", "গান শুনতে", "কান পরিষ্কার রাখতে", "ড্রিল নিঃশব্দ"],
        "শব্দে শ্রবণশক্তির ক্ষতি আর ফেরানো যায় না।"),
    mcq("Which sense uses the tongue?", ["Taste", "Sight", "Hearing", "Touch only"], 0,
        "Taste buds detect sweet, salty, sour, bitter and savoury.",
        "কোন ইন্দ্রিয় জিভ ব্যবহার করে?", ["স্বাদ", "দৃষ্টি", "শ্রবণ", "শুধু স্পর্শ"],
        "স্বাদকোরক মিষ্টি, নোনতা, টক, তেতো আর মশলাদার স্বাদ বোঝে।"),
    mcq("Why can smell warn us of danger?", ["We can smell smoke, gas leaks or spoiled food", "Smell lets us see", "Smell makes us strong", "It cannot"], 0,
        "Cooking gas has a strong smell added on purpose so leaks are noticed.",
        "গন্ধ আমাদের বিপদ সম্পর্কে সতর্ক করে কেন?", ["আমরা ধোঁয়া, গ্যাস লিক বা নষ্ট খাবারের গন্ধ পাই", "গন্ধে দেখা যায়", "গন্ধ শক্তিশালী করে", "করে না"],
        "রান্নার গ্যাসে ইচ্ছে করে কড়া গন্ধ মেশানো হয়, যাতে লিক টের পাওয়া যায়।"),
    mcq("What is a 'vertebrate'?", ["An animal with a backbone", "An animal without a backbone", "A plant", "A rock"], 0,
        "Fish, amphibians, reptiles, birds and mammals are vertebrates.",
        "'মেরুদণ্ডী' কী?", ["মেরুদণ্ডওয়ালা প্রাণী", "মেরুদণ্ডহীন প্রাণী", "উদ্ভিদ", "পাথর"],
        "মাছ, উভচর, সরীসৃপ, পাখি আর স্তন্যপায়ী মেরুদণ্ডী।"),
    mcq("Which of these is an invertebrate (no backbone)?", ["Earthworm", "Frog", "Cat", "Pigeon"], 0,
        "Most animals on Earth are invertebrates - insects, worms, snails and more.",
        "এগুলোর কোনটা অমেরুদণ্ডী (মেরুদণ্ড নেই)?", ["কেঁচো", "ব্যাঙ", "বিড়াল", "পায়রা"],
        "পৃথিবীর বেশিরভাগ প্রাণী অমেরুদণ্ডী - পোকা, কৃমি, শামুক আর আরও।"),
    mcq("Which group of animals breathes with gills?", ["Fish", "Birds", "Mammals", "Reptiles"], 0,
        "Gills take oxygen from water.",
        "কোন প্রাণীগোষ্ঠী ফুলকা দিয়ে শ্বাস নেয়?", ["মাছ", "পাখি", "স্তন্যপায়ী", "সরীসৃপ"],
        "ফুলকা জল থেকে অক্সিজেন নেয়।"),
    mcq("Frogs are amphibians. What does that mean?", ["They live part of their life in water and part on land", "They only fly", "They have feathers", "They never lay eggs"], 0,
        "Tadpoles live in water; adult frogs can live on land.",
        "ব্যাঙ উভচর। এর মানে কী?", ["জীবনের কিছু অংশ জলে আর কিছু ডাঙায় কাটায়", "শুধু ওড়ে", "পালক আছে", "কখনো ডিম পাড়ে না"],
        "ব্যাঙাচি জলে থাকে; পূর্ণবয়স্ক ব্যাঙ ডাঙায় থাকতে পারে।"),
    mcq("Which feature is found ONLY in birds?", ["Feathers", "Eggs", "A backbone", "Lungs"], 0,
        "Many animals lay eggs, but only birds have feathers.",
        "কোন বৈশিষ্ট্য শুধু পাখিদেরই আছে?", ["পালক", "ডিম", "মেরুদণ্ড", "ফুসফুস"],
        "অনেক প্রাণী ডিম পাড়ে, কিন্তু পালক শুধু পাখির।"),
    mcq("What is special about mammals?", ["They have hair and feed their babies milk", "They all lay eggs in water", "They have scales and gills", "They have six legs"], 0,
        "Humans, cows, whales and bats are mammals.",
        "স্তন্যপায়ীদের বিশেষত্ব কী?", ["লোম আছে আর বাচ্চাদের দুধ খাওয়ায়", "সবাই জলে ডিম পাড়ে", "আঁশ আর ফুলকা আছে", "ছয়টা পা আছে"],
        "মানুষ, গরু, তিমি আর বাদুড় স্তন্যপায়ী।"),
    mcq("What is a 'classification key'?", ["A set of yes/no questions to identify a living thing", "A key for a door", "A piano key", "A map"], 0,
        "'Does it have legs? Does it have feathers?' - each answer narrows it down.",
        "'শ্রেণিবিন্যাসের চাবি' কী?", ["জীব শনাক্ত করার হ্যাঁ/না প্রশ্নের তালিকা", "দরজার চাবি", "পিয়ানোর চাবি", "মানচিত্র"],
        "'পা আছে? পালক আছে?' - প্রতিটি উত্তর সম্ভাবনা কমায়।"),
    mcq("In a river food web, what usually starts every chain?", ["Plants and algae using sunlight", "Big fish", "Herons", "Crocodiles"], 0,
        "Producers make food from sunlight; everything else depends on them.",
        "নদীর খাদ্যজালে সাধারণত প্রতিটি শৃঙ্খল কী দিয়ে শুরু হয়?", ["সূর্যালোক ব্যবহারকারী উদ্ভিদ আর শৈবাল", "বড় মাছ", "বক", "কুমির"],
        "উৎপাদক সূর্যালোক থেকে খাদ্য তৈরি করে; বাকিরা তাদের উপর নির্ভরশীল।"),
    mcq("What is a 'predator'?", ["An animal that hunts and eats other animals", "An animal that is hunted", "A plant", "A rock"], 0,
        "A kingfisher is a predator; the small fish it catches is its prey.",
        "'শিকারি প্রাণী' কী?", ["যে প্রাণী অন্য প্রাণী শিকার করে খায়", "যে প্রাণী শিকার হয়", "উদ্ভিদ", "পাথর"],
        "মাছরাঙা শিকারি; যে ছোট মাছ ধরে, সেটা তার শিকার।"),
    mcq("If all the small fish in a river died, what would happen to the herons that eat them?", ["They would go hungry or leave", "They would grow bigger", "Nothing at all", "They would eat rocks"], 0,
        "Changes in one part of a food web affect the rest.",
        "নদীর সব ছোট মাছ মরে গেলে, যে বক তাদের খায় তাদের কী হবে?", ["খিদেয় থাকবে বা চলে যাবে", "আরও বড় হবে", "কিছুই না", "পাথর খাবে"],
        "খাদ্যজালের এক অংশের পরিবর্তন বাকিদেরও প্রভাবিত করে।"),
    mcq("What are micro-organisms?", ["Living things too small to see without a microscope", "Very small rocks", "Tiny toys", "Baby animals"], 0,
        "Bacteria, viruses and some fungi are micro-organisms.",
        "অণুজীব কী?", ["অণুবীক্ষণ ছাড়া দেখা যায় না এমন ক্ষুদ্র জীব", "খুব ছোট পাথর", "ছোট্ট খেলনা", "বাচ্চা প্রাণী"],
        "ব্যাকটেরিয়া, ভাইরাস আর কিছু ছত্রাক অণুজীব।"),
    mcq("Are all micro-organisms harmful?", ["No - some help make yoghurt and bread, and break down waste", "Yes, all of them", "They do not exist", "Only in winter"], 0,
        "Helpful microbes make curd from milk and compost from leaves.",
        "সব অণুজীব কি ক্ষতিকর?", ["না - কিছু দই আর রুটি তৈরি আর বর্জ্য ভাঙতে সাহায্য করে", "হ্যাঁ, সবাই", "এদের অস্তিত্বই নেই", "শুধু শীতকালে"],
        "উপকারী জীবাণু দুধ থেকে দই আর পাতা থেকে সার বানায়।"),
    mcq("Which micro-organism helps turn milk into curd (yoghurt)?", ["Bacteria", "Viruses that cause flu", "Mould on bread", "None"], 0,
        "Friendly bacteria turn milk sugar into acid, thickening it.",
        "কোন অণুজীব দুধকে দই বানাতে সাহায্য করে?", ["ব্যাকটেরিয়া", "ফ্লু-এর ভাইরাস", "রুটির ছত্রাক", "কোনোটাই না"],
        "উপকারী ব্যাকটেরিয়া দুধের চিনিকে অ্যাসিডে বদলে ঘন করে।"),
    mcq("What are 'decomposers'?", ["Living things that break down dead plants and animals", "Animals that only hunt", "Rocks", "Machines"], 0,
        "Fungi, bacteria and worms recycle nutrients back into the soil.",
        "'বিয়োজক' কী?", ["যে জীবেরা মরা উদ্ভিদ আর প্রাণী ভেঙে ফেলে", "যে প্রাণী শুধু শিকার করে", "পাথর", "যন্ত্র"],
        "ছত্রাক, ব্যাকটেরিয়া আর কেঁচো পুষ্টি আবার মাটিতে ফেরায়।"),
    mcq("Why do wooden bridge planks eventually rot?", ["Fungi and bacteria feed on damp wood", "Wood melts in rain", "Planks rust", "Cars eat them"], 0,
        "Keeping wood dry and treated slows rot.",
        "কাঠের সেতুর তক্তা শেষে পচে যায় কেন?", ["ছত্রাক আর ব্যাকটেরিয়া ভেজা কাঠ খায়", "বৃষ্টিতে কাঠ গলে", "তক্তায় মরচে ধরে", "গাড়ি খায়"],
        "কাঠ শুকনো আর শোধিত রাখলে পচন ধীর হয়।"),
    mcq("What is the best way to stop germs spreading when you cough?", ["Cough into a tissue or your elbow, then wash hands", "Cough on your hands and touch things", "Cough at friends", "Hold your breath forever"], 0,
        "Catch it, bin it, kill it.",
        "কাশির সময় জীবাণু ছড়ানো আটকানোর সবচেয়ে ভালো উপায় কী?", ["টিস্যু বা কনুইয়ে কাশো, তারপর হাত ধোও", "হাতে কেশে জিনিস ছোঁও", "বন্ধুদের দিকে কাশো", "চিরকাল শ্বাস আটকে রাখো"],
        "ধরো, ফেলো, মারো।"),
    mcq("Why should you wash your hands with soap after using the toilet?", ["Soap removes germs that could make people ill", "Soap makes hands heavier", "It is just a habit", "Water alone is magic"], 0,
        "Rub for at least 20 seconds, between fingers too.",
        "শৌচাগার ব্যবহারের পর সাবান দিয়ে হাত ধোয়া উচিত কেন?", ["সাবান অসুখ ছড়ানো জীবাণু সরায়", "সাবান হাত ভারী করে", "শুধু অভ্যাস", "শুধু জল জাদুকরী"],
        "অন্তত 20 সেকেন্ড ঘষো, আঙুলের ফাঁকেও।"),
    mcq("Why must a building site have clean toilets and drinking water?", ["To stop diseases spreading among workers", "To make the site look nice", "For visitors only", "They are not needed"], 0,
        "Good sanitation keeps workers healthy and work on schedule.",
        "নির্মাণস্থলে পরিষ্কার শৌচাগার আর খাবার জল থাকতে হবে কেন?", ["কর্মীদের মধ্যে রোগ ছড়ানো আটকাতে", "জায়গাটা সুন্দর দেখাতে", "শুধু দর্শনার্থীদের জন্য", "দরকার নেই"],
        "ভালো স্যানিটেশন কর্মীদের সুস্থ আর কাজ সময়মতো রাখে।"),
    mcq("Why do people get vaccinated?", ["Vaccines train the body to fight certain diseases", "Vaccines are food", "To change eye colour", "To grow taller"], 0,
        "Vaccines have saved millions of lives.",
        "মানুষ টিকা নেয় কেন?", ["টিকা শরীরকে নির্দিষ্ট রোগের বিরুদ্ধে লড়তে শেখায়", "টিকা খাবার", "চোখের রং বদলাতে", "লম্বা হতে"],
        "টিকা লক্ষ লক্ষ প্রাণ বাঁচিয়েছে।"),
    mcq("Why is still, dirty water near a site a health risk?", ["Mosquitoes breed in it and can spread malaria and dengue", "It makes the ground stronger", "Fish like it", "It is not a risk"], 0,
        "Cover tanks and drain puddles to stop mosquitoes.",
        "নির্মাণস্থলের কাছে জমা নোংরা জল স্বাস্থ্যের ঝুঁকি কেন?", ["তাতে মশা জন্মায় আর ম্যালেরিয়া ও ডেঙ্গি ছড়াতে পারে", "মাটি শক্ত করে", "মাছ পছন্দ করে", "ঝুঁকি নেই"],
        "মশা থামাতে ট্যাংক ঢাকো আর জমা জল বের করে দাও।"),
    mcq("What is the job of a flower?", ["To make seeds for new plants", "To store water only", "To hold the plant up", "To scare animals"], 0,
        "Flowers attract pollinators so seeds can form.",
        "ফুলের কাজ কী?", ["নতুন গাছের জন্য বীজ তৈরি করা", "শুধু জল জমানো", "গাছ ধরে রাখা", "প্রাণী তাড়ানো"],
        "ফুল পরাগবাহক টানে, যাতে বীজ তৈরি হয়।"),
    mcq("Why are bees so important for farmers?", ["They pollinate many crops so fruit and seeds form", "They eat pests only", "They plough fields", "They are not important"], 0,
        "Without pollinators we would have far less fruit and vegetables.",
        "চাষিদের জন্য মৌমাছি এত জরুরি কেন?", ["অনেক ফসলের পরাগায়ন করে যাতে ফল আর বীজ হয়", "শুধু পোকা খায়", "জমি চষে", "জরুরি নয়"],
        "পরাগবাহক না থাকলে আমরা অনেক কম ফল আর সবজি পেতাম।"),
    mcq("How are dandelion and cotton seeds spread?", ["By the wind - they have fluffy parachutes", "By swimming", "By exploding only", "They never spread"], 0,
        "Wind can carry them far away to new places.",
        "কিভাবে ড্যান্ডেলিয়ন আর শিমুল তুলোর বীজ ছড়ায়?", ["বাতাসে - তাদের তুলতুলে প্যারাশুট আছে", "সাঁতরে", "শুধু ফেটে", "কখনো ছড়ায় না"],
        "বাতাস তাদের অনেক দূরে নতুন জায়গায় নিয়ে যায়।"),
    mcq("How are coconut seeds often spread?", ["Floating on water", "Carried by bees", "Blown like dust", "Buried by worms"], 0,
        "Coconuts can float across seas to new islands.",
        "নারকেলের বীজ প্রায়ই কীভাবে ছড়ায়?", ["জলে ভেসে", "মৌমাছির বয়ে", "ধুলোর মতো উড়ে", "কেঁচোর পুঁতে"],
        "নারকেল সমুদ্র পেরিয়ে নতুন দ্বীপে ভেসে যেতে পারে।"),
    mcq("Why do birds help spread seeds?", ["They eat fruit and drop the seeds elsewhere", "They plant seeds with their feet", "They do not", "Seeds stick to their eggs"], 0,
        "Seeds pass through and grow far from the parent tree.",
        "পাখি বীজ ছড়াতে সাহায্য করে কেন?", ["ফল খেয়ে অন্য জায়গায় বীজ ফেলে", "পায়ে বীজ পোঁতে", "করে না", "ডিমে বীজ লেগে থাকে"],
        "বীজ পেরিয়ে এসে মূল গাছ থেকে দূরে জন্মায়।"),
    mcq("What is a 'habitat'?", ["The natural home of a living thing", "A type of food", "A building", "A kind of rock"], 0,
        "Rivers, forests and mangroves are habitats.",
        "'বাসস্থান' কী?", ["কোনো জীবের প্রাকৃতিক ঘর", "এক রকম খাবার", "একটা ভবন", "এক রকম পাথর"],
        "নদী, বন আর ম্যানগ্রোভ বাসস্থান।"),
    mcq("Why do engineers study wildlife before building a bridge over a river?", ["To protect fish, birds and plants that live there", "To count fish for dinner", "Animals pay tolls", "It is not needed"], 0,
        "Environmental surveys help plan bridges that harm nature as little as possible.",
        "নদীর উপর সেতু বানানোর আগে প্রকৌশলীরা বন্যপ্রাণী নিয়ে গবেষণা করেন কেন?", ["সেখানে থাকা মাছ, পাখি আর গাছ রক্ষা করতে", "রাতের খাবারের জন্য মাছ গুনতে", "প্রাণীরা টোল দেয়", "দরকার নেই"],
        "পরিবেশ-সমীক্ষা এমন সেতুর পরিকল্পনায় সাহায্য করে, যা প্রকৃতির যত কম সম্ভব ক্ষতি করে।"),
    mcq("Why might builders avoid driving piles into a river during fish breeding season?", ["Loud vibrations can disturb fish and their eggs", "Fish steal tools", "Water is too wet", "No reason"], 0,
        "Timing noisy work carefully protects wildlife.",
        "মাছের প্রজনন-মরসুমে নির্মাতারা নদীতে খুঁটি পোঁতা এড়াতে পারেন কেন?", ["জোরালো কম্পন মাছ আর তাদের ডিমের ক্ষতি করতে পারে", "মাছ যন্ত্র চুরি করে", "জল খুব ভেজা", "কোনো কারণ নেই"],
        "শব্দের কাজ সময় বুঝে করলে বন্যপ্রাণী রক্ষা পায়।"),
    mcq("What is a 'wildlife crossing' (green bridge)?", ["A bridge or tunnel that lets animals cross busy roads safely", "A bridge painted green", "A zoo", "A bridge for trains only"], 0,
        "Green bridges with soil and plants reconnect forests split by highways.",
        "'বন্যপ্রাণী পারাপার' (সবুজ সেতু) কী?", ["যে সেতু বা সুড়ঙ্গ প্রাণীদের ব্যস্ত রাস্তা নিরাপদে পার হতে দেয়", "সবুজ রং করা সেতু", "চিড়িয়াখানা", "শুধু ট্রেনের সেতু"],
        "মাটি আর গাছসহ সবুজ সেতু মহাসড়কে ভাগ হওয়া বনকে আবার জোড়ে।"),
    mcq("What are mangroves?", ["Trees that grow in salty coastal water", "Desert cacti", "Mountain pines", "Water lilies"], 0,
        "The Sundarbans is the world's largest mangrove forest.",
        "ম্যানগ্রোভ কী?", ["উপকূলের নোনা জলে জন্মানো গাছ", "মরুভূমির ক্যাকটাস", "পাহাড়ি পাইন", "শাপলা"],
        "সুন্দরবন পৃথিবীর বৃহত্তম ম্যানগ্রোভ বন।"),
    mcq("How do mangroves protect coasts and bridges?", ["Their roots slow waves and storm surges", "They attract lightning", "They push water uphill", "They do not"], 0,
        "Healthy mangroves reduce cyclone damage.",
        "ম্যানগ্রোভ উপকূল আর সেতু কীভাবে রক্ষা করে?", ["তাদের শিকড় ঢেউ আর জলোচ্ছ্বাস ধীর করে", "বজ্র টানে", "জলকে উপরে ঠেলে", "করে না"],
        "সুস্থ ম্যানগ্রোভ ঘূর্ণিঝড়ের ক্ষতি কমায়।"),
    mcq("Which animal lives in the Sundarbans and is India's national animal?", ["Royal Bengal tiger", "Polar bear", "Kangaroo", "Penguin"], 0,
        "Tigers there can even swim between islands.",
        "কোন প্রাণী সুন্দরবনে থাকে আর ভারতের জাতীয় পশু?", ["রয়েল বেঙ্গল টাইগার", "মেরু ভালুক", "ক্যাঙারু", "পেঙ্গুইন"],
        "সেখানকার বাঘ দ্বীপের মধ্যে সাঁতরেও যেতে পারে।"),
    mcq("Why are tree roots good near riverbanks?", ["They hold soil together and stop erosion", "They make the river dirty", "They dig holes", "They are bad"], 0,
        "Bank erosion can undermine bridge foundations - plants help.",
        "নদীর পাড়ে গাছের শিকড় ভালো কেন?", ["মাটি ধরে রাখে আর ক্ষয় আটকায়", "নদী নোংরা করে", "গর্ত খোঁড়ে", "খারাপ"],
        "পাড়ের ক্ষয় সেতুর ভিত দুর্বল করতে পারে - গাছ সাহায্য করে।"),
    mcq("What do plants give off that animals need to breathe?", ["Oxygen", "Carbon dioxide", "Nitrogen only", "Smoke"], 0,
        "Plants take in carbon dioxide and release oxygen in sunlight.",
        "উদ্ভিদ কী ছাড়ে যা প্রাণীদের শ্বাসের জন্য দরকার?", ["অক্সিজেন", "কার্বন ডাই-অক্সাইড", "শুধু নাইট্রোজেন", "ধোঁয়া"],
        "রোদে উদ্ভিদ কার্বন ডাই-অক্সাইড নেয় আর অক্সিজেন ছাড়ে।"),
    mcq("Why do construction projects often plant new trees when they finish?", ["To replace trees cut down and restore habitats", "Trees hold up bridges", "To hide the bridge", "It is never done"], 0,
        "Replanting helps wildlife, air and soil recover.",
        "নির্মাণ প্রকল্প শেষে প্রায়ই নতুন গাছ লাগানো হয় কেন?", ["কাটা গাছের জায়গা পূরণ আর বাসস্থান ফেরাতে", "গাছ সেতু ধরে রাখে", "সেতু লুকাতে", "কখনো করা হয় না"],
        "আবার গাছ লাগালে বন্যপ্রাণী, বাতাস আর মাটি সেরে ওঠে।"),
    mcq("What is 'heat exhaustion'?", ["Feeling faint, tired and sick from too much heat and too little water", "Feeling cold", "A broken bone", "A sunburn on the hair"], 0,
        "Rest in shade and drink water; seek help if it gets worse.",
        "'গরমে অবসাদ' কী?", ["বেশি গরম আর কম জলে দুর্বল, ক্লান্ত আর অসুস্থ বোধ", "ঠান্ডা লাগা", "হাড় ভাঙা", "চুলে রোদে পোড়া"],
        "ছায়ায় বিশ্রাম নাও আর জল খাও; খারাপ হলে সাহায্য নাও।"),
    mcq("Why should outdoor workers wear sunscreen and long sleeves?", ["To protect skin from sunburn and UV damage", "To keep cool by magic", "To look smart only", "No reason"], 0,
        "Strong sun can burn skin within minutes.",
        "বাইরের কর্মীদের সানস্ক্রিন আর লম্বা হাতা পরা উচিত কেন?", ["রোদে পোড়া আর অতিবেগুনি রশ্মির ক্ষতি থেকে ত্বক বাঁচাতে", "জাদুতে ঠান্ডা থাকতে", "শুধু স্মার্ট দেখাতে", "কোনো কারণ নেই"],
        "কড়া রোদ মিনিটের মধ্যে ত্বক পোড়াতে পারে।"),
    mcq("Why should you bend your knees, not your back, when lifting a heavy box?", ["Leg muscles are strong and it protects your spine", "It looks funny", "Backs never get hurt", "It makes the box lighter"], 0,
        "Back injuries are common on building sites - lift safely.",
        "ভারী বাক্স তোলার সময় পিঠ নয়, হাঁটু ভাঁজ করা উচিত কেন?", ["পায়ের পেশি শক্ত আর মেরুদণ্ড রক্ষা পায়", "মজার দেখায়", "পিঠে কখনো আঘাত লাগে না", "বাক্স হালকা হয়"],
        "নির্মাণস্থলে পিঠের আঘাত সাধারণ - নিরাপদে তোলো।"),
    mcq("What should you do first if someone gets a small cut?", ["Wash it gently with clean water and cover it", "Rub dirt in it", "Ignore it forever", "Pour paint on it"], 0,
        "Cleaning and covering stops germs getting in.",
        "কারও ছোট কেটে গেলে প্রথমে কী করবে?", ["পরিষ্কার জলে আলতো করে ধুয়ে ঢেকে দাও", "ময়লা ঘষো", "চিরকাল উপেক্ষা করো", "রং ঢালো"],
        "পরিষ্কার করে ঢাকলে জীবাণু ঢোকে না।"),
    mcq("What is in a first aid kit?", ["Bandages, plasters, antiseptic and gloves", "Hammers and nails", "Food and drinks only", "Toys"], 0,
        "Every building site must have a first aid kit and a trained first aider.",
        "প্রাথমিক চিকিৎসার বাক্সে কী থাকে?", ["ব্যান্ডেজ, প্লাস্টার, জীবাণুনাশক আর দস্তানা", "হাতুড়ি আর পেরেক", "শুধু খাবার আর পানীয়", "খেলনা"],
        "প্রতিটি নির্মাণস্থলে প্রাথমিক চিকিৎসার বাক্স আর প্রশিক্ষিত সাহায্যকারী থাকতে হয়।"),
    mcq("What is a balanced diet?", ["Eating the right amounts of different food groups", "Eating only sweets", "Eating only one food", "Skipping meals"], 0,
        "Carbohydrates, proteins, fats, vitamins, minerals, fibre and water.",
        "সুষম খাদ্য কী?", ["বিভিন্ন খাদ্যগোষ্ঠী সঠিক পরিমাণে খাওয়া", "শুধু মিষ্টি খাওয়া", "শুধু একটা খাবার খাওয়া", "খাবার বাদ দেওয়া"],
        "শর্করা, প্রোটিন, স্নেহপদার্থ, ভিটামিন, খনিজ, আঁশ আর জল।"),
    mcq("Which food group gives quick energy for hard physical work?", ["Carbohydrates like rice, roti and potatoes", "Only vitamins", "Only water", "Salt"], 0,
        "Builders doing heavy work need plenty of energy food.",
        "কঠিন শারীরিক কাজের জন্য কোন খাদ্যগোষ্ঠী দ্রুত শক্তি দেয়?", ["শর্করা, যেমন ভাত, রুটি আর আলু", "শুধু ভিটামিন", "শুধু জল", "লবণ"],
        "ভারী কাজ করা নির্মাতাদের প্রচুর শক্তির খাবার লাগে।"),
    mcq("Which food group helps repair muscles after hard work?", ["Proteins like dal, eggs, fish and milk", "Sugar", "Cooking oil only", "Salt"], 0,
        "Proteins are the body's building blocks.",
        "কঠিন কাজের পর কোন খাদ্যগোষ্ঠী পেশি মেরামতে সাহায্য করে?", ["প্রোটিন, যেমন ডাল, ডিম, মাছ আর দুধ", "চিনি", "শুধু রান্নার তেল", "লবণ"],
        "প্রোটিন শরীরের গঠনের উপাদান।"),
    mcq("Which vitamin does sunlight help our skin make?", ["Vitamin D", "Vitamin C", "Vitamin A", "Vitamin B12"], 0,
        "Vitamin D helps us use calcium for strong bones.",
        "সূর্যালোক আমাদের ত্বককে কোন ভিটামিন তৈরি করতে সাহায্য করে?", ["ভিটামিন D", "ভিটামিন C", "ভিটামিন A", "ভিটামিন B12"],
        "ভিটামিন D হাড় শক্ত করতে ক্যালসিয়াম কাজে লাগাতে সাহায্য করে।"),
    mcq("Which fruits are rich in vitamin C?", ["Oranges, amla and guava", "Bread and rice", "Oil and butter", "Salt and sugar"], 0,
        "Vitamin C helps heal wounds and fight infection.",
        "কোন ফলে ভিটামিন C বেশি?", ["কমলা, আমলকী আর পেয়ারা", "রুটি আর ভাত", "তেল আর মাখন", "লবণ আর চিনি"],
        "ভিটামিন C ক্ষত সারাতে আর সংক্রমণের সঙ্গে লড়তে সাহায্য করে।"),
    mcq("Why do we need sleep?", ["The body and brain rest, repair and grow", "To waste time", "Sleep is not needed", "Only babies need sleep"], 0,
        "Tired workers make more mistakes - sleep is a safety tool.",
        "আমাদের ঘুম দরকার কেন?", ["শরীর আর মস্তিষ্ক বিশ্রাম নেয়, মেরামত হয় আর বাড়ে", "সময় নষ্ট করতে", "ঘুম দরকার নেই", "শুধু শিশুদের ঘুম লাগে"],
        "ক্লান্ত কর্মী বেশি ভুল করেন - ঘুম একটা নিরাপত্তার হাতিয়ার।"),
    mcq("What happens to muscles when you exercise regularly?", ["They get stronger", "They disappear", "They turn into bone", "They get weaker"], 0,
        "Muscles grow stronger when they are used.",
        "নিয়মিত ব্যায়াম করলে পেশির কী হয়?", ["আরও শক্ত হয়", "উধাও হয়", "হাড় হয়ে যায়", "দুর্বল হয়"],
        "ব্যবহার করলে পেশি শক্ত হয়।"),
    mcq("Muscles work in pairs. When your biceps contracts to bend your arm, what does the triceps do?", ["Relaxes", "Also contracts", "Breaks", "Turns to bone"], 0,
        "One pulls, the other relaxes - like the two cables pulling a crane arm either way.",
        "পেশি জোড়ায় কাজ করে। বাইসেপ সংকুচিত হয়ে হাত ভাঁজ করলে ট্রাইসেপ কী করে?", ["শিথিল হয়", "সেও সংকুচিত হয়", "ভেঙে যায়", "হাড় হয়ে যায়"],
        "একটা টানে, অন্যটা শিথিল হয় - ক্রেনের বাহু দুই দিকে টানা দুটি তারের মতো।"),
    mcq("What joins muscles to bones?", ["Tendons", "Veins", "Nails", "Hair"], 0,
        "Tendons are tough cords - like cables attaching a deck to a tower.",
        "পেশিকে হাড়ের সঙ্গে কী জোড়ে?", ["কণ্ডরা (টেনডন)", "শিরা", "নখ", "চুল"],
        "কণ্ডরা শক্ত দড়ির মতো - পাটাতনকে টাওয়ারের সঙ্গে জোড়া তারের মতো।"),
    mcq("What is a joint in the body?", ["A place where two bones meet and can move", "A broken bone", "A muscle", "A blood vessel"], 0,
        "Knees and elbows are hinge joints - like a bridge's hinge bearing.",
        "শরীরে অস্থিসন্ধি কী?", ["যেখানে দুটি হাড় মেলে আর নড়তে পারে", "ভাঙা হাড়", "পেশি", "রক্তনালী"],
        "হাঁটু আর কনুই কব্জা-সন্ধি - সেতুর কব্জা-বিয়ারিংয়ের মতো।"),
    mcq("Which joint lets your arm swing round in a circle?", ["The shoulder (ball and socket)", "The knee (hinge)", "The skull", "The fingernail"], 0,
        "A ball-and-socket joint moves in many directions.",
        "কোন সন্ধি তোমার হাতকে বৃত্তে ঘুরতে দেয়?", ["কাঁধ (বল-ও-কোটর)", "হাঁটু (কব্জা)", "খুলি", "নখ"],
        "বল-ও-কোটর সন্ধি নানা দিকে নড়ে।"),
    mcq("How long is a human's usual pregnancy before a baby is born?", ["About 9 months", "About 9 days", "About 9 years", "About 9 weeks"], 0,
        "Baby animals take different times: an elephant takes about 22 months!",
        "সাধারণত মানুষের শিশু জন্মের আগে গর্ভাবস্থা কতদিন?", ["প্রায় 9 মাস", "প্রায় 9 দিন", "প্রায় 9 বছর", "প্রায় 9 সপ্তাহ"],
        "প্রাণীভেদে সময় আলাদা: হাতির লাগে প্রায় 22 মাস!"),
    mcq("What changes happen as children grow into adults?", ["They grow taller and their bodies mature", "They shrink", "Nothing changes", "They grow feathers"], 0,
        "Growth needs good food, sleep and exercise.",
        "শিশু থেকে বড় হতে কী পরিবর্তন হয়?", ["লম্বা হয় আর শরীর পরিণত হয়", "ছোট হয়", "কিছুই বদলায় না", "পালক গজায়"],
        "বেড়ে ওঠার জন্য ভালো খাবার, ঘুম আর ব্যায়াম লাগে।"),
    mcq("How do animals in cold mountain areas stay warm?", ["Thick fur and a layer of fat", "Thin skin", "No hair", "Sweating a lot"], 0,
        "Yaks and snow leopards have thick coats.",
        "ঠান্ডা পাহাড়ি অঞ্চলের প্রাণীরা কীভাবে গরম থাকে?", ["মোটা লোম আর চর্বির স্তর", "পাতলা চামড়া", "লোম নেই", "খুব ঘেমে"],
        "চমরী গাই আর তুষার চিতার মোটা লোম আছে।"),
    mcq("Why do camels survive well in deserts?", ["They store fat in their hump and can go days without water", "They love rain", "They have gills", "They hibernate in snow"], 0,
        "Wide feet also stop them sinking into sand.",
        "উট মরুভূমিতে ভালো টিকে থাকে কেন?", ["কুঁজে চর্বি জমায় আর জল ছাড়া দিনের পর দিন চলে", "বৃষ্টি ভালোবাসে", "ফুলকা আছে", "বরফে শীতঘুম দেয়"],
        "চওড়া পা বালিতে ডোবা থেকেও বাঁচায়।"),
    mcq("What is 'camouflage'?", ["Colours or patterns that help an animal blend in", "A loud call", "A type of food", "A nest"], 0,
        "Tigers' stripes hide them in tall grass.",
        "'ছদ্মবেশ' কী?", ["রং বা নকশা, যা প্রাণীকে চারপাশে মিশে যেতে সাহায্য করে", "জোরালো ডাক", "এক রকম খাবার", "বাসা"],
        "বাঘের ডোরা লম্বা ঘাসে তাকে লুকিয়ে রাখে।"),
    mcq("Why are safety vests on building sites bright orange or yellow - the opposite of camouflage?", ["So workers are easy to see and avoid", "Because they are cheap", "To scare birds", "For fashion"], 0,
        "High-visibility clothing stops accidents with vehicles and cranes.",
        "নির্মাণস্থলের সুরক্ষা-জ্যাকেট উজ্জ্বল কমলা বা হলুদ হয় কেন - ছদ্মবেশের উল্টো?", ["যাতে কর্মীদের সহজে দেখা যায় আর এড়ানো যায়", "কারণ সস্তা", "পাখি তাড়াতে", "ফ্যাশনের জন্য"],
        "উজ্জ্বল পোশাক গাড়ি আর ক্রেনের সঙ্গে দুর্ঘটনা ঠেকায়।"),
    mcq("A creature has 8 legs and spins silk. Which group is it in?", ["Arachnids (spiders)", "Insects", "Mammals", "Fish"], 0,
        "Insects have 6 legs; spiders and scorpions have 8. Spider silk is stronger than steel for its weight!",
        "একটা প্রাণীর 8টি পা আর সে রেশম বোনে। সে কোন দলে?", ["মাকড়সা-জাতীয় (অ্যারাকনিড)", "পতঙ্গ", "স্তন্যপায়ী", "মাছ"],
        "পতঙ্গের 6টি পা; মাকড়সা আর বিছের 8টি। ওজনের তুলনায় মাকড়সার রেশম ইস্পাতের চেয়েও শক্ত!"),
    mcq("Beans kept in dry cotton wool did not sprout, but beans in damp cotton wool did. What did the dry beans lack?", ["Water", "Light", "Soil", "Wind"], 0,
        "Seeds need water, warmth and air to germinate.",
        "শুকনো তুলোয় রাখা শিম অঙ্কুরিত হয়নি, কিন্তু ভেজা তুলোয় হয়েছে। শুকনোগুলোর কী অভাব ছিল?", ["জল", "আলো", "মাটি", "বাতাস"],
        "অঙ্কুরোদগমে বীজের জল, উষ্ণতা আর বাতাস লাগে।"),
    mcq("A bee visits a mango flower, then another. What is it doing for the tree?", ["Carrying pollen so fruit can form", "Eating the leaves", "Watering the roots", "Harming the flower"], 0,
        "Moving pollen between flowers is pollination.",
        "একটা মৌমাছি একটা আমের মুকুলে যায়, তারপর আরেকটায়। গাছের জন্য সে কী করছে?", ["পরাগ বয়ে নিচ্ছে যাতে ফল হয়", "পাতা খাচ্ছে", "শিকড়ে জল দিচ্ছে", "ফুলের ক্ষতি করছে"],
        "ফুল থেকে ফুলে পরাগ সরানোকে পরাগায়ন বলে।"),
    mcq("Frogs eat insects; snakes eat frogs; owls eat snakes and mice; mice eat seeds. What is this connected picture called?", ["A food web", "A life cycle", "A habitat map", "A family tree"], 0,
        "Many linked food chains make a food web.",
        "ব্যাঙ পোকা খায়; সাপ ব্যাঙ খায়; পেঁচা সাপ আর ইঁদুর খায়; ইঁদুর বীজ খায়। এই জোড়া ছবিকে কী বলে?", ["খাদ্যজাল", "জীবনচক্র", "বাসস্থানের মানচিত্র", "বংশলতিকা"],
        "অনেক জোড়া খাদ্যশৃঙ্খল মিলে খাদ্যজাল হয়।"),
    mcq("Why do workers on bridges over rivers wear life jackets?", ["If they fall in, the jacket keeps them afloat", "To stay warm only", "To look bright only", "Jackets make them swim faster than fish"], 0,
        "Water rescue boats also stand by on many river projects.",
        "নদীর উপর সেতুতে কর্মীরা লাইফ-জ্যাকেট পরেন কেন?", ["জলে পড়ে গেলে জ্যাকেট ভাসিয়ে রাখে", "শুধু গরম থাকতে", "শুধু উজ্জ্বল দেখাতে", "জ্যাকেটে মাছের চেয়ে দ্রুত সাঁতার"],
        "অনেক নদী-প্রকল্পে উদ্ধারকারী নৌকাও তৈরি থাকে।"),
    mcq("What do kidneys do?", ["Filter waste from the blood to make urine", "Pump blood", "Digest food", "Help us see"], 0,
        "Drinking enough water helps the kidneys work well.",
        "বৃক্ক (কিডনি) কী করে?", ["রক্ত থেকে বর্জ্য ছেঁকে মূত্র তৈরি করে", "রক্ত পাম্প করে", "খাবার হজম করে", "দেখতে সাহায্য করে"],
        "যথেষ্ট জল খেলে বৃক্ক ভালো কাজ করে।"),
)
