"""Class 4 - Math: four-digit numbers, rounding, multiplying and dividing by 1 and 2 digits,
times tables to 12, fractions and decimals, area and perimeter, angles, units, time, negatives
and reading data - all from bridge sites, trains and markets."""
from . import mcq


def _opts(r, near):
    out = [r]
    for d in near + (1, -1, 10, -10, 2, 100, 1000):
        if len(out) == 4:
            break
        if r + d >= 0 and r + d not in out:
            out.append(r + d)
    return [f"{o:,}" if isinstance(o, int) else str(o) for o in out]


def calc(q_en, q_bn, r, ex_en, ex_bn, near=(10, -10, 1), unit_en="", unit_bn=""):
    o = _opts(r, near)
    return mcq(q_en, [x + unit_en for x in o], 0, ex_en, q_bn, [x + unit_bn for x in o], ex_bn)


def mul(a, b, q_en, q_bn):
    r = a * b
    return calc(q_en.format(a=a, b=b), q_bn.format(a=a, b=b), r,
                f"{a} x {b} = {r:,}. Split it: {a} x {b // 10 * 10} + {a} x {b % 10}." if b >= 10 else f"{a} x {b} = {r:,}.",
                f"{a} x {b} = {r:,}। ভেঙে করো: {a} x {b // 10 * 10} + {a} x {b % 10}।" if b >= 10 else f"{a} x {b} = {r:,}।",
                (a, -a, 10))


def div(t, n, q_en, q_bn):
    q = t // n
    return calc(q_en.format(t=t, n=n), q_bn.format(t=t, n=n), q,
                f"{t} ÷ {n} = {q}, because {q} x {n} = {t}.",
                f"{t} ÷ {n} = {q}, কারণ {q} x {n} = {t}।", (1, -1, 10))


def area(l, w, what_en, what_bn):
    return calc(f"{what_en} is {l} m long and {w} m wide. What is its area?",
                f"{what_bn} {l} m লম্বা আর {w} m চওড়া। তার ক্ষেত্রফল কত?",
                l * w, f"Area = length x width = {l} x {w} = {l * w} square metres.",
                f"ক্ষেত্রফল = দৈর্ঘ্য x প্রস্থ = {l} x {w} = {l * w} বর্গমিটার।",
                (l + w - l * w, 2 * (l + w) - l * w, 10), " m²", " m²")


def perim(l, w, what_en, what_bn):
    p = 2 * (l + w)
    return calc(f"A fence goes all the way round {what_en} {l} m by {w} m. How long is the fence?",
                f"{l} m x {w} m মাপের {what_bn} চারদিকে বেড়া দেওয়া হলো। বেড়া কত লম্বা?",
                p, f"Perimeter = 2 x (length + width) = 2 x ({l} + {w}) = {p} m.",
                f"পরিসীমা = 2 x (দৈর্ঘ্য + প্রস্থ) = 2 x ({l} + {w}) = {p} m।",
                (l * w - p, l + w - p, 2), " m", " m")


def roundto(n, to):
    r = (n + to // 2) // to * to
    return calc(f"Round {n:,} to the nearest {to:,}.", f"{n:,}-কে নিকটতম {to:,}-এ সংখ্যা-আসন্ন করো।", r,
                f"Look at the digit after the {to:,}s place: 5 or more rounds up, less than 5 rounds down. {n:,} -> {r:,}.",
                f"{to:,}-এর ঘরের পরের অঙ্ক দেখো: 5 বা বেশি হলে উপরে, 5-এর কম হলে নিচে। {n:,} -> {r:,}।",
                (to, -to, to * 10))


def fracof(num, den, total, q_en, q_bn):
    r = total // den * num
    return calc(q_en.format(f=f"{num}/{den}", t=total), q_bn.format(f=f"{num}/{den}", t=total), r,
                f"{num}/{den} of {total} = {total} ÷ {den} x {num} = {r}.",
                f"{total}-এর {num}/{den} = {total} ÷ {den} x {num} = {r}।",
                (total // den, -(total // den) if r > total // den else total // den * 2, 1))


ITEMS = (
    mul(24, 6, "A truss has {a} bolts at each joint and {b} joints. How many bolts?",
        "একটা ট্রাসের প্রতিটি জোড়ে {a}টি বল্টু আর মোট {b}টি জোড়। কয়টি বল্টু?"),
    mul(35, 8, "A goods train has {b} wagons, each carrying {a} tonnes. Total tonnes?",
        "একটা মালগাড়ির {b}টি ওয়াগন, প্রতিটি {a} টন বয়। মোট কত টন?"),
    mul(47, 9, "A shop sells {b} boxes of {a} pencils. How many pencils?",
        "একটা দোকান {a}টি পেনসিলের {b}টি বাক্স বেচে। কয়টি পেনসিল?"),
    mul(23, 14, "A bridge has {b} lamp posts with {a} bulbs on each. How many bulbs?",
        "একটা সেতুতে {b}টি বাতির খুঁটি, প্রতিটিতে {a}টি বাল্ব। কয়টি বাল্ব?"),
    mul(36, 12, "Each steel panel has {a} rivets. How many rivets in {b} panels?",
        "প্রতিটি ইস্পাতের প্যানেলে {a}টি রিভেট। {b}টি প্যানেলে কয়টি রিভেট?"),
    mul(125, 4, "A crane lifts {a} kg each trip. How much in {b} trips?",
        "একটা ক্রেন প্রতিবারে {a} kg তোলে। {b}বারে কত?"),
    mul(52, 15, "A ferry carries {a} passengers a trip and makes {b} trips. How many passengers?",
        "একটা খেয়া প্রতিবার {a} জন যাত্রী বয় আর {b}বার যায়। কতজন যাত্রী?"),
    mul(18, 25, "A road has {b} rows of paving stones with {a} stones in each. How many stones?",
        "একটা রাস্তায় {b} সারি পাথর, প্রতিটিতে {a}টি। কয়টি পাথর?"),
    mul(11, 12, "What is {a} x {b}?", "{a} x {b} কত?"),
    mul(12, 9, "A dozen is 12. How many eggs are in {b} dozen?", "এক ডজন মানে 12। {b} ডজনে কয়টি ডিম?"),
    mul(7, 8, "Workers lay {a} m of track a day. How much in {b} days?", "কর্মীরা দিনে {a} m লাইন পাতেন। {b} দিনে কত?"),
    mul(9, 6, "A bus has {b} rows of {a} seats. How many seats?", "একটা বাসে {a}টি করে আসনের {b} সারি। কয়টি আসন?"),
    div(144, 12, "{t} bolts are packed equally into {n} bags. How many in each bag?",
        "{t}টি বল্টু {n}টি ব্যাগে সমান ভাগে রাখা হলো। প্রতিটিতে কয়টি?"),
    div(256, 8, "{t} tonnes of gravel are loaded equally onto {n} trucks. Tonnes per truck?",
        "{t} টন পাথরকুচি {n}টি ট্রাকে সমান ভাগে তোলা হলো। প্রতি ট্রাকে কত টন?"),
    div(420, 6, "A {t} m bridge has {n} equal spans. How long is each span?",
        "{t} m লম্বা সেতুর {n}টি সমান স্প্যান। প্রতিটি স্প্যান কত লম্বা?"),
    div(372, 4, "{t} students share {n} buses equally. How many per bus?",
        "{t} জন ছাত্রছাত্রী {n}টি বাসে সমান ভাগে বসল। প্রতি বাসে কতজন?"),
    div(945, 9, "Rs {t} is shared equally by {n} workers. How much each?",
        "{t} টাকা {n} জন কর্মীর মধ্যে সমান ভাগ হলো। প্রত্যেকে কত?"),
    div(648, 12, "{t} eggs are packed in trays of {n}. How many trays?",
        "{t}টি ডিম {n}টি করে ট্রেতে রাখা হলো। কয়টি ট্রে?"),
    div(1000, 8, "A {t} m rope is cut into {n} equal pieces. How long is each?",
        "{t} m লম্বা দড়ি {n}টি সমান টুকরো করা হলো। প্রতিটি কত লম্বা?"),
    div(315, 7, "{t} km is driven in {n} equal days of driving. How far each day?",
        "{n} দিনে সমান ভাগে {t} km গাড়ি চালানো হলো। প্রতিদিন কত দূর?"),
    area(8, 5, "A bridge deck section", "সেতুর পাটাতনের একটা অংশ"),
    area(12, 4, "A classroom floor", "একটা শ্রেণিকক্ষের মেঝে"),
    area(9, 7, "A vegetable garden", "একটা সবজি বাগান"),
    area(15, 6, "A parking area by the bridge", "সেতুর পাশের পার্কিং জায়গা"),
    area(20, 3, "A footpath", "একটা ফুটপাথ"),
    area(11, 11, "A square playground", "একটা বর্গাকার খেলার মাঠ"),
    perim(10, 6, "a garden", "বাগানের"),
    perim(25, 15, "a construction site", "নির্মাণস্থলের"),
    perim(9, 9, "a square pond", "বর্গাকার পুকুরের"),
    perim(30, 12, "a storage yard", "মালপত্র রাখার উঠোনের"),
    roundto(4372, 100), roundto(8650, 1000), roundto(2349, 10), roundto(6951, 100), roundto(1499, 1000),
    fracof(1, 4, 48, "A truck carries 48 sacks; {f} are cement. How many cement sacks?",
           "একটা ট্রাক 48টি বস্তা বয়; তার {f} সিমেন্ট। কয়টি সিমেন্টের বস্তা?"),
    fracof(3, 4, 60, "{f} of a 60 m bridge is painted. How many metres are painted?",
           "60 m সেতুর {f} রং করা হয়েছে। কত মিটার রং হয়েছে?"),
    fracof(2, 5, 35, "{f} of 35 workers are welders. How many welders?",
           "35 জন কর্মীর {f} ঝালাইকারী। কতজন ঝালাইকারী?"),
    fracof(5, 6, 72, "{f} of 72 seats on a train are taken. How many are taken?",
           "একটা ট্রেনের 72টি আসনের {f} ভর্তি। কয়টি ভর্তি?"),
    fracof(2, 3, 90, "{f} of Rs 90 is spent on a ticket. How much is spent?",
           "90 টাকার {f} টিকিটে খরচ হলো। কত খরচ হলো?"),
    mcq("What is the value of the 7 in 4,735?", ["700", "7", "70", "7,000"], 0,
        "4,735 = 4 thousands, 7 hundreds, 3 tens, 5 ones.",
        "4,735-এ 7-এর স্থানীয় মান কত?", ["700", "7", "70", "7,000"],
        "4,735 = 4 হাজার, 7 শত, 3 দশ, 5 এক।"),
    mcq("Which number is largest?", ["6,402", "6,240", "6,042", "6,204"], 0,
        "Compare thousands, then hundreds: 6,402 has 4 hundreds.",
        "কোন সংখ্যাটা সবচেয়ে বড়?", ["6,402", "6,240", "6,042", "6,204"],
        "আগে হাজার, তারপর শতক তুলনা করো: 6,402-তে 4 শত।"),
    mcq("Write five thousand and sixty-two in numbers.", ["5,062", "5,620", "50,062", "5,602"], 0,
        "5 thousands, 0 hundreds, 6 tens, 2 ones.",
        "পাঁচ হাজার বাষট্টি সংখ্যায় লেখো।", ["5,062", "5,620", "50,062", "5,602"],
        "5 হাজার, 0 শত, 6 দশ, 2 এক।"),
    mcq("What is 1,000 more than 8,450?", ["9,450", "8,550", "18,450", "8,460"], 0,
        "Only the thousands digit goes up by 1.",
        "8,450-এর চেয়ে 1,000 বেশি কত?", ["9,450", "8,550", "18,450", "8,460"],
        "শুধু হাজারের ঘরের অঙ্ক 1 বাড়ে।"),
    mcq("What is 6 x 7?", ["42", "36", "48", "49"], 0,
        "6 x 7 = 42. Tip: 5 x 7 = 35, plus one more 7.",
        "6 x 7 কত?", ["42", "36", "48", "49"],
        "6 x 7 = 42। কৌশল: 5 x 7 = 35, তার সঙ্গে আরেকটা 7।"),
    mcq("What is 8 x 12?", ["96", "84", "108", "88"], 0,
        "8 x 12 = 8 x 10 + 8 x 2 = 80 + 16 = 96.",
        "8 x 12 কত?", ["96", "84", "108", "88"],
        "8 x 12 = 8 x 10 + 8 x 2 = 80 + 16 = 96।"),
    mcq("What is 9 x 9?", ["81", "72", "99", "89"], 0,
        "9 x 9 = 81 - the digits of 9-times answers add to 9.",
        "9 x 9 কত?", ["81", "72", "99", "89"],
        "9 x 9 = 81 - 9-এর নামতার উত্তরের অঙ্কগুলোর যোগফল 9।"),
    mcq("Which fraction is equal to 1/2?", ["4/8", "3/8", "2/6", "5/8"], 0,
        "Multiply top and bottom by 4: 1/2 = 4/8.",
        "কোন ভগ্নাংশ 1/2-এর সমান?", ["4/8", "3/8", "2/6", "5/8"],
        "লব আর হর দুটোকেই 4 দিয়ে গুণ করো: 1/2 = 4/8।"),
    mcq("Which fraction is equal to 3/4?", ["6/8", "3/8", "4/6", "9/16"], 0,
        "3/4 = (3 x 2)/(4 x 2) = 6/8.",
        "কোন ভগ্নাংশ 3/4-এর সমান?", ["6/8", "3/8", "4/6", "9/16"],
        "3/4 = (3 x 2)/(4 x 2) = 6/8।"),
    mcq("What is 2/7 + 3/7?", ["5/7", "5/14", "6/7", "1/7"], 0,
        "Same bottoms: add the tops. 2 + 3 = 5 sevenths.",
        "2/7 + 3/7 কত?", ["5/7", "5/14", "6/7", "1/7"],
        "হর এক হলে লব যোগ করো। 2 + 3 = 5 সপ্তমাংশ।"),
    mcq("What is 7/10 - 4/10?", ["3/10", "3/0", "11/10", "4/10"], 0,
        "Same bottoms: subtract the tops.",
        "7/10 - 4/10 কত?", ["3/10", "3/0", "11/10", "4/10"],
        "হর এক হলে লব বিয়োগ করো।"),
    mcq("Which is bigger: 3/5 or 3/8?", ["3/5", "3/8", "They are equal", "Cannot tell"], 0,
        "Same top: fewer, bigger pieces (fifths) beat smaller pieces (eighths).",
        "কোনটা বড়: 3/5 না 3/8?", ["3/5", "3/8", "দুটো সমান", "বলা যায় না"],
        "লব এক হলে কম, বড় টুকরো (পঞ্চমাংশ) ছোট টুকরোকে (অষ্টমাংশ) হারায়।"),
    mcq("What is 0.5 as a fraction?", ["1/2", "1/5", "5/1", "1/50"], 0,
        "0.5 = 5 tenths = 5/10 = 1/2.",
        "0.5 ভগ্নাংশে কত?", ["1/2", "1/5", "5/1", "1/50"],
        "0.5 = 5 দশমাংশ = 5/10 = 1/2।"),
    mcq("What is 1/4 as a decimal?", ["0.25", "0.4", "1.4", "0.14"], 0,
        "1 ÷ 4 = 0.25, like 25 paise in a rupee.",
        "1/4 দশমিকে কত?", ["0.25", "0.4", "1.4", "0.14"],
        "1 ÷ 4 = 0.25, যেমন এক টাকায় 25 পয়সা।"),
    mcq("What is 3.6 + 2.5?", ["6.1", "5.11", "5.1", "6.11"], 0,
        "Line up the decimal points: 3.6 + 2.5 = 6.1.",
        "3.6 + 2.5 কত?", ["6.1", "5.11", "5.1", "6.11"],
        "দশমিক বিন্দু মিলিয়ে লেখো: 3.6 + 2.5 = 6.1।"),
    mcq("A plank is 4.5 m long. 1.8 m is cut off. How much is left?", ["2.7 m", "3.3 m", "2.3 m", "6.3 m"], 0,
        "4.5 - 1.8 = 2.7 m.",
        "একটা তক্তা 4.5 m লম্বা। 1.8 m কেটে নেওয়া হলো। কত বাকি?", ["2.7 m", "3.3 m", "2.3 m", "6.3 m"],
        "4.5 - 1.8 = 2.7 m।"),
    mcq("Which decimal is largest?", ["0.9", "0.45", "0.19", "0.099"], 0,
        "Compare tenths first: 9 tenths is the most.",
        "কোন দশমিক সংখ্যাটা সবচেয়ে বড়?", ["0.9", "0.45", "0.19", "0.099"],
        "আগে দশমাংশ তুলনা করো: 9 দশমাংশ সবচেয়ে বেশি।"),
    mcq("What is 3.7 x 10?", ["37", "3.70", "0.37", "370"], 0,
        "Multiplying by 10 moves every digit one place to the left.",
        "3.7 x 10 কত?", ["37", "3.70", "0.37", "370"],
        "10 দিয়ে গুণ করলে প্রতিটি অঙ্ক এক ঘর বাঁয়ে সরে।"),
    mcq("What is 45 ÷ 10?", ["4.5", "450", "0.45", "45.10"], 0,
        "Dividing by 10 moves digits one place to the right.",
        "45 ÷ 10 কত?", ["4.5", "450", "0.45", "45.10"],
        "10 দিয়ে ভাগ করলে অঙ্ক এক ঘর ডানে সরে।"),
    mcq("How many centimetres are in 3.5 m?", ["350 cm", "35 cm", "3,500 cm", "3.5 cm"], 0,
        "1 m = 100 cm, so 3.5 x 100 = 350 cm.",
        "3.5 m-এ কত সেন্টিমিটার?", ["350 cm", "35 cm", "3,500 cm", "3.5 cm"],
        "1 m = 100 cm, তাই 3.5 x 100 = 350 cm।"),
    mcq("How many grams are in 2.5 kg?", ["2,500 g", "250 g", "25 g", "25,000 g"], 0,
        "1 kg = 1,000 g, so 2.5 kg = 2,500 g.",
        "2.5 kg-এ কত গ্রাম?", ["2,500 g", "250 g", "25 g", "25,000 g"],
        "1 kg = 1,000 g, তাই 2.5 kg = 2,500 g।"),
    mcq("How many millilitres are in 4 litres?", ["4,000 ml", "400 ml", "40 ml", "40,000 ml"], 0,
        "1 litre = 1,000 ml.",
        "4 লিটারে কত মিলিলিটার?", ["4,000 ml", "400 ml", "40 ml", "40,000 ml"],
        "1 লিটার = 1,000 ml।"),
    mcq("A beam is 600 cm long. How many metres is that?", ["6 m", "60 m", "0.6 m", "600 m"], 0,
        "Divide by 100: 600 ÷ 100 = 6 m.",
        "একটা বিম 600 cm লম্বা। তা কত মিটার?", ["6 m", "60 m", "0.6 m", "600 m"],
        "100 দিয়ে ভাগ করো: 600 ÷ 100 = 6 m।"),
    mcq("A truck's load is 7,500 kg. How many tonnes?", ["7.5 tonnes", "75 tonnes", "750 tonnes", "0.75 tonnes"], 0,
        "1 tonne = 1,000 kg, so 7,500 ÷ 1,000 = 7.5.",
        "একটা ট্রাকের বোঝা 7,500 kg। কত টন?", ["7.5 টন", "75 টন", "750 টন", "0.75 টন"],
        "1 টন = 1,000 kg, তাই 7,500 ÷ 1,000 = 7.5।"),
    mcq("What is 15:30 in 12-hour time?", ["3:30 pm", "5:30 pm", "3:30 am", "1:30 pm"], 0,
        "Subtract 12 from afternoon hours: 15 - 12 = 3.",
        "15:30 মানে 12-ঘণ্টার হিসেবে কত?", ["বিকেল 3:30", "বিকেল 5:30", "রাত 3:30", "দুপুর 1:30"],
        "দুপুরের পরের ঘণ্টা থেকে 12 বিয়োগ করো: 15 - 12 = 3।"),
    mcq("A train leaves at 09:45 and arrives at 13:15. How long is the trip?", ["3 h 30 min", "4 h 30 min", "3 h 15 min", "4 h"], 0,
        "09:45 to 12:45 is 3 h; 12:45 to 13:15 is 30 min.",
        "একটা ট্রেন 09:45-এ ছেড়ে 13:15-এ পৌঁছায়। যাত্রা কতক্ষণ?", ["3 ঘণ্টা 30 মিনিট", "4 ঘণ্টা 30 মিনিট", "3 ঘণ্টা 15 মিনিট", "4 ঘণ্টা"],
        "09:45 থেকে 12:45 হলো 3 ঘণ্টা; 12:45 থেকে 13:15 হলো 30 মিনিট।"),
    mcq("How many minutes are in 2 and a half hours?", ["150", "120", "250", "130"], 0,
        "2 x 60 = 120, plus 30 = 150 minutes.",
        "আড়াই ঘণ্টায় কত মিনিট?", ["150", "120", "250", "130"],
        "2 x 60 = 120, সঙ্গে 30 = 150 মিনিট।"),
    mcq("What is a right angle?", ["A quarter turn, 90°", "A half turn, 180°", "Any small angle", "A full turn"], 0,
        "Corners of a book and a square are right angles.",
        "সমকোণ কী?", ["এক-চতুর্থাংশ পাক, 90°", "অর্ধেক পাক, 180°", "যেকোনো ছোট কোণ", "পুরো পাক"],
        "বইয়ের কোণ আর বর্গের কোণ সমকোণ।"),
    mcq("An angle between 90° and 180° is called...", ["Obtuse", "Acute", "Right", "Full"], 0,
        "Obtuse angles are wider than a right angle.",
        "90° আর 180°-এর মাঝের কোণকে বলে...", ["স্থূলকোণ", "সূক্ষ্মকোণ", "সমকোণ", "পূর্ণকোণ"],
        "স্থূলকোণ সমকোণের চেয়ে চওড়া।"),
    mcq("A bridge pillar stands perfectly upright on flat ground. What angle does it make with the ground?", ["90°", "45°", "180°", "30°"], 0,
        "Vertical meets horizontal at a right angle - builders check with a set square or level.",
        "একটা সেতুর থাম সমতল মাটিতে একদম খাড়া দাঁড়িয়ে। মাটির সঙ্গে কত কোণ করে?", ["90°", "45°", "180°", "30°"],
        "খাড়া আর অনুভূমিক রেখা সমকোণে মেলে - নির্মাতারা সেট-স্কোয়ার বা লেভেল দিয়ে যাচাই করেন।"),
    mcq("What do the three angles inside any triangle add up to?", ["180°", "90°", "360°", "100°"], 0,
        "Tear off the corners of a paper triangle and they make a straight line.",
        "যেকোনো ত্রিভুজের ভেতরের তিনটি কোণের যোগফল কত?", ["180°", "90°", "360°", "100°"],
        "কাগজের ত্রিভুজের কোণ ছিঁড়ে পাশাপাশি রাখলে সরলরেখা হয়।"),
    mcq("A truss triangle has angles of 60° and 60°. What is the third?", ["60°", "90°", "30°", "120°"], 0,
        "180 - 60 - 60 = 60°, an equilateral triangle - a favourite in Warren trusses.",
        "ট্রাসের একটা ত্রিভুজের দুটি কোণ 60° আর 60°। তৃতীয়টি কত?", ["60°", "90°", "30°", "120°"],
        "180 - 60 - 60 = 60°, সমবাহু ত্রিভুজ - ওয়ারেন ট্রাসের প্রিয়।"),
    mcq("Why are most bridges symmetrical?", ["Balanced shapes share loads evenly and are easier to build", "Symmetry is required for paint", "They are not", "To confuse drivers"], 0,
        "Matching halves share forces equally.",
        "বেশিরভাগ সেতু প্রতিসম হয় কেন?", ["ভারসাম্যপূর্ণ আকার বোঝা সমানভাবে ভাগ করে আর বানানো সহজ", "রঙের জন্য প্রতিসাম্য বাধ্যতামূলক", "হয় না", "চালকদের বিভ্রান্ত করতে"],
        "মিলে যাওয়া দুই অর্ধেক বল সমানভাবে ভাগ করে।"),
    mcq("The temperature is 4 °C and falls by 7 degrees. What is it now?", ["-3 °C", "3 °C", "11 °C", "-11 °C"], 0,
        "Count down past zero: 4 -> 0 is 4 steps, 3 more steps gives -3.",
        "তাপমাত্রা 4 °C, তারপর 7 ডিগ্রি কমল। এখন কত?", ["-3 °C", "3 °C", "11 °C", "-11 °C"],
        "শূন্য পেরিয়ে নিচে গোনো: 4 -> 0 হলো 4 ধাপ, আরও 3 ধাপে -3।"),
    mcq("Which is colder: -8 °C or -2 °C?", ["-8 °C", "-2 °C", "They are equal", "Neither is cold"], 0,
        "The further below zero, the colder.",
        "কোনটা বেশি ঠান্ডা: -8 °C না -2 °C?", ["-8 °C", "-2 °C", "দুটো সমান", "কোনোটাই ঠান্ডা নয়"],
        "শূন্যের যত নিচে, তত ঠান্ডা।"),
    mcq("A bridge foundation goes 6 m below river level; the deck is 9 m above. How far from the bottom of the foundation to the deck?", ["15 m", "3 m", "9 m", "6 m"], 0,
        "From -6 to +9 is 6 + 9 = 15 m.",
        "সেতুর ভিত নদীতলের 6 m নিচে; পাটাতন 9 m উপরে। ভিতের তলা থেকে পাটাতন কত দূরে?", ["15 m", "3 m", "9 m", "6 m"],
        "-6 থেকে +9 পর্যন্ত 6 + 9 = 15 m।"),
    mcq("What is XIV in Roman numerals?", ["14", "16", "9", "41"], 0,
        "X = 10, IV = 4 (one before five). 10 + 4 = 14. Old bridges often show dates in Roman numerals.",
        "রোমান সংখ্যায় XIV কত?", ["14", "16", "9", "41"],
        "X = 10, IV = 4 (পাঁচের এক আগে)। 10 + 4 = 14। পুরোনো সেতুতে প্রায়ই রোমান সংখ্যায় সাল লেখা থাকে।"),
    mcq("What is 'L' in Roman numerals?", ["50", "100", "5", "1000"], 0,
        "I = 1, V = 5, X = 10, L = 50, C = 100, D = 500, M = 1000.",
        "রোমান সংখ্যায় 'L' কত?", ["50", "100", "5", "1000"],
        "I = 1, V = 5, X = 10, L = 50, C = 100, D = 500, M = 1000।"),
    mcq("A bar chart shows trucks crossing a bridge: Mon 40, Tue 55, Wed 35. How many more on Tuesday than Wednesday?", ["20", "15", "90", "5"], 0,
        "55 - 35 = 20.",
        "একটা স্তম্ভলেখ সেতু পার হওয়া ট্রাক দেখায়: সোম 40, মঙ্গল 55, বুধ 35। বুধবারের চেয়ে মঙ্গলবারে কত বেশি?", ["20", "15", "90", "5"],
        "55 - 35 = 20।"),
    mcq("Using the same chart (Mon 40, Tue 55, Wed 35), how many trucks in all three days?", ["130", "120", "95", "140"], 0,
        "40 + 55 + 35 = 130.",
        "একই স্তম্ভলেখ (সোম 40, মঙ্গল 55, বুধ 35) থেকে তিন দিনে মোট কতগুলো ট্রাক?", ["130", "120", "95", "140"],
        "40 + 55 + 35 = 130।"),
    mcq("What is the mean (average) of 4, 6 and 8?", ["6", "18", "4", "8"], 0,
        "Add them (18) and divide by how many there are (3): 6.",
        "4, 6 আর 8-এর গড় কত?", ["6", "18", "4", "8"],
        "যোগ করো (18) আর সংখ্যার মোট পরিমাণ (3) দিয়ে ভাগ করো: 6।"),
    mcq("On a grid map, the point (3, 5) means...", ["3 across, then 5 up", "5 across, then 3 up", "3 down, 5 left", "8 in total"], 0,
        "Along the corridor, then up the stairs.",
        "গ্রিড মানচিত্রে (3, 5) বিন্দু মানে...", ["আড়াআড়ি 3, তারপর উপরে 5", "আড়াআড়ি 5, তারপর উপরে 3", "নিচে 3, বাঁয়ে 5", "মোট 8"],
        "আগে বারান্দা বরাবর, তারপর সিঁড়ি দিয়ে উপরে।"),
    mcq("What is the next number: 125, 250, 375, ...?", ["500", "400", "450", "625"], 0,
        "Add 125 each time.",
        "পরের সংখ্যা কত: 125, 250, 375, ...?", ["500", "400", "450", "625"],
        "প্রতিবার 125 যোগ করো।"),
    mcq("Which number is a multiple of both 4 and 6?", ["12", "10", "8", "18"], 0,
        "12 is in both the 4 and the 6 times tables.",
        "কোন সংখ্যা 4 আর 6 দুটোরই গুণিতক?", ["12", "10", "8", "18"],
        "12 থাকে 4 আর 6 দুটো নামতাতেই।"),
    mcq("What are the factors of 12?", ["1, 2, 3, 4, 6, 12", "1, 2, 12", "2, 4, 8, 12", "1, 3, 5, 12"], 0,
        "Factors divide 12 exactly. 12 bolts can be arranged in rows of any of these.",
        "12-এর উৎপাদকগুলো কী?", ["1, 2, 3, 4, 6, 12", "1, 2, 12", "2, 4, 8, 12", "1, 3, 5, 12"],
        "উৎপাদক 12-কে নিঃশেষে ভাগ করে। 12টি বল্টু এর যেকোনো মাপের সারিতে সাজানো যায়।"),
    mcq("Estimate 398 + 211 by rounding to the nearest hundred.", ["About 600", "About 500", "About 700", "About 400"], 0,
        "400 + 200 = 600. Estimating checks if an answer is sensible.",
        "নিকটতম শতকে আসন্ন করে 398 + 211 আন্দাজ করো।", ["প্রায় 600", "প্রায় 500", "প্রায় 700", "প্রায় 400"],
        "400 + 200 = 600। আন্দাজ দিয়ে উত্তর যুক্তিসঙ্গত কিনা যাচাই হয়।"),
    mcq("Steel costs Rs 52 per kg. Roughly how much for 9 kg?", ["About Rs 450", "About Rs 45", "About Rs 4,500", "About Rs 90"], 0,
        "52 is about 50; 50 x 9 = 450 (exactly 468).",
        "ইস্পাতের দাম কেজিপ্রতি 52 টাকা। 9 kg-এ মোটামুটি কত?", ["প্রায় 450 টাকা", "প্রায় 45 টাকা", "প্রায় 4,500 টাকা", "প্রায় 90 টাকা"],
        "52 প্রায় 50; 50 x 9 = 450 (ঠিকঠাক 468)।"),
    mcq("A bridge toll is Rs 35. A driver pays with a Rs 100 note. How much change?", ["Rs 65", "Rs 75", "Rs 35", "Rs 135"], 0,
        "100 - 35 = 65.",
        "সেতুর টোল 35 টাকা। একজন চালক 100 টাকার নোট দিলেন। কত ফেরত?", ["65 টাকা", "75 টাকা", "35 টাকা", "135 টাকা"],
        "100 - 35 = 65।"),
    mcq("A shape has 6 equal sides. What is it called?", ["Regular hexagon", "Pentagon", "Octagon", "Rectangle"], 0,
        "Bees build hexagons - strong and space-saving.",
        "একটা আকারের 6টি সমান বাহু। তার নাম কী?", ["সুষম ষড়ভুজ", "পঞ্চভুজ", "অষ্টভুজ", "আয়তক্ষেত্র"],
        "মৌমাছিরা ষড়ভুজ বানায় - শক্ত আর জায়গা বাঁচায়।"),
    mcq("How many faces does a cube have?", ["6", "8", "12", "4"], 0,
        "A cube has 6 square faces, 12 edges and 8 corners.",
        "একটা ঘনকের কয়টি তল?", ["6", "8", "12", "4"],
        "ঘনকের 6টি বর্গাকার তল, 12টি ধার আর 8টি কোণ।"),
    mcq("A concrete block is 2 m long, 1 m wide and 1 m high. How many 1 m cubes fit inside?", ["2", "4", "1", "3"], 0,
        "Volume = 2 x 1 x 1 = 2 cubic metres.",
        "একটা কংক্রিটের ব্লক 2 m লম্বা, 1 m চওড়া আর 1 m উঁচু। ভেতরে 1 m-এর কয়টি ঘনক আঁটবে?", ["2", "4", "1", "3"],
        "আয়তন = 2 x 1 x 1 = 2 ঘনমিটার।"),
    mcq("What is 1,000 - 375?", ["625", "735", "675", "725"], 0,
        "375 + 625 = 1,000.",
        "1,000 - 375 কত?", ["625", "735", "675", "725"],
        "375 + 625 = 1,000।"),
    mcq("A bridge budget is Rs 5,000. Steel costs Rs 2,750 and labour Rs 1,600. How much is left?", ["Rs 650", "Rs 750", "Rs 1,650", "Rs 4,350"], 0,
        "2,750 + 1,600 = 4,350; 5,000 - 4,350 = 650.",
        "একটা সেতুর বাজেট 5,000 টাকা। ইস্পাতে 2,750 আর শ্রমে 1,600 টাকা খরচ। কত বাকি?", ["650 টাকা", "750 টাকা", "1,650 টাকা", "4,350 টাকা"],
        "2,750 + 1,600 = 4,350; 5,000 - 4,350 = 650।"),
    mcq("A truss member meets the deck at 35°. What kind of angle is that?", ["Acute", "Obtuse", "Right", "Straight"], 0,
        "35° is less than 90°, so it is acute.",
        "ট্রাসের একটা অংশ পাটাতনের সঙ্গে 35° কোণ করে। এটা কোন ধরনের কোণ?", ["সূক্ষ্মকোণ", "স্থূলকোণ", "সমকোণ", "সরলকোণ"],
        "35° হলো 90°-এর কম, তাই সূক্ষ্মকোণ।"),
    mcq("How many lines of symmetry does a rectangle (not a square) have?", ["2", "4", "1", "0"], 0,
        "One across the middle and one down the middle - the diagonals do not fold it evenly.",
        "একটা আয়তক্ষেত্রের (বর্গ নয়) কয়টি প্রতিসাম্য-রেখা?", ["2", "4", "1", "0"],
        "একটা আড়াআড়ি মাঝখান দিয়ে আর একটা লম্বালম্বি - কর্ণ বরাবর ভাঁজে সমান হয় না।"),
    mcq("A bridge project starts on 1 March and takes 45 days. Which month does it finish in?", ["April", "March", "May", "June"], 0,
        "March has 31 days; 45 - 31 = 14, so it ends on 14 April.",
        "একটা সেতু-প্রকল্প 1 মার্চ শুরু হয়ে 45 দিন চলে। কোন মাসে শেষ হয়?", ["এপ্রিল", "মার্চ", "মে", "জুন"],
        "মার্চে 31 দিন; 45 - 31 = 14, তাই 14 এপ্রিল শেষ হয়।"),
    mcq("What is 13 x 100?", ["1,300", "130", "13,000", "1,013"], 0,
        "Multiplying by 100 moves digits two places left: add two zeros.",
        "13 x 100 কত?", ["1,300", "130", "13,000", "1,013"],
        "100 দিয়ে গুণ করলে অঙ্ক দুই ঘর বাঁয়ে সরে: দুটো শূন্য যোগ করো।"),
    mcq("A worker earns Rs 450 a day. How much in a 6-day week?", ["Rs 2,700", "Rs 2,400", "Rs 3,150", "Rs 456"], 0,
        "450 x 6 = 2,700.",
        "একজন কর্মী দিনে 450 টাকা পান। 6 দিনের সপ্তাহে কত?", ["2,700 টাকা", "2,400 টাকা", "3,150 টাকা", "456 টাকা"],
        "450 x 6 = 2,700।"),
    mcq("A 1 m ruler is split into 10 equal parts. How long is each part?", ["0.1 m (10 cm)", "1 cm", "0.01 m", "10 m"], 0,
        "One tenth of a metre = 0.1 m = 10 cm.",
        "1 m-এর একটা রুলার 10টি সমান ভাগে ভাগ করা। প্রতিটি ভাগ কত লম্বা?", ["0.1 m (10 cm)", "1 cm", "0.01 m", "10 m"],
        "এক মিটারের এক-দশমাংশ = 0.1 m = 10 cm।"),
    mcq("Which number is a prime number?", ["13", "15", "21", "9"], 0,
        "A prime has exactly two factors: 1 and itself. 13 cannot be split into equal rows.",
        "কোন সংখ্যা মৌলিক?", ["13", "15", "21", "9"],
        "মৌলিক সংখ্যার ঠিক দুটি উৎপাদক: 1 আর নিজে। 13-কে সমান সারিতে ভাগ করা যায় না।"),
)
