"""Class 4 - Chemistry: reversible and irreversible changes, burning, acids and bases, solutions,
separating mixtures, mixing concrete and mortar, rust protection, air and water, and recycling."""
from . import mcq


def concrete(cement):
    sand, gravel = cement * 2, cement * 4
    o = list(dict.fromkeys([sand, cement, gravel, sand + 1]))[:4]
    return mcq(f"A common concrete mix is 1 part cement : 2 parts sand : 4 parts gravel. With {cement} buckets of cement, how many buckets of sand?",
               [f"{x}" for x in o], 0,
               f"Sand is 2 parts for each part of cement: {cement} x 2 = {sand}. (Gravel would be {gravel}.)",
               f"সাধারণ কংক্রিট মিশ্রণ 1 ভাগ সিমেন্ট : 2 ভাগ বালি : 4 ভাগ পাথরকুচি। {cement} বালতি সিমেন্টে কত বালতি বালি?",
               [f"{x}" for x in o],
               f"প্রতি ভাগ সিমেন্টে 2 ভাগ বালি: {cement} x 2 = {sand}। (পাথরকুচি হবে {gravel}।)")


def gravel(cement):
    g = cement * 4
    o = list(dict.fromkeys([g, cement * 2, g + cement, cement + 4]))[:4]
    return mcq(f"Using the 1 : 2 : 4 concrete mix, how many buckets of gravel go with {cement} buckets of cement?",
               [f"{x}" for x in o], 0,
               f"Gravel is 4 parts per part of cement: {cement} x 4 = {g}.",
               f"1 : 2 : 4 কংক্রিট মিশ্রণে {cement} বালতি সিমেন্টের সঙ্গে কত বালতি পাথরকুচি যায়?",
               [f"{x}" for x in o],
               f"প্রতি ভাগ সিমেন্টে 4 ভাগ পাথরকুচি: {cement} x 4 = {g}।")


def stronger(salt_a, water_a, salt_b, water_b):
    a, b = salt_a / water_a, salt_b / water_b
    first = a > b
    o = ["Cup A", "Cup B", "Both the same", "Neither has salt"]
    o_bn = ["কাপ A", "কাপ B", "দুটোই সমান", "কোনোটাতেই লবণ নেই"]
    return mcq(f"Cup A has {salt_a} g of salt in {water_a} ml of water. Cup B has {salt_b} g in {water_b} ml. Which is saltier?",
               o, 0 if first else 1,
               f"Compare salt per ml: A = {salt_a}/{water_a}, B = {salt_b}/{water_b}. More salt for each ml is a stronger (more concentrated) solution.",
               f"কাপ A-তে {water_a} ml জলে {salt_a} g লবণ। কাপ B-তে {water_b} ml-এ {salt_b} g। কোনটা বেশি নোনতা?",
               o_bn,
               f"প্রতি ml-এ লবণ তুলনা করো: A = {salt_a}/{water_a}, B = {salt_b}/{water_b}। প্রতি ml-এ বেশি লবণ মানে বেশি ঘন দ্রবণ।")


ITEMS = (
    concrete(3), concrete(5), concrete(7),
    gravel(2), gravel(6),
    stronger(20, 100, 20, 200),
    stronger(10, 250, 30, 300),
    stronger(15, 50, 40, 400),
    stronger(5, 100, 25, 200),
    mcq("What is a 'reversible change'?", ["A change that can be undone, like melting ice", "A change that can never be undone", "Burning wood", "Baking a cake"], 0,
        "Melted chocolate can set again - the change goes both ways.",
        "'উভমুখী পরিবর্তন' কী?", ["যে পরিবর্তন ফেরানো যায়, যেমন বরফ গলা", "যে পরিবর্তন কখনো ফেরানো যায় না", "কাঠ পোড়ানো", "কেক সেঁকা"],
        "গলানো চকোলেট আবার জমে - পরিবর্তন দুই দিকেই যায়।"),
    mcq("Which of these is an irreversible change?", ["Burning paper", "Freezing water", "Melting butter", "Dissolving sugar"], 0,
        "Ash and smoke cannot be turned back into paper.",
        "এগুলোর কোনটা অপরিবর্তনীয় পরিবর্তন?", ["কাগজ পোড়ানো", "জল জমানো", "মাখন গলানো", "চিনি গোলা"],
        "ছাই আর ধোঁয়া আবার কাগজে ফেরানো যায় না।"),
    mcq("Cement mixed with water sets hard. What kind of change is this?", ["Irreversible - a new hard material forms", "Reversible - add water to soften it again", "No change at all", "A change of colour only"], 0,
        "Setting cement is a chemical reaction; you cannot turn concrete back into powder and water.",
        "জলে মেশানো সিমেন্ট শক্ত হয়ে জমে। এটা কোন ধরনের পরিবর্তন?", ["অপরিবর্তনীয় - নতুন শক্ত পদার্থ তৈরি হয়", "উভমুখী - জল দিলে আবার নরম হয়", "কোনো পরিবর্তন নয়", "শুধু রঙের পরিবর্তন"],
        "সিমেন্ট জমা একটা রাসায়নিক বিক্রিয়া; কংক্রিটকে আর গুঁড়ো আর জলে ফেরানো যায় না।"),
    mcq("What signs tell you a chemical change has happened?", ["A new substance, gas bubbles, colour change, heat or light", "Only a change of shape", "Only cutting into pieces", "Only melting"], 0,
        "Chemical changes make new substances; physical changes only change form.",
        "কোন চিহ্ন বলে যে রাসায়নিক পরিবর্তন ঘটেছে?", ["নতুন পদার্থ, গ্যাসের বুদবুদ, রং বদল, তাপ বা আলো", "শুধু আকার বদল", "শুধু টুকরো করা", "শুধু গলা"],
        "রাসায়নিক পরিবর্তন নতুন পদার্থ তৈরি করে; ভৌত পরিবর্তন শুধু রূপ বদলায়।"),
    mcq("Cutting a steel bar into two pieces is a...", ["Physical change - it is still steel", "Chemical change", "Kind of rusting", "Kind of burning"], 0,
        "Shape and size changed, but the material did not.",
        "একটা ইস্পাতের দণ্ড দুই টুকরো করা হলো...", ["ভৌত পরিবর্তন - তখনো ইস্পাত", "রাসায়নিক পরিবর্তন", "এক রকম মরচে ধরা", "এক রকম পোড়া"],
        "আকার আর মাপ বদলেছে, কিন্তু পদার্থ বদলায়নি।"),
    mcq("What three things does a fire need?", ["Fuel, oxygen (air) and heat", "Water, sand and ice", "Wind, rain and snow", "Metal, glass and stone"], 0,
        "Take away any one side of the 'fire triangle' and the fire goes out.",
        "আগুনের জন্য কোন তিনটি জিনিস লাগে?", ["জ্বালানি, অক্সিজেন (বাতাস) আর তাপ", "জল, বালি আর বরফ", "বাতাস, বৃষ্টি আর তুষার", "ধাতু, কাচ আর পাথর"],
        "'আগুনের ত্রিভুজের' যেকোনো একটা দিক সরালে আগুন নেভে।"),
    mcq("Why does throwing sand on a small fire put it out?", ["It cuts off the oxygen from the air", "Sand is cold fuel", "Sand is wet", "Sand makes more heat"], 0,
        "No oxygen, no fire. Fire buckets with sand are common at building sites.",
        "ছোট আগুনে বালি ছুড়লে নিভে যায় কেন?", ["বাতাসের অক্সিজেন বন্ধ করে দেয়", "বালি ঠান্ডা জ্বালানি", "বালি ভেজা", "বালি বেশি তাপ দেয়"],
        "অক্সিজেন নেই তো আগুন নেই। নির্মাণস্থলে বালির বালতি সাধারণ দৃশ্য।"),
    mcq("Why must you never use water on an electrical or oil fire?", ["Water can carry electricity or spread burning oil", "Water is a fuel", "Water makes fires colder only", "Water is too expensive"], 0,
        "Use the right extinguisher - and get an adult.",
        "বৈদ্যুতিক বা তেলের আগুনে কখনো জল দেবে না কেন?", ["জল বিদ্যুৎ বয়ে আনতে বা জ্বলন্ত তেল ছড়াতে পারে", "জল জ্বালানি", "জল শুধু আগুন ঠান্ডা করে", "জল খুব দামি"],
        "ঠিক অগ্নিনির্বাপক ব্যবহার করো - আর বড়দের ডাকো।"),
    mcq("Why are steel bridge parts sometimes covered with fire-resistant coatings?", ["Steel weakens badly when it gets very hot", "To make them shiny", "To make them heavier", "Steel catches fire like paper"], 0,
        "A vehicle fire under a bridge could soften steel - coatings buy precious time.",
        "ইস্পাতের সেতুর অংশে কখনো আগুন-প্রতিরোধী প্রলেপ দেওয়া হয় কেন?", ["খুব গরম হলে ইস্পাত মারাত্মক দুর্বল হয়", "চকচকে করতে", "ভারী করতে", "ইস্পাত কাগজের মতো জ্বলে"],
        "সেতুর নিচে গাড়িতে আগুন লাগলে ইস্পাত নরম হতে পারে - প্রলেপ মূল্যবান সময় দেয়।"),
    mcq("What is an 'acid'?", ["A sour-tasting substance, like lemon juice or vinegar", "A soapy substance", "A metal", "A gas only"], 0,
        "Weak acids are in fruit; strong acids can burn - never taste lab chemicals.",
        "'অ্যাসিড' কী?", ["টক স্বাদের পদার্থ, যেমন লেবুর রস বা ভিনিগার", "সাবানের মতো পদার্থ", "ধাতু", "শুধু গ্যাস"],
        "দুর্বল অ্যাসিড ফলে থাকে; শক্তিশালী অ্যাসিড পোড়াতে পারে - পরীক্ষাগারের রাসায়নিক কখনো চাখবে না।"),
    mcq("Which of these is an alkali (base)?", ["Soap", "Lemon juice", "Vinegar", "Orange juice"], 0,
        "Alkalis feel slippery, like soap; they are the opposite of acids.",
        "এগুলোর কোনটা ক্ষার?", ["সাবান", "লেবুর রস", "ভিনিগার", "কমলার রস"],
        "ক্ষার সাবানের মতো পিছল লাগে; এরা অ্যাসিডের বিপরীত।"),
    mcq("What does an indicator like litmus paper tell you?", ["Whether something is an acid or an alkali", "How heavy it is", "How long it is", "Its temperature"], 0,
        "Litmus turns red in acid and blue in alkali.",
        "লিটমাস কাগজের মতো নির্দেশক কী জানায়?", ["কোনো কিছু অ্যাসিড না ক্ষার", "কত ভারী", "কত লম্বা", "তার তাপমাত্রা"],
        "লিটমাস অ্যাসিডে লাল আর ক্ষারে নীল হয়।"),
    mcq("Blue litmus paper turns red in a liquid. The liquid is...", ["An acid", "An alkali", "Pure water", "Oil"], 0,
        "Red means acid.",
        "একটা তরলে নীল লিটমাস লাল হলো। তরলটা...", ["অ্যাসিড", "ক্ষার", "বিশুদ্ধ জল", "তেল"],
        "লাল মানে অ্যাসিড।"),
    mcq("Red cabbage juice can act as an indicator because...", ["It changes colour in acids and alkalis", "It is always red", "It is magnetic", "It boils easily"], 0,
        "A kitchen experiment: add vinegar (pinkish) or baking soda (greenish-blue).",
        "লাল বাঁধাকপির রস নির্দেশক হতে পারে কারণ...", ["অ্যাসিড আর ক্ষারে রং বদলায়", "সবসময় লাল", "চুম্বকীয়", "সহজে ফোটে"],
        "রান্নাঘরের পরীক্ষা: ভিনিগার দাও (গোলাপি) বা খাবার সোডা দাও (সবুজ-নীল)।"),
    mcq("What happens when acid and alkali are mixed in the right amounts?", ["They cancel out (neutralise)", "They explode always", "They turn to metal", "Nothing at all"], 0,
        "Neutralisation is why antacid tablets ease too much stomach acid.",
        "সঠিক মাপে অ্যাসিড আর ক্ষার মেশালে কী হয়?", ["একে অপরকে প্রশমিত করে", "সবসময় বিস্ফোরণ হয়", "ধাতু হয়ে যায়", "কিছুই না"],
        "প্রশমনের জন্যই অ্যান্টাসিড ট্যাবলেট পেটের বাড়তি অ্যাসিড কমায়।"),
    mcq("Why can acid rain damage stone bridges and statues?", ["Acids slowly react with stone like limestone and wear it away", "Acid rain is too heavy", "Rain is magnetic", "It cannot damage stone"], 0,
        "Pollution from burning fuels makes rain more acidic.",
        "অ্যাসিড বৃষ্টি পাথরের সেতু আর মূর্তির ক্ষতি করে কেন?", ["অ্যাসিড চুনাপাথরের মতো পাথরের সঙ্গে ধীরে বিক্রিয়া করে ক্ষয় করে", "অ্যাসিড বৃষ্টি খুব ভারী", "বৃষ্টি চুম্বকীয়", "পাথরের ক্ষতি করতে পারে না"],
        "জ্বালানি পোড়ানোর দূষণে বৃষ্টি বেশি অম্লীয় হয়।"),
    mcq("What happens when vinegar is poured on baking soda?", ["It fizzes and gives off carbon dioxide gas", "It freezes", "It turns into metal", "Nothing"], 0,
        "A new gas forms - a sure sign of a chemical change.",
        "খাবার সোডায় ভিনিগার ঢাললে কী হয়?", ["বুদবুদ ওঠে আর কার্বন ডাই-অক্সাইড গ্যাস বেরোয়", "জমে যায়", "ধাতু হয়ে যায়", "কিছুই না"],
        "নতুন গ্যাস তৈরি হয় - রাসায়নিক পরিবর্তনের নিশ্চিত চিহ্ন।"),
    mcq("What is a 'solution'?", ["A mixture where one substance dissolves evenly in a liquid", "A solid lump", "A broken bridge", "A gas cloud only"], 0,
        "Salt water is a solution: you cannot see the salt, but it is there.",
        "'দ্রবণ' কী?", ["যে মিশ্রণে একটা পদার্থ তরলে সমানভাবে গুলে যায়", "শক্ত দলা", "ভাঙা সেতু", "শুধু গ্যাসের মেঘ"],
        "নুন-জল একটা দ্রবণ: লবণ দেখা যায় না, কিন্তু আছে।"),
    mcq("In salty water, what is the 'solvent'?", ["The water", "The salt", "The glass", "The spoon"], 0,
        "The solvent does the dissolving; the solute (salt) gets dissolved.",
        "নোনা জলে 'দ্রাবক' কোনটা?", ["জল", "লবণ", "গ্লাস", "চামচ"],
        "দ্রাবক গোলায়; দ্রাব (লবণ) গোলে।"),
    mcq("How can you make sugar dissolve faster in water?", ["Use warm water and stir", "Use ice-cold water and wait", "Add sand", "Shine a torch on it"], 0,
        "Heat and stirring help the sugar spread through the water.",
        "জলে চিনি দ্রুত গোলাবে কীভাবে?", ["গরম জল ব্যবহার করে নাড়ো", "বরফ-ঠান্ডা জলে অপেক্ষা করো", "বালি দাও", "টর্চের আলো ফেলো"],
        "তাপ আর নাড়া চিনিকে জলে ছড়িয়ে দিতে সাহায্য করে।"),
    mcq("What is a 'saturated' solution?", ["One that cannot dissolve any more of the solute", "One with no solute", "A frozen one", "One that is magnetic"], 0,
        "Keep adding salt and eventually it settles at the bottom - the water is full.",
        "'সম্পৃক্ত' দ্রবণ কী?", ["যাতে আর দ্রাব গোলে না", "যাতে কোনো দ্রাব নেই", "জমে যাওয়া দ্রবণ", "চুম্বকীয় দ্রবণ"],
        "লবণ দিতে থাকলে শেষে তলায় জমে - জল ভরে গেছে।"),
    mcq("Which of these does NOT dissolve in water?", ["Sand", "Salt", "Sugar", "Instant coffee"], 0,
        "Sand is insoluble - useful, because concrete must not dissolve in rain!",
        "এগুলোর কোনটা জলে গোলে না?", ["বালি", "লবণ", "চিনি", "ইনস্ট্যান্ট কফি"],
        "বালি অদ্রাব্য - কাজের কথা, কারণ কংক্রিট বৃষ্টিতে গলে গেলে চলবে না!"),
    mcq("Muddy river water has sand in it. How do you remove the sand?", ["Filter it through filter paper", "Use a magnet", "Freeze it", "Shake it"], 0,
        "Water passes through the tiny holes; sand is trapped.",
        "নদীর ঘোলা জলে বালি আছে। বালি সরাবে কীভাবে?", ["ফিল্টার কাগজে ছাঁকো", "চুম্বক ব্যবহার করো", "জমাও", "ঝাঁকাও"],
        "জল ছোট ছিদ্র দিয়ে যায়; বালি আটকে থাকে।"),
    mcq("Which method gets dissolved salt back out of sea water?", ["Evaporate the water away", "Filter it", "Use a magnet", "Use a sieve"], 0,
        "Salt is dissolved, so filtering will not catch it; heat drives off the water.",
        "সমুদ্রের জল থেকে গোলা লবণ ফেরত পাওয়ার পদ্ধতি কোনটা?", ["জল বাষ্পীভূত করে", "ছেঁকে", "চুম্বক দিয়ে", "চালুনি দিয়ে"],
        "লবণ গুলে আছে, তাই ছাঁকনিতে ধরা পড়বে না; তাপ জল উড়িয়ে দেয়।"),
    mcq("How are iron nails separated from a pile of sand?", ["With a magnet", "With filter paper", "By evaporating", "By adding water"], 0,
        "Iron is magnetic; sand is not.",
        "এক গাদা বালি থেকে লোহার পেরেক আলাদা করা হয় কীভাবে?", ["চুম্বক দিয়ে", "ফিল্টার কাগজ দিয়ে", "বাষ্পীভবন করে", "জল দিয়ে"],
        "লোহা চুম্বকীয়; বালি নয়।"),
    mcq("Builders shake sand through a mesh to remove stones. This is called...", ["Sieving", "Evaporating", "Melting", "Burning"], 0,
        "A sieve separates by size: small grains fall through, big stones stay.",
        "নির্মাতারা পাথর সরাতে জালের মধ্য দিয়ে বালি ঝাঁকান। একে বলে...", ["চালা (চালুনিতে ছাঁকা)", "বাষ্পীভবন", "গলানো", "পোড়ানো"],
        "চালুনি মাপ অনুযায়ী আলাদা করে: ছোট দানা পড়ে যায়, বড় পাথর থাকে।"),
    mcq("Why do builders sieve sand before making mortar?", ["Stones and lumps make weak, uneven mortar", "To make it heavier", "To change its colour", "Sieving adds cement"], 0,
        "Clean, even sand gives smooth, strong mortar.",
        "মশলা বানানোর আগে নির্মাতারা বালি চালেন কেন?", ["পাথর আর দলা দুর্বল, অসমান মশলা বানায়", "ভারী করতে", "রং বদলাতে", "চালায় সিমেন্ট যোগ হয়"],
        "পরিষ্কার, সমান বালি মসৃণ, শক্ত মশলা দেয়।"),
    mcq("Why is sea sand usually washed before being used in concrete?", ["Salt in it can make steel bars inside rust", "It is too dry", "It is too heavy", "Sea sand is magnetic"], 0,
        "Salt speeds up rusting of the steel reinforcement.",
        "কংক্রিটে ব্যবহারের আগে সাধারণত সমুদ্রের বালি ধোয়া হয় কেন?", ["তার লবণ ভেতরের ইস্পাতের রডে মরচে ধরাতে পারে", "খুব শুকনো", "খুব ভারী", "সমুদ্রের বালি চুম্বকীয়"],
        "লবণ রডের মরচে ধরা দ্রুত করে।"),
    mcq("What job does mortar do in a brick bridge pier?", ["Sticking bricks or stones together", "Painting walls", "Making glass", "Fuel for engines"], 0,
        "Mortar is cement (or lime), sand and water.",
        "ইটের সেতু-থামে মশলা (মর্টার) কী কাজ করে?", ["ইট বা পাথর জোড়া লাগাতে", "দেওয়াল রং করতে", "কাচ বানাতে", "ইঞ্জিনের জ্বালানি"],
        "মশলা হলো সিমেন্ট (বা চুন), বালি আর জল।"),
    mcq("What happens if you add far too much water to concrete?", ["It becomes weaker when it sets", "It becomes stronger", "It sets instantly", "It becomes lighter than air"], 0,
        "Extra water leaves tiny holes as it dries - the right amount matters.",
        "কংক্রিটে অনেক বেশি জল দিলে কী হয়?", ["জমার পর দুর্বল হয়", "আরও শক্ত হয়", "সঙ্গে সঙ্গে জমে", "বাতাসের চেয়ে হালকা হয়"],
        "বাড়তি জল শুকিয়ে ছোট ছিদ্র রেখে যায় - সঠিক মাপ জরুরি।"),
    mcq("Why is new concrete kept damp for several days ('curing')?", ["It needs water to keep reacting and gain strength", "To keep it clean", "To cool the workers", "To make it float"], 0,
        "Concrete that dries too fast can crack and stay weak.",
        "নতুন কংক্রিট কয়েক দিন ভেজা রাখা হয় ('কিউরিং') কেন?", ["শক্তি পেতে বিক্রিয়া চালিয়ে যেতে তার জল লাগে", "পরিষ্কার রাখতে", "কর্মীদের ঠান্ডা রাখতে", "ভাসাতে"],
        "খুব দ্রুত শুকোনো কংক্রিট ফেটে দুর্বল থেকে যেতে পারে।"),
    mcq("Why is steel bar (rebar) placed inside concrete beams?", ["Concrete is strong in squeezing but weak in stretching; steel takes the stretch", "To make it shiny", "To make it lighter", "Steel dissolves in concrete"], 0,
        "Together they make reinforced concrete - the most common bridge material.",
        "কংক্রিটের বিমের ভেতরে ইস্পাতের রড (রিবার) রাখা হয় কেন?", ["কংক্রিট চাপে শক্ত, টানে দুর্বল; ইস্পাত টান সামলায়", "চকচকে করতে", "হালকা করতে", "ইস্পাত কংক্রিটে গলে যায়"],
        "দুটো মিলে হয় রড-কংক্রিট (আরসিসি) - সেতুর সবচেয়ে প্রচলিত উপাদান।"),
    mcq("A steel railing has rusted. Which two things around it caused this?", ["Water and oxygen", "Sand and sugar", "Heat and light", "Salt and wood"], 0,
        "Keep out either water or air and iron will not rust.",
        "একটা ইস্পাতের রেলিংয়ে মরচে ধরেছে। চারপাশের কোন দুটো জিনিস এর কারণ?", ["জল আর অক্সিজেন", "বালি আর চিনি", "তাপ আর আলো", "লবণ আর কাঠ"],
        "জল বা বাতাস যেকোনো একটা আটকালে লোহায় মরচে ধরবে না।"),
    mcq("Which nail rusts fastest?", ["One in salty water", "One in dry air", "One in oil", "One in a sealed dry jar"], 0,
        "Salt speeds up rusting - a big problem for bridges near the sea or salted roads.",
        "কোন পেরেকে সবচেয়ে দ্রুত মরচে ধরে?", ["নোনা জলের পেরেক", "শুকনো বাতাসের পেরেক", "তেলের পেরেক", "বন্ধ শুকনো বয়ামের পেরেক"],
        "লবণ মরচে ধরা দ্রুত করে - সমুদ্রের কাছের বা লবণ ছড়ানো রাস্তার সেতুর বড় সমস্যা।"),
    mcq("Which of these protects a steel bridge from rust?", ["Paint", "Washing it with salt water", "Leaving it bare", "Scratching it"], 0,
        "Paint keeps water and air away from the steel.",
        "এগুলোর কোনটা ইস্পাতের সেতুকে মরচে থেকে রক্ষা করে?", ["রং", "নোনা জলে ধোয়া", "খোলা রাখা", "আঁচড় কাটা"],
        "রং ইস্পাত থেকে জল আর বাতাস দূরে রাখে।"),
    mcq("A bolt is labelled 'galvanised'. What was done to it?", ["Coating steel with zinc to stop rust", "Painting with gold", "Melting steel", "Freezing steel"], 0,
        "Zinc protects steel even if scratched - many bridge bolts and railings are galvanised.",
        "একটা বোল্টে লেখা 'গ্যালভানাইজড'। তার উপর কী করা হয়েছে?", ["মরচে থামাতে ইস্পাতে দস্তার প্রলেপ", "সোনা দিয়ে রং", "ইস্পাত গলানো", "ইস্পাত জমানো"],
        "আঁচড় লাগলেও দস্তা ইস্পাতকে রক্ষা করে - অনেক সেতুর বোল্ট আর রেলিং গ্যালভানাইজড।"),
    mcq("Why do bicycle chains get oiled?", ["Oil reduces friction and keeps water off to stop rust", "Oil makes them heavier", "For the smell", "Oil makes them magnetic"], 0,
        "Grease and oil do two jobs: smooth movement and rust protection.",
        "সাইকেলের চেনে তেল দেওয়া হয় কেন?", ["তেল ঘর্ষণ কমায় আর জল দূরে রেখে মরচে থামায়", "তেল ভারী করে", "গন্ধের জন্য", "তেল চুম্বকীয় করে"],
        "গ্রিজ আর তেল দুটো কাজ করে: মসৃণ চলা আর মরচে থেকে রক্ষা।"),
    mcq("Why is rust bad for a bridge?", ["Rust is weak and flaky, so the steel gets thinner and weaker", "Rust makes steel stronger", "Rust is just a nice colour", "Rust makes bridges lighter and safer"], 0,
        "Inspectors look for rust and repaint before it eats into the steel.",
        "মরচে সেতুর জন্য খারাপ কেন?", ["মরচে দুর্বল আর ঝুরঝুরে, তাই ইস্পাত পাতলা আর দুর্বল হয়", "মরচে ইস্পাত শক্ত করে", "মরচে শুধু সুন্দর রং", "মরচে সেতু হালকা আর নিরাপদ করে"],
        "পরিদর্শকেরা মরচে খোঁজেন আর ইস্পাত ক্ষয়ের আগেই আবার রং করেন।"),
    mcq("Which metal does NOT rust (though it can tarnish)?", ["Gold", "Iron", "Steel", "Cast iron"], 0,
        "Only iron and steel rust; gold stays shiny for thousands of years.",
        "কোন ধাতুতে মরচে ধরে না (যদিও মলিন হতে পারে)?", ["সোনা", "লোহা", "ইস্পাত", "ঢালাই লোহা"],
        "কেবল লোহা আর ইস্পাতে মরচে ধরে; সোনা হাজার বছর চকচকে থাকে।"),
    mcq("Why is aluminium used for some lightweight footbridges?", ["It is light and does not rust like iron", "It is the heaviest metal", "It is magnetic", "It melts in the sun"], 0,
        "Aluminium forms a thin protective layer instead of flaky rust.",
        "কিছু হালকা হাঁটার সেতুতে অ্যালুমিনিয়াম ব্যবহার হয় কেন?", ["হালকা আর লোহার মতো মরচে ধরে না", "সবচেয়ে ভারী ধাতু", "চুম্বকীয়", "রোদে গলে যায়"],
        "অ্যালুমিনিয়াম ঝুরঝুরে মরচের বদলে পাতলা রক্ষাকারী স্তর তৈরি করে।"),
    mcq("What gas makes up most of the air?", ["Nitrogen", "Oxygen", "Carbon dioxide", "Helium"], 0,
        "Air is about 78% nitrogen and 21% oxygen.",
        "বাতাসের বেশিরভাগ কোন গ্যাস?", ["নাইট্রোজেন", "অক্সিজেন", "কার্বন ডাই-অক্সাইড", "হিলিয়াম"],
        "বাতাসে প্রায় 78% নাইট্রোজেন আর 21% অক্সিজেন।"),
    mcq("Which gas do we need to breathe in to live?", ["Oxygen", "Nitrogen", "Carbon dioxide", "Smoke"], 0,
        "Our bodies use oxygen to release energy from food.",
        "বাঁচতে আমাদের কোন গ্যাস শ্বাসে নিতে হয়?", ["অক্সিজেন", "নাইট্রোজেন", "কার্বন ডাই-অক্সাইড", "ধোঁয়া"],
        "শরীর খাবার থেকে শক্তি বের করতে অক্সিজেন ব্যবহার করে।"),
    mcq("Which gas is in the bubbles of fizzy drinks?", ["Carbon dioxide", "Oxygen", "Hydrogen", "Nitrogen"], 0,
        "Carbon dioxide is dissolved under pressure and escapes when you open the bottle.",
        "সোডা-পানীয়ের বুদবুদে কোন গ্যাস?", ["কার্বন ডাই-অক্সাইড", "অক্সিজেন", "হাইড্রোজেন", "নাইট্রোজেন"],
        "কার্বন ডাই-অক্সাইড চাপে গুলে থাকে আর বোতল খুললে বেরিয়ে যায়।"),
    mcq("What does burning petrol and diesel release into the air?", ["Carbon dioxide and other pollutants", "Only pure oxygen", "Only water", "Nothing"], 0,
        "Exhaust gases add to air pollution and climate change.",
        "পেট্রোল আর ডিজেল পোড়ালে বাতাসে কী মেশে?", ["কার্বন ডাই-অক্সাইড আর অন্য দূষক", "শুধু বিশুদ্ধ অক্সিজেন", "শুধু জল", "কিছুই না"],
        "নিষ্কাশিত গ্যাস বায়ুদূষণ আর জলবায়ু পরিবর্তন বাড়ায়।"),
    mcq("How can a new bridge reduce air pollution?", ["Shorter routes mean vehicles burn less fuel", "Bridges absorb all smoke", "Bridges stop cars", "It cannot help"], 0,
        "Cutting a long detour saves fuel, money and pollution every day.",
        "নতুন সেতু কীভাবে বায়ুদূষণ কমাতে পারে?", ["ছোট পথে গাড়ি কম জ্বালানি পোড়ায়", "সেতু সব ধোঁয়া শোষণ করে", "সেতু গাড়ি থামায়", "সাহায্য করতে পারে না"],
        "লম্বা ঘুরপথ বাদ গেলে প্রতিদিন জ্বালানি, টাকা আর দূষণ বাঁচে।"),
    mcq("Why is river water usually treated before we drink it?", ["It may contain germs and dirt", "It is too cold", "It is too blue", "It is always salty"], 0,
        "Water works filter and disinfect water to make it safe.",
        "নদীর জল খাওয়ার আগে সাধারণত শোধন করা হয় কেন?", ["তাতে জীবাণু আর ময়লা থাকতে পারে", "খুব ঠান্ডা", "খুব নীল", "সবসময় নোনতা"],
        "জল-শোধনাগার জল ছেঁকে আর জীবাণুমুক্ত করে নিরাপদ করে।"),
    mcq("How does boiling make water safer to drink?", ["The heat kills most germs", "It removes all salt", "It adds vitamins", "It makes the water heavier"], 0,
        "Boiling kills germs but does not remove dissolved chemicals.",
        "ফোটালে জল খাওয়ার জন্য নিরাপদ হয় কীভাবে?", ["তাপ বেশিরভাগ জীবাণু মারে", "সব লবণ সরায়", "ভিটামিন যোগ করে", "জল ভারী করে"],
        "ফোটালে জীবাণু মরে, কিন্তু গোলা রাসায়নিক সরে না।"),
    mcq("What is a sand-and-gravel water filter good at removing?", ["Mud and bits floating in the water", "Dissolved salt", "All germs completely", "Sugar"], 0,
        "Layers of sand and gravel trap solid particles; germs need boiling or disinfecting too.",
        "বালি-আর-কাঁকরের জল-ছাঁকনি কী সরাতে ভালো?", ["জলে ভাসমান কাদা আর টুকরো", "গোলা লবণ", "পুরোপুরি সব জীবাণু", "চিনি"],
        "বালি আর কাঁকরের স্তর কঠিন কণা আটকায়; জীবাণুর জন্য ফোটানো বা জীবাণুনাশও লাগে।"),
    mcq("Why must chemicals from building sites never be poured into rivers?", ["They poison fish, plants and drinking water", "Rivers like chemicals", "They make rivers clean", "It is fine"], 0,
        "Good builders collect and safely dispose of waste.",
        "নির্মাণস্থলের রাসায়নিক কখনো নদীতে ঢালা চলবে না কেন?", ["মাছ, গাছ আর খাবার জল বিষিয়ে দেয়", "নদী রাসায়নিক পছন্দ করে", "নদী পরিষ্কার করে", "কোনো অসুবিধা নেই"],
        "ভালো নির্মাতারা বর্জ্য জমিয়ে নিরাপদে ফেলেন।"),
    mcq("What does 'recycling' mean?", ["Turning used materials into new products", "Throwing everything away", "Riding a bicycle twice", "Burning rubbish"], 0,
        "Recycled steel is used again in new beams and cars.",
        "'পুনর্ব্যবহার' (রিসাইক্লিং) মানে কী?", ["ব্যবহৃত উপাদান থেকে নতুন পণ্য বানানো", "সব কিছু ফেলে দেওয়া", "দুবার সাইকেল চালানো", "আবর্জনা পোড়ানো"],
        "পুনর্ব্যবহৃত ইস্পাত আবার নতুন বিম আর গাড়িতে লাগে।"),
    mcq("Which material can be recycled again and again without losing strength?", ["Steel", "Paper", "Food scraps", "Cloth"], 0,
        "Steel is one of the most recycled materials in the world.",
        "কোন উপাদান শক্তি না হারিয়ে বারবার পুনর্ব্যবহার করা যায়?", ["ইস্পাত", "কাগজ", "খাবারের উচ্ছিষ্ট", "কাপড়"],
        "ইস্পাত পৃথিবীর সবচেয়ে বেশি পুনর্ব্যবহৃত উপাদানগুলোর একটি।"),
    mcq("What can old concrete from a demolished bridge be used for?", ["Crushed into gravel for new roads", "Nothing - it vanishes", "Food", "Drinking water"], 0,
        "Crushed concrete makes a good base layer for roads.",
        "ভাঙা সেতুর পুরোনো কংক্রিট কী কাজে লাগানো যায়?", ["গুঁড়িয়ে নতুন রাস্তার পাথরকুচি", "কিছুই না - উধাও হয়ে যায়", "খাবার", "খাবার জল"],
        "গুঁড়ো কংক্রিট রাস্তার ভালো নিচের স্তর হয়।"),
    mcq("Why is plastic litter a big problem?", ["Most plastic takes hundreds of years to break down", "Plastic disappears in a day", "Plastic is food for fish", "It is not a problem"], 0,
        "Reduce, reuse, recycle!",
        "প্লাস্টিকের আবর্জনা বড় সমস্যা কেন?", ["বেশিরভাগ প্লাস্টিক ভাঙতে শত শত বছর লাগে", "প্লাস্টিক এক দিনে উধাও হয়", "প্লাস্টিক মাছের খাবার", "সমস্যা নয়"],
        "কম ব্যবহার, আবার ব্যবহার, পুনর্ব্যবহার!"),
    mcq("Which of these is 'biodegradable'?", ["A banana peel", "A plastic bottle", "A glass jar", "A steel can"], 0,
        "Biodegradable things are broken down by tiny living things.",
        "এগুলোর কোনটা 'জৈব-বিয়োজ্য'?", ["কলার খোসা", "প্লাস্টিকের বোতল", "কাচের বয়াম", "ইস্পাতের কৌটো"],
        "জৈব-বিয়োজ্য জিনিস ক্ষুদ্র জীব ভেঙে ফেলে।"),
    mcq("How is glass made?", ["By melting sand with other minerals at very high heat", "By freezing water", "By drying mud", "By pressing paper"], 0,
        "Sand (silica) melts at about 1700 °C and cools into glass.",
        "কাচ কীভাবে তৈরি হয়?", ["খুব উঁচু তাপে অন্য খনিজের সঙ্গে বালি গলিয়ে", "জল জমিয়ে", "কাদা শুকিয়ে", "কাগজ চেপে"],
        "বালি (সিলিকা) প্রায় 1700 °C-এ গলে ঠান্ডা হয়ে কাচ হয়।"),
    mcq("How is iron got from iron ore?", ["Heating the ore with carbon in a blast furnace", "Washing it in water", "Freezing it", "Crushing it only"], 0,
        "The furnace removes oxygen from the ore, leaving molten iron.",
        "লোহার আকরিক থেকে লোহা পাওয়া যায় কীভাবে?", ["মারুত চুল্লিতে কার্বনের সঙ্গে আকরিক উত্তপ্ত করে", "জলে ধুয়ে", "জমিয়ে", "শুধু গুঁড়িয়ে"],
        "চুল্লি আকরিক থেকে অক্সিজেন সরায়, গলিত লোহা পড়ে থাকে।"),
    mcq("What is steel made mostly from?", ["Iron with a little carbon", "Copper and tin", "Sand and clay", "Aluminium and gold"], 0,
        "A tiny bit of carbon makes iron much stronger and tougher.",
        "ইস্পাত মূলত কী দিয়ে তৈরি?", ["লোহা আর সামান্য কার্বন", "তামা আর টিন", "বালি আর কাদা", "অ্যালুমিনিয়াম আর সোনা"],
        "সামান্য কার্বন লোহাকে অনেক শক্ত আর মজবুত করে।"),
    mcq("Steel, brass and bronze are all 'alloys'. What does that mean?", ["A mixture of a metal with other elements", "A pure metal only", "A kind of plastic", "A type of glass"], 0,
        "Steel, brass and bronze are alloys - often stronger than pure metals.",
        "ইস্পাত, পিতল আর ব্রোঞ্জ সবই 'সংকর ধাতু'। এর মানে কী?", ["একটা ধাতুর সঙ্গে অন্য মৌলের মিশ্রণ", "শুধু বিশুদ্ধ ধাতু", "এক রকম প্লাস্টিক", "এক রকম কাচ"],
        "ইস্পাত, পিতল আর ব্রোঞ্জ সংকর ধাতু - প্রায়ই বিশুদ্ধ ধাতুর চেয়ে শক্ত।"),
    mcq("Brass is an alloy of which two metals?", ["Copper and zinc", "Iron and carbon", "Gold and silver", "Tin and lead"], 0,
        "Brass is used for door handles, taps and musical instruments.",
        "পিতল কোন দুটো ধাতুর সংকর?", ["তামা আর দস্তা", "লোহা আর কার্বন", "সোনা আর রুপো", "টিন আর সিসা"],
        "দরজার হাতল, কল আর বাদ্যযন্ত্রে পিতল ব্যবহার হয়।"),
    mcq("What is wood mainly made of?", ["Fibres from plants (cellulose)", "Metal", "Glass", "Stone"], 0,
        "Long fibres make wood strong along the grain - good for beams.",
        "কাঠ মূলত কী দিয়ে তৈরি?", ["উদ্ভিদের তন্তু (সেলুলোজ)", "ধাতু", "কাচ", "পাথর"],
        "লম্বা তন্তু আঁশ বরাবর কাঠকে শক্ত করে - বিমের জন্য ভালো।"),
    mcq("Why is wood used outdoors often treated with chemicals?", ["To stop rot, fungi and insects", "To make it rust", "To make it melt", "To make it magnetic"], 0,
        "Treated timber lasts much longer in bridges and fences.",
        "বাইরে ব্যবহৃত কাঠে প্রায়ই রাসায়নিক দেওয়া হয় কেন?", ["পচন, ছত্রাক আর পোকা আটকাতে", "মরচে ধরাতে", "গলাতে", "চুম্বকীয় করতে"],
        "শোধিত কাঠ সেতু আর বেড়ায় অনেক দিন টেকে।"),
    mcq("Why is bamboo a good building material in many villages?", ["It is light, strong, grows fast and is cheap", "It never needs looking after", "It is a metal", "It is fireproof"], 0,
        "Bamboo footbridges are common in Bengal - but they need regular checks and care.",
        "অনেক গ্রামে বাঁশ ভালো নির্মাণ-উপাদান কেন?", ["হালকা, শক্ত, দ্রুত বাড়ে আর সস্তা", "কখনো যত্ন লাগে না", "এটা ধাতু", "আগুনে পোড়ে না"],
        "বাংলায় বাঁশের সাঁকো সাধারণ - তবে নিয়মিত পরীক্ষা আর যত্ন লাগে।"),
    mcq("What is the 'melting point' of a material?", ["The temperature at which it turns from solid to liquid", "Its weight", "Its colour", "Where it is mined"], 0,
        "Ice melts at 0 °C; steel at about 1400 °C.",
        "কোনো উপাদানের 'গলনাঙ্ক' কী?", ["যে তাপমাত্রায় কঠিন থেকে তরল হয়", "তার ওজন", "তার রং", "যেখানে খনি থেকে ওঠে"],
        "বরফ 0 °C-এ গলে; ইস্পাত প্রায় 1400 °C-এ।"),
    mcq("Why are metals melted and poured into moulds?", ["To shape them into parts like bolts and brackets", "To make them disappear", "To cool them", "To make them softer forever"], 0,
        "This is called casting - the metal sets in the mould's shape.",
        "ধাতু গলিয়ে ছাঁচে ঢালা হয় কেন?", ["বোল্ট আর বন্ধনীর মতো অংশে আকার দিতে", "উধাও করতে", "ঠান্ডা করতে", "চিরকাল নরম করতে"],
        "একে বলে ঢালাই - ধাতু ছাঁচের আকারে জমে।"),
    mcq("What is a 'property' of a material?", ["A feature, like how hard, heavy or flexible it is", "Who owns it", "Its price tag", "Its name"], 0,
        "Engineers choose materials by their properties.",
        "উপাদানের 'ধর্ম' কী?", ["একটা বৈশিষ্ট্য, যেমন কত শক্ত, ভারী বা নমনীয়", "কার মালিকানা", "তার দামের ট্যাগ", "তার নাম"],
        "প্রকৌশলীরা ধর্ম দেখে উপাদান বাছেন।"),
    mcq("Which property is most important for bridge cables?", ["Strong when pulled (high tensile strength)", "Bright colour", "Soft and squashy", "Easy to dissolve"], 0,
        "Cables carry huge pulling forces.",
        "সেতুর তারের জন্য কোন ধর্ম সবচেয়ে জরুরি?", ["টানে শক্ত (উচ্চ টানশক্তি)", "উজ্জ্বল রং", "নরম আর থলথলে", "সহজে গোলে"],
        "তার বিশাল টানের বল বয়।"),
    mcq("Which property matters most for a bridge's concrete pillars?", ["Strong when squeezed (compressive strength)", "Stretchy like rubber", "Floats on water", "Transparent"], 0,
        "Pillars are pushed down by the weight above.",
        "সেতুর কংক্রিটের থামের জন্য কোন ধর্ম সবচেয়ে জরুরি?", ["চাপে শক্ত (সংনমন-শক্তি)", "রবারের মতো স্থিতিস্থাপক", "জলে ভাসে", "স্বচ্ছ"],
        "উপরের ওজন থামকে নিচে ঠেলে।"),
    mcq("Why are car tyres made of rubber?", ["Rubber is flexible, grips the road and is waterproof", "Rubber is the hardest material", "Rubber is magnetic", "Rubber conducts electricity well"], 0,
        "Rubber cushions bumps and grips.",
        "গাড়ির টায়ার রবারের হয় কেন?", ["রবার নমনীয়, রাস্তা আঁকড়ে ধরে আর জলরোধী", "রবার সবচেয়ে শক্ত", "রবার চুম্বকীয়", "রবার ভালো বিদ্যুৎ পরিবাহী"],
        "রবার ঝাঁকুনি সামলায় আর আঁকড়ে ধরে।"),
    mcq("Why do bridges sit on rubber 'bearings' on top of their pillars?", ["Rubber lets the deck move a little as it heats, cools and carries traffic", "Rubber makes the bridge bounce for fun", "To make it lighter", "To stop electricity"], 0,
        "Bearings allow small movements so the structure is not damaged.",
        "সেতু তার থামের উপর রবারের 'বিয়ারিং'-এ বসে কেন?", ["গরম-ঠান্ডা আর যানবাহনে পাটাতনকে একটু সরতে দেয়", "মজা করে সেতু লাফাতে", "হালকা করতে", "বিদ্যুৎ থামাতে"],
        "বিয়ারিং ছোট নড়াচড়া হতে দেয়, যাতে কাঠামোর ক্ষতি না হয়।"),
    mcq("What does waterproof mean?", ["Water cannot get through it", "It dissolves in water", "It is made of water", "It floats"], 0,
        "Raincoats, roofs and bridge deck membranes are waterproof.",
        "জলরোধী মানে কী?", ["জল ভেদ করতে পারে না", "জলে গোলে", "জল দিয়ে তৈরি", "ভাসে"],
        "রেইনকোট, ছাদ আর সেতুর পাটাতনের আস্তরণ জলরোধী।"),
    mcq("Why do bridge decks have a waterproof layer under the road surface?", ["To stop water and salt soaking into the concrete and rusting the steel", "To make cars faster", "To keep the road warm", "To make it heavier"], 0,
        "Keeping water out makes the bridge last much longer.",
        "সেতুর পাটাতনে রাস্তার তলের নিচে জলরোধী স্তর থাকে কেন?", ["জল আর লবণ কংক্রিটে ঢুকে রডে মরচে ধরাতে না দিতে", "গাড়ি দ্রুত চালাতে", "রাস্তা গরম রাখতে", "ভারী করতে"],
        "জল আটকালে সেতু অনেক দিন টেকে।"),
    mcq("What is 'evaporation'?", ["A liquid turning into a gas", "A gas turning into a liquid", "A solid melting", "A liquid freezing"], 0,
        "Puddles disappear on sunny days by evaporating.",
        "'বাষ্পীভবন' কী?", ["তরলের গ্যাসে বদলানো", "গ্যাসের তরলে বদলানো", "কঠিনের গলা", "তরলের জমা"],
        "রোদের দিনে ডোবার জল বাষ্পীভূত হয়ে উধাও হয়।"),
    mcq("What is 'condensation'?", ["A gas cooling and turning into a liquid", "A liquid turning to gas", "A solid turning to gas", "Burning"], 0,
        "Water droplets on a cold glass come from water vapour in the air.",
        "'ঘনীভবন' কী?", ["গ্যাস ঠান্ডা হয়ে তরলে বদলানো", "তরলের গ্যাসে বদলানো", "কঠিনের গ্যাসে বদলানো", "পোড়া"],
        "ঠান্ডা গ্লাসের গায়ে জলের ফোঁটা আসে বাতাসের জলীয় বাষ্প থেকে।"),
    mcq("How is salt collected from sea water in salt pans?", ["The sun evaporates the water, leaving salt", "By freezing the sea", "With magnets", "By filtering"], 0,
        "Shallow pools let sunlight and wind dry the water away.",
        "লবণের খেতে সমুদ্রের জল থেকে লবণ কীভাবে সংগ্রহ হয়?", ["রোদে জল বাষ্পীভূত হয়ে লবণ পড়ে থাকে", "সমুদ্র জমিয়ে", "চুম্বক দিয়ে", "ছেঁকে"],
        "অগভীর পুকুরে রোদ আর বাতাস জল শুকিয়ে দেয়।"),
    mcq("Why must cement bags be kept dry before use?", ["Damp cement starts setting into lumps and is wasted", "Dry cement is heavier", "Water makes cement magnetic", "Cement grows in water"], 0,
        "Store cement off the ground and under cover.",
        "ব্যবহারের আগে সিমেন্টের বস্তা শুকনো রাখতে হয় কেন?", ["ভেজা সিমেন্ট দলা পাকিয়ে জমতে শুরু করে আর নষ্ট হয়", "শুকনো সিমেন্ট ভারী", "জল সিমেন্টকে চুম্বকীয় করে", "জলে সিমেন্ট বাড়ে"],
        "সিমেন্ট মাটি থেকে উঁচুতে আর ঢাকা জায়গায় রাখো।"),
    mcq("What is 'lime' used for in old buildings and bridges?", ["Making mortar to join stones", "Making glass windows", "As a fuel", "As paint for cars"], 0,
        "Lime mortar was used for centuries before modern cement.",
        "পুরোনো বাড়ি আর সেতুতে 'চুন' কীসে ব্যবহার হতো?", ["পাথর জোড়ার মশলা বানাতে", "কাচের জানালা বানাতে", "জ্বালানি হিসেবে", "গাড়ির রং হিসেবে"],
        "আধুনিক সিমেন্টের আগে শত শত বছর চুন-মশলা ব্যবহার হয়েছে।"),
    mcq("Why do builders wear gloves when handling wet cement?", ["Wet cement is alkaline and can burn skin", "Cement is hot as fire", "Cement is sticky glue only", "No reason"], 0,
        "Gloves, boots and goggles protect against cement burns.",
        "ভেজা সিমেন্ট ধরার সময় নির্মাতারা দস্তানা পরেন কেন?", ["ভেজা সিমেন্ট ক্ষারীয় আর ত্বক পোড়াতে পারে", "সিমেন্ট আগুনের মতো গরম", "সিমেন্ট শুধু আঠালো", "কোনো কারণ নেই"],
        "দস্তানা, বুট আর চশমা সিমেন্টের পোড়া থেকে বাঁচায়।"),
    mcq("What do hazard symbols on chemical bottles tell you?", ["The dangers, like flammable, toxic or corrosive", "The price", "The colour inside", "The expiry date only"], 0,
        "Always read labels and follow the safety instructions.",
        "রাসায়নিকের বোতলের বিপদ-চিহ্ন কী জানায়?", ["বিপদের ধরন, যেমন দাহ্য, বিষাক্ত বা ক্ষয়কারী", "দাম", "ভেতরের রং", "শুধু মেয়াদ শেষের তারিখ"],
        "সবসময় লেবেল পড়ো আর নিরাপত্তার নির্দেশ মানো।"),
    mcq("What does 'corrosive' mean on a label?", ["It can eat away skin or materials", "It smells nice", "It is safe to drink", "It is magnetic"], 0,
        "Strong acids and alkalis are corrosive - handle only with protection.",
        "লেবেলে 'ক্ষয়কারী' মানে কী?", ["ত্বক বা উপাদান ক্ষয় করতে পারে", "সুগন্ধি", "খাওয়া নিরাপদ", "চুম্বকীয়"],
        "শক্তিশালী অ্যাসিড আর ক্ষার ক্ষয়কারী - সুরক্ষা নিয়েই ধরো।"),
    mcq("What does 'flammable' mean?", ["It catches fire easily", "It cannot burn", "It is made of water", "It is very cold"], 0,
        "Keep flammable things like petrol and paint thinner away from flames.",
        "'দাহ্য' মানে কী?", ["সহজে আগুন ধরে", "পুড়তে পারে না", "জল দিয়ে তৈরি", "খুব ঠান্ডা"],
        "পেট্রোল আর রং-পাতলাকারীর মতো দাহ্য জিনিস আগুন থেকে দূরে রাখো।"),
    mcq("Why does bread dough rise?", ["Yeast makes carbon dioxide gas bubbles", "Flour is light", "Water expands", "Salt pushes it up"], 0,
        "Tiny yeast cells feed on sugar and give off gas - a chemical change.",
        "রুটির মণ্ড ফোলে কেন?", ["ইস্ট কার্বন ডাই-অক্সাইড গ্যাসের বুদবুদ তৈরি করে", "ময়দা হালকা", "জল প্রসারিত হয়", "লবণ উপরে ঠেলে"],
        "ছোট্ট ইস্ট কোষ চিনি খেয়ে গ্যাস ছাড়ে - একটা রাসায়নিক পরিবর্তন।"),
    mcq("Why does a cut apple turn brown?", ["It reacts with oxygen in the air", "It gets cold", "It absorbs light", "It dries into sand"], 0,
        "A squeeze of lemon juice slows the browning.",
        "কাটা আপেল বাদামি হয় কেন?", ["বাতাসের অক্সিজেনের সঙ্গে বিক্রিয়া করে", "ঠান্ডা হয়", "আলো শোষণ করে", "শুকিয়ে বালি হয়"],
        "একটু লেবুর রস দিলে বাদামি হওয়া ধীর হয়।"),
    mcq("Why do fireworks have different colours?", ["Different metal compounds give off different coloured light when burned", "They are painted", "The sky changes colour", "Sound makes colour"], 0,
        "Copper gives blue-green, sodium gives yellow, strontium gives red.",
        "আতশবাজির রং আলাদা হয় কেন?", ["আলাদা ধাতুর যৌগ পুড়লে আলাদা রঙের আলো দেয়", "রং করা থাকে", "আকাশের রং বদলায়", "শব্দ রং তৈরি করে"],
        "তামা নীল-সবুজ, সোডিয়াম হলুদ আর স্ট্রনশিয়াম লাল দেয়।"),
    mcq("What is 'pollution'?", ["Harmful substances added to air, water or land", "Fresh rain", "Clean wind", "Healthy soil"], 0,
        "Good engineering keeps building sites from polluting rivers and air.",
        "'দূষণ' কী?", ["বাতাস, জল বা মাটিতে মেশা ক্ষতিকর পদার্থ", "টাটকা বৃষ্টি", "পরিষ্কার বাতাস", "স্বাস্থ্যকর মাটি"],
        "ভালো প্রকৌশল নির্মাণস্থলকে নদী আর বাতাস দূষিত করতে দেয় না।"),
    mcq("Why do building sites spray water on dusty roads?", ["To stop dust polluting the air people breathe", "To grow grass", "To cool the trucks", "To wash the sky"], 0,
        "Dust can harm lungs - damping it down protects workers and neighbours.",
        "নির্মাণস্থল ধুলোময় রাস্তায় জল ছিটায় কেন?", ["মানুষের শ্বাসের বাতাসে ধুলো মিশতে না দিতে", "ঘাস জন্মাতে", "ট্রাক ঠান্ডা করতে", "আকাশ ধুতে"],
        "ধুলো ফুসফুসের ক্ষতি করে - ভিজিয়ে রাখলে কর্মী আর প্রতিবেশীরা নিরাপদ থাকেন।"),
    mcq("What is the chemical symbol for iron?", ["Fe", "Ir", "I", "In"], 0,
        "Fe comes from 'ferrum', the Latin word for iron.",
        "লোহার রাসায়নিক সংকেত কী?", ["Fe", "Ir", "I", "In"],
        "Fe এসেছে লোহার লাতিন নাম 'ফেরাম' থেকে।"),
    mcq("What is water's chemical formula?", ["H2O", "CO2", "O2", "N2"], 0,
        "Two hydrogen atoms joined to one oxygen atom.",
        "জলের রাসায়নিক সংকেত কী?", ["H2O", "CO2", "O2", "N2"],
        "দুটি হাইড্রোজেন পরমাণু একটি অক্সিজেন পরমাণুর সঙ্গে যুক্ত।"),
    mcq("Common table salt is the chemical...", ["Sodium chloride (NaCl)", "Carbon dioxide", "Iron oxide", "Calcium carbonate"], 0,
        "Sodium and chlorine joined together.",
        "সাধারণ খাবার লবণ রাসায়নিকভাবে...", ["সোডিয়াম ক্লোরাইড (NaCl)", "কার্বন ডাই-অক্সাইড", "আয়রন অক্সাইড", "ক্যালসিয়াম কার্বোনেট"],
        "সোডিয়াম আর ক্লোরিন জুড়ে তৈরি।"),
    mcq("Rust is mainly which chemical?", ["Iron oxide", "Sodium chloride", "Water", "Carbon dioxide"], 0,
        "Iron + oxygen (with water) = iron oxide, the reddish-brown flakes.",
        "মরচে মূলত কোন রাসায়নিক?", ["আয়রন অক্সাইড", "সোডিয়াম ক্লোরাইড", "জল", "কার্বন ডাই-অক্সাইড"],
        "লোহা + অক্সিজেন (জলের সঙ্গে) = আয়রন অক্সাইড, লালচে-বাদামি ঝুরঝুরে স্তর।"),
    mcq("Chalk and limestone are mostly which chemical?", ["Calcium carbonate", "Sodium chloride", "Iron oxide", "Sugar"], 0,
        "Limestone is heated to make lime and cement.",
        "খড়ি আর চুনাপাথর মূলত কোন রাসায়নিক?", ["ক্যালসিয়াম কার্বোনেট", "সোডিয়াম ক্লোরাইড", "আয়রন অক্সাইড", "চিনি"],
        "চুনাপাথর পুড়িয়ে চুন আর সিমেন্ট বানানো হয়।"),
    mcq("What is cement mainly made from?", ["Heated limestone and clay, ground to powder", "Melted sand only", "Iron ore", "Crushed glass"], 0,
        "Limestone and clay are baked at about 1450 °C, then ground with a little gypsum.",
        "সিমেন্ট মূলত কী দিয়ে তৈরি?", ["উত্তপ্ত চুনাপাথর আর কাদামাটি, গুঁড়ো করা", "শুধু গলানো বালি", "লোহার আকরিক", "চূর্ণ কাচ"],
        "চুনাপাথর আর কাদামাটি প্রায় 1450 °C-এ পুড়িয়ে সামান্য জিপসামের সঙ্গে গুঁড়ো করা হয়।"),
)
