"""Class 5 - Physics (Junior Cadet): moments and torque, levers, pressure, density and floating,
tension and compression in structures, series and parallel circuits, light and lenses,
Earth, Moon and gravity, and measuring carefully."""
from . import mcq


def _o(r, *alts):
    return list(dict.fromkeys([r, *alts, r + 10, r * 2, r + 1]))[:4]


def moment(f, d, who_en, who_bn):
    r = f * d
    o = _o(r, f + d, f, r // 2 if r % 2 == 0 else r + 5)
    return mcq(f"{who_en} pushes with {f} N at {d} m from the pivot. What turning effect (moment) is made?",
               [f"{x} Nm" for x in o], 0,
               f"Moment = force x distance from pivot = {f} x {d} = {r} Nm.",
               f"{who_bn} আলম্ব থেকে {d} m দূরে {f} N বলে ঠেলেন। কত ঘূর্ণন-প্রভাব (ভ্রামক) তৈরি হয়?",
               [f"{x} Nm" for x in o],
               f"ভ্রামক = বল x আলম্ব থেকে দূরত্ব = {f} x {d} = {r} Nm।")


def balance(f1, d1, d2):
    f2 = f1 * d1 // d2
    o = _o(f2, f1, f1 * d2, f2 + d2)
    return mcq(f"A beam balances on a pivot. A {f1} N load sits {d1} m to the left. What force {d2} m to the right balances it?",
               [f"{x} N" for x in o], 0,
               f"Clockwise moment = anticlockwise moment: {f1} x {d1} = F x {d2}, so F = {f1 * d1} ÷ {d2} = {f2} N.",
               f"একটা বিম আলম্বে ভারসাম্যে। {f1} N বোঝা বাঁ দিকে {d1} m দূরে। ডান দিকে {d2} m দূরে কত বল ভারসাম্য আনবে?",
               [f"{x} N" for x in o],
               f"দক্ষিণাবর্ত ভ্রামক = বামাবর্ত ভ্রামক: {f1} x {d1} = F x {d2}, তাই F = {f1 * d1} ÷ {d2} = {f2} N।")


def pressure(f, a, what_en, what_bn):
    r = f // a
    o = _o(r, f * a, f + a, r // 2 if r > 2 else r + 3)
    return mcq(f"{what_en} pushes down with {f:,} N on an area of {a} m². What is the pressure?",
               [f"{x:,} Pa" for x in o], 0,
               f"Pressure = force ÷ area = {f:,} ÷ {a} = {r:,} N/m² (pascals).",
               f"{what_bn} {a} m² জায়গায় {f:,} N বলে নিচে চাপ দেয়। চাপ কত?",
               [f"{x:,} Pa" for x in o],
               f"চাপ = বল ÷ ক্ষেত্রফল = {f:,} ÷ {a} = {r:,} N/m² (প্যাসকেল)।")


def density(m, v, what_en, what_bn):
    r = m // v
    o = _o(r, m * v, m + v, r // 2 if r > 2 else r + 3)
    return mcq(f"{what_en} has a mass of {m:,} kg and a volume of {v} m³. What is its density?",
               [f"{x:,} kg/m³" for x in o], 0,
               f"Density = mass ÷ volume = {m:,} ÷ {v} = {r:,} kg/m³.",
               f"{what_bn}-এর ভর {m:,} kg আর আয়তন {v} m³। ঘনত্ব কত?",
               [f"{x:,} kg/m³" for x in o],
               f"ঘনত্ব = ভর ÷ আয়তন = {m:,} ÷ {v} = {r:,} kg/m³।")


ITEMS = (
    moment(50, 2, "A worker on a spanner", "রেঞ্চে একজন কর্মী"),
    moment(30, 3, "A child on a seesaw", "ঢেঁকি-দোলনায় এক শিশু"),
    moment(200, 4, "A crane's counterweight", "ক্রেনের পাল্টা-ওজন"),
    moment(15, 6, "A gatekeeper on a toll barrier", "টোল-বাধায় একজন রক্ষী"),
    moment(80, 5, "A rope pulling a lever", "লিভার টানা একটা দড়ি"),
    balance(100, 2, 4), balance(60, 3, 2), balance(250, 4, 5), balance(90, 2, 3), balance(400, 1, 4),
    pressure(12000, 3, "A small car", "একটা ছোট গাড়ি"),
    pressure(600, 2, "A crate", "একটা কাঠের বাক্স"),
    pressure(50000, 5, "A concrete pier", "একটা কংক্রিটের থাম"),
    pressure(800, 4, "A table", "একটা টেবিল"),
    pressure(90000, 10, "A loaded lorry", "একটা বোঝাই লরি"),
    density(7800, 1, "A cube of steel", "ইস্পাতের একটা ঘনক"),
    density(4800, 2, "A block of concrete", "কংক্রিটের একটা ব্লক"),
    density(1500, 3, "A pile of timber", "কাঠের একটা স্তূপ"),
    density(2700, 1, "A cube of aluminium", "অ্যালুমিনিয়ামের একটা ঘনক"),
    density(3000, 3, "A tank of water", "জলের একটা ট্যাংক"),
    mcq("What is a 'moment' in physics?", ["The turning effect of a force about a pivot", "A very short time only", "A type of energy", "The weight of an object"], 0,
        "Moment = force x perpendicular distance from the pivot, measured in newton-metres (Nm).",
        "পদার্থবিদ্যায় 'ভ্রামক' কী?", ["আলম্বের চারদিকে বলের ঘূর্ণন-প্রভাব", "শুধু খুব অল্প সময়", "এক রকম শক্তি", "বস্তুর ওজন"],
        "ভ্রামক = বল x আলম্ব থেকে লম্ব দূরত্ব, মাপা হয় নিউটন-মিটারে (Nm)।"),
    mcq("Why is a long spanner better for undoing a tight bolt?", ["The longer handle gives a bigger moment for the same push", "Long spanners are heavier", "Bolts like long tools", "It is not better"], 0,
        "More distance from the pivot = more turning effect.",
        "শক্ত বল্টু খুলতে লম্বা রেঞ্চ ভালো কেন?", ["লম্বা হাতল একই ঠেলায় বড় ভ্রামক দেয়", "লম্বা রেঞ্চ ভারী", "বল্টু লম্বা যন্ত্র পছন্দ করে", "ভালো নয়"],
        "আলম্ব থেকে বেশি দূরত্ব = বেশি ঘূর্ণন-প্রভাব।"),
    mcq("Why are door handles placed far from the hinges?", ["You need less force to turn the door", "It looks nicer", "Hinges are hot", "To make doors heavier"], 0,
        "Try pushing a door near its hinge - it is much harder!",
        "দরজার হাতল কব্জা থেকে দূরে রাখা হয় কেন?", ["দরজা ঘোরাতে কম বল লাগে", "সুন্দর দেখায়", "কব্জা গরম", "দরজা ভারী করতে"],
        "কব্জার কাছে দরজা ঠেলে দেখো - অনেক কঠিন!"),
    mcq("What is the 'principle of moments'?", ["For balance, clockwise moments equal anticlockwise moments", "Heavier side always wins", "Moments only work on Sundays", "Forces never balance"], 0,
        "Bridge engineers use it to check every joint stays in equilibrium.",
        "'ভ্রামকের নীতি' কী?", ["ভারসাম্যে দক্ষিণাবর্ত ভ্রামক বামাবর্ত ভ্রামকের সমান", "ভারী দিক সবসময় জেতে", "ভ্রামক শুধু রবিবার কাজ করে", "বল কখনো ভারসাম্যে আসে না"],
        "সেতুর প্রকৌশলীরা প্রতিটি জোড় সাম্যাবস্থায় আছে কিনা যাচাইয়ে এটা ব্যবহার করেন।"),
    mcq("Why does a tower crane have a heavy counterweight on its short arm?", ["To balance the moment of the load on the long arm", "To look strong", "To store fuel", "To slow the crane"], 0,
        "Without it, the load would tip the crane over.",
        "টাওয়ার-ক্রেনের ছোট বাহুতে ভারী পাল্টা-ওজন থাকে কেন?", ["লম্বা বাহুর বোঝার ভ্রামক সামলাতে", "শক্ত দেখাতে", "জ্বালানি রাখতে", "ক্রেন ধীর করতে"],
        "এটা না থাকলে বোঝা ক্রেনকে উল্টে দিত।"),
    mcq("Why is it dangerous for a crane to lift a load further out than its chart allows?", ["The moment becomes too big and the crane can topple", "Loads get lighter far away", "Cranes stretch", "It is never dangerous"], 0,
        "Cranes have load charts: the further out, the less they may lift.",
        "চার্টে অনুমোদিত দূরত্বের বেশি দূরে বোঝা তোলা ক্রেনের জন্য বিপজ্জনক কেন?", ["ভ্রামক খুব বড় হয়ে ক্রেন উল্টে যেতে পারে", "দূরে বোঝা হালকা হয়", "ক্রেন লম্বা হয়", "কখনো বিপজ্জনক নয়"],
        "ক্রেনের বোঝা-চার্ট থাকে: যত দূরে, তত কম তোলা যায়।"),
    mcq("A cantilever is a beam fixed at one end only. Where is the bending moment biggest?", ["At the fixed end", "At the free tip", "In the exact middle", "It is the same everywhere"], 0,
        "The fixed end resists the turning effect of the whole load - so cantilevers are deepest there.",
        "ক্যান্টিলিভার শুধু এক প্রান্তে আটকানো বিম। নমন-ভ্রামক কোথায় সবচেয়ে বেশি?", ["আটকানো প্রান্তে", "মুক্ত ডগায়", "ঠিক মাঝখানে", "সব জায়গায় সমান"],
        "আটকানো প্রান্ত পুরো বোঝার ঘূর্ণন-প্রভাব সামলায় - তাই ক্যান্টিলিভার সেখানে সবচেয়ে গভীর।"),
    mcq("What is 'tension'?", ["A pulling force that stretches a member", "A pushing force that squashes it", "A twisting force", "No force"], 0,
        "Ropes, cables and the bottom of a loaded beam are in tension.",
        "'টান' কী?", ["যে টানা বল একটা অংশকে লম্বা করে", "যে ঠেলা বল তাকে চাপে", "মোচড়ানো বল", "কোনো বল নয়"],
        "দড়ি, তার আর বোঝাই বিমের নিচের দিক টানে থাকে।"),
    mcq("What is 'compression'?", ["A pushing force that squashes a member", "A pulling force", "A magnetic force", "An electric force"], 0,
        "Pillars, arches and the top of a loaded beam are in compression.",
        "'সংনমন' কী?", ["যে ঠেলা বল একটা অংশকে চাপে", "টানা বল", "চুম্বকীয় বল", "বৈদ্যুতিক বল"],
        "থাম, খিলান আর বোঝাই বিমের উপরের দিক সংনমনে থাকে।"),
    mcq("A plank across a stream bends down when you stand on it. Which surface is squashed?", ["The top surface", "The bottom surface", "Neither", "Both stretch"], 0,
        "Top in compression, bottom in tension - the middle layer is neither (the neutral axis).",
        "খালের উপর তক্তায় দাঁড়ালে তা নিচে বাঁকে। কোন তল চাপা পড়ে?", ["উপরের তল", "নিচের তল", "কোনোটাই না", "দুটোই লম্বা হয়"],
        "উপরে সংনমন, নিচে টান - মাঝের স্তরে কোনোটাই না (নিরপেক্ষ অক্ষ)।"),
    mcq("Why do suspension bridges hang the deck from cables?", ["Cables are very strong in tension and light", "Cables are strong in compression", "Cables float", "Cables are cheap decoration"], 0,
        "Steel cable is thin but can carry enormous pulls.",
        "ঝুলন্ত সেতু পাটাতন তার থেকে ঝোলায় কেন?", ["তার টানে খুব শক্ত আর হালকা", "তার সংনমনে শক্ত", "তার ভাসে", "তার সস্তা সাজ"],
        "ইস্পাতের তার সরু, কিন্তু বিশাল টান বইতে পারে।"),
    mcq("Why are arches usually made of stone or concrete?", ["Arches carry load mainly in compression, where these are strong", "Stone is light", "Stone is strong in tension", "Concrete is stretchy"], 0,
        "Roman stone arches have stood for 2,000 years.",
        "খিলান সাধারণত পাথর বা কংক্রিটের হয় কেন?", ["খিলান মূলত সংনমনে বোঝা বয়, যেখানে এরা শক্ত", "পাথর হালকা", "পাথর টানে শক্ত", "কংক্রিট স্থিতিস্থাপক"],
        "রোমের পাথরের খিলান 2,000 বছর ধরে দাঁড়িয়ে।"),
    mcq("What happens to a long thin strut pushed hard from both ends?", ["It can suddenly bow sideways (buckle)", "It gets stronger", "It stretches", "Nothing ever"], 0,
        "Slender members in compression buckle - one way bridges fail in BridgeWorks!",
        "লম্বা সরু ঠেকনা দুই প্রান্ত থেকে জোরে ঠেললে কী হয়?", ["হঠাৎ পাশে বেঁকে যেতে পারে (বাকলিং)", "আরও শক্ত হয়", "লম্বা হয়", "কখনো কিছু হয় না"],
        "সংনমনে সরু অংশ বেঁকে যায় - BridgeWorks-এ সেতু ভাঙার একটা উপায়!"),
    mcq("How can you stop a strut from buckling?", ["Make it shorter or thicker, or brace it in the middle", "Paint it", "Make it longer and thinner", "Heat it"], 0,
        "Shorter, fatter members resist buckling far better.",
        "ঠেকনার বাকলিং আটকাবে কীভাবে?", ["ছোট বা মোটা করো, বা মাঝখানে ঠেকা দাও", "রং করো", "লম্বা আর সরু করো", "গরম করো"],
        "ছোট, মোটা অংশ বাকলিং অনেক ভালো ঠেকায়।"),
    mcq("Why are triangles used in trusses instead of squares?", ["A triangle cannot change shape without changing a side length", "Squares are illegal", "Triangles are lighter paint", "Squares are stronger"], 0,
        "A square of pin-jointed bars folds into a diamond; a triangle stays rigid.",
        "ট্রাসে বর্গের বদলে ত্রিভুজ ব্যবহার হয় কেন?", ["বাহুর দৈর্ঘ্য না বদলে ত্রিভুজের আকার বদলায় না", "বর্গ বেআইনি", "ত্রিভুজে রং হালকা", "বর্গ বেশি শক্ত"],
        "পিন-জোড়া দণ্ডের বর্গ ভাঁজ হয়ে রম্বস হয়; ত্রিভুজ অনড় থাকে।"),
    mcq("What is 'pressure'?", ["Force spread over an area", "Weight only", "Speed per second", "Mass per volume"], 0,
        "Pressure = force ÷ area, measured in pascals (N/m²).",
        "'চাপ' কী?", ["ক্ষেত্রফলে ছড়ানো বল", "শুধু ওজন", "সেকেন্ডপ্রতি গতি", "আয়তনপ্রতি ভর"],
        "চাপ = বল ÷ ক্ষেত্রফল, মাপা হয় প্যাসকেলে (N/m²)।"),
    mcq("Why do bridge pillars stand on wide 'footings'?", ["A bigger area lowers the pressure on the soil", "To look grand", "Wide is lighter", "To catch fish"], 0,
        "Soft soil sinks under high pressure; spreading the load stops settling.",
        "সেতুর থাম চওড়া 'পাদভিত্তি'-র উপর দাঁড়ায় কেন?", ["বড় ক্ষেত্রফল মাটির উপর চাপ কমায়", "জমকালো দেখাতে", "চওড়া হালকা", "মাছ ধরতে"],
        "উচ্চ চাপে নরম মাটি বসে যায়; বোঝা ছড়ালে বসা থামে।"),
    mcq("Why does a sharp knife cut better than a blunt one?", ["Its tiny edge area makes huge pressure", "Sharp knives are heavier", "Blunt knives are magnetic", "It does not"], 0,
        "Same force, smaller area, much bigger pressure.",
        "ধারালো ছুরি ভোঁতার চেয়ে ভালো কাটে কেন?", ["ছোট্ট ধারের ক্ষেত্রফল বিশাল চাপ তৈরি করে", "ধারালো ছুরি ভারী", "ভোঁতা ছুরি চুম্বকীয়", "কাটে না"],
        "একই বল, ছোট ক্ষেত্রফল, অনেক বেশি চাপ।"),
    mcq("Why do heavy cranes and tanks use wide tracks instead of wheels on soft ground?", ["Tracks spread the weight and stop sinking", "Tracks are faster", "Tracks are lighter", "Wheels are illegal"], 0,
        "Lower pressure on the ground = less sinking into mud.",
        "নরম মাটিতে ভারী ক্রেন আর ট্যাংক চাকার বদলে চওড়া চেন-চাকা ব্যবহার করে কেন?", ["চেন-চাকা ওজন ছড়িয়ে ডোবা আটকায়", "চেন-চাকা দ্রুত", "চেন-চাকা হালকা", "চাকা বেআইনি"],
        "মাটিতে কম চাপ = কাদায় কম ডোবা।"),
    mcq("How does water pressure change as you go deeper in a river?", ["It increases", "It decreases", "It stays the same", "It becomes zero"], 0,
        "More water above pushes down harder - so dams are thicker at the bottom.",
        "নদীর গভীরে গেলে জলের চাপ কীভাবে বদলায়?", ["বাড়ে", "কমে", "একই থাকে", "শূন্য হয়"],
        "উপরে বেশি জল আরও জোরে নিচে চাপে - তাই বাঁধ নিচে বেশি মোটা।"),
    mcq("Why are dams much thicker at the bottom than at the top?", ["Water pressure is greatest at the bottom", "To save concrete at the top only", "Fish live at the bottom", "For decoration"], 0,
        "The deeper the water, the greater the push on the wall.",
        "বাঁধ উপরের চেয়ে নিচে অনেক মোটা কেন?", ["জলের চাপ নিচে সবচেয়ে বেশি", "শুধু উপরে কংক্রিট বাঁচাতে", "মাছ নিচে থাকে", "সাজসজ্জার জন্য"],
        "জল যত গভীর, দেওয়ালে ঠেলা তত বেশি।"),
    mcq("What is 'atmospheric pressure'?", ["The push of the air all around us", "Pressure under water only", "A storm", "Pressure inside tyres only"], 0,
        "Air presses on everything with about 100,000 Pa at sea level.",
        "'বায়ুমণ্ডলীয় চাপ' কী?", ["চারপাশের বাতাসের ঠেলা", "শুধু জলের নিচের চাপ", "ঝড়", "শুধু টায়ারের ভেতরের চাপ"],
        "সমুদ্রতলে বাতাস সব কিছুর উপর প্রায় 1,00,000 Pa চাপ দেয়।"),
    mcq("What is 'density'?", ["How much mass is packed into each unit of volume", "How tall something is", "How fast it moves", "Its colour"], 0,
        "Density = mass ÷ volume. Steel is about 7,800 kg/m³; water is 1,000 kg/m³.",
        "'ঘনত্ব' কী?", ["প্রতি একক আয়তনে কতটা ভর ঠাসা", "কোনো কিছু কত লম্বা", "কত দ্রুত চলে", "তার রং"],
        "ঘনত্ব = ভর ÷ আয়তন। ইস্পাত প্রায় 7,800 kg/m³; জল 1,000 kg/m³।"),
    mcq("An object will float in water if its overall density is...", ["Less than water's", "More than water's", "Exactly double water's", "Any value"], 0,
        "Wood (about 600 kg/m³) floats; steel (7,800) sinks unless shaped into a hollow hull.",
        "কোনো বস্তু জলে ভাসবে যদি তার সামগ্রিক ঘনত্ব...", ["জলের চেয়ে কম হয়", "জলের চেয়ে বেশি হয়", "ঠিক জলের দ্বিগুণ হয়", "যেকোনো মান"],
        "কাঠ (প্রায় 600 kg/m³) ভাসে; ইস্পাত (7,800) ডোবে, যদি না ফাঁপা খোলের আকার দেওয়া হয়।"),
    mcq("Why do engineers want light but strong materials for long bridges?", ["A long bridge must carry its own weight before any traffic", "Light materials are always cheapest", "Heavy bridges float away", "Strength does not matter"], 0,
        "For very long spans, most of the load is the bridge itself.",
        "লম্বা সেতুর জন্য প্রকৌশলীরা হালকা কিন্তু শক্ত উপাদান চান কেন?", ["যানবাহনের আগে লম্বা সেতুকে নিজের ওজন বইতে হয়", "হালকা উপাদান সবসময় সস্তা", "ভারী সেতু ভেসে যায়", "শক্তি জরুরি নয়"],
        "খুব লম্বা স্প্যানে বেশিরভাগ বোঝাই সেতুর নিজের।"),
    mcq("What is the 'dead load' of a bridge?", ["The weight of the bridge itself", "The weight of traffic", "Wind force", "Earthquake force"], 0,
        "Dead load is permanent; live load (traffic) comes and goes.",
        "সেতুর 'স্থির বোঝা' (ডেড লোড) কী?", ["সেতুর নিজের ওজন", "যানবাহনের ওজন", "বাতাসের বল", "ভূমিকম্পের বল"],
        "স্থির বোঝা স্থায়ী; চলমান বোঝা (যানবাহন) আসে আর যায়।"),
    mcq("What is the 'live load' on a bridge?", ["Moving loads like vehicles and people", "The bridge's own weight", "The paint", "The foundations"], 0,
        "Engineers design for the heaviest traffic expected, plus a safety margin.",
        "সেতুর 'চলমান বোঝা' (লাইভ লোড) কী?", ["যানবাহন আর মানুষের মতো চলমান বোঝা", "সেতুর নিজের ওজন", "রং", "ভিত"],
        "প্রকৌশলীরা প্রত্যাশিত সবচেয়ে ভারী যানবাহন আর নিরাপত্তা-মার্জিন ধরে নকশা করেন।"),
    mcq("What is a 'safety factor' in design?", ["Making a part stronger than the biggest expected load, for extra safety", "A safety poster", "A helmet", "Making things weaker"], 0,
        "A safety factor of 2 means the part could hold twice the design load.",
        "নকশায় 'নিরাপত্তা-গুণক' কী?", ["বাড়তি নিরাপত্তার জন্য অংশটাকে প্রত্যাশিত সর্বোচ্চ বোঝার চেয়ে শক্ত করা", "নিরাপত্তার পোস্টার", "হেলমেট", "জিনিস দুর্বল করা"],
        "নিরাপত্তা-গুণক 2 মানে অংশটা নকশার বোঝার দ্বিগুণ ধরতে পারত।"),
    mcq("A cable must carry 50 kN. With a safety factor of 2, what strength should it have?", ["100 kN", "52 kN", "25 kN", "50 kN"], 0,
        "50 x 2 = 100 kN.",
        "একটা তারকে 50 kN বইতে হবে। নিরাপত্তা-গুণক 2 হলে তার শক্তি কত হওয়া উচিত?", ["100 kN", "52 kN", "25 kN", "50 kN"],
        "50 x 2 = 100 kN।"),
    mcq("In a series circuit with two bulbs, what happens if one bulb breaks?", ["Both go out - the single loop is broken", "The other gets brighter", "Nothing", "Both get brighter"], 0,
        "Series = one path. Old fairy lights worked like this.",
        "দুটি বাল্বের শ্রেণি-বর্তনীতে একটা বাল্ব ভাঙলে কী হয়?", ["দুটোই নেভে - একমাত্র পথ ভেঙে যায়", "অন্যটা উজ্জ্বল হয়", "কিছুই না", "দুটোই উজ্জ্বল হয়"],
        "শ্রেণি = একটা পথ। পুরোনো আলোকসজ্জা এভাবে চলত।"),
    mcq("In a parallel circuit, what happens if one bulb breaks?", ["The others stay lit - each has its own path", "All go out", "The battery explodes", "The wires melt"], 0,
        "Homes and bridge lighting are wired in parallel.",
        "সমান্তরাল বর্তনীতে একটা বাল্ব ভাঙলে কী হয়?", ["বাকিগুলো জ্বলে থাকে - প্রত্যেকের নিজের পথ", "সব নেভে", "ব্যাটারি ফাটে", "তার গলে"],
        "বাড়ি আর সেতুর আলো সমান্তরালে জোড়া থাকে।"),
    mcq("Why is bridge lighting wired in parallel?", ["One failed lamp does not darken the whole bridge", "It uses no electricity", "Series is illegal", "It makes lamps cheaper"], 0,
        "Safety-critical lighting must keep working.",
        "সেতুর আলো সমান্তরালে জোড়া হয় কেন?", ["একটা বাতি নষ্ট হলে পুরো সেতু অন্ধকার হয় না", "বিদ্যুৎ লাগে না", "শ্রেণি বেআইনি", "বাতি সস্তা হয়"],
        "নিরাপত্তা-জরুরি আলোকে চালু থাকতেই হবে।"),
    mcq("What does a fuse do?", ["Melts and breaks the circuit if too much current flows", "Stores electricity", "Makes light", "Speeds up current"], 0,
        "Fuses and circuit breakers prevent fires from overloaded wires.",
        "ফিউজ কী করে?", ["বেশি বিদ্যুৎ চললে গলে বর্তনী ভেঙে দেয়", "বিদ্যুৎ জমায়", "আলো তৈরি করে", "বিদ্যুৎ দ্রুত করে"],
        "ফিউজ আর সার্কিট-ব্রেকার অতিরিক্ত বোঝার তার থেকে আগুন ঠেকায়।"),
    mcq("What is the unit of electrical voltage?", ["Volt (V)", "Newton (N)", "Metre (m)", "Kilogram (kg)"], 0,
        "A torch battery is 1.5 V; Indian home sockets are about 230 V.",
        "বৈদ্যুতিক ভোল্টেজের একক কী?", ["ভোল্ট (V)", "নিউটন (N)", "মিটার (m)", "কিলোগ্রাম (kg)"],
        "টর্চের ব্যাটারি 1.5 V; ভারতের বাড়ির সকেট প্রায় 230 V।"),
    mcq("What is electric current measured in?", ["Amperes (amps, A)", "Volts", "Watts only", "Litres"], 0,
        "Current is the flow of electric charge.",
        "বিদ্যুৎ-প্রবাহ কীসে মাপা হয়?", ["অ্যাম্পিয়ার (A)", "ভোল্ট", "শুধু ওয়াট", "লিটার"],
        "বিদ্যুৎ-প্রবাহ হলো বৈদ্যুতিক আধানের প্রবাহ।"),
    mcq("Three 1.5 V cells are joined in series. What total voltage do they give?", ["4.5 V", "1.5 V", "3 V", "0.5 V"], 0,
        "In series the voltages add: 1.5 + 1.5 + 1.5 = 4.5 V.",
        "তিনটি 1.5 V কোষ শ্রেণিতে জোড়া হলো। মোট কত ভোল্টেজ দেয়?", ["4.5 V", "1.5 V", "3 V", "0.5 V"],
        "শ্রেণিতে ভোল্টেজ যোগ হয়: 1.5 + 1.5 + 1.5 = 4.5 V।"),
    mcq("What is 'resistance' in a circuit?", ["How much a component opposes the flow of current", "A battery", "A switch only", "The speed of light"], 0,
        "Thin, long wires have more resistance and get warmer.",
        "বর্তনীতে 'রোধ' কী?", ["একটা উপাদান বিদ্যুৎ-প্রবাহে কতটা বাধা দেয়", "ব্যাটারি", "শুধু সুইচ", "আলোর গতি"],
        "সরু, লম্বা তারে রোধ বেশি আর বেশি গরম হয়।"),
    mcq("Why does an LED lamp save money compared with an old bulb?", ["It turns more electricity into light and less into heat", "It uses no electricity", "It is always free", "It is darker"], 0,
        "Many towns replace bridge lights with LEDs to cut bills.",
        "পুরোনো বাল্বের তুলনায় এলইডি বাতি টাকা বাঁচায় কেন?", ["বেশি বিদ্যুৎকে আলোয় আর কমকে তাপে বদলায়", "বিদ্যুৎ লাগে না", "সবসময় বিনামূল্যে", "বেশি অন্ধকার"],
        "অনেক শহর বিল কমাতে সেতুর আলো এলইডি দিয়ে বদলায়।"),
    mcq("What does a convex (converging) lens do to light?", ["Bends rays together to a focus", "Spreads rays apart", "Stops all light", "Turns light into sound"], 0,
        "Magnifying glasses and camera lenses are convex.",
        "উত্তল (অভিসারী) লেন্স আলোর সঙ্গে কী করে?", ["রশ্মিগুলোকে একটা ফোকাসে মেলায়", "রশ্মিগুলো ছড়িয়ে দেয়", "সব আলো আটকায়", "আলোকে শব্দে বদলায়"],
        "আতশকাচ আর ক্যামেরার লেন্স উত্তল।"),
    mcq("What does a concave (diverging) lens do to light?", ["Spreads rays apart", "Brings rays to a focus", "Reflects all light", "Makes light heavier"], 0,
        "Glasses for short-sighted people use concave lenses.",
        "অবতল (অপসারী) লেন্স আলোর সঙ্গে কী করে?", ["রশ্মিগুলো ছড়িয়ে দেয়", "রশ্মিগুলো ফোকাসে আনে", "সব আলো প্রতিফলিত করে", "আলো ভারী করে"],
        "স্বল্পদৃষ্টির চশমায় অবতল লেন্স থাকে।"),
    mcq("How do surveyors' levelling instruments help build bridges?", ["Their telescopes measure heights accurately so the deck is level", "They measure temperature", "They weigh steel", "They count cars"], 0,
        "Precise levels make sure spans meet exactly in the middle.",
        "জরিপকারীদের লেভেলিং-যন্ত্র সেতু বানাতে কীভাবে সাহায্য করে?", ["দূরবিন দিয়ে নিখুঁতভাবে উচ্চতা মাপে যাতে পাটাতন সমতল হয়", "তাপমাত্রা মাপে", "ইস্পাত ওজন করে", "গাড়ি গোনে"],
        "নিখুঁত মাপে স্প্যানগুলো ঠিক মাঝখানে মেলে।"),
    mcq("Why does the Moon cause tides in rivers near the sea?", ["Its gravity pulls on the oceans", "It heats the water", "It blows wind", "It has magnets"], 0,
        "Tidal rivers rise and fall twice a day - bridge clearances must allow for high tide.",
        "চাঁদ সমুদ্রের কাছের নদীতে জোয়ার-ভাটা আনে কেন?", ["তার মাধ্যাকর্ষণ সমুদ্রকে টানে", "জল গরম করে", "বাতাস বয়", "তার চুম্বক আছে"],
        "জোয়ারের নদী দিনে দুবার ওঠে-নামে - সেতুর নিচের ফাঁকে জোয়ারের হিসাব রাখতে হয়।"),
    mcq("Why must a bridge over a tidal river be high enough at high tide?", ["So boats can still pass underneath", "To catch the Moon", "High bridges are cheaper", "Tides do not matter"], 0,
        "Navigation clearance is measured at the highest expected water level.",
        "জোয়ারের নদীর উপর সেতুকে জোয়ারের সময়েও যথেষ্ট উঁচু হতে হবে কেন?", ["যাতে নৌকা তখনো নিচ দিয়ে যেতে পারে", "চাঁদ ধরতে", "উঁচু সেতু সস্তা", "জোয়ার জরুরি নয়"],
        "নৌচলাচলের ফাঁক মাপা হয় সর্বোচ্চ প্রত্যাশিত জলস্তরে।"),
    mcq("How long does Earth take to spin once on its axis?", ["About 24 hours", "About 365 days", "About 1 hour", "About 30 days"], 0,
        "One spin gives day and night.",
        "পৃথিবী অক্ষের উপর একবার ঘুরতে কত সময় নেয়?", ["প্রায় 24 ঘণ্টা", "প্রায় 365 দিন", "প্রায় 1 ঘণ্টা", "প্রায় 30 দিন"],
        "একটা আবর্তনে দিন আর রাত হয়।"),
    mcq("How long does Earth take to orbit the Sun?", ["About 365 days", "About 24 hours", "About 28 days", "About 10 years"], 0,
        "That is one year.",
        "পৃথিবী সূর্যের চারদিকে একবার ঘুরতে কত সময় নেয়?", ["প্রায় 365 দিন", "প্রায় 24 ঘণ্টা", "প্রায় 28 দিন", "প্রায় 10 বছর"],
        "সেটাই এক বছর।"),
    mcq("Why would a bridge weigh less on the Moon?", ["The Moon's gravity is about 1/6 of Earth's", "The Moon has no air", "Bridges shrink in space", "It would weigh more"], 0,
        "Its mass is the same, but the pull of gravity is weaker.",
        "চাঁদে একটা সেতুর ওজন কম হবে কেন?", ["চাঁদের মাধ্যাকর্ষণ পৃথিবীর প্রায় 1/6", "চাঁদে বাতাস নেই", "মহাকাশে সেতু ছোট হয়", "ওজন বাড়বে"],
        "ভর একই, কিন্তু মাধ্যাকর্ষণের টান দুর্বল।"),
    mcq("A beam's mass is 600 kg. About what is its weight on Earth (g ≈ 10 N/kg)?", ["6,000 N", "600 N", "60 N", "60,000 N"], 0,
        "Weight = mass x g = 600 x 10 = 6,000 N.",
        "একটা বিমের ভর 600 kg। পৃথিবীতে (g ≈ 10 N/kg) তার ওজন মোটামুটি কত?", ["6,000 N", "600 N", "60 N", "60,000 N"],
        "ওজন = ভর x g = 600 x 10 = 6,000 N।"),
    mcq("What is 'friction' doing when a truck brakes on a bridge?", ["Gripping between tyre and road to slow the truck", "Pushing the truck faster", "Lifting the truck", "Nothing"], 0,
        "Braking also pushes forward on the deck - engineers design for braking forces too.",
        "সেতুর উপর ট্রাক ব্রেক কষলে ঘর্ষণ কী করে?", ["টায়ার আর রাস্তার মধ্যে আঁকড়ে ট্রাক ধীর করে", "ট্রাককে দ্রুত ঠেলে", "ট্রাক তোলে", "কিছুই না"],
        "ব্রেক কষলে পাটাতনে সামনের দিকেও ঠেলা লাগে - প্রকৌশলীরা ব্রেকের বলও হিসাব করেন।"),
    mcq("What is 'speed' measured in, in science?", ["Metres per second (m/s)", "Kilograms", "Newtons", "Pascals"], 0,
        "1 m/s is a slow walk; 30 m/s is about 108 km/h.",
        "বিজ্ঞানে 'গতি' কীসে মাপা হয়?", ["মিটার প্রতি সেকেন্ড (m/s)", "কিলোগ্রাম", "নিউটন", "প্যাসকেল"],
        "1 m/s ধীর হাঁটা; 30 m/s প্রায় 108 km/h।"),
    mcq("A cyclist covers 100 m in 20 s. What is their speed?", ["5 m/s", "2,000 m/s", "120 m/s", "0.2 m/s"], 0,
        "100 ÷ 20 = 5 m/s.",
        "একজন সাইকেল-আরোহী 20 s-এ 100 m যান। তাঁর গতি কত?", ["5 m/s", "2,000 m/s", "120 m/s", "0.2 m/s"],
        "100 ÷ 20 = 5 m/s।"),
    mcq("A train speeds up from 10 m/s to 30 m/s. What is this change called?", ["Acceleration", "Friction", "Pressure", "Density"], 0,
        "Acceleration is how quickly speed changes.",
        "একটা ট্রেন 10 m/s থেকে 30 m/s-এ গতি বাড়াল। এই পরিবর্তনকে কী বলে?", ["ত্বরণ", "ঘর্ষণ", "চাপ", "ঘনত্ব"],
        "ত্বরণ হলো গতি কত দ্রুত বদলায়।"),
    mcq("What is the 'centre of gravity' of an object?", ["The point where its weight seems to act", "The heaviest corner", "The top", "Its colour centre"], 0,
        "Low centres of gravity make vehicles and cranes more stable.",
        "বস্তুর 'ভারকেন্দ্র' কী?", ["যে বিন্দুতে তার ওজন কাজ করছে বলে মনে হয়", "সবচেয়ে ভারী কোণ", "উপরের দিক", "রঙের কেন্দ্র"],
        "নিচু ভারকেন্দ্র গাড়ি আর ক্রেনকে বেশি স্থির করে।"),
    mcq("Why are double-decker buses tested by tilting them?", ["To make sure their centre of gravity is low enough not to tip", "To clean them", "To test the paint", "For fun"], 0,
        "If the centre of gravity moves outside the wheels, the bus topples.",
        "দোতলা বাস কাত করে পরীক্ষা করা হয় কেন?", ["ভারকেন্দ্র যথেষ্ট নিচু কিনা, যাতে উল্টে না যায়", "পরিষ্কার করতে", "রং পরীক্ষা করতে", "মজার জন্য"],
        "ভারকেন্দ্র চাকার বাইরে গেলে বাস উল্টে যায়।"),
    mcq("Why do workers carrying beams on a narrow walkway keep loads low and central?", ["It keeps their centre of gravity stable so they do not fall", "Beams prefer the middle", "It is faster", "No reason"], 0,
        "Balance is safety at height.",
        "সরু পথে বিম বয়ে নেওয়া কর্মীরা বোঝা নিচু আর মাঝখানে রাখেন কেন?", ["ভারকেন্দ্র স্থির থাকে যাতে পড়ে না যান", "বিম মাঝখান পছন্দ করে", "দ্রুত হয়", "কোনো কারণ নেই"],
        "উঁচুতে ভারসাম্যই নিরাপত্তা।"),
    mcq("What is 'elastic' behaviour?", ["A material returns to its shape after the load is removed", "It snaps instantly", "It melts", "It stays bent forever"], 0,
        "Bridges are designed to stay elastic under normal traffic.",
        "'স্থিতিস্থাপক' আচরণ কী?", ["বোঝা সরালে উপাদান আগের আকারে ফেরে", "সঙ্গে সঙ্গে ভাঙে", "গলে যায়", "চিরকাল বাঁকা থাকে"],
        "স্বাভাবিক যানবাহনে সেতু স্থিতিস্থাপক থাকার মতো করে নকশা হয়।"),
    mcq("What is 'plastic' (permanent) deformation in metals?", ["Bending that stays after the load is removed", "Turning into plastic", "Getting stronger by magic", "Rusting"], 0,
        "Beyond the elastic limit, steel stays bent - a warning before failure.",
        "ধাতুতে 'প্লাস্টিক' (স্থায়ী) বিকৃতি কী?", ["বোঝা সরানোর পরেও যে বাঁক থেকে যায়", "প্লাস্টিকে বদলে যাওয়া", "জাদুতে শক্ত হওয়া", "মরচে ধরা"],
        "স্থিতিস্থাপক সীমার পরে ইস্পাত বাঁকা থাকে - ভাঙার আগে একটা সতর্কসংকেত।"),
    mcq("Why is steel's ability to bend before breaking (ductility) good for bridges?", ["It gives visible warning instead of snapping suddenly", "It makes bridges bouncy for fun", "It is not good", "It makes steel lighter"], 0,
        "Brittle materials like glass snap without warning.",
        "ভাঙার আগে বাঁকার ক্ষমতা (নমনীয়তা) সেতুর জন্য ভালো কেন?", ["হঠাৎ ছেঁড়ার বদলে দৃশ্যমান সতর্কতা দেয়", "মজায় সেতু লাফায়", "ভালো নয়", "ইস্পাত হালকা করে"],
        "কাচের মতো ভঙ্গুর উপাদান কোনো সতর্কতা ছাড়াই ভাঙে।"),
    mcq("What is 'vibration' in a footbridge?", ["Small, repeated back-and-forth movements", "The bridge melting", "Paint peeling", "A traffic jam"], 0,
        "Engineers add dampers so walking crowds do not make bridges wobble.",
        "হাঁটার সেতুতে 'কম্পন' কী?", ["ছোট, বারবার সামনে-পেছনে নড়াচড়া", "সেতু গলা", "রং ওঠা", "যানজট"],
        "হাঁটা ভিড় যাতে সেতু না দোলায়, তাই প্রকৌশলীরা ড্যাম্পার লাগান।"),
    mcq("What is 'resonance'?", ["Small pushes at just the right rhythm building up big swings", "A loud echo only", "Rust on cables", "A kind of paint"], 0,
        "Like pushing a swing at the right moment - bridges must avoid matching rhythms of wind or feet.",
        "'অনুনাদ' কী?", ["ঠিক ছন্দে ছোট ঠেলায় বড় দোলা জমে ওঠা", "শুধু জোরালো প্রতিধ্বনি", "তারে মরচে", "এক রকম রং"],
        "ঠিক মুহূর্তে দোলনা ঠেলার মতো - সেতুকে বাতাস বা পায়ের ছন্দের সঙ্গে মিলে যাওয়া এড়াতে হয়।"),
    mcq("Which instrument measures very small changes in a bridge's length under load?", ["A strain gauge", "A thermometer", "A compass", "A barometer"], 0,
        "Strain gauges glued to steel tell engineers how hard each member is working.",
        "বোঝার অধীনে সেতুর দৈর্ঘ্যের খুব ছোট পরিবর্তন কোন যন্ত্র মাপে?", ["স্ট্রেন গেজ", "থার্মোমিটার", "কম্পাস", "ব্যারোমিটার"],
        "ইস্পাতে আটকানো স্ট্রেন গেজ প্রকৌশলীদের জানায় প্রতিটি অংশ কতটা চাপে কাজ করছে।"),
    mcq("What is 'precision' when measuring?", ["How close repeated measurements are to each other", "Measuring quickly", "Measuring with a guess", "Measuring once only"], 0,
        "Precise, accurate measurements make parts fit on site.",
        "মাপার সময় 'সূক্ষ্মতা' কী?", ["বারবার মাপলে মানগুলো পরস্পরের কতটা কাছে", "দ্রুত মাপা", "আন্দাজে মাপা", "একবারই মাপা"],
        "সূক্ষ্ম, নির্ভুল মাপে অংশগুলো জায়গায় ঠিক বসে।"),
    mcq("A steel beam made in a factory arrives 5 cm too short. Why is this serious?", ["It may not reach its supports, so it cannot be fixed safely", "5 cm never matters", "Steel grows on site", "It can be stretched by hand"], 0,
        "Measure twice, cut once!",
        "কারখানায় তৈরি একটা ইস্পাতের বিম 5 cm ছোট হয়ে এল। এটা গুরুতর কেন?", ["আলম্ব পর্যন্ত না পৌঁছাতে পারে, তাই নিরাপদে বসানো যায় না", "5 cm কখনো জরুরি নয়", "জায়গায় ইস্পাত বাড়ে", "হাতে টেনে লম্বা করা যায়"],
        "দুবার মাপো, একবার কাটো!"),
    mcq("Why does a hot-air balloon rise?", ["Hot air inside is less dense than the cooler air outside", "Balloons are magnetic", "The basket is light", "Wind pushes it up only"], 0,
        "Less dense fluids rise above denser ones.",
        "গরম বাতাসের বেলুন ওঠে কেন?", ["ভেতরের গরম বাতাস বাইরের ঠান্ডা বাতাসের চেয়ে কম ঘন", "বেলুন চুম্বকীয়", "ঝুড়ি হালকা", "শুধু বাতাস উপরে ঠেলে"],
        "কম ঘন তরল বা গ্যাস বেশি ঘনের উপরে ওঠে।"),
    mcq("Why does a hydraulic jack let one person lift a car?", ["Liquid passes pressure from a small piston to a big one, multiplying force", "Oil is magic", "Cars become light", "The jack uses electricity only"], 0,
        "Hydraulic jacks are used to lift whole bridge decks to replace bearings!",
        "হাইড্রলিক জ্যাক দিয়ে একজন মানুষ গাড়ি তুলতে পারেন কেন?", ["তরল ছোট পিস্টন থেকে বড় পিস্টনে চাপ পাঠিয়ে বল বহুগুণ করে", "তেল জাদুর", "গাড়ি হালকা হয়", "জ্যাক শুধু বিদ্যুতে চলে"],
        "বিয়ারিং বদলাতে হাইড্রলিক জ্যাক দিয়ে পুরো সেতুর পাটাতন তোলা হয়!"),
    mcq("What is the main force trying to push a bridge sideways in a storm?", ["Wind", "Gravity", "Magnetism", "Friction from cars"], 0,
        "Wind loads are checked in design and with wind-tunnel models.",
        "ঝড়ে সেতুকে পাশে ঠেলতে চাওয়া প্রধান বল কোনটা?", ["বাতাস", "মাধ্যাকর্ষণ", "চুম্বকত্ব", "গাড়ির ঘর্ষণ"],
        "নকশায় আর বায়ু-সুড়ঙ্গের মডেলে বাতাসের বোঝা যাচাই হয়।"),
    mcq("Why do earthquake-zone bridges use special bearings and joints?", ["To let the ground shake without tearing the bridge apart", "To make the bridge heavier", "To stop cars", "They do not"], 0,
        "Isolation bearings act like shock absorbers between deck and piers.",
        "ভূমিকম্প-প্রবণ অঞ্চলের সেতুতে বিশেষ বিয়ারিং আর জোড় থাকে কেন?", ["মাটি কাঁপলেও যাতে সেতু ছিঁড়ে না যায়", "সেতু ভারী করতে", "গাড়ি থামাতে", "থাকে না"],
        "বিচ্ছিন্নকারী বিয়ারিং পাটাতন আর থামের মধ্যে শক-অ্যাবজর্বারের মতো কাজ করে।"),
    moment(120, 3, "A pump handle user", "পাম্পের হাতলে একজন"),
    moment(25, 8, "A boatman on a long oar", "লম্বা দাঁড়ে একজন মাঝি"),
    balance(150, 2, 5), balance(80, 5, 4), balance(300, 2, 3),
    pressure(2400, 6, "A stack of bricks", "ইটের একটা স্তূপ"),
    pressure(72000, 8, "A road roller", "একটা রোড-রোলার"),
    density(1800, 2, "A heap of dry sand", "শুকনো বালির একটা ঢিবি"),
    density(17800, 2, "A block of copper", "তামার একটা ব্লক"),
    mcq("Why does a bicycle's long pedal crank make climbing easier than a short one?", ["Longer cranks give a bigger moment for the same foot push", "They weigh less", "They make the chain shorter", "They are not easier"], 0,
        "Moment = force x distance - a longer crank increases the distance.",
        "চড়াই ভাঙতে সাইকেলের লম্বা প্যাডেল-হাতল ছোটটার চেয়ে সহজ কেন?", ["একই পায়ের ঠেলায় লম্বা হাতল বড় ভ্রামক দেয়", "ওজনে হালকা", "চেন ছোট করে", "সহজ নয়"],
        "ভ্রামক = বল x দূরত্ব - লম্বা হাতল দূরত্ব বাড়ায়।"),
    mcq("A diver feels pressure on their ears at the bottom of a pool. Why?", ["The water above pushes harder the deeper you go", "Pools are magnetic", "The water is colder", "Ears shrink in water"], 0,
        "Water pressure grows with depth - foundations in deep rivers feel it too.",
        "পুকুরের তলায় একজন ডুবুরি কানে চাপ অনুভব করেন। কেন?", ["যত গভীরে, উপরের জল তত জোরে চাপে", "পুকুর চুম্বকীয়", "জল ঠান্ডা", "জলে কান ছোট হয়"],
        "গভীরতার সঙ্গে জলের চাপ বাড়ে - গভীর নদীর ভিতও তা টের পায়।"),
    mcq("An ice cube floats in water. What does that tell you?", ["Ice is less dense than liquid water", "Ice is heavier than water", "Water is magnetic", "Ice has no mass"], 0,
        "Water expands when it freezes - which can crack concrete in cold climates.",
        "বরফের টুকরো জলে ভাসে। এতে কী বোঝা যায়?", ["বরফ তরল জলের চেয়ে কম ঘন", "বরফ জলের চেয়ে ভারী", "জল চুম্বকীয়", "বরফের ভর নেই"],
        "জমলে জল প্রসারিত হয় - ঠান্ডা অঞ্চলে যা কংক্রিট ফাটাতে পারে।"),
    mcq("A rope holds up a 500 N lantern under a footbridge. What force is in the rope?", ["500 N of tension", "500 N of compression", "0 N", "1,000 N of compression"], 0,
        "The rope pulls up exactly as hard as the weight pulls down.",
        "একটা দড়ি হাঁটার সেতুর নিচে 500 N-এর একটা লণ্ঠন ঝুলিয়ে রেখেছে। দড়িতে কত বল?", ["500 N টান", "500 N সংনমন", "0 N", "1,000 N সংনমন"],
        "ওজন যতটা জোরে নিচে টানে, দড়ি ঠিক ততটা জোরে উপরে টানে।"),
    mcq("Two people carry a 600 N plank, one at each end, with the weight in the middle. How much does each hold?", ["300 N", "600 N", "150 N", "1,200 N"], 0,
        "With the load central, the supports share it equally - just like a simply supported bridge.",
        "দুজন একটা 600 N তক্তা দুই প্রান্তে ধরে আছেন, ওজন মাঝখানে। প্রত্যেকে কত ধরেন?", ["300 N", "600 N", "150 N", "1,200 N"],
        "বোঝা মাঝখানে থাকলে আলম্বগুলো সমান ভাগ করে - সরল-আলম্বিত সেতুর মতো।"),
)
