"""Class 5 - Chemistry (Junior Cadet): atoms, elements and compounds, symbols, metals and
non-metals, the pH scale, word equations, combustion and fuels, cement hydration and the
water-cement ratio, corrosion chemistry, polymers and safe handling on site."""
from . import mcq


def wc(water, cement):
    r = round(water / cement, 2)
    o = list(dict.fromkeys([r, round(cement / water, 2), round(r + 0.1, 2), round(r - 0.1, 2)]))[:4]
    return mcq(f"A mix uses {water} kg of water with {cement} kg of cement. What is its water-cement ratio?",
               [str(x) for x in o], 0,
               f"Water-cement ratio = water ÷ cement = {water} ÷ {cement} = {r}. Lower ratios (about 0.4-0.5) give stronger concrete.",
               f"একটা মিশ্রণে {cement} kg সিমেন্টের সঙ্গে {water} kg জল। জল-সিমেন্ট অনুপাত কত?",
               [str(x) for x in o],
               f"জল-সিমেন্ট অনুপাত = জল ÷ সিমেন্ট = {water} ÷ {cement} = {r}। কম অনুপাত (প্রায় 0.4-0.5) বেশি শক্ত কংক্রিট দেয়।")


def conc(solute, total, what_en, what_bn):
    r = solute * 100 // total
    o = list(dict.fromkeys([r, solute, 100 - r, r * 2, r + 5]))[:4]
    return mcq(f"{solute} g of {what_en} is dissolved to make {total} g of solution. What percent by mass is {what_en}?",
               [f"{x}%" for x in o], 0,
               f"{solute} ÷ {total} x 100 = {r}%.",
               f"{solute} g {what_bn} গুলে {total} g দ্রবণ তৈরি হলো। ভরের হিসেবে {what_bn} কত শতাংশ?",
               [f"{x}%" for x in o],
               f"{solute} ÷ {total} x 100 = {r}%।")


def ph(value, what_en, what_bn):
    kind = 0 if value < 7 else (1 if value == 7 else 2)
    o = ["Acidic", "Neutral", "Alkaline", "Cannot have a pH"]
    o_bn = ["অম্লীয়", "নিরপেক্ষ", "ক্ষারীয়", "pH থাকতে পারে না"]
    return mcq(f"{what_en} has a pH of {value}. What is it?", o, kind,
               "Below 7 is acidic, 7 is neutral, above 7 is alkaline.",
               f"{what_bn}-এর pH {value}। এটা কী?", o_bn,
               "7-এর কম অম্লীয়, 7 নিরপেক্ষ, 7-এর বেশি ক্ষারীয়।")


def sym(name_en, name_bn, s, wrong):
    o = [s, *wrong]
    return mcq(f"What is the chemical symbol for {name_en}?", o, 0,
               f"{name_en} = {s}.",
               f"{name_bn}-এর রাসায়নিক সংকেত কী?", o,
               f"{name_bn} = {s}।")


ITEMS = (
    wc(200, 400), wc(180, 400), wc(250, 500), wc(225, 450), wc(150, 300), wc(270, 450),
    conc(10, 100, "salt", "লবণ"), conc(25, 200, "sugar", "চিনি"), conc(5, 50, "copper sulphate", "তুঁতে"),
    conc(30, 120, "baking soda", "খাবার সোডা"), conc(45, 300, "washing soda", "কাপড়কাচা সোডা"),
    ph(2, "Lemon juice", "লেবুর রস"), ph(7, "Pure water", "বিশুদ্ধ জল"), ph(12, "Wet cement paste", "ভেজা সিমেন্ট-মণ্ড"),
    ph(5, "Acid rain", "অ্যাসিড বৃষ্টি"), ph(9, "Soap solution", "সাবান-জল"), ph(3, "Vinegar", "ভিনিগার"),
    ph(13, "Oven cleaner", "চুলা-পরিষ্কারক"), ph(8, "Sea water", "সমুদ্রের জল"),
    sym("copper", "তামা", "Cu", ["Co", "C", "Cp"]),
    sym("zinc", "দস্তা", "Zn", ["Z", "Zi", "Sn"]),
    sym("aluminium", "অ্যালুমিনিয়াম", "Al", ["Am", "A", "Au"]),
    sym("carbon", "কার্বন", "C", ["Ca", "Co", "Cr"]),
    sym("oxygen", "অক্সিজেন", "O", ["Ox", "Os", "Og"]),
    sym("gold", "সোনা", "Au", ["Go", "Ag", "Gd"]),
    sym("silver", "রুপো", "Ag", ["Si", "Sv", "Au"]),
    sym("calcium", "ক্যালসিয়াম", "Ca", ["C", "Cl", "Cm"]),
    mcq("What is an 'atom'?", ["The tiny basic particle that all matter is made of", "A type of cell", "A small planet", "A grain of sand"], 0,
        "Atoms are so small that millions fit across the width of a hair.",
        "'পরমাণু' কী?", ["যে ক্ষুদ্র মৌলিক কণা দিয়ে সব পদার্থ তৈরি", "এক রকম কোষ", "ছোট গ্রহ", "বালির দানা"],
        "পরমাণু এত ছোট যে একটা চুলের প্রস্থে লক্ষ লক্ষ আঁটে।"),
    mcq("What is an 'element'?", ["A substance made of only one kind of atom", "A mixture of many things", "A kind of machine", "A compound always"], 0,
        "Iron, oxygen and gold are elements.",
        "'মৌল' কী?", ["যে পদার্থ কেবল এক রকম পরমাণু দিয়ে তৈরি", "অনেক কিছুর মিশ্রণ", "এক রকম যন্ত্র", "সবসময় যৌগ"],
        "লোহা, অক্সিজেন আর সোনা মৌল।"),
    mcq("What is a 'compound'?", ["Two or more elements chemically joined", "A single element", "A mixture you can sieve apart", "A metal only"], 0,
        "Water (H2O) and rust (iron oxide) are compounds.",
        "'যৌগ' কী?", ["রাসায়নিকভাবে জোড়া দুই বা বেশি মৌল", "একটা মাত্র মৌল", "চালুনিতে আলাদা করা যায় এমন মিশ্রণ", "শুধু ধাতু"],
        "জল (H2O) আর মরচে (আয়রন অক্সাইড) যৌগ।"),
    mcq("How is a compound different from a mixture?", ["A compound's parts are chemically bonded; a mixture's can be separated physically", "They are the same", "Mixtures are always liquids", "Compounds are always gases"], 0,
        "Sand and iron filings (mixture) separate with a magnet; iron sulphide (compound) does not.",
        "যৌগ মিশ্রণ থেকে কীভাবে আলাদা?", ["যৌগের অংশ রাসায়নিকভাবে বাঁধা; মিশ্রণের অংশ ভৌতভাবে আলাদা করা যায়", "দুটো একই", "মিশ্রণ সবসময় তরল", "যৌগ সবসময় গ্যাস"],
        "বালি আর লোহার গুঁড়ো (মিশ্রণ) চুম্বকে আলাদা হয়; আয়রন সালফাইড (যৌগ) হয় না।"),
    mcq("What is a 'molecule'?", ["Two or more atoms joined together", "A single atom always", "A kind of cell", "A grain of salt"], 0,
        "An oxygen molecule (O2) has two oxygen atoms.",
        "'অণু' কী?", ["দুই বা বেশি পরমাণু একসঙ্গে জোড়া", "সবসময় একটা পরমাণু", "এক রকম কোষ", "লবণের দানা"],
        "অক্সিজেনের একটা অণুতে (O2) দুটি অক্সিজেন পরমাণু।"),
    mcq("How many atoms are in one molecule of water, H2O?", ["3", "2", "1", "4"], 0,
        "Two hydrogen atoms + one oxygen atom.",
        "জলের একটা অণুতে (H2O) কয়টি পরমাণু?", ["3", "2", "1", "4"],
        "দুটি হাইড্রোজেন পরমাণু + একটি অক্সিজেন পরমাণু।"),
    mcq("What is the periodic table?", ["A chart that lists all the chemical elements in order", "A train timetable", "A multiplication table", "A calendar"], 0,
        "Dmitri Mendeleev arranged it in 1869; it now has 118 elements.",
        "পর্যায় সারণি কী?", ["সব রাসায়নিক মৌলকে ক্রমানুসারে সাজানো তালিকা", "ট্রেনের সময়সূচি", "নামতার সারণি", "ক্যালেন্ডার"],
        "দিমিত্রি মেন্ডেলিভ 1869 সালে সাজান; এখন 118টি মৌল।"),
    mcq("Which property do most metals share?", ["They conduct electricity and heat well", "They are all liquids", "They break like glass", "They are poor conductors"], 0,
        "Metals are also usually shiny, strong and can be bent or drawn into wire.",
        "বেশিরভাগ ধাতুর কোন ধর্ম একই?", ["তারা ভালো বিদ্যুৎ আর তাপ পরিবহন করে", "সবাই তরল", "কাচের মতো ভাঙে", "দুর্বল পরিবাহী"],
        "ধাতু সাধারণত চকচকে, শক্ত আর বাঁকানো বা তারে টানা যায়।"),
    mcq("Which of these is a non-metal?", ["Sulphur", "Iron", "Copper", "Zinc"], 0,
        "Non-metals are usually dull, brittle and poor conductors.",
        "এগুলোর কোনটা অধাতু?", ["সালফার (গন্ধক)", "লোহা", "তামা", "দস্তা"],
        "অধাতু সাধারণত নিষ্প্রভ, ভঙ্গুর আর দুর্বল পরিবাহী।"),
    mcq("What does 'malleable' mean for a metal?", ["It can be hammered into thin sheets", "It shatters easily", "It is magnetic", "It is liquid"], 0,
        "Gold is so malleable it can be beaten into leaf thinner than paper.",
        "ধাতুর ক্ষেত্রে 'ঘাতসহ' মানে কী?", ["পিটিয়ে পাতলা পাত বানানো যায়", "সহজে চূর্ণ হয়", "চুম্বকীয়", "তরল"],
        "সোনা এত ঘাতসহ যে কাগজের চেয়ে পাতলা পাতে পেটানো যায়।"),
    mcq("What does 'ductile' mean for a metal?", ["It can be stretched into wire", "It cannot be shaped", "It floats", "It dissolves in water"], 0,
        "Copper's ductility makes it perfect for electrical wires; steel's makes cables.",
        "ধাতুর ক্ষেত্রে 'প্রসার্য' মানে কী?", ["টেনে তার বানানো যায়", "আকার দেওয়া যায় না", "ভাসে", "জলে গোলে"],
        "তামার প্রসার্যতা তাকে বিদ্যুতের তারের জন্য আদর্শ করে; ইস্পাতের প্রসার্যতা দিয়ে তার বানানো হয়।"),
    mcq("Which metals are magnetic?", ["Iron, nickel and cobalt (and steel)", "Copper and gold", "Aluminium and silver", "All metals"], 0,
        "Most metals are not magnetic - a magnet will not pick up a copper coin.",
        "কোন ধাতুগুলো চুম্বকীয়?", ["লোহা, নিকেল আর কোবাল্ট (আর ইস্পাত)", "তামা আর সোনা", "অ্যালুমিনিয়াম আর রুপো", "সব ধাতু"],
        "বেশিরভাগ ধাতু চুম্বকীয় নয় - চুম্বক তামার পয়সা তোলে না।"),
    mcq("What is a 'chemical reaction'?", ["A change where substances turn into new substances", "Mixing sand and water", "Melting ice", "Breaking glass"], 0,
        "Burning, rusting and cement setting are reactions.",
        "'রাসায়নিক বিক্রিয়া' কী?", ["যে পরিবর্তনে পদার্থ নতুন পদার্থে বদলায়", "বালি আর জল মেশানো", "বরফ গলানো", "কাচ ভাঙা"],
        "পোড়া, মরচে ধরা আর সিমেন্ট জমা বিক্রিয়া।"),
    mcq("In a word equation, what are 'reactants'?", ["The substances you start with", "The new substances made", "The container", "The heat only"], 0,
        "Reactants -> products.",
        "শব্দ-সমীকরণে 'বিক্রিয়ক' কী?", ["যে পদার্থ দিয়ে শুরু হয়", "তৈরি হওয়া নতুন পদার্থ", "পাত্র", "শুধু তাপ"],
        "বিক্রিয়ক -> বিক্রিয়াজাত।"),
    mcq("Complete: iron + oxygen -> ?", ["iron oxide (rust)", "iron water", "steel", "carbon dioxide"], 0,
        "Iron reacts with oxygen (helped by water) to make iron oxide.",
        "সম্পূর্ণ করো: লোহা + অক্সিজেন -> ?", ["আয়রন অক্সাইড (মরচে)", "লোহা-জল", "ইস্পাত", "কার্বন ডাই-অক্সাইড"],
        "লোহা অক্সিজেনের সঙ্গে (জলের সাহায্যে) বিক্রিয়া করে আয়রন অক্সাইড তৈরি করে।"),
    mcq("Complete: carbon + oxygen -> ?", ["carbon dioxide", "carbon water", "oxygen carbonate", "hydrogen"], 0,
        "Burning charcoal makes carbon dioxide.",
        "সম্পূর্ণ করো: কার্বন + অক্সিজেন -> ?", ["কার্বন ডাই-অক্সাইড", "কার্বন-জল", "অক্সিজেন কার্বোনেট", "হাইড্রোজেন"],
        "কাঠকয়লা পোড়ালে কার্বন ডাই-অক্সাইড হয়।"),
    mcq("Complete: hydrogen + oxygen -> ?", ["water", "salt", "rust", "air"], 0,
        "Hydrogen burns cleanly - its only product is water.",
        "সম্পূর্ণ করো: হাইড্রোজেন + অক্সিজেন -> ?", ["জল", "লবণ", "মরচে", "বাতাস"],
        "হাইড্রোজেন পরিষ্কারভাবে পোড়ে - একমাত্র বিক্রিয়াজাত জল।"),
    mcq("Complete: acid + alkali -> ?", ["salt + water", "metal + gas", "rust", "oxygen only"], 0,
        "This is neutralisation.",
        "সম্পূর্ণ করো: অ্যাসিড + ক্ষার -> ?", ["লবণ + জল", "ধাতু + গ্যাস", "মরচে", "শুধু অক্সিজেন"],
        "এটাই প্রশমন।"),
    mcq("Complete: metal + acid -> ?", ["salt + hydrogen", "water only", "rust + oxygen", "nothing"], 0,
        "Fizzing bubbles are hydrogen gas - acids eat into many metals.",
        "সম্পূর্ণ করো: ধাতু + অ্যাসিড -> ?", ["লবণ + হাইড্রোজেন", "শুধু জল", "মরচে + অক্সিজেন", "কিছুই না"],
        "বুদবুদ হলো হাইড্রোজেন গ্যাস - অ্যাসিড অনেক ধাতু ক্ষয় করে।"),
    mcq("In a chemical reaction, what happens to the total mass?", ["It stays the same - atoms are rearranged, not lost", "It always doubles", "It disappears", "It always halves"], 0,
        "This is the law of conservation of mass.",
        "রাসায়নিক বিক্রিয়ায় মোট ভরের কী হয়?", ["একই থাকে - পরমাণু নতুন করে সাজে, হারায় না", "সবসময় দ্বিগুণ হয়", "উধাও হয়", "সবসময় অর্ধেক হয়"],
        "এটা ভরের সংরক্ষণ-সূত্র।"),
    mcq("Why does a steel bar get heavier as it rusts?", ["Oxygen atoms from the air join onto the iron", "Rust grows from nowhere", "Water turns into iron", "It does not"], 0,
        "Mass is conserved: iron + oxygen = heavier iron oxide.",
        "মরচে ধরলে ইস্পাতের দণ্ড ভারী হয় কেন?", ["বাতাসের অক্সিজেন-পরমাণু লোহার সঙ্গে জোড়ে", "শূন্য থেকে মরচে জন্মায়", "জল লোহায় বদলায়", "ভারী হয় না"],
        "ভর সংরক্ষিত থাকে: লোহা + অক্সিজেন = ভারী আয়রন অক্সাইড।"),
    mcq("What is 'combustion'?", ["Burning: a fuel reacting with oxygen and releasing heat", "Freezing", "Dissolving", "Melting"], 0,
        "Engines and stoves use combustion.",
        "'দহন' কী?", ["পোড়া: জ্বালানি অক্সিজেনের সঙ্গে বিক্রিয়া করে তাপ ছাড়ে", "জমা", "গোলা", "গলা"],
        "ইঞ্জিন আর চুলা দহন ব্যবহার করে।"),
    mcq("Why is burning fuel in a closed room without air flow dangerous?", ["Incomplete burning makes carbon monoxide, a deadly gas", "It makes too much oxygen", "Rooms explode always", "It is not dangerous"], 0,
        "Never run generators or charcoal stoves indoors.",
        "বাতাস চলাচল ছাড়া বন্ধ ঘরে জ্বালানি পোড়ানো বিপজ্জনক কেন?", ["অসম্পূর্ণ দহনে কার্বন মনোক্সাইড হয়, একটা প্রাণঘাতী গ্যাস", "অনেক বেশি অক্সিজেন হয়", "ঘর সবসময় ফাটে", "বিপজ্জনক নয়"],
        "কখনো ঘরের ভেতরে জেনারেটর বা কাঠকয়লার চুলা চালাবে না।"),
    mcq("What are 'fossil fuels'?", ["Coal, oil and gas formed from ancient plants and animals", "Fuel made from fossils in museums", "Solar power", "Wind"], 0,
        "They took millions of years to form and will run out.",
        "'জীবাশ্ম জ্বালানি' কী?", ["প্রাচীন উদ্ভিদ আর প্রাণী থেকে তৈরি কয়লা, তেল আর গ্যাস", "জাদুঘরের জীবাশ্ম থেকে তৈরি জ্বালানি", "সৌরশক্তি", "বাতাস"],
        "তৈরি হতে লক্ষ লক্ষ বছর লেগেছে আর একদিন ফুরোবে।"),
    mcq("Which gas from burning fuels is the main cause of climate change?", ["Carbon dioxide", "Oxygen", "Nitrogen", "Helium"], 0,
        "Making cement and steel also releases lots of CO2 - engineers are finding greener ways.",
        "জ্বালানি পোড়ানোর কোন গ্যাস জলবায়ু পরিবর্তনের প্রধান কারণ?", ["কার্বন ডাই-অক্সাইড", "অক্সিজেন", "নাইট্রোজেন", "হিলিয়াম"],
        "সিমেন্ট আর ইস্পাত তৈরিতেও অনেক CO2 বেরোয় - প্রকৌশলীরা সবুজ উপায় খুঁজছেন।"),
    mcq("What happens chemically when cement is mixed with water?", ["It reacts (hydration) to form hard crystals that bind everything", "It simply dries like mud", "It melts", "It dissolves completely"], 0,
        "Hydration keeps going for weeks - concrete keeps gaining strength.",
        "সিমেন্ট জলে মেশালে রাসায়নিকভাবে কী হয়?", ["বিক্রিয়া (জলযোজন) করে শক্ত কেলাস তৈরি হয় যা সব কিছু বাঁধে", "শুধু কাদার মতো শুকোয়", "গলে যায়", "পুরো গুলে যায়"],
        "জলযোজন সপ্তাহের পর সপ্তাহ চলে - কংক্রিট শক্তি পেতেই থাকে।"),
    mcq("Why does setting concrete feel warm?", ["Hydration is a reaction that gives off heat", "The sun heats it only", "Cement is electric", "It does not"], 0,
        "Huge pours (like dam walls) need cooling so heat does not crack them.",
        "জমতে থাকা কংক্রিট গরম লাগে কেন?", ["জলযোজন এমন বিক্রিয়া যা তাপ ছাড়ে", "শুধু রোদ গরম করে", "সিমেন্ট বৈদ্যুতিক", "লাগে না"],
        "বিশাল ঢালাইয়ে (যেমন বাঁধের দেওয়াল) ঠান্ডা রাখতে হয়, যাতে তাপে না ফাটে।"),
    mcq("How long does concrete usually take to reach most of its design strength?", ["About 28 days", "About 1 hour", "About 1 year exactly", "Instantly"], 0,
        "Engineers test sample cubes at 7 and 28 days.",
        "কংক্রিট সাধারণত কত দিনে নকশার বেশিরভাগ শক্তি পায়?", ["প্রায় 28 দিন", "প্রায় 1 ঘণ্টা", "ঠিক 1 বছর", "সঙ্গে সঙ্গে"],
        "প্রকৌশলীরা নমুনা-ঘনক 7 আর 28 দিনে পরীক্ষা করেন।"),
    mcq("Why do engineers crush concrete test cubes in a machine?", ["To check the concrete is as strong as the design needs", "To recycle them", "For fun", "To make gravel"], 0,
        "If cubes fail early, the batch may need to be removed.",
        "প্রকৌশলীরা কংক্রিটের পরীক্ষা-ঘনক যন্ত্রে চূর্ণ করেন কেন?", ["কংক্রিট নকশার মতো শক্ত কিনা যাচাই করতে", "পুনর্ব্যবহারের জন্য", "মজার জন্য", "পাথরকুচি বানাতে"],
        "ঘনক আগেই ভাঙলে সেই ব্যাচ সরাতে হতে পারে।"),
    mcq("Which water-cement ratio usually gives the strongest concrete (if it can still be placed)?", ["0.4", "0.7", "0.9", "1.2"], 0,
        "Less water = fewer pores = stronger - but the mix must still flow into the moulds.",
        "কোন জল-সিমেন্ট অনুপাতে সাধারণত সবচেয়ে শক্ত কংক্রিট হয় (যদি তখনো ঢালা যায়)?", ["0.4", "0.7", "0.9", "1.2"],
        "কম জল = কম ছিদ্র = বেশি শক্ত - তবে মিশ্রণকে তখনো ছাঁচে গড়াতে হবে।"),
    mcq("Why are 'plasticisers' added to some concrete?", ["They make it flow easily without adding extra water", "To make it colourful", "To make it weaker", "To make it float"], 0,
        "Workability without weakening.",
        "কিছু কংক্রিটে 'প্লাস্টিসাইজার' মেশানো হয় কেন?", ["বাড়তি জল ছাড়াই সহজে গড়াতে", "রঙিন করতে", "দুর্বল করতে", "ভাসাতে"],
        "দুর্বল না করেই কাজের সুবিধা।"),
    mcq("Why does salt water make steel rust faster?", ["Dissolved salt helps electric charges move, speeding the reaction", "Salt is made of iron", "Salt cools steel", "It does not"], 0,
        "Coastal bridges need extra protection from salty spray.",
        "নোনা জল ইস্পাতে দ্রুত মরচে ধরায় কেন?", ["গোলা লবণ বৈদ্যুতিক আধান চলতে সাহায্য করে, বিক্রিয়া দ্রুত হয়", "লবণ লোহা দিয়ে তৈরি", "লবণ ইস্পাত ঠান্ডা করে", "ধরায় না"],
        "উপকূলের সেতুতে নোনা ছিটে থেকে বাড়তি সুরক্ষা লাগে।"),
    mcq("How does a zinc coating protect steel even when scratched?", ["Zinc reacts first, sacrificing itself instead of the steel", "Zinc is invisible", "Zinc is magnetic", "It does not protect"], 0,
        "This is sacrificial protection - zinc corrodes so iron does not.",
        "আঁচড় লাগলেও দস্তার প্রলেপ ইস্পাতকে কীভাবে রক্ষা করে?", ["দস্তা আগে বিক্রিয়া করে, ইস্পাতের বদলে নিজেকে উৎসর্গ করে", "দস্তা অদৃশ্য", "দস্তা চুম্বকীয়", "রক্ষা করে না"],
        "এটা উৎসর্গী সুরক্ষা - দস্তা ক্ষয় হয় যাতে লোহা না হয়।"),
    mcq("Why are blocks of zinc or magnesium bolted onto ships and steel piers in the sea?", ["They corrode instead of the steel (sacrificial anodes)", "To add weight", "To attract fish", "For decoration"], 0,
        "They are replaced when used up.",
        "সমুদ্রে জাহাজ আর ইস্পাতের থামে দস্তা বা ম্যাগনেশিয়ামের ব্লক বোল্ট করা হয় কেন?", ["ইস্পাতের বদলে তারা ক্ষয় হয় (উৎসর্গী অ্যানোড)", "ওজন বাড়াতে", "মাছ টানতে", "সাজসজ্জার জন্য"],
        "ক্ষয়ে গেলে বদলে দেওয়া হয়।"),
    mcq("What is 'stainless steel'?", ["Steel with chromium added so it resists rust", "Steel painted silver", "Pure iron", "Steel that never bends"], 0,
        "Chromium forms a thin protective film on the surface.",
        "'মরচে-রোধী ইস্পাত' (স্টেইনলেস স্টিল) কী?", ["ক্রোমিয়াম মেশানো ইস্পাত, যা মরচে ঠেকায়", "রুপোলি রং করা ইস্পাত", "বিশুদ্ধ লোহা", "যে ইস্পাত কখনো বাঁকে না"],
        "ক্রোমিয়াম তলে পাতলা রক্ষাকারী পর্দা তৈরি করে।"),
    mcq("What is 'weathering steel'?", ["Steel that forms a stable rust layer which protects it from deeper rust", "Steel that predicts weather", "Steel painted blue", "Steel that melts in rain"], 0,
        "Some bridges are left unpainted because of this protective patina.",
        "'আবহাওয়া-রোধী ইস্পাত' কী?", ["যে ইস্পাত একটা স্থির মরচে-স্তর বানায় যা গভীর মরচে থেকে রক্ষা করে", "যে ইস্পাত আবহাওয়ার পূর্বাভাস দেয়", "নীল রং করা ইস্পাত", "যে ইস্পাত বৃষ্টিতে গলে"],
        "এই রক্ষাকারী আস্তরণের জন্য কিছু সেতু রং ছাড়াই রাখা হয়।"),
    mcq("What is a 'polymer'?", ["A long chain molecule made of many repeating units", "A single atom", "A metal", "A type of rock"], 0,
        "Plastics, rubber and nylon are polymers.",
        "'পলিমার' কী?", ["বহু পুনরাবৃত্ত একক দিয়ে তৈরি লম্বা শিকল-অণু", "একটা মাত্র পরমাণু", "ধাতু", "এক রকম পাথর"],
        "প্লাস্টিক, রবার আর নাইলন পলিমার।"),
    mcq("Why are some modern footbridges made with fibre-reinforced polymer (FRP)?", ["It is light, strong and does not rust", "It is the heaviest material", "It melts in sunlight", "It is magnetic"], 0,
        "FRP decks can be lifted into place in one piece.",
        "কিছু আধুনিক হাঁটার সেতু তন্তু-শক্তিশালী পলিমার (এফআরপি) দিয়ে তৈরি কেন?", ["হালকা, শক্ত আর মরচে ধরে না", "সবচেয়ে ভারী উপাদান", "রোদে গলে", "চুম্বকীয়"],
        "এফআরপি পাটাতন এক টুকরোয় তুলে বসানো যায়।"),
    mcq("What is 'bitumen' used for on bridges and roads?", ["Binding stones in the road surface and waterproofing", "Painting signs", "Making glass", "Fuel for cars"], 0,
        "Bitumen is a sticky black product from crude oil.",
        "সেতু আর রাস্তায় 'বিটুমিন' কীসে ব্যবহার হয়?", ["রাস্তার তলে পাথর বাঁধতে আর জলরোধী করতে", "ফলক রং করতে", "কাচ বানাতে", "গাড়ির জ্বালানি"],
        "বিটুমিন অপরিশোধিত তেল থেকে পাওয়া আঠালো কালো পদার্থ।"),
    mcq("Why does bitumen become soft on very hot days?", ["It is a thick liquid that flows more as it warms", "It turns into water", "It rusts", "It does not"], 0,
        "Engineers choose bitumen grades to suit the local climate.",
        "খুব গরম দিনে বিটুমিন নরম হয় কেন?", ["এটা ঘন তরল, গরমে বেশি গড়ায়", "জলে বদলায়", "মরচে ধরে", "হয় না"],
        "প্রকৌশলীরা স্থানীয় জলবায়ু মেনে বিটুমিনের ধরন বাছেন।"),
    mcq("Which gas is used in welding torches with oxygen?", ["Acetylene", "Helium", "Nitrogen", "Carbon dioxide"], 0,
        "Oxy-acetylene flames reach about 3,100 °C - hot enough to cut steel.",
        "ঝালাইয়ের টর্চে অক্সিজেনের সঙ্গে কোন গ্যাস ব্যবহার হয়?", ["অ্যাসিটিলিন", "হিলিয়াম", "নাইট্রোজেন", "কার্বন ডাই-অক্সাইড"],
        "অক্সি-অ্যাসিটিলিন শিখা প্রায় 3,100 °C পৌঁছায় - ইস্পাত কাটার মতো গরম।"),
    mcq("Why must gas cylinders on site be stored upright and chained?", ["If they fall and the valve breaks, they can shoot off like rockets", "To look tidy only", "To keep gas cold", "They are not dangerous"], 0,
        "Compressed gas is a big stored energy hazard.",
        "নির্মাণস্থলে গ্যাস-সিলিন্ডার খাড়া করে শিকলে বাঁধা রাখতে হয় কেন?", ["পড়ে গিয়ে ভালভ ভাঙলে রকেটের মতো ছুটে যেতে পারে", "শুধু পরিপাটি দেখাতে", "গ্যাস ঠান্ডা রাখতে", "বিপজ্জনক নয়"],
        "চাপা গ্যাস বিশাল সঞ্চিত শক্তির বিপদ।"),
    mcq("What does 'toxic' on a chemical label warn you about?", ["It can poison you if swallowed, breathed or touched", "It is tasty", "It is cold", "It is a metal"], 0,
        "Use gloves, masks and ventilation as the label says.",
        "রাসায়নিকের লেবেলে 'বিষাক্ত' কী নিয়ে সতর্ক করে?", ["গিললে, শ্বাসে নিলে বা ছুঁলে বিষক্রিয়া হতে পারে", "সুস্বাদু", "ঠান্ডা", "এটা ধাতু"],
        "লেবেল অনুযায়ী দস্তানা, মুখোশ আর বায়ুচলাচল ব্যবহার করো।"),
    mcq("Why should chemicals never be stored in drink bottles?", ["Someone may drink them by mistake", "Bottles leak gas", "It is cheaper", "Labels fall off"], 0,
        "Always keep chemicals in their labelled containers.",
        "রাসায়নিক কখনো পানীয়ের বোতলে রাখবে না কেন?", ["কেউ ভুল করে খেয়ে ফেলতে পারে", "বোতল থেকে গ্যাস বেরোয়", "সস্তা হয়", "লেবেল খুলে যায়"],
        "রাসায়নিক সবসময় লেবেল-লাগানো পাত্রে রাখো।"),
    mcq("What is a 'catalyst'?", ["A substance that speeds up a reaction without being used up", "A kind of cat", "A fuel", "An acid only"], 0,
        "Car exhaust catalysts turn harmful gases into less harmful ones.",
        "'অনুঘটক' কী?", ["যে পদার্থ নিজে খরচ না হয়ে বিক্রিয়া দ্রুত করে", "এক রকম বিড়াল", "জ্বালানি", "শুধু অ্যাসিড"],
        "গাড়ির নিষ্কাশনের অনুঘটক ক্ষতিকর গ্যাসকে কম ক্ষতিকর গ্যাসে বদলায়।"),
    mcq("How can you make a reaction go faster?", ["Raise the temperature, crush solids into powder or use a catalyst", "Make it colder always", "Use bigger lumps", "Add nothing"], 0,
        "Concrete sets faster in warm weather for the same reason.",
        "বিক্রিয়া দ্রুত করবে কীভাবে?", ["তাপমাত্রা বাড়াও, কঠিনকে গুঁড়ো করো বা অনুঘটক দাও", "সবসময় ঠান্ডা করো", "বড় দলা ব্যবহার করো", "কিছু দিও না"],
        "একই কারণে গরম আবহাওয়ায় কংক্রিট দ্রুত জমে।"),
    mcq("Why does powdered sugar dissolve faster than a sugar cube?", ["Powder has much more surface area touching the water", "Powder is sweeter", "Cubes are magnetic", "It does not"], 0,
        "Fine cement powder reacts quickly with water for the same reason.",
        "চিনির কিউবের চেয়ে গুঁড়ো চিনি দ্রুত গোলে কেন?", ["গুঁড়োর অনেক বেশি তল জলের সংস্পর্শে আসে", "গুঁড়ো বেশি মিষ্টি", "কিউব চুম্বকীয়", "গোলে না"],
        "একই কারণে মিহি সিমেন্ট-গুঁড়ো জলের সঙ্গে দ্রুত বিক্রিয়া করে।"),
    mcq("Which separation method is used to get pure water from salty water?", ["Distillation", "Filtering", "Sieving", "Using a magnet"], 0,
        "Boil, collect the steam, cool it back to water - salt stays behind.",
        "নোনা জল থেকে বিশুদ্ধ জল পেতে কোন পৃথকীকরণ পদ্ধতি ব্যবহার হয়?", ["পাতন", "ছাঁকা", "চালা", "চুম্বক"],
        "ফোটাও, বাষ্প জমাও, ঠান্ডা করে আবার জল করো - লবণ পড়ে থাকে।"),
    mcq("What is 'chromatography' used for?", ["Separating the coloured dyes in an ink", "Measuring force", "Building bridges", "Melting metal"], 0,
        "Different dyes travel at different speeds up wet paper.",
        "'বর্ণলিপি' (ক্রোমাটোগ্রাফি) কীসে ব্যবহার হয়?", ["কালির রঙিন রঞ্জক আলাদা করতে", "বল মাপতে", "সেতু বানাতে", "ধাতু গলাতে"],
        "ভেজা কাগজে আলাদা রঞ্জক আলাদা গতিতে ওঠে।"),
    mcq("Why do steel plants add limestone to the blast furnace?", ["It removes impurities as slag", "To make steel white", "To cool the furnace", "As food for workers"], 0,
        "Slag is even reused in some cements.",
        "ইস্পাত-কারখানা মারুত চুল্লিতে চুনাপাথর দেয় কেন?", ["অশুদ্ধি ধাতুমল হিসেবে সরাতে", "ইস্পাত সাদা করতে", "চুল্লি ঠান্ডা করতে", "কর্মীদের খাবার হিসেবে"],
        "ধাতুমল কিছু সিমেন্টে আবার ব্যবহার হয়।"),
    mcq("What is 'fly ash' and why is it used in concrete?", ["Ash from power stations that can replace some cement and cut CO2", "Ash from flies", "Volcanic dust only", "It is never used"], 0,
        "Using waste products makes concrete greener.",
        "'ফ্লাই অ্যাশ' কী আর কংক্রিটে কেন ব্যবহার হয়?", ["বিদ্যুৎকেন্দ্রের ছাই, যা কিছু সিমেন্টের বদলে চলে আর CO2 কমায়", "মাছির ছাই", "শুধু আগ্নেয়গিরির ধুলো", "কখনো ব্যবহার হয় না"],
        "বর্জ্য কাজে লাগালে কংক্রিট পরিবেশবান্ধব হয়।"),
    mcq("Why is the Iron Pillar of Delhi famous among chemists?", ["It has resisted rust for about 1,600 years", "It is made of gold", "It floats", "It is magnetic north"], 0,
        "Its iron contains phosphorus that helped form a protective layer.",
        "দিল্লির লৌহস্তম্ভ রসায়নবিদদের কাছে বিখ্যাত কেন?", ["প্রায় 1,600 বছর ধরে মরচে ঠেকিয়েছে", "সোনা দিয়ে তৈরি", "ভাসে", "চুম্বকীয় উত্তর"],
        "এর লোহায় ফসফরাস আছে, যা রক্ষাকারী স্তর তৈরিতে সাহায্য করেছে।"),
    mcq("What is an 'indicator' that changes colour at different pH values called when it shows many colours?", ["Universal indicator", "Litmus only", "Thermometer", "Barometer"], 0,
        "Universal indicator goes red (strong acid) through green (neutral) to purple (strong alkali).",
        "বিভিন্ন pH-এ নানা রং দেখানো নির্দেশককে কী বলে?", ["সর্বজনীন নির্দেশক", "শুধু লিটমাস", "থার্মোমিটার", "ব্যারোমিটার"],
        "সর্বজনীন নির্দেশক লাল (শক্তিশালী অ্যাসিড) থেকে সবুজ (নিরপেক্ষ) হয়ে বেগুনি (শক্তিশালী ক্ষার) হয়।"),
    mcq("Why is fresh concrete's high pH good for the steel inside?", ["The alkaline concrete protects steel from rusting", "It dissolves the steel", "It makes the steel acidic", "It is bad for steel"], 0,
        "Over decades CO2 slowly lowers the pH (carbonation), so cover thickness matters.",
        "তাজা কংক্রিটের উচ্চ pH ভেতরের ইস্পাতের জন্য ভালো কেন?", ["ক্ষারীয় কংক্রিট ইস্পাতকে মরচে থেকে রক্ষা করে", "ইস্পাত গলিয়ে দেয়", "ইস্পাতকে অম্লীয় করে", "ইস্পাতের জন্য খারাপ"],
        "দশকের পর দশক CO2 ধীরে pH কমায় (কার্বনেশন), তাই ঢাকনার পুরুত্ব জরুরি।"),
    mcq("What is the 'cover' in reinforced concrete?", ["The layer of concrete between the steel bars and the surface", "A plastic sheet", "The paint", "The road surface"], 0,
        "Thicker cover keeps water, salt and CO2 away from the steel longer.",
        "রড-কংক্রিটে 'ঢাকনা' (কভার) কী?", ["রড আর তলের মাঝের কংক্রিটের স্তর", "প্লাস্টিকের চাদর", "রং", "রাস্তার তল"],
        "মোটা ঢাকনা জল, লবণ আর CO2-কে রড থেকে বেশি দিন দূরে রাখে।"),
    mcq("Why do cracks in a concrete bridge need repairing quickly?", ["Water and salt get in and rust the steel inside", "Cracks make it heavier", "Cracks are decorative", "They never matter"], 0,
        "Rusting steel expands and cracks the concrete further - a vicious circle.",
        "কংক্রিটের সেতুর ফাটল দ্রুত সারাতে হয় কেন?", ["জল আর লবণ ঢুকে ভেতরের রডে মরচে ধরায়", "ফাটলে ভারী হয়", "ফাটল সাজসজ্জা", "কখনো জরুরি নয়"],
        "মরচে-ধরা রড ফোলে আর কংক্রিট আরও ফাটায় - একটা দুষ্টচক্র।"),
    wc(160, 400),
    conc(12, 60, "sugar", "চিনি"),
    ph(1, "Battery acid", "ব্যাটারির অ্যাসিড"), ph(6, "Milk", "দুধ"), ph(11, "Lime water", "চুন-জল"), ph(4, "Orange juice", "কমলার রস"),
    sym("nitrogen", "নাইট্রোজেন", "N", ["Ni", "Na", "Ne"]),
    sym("hydrogen", "হাইড্রোজেন", "H", ["Hy", "He", "Hg"]),
    sym("sodium", "সোডিয়াম", "Na", ["So", "S", "Sd"]),
    sym("lead", "সিসা", "Pb", ["Le", "Ld", "L"]),
    sym("tin", "টিন", "Sn", ["Ti", "T", "Tn"]),
    sym("chlorine", "ক্লোরিন", "Cl", ["Ch", "C", "Co"]),
    mcq("A thermometer once used a shiny liquid metal that is poisonous. Which metal was it?", ["Mercury", "Iron", "Aluminium", "Copper"], 0,
        "Mercury is the only common metal that is liquid at room temperature - never touch it.",
        "একসময় থার্মোমিটারে একটা চকচকে বিষাক্ত তরল ধাতু ব্যবহার হতো। কোন ধাতু?", ["পারদ", "লোহা", "অ্যালুমিনিয়াম", "তামা"],
        "পারদই একমাত্র সাধারণ ধাতু যা ঘরের তাপমাত্রায় তরল - কখনো ছোঁবে না।"),
    mcq("Why is copper used for roofs of some old buildings, turning green over time?", ["Copper reacts slowly with air and water to form a protective green layer", "It is painted green", "Moss grows on it", "Copper is naturally green"], 0,
        "The green patina (verdigris) protects the copper underneath.",
        "কিছু পুরোনো ভবনের ছাদে তামা ব্যবহার হয়, যা সময়ের সঙ্গে সবুজ হয় কেন?", ["তামা বাতাস আর জলের সঙ্গে ধীরে বিক্রিয়া করে রক্ষাকারী সবুজ স্তর বানায়", "সবুজ রং করা", "শ্যাওলা জন্মায়", "তামা স্বাভাবিকভাবে সবুজ"],
        "সবুজ আস্তরণ (কলঙ্ক) নিচের তামাকে রক্ষা করে।"),
    mcq("Which is a sign that a reaction gives out heat (exothermic)?", ["The container gets warm", "The container gets cold", "Nothing changes", "It turns blue always"], 0,
        "Burning and cement hydration are exothermic; cold packs are endothermic.",
        "কোনটা বোঝায় যে একটা বিক্রিয়া তাপ ছাড়ে (তাপমোচী)?", ["পাত্র গরম হয়", "পাত্র ঠান্ডা হয়", "কিছুই বদলায় না", "সবসময় নীল হয়"],
        "দহন আর সিমেন্টের জলযোজন তাপমোচী; ঠান্ডা-প্যাক তাপগ্রাহী।"),
    mcq("An instant cold pack gets icy when squeezed. What kind of reaction is that?", ["Endothermic - it takes in heat", "Exothermic - it gives out heat", "Combustion", "Rusting"], 0,
        "Endothermic changes absorb heat from their surroundings.",
        "একটা তাৎক্ষণিক ঠান্ডা-প্যাক চাপলে বরফ-ঠান্ডা হয়। এটা কী ধরনের বিক্রিয়া?", ["তাপগ্রাহী - তাপ শোষণ করে", "তাপমোচী - তাপ ছাড়ে", "দহন", "মরচে ধরা"],
        "তাপগ্রাহী পরিবর্তন চারপাশ থেকে তাপ শোষণ করে।"),
    mcq("What does the 2 in O2 tell you?", ["Each oxygen molecule has 2 oxygen atoms", "There are 2 molecules", "Oxygen weighs 2 kg", "It is the second element"], 0,
        "Small numbers after a symbol count the atoms of that element.",
        "O2-তে 2 কী জানায়?", ["প্রতিটি অক্সিজেন-অণুতে 2টি অক্সিজেন পরমাণু", "2টি অণু আছে", "অক্সিজেনের ওজন 2 kg", "এটা দ্বিতীয় মৌল"],
        "সংকেতের পরের ছোট সংখ্যা সেই মৌলের পরমাণু গোনে।"),
)
