"""Class 5 - Commercials (Junior Cadet): truck trips and fuel costs, best value per unit,
gross margin and contribution, supply and demand shifts, toll revenue, procurement and quotes,
negotiation, market research and segments, SWOT, public-private partnerships and fair trade."""
from . import mcq


def _o(r, *alts):
    out = []
    for x in (r, *alts, r + 10, r * 2, r + 1):
        if x not in out and x >= 0:
            out.append(x)
    return out[:4]


def trips(load, cap, what_en, what_bn):
    r = -(-load // cap)
    o = _o(r, load // cap if load % cap else r + 1, cap, r - 1 if r > 1 else r + 2)
    return mcq(f"{load} tonnes of {what_en} must be moved in trucks that carry {cap} tonnes each. How many truck trips are needed?",
               [str(x) for x in o], 0,
               f"{load} ÷ {cap} = {round(load / cap, 1):g}" + (", so round UP: a part-load still needs a whole trip." if load % cap else "."),
               f"{load} টন {what_bn} {cap} টন-ধারী ট্রাকে সরাতে হবে। কতগুলো ট্রাক-যাত্রা লাগবে?",
               [str(x) for x in o],
               f"{load} ÷ {cap} = {round(load / cap, 1):g}" + ("; তাই উপরে আসন্ন করো: আংশিক বোঝাতেও একটা পুরো যাত্রা লাগে।" if load % cap else "।"))


def fuel(km, kmpl, price):
    litres = km // kmpl
    r = litres * price
    o = _o(r, km * price, litres, r // 2)
    return mcq(f"A truck drives {km} km and does {kmpl} km per litre. Diesel costs Rs {price} a litre. What is the fuel cost?",
               [f"Rs {x:,}" for x in o], 0,
               f"Litres = {km} ÷ {kmpl} = {litres}; cost = {litres} x {price} = Rs {r:,}.",
               f"একটা ট্রাক {km} km চলে আর লিটারে {kmpl} km যায়। ডিজেল লিটারপ্রতি {price} টাকা। জ্বালানি-খরচ কত?",
               [f"{x:,} টাকা" for x in o],
               f"লিটার = {km} ÷ {kmpl} = {litres}; খরচ = {litres} x {price} = {r:,} টাকা।")


def best(p1, q1, p2, q2, unit_en, unit_bn, item_en, item_bn):
    u1, u2 = p1 / q1, p2 / q2
    o = [f"Pack A (Rs {u1:g} per {unit_en})", f"Pack B (Rs {u2:g} per {unit_en})", "Both the same", "Cannot compare"]
    o_bn = [f"প্যাক A ({unit_bn}প্রতি {u1:g} টাকা)", f"প্যাক B ({unit_bn}প্রতি {u2:g} টাকা)", "দুটো সমান", "তুলনা করা যায় না"]
    return mcq(f"{item_en}: Pack A is {q1} {unit_en} for Rs {p1:,}; Pack B is {q2} {unit_en} for Rs {p2:,}. Which is better value?",
               o, 0 if u1 < u2 else 1,
               f"Price per {unit_en}: A = {p1:,} ÷ {q1} = {u1:g}; B = {p2:,} ÷ {q2} = {u2:g}. Lower is better value.",
               f"{item_bn}: প্যাক A {q1} {unit_bn} {p1:,} টাকায়; প্যাক B {q2} {unit_bn} {p2:,} টাকায়। কোনটা বেশি সাশ্রয়ী?",
               o_bn,
               f"{unit_bn}প্রতি দাম: A = {p1:,} ÷ {q1} = {u1:g}; B = {p2:,} ÷ {q2} = {u2:g}। কম দামই সাশ্রয়ী।")


def tollrev(vehicles, toll, days):
    r = vehicles * toll * days
    o = _o(r, vehicles * toll, vehicles * days, r // 10)
    return mcq(f"About {vehicles:,} vehicles a day cross a bridge paying Rs {toll} each. What is the toll income in {days} days?",
               [f"Rs {x:,}" for x in o], 0,
               f"{vehicles:,} x {toll} x {days} = Rs {r:,}.",
               f"দিনে প্রায় {vehicles:,}টি গাড়ি {toll} টাকা করে দিয়ে সেতু পার হয়। {days} দিনে টোল-আয় কত?",
               [f"{x:,} টাকা" for x in o],
               f"{vehicles:,} x {toll} x {days} = {r:,} টাকা।")


def gm(price, cost, item_en, item_bn):
    p = (price - cost) * 100 // price
    o = _o(p, (price - cost) * 100 // cost, price - cost, 100 - p)
    return mcq(f"{item_en} sells for Rs {price:,} and costs Rs {cost:,} to make. What is the gross margin as a percent of the price?",
               [f"{x}%" for x in o], 0,
               f"Margin = ({price:,} - {cost:,}) ÷ {price:,} x 100 = {p}%.",
               f"{item_bn} {price:,} টাকায় বিক্রি হয় আর বানাতে {cost:,} টাকা লাগে। দামের শতাংশে মোট মার্জিন কত?",
               [f"{x}%" for x in o],
               f"মার্জিন = ({price:,} - {cost:,}) ÷ {price:,} x 100 = {p}%।")


ITEMS = (
    trips(100, 10, "sand", "বালি"), trips(125, 20, "gravel", "পাথরকুচি"), trips(48, 9, "steel bars", "ইস্পাতের রড"),
    trips(300, 25, "cement", "সিমেন্ট"), trips(70, 15, "bricks", "ইট"), trips(260, 40, "rock fill", "পাথর-ভরাট"),
    fuel(240, 4, 90), fuel(600, 5, 92), fuel(150, 3, 88), fuel(360, 6, 95), fuel(900, 5, 90),
    best(450, 50, 260, 25, "kg", "kg", "Cement", "সিমেন্ট"),
    best(120, 10, 330, 30, "m", "m", "Rope", "দড়ি"),
    best(90, 3, 160, 5, "litres", "লিটার", "Paint", "রং"),
    best(200, 4, 260, 5, "kg", "kg", "Nails", "পেরেক"),
    tollrev(2000, 30, 30), tollrev(5000, 20, 7), tollrev(800, 50, 30), tollrev(12000, 15, 10),
    gm(500, 300, "A bridge model kit", "একটা সেতু-মডেল কিট"), gm(1000, 750, "A safety harness", "একটা নিরাপত্তা-হারনেস"),
    gm(200, 120, "A pack of bolts", "এক প্যাকেট বল্টু"), gm(80, 60, "A cup of masala tea", "এক কাপ মশলা চা"),
    mcq("Why must you round UP when working out truck trips?", ["A partly full truck still needs a whole trip", "Rounding down is illegal", "Trucks prefer even numbers", "You should round down"], 0,
        "45 tonnes in 10-tonne trucks = 4.5 -> 5 trips.",
        "ট্রাক-যাত্রা হিসাবের সময় উপরে আসন্ন করতে হয় কেন?", ["আংশিক ভরা ট্রাকেরও একটা পুরো যাত্রা লাগে", "নিচে আসন্ন করা বেআইনি", "ট্রাক জোড় সংখ্যা পছন্দ করে", "নিচে আসন্ন করা উচিত"],
        "10 টনের ট্রাকে 45 টন = 4.5 -> 5 যাত্রা।"),
    mcq("What is 'capacity utilisation' for a truck fleet?", ["How much of the available carrying space is actually used", "The colour of the trucks", "The number of drivers", "Fuel type"], 0,
        "Half-empty trucks waste money; good planning fills them.",
        "ট্রাক-বহরের 'ধারণক্ষমতার ব্যবহার' কী?", ["উপলব্ধ বহনক্ষমতার কতটা সত্যিই ব্যবহার হয়", "ট্রাকের রং", "চালকের সংখ্যা", "জ্বালানির ধরন"],
        "অর্ধেক খালি ট্রাক টাকা নষ্ট করে; ভালো পরিকল্পনা তাদের ভরে।"),
    mcq("A 20-tonne truck carries 15 tonnes. What is its capacity utilisation?", ["75%", "25%", "15%", "133%"], 0,
        "15 ÷ 20 x 100 = 75%.",
        "20 টনের একটা ট্রাক 15 টন বয়। ধারণক্ষমতার ব্যবহার কত?", ["75%", "25%", "15%", "133%"],
        "15 ÷ 20 x 100 = 75%।"),
    mcq("What is 'gross margin'?", ["Sales minus the direct cost of the goods sold", "Total profit after everything", "The shop's rent", "A tax"], 0,
        "Overheads come out of gross margin to leave net profit.",
        "'মোট মার্জিন' কী?", ["বিক্রি বিয়োগ বিক্রীত মালের প্রত্যক্ষ খরচ", "সব কিছুর পরে মোট লাভ", "দোকানের ভাড়া", "কর"],
        "মোট মার্জিন থেকে উপরি খরচ বাদ দিলে নিট লাভ থাকে।"),
    mcq("What is 'net profit'?", ["What is left after ALL costs, including overheads and tax", "Sales only", "Gross margin before costs", "A loan"], 0,
        "Net profit is the true bottom line.",
        "'নিট লাভ' কী?", ["উপরি খরচ আর করসহ সব খরচের পরে যা বাকি থাকে", "শুধু বিক্রি", "খরচের আগের মোট মার্জিন", "ঋণ"],
        "নিট লাভই আসল চূড়ান্ত হিসাব।"),
    mcq("A shop has sales of Rs 1,00,000, goods cost Rs 60,000 and overheads Rs 25,000. What is the net profit?", ["Rs 15,000", "Rs 40,000", "Rs 75,000", "Rs 85,000"], 0,
        "1,00,000 - 60,000 - 25,000 = 15,000.",
        "একটা দোকানের বিক্রি 1,00,000 টাকা, মালের খরচ 60,000 আর উপরি খরচ 25,000। নিট লাভ কত?", ["15,000 টাকা", "40,000 টাকা", "75,000 টাকা", "85,000 টাকা"],
        "1,00,000 - 60,000 - 25,000 = 15,000।"),
    mcq("What is 'contribution' per unit?", ["Selling price minus variable cost per unit", "Price minus rent", "Total sales", "A donation"], 0,
        "Each unit's contribution helps pay fixed costs, then adds profit.",
        "এককপ্রতি 'অবদান' (কন্ট্রিবিউশন) কী?", ["বিক্রয়মূল্য বিয়োগ এককপ্রতি পরিবর্তনশীল খরচ", "দাম বিয়োগ ভাড়া", "মোট বিক্রি", "দান"],
        "প্রতি এককের অবদান স্থির খরচ মেটায়, তারপর লাভ যোগ করে।"),
    mcq("If demand for cement rises sharply but supply stays the same, what usually happens to its price?", ["It rises", "It falls", "It stays exactly the same", "Cement becomes free"], 0,
        "More buyers chasing the same goods push prices up.",
        "সিমেন্টের চাহিদা হঠাৎ অনেক বাড়লে কিন্তু জোগান একই থাকলে দামের সাধারণত কী হয়?", ["বাড়ে", "কমে", "একদম একই থাকে", "সিমেন্ট বিনামূল্যে হয়"],
        "একই মালের পেছনে বেশি ক্রেতা দাম বাড়ায়।"),
    mcq("A bumper mango harvest floods the market. What usually happens to mango prices?", ["They fall", "They rise", "They stay the same", "Mangoes disappear"], 0,
        "More supply with the same demand lowers prices - unless farmers can reach bigger markets.",
        "আমের বাম্পার ফলনে বাজার ভরে গেল। আমের দামের সাধারণত কী হয়?", ["কমে", "বাড়ে", "একই থাকে", "আম উধাও হয়"],
        "চাহিদা একই রেখে জোগান বাড়লে দাম কমে - যদি না চাষিরা বড় বাজারে পৌঁছাতে পারেন।"),
    mcq("How can a new bridge help farmers when local prices crash at harvest?", ["They can sell to distant markets where prices are better", "Bridges raise local prices by law", "They cannot", "Bridges store mangoes"], 0,
        "Market access smooths out local gluts.",
        "ফসলের সময় স্থানীয় দাম পড়ে গেলে নতুন সেতু চাষিদের কীভাবে সাহায্য করে?", ["দূরের ভালো দামের বাজারে বেচতে পারেন", "আইনে সেতু স্থানীয় দাম বাড়ায়", "পারে না", "সেতু আম জমিয়ে রাখে"],
        "বাজারে পৌঁছানো স্থানীয় অতিরিক্ত জোগান সামলায়।"),
    mcq("What is 'price elasticity' about?", ["How much demand changes when price changes", "How stretchy a product is", "Rubber prices only", "Tax rates"], 0,
        "Salt sales barely change with price; luxury items change a lot.",
        "'দামের স্থিতিস্থাপকতা' কী নিয়ে?", ["দাম বদলালে চাহিদা কতটা বদলায়", "পণ্য কতটা টানা যায়", "শুধু রবারের দাম", "করের হার"],
        "দামের সঙ্গে লবণের বিক্রি প্রায় বদলায় না; বিলাসদ্রব্যে অনেক বদলায়।"),
    mcq("Why might raising a bridge toll a lot actually reduce total toll income?", ["Many drivers switch to other routes or stop travelling", "Tolls always increase income", "Cars become cheaper", "Bridges get shorter"], 0,
        "If demand is elastic, higher prices can mean lower revenue.",
        "সেতুর টোল অনেক বাড়ালে মোট টোল-আয় আসলে কমতে পারে কেন?", ["অনেক চালক অন্য পথে যান বা যাতায়াত থামান", "টোল সবসময় আয় বাড়ায়", "গাড়ি সস্তা হয়", "সেতু ছোট হয়"],
        "চাহিদা স্থিতিস্থাপক হলে বেশি দামে কম আয় হতে পারে।"),
    mcq("What is 'procurement'?", ["Buying the goods and services a project needs", "Selling to customers", "Hiring a lawyer only", "Painting a bridge"], 0,
        "Good procurement gets the right quality at a fair price, on time.",
        "'সংগ্রহ' (প্রোকিওরমেন্ট) কী?", ["প্রকল্পের দরকারি মাল আর পরিষেবা কেনা", "খদ্দেরকে বেচা", "শুধু উকিল নিয়োগ", "সেতু রং করা"],
        "ভালো সংগ্রহে সঠিক মান ন্যায্য দামে সময়মতো মেলে।"),
    mcq("Why do public projects usually require at least three quotes?", ["To compare prices fairly and prevent favouritism", "Three is a lucky number", "To slow down work", "Quotes are free gifts"], 0,
        "Competition protects public money.",
        "সরকারি প্রকল্পে সাধারণত অন্তত তিনটি দরপ্রস্তাব লাগে কেন?", ["ন্যায্যভাবে দাম তুলনা আর পক্ষপাত আটকাতে", "তিন শুভ সংখ্যা", "কাজ ধীর করতে", "দরপ্রস্তাব বিনামূল্যের উপহার"],
        "প্রতিযোগিতা জনগণের টাকা রক্ষা করে।"),
    mcq("What is 'lead time' in purchasing?", ["The time between ordering and receiving goods", "Time to melt lead", "The time a meeting starts", "A pencil's life"], 0,
        "Long lead times (like special steel) must be ordered early.",
        "কেনাকাটায় 'অগ্রিম সময়' (লিড টাইম) কী?", ["অর্ডার আর মাল পাওয়ার মাঝের সময়", "সিসা গলানোর সময়", "মিটিং শুরুর সময়", "পেনসিলের আয়ু"],
        "লম্বা অগ্রিম সময়ের জিনিস (যেমন বিশেষ ইস্পাত) আগে অর্ডার করতে হয়।"),
    mcq("What is good 'negotiation' in business?", ["Reaching a fair deal both sides can accept", "Shouting until you win", "Never agreeing", "Lying about prices"], 0,
        "Win-win deals build long relationships with suppliers.",
        "ব্যবসায় ভালো 'দরকষাকষি' কী?", ["দুই পক্ষই মানতে পারে এমন ন্যায্য চুক্তিতে পৌঁছানো", "জেতা পর্যন্ত চেঁচানো", "কখনো রাজি না হওয়া", "দাম নিয়ে মিথ্যা বলা"],
        "দুই পক্ষের লাভের চুক্তি সরবরাহকারীদের সঙ্গে দীর্ঘ সম্পর্ক গড়ে।"),
    mcq("A supplier offers 5% off if you pay within 10 days instead of 30. Why might that be worth it?", ["You save 5% of the bill for paying a little earlier", "It costs more", "Paying early is illegal", "There is no benefit"], 0,
        "Early-payment discounts can be very good value if you have the cash.",
        "একজন সরবরাহকারী 30-এর বদলে 10 দিনে দাম দিলে 5% ছাড় দেন। কেন তা লাভজনক হতে পারে?", ["একটু আগে দাম দিয়ে বিলের 5% বাঁচে", "খরচ বেশি", "আগে দেওয়া বেআইনি", "কোনো লাভ নেই"],
        "নগদ থাকলে আগাম-পেমেন্টের ছাড় খুব লাভজনক হতে পারে।"),
    mcq("What is 'market segmentation'?", ["Dividing customers into groups with similar needs", "Cutting a market in half with a fence", "Closing a market", "A tax on markets"], 0,
        "Bridge builders serve segments like railways, highways and villages differently.",
        "'বাজার-বিভাজন' কী?", ["একই রকম প্রয়োজনের খদ্দেরদের দলে ভাগ করা", "বেড়া দিয়ে বাজার দুই ভাগ", "বাজার বন্ধ", "বাজারে কর"],
        "সেতু-নির্মাতারা রেল, মহাসড়ক আর গ্রামের মতো অংশকে আলাদাভাবে পরিষেবা দেন।"),
    mcq("What is 'primary market research'?", ["Collecting new information yourself, like surveys and interviews", "Reading old reports only", "Guessing", "Copying a rival"], 0,
        "Secondary research uses information others already collected.",
        "'প্রাথমিক বাজার-গবেষণা' কী?", ["নিজে নতুন তথ্য সংগ্রহ, যেমন সমীক্ষা আর সাক্ষাৎকার", "শুধু পুরোনো রিপোর্ট পড়া", "আন্দাজ", "প্রতিযোগীকে নকল"],
        "মাধ্যমিক গবেষণা অন্যদের আগেই সংগ্রহ করা তথ্য ব্যবহার করে।"),
    mcq("A traffic count finds 3,000 people a day wait for a ferry. Why is this useful to bridge planners?", ["It shows demand and helps estimate toll income and benefits", "Ferries are illegal", "To count fish", "It is not useful"], 0,
        "Good data justifies investment.",
        "একটা যানবাহন-গণনায় দেখা গেল দিনে 3,000 জন খেয়ার জন্য অপেক্ষা করেন। সেতু-পরিকল্পকদের কাছে এটা কাজের কেন?", ["চাহিদা দেখায় আর টোল-আয় আর উপকারের আন্দাজে সাহায্য করে", "খেয়া বেআইনি", "মাছ গুনতে", "কাজের নয়"],
        "ভালো তথ্য বিনিয়োগের যুক্তি দেয়।"),
    mcq("What does a SWOT analysis list?", ["Strengths, Weaknesses, Opportunities and Threats", "Sales, Wages, Orders and Tax", "Steel, Wood, Oil and Tar", "Shops, Warehouses, Offices and Trucks"], 0,
        "A simple tool to plan a business or project.",
        "সোয়াট (SWOT) বিশ্লেষণে কী তালিকা হয়?", ["শক্তি, দুর্বলতা, সুযোগ আর হুমকি", "বিক্রি, মজুরি, অর্ডার আর কর", "ইস্পাত, কাঠ, তেল আর আলকাতরা", "দোকান, গুদাম, অফিস আর ট্রাক"],
        "ব্যবসা বা প্রকল্প পরিকল্পনার একটা সহজ হাতিয়ার।"),
    mcq("In a SWOT for a bridge firm, 'a new government highway plan' is most likely a...", ["Opportunity", "Weakness", "Strength", "Threat"], 0,
        "Opportunities are outside chances the firm can use.",
        "একটা সেতু-সংস্থার সোয়াটে 'সরকারের নতুন মহাসড়ক-পরিকল্পনা' সম্ভবত একটা...", ["সুযোগ", "দুর্বলতা", "শক্তি", "হুমকি"],
        "সুযোগ হলো বাইরের সম্ভাবনা, যা সংস্থা কাজে লাগাতে পারে।"),
    mcq("In a SWOT, 'rising steel prices' would usually be a...", ["Threat", "Strength", "Opportunity", "Weakness"], 0,
        "Threats are outside risks that could hurt the business.",
        "সোয়াটে 'ইস্পাতের দাম বৃদ্ধি' সাধারণত একটা...", ["হুমকি", "শক্তি", "সুযোগ", "দুর্বলতা"],
        "হুমকি হলো বাইরের ঝুঁকি, যা ব্যবসার ক্ষতি করতে পারে।"),
    mcq("In a SWOT, 'highly skilled welders on the team' is a...", ["Strength", "Threat", "Weakness", "Opportunity"], 0,
        "Strengths are internal advantages.",
        "সোয়াটে 'দলে অত্যন্ত দক্ষ ঝালাইকারী' একটা...", ["শক্তি", "হুমকি", "দুর্বলতা", "সুযোগ"],
        "শক্তি হলো ভেতরের সুবিধা।"),
    mcq("What is a 'public-private partnership' (PPP) for a bridge?", ["Government and a private company share the cost, risk and rewards", "A bridge only for private cars", "A free bridge", "A secret deal"], 0,
        "The company may build and run the bridge, earning tolls for some years.",
        "সেতুর জন্য 'সরকারি-বেসরকারি অংশীদারি' (পিপিপি) কী?", ["সরকার আর একটা বেসরকারি কোম্পানি খরচ, ঝুঁকি আর লাভ ভাগ করে", "শুধু ব্যক্তিগত গাড়ির সেতু", "বিনামূল্যের সেতু", "গোপন চুক্তি"],
        "কোম্পানি সেতু বানিয়ে কয়েক বছর চালিয়ে টোল আয় করতে পারে।"),
    mcq("What does 'BOT' mean in infrastructure?", ["Build, Operate, Transfer", "Buy One Today", "Bridge Over Traffic", "Bank Owned Toll"], 0,
        "A firm builds, runs it for years to earn back costs, then hands it to the government.",
        "পরিকাঠামোয় 'বিওটি' মানে কী?", ["নির্মাণ, পরিচালনা, হস্তান্তর", "আজই একটা কেনো", "যানবাহনের উপর সেতু", "ব্যাংকের মালিকানার টোল"],
        "সংস্থা বানায়, খরচ তুলতে বছরের পর বছর চালায়, তারপর সরকারকে হস্তান্তর করে।"),
    mcq("What is 'fair trade'?", ["Trading so producers get a fair price and decent working conditions", "Trading at a funfair", "Free goods", "Trading only at night"], 0,
        "Fair trade labels help shoppers support ethical producers.",
        "'ন্যায্য বাণিজ্য' কী?", ["উৎপাদক যাতে ন্যায্য দাম আর ভালো কাজের পরিবেশ পান এমন বাণিজ্য", "মেলায় বাণিজ্য", "বিনামূল্যের মাল", "শুধু রাতে বাণিজ্য"],
        "ন্যায্য বাণিজ্যের লেবেল ক্রেতাদের নৈতিক উৎপাদকদের সমর্থন করতে সাহায্য করে।"),
    mcq("Why should a building firm check that its suppliers do not use child labour?", ["It is illegal and wrong, and harms children's education and health", "Children are cheaper so it is fine", "It does not matter", "Suppliers never do"], 0,
        "Responsible firms audit their supply chains.",
        "একটা নির্মাণ-সংস্থার যাচাই করা উচিত কেন যে সরবরাহকারীরা শিশুশ্রম ব্যবহার করে না?", ["এটা বেআইনি আর অন্যায়, আর শিশুদের পড়াশোনা ও স্বাস্থ্যের ক্ষতি করে", "শিশুরা সস্তা তাই ঠিক আছে", "কিছু যায় আসে না", "সরবরাহকারীরা কখনো করে না"],
        "দায়িত্বশীল সংস্থা তাদের সরবরাহ শৃঙ্খল পরীক্ষা করে।"),
    mcq("What is 'just-in-time' delivery?", ["Goods arrive exactly when needed, so little stock is stored", "Deliveries always late", "Storing a year's stock", "Delivering at midnight only"], 0,
        "It saves storage space but needs very reliable transport.",
        "'ঠিক-সময়ে' (জাস্ট-ইন-টাইম) ডেলিভারি কী?", ["মাল ঠিক দরকারের সময় আসে, তাই কম মজুত রাখা হয়", "ডেলিভারি সবসময় দেরিতে", "এক বছরের মজুত রাখা", "শুধু মাঝরাতে পৌঁছানো"],
        "জায়গা বাঁচায়, তবে খুব নির্ভরযোগ্য পরিবহন লাগে।"),
    mcq("Why is just-in-time risky for a bridge site in the monsoon?", ["Floods may block roads, so materials arrive late and work stops", "Rain makes steel cheaper", "Monsoon is always dry", "It is never risky"], 0,
        "Plan buffers when transport is unreliable.",
        "বর্ষায় সেতু-নির্মাণস্থলে ঠিক-সময়ের ডেলিভারি ঝুঁকির কেন?", ["বন্যায় রাস্তা আটকাতে পারে, উপাদান দেরিতে আসে আর কাজ থামে", "বৃষ্টিতে ইস্পাত সস্তা", "বর্ষা সবসময় শুকনো", "কখনো ঝুঁকির নয়"],
        "পরিবহন অনির্ভরযোগ্য হলে বাড়তি মজুতের পরিকল্পনা করো।"),
    mcq("A courier must choose: road (2 days, Rs 5,000) or air (1 day, Rs 15,000). When is air worth it?", ["When a one-day delay would cost more than Rs 10,000", "Always", "Never", "Only on Sundays"], 0,
        "Compare the extra cost with the cost of waiting.",
        "একটা কুরিয়ারকে বাছতে হবে: সড়ক (2 দিন, 5,000 টাকা) না আকাশপথ (1 দিন, 15,000 টাকা)। কখন আকাশপথ লাভজনক?", ["যখন এক দিনের দেরির ক্ষতি 10,000 টাকার বেশি", "সবসময়", "কখনো না", "শুধু রবিবার"],
        "বাড়তি খরচকে অপেক্ষার ক্ষতির সঙ্গে তুলনা করো।"),
    mcq("What is a 'bill of lading'?", ["A document listing goods being shipped, acting as a receipt", "A restaurant bill", "A tax form", "A toll ticket"], 0,
        "It travels with cargo from seller to buyer.",
        "'বিল অফ লেডিং' কী?", ["জাহাজে পাঠানো মালের তালিকাসহ নথি, যা রসিদের কাজ করে", "রেস্তোরাঁর বিল", "করের ফর্ম", "টোলের টিকিট"],
        "এটা বিক্রেতা থেকে ক্রেতা পর্যন্ত মালের সঙ্গে যায়।"),
    mcq("What is 'customs' at a border or port?", ["The office that checks imports and collects import duties", "Local traditions only", "A shop", "A bank"], 0,
        "Imported bridge parts must clear customs.",
        "সীমান্ত বা বন্দরে 'শুল্ক-দপ্তর' (কাস্টমস) কী?", ["যে দপ্তর আমদানি পরীক্ষা করে আর আমদানি-শুল্ক নেয়", "শুধু স্থানীয় প্রথা", "দোকান", "ব্যাংক"],
        "আমদানি করা সেতুর অংশকে শুল্ক-ছাড়পত্র নিতে হয়।"),
    mcq("What is 'local sourcing'?", ["Buying materials from nearby suppliers", "Buying only from abroad", "Making everything yourself", "Not buying anything"], 0,
        "It cuts transport costs, supports local jobs and lowers emissions.",
        "'স্থানীয় সংগ্রহ' কী?", ["কাছের সরবরাহকারীদের থেকে উপাদান কেনা", "শুধু বিদেশ থেকে কেনা", "সব নিজে বানানো", "কিছুই না কেনা"],
        "এতে পরিবহন খরচ কমে, স্থানীয় কাজ বাড়ে আর দূষণ কমে।"),
    mcq("What is a 'warranty claim'?", ["Asking the seller to repair or replace a faulty item under its warranty", "A new sale", "A tax refund", "A loan"], 0,
        "Keep receipts and warranty cards safe.",
        "'ওয়ারেন্টি-দাবি' কী?", ["ওয়ারেন্টির আওতায় ত্রুটিপূর্ণ জিনিস সারানো বা বদলাতে বিক্রেতাকে বলা", "নতুন বিক্রি", "করের ফেরত", "ঋণ"],
        "রসিদ আর ওয়ারেন্টি-কার্ড নিরাপদে রাখো।"),
    mcq("What is 'brand loyalty' worth to a cement maker?", ["Builders keep choosing it, giving steady sales", "Nothing", "It lowers quality", "It raises tax"], 0,
        "Consistent quality builds loyal customers.",
        "সিমেন্ট-নির্মাতার কাছে 'ব্র্যান্ড-আনুগত্যের' মূল্য কী?", ["নির্মাতারা বারবার তা বাছেন, স্থির বিক্রি হয়", "কিছুই না", "মান কমায়", "কর বাড়ায়"],
        "ধারাবাহিক মান অনুগত খদ্দের গড়ে।"),
    mcq("What is 'cross-selling'?", ["Offering customers related products, like bolts with steel beams", "Selling to angry customers", "Selling across a river only", "Refusing sales"], 0,
        "It raises sales and helps customers get everything they need.",
        "'আনুষঙ্গিক বিক্রি' (ক্রস-সেলিং) কী?", ["খদ্দেরকে সম্পর্কিত পণ্য দেওয়া, যেমন ইস্পাতের বিমের সঙ্গে বল্টু", "রাগী খদ্দেরকে বেচা", "শুধু নদীর ওপারে বেচা", "বিক্রি প্রত্যাখ্যান"],
        "বিক্রি বাড়ায় আর খদ্দেরকে দরকারি সব পেতে সাহায্য করে।"),
    mcq("What is a 'sales target'?", ["A goal for how much to sell in a period", "A dartboard", "A customer's address", "A tax rate"], 0,
        "Targets help teams plan and measure progress.",
        "'বিক্রয়-লক্ষ্য' কী?", ["নির্দিষ্ট সময়ে কতটা বেচতে হবে তার লক্ষ্য", "ডার্টবোর্ড", "খদ্দেরের ঠিকানা", "করের হার"],
        "লক্ষ্য দলকে পরিকল্পনা আর অগ্রগতি মাপতে সাহায্য করে।"),
    mcq("A shop's target is Rs 60,000 this month. After 20 days it has sold Rs 45,000. What is still needed?", ["Rs 15,000", "Rs 45,000", "Rs 105,000", "Rs 25,000"], 0,
        "60,000 - 45,000 = 15,000.",
        "একটা দোকানের এ মাসের লক্ষ্য 60,000 টাকা। 20 দিনে বিক্রি 45,000 টাকা। আর কত লাগবে?", ["15,000 টাকা", "45,000 টাকা", "1,05,000 টাকা", "25,000 টাকা"],
        "60,000 - 45,000 = 15,000।"),
    mcq("What is 'seasonality' in sales?", ["Regular rises and falls in demand at certain times of year", "Selling seasoning", "A one-off sale", "Weather forecasting"], 0,
        "Construction often slows in heavy monsoon months.",
        "বিক্রিতে 'মরসুমি প্রভাব' কী?", ["বছরের নির্দিষ্ট সময়ে চাহিদার নিয়মিত ওঠানামা", "মশলা বেচা", "একবারের সেল", "আবহাওয়ার পূর্বাভাস"],
        "প্রবল বর্ষার মাসে নির্মাণ প্রায়ই ধীর হয়।"),
    mcq("Why might a construction firm plan most concrete work for the dry season?", ["Heavy rain can spoil fresh concrete and flood sites", "Concrete only exists in winter", "Workers dislike sunshine", "No reason"], 0,
        "Planning around seasons saves money and protects quality.",
        "একটা নির্মাণ-সংস্থা বেশিরভাগ কংক্রিটের কাজ শুকনো মরসুমে রাখতে পারে কেন?", ["ভারী বৃষ্টি তাজা কংক্রিট নষ্ট আর নির্মাণস্থল ডুবিয়ে দিতে পারে", "কংক্রিট শুধু শীতে থাকে", "কর্মীরা রোদ অপছন্দ করেন", "কোনো কারণ নেই"],
        "মরসুম মেনে পরিকল্পনা টাকা বাঁচায় আর মান রক্ষা করে।"),
    mcq("What is 'customer lifetime value'?", ["The total a customer is likely to spend with a business over time", "A customer's age", "One purchase only", "The price of a product"], 0,
        "Keeping a happy customer is often cheaper than finding a new one.",
        "'খদ্দেরের আজীবন মূল্য' কী?", ["সময়ের সঙ্গে একজন খদ্দের একটা ব্যবসায় মোট কত খরচ করতে পারেন", "খদ্দেরের বয়স", "শুধু একটা কেনা", "পণ্যের দাম"],
        "খুশি খদ্দের ধরে রাখা প্রায়ই নতুন খোঁজার চেয়ে সস্তা।"),
    mcq("A customer spends Rs 2,000 a month at a hardware shop for 5 years. What is their total spend?", ["Rs 1,20,000", "Rs 10,000", "Rs 24,000", "Rs 2,000"], 0,
        "2,000 x 12 x 5 = 1,20,000.",
        "একজন খদ্দের একটা হার্ডওয়্যারের দোকানে 5 বছর মাসে 2,000 টাকা খরচ করেন। মোট খরচ কত?", ["1,20,000 টাকা", "10,000 টাকা", "24,000 টাকা", "2,000 টাকা"],
        "2,000 x 12 x 5 = 1,20,000।"),
    mcq("Why do big projects publish progress photos and updates?", ["To keep the public, funders and users informed and trusting", "To waste time", "Photos are required for steel", "No reason"], 0,
        "Transparency builds goodwill and accountability.",
        "বড় প্রকল্প অগ্রগতির ছবি আর খবর প্রকাশ করে কেন?", ["জনগণ, অর্থদাতা আর ব্যবহারকারীদের জানাতে আর আস্থা রাখতে", "সময় নষ্ট করতে", "ইস্পাতের জন্য ছবি বাধ্যতামূলক", "কোনো কারণ নেই"],
        "স্বচ্ছতা সদিচ্ছা আর জবাবদিহি গড়ে।"),
    mcq("What does 'scaling up' a business mean?", ["Growing to serve many more customers efficiently", "Weighing products", "Climbing a ladder", "Shrinking"], 0,
        "A firm that builds one footbridge a year might scale up to ten.",
        "ব্যবসা 'বড় করা' (স্কেলিং আপ) মানে কী?", ["দক্ষতার সঙ্গে আরও অনেক খদ্দেরকে পরিষেবা দিতে বাড়া", "পণ্য ওজন করা", "মই চড়া", "ছোট হওয়া"],
        "বছরে একটা হাঁটার সেতু বানানো সংস্থা দশটায় বাড়তে পারে।"),
    mcq("What is 'outsourcing'?", ["Paying another firm to do part of your work", "Working outdoors", "Selling abroad only", "Closing a factory"], 0,
        "A builder might outsource steel fabrication to a specialist.",
        "'বহিঃসম্পদ' (আউটসোর্সিং) কী?", ["নিজের কাজের অংশ অন্য সংস্থাকে টাকা দিয়ে করানো", "বাইরে কাজ করা", "শুধু বিদেশে বেচা", "কারখানা বন্ধ"],
        "একজন নির্মাতা ইস্পাত-কাঠামো তৈরির কাজ বিশেষজ্ঞ সংস্থাকে দিতে পারেন।"),
    mcq("What is a 'kickback'?", ["A secret illegal payment for giving someone business", "A football move", "A legal discount", "A refund"], 0,
        "Kickbacks are corruption - they raise costs and can lead to unsafe work.",
        "'গোপন ঘুষ' (কিকব্যাক) কী?", ["কাউকে কাজ পাইয়ে দেওয়ার জন্য গোপন বেআইনি টাকা", "ফুটবলের কৌশল", "আইনি ছাড়", "টাকা ফেরত"],
        "এটা দুর্নীতি - খরচ বাড়ায় আর অনিরাপদ কাজের দিকে নিতে পারে।"),
    trips(90, 12, "timber", "কাঠ"), trips(200, 30, "precast slabs", "আগে-ঢালাই স্ল্যাব"),
    trips(55, 5, "water pipes", "জলের পাইপ"), trips(400, 35, "soil", "মাটি"),
    fuel(480, 4, 94), fuel(200, 5, 91), fuel(750, 6, 96), fuel(120, 4, 89),
    best(300, 20, 700, 50, "kg", "kg", "Lime", "চুন"),
    best(1500, 100, 800, 50, "m", "m", "Steel cable", "ইস্পাতের তার"),
    best(48, 2, 90, 4, "kg", "kg", "Washers", "ওয়াশার"),
    tollrev(3000, 25, 30), tollrev(1500, 40, 7), tollrev(600, 60, 30),
    gm(1200, 900, "A pair of work boots", "এক জোড়া কাজের বুট"), gm(50, 30, "A sandwich", "একটা স্যান্ডউইচ"),
    gm(400, 260, "A tool kit", "একটা যন্ত্রের বাক্স"), gm(2500, 2000, "A welding mask", "একটা ঝালাই-মুখোশ"),
    mcq("What is 'turnover' in a business?", ["Total sales in a period", "Profit only", "Workers leaving", "Flipping pancakes"], 0,
        "A firm with Rs 1 crore turnover still needs to check its costs to know its profit.",
        "ব্যবসায় 'লেনদেনের পরিমাণ' (টার্নওভার) কী?", ["নির্দিষ্ট সময়ে মোট বিক্রি", "শুধু লাভ", "কর্মীদের চলে যাওয়া", "প্যানকেক উল্টানো"],
        "1 কোটি টাকার টার্নওভারের সংস্থাকেও লাভ জানতে খরচ দেখতে হয়।"),
    mcq("What is 'stock turnover'?", ["How many times stock is sold and replaced in a period", "Turning boxes upside down", "Stealing stock", "The value of shares"], 0,
        "Fast turnover means goods do not sit around tying up cash.",
        "'মজুতের আবর্তন' কী?", ["নির্দিষ্ট সময়ে মজুত কতবার বিক্রি হয়ে আবার ভরে", "বাক্স উল্টানো", "মজুত চুরি", "শেয়ারের দাম"],
        "দ্রুত আবর্তনে মাল পড়ে থেকে টাকা আটকায় না।"),
    mcq("Why do large construction firms have 'safety officers'?", ["To prevent accidents, which cost lives, delays and money", "To slow work", "To count bricks", "They do not"], 0,
        "Good safety records also help win contracts.",
        "বড় নির্মাণ-সংস্থায় 'নিরাপত্তা আধিকারিক' থাকে কেন?", ["দুর্ঘটনা ঠেকাতে, যাতে প্রাণ, সময় আর টাকা হারায়", "কাজ ধীর করতে", "ইট গুনতে", "থাকে না"],
        "ভালো নিরাপত্তা-রেকর্ড চুক্তি জিততেও সাহায্য করে।"),
    mcq("What does 'quality assurance' (QA) do on a bridge project?", ["Sets up checks so work meets standards every time", "Paints the bridge", "Sells tickets", "Hires drivers"], 0,
        "QA prevents problems; quality control finds them.",
        "সেতু-প্রকল্পে 'মান-নিশ্চিতকরণ' (কিউএ) কী করে?", ["কাজ যাতে প্রতিবার মান মেনে হয় তার পরীক্ষা-ব্যবস্থা তৈরি করে", "সেতু রং করে", "টিকিট বেচে", "চালক নিয়োগ করে"],
        "কিউএ সমস্যা ঠেকায়; মান-নিয়ন্ত্রণ সমস্যা খুঁজে বের করে।"),
    mcq("What is a 'unique customer need' a footbridge firm might meet in hilly villages?", ["Light parts that can be carried by hand where trucks cannot reach", "Gold railings", "Ten-lane decks", "Underwater tunnels"], 0,
        "Designing for the customer's real situation wins business.",
        "পাহাড়ি গ্রামে একটা হাঁটার সেতুর সংস্থা কোন বিশেষ খদ্দের-প্রয়োজন মেটাতে পারে?", ["ট্রাক যেখানে পৌঁছায় না সেখানে হাতে বয়ে নেওয়ার মতো হালকা অংশ", "সোনার রেলিং", "দশ লেনের পাটাতন", "জলের নিচের সুড়ঙ্গ"],
        "খদ্দেরের আসল পরিস্থিতি মেনে নকশা করলে কাজ মেলে।"),
    mcq("A transport firm charges Rs 3,000 per trip plus Rs 20 per km. What does a 50 km trip cost?", ["Rs 4,000", "Rs 3,020", "Rs 1,000", "Rs 3,050"], 0,
        "3,000 + 20 x 50 = 4,000.",
        "একটা পরিবহণ-সংস্থা প্রতি যাত্রায় 3,000 টাকা আর km-প্রতি 20 টাকা নেয়। 50 km যাত্রায় খরচ কত?", ["4,000 টাকা", "3,020 টাকা", "1,000 টাকা", "3,050 টাকা"],
        "3,000 + 20 x 50 = 4,000।"),
    mcq("Rail costs Rs 1.5 per tonne-km and road Rs 4 per tonne-km. How much is saved moving 100 tonnes 200 km by rail?", ["Rs 50,000", "Rs 30,000", "Rs 80,000", "Rs 2,500"], 0,
        "Road: 100 x 200 x 4 = 80,000; rail: 100 x 200 x 1.5 = 30,000; saving 50,000.",
        "রেলে টন-km-প্রতি 1.5 টাকা আর সড়কে 4 টাকা। 100 টন 200 km রেলে নিলে কত বাঁচে?", ["50,000 টাকা", "30,000 টাকা", "80,000 টাকা", "2,500 টাকা"],
        "সড়ক: 100 x 200 x 4 = 80,000; রেল: 100 x 200 x 1.5 = 30,000; সাশ্রয় 50,000।"),
    mcq("What is a 'freight forwarder'?", ["A company that arranges shipping and paperwork for others' goods", "A fast truck", "A ship's captain", "A post office box"], 0,
        "They book space on ships, trains and trucks and handle customs papers.",
        "'মাল-প্রেরক এজেন্ট' (ফ্রেইট ফরোয়ার্ডার) কী?", ["যে সংস্থা অন্যের মালের পরিবহন আর কাগজপত্রের ব্যবস্থা করে", "দ্রুতগামী ট্রাক", "জাহাজের ক্যাপ্টেন", "ডাকঘরের বাক্স"],
        "তারা জাহাজ, ট্রেন আর ট্রাকে জায়গা বুক করে আর শুল্কের কাগজ সামলায়।"),
    mcq("What is 'demurrage'?", ["A fee charged when cargo or containers are kept too long at a port", "A ship's horn", "A type of crane", "A discount"], 0,
        "Delays in collecting goods cost money every day.",
        "'বিলম্ব-মাশুল' (ডেমারেজ) কী?", ["বন্দরে মাল বা কনটেনার বেশি দিন রাখলে যে ফি লাগে", "জাহাজের ভেঁপু", "এক রকম ক্রেন", "ছাড়"],
        "মাল তুলতে দেরি হলে প্রতিদিন টাকা লাগে।"),
    mcq("Port demurrage is Rs 2,500 per container per day. Two containers wait 4 extra days. Cost?", ["Rs 20,000", "Rs 10,000", "Rs 5,000", "Rs 2,508"], 0,
        "2,500 x 2 x 4 = 20,000.",
        "বন্দরে কনটেনারপ্রতি দিনে 2,500 টাকা বিলম্ব-মাশুল। দুটো কনটেনার 4 দিন বেশি থাকল। খরচ কত?", ["20,000 টাকা", "10,000 টাকা", "5,000 টাকা", "2,508 টাকা"],
        "2,500 x 2 x 4 = 20,000।"),
    mcq("Why do shops place everyday items like rice and dal at the back?", ["Customers walk past other products and may buy more", "Rice is heavy", "It is required by law", "No reason"], 0,
        "Store layout is part of marketing.",
        "দোকান চাল-ডালের মতো রোজকার জিনিস পেছনে রাখে কেন?", ["খদ্দেরেরা অন্য পণ্যের পাশ দিয়ে হাঁটেন আর বেশি কিনতে পারেন", "চাল ভারী", "আইনে বাধ্যতামূলক", "কোনো কারণ নেই"],
        "দোকানের সাজসজ্জাও বিপণনের অংশ।"),
    mcq("Which is a fair way to price safety helmets for village workers?", ["Cover costs with a small margin, perhaps helped by a grant or sponsor", "Charge as much as possible", "Refuse to sell", "Sell fake helmets cheaply"], 0,
        "Affordable safety saves lives - business can do good and stay viable.",
        "গ্রামের কর্মীদের জন্য নিরাপত্তা-হেলমেটের ন্যায্য দাম ঠিক করার উপায় কোনটা?", ["ছোট মার্জিনে খরচ মেটানো, হয়তো অনুদান বা পৃষ্ঠপোষকের সাহায্যে", "যত বেশি সম্ভব নেওয়া", "বেচতে অস্বীকার", "সস্তায় নকল হেলমেট বেচা"],
        "সাশ্রয়ী নিরাপত্তা প্রাণ বাঁচায় - ব্যবসা ভালো কাজ করেও টিকে থাকতে পারে।"),
)
