"""Class 5 - Biology (Junior Cadet): cells, photosynthesis and respiration, plant transport,
micro-organisms and disease, the skeleton as a structure, energy in food, ecosystems and the
10% energy rule, inheritance and fossils, and biomimicry - engineering ideas borrowed from nature."""
from . import mcq


def _o(r, *alts):
    out = []
    for x in (r, *alts, r + 10, r * 2, r + 1):
        if x not in out and x >= 0:
            out.append(x)
    return out[:4]


def energy10(start, levels, what_en, what_bn):
    r = start
    for _ in range(levels):
        r //= 10
    o = _o(r, start, start // 2, r * 10 if levels > 1 else r + 50)
    return mcq(f"{what_en} capture {start:,} units of energy. Only about 10% passes to each next level. How much reaches level {levels + 1} of the food chain?",
               [f"{x:,} units" for x in o], 0,
               f"Divide by 10 for each step: {start:,} -> " + " -> ".join(str(start // 10 ** (i + 1)) for i in range(levels)) + ". Most energy is used for living or lost as heat.",
               f"{what_bn} {start:,} একক শক্তি ধরে। প্রতি পরের স্তরে মাত্র প্রায় 10% যায়। খাদ্যশৃঙ্খলের {levels + 1} নম্বর স্তরে কত পৌঁছায়?",
               [f"{x:,} একক" for x in o],
               f"প্রতি ধাপে 10 দিয়ে ভাগ: {start:,} -> " + " -> ".join(str(start // 10 ** (i + 1)) for i in range(levels)) + "। বেশিরভাগ শক্তি বাঁচার কাজে লাগে বা তাপ হয়ে হারায়।")


def kcal(per100, grams, food_en, food_bn):
    r = per100 * grams // 100
    o = _o(r, per100, per100 + grams, r // 2)
    return mcq(f"{food_en} gives {per100} kcal per 100 g. How much energy is in {grams} g?",
               [f"{x:,} kcal" for x in o], 0,
               f"{per100} x {grams} ÷ 100 = {r} kcal.",
               f"{food_bn} প্রতি 100 g-এ {per100} kcal দেয়। {grams} g-এ কত শক্তি?",
               [f"{x:,} কিলোক্যালরি" for x in o],
               f"{per100} x {grams} ÷ 100 = {r} কিলোক্যালরি।")


ITEMS = (
    energy10(10000, 1, "Grass plants", "ঘাস"), energy10(50000, 2, "Rice plants in a field", "খেতের ধানগাছ"),
    energy10(200000, 3, "River algae", "নদীর শৈবাল"), energy10(30000, 1, "Water plants", "জলজ উদ্ভিদ"),
    energy10(800000, 2, "Forest trees", "বনের গাছ"),
    kcal(350, 200, "Cooked rice (dry weight)", "চাল (শুকনো ওজন)"), kcal(120, 150, "Dal", "ডাল"),
    kcal(90, 300, "Bananas", "কলা"), kcal(250, 80, "Roti", "রুটি"), kcal(60, 250, "Milk", "দুধ"),
    mcq("What is a 'cell'?", ["The smallest living unit that makes up all living things", "A prison room", "A battery only", "A grain of sand"], 0,
        "Your body has about 37 trillion cells.",
        "'কোষ' কী?", ["ক্ষুদ্রতম জীবিত একক, যা দিয়ে সব জীব তৈরি", "জেলখানার ঘর", "শুধু ব্যাটারি", "বালির দানা"],
        "তোমার শরীরে প্রায় 37 লক্ষ কোটি কোষ।"),
    mcq("Which part of a cell controls what it does and holds its DNA?", ["The nucleus", "The cell wall", "The vacuole", "The membrane only"], 0,
        "The nucleus is the cell's control centre.",
        "কোষের কোন অংশ তার কাজ নিয়ন্ত্রণ করে আর ডিএনএ রাখে?", ["নিউক্লিয়াস", "কোষপ্রাচীর", "গহ্বর", "শুধু পর্দা"],
        "নিউক্লিয়াস কোষের নিয়ন্ত্রণকেন্দ্র।"),
    mcq("Which part do plant cells have but animal cells do not?", ["A cell wall and chloroplasts", "A nucleus", "A membrane", "Cytoplasm"], 0,
        "The stiff cell wall gives plants structure - like a building's frame.",
        "কোন অংশ উদ্ভিদকোষে আছে কিন্তু প্রাণীকোষে নেই?", ["কোষপ্রাচীর আর ক্লোরোপ্লাস্ট", "নিউক্লিয়াস", "পর্দা", "সাইটোপ্লাজম"],
        "শক্ত কোষপ্রাচীর উদ্ভিদকে গঠন দেয় - ভবনের কাঠামোর মতো।"),
    mcq("What do chloroplasts do?", ["Capture sunlight to make food by photosynthesis", "Store bones", "Pump blood", "Digest meat"], 0,
        "They contain green chlorophyll.",
        "ক্লোরোপ্লাস্ট কী করে?", ["সালোকসংশ্লেষে খাদ্য তৈরির জন্য সূর্যালোক ধরে", "হাড় জমায়", "রক্ত পাম্প করে", "মাংস হজম করে"],
        "এতে সবুজ ক্লোরোফিল থাকে।"),
    mcq("What does the cell membrane do?", ["Controls what goes in and out of the cell", "Makes the cell green", "Stores DNA", "Makes it rigid like wood"], 0,
        "It is like a security gate.",
        "কোষপর্দা কী করে?", ["কোষে কী ঢুকবে আর বেরোবে তা নিয়ন্ত্রণ করে", "কোষকে সবুজ করে", "ডিএনএ রাখে", "কাঠের মতো শক্ত করে"],
        "এটা নিরাপত্তা-ফটকের মতো।"),
    mcq("What do you need to see cells clearly?", ["A microscope", "A telescope", "A thermometer", "A ruler"], 0,
        "Robert Hooke first saw cells in cork in 1665.",
        "কোষ স্পষ্ট দেখতে কী লাগে?", ["অণুবীক্ষণ যন্ত্র", "দূরবিন", "থার্মোমিটার", "রুলার"],
        "রবার্ট হুক 1665 সালে প্রথম কর্কে কোষ দেখেন।"),
    mcq("What is the word equation for photosynthesis?", ["carbon dioxide + water -> glucose + oxygen (using light)", "oxygen + glucose -> water", "water -> oxygen only", "glucose + light -> carbon dioxide"], 0,
        "Light energy is captured by chlorophyll to build sugar.",
        "সালোকসংশ্লেষের শব্দ-সমীকরণ কী?", ["কার্বন ডাই-অক্সাইড + জল -> গ্লুকোজ + অক্সিজেন (আলো ব্যবহার করে)", "অক্সিজেন + গ্লুকোজ -> জল", "জল -> শুধু অক্সিজেন", "গ্লুকোজ + আলো -> কার্বন ডাই-অক্সাইড"],
        "ক্লোরোফিল আলোর শক্তি ধরে চিনি গড়ে।"),
    mcq("Where does most photosynthesis happen in a plant?", ["In the leaves", "In the roots", "In the flowers only", "In the seeds"], 0,
        "Leaves are thin and broad to catch light.",
        "গাছের কোথায় বেশিরভাগ সালোকসংশ্লেষ হয়?", ["পাতায়", "শিকড়ে", "শুধু ফুলে", "বীজে"],
        "আলো ধরতে পাতা পাতলা আর চওড়া।"),
    mcq("How does carbon dioxide get into a leaf?", ["Through tiny holes called stomata", "Through the roots", "Through flowers", "It does not"], 0,
        "Stomata also let water vapour out.",
        "কার্বন ডাই-অক্সাইড পাতায় ঢোকে কীভাবে?", ["পত্ররন্ধ্র নামের ছোট ছিদ্র দিয়ে", "শিকড় দিয়ে", "ফুল দিয়ে", "ঢোকে না"],
        "পত্ররন্ধ্র দিয়ে জলীয় বাষ্পও বেরোয়।"),
    mcq("What is 'respiration' in living things?", ["Releasing energy from food using oxygen", "Breathing only", "Making food from light", "Growing hair"], 0,
        "glucose + oxygen -> carbon dioxide + water + energy. It happens in every cell.",
        "জীবের 'শ্বসন' কী?", ["অক্সিজেন দিয়ে খাবার থেকে শক্তি মুক্ত করা", "শুধু শ্বাস নেওয়া", "আলো থেকে খাদ্য তৈরি", "চুল গজানো"],
        "গ্লুকোজ + অক্সিজেন -> কার্বন ডাই-অক্সাইড + জল + শক্তি। প্রতিটি কোষে হয়।"),
    mcq("Do plants respire as well as photosynthesise?", ["Yes - plants respire all the time, day and night", "No, never", "Only in winter", "Only their flowers do"], 0,
        "In daylight, photosynthesis is usually faster, so they give out more oxygen than they use.",
        "উদ্ভিদ কি সালোকসংশ্লেষের সঙ্গে শ্বসনও করে?", ["হ্যাঁ - দিনরাত সবসময় শ্বসন করে", "না, কখনো না", "শুধু শীতে", "শুধু ফুল করে"],
        "দিনের আলোয় সালোকসংশ্লেষ সাধারণত দ্রুত হয়, তাই যত অক্সিজেন খরচ করে তার বেশি ছাড়ে।"),
    mcq("Which part of a cell releases energy in respiration?", ["Mitochondria", "Nucleus", "Cell wall", "Vacuole"], 0,
        "Mitochondria are the cell's power stations.",
        "শ্বসনে কোষের কোন অংশ শক্তি মুক্ত করে?", ["মাইটোকন্ড্রিয়া", "নিউক্লিয়াস", "কোষপ্রাচীর", "গহ্বর"],
        "মাইটোকন্ড্রিয়া কোষের বিদ্যুৎকেন্দ্র।"),
    mcq("Why do your muscles ache after very hard exercise?", ["Without enough oxygen they make lactic acid", "Muscles turn to bone", "Blood stops", "They are cold"], 0,
        "This is anaerobic respiration - rest lets the body clear it.",
        "খুব কঠিন ব্যায়ামের পর পেশিতে ব্যথা হয় কেন?", ["যথেষ্ট অক্সিজেন ছাড়া তারা ল্যাকটিক অ্যাসিড তৈরি করে", "পেশি হাড় হয়ে যায়", "রক্ত থামে", "ঠান্ডা লাগে"],
        "এটা অবাত শ্বসন - বিশ্রামে শরীর তা সরিয়ে ফেলে।"),
    mcq("Which tubes carry water up a plant from the roots?", ["Xylem", "Phloem", "Arteries", "Nerves"], 0,
        "Xylem cells are hollow and stiffened - they also help hold the plant up.",
        "কোন নল শিকড় থেকে গাছের উপরে জল নিয়ে যায়?", ["জাইলেম", "ফ্লোয়েম", "ধমনি", "স্নায়ু"],
        "জাইলেম কোষ ফাঁপা আর শক্ত - গাছকে খাড়া রাখতেও সাহায্য করে।"),
    mcq("Which tubes carry sugar around a plant?", ["Phloem", "Xylem", "Veins", "Stomata"], 0,
        "Phloem moves food from leaves to where it is needed.",
        "কোন নল গাছের সর্বত্র চিনি বয়ে নেয়?", ["ফ্লোয়েম", "জাইলেম", "শিরা", "পত্ররন্ধ্র"],
        "ফ্লোয়েম পাতা থেকে প্রয়োজনের জায়গায় খাদ্য নেয়।"),
    mcq("What is 'transpiration'?", ["Water evaporating from leaves, pulling more water up the plant", "Plants moving to new places", "Roots growing", "Flowers opening"], 0,
        "A big tree can lose hundreds of litres a day this way.",
        "'প্রস্বেদন' কী?", ["পাতা থেকে জল বাষ্পীভূত হয়ে গাছে আরও জল টেনে তোলা", "উদ্ভিদের নতুন জায়গায় যাওয়া", "শিকড় বাড়া", "ফুল ফোটা"],
        "একটা বড় গাছ এভাবে দিনে শত শত লিটার জল হারাতে পারে।"),
    mcq("Why do tree trunks get thicker every year?", ["New layers of wood grow, making growth rings", "Bark absorbs rain", "Insects add wood", "They do not"], 0,
        "Counting rings tells a tree's age.",
        "গাছের গুঁড়ি প্রতি বছর মোটা হয় কেন?", ["কাঠের নতুন স্তর জন্মে বর্ষবলয় তৈরি করে", "বাকল বৃষ্টি শোষে", "পোকা কাঠ যোগ করে", "হয় না"],
        "বলয় গুনে গাছের বয়স জানা যায়।"),
    mcq("Why is a hollow bamboo stem strong for its weight?", ["A tube resists bending well with little material", "Hollow things are always weak", "Bamboo is metal inside", "It is filled with water"], 0,
        "Engineers use hollow tubes for the same reason.",
        "ফাঁপা বাঁশের কাণ্ড ওজনের তুলনায় শক্ত কেন?", ["নল অল্প উপাদানে বাঁকা ভালো ঠেকায়", "ফাঁপা জিনিস সবসময় দুর্বল", "বাঁশের ভেতরে ধাতু", "জলে ভরা"],
        "একই কারণে প্রকৌশলীরা ফাঁপা নল ব্যবহার করেন।"),
    mcq("What are bacteria?", ["Single-celled micro-organisms, some helpful and some harmful", "Tiny insects", "Plants", "Viruses only"], 0,
        "Bacteria in your gut help digest food.",
        "ব্যাকটেরিয়া কী?", ["এককোষী অণুজীব, কিছু উপকারী আর কিছু ক্ষতিকর", "ছোট্ট পোকা", "উদ্ভিদ", "শুধু ভাইরাস"],
        "তোমার অন্ত্রের ব্যাকটেরিয়া খাবার হজমে সাহায্য করে।"),
    mcq("How are viruses different from bacteria?", ["Viruses are much smaller and can only reproduce inside living cells", "Viruses are bigger", "Viruses are plants", "They are the same"], 0,
        "Antibiotics kill bacteria but do not work on viruses.",
        "ভাইরাস ব্যাকটেরিয়া থেকে কীভাবে আলাদা?", ["ভাইরাস অনেক ছোট আর শুধু জীবিত কোষের ভেতরে বংশবৃদ্ধি করে", "ভাইরাস বড়", "ভাইরাস উদ্ভিদ", "দুটো একই"],
        "অ্যান্টিবায়োটিক ব্যাকটেরিয়া মারে, কিন্তু ভাইরাসে কাজ করে না।"),
    mcq("What are antibiotics used for?", ["Treating infections caused by bacteria", "Curing colds caused by viruses", "Growing taller", "Making vitamins"], 0,
        "Always finish the course a doctor prescribes.",
        "অ্যান্টিবায়োটিক কীসে ব্যবহার হয়?", ["ব্যাকটেরিয়ার সংক্রমণের চিকিৎসায়", "ভাইরাসের সর্দি সারাতে", "লম্বা হতে", "ভিটামিন বানাতে"],
        "ডাক্তার যে কোর্স দেন, সবসময় পুরোটা শেষ করো।"),
    mcq("What are fungi?", ["Living things like mushrooms, moulds and yeast", "Plants that make food from light", "Bacteria", "Animals"], 0,
        "Fungi feed on dead or living material - they can rot timber bridges.",
        "ছত্রাক কী?", ["মাশরুম, ছাতা-পড়া আর ইস্টের মতো জীব", "আলো থেকে খাদ্য তৈরি করা উদ্ভিদ", "ব্যাকটেরিয়া", "প্রাণী"],
        "ছত্রাক মরা বা জীবিত উপাদান খায় - কাঠের সেতু পচাতে পারে।"),
    mcq("Which disease is spread by mosquitoes?", ["Malaria", "Chickenpox", "Common cold", "Broken bones"], 0,
        "Dengue is also mosquito-borne - remove standing water.",
        "কোন রোগ মশায় ছড়ায়?", ["ম্যালেরিয়া", "জলবসন্ত", "সাধারণ সর্দি", "হাড় ভাঙা"],
        "ডেঙ্গিও মশাবাহিত - জমা জল সরাও।"),
    mcq("Which disease can spread through dirty drinking water?", ["Cholera", "Malaria", "Asthma", "Short-sightedness"], 0,
        "Clean water and good sanitation stop cholera.",
        "কোন রোগ নোংরা খাবার জলে ছড়াতে পারে?", ["কলেরা", "ম্যালেরিয়া", "হাঁপানি", "স্বল্পদৃষ্টি"],
        "পরিষ্কার জল আর ভালো স্যানিটেশন কলেরা ঠেকায়।"),
    mcq("How do vaccines protect you?", ["They teach your immune system to recognise a germ in advance", "They kill all germs everywhere", "They are food", "They make you stronger at sport"], 0,
        "When the real germ comes, the body fights it quickly.",
        "টিকা তোমাকে কীভাবে রক্ষা করে?", ["রোগ-প্রতিরোধ ব্যবস্থাকে আগে থেকেই জীবাণু চিনতে শেখায়", "সব জায়গার সব জীবাণু মারে", "এটা খাবার", "খেলায় শক্তিশালী করে"],
        "আসল জীবাণু এলে শরীর দ্রুত লড়ে।"),
    mcq("What do white blood cells do?", ["Fight germs that get into the body", "Carry oxygen", "Help blood clot only", "Make bones"], 0,
        "They are the body's defence army.",
        "শ্বেত রক্তকণিকা কী করে?", ["শরীরে ঢোকা জীবাণুর সঙ্গে লড়ে", "অক্সিজেন বয়", "শুধু রক্ত জমাট বাঁধাতে সাহায্য করে", "হাড় তৈরি করে"],
        "তারা শরীরের প্রতিরক্ষা-বাহিনী।"),
    mcq("What do platelets in the blood do?", ["Help blood clot to seal cuts", "Carry oxygen", "Fight all germs", "Digest food"], 0,
        "A scab forms over a cut as platelets work.",
        "রক্তের অণুচক্রিকা কী করে?", ["কাটা জায়গা বন্ধ করতে রক্ত জমাট বাঁধাতে সাহায্য করে", "অক্সিজেন বয়", "সব জীবাণুর সঙ্গে লড়ে", "খাবার হজম করে"],
        "অণুচক্রিকা কাজ করলে কাটা জায়গায় মামড়ি পড়ে।"),
    mcq("How many bones does an adult human skeleton have?", ["206", "106", "306", "26"], 0,
        "Babies have about 300; some fuse together as they grow.",
        "পূর্ণবয়স্ক মানুষের কঙ্কালে কয়টি হাড়?", ["206", "106", "306", "26"],
        "শিশুর প্রায় 300টি; বড় হতে হতে কিছু জুড়ে যায়।"),
    mcq("Which is the longest and strongest bone in the body?", ["The thigh bone (femur)", "The skull", "A finger bone", "The rib"], 0,
        "The femur can carry many times your body weight.",
        "শরীরের সবচেয়ে লম্বা আর শক্ত হাড় কোনটা?", ["উরুর হাড় (ফিমার)", "মাথার খুলি", "আঙুলের হাড়", "পাঁজর"],
        "ফিমার শরীরের ওজনের বহুগুণ বইতে পারে।"),
    mcq("Why are long bones like the femur hollow tubes?", ["A tube is strong and light - like a steel pipe", "To store air", "Because they are weak", "To make noise"], 0,
        "Nature and engineers both use tubes for strength with less weight.",
        "ফিমারের মতো লম্বা হাড় ফাঁপা নলের মতো কেন?", ["নল শক্ত আর হালকা - ইস্পাতের পাইপের মতো", "বাতাস রাখতে", "দুর্বল বলে", "শব্দ করতে"],
        "প্রকৃতি আর প্রকৌশলী দুজনেই কম ওজনে শক্তির জন্য নল ব্যবহার করে।"),
    mcq("What is inside many bones that makes blood cells?", ["Bone marrow", "Air", "Water only", "Muscle"], 0,
        "Bone marrow makes millions of blood cells every second.",
        "অনেক হাড়ের ভেতরে কী থাকে, যা রক্তকণিকা তৈরি করে?", ["অস্থিমজ্জা", "বাতাস", "শুধু জল", "পেশি"],
        "অস্থিমজ্জা প্রতি সেকেন্ডে লক্ষ লক্ষ রক্তকণিকা তৈরি করে।"),
    mcq("Which mineral makes bones hard?", ["Calcium", "Iron only", "Sodium", "Gold"], 0,
        "Milk, curd, ragi and green vegetables give calcium.",
        "কোন খনিজ হাড় শক্ত করে?", ["ক্যালসিয়াম", "শুধু লোহা", "সোডিয়াম", "সোনা"],
        "দুধ, দই, রাগি আর সবুজ শাক ক্যালসিয়াম দেয়।"),
    mcq("Why is the spine made of many small bones instead of one long bone?", ["It can bend while still protecting the spinal cord", "One bone would be too light", "To save calcium", "It is one bone"], 0,
        "Flexible yet strong - like a chain of short segments.",
        "মেরুদণ্ড একটা লম্বা হাড়ের বদলে অনেক ছোট হাড় দিয়ে তৈরি কেন?", ["সুষুম্নাকাণ্ড রক্ষা করেও বাঁকতে পারে", "একটা হাড় খুব হালকা হতো", "ক্যালসিয়াম বাঁচাতে", "এটা একটাই হাড়"],
        "নমনীয় অথচ শক্ত - ছোট ছোট অংশের শিকলের মতো।"),
    mcq("What is 'cartilage'?", ["Smooth, rubbery tissue that cushions joints", "A type of bone marrow", "A blood vessel", "Hair"], 0,
        "Your nose and ears are shaped by cartilage - like bridge bearings, it absorbs knocks.",
        "'তরুণাস্থি' কী?", ["মসৃণ, রবারের মতো কলা যা সন্ধিতে গদির কাজ করে", "এক রকম অস্থিমজ্জা", "রক্তনালী", "চুল"],
        "নাক আর কান তরুণাস্থিতে আকার পায় - সেতুর বিয়ারিংয়ের মতো এটা ধাক্কা শোষে।"),
    mcq("What is an 'ecosystem'?", ["Living things and their environment working together", "Only the animals in an area", "A computer system", "A single tree"], 0,
        "A pond, a forest and a mangrove are ecosystems.",
        "'বাস্তুতন্ত্র' কী?", ["জীব আর তাদের পরিবেশ একসঙ্গে কাজ করে", "শুধু একটা অঞ্চলের প্রাণী", "কম্পিউটার-ব্যবস্থা", "একটা মাত্র গাছ"],
        "পুকুর, বন আর ম্যানগ্রোভ বাস্তুতন্ত্র।"),
    mcq("In a food chain, what are animals that eat only plants called?", ["Herbivores (primary consumers)", "Carnivores", "Decomposers", "Producers"], 0,
        "Cows, deer and many insects are herbivores.",
        "খাদ্যশৃঙ্খলে শুধু উদ্ভিদ খাওয়া প্রাণীদের কী বলে?", ["তৃণভোজী (প্রথম স্তরের খাদক)", "মাংসাশী", "বিয়োজক", "উৎপাদক"],
        "গরু, হরিণ আর অনেক পোকা তৃণভোজী।"),
    mcq("Why are there usually far fewer tigers than deer in a forest?", ["Energy is lost at each step, so top predators have less food energy", "Tigers are shy", "Deer are faster", "Tigers live longer"], 0,
        "Only about 10% of energy passes up each level of a food chain.",
        "বনে সাধারণত হরিণের চেয়ে বাঘ অনেক কম কেন?", ["প্রতি ধাপে শক্তি হারায়, তাই শীর্ষ শিকারির খাদ্যশক্তি কম", "বাঘ লাজুক", "হরিণ দ্রুত", "বাঘ বেশি দিন বাঁচে"],
        "খাদ্যশৃঙ্খলের প্রতি স্তরে মাত্র প্রায় 10% শক্তি উপরে যায়।"),
    mcq("What is 'biodiversity'?", ["The variety of different living things in an area", "One species only", "A type of soil", "A weather pattern"], 0,
        "High biodiversity makes ecosystems more stable.",
        "'জীববৈচিত্র্য' কী?", ["একটা অঞ্চলে নানা রকম জীবের বৈচিত্র্য", "শুধু একটা প্রজাতি", "এক রকম মাটি", "আবহাওয়ার ধরন"],
        "বেশি জীববৈচিত্র্য বাস্তুতন্ত্রকে স্থিতিশীল করে।"),
    mcq("What is an 'endangered species'?", ["A kind of living thing at risk of dying out", "A dangerous animal", "A new species", "A pet"], 0,
        "The Ganges river dolphin is endangered - bridge projects must protect its habitat.",
        "'বিপন্ন প্রজাতি' কী?", ["যে ধরনের জীব লুপ্ত হওয়ার ঝুঁকিতে", "বিপজ্জনক প্রাণী", "নতুন প্রজাতি", "পোষা প্রাণী"],
        "গাঙ্গেয় শুশুক বিপন্ন - সেতু-প্রকল্পকে তার বাসস্থান রক্ষা করতে হয়।"),
    mcq("How can a badly planned bridge harm river life?", ["Blocking fish movement, muddying water and destroying banks", "It always helps fish", "It cools the river", "It cannot harm anything"], 0,
        "Good designs keep channels open and limit construction mess.",
        "খারাপ পরিকল্পনার সেতু নদীর জীবের কীভাবে ক্ষতি করতে পারে?", ["মাছের চলাচল আটকে, জল ঘোলা করে আর পাড় নষ্ট করে", "সবসময় মাছের উপকার করে", "নদী ঠান্ডা করে", "কোনো ক্ষতি করতে পারে না"],
        "ভালো নকশা প্রবাহপথ খোলা রাখে আর নির্মাণের নোংরা সীমিত রাখে।"),
    mcq("What is 'inheritance' in biology?", ["Features passed from parents to children through genes", "Money left in a will", "Learning a skill", "Catching a cold"], 0,
        "Eye colour and blood group are inherited.",
        "জীববিদ্যায় 'বংশগতি' কী?", ["জিনের মাধ্যমে বাবা-মা থেকে সন্তানে বৈশিষ্ট্য আসা", "উইলে রেখে যাওয়া টাকা", "দক্ষতা শেখা", "সর্দি লাগা"],
        "চোখের রং আর রক্তের গ্রুপ বংশগত।"),
    mcq("Where are genes found?", ["In DNA inside the nucleus of cells", "In the blood only", "In the hair only", "In food"], 0,
        "DNA is a long molecule like an instruction manual.",
        "জিন কোথায় থাকে?", ["কোষের নিউক্লিয়াসের ভেতরে ডিএনএ-তে", "শুধু রক্তে", "শুধু চুলে", "খাবারে"],
        "ডিএনএ নির্দেশিকা-বইয়ের মতো একটা লম্বা অণু।"),
    mcq("Which is NOT inherited but learned?", ["Speaking Bengali", "Eye colour", "Blood group", "Natural hair colour"], 0,
        "Skills and languages are learned - including how to design bridges!",
        "কোনটা বংশগত নয়, শেখা?", ["বাংলা বলা", "চোখের রং", "রক্তের গ্রুপ", "স্বাভাবিক চুলের রং"],
        "দক্ষতা আর ভাষা শেখা হয় - সেতুর নকশা করাও!"),
    mcq("What is a 'fossil'?", ["The preserved remains or traces of ancient living things in rock", "A new rock", "A type of fuel only", "A living animal"], 0,
        "Fossils show how life has changed over millions of years.",
        "'জীবাশ্ম' কী?", ["পাথরে সংরক্ষিত প্রাচীন জীবের দেহাবশেষ বা ছাপ", "নতুন পাথর", "শুধু এক রকম জ্বালানি", "জীবিত প্রাণী"],
        "জীবাশ্ম দেখায় লক্ষ লক্ষ বছরে জীবন কীভাবে বদলেছে।"),
    mcq("What is 'evolution'?", ["The slow change of living things over many generations", "Growing up in one lifetime", "A machine", "A daily change of weather"], 0,
        "Charles Darwin explained it through natural selection.",
        "'বিবর্তন' কী?", ["বহু প্রজন্ম ধরে জীবের ধীর পরিবর্তন", "এক জীবনে বড় হওয়া", "একটা যন্ত্র", "আবহাওয়ার দৈনিক বদল"],
        "চার্লস ডারউইন প্রাকৃতিক নির্বাচন দিয়ে ব্যাখ্যা করেন।"),
    mcq("What is 'natural selection'?", ["Living things best suited to their environment survive and pass on their features", "Choosing pets", "Picking fruit", "A school election"], 0,
        "Over time, helpful features become more common.",
        "'প্রাকৃতিক নির্বাচন' কী?", ["পরিবেশের সঙ্গে সবচেয়ে মানানসই জীবেরা টিকে থেকে বৈশিষ্ট্য সন্তানে দেয়", "পোষা প্রাণী বাছা", "ফল তোলা", "স্কুলের নির্বাচন"],
        "সময়ের সঙ্গে উপকারী বৈশিষ্ট্য বেশি দেখা যায়।"),
    mcq("What is 'biomimicry'?", ["Copying ideas from nature to solve design problems", "Painting animals", "Keeping a zoo", "Cloning plants"], 0,
        "Engineers study spider silk, bones and termite mounds for ideas.",
        "'জৈব-অনুকরণ' (বায়োমিমিক্রি) কী?", ["নকশার সমস্যা সমাধানে প্রকৃতি থেকে ধারণা নেওয়া", "প্রাণী রং করা", "চিড়িয়াখানা রাখা", "উদ্ভিদ ক্লোন করা"],
        "প্রকৌশলীরা ধারণার জন্য মাকড়সার রেশম, হাড় আর উইঢিবি নিয়ে গবেষণা করেন।"),
    mcq("Why is spider silk interesting to engineers?", ["For its weight, it is stronger than steel and very stretchy", "It is magnetic", "It glows", "It is heavy"], 0,
        "Scientists try to make cables inspired by it.",
        "মাকড়সার রেশম প্রকৌশলীদের কাছে আকর্ষণীয় কেন?", ["ওজনের তুলনায় ইস্পাতের চেয়ে শক্ত আর খুব স্থিতিস্থাপক", "চুম্বকীয়", "জ্বলজ্বল করে", "ভারী"],
        "বিজ্ঞানীরা এর অনুপ্রেরণায় তার বানানোর চেষ্টা করেন।"),
    mcq("How do termite mounds inspire building design?", ["Their tunnels keep air cool without machines", "They are made of steel", "They float", "They attract rain"], 0,
        "The Eastgate Centre in Zimbabwe copies termite cooling.",
        "উইঢিবি ভবনের নকশায় কীভাবে অনুপ্রেরণা দেয়?", ["তাদের সুড়ঙ্গ যন্ত্র ছাড়াই বাতাস ঠান্ডা রাখে", "ইস্পাতের তৈরি", "ভাসে", "বৃষ্টি টানে"],
        "জিম্বাবোয়ের ইস্টগেট সেন্টার উইপোকার শীতলীকরণ নকল করে।"),
    mcq("Why is the honeycomb shape used in aircraft panels and some bridge decks?", ["Hexagon cells give great strength with little material", "Bees designed planes", "It is sticky", "It is heavy"], 0,
        "Honeycomb sandwich panels are stiff and light.",
        "বিমানের প্যানেল আর কিছু সেতুর পাটাতনে মৌচাকের আকার ব্যবহার হয় কেন?", ["ষড়ভুজ কোষ অল্প উপাদানে দারুণ শক্তি দেয়", "মৌমাছি বিমান বানিয়েছে", "আঠালো", "ভারী"],
        "মৌচাক-স্যান্ডউইচ প্যানেল শক্ত আর হালকা।"),
    mcq("How do bird bones help birds fly?", ["They are hollow with internal struts - light but strong", "They are solid and heavy", "They are made of feathers", "Birds have no bones"], 0,
        "Inside, tiny cross-braces look like a truss!",
        "পাখির হাড় উড়তে কীভাবে সাহায্য করে?", ["ভেতরে ঠেকনাসহ ফাঁপা - হালকা অথচ শক্ত", "শক্ত আর ভারী", "পালক দিয়ে তৈরি", "পাখির হাড় নেই"],
        "ভেতরে ছোট্ট আড়াআড়ি ঠেকনা ট্রাসের মতো দেখায়!"),
    mcq("A kingfisher's beak inspired the shape of which machine?", ["Japan's bullet train nose", "A bicycle", "A crane hook", "A tractor"], 0,
        "The pointed shape cut noise when the train left tunnels.",
        "মাছরাঙার ঠোঁট কোন যন্ত্রের আকারে অনুপ্রেরণা দিয়েছে?", ["জাপানের বুলেট ট্রেনের সামনের দিক", "সাইকেল", "ক্রেনের আংটা", "ট্রাক্টর"],
        "সরু আকার সুড়ঙ্গ থেকে বেরোনোর সময় ট্রেনের শব্দ কমিয়েছে।"),
    mcq("What do tree roots teach engineers about foundations?", ["Spreading and going deep gives a firm grip in soil", "Shallow is always best", "Roots are useless", "Foundations should float"], 0,
        "Pile foundations reach deep, stronger layers - like tap roots.",
        "গাছের শিকড় ভিত সম্পর্কে প্রকৌশলীদের কী শেখায়?", ["ছড়িয়ে আর গভীরে গেলে মাটিতে শক্ত আঁকড় হয়", "অগভীরই সবসময় ভালো", "শিকড় অকেজো", "ভিত ভাসা উচিত"],
        "পাইল-ভিত গভীর, শক্ত স্তরে পৌঁছায় - প্রধান মূলের মতো।"),
    mcq("Why do giant water lily leaves (Victoria amazonica) inspire engineers?", ["Ribs underneath let a thin leaf carry a heavy load", "They are made of iron", "They sink", "They are tiny"], 0,
        "Their rib pattern inspired the Crystal Palace roof in 1851.",
        "বিশাল জলপদ্মের (ভিক্টোরিয়া অ্যামাজোনিকা) পাতা প্রকৌশলীদের অনুপ্রেরণা দেয় কেন?", ["নিচের শিরা পাতলা পাতাকে ভারী বোঝা বইতে দেয়", "লোহার তৈরি", "ডুবে যায়", "খুব ছোট"],
        "এর শিরার নকশা 1851 সালে ক্রিস্টাল প্যালেসের ছাদে অনুপ্রেরণা দিয়েছিল।"),
    mcq("What is 'puberty'?", ["The stage when children's bodies start changing into adults'", "A type of bone", "A disease", "A food group"], 0,
        "It usually happens between about 9 and 16 - everyone's timing is different.",
        "'বয়ঃসন্ধি' কী?", ["যে পর্যায়ে শিশুর শরীর বড়দের শরীরে বদলাতে শুরু করে", "এক রকম হাড়", "একটা রোগ", "খাদ্যগোষ্ঠী"],
        "সাধারণত প্রায় 9 থেকে 16 বছরে হয় - প্রত্যেকের সময় আলাদা।"),
    mcq("Why do the labels on food packets show energy (kcal)?", ["To help people eat the right amount for their needs", "For decoration", "To show the price", "It is the weight of the box"], 0,
        "Active workers need more energy than people sitting all day.",
        "খাবারের প্যাকেটের লেবেলে শক্তি (kcal) দেখায় কেন?", ["প্রয়োজন অনুযায়ী ঠিক পরিমাণ খেতে সাহায্য করতে", "সাজসজ্জার জন্য", "দাম দেখাতে", "এটা বাক্সের ওজন"],
        "সক্রিয় কর্মীদের সারাদিন বসে থাকা মানুষের চেয়ে বেশি শক্তি লাগে।"),
    mcq("Why do people doing heavy building work need more food energy?", ["Their muscles respire more to do physical work", "Building sites are cold", "Food makes bricks lighter", "They do not"], 0,
        "A labourer may need 3,000+ kcal a day.",
        "ভারী নির্মাণকাজ করা মানুষের বেশি খাদ্যশক্তি লাগে কেন?", ["শারীরিক কাজ করতে তাঁদের পেশি বেশি শ্বসন করে", "নির্মাণস্থল ঠান্ডা", "খাবারে ইট হালকা হয়", "লাগে না"],
        "একজন শ্রমিকের দিনে 3,000+ kcal লাগতে পারে।"),
    mcq("What happens if you eat more energy than you use, every day for a long time?", ["The extra is stored as fat and weight rises", "Nothing ever", "You shrink", "You get taller"], 0,
        "Balance food energy with activity.",
        "দীর্ঘদিন রোজ খরচের চেয়ে বেশি শক্তি খেলে কী হয়?", ["বাড়তি চর্বি হিসেবে জমে আর ওজন বাড়ে", "কখনো কিছু না", "ছোট হয়ে যাও", "লম্বা হও"],
        "খাদ্যশক্তি আর কাজের মধ্যে ভারসাম্য রাখো।"),
    mcq("Why is drinking alcohol on a building site dangerous?", ["It slows reactions and judgement, causing accidents", "It makes workers stronger", "It is a safety rule to drink", "It is not dangerous"], 0,
        "Sites have strict no-alcohol rules.",
        "নির্মাণস্থলে মদ্যপান বিপজ্জনক কেন?", ["প্রতিক্রিয়া আর বিচারবুদ্ধি ধীর করে দুর্ঘটনা ঘটায়", "কর্মীদের শক্তিশালী করে", "পান করা নিরাপত্তার নিয়ম", "বিপজ্জনক নয়"],
        "নির্মাণস্থলে কঠোর মদ্যপান-নিষেধ নিয়ম থাকে।"),
    mcq("What is the job of the skin?", ["Protecting the body, sensing touch and controlling temperature", "Pumping blood", "Digesting food", "Making bones"], 0,
        "Skin is the body's largest organ.",
        "ত্বকের কাজ কী?", ["শরীর রক্ষা, স্পর্শ অনুভব আর তাপমাত্রা নিয়ন্ত্রণ", "রক্ত পাম্প করা", "খাবার হজম", "হাড় তৈরি"],
        "ত্বক শরীরের বৃহত্তম অঙ্গ।"),
    mcq("Why do we sweat on a hot building site?", ["Evaporating sweat cools the skin", "To clean our clothes", "To make us heavier", "To smell nice"], 0,
        "Drink water to replace what you sweat out.",
        "গরম নির্মাণস্থলে আমরা ঘামি কেন?", ["ঘাম বাষ্পীভূত হয়ে ত্বক ঠান্ডা করে", "জামা পরিষ্কার করতে", "ভারী হতে", "সুগন্ধ ছড়াতে"],
        "যতটা ঘাম বেরোয় ততটা জল খাও।"),
    mcq("What is the 'immune system'?", ["The body's defences against disease", "The skeleton", "The digestive tract", "The lungs only"], 0,
        "Sleep, good food and vaccines keep it strong.",
        "'রোগ-প্রতিরোধ ব্যবস্থা' কী?", ["রোগের বিরুদ্ধে শরীরের প্রতিরক্ষা", "কঙ্কাল", "পরিপাকনালী", "শুধু ফুসফুস"],
        "ঘুম, ভালো খাবার আর টিকা একে শক্তিশালী রাখে।"),
    mcq("Why are mangrove forests called 'nurseries of the sea'?", ["Many young fish and crabs shelter and grow among their roots", "They grow baby trees only", "Schools are built there", "They are not"], 0,
        "Protecting mangroves protects fishing incomes too.",
        "ম্যানগ্রোভ বনকে 'সমুদ্রের শিশুশালা' বলে কেন?", ["অনেক ছোট মাছ আর কাঁকড়া তাদের শিকড়ের মাঝে আশ্রয় নিয়ে বড় হয়", "শুধু চারা গাছ জন্মায়", "সেখানে স্কুল বানানো হয়", "বলে না"],
        "ম্যানগ্রোভ রক্ষা করলে মাছধরার আয়ও রক্ষা পায়।"),
    mcq("What is 'pollution' doing to rivers when oxygen levels fall?", ["Fish and other animals can suffocate", "Fish grow faster", "Water becomes cleaner", "Nothing"], 0,
        "Sewage and chemicals use up dissolved oxygen.",
        "দূষণে নদীর অক্সিজেন কমলে কী হয়?", ["মাছ আর অন্য প্রাণীর দম বন্ধ হতে পারে", "মাছ দ্রুত বাড়ে", "জল পরিষ্কার হয়", "কিছুই না"],
        "নর্দমার জল আর রাসায়নিক গোলা অক্সিজেন শেষ করে।"),
    mcq("Why do construction sites near rivers use silt fences?", ["To stop muddy runoff smothering river life", "To keep cows out only", "To make noise", "For decoration"], 0,
        "Fine mud blocks light and clogs fish gills.",
        "নদীর কাছের নির্মাণস্থলে পলি-বেড়া ব্যবহার হয় কেন?", ["কাদা-মেশানো জল নদীর জীবকে চাপা দিতে না দিতে", "শুধু গরু আটকাতে", "শব্দ করতে", "সাজসজ্জার জন্য"],
        "মিহি কাদা আলো আটকায় আর মাছের ফুলকা বন্ধ করে।"),
    energy10(60000, 1, "Phytoplankton in a pond", "পুকুরের উদ্ভিদ-প্লাংকটন"),
    energy10(400000, 3, "Mangrove plants", "ম্যানগ্রোভ গাছ"),
    energy10(90000, 2, "Wheat plants", "গমগাছ"),
    kcal(160, 250, "Boiled potatoes", "সেদ্ধ আলু"), kcal(150, 200, "Eggs", "ডিম"),
    kcal(580, 50, "Peanuts", "চিনেবাদাম"),
    mcq("Which blood cells contain haemoglobin to carry oxygen?", ["Red blood cells", "White blood cells", "Platelets", "Nerve cells"], 0,
        "Haemoglobin needs iron - lentils, green leafy vegetables and jaggery help.",
        "কোন রক্তকণিকায় অক্সিজেন বইতে হিমোগ্লোবিন থাকে?", ["লোহিত রক্তকণিকা", "শ্বেত রক্তকণিকা", "অণুচক্রিকা", "স্নায়ুকোষ"],
        "হিমোগ্লোবিনের লোহা লাগে - ডাল, সবুজ শাক আর গুড় সাহায্য করে।"),
    mcq("What is a 'tissue' in the body?", ["A group of similar cells working together", "A paper handkerchief only", "A single atom", "A bone"], 0,
        "Muscle tissue, nerve tissue and bone tissue are examples.",
        "শরীরে 'কলা' (টিস্যু) কী?", ["একসঙ্গে কাজ করা একই রকম কোষের দল", "শুধু কাগজের রুমাল", "একটা পরমাণু", "হাড়"],
        "পেশিকলা, স্নায়ুকলা আর অস্থিকলা উদাহরণ।"),
    mcq("What is an 'organ'?", ["A group of tissues doing a job, like the heart or a leaf", "A musical instrument only", "A single cell", "A molecule"], 0,
        "Cells -> tissues -> organs -> organ systems -> organism.",
        "'অঙ্গ' কী?", ["একটা কাজ করা কলার দল, যেমন হৃৎপিণ্ড বা পাতা", "শুধু বাদ্যযন্ত্র", "একটা মাত্র কোষ", "অণু"],
        "কোষ -> কলা -> অঙ্গ -> অঙ্গতন্ত্র -> জীব।"),
    mcq("A plant is kept in a dark cupboard for a week. What happens?", ["It turns pale and weak because it cannot photosynthesise", "It grows greener", "Nothing changes", "It turns into a mushroom"], 0,
        "Without light, it uses up stored food.",
        "একটা গাছ এক সপ্তাহ অন্ধকার আলমারিতে রাখা হলো। কী হয়?", ["সালোকসংশ্লেষ না পেরে ফ্যাকাশে আর দুর্বল হয়", "আরও সবুজ হয়", "কিছুই বদলায় না", "মাশরুম হয়ে যায়"],
        "আলো ছাড়া সে জমানো খাবার খরচ করে ফেলে।"),
    mcq("Why do forests help fight climate change?", ["Trees take in carbon dioxide and store carbon in wood", "Trees make carbon dioxide only", "Forests are cold", "They do not"], 0,
        "Timber bridges keep carbon locked up for decades.",
        "বন জলবায়ু পরিবর্তনের বিরুদ্ধে লড়তে সাহায্য করে কেন?", ["গাছ কার্বন ডাই-অক্সাইড নিয়ে কাঠে কার্বন জমায়", "গাছ শুধু কার্বন ডাই-অক্সাইড তৈরি করে", "বন ঠান্ডা", "করে না"],
        "কাঠের সেতু দশকের পর দশক কার্বন আটকে রাখে।"),
    mcq("How do roots take in water from the soil?", ["Through tiny root hairs with a huge surface area", "Through leaves", "Through flowers", "They swallow it"], 0,
        "Root hairs are tiny extensions of root cells.",
        "শিকড় মাটি থেকে জল নেয় কীভাবে?", ["বিশাল তলের ক্ষুদ্র মূলরোম দিয়ে", "পাতা দিয়ে", "ফুল দিয়ে", "গিলে ফেলে"],
        "মূলরোম শিকড়-কোষের ছোট্ট প্রসারণ।"),
    mcq("Why do plants wilt when they lack water?", ["Their cells lose water pressure and go floppy", "They are sleeping", "Their roots grow too much", "Sunlight is too weak"], 0,
        "Water pressure in cells keeps soft plants upright - like air in a tyre.",
        "জলের অভাবে গাছ নেতিয়ে পড়ে কেন?", ["কোষ জলের চাপ হারিয়ে নরম হয়ে যায়", "তারা ঘুমোচ্ছে", "শিকড় বেশি বাড়ে", "রোদ খুব দুর্বল"],
        "কোষের জলের চাপ নরম গাছকে খাড়া রাখে - টায়ারের বাতাসের মতো।"),
    mcq("What is a 'scavenger'?", ["An animal that eats dead animals", "A plant", "A predator only", "A type of fungus only"], 0,
        "Vultures clean up carcasses and stop disease spreading.",
        "'মৃতভোজী' প্রাণী কী?", ["যে প্রাণী মরা প্রাণী খায়", "উদ্ভিদ", "শুধু শিকারি", "শুধু এক রকম ছত্রাক"],
        "শকুন মরা দেহ সাফ করে রোগ ছড়ানো আটকায়।"),
    mcq("Why are vultures important in India?", ["They clear dead animals that could spread disease", "They pollinate flowers", "They eat crops", "They are not important"], 0,
        "When vultures declined, diseases from carcasses increased.",
        "ভারতে শকুন জরুরি কেন?", ["রোগ ছড়াতে পারে এমন মরা প্রাণী সাফ করে", "ফুলের পরাগায়ন করে", "ফসল খায়", "জরুরি নয়"],
        "শকুন কমে গেলে মরা দেহ থেকে রোগ বেড়েছিল।"),
    mcq("What is 'germination'?", ["A seed starting to grow into a new plant", "A germ spreading", "Pollen landing", "A leaf falling"], 0,
        "It needs water, warmth and oxygen.",
        "'অঙ্কুরোদগম' কী?", ["বীজ থেকে নতুন গাছ জন্মাতে শুরু করা", "জীবাণু ছড়ানো", "পরাগ পড়া", "পাতা ঝরা"],
        "এর জন্য জল, উষ্ণতা আর অক্সিজেন লাগে।"),
    mcq("What is 'metamorphosis'?", ["A big change in body form during a life cycle, like caterpillar to butterfly", "Rusting of metal", "A rock forming", "Growing taller each year"], 0,
        "Frogs also go through metamorphosis from tadpoles.",
        "'রূপান্তর' কী?", ["জীবনচক্রে দেহের আকারে বড় পরিবর্তন, যেমন শুঁয়োপোকা থেকে প্রজাপতি", "ধাতুতে মরচে", "পাথর তৈরি", "প্রতি বছর লম্বা হওয়া"],
        "ব্যাঙও ব্যাঙাচি থেকে রূপান্তরের মধ্য দিয়ে যায়।"),
    mcq("Which organ filters toxins and stores energy as glycogen?", ["The liver", "The heart", "The lungs", "The skin"], 0,
        "The liver does over 500 jobs.",
        "কোন অঙ্গ বিষ ছাঁকে আর গ্লাইকোজেন হিসেবে শক্তি জমায়?", ["যকৃৎ", "হৃৎপিণ্ড", "ফুসফুস", "ত্বক"],
        "যকৃৎ 500-র বেশি কাজ করে।"),
    mcq("Why do doctors check blood pressure?", ["Very high pressure strains the heart and blood vessels", "To measure height", "To check eyesight", "To count bones"], 0,
        "Exercise, less salt and no smoking help keep it healthy.",
        "ডাক্তার রক্তচাপ পরীক্ষা করেন কেন?", ["খুব উচ্চ চাপ হৃৎপিণ্ড আর রক্তনালীতে চাপ দেয়", "উচ্চতা মাপতে", "দৃষ্টি পরীক্ষায়", "হাড় গুনতে"],
        "ব্যায়াম, কম লবণ আর ধূমপান না করা একে সুস্থ রাখে।"),
    mcq("What is an 'allergy'?", ["The immune system over-reacting to something harmless, like pollen or dust", "A broken bone", "A vitamin", "A type of exercise"], 0,
        "Cement dust can cause skin allergies in some workers.",
        "'অ্যালার্জি' কী?", ["পরাগ বা ধুলোর মতো নিরীহ জিনিসে রোগ-প্রতিরোধ ব্যবস্থার অতিরিক্ত প্রতিক্রিয়া", "হাড় ভাঙা", "ভিটামিন", "এক রকম ব্যায়াম"],
        "সিমেন্টের ধুলোয় কিছু কর্মীর ত্বকে অ্যালার্জি হতে পারে।"),
    mcq("Which sense organ helps you keep your balance?", ["The inner ear", "The nose", "The tongue", "The fingernails"], 0,
        "Fluid in the inner ear senses tilting - vital for workers at height.",
        "কোন ইন্দ্রিয়-অঙ্গ ভারসাম্য রাখতে সাহায্য করে?", ["অন্তঃকর্ণ", "নাক", "জিভ", "নখ"],
        "অন্তঃকর্ণের তরল কাত হওয়া টের পায় - উঁচুতে কাজ করা কর্মীদের জন্য জরুরি।"),
    mcq("What do reflexes do?", ["Protect you with fast automatic reactions, like pulling your hand from heat", "Make you think slowly", "Digest food", "Grow hair"], 0,
        "Reflexes skip the thinking part of the brain to save time.",
        "প্রতিবর্ত ক্রিয়া কী করে?", ["দ্রুত স্বয়ংক্রিয় প্রতিক্রিয়ায় রক্ষা করে, যেমন গরম থেকে হাত সরানো", "ধীরে ভাবায়", "খাবার হজম করে", "চুল গজায়"],
        "সময় বাঁচাতে প্রতিবর্ত মস্তিষ্কের চিন্তার অংশ এড়িয়ে যায়।"),
    mcq("Why do workers take regular breaks on long shifts?", ["Tired brains and muscles make more mistakes and injuries", "Breaks waste time", "Rules are just for fun", "Machines need workers to rest"], 0,
        "Rest restores attention - a key part of site safety.",
        "লম্বা পালায় কর্মীরা নিয়মিত বিরতি নেন কেন?", ["ক্লান্ত মস্তিষ্ক আর পেশি বেশি ভুল আর আঘাত ঘটায়", "বিরতিতে সময় নষ্ট", "নিয়ম শুধু মজার জন্য", "যন্ত্রের জন্য কর্মীদের বিশ্রাম লাগে"],
        "বিশ্রাম মনোযোগ ফেরায় - নির্মাণস্থলের নিরাপত্তার মূল অংশ।"),
    mcq("What is 'symbiosis'?", ["Two different species living closely and often helping each other", "One animal eating another", "A disease", "A type of rock"], 0,
        "Clownfish and sea anemones, or bees and flowers, help each other.",
        "'মিথোজীবিতা' কী?", ["দুটি আলাদা প্রজাতি ঘনিষ্ঠভাবে থাকে আর প্রায়ই পরস্পরকে সাহায্য করে", "একটা প্রাণী আরেকটাকে খায়", "একটা রোগ", "এক রকম পাথর"],
        "ক্লাউনফিশ আর সামুদ্রিক অ্যানিমোন, বা মৌমাছি আর ফুল পরস্পরকে সাহায্য করে।"),
    mcq("What is a 'parasite'?", ["A living thing that lives on or in another and harms it", "A helpful partner", "A plant that makes its own food", "A decomposer"], 0,
        "Ticks, lice and some worms are parasites.",
        "'পরজীবী' কী?", ["যে জীব অন্যের উপরে বা ভেতরে থেকে তার ক্ষতি করে", "উপকারী সঙ্গী", "নিজের খাদ্য তৈরি করা উদ্ভিদ", "বিয়োজক"],
        "আঁটুলি, উকুন আর কিছু কৃমি পরজীবী।"),
)
