"""Class 6 - Physics (Junior Cadet): work, power and efficiency, Ohm's law, thermal expansion of
bridge steel, sound and echoes, water pressure with depth, distance-time graphs, balanced and
unbalanced forces, heat transfer, reflection, electromagnets and energy resources."""
from . import mcq


def _o(r, *alts):
    out = []
    for x in (r, *alts, r + 10, r * 2, r + 1):
        if x not in out and x >= 0:
            out.append(x)
    return out[:4]


def _num(q_en, q_bn, r, ex_en, ex_bn, alts, u_en, u_bn):
    o = _o(r, *alts)
    f = lambda x: f"{x:,}" if isinstance(x, int) else f"{x:g}"
    return mcq(q_en, [f(x) + u_en for x in o], 0, ex_en, q_bn, [f(x) + u_bn for x in o], ex_bn)


def work(f, d, who_en, who_bn):
    r = f * d
    return _num(f"{who_en} pushes with {f:,} N through {d} m. How much work is done?",
                f"{who_bn} {f:,} N বলে {d} m ঠেলেন। কত কার্য হলো?", r,
                f"Work = force x distance = {f:,} x {d} = {r:,} J (joules).",
                f"কার্য = বল x সরণ = {f:,} x {d} = {r:,} J (জুল)।",
                (f + d, f, r // 2 if r > 2 else r + 3), " J", " J")


def power(w, t, what_en, what_bn):
    r = w // t
    return _num(f"{what_en} does {w:,} J of work in {t} s. What is its power?",
                f"{what_bn} {t} s-এ {w:,} J কার্য করে। তার ক্ষমতা কত?", r,
                f"Power = work ÷ time = {w:,} ÷ {t} = {r:,} W (watts).",
                f"ক্ষমতা = কার্য ÷ সময় = {w:,} ÷ {t} = {r:,} W (ওয়াট)।",
                (w * t, w - t, r // 2 if r > 2 else r + 3), " W", " W")


def eff(out, inp, what_en, what_bn):
    r = out * 100 // inp
    return _num(f"{what_en} takes in {inp:,} J and gives out {out:,} J of useful energy. What is its efficiency?",
                f"{what_bn} {inp:,} J নেয় আর {out:,} J দরকারি শক্তি দেয়। দক্ষতা কত?", r,
                f"Efficiency = useful out ÷ total in x 100 = {out:,} ÷ {inp:,} x 100 = {r}%. The rest is wasted, mostly as heat.",
                f"দক্ষতা = দরকারি শক্তি ÷ মোট প্রদত্ত x 100 = {out:,} ÷ {inp:,} x 100 = {r}%। বাকিটা অপচয়, বেশিরভাগ তাপ হিসেবে।",
                (100 - r, inp - out, r + 5), "%", "%")


def ohm(v, r_, what_en, what_bn):
    i = v / r_
    i = int(i) if i == int(i) else round(i, 2)
    return _num(f"{what_en} has {v} V across a {r_} Ω resistance. What current flows?",
                f"{what_bn}-এ {r_} Ω রোধের দুই প্রান্তে {v} V। কত বিদ্যুৎ-প্রবাহ চলে?", i,
                f"Ohm's law: I = V ÷ R = {v} ÷ {r_} = {i:g} A.",
                f"ওহমের সূত্র: I = V ÷ R = {v} ÷ {r_} = {i:g} A।",
                (v * r_, v + r_, round(r_ / v, 2) if r_ / v != i else i + 2), " A", " A")


def expand(length, dT):
    mm = round(length * 12 * dT / 1000, 1)  # steel: about 12 millionths per °C
    mm = int(mm) if mm == int(mm) else mm
    return _num(f"A {length} m steel bridge deck warms by {dT} °C. Steel grows about 0.012 mm per metre per °C. About how much longer does it get?",
                f"{length} m লম্বা ইস্পাতের সেতুর পাটাতন {dT} °C গরম হলো। ইস্পাত প্রতি মিটারে প্রতি °C-এ প্রায় 0.012 mm বাড়ে। মোটামুটি কত লম্বা হয়?", mm,
                f"{length} x 0.012 x {dT} = {mm:g} mm. Expansion joints must leave at least this much room.",
                f"{length} x 0.012 x {dT} = {mm:g} mm। প্রসারণ-জোড়ে অন্তত এতটা জায়গা রাখতে হয়।",
                (round(mm * 10, 1), round(mm / 10, 2), length * dT), " mm", " mm")


def echo(t, what_en, what_bn):
    d = 340 * t // 2
    return _num(f"A surveyor shouts at {what_en} and hears the echo after {t} s. Sound travels at 340 m/s. How far away is it?",
                f"একজন জরিপকারী {what_bn}-এর দিকে চিৎকার করে {t} s পরে প্রতিধ্বনি শুনলেন। শব্দের গতি 340 m/s। সেটা কত দূরে?", d,
                f"Sound goes there and back: 340 x {t} = {340 * t} m in total, so the distance is half: {d} m.",
                f"শব্দ যায় আর ফেরে: মোট 340 x {t} = {340 * t} m, তাই দূরত্ব অর্ধেক: {d} m।",
                (340 * t, 340 // t, d + 100), " m", " m")


def depthp(h):
    r = 10 * h  # kPa: rho g h = 1000 x 10 x h Pa
    return _num(f"About what extra water pressure acts on a bridge pier {h} m below the river surface? (Use 10 kPa per metre of depth.)",
                f"নদীর তল থেকে {h} m নিচে সেতুর থামে মোটামুটি কত বাড়তি জলের চাপ পড়ে? (প্রতি মিটার গভীরতায় 10 kPa ধরো।)", r,
                f"Pressure = density x g x depth ≈ 1000 x 10 x {h} = {r * 1000:,} Pa = {r} kPa.",
                f"চাপ = ঘনত্ব x g x গভীরতা ≈ 1000 x 10 x {h} = {r * 1000:,} Pa = {r} kPa।",
                (h, r * 10, r + 5), " kPa", " কিলোপ্যাসকেল")


ITEMS = (
    work(500, 4, "A worker", "একজন কর্মী"), work(2000, 3, "A winch", "একটা উইঞ্চ"),
    work(150, 10, "A cyclist", "একজন সাইকেল-আরোহী"), work(12000, 5, "A crane", "একটা ক্রেন"),
    work(80, 25, "A child pulling a cart", "গাড়ি টানা এক শিশু"),
    power(6000, 30, "A pump", "একটা পাম্প"), power(45000, 15, "A crane motor", "ক্রেনের একটা মোটর"),
    power(1200, 4, "A drill", "একটা ড্রিল"), power(90000, 60, "A lift", "একটা লিফট"),
    eff(600, 1000, "A motor", "একটা মোটর"), eff(250, 1000, "An old bulb", "একটা পুরোনো বাল্ব"),
    eff(3500, 5000, "A diesel generator", "একটা ডিজেল জেনারেটর"), eff(900, 1000, "An LED lamp", "একটা এলইডি বাতি"),
    ohm(12, 4, "A torch circuit", "একটা টর্চের বর্তনী"), ohm(230, 46, "A heater", "একটা হিটার"),
    ohm(9, 3, "A toy motor", "একটা খেলনা-মোটর"), ohm(24, 8, "A warning light", "একটা সতর্কবাতি"),
    expand(50, 30), expand(100, 40), expand(200, 25), expand(500, 20),
    echo(2, "a cliff", "একটা খাড়া পাহাড়"), echo(4, "a far river bank", "দূরের নদীর পাড়"), echo(1, "a bridge pier", "একটা সেতুর থাম"),
    depthp(5), depthp(12), depthp(20),
    mcq("What is 'work' in physics?", ["Energy transferred when a force moves something", "Any tiring job", "Thinking hard", "Standing still holding a load"], 0,
        "No movement in the direction of the force = no work done, even if you get tired!",
        "পদার্থবিদ্যায় 'কার্য' কী?", ["বল কোনো কিছুকে সরালে স্থানান্তরিত শক্তি", "যেকোনো ক্লান্তিকর কাজ", "জোরে চিন্তা করা", "বোঝা ধরে স্থির দাঁড়িয়ে থাকা"],
        "বলের দিকে সরণ না হলে কার্য নেই, ক্লান্ত লাগলেও!"),
    mcq("What is 1 joule?", ["The work done when 1 N moves something 1 m", "1 kg of mass", "1 metre per second", "1 watt for 1 hour"], 0,
        "Lifting an apple about 1 m takes about 1 J.",
        "1 জুল কী?", ["1 N বল কোনো কিছুকে 1 m সরালে কৃতকার্য", "1 kg ভর", "1 মিটার প্রতি সেকেন্ড", "1 ঘণ্টা 1 ওয়াট"],
        "একটা আপেল প্রায় 1 m তুলতে প্রায় 1 J লাগে।"),
    mcq("What does 'power' measure?", ["How fast energy is transferred or work is done", "How heavy something is", "Total energy only", "Pressure"], 0,
        "1 watt = 1 joule per second.",
        "'ক্ষমতা' কী মাপে?", ["কত দ্রুত শক্তি স্থানান্তরিত বা কার্য হয়", "কোনো কিছু কত ভারী", "শুধু মোট শক্তি", "চাপ"],
        "1 ওয়াট = সেকেন্ডে 1 জুল।"),
    mcq("Two cranes lift the same beam to the same height. Crane A takes 20 s, crane B takes 40 s. Which is more powerful?", ["Crane A", "Crane B", "They are equal", "Neither does work"], 0,
        "Same work in less time = more power.",
        "দুটো ক্রেন একই বিম একই উচ্চতায় তোলে। A নেয় 20 s, B নেয় 40 s। কোনটা বেশি ক্ষমতাশালী?", ["ক্রেন A", "ক্রেন B", "দুটো সমান", "কোনোটাই কার্য করে না"],
        "কম সময়ে একই কার্য = বেশি ক্ষমতা।"),
    mcq("What is a kilowatt-hour (kWh)?", ["The energy used by a 1,000 W device in 1 hour", "A unit of force", "A speed", "A unit of mass"], 0,
        "Electricity bills charge per kWh, often called a 'unit'.",
        "কিলোওয়াট-ঘণ্টা (kWh) কী?", ["1,000 W যন্ত্র 1 ঘণ্টায় যে শক্তি খরচ করে", "বলের একক", "গতি", "ভরের একক"],
        "বিদ্যুতের বিল kWh-প্রতি নেয়, প্রায়ই 'ইউনিট' বলা হয়।"),
    mcq("Bridge lights use 2 kW for 10 hours a night. How many kWh is that?", ["20 kWh", "12 kWh", "5 kWh", "200 kWh"], 0,
        "2 x 10 = 20 kWh.",
        "সেতুর বাতি রাতে 10 ঘণ্টা 2 kW খরচ করে। তা কত কিলোওয়াট-ঘণ্টা?", ["20 কিলোওয়াট-ঘণ্টা", "12 কিলোওয়াট-ঘণ্টা", "5 কিলোওয়াট-ঘণ্টা", "200 কিলোওয়াট-ঘণ্টা"],
        "2 x 10 = 20 কিলোওয়াট-ঘণ্টা।"),
    mcq("What does 'efficiency' tell you?", ["How much input energy becomes useful output", "How fast a machine runs", "How heavy a machine is", "Its price"], 0,
        "No machine is 100% efficient - some energy is always wasted.",
        "'দক্ষতা' কী জানায়?", ["প্রদত্ত শক্তির কতটা দরকারি শক্তিতে বদলায়", "যন্ত্র কত দ্রুত চলে", "যন্ত্র কত ভারী", "তার দাম"],
        "কোনো যন্ত্র 100% দক্ষ নয় - কিছু শক্তি সবসময় নষ্ট হয়।"),
    mcq("Where does most 'wasted' energy in machines usually go?", ["Heat, from friction", "It disappears completely", "Into extra mass", "Into light only"], 0,
        "Energy is never destroyed - it spreads out as heat and sound.",
        "যন্ত্রের বেশিরভাগ 'অপচয়' শক্তি সাধারণত কোথায় যায়?", ["ঘর্ষণ থেকে তাপে", "পুরো উধাও হয়", "বাড়তি ভরে", "শুধু আলোয়"],
        "শক্তি কখনো ধ্বংস হয় না - তাপ আর শব্দ হয়ে ছড়িয়ে পড়ে।"),
    mcq("What is Ohm's law?", ["Voltage = current x resistance (V = IR)", "Force = mass x speed", "Power = work x time", "Pressure = force x area"], 0,
        "For a fixed resistance, doubling the voltage doubles the current.",
        "ওহমের সূত্র কী?", ["ভোল্টেজ = বিদ্যুৎ-প্রবাহ x রোধ (V = IR)", "বল = ভর x গতি", "ক্ষমতা = কার্য x সময়", "চাপ = বল x ক্ষেত্রফল"],
        "স্থির রোধে ভোল্টেজ দ্বিগুণ করলে প্রবাহও দ্বিগুণ।"),
    mcq("What is the unit of resistance?", ["Ohm (Ω)", "Volt", "Ampere", "Watt"], 0,
        "Named after Georg Ohm.",
        "রোধের একক কী?", ["ওহম (Ω)", "ভোল্ট", "অ্যাম্পিয়ার", "ওয়াট"],
        "গেয়র্গ ওহমের নামে।"),
    mcq("How is electrical power calculated?", ["Power = voltage x current (P = VI)", "Power = current ÷ voltage", "Power = resistance x time", "Power = volts + amps"], 0,
        "A 230 V kettle drawing 10 A uses 2,300 W.",
        "বৈদ্যুতিক ক্ষমতা কীভাবে হিসাব হয়?", ["ক্ষমতা = ভোল্টেজ x বিদ্যুৎ-প্রবাহ (P = VI)", "ক্ষমতা = প্রবাহ ÷ ভোল্টেজ", "ক্ষমতা = রোধ x সময়", "ক্ষমতা = ভোল্ট + অ্যাম্প"],
        "230 V-এ 10 A টানা কেটলি 2,300 W খরচ করে।"),
    mcq("A 230 V site floodlight draws 2 A. What is its power?", ["460 W", "115 W", "232 W", "4,600 W"], 0,
        "P = VI = 230 x 2 = 460 W.",
        "একটা 230 V নির্মাণস্থলের ফ্লাডলাইট 2 A টানে। তার ক্ষমতা কত?", ["460 W", "115 W", "232 W", "4,600 W"],
        "P = VI = 230 x 2 = 460 W।"),
    mcq("Why do power lines carry electricity at very high voltage?", ["Less current is needed for the same power, so less energy is lost as heat", "High voltage is safer to touch", "It makes wires lighter", "No reason"], 0,
        "Transformers step voltage up for transmission and down for homes.",
        "বিদ্যুতের লাইন খুব উচ্চ ভোল্টেজে বিদ্যুৎ বয় কেন?", ["একই ক্ষমতায় কম প্রবাহ লাগে, তাই তাপে কম শক্তি নষ্ট", "উচ্চ ভোল্টেজ ছোঁয়া নিরাপদ", "তার হালকা হয়", "কোনো কারণ নেই"],
        "ট্রান্সফর্মার পরিবহনের জন্য ভোল্টেজ বাড়ায় আর বাড়ির জন্য কমায়।"),
    mcq("What is a distance-time graph's slope (steepness) telling you?", ["The speed", "The mass", "The temperature", "The colour"], 0,
        "Steeper line = faster. A flat line means stopped.",
        "দূরত্ব-সময় লেখচিত্রের ঢাল কী জানায়?", ["গতি", "ভর", "তাপমাত্রা", "রং"],
        "খাড়া রেখা = দ্রুত। সমতল রেখা মানে থেমে আছে।"),
    mcq("On a distance-time graph, a truck's line is flat for 10 minutes. What was the truck doing?", ["Stopped (for example, at a toll booth)", "Going very fast", "Going backwards", "Flying"], 0,
        "Distance did not change, so speed was zero.",
        "দূরত্ব-সময় লেখচিত্রে একটা ট্রাকের রেখা 10 মিনিট সমতল। ট্রাক কী করছিল?", ["থেমে ছিল (যেমন টোল-বুথে)", "খুব দ্রুত চলছিল", "পেছনে যাচ্ছিল", "উড়ছিল"],
        "দূরত্ব বদলায়নি, তাই গতি শূন্য।"),
    mcq("What happens to an object when the forces on it are balanced?", ["It stays still or keeps moving at a steady speed", "It always speeds up", "It always stops", "It flies upward"], 0,
        "This is Newton's first law.",
        "কোনো বস্তুর উপর বল ভারসাম্যে থাকলে কী হয়?", ["স্থির থাকে বা একটানা গতিতে চলতে থাকে", "সবসময় গতি বাড়ায়", "সবসময় থামে", "উপরে ওড়ে"],
        "এটা নিউটনের প্রথম সূত্র।"),
    mcq("A truck's engine push is bigger than air resistance and friction. What happens?", ["It speeds up", "It slows down", "It stays at the same speed", "It stops"], 0,
        "Unbalanced forces change speed or direction.",
        "ট্রাকের ইঞ্জিনের ঠেলা বায়ুর বাধা আর ঘর্ষণের চেয়ে বেশি। কী হয়?", ["গতি বাড়ে", "গতি কমে", "একই গতিতে থাকে", "থেমে যায়"],
        "অসম বল গতি বা দিক বদলায়।"),
    mcq("A parked car sits still on a bridge. What balances its weight?", ["The upward push (reaction) of the bridge deck", "Air pressure", "The car's engine", "Nothing"], 0,
        "The deck pushes up exactly as hard as the car pushes down.",
        "একটা থামানো গাড়ি সেতুর উপর স্থির। তার ওজন কী ভারসাম্যে রাখে?", ["সেতুর পাটাতনের উপরমুখী ঠেলা (প্রতিক্রিয়া)", "বায়ুর চাপ", "গাড়ির ইঞ্জিন", "কিছুই না"],
        "গাড়ি যতটা জোরে নিচে ঠেলে, পাটাতন ঠিক ততটা জোরে উপরে ঠেলে।"),
    mcq("What is Newton's third law?", ["For every action there is an equal and opposite reaction", "Force = mass x acceleration", "Objects at rest stay at rest", "Energy is conserved"], 0,
        "A bridge pier pushes up on the deck as the deck pushes down on it.",
        "নিউটনের তৃতীয় সূত্র কী?", ["প্রতিটি ক্রিয়ার সমান ও বিপরীত প্রতিক্রিয়া আছে", "বল = ভর x ত্বরণ", "স্থির বস্তু স্থির থাকে", "শক্তি সংরক্ষিত"],
        "পাটাতন থামে নিচে চাপ দিলে থাম পাটাতনকে উপরে ঠেলে।"),
    mcq("What are the three ways heat can travel?", ["Conduction, convection and radiation", "Reflection, refraction and diffraction", "Melting, freezing and boiling", "Push, pull and twist"], 0,
        "Conduction through solids, convection in fluids, radiation through space.",
        "তাপ কোন তিন উপায়ে যায়?", ["পরিবহন, পরিচলন আর বিকিরণ", "প্রতিফলন, প্রতিসরণ আর অপবর্তন", "গলা, জমা আর ফোটা", "ঠেলা, টানা আর মোচড়"],
        "কঠিনে পরিবহন, তরল-গ্যাসে পরিচলন, শূন্যস্থানে বিকিরণ।"),
    mcq("How does heat from the Sun reach a bridge deck?", ["Radiation", "Conduction through space", "Convection in space", "It does not"], 0,
        "Radiation needs no material - it crosses empty space.",
        "সূর্যের তাপ সেতুর পাটাতনে পৌঁছায় কীভাবে?", ["বিকিরণে", "শূন্যস্থানে পরিবহনে", "মহাকাশে পরিচলনে", "পৌঁছায় না"],
        "বিকিরণে মাধ্যম লাগে না - এটা ফাঁকা স্থান পেরোয়।"),
    mcq("Why does warm air rise in a room?", ["Warm air is less dense, so it floats up - convection", "Warm air is heavier", "Ceilings attract air", "It does not"], 0,
        "Convection currents carry heat around rooms and the atmosphere.",
        "ঘরে গরম বাতাস ওঠে কেন?", ["গরম বাতাস কম ঘন, তাই উপরে ভাসে - পরিচলন", "গরম বাতাস ভারী", "ছাদ বাতাস টানে", "ওঠে না"],
        "পরিচলন-স্রোত ঘর আর বায়ুমণ্ডলে তাপ বয়।"),
    mcq("Why are bridge cables sometimes painted white or light grey?", ["Light colours reflect sunlight, so cables heat and expand less", "White steel is stronger", "To attract birds", "Paint is free"], 0,
        "Less heating means less thermal movement.",
        "সেতুর তার কখনো সাদা বা হালকা ধূসর রং করা হয় কেন?", ["হালকা রং রোদ প্রতিফলিত করে, তাই তার কম গরম আর কম প্রসারিত হয়", "সাদা ইস্পাত বেশি শক্ত", "পাখি টানতে", "রং বিনামূল্যে"],
        "কম গরম মানে কম তাপীয় নড়াচড়া।"),
    mcq("Why do concrete roads have cut joints every few metres?", ["To control where cracks form as the concrete shrinks and expands", "For decoration", "To drain oil", "To slow cars"], 0,
        "Planned joints stop random cracking.",
        "কংক্রিটের রাস্তায় কয়েক মিটার অন্তর কাটা জোড় থাকে কেন?", ["কংক্রিট সংকোচন-প্রসারণে কোথায় ফাটবে তা নিয়ন্ত্রণ করতে", "সাজসজ্জার জন্য", "তেল বের করতে", "গাড়ি ধীর করতে"],
        "পরিকল্পিত জোড় এলোমেলো ফাটল আটকায়।"),
    mcq("Steel and concrete expand by almost the same amount when heated. Why is that lucky?", ["Reinforced concrete does not crack apart when temperature changes", "It makes them cheaper", "It makes them magnetic", "It does not matter"], 0,
        "If they expanded differently, the bond would break.",
        "গরম হলে ইস্পাত আর কংক্রিট প্রায় সমান প্রসারিত হয়। এটা সৌভাগ্য কেন?", ["তাপমাত্রা বদলালে রড-কংক্রিট আলাদা হয়ে ফাটে না", "সস্তা হয়", "চুম্বকীয় হয়", "কিছু যায় আসে না"],
        "আলাদা হারে প্রসারিত হলে বন্ধন ভেঙে যেত।"),
    mcq("What is the speed of sound in air, roughly?", ["About 340 m/s", "About 3 m/s", "About 300,000 km/s", "About 34 km/s"], 0,
        "Light travels about 900,000 times faster.",
        "বাতাসে শব্দের গতি মোটামুটি কত?", ["প্রায় 340 m/s", "প্রায় 3 m/s", "প্রায় 3,00,000 km/s", "প্রায় 34 km/s"],
        "আলো প্রায় 9,00,000 গুণ দ্রুত চলে।"),
    mcq("How do ships and survey boats measure river depth?", ["Sonar - timing sound echoes from the riverbed", "With a thermometer", "By guessing", "With a magnet"], 0,
        "Engineers map the riverbed before placing bridge piers.",
        "জাহাজ আর জরিপ-নৌকা নদীর গভীরতা কীভাবে মাপে?", ["সোনার - নদীতল থেকে শব্দের প্রতিধ্বনির সময় মেপে", "থার্মোমিটার দিয়ে", "আন্দাজে", "চুম্বক দিয়ে"],
        "সেতুর থাম বসানোর আগে প্রকৌশলীরা নদীতলের মানচিত্র বানান।"),
    mcq("What is 'frequency' of a sound?", ["How many vibrations happen each second, in hertz (Hz)", "How loud it is", "How far it travels", "Its colour"], 0,
        "Humans hear roughly 20 Hz to 20,000 Hz.",
        "শব্দের 'কম্পাঙ্ক' কী?", ["প্রতি সেকেন্ডে কতবার কম্পন হয়, হার্ৎজে (Hz)", "কত জোরালো", "কত দূর যায়", "তার রং"],
        "মানুষ মোটামুটি 20 Hz থেকে 20,000 Hz শোনে।"),
    mcq("What is 'ultrasound'?", ["Sound too high-pitched for humans to hear", "Very loud sound", "Light from the Sun", "Sound under water only"], 0,
        "Ultrasound testing finds hidden cracks inside steel welds.",
        "'আলট্রাসাউন্ড' কী?", ["মানুষের শোনার পক্ষে অতি তীক্ষ্ণ শব্দ", "খুব জোরালো শব্দ", "সূর্যের আলো", "শুধু জলের নিচের শব্দ"],
        "আলট্রাসাউন্ড-পরীক্ষা ইস্পাতের ঝালাইয়ের ভেতরের লুকোনো ফাটল খোঁজে।"),
    mcq("How is noise measured?", ["In decibels (dB)", "In newtons", "In metres", "In watts per kg"], 0,
        "Above about 85 dB for long periods, hearing protection is needed.",
        "শব্দের মাত্রা কীসে মাপা হয়?", ["ডেসিবেলে (dB)", "নিউটনে", "মিটারে", "কেজিপ্রতি ওয়াটে"],
        "দীর্ঘ সময় প্রায় 85 dB-এর বেশিতে কান-রক্ষাকারী লাগে।"),
    mcq("When light reflects off a flat mirror, how do the angles compare?", ["Angle of incidence equals angle of reflection", "Reflection is always 90°", "Incidence is double", "They are unrelated"], 0,
        "This law lets engineers aim reflectors and traffic mirrors.",
        "সমতল আয়নায় আলো প্রতিফলিত হলে কোণগুলো কেমন?", ["আপতন কোণ = প্রতিফলন কোণ", "প্রতিফলন সবসময় 90°", "আপতন দ্বিগুণ", "সম্পর্ক নেই"],
        "এই সূত্র দিয়ে প্রকৌশলীরা প্রতিফলক আর রাস্তার আয়না তাক করেন।"),
    mcq("A light ray hits a mirror at 35° to the normal. At what angle does it reflect?", ["35°", "55°", "90°", "70°"], 0,
        "i = r.",
        "একটা আলোকরশ্মি অভিলম্বের সঙ্গে 35° কোণে আয়নায় পড়ল। কত কোণে প্রতিফলিত হবে?", ["35°", "55°", "90°", "70°"],
        "আপতন = প্রতিফলন।"),
    mcq("What is the 'normal' in a reflection diagram?", ["A line at 90° to the mirror where the ray hits", "The mirror itself", "The reflected ray", "Any ordinary line"], 0,
        "Angles are measured from the normal.",
        "প্রতিফলনের চিত্রে 'অভিলম্ব' কী?", ["রশ্মি যেখানে পড়ে সেখানে আয়নার সঙ্গে 90° রেখা", "আয়না নিজে", "প্রতিফলিত রশ্মি", "যেকোনো সাধারণ রেখা"],
        "কোণ অভিলম্ব থেকে মাপা হয়।"),
    mcq("Why do optical fibres carry internet signals so well?", ["Light bounces along inside the glass by total internal reflection", "Glass is magnetic", "Light turns into electricity in glass", "They do not"], 0,
        "Many modern bridges carry fibre cables and sensors inside.",
        "অপটিক্যাল ফাইবার ইন্টারনেট-সংকেত এত ভালো বয় কেন?", ["পূর্ণ অভ্যন্তরীণ প্রতিফলনে আলো কাচের ভেতর ধরে লাফিয়ে চলে", "কাচ চুম্বকীয়", "কাচে আলো বিদ্যুতে বদলায়", "বয় না"],
        "অনেক আধুনিক সেতুর ভেতরে ফাইবার-তার আর সেন্সর থাকে।"),
    mcq("How can you make an electromagnet stronger?", ["More turns of wire, more current, or an iron core", "Use plastic wire", "Use less current", "Paint it red"], 0,
        "Electromagnets in cranes lift scrap steel.",
        "তড়িৎচুম্বক আরও শক্তিশালী করবে কীভাবে?", ["তারের বেশি পাক, বেশি প্রবাহ বা লোহার মজ্জা", "প্লাস্টিকের তার", "কম প্রবাহ", "লাল রং"],
        "ক্রেনের তড়িৎচুম্বক লোহার টুকরো তোলে।"),
    mcq("What does an electric motor do?", ["Turns electrical energy into movement", "Turns movement into electricity", "Stores electricity", "Makes light only"], 0,
        "Motors use magnets and current-carrying coils.",
        "বৈদ্যুতিক মোটর কী করে?", ["বিদ্যুৎশক্তিকে গতিতে বদলায়", "গতিকে বিদ্যুতে বদলায়", "বিদ্যুৎ জমায়", "শুধু আলো তৈরি করে"],
        "মোটর চুম্বক আর বিদ্যুৎবাহী কুণ্ডলী ব্যবহার করে।"),
    mcq("What does a generator do?", ["Turns movement into electrical energy", "Turns electricity into movement", "Stores heat", "Measures voltage"], 0,
        "Spinning a coil near a magnet makes current.",
        "জেনারেটর কী করে?", ["গতিকে বিদ্যুৎশক্তিতে বদলায়", "বিদ্যুৎকে গতিতে বদলায়", "তাপ জমায়", "ভোল্টেজ মাপে"],
        "চুম্বকের কাছে কুণ্ডলী ঘোরালে বিদ্যুৎ তৈরি হয়।"),
    mcq("How does a hydroelectric dam produce electricity?", ["Falling water spins turbines connected to generators", "Water is burned", "Fish swim through magnets", "Sunlight hits the water"], 0,
        "Stored potential energy -> kinetic energy -> electricity.",
        "জলবিদ্যুৎ-বাঁধ কীভাবে বিদ্যুৎ তৈরি করে?", ["পড়ন্ত জল জেনারেটরে জোড়া টারবাইন ঘোরায়", "জল পোড়ানো হয়", "মাছ চুম্বকের মধ্য দিয়ে সাঁতরায়", "রোদ জলে পড়ে"],
        "সঞ্চিত স্থিতিশক্তি -> গতিশক্তি -> বিদ্যুৎ।"),
    mcq("Which energy resource is non-renewable?", ["Natural gas", "Wind", "Solar", "Hydroelectric"], 0,
        "Gas, coal and oil will run out; wind, sun and flowing water will not.",
        "কোন শক্তির উৎস অনবীকরণযোগ্য?", ["প্রাকৃতিক গ্যাস", "বাতাস", "সৌর", "জলবিদ্যুৎ"],
        "গ্যাস, কয়লা আর তেল ফুরোবে; বাতাস, রোদ আর প্রবাহিত জল নয়।"),
    mcq("Why are wind turbines placed on hills or offshore?", ["Winds are stronger and steadier there", "Hills are cheaper", "To hide them", "Birds prefer it"], 0,
        "Doubling wind speed gives about 8 times the power.",
        "বায়ুকল পাহাড়ে বা সমুদ্রে বসানো হয় কেন?", ["সেখানে বাতাস বেশি জোরালো আর স্থির", "পাহাড় সস্তা", "লুকাতে", "পাখি পছন্দ করে"],
        "বাতাসের গতি দ্বিগুণ হলে ক্ষমতা প্রায় 8 গুণ।"),
    mcq("A solar panel gives 300 W for 5 sunny hours. How much energy is that?", ["1.5 kWh", "15 kWh", "0.3 kWh", "305 kWh"], 0,
        "300 x 5 = 1,500 Wh = 1.5 kWh.",
        "একটা সৌর প্যানেল 5 ঘণ্টা রোদে 300 W দেয়। তা কত শক্তি?", ["1.5 কিলোওয়াট-ঘণ্টা", "15 কিলোওয়াট-ঘণ্টা", "0.3 কিলোওয়াট-ঘণ্টা", "305 কিলোওয়াট-ঘণ্টা"],
        "300 x 5 = 1,500 ওয়াট-ঘণ্টা = 1.5 কিলোওয়াট-ঘণ্টা।"),
    mcq("What is gravitational potential energy?", ["Energy stored because of an object's height", "Energy of moving objects", "Heat energy", "Sound energy"], 0,
        "GPE = mass x g x height.",
        "মাধ্যাকর্ষণজনিত স্থিতিশক্তি কী?", ["উচ্চতার জন্য বস্তুতে সঞ্চিত শক্তি", "চলমান বস্তুর শক্তি", "তাপশক্তি", "শব্দশক্তি"],
        "স্থিতিশক্তি = ভর x g x উচ্চতা।"),
    mcq("A 50 kg bag of cement is lifted 10 m (g = 10 N/kg). How much potential energy does it gain?", ["5,000 J", "500 J", "60 J", "50,000 J"], 0,
        "50 x 10 x 10 = 5,000 J.",
        "50 kg সিমেন্টের বস্তা 10 m তোলা হলো (g = 10 N/kg)। কত স্থিতিশক্তি বাড়ল?", ["5,000 J", "500 J", "60 J", "50,000 J"],
        "50 x 10 x 10 = 5,000 J।"),
    mcq("What happens to a falling hammer's energy just before it hits the ground?", ["Most potential energy has become kinetic energy", "It has no energy", "It has only potential energy", "It becomes lighter"], 0,
        "That is why dropped tools are so dangerous on sites.",
        "মাটিতে পড়ার ঠিক আগে পড়ন্ত হাতুড়ির শক্তির কী হয়?", ["বেশিরভাগ স্থিতিশক্তি গতিশক্তি হয়ে গেছে", "কোনো শক্তি নেই", "শুধু স্থিতিশক্তি", "হালকা হয়"],
        "তাই নির্মাণস্থলে পড়ে যাওয়া যন্ত্র এত বিপজ্জনক।"),
    mcq("Why are toe-boards fitted along scaffold edges?", ["To stop tools and materials falling on people below", "To rest feet", "For decoration", "To hold paint"], 0,
        "Falling objects are a major hazard.",
        "ভারার কিনারায় পায়ের তক্তা (টো-বোর্ড) লাগানো হয় কেন?", ["নিচের মানুষের উপর যন্ত্র আর মাল পড়া আটকাতে", "পা রাখতে", "সাজসজ্জার জন্য", "রং ধরে রাখতে"],
        "পড়ন্ত জিনিস একটা বড় বিপদ।"),
    mcq("What is 'stiffness' of a beam?", ["How much it resists bending under load", "Its colour", "Its temperature", "Its price"], 0,
        "A stiff bridge deflects only a little - bouncy decks feel unsafe.",
        "বিমের 'দৃঢ়তা' কী?", ["বোঝার অধীনে বাঁকার বিরুদ্ধে কতটা প্রতিরোধ করে", "তার রং", "তার তাপমাত্রা", "তার দাম"],
        "দৃঢ় সেতু সামান্যই বাঁকে - লাফানো পাটাতন অনিরাপদ লাগে।"),
    mcq("Doubling the depth of a rectangular beam makes it about how much stiffer?", ["About 8 times", "About 2 times", "About the same", "Half as stiff"], 0,
        "Stiffness grows with depth cubed (2³ = 8) - depth is the best way to add stiffness.",
        "আয়তাকার বিমের গভীরতা দ্বিগুণ করলে মোটামুটি কত গুণ দৃঢ় হয়?", ["প্রায় 8 গুণ", "প্রায় 2 গুণ", "প্রায় একই", "অর্ধেক দৃঢ়"],
        "দৃঢ়তা গভীরতার ঘনের সঙ্গে বাড়ে (2³ = 8) - গভীরতাই দৃঢ়তা বাড়ানোর সেরা উপায়।"),
    mcq("Why is a plank stronger when stood on its edge than laid flat?", ["Its depth in the direction of bending is much bigger", "It becomes lighter", "Wood fibres turn", "It is not stronger"], 0,
        "The same material resists bending far better when deep.",
        "তক্তা চ্যাপ্টা না রেখে কিনারায় খাড়া রাখলে বেশি শক্ত কেন?", ["বাঁকার দিকে তার গভীরতা অনেক বেশি", "হালকা হয়", "কাঠের তন্তু ঘোরে", "শক্ত নয়"],
        "একই উপাদান গভীর হলে অনেক ভালো বাঁকা ঠেকায়।"),
    mcq("What is 'deflection' in a bridge?", ["How far it bends down under load", "Bouncing light", "A change of colour", "A traffic diversion"], 0,
        "Engineers limit deflection, often to span ÷ 360 or similar.",
        "সেতুর 'বিক্ষেপ' (ডিফ্লেকশন) কী?", ["বোঝার অধীনে কতটা নিচে বাঁকে", "আলোর লাফ", "রঙের বদল", "যানবাহনের ঘুরপথ"],
        "প্রকৌশলীরা বিক্ষেপ সীমিত রাখেন, প্রায়ই স্প্যান ÷ 360 বা এমন কিছু।"),
    mcq("Using a limit of span ÷ 360, what is the maximum deflection for a 36 m span?", ["0.1 m (100 mm)", "1 m", "10 m", "0.01 m"], 0,
        "36 ÷ 360 = 0.1 m.",
        "স্প্যান ÷ 360 সীমা ধরলে 36 m স্প্যানে সর্বোচ্চ বিক্ষেপ কত?", ["0.1 m (100 mm)", "1 m", "10 m", "0.01 m"],
        "36 ÷ 360 = 0.1 m।"),
    mcq("What is the 'natural frequency' of a structure?", ["The rate at which it likes to vibrate when disturbed", "How often it is painted", "Its age", "The traffic count"], 0,
        "If walking or wind matches it, resonance can cause big swaying.",
        "কাঠামোর 'স্বাভাবিক কম্পাঙ্ক' কী?", ["বিচলিত হলে যে হারে সে কাঁপতে চায়", "কতবার রং হয়", "তার বয়স", "যানবাহনের সংখ্যা"],
        "হাঁটা বা বাতাস এর সঙ্গে মিললে অনুনাদে বড় দোলা হতে পারে।"),
    mcq("London's Millennium Bridge wobbled on opening day in 2000. Why?", ["Crowds' footsteps fell into step with its sideways sway", "It was made of rubber", "An earthquake hit", "Boats hit it"], 0,
        "Dampers were added to fix it.",
        "লন্ডনের মিলেনিয়াম ব্রিজ 2000 সালে উদ্বোধনের দিন দুলেছিল। কেন?", ["ভিড়ের পা তার পাশাপাশি দোলার সঙ্গে তালে মিলে গিয়েছিল", "রবারের তৈরি ছিল", "ভূমিকম্প হয়েছিল", "নৌকা ধাক্কা দিয়েছিল"],
        "সারাতে ড্যাম্পার লাগানো হয়েছিল।"),
    mcq("What does a 'damper' do on a bridge?", ["Absorbs vibration energy to reduce swaying", "Makes it wet", "Adds weight only", "Lights the deck"], 0,
        "Like shock absorbers in a car.",
        "সেতুতে 'ড্যাম্পার' কী করে?", ["দোলা কমাতে কম্পনের শক্তি শোষণ করে", "ভিজিয়ে দেয়", "শুধু ওজন বাড়ায়", "পাটাতন আলোকিত করে"],
        "গাড়ির শক-অ্যাবজর্বারের মতো।"),
    mcq("What is 'momentum'?", ["Mass x velocity - how hard a moving object is to stop", "Speed only", "Mass only", "A type of force meter"], 0,
        "A loaded truck has huge momentum, so crash barriers must be strong.",
        "'ভরবেগ' কী?", ["ভর x বেগ - চলমান বস্তুকে থামানো কত কঠিন", "শুধু গতি", "শুধু ভর", "এক রকম বলমাপক"],
        "বোঝাই ট্রাকের বিশাল ভরবেগ, তাই সংঘর্ষ-বাধা শক্ত হতে হয়।"),
    mcq("A 2,000 kg car moves at 15 m/s. What is its momentum?", ["30,000 kg m/s", "2,015 kg m/s", "133 kg m/s", "3,000 kg m/s"], 0,
        "p = mv = 2,000 x 15 = 30,000 kg m/s.",
        "একটা 2,000 kg গাড়ি 15 m/s বেগে চলছে। তার ভরবেগ কত?", ["30,000 kg m/s", "2,015 kg m/s", "133 kg m/s", "3,000 kg m/s"],
        "p = mv = 2,000 x 15 = 30,000 kg m/s।"),
    mcq("Why do bridge crash barriers bend and crumple a little when hit?", ["Crumpling spreads the stopping over more time, reducing the force", "To look damaged", "They are weak by mistake", "They do not"], 0,
        "Longer stopping time = smaller force on the people inside.",
        "আঘাত লাগলে সেতুর সংঘর্ষ-বাধা একটু বাঁকে আর দুমড়ে যায় কেন?", ["দুমড়ানো থামাকে বেশি সময়ে ছড়ায়, বল কমায়", "ক্ষতিগ্রস্ত দেখাতে", "ভুল করে দুর্বল", "যায় না"],
        "বেশি থামার সময় = ভেতরের মানুষের উপর কম বল।"),
    work(300, 6, "A porter carrying sacks", "বস্তা বওয়া একজন কুলি"), work(5000, 2, "A hydraulic jack", "একটা হাইড্রলিক জ্যাক"),
    power(24000, 8, "A concrete pump", "একটা কংক্রিট-পাম্প"), power(3000, 6, "A hand winch", "একটা হাতে-চালানো উইঞ্চ"),
    eff(400, 500, "An electric hoist", "একটা বৈদ্যুতিক উত্তোলক"), eff(150, 600, "A petrol engine", "একটা পেট্রোল ইঞ্জিন"),
    ohm(6, 2, "A bicycle lamp", "একটা সাইকেলের বাতি"), ohm(110, 22, "A site heater", "নির্মাণস্থলের একটা হিটার"),
    expand(80, 35), expand(300, 30),
    echo(3, "a tall dam wall", "একটা উঁচু বাঁধের দেওয়াল"),
    depthp(8), depthp(30),
    mcq("What is 'acceleration' measured in?", ["Metres per second squared (m/s²)", "Metres per second", "Newtons", "Joules"], 0,
        "It is the change in velocity each second.",
        "'ত্বরণ' কীসে মাপা হয়?", ["মিটার প্রতি বর্গ-সেকেন্ড (m/s²)", "মিটার প্রতি সেকেন্ড", "নিউটন", "জুল"],
        "প্রতি সেকেন্ডে বেগের পরিবর্তন।"),
    mcq("A train goes from 0 to 20 m/s in 10 s. What is its acceleration?", ["2 m/s²", "200 m/s²", "0.5 m/s²", "30 m/s²"], 0,
        "a = change in speed ÷ time = 20 ÷ 10 = 2 m/s².",
        "একটা ট্রেন 10 s-এ 0 থেকে 20 m/s হলো। তার ত্বরণ কত?", ["2 m/s²", "200 m/s²", "0.5 m/s²", "30 m/s²"],
        "a = গতির পরিবর্তন ÷ সময় = 20 ÷ 10 = 2 m/s²।"),
    mcq("Why does a thermos flask keep tea hot?", ["Its vacuum layer and shiny walls cut conduction, convection and radiation", "It heats the tea", "It is magnetic", "It is made of ice"], 0,
        "Good insulation blocks all three ways heat travels.",
        "থার্মোফ্লাস্ক চা গরম রাখে কেন?", ["শূন্যস্থানের স্তর আর চকচকে দেওয়াল পরিবহন, পরিচলন আর বিকিরণ কমায়", "চা গরম করে", "চুম্বকীয়", "বরফের তৈরি"],
        "ভালো অন্তরণ তাপের তিনটি পথই আটকায়।"),
    mcq("What is 'velocity'?", ["Speed in a particular direction", "Speed only", "Mass in motion", "Force per area"], 0,
        "A car going round a bend at steady speed is changing velocity.",
        "'বেগ' কী?", ["নির্দিষ্ট দিকে গতি", "শুধু গতি", "চলমান ভর", "ক্ষেত্রফলপ্রতি বল"],
        "স্থির গতিতে বাঁক নেওয়া গাড়ির বেগ বদলাচ্ছে।"),
)
