"""Class 6 - Biology (Junior Cadet): specialised cells, diffusion and osmosis, enzymes and
digestion, gas exchange, double circulation and cardiac output, body levers, limiting factors in
photosynthesis, field sampling with quadrats, magnification, BMI, genes and inheritance,
classification, and pollution indicators near bridge sites."""
from . import mcq


def _o(r, *alts):
    out = []
    for x in (r, *alts, r + 1, r + 2, r * 2, r + 10):
        if x not in out and x > 0:
            out.append(x)
    return out[:4]


def _n(q_en, q_bn, r, ex_en, ex_bn, alts, u_en="", u_bn=""):
    f = lambda x: f"{x:,}" if isinstance(x, int) else f"{x:g}"
    o = _o(r, *alts)
    return mcq(q_en, [f(x) + u_en for x in o], 0, ex_en, q_bn, [f(x) + u_bn for x in o], ex_bn)


def quadrat(total, n, field):
    mean = total / n
    est = int(mean * field)
    return _n(f"A student counts {total} daisies in {n} quadrats of 1 m² each, in a {field} m² field by a bridge. Estimate the daisies in the whole field.",
              f"একজন ছাত্র সেতুর পাশের {field} m² মাঠে 1 m²-এর {n}টি কোয়াড্র্যাটে মোট {total}টি ডেইজি গুনল। গোটা মাঠে কতগুলো ডেইজি আন্দাজ করো।", est,
              f"Mean per m² = {total} ÷ {n} = {mean:g}; x {field} m² = {est:,}.",
              f"প্রতি m²-এ গড় = {total} ÷ {n} = {mean:g}; x {field} m² = {est:,}।",
              (total * field, int(mean), total + field))


def mag(image_mm, actual_um):
    m = image_mm * 1000 // actual_um
    return _n(f"A cell is {actual_um} micrometres (µm) across. In a drawing it measures {image_mm} mm. What is the magnification?",
              f"একটা কোষের প্রস্থ {actual_um} মাইক্রোমিটার (µm)। ছবিতে তা {image_mm} mm। বিবর্ধন কত?", m,
              f"Convert: {image_mm} mm = {image_mm * 1000} µm. Magnification = image ÷ actual = {image_mm * 1000} ÷ {actual_um} = x{m}.",
              f"একক বদলাও: {image_mm} mm = {image_mm * 1000} µm। বিবর্ধন = ছবি ÷ প্রকৃত = {image_mm * 1000} ÷ {actual_um} = x{m}।",
              (image_mm // actual_um if image_mm >= actual_um else m // 10, m * 10, image_mm * actual_um), "", "")


def bmi(kg, cm):
    m = cm / 100
    r = round(kg / (m * m), 1)
    r = int(r) if r == int(r) else r
    return _n(f"A worker weighs {kg} kg and is {cm} cm tall. What is their BMI (kg ÷ height in m²)?",
              f"একজন কর্মীর ওজন {kg} kg আর উচ্চতা {cm} cm। তাঁর বিএমআই (kg ÷ উচ্চতা m²) কত?", r,
              f"{cm} cm = {m:g} m; {m:g}² = {round(m * m, 4):g}; {kg} ÷ {round(m * m, 4):g} ≈ {r:g}. 18.5-25 is a healthy range for most adults.",
              f"{cm} cm = {m:g} m; {m:g}² = {round(m * m, 4):g}; {kg} ÷ {round(m * m, 4):g} ≈ {r:g}। বেশিরভাগ বড়দের জন্য 18.5-25 সুস্থ পরিসর।",
              (round(kg / m, 1), round(kg / cm * 10, 1), r + 5))


def cardiac(sv, hr):
    co = sv * hr
    return _n(f"A heart pumps {sv} ml per beat at {hr} beats per minute. What is the cardiac output?",
              f"একটা হৃৎপিণ্ড প্রতি স্পন্দনে {sv} ml পাম্প করে, মিনিটে {hr}বার। হৃৎ-উৎপাদ কত?", co,
              f"Cardiac output = stroke volume x heart rate = {sv} x {hr} = {co:,} ml per minute ({co / 1000:g} litres).",
              f"হৃৎ-উৎপাদ = প্রতি স্পন্দনের আয়তন x হৃৎস্পন্দনের হার = {sv} x {hr} = মিনিটে {co:,} ml ({co / 1000:g} লিটার)।",
              (sv + hr, co // 2, co + sv), " ml/min", " ml/মিনিট")


ITEMS = (
    quadrat(30, 10, 500), quadrat(48, 8, 1200), quadrat(15, 5, 800), quadrat(72, 12, 2000), quadrat(20, 10, 650),
    mag(10, 100), mag(50, 25), mag(30, 10), mag(8, 40), mag(12, 6),
    bmi(60, 170), bmi(72, 180), bmi(50, 160), bmi(81, 180),
    cardiac(70, 72), cardiac(80, 60), cardiac(100, 120), cardiac(65, 80),
    mcq("Why do red blood cells have no nucleus and a dimpled disc shape?", ["More room for haemoglobin and a big surface for oxygen to pass", "To look pretty", "To fight germs", "They have a nucleus"], 0,
        "Their shape fits their job - just as a beam's shape fits its load.",
        "লোহিত রক্তকণিকায় নিউক্লিয়াস নেই আর টোল-খাওয়া চাকতির আকার কেন?", ["হিমোগ্লোবিনের বেশি জায়গা আর অক্সিজেন যাওয়ার বড় তল", "সুন্দর দেখাতে", "জীবাণুর সঙ্গে লড়তে", "নিউক্লিয়াস আছে"],
        "আকার কাজের সঙ্গে মানানসই - বিমের আকার যেমন তার বোঝার সঙ্গে।"),
    mcq("Why are nerve cells very long?", ["To carry signals quickly over long distances in the body", "To store fat", "To make blood", "They are short"], 0,
        "Some nerve cells reach from your spine to your toes.",
        "স্নায়ুকোষ খুব লম্বা কেন?", ["শরীরের লম্বা দূরত্বে দ্রুত সংকেত বইতে", "চর্বি জমাতে", "রক্ত তৈরি করতে", "ছোট হয়"],
        "কিছু স্নায়ুকোষ মেরুদণ্ড থেকে পায়ের আঙুল পর্যন্ত যায়।"),
    mcq("Why do root hair cells have long thin extensions?", ["To increase surface area for absorbing water and minerals", "To anchor flowers", "To make food from light", "To store seeds"], 0,
        "More surface = faster absorption.",
        "মূলরোম কোষে লম্বা সরু প্রসারণ থাকে কেন?", ["জল আর খনিজ শোষণে তলের ক্ষেত্রফল বাড়াতে", "ফুল আটকাতে", "আলো থেকে খাদ্য তৈরি করতে", "বীজ জমাতে"],
        "বেশি তল = দ্রুত শোষণ।"),
    mcq("What is 'osmosis'?", ["Water moving through a partly permeable membrane from dilute to concentrated solution", "Gas spreading in air", "Food being digested", "Light being absorbed"], 0,
        "It is why salted vegetables release water.",
        "'অভিস্রবণ' কী?", ["অর্ধভেদ্য পর্দার মধ্য দিয়ে লঘু থেকে গাঢ় দ্রবণে জলের চলাচল", "বাতাসে গ্যাস ছড়ানো", "খাবার হজম", "আলো শোষণ"],
        "এই কারণেই লবণ মাখানো সবজি থেকে জল বেরোয়।"),
    mcq("Why do plant cells not burst when they take in lots of water?", ["The strong cell wall resists the pressure", "They have no water", "They leak", "They do burst"], 0,
        "Like a tyre's casing holding air pressure.",
        "অনেক জল নিলেও উদ্ভিদকোষ ফাটে না কেন?", ["শক্ত কোষপ্রাচীর চাপ সামলায়", "তাদের জল নেই", "চুঁইয়ে পড়ে", "ফাটে"],
        "টায়ারের খোল যেমন বাতাসের চাপ ধরে রাখে।"),
    mcq("What are 'enzymes'?", ["Biological catalysts that speed up reactions in the body", "Types of bone", "Blood cells", "Vitamins"], 0,
        "Digestive enzymes break big food molecules into small ones.",
        "'উৎসেচক' (এনজাইম) কী?", ["জৈব অনুঘটক যা শরীরের বিক্রিয়া দ্রুত করে", "এক রকম হাড়", "রক্তকণিকা", "ভিটামিন"],
        "পরিপাক-উৎসেচক বড় খাদ্য-অণুকে ছোট অণুতে ভাঙে।"),
    mcq("Which enzyme breaks down starch into sugar?", ["Amylase", "Protease", "Lipase", "Haemoglobin"], 0,
        "Amylase is in saliva - chew bread for a while and it tastes sweeter.",
        "কোন উৎসেচক শ্বেতসারকে চিনিতে ভাঙে?", ["অ্যামাইলেজ", "প্রোটিয়েজ", "লাইপেজ", "হিমোগ্লোবিন"],
        "অ্যামাইলেজ লালায় থাকে - রুটি কিছুক্ষণ চিবোলে মিষ্টি লাগে।"),
    mcq("What does protease digest?", ["Proteins into amino acids", "Fats into fatty acids", "Starch into sugar", "Water into air"], 0,
        "Proteins come from dal, eggs, fish and milk.",
        "প্রোটিয়েজ কী হজম করে?", ["প্রোটিনকে অ্যামাইনো অ্যাসিডে", "চর্বিকে ফ্যাটি অ্যাসিডে", "শ্বেতসারকে চিনিতে", "জলকে বাতাসে"],
        "প্রোটিন আসে ডাল, ডিম, মাছ আর দুধ থেকে।"),
    mcq("What does lipase digest?", ["Fats and oils", "Proteins", "Starch", "Fibre"], 0,
        "Bile from the liver helps by breaking fat into small droplets.",
        "লাইপেজ কী হজম করে?", ["চর্বি আর তেল", "প্রোটিন", "শ্বেতসার", "আঁশ"],
        "যকৃতের পিত্ত চর্বিকে ছোট ফোঁটায় ভেঙে সাহায্য করে।"),
    mcq("Why do enzymes stop working if they get too hot?", ["Their shape changes (they denature) so they no longer fit their target", "They melt into metal", "They freeze", "They multiply"], 0,
        "Shape matters - like a key that has been bent.",
        "খুব গরম হলে উৎসেচক কাজ থামায় কেন?", ["তাদের আকার বদলে যায় (বিকৃত হয়) তাই লক্ষ্যের সঙ্গে আর মেলে না", "গলে ধাতু হয়", "জমে যায়", "সংখ্যায় বাড়ে"],
        "আকার জরুরি - বেঁকে যাওয়া চাবির মতো।"),
    mcq("Where does gas exchange happen in the lungs?", ["In tiny air sacs called alveoli", "In the windpipe", "In the stomach", "In the ribs"], 0,
        "Alveoli have a huge total surface area - about a tennis court.",
        "ফুসফুসে গ্যাস বিনিময় কোথায় হয়?", ["অ্যালভিওলাই নামের ক্ষুদ্র বায়ুথলিতে", "শ্বাসনালীতে", "পাকস্থলীতে", "পাঁজরে"],
        "অ্যালভিওলাইয়ের মোট তল বিশাল - প্রায় একটা টেনিস কোর্ট।"),
    mcq("Why are alveoli walls only one cell thick?", ["So gases diffuse across quickly", "To save energy", "To stay warm", "To store air"], 0,
        "Short distance = fast diffusion.",
        "অ্যালভিওলাইয়ের দেওয়াল মাত্র এক কোষ পুরু কেন?", ["যাতে গ্যাস দ্রুত পেরিয়ে ব্যাপিত হয়", "শক্তি বাঁচাতে", "গরম থাকতে", "বাতাস জমাতে"],
        "কম দূরত্ব = দ্রুত ব্যাপন।"),
    mcq("What is 'double circulation' in humans?", ["Blood passes through the heart twice per full circuit: to the lungs and to the body", "Two hearts", "Blood flowing backwards", "Two kinds of blood"], 0,
        "The right side pumps to the lungs, the left side to the body.",
        "মানুষের 'দ্বি-সংবহন' কী?", ["এক পূর্ণ চক্রে রক্ত দুবার হৃৎপিণ্ড পেরোয়: ফুসফুসে আর শরীরে", "দুটো হৃৎপিণ্ড", "উল্টো দিকে রক্তপ্রবাহ", "দুই রকম রক্ত"],
        "ডান দিক ফুসফুসে আর বাঁ দিক শরীরে পাম্প করে।"),
    mcq("Why is the left side of the heart's wall thicker than the right?", ["It must pump blood all around the body at higher pressure", "It is older", "It stores fat", "It is not thicker"], 0,
        "The right side only pumps to the nearby lungs.",
        "হৃৎপিণ্ডের বাঁ দিকের দেওয়াল ডান দিকের চেয়ে মোটা কেন?", ["উচ্চ চাপে সারা শরীরে রক্ত পাম্প করতে হয়", "বেশি পুরোনো", "চর্বি জমায়", "মোটা নয়"],
        "ডান দিক শুধু কাছের ফুসফুসে পাম্প করে।"),
    mcq("What do valves in the heart do?", ["Stop blood flowing backwards", "Make blood red", "Fight germs", "Store oxygen"], 0,
        "Like one-way gates in a water system.",
        "হৃৎপিণ্ডের কপাটিকা কী করে?", ["রক্তকে উল্টো দিকে যেতে দেয় না", "রক্ত লাল করে", "জীবাণুর সঙ্গে লড়ে", "অক্সিজেন জমায়"],
        "জল-ব্যবস্থার একমুখী ফটকের মতো।"),
    mcq("What is 'coronary heart disease'?", ["Fatty deposits narrowing the arteries that feed the heart muscle", "A broken rib", "A lung infection", "A skin rash"], 0,
        "Exercise, a balanced diet and not smoking lower the risk.",
        "'করোনারি হৃদ্‌রোগ' কী?", ["হৃৎপেশিকে পুষ্টি দেওয়া ধমনিতে চর্বি জমে সরু হয়ে যাওয়া", "পাঁজর ভাঙা", "ফুসফুসের সংক্রমণ", "ত্বকের ফুসকুড়ি"],
        "ব্যায়াম, সুষম খাদ্য আর ধূমপান না করা ঝুঁকি কমায়।"),
    mcq("Your forearm lifting a load is a lever. Where is the pivot?", ["At the elbow joint", "At the hand", "At the shoulder blade", "At the fingertips"], 0,
        "The biceps pulls near the elbow, so it needs a big force to lift a load in the hand.",
        "বোঝা তোলা তোমার বাহু একটা লিভার। আলম্ব কোথায়?", ["কনুইয়ের সন্ধিতে", "হাতে", "কাঁধের হাড়ে", "আঙুলের ডগায়"],
        "বাইসেপ কনুইয়ের কাছে টানে, তাই হাতে বোঝা তুলতে বড় বল লাগে।"),
    mcq("Why does holding a heavy bag at arm's length feel much harder than close to your body?", ["The bigger distance from the joint makes a bigger turning moment", "The bag gets heavier", "Arms get shorter", "It does not"], 0,
        "Workers carry loads close to the body for this reason.",
        "ভারী ব্যাগ হাত-লম্বা দূরে ধরা শরীরের কাছে ধরার চেয়ে অনেক কঠিন লাগে কেন?", ["সন্ধি থেকে বেশি দূরত্ব বড় ঘূর্ণন-ভ্রামক তৈরি করে", "ব্যাগ ভারী হয়", "হাত ছোট হয়", "লাগে না"],
        "এই কারণে কর্মীরা বোঝা শরীরের কাছে বয়।"),
    mcq("What are ligaments?", ["Tough bands that join bone to bone at joints", "Tissue joining muscle to bone", "Blood vessels", "Nerves"], 0,
        "Tendons join muscle to bone; ligaments join bones together.",
        "অস্থিবন্ধনী (লিগামেন্ট) কী?", ["সন্ধিতে হাড়কে হাড়ের সঙ্গে জোড়া শক্ত ফিতে", "পেশিকে হাড়ে জোড়া কলা", "রক্তনালী", "স্নায়ু"],
        "কণ্ডরা পেশিকে হাড়ে জোড়ে; অস্থিবন্ধনী হাড়কে হাড়ে।"),
    mcq("What are 'limiting factors' for photosynthesis?", ["Light, carbon dioxide and temperature - whichever is in shortest supply limits the rate", "Only soil colour", "Only the plant's age", "Wind direction"], 0,
        "Greenhouses add light, warmth and CO2 to grow crops faster.",
        "সালোকসংশ্লেষের 'সীমাবদ্ধকারী উপাদান' কী?", ["আলো, কার্বন ডাই-অক্সাইড আর তাপমাত্রা - যেটা সবচেয়ে কম, সেটাই হার সীমিত করে", "শুধু মাটির রং", "শুধু গাছের বয়স", "বাতাসের দিক"],
        "গ্রিনহাউস দ্রুত ফসল ফলাতে আলো, উষ্ণতা আর CO2 যোগ করে।"),
    mcq("Why might plants under a wide bridge deck grow poorly?", ["The deck blocks light, limiting photosynthesis", "Bridges make soil salty always", "Plants dislike traffic noise", "They grow better"], 0,
        "Designers sometimes add light gaps or choose shade-loving plants.",
        "চওড়া সেতুর পাটাতনের নিচে গাছ খারাপভাবে বাড়তে পারে কেন?", ["পাটাতন আলো আটকে সালোকসংশ্লেষ সীমিত করে", "সেতু সবসময় মাটি নোনা করে", "গাছ যানবাহনের শব্দ অপছন্দ করে", "ভালো বাড়ে"],
        "নকশাকারীরা কখনো আলোর ফাঁক রাখেন বা ছায়াপ্রিয় গাছ বাছেন।"),
    mcq("How do plants use the glucose they make?", ["For respiration, to make cellulose for cell walls, and stored as starch", "Only to colour flowers", "They throw it away", "Only to make oxygen"], 0,
        "Cellulose makes wood - the bridge material grown from sunlight!",
        "উদ্ভিদ তৈরি করা গ্লুকোজ কীভাবে ব্যবহার করে?", ["শ্বসনে, কোষপ্রাচীরের সেলুলোজ বানাতে, আর শ্বেতসার হিসেবে জমায়", "শুধু ফুল রাঙাতে", "ফেলে দেয়", "শুধু অক্সিজেন বানাতে"],
        "সেলুলোজ থেকেই কাঠ - রোদ থেকে জন্মানো সেতুর উপাদান!"),
    mcq("What is a 'quadrat' used for?", ["Sampling plants or small animals in a measured square area", "Measuring rainfall", "Catching birds", "Weighing soil"], 0,
        "Ecologists use quadrats to survey sites before construction.",
        "'কোয়াড্র্যাট' কীসের জন্য ব্যবহার হয়?", ["মাপা বর্গাকার জায়গায় উদ্ভিদ বা ছোট প্রাণীর নমুনা নিতে", "বৃষ্টি মাপতে", "পাখি ধরতে", "মাটি ওজন করতে"],
        "নির্মাণের আগে জায়গা সমীক্ষায় বাস্তুবিদরা কোয়াড্র্যাট ব্যবহার করেন।"),
    mcq("Why should quadrats be placed randomly?", ["To avoid bias and get a fair sample", "To make it faster", "Random is required by law", "It does not matter"], 0,
        "Choosing only the best patches would overestimate numbers.",
        "কোয়াড্র্যাট এলোমেলোভাবে রাখা উচিত কেন?", ["পক্ষপাত এড়িয়ে ন্যায্য নমুনা পেতে", "দ্রুত করতে", "আইনে বাধ্যতামূলক", "কিছু যায় আসে না"],
        "শুধু সেরা জায়গা বাছলে সংখ্যা বেশি ধরা হবে।"),
    mcq("What is a 'transect'?", ["A line across a habitat along which samples are taken", "A type of insect", "A river crossing", "A bridge part"], 0,
        "A transect from riverbank inland shows how plants change with distance from water.",
        "'ট্রান্সেক্ট' কী?", ["বাসস্থানের আড়াআড়ি একটা রেখা, যা বরাবর নমুনা নেওয়া হয়", "এক রকম পোকা", "নদী-পারাপার", "সেতুর অংশ"],
        "নদীর পাড় থেকে ভেতরের দিকে ট্রান্সেক্ট দেখায় জল থেকে দূরত্বে গাছ কীভাবে বদলায়।"),
    mcq("What does a microscope's 'magnification' mean?", ["How many times bigger the image looks than the real object", "How bright the light is", "How heavy the lens is", "How sharp the image is"], 0,
        "Magnification = image size ÷ actual size.",
        "অণুবীক্ষণের 'বিবর্ধন' মানে কী?", ["প্রকৃত বস্তুর চেয়ে ছবি কত গুণ বড় দেখায়", "আলো কত উজ্জ্বল", "লেন্স কত ভারী", "ছবি কত স্পষ্ট"],
        "বিবর্ধন = ছবির মাপ ÷ প্রকৃত মাপ।"),
    mcq("How many micrometres (µm) are in 1 mm?", ["1,000", "100", "10", "1,000,000"], 0,
        "Cells are usually 10-100 µm across.",
        "1 mm-এ কত মাইক্রোমিটার (µm)?", ["1,000", "100", "10", "1,000,000"],
        "কোষ সাধারণত 10-100 µm চওড়া।"),
    mcq("What is DNA?", ["The molecule carrying genetic instructions, shaped like a twisted ladder (double helix)", "A type of protein food", "A blood cell", "A virus"], 0,
        "Rosalind Franklin's X-ray images helped reveal its shape.",
        "ডিএনএ কী?", ["বংশগত নির্দেশ বহনকারী অণু, পাকানো মইয়ের মতো (দ্বি-কুণ্ডলী)", "এক রকম প্রোটিন খাবার", "রক্তকণিকা", "ভাইরাস"],
        "রোজালিন্ড ফ্র্যাঙ্কলিনের এক্স-রে ছবি তার আকার প্রকাশে সাহায্য করেছিল।"),
    mcq("What is a 'gene'?", ["A section of DNA that codes for a characteristic", "A whole chromosome", "A type of cell", "A kind of jeans"], 0,
        "Genes are like individual recipes in a cookbook.",
        "'জিন' কী?", ["ডিএনএ-র যে অংশ একটা বৈশিষ্ট্যের সংকেত দেয়", "গোটা ক্রোমোজোম", "এক রকম কোষ", "এক রকম জিনস প্যান্ট"],
        "জিন রান্নার বইয়ের আলাদা আলাদা প্রণালীর মতো।"),
    mcq("How many chromosomes are in most human body cells?", ["46 (23 pairs)", "23", "100", "12"], 0,
        "Egg and sperm cells have 23 each, so a baby gets half from each parent.",
        "বেশিরভাগ মানুষের দেহকোষে কয়টি ক্রোমোজোম?", ["46 (23 জোড়া)", "23", "100", "12"],
        "ডিম্বাণু আর শুক্রাণুতে 23টি করে, তাই শিশু প্রত্যেক বাবা-মা থেকে অর্ধেক পায়।"),
    mcq("What does 'dominant' mean for an allele?", ["It shows its effect even if only one copy is present", "It is always harmful", "It never shows", "It is the longest gene"], 0,
        "A recessive allele only shows when two copies are present.",
        "অ্যালিলের ক্ষেত্রে 'প্রকট' মানে কী?", ["মাত্র একটা প্রতিলিপি থাকলেও প্রভাব দেখায়", "সবসময় ক্ষতিকর", "কখনো দেখায় না", "সবচেয়ে লম্বা জিন"],
        "প্রচ্ছন্ন অ্যালিল শুধু দুটো প্রতিলিপি থাকলে দেখা দেয়।"),
    mcq("Two parents both carry one recessive allele (Bb). What fraction of children are expected to show the recessive trait (bb)?", ["1/4", "1/2", "3/4", "None"], 0,
        "Punnett square: BB, Bb, bB, bb - one in four.",
        "বাবা-মা দুজনেই একটা প্রচ্ছন্ন অ্যালিল বহন করেন (Bb)। সন্তানদের কত ভাগ প্রচ্ছন্ন বৈশিষ্ট্য (bb) দেখাবে বলে প্রত্যাশিত?", ["1/4", "1/2", "3/4", "কেউ না"],
        "পানেট বর্গ: BB, Bb, bB, bb - চারজনে একজন।"),
    mcq("What is a 'mutation'?", ["A change in the DNA", "A type of food", "A broken bone", "A change of clothes"], 0,
        "Most mutations have no effect; a few help or harm.",
        "'পরিব্যক্তি' (মিউটেশন) কী?", ["ডিএনএ-তে পরিবর্তন", "এক রকম খাবার", "হাড় ভাঙা", "জামা বদল"],
        "বেশিরভাগ পরিব্যক্তির প্রভাব নেই; অল্প কয়েকটি উপকার বা ক্ষতি করে।"),
    mcq("What are the five kingdoms of living things?", ["Animals, plants, fungi, protists and prokaryotes (bacteria)", "Lions, tigers, bears, wolves and birds", "Land, sea, air, fire and ice", "Cells, tissues, organs, systems and bodies"], 0,
        "Classification groups living things by shared features.",
        "জীবের পাঁচটি রাজ্য কী?", ["প্রাণী, উদ্ভিদ, ছত্রাক, প্রোটিস্ট আর প্রোক্যারিওট (ব্যাকটেরিয়া)", "সিংহ, বাঘ, ভালুক, নেকড়ে আর পাখি", "ডাঙা, সমুদ্র, বাতাস, আগুন আর বরফ", "কোষ, কলা, অঙ্গ, তন্ত্র আর দেহ"],
        "শ্রেণিবিন্যাস একই বৈশিষ্ট্য দেখে জীবদের দলে ভাগ করে।"),
    mcq("What is a species' two-part scientific name called?", ["Binomial name, like Panthera tigris", "Nickname", "Barcode", "Common name only"], 0,
        "Genus first, then species - used worldwide.",
        "একটা প্রজাতির দুই-অংশের বৈজ্ঞানিক নামকে কী বলে?", ["দ্বিপদ নাম, যেমন Panthera tigris", "ডাকনাম", "বারকোড", "শুধু সাধারণ নাম"],
        "আগে গণ, তারপর প্রজাতি - সারা বিশ্বে ব্যবহৃত।"),
    mcq("Which animals can show that a river is clean?", ["Mayfly and stonefly larvae, which need lots of oxygen", "Rat-tailed maggots", "Sludge worms", "None ever"], 0,
        "These are 'indicator species' - checked before and after bridge works.",
        "কোন প্রাণী দেখাতে পারে যে নদী পরিষ্কার?", ["মেফ্লাই আর স্টোনফ্লাইয়ের শূককীট, যাদের অনেক অক্সিজেন লাগে", "ইঁদুর-লেজি শূককীট", "কাদা-কৃমি", "কেউ কখনো না"],
        "এরা 'নির্দেশক প্রজাতি' - সেতুর কাজের আগে আর পরে পরীক্ষা হয়।"),
    mcq("What is 'eutrophication'?", ["Too many nutrients cause algae blooms that use up oxygen and kill fish", "Water freezing", "Fish multiplying healthily", "Rivers drying"], 0,
        "Fertiliser and sewage runoff are common causes.",
        "'ইউট্রোফিকেশন' কী?", ["অতিরিক্ত পুষ্টিতে শৈবাল বেড়ে অক্সিজেন শেষ করে মাছ মারে", "জল জমা", "মাছ সুস্থভাবে বাড়া", "নদী শুকোনো"],
        "সার আর নর্দমার জল সাধারণ কারণ।"),
    mcq("Why are lichens on bridge stonework a good sign?", ["Many lichens only grow where the air is clean", "They make stone stronger", "They eat rust", "They are a bad sign"], 0,
        "Lichens are indicators of low sulphur dioxide pollution.",
        "সেতুর পাথরে লাইকেন থাকা ভালো লক্ষণ কেন?", ["অনেক লাইকেন কেবল পরিষ্কার বাতাসেই জন্মায়", "পাথর শক্ত করে", "মরচে খায়", "খারাপ লক্ষণ"],
        "লাইকেন কম সালফার ডাই-অক্সাইড দূষণের নির্দেশক।"),
    mcq("Why can tree roots damage old masonry bridges?", ["Roots grow into joints and push stones apart", "Roots are magnetic", "Roots dissolve stone instantly", "They cannot"], 0,
        "Bridge inspectors remove saplings from stonework.",
        "গাছের শিকড় পুরোনো পাথরের সেতুর ক্ষতি করতে পারে কেন?", ["শিকড় জোড়ে ঢুকে পাথর ঠেলে আলাদা করে", "শিকড় চুম্বকীয়", "শিকড় সঙ্গে সঙ্গে পাথর গলায়", "পারে না"],
        "সেতু-পরিদর্শকেরা পাথরের ফাঁক থেকে চারা গাছ সরান।"),
    mcq("What is 'antibiotic resistance'?", ["Bacteria evolving so antibiotics no longer kill them", "People resisting medicine", "A strong immune system", "Vaccines failing in fridges"], 0,
        "Only use antibiotics when prescribed, and finish the course.",
        "'অ্যান্টিবায়োটিক প্রতিরোধ' কী?", ["ব্যাকটেরিয়া বিবর্তিত হয়ে আর অ্যান্টিবায়োটিকে মরে না", "মানুষের ওষুধ প্রত্যাখ্যান", "শক্তিশালী রোগ-প্রতিরোধ", "ফ্রিজে টিকা নষ্ট হওয়া"],
        "শুধু প্রেসক্রিপশনে অ্যান্টিবায়োটিক খাও আর কোর্স শেষ করো।"),
    mcq("How do antibodies help fight infection?", ["They lock onto specific germs so white blood cells can destroy them", "They are food for germs", "They make blood thicker", "They cool the body"], 0,
        "Vaccines train the body to make antibodies in advance.",
        "অ্যান্টিবডি কীভাবে সংক্রমণের সঙ্গে লড়তে সাহায্য করে?", ["নির্দিষ্ট জীবাণুর সঙ্গে আটকে যায় যাতে শ্বেত রক্তকণিকা তাদের ধ্বংস করতে পারে", "জীবাণুর খাবার", "রক্ত ঘন করে", "শরীর ঠান্ডা করে"],
        "টিকা শরীরকে আগে থেকে অ্যান্টিবডি বানাতে শেখায়।"),
    mcq("What is 'herd immunity'?", ["When enough people are immune, a disease cannot spread easily", "Cows becoming immune only", "Everyone getting sick", "A type of vaccine"], 0,
        "It protects those who cannot be vaccinated.",
        "'দলগত প্রতিরোধ' (হার্ড ইমিউনিটি) কী?", ["যথেষ্ট মানুষ প্রতিরোধী হলে রোগ সহজে ছড়াতে পারে না", "শুধু গরু প্রতিরোধী হওয়া", "সবাই অসুস্থ হওয়া", "এক রকম টিকা"],
        "যাঁরা টিকা নিতে পারেন না তাঁদের রক্ষা করে।"),
    mcq("How is tuberculosis (TB) spread?", ["Through the air when infected people cough", "By mosquito bites", "Through broken bones", "By sunlight"], 0,
        "Good ventilation in workers' housing reduces spread.",
        "যক্ষ্মা (টিবি) কীভাবে ছড়ায়?", ["আক্রান্ত মানুষ কাশলে বাতাসে", "মশার কামড়ে", "ভাঙা হাড়ে", "রোদে"],
        "শ্রমিক-আবাসে ভালো বায়ুচলাচল ছড়ানো কমায়।"),
    mcq("Why do construction workers need tetanus vaccinations?", ["Tetanus bacteria in soil can enter cuts from rusty nails or tools", "Tetanus is caused by noise", "It prevents sunburn", "It is not needed"], 0,
        "Clean wounds quickly and keep vaccinations up to date.",
        "নির্মাণ-কর্মীদের ধনুষ্টংকারের টিকা লাগে কেন?", ["মাটির টিটেনাস ব্যাকটেরিয়া মরচে-ধরা পেরেক বা যন্ত্রের ক্ষত দিয়ে ঢুকতে পারে", "শব্দে ধনুষ্টংকার হয়", "রোদে পোড়া ঠেকায়", "দরকার নেই"],
        "ক্ষত দ্রুত পরিষ্কার করো আর টিকা হালনাগাদ রাখো।"),
    mcq("What is the job of insulin?", ["It lowers blood sugar by helping cells take in glucose", "It digests fat", "It carries oxygen", "It fights germs"], 0,
        "People with type 1 diabetes need insulin injections.",
        "ইনসুলিনের কাজ কী?", ["কোষকে গ্লুকোজ নিতে সাহায্য করে রক্তে শর্করা কমায়", "চর্বি হজম করে", "অক্সিজেন বয়", "জীবাণুর সঙ্গে লড়ে"],
        "টাইপ 1 ডায়াবেটিস রোগীদের ইনসুলিন ইনজেকশন লাগে।"),
    mcq("What are hormones?", ["Chemical messengers carried in the blood", "Bones in the ear", "Types of muscle", "Nerve cells"], 0,
        "Adrenaline prepares you for action in emergencies.",
        "হরমোন কী?", ["রক্তে বাহিত রাসায়নিক বার্তাবাহক", "কানের হাড়", "এক রকম পেশি", "স্নায়ুকোষ"],
        "জরুরি অবস্থায় অ্যাড্রেনালিন তোমাকে কাজের জন্য তৈরি করে।"),
    mcq("What does adrenaline do when a worker sees a falling load?", ["Speeds up heart rate and breathing so muscles can react fast", "Puts them to sleep", "Slows the heart", "Makes them hungry"], 0,
        "The 'fight or flight' response.",
        "একজন কর্মী বোঝা পড়তে দেখলে অ্যাড্রেনালিন কী করে?", ["হৃৎস্পন্দন আর শ্বাস দ্রুত করে যাতে পেশি দ্রুত সাড়া দিতে পারে", "ঘুম পাড়ায়", "হৃৎপিণ্ড ধীর করে", "খিদে পাওয়ায়"],
        "'লড়াই বা পলায়ন' প্রতিক্রিয়া।"),
    mcq("What is 'homeostasis'?", ["Keeping conditions inside the body steady, like temperature and water", "Building a home", "Growing taller", "Digesting food"], 0,
        "Sweating and shivering help keep body temperature near 37 °C.",
        "'সমস্থিতি' (হোমিওস্ট্যাসিস) কী?", ["শরীরের ভেতরের অবস্থা স্থির রাখা, যেমন তাপমাত্রা আর জল", "বাড়ি বানানো", "লম্বা হওয়া", "খাবার হজম"],
        "ঘাম আর কাঁপুনি শরীরের তাপমাত্রা প্রায় 37 °C-এ রাখতে সাহায্য করে।"),
    mcq("What is 'heat stroke'?", ["A dangerous rise in body temperature when the body cannot cool itself", "A mild sunburn", "Feeling cold", "A muscle cramp only"], 0,
        "It is an emergency: cool the person and get medical help.",
        "'হিটস্ট্রোক' কী?", ["শরীর নিজেকে ঠান্ডা করতে না পারায় বিপজ্জনকভাবে তাপমাত্রা বাড়া", "সামান্য রোদে পোড়া", "ঠান্ডা লাগা", "শুধু পেশিতে টান"],
        "এটা জরুরি অবস্থা: মানুষটিকে ঠান্ডা করো আর চিকিৎসা নাও।"),
    mcq("Why do mangrove roots stick up out of the mud?", ["They take in air because waterlogged mud has little oxygen", "To catch fish", "To hold up bridges", "For decoration"], 0,
        "These breathing roots are called pneumatophores.",
        "ম্যানগ্রোভের শিকড় কাদা থেকে উপরে বেরিয়ে থাকে কেন?", ["জলাবদ্ধ কাদায় অক্সিজেন কম, তাই বাতাস নেয়", "মাছ ধরতে", "সেতু ধরে রাখতে", "সাজসজ্জার জন্য"],
        "এই শ্বাসমূলকে নিউম্যাটোফোর বলে।"),
    mcq("What is 'selective breeding'?", ["Choosing parents with useful traits to breed the next generation", "Random mating", "Cloning only", "Feeding animals more"], 0,
        "It produced high-yield rice and strong bamboo varieties.",
        "'নির্বাচিত প্রজনন' কী?", ["পরের প্রজন্ম জন্মাতে দরকারি বৈশিষ্ট্যের বাবা-মা বাছা", "এলোমেলো মিলন", "শুধু ক্লোনিং", "প্রাণীদের বেশি খাওয়ানো"],
        "এ থেকে বেশি ফলনের ধান আর শক্ত বাঁশের জাত তৈরি হয়েছে।"),
    mcq("Why does bamboo make a good sustainable building material?", ["It grows back in a few years, unlike slow-growing hardwoods", "It never grows back", "It is a metal", "It is fireproof"], 0,
        "Some bamboo species grow nearly 1 m a day!",
        "বাঁশ টেকসই নির্মাণ-উপাদান কেন?", ["ধীরে বাড়া শক্ত কাঠের মতো নয়, কয়েক বছরেই আবার জন্মায়", "আর কখনো জন্মায় না", "এটা ধাতু", "আগুনে পোড়ে না"],
        "কিছু প্রজাতির বাঁশ দিনে প্রায় 1 m বাড়ে!"),
    quadrat(36, 6, 900), quadrat(56, 7, 1500), quadrat(90, 15, 3000),
    mag(20, 50), mag(6, 2), mag(45, 15),
    bmi(65, 165), bmi(90, 175), bmi(55, 150),
    cardiac(75, 90), cardiac(90, 100),
    mcq("What is 'active transport' in cells?", ["Moving substances against a concentration gradient using energy", "Diffusion only", "Water moving by osmosis", "Cells moving around the body"], 0,
        "Root hair cells use it to take in minerals from dilute soil water.",
        "কোষে 'সক্রিয় পরিবহন' কী?", ["শক্তি খরচ করে গাঢ়ত্বের উল্টো দিকে পদার্থ সরানো", "শুধু ব্যাপন", "অভিস্রবণে জল চলা", "কোষের শরীরে ঘোরা"],
        "মূলরোম কোষ লঘু মাটির জল থেকে খনিজ নিতে এটা ব্যবহার করে।"),
    mcq("Why does a long distance runner breathe hard after the race?", ["To repay the 'oxygen debt' and remove lactic acid", "To cool the lungs only", "To build bones", "To stop sweating"], 0,
        "The body needs extra oxygen to break down lactic acid.",
        "দৌড় শেষে লম্বা দূরত্বের দৌড়বিদ জোরে শ্বাস নেন কেন?", ["'অক্সিজেন-ঋণ' শোধ আর ল্যাকটিক অ্যাসিড সরাতে", "শুধু ফুসফুস ঠান্ডা করতে", "হাড় গড়তে", "ঘাম থামাতে"],
        "ল্যাকটিক অ্যাসিড ভাঙতে শরীরের বাড়তি অক্সিজেন লাগে।"),
    mcq("What is the job of the small intestine's villi?", ["To increase surface area for absorbing digested food", "To chew food", "To pump blood", "To make bile"], 0,
        "Millions of finger-like villi make absorption fast.",
        "ক্ষুদ্রান্ত্রের ভিলাইয়ের কাজ কী?", ["হজম হওয়া খাবার শোষণে তলের ক্ষেত্রফল বাড়ানো", "খাবার চিবোনো", "রক্ত পাম্প করা", "পিত্ত তৈরি করা"],
        "লক্ষ লক্ষ আঙুলের মতো ভিলাই শোষণ দ্রুত করে।"),
    mcq("What does bile do?", ["Breaks fat into small droplets and neutralises stomach acid", "Digests protein", "Carries oxygen", "Makes saliva"], 0,
        "Bile is made in the liver and stored in the gall bladder.",
        "পিত্ত কী করে?", ["চর্বিকে ছোট ফোঁটায় ভাঙে আর পাকস্থলীর অ্যাসিড প্রশমিত করে", "প্রোটিন হজম করে", "অক্সিজেন বয়", "লালা তৈরি করে"],
        "পিত্ত যকৃতে তৈরি হয়ে পিত্তথলিতে জমা থাকে।"),
    mcq("What are stem cells?", ["Unspecialised cells that can become many types of cell", "Plant stem parts only", "Dead cells", "Red blood cells only"], 0,
        "They may one day help repair damaged tissues.",
        "স্টেম কোষ কী?", ["অবিশেষায়িত কোষ, যা নানা রকম কোষে পরিণত হতে পারে", "শুধু উদ্ভিদের কাণ্ডের অংশ", "মৃত কোষ", "শুধু লোহিত রক্তকণিকা"],
        "একদিন এরা ক্ষতিগ্রস্ত কলা সারাতে সাহায্য করতে পারে।"),
    mcq("Where are plant stem cells found?", ["In meristems at the tips of roots and shoots", "In the leaves only", "In the flowers only", "Plants have none"], 0,
        "That is why cuttings can grow into new plants.",
        "উদ্ভিদের স্টেম কোষ কোথায় থাকে?", ["মূল আর বিটপের ডগার ভাজক কলায়", "শুধু পাতায়", "শুধু ফুলে", "উদ্ভিদে নেই"],
        "তাই ডাল কেটে লাগালে নতুন গাছ হয়।"),
    mcq("What is 'mitosis'?", ["Cell division that makes two identical cells for growth and repair", "Making sex cells", "Cell death", "Digestion"], 0,
        "Your skin heals a cut by mitosis.",
        "'মাইটোসিস' কী?", ["বৃদ্ধি আর মেরামতে দুটি অভিন্ন কোষ তৈরির কোষবিভাজন", "জননকোষ তৈরি", "কোষের মৃত্যু", "পরিপাক"],
        "তোমার ত্বক মাইটোসিসে কাটা জায়গা সারায়।"),
    mcq("What is 'meiosis'?", ["Cell division that makes sex cells with half the chromosomes", "Making identical body cells", "Muscle growth", "Breathing"], 0,
        "It creates variation in offspring.",
        "'মিয়োসিস' কী?", ["অর্ধেক ক্রোমোজোমসহ জননকোষ তৈরির কোষবিভাজন", "অভিন্ন দেহকোষ তৈরি", "পেশির বৃদ্ধি", "শ্বাস নেওয়া"],
        "এটা সন্তানদের মধ্যে বৈচিত্র্য আনে।"),
    mcq("What is 'cancer'?", ["Cells dividing out of control", "A broken bone", "A virus only", "A healthy growth"], 0,
        "Avoiding tobacco and too much sun lowers the risk.",
        "'ক্যানসার' কী?", ["কোষের নিয়ন্ত্রণহীন বিভাজন", "হাড় ভাঙা", "শুধু ভাইরাস", "স্বাস্থ্যকর বৃদ্ধি"],
        "তামাক আর বেশি রোদ এড়ালে ঝুঁকি কমে।"),
    mcq("Why do welders protect their skin from UV light?", ["UV can burn skin and raise skin cancer risk", "UV makes skin stronger", "UV is cold", "It is not needed"], 0,
        "Welding arcs produce strong ultraviolet light.",
        "ঝালাইকারীরা অতিবেগুনি আলো থেকে ত্বক রক্ষা করেন কেন?", ["অতিবেগুনি রশ্মি ত্বক পোড়াতে আর ত্বকের ক্যানসারের ঝুঁকি বাড়াতে পারে", "অতিবেগুনি ত্বক শক্ত করে", "অতিবেগুনি ঠান্ডা", "দরকার নেই"],
        "ঝালাইয়ের শিখা জোরালো অতিবেগুনি আলো তৈরি করে।"),
    mcq("What is 'asbestos' and why is it dangerous in old buildings and bridges?", ["A fibrous mineral whose dust can cause serious lung disease", "A type of paint", "A safe insulation", "A kind of steel"], 0,
        "Only trained specialists may remove it.",
        "'অ্যাসবেস্টস' কী আর পুরোনো ভবন ও সেতুতে কেন বিপজ্জনক?", ["তন্তুময় খনিজ, যার ধুলো ফুসফুসের গুরুতর রোগ ঘটাতে পারে", "এক রকম রং", "নিরাপদ অন্তরক", "এক রকম ইস্পাত"],
        "শুধু প্রশিক্ষিত বিশেষজ্ঞরাই সরাতে পারেন।"),
    mcq("What is a 'food chain' arrow pointing from grass to deer showing?", ["The direction energy flows - grass is eaten by deer", "Deer eating arrows", "Grass eating deer", "Nothing"], 0,
        "Arrows point to the eater.",
        "খাদ্যশৃঙ্খলে ঘাস থেকে হরিণের দিকে তির কী দেখায়?", ["শক্তিপ্রবাহের দিক - ঘাস হরিণ খায়", "হরিণ তির খায়", "ঘাস হরিণ খায়", "কিছুই না"],
        "তির খাদকের দিকে মুখ করে।"),
    mcq("What is a 'pyramid of biomass'?", ["A diagram showing the mass of living material at each feeding level", "An Egyptian monument", "A food shop", "A stack of logs"], 0,
        "It usually narrows towards the top predators.",
        "'জীবভরের পিরামিড' কী?", ["প্রতি খাদ্যস্তরে জীবিত পদার্থের ভর দেখানো চিত্র", "মিশরের স্মৃতিস্তম্ভ", "খাবারের দোকান", "কাঠের গুঁড়ির স্তূপ"],
        "সাধারণত শীর্ষ শিকারির দিকে সরু হয়।"),
    mcq("What is the 'carbon cycle'?", ["The movement of carbon between air, living things, oceans and rocks", "A bicycle made of carbon", "Coal burning only", "A type of engine"], 0,
        "Photosynthesis takes carbon in; respiration and burning release it.",
        "'কার্বন চক্র' কী?", ["বাতাস, জীব, সমুদ্র আর পাথরের মধ্যে কার্বনের চলাচল", "কার্বনের তৈরি সাইকেল", "শুধু কয়লা পোড়া", "এক রকম ইঞ্জিন"],
        "সালোকসংশ্লেষ কার্বন নেয়; শ্বসন আর দহন ছাড়ে।"),
    mcq("Why are bats sometimes found roosting under bridges?", ["Bridges offer dark, sheltered spaces like caves", "Bats eat concrete", "Bridges are warm ovens", "They never roost there"], 0,
        "Surveys check for protected bats before bridge repairs.",
        "বাদুড় কখনো সেতুর নিচে বাসা বাঁধে কেন?", ["সেতু গুহার মতো অন্ধকার, আশ্রিত জায়গা দেয়", "বাদুড় কংক্রিট খায়", "সেতু গরম চুল্লি", "কখনো বাঁধে না"],
        "সেতু মেরামতের আগে সমীক্ষায় সুরক্ষিত বাদুড় খোঁজা হয়।"),
    mcq("What is a 'keystone species'?", ["A species that many others in its ecosystem depend on", "The biggest animal", "A species found in stone", "An extinct species"], 0,
        "Like the keystone of an arch - remove it and the structure collapses.",
        "'কিস্টোন প্রজাতি' কী?", ["যে প্রজাতির উপর বাস্তুতন্ত্রের অনেকে নির্ভর করে", "সবচেয়ে বড় প্রাণী", "পাথরে পাওয়া প্রজাতি", "বিলুপ্ত প্রজাতি"],
        "খিলানের মূল পাথরের মতো - সরালে কাঠামো ভেঙে পড়ে।"),
    mcq("Why did the keystone of a stone arch give its name to keystone species?", ["Removing the top central stone makes the whole arch fall", "It is the heaviest stone", "It is decorative", "It was painted"], 0,
        "Ecology borrowed a word from bridge engineering!",
        "পাথরের খিলানের কিস্টোন থেকে কিস্টোন প্রজাতির নাম এল কেন?", ["উপরের মাঝের পাথর সরালে পুরো খিলান পড়ে যায়", "এটা সবচেয়ে ভারী পাথর", "এটা সাজসজ্জা", "রং করা ছিল"],
        "বাস্তুবিদ্যা সেতু-প্রকৌশল থেকে একটা শব্দ ধার নিয়েছে!"),
    mcq("What is 'conservation'?", ["Protecting habitats and species for the future", "Building over forests", "Hunting animals", "Ignoring nature"], 0,
        "Good bridge projects include conservation plans.",
        "'সংরক্ষণ' কী?", ["ভবিষ্যতের জন্য বাসস্থান আর প্রজাতি রক্ষা", "বনের উপর নির্মাণ", "প্রাণী শিকার", "প্রকৃতি উপেক্ষা"],
        "ভালো সেতু-প্রকল্পে সংরক্ষণ-পরিকল্পনা থাকে।"),
    mcq("What is an 'Environmental Impact Assessment' (EIA)?", ["A study of how a project may affect nature and people, before it is approved", "A paint test", "A traffic count only", "A bank loan form"], 0,
        "Large bridges in India need an EIA and public consultation.",
        "'পরিবেশগত প্রভাব মূল্যায়ন' (ইআইএ) কী?", ["অনুমোদনের আগে প্রকল্প প্রকৃতি আর মানুষের উপর কী প্রভাব ফেলতে পারে তার সমীক্ষা", "রঙের পরীক্ষা", "শুধু যানবাহন গণনা", "ব্যাংক-ঋণের ফর্ম"],
        "ভারতে বড় সেতুর জন্য ইআইএ আর জনশুনানি লাগে।"),
)
