"""Class 6 - Commercials (Junior Cadet): pricing strategies, the marketing mix (4 Ps), product
life cycle, weighted tender scoring, online conversion rates, container and warehouse space,
mixed-vehicle toll income, delivery-time planning, contract types and supply-chain risk."""
from . import mcq


def _o(r, *alts):
    out = []
    for x in (r, *alts, r + 1, r + 2, r * 2, r + 10):
        if x not in out and x > 0:
            out.append(x)
    return out[:4]


def _n(q_en, q_bn, r, ex_en, ex_bn, alts, u_en="", u_bn="", pre_en="", pre_bn_suffix=""):
    f = lambda x: f"{x:,}" if isinstance(x, int) else f"{x:g}"
    o = _o(r, *alts)
    return mcq(q_en, [pre_en + f(x) + u_en for x in o], 0, ex_en, q_bn,
               [f(x) + (pre_bn_suffix or u_bn) for x in o], ex_bn)


def score(p1, q1, p2, q2, wp, wq):
    a = p1 * wp + q1 * wq
    b = p2 * wp + q2 * wq
    a_, b_ = round(a / 100, 1), round(b / 100, 1)
    o = [f"Firm A ({a_:g})", f"Firm B ({b_:g})", "A tie", "Neither can win"]
    o_bn = [f"সংস্থা A ({a_:g})", f"সংস্থা B ({b_:g})", "সমান", "কেউ জিততে পারে না"]
    return mcq(f"A tender is scored {wp}% on price and {wq}% on quality. Firm A scores price {p1}, quality {q1}; firm B scores price {p2}, quality {q2} (out of 10). Who wins?",
               o, 0 if a > b else (1 if b > a else 2),
               f"A = {p1} x {wp / 100:g} + {q1} x {wq / 100:g} = {a_:g}; B = {p2} x {wp / 100:g} + {q2} x {wq / 100:g} = {b_:g}.",
               f"একটা দরপত্রে দামে {wp}% আর মানে {wq}% নম্বর। সংস্থা A দামে {p1}, মানে {q1}; সংস্থা B দামে {p2}, মানে {q2} (10-এর মধ্যে)। কে জেতে?",
               o_bn,
               f"A = {p1} x {wp / 100:g} + {q1} x {wq / 100:g} = {a_:g}; B = {p2} x {wp / 100:g} + {q2} x {wq / 100:g} = {b_:g}।")


def conv(visits, orders):
    r = round(orders * 100 / visits, 1)
    r = int(r) if r == int(r) else r
    return _n(f"An online tool shop had {visits:,} visitors and {orders:,} orders. What is the conversion rate?",
              f"একটা অনলাইন যন্ত্রের দোকানে {visits:,} জন এলেন আর {orders:,}টি অর্ডার হলো। রূপান্তরের হার কত?", r,
              f"Conversion = orders ÷ visitors x 100 = {orders:,} ÷ {visits:,} x 100 = {r:g}%.",
              f"রূপান্তর = অর্ডার ÷ আগত x 100 = {orders:,} ÷ {visits:,} x 100 = {r:g}%।",
              (round(visits / orders, 1), orders, r * 10), "%", "%")


def boxes(L, W, H, l, w, h):
    n = (L // l) * (W // w) * (H // h)
    vol = (L * W * H) // (l * w * h)
    return _n(f"A container is {L} x {W} x {H} units inside. Crates are {l} x {w} x {h}, packed upright and lined up. How many fit?",
              f"একটা কনটেনারের ভেতরের মাপ {L} x {W} x {H} একক। বাক্সগুলো {l} x {w} x {h}, খাড়া করে সারি দিয়ে রাখা। কয়টি আঁটবে?", n,
              f"Along each side: {L // l} x {W // w} x {H // h} = {n}. (Dividing volumes gives {vol}, but crates cannot be cut!)",
              f"প্রতি দিক বরাবর: {L // l} x {W // w} x {H // h} = {n}। (আয়তন ভাগ করলে {vol} হয়, কিন্তু বাক্স কাটা যায় না!)",
              (vol if vol != n else n + 3, n + L // l, (L // l) * (W // w)))


def tollmix(cars, cr, trucks, tr, buses, br):
    r = cars * cr + trucks * tr + buses * br
    return _n(f"In one day a bridge sees {cars:,} cars at Rs {cr}, {trucks:,} trucks at Rs {tr} and {buses:,} buses at Rs {br}. What is the toll income?",
              f"এক দিনে একটা সেতু দিয়ে {cr} টাকায় {cars:,}টি গাড়ি, {tr} টাকায় {trucks:,}টি ট্রাক আর {br} টাকায় {buses:,}টি বাস গেল। টোল-আয় কত?", r,
              f"{cars:,} x {cr} + {trucks:,} x {tr} + {buses:,} x {br} = Rs {r:,}.",
              f"{cars:,} x {cr} + {trucks:,} x {tr} + {buses:,} x {br} = {r:,} টাকা।",
              ((cars + trucks + buses) * cr, cars * cr + trucks * tr, r - buses * br + buses), "", " টাকা", "Rs ")


def eta(km, speed, stops, stop_min):
    mins = km * 60 // speed + stops * stop_min
    h, m = divmod(mins, 60)
    def fmt(x):
        a, b = divmod(x, 60)
        return f"{a} h {b:02d} min"
    def fmt_bn(x):
        a, b = divmod(x, 60)
        return f"{a} ঘণ্টা {b:02d} মিনিট"
    alts = [km * 60 // speed, mins + 30, mins - stops * stop_min // 2 if stops else mins + 15]
    o = []
    for x in [mins, *alts, mins + 60]:
        if x not in o and x > 0:
            o.append(x)
    o = o[:4]
    return mcq(f"A truck drives {km} km at an average {speed} km/h and makes {stops} stops of {stop_min} minutes. How long is the trip?",
               [fmt(x) for x in o], 0,
               f"Driving: {km} ÷ {speed} = {km / speed:g} h = {km * 60 // speed} min; stops: {stops} x {stop_min} = {stops * stop_min} min; total {mins} min = {fmt(mins)}.",
               f"একটা ট্রাক গড়ে {speed} km/h বেগে {km} km যায় আর {stop_min} মিনিটের {stops}টি বিরতি নেয়। যাত্রা কতক্ষণ?",
               [fmt_bn(x) for x in o],
               f"চালানো: {km} ÷ {speed} = {km / speed:g} ঘণ্টা = {km * 60 // speed} মিনিট; বিরতি: {stops} x {stop_min} = {stops * stop_min} মিনিট; মোট {mins} মিনিট = {fmt_bn(mins)}।")


ITEMS = (
    score(9, 6, 6, 9, 60, 40), score(7, 8, 9, 5, 40, 60), score(8, 7, 6, 9, 50, 50), score(5, 9, 9, 6, 30, 70), score(9, 7, 7, 9, 70, 30),
    conv(2000, 50), conv(5000, 150), conv(800, 24), conv(12000, 180), conv(400, 30),
    boxes(13, 6, 6, 3, 2, 2), boxes(10, 5, 4, 3, 2, 2), boxes(20, 8, 8, 4, 3, 3), boxes(15, 6, 6, 4, 3, 2),
    tollmix(3000, 40, 500, 150, 200, 100), tollmix(1200, 30, 300, 120, 80, 90), tollmix(5000, 50, 800, 200, 400, 150),
    eta(240, 60, 2, 15), eta(180, 45, 3, 20), eta(300, 50, 1, 30), eta(150, 30, 2, 10),
    mcq("What is 'penetration pricing'?", ["Starting with a low price to win customers quickly, then raising it", "Always charging the highest price", "Giving everything free forever", "Pricing by weight only"], 0,
        "Used by new firms entering a crowded market.",
        "'অনুপ্রবেশ মূল্যনির্ধারণ' কী?", ["দ্রুত খদ্দের পেতে কম দামে শুরু করে পরে বাড়ানো", "সবসময় সবচেয়ে বেশি দাম নেওয়া", "চিরকাল সব বিনামূল্যে দেওয়া", "শুধু ওজন দেখে দাম"],
        "ভিড়ের বাজারে ঢোকা নতুন সংস্থা এটা ব্যবহার করে।"),
    mcq("What is 'price skimming'?", ["Starting with a high price for a new product, then lowering it over time", "Stealing small amounts", "Selling below cost forever", "A discount for students only"], 0,
        "New gadgets often launch expensive, then get cheaper.",
        "'মূল্য-স্কিমিং' কী?", ["নতুন পণ্যে চড়া দামে শুরু করে সময়ের সঙ্গে কমানো", "অল্প অল্প চুরি", "চিরকাল খরচের কম দামে বেচা", "শুধু ছাত্রছাত্রীদের ছাড়"],
        "নতুন যন্ত্র প্রায়ই দামি হয়ে শুরু হয়, পরে সস্তা হয়।"),
    mcq("Why do shops price items at Rs 199 instead of Rs 200?", ["It feels much cheaper to many buyers (psychological pricing)", "Rs 200 is illegal", "It costs less to print", "Coins are scarce"], 0,
        "Rs 199 'looks like' 100-something.",
        "দোকান 200 টাকার বদলে 199 টাকা দাম রাখে কেন?", ["অনেক ক্রেতার কাছে অনেক সস্তা মনে হয় (মনস্তাত্ত্বিক মূল্যনির্ধারণ)", "200 টাকা বেআইনি", "ছাপাতে কম খরচ", "খুচরো কম"],
        "199 টাকা '100-এর ঘরের' মনে হয়।"),
    mcq("What are the '4 Ps' of the marketing mix?", ["Product, Price, Place and Promotion", "People, Paint, Pipes and Plans", "Profit, Pay, Power and Pressure", "Plan, Print, Post and Pay"], 0,
        "Get all four right and customers come.",
        "বিপণন-মিশ্রণের '4 P' কী?", ["পণ্য, দাম, স্থান আর প্রচার", "মানুষ, রং, পাইপ আর পরিকল্পনা", "লাভ, বেতন, ক্ষমতা আর চাপ", "পরিকল্পনা, ছাপা, ডাক আর দাম"],
        "চারটেই ঠিক হলে খদ্দের আসে।"),
    mcq("In the 4 Ps, what does 'Place' mean?", ["Where and how customers can buy the product", "The factory's address", "A seat in a cinema", "The price label"], 0,
        "Shops, websites, distributors and delivery routes.",
        "4 P-তে 'স্থান' মানে কী?", ["খদ্দের কোথায় আর কীভাবে পণ্য কিনতে পারেন", "কারখানার ঠিকানা", "সিনেমার আসন", "দামের লেবেল"],
        "দোকান, ওয়েবসাইট, পরিবেশক আর ডেলিভারি-পথ।"),
    mcq("In the 4 Ps, what is 'Promotion'?", ["Telling customers about the product through adverts, offers and PR", "Getting a better job", "Making the product", "Setting the price"], 0,
        "Promotion creates awareness and interest.",
        "4 P-তে 'প্রচার' কী?", ["বিজ্ঞাপন, অফার আর জনসংযোগে খদ্দেরদের পণ্যের কথা জানানো", "ভালো চাকরি পাওয়া", "পণ্য বানানো", "দাম ঠিক করা"],
        "প্রচার সচেতনতা আর আগ্রহ তৈরি করে।"),
    mcq("What are the stages of the 'product life cycle'?", ["Introduction, growth, maturity and decline", "Birth, school, job and retirement", "Plan, build, paint and sell", "Buy, use, break and fix"], 0,
        "Firms launch new products as old ones decline.",
        "'পণ্যের জীবনচক্রের' ধাপগুলো কী?", ["প্রবর্তন, বৃদ্ধি, পরিপক্বতা আর পতন", "জন্ম, স্কুল, চাকরি আর অবসর", "পরিকল্পনা, নির্মাণ, রং আর বিক্রি", "কেনা, ব্যবহার, ভাঙা আর সারানো"],
        "পুরোনো পণ্যের পতনের সঙ্গে সংস্থা নতুন পণ্য আনে।"),
    mcq("A type of steel bolt has sold steadily for years but sales are now slowly falling. Which stage is it in?", ["Decline", "Introduction", "Growth", "Launch"], 0,
        "Firms may refresh it or replace it with a better design.",
        "এক রকম ইস্পাতের বল্টু বছরের পর বছর স্থিরভাবে বিক্রি হয়েছে, এখন ধীরে কমছে। এটা কোন ধাপে?", ["পতন", "প্রবর্তন", "বৃদ্ধি", "উদ্বোধন"],
        "সংস্থা একে নতুন করতে বা ভালো নকশায় বদলাতে পারে।"),
    mcq("What is 'weighted scoring' in choosing a contractor?", ["Giving more importance to some criteria (like safety) than others", "Weighing the contractor", "Picking the heaviest bid", "Random choice"], 0,
        "It makes decisions fair and transparent.",
        "ঠিকাদার বাছাইয়ে 'ভারযুক্ত নম্বর' কী?", ["কিছু মানদণ্ডকে (যেমন নিরাপত্তা) অন্যদের চেয়ে বেশি গুরুত্ব দেওয়া", "ঠিকাদারকে ওজন করা", "সবচেয়ে ভারী দর বাছা", "এলোমেলো বাছাই"],
        "এতে সিদ্ধান্ত ন্যায্য আর স্বচ্ছ হয়।"),
    mcq("What is a 'conversion rate' online?", ["The percentage of visitors who actually buy", "The exchange rate", "Speed of a website", "The number of products"], 0,
        "Better photos and clear prices raise conversion.",
        "অনলাইনে 'রূপান্তরের হার' কী?", ["আগতদের কত শতাংশ সত্যিই কেনেন", "বিনিময় হার", "ওয়েবসাইটের গতি", "পণ্যের সংখ্যা"],
        "ভালো ছবি আর স্পষ্ট দাম রূপান্তর বাড়ায়।"),
    mcq("Why can you not just divide container volume by crate volume to find how many crates fit?", ["Leftover gaps along each side cannot hold a whole crate", "Crates grow", "Containers shrink", "You can always"], 0,
        "Count how many fit along each edge, then multiply.",
        "কতগুলো বাক্স আঁটবে বের করতে শুধু কনটেনারের আয়তনকে বাক্সের আয়তন দিয়ে ভাগ করা যায় না কেন?", ["প্রতি দিকের বাকি ফাঁকে পুরো বাক্স আঁটে না", "বাক্স বাড়ে", "কনটেনার ছোট হয়", "সবসময় যায়"],
        "প্রতি ধার বরাবর কতগুলো আঁটে গুনে তারপর গুণ করো।"),
    mcq("What is a 'pallet'?", ["A flat wooden or plastic base for stacking goods so forklifts can move them", "A painter's board", "A type of crate lid", "A small bed"], 0,
        "Pallets speed up loading and unloading.",
        "'প্যালেট' কী?", ["মাল স্তূপ করার কাঠ বা প্লাস্টিকের সমতল ভিত্তি, যাতে ফর্কলিফট সরাতে পারে", "চিত্রকরের বোর্ড", "এক রকম বাক্সের ঢাকনা", "ছোট খাট"],
        "প্যালেট ওঠানো-নামানো দ্রুত করে।"),
    mcq("What is 'payload'?", ["The weight of goods a vehicle can carry", "The driver's salary", "The fuel tank size", "A loan payment"], 0,
        "Never exceed a vehicle's payload - or a bridge's weight limit.",
        "'বহনযোগ্য বোঝা' (পেলোড) কী?", ["একটা যান যত ওজনের মাল বইতে পারে", "চালকের বেতন", "জ্বালানি-ট্যাংকের মাপ", "ঋণের কিস্তি"],
        "যানের পেলোড - বা সেতুর ওজন-সীমা - কখনো ছাড়াবে না।"),
    mcq("A truck's payload is 10 tonnes. A crate weighs 400 kg. How many crates can it carry?", ["25", "40", "4", "250"], 0,
        "10,000 kg ÷ 400 kg = 25.",
        "একটা ট্রাকের পেলোড 10 টন। একটা বাক্স 400 kg। কয়টি বাক্স বইতে পারে?", ["25", "40", "4", "250"],
        "10,000 kg ÷ 400 kg = 25।"),
    mcq("What is a 'fixed-price contract'?", ["The builder agrees one total price, taking the risk if costs rise", "The price changes daily", "The client pays all costs plus profit", "There is no price"], 0,
        "Good for clients wanting certainty; risky for builders.",
        "'স্থির-দামের চুক্তি' কী?", ["নির্মাতা একটা মোট দামে রাজি হন, খরচ বাড়লে ঝুঁকি তাঁর", "রোজ দাম বদলায়", "গ্রাহক সব খরচ আর লাভ দেন", "দাম নেই"],
        "নিশ্চয়তা চাওয়া গ্রাহকের জন্য ভালো; নির্মাতার জন্য ঝুঁকির।"),
    mcq("What is a 'cost-plus contract'?", ["The client pays actual costs plus an agreed fee or percentage", "One fixed total price", "Free work", "A loan contract"], 0,
        "Used when the work is hard to estimate in advance.",
        "'খরচ-যোগ চুক্তি' কী?", ["গ্রাহক প্রকৃত খরচ আর সম্মত ফি বা শতাংশ দেন", "একটা স্থির মোট দাম", "বিনামূল্যের কাজ", "ঋণের চুক্তি"],
        "আগে থেকে আন্দাজ করা কঠিন এমন কাজে ব্যবহার হয়।"),
    mcq("What is a 'variation order' in a construction contract?", ["A formal change to the agreed work, usually with a price change", "A different paint colour only", "A late fee", "A cancelled contract"], 0,
        "Changes must be written down to avoid disputes.",
        "নির্মাণ-চুক্তিতে 'পরিবর্তন-আদেশ' কী?", ["সম্মত কাজে আনুষ্ঠানিক পরিবর্তন, সাধারণত দামের পরিবর্তনসহ", "শুধু অন্য রং", "দেরির ফি", "বাতিল চুক্তি"],
        "বিবাদ এড়াতে পরিবর্তন লিখে রাখতে হয়।"),
    mcq("What is 'supply-chain risk'?", ["The chance that a problem at a supplier or in transport delays your work", "A risk of buying too much", "A safety helmet", "A tax"], 0,
        "Floods, strikes or a supplier going bust are examples.",
        "'সরবরাহ শৃঙ্খলের ঝুঁকি' কী?", ["সরবরাহকারী বা পরিবহনে সমস্যায় তোমার কাজ দেরি হওয়ার সম্ভাবনা", "বেশি কেনার ঝুঁকি", "নিরাপত্তা-হেলমেট", "কর"],
        "বন্যা, ধর্মঘট বা সরবরাহকারী দেউলিয়া হওয়া উদাহরণ।"),
    mcq("How can a bridge builder reduce supply-chain risk?", ["Use more than one supplier and keep a small safety stock", "Use one supplier only", "Never plan ahead", "Buy nothing"], 0,
        "Diversify suppliers like investors diversify money.",
        "একজন সেতু-নির্মাতা সরবরাহ শৃঙ্খলের ঝুঁকি কীভাবে কমাতে পারেন?", ["একাধিক সরবরাহকারী আর ছোট নিরাপত্তা-মজুত রাখো", "শুধু একজন সরবরাহকারী", "আগে কখনো পরিকল্পনা নয়", "কিছুই না কেনা"],
        "বিনিয়োগকারীদের টাকা ছড়ানোর মতো সরবরাহকারী ছড়াও।"),
    mcq("What is a 'distributor'?", ["A business that buys from makers and supplies many shops", "A factory worker", "A customer", "A tax officer"], 0,
        "Distributors help products reach far-off towns.",
        "'পরিবেশক' কী?", ["যে ব্যবসা নির্মাতাদের থেকে কিনে বহু দোকানে জোগান দেয়", "কারখানার কর্মী", "খদ্দের", "কর-আধিকারিক"],
        "পরিবেশক দূরের শহরে পণ্য পৌঁছাতে সাহায্য করে।"),
    mcq("What is 'B2B' trade?", ["Business-to-business sales, like a steel mill selling to a bridge builder", "Back to back", "Bank to bank only", "Buying two, getting one free"], 0,
        "B2C means business-to-consumer.",
        "'বি2বি' বাণিজ্য কী?", ["ব্যবসা-থেকে-ব্যবসা বিক্রি, যেমন ইস্পাত-কারখানা সেতু-নির্মাতাকে বেচে", "পিঠে পিঠ", "শুধু ব্যাংক থেকে ব্যাংক", "দুটো কিনলে একটা ফ্রি"],
        "বি2সি মানে ব্যবসা-থেকে-ভোক্তা।"),
    mcq("What is 'public relations' (PR)?", ["Managing a firm's reputation with the public and media", "Relatives working together", "A tax form", "Building public toilets"], 0,
        "Opening ceremonies and news stories are PR.",
        "'জনসংযোগ' (পিআর) কী?", ["জনগণ আর গণমাধ্যমে সংস্থার সুনাম সামলানো", "আত্মীয়দের একসঙ্গে কাজ", "করের ফর্ম", "জনশৌচাগার বানানো"],
        "উদ্বোধনী অনুষ্ঠান আর খবর পিআর।"),
    mcq("A bridge opening is delayed. What is good PR?", ["Explain honestly why, give a new date and say how users will be helped", "Hide it", "Blame users", "Say nothing for months"], 0,
        "Honest updates protect trust.",
        "একটা সেতুর উদ্বোধন পিছিয়েছে। ভালো পিআর কী?", ["কেন তা সৎভাবে জানাও, নতুন তারিখ দাও আর ব্যবহারকারীদের কীভাবে সাহায্য হবে বলো", "লুকাও", "ব্যবহারকারীদের দোষ দাও", "মাসের পর মাস চুপ থাকো"],
        "সৎ খবর আস্থা রক্ষা করে।"),
    mcq("What is 'differential pricing' at toll plazas?", ["Charging different vehicle types different tolls", "Charging everyone the same", "Free entry for trucks", "Random prices"], 0,
        "Heavier vehicles cause more wear, so they pay more.",
        "টোল-প্লাজায় 'পার্থক্যমূলক মূল্যনির্ধারণ' কী?", ["ভিন্ন ধরনের যানে ভিন্ন টোল", "সবার একই টোল", "ট্রাকের বিনামূল্যে প্রবেশ", "এলোমেলো দাম"],
        "ভারী যান বেশি ক্ষয় করে, তাই বেশি দেয়।"),
    mcq("What is FASTag used for in India?", ["Paying tolls electronically without stopping", "Speeding fines only", "Fuel discounts", "Parking tickets only"], 0,
        "It cuts queues and fuel wasted idling at plazas.",
        "ভারতে ফাস্ট্যাগ কীসের জন্য ব্যবহার হয়?", ["না থেমে বৈদ্যুতিনভাবে টোল দেওয়া", "শুধু দ্রুতগতির জরিমানা", "জ্বালানির ছাড়", "শুধু পার্কিং-টিকিট"],
        "লাইন আর প্লাজায় দাঁড়িয়ে নষ্ট জ্বালানি কমায়।"),
    mcq("What is 'market research data' best used for before building a toll bridge?", ["Estimating how many vehicles will use it and what they will pay", "Choosing the paint colour only", "Counting fish", "Nothing"], 0,
        "Over-optimistic traffic forecasts have bankrupted some toll roads.",
        "টোল-সেতু বানানোর আগে 'বাজার-গবেষণার তথ্য' কীসে সবচেয়ে ভালো ব্যবহার হয়?", ["কতগুলো যান ব্যবহার করবে আর কত দেবে তা আন্দাজ করতে", "শুধু রং বাছতে", "মাছ গুনতে", "কিছুতেই না"],
        "অতি-আশাবাদী যানবাহন-পূর্বাভাসে কিছু টোল-রাস্তা দেউলিয়া হয়েছে।"),
    mcq("What is an 'Incoterm' like FOB (Free On Board)?", ["An international rule for when the seller's responsibility for goods ends", "A type of ship", "A customs fine", "A shipping container size"], 0,
        "FOB: the seller pays until goods are loaded onto the ship.",
        "এফওবি (ফ্রি অন বোর্ড)-এর মতো 'ইনকোটার্ম' কী?", ["আন্তর্জাতিক নিয়ম, যা ঠিক করে মালের দায় বিক্রেতার কোথায় শেষ", "এক রকম জাহাজ", "শুল্কের জরিমানা", "কনটেনারের মাপ"],
        "এফওবি: মাল জাহাজে না ওঠা পর্যন্ত খরচ বিক্রেতার।"),
    mcq("What is a 'letter of credit' in trade?", ["A bank's promise to pay the seller once agreed documents are shown", "A thank-you note", "A loan to a customer", "A tax refund letter"], 0,
        "It lets strangers in different countries trade safely.",
        "বাণিজ্যে 'ঋণপত্র' (লেটার অফ ক্রেডিট) কী?", ["সম্মত নথি দেখালে বিক্রেতাকে দাম দেওয়ার ব্যাংকের প্রতিশ্রুতি", "ধন্যবাদ-চিঠি", "খদ্দেরকে ঋণ", "করের ফেরতের চিঠি"],
        "এতে বিভিন্ন দেশের অচেনা মানুষ নিরাপদে বাণিজ্য করতে পারেন।"),
    mcq("What is 'last-mile delivery'?", ["The final step getting goods from a local hub to the customer's door", "The last kilometre of a race", "A long-distance train", "A ship's final port"], 0,
        "It is often the most expensive part per parcel.",
        "'শেষ-মাইলের ডেলিভারি' কী?", ["স্থানীয় কেন্দ্র থেকে খদ্দেরের দোরগোড়ায় মাল পৌঁছানোর শেষ ধাপ", "দৌড়ের শেষ কিলোমিটার", "দূরপাল্লার ট্রেন", "জাহাজের শেষ বন্দর"],
        "প্রায়ই পার্সেলপ্রতি সবচেয়ে ব্যয়বহুল অংশ।"),
    mcq("What is 'route optimisation'?", ["Planning the shortest or cheapest order of delivery stops", "Painting road lines", "Building new routes only", "Driving as fast as possible"], 0,
        "Software can save lots of fuel and time.",
        "'পথ-অনুকূলন' কী?", ["ডেলিভারি-বিরতির সবচেয়ে ছোট বা সস্তা ক্রম পরিকল্পনা", "রাস্তার দাগ রং করা", "শুধু নতুন পথ বানানো", "যত দ্রুত সম্ভব চালানো"],
        "সফটওয়্যার অনেক জ্বালানি আর সময় বাঁচাতে পারে।"),
    mcq("A van must visit A, B and C. Distances: depot-A 5, A-B 3, B-C 4, C-depot 6, depot-C 6, C-A 7, B-depot 8 km. Which round trip is shortest?", ["Depot-A-B-C-depot (18 km)", "Depot-C-A-B-depot (24 km)", "Depot-B-A-C-depot", "All are equal"], 0,
        "5 + 3 + 4 + 6 = 18 km; depot-C-A-B-depot = 6 + 7 + 3 + 8 = 24 km.",
        "একটা ভ্যানকে A, B আর C-তে যেতে হবে। দূরত্ব: ডিপো-A 5, A-B 3, B-C 4, C-ডিপো 6, ডিপো-C 6, C-A 7, B-ডিপো 8 km। কোন চক্রপথ সবচেয়ে ছোট?", ["ডিপো-A-B-C-ডিপো (18 km)", "ডিপো-C-A-B-ডিপো (24 km)", "ডিপো-B-A-C-ডিপো", "সব সমান"],
        "5 + 3 + 4 + 6 = 18 km; ডিপো-C-A-B-ডিপো = 6 + 7 + 3 + 8 = 24 km।"),
    mcq("What is 'customer satisfaction' measured with, often?", ["Surveys and ratings, like 1-5 stars", "A thermometer", "A tape measure", "A weighing scale"], 0,
        "Feedback tells firms what to fix.",
        "'খদ্দেরের সন্তুষ্টি' প্রায়ই কী দিয়ে মাপা হয়?", ["সমীক্ষা আর রেটিং, যেমন 1-5 তারা", "থার্মোমিটার", "মাপার ফিতে", "দাঁড়িপাল্লা"],
        "প্রতিক্রিয়া সংস্থাকে জানায় কী সারাতে হবে।"),
    mcq("An app gets ratings 5, 4, 4, 3 and 5 stars. What is the average?", ["4.2", "4", "21", "3.5"], 0,
        "(5 + 4 + 4 + 3 + 5) ÷ 5 = 21 ÷ 5 = 4.2.",
        "একটা অ্যাপ 5, 4, 4, 3 আর 5 তারা পেল। গড় কত?", ["4.2", "4", "21", "3.5"],
        "(5 + 4 + 4 + 3 + 5) ÷ 5 = 21 ÷ 5 = 4.2।"),
    mcq("What is a 'service level agreement' (SLA)?", ["A promise of how fast and how well a service will be delivered", "A loan agreement", "A tax rule", "A bridge drawing"], 0,
        "E.g., 'repairs within 24 hours, 99% of the time'.",
        "'পরিষেবা-স্তর চুক্তি' (এসএলএ) কী?", ["পরিষেবা কত দ্রুত আর কত ভালোভাবে দেওয়া হবে তার প্রতিশ্রুতি", "ঋণের চুক্তি", "করের নিয়ম", "সেতুর নকশা"],
        "যেমন, '99% ক্ষেত্রে 24 ঘণ্টার মধ্যে মেরামত'।"),
    mcq("Why do firms 'benchmark' against competitors?", ["To compare performance and find ways to improve", "To copy illegally", "To lower quality", "To raise tax"], 0,
        "Learning from the best raises standards.",
        "সংস্থা প্রতিযোগীদের সঙ্গে 'মানদণ্ড-তুলনা' করে কেন?", ["কাজের তুলনা করে উন্নতির উপায় খুঁজতে", "বেআইনিভাবে নকল করতে", "মান কমাতে", "কর বাড়াতে"],
        "সেরাদের থেকে শিখলে মান বাড়ে।"),
    mcq("What is 'corporate social responsibility' (CSR) in India?", ["Large companies spending part of profit on social good, as required by law", "A tax-free shop", "A loan scheme", "A type of bridge"], 0,
        "CSR funds have built schools, clinics and village footbridges.",
        "ভারতে 'কর্পোরেট সামাজিক দায়িত্ব' (সিএসআর) কী?", ["আইন অনুযায়ী বড় কোম্পানির লাভের অংশ সামাজিক কল্যাণে খরচ", "করমুক্ত দোকান", "ঋণ-প্রকল্প", "এক রকম সেতু"],
        "সিএসআর তহবিলে স্কুল, চিকিৎসাকেন্দ্র আর গ্রামের হাঁটার সেতু তৈরি হয়েছে।"),
    mcq("Indian law asks big companies to spend about what share of average profit on CSR?", ["2%", "50%", "0.1%", "20%"], 0,
        "Companies above certain size limits must spend 2% of average net profit.",
        "ভারতের আইনে বড় কোম্পানিকে গড় লাভের মোটামুটি কত অংশ সিএসআর-এ খরচ করতে বলে?", ["2%", "50%", "0.1%", "20%"],
        "নির্দিষ্ট মাপের বেশি কোম্পানিকে গড় নিট লাভের 2% খরচ করতে হয়।"),
    score(6, 9, 9, 7, 40, 60), score(8, 6, 7, 8, 60, 40), score(9, 5, 5, 9, 80, 20), score(7, 7, 8, 6, 50, 50),
    conv(3000, 90), conv(1500, 15), conv(25000, 500),
    boxes(20, 10, 9, 6, 4, 3), boxes(16, 9, 8, 5, 4, 3), boxes(30, 12, 10, 7, 5, 4),
    tollmix(2000, 35, 400, 140, 150, 110), tollmix(800, 25, 100, 100, 60, 80), tollmix(4000, 45, 600, 180, 250, 120),
    eta(360, 60, 3, 20), eta(90, 30, 1, 15), eta(420, 70, 4, 15),
    mcq("What is a 'loss leader'?", ["A product sold cheaply, even at a loss, to bring customers into a shop", "A failing manager", "A broken product", "The best-selling item at full price"], 0,
        "Customers often buy other, profitable items too.",
        "'ক্ষতি-টানা পণ্য' (লস লিডার) কী?", ["দোকানে খদ্দের টানতে সস্তায়, এমনকি ক্ষতিতে বেচা পণ্য", "ব্যর্থ ম্যানেজার", "ভাঙা পণ্য", "পুরো দামে সবচেয়ে বেশি বিক্রি হওয়া জিনিস"],
        "খদ্দের প্রায়ই অন্য লাভজনক জিনিসও কেনেন।"),
    mcq("What is 'bundling' in pricing?", ["Selling several products together for one lower price", "Tying products with rope", "Raising prices", "Selling one item only"], 0,
        "A helmet, gloves and boots safety bundle is cheaper than buying each.",
        "মূল্যনির্ধারণে 'একত্রীকরণ' (বান্ডলিং) কী?", ["কয়েকটা পণ্য একসঙ্গে কম এক দামে বেচা", "দড়ি দিয়ে পণ্য বাঁধা", "দাম বাড়ানো", "শুধু একটা জিনিস বেচা"],
        "হেলমেট, দস্তানা আর বুটের সুরক্ষা-বান্ডল আলাদা কেনার চেয়ে সস্তা।"),
    mcq("What is 'dynamic pricing'?", ["Prices that change with demand, time or conditions", "Prices that never change", "Free prices", "Prices set by lottery"], 0,
        "Peak-hour tolls and train fares use it.",
        "'গতিশীল মূল্যনির্ধারণ' কী?", ["চাহিদা, সময় বা অবস্থা অনুযায়ী বদলানো দাম", "কখনো না বদলানো দাম", "বিনামূল্যের দাম", "লটারিতে ঠিক হওয়া দাম"],
        "ব্যস্ত সময়ের টোল আর ট্রেনের ভাড়া এটা ব্যবহার করে।"),
    mcq("What is a 'target market' for a company making prefabricated footbridges?", ["Local governments, villages, parks and railway operators", "Toddlers", "Fishermen's boats only", "Space agencies"], 0,
        "Knowing the target market guides design and marketing.",
        "আগে-তৈরি হাঁটার সেতু বানানো কোম্পানির 'লক্ষ্য-বাজার' কী?", ["স্থানীয় সরকার, গ্রাম, পার্ক আর রেল-পরিচালক", "ছোট শিশু", "শুধু জেলেদের নৌকা", "মহাকাশ সংস্থা"],
        "লক্ষ্য-বাজার জানলে নকশা আর বিপণন ঠিক হয়।"),
    mcq("What is 'brand awareness'?", ["How well people recognise and remember a brand", "A brand's price", "A factory's size", "A delivery date"], 0,
        "Sponsoring local events raises awareness.",
        "'ব্র্যান্ড-সচেতনতা' কী?", ["মানুষ একটা ব্র্যান্ড কতটা চেনেন আর মনে রাখেন", "ব্র্যান্ডের দাম", "কারখানার মাপ", "ডেলিভারির তারিখ"],
        "স্থানীয় অনুষ্ঠানে পৃষ্ঠপোষকতা সচেতনতা বাড়ায়।"),
    mcq("What is a 'sales funnel'?", ["The steps from first noticing a product to buying it", "A kitchen funnel", "A tax form", "A warehouse door"], 0,
        "Awareness -> interest -> decision -> purchase.",
        "'বিক্রয়-ফানেল' কী?", ["পণ্য প্রথম চোখে পড়া থেকে কেনা পর্যন্ত ধাপ", "রান্নাঘরের চোঙ", "করের ফর্ম", "গুদামের দরজা"],
        "সচেতনতা -> আগ্রহ -> সিদ্ধান্ত -> কেনা।"),
    mcq("What is 'inventory shrinkage'?", ["Stock lost to theft, damage or errors", "Stock getting smaller in the sun", "New stock arriving", "Selling more"], 0,
        "Good records and security reduce it.",
        "'মজুত-ঘাটতি' কী?", ["চুরি, ক্ষতি বা ভুলে হারানো মজুত", "রোদে মজুত ছোট হওয়া", "নতুন মাল আসা", "বেশি বিক্রি"],
        "ভালো হিসাব আর নিরাপত্তা এটা কমায়।"),
    mcq("A warehouse records 500 bags but finds 480. What is the shrinkage percentage?", ["4%", "20%", "96%", "2%"], 0,
        "20 missing ÷ 500 x 100 = 4%.",
        "একটা গুদামের হিসাবে 500 বস্তা, পাওয়া গেল 480। ঘাটতি কত শতাংশ?", ["4%", "20%", "96%", "2%"],
        "20টি নেই ÷ 500 x 100 = 4%।"),
    mcq("What is 'FIFO' in a warehouse?", ["First In, First Out - oldest stock is used first", "Fast In, Fast Out", "Free Items For Owners", "Fix It, Fix Others"], 0,
        "Important for cement, which spoils with age.",
        "গুদামে 'ফিফো' কী?", ["আগে এলে আগে যাবে - পুরোনো মজুত আগে ব্যবহার", "দ্রুত ঢোকো, দ্রুত বেরোও", "মালিকদের বিনামূল্যের জিনিস", "নিজে সারাও, অন্যকে সারাও"],
        "সিমেন্টের জন্য জরুরি, যা পুরোনো হলে নষ্ট হয়।"),
    mcq("What is a 'barcode' used for in shops and warehouses?", ["Scanning items quickly to track price and stock", "Decorating boxes", "Locking doors", "Measuring weight"], 0,
        "Scanning cuts errors and speeds up checkout.",
        "দোকান আর গুদামে 'বারকোড' কীসে ব্যবহার হয়?", ["দাম আর মজুত জানতে জিনিস দ্রুত স্ক্যান করা", "বাক্স সাজানো", "দরজা বন্ধ করা", "ওজন মাপা"],
        "স্ক্যান করলে ভুল কমে আর বিল দ্রুত হয়।"),
    mcq("What is a 'tender document'?", ["The written description of a job that bidders price against", "A soft piece of paper", "A receipt", "A payslip"], 0,
        "It includes drawings, specifications and contract terms.",
        "'দরপত্র-নথি' কী?", ["কাজের লিখিত বিবরণ, যার ভিত্তিতে দরদাতারা দাম দেন", "নরম কাগজ", "রসিদ", "বেতনপত্র"],
        "এতে নকশা, বিবরণী আর চুক্তির শর্ত থাকে।"),
    mcq("What is a 'specification' in construction?", ["A detailed description of required materials, standards and workmanship", "A pair of glasses", "A guess", "A sales poster"], 0,
        "E.g., 'concrete grade M30, steel Fe500'.",
        "নির্মাণে 'বিবরণী' (স্পেসিফিকেশন) কী?", ["প্রয়োজনীয় উপাদান, মান আর কারিগরির বিস্তারিত বিবরণ", "এক জোড়া চশমা", "আন্দাজ", "বিক্রির পোস্টার"],
        "যেমন, 'কংক্রিট গ্রেড M30, ইস্পাত Fe500'।"),
    mcq("What is a 'bill of quantities'?", ["A list of all materials and work items with amounts, used for pricing", "A restaurant bill", "A list of workers' names", "A bank statement"], 0,
        "Bidders fill in rates to calculate their total price.",
        "'পরিমাণের তালিকা' (বিল অফ কোয়ান্টিটিজ) কী?", ["দাম ঠিক করতে পরিমাণসহ সব উপাদান আর কাজের তালিকা", "রেস্তোরাঁর বিল", "কর্মীদের নামের তালিকা", "ব্যাংক-বিবরণী"],
        "দরদাতারা হার বসিয়ে মোট দাম হিসাব করেন।"),
    mcq("A bill of quantities lists 50 m³ of concrete at Rs 6,000 per m³ and 4 tonnes of steel at Rs 60,000 per tonne. Total?", ["Rs 5,40,000", "Rs 3,00,000", "Rs 2,40,000", "Rs 66,000"], 0,
        "50 x 6,000 = 3,00,000; 4 x 60,000 = 2,40,000; total 5,40,000.",
        "পরিমাণের তালিকায় 50 m³ কংক্রিট m³-প্রতি 6,000 টাকায় আর 4 টন ইস্পাত টনপ্রতি 60,000 টাকায়। মোট?", ["5,40,000 টাকা", "3,00,000 টাকা", "2,40,000 টাকা", "66,000 টাকা"],
        "50 x 6,000 = 3,00,000; 4 x 60,000 = 2,40,000; মোট 5,40,000।"),
    mcq("What is 'earnest money deposit' (EMD) in a tender?", ["A small deposit bidders pay to show they are serious", "A gift to officials", "A loan to the client", "A fine"], 0,
        "It is returned to unsuccessful bidders.",
        "দরপত্রে 'বায়না-জমা' (ইএমডি) কী?", ["দরদাতারা আন্তরিকতা দেখাতে যে ছোট জমা দেন", "আধিকারিকদের উপহার", "গ্রাহককে ঋণ", "জরিমানা"],
        "অসফল দরদাতাদের তা ফেরত দেওয়া হয়।"),
    mcq("What is a 'performance bond'?", ["A guarantee that pays the client if the contractor fails to finish the work", "A bond between friends", "A sports trophy", "A type of glue"], 0,
        "It protects public money on big projects.",
        "'কাজের জামানত' (পারফরম্যান্স বন্ড) কী?", ["ঠিকাদার কাজ শেষ করতে না পারলে গ্রাহককে টাকা দেওয়ার নিশ্চয়তা", "বন্ধুদের বন্ধন", "খেলার ট্রফি", "এক রকম আঠা"],
        "বড় প্রকল্পে জনগণের টাকা রক্ষা করে।"),
    mcq("What is 'liquidated damages' in a contract?", ["A fixed amount the contractor pays for each day of delay", "Water damage", "A refund for faulty goods", "A bonus for speed"], 0,
        "It is agreed in advance, so there is no argument later.",
        "চুক্তিতে 'নির্ধারিত ক্ষতিপূরণ' কী?", ["প্রতি দিনের দেরির জন্য ঠিকাদারের দেওয়া নির্দিষ্ট অঙ্ক", "জলের ক্ষতি", "ত্রুটিপূর্ণ মালের টাকা ফেরত", "দ্রুততার বোনাস"],
        "আগে থেকে সম্মত হয়, তাই পরে তর্ক থাকে না।"),
    mcq("What is 'force majeure' in a contract?", ["Events beyond anyone's control, like floods or earthquakes, that excuse delays", "A strong worker", "A military order", "A penalty"], 0,
        "It means neither side is blamed for such disasters.",
        "চুক্তিতে 'অপ্রতিরোধ্য ঘটনা' (ফোর্স মেজিওর) কী?", ["বন্যা বা ভূমিকম্পের মতো কারও নিয়ন্ত্রণের বাইরের ঘটনা, যা দেরি মাফ করে", "শক্তিশালী কর্মী", "সামরিক আদেশ", "জরিমানা"],
        "এমন বিপর্যয়ে কোনো পক্ষকেই দোষ দেওয়া হয় না।"),
    mcq("Why do contracts include a 'dispute resolution' clause?", ["To agree in advance how disagreements will be settled, like arbitration", "To start fights", "To cancel work", "To raise prices"], 0,
        "Arbitration is usually faster and cheaper than court.",
        "চুক্তিতে 'বিবাদ-নিষ্পত্তি' ধারা থাকে কেন?", ["মতভেদ কীভাবে মেটানো হবে (যেমন সালিশি) তা আগে থেকে ঠিক করতে", "ঝগড়া শুরু করতে", "কাজ বাতিল করতে", "দাম বাড়াতে"],
        "সালিশি সাধারণত আদালতের চেয়ে দ্রুত আর সস্তা।"),
    mcq("What is 'subcontracting'?", ["A main contractor hiring another firm for part of the work", "Cancelling a contract", "Working underwater", "A tax"], 0,
        "A bridge builder might subcontract the painting or electrical work.",
        "'উপ-ঠিকা' (সাবকন্ট্র্যাক্টিং) কী?", ["প্রধান ঠিকাদার কাজের অংশে অন্য সংস্থা নিয়োগ করেন", "চুক্তি বাতিল", "জলের নিচে কাজ", "কর"],
        "সেতু-নির্মাতা রং বা বিদ্যুতের কাজ উপ-ঠিকায় দিতে পারেন।"),
    mcq("What is a 'site diary'?", ["A daily record of work done, weather, workers and problems on site", "A personal journal", "A tax book", "A sales brochure"], 0,
        "It is valuable evidence if disputes arise.",
        "'নির্মাণস্থলের দিনলিপি' কী?", ["নির্মাণস্থলে রোজকার কাজ, আবহাওয়া, কর্মী আর সমস্যার হিসাব", "ব্যক্তিগত ডায়েরি", "করের খাতা", "বিক্রির পুস্তিকা"],
        "বিবাদ হলে এটা মূল্যবান প্রমাণ।"),
    mcq("Why do firms keep 'customer data' private and secure?", ["It is the law and protects customers from fraud", "It is useless", "To sell it secretly", "No reason"], 0,
        "Leaking data destroys trust and brings fines.",
        "সংস্থা 'খদ্দেরের তথ্য' গোপন আর সুরক্ষিত রাখে কেন?", ["এটা আইন আর খদ্দেরদের প্রতারণা থেকে বাঁচায়", "এটা অকেজো", "গোপনে বেচতে", "কোনো কারণ নেই"],
        "তথ্য ফাঁস আস্থা নষ্ট করে আর জরিমানা আনে।"),
    mcq("What does 'GST registration' allow a business to do?", ["Collect GST on sales and claim credit for GST paid on purchases", "Avoid all taxes", "Print money", "Skip paying workers"], 0,
        "Registered firms file regular GST returns.",
        "'জিএসটি নিবন্ধন' ব্যবসাকে কী করতে দেয়?", ["বিক্রিতে জিএসটি আদায় আর কেনায় দেওয়া জিএসটির ক্রেডিট নেওয়া", "সব কর এড়ানো", "টাকা ছাপানো", "কর্মীদের বেতন না দেওয়া"],
        "নিবন্ধিত সংস্থা নিয়মিত জিএসটি রিটার্ন দাখিল করে।"),
    mcq("What is 'e-procurement'?", ["Running tenders and purchasing online for transparency and speed", "Buying electronics only", "Email spam", "A type of loan"], 0,
        "Government e-procurement portals publish tenders openly.",
        "'ই-সংগ্রহ' (ই-প্রোকিওরমেন্ট) কী?", ["স্বচ্ছতা আর গতির জন্য অনলাইনে দরপত্র আর কেনাকাটা", "শুধু বৈদ্যুতিন জিনিস কেনা", "ইমেলের জঞ্জাল", "এক রকম ঋণ"],
        "সরকারি ই-সংগ্রহ পোর্টাল প্রকাশ্যে দরপত্র প্রকাশ করে।"),
    mcq("What is 'just-in-case' stock?", ["Extra stock held to guard against delays or surprises", "Stock that is never used", "Stock for decoration", "Borrowed stock"], 0,
        "The opposite of just-in-time.",
        "'যদি-লাগে' মজুত (জাস্ট-ইন-কেস) কী?", ["দেরি বা আকস্মিকতা সামলাতে রাখা বাড়তি মজুত", "কখনো ব্যবহার না হওয়া মজুত", "সাজসজ্জার মজুত", "ধার করা মজুত"],
        "ঠিক-সময়ের উল্টো।"),
    mcq("Why might a firm choose rail freight over road even if it is slower?", ["It is cheaper per tonne and produces less pollution", "Rail is always faster", "Roads are always closed", "Trucks cannot carry steel"], 0,
        "For heavy, non-urgent loads, rail often wins.",
        "ধীর হলেও সংস্থা সড়কের বদলে রেলে মাল পাঠানো বাছতে পারে কেন?", ["টনপ্রতি সস্তা আর কম দূষণ", "রেল সবসময় দ্রুত", "রাস্তা সবসময় বন্ধ", "ট্রাক ইস্পাত বইতে পারে না"],
        "ভারী, অ-জরুরি বোঝায় প্রায়ই রেল জেতে।"),
)
