"""Class 6 - Math (Junior Cadet): solving linear equations, substitution, nth terms, area and
circumference of circles, volume of prisms and cylinders, Pythagoras for truss members,
angles with parallel lines, probability, averages from tables, and straight-line graphs."""
from . import mcq


def _o(r, *alts):
    out = []
    for x in (r, *alts, r + 1, r + 2, r * 2, r + 10):
        if x not in out and x >= 0:
            out.append(x)
    return out[:4]


def _n(q_en, q_bn, r, ex_en, ex_bn, alts, u_en="", u_bn=""):
    f = lambda x: f"{x:,}" if isinstance(x, int) else f"{x:g}"
    o = _o(r, *alts)
    return mcq(q_en, [f(x) + u_en for x in o], 0, ex_en, q_bn, [f(x) + u_bn for x in o], ex_bn)


def solve(a, b, c):
    x = (c - b) // a
    return _n(f"Solve {a}x + {b} = {c}.", f"সমাধান করো: {a}x + {b} = {c}।", x,
              f"Subtract {b}: {a}x = {c - b}. Divide by {a}: x = {x}.",
              f"{b} বিয়োগ: {a}x = {c - b}। {a} দিয়ে ভাগ: x = {x}।",
              (c - b, (c + b) // a, x + a))


def subst(a, b, x):
    r = a * x * x + b
    return _n(f"Find the value of {a}x² + {b} when x = {x}.", f"x = {x} হলে {a}x² + {b}-এর মান কত?", r,
              f"x² = {x * x}; {a} x {x * x} = {a * x * x}; + {b} = {r}.",
              f"x² = {x * x}; {a} x {x * x} = {a * x * x}; + {b} = {r}।",
              ((a * x) ** 2 + b, a * x * 2 + b, a * x + b))


def nth(a, b, n):
    seq = ", ".join(str(a * k + b) for k in range(1, 5))
    r = a * n + b
    return _n(f"The sequence {seq}, ... has nth term {a}n {'+' if b >= 0 else '-'} {abs(b)}. What is the {n}th term?",
              f"{seq}, ... অনুক্রমের n-তম পদ {a}n {'+' if b >= 0 else '-'} {abs(b)}। {n}-তম পদ কত?", r,
              f"{a} x {n} {'+' if b >= 0 else '-'} {abs(b)} = {r}.",
              f"{a} x {n} {'+' if b >= 0 else '-'} {abs(b)} = {r}।",
              (a * n, r + a, a + n + b))


def circ_area(r_, what_en, what_bn):
    a = 22 * r_ * r_ // 7
    return _n(f"{what_en} has radius {r_} m. Using π = 22/7, what is its area?",
              f"{what_bn}-এর ব্যাসার্ধ {r_} m। π = 22/7 ধরে ক্ষেত্রফল কত?", a,
              f"Area = πr² = 22/7 x {r_} x {r_} = {a} m².",
              f"ক্ষেত্রফল = πr² = 22/7 x {r_} x {r_} = {a} m²।",
              (44 * r_ // 7, 22 * r_ * 2 // 7 * r_, r_ * r_), " m²", " m²")


def circ_len(d, what_en, what_bn):
    c = 22 * d // 7
    return _n(f"{what_en} has diameter {d} m. Using π = 22/7, what is its circumference?",
              f"{what_bn}-এর ব্যাস {d} m। π = 22/7 ধরে পরিধি কত?", c,
              f"C = πd = 22/7 x {d} = {c} m.",
              f"পরিধি = πd = 22/7 x {d} = {c} m।",
              (c * 2, 11 * d * d // 14, d * 3), " m", " m")


def cyl(r_, h, what_en, what_bn):
    v = 22 * r_ * r_ * h // 7
    return _n(f"{what_en} is a cylinder with radius {r_} m and height {h} m. Using π = 22/7, what is its volume?",
              f"{what_bn} একটা চোঙ, ব্যাসার্ধ {r_} m আর উচ্চতা {h} m। π = 22/7 ধরে আয়তন কত?", v,
              f"V = πr²h = 22/7 x {r_}² x {h} = {v} m³.",
              f"আয়তন = πr²h = 22/7 x {r_}² x {h} = {v} m³।",
              (22 * r_ * h // 7 * 2, 22 * r_ * r_ // 7, r_ * r_ * h), " m³", " m³")


def pyth(a, b, what_en, what_bn):
    c = int((a * a + b * b) ** 0.5)
    return _n(f"{what_en}: one side is {a} m and the other {b} m, at a right angle. How long is the diagonal?",
              f"{what_bn}: এক বাহু {a} m আর অন্যটি {b} m, সমকোণে। কর্ণ কত লম্বা?", c,
              f"Pythagoras: c² = {a}² + {b}² = {a * a} + {b * b} = {c * c}; c = {c} m.",
              f"পিথাগোরাস: c² = {a}² + {b}² = {a * a} + {b * b} = {c * c}; c = {c} m।",
              (a + b, c * c, abs(b - a) if b != a else c + 3), " m", " m")


def prism(base_area, length, what_en, what_bn):
    v = base_area * length
    return _n(f"{what_en} has a cross-section of {base_area} m² and is {length} m long. What is its volume?",
              f"{what_bn}-এর প্রস্থচ্ছেদ {base_area} m² আর দৈর্ঘ্য {length} m। আয়তন কত?", v,
              f"Prism volume = cross-section area x length = {base_area} x {length} = {v} m³.",
              f"প্রিজমের আয়তন = প্রস্থচ্ছেদের ক্ষেত্রফল x দৈর্ঘ্য = {base_area} x {length} = {v} m³।",
              (base_area + length, v * 2, v // 2 if v > 2 else v + 5), " m³", " m³")


ITEMS = (
    solve(3, 5, 26), solve(5, 12, 47), solve(7, 4, 60), solve(4, 9, 41), solve(6, 15, 63), solve(2, 19, 45),
    subst(2, 3, 4), subst(3, 1, 5), subst(5, 7, 2), subst(4, 10, 3),
    nth(3, 2, 10), nth(5, -1, 20), nth(4, 3, 15), nth(7, -4, 12),
    circ_area(7, "A circular pier footing", "একটা বৃত্তাকার থাম-পাদভিত্তি"),
    circ_area(14, "A round fountain", "একটা গোল ফোয়ারা"),
    circ_area(21, "A circular roundabout", "একটা বৃত্তাকার চত্বর"),
    circ_len(14, "A circular pier cap", "একটা বৃত্তাকার থাম-মাথা"), circ_len(35, "A circular track", "একটা বৃত্তাকার পথ"),
    circ_len(7, "A water tank", "একটা জলের ট্যাংক"),
    cyl(7, 10, "A caisson (giant hollow pier foundation)", "একটা কেসন (বিশাল ফাঁপা থাম-ভিত)"), cyl(1, 14, "A concrete column", "একটা কংক্রিটের স্তম্ভ"),
    cyl(14, 5, "A water tower tank", "একটা জলের মিনারের ট্যাংক"),
    pyth(3, 4, "A truss panel", "একটা ট্রাস-প্যানেল"), pyth(6, 8, "A bridge bracing panel", "একটা সেতুর ঠেকনা-প্যানেল"),
    pyth(5, 12, "A ramp support", "একটা ঢালের অবলম্বন"), pyth(9, 12, "A crane jib frame", "একটা ক্রেনের বাহু-কাঠামো"),
    pyth(8, 15, "A tower brace", "একটা টাওয়ারের ঠেকনা"), pyth(12, 16, "A stair stringer", "একটা সিঁড়ির পাশ-কাঠামো"),
    prism(6, 20, "A triangular concrete beam", "একটা ত্রিভুজাকার কংক্রিটের বিম"),
    prism(2, 50, "A steel girder", "একটা ইস্পাতের গার্ডার"), prism(12, 8, "An embankment section", "বাঁধের একটা অংশ"),
    mcq("Simplify 3a + 5a - 2a.", ["6a", "10a", "8a", "6"], 0,
        "Collect like terms: 3 + 5 - 2 = 6.",
        "সরল করো: 3a + 5a - 2a।", ["6a", "10a", "8a", "6"],
        "সদৃশ পদ একত্র করো: 3 + 5 - 2 = 6।"),
    mcq("Simplify 4x + 3y - x + 2y.", ["3x + 5y", "5x + 5y", "3x + y", "8xy"], 0,
        "x terms: 4 - 1 = 3; y terms: 3 + 2 = 5.",
        "সরল করো: 4x + 3y - x + 2y।", ["3x + 5y", "5x + 5y", "3x + y", "8xy"],
        "x পদ: 4 - 1 = 3; y পদ: 3 + 2 = 5।"),
    mcq("Expand 3(x + 4).", ["3x + 12", "3x + 4", "x + 12", "3x + 7"], 0,
        "Multiply each term inside by 3.",
        "বিস্তার করো: 3(x + 4)।", ["3x + 12", "3x + 4", "x + 12", "3x + 7"],
        "ভেতরের প্রতিটি পদকে 3 দিয়ে গুণ করো।"),
    mcq("Factorise 6x + 9.", ["3(2x + 3)", "6(x + 9)", "3(2x + 9)", "9(6x + 1)"], 0,
        "The HCF of 6 and 9 is 3.",
        "উৎপাদকে বিশ্লেষণ করো: 6x + 9।", ["3(2x + 3)", "6(x + 9)", "3(2x + 9)", "9(6x + 1)"],
        "6 আর 9-এর গসাগু 3।"),
    mcq("Solve x/4 = 7.", ["x = 28", "x = 11", "x = 3", "x = 1.75"], 0,
        "Multiply both sides by 4.",
        "সমাধান করো: x/4 = 7।", ["x = 28", "x = 11", "x = 3", "x = 1.75"],
        "দুই দিককে 4 দিয়ে গুণ করো।"),
    mcq("Solve 5x - 3 = 2x + 12.", ["x = 5", "x = 3", "x = 9", "x = 15"], 0,
        "Take 2x from both sides: 3x - 3 = 12; add 3: 3x = 15; x = 5.",
        "সমাধান করো: 5x - 3 = 2x + 12।", ["x = 5", "x = 3", "x = 9", "x = 15"],
        "দুই দিক থেকে 2x বিয়োগ: 3x - 3 = 12; 3 যোগ: 3x = 15; x = 5।"),
    mcq("A bridge has 3 spans of length L and one 40 m span. Total length 190 m. What is L?", ["50 m", "63 m", "150 m", "40 m"], 0,
        "3L + 40 = 190, so 3L = 150 and L = 50.",
        "একটা সেতুতে L দৈর্ঘ্যের 3টি স্প্যান আর একটা 40 m স্প্যান। মোট 190 m। L কত?", ["50 m", "63 m", "150 m", "40 m"],
        "3L + 40 = 190, তাই 3L = 150 আর L = 50।"),
    mcq("Which inequality means 'x is at least 5'?", ["x ≥ 5", "x > 5", "x ≤ 5", "x < 5"], 0,
        "'At least' includes 5 itself.",
        "কোন অসমতা মানে 'x অন্তত 5'?", ["x ≥ 5", "x > 5", "x ≤ 5", "x < 5"],
        "'অন্তত' মানে 5 নিজেও ধরা।"),
    mcq("A truck must weigh at most 40 tonnes to cross. Which describes allowed weight w?", ["w ≤ 40", "w ≥ 40", "w > 40", "w = 0"], 0,
        "'At most' means 40 or less.",
        "পার হতে একটা ট্রাকের ওজন সর্বোচ্চ 40 টন হতে পারে। অনুমোদিত ওজন w কোনটা বোঝায়?", ["w ≤ 40", "w ≥ 40", "w > 40", "w = 0"],
        "'সর্বোচ্চ' মানে 40 বা কম।"),
    mcq("What is the gradient of the line y = 3x + 2?", ["3", "2", "5", "1/3"], 0,
        "In y = mx + c, m is the gradient (slope).",
        "y = 3x + 2 রেখার নতি কত?", ["3", "2", "5", "1/3"],
        "y = mx + c-তে m হলো নতি (ঢাল)।"),
    mcq("Where does y = 2x - 5 cross the y-axis?", ["(0, -5)", "(0, 2)", "(-5, 0)", "(2, -5)"], 0,
        "The y-intercept is c = -5.",
        "y = 2x - 5 রেখা y-অক্ষকে কোথায় ছেদ করে?", ["(0, -5)", "(0, 2)", "(-5, 0)", "(2, -5)"],
        "y-ছেদক c = -5।"),
    mcq("A ramp rises 1 m for every 20 m along. What is its gradient?", ["1/20 (5%)", "20", "1/2", "21"], 0,
        "Gradient = rise ÷ run = 1 ÷ 20.",
        "একটা ঢাল প্রতি 20 m-এ 1 m ওঠে। তার নতি কত?", ["1/20 (5%)", "20", "1/2", "21"],
        "নতি = উত্থান ÷ অনুভূমিক দূরত্ব = 1 ÷ 20।"),
    mcq("Point A is (2, 3) and point B is (8, 11). What is the midpoint?", ["(5, 7)", "(10, 14)", "(6, 8)", "(3, 4)"], 0,
        "Average the x's and the y's: ((2 + 8)/2, (3 + 11)/2).",
        "বিন্দু A (2, 3) আর বিন্দু B (8, 11)। মধ্যবিন্দু কত?", ["(5, 7)", "(10, 14)", "(6, 8)", "(3, 4)"],
        "x আর y-গুলোর গড় নাও: ((2 + 8)/2, (3 + 11)/2)।"),
    mcq("Two parallel lines are cut by a transversal. Alternate angles are...", ["Equal", "Add up to 180°", "Always 90°", "Unrelated"], 0,
        "Z-angles are equal - handy for checking truss geometry.",
        "দুটি সমান্তরাল রেখাকে একটা ছেদক কাটলে একান্তর কোণগুলো...", ["সমান", "যোগফল 180°", "সবসময় 90°", "সম্পর্কহীন"],
        "Z-কোণ সমান - ট্রাসের জ্যামিতি যাচাইয়ে কাজের।"),
    mcq("Co-interior angles between parallel lines add up to...", ["180°", "90°", "360°", "They are equal"], 0,
        "C-angles are supplementary.",
        "সমান্তরাল রেখার মাঝের সন্নিহিত অন্তঃস্থ কোণের যোগফল...", ["180°", "90°", "360°", "এরা সমান"],
        "C-কোণ সম্পূরক।"),
    mcq("A truss diagonal meets the top chord at 50°. The chords are parallel. What angle does it make with the bottom chord (alternate)?", ["50°", "130°", "40°", "90°"], 0,
        "Alternate angles between parallel lines are equal.",
        "ট্রাসের একটা কর্ণ উপরের দণ্ডের সঙ্গে 50° কোণ করে। দণ্ড দুটো সমান্তরাল। নিচের দণ্ডের সঙ্গে (একান্তর) কত কোণ করে?", ["50°", "130°", "40°", "90°"],
        "সমান্তরাল রেখার মাঝে একান্তর কোণ সমান।"),
    mcq("What is the sum of interior angles of a hexagon?", ["720°", "540°", "360°", "1080°"], 0,
        "(n - 2) x 180 = 4 x 180 = 720°.",
        "ষড়ভুজের অন্তঃকোণগুলোর যোগফল কত?", ["720°", "540°", "360°", "1080°"],
        "(n - 2) x 180 = 4 x 180 = 720°।"),
    mcq("Each interior angle of a regular hexagon is...", ["120°", "60°", "108°", "135°"], 0,
        "720 ÷ 6 = 120°.",
        "সুষম ষড়ভুজের প্রতিটি অন্তঃকোণ...", ["120°", "60°", "108°", "135°"],
        "720 ÷ 6 = 120°।"),
    mcq("A fair die is rolled. What is the probability of a 6?", ["1/6", "1/2", "6", "1/3"], 0,
        "1 favourable outcome out of 6 equally likely ones.",
        "একটা নিরপেক্ষ লুডোর ছক্কা গড়ানো হলো। 6 পড়ার সম্ভাবনা কত?", ["1/6", "1/2", "6", "1/3"],
        "6টি সমসম্ভব ফলের মধ্যে 1টি অনুকূল।"),
    mcq("A bag has 3 red and 7 blue bolts. What is the probability of picking red?", ["3/10", "3/7", "7/10", "1/3"], 0,
        "3 red out of 10 bolts.",
        "একটা ব্যাগে 3টি লাল আর 7টি নীল বল্টু। লাল তোলার সম্ভাবনা কত?", ["3/10", "3/7", "7/10", "1/3"],
        "10টি বল্টুর মধ্যে 3টি লাল।"),
    mcq("The probability of rain tomorrow is 0.3. What is the probability of no rain?", ["0.7", "0.3", "1.3", "0"], 0,
        "Probabilities of all outcomes add to 1.",
        "কাল বৃষ্টির সম্ভাবনা 0.3। বৃষ্টি না হওয়ার সম্ভাবনা কত?", ["0.7", "0.3", "1.3", "0"],
        "সব ফলের সম্ভাবনার যোগফল 1।"),
    mcq("A coin is tossed twice. What is the probability of two heads?", ["1/4", "1/2", "1/3", "2/4"], 0,
        "Outcomes: HH, HT, TH, TT - one of four.",
        "একটা মুদ্রা দুবার টস করা হলো। দুটোই হেড হওয়ার সম্ভাবনা কত?", ["1/4", "1/2", "1/3", "2/4"],
        "ফল: HH, HT, TH, TT - চারটির একটি।"),
    mcq("A test shows 2 of every 50 bolts are faulty. About how many faulty in 1,000?", ["40", "20", "2", "100"], 0,
        "2/50 = 4%; 4% of 1,000 = 40. This is 'expected frequency'.",
        "পরীক্ষায় প্রতি 50টি বল্টুর 2টি ত্রুটিপূর্ণ। 1,000-এ মোটামুটি কয়টি ত্রুটিপূর্ণ?", ["40", "20", "2", "100"],
        "2/50 = 4%; 1,000-এর 4% = 40। একে বলে 'প্রত্যাশিত পরিসংখ্যা'।"),
    mcq("Trucks per hour: 10 (3 hours), 20 (5 hours), 30 (2 hours). What is the mean per hour?", ["19", "20", "60", "10"], 0,
        "(10x3 + 20x5 + 30x2) ÷ 10 = (30 + 100 + 60) ÷ 10 = 19.",
        "ঘণ্টাপ্রতি ট্রাক: 10 (3 ঘণ্টা), 20 (5 ঘণ্টা), 30 (2 ঘণ্টা)। ঘণ্টাপ্রতি গড় কত?", ["19", "20", "60", "10"],
        "(10x3 + 20x5 + 30x2) ÷ 10 = (30 + 100 + 60) ÷ 10 = 19।"),
    mcq("How many cm² are in 1 m²?", ["10,000", "100", "1,000", "1,000,000"], 0,
        "1 m = 100 cm, so 1 m² = 100 x 100 = 10,000 cm².",
        "1 m²-এ কত cm²?", ["10,000", "100", "1,000", "1,000,000"],
        "1 m = 100 cm, তাই 1 m² = 100 x 100 = 10,000 cm²।"),
    mcq("How many litres are in 1 m³?", ["1,000", "100", "10", "10,000"], 0,
        "1 m³ = 1,000 litres.",
        "1 m³-এ কত লিটার?", ["1,000", "100", "10", "10,000"],
        "1 m³ = 1,000 লিটার।"),
    mcq("A plan is drawn at 1 : 250. A beam is 4 cm on the plan. How long is it really?", ["10 m", "1 m", "100 m", "2.5 m"], 0,
        "4 x 250 = 1,000 cm = 10 m.",
        "একটা নকশা 1 : 250 মাপে আঁকা। নকশায় একটা বিম 4 cm। বাস্তবে কত লম্বা?", ["10 m", "1 m", "100 m", "2.5 m"],
        "4 x 250 = 1,000 cm = 10 m।"),
    mcq("What is a bearing of 090°?", ["Due east", "Due north", "Due south", "Due west"], 0,
        "Bearings are measured clockwise from north: 000° N, 090° E, 180° S, 270° W.",
        "090° দিগংশ মানে কী?", ["ঠিক পূর্ব", "ঠিক উত্তর", "ঠিক দক্ষিণ", "ঠিক পশ্চিম"],
        "দিগংশ উত্তর থেকে ঘড়ির কাঁটার দিকে মাপা হয়: 000° উ, 090° পূ, 180° দ, 270° প।"),
    mcq("A surveyor walks on a bearing of 180°. Which way are they heading?", ["South", "North", "East", "West"], 0,
        "180° is half a turn from north.",
        "একজন জরিপকারী 180° দিগংশে হাঁটছেন। কোন দিকে যাচ্ছেন?", ["দক্ষিণ", "উত্তর", "পূর্ব", "পশ্চিম"],
        "180° হলো উত্তর থেকে অর্ধেক পাক।"),
    mcq("Write 4,500,000 in standard form.", ["4.5 x 10^6", "45 x 10^5", "4.5 x 10^5", "0.45 x 10^7"], 0,
        "One digit before the point, times a power of 10.",
        "4,500,000-কে আদর্শ রূপে লেখো।", ["4.5 x 10^6", "45 x 10^5", "4.5 x 10^5", "0.45 x 10^7"],
        "দশমিকের আগে একটা অঙ্ক, তার সঙ্গে 10-এর ঘাত।"),
    mcq("Increase Rs 800 by 15%.", ["Rs 920", "Rs 815", "Rs 680", "Rs 1,200"], 0,
        "800 x 1.15 = 920.",
        "800 টাকাকে 15% বাড়াও।", ["920 টাকা", "815 টাকা", "680 টাকা", "1,200 টাকা"],
        "800 x 1.15 = 920।"),
    mcq("Decrease 250 kg by 20%.", ["200 kg", "230 kg", "50 kg", "300 kg"], 0,
        "250 x 0.8 = 200.",
        "250 kg-কে 20% কমাও।", ["200 kg", "230 kg", "50 kg", "300 kg"],
        "250 x 0.8 = 200।"),
    mcq("What is 3/8 as a decimal?", ["0.375", "0.38", "3.8", "0.83"], 0,
        "3 ÷ 8 = 0.375.",
        "3/8 দশমিকে কত?", ["0.375", "0.38", "3.8", "0.83"],
        "3 ÷ 8 = 0.375।"),
    mcq("What is 2/3 of 3/4?", ["1/2", "5/7", "6/7", "8/9"], 0,
        "2/3 x 3/4 = 6/12 = 1/2.",
        "3/4-এর 2/3 কত?", ["1/2", "5/7", "6/7", "8/9"],
        "2/3 x 3/4 = 6/12 = 1/2।"),
    mcq("What is 3/5 ÷ 3/10?", ["2", "9/50", "1/2", "6/5"], 0,
        "Flip and multiply: 3/5 x 10/3 = 2.",
        "3/5 ÷ 3/10 কত?", ["2", "9/50", "1/2", "6/5"],
        "উল্টে গুণ করো: 3/5 x 10/3 = 2।"),
    mcq("What is (-4) x (-6)?", ["24", "-24", "-10", "10"], 0,
        "Negative times negative is positive.",
        "(-4) x (-6) কত?", ["24", "-24", "-10", "10"],
        "ঋণাত্মক গুণ ঋণাত্মক ধনাত্মক।"),
    mcq("What is -20 ÷ 4?", ["-5", "5", "-80", "-16"], 0,
        "Negative divided by positive is negative.",
        "-20 ÷ 4 কত?", ["-5", "5", "-80", "-16"],
        "ঋণাত্মক ভাগ ধনাত্মক ঋণাত্মক।"),
    mcq("A riverbed is at -8 m and a deck at +14 m. How high is the deck above the riverbed?", ["22 m", "6 m", "14 m", "-22 m"], 0,
        "14 - (-8) = 22.",
        "নদীতল -8 m-এ আর পাটাতন +14 m-এ। পাটাতন নদীতল থেকে কত উঁচু?", ["22 m", "6 m", "14 m", "-22 m"],
        "14 - (-8) = 22।"),
    mcq("What is the square root of 144?", ["12", "14", "72", "11"], 0,
        "12 x 12 = 144.",
        "144-এর বর্গমূল কত?", ["12", "14", "72", "11"],
        "12 x 12 = 144।"),
    mcq("Between which two whole numbers is √50?", ["7 and 8", "6 and 7", "8 and 9", "24 and 25"], 0,
        "7² = 49 and 8² = 64.",
        "√50 কোন দুটি পূর্ণসংখ্যার মাঝে?", ["7 আর 8", "6 আর 7", "8 আর 9", "24 আর 25"],
        "7² = 49 আর 8² = 64।"),
    mcq("Which triple can make a right-angled triangle?", ["5, 12, 13", "4, 5, 6", "2, 3, 4", "6, 7, 8"], 0,
        "25 + 144 = 169 = 13².",
        "কোন তিনটি মাপে সমকোণী ত্রিভুজ হয়?", ["5, 12, 13", "4, 5, 6", "2, 3, 4", "6, 7, 8"],
        "25 + 144 = 169 = 13²।"),
    mcq("Builders use a 3-4-5 rope triangle. Why?", ["It guarantees a perfect right angle without special tools", "It is a lucky number", "It measures weight", "It stops rain"], 0,
        "Ancient builders used knotted ropes the same way.",
        "নির্মাতারা 3-4-5 দড়ির ত্রিভুজ ব্যবহার করেন কেন?", ["বিশেষ যন্ত্র ছাড়াই নিখুঁত সমকোণ নিশ্চিত করে", "শুভ সংখ্যা", "ওজন মাপে", "বৃষ্টি থামায়"],
        "প্রাচীন নির্মাতারাও গিঁট-দেওয়া দড়ি এভাবে ব্যবহার করতেন।"),
    mcq("A ladder 10 m long leans against a pier with its foot 6 m away. How high does it reach?", ["8 m", "4 m", "16 m", "12 m"], 0,
        "10² - 6² = 100 - 36 = 64; √64 = 8 m.",
        "10 m লম্বা একটা মই একটা থামে হেলানো, তলা 6 m দূরে। কত উঁচুতে পৌঁছায়?", ["8 m", "4 m", "16 m", "12 m"],
        "10² - 6² = 100 - 36 = 64; √64 = 8 m।"),
    mcq("What is the surface area of a cube with 3 m edges?", ["54 m²", "27 m²", "9 m²", "36 m²"], 0,
        "6 faces x 9 m² = 54 m² - handy for working out paint needed.",
        "3 m ধারের ঘনকের পৃষ্ঠতলের ক্ষেত্রফল কত?", ["54 m²", "27 m²", "9 m²", "36 m²"],
        "6টি তল x 9 m² = 54 m² - কত রং লাগবে তা বের করতে কাজের।"),
    mcq("Paint covers 12 m² per litre. How many litres for 54 m²?", ["4.5 litres", "6 litres", "648 litres", "42 litres"], 0,
        "54 ÷ 12 = 4.5.",
        "রং লিটারপ্রতি 12 m² ঢাকে। 54 m²-এর জন্য কত লিটার?", ["4.5 লিটার", "6 লিটার", "648 লিটার", "42 লিটার"],
        "54 ÷ 12 = 4.5।"),
    mcq("What is 15% of 15% as a percentage?", ["2.25%", "30%", "0.15%", "225%"], 0,
        "0.15 x 0.15 = 0.0225 = 2.25%.",
        "15%-এর 15% শতাংশে কত?", ["2.25%", "30%", "0.15%", "225%"],
        "0.15 x 0.15 = 0.0225 = 2.25%।"),
    mcq("A map scale is 1 : 50,000. 3 cm on the map is how far in reality?", ["1.5 km", "15 km", "150 m", "0.15 km"], 0,
        "3 x 50,000 = 150,000 cm = 1,500 m = 1.5 km.",
        "মানচিত্রের মাপ 1 : 50,000। মানচিত্রে 3 cm বাস্তবে কত দূর?", ["1.5 km", "15 km", "150 m", "0.15 km"],
        "3 x 50,000 = 1,50,000 cm = 1,500 m = 1.5 km।"),
    mcq("Which is the best estimate of 6.9 x 31.2?", ["About 210", "About 21", "About 2,100", "About 38"], 0,
        "7 x 30 = 210.",
        "6.9 x 31.2-এর সেরা আন্দাজ কোনটা?", ["প্রায় 210", "প্রায় 21", "প্রায় 2,100", "প্রায় 38"],
        "7 x 30 = 210।"),
    solve(8, 6, 70), solve(9, 2, 83), solve(3, 18, 39),
    subst(6, 5, 2), subst(2, 9, 6),
    nth(6, 1, 25), nth(2, 9, 30),
    circ_area(35, "A circular sports ground", "একটা বৃত্তাকার খেলার মাঠ"),
    circ_area(28, "A circular park beside the bridge", "সেতুর পাশের একটা বৃত্তাকার পার্ক"),
    circ_len(28, "A circular cofferdam", "একটা বৃত্তাকার কফারড্যাম"),
    cyl(2, 7, "A drainage culvert pipe section", "একটা জল-নিকাশি কালভার্ট পাইপের অংশ"),
    pyth(15, 20, "A cable-stayed fan panel", "তার-ঝোলানো সেতুর একটা পাখা-প্যানেল"), pyth(7, 24, "A long ramp frame", "একটা লম্বা ঢালের কাঠামো"),
    prism(3, 40, "A precast deck slab", "একটা আগে-ঢালাই পাটাতন-স্ল্যাব"), prism(15, 6, "A retaining wall section", "একটা ধারক-দেওয়ালের অংশ"),
    mcq("Make r the subject of C = 2πr.", ["r = C ÷ 2π", "r = 2πC", "r = C - 2π", "r = C x π ÷ 2"], 0,
        "Divide both sides by 2π.",
        "C = 2πr থেকে r-কে বিষয় করো।", ["r = C ÷ 2π", "r = 2πC", "r = C - 2π", "r = C x π ÷ 2"],
        "দুই দিককে 2π দিয়ে ভাগ করো।"),
    mcq("Using speed = distance ÷ time, which gives time?", ["time = distance ÷ speed", "time = speed x distance", "time = speed ÷ distance", "time = distance - speed"], 0,
        "Rearranging formulas is a key engineering skill.",
        "গতি = দূরত্ব ÷ সময় থেকে সময় কোনটা?", ["সময় = দূরত্ব ÷ গতি", "সময় = গতি x দূরত্ব", "সময় = গতি ÷ দূরত্ব", "সময় = দূরত্ব - গতি"],
        "সূত্র সাজিয়ে নেওয়া প্রকৌশলের একটা মূল দক্ষতা।"),
    mcq("A cyclist rides 18 km in 45 minutes. What is the speed in km/h?", ["24 km/h", "40 km/h", "13.5 km/h", "0.4 km/h"], 0,
        "45 min = 0.75 h; 18 ÷ 0.75 = 24 km/h.",
        "একজন সাইকেল-আরোহী 45 মিনিটে 18 km যান। km/h-এ গতি কত?", ["24 km/h", "40 km/h", "13.5 km/h", "0.4 km/h"],
        "45 মিনিট = 0.75 ঘণ্টা; 18 ÷ 0.75 = 24 km/h।"),
    mcq("What is the reciprocal of 4/5?", ["5/4", "4/5", "-4/5", "1/5"], 0,
        "Flip the fraction: 5/4. A number times its reciprocal is 1.",
        "4/5-এর অন্যোন্যক কত?", ["5/4", "4/5", "-4/5", "1/5"],
        "ভগ্নাংশ উল্টে দাও: 5/4। কোনো সংখ্যা x তার অন্যোন্যক = 1।"),
    mcq("A recipe for concrete uses cement : sand : gravel = 1 : 2 : 3. What fraction is gravel?", ["1/2", "1/3", "3/5", "1/6"], 0,
        "Total parts 6; gravel 3/6 = 1/2.",
        "কংক্রিটের মিশ্রণে সিমেন্ট : বালি : পাথরকুচি = 1 : 2 : 3। পাথরকুচি কোন ভগ্নাংশ?", ["1/2", "1/3", "3/5", "1/6"],
        "মোট 6 ভাগ; পাথরকুচি 3/6 = 1/2।"),
)
