"""Class 6 - Chemistry (Junior Cadet): particle model, atomic structure, the periodic table's
groups, the reactivity series and displacement, counting atoms and relative formula mass,
balancing equations, acids with metals and carbonates, the limestone cycle, electroplating,
crude oil and polymers - with bridge-building examples."""
from . import mcq

AR = {"H": 1, "C": 12, "N": 14, "O": 16, "Na": 23, "Mg": 24, "Al": 27, "S": 32, "Cl": 35.5,
      "Ca": 40, "Fe": 56, "Cu": 64, "Zn": 65}


def _o(r, *alts):
    out = []
    for x in (r, *alts, r + 2, r + 16, r * 2):
        if x not in out and x > 0:
            out.append(x)
    return out[:4]


def mr(formula, parts, name_en, name_bn):
    r = sum(AR[e] * n for e, n in parts)
    r = int(r) if r == int(r) else r
    working = " + ".join(f"{n} x {AR[e]:g}" if n > 1 else f"{AR[e]:g}" for e, n in parts)
    o = _o(r, sum(AR[e] for e, _ in parts), r - 16 if r > 16 else r + 4, r + 12)
    f = lambda x: f"{x:g}"
    return mcq(f"What is the relative formula mass (Mr) of {name_en}, {formula}? (Use Ar: " + ", ".join(f"{e} = {AR[e]:g}" for e, _ in parts) + ")",
               [f(x) for x in o], 0,
               f"Add the atomic masses: {working} = {r:g}.",
               f"{name_bn} ({formula})-এর আপেক্ষিক সংকেত-ভর (Mr) কত? (Ar: " + ", ".join(f"{e} = {AR[e]:g}" for e, _ in parts) + ")",
               [f(x) for x in o],
               f"পারমাণবিক ভর যোগ করো: {working} = {r:g}।")


def atoms(formula, n, name_en, name_bn):
    o = _o(n, n - 1, n + 1, len(formula))
    return mcq(f"How many atoms in total are in one unit of {name_en}, {formula}?", [str(x) for x in o], 0,
               f"Count every atom shown by the symbols and small numbers in {formula}: {n}.",
               f"{name_bn} ({formula})-এর এক এককে মোট কয়টি পরমাণু?", [str(x) for x in o],
               f"{formula}-এর সংকেত আর ছোট সংখ্যা দেখে প্রতিটি পরমাণু গোনো: {n}।")


def displace(metal_en, metal_bn, salt_en, salt_bn, yes):
    o = ["Yes - it is more reactive, so it displaces the other metal", "No - it is less reactive, so nothing happens",
         "Only if heated to 1,000 °C", "Only in the dark"]
    o_bn = ["হ্যাঁ - এটা বেশি সক্রিয়, তাই অন্য ধাতুকে প্রতিস্থাপন করে", "না - এটা কম সক্রিয়, তাই কিছুই হয় না",
            "শুধু 1,000 °C-এ গরম করলে", "শুধু অন্ধকারে"]
    return mcq(f"Will {metal_en} react with {salt_en} solution?", o, 0 if yes else 1,
               "A more reactive metal pushes a less reactive metal out of its compound. Reactivity: K > Na > Ca > Mg > Al > Zn > Fe > Cu > Ag > Au.",
               f"{metal_bn} কি {salt_bn}-এর দ্রবণের সঙ্গে বিক্রিয়া করবে?", o_bn,
               "বেশি সক্রিয় ধাতু কম সক্রিয় ধাতুকে তার যৌগ থেকে সরিয়ে দেয়। সক্রিয়তা: K > Na > Ca > Mg > Al > Zn > Fe > Cu > Ag > Au।")


ITEMS = (
    mr("H2O", [("H", 2), ("O", 1)], "water", "জল"),
    mr("CO2", [("C", 1), ("O", 2)], "carbon dioxide", "কার্বন ডাই-অক্সাইড"),
    mr("CaCO3", [("Ca", 1), ("C", 1), ("O", 3)], "calcium carbonate (limestone)", "ক্যালসিয়াম কার্বোনেট (চুনাপাথর)"),
    mr("CaO", [("Ca", 1), ("O", 1)], "calcium oxide (quicklime)", "ক্যালসিয়াম অক্সাইড (কলিচুন)"),
    mr("Fe2O3", [("Fe", 2), ("O", 3)], "iron(III) oxide (rust)", "আয়রন(III) অক্সাইড (মরচে)"),
    mr("NaCl", [("Na", 1), ("Cl", 1)], "sodium chloride", "সোডিয়াম ক্লোরাইড"),
    mr("MgO", [("Mg", 1), ("O", 1)], "magnesium oxide", "ম্যাগনেশিয়াম অক্সাইড"),
    mr("CH4", [("C", 1), ("H", 4)], "methane", "মিথেন"),
    mr("ZnO", [("Zn", 1), ("O", 1)], "zinc oxide", "জিঙ্ক অক্সাইড"),
    mr("H2SO4", [("H", 2), ("S", 1), ("O", 4)], "sulphuric acid", "সালফিউরিক অ্যাসিড"),
    mr("NH3", [("N", 1), ("H", 3)], "ammonia", "অ্যামোনিয়া"),
    mr("Al2O3", [("Al", 2), ("O", 3)], "aluminium oxide", "অ্যালুমিনিয়াম অক্সাইড"),
    atoms("CaCO3", 5, "calcium carbonate", "ক্যালসিয়াম কার্বোনেট"),
    atoms("H2SO4", 7, "sulphuric acid", "সালফিউরিক অ্যাসিড"),
    atoms("C6H12O6", 24, "glucose", "গ্লুকোজ"),
    atoms("Fe2O3", 5, "iron(III) oxide", "আয়রন(III) অক্সাইড"),
    atoms("NH3", 4, "ammonia", "অ্যামোনিয়া"),
    atoms("Ca(OH)2", 5, "calcium hydroxide (slaked lime)", "ক্যালসিয়াম হাইড্রক্সাইড (কলিচুন-জল)"),
    displace("magnesium", "ম্যাগনেশিয়াম", "copper sulphate", "কপার সালফেট", True),
    displace("copper", "তামা", "zinc sulphate", "জিঙ্ক সালফেট", False),
    displace("zinc", "দস্তা", "iron sulphate", "আয়রন সালফেট", True),
    displace("iron", "লোহা", "copper sulphate", "কপার সালফেট", True),
    displace("silver", "রুপো", "copper nitrate", "কপার নাইট্রেট", False),
    displace("copper", "তামা", "silver nitrate", "সিলভার নাইট্রেট", True),
    mcq("In the particle model, how are particles arranged in a solid?", ["Tightly packed in a regular pattern, vibrating in place", "Far apart and moving fast", "Touching but sliding past each other", "Not moving at all and far apart"], 0,
        "Strong forces hold solid particles in place - that is why steel keeps its shape.",
        "কণা-মডেলে কঠিনে কণাগুলো কীভাবে সাজানো?", ["নিয়মিত নকশায় ঘন ঠাসা, জায়গায় কাঁপে", "দূরে দূরে আর দ্রুত চলে", "ছুঁয়ে থাকে কিন্তু পাশ কাটিয়ে সরে", "একদম না নড়ে দূরে দূরে"],
        "শক্তিশালী বল কঠিনের কণা ধরে রাখে - তাই ইস্পাত আকার ধরে রাখে।"),
    mcq("Why can liquids flow but keep the same volume?", ["Particles touch but can slide past each other", "Particles are far apart", "Particles are fixed", "Liquids have no particles"], 0,
        "Fresh concrete flows into moulds for the same reason.",
        "তরল গড়াতে পারে কিন্তু আয়তন একই থাকে কেন?", ["কণাগুলো ছুঁয়ে থাকে কিন্তু পাশ কাটিয়ে সরতে পারে", "কণাগুলো দূরে দূরে", "কণাগুলো স্থির", "তরলে কণা নেই"],
        "একই কারণে তাজা কংক্রিট ছাঁচে গড়িয়ে যায়।"),
    mcq("Why can a gas be squashed (compressed) easily?", ["Its particles are far apart with lots of space", "Its particles are tightly packed", "Gases have no mass", "It cannot"], 0,
        "Compressed air powers tools like jackhammers.",
        "গ্যাসকে সহজে চাপা (সংকুচিত) যায় কেন?", ["কণাগুলো দূরে দূরে, অনেক ফাঁকা জায়গা", "কণাগুলো ঘন ঠাসা", "গ্যাসের ভর নেই", "যায় না"],
        "চাপা বাতাস জ্যাকহ্যামারের মতো যন্ত্র চালায়।"),
    mcq("What happens to particles when a solid is heated?", ["They vibrate more and move slightly apart, so it expands", "They shrink", "They stop moving", "They turn into new atoms"], 0,
        "This is why bridges need expansion joints.",
        "কঠিন গরম করলে কণাগুলোর কী হয়?", ["বেশি কাঁপে আর সামান্য দূরে সরে, তাই প্রসারিত হয়", "ছোট হয়", "থেমে যায়", "নতুন পরমাণু হয়"],
        "তাই সেতুর প্রসারণ-জোড় লাগে।"),
    mcq("What is 'diffusion'?", ["Particles spreading from where there are many to where there are few", "Freezing", "A chemical reaction", "Particles stopping"], 0,
        "The smell of fresh paint spreading across a room is diffusion.",
        "'ব্যাপন' কী?", ["কণার বেশি থাকার জায়গা থেকে কম থাকার জায়গায় ছড়ানো", "জমা", "রাসায়নিক বিক্রিয়া", "কণা থেমে যাওয়া"],
        "তাজা রঙের গন্ধ ঘরে ছড়ানো ব্যাপন।"),
    mcq("What three particles make up an atom?", ["Protons, neutrons and electrons", "Cells, tissues and organs", "Molecules, ions and salts", "Light, heat and sound"], 0,
        "Protons and neutrons are in the nucleus; electrons orbit around it.",
        "কোন তিনটি কণা দিয়ে পরমাণু তৈরি?", ["প্রোটন, নিউট্রন আর ইলেকট্রন", "কোষ, কলা আর অঙ্গ", "অণু, আয়ন আর লবণ", "আলো, তাপ আর শব্দ"],
        "প্রোটন আর নিউট্রন নিউক্লিয়াসে; ইলেকট্রন চারপাশে ঘোরে।"),
    mcq("What is the charge on an electron?", ["Negative", "Positive", "Neutral", "Double positive"], 0,
        "Protons are positive, neutrons have no charge.",
        "ইলেকট্রনের আধান কী?", ["ঋণাত্মক", "ধনাত্মক", "নিরপেক্ষ", "দ্বিগুণ ধনাত্মক"],
        "প্রোটন ধনাত্মক, নিউট্রনের আধান নেই।"),
    mcq("What does the 'atomic number' of an element tell you?", ["The number of protons in its atoms", "Its mass in kg", "How many neutrons it has", "Its melting point"], 0,
        "Carbon has 6 protons, so its atomic number is 6.",
        "মৌলের 'পারমাণবিক সংখ্যা' কী জানায়?", ["তার পরমাণুতে প্রোটনের সংখ্যা", "kg-এ তার ভর", "কতগুলো নিউট্রন", "তার গলনাঙ্ক"],
        "কার্বনের 6টি প্রোটন, তাই পারমাণবিক সংখ্যা 6।"),
    mcq("Iron has atomic number 26. How many electrons does a neutral iron atom have?", ["26", "56", "30", "13"], 0,
        "Neutral atoms have equal numbers of protons and electrons.",
        "লোহার পারমাণবিক সংখ্যা 26। নিরপেক্ষ লোহার পরমাণুতে কয়টি ইলেকট্রন?", ["26", "56", "30", "13"],
        "নিরপেক্ষ পরমাণুতে প্রোটন আর ইলেকট্রন সমান।"),
    mcq("An iron atom has mass number 56 and atomic number 26. How many neutrons?", ["30", "26", "56", "82"], 0,
        "Neutrons = mass number - atomic number = 56 - 26 = 30.",
        "একটা লোহার পরমাণুর ভরসংখ্যা 56 আর পারমাণবিক সংখ্যা 26। কয়টি নিউট্রন?", ["30", "26", "56", "82"],
        "নিউট্রন = ভরসংখ্যা - পারমাণবিক সংখ্যা = 56 - 26 = 30।"),
    mcq("What is an 'isotope'?", ["Atoms of the same element with different numbers of neutrons", "A type of molecule", "A new element", "A charged particle"], 0,
        "Carbon-12 and carbon-14 are isotopes; carbon-14 helps date ancient wood.",
        "'আইসোটোপ' কী?", ["একই মৌলের পরমাণু, কিন্তু নিউট্রন-সংখ্যা আলাদা", "এক রকম অণু", "নতুন মৌল", "আহিত কণা"],
        "কার্বন-12 আর কার্বন-14 আইসোটোপ; কার্বন-14 প্রাচীন কাঠের বয়স মাপতে সাহায্য করে।"),
    mcq("In the periodic table, what are the vertical columns called?", ["Groups", "Periods", "Rows", "Families of metals only"], 0,
        "Elements in a group have similar chemical properties.",
        "পর্যায় সারণিতে খাড়া স্তম্ভগুলোকে কী বলে?", ["শ্রেণি (গ্রুপ)", "পর্যায়", "সারি", "শুধু ধাতুর পরিবার"],
        "একই শ্রেণির মৌলের রাসায়নিক ধর্ম একই রকম।"),
    mcq("What are the horizontal rows of the periodic table called?", ["Periods", "Groups", "Columns", "Blocks of noble gases"], 0,
        "Across a period, elements change from metals to non-metals.",
        "পর্যায় সারণির আনুভূমিক সারিগুলোকে কী বলে?", ["পর্যায়", "শ্রেণি", "স্তম্ভ", "নিষ্ক্রিয় গ্যাসের ব্লক"],
        "পর্যায় বরাবর মৌলগুলো ধাতু থেকে অধাতুতে বদলায়।"),
    mcq("Group 1 metals (lithium, sodium, potassium) are known for being...", ["Very reactive - they fizz in water", "Completely unreactive", "Gases at room temperature", "Strong building metals"], 0,
        "They are stored under oil. Never used to build bridges!",
        "গ্রুপ 1-এর ধাতু (লিথিয়াম, সোডিয়াম, পটাশিয়াম) কীসের জন্য পরিচিত?", ["খুব সক্রিয় - জলে বুদবুদ ছাড়ে", "পুরো নিষ্ক্রিয়", "ঘরের তাপমাত্রায় গ্যাস", "শক্ত নির্মাণ-ধাতু"],
        "এদের তেলের নিচে রাখা হয়। সেতু বানাতে কখনো ব্যবহার হয় না!"),
    mcq("Group 0 (noble gases) such as helium, neon and argon are...", ["Very unreactive", "Explosive metals", "Strong acids", "Liquids"], 0,
        "Argon shields welds from air during welding.",
        "গ্রুপ 0-এর (নিষ্ক্রিয় গ্যাস) হিলিয়াম, নিয়ন আর আর্গন...", ["খুব নিষ্ক্রিয়", "বিস্ফোরক ধাতু", "শক্তিশালী অ্যাসিড", "তরল"],
        "ঝালাইয়ের সময় আর্গন বাতাস থেকে ঝালাইকে আড়াল করে।"),
    mcq("Why is argon gas blown over some welds?", ["It keeps oxygen away so the hot metal does not react", "It cools the welder", "It adds iron", "It makes sparks bigger"], 0,
        "Unreactive gas shielding gives clean, strong welds.",
        "কিছু ঝালাইয়ের উপর আর্গন গ্যাস ছড়ানো হয় কেন?", ["অক্সিজেন দূরে রাখে যাতে গরম ধাতু বিক্রিয়া না করে", "ঝালাইকারীকে ঠান্ডা রাখে", "লোহা যোগ করে", "স্ফুলিঙ্গ বড় করে"],
        "নিষ্ক্রিয় গ্যাসের আবরণ পরিষ্কার, শক্ত ঝালাই দেয়।"),
    mcq("Group 7 elements (chlorine, bromine, iodine) are called...", ["Halogens", "Noble gases", "Alkali metals", "Transition metals"], 0,
        "Chlorine is used to disinfect drinking water.",
        "গ্রুপ 7-এর মৌলগুলো (ক্লোরিন, ব্রোমিন, আয়োডিন) কী নামে পরিচিত?", ["হ্যালোজেন", "নিষ্ক্রিয় গ্যাস", "ক্ষার ধাতু", "অবস্থান্তর ধাতু"],
        "খাবার জল জীবাণুমুক্ত করতে ক্লোরিন ব্যবহার হয়।"),
    mcq("Iron, copper and zinc are in the middle block of the periodic table. What are they called?", ["Transition metals", "Noble gases", "Halogens", "Alkali metals"], 0,
        "Transition metals are strong, dense and often make coloured compounds.",
        "লোহা, তামা আর দস্তা পর্যায় সারণির মাঝের ব্লকে। এদের কী বলে?", ["অবস্থান্তর ধাতু", "নিষ্ক্রিয় গ্যাস", "হ্যালোজেন", "ক্ষার ধাতু"],
        "অবস্থান্তর ধাতু শক্ত, ঘন আর প্রায়ই রঙিন যৌগ তৈরি করে।"),
    mcq("What is the 'reactivity series'?", ["A list of metals in order of how readily they react", "A TV series", "A list of acids", "The order of the periodic table"], 0,
        "It explains why zinc protects iron, and why gold never rusts.",
        "'সক্রিয়তা শ্রেণি' কী?", ["কত সহজে বিক্রিয়া করে সেই ক্রমে ধাতুর তালিকা", "টিভি সিরিজ", "অ্যাসিডের তালিকা", "পর্যায় সারণির ক্রম"],
        "এটা ব্যাখ্যা করে কেন দস্তা লোহাকে রক্ষা করে, আর সোনায় কেন মরচে ধরে না।"),
    mcq("Why does zinc protect iron in galvanised steel?", ["Zinc is more reactive, so it corrodes first", "Zinc is less reactive", "Zinc is a gas", "Zinc repels water magnetically"], 0,
        "The more reactive metal sacrifices itself.",
        "গ্যালভানাইজড ইস্পাতে দস্তা লোহাকে রক্ষা করে কেন?", ["দস্তা বেশি সক্রিয়, তাই আগে ক্ষয় হয়", "দস্তা কম সক্রিয়", "দস্তা গ্যাস", "দস্তা চুম্বকে জল সরায়"],
        "বেশি সক্রিয় ধাতু নিজেকে উৎসর্গ করে।"),
    mcq("Why is gold found as pure metal in nature, but iron is found as ore?", ["Gold is very unreactive; iron reacts and forms compounds", "Gold is magnetic", "Iron is rarer", "Gold is a gas"], 0,
        "Less reactive metals are easier to find pure.",
        "প্রকৃতিতে সোনা বিশুদ্ধ ধাতু হিসেবে আর লোহা আকরিক হিসেবে পাওয়া যায় কেন?", ["সোনা খুব নিষ্ক্রিয়; লোহা বিক্রিয়া করে যৌগ তৈরি করে", "সোনা চুম্বকীয়", "লোহা দুষ্প্রাপ্য", "সোনা গ্যাস"],
        "কম সক্রিয় ধাতু বিশুদ্ধ অবস্থায় পাওয়া সহজ।"),
    mcq("How is iron extracted from its oxide in a blast furnace?", ["Carbon (as carbon monoxide) removes the oxygen - reduction", "By dissolving in water", "By electricity only", "By freezing"], 0,
        "Carbon is more reactive than iron, so it takes iron's oxygen.",
        "মারুত চুল্লিতে লোহা তার অক্সাইড থেকে কীভাবে নিষ্কাশিত হয়?", ["কার্বন (কার্বন মনোক্সাইড হিসেবে) অক্সিজেন সরায় - বিজারণ", "জলে গুলে", "শুধু বিদ্যুতে", "জমিয়ে"],
        "কার্বন লোহার চেয়ে সক্রিয়, তাই লোহার অক্সিজেন কেড়ে নেয়।"),
    mcq("What is 'oxidation'?", ["Gaining oxygen (or losing electrons)", "Losing oxygen", "Freezing", "Dissolving"], 0,
        "Rusting and burning are oxidation.",
        "'জারণ' কী?", ["অক্সিজেন গ্রহণ (বা ইলেকট্রন ত্যাগ)", "অক্সিজেন ত্যাগ", "জমা", "গোলা"],
        "মরচে ধরা আর পোড়া জারণ।"),
    mcq("What is 'reduction'?", ["Losing oxygen (or gaining electrons)", "Gaining oxygen", "Getting smaller in size", "Melting"], 0,
        "Getting iron from iron ore is reduction.",
        "'বিজারণ' কী?", ["অক্সিজেন ত্যাগ (বা ইলেকট্রন গ্রহণ)", "অক্সিজেন গ্রহণ", "আকারে ছোট হওয়া", "গলা"],
        "আকরিক থেকে লোহা পাওয়া বিজারণ।"),
    mcq("Balance: H2 + O2 -> H2O. Which is correct?", ["2H2 + O2 -> 2H2O", "H2 + O2 -> H2O", "H2 + 2O2 -> H2O", "2H2 + 2O2 -> H2O"], 0,
        "4 H and 2 O on each side.",
        "সমতা আনো: H2 + O2 -> H2O। কোনটা সঠিক?", ["2H2 + O2 -> 2H2O", "H2 + O2 -> H2O", "H2 + 2O2 -> H2O", "2H2 + 2O2 -> H2O"],
        "দুই দিকে 4টি H আর 2টি O।"),
    mcq("Balance the rusting equation: Fe + O2 -> Fe2O3. Which is correct?", ["4Fe + 3O2 -> 2Fe2O3", "Fe + O2 -> Fe2O3", "2Fe + 3O2 -> Fe2O3", "4Fe + 2O2 -> 2Fe2O3"], 0,
        "4 Fe and 6 O on each side.",
        "মরচের সমীকরণে সমতা আনো: Fe + O2 -> Fe2O3। কোনটা সঠিক?", ["4Fe + 3O2 -> 2Fe2O3", "Fe + O2 -> Fe2O3", "2Fe + 3O2 -> Fe2O3", "4Fe + 2O2 -> 2Fe2O3"],
        "দুই দিকে 4টি Fe আর 6টি O।"),
    mcq("Why must chemical equations be balanced?", ["Atoms are not created or destroyed in reactions", "To look neat", "Because acids require it", "They do not need to be"], 0,
        "Conservation of mass.",
        "রাসায়নিক সমীকরণে সমতা আনতে হয় কেন?", ["বিক্রিয়ায় পরমাণু তৈরি বা ধ্বংস হয় না", "পরিপাটি দেখাতে", "অ্যাসিডের জন্য বাধ্যতামূলক", "আনতে হয় না"],
        "ভরের সংরক্ষণ।"),
    mcq("What is made when an acid reacts with a carbonate?", ["A salt, water and carbon dioxide", "Only hydrogen", "Only water", "A metal"], 0,
        "Acid rain fizzing on limestone releases CO2.",
        "অ্যাসিড কার্বোনেটের সঙ্গে বিক্রিয়া করলে কী তৈরি হয়?", ["লবণ, জল আর কার্বন ডাই-অক্সাইড", "শুধু হাইড্রোজেন", "শুধু জল", "ধাতু"],
        "চুনাপাথরে অ্যাসিড বৃষ্টি বুদবুদ তুলে CO2 ছাড়ে।"),
    mcq("What salt forms when hydrochloric acid reacts with sodium hydroxide?", ["Sodium chloride", "Sodium sulphate", "Calcium chloride", "Copper nitrate"], 0,
        "Hydrochloric acid gives 'chlorides'; sulphuric gives 'sulphates'; nitric gives 'nitrates'.",
        "হাইড্রোক্লোরিক অ্যাসিড সোডিয়াম হাইড্রক্সাইডের সঙ্গে বিক্রিয়া করলে কোন লবণ হয়?", ["সোডিয়াম ক্লোরাইড", "সোডিয়াম সালফেট", "ক্যালসিয়াম ক্লোরাইড", "কপার নাইট্রেট"],
        "হাইড্রোক্লোরিক অ্যাসিড থেকে 'ক্লোরাইড'; সালফিউরিক থেকে 'সালফেট'; নাইট্রিক থেকে 'নাইট্রেট'।"),
    mcq("Which salt forms when sulphuric acid reacts with zinc?", ["Zinc sulphate", "Zinc chloride", "Zinc nitrate", "Zinc carbonate"], 0,
        "Sulphuric acid makes sulphates - and hydrogen gas is given off.",
        "সালফিউরিক অ্যাসিড দস্তার সঙ্গে বিক্রিয়া করলে কোন লবণ হয়?", ["জিঙ্ক সালফেট", "জিঙ্ক ক্লোরাইড", "জিঙ্ক নাইট্রেট", "জিঙ্ক কার্বোনেট"],
        "সালফিউরিক অ্যাসিড সালফেট তৈরি করে - আর হাইড্রোজেন গ্যাস বেরোয়।"),
    mcq("What happens when limestone (calcium carbonate) is strongly heated?", ["It breaks down into quicklime (calcium oxide) and carbon dioxide", "It melts into glass", "It turns into iron", "Nothing"], 0,
        "This 'thermal decomposition' is the first step in making cement and lime.",
        "চুনাপাথর (ক্যালসিয়াম কার্বোনেট) খুব গরম করলে কী হয়?", ["কলিচুন (ক্যালসিয়াম অক্সাইড) আর কার্বন ডাই-অক্সাইডে ভাঙে", "গলে কাচ হয়", "লোহা হয়", "কিছুই না"],
        "এই 'তাপীয় বিয়োজন' সিমেন্ট আর চুন তৈরির প্রথম ধাপ।"),
    mcq("What is slaked lime (calcium hydroxide) made from?", ["Adding water to quicklime", "Burning wood", "Melting sand", "Mixing iron and salt"], 0,
        "The reaction is very hot - it can even boil the water.",
        "কলিচুন-জল (ক্যালসিয়াম হাইড্রক্সাইড) কী থেকে তৈরি?", ["কলিচুনে জল দিয়ে", "কাঠ পুড়িয়ে", "বালি গলিয়ে", "লোহা আর লবণ মিশিয়ে"],
        "বিক্রিয়াটা খুব গরম - জল ফুটিয়েও দিতে পারে।"),
    mcq("Why does lime mortar slowly harden in old bridges?", ["Calcium hydroxide reacts with CO2 in air to form calcium carbonate again", "It freezes", "Water turns into stone", "It never hardens"], 0,
        "The limestone cycle comes full circle.",
        "পুরোনো সেতুতে চুন-মশলা ধীরে শক্ত হয় কেন?", ["ক্যালসিয়াম হাইড্রক্সাইড বাতাসের CO2-র সঙ্গে বিক্রিয়া করে আবার ক্যালসিয়াম কার্বোনেট হয়", "জমে যায়", "জল পাথর হয়", "কখনো শক্ত হয় না"],
        "চুনাপাথর-চক্র পুরো ঘুরে আসে।"),
    mcq("What is 'electrolysis'?", ["Splitting a compound using electricity", "Burning with electricity", "Melting with sunlight", "Mixing metals"], 0,
        "Aluminium is extracted from its ore by electrolysis.",
        "'তড়িৎবিশ্লেষণ' কী?", ["বিদ্যুৎ দিয়ে যৌগ ভাঙা", "বিদ্যুতে পোড়ানো", "রোদে গলানো", "ধাতু মেশানো"],
        "অ্যালুমিনিয়াম আকরিক থেকে তড়িৎবিশ্লেষণে নিষ্কাশিত হয়।"),
    mcq("What is 'electroplating'?", ["Using electricity to coat an object with a thin layer of metal", "Painting with electric paint", "Melting plates", "Cutting metal with electricity"], 0,
        "Chrome-plated taps and zinc-plated bolts are electroplated.",
        "'তড়িৎলেপন' কী?", ["বিদ্যুৎ দিয়ে কোনো বস্তুতে ধাতুর পাতলা স্তর লাগানো", "বৈদ্যুতিক রঙে রং", "থালা গলানো", "বিদ্যুতে ধাতু কাটা"],
        "ক্রোম-প্লেটেড কল আর দস্তা-প্লেটেড বল্টু তড়িৎলেপিত।"),
    mcq("Why is aluminium expensive to extract despite being very common?", ["Electrolysis needs huge amounts of electricity", "It is rare", "It is poisonous", "It melts in air"], 0,
        "Recycling aluminium saves about 95% of that energy.",
        "অ্যালুমিনিয়াম খুব সাধারণ হলেও নিষ্কাশন ব্যয়বহুল কেন?", ["তড়িৎবিশ্লেষণে বিশাল বিদ্যুৎ লাগে", "এটা দুষ্প্রাপ্য", "বিষাক্ত", "বাতাসে গলে"],
        "অ্যালুমিনিয়াম পুনর্ব্যবহারে সেই শক্তির প্রায় 95% বাঁচে।"),
    mcq("What is crude oil?", ["A mixture of many hydrocarbons formed from ancient sea life", "A pure chemical", "Vegetable oil", "Melted rock"], 0,
        "It is separated into useful fractions at a refinery.",
        "অপরিশোধিত তেল কী?", ["প্রাচীন সামুদ্রিক জীব থেকে তৈরি বহু হাইড্রোকার্বনের মিশ্রণ", "একটা বিশুদ্ধ রাসায়নিক", "উদ্ভিজ্জ তেল", "গলিত পাথর"],
        "শোধনাগারে একে দরকারি ভগ্নাংশে আলাদা করা হয়।"),
    mcq("How is crude oil separated into petrol, diesel and bitumen?", ["Fractional distillation by boiling point", "Filtering", "Using magnets", "Freezing"], 0,
        "Bitumen, with the highest boiling point, stays at the bottom - and paves our roads.",
        "অপরিশোধিত তেলকে পেট্রোল, ডিজেল আর বিটুমিনে কীভাবে আলাদা করা হয়?", ["স্ফুটনাঙ্ক অনুযায়ী আংশিক পাতন", "ছেঁকে", "চুম্বক দিয়ে", "জমিয়ে"],
        "সবচেয়ে উঁচু স্ফুটনাঙ্কের বিটুমিন নিচে থাকে - আর আমাদের রাস্তা বানায়।"),
    mcq("What is a 'hydrocarbon'?", ["A compound of hydrogen and carbon only", "Water with carbon", "A type of metal", "Any gas"], 0,
        "Methane (CH4) is the simplest hydrocarbon.",
        "'হাইড্রোকার্বন' কী?", ["শুধু হাইড্রোজেন আর কার্বনের যৌগ", "কার্বনসহ জল", "এক রকম ধাতু", "যেকোনো গ্যাস"],
        "মিথেন (CH4) সবচেয়ে সরল হাইড্রোকার্বন।"),
    mcq("What is 'polymerisation'?", ["Joining many small molecules (monomers) into long chains", "Splitting atoms", "Melting metal", "Dissolving salt"], 0,
        "Ethene monomers join to make poly(ethene) - common plastic.",
        "'পলিমারকরণ' কী?", ["অনেক ছোট অণু (মনোমার) জুড়ে লম্বা শিকল বানানো", "পরমাণু ভাঙা", "ধাতু গলানো", "লবণ গোলা"],
        "ইথিন মনোমার জুড়ে পলি(ইথিন) হয় - সাধারণ প্লাস্টিক।"),
    mcq("Why are HDPE plastic pipes used for drainage under bridges?", ["They resist rust and chemicals and are light", "They are the strongest metal", "They dissolve in rain", "They conduct electricity"], 0,
        "Choosing the right material for each job is good engineering.",
        "সেতুর নিচে জল-নিকাশিতে এইচডিপিই প্লাস্টিকের পাইপ কেন ব্যবহার হয়?", ["মরচে আর রাসায়নিক ঠেকায় আর হালকা", "সবচেয়ে শক্ত ধাতু", "বৃষ্টিতে গলে", "বিদ্যুৎ পরিবহন করে"],
        "প্রতিটি কাজে ঠিক উপাদান বাছাই ভালো প্রকৌশল।"),
    mcq("What is an 'ionic compound'?", ["A compound made of positive and negative ions held together", "A gas made of single atoms", "A pure metal", "A mixture of liquids"], 0,
        "Sodium chloride is ionic: Na+ and Cl- ions.",
        "'আয়নীয় যৌগ' কী?", ["ধনাত্মক আর ঋণাত্মক আয়ন একসঙ্গে বাঁধা যৌগ", "একক পরমাণুর গ্যাস", "বিশুদ্ধ ধাতু", "তরলের মিশ্রণ"],
        "সোডিয়াম ক্লোরাইড আয়নীয়: Na+ আর Cl- আয়ন।"),
    mcq("What is a 'covalent bond'?", ["A shared pair of electrons between non-metal atoms", "A bond between a metal and a magnet", "A legal agreement", "A type of glue"], 0,
        "Water and carbon dioxide have covalent bonds.",
        "'সমযোজী বন্ধন' কী?", ["অধাতু-পরমাণুর মধ্যে ভাগ করা এক জোড়া ইলেকট্রন", "ধাতু আর চুম্বকের বন্ধন", "আইনি চুক্তি", "এক রকম আঠা"],
        "জল আর কার্বন ডাই-অক্সাইডে সমযোজী বন্ধন।"),
    mcq("Why do metals conduct electricity?", ["They have free electrons that can move through the structure", "They are shiny", "They are heavy", "They are cold"], 0,
        "A 'sea' of delocalised electrons carries the current.",
        "ধাতু বিদ্যুৎ পরিবহন করে কেন?", ["তাদের মুক্ত ইলেকট্রন কাঠামোর মধ্য দিয়ে চলতে পারে", "চকচকে", "ভারী", "ঠান্ডা"],
        "মুক্ত ইলেকট্রনের 'সমুদ্র' বিদ্যুৎ বয়।"),
    mcq("Why is diamond so hard while graphite is soft, though both are pure carbon?", ["Their atoms are bonded in different structures", "Diamond is mixed with iron", "Graphite is wet", "They are different elements"], 0,
        "Structure decides properties - as true for bridges as for molecules!",
        "দুটোই বিশুদ্ধ কার্বন হলেও হীরে এত শক্ত আর গ্রাফাইট নরম কেন?", ["তাদের পরমাণু ভিন্ন কাঠামোয় বাঁধা", "হীরেয় লোহা মেশানো", "গ্রাফাইট ভেজা", "এরা আলাদা মৌল"],
        "কাঠামোই ধর্ম ঠিক করে - অণুর মতো সেতুর ক্ষেত্রেও সত্যি!"),
    mcq("What is 'carbon fibre'?", ["Very thin carbon threads, extremely strong and light, used in composites", "Coal dust", "Pencil lead", "A type of cotton"], 0,
        "Carbon-fibre strips are glued on to strengthen old bridges.",
        "'কার্বন ফাইবার' কী?", ["খুব সরু কার্বনের সুতো, অত্যন্ত শক্ত আর হালকা, যৌগিক উপাদানে ব্যবহৃত", "কয়লার গুঁড়ো", "পেনসিলের সিস", "এক রকম তুলো"],
        "পুরোনো সেতু মজবুত করতে কার্বন-ফাইবারের ফালি আঠা দিয়ে লাগানো হয়।"),
    mcq("What does a higher temperature do to the rate of most reactions?", ["Speeds them up - particles move faster and collide more", "Slows them down", "Stops them", "Has no effect"], 0,
        "Concrete sets faster on hot days, so it may need retarders.",
        "উঁচু তাপমাত্রা বেশিরভাগ বিক্রিয়ার হারে কী করে?", ["দ্রুত করে - কণা দ্রুত চলে আর বেশি ধাক্কা খায়", "ধীর করে", "থামায়", "প্রভাব নেই"],
        "গরম দিনে কংক্রিট দ্রুত জমে, তাই মন্দকারী লাগতে পারে।"),
    mcq("What is a 'retarder' in concrete?", ["A chemical that slows setting so there is time to place it", "A chemical that makes it set instantly", "Extra stones", "A colour dye"], 0,
        "Useful for long pours or hot weather.",
        "কংক্রিটে 'মন্দকারী' (রিটার্ডার) কী?", ["যে রাসায়নিক জমা ধীর করে যাতে ঢালার সময় পাওয়া যায়", "যে রাসায়নিক সঙ্গে সঙ্গে জমায়", "বাড়তি পাথর", "রঙের রঞ্জক"],
        "লম্বা ঢালাই বা গরম আবহাওয়ায় কাজের।"),
    mcq("What is an 'accelerator' in concrete?", ["A chemical that speeds up setting, useful in cold weather", "A car pedal", "A type of cement bag", "A slow-down chemical"], 0,
        "It helps concrete gain strength before frost can harm it.",
        "কংক্রিটে 'ত্বরক' (অ্যাক্সিলারেটর) কী?", ["যে রাসায়নিক জমা দ্রুত করে, ঠান্ডা আবহাওয়ায় কাজের", "গাড়ির প্যাডেল", "এক রকম সিমেন্টের বস্তা", "ধীর-করার রাসায়নিক"],
        "তুষারপাতে ক্ষতির আগেই কংক্রিটকে শক্তি পেতে সাহায্য করে।"),
    mcq("What is a 'precipitate'?", ["An insoluble solid formed when two solutions react", "Rain", "A gas bubble", "A dissolved salt"], 0,
        "Mixing some solutions produces a cloudy solid that settles.",
        "'অধঃক্ষেপ' কী?", ["দুটি দ্রবণ বিক্রিয়া করলে তৈরি অদ্রাব্য কঠিন", "বৃষ্টি", "গ্যাসের বুদবুদ", "গোলা লবণ"],
        "কিছু দ্রবণ মেশালে ঘোলাটে কঠিন তৈরি হয়ে থিতিয়ে পড়ে।"),
    mcq("Which gas turns limewater milky?", ["Carbon dioxide", "Oxygen", "Hydrogen", "Nitrogen"], 0,
        "A classic test for CO2.",
        "কোন গ্যাস চুন-জলকে দুধের মতো ঘোলা করে?", ["কার্বন ডাই-অক্সাইড", "অক্সিজেন", "হাইড্রোজেন", "নাইট্রোজেন"],
        "CO2-র একটা পুরোনো পরীক্ষা।"),
    mcq("How do you test for hydrogen gas?", ["A lit splint gives a squeaky pop", "It relights a glowing splint", "It turns limewater milky", "It bleaches litmus"], 0,
        "Hydrogen burns quickly with oxygen.",
        "হাইড্রোজেন গ্যাস কীভাবে পরীক্ষা করো?", ["জ্বলন্ত কাঠি একটা কিচ শব্দে 'পপ' করে", "জ্বলজ্বলে কাঠিকে আবার জ্বালায়", "চুন-জল ঘোলা করে", "লিটমাস বিবর্ণ করে"],
        "হাইড্রোজেন অক্সিজেনের সঙ্গে দ্রুত পোড়ে।"),
    mcq("How do you test for oxygen gas?", ["It relights a glowing splint", "It makes a squeaky pop", "It turns limewater milky", "It smells of rotten eggs"], 0,
        "Oxygen helps things burn.",
        "অক্সিজেন গ্যাস কীভাবে পরীক্ষা করো?", ["জ্বলজ্বলে কাঠিকে আবার জ্বালায়", "কিচ শব্দে পপ করে", "চুন-জল ঘোলা করে", "পচা ডিমের গন্ধ"],
        "অক্সিজেন পুড়তে সাহায্য করে।"),
    mcq("Why is concrete production a big source of CO2?", ["Heating limestone releases CO2, and kilns burn fuel", "Concrete breathes", "Sand gives off CO2", "It is not"], 0,
        "Cement makes about 8% of world CO2 - engineers seek greener mixes.",
        "কংক্রিট উৎপাদন CO2-র একটা বড় উৎস কেন?", ["চুনাপাথর গরম করলে CO2 বেরোয়, আর চুল্লিতে জ্বালানি পোড়ে", "কংক্রিট শ্বাস নেয়", "বালি CO2 ছাড়ে", "নয়"],
        "বিশ্বের CO2-র প্রায় 8% সিমেন্ট থেকে - প্রকৌশলীরা পরিবেশবান্ধব মিশ্রণ খুঁজছেন।"),
    mcq("What is 'carbonation' of concrete?", ["CO2 from air slowly lowers concrete's alkalinity from the surface inward", "Adding fizzy drinks", "Making concrete black", "Painting concrete"], 0,
        "Once it reaches the steel, rusting can start.",
        "কংক্রিটের 'কার্বনেশন' কী?", ["বাতাসের CO2 তল থেকে ভেতরের দিকে কংক্রিটের ক্ষারত্ব ধীরে কমায়", "সোডা পানীয় মেশানো", "কংক্রিট কালো করা", "কংক্রিট রং করা"],
        "রড পর্যন্ত পৌঁছালে মরচে শুরু হতে পারে।"),
    mcq("What does 'concentration' of a solution mean?", ["How much solute is dissolved in a given volume", "How hard you think", "The temperature", "The colour"], 0,
        "Measured in g/dm³ or mol/dm³.",
        "দ্রবণের 'গাঢ়ত্ব' মানে কী?", ["নির্দিষ্ট আয়তনে কতটা দ্রাব গোলা", "কতটা মন দিয়ে ভাবো", "তাপমাত্রা", "রং"],
        "g/dm³ বা mol/dm³-এ মাপা হয়।"),
    mcq("20 g of salt is dissolved to make 2 dm³ of solution. What is the concentration?", ["10 g/dm³", "40 g/dm³", "22 g/dm³", "0.1 g/dm³"], 0,
        "20 ÷ 2 = 10 g/dm³.",
        "20 g লবণ গুলে 2 dm³ দ্রবণ তৈরি হলো। গাঢ়ত্ব কত?", ["10 g/dm³", "40 g/dm³", "22 g/dm³", "0.1 g/dm³"],
        "20 ÷ 2 = 10 g/dm³।"),
    mr("CuO", [("Cu", 1), ("O", 1)], "copper(II) oxide", "কপার(II) অক্সাইড"),
    mr("ZnCl2", [("Zn", 1), ("Cl", 2)], "zinc chloride", "জিঙ্ক ক্লোরাইড"),
    mr("Ca(OH)2", [("Ca", 1), ("O", 2), ("H", 2)], "calcium hydroxide", "ক্যালসিয়াম হাইড্রক্সাইড"),
    mr("C2H6", [("C", 2), ("H", 6)], "ethane", "ইথেন"),
    atoms("CH4", 5, "methane", "মিথেন"), atoms("Al2O3", 5, "aluminium oxide", "অ্যালুমিনিয়াম অক্সাইড"), atoms("C2H5OH", 9, "ethanol", "ইথানল"),
    displace("aluminium", "অ্যালুমিনিয়াম", "iron oxide (in the thermite reaction)", "আয়রন অক্সাইডের (থার্মিট বিক্রিয়ায়)", True),
    displace("gold", "সোনা", "zinc chloride", "জিঙ্ক ক্লোরাইড", False),
    mcq("Why is the thermite reaction used to weld railway tracks?", ["Aluminium displaces iron from its oxide, releasing molten iron that joins the rails", "It freezes the rails together", "It uses glue", "It is never used"], 0,
        "The reaction is so hot the iron produced is liquid.",
        "রেললাইন ঝালাই করতে থার্মিট বিক্রিয়া ব্যবহার হয় কেন?", ["অ্যালুমিনিয়াম অক্সাইড থেকে লোহা সরিয়ে গলিত লোহা ছাড়ে, যা রেল জোড়ে", "রেল জমিয়ে জোড়ে", "আঠা ব্যবহার করে", "কখনো ব্যবহার হয় না"],
        "বিক্রিয়া এত গরম যে উৎপন্ন লোহা তরল।"),
    mcq("What is an 'alloy' of iron with a little carbon, chromium and nickel?", ["Stainless steel", "Brass", "Bronze", "Solder"], 0,
        "Chromium and nickel make it resist corrosion.",
        "লোহার সঙ্গে সামান্য কার্বন, ক্রোমিয়াম আর নিকেলের সংকর কী?", ["মরচে-রোধী ইস্পাত", "পিতল", "ব্রোঞ্জ", "ঝালাই-ধাতু"],
        "ক্রোমিয়াম আর নিকেল ক্ষয় ঠেকায়।"),
    mcq("Why are alloys usually harder than pure metals?", ["Different-sized atoms stop the layers sliding easily", "Alloys are always colder", "Alloys have no atoms", "They are not"], 0,
        "Pure iron is soft; steel is much stronger.",
        "সংকর ধাতু সাধারণত বিশুদ্ধ ধাতুর চেয়ে শক্ত কেন?", ["ভিন্ন মাপের পরমাণু স্তরগুলোকে সহজে পিছলাতে দেয় না", "সংকর সবসময় ঠান্ডা", "সংকরে পরমাণু নেই", "শক্ত নয়"],
        "বিশুদ্ধ লোহা নরম; ইস্পাত অনেক শক্ত।"),
    mcq("What is 'bronze'?", ["An alloy of copper and tin", "Pure copper", "Iron and carbon", "Zinc and lead"], 0,
        "Bronze was so important it named an age of history.",
        "'ব্রোঞ্জ' কী?", ["তামা আর টিনের সংকর", "বিশুদ্ধ তামা", "লোহা আর কার্বন", "দস্তা আর সিসা"],
        "ব্রোঞ্জ এত জরুরি ছিল যে ইতিহাসের একটা যুগের নাম হয়েছে।"),
    mcq("Why do old bronze bridge bearings and statues last for centuries?", ["Bronze resists corrosion well", "Bronze is magnetic", "Bronze is very light", "They are repainted daily"], 0,
        "It forms a protective patina.",
        "পুরোনো ব্রোঞ্জের সেতু-বিয়ারিং আর মূর্তি শতাব্দী ধরে টেকে কেন?", ["ব্রোঞ্জ ভালো ক্ষয় ঠেকায়", "ব্রোঞ্জ চুম্বকীয়", "ব্রোঞ্জ খুব হালকা", "রোজ রং করা হয়"],
        "এটা রক্ষাকারী আস্তরণ তৈরি করে।"),
    mcq("What is a 'mole' in chemistry?", ["A fixed number of particles (about 6 x 10^23), used for counting atoms", "A small animal only", "A spy", "A unit of length"], 0,
        "Chemists count atoms in moles, like builders count bricks in thousands.",
        "রসায়নে 'মোল' কী?", ["কণার একটা নির্দিষ্ট সংখ্যা (প্রায় 6 x 10^23), পরমাণু গোনার জন্য", "শুধু ছোট্ট প্রাণী", "গুপ্তচর", "দৈর্ঘ্যের একক"],
        "নির্মাতারা হাজারে ইট গোনেন, রসায়নবিদরা মোলে পরমাণু গোনেন।"),
    mcq("What is the mass of 1 mole of water (Mr = 18)?", ["18 g", "1 g", "6 g", "180 g"], 0,
        "The mass of one mole in grams equals the Mr.",
        "1 মোল জলের (Mr = 18) ভর কত?", ["18 g", "1 g", "6 g", "180 g"],
        "এক মোলের গ্রামে ভর Mr-এর সমান।"),
    mcq("What is 'pH 7'?", ["Neutral", "Strongly acidic", "Strongly alkaline", "Impossible"], 0,
        "Pure water at room temperature has pH 7.",
        "'pH 7' কী?", ["নিরপেক্ষ", "তীব্র অম্লীয়", "তীব্র ক্ষারীয়", "অসম্ভব"],
        "ঘরের তাপমাত্রায় বিশুদ্ধ জলের pH 7।"),
    mcq("Why do engineers test soil and groundwater chemistry before building foundations?", ["Acids or sulphates in the ground can attack concrete", "To find gold", "To grow crops", "It is not needed"], 0,
        "Special sulphate-resisting cement may be needed.",
        "ভিত বানানোর আগে প্রকৌশলীরা মাটি আর ভূগর্ভস্থ জলের রসায়ন পরীক্ষা করেন কেন?", ["মাটির অ্যাসিড বা সালফেট কংক্রিট আক্রমণ করতে পারে", "সোনা খুঁজতে", "ফসল ফলাতে", "দরকার নেই"],
        "বিশেষ সালফেট-রোধী সিমেন্ট লাগতে পারে।"),
    mcq("Which gas makes up about 21% of the air and is needed for rusting and burning?", ["Oxygen", "Nitrogen", "Argon", "Carbon dioxide"], 0,
        "Remove oxygen and both rusting and burning stop.",
        "কোন গ্যাস বাতাসের প্রায় 21% আর মরচে ধরা ও পোড়ার জন্য লাগে?", ["অক্সিজেন", "নাইট্রোজেন", "আর্গন", "কার্বন ডাই-অক্সাইড"],
        "অক্সিজেন সরালে মরচে আর পোড়া দুটোই থামে।"),
)
