"""Class 7 - Commercials (Junior Cadet): markup versus margin, re-order points and safety stock,
stock turnover, market share, truck load factors and trip counts, early-payment discounts,
customer lifetime value, Incoterms, critical path planning, the 80/20 rule and fair dealing."""
from . import mcq


def _o(r, *alts):
    out = []
    for x in (r, *alts, r + 1, r + 2, r * 2, r + 10):
        if x not in out and x > 0:
            out.append(x)
    return out[:4]


def _n(q_en, q_bn, r, ex_en, ex_bn, alts, u_en="", u_bn="", pre_en=""):
    f = lambda x: f"{x:,}" if isinstance(x, int) else f"{x:g}"
    o = _o(r, *alts)
    return mcq(q_en, [pre_en + f(x) + u_en for x in o], 0, ex_en, q_bn, [f(x) + u_bn for x in o], ex_bn)


def _c(x):
    x = round(x, 1)
    return int(x) if x == int(x) else x


def margin(cost, price, item_en, item_bn):
    m = _c((price - cost) * 100 / price)
    mk = _c((price - cost) * 100 / cost)
    return _n(f"A dealer buys {item_en} for Rs {cost:,} and sells it for Rs {price:,}. What is the profit margin (profit as a % of the selling price)?",
              f"একজন বিক্রেতা {item_bn} {cost:,} টাকায় কিনে {price:,} টাকায় বেচেন। লাভের মার্জিন (বিক্রয়মূল্যের শতাংশে লাভ) কত?", m,
              f"Profit {price - cost:,} ÷ price {price:,} x 100 = {m:g}%. (Markup on cost would be {mk:g}% - a different measure!)",
              f"লাভ {price - cost:,} ÷ দাম {price:,} x 100 = {m:g}%। (খরচের উপর মার্কআপ হতো {mk:g}% - আলাদা মাপ!)",
              (mk, _c((price - cost) * 100 / (price + cost)), _c(m + 5)), "%", "%")


def markup(cost, pct, item_en, item_bn):
    r = cost + cost * pct // 100
    return _n(f"A supplier adds a {pct}% markup to {item_en} that cost Rs {cost:,}. What is the selling price?",
              f"একজন সরবরাহকারী {cost:,} টাকা খরচের {item_bn}-এ {pct}% মার্কআপ যোগ করেন। বিক্রয়মূল্য কত?", r,
              f"Markup = {cost:,} x {pct}% = {cost * pct // 100:,}; price = {cost:,} + {cost * pct // 100:,} = Rs {r:,}.",
              f"মার্কআপ = {cost:,} x {pct}% = {cost * pct // 100:,}; দাম = {cost:,} + {cost * pct // 100:,} = {r:,} টাকা।",
              (cost * pct // 100, cost - cost * pct // 100, r + cost // 10), "", " টাকা", "Rs ")


def rop(daily, lead, safety, item_en, item_bn):
    r = daily * lead + safety
    return _n(f"A site uses {daily} {item_en} a day. Delivery takes {lead} days and the manager keeps {safety} as safety stock. At what stock level should a new order be placed?",
              f"একটা নির্মাণস্থলে দিনে {daily}টি {item_bn} লাগে। মাল আসতে {lead} দিন লাগে আর ম্যানেজার {safety}টি নিরাপত্তা-মজুত রাখেন। মজুত কত হলে নতুন অর্ডার দিতে হবে?", r,
              f"Re-order point = daily use x lead time + safety stock = {daily} x {lead} + {safety} = {r:,}.",
              f"পুনঃঅর্ডার-বিন্দু = দৈনিক ব্যবহার x সরবরাহ-সময় + নিরাপত্তা-মজুত = {daily} x {lead} + {safety} = {r:,}।",
              (daily * lead, r + safety, daily + lead + safety))


def turnover(cogs, stock):
    r = _c(cogs / stock)
    return _n(f"A hardware store sold goods costing Rs {cogs:,} in a year and held average stock worth Rs {stock:,}. How many times did its stock turn over?",
              f"একটা হার্ডওয়্যার-দোকান বছরে {cogs:,} টাকা খরচের মাল বেচল, গড় মজুত ছিল {stock:,} টাকার। মজুত কতবার ঘুরল?", r,
              f"Stock turnover = cost of goods sold ÷ average stock = {cogs:,} ÷ {stock:,} = {r:g} times. Higher means goods sit on shelves for less time.",
              f"মজুত-ঘূর্ণন = বিক্রীত মালের খরচ ÷ গড় মজুত = {cogs:,} ÷ {stock:,} = {r:g} বার। বেশি মানে মাল তাকে কম সময় পড়ে থাকে।",
              (_c(stock / cogs * 10), _c(r * 2), _c(r + 3)), " times", " বার")


def share(firm, market, firm_en, firm_bn):
    r = _c(firm * 100 / market)
    return _n(f"{firm_en} sold Rs {firm:,} lakh of goods in a market worth Rs {market:,} lakh. What is its market share?",
              f"{firm_bn} {market:,} লাখ টাকার বাজারে {firm:,} লাখ টাকার মাল বেচল। এর বাজার-অংশ কত?", r,
              f"Market share = {firm:,} ÷ {market:,} x 100 = {r:g}%.",
              f"বাজার-অংশ = {firm:,} ÷ {market:,} x 100 = {r:g}%।",
              (_c(market / firm), _c(r / 2), _c(r + 10)), "%", "%")


def loadf(cap, load):
    r = _c(load * 100 / cap)
    return _n(f"A {cap}-tonne truck leaves the depot carrying {load} tonnes of steel. What is its load factor?",
              f"একটা {cap} টনের ট্রাক {load} টন ইস্পাত নিয়ে ডিপো ছাড়ল। এর বোঝাই-অনুপাত কত?", r,
              f"Load factor = load ÷ capacity x 100 = {load} ÷ {cap} x 100 = {r:g}%. Empty space still burns diesel!",
              f"বোঝাই-অনুপাত = বোঝা ÷ ক্ষমতা x 100 = {load} ÷ {cap} x 100 = {r:g}%। খালি জায়গাও ডিজেল পোড়ায়!",
              (_c(100 - r), _c(cap * 100 / load), _c(r + 15)), "%", "%")


def trips(tonnes, cap, cost):
    n = -(-tonnes // cap)
    return _n(f"{tonnes} tonnes of girders must be moved in {cap}-tonne trucks at Rs {cost:,} per trip. What is the transport cost?",
              f"{tonnes} টন গার্ডার {cap} টনের ট্রাকে সরাতে হবে, প্রতি যাত্রায় {cost:,} টাকা। পরিবহন-খরচ কত?", n * cost,
              f"Trips = {tonnes} ÷ {cap} = {tonnes / cap:.2f}, rounded UP to {n}; {n} x {cost:,} = Rs {n * cost:,}.",
              f"যাত্রা = {tonnes} ÷ {cap} = {tonnes / cap:.2f}, উপরে আসন্ন করে {n}; {n} x {cost:,} = {n * cost:,} টাকা।",
              ((tonnes // cap) * cost, tonnes * cost // cap, (n + 1) * cost), "", " টাকা", "Rs ")


def cashdisc(bill, pct):
    r = bill - bill * pct // 100
    return _n(f"An invoice for Rs {bill:,} offers '{pct}/10, net 30': {pct}% off if paid within 10 days, otherwise the full amount in 30 days. How much is paid on day 7?",
              f"{bill:,} টাকার একটা চালানে লেখা '{pct}/10, নিট 30': 10 দিনের মধ্যে দিলে {pct}% ছাড়, নইলে 30 দিনে পুরো টাকা। সপ্তম দিনে কত দিতে হবে?", r,
              f"Paid within 10 days, so {bill:,} - {pct}% ({bill * pct // 100:,}) = Rs {r:,}.",
              f"10 দিনের মধ্যে দেওয়া, তাই {bill:,} - {pct}% ({bill * pct // 100:,}) = {r:,} টাকা।",
              (bill, bill * pct // 100, bill - bill * pct // 10), "", " টাকা", "Rs ")


def clv(spend, per_year, years):
    r = spend * per_year * years
    return _n(f"A contractor spends Rs {spend:,} per order, orders {per_year} times a year and stays a customer for {years} years. What is this customer worth in sales over that time?",
              f"একজন ঠিকাদার প্রতি অর্ডারে {spend:,} টাকা খরচ করেন, বছরে {per_year} বার অর্ডার দেন আর {years} বছর খদ্দের থাকেন। এই সময়ে এই খদ্দেরের বিক্রি-মূল্য কত?", r,
              f"Lifetime value = {spend:,} x {per_year} x {years} = Rs {r:,}. Keeping a customer happy is worth far more than one sale.",
              f"জীবনকালীন মূল্য = {spend:,} x {per_year} x {years} = {r:,} টাকা। একটা বিক্রির চেয়ে খদ্দেরকে খুশি রাখার দাম অনেক বেশি।",
              (spend * per_year, spend * years, spend + per_year + years), "", " টাকা", "Rs ")


def critical(a, b, c, d):
    p1, p2 = a + b, c + d
    r = max(p1, p2)
    return _n(f"A bridge job has two parallel paths before the deck can be poured: foundations ({a} days) then piers ({b} days), and casting girders ({c} days) then curing ({d} days). What is the shortest time before the deck pour?",
              f"পাটাতন ঢালার আগে একটা সেতু-কাজে দুটো সমান্তরাল পথ: ভিত ({a} দিন) তারপর স্তম্ভ ({b} দিন), আর গার্ডার ঢালাই ({c} দিন) তারপর জমাট ({d} দিন)। পাটাতন ঢালার আগে সবচেয়ে কম কত সময়?", r,
              f"Path 1 = {a} + {b} = {p1}; path 2 = {c} + {d} = {p2}. The longer path ({r} days) is the critical path - it sets the date.",
              f"পথ ১ = {a} + {b} = {p1}; পথ ২ = {c} + {d} = {p2}। লম্বা পথটাই ({r} দিন) সংকট-পথ - এটাই তারিখ ঠিক করে।",
              (min(p1, p2), p1 + p2, r + 5), " days", " দিন")


ITEMS = (
    margin(80, 100, "a safety helmet", "একটা নিরাপত্তা-হেলমেট"), margin(600, 800, "a bag of bolts", "এক ব্যাগ বল্টু"),
    margin(300, 500, "a spirit level", "একটা স্পিরিট-লেভেল"),
    markup(400, 25, "a box of rivets", "এক বাক্স রিভেট"), markup(1200, 30, "a steel plate", "একটা ইস্পাতের পাত"),
    markup(2500, 20, "a hand winch", "একটা হাত-উইঞ্চ"),
    rop(40, 5, 60, "cement bags", "সিমেন্টের বস্তা"), rop(12, 7, 20, "steel rods", "ইস্পাতের রড"),
    rop(150, 3, 100, "bricks", "ইট"),
    turnover(1200000, 200000), turnover(900000, 300000), turnover(500000, 125000),
    share(150, 600, "A cement brand", "একটা সিমেন্ট-ব্র্যান্ড"),
    share(45, 300, "A paint maker", "একটা রং-নির্মাতা"),
    loadf(20, 15), loadf(10, 6), loadf(25, 20),
    trips(95, 20, 3000), trips(130, 25, 4500), trips(210, 40, 6000),
    cashdisc(50000, 2), cashdisc(120000, 3), cashdisc(200000, 2),
    clv(5000, 6, 4), clv(12000, 4, 5), clv(2500, 12, 3),
    critical(20, 15, 25, 14), critical(12, 18, 10, 28), critical(30, 10, 18, 20),
    mcq("What is the difference between markup and margin?", ["Markup compares profit with cost; margin compares profit with the selling price", "They are always the same number", "Markup is a tax; margin is a fee", "Margin is only used for exports"], 0,
        "Buy at 80, sell at 100: markup 25%, margin 20%. Mixing them up can wreck a price list.",
        "মার্কআপ আর মার্জিনের পার্থক্য কী?", ["মার্কআপ লাভকে খরচের সঙ্গে তুলনা করে; মার্জিন বিক্রয়মূল্যের সঙ্গে", "সবসময় একই সংখ্যা", "মার্কআপ কর; মার্জিন ফি", "মার্জিন শুধু রপ্তানিতে"],
        "80-তে কিনে 100-তে বেচলে: মার্কআপ 25%, মার্জিন 20%। গুলিয়ে ফেললে দামের তালিকা বিগড়ে যায়।"),
    mcq("Why does a site keep 'safety stock'?", ["To keep working if a delivery is late or use suddenly rises", "To fill empty shelves for photos", "Because suppliers insist", "To make the store look busy"], 0,
        "Running out of cement can stop a whole crew for a day.",
        "নির্মাণস্থলে 'নিরাপত্তা-মজুত' রাখা হয় কেন?", ["ডেলিভারি দেরি হলে বা ব্যবহার হঠাৎ বাড়লেও কাজ চালাতে", "ছবির জন্য খালি তাক ভরাতে", "সরবরাহকারী জোর করে বলে", "দোকান ব্যস্ত দেখাতে"],
        "সিমেন্ট ফুরোলে একটা পুরো দল এক দিন বসে থাকতে পারে।"),
    mcq("A cement supplier's lead time grows from 5 days to 9 days. What should the site do with its re-order point?", ["Raise it, so orders go out earlier", "Lower it", "Leave it unchanged", "Stop ordering cement"], 0,
        "More days of waiting means more bags used before the delivery arrives.",
        "একজন সিমেন্ট-সরবরাহকারীর সরবরাহ-সময় 5 দিন থেকে বেড়ে 9 দিন হলো। নির্মাণস্থলের পুনঃঅর্ডার-বিন্দু নিয়ে কী করা উচিত?", ["বাড়ানো, যাতে অর্ডার আগে যায়", "কমানো", "যেমন আছে রাখা", "সিমেন্ট অর্ডার বন্ধ করা"],
        "অপেক্ষার দিন বাড়লে ডেলিভারি আসার আগে আরও বেশি বস্তা খরচ হয়।"),
    mcq("What is the risk of holding too much stock?", ["Cash is tied up, storage costs rise and goods may rust, spoil or go out of date", "There is no risk at all", "Customers will stop buying", "Taxes become zero"], 0,
        "Cement that sits too long absorbs moisture and goes hard in the bag.",
        "বেশি মজুত রাখার ঝুঁকি কী?", ["নগদ আটকে যায়, গুদাম-খরচ বাড়ে আর মালে মরচে ধরতে, নষ্ট বা পুরোনো হতে পারে", "কোনো ঝুঁকি নেই", "খদ্দের কেনা বন্ধ করবেন", "কর শূন্য হয়ে যায়"],
        "বেশিদিন পড়ে থাকা সিমেন্ট আর্দ্রতা টেনে বস্তাতেই শক্ত হয়ে যায়।"),
    mcq("What does 'just-in-time' (JIT) delivery mean?", ["Materials arrive exactly when needed, so little stock is stored", "Deliveries always arrive late", "Everything is bought a year early", "Trucks drive as fast as possible"], 0,
        "It saves space on a cramped city site but needs very reliable suppliers.",
        "'ঠিক-সময়ে' (জেআইটি) ডেলিভারি মানে কী?", ["মাল ঠিক যখন দরকার তখনই আসে, তাই কম মজুত রাখতে হয়", "ডেলিভারি সবসময় দেরিতে আসে", "সব এক বছর আগে কেনা", "ট্রাক যত জোরে পারে চলে"],
        "ঘিঞ্জি শহুরে নির্মাণস্থলে জায়গা বাঁচায়, কিন্তু খুব ভরসাযোগ্য সরবরাহকারী লাগে।"),
    mcq("What is a 'stock-out'?", ["Running out of an item that customers or workers need", "Selling shares", "A stock-taking party", "A broken shelf"], 0,
        "Stock-outs lose sales and delay projects.",
        "'মজুত-শূন্যতা' কী?", ["খদ্দের বা কর্মীদের দরকারি জিনিস ফুরিয়ে যাওয়া", "শেয়ার বেচা", "মজুত গোনার উৎসব", "ভাঙা তাক"],
        "মজুত-শূন্যতায় বিক্রি হারায় আর প্রকল্প পিছোয়।"),
    mcq("What does 'FIFO' mean in a warehouse?", ["First in, first out - use the oldest stock first", "Fast in, fast out", "Fill it, forget it", "Fragile items on top only"], 0,
        "Older cement bags are used before newer ones so nothing expires.",
        "গুদামে 'এফআইএফও' মানে কী?", ["আগে এলে আগে যাবে - সবচেয়ে পুরোনো মজুত আগে ব্যবহার", "দ্রুত ঢোকে, দ্রুত বেরোয়", "ভরাও আর ভুলে যাও", "ভঙ্গুর জিনিস শুধু উপরে"],
        "পুরোনো সিমেন্টের বস্তা আগে ব্যবহার হয়, যাতে কিছু মেয়াদ না পেরোয়।"),
    mcq("The whole steel-pipe market grows 10% this year but one firm's sales grow only 5%. What happens to its market share?", ["It falls", "It rises", "It stays the same", "It doubles"], 0,
        "Its sales grew more slowly than the market, so its slice of the pie got smaller.",
        "এ বছর গোটা ইস্পাত-পাইপের বাজার 10% বাড়ল, কিন্তু একটা সংস্থার বিক্রি বাড়ল মাত্র 5%। তার বাজার-অংশের কী হয়?", ["কমে", "বাড়ে", "একই থাকে", "দ্বিগুণ হয়"],
        "বিক্রি বাজারের চেয়ে ধীরে বেড়েছে, তাই তার ভাগের টুকরো ছোট হয়েছে।"),
    mcq("Why does a haulage firm care about load factor?", ["Fuel, driver and toll costs are almost the same whether a truck is full or half-empty", "Full trucks need no driver", "Empty trucks are illegal", "Load factor sets the truck's colour"], 0,
        "Combining part-loads from several customers fills trucks and cuts cost per tonne.",
        "পরিবহন-সংস্থা বোঝাই-অনুপাত নিয়ে ভাবে কেন?", ["ট্রাক ভরা হোক বা আধখালি, জ্বালানি, চালক আর টোলের খরচ প্রায় একই", "ভরা ট্রাকে চালক লাগে না", "খালি ট্রাক বেআইনি", "বোঝাই-অনুপাত ট্রাকের রং ঠিক করে"],
        "কয়েকজন খদ্দেরের আংশিক মাল এক করে ট্রাক ভরালে টনপ্রতি খরচ কমে।"),
    mcq("What is a 'backhaul' in logistics?", ["Carrying a paying load on the return trip instead of driving back empty", "Hauling a truck backwards", "A heavy backpack", "Returning faulty goods only"], 0,
        "A truck that brings steel to the site can carry scrap back to the mill.",
        "পরিবহনে 'ফিরতি বোঝাই' কী?", ["খালি না ফিরে ফেরার পথেও টাকা-দেওয়া মাল বয়ে আনা", "ট্রাককে পিছন দিকে টানা", "ভারী পিঠের ব্যাগ", "শুধু ত্রুটিপূর্ণ মাল ফেরত"],
        "যে ট্রাক নির্মাণস্থলে ইস্পাত আনে, সে কারখানায় ফেরত লোহার টুকরো নিতে পারে।"),
    mcq("What does '2/10, net 30' on an invoice mean?", ["2% discount if paid within 10 days; otherwise the full amount is due in 30 days", "Pay 2 rupees every 10 days", "Pay within 2 days or 30% fine", "Only 10 items can be bought"], 0,
        "Suppliers offer it to get their cash sooner.",
        "চালানে '2/10, নিট 30' মানে কী?", ["10 দিনের মধ্যে দিলে 2% ছাড়; নইলে 30 দিনে পুরো টাকা", "প্রতি 10 দিনে 2 টাকা দাও", "2 দিনে দাও নইলে 30% জরিমানা", "শুধু 10টা জিনিস কেনা যাবে"],
        "সরবরাহকারীরা তাড়াতাড়ি নগদ পেতে এটা দেন।"),
    mcq("What are 'credit terms' between a supplier and a builder?", ["The agreed time and conditions for paying an invoice after delivery", "The builder's school grades", "A loan from a bank only", "The supplier's opening hours"], 0,
        "30 or 60 days' credit helps a builder pay after the client pays them.",
        "সরবরাহকারী আর নির্মাতার মধ্যে 'ধারের শর্ত' কী?", ["ডেলিভারির পরে চালান মেটানোর ঠিক করা সময় আর শর্ত", "নির্মাতার স্কুলের নম্বর", "শুধু ব্যাংকের ঋণ", "সরবরাহকারীর খোলার সময়"],
        "30 বা 60 দিনের ধার নির্মাতাকে গ্রাহকের টাকা পাওয়ার পরে দিতে সাহায্য করে।"),
    mcq("Why might a supplier give a loyal contractor free delivery, even though each trip costs it Rs 500?", ["The contractor's future orders are worth far more than the delivery cost", "Delivery is always free by law", "Trucks cost nothing to run", "To lose money on purpose"], 0,
        "Thinking about a customer's lifetime value changes what 'expensive' means.",
        "প্রতি যাত্রায় 500 টাকা খরচ হলেও একজন সরবরাহকারী অনুগত ঠিকাদারকে বিনামূল্যে ডেলিভারি দিতে পারেন কেন?", ["ঠিকাদারের ভবিষ্যৎ অর্ডারের মূল্য ডেলিভারির খরচের চেয়ে অনেক বেশি", "আইনে ডেলিভারি সবসময় বিনামূল্যে", "ট্রাক চালাতে খরচ নেই", "ইচ্ছে করে টাকা হারাতে"],
        "খদ্দেরের জীবনকালীন মূল্যের কথা ভাবলে 'দামি' কথাটার মানে বদলে যায়।"),
    mcq("Why is keeping an existing customer usually cheaper than finding a new one?", ["New customers need advertising, visits and trust-building; loyal ones already trust you", "Old customers pay double", "New customers are not allowed", "It is never cheaper"], 0,
        "Repeat orders from happy clients are the backbone of most builders.",
        "নতুন খদ্দের খোঁজার চেয়ে পুরোনো খদ্দের ধরে রাখা সাধারণত সস্তা কেন?", ["নতুনদের জন্য বিজ্ঞাপন, দেখা-সাক্ষাৎ আর আস্থা গড়া লাগে; অনুগতরা আগেই ভরসা করেন", "পুরোনো খদ্দের দ্বিগুণ দেন", "নতুন খদ্দের নিষিদ্ধ", "কখনো সস্তা নয়"],
        "খুশি গ্রাহকের বারবার অর্ডারই বেশিরভাগ নির্মাতার মেরুদণ্ড।"),
    mcq("What is the 'critical path' in a project plan?", ["The longest chain of dependent tasks; any delay on it delays the whole project", "The shortest road to the site", "A path for emergency vehicles", "The most dangerous task"], 0,
        "Managers watch critical-path tasks most closely.",
        "প্রকল্প-পরিকল্পনায় 'সংকট-পথ' কী?", ["পরস্পর-নির্ভর কাজের সবচেয়ে লম্বা শৃঙ্খল; এতে দেরি হলে পুরো প্রকল্প পিছোয়", "নির্মাণস্থলের সবচেয়ে ছোট রাস্তা", "জরুরি গাড়ির পথ", "সবচেয়ে বিপজ্জনক কাজ"],
        "ম্যানেজাররা সংকট-পথের কাজ সবচেয়ে কাছ থেকে নজর রাখেন।"),
    mcq("A task NOT on the critical path is delayed by 2 days but has 5 days of 'float'. What happens to the finish date?", ["Nothing - the float absorbs the delay", "It moves 2 days later", "It moves 5 days later", "The project is cancelled"], 0,
        "Float (slack) is spare time a task can use without delaying the project.",
        "সংকট-পথের বাইরের একটা কাজ 2 দিন পিছোল, কিন্তু তার 5 দিনের 'ফাঁকা সময়' আছে। শেষের তারিখের কী হয়?", ["কিছু না - ফাঁকা সময় দেরিটা শুষে নেয়", "2 দিন পিছোয়", "5 দিন পিছোয়", "প্রকল্প বাতিল"],
        "ফাঁকা সময় হলো প্রকল্প না পিছিয়ে কাজটা যে বাড়তি সময় নিতে পারে।"),
    mcq("What does a Gantt chart show?", ["Tasks as bars along a timeline, showing when each starts and ends", "Profit for each month", "The bridge's load", "A map of delivery routes"], 0,
        "It lets everyone see at a glance what should be happening this week.",
        "গ্যান্ট-চার্ট কী দেখায়?", ["সময়রেখা বরাবর বার হিসেবে কাজগুলো, কোনটা কবে শুরু আর শেষ", "প্রতি মাসের লাভ", "সেতুর বোঝা", "ডেলিভারি-পথের মানচিত্র"],
        "এই সপ্তাহে কী হওয়ার কথা, সবাই এক নজরে দেখতে পায়।"),
    mcq("What does the '80/20 rule' (Pareto principle) often say about a supplier's business?", ["About 80% of sales come from about 20% of customers", "80% of staff work 20% of the time", "Prices rise 80% every 20 years", "Only 20 products can be sold"], 0,
        "It helps firms focus care on their most important customers and products.",
        "'80/20 নিয়ম' (প্যারেটো নীতি) একজন সরবরাহকারীর ব্যবসা নিয়ে প্রায়ই কী বলে?", ["প্রায় 80% বিক্রি আসে প্রায় 20% খদ্দের থেকে", "80% কর্মী 20% সময় কাজ করেন", "প্রতি 20 বছরে দাম 80% বাড়ে", "শুধু 20টা পণ্য বেচা যায়"],
        "সবচেয়ে জরুরি খদ্দের আর পণ্যে মনোযোগ দিতে সাহায্য করে।"),
    mcq("A depot found that 20% of its spare parts cause 80% of its stock value. How should it treat those parts?", ["Count and control them most carefully (they are the 'A' items)", "Ignore them", "Throw them away", "Store them outside in the rain"], 0,
        "ABC analysis: watch A items closely, C items more loosely.",
        "একটা ডিপো দেখল 20% খুচরো যন্ত্রাংশেই মজুতের 80% মূল্য। ওই যন্ত্রাংশগুলোর সঙ্গে কী করা উচিত?", ["সবচেয়ে যত্নে গোনা আর নিয়ন্ত্রণ করা (এগুলো 'A' শ্রেণি)", "উপেক্ষা করা", "ফেলে দেওয়া", "বাইরে বৃষ্টিতে রাখা"],
        "এবিসি বিশ্লেষণ: A শ্রেণি কড়া নজরে, C শ্রেণি একটু ঢিলে।"),
    mcq("What does the Incoterm 'FOB' (free on board) mean for a shipment of steel?", ["The seller pays until the goods are loaded on the ship; the buyer pays after that", "Shipping is free for everyone", "The ship is free to leave without cargo", "The buyer pays nothing at all"], 0,
        "Incoterms make clear who pays and who carries the risk at each step.",
        "ইস্পাতের চালানে ইনকোটার্ম 'এফওবি' (জাহাজে বিনামূল্যে) মানে কী?", ["মাল জাহাজে তোলা পর্যন্ত বিক্রেতা খরচ দেন; তারপর ক্রেতা", "সবার জন্য পরিবহন বিনামূল্যে", "জাহাজ মাল ছাড়াই ছাড়তে পারে", "ক্রেতা কিছুই দেন না"],
        "প্রতি ধাপে কে খরচ দেবেন আর ঝুঁকি কার, ইনকোটার্ম তা স্পষ্ট করে।"),
    mcq("Under 'CIF' (cost, insurance and freight), who pays for sea freight and insurance to the destination port?", ["The seller", "The buyer", "The port", "The government"], 0,
        "So CIF prices are higher than FOB prices for the same goods.",
        "'সিআইএফ' (খরচ, বিমা আর ভাড়া) শর্তে গন্তব্য-বন্দর পর্যন্ত সমুদ্র-ভাড়া আর বিমা কে দেন?", ["বিক্রেতা", "ক্রেতা", "বন্দর", "সরকার"],
        "তাই একই মালের সিআইএফ দাম এফওবি দামের চেয়ে বেশি।"),
    mcq("What is 'customs duty'?", ["A tax charged on goods brought into a country", "A tip for port workers", "A shipping company's fee", "A road toll"], 0,
        "It is added to the landed cost of imported steel or machines.",
        "'শুল্ক' কী?", ["দেশে আনা মালের উপর বসানো কর", "বন্দর-কর্মীদের বকশিশ", "জাহাজ-সংস্থার ফি", "রাস্তার টোল"],
        "আমদানি করা ইস্পাত বা যন্ত্রের মোট খরচে যোগ হয়।"),
    mcq("What is 'landed cost'?", ["The full cost of an imported item once it reaches you: price + freight + insurance + duty", "The price on the supplier's website", "The cost of land for a warehouse", "The cost of a plane ticket"], 0,
        "Comparing only factory prices can make imports look cheaper than they are.",
        "'পৌঁছানো খরচ' কী?", ["আমদানি করা মাল হাতে পৌঁছানো পর্যন্ত পুরো খরচ: দাম + ভাড়া + বিমা + শুল্ক", "সরবরাহকারীর ওয়েবসাইটের দাম", "গুদামের জমির দাম", "বিমানের টিকিটের দাম"],
        "শুধু কারখানার দাম তুলনা করলে আমদানি আসলের চেয়ে সস্তা মনে হয়।"),
    mcq("Steel costs Rs 50,000 a tonne abroad; freight and insurance add Rs 6,000 and duty adds Rs 4,000. What is the landed cost per tonne?", ["Rs 60,000", "Rs 56,000", "Rs 54,000", "Rs 50,000"], 0,
        "50,000 + 6,000 + 4,000 = Rs 60,000 - compare this with the local price.",
        "বিদেশে ইস্পাতের দাম টনপ্রতি 50,000 টাকা; ভাড়া আর বিমা 6,000 টাকা আর শুল্ক 4,000 টাকা যোগ হয়। টনপ্রতি পৌঁছানো খরচ কত?", ["60,000 টাকা", "56,000 টাকা", "54,000 টাকা", "50,000 টাকা"],
        "50,000 + 6,000 + 4,000 = 60,000 টাকা - এটা স্থানীয় দামের সঙ্গে তুলনা করো।"),
    mcq("What are 'economies of scale'?", ["Cost per unit falls as a firm produces more", "Weighing scales in a market", "Prices rising with demand", "Saving money by doing less"], 0,
        "A big cement plant makes each bag cheaper than a small kiln can.",
        "'বৃহদায়তনের সাশ্রয়' কী?", ["সংস্থা বেশি বানালে একক-প্রতি খরচ কমে", "বাজারের দাঁড়িপাল্লা", "চাহিদার সঙ্গে দাম বাড়া", "কম কাজ করে টাকা বাঁচানো"],
        "বড় সিমেন্ট-কারখানা ছোট ভাটির চেয়ে প্রতি বস্তা সস্তায় বানায়।"),
    mcq("Why might a builder get a lower price per bag when buying 1,000 bags of cement rather than 10?", ["Bulk discounts: the supplier saves on handling and delivery per bag", "Large orders are taxed less by law", "Cement in big orders is weaker", "Suppliers dislike small customers"], 0,
        "But buy only what you can store safely and use in time.",
        "10 বস্তার বদলে 1,000 বস্তা সিমেন্ট কিনলে নির্মাতা বস্তাপ্রতি কম দাম পান কেন?", ["একসঙ্গে বেশি কেনায় ছাড়: সরবরাহকারীর বস্তাপ্রতি নাড়াচাড়া আর ডেলিভারি-খরচ বাঁচে", "আইনে বড় অর্ডারে কম কর", "বড় অর্ডারের সিমেন্ট দুর্বল", "সরবরাহকারী ছোট খদ্দের পছন্দ করেন না"],
        "তবে যতটা নিরাপদে রাখতে আর সময়ে ব্যবহার করতে পারবে, ততটাই কেনো।"),
    mcq("What does a franchisee usually pay the brand owner for running a tool-hire franchise?", ["An upfront fee plus a share of sales, called a royalty", "Nothing at all", "Only the electricity bill", "A one-rupee coin each year"], 0,
        "In return the franchisee gets a known brand, training and a tested system.",
        "যন্ত্র-ভাড়ার ফ্র্যাঞ্চাইজি চালাতে ফ্র্যাঞ্চাইজি-গ্রহীতা সাধারণত ব্র্যান্ড-মালিককে কী দেন?", ["শুরুতে একটা ফি আর বিক্রির একটা ভাগ, যাকে রয়্যালটি বলে", "কিছুই না", "শুধু বিদ্যুতের বিল", "বছরে একটা এক টাকার কয়েন"],
        "বদলে গ্রহীতা পান চেনা ব্র্যান্ড, প্রশিক্ষণ আর পরীক্ষিত পদ্ধতি।"),
    mcq("Which of these is the strongest unique selling point for a bridge-paint brand?", ["It lasts 20 years in salty sea air - twice as long as rivals", "It is a paint", "It comes in a tin", "It is sold in shops"], 0,
        "A USP must be something rivals cannot easily claim - and it must be true.",
        "সেতুর রঙের একটা ব্র্যান্ডের জন্য কোনটা সবচেয়ে জোরালো অনন্য বিক্রয়-বৈশিষ্ট্য?", ["নোনা সমুদ্র-বাতাসে 20 বছর টেকে - প্রতিদ্বন্দ্বীদের দ্বিগুণ", "এটা একটা রং", "টিনে আসে", "দোকানে বিক্রি হয়"],
        "ইউএসপি এমন হতে হবে যা প্রতিদ্বন্দ্বীরা সহজে দাবি করতে পারে না - আর সত্যি হতে হবে।"),
    mcq("What is 'brand loyalty'?", ["Customers choosing the same brand again and again", "A brand's logo", "A loyalty card machine", "A brand that never changes price"], 0,
        "Builders often stick with a cement brand they trust.",
        "'ব্র্যান্ডের প্রতি আনুগত্য' কী?", ["খদ্দেরের বারবার একই ব্র্যান্ড বেছে নেওয়া", "ব্র্যান্ডের লোগো", "আনুগত্য-কার্ডের যন্ত্র", "যে ব্র্যান্ড দাম বদলায় না"],
        "নির্মাতারা প্রায়ই ভরসার সিমেন্ট-ব্র্যান্ডেই থাকেন।"),
    mcq("What is 'price elasticity of demand' in simple words?", ["How much the quantity bought changes when the price changes", "How stretchy a product is", "The highest price allowed", "The price of rubber"], 0,
        "If a small price rise makes sales drop a lot, demand is 'elastic'.",
        "সহজ কথায় 'চাহিদার দাম-স্থিতিস্থাপকতা' কী?", ["দাম বদলালে কেনা পরিমাণ কতটা বদলায়", "পণ্য কতটা টানলে বাড়ে", "অনুমোদিত সর্বোচ্চ দাম", "রবারের দাম"],
        "দাম একটু বাড়লেই বিক্রি অনেক কমলে চাহিদা 'স্থিতিস্থাপক'।"),
    mcq("Salt and life-saving medicine sell about the same amount even when prices rise. Their demand is…", ["Inelastic", "Elastic", "Zero", "Unlimited"], 0,
        "People need them whatever the price, so buying hardly changes.",
        "দাম বাড়লেও নুন আর জীবনদায়ী ওষুধ প্রায় একই পরিমাণে বিক্রি হয়। এদের চাহিদা…", ["অস্থিতিস্থাপক", "স্থিতিস্থাপক", "শূন্য", "অসীম"],
        "দাম যা-ই হোক মানুষের এগুলো লাগে, তাই কেনা প্রায় বদলায় না।"),
    mcq("What is a 'complementary good'?", ["A product used together with another, like nuts with bolts", "A free gift", "A product that praises you", "A substitute product"], 0,
        "If bolt sales rise, nut sales usually rise too.",
        "'পরিপূরক পণ্য' কী?", ["যে পণ্য অন্যটার সঙ্গে একসঙ্গে ব্যবহার হয়, যেমন বল্টুর সঙ্গে নাট", "বিনামূল্যের উপহার", "যে পণ্য তোমার প্রশংসা করে", "বিকল্প পণ্য"],
        "বল্টুর বিক্রি বাড়লে সাধারণত নাটের বিক্রিও বাড়ে।"),
    mcq("What is a 'substitute good'?", ["A product that can be used instead of another, like steel instead of timber beams", "A spare player", "A fake product", "A product sold only on Sundays"], 0,
        "If timber gets expensive, demand for steel beams may rise.",
        "'বিকল্প পণ্য' কী?", ["যে পণ্য অন্যটার বদলে ব্যবহার করা যায়, যেমন কাঠের কড়ির বদলে ইস্পাত", "বদলি খেলোয়াড়", "নকল পণ্য", "শুধু রবিবারে বিক্রি হওয়া পণ্য"],
        "কাঠ দামি হলে ইস্পাতের কড়ির চাহিদা বাড়তে পারে।"),
    mcq("What does a 'purchase order' (PO) do?", ["It is the buyer's written, numbered order stating items, prices and delivery terms", "It is a receipt for cash", "It is a bank loan form", "It cancels an order"], 0,
        "POs prevent arguments about what was actually ordered.",
        "'ক্রয়াদেশ' (পিও) কী করে?", ["ক্রেতার লিখিত, নম্বর-দেওয়া অর্ডার, যাতে জিনিস, দাম আর ডেলিভারির শর্ত থাকে", "নগদের রসিদ", "ব্যাংক-ঋণের ফর্ম", "অর্ডার বাতিল করে"],
        "আসলে কী অর্ডার হয়েছিল, তা নিয়ে তর্ক আটকায়।"),
    mcq("What is a 'delivery challan' or delivery note?", ["A document that goes with the goods listing what was delivered, signed on receipt", "A speeding ticket", "A bill for payment", "A product advert"], 0,
        "Check the goods against it before signing.",
        "'ডেলিভারি-চালান' কী?", ["মালের সঙ্গে আসা কাগজ, যাতে কী এল তার তালিকা, পেয়ে সই করতে হয়", "গতির জরিমানার রসিদ", "টাকা দেওয়ার বিল", "পণ্যের বিজ্ঞাপন"],
        "সই করার আগে মাল মিলিয়ে দেখো।"),
    mcq("Why should a site manager check deliveries against the purchase order before signing?", ["Once signed, it is hard to claim for short or damaged goods", "Signing is optional anyway", "Drivers like waiting", "To slow the work down"], 0,
        "Count the bags and look for damage: a two-minute check saves a lot of money.",
        "সই করার আগে নির্মাণস্থলের ম্যানেজারের ডেলিভারি ক্রয়াদেশের সঙ্গে মেলানো উচিত কেন?", ["সই করার পরে কম বা ভাঙা মালের দাবি করা কঠিন", "সই তো ঐচ্ছিক", "চালকরা অপেক্ষা পছন্দ করেন", "কাজ ধীর করতে"],
        "বস্তা গোনো আর ক্ষতি দেখো: দুই মিনিটের যাচাই অনেক টাকা বাঁচায়।"),
    mcq("What is a 'quotation' from a supplier?", ["A written offer stating the price at which they will supply goods", "A famous saying", "A final bill", "A complaint letter"], 0,
        "Get at least three quotes for big purchases.",
        "সরবরাহকারীর 'দরপত্র-উদ্ধৃতি' কী?", ["কোন দামে মাল দেবেন তার লিখিত প্রস্তাব", "বিখ্যাত উক্তি", "শেষ বিল", "অভিযোগের চিঠি"],
        "বড় কেনাকাটায় অন্তত তিনটে উদ্ধৃতি নাও।"),
    mcq("Why is the cheapest quote not always the best choice?", ["Quality, delivery time, reliability and after-sales service also matter", "Cheap goods are illegal", "The most expensive is always best", "Quotes are never honest"], 0,
        "Weak bolts at a low price can cost a whole bridge.",
        "সবচেয়ে সস্তা উদ্ধৃতি সবসময় সেরা বাছাই নয় কেন?", ["মান, ডেলিভারির সময়, ভরসাযোগ্যতা আর বিক্রির পরের পরিষেবাও জরুরি", "সস্তা মাল বেআইনি", "সবচেয়ে দামিটাই সবসময় সেরা", "উদ্ধৃতি কখনো সৎ নয়"],
        "কম দামের দুর্বল বল্টুর দাম গোটা সেতু হতে পারে।"),
    mcq("What is a 'warranty' on a machine?", ["The maker's promise to repair or replace it if it fails within a set time", "A police warrant", "An extra charge for delivery", "A guarantee of profit"], 0,
        "Keep the invoice: you will need it to claim.",
        "যন্ত্রের 'ওয়ারেন্টি' কী?", ["নির্দিষ্ট সময়ের মধ্যে বিগড়োলে সারানো বা বদলে দেওয়ার নির্মাতার প্রতিশ্রুতি", "পুলিশের পরোয়ানা", "ডেলিভারির বাড়তি খরচ", "লাভের নিশ্চয়তা"],
        "চালান রেখে দাও: দাবি করতে লাগবে।"),
    mcq("A crane maker promises spare parts within 24 hours anywhere in the state. Why does this help it sell cranes?", ["A broken crane stops a whole site, so fast repairs save buyers a lot of money", "Cranes never break", "Spare parts are free", "It makes the crane taller"], 0,
        "Strong after-sales service can matter more to buyers than a lower price.",
        "একজন ক্রেন-নির্মাতা রাজ্যের যেকোনো জায়গায় 24 ঘণ্টায় খুচরো যন্ত্রাংশের প্রতিশ্রুতি দেন। এতে ক্রেন বিক্রি বাড়ে কেন?", ["বিকল ক্রেন গোটা নির্মাণস্থল থামায়, তাই দ্রুত মেরামতে ক্রেতার অনেক টাকা বাঁচে", "ক্রেন কখনো বিগড়োয় না", "খুচরো যন্ত্রাংশ বিনামূল্যে", "ক্রেন লম্বা হয়"],
        "ক্রেতার কাছে কম দামের চেয়ে বিক্রির পরের ভালো পরিষেবা বেশি জরুরি হতে পারে।"),
    mcq("What is 'net promoter score' (NPS) based on?", ["How likely customers are to recommend the firm to others", "The number of staff", "The firm's net profit", "The number of adverts"], 0,
        "Word of mouth is powerful in the building trade.",
        "'নিট প্রোমোটার স্কোর' (এনপিএস) কীসের উপর ভিত্তি করে?", ["খদ্দেররা অন্যদের কাছে সংস্থাটার সুপারিশ করতে কতটা ইচ্ছুক", "কর্মীর সংখ্যা", "সংস্থার নিট লাভ", "বিজ্ঞাপনের সংখ্যা"],
        "নির্মাণ-ব্যবসায় মুখের কথা খুব শক্তিশালী।"),
    mcq("A customer complains that a delivery of bricks was broken. What is the best first response?", ["Listen, apologise, check the facts and offer to replace the damaged bricks", "Argue that bricks are meant to break", "Ignore the complaint", "Blame the driver in front of the customer"], 0,
        "Handled well, a complaint can win a customer for life.",
        "একজন খদ্দের অভিযোগ করলেন ইটের ডেলিভারি ভাঙা ছিল। প্রথম সবচেয়ে ভালো জবাব কী?", ["শোনো, দুঃখপ্রকাশ করো, তথ্য যাচাই করো আর ভাঙা ইট বদলে দেওয়ার প্রস্তাব দাও", "তর্ক করো যে ইট ভাঙারই কথা", "অভিযোগ উপেক্ষা করো", "খদ্দেরের সামনে চালককে দোষ দাও"],
        "ভালোভাবে সামলালে একটা অভিযোগ আজীবনের খদ্দের এনে দিতে পারে।"),
    mcq("Why does publishing every public bridge tender online help fight corruption?", ["Anyone can see the rules, the bids and who won, so secret deals are harder", "Computers cannot be bribed by anyone", "Online tenders are always cheaper to build", "It hides the bids from the public"], 0,
        "Transparency lets citizens and honest firms spot unfair results.",
        "প্রতিটা সরকারি সেতু-দরপত্র অনলাইনে প্রকাশ করলে দুর্নীতি রুখতে সাহায্য হয় কেন?", ["যে কেউ নিয়ম, দর আর কে জিতল দেখতে পায়, তাই গোপন বোঝাপড়া কঠিন হয়", "কম্পিউটারকে কেউ ঘুষ দিতে পারে না", "অনলাইন দরপত্রে বানানো সবসময় সস্তা", "দরগুলো জনসাধারণের থেকে লুকোয়"],
        "স্বচ্ছতা নাগরিক আর সৎ সংস্থাদের অন্যায্য ফল ধরতে দেয়।"),
    mcq("What is a 'reverse auction' in procurement?", ["Suppliers bid prices down to win the buyer's order", "Buyers bid prices up for an item", "An auction held backwards in time", "Returning goods to a shop"], 0,
        "Used for standard items like cement and steel bars.",
        "ক্রয়ে 'উল্টো নিলাম' কী?", ["ক্রেতার অর্ডার পেতে সরবরাহকারীরা দর কমিয়ে ডাকেন", "ক্রেতারা দর বাড়িয়ে ডাকেন", "সময়ে পিছনের দিকে নিলাম", "দোকানে মাল ফেরত"],
        "সিমেন্ট আর ইস্পাতের রডের মতো সাধারণ জিনিসে ব্যবহার হয়।"),
    mcq("What is 'supply-chain visibility'?", ["Being able to track where materials are at every step, from factory to site", "Painting trucks bright colours", "A clear window in a warehouse", "Seeing suppliers on TV"], 0,
        "GPS on trucks and barcodes on pallets make it possible.",
        "'সরবরাহ-শৃঙ্খলের দৃশ্যমানতা' কী?", ["কারখানা থেকে নির্মাণস্থল পর্যন্ত প্রতি ধাপে মাল কোথায় তা দেখতে পারা", "ট্রাকে উজ্জ্বল রং", "গুদামের স্বচ্ছ জানালা", "টিভিতে সরবরাহকারী দেখা"],
        "ট্রাকে জিপিএস আর প্যালেটে বারকোড এটা সম্ভব করে।"),
    mcq("What does a barcode scanner do in a warehouse?", ["Reads product codes quickly so stock records update without typing errors", "Cuts boxes open", "Weighs the trucks", "Prints money"], 0,
        "Fewer typing mistakes means more accurate stock counts.",
        "গুদামে বারকোড-স্ক্যানার কী করে?", ["দ্রুত পণ্যের সংকেত পড়ে, যাতে টাইপের ভুল ছাড়াই মজুতের হিসাব হালনাগাদ হয়", "বাক্স কেটে খোলে", "ট্রাক ওজন করে", "টাকা ছাপে"],
        "কম টাইপের ভুল মানে আরও সঠিক মজুত-গণনা।"),
    mcq("What is 'cross-docking'?", ["Unloading goods from incoming trucks and loading them straight onto outgoing ones, with little storage", "Building two docks side by side", "Arguing at the dock", "Painting a cross on a dock"], 0,
        "It speeds goods through a depot and saves warehouse space.",
        "'ক্রস-ডকিং' কী?", ["আসা ট্রাক থেকে মাল নামিয়ে প্রায় না রেখে সোজা যাওয়ার ট্রাকে তোলা", "পাশাপাশি দুটো ঘাট বানানো", "ঘাটে ঝগড়া", "ঘাটে ক্রুশচিহ্ন আঁকা"],
        "ডিপো দিয়ে মাল দ্রুত যায় আর গুদামের জায়গা বাঁচে।"),
    mcq("Why do logistics firms plan 'milk runs'?", ["One truck collects from several nearby suppliers on a single loop, filling up as it goes", "To deliver milk only", "To race trucks", "To avoid all customers"], 0,
        "Named after the old milkman's daily round.",
        "পরিবহন-সংস্থা 'দুধওয়ালার পথ' পরিকল্পনা করে কেন?", ["একটা ট্রাক এক চক্করে কাছাকাছি কয়েকজন সরবরাহকারীর থেকে মাল তুলে ভরে ওঠে", "শুধু দুধ পৌঁছাতে", "ট্রাকের দৌড়ের জন্য", "সব খদ্দের এড়াতে"],
        "পুরোনো দুধওয়ালার রোজকার চক্কর থেকে নাম।"),
    mcq("What is 'reverse logistics'?", ["Moving goods back from customers - returns, repairs, reusable pallets and recycling", "Driving in reverse gear", "Delivering to the wrong address", "Cancelling all deliveries"], 0,
        "Returning empty gas cylinders and formwork is reverse logistics.",
        "'উল্টো পরিবহন' কী?", ["খদ্দেরের কাছ থেকে মাল ফেরানো - ফেরত, মেরামত, আবার-ব্যবহারের প্যালেট আর পুনর্ব্যবহার", "পিছনের গিয়ারে চালানো", "ভুল ঠিকানায় পৌঁছানো", "সব ডেলিভারি বাতিল"],
        "খালি গ্যাস-সিলিন্ডার আর ঢালাইয়ের ছাঁচ ফেরানোও উল্টো পরিবহন।"),
    mcq("What is a 'service level agreement' (SLA) with a transport firm?", ["A written promise on standards, such as '95% of deliveries on time'", "A list of drivers' names", "The truck's service manual", "A loan agreement"], 0,
        "If the SLA is missed, the contract may set penalties.",
        "পরিবহন-সংস্থার সঙ্গে 'পরিষেবা-মান চুক্তি' (এসএলএ) কী?", ["মান নিয়ে লিখিত প্রতিশ্রুতি, যেমন '95% ডেলিভারি সময়মতো'", "চালকদের নামের তালিকা", "ট্রাকের সার্ভিস-বই", "ঋণের চুক্তি"],
        "এসএলএ না মানলে চুক্তিতে জরিমানা থাকতে পারে।"),
    mcq("A transporter made 190 of 200 deliveries on time. What is its on-time rate?", ["95%", "90%", "19%", "10%"], 0,
        "190 ÷ 200 x 100 = 95%.",
        "একজন পরিবহনকারী 200টার মধ্যে 190টা ডেলিভারি সময়মতো দিলেন। সময়মতো হার কত?", ["95%", "90%", "19%", "10%"],
        "190 ÷ 200 x 100 = 95%।"),
    mcq("What is 'liquidated damages' in a bridge contract?", ["A fixed sum per day the contractor pays if the work finishes late", "Damage caused by water", "Money for broken tools", "A bonus for finishing early"], 0,
        "It is agreed in advance so there is no argument later.",
        "সেতু-চুক্তিতে 'নির্ধারিত ক্ষতিপূরণ' কী?", ["কাজ দেরিতে শেষ হলে ঠিকাদার দিনপ্রতি যে নির্দিষ্ট অঙ্ক দেন", "জলে হওয়া ক্ষতি", "ভাঙা যন্ত্রের টাকা", "আগে শেষ করার বোনাস"],
        "আগেই ঠিক করা থাকে, তাই পরে তর্ক হয় না।"),
    mcq("A contract sets liquidated damages of Rs 20,000 a day. The bridge opens 6 days late. How much does the contractor pay?", ["Rs 1,20,000", "Rs 20,000", "Rs 1,20,00,000", "Rs 26,000"], 0,
        "20,000 x 6 = Rs 1,20,000.",
        "চুক্তিতে নির্ধারিত ক্ষতিপূরণ দিনে 20,000 টাকা। সেতু 6 দিন দেরিতে খুলল। ঠিকাদার কত দেবেন?", ["1,20,000 টাকা", "20,000 টাকা", "1,20,00,000 টাকা", "26,000 টাকা"],
        "20,000 x 6 = 1,20,000 টাকা।"),
    mcq("What is a 'variation order' on a building contract?", ["A formal change to the agreed work, with its effect on cost and time written down", "An order for many different products", "A random inspection", "A change in the weather"], 0,
        "Never start extra work without one - or you may never be paid for it.",
        "নির্মাণ-চুক্তিতে 'পরিবর্তন-আদেশ' কী?", ["ঠিক করা কাজে আনুষ্ঠানিক বদল, খরচ আর সময়ে তার প্রভাব লিখে রাখা", "অনেক রকম পণ্যের অর্ডার", "হঠাৎ পরিদর্শন", "আবহাওয়ার বদল"],
        "এটা ছাড়া বাড়তি কাজ শুরু কোরো না - নইলে টাকা হয়তো কখনো পাবে না।"),
    mcq("Why is offering a gift to an official to win a tender wrong?", ["It is bribery: it cheats honest bidders and can put unsafe work on public bridges", "Gifts are always too small", "It is fine if nobody sees", "Officials prefer cash only"], 0,
        "Bribery is a crime for both giver and taker.",
        "দরপত্র জিততে কর্মকর্তাকে উপহার দেওয়া ভুল কেন?", ["এটা ঘুষ: সৎ দরদাতাদের ঠকায় আর সরকারি সেতুতে অনিরাপদ কাজ ঢোকাতে পারে", "উপহার সবসময় খুব ছোট", "কেউ না দেখলে ঠিক আছে", "কর্মকর্তারা শুধু নগদ পছন্দ করেন"],
        "ঘুষ দেওয়া আর নেওয়া দুটোই অপরাধ।"),
    mcq("What is 'bid rigging'?", ["Rival firms secretly agreeing who will win a tender and at what price", "Rigging a ship's sails", "Fixing a broken bid form", "Bidding very early"], 0,
        "It makes public projects cost more and is illegal under competition law.",
        "'দরপত্রে কারসাজি' কী?", ["প্রতিদ্বন্দ্বী সংস্থাগুলোর গোপনে ঠিক করা কে কোন দামে দরপত্র জিতবে", "জাহাজের পাল খাটানো", "ভাঙা দরপত্র-ফর্ম সারানো", "খুব আগে দর দেওয়া"],
        "এতে সরকারি প্রকল্পের খরচ বাড়ে আর প্রতিযোগিতা-আইনে এটা বেআইনি।"),
    mcq("What is a 'conflict of interest' in buying for a project?", ["When a buyer's personal gain could affect their choice, e.g. buying from a relative's firm", "Two suppliers arguing", "A disagreement about colours", "Interest rates going up"], 0,
        "Declare it openly and let someone else decide.",
        "প্রকল্পের কেনাকাটায় 'স্বার্থের সংঘাত' কী?", ["যখন ক্রেতার ব্যক্তিগত লাভ তাঁর বাছাইয়ে প্রভাব ফেলতে পারে, যেমন আত্মীয়ের সংস্থা থেকে কেনা", "দুজন সরবরাহকারীর ঝগড়া", "রং নিয়ে মতভেদ", "সুদের হার বাড়া"],
        "খোলাখুলি জানাও আর অন্য কাউকে সিদ্ধান্ত নিতে দাও।"),
    mcq("What does 'ethical sourcing' mean?", ["Buying from suppliers who treat workers fairly and protect the environment", "Buying only the cheapest goods", "Buying only from abroad", "Buying secretly"], 0,
        "Ask where the sand and stone come from - illegal river mining harms bridges and villages.",
        "'নৈতিক সংগ্রহ' মানে কী?", ["এমন সরবরাহকারীর থেকে কেনা যাঁরা কর্মীদের সঙ্গে ন্যায্য আচরণ করেন আর পরিবেশ রক্ষা করেন", "শুধু সবচেয়ে সস্তা মাল কেনা", "শুধু বিদেশ থেকে কেনা", "গোপনে কেনা"],
        "বালি আর পাথর কোথা থেকে আসে জিজ্ঞাসা করো - বেআইনি নদী-খনন সেতু আর গ্রামের ক্ষতি করে।"),
    mcq("Why can illegal sand mining near a river bridge be dangerous?", ["Removing riverbed sand can expose and undermine the bridge's foundations", "Sand makes the river too salty", "It makes the bridge heavier", "It changes the bridge's colour"], 0,
        "Several bridges have collapsed after their piers were undermined.",
        "নদী-সেতুর কাছে বেআইনি বালি-খনন বিপজ্জনক কেন?", ["নদীর তলার বালি সরালে সেতুর ভিত বেরিয়ে পড়ে আর নিচ থেকে ক্ষয়ে যেতে পারে", "বালি নদীকে খুব নোনা করে", "সেতু ভারী হয়", "সেতুর রং বদলায়"],
        "স্তম্ভের নিচ ক্ষয়ে যাওয়ার পরে বেশ কয়েকটা সেতু ভেঙে পড়েছে।"),
    mcq("What is a 'carbon footprint' of delivering materials?", ["The greenhouse gases released by making and transporting them", "A footprint left in wet concrete", "The size of a delivery truck", "Coal used in a kitchen"], 0,
        "Buying local materials can cut transport emissions.",
        "মাল পৌঁছানোর 'কার্বন-পদচিহ্ন' কী?", ["বানানো আর পরিবহনে নির্গত গ্রিনহাউস গ্যাস", "ভেজা কংক্রিটে পায়ের ছাপ", "ডেলিভারি-ট্রাকের মাপ", "রান্নাঘরের কয়লা"],
        "স্থানীয় মাল কিনলে পরিবহনের নির্গমন কমতে পারে।"),
    mcq("Rail can carry a tonne of steel 100 km with far less fuel than road. Why don't all goods go by rail?", ["Rail needs loading at stations and a truck for the last stretch, so short or urgent trips often suit road", "Trains cannot carry steel", "Rail is always slower than walking", "Trucks are free"], 0,
        "The best plans often combine rail for long distances with trucks at each end.",
        "রেলে এক টন ইস্পাত 100 km নিতে সড়কের চেয়ে অনেক কম জ্বালানি লাগে। তবু সব মাল রেলে যায় না কেন?", ["রেলে স্টেশনে তোলা-নামানো আর শেষ পথটুকুর জন্য ট্রাক লাগে, তাই ছোট বা জরুরি যাত্রায় সড়ক সুবিধার", "ট্রেন ইস্পাত বইতে পারে না", "রেল সবসময় হাঁটার চেয়ে ধীর", "ট্রাক বিনামূল্যে"],
        "সেরা পরিকল্পনায় প্রায়ই দূরপথে রেল আর দুই প্রান্তে ট্রাক থাকে।"),
    mcq("What is 'multimodal transport'?", ["Moving goods using two or more types of transport, such as ship, rail and truck, on one journey", "A truck with many gears", "Many trucks on one road", "Transport with music"], 0,
        "Containers make switching between ship, train and truck quick.",
        "'বহুমাধ্যম পরিবহন' কী?", ["এক যাত্রায় দুই বা তার বেশি ধরনের পরিবহন, যেমন জাহাজ, রেল আর ট্রাক, দিয়ে মাল নেওয়া", "অনেক গিয়ারের ট্রাক", "এক রাস্তায় অনেক ট্রাক", "গানসহ পরিবহন"],
        "কনটেনার থাকায় জাহাজ, ট্রেন আর ট্রাকে বদল দ্রুত হয়।"),
    mcq("A new bridge cuts a market town's trip to the port from 4 hours to 1.5 hours. Which business effect is most likely?", ["Lower transport costs and fresher goods, so local firms can sell further away", "Fewer customers for everyone", "Prices of all goods double", "No change at all"], 0,
        "That is why bridges are called engines of trade.",
        "একটা নতুন সেতু বাজার-শহর থেকে বন্দরের যাত্রা 4 ঘণ্টা থেকে 1.5 ঘণ্টায় নামাল। ব্যবসায় কোন প্রভাব সবচেয়ে সম্ভব?", ["পরিবহন-খরচ কমে আর মাল টাটকা থাকে, তাই স্থানীয় সংস্থা আরও দূরে বেচতে পারে", "সবার খদ্দের কমে", "সব জিনিসের দাম দ্বিগুণ", "কোনো বদল নেই"],
        "তাই সেতুকে বাণিজ্যের ইঞ্জিন বলা হয়।"),
    mcq("What is a 'distribution channel'?", ["The route a product takes from maker to final customer, e.g. factory -> wholesaler -> shop", "A TV channel about trucks", "A drain beside a road", "A water canal"], 0,
        "Each step in the channel adds cost and service.",
        "'বণ্টন-প্রণালী' কী?", ["নির্মাতা থেকে শেষ খদ্দের পর্যন্ত পণ্যের পথ, যেমন কারখানা -> পাইকার -> দোকান", "ট্রাক নিয়ে টিভি-চ্যানেল", "রাস্তার পাশের নালা", "জলের খাল"],
        "প্রণালীর প্রতিটা ধাপ খরচ আর পরিষেবা যোগ করে।"),
    mcq("What does a 'wholesaler' do?", ["Buys in bulk from makers and sells in smaller lots to shops", "Sells only to final customers", "Makes the products", "Repairs wholes"], 0,
        "Small hardware shops rely on wholesalers for variety and credit.",
        "'পাইকার' কী করেন?", ["নির্মাতার কাছ থেকে একসঙ্গে বেশি কিনে দোকানে ছোট ছোট পরিমাণে বেচেন", "শুধু শেষ খদ্দেরকে বেচেন", "পণ্য বানান", "ফুটো সারান"],
        "ছোট হার্ডওয়্যার-দোকান বৈচিত্র্য আর ধারের জন্য পাইকারের উপর নির্ভর করে।"),
    mcq("What is a 'trade discount'?", ["A price cut given to businesses in the trade, such as builders, rather than the public", "A discount on trains", "A swap of goods", "A tax on trade"], 0,
        "Builders with trade accounts often pay less than walk-in shoppers.",
        "'ব্যবসায়িক ছাড়' কী?", ["সাধারণ মানুষের বদলে ব্যবসার লোকদের, যেমন নির্মাতাদের, দেওয়া দামে ছাড়", "ট্রেনে ছাড়", "মাল অদলবদল", "বাণিজ্যের উপর কর"],
        "ব্যবসায়িক অ্যাকাউন্টের নির্মাতারা প্রায়ই সাধারণ ক্রেতার চেয়ে কম দেন।"),
    mcq("What is 'seasonal demand' for building materials?", ["Demand that rises and falls with the time of year, e.g. low in the monsoon", "Demand for spices", "Demand that never changes", "Demand only on festivals"], 0,
        "Suppliers plan stock and staff around the building season.",
        "নির্মাণ-সামগ্রীর 'মরসুমি চাহিদা' কী?", ["বছরের সময়ের সঙ্গে ওঠানামা করা চাহিদা, যেমন বর্ষায় কম", "মশলার চাহিদা", "কখনো না বদলানো চাহিদা", "শুধু উৎসবের চাহিদা"],
        "সরবরাহকারীরা নির্মাণ-মরসুম ধরে মজুত আর কর্মী ঠিক করেন।"),
    mcq("What is 'sales forecasting'?", ["Estimating future sales from past data and market trends", "Guessing the weather", "Counting today's cash", "Writing adverts"], 0,
        "Good forecasts help order the right amount of stock.",
        "'বিক্রির পূর্বাভাস' কী?", ["আগের তথ্য আর বাজারের ঝোঁক থেকে ভবিষ্যৎ বিক্রি অনুমান", "আবহাওয়া আন্দাজ", "আজকের নগদ গোনা", "বিজ্ঞাপন লেখা"],
        "ভালো পূর্বাভাস ঠিক পরিমাণ মজুত অর্ডার দিতে সাহায্য করে।"),
    mcq("A shop sold 120, 140 and 160 bags in three months, rising steadily. What is a sensible forecast for next month?", ["About 180 bags", "About 120 bags", "About 420 bags", "About 40 bags"], 0,
        "Sales rise by 20 each month, so 160 + 20 = 180.",
        "একটা দোকান তিন মাসে 120, 140 আর 160 বস্তা বেচল, স্থিরভাবে বাড়ছে। পরের মাসের জন্য যুক্তিসঙ্গত পূর্বাভাস কী?", ["প্রায় 180 বস্তা", "প্রায় 120 বস্তা", "প্রায় 420 বস্তা", "প্রায় 40 বস্তা"],
        "প্রতি মাসে 20 করে বাড়ছে, তাই 160 + 20 = 180।"),
    mcq("A toll bridge charges trucks Rs 60 at peak hours and Rs 40 at night. A haulier moves 25 trips a week to night time. How much does it save each week?", ["Rs 500", "Rs 1,000", "Rs 1,500", "Rs 20"], 0,
        "Saving per trip = 60 - 40 = 20; 20 x 25 = Rs 500. Off-peak pricing spreads traffic out of rush hour.",
        "একটা টোল-সেতু ভিড়ের সময় ট্রাকপ্রতি 60 টাকা আর রাতে 40 টাকা নেয়। একজন পরিবহনকারী সপ্তাহে 25টা যাত্রা রাতে সরালেন। প্রতি সপ্তাহে কত বাঁচে?", ["500 টাকা", "1,000 টাকা", "1,500 টাকা", "20 টাকা"],
        "যাত্রাপ্রতি সাশ্রয় = 60 - 40 = 20; 20 x 25 = 500 টাকা। ভিড়হীন সময়ের দাম ভিড়ের ঘণ্টা থেকে যানবাহন সরায়।"),
    mcq("What is 'FASTag' (electronic toll collection) good for?", ["Vehicles pay tolls automatically without stopping, cutting queues and fuel waste", "Making cars faster", "Free tolls for everyone", "Tracking speeding only"], 0,
        "Shorter queues at the plaza mean fewer emissions and happier drivers.",
        "'ফাস্ট্যাগ' (ইলেকট্রনিক টোল-আদায়) কীসের জন্য ভালো?", ["গাড়ি না থেমেই নিজে থেকে টোল দেয়, লাইন আর জ্বালানির অপচয় কমে", "গাড়ি দ্রুত করে", "সবার টোল বিনামূল্যে", "শুধু গতি-লঙ্ঘন ধরা"],
        "টোল-প্লাজায় ছোট লাইন মানে কম নির্গমন আর খুশি চালক।"),
)
