"""Class 7 - Chemistry (Junior Cadet): moles and masses, percentage composition, gas volumes,
concentration in mol/dm³, percentage yield and atom economy, energy changes, collision theory,
reversible reactions, flame tests, composites and ceramics, and life-cycle thinking for bridges."""
from . import mcq


def _o(r, *alts):
    out = []
    for x in (r, *alts, r + 1, r * 2, r + 10, r + 2):
        if x not in out and x > 0:
            out.append(x)
    return out[:4]


def _n(q_en, q_bn, r, ex_en, ex_bn, alts, u_en="", u_bn=None):
    f = lambda x: f"{x:,}" if isinstance(x, int) else f"{x:g}"
    o = _o(r, *alts)
    ub = u_en if u_bn is None else u_bn
    return mcq(q_en, [f(x) + u_en for x in o], 0, ex_en, q_bn, [f(x) + ub for x in o], ex_bn)


def _c(x):
    return int(x) if x == int(x) else round(x, 2)


def moles(mass, mr, name_en, name_bn):
    r = _c(mass / mr)
    return _n(f"How many moles are in {mass:g} g of {name_en} (Mr = {mr:g})?",
              f"{mass:g} g {name_bn}-এ (Mr = {mr:g}) কত মোল?", r,
              f"Moles = mass ÷ Mr = {mass:g} ÷ {mr:g} = {r:g} mol.",
              f"মোল = ভর ÷ Mr = {mass:g} ÷ {mr:g} = {r:g} মোল।",
              (_c(mass * mr), _c(mr / mass), _c(r * 10)), " mol", " মোল")


def massof(n, mr, name_en, name_bn):
    r = _c(n * mr)
    return _n(f"What is the mass of {n:g} mol of {name_en} (Mr = {mr:g})?",
              f"{n:g} মোল {name_bn}-এর (Mr = {mr:g}) ভর কত?", r,
              f"Mass = moles x Mr = {n:g} x {mr:g} = {r:g} g.",
              f"ভর = মোল x Mr = {n:g} x {mr:g} = {r:g} g।",
              (_c(mr / n), _c(n + mr), _c(r / 10)), " g")


def pcomp(el_en, el_bn, el_mass, mr, name_en, name_bn):
    r = _c(el_mass * 100 / mr)
    return _n(f"What percentage by mass of {name_en} (Mr = {mr:g}) is {el_en}, if its {el_en} atoms total {el_mass:g}?",
              f"{name_bn}-এর (Mr = {mr:g}) ভরের কত শতাংশ {el_bn}, যদি {el_bn}-পরমাণুর মোট ভর {el_mass:g} হয়?", r,
              f"{el_mass:g} ÷ {mr:g} x 100 = {r:g}%.",
              f"{el_mass:g} ÷ {mr:g} x 100 = {r:g}%।",
              (_c(100 - r), _c(mr / el_mass), _c(r / 2)), "%")


def gasvol(n, name_en, name_bn):
    r = _c(n * 24)
    return _n(f"At room temperature, 1 mol of any gas fills about 24 dm³. What volume does {n:g} mol of {name_en} fill?",
              f"ঘরের তাপমাত্রায় যেকোনো গ্যাসের 1 মোল প্রায় 24 dm³ জায়গা নেয়। {n:g} মোল {name_bn} কত আয়তন নেবে?", r,
              f"{n:g} x 24 = {r:g} dm³.",
              f"{n:g} x 24 = {r:g} dm³।",
              (_c(24 / n), _c(n + 24), _c(r / 2)), " dm³")


def molar(n, vol, name_en, name_bn):
    r = _c(n / vol)
    return _n(f"{n:g} mol of {name_en} is dissolved to make {vol:g} dm³ of solution. What is the concentration?",
              f"{n:g} মোল {name_bn} গুলে {vol:g} dm³ দ্রবণ তৈরি হলো। গাঢ়ত্ব কত?", r,
              f"Concentration = moles ÷ volume = {n:g} ÷ {vol:g} = {r:g} mol/dm³.",
              f"গাঢ়ত্ব = মোল ÷ আয়তন = {n:g} ÷ {vol:g} = {r:g} mol/dm³।",
              (_c(n * vol), _c(vol / n), _c(r + 0.5)), " mol/dm³", " মোল/dm³")


def yld(actual, theory, what_en, what_bn):
    r = _c(actual * 100 / theory)
    return _n(f"A reaction should make {theory:g} kg of {what_en} but only {actual:g} kg is collected. What is the percentage yield?",
              f"একটা বিক্রিয়ায় {theory:g} kg {what_bn} হওয়ার কথা, কিন্তু পাওয়া গেল মাত্র {actual:g} kg। শতাংশ-উৎপাদন কত?", r,
              f"Yield = actual ÷ theoretical x 100 = {actual:g} ÷ {theory:g} x 100 = {r:g}%.",
              f"উৎপাদন = প্রকৃত ÷ তাত্ত্বিক x 100 = {actual:g} ÷ {theory:g} x 100 = {r:g}%।",
              (_c(100 - r), _c(theory - actual), _c(theory * 100 / actual)), "%")


ITEMS = (
    moles(88, 44, "carbon dioxide", "কার্বন ডাই-অক্সাইড"), moles(36, 18, "water", "জল"),
    moles(500, 100, "calcium carbonate", "ক্যালসিয়াম কার্বোনেট"), moles(112, 56, "iron", "লোহা"),
    moles(11.7, 58.5, "sodium chloride", "সোডিয়াম ক্লোরাইড"), moles(320, 160, "iron(III) oxide", "আয়রন(III) অক্সাইড"),
    massof(3, 44, "carbon dioxide", "কার্বন ডাই-অক্সাইড"), massof(0.5, 100, "calcium carbonate", "ক্যালসিয়াম কার্বোনেট"),
    massof(4, 56, "calcium oxide", "ক্যালসিয়াম অক্সাইড"), massof(2.5, 98, "sulphuric acid", "সালফিউরিক অ্যাসিড"),
    pcomp("iron", "লোহা", 112, 160, "iron(III) oxide, Fe2O3", "আয়রন(III) অক্সাইড, Fe2O3"),
    pcomp("calcium", "ক্যালসিয়াম", 40, 100, "calcium carbonate, CaCO3", "ক্যালসিয়াম কার্বোনেট, CaCO3"),
    pcomp("oxygen", "অক্সিজেন", 16, 18, "water, H2O", "জল, H2O"),
    pcomp("carbon", "কার্বন", 12, 44, "carbon dioxide, CO2", "কার্বন ডাই-অক্সাইড, CO2"),
    pcomp("aluminium", "অ্যালুমিনিয়াম", 54, 102, "aluminium oxide, Al2O3", "অ্যালুমিনিয়াম অক্সাইড, Al2O3"),
    gasvol(2, "oxygen", "অক্সিজেন"), gasvol(0.5, "carbon dioxide", "কার্বন ডাই-অক্সাইড"),
    gasvol(10, "hydrogen", "হাইড্রোজেন"), gasvol(0.25, "nitrogen", "নাইট্রোজেন"),
    molar(2, 4, "sodium hydroxide", "সোডিয়াম হাইড্রক্সাইড"), molar(0.5, 0.25, "hydrochloric acid", "হাইড্রোক্লোরিক অ্যাসিড"),
    molar(3, 2, "copper sulphate", "কপার সালফেট"), molar(0.1, 0.5, "sodium chloride", "সোডিয়াম ক্লোরাইড"),
    yld(80, 100, "iron from ore", "আকরিক থেকে লোহা"), yld(45, 60, "quicklime", "কলিচুন"),
    yld(9, 12, "zinc coating material", "দস্তার প্রলেপ-উপাদান"), yld(170, 200, "cement clinker", "সিমেন্ট-ক্লিংকার"),
    mcq("Why do chemists use 'moles' instead of counting atoms?", ["Atoms are far too tiny and numerous to count one by one", "Moles are lighter", "It is a tradition only", "Atoms do not exist"], 0,
        "One mole is about 6 x 10^23 particles - like using 'dozens' or 'lakhs' for big numbers.",
        "রসায়নবিদেরা পরমাণু না গুনে 'মোল' ব্যবহার করেন কেন?", ["পরমাণু এত ছোট আর অসংখ্য যে একটা একটা গোনা যায় না", "মোল হালকা", "শুধু প্রথা", "পরমাণুর অস্তিত্ব নেই"],
        "এক মোল প্রায় 6 x 10^23 কণা - বড় সংখ্যার জন্য 'ডজন' বা 'লাখ' ব্যবহারের মতো।"),
    mcq("In CaCO3 -> CaO + CO2, 100 g of limestone gives about how much quicklime?", ["56 g", "100 g", "44 g", "156 g"], 0,
        "1 mol CaCO3 (100 g) -> 1 mol CaO (56 g) + 1 mol CO2 (44 g). Mass is conserved: 56 + 44 = 100.",
        "CaCO3 -> CaO + CO2-এ 100 g চুনাপাথর থেকে প্রায় কত কলিচুন হয়?", ["56 g", "100 g", "44 g", "156 g"],
        "1 মোল CaCO3 (100 g) -> 1 মোল CaO (56 g) + 1 মোল CO2 (44 g)। ভর সংরক্ষিত: 56 + 44 = 100।"),
    mcq("Following CaCO3 -> CaO + CO2, how much CO2 is released when 1 tonne of limestone is heated?", ["About 440 kg", "About 1 tonne", "About 56 kg", "None"], 0,
        "44% of the mass leaves as CO2 - a big reason cement making is carbon-heavy.",
        "CaCO3 -> CaO + CO2 অনুযায়ী 1 টন চুনাপাথর গরম করলে কত CO2 বেরোয়?", ["প্রায় 440 kg", "প্রায় 1 টন", "প্রায় 56 kg", "একটুও না"],
        "ভরের 44% CO2 হয়ে বেরোয় - সিমেন্ট তৈরিতে কার্বন বেশি হওয়ার একটা বড় কারণ।"),
    mcq("What is an 'empirical formula'?", ["The simplest whole-number ratio of atoms in a compound", "The full structure", "The mass of a compound", "A type of experiment"], 0,
        "Glucose C6H12O6 has the empirical formula CH2O.",
        "'স্থূল সংকেত' (এম্পিরিক্যাল ফর্মুলা) কী?", ["যৌগে পরমাণুর সরলতম পূর্ণসংখ্যার অনুপাত", "পূর্ণ গঠন", "যৌগের ভর", "এক রকম পরীক্ষা"],
        "গ্লুকোজ C6H12O6-এর স্থূল সংকেত CH2O।"),
    mcq("What is the empirical formula of ethane, C2H6?", ["CH3", "C2H6", "CH2", "C3H"], 0,
        "Divide both numbers by 2.",
        "ইথেন C2H6-এর স্থূল সংকেত কী?", ["CH3", "C2H6", "CH2", "C3H"],
        "দুটো সংখ্যাকেই 2 দিয়ে ভাগ করো।"),
    mcq("Why is percentage yield usually below 100%?", ["Some product is lost, reactions may not finish, or side reactions happen", "Atoms disappear", "Scales are always wrong", "It is always 100%"], 0,
        "Industry works hard to raise yield and cut waste.",
        "শতাংশ-উৎপাদন সাধারণত 100%-এর কম হয় কেন?", ["কিছু পণ্য হারায়, বিক্রিয়া শেষ না হতে পারে বা পার্শ্ব-বিক্রিয়া হয়", "পরমাণু উধাও হয়", "দাঁড়িপাল্লা সবসময় ভুল", "সবসময় 100%"],
        "শিল্প উৎপাদন বাড়াতে আর অপচয় কমাতে খুব চেষ্টা করে।"),
    mcq("What is 'atom economy'?", ["The percentage of reactant atoms that end up in the useful product", "Saving money on atoms", "The number of atoms in a mole", "Recycling atoms in bins"], 0,
        "Higher atom economy = less waste.",
        "'পরমাণু-সাশ্রয়' (অ্যাটম ইকোনমি) কী?", ["বিক্রিয়কের পরমাণুর কত শতাংশ দরকারি পণ্যে যায়", "পরমাণুতে টাকা বাঁচানো", "এক মোলে পরমাণুর সংখ্যা", "ডাস্টবিনে পরমাণু পুনর্ব্যবহার"],
        "বেশি পরমাণু-সাশ্রয় = কম অপচয়।"),
    mcq("What is an 'exothermic' reaction?", ["One that releases heat to the surroundings", "One that takes in heat", "One with no energy change", "One that only happens in ice"], 0,
        "Combustion, rusting and cement hydration are exothermic.",
        "'তাপমোচী' বিক্রিয়া কী?", ["যে বিক্রিয়া চারপাশে তাপ ছাড়ে", "যে বিক্রিয়া তাপ নেয়", "যাতে শক্তির পরিবর্তন নেই", "যা শুধু বরফে হয়"],
        "দহন, মরচে আর সিমেন্টের জলযোজন তাপমোচী।"),
    mcq("What is an 'endothermic' reaction?", ["One that takes in heat from the surroundings", "One that releases heat", "An explosion", "A neutral reaction"], 0,
        "Thermal decomposition of limestone is endothermic - it needs a hot kiln.",
        "'তাপগ্রাহী' বিক্রিয়া কী?", ["যে বিক্রিয়া চারপাশ থেকে তাপ নেয়", "যে বিক্রিয়া তাপ ছাড়ে", "বিস্ফোরণ", "নিরপেক্ষ বিক্রিয়া"],
        "চুনাপাথরের তাপীয় বিয়োজন তাপগ্রাহী - গরম চুল্লি লাগে।"),
    mcq("In bond terms, why is a reaction exothermic?", ["More energy is released making new bonds than is needed to break old ones", "No bonds change", "Bonds absorb all energy", "Atoms are destroyed"], 0,
        "Breaking bonds takes energy; making bonds releases it.",
        "বন্ধনের হিসেবে একটা বিক্রিয়া তাপমোচী কেন?", ["নতুন বন্ধন তৈরিতে যত শক্তি বেরোয়, পুরোনো ভাঙতে তার কম লাগে", "কোনো বন্ধন বদলায় না", "বন্ধন সব শক্তি শোষে", "পরমাণু ধ্বংস হয়"],
        "বন্ধন ভাঙতে শক্তি লাগে; বন্ধন গড়তে শক্তি বেরোয়।"),
    mcq("What is 'activation energy'?", ["The minimum energy particles need to react when they collide", "The energy in a battery", "Heat given off", "The energy of light"], 0,
        "A match needs a strike to get started.",
        "'সক্রিয়করণ শক্তি' কী?", ["সংঘর্ষে বিক্রিয়ার জন্য কণার ন্যূনতম প্রয়োজনীয় শক্তি", "ব্যাটারির শক্তি", "নির্গত তাপ", "আলোর শক্তি"],
        "দেশলাই জ্বালাতে ঘষা লাগে।"),
    mcq("What does 'collision theory' say about reaction rate?", ["Reactions go faster when particles collide more often and with enough energy", "Particles never collide", "Rate depends only on colour", "Collisions slow reactions"], 0,
        "Heat, concentration, surface area and catalysts all raise successful collisions.",
        "'সংঘর্ষ-তত্ত্ব' বিক্রিয়ার হার নিয়ে কী বলে?", ["কণা বেশিবার আর যথেষ্ট শক্তিতে ধাক্কা খেলে বিক্রিয়া দ্রুত হয়", "কণা কখনো ধাক্কা খায় না", "হার শুধু রঙের উপর নির্ভর করে", "সংঘর্ষ বিক্রিয়া ধীর করে"],
        "তাপ, গাঢ়ত্ব, তলের ক্ষেত্রফল আর অনুঘটক সফল সংঘর্ষ বাড়ায়।"),
    mcq("How does a catalyst speed up a reaction?", ["It provides a route with lower activation energy", "It adds more heat", "It is used up quickly", "It makes particles bigger"], 0,
        "Catalysts are not used up, so small amounts work for a long time.",
        "অনুঘটক কীভাবে বিক্রিয়া দ্রুত করে?", ["কম সক্রিয়করণ-শক্তির পথ দেয়", "বেশি তাপ যোগ করে", "দ্রুত খরচ হয়", "কণা বড় করে"],
        "অনুঘটক খরচ হয় না, তাই অল্পে অনেক দিন কাজ করে।"),
    mcq("What is a 'reversible reaction'?", ["One where products can turn back into reactants", "One that always explodes", "One that happens once only", "One with no products"], 0,
        "Shown with a double arrow ⇌.",
        "'উভমুখী বিক্রিয়া' কী?", ["যাতে বিক্রিয়াজাত আবার বিক্রিয়কে ফিরতে পারে", "যা সবসময় বিস্ফোরিত হয়", "যা একবারই হয়", "যাতে বিক্রিয়াজাত নেই"],
        "দুই দিকের তির ⇌ দিয়ে দেখানো হয়।"),
    mcq("What is 'dynamic equilibrium'?", ["Forward and backward reactions happen at the same rate, so amounts stay constant", "The reaction has stopped completely", "Only products remain", "Particles stop moving"], 0,
        "It looks still but is busy underneath - like a toll bridge with equal traffic both ways.",
        "'গতিশীল সাম্যাবস্থা' কী?", ["সম্মুখ আর বিপরীত বিক্রিয়া একই হারে হয়, তাই পরিমাণ স্থির থাকে", "বিক্রিয়া পুরো থেমে গেছে", "শুধু বিক্রিয়াজাত থাকে", "কণা থেমে যায়"],
        "বাইরে স্থির দেখালেও ভেতরে ব্যস্ত - দুই দিকে সমান যানবাহনের টোল-সেতুর মতো।"),
    mcq("What colour flame does a copper compound give in a flame test?", ["Blue-green", "Red", "Yellow", "Lilac"], 0,
        "Flame tests identify metal ions.",
        "শিখা-পরীক্ষায় তামার যৌগ কোন রঙের শিখা দেয়?", ["নীল-সবুজ", "লাল", "হলুদ", "বেগুনি"],
        "শিখা-পরীক্ষা ধাতব আয়ন শনাক্ত করে।"),
    mcq("A sample gives a strong orange-yellow flame. Which metal ion is present?", ["Sodium", "Copper", "Potassium", "Calcium"], 0,
        "Sodium street lamps glow orange for the same reason.",
        "একটা নমুনা জোরালো কমলা-হলুদ শিখা দেয়। কোন ধাতব আয়ন আছে?", ["সোডিয়াম", "তামা", "পটাশিয়াম", "ক্যালসিয়াম"],
        "একই কারণে সোডিয়ামের রাস্তার বাতি কমলা জ্বলে।"),
    mcq("What is the test for chloride ions?", ["Add acidified silver nitrate - a white precipitate forms", "Add water - it fizzes", "Use a magnet", "Heat it - it turns blue"], 0,
        "Engineers test concrete for chlorides, which cause steel to rust.",
        "ক্লোরাইড আয়নের পরীক্ষা কী?", ["অম্লীকৃত সিলভার নাইট্রেট দাও - সাদা অধঃক্ষেপ হয়", "জল দাও - বুদবুদ ওঠে", "চুম্বক ব্যবহার করো", "গরম করো - নীল হয়"],
        "রডে মরচে ধরানো ক্লোরাইডের জন্য প্রকৌশলীরা কংক্রিট পরীক্ষা করেন।"),
    mcq("What is a 'composite material'?", ["Two or more materials combined to get better properties", "A pure metal", "A single element", "A liquid mixture"], 0,
        "Reinforced concrete and carbon-fibre plastic are composites.",
        "'যৌগিক উপাদান' (কম্পোজিট) কী?", ["উন্নত ধর্ম পেতে দুই বা বেশি উপাদান একসঙ্গে", "বিশুদ্ধ ধাতু", "একটা মৌল", "তরলের মিশ্রণ"],
        "রড-কংক্রিট আর কার্বন-ফাইবার প্লাস্টিক যৌগিক উপাদান।"),
    mcq("In reinforced concrete, what does each part do?", ["Concrete resists squashing; steel bars resist stretching", "Steel adds colour", "Concrete conducts electricity", "Both resist only heat"], 0,
        "Together they handle both compression and tension.",
        "রড-কংক্রিটে প্রতিটি অংশ কী করে?", ["কংক্রিট চাপ ঠেকায়; ইস্পাতের রড টান ঠেকায়", "ইস্পাত রং যোগ করে", "কংক্রিট বিদ্যুৎ পরিবহন করে", "দুটোই শুধু তাপ ঠেকায়"],
        "একসঙ্গে সংনমন আর টান দুটোই সামলায়।"),
    mcq("What are 'ceramics'?", ["Hard, heat-resistant materials made by firing clay or minerals", "Soft plastics", "Metals", "Liquids"], 0,
        "Bricks, tiles and porcelain insulators are ceramics.",
        "'সিরামিক' কী?", ["মাটি বা খনিজ পুড়িয়ে তৈরি শক্ত, তাপ-রোধী উপাদান", "নরম প্লাস্টিক", "ধাতু", "তরল"],
        "ইট, টালি আর চীনামাটির অন্তরক সিরামিক।"),
    mcq("Why are bricks strong in compression but weak in tension?", ["Ceramics are brittle - cracks spread easily when pulled", "Bricks are hollow", "Bricks contain steel", "They are strong in both"], 0,
        "That is why brick arches work but brick beams do not.",
        "ইট চাপে শক্ত কিন্তু টানে দুর্বল কেন?", ["সিরামিক ভঙ্গুর - টানলে ফাটল সহজে ছড়ায়", "ইট ফাঁপা", "ইটে ইস্পাত থাকে", "দুটোতেই শক্ত"],
        "তাই ইটের খিলান চলে, কিন্তু ইটের বিম চলে না।"),
    mcq("What is the difference between thermosoftening and thermosetting polymers?", ["Thermosoftening melt when heated; thermosetting stay hard", "Thermosetting melt easily", "They are the same", "Neither can be shaped"], 0,
        "Thermosoftening plastics can be recycled by melting.",
        "তাপে-নরম আর তাপে-শক্ত পলিমারের পার্থক্য কী?", ["তাপে-নরম গরমে গলে; তাপে-শক্ত শক্তই থাকে", "তাপে-শক্ত সহজে গলে", "দুটো একই", "কোনোটাই আকার দেওয়া যায় না"],
        "তাপে-নরম প্লাস্টিক গলিয়ে পুনর্ব্যবহার করা যায়।"),
    mcq("What is an 'epoxy resin' used for on bridges?", ["Strong glue and protective coating, and bonding carbon-fibre strips", "Fuel", "Drinking water treatment", "Making glass"], 0,
        "Epoxy is a thermosetting polymer.",
        "সেতুতে 'ইপক্সি রেজিন' কীসে ব্যবহার হয়?", ["শক্ত আঠা আর রক্ষাকারী প্রলেপ, আর কার্বন-ফাইবার ফালি জোড়া", "জ্বালানি", "খাবার জল শোধন", "কাচ তৈরি"],
        "ইপক্সি একটা তাপে-শক্ত পলিমার।"),
    mcq("What is a 'life cycle assessment' (LCA)?", ["Measuring environmental impact from raw materials to disposal", "A biology test", "A bike service", "A bank report"], 0,
        "LCAs help choose greener bridge materials.",
        "'জীবনচক্র মূল্যায়ন' (এলসিএ) কী?", ["কাঁচামাল থেকে বাতিল পর্যন্ত পরিবেশগত প্রভাব মাপা", "জীববিদ্যার পরীক্ষা", "সাইকেলের পরিষেবা", "ব্যাংকের রিপোর্ট"],
        "এলসিএ সবুজ সেতু-উপাদান বাছতে সাহায্য করে।"),
    mcq("Why does recycled steel have a much lower carbon footprint than new steel?", ["Melting scrap needs far less energy than extracting iron from ore", "Recycled steel is lighter", "It is not made of iron", "It never rusts"], 0,
        "Electric arc furnaces recycle scrap efficiently.",
        "পুনর্ব্যবহৃত ইস্পাতের কার্বন-পদচিহ্ন নতুনের চেয়ে অনেক কম কেন?", ["আকরিক থেকে লোহা বের করার চেয়ে টুকরো গলাতে অনেক কম শক্তি লাগে", "পুনর্ব্যবহৃত ইস্পাত হালকা", "লোহা দিয়ে তৈরি নয়", "কখনো মরচে ধরে না"],
        "বৈদ্যুতিক আর্ক-চুল্লি দক্ষতার সঙ্গে টুকরো পুনর্ব্যবহার করে।"),
    mcq("What is 'potable water'?", ["Water safe to drink", "Water in pots only", "Salty sea water", "Rain on roofs"], 0,
        "Treatment: screening, sedimentation, filtration and chlorination.",
        "'পানযোগ্য জল' কী?", ["খাওয়ার জন্য নিরাপদ জল", "শুধু হাঁড়ির জল", "নোনা সমুদ্রের জল", "ছাদের বৃষ্টি"],
        "শোধন: ছাঁকনি, থিতানো, পরিস্রাবণ আর ক্লোরিনেশন।"),
    mcq("Why is chlorine added to drinking water?", ["To kill harmful microbes", "To make it blue", "To add taste only", "To make it fizzy"], 0,
        "Only tiny, safe amounts are used.",
        "খাবার জলে ক্লোরিন মেশানো হয় কেন?", ["ক্ষতিকর জীবাণু মারতে", "নীল করতে", "শুধু স্বাদের জন্য", "বুদবুদ করতে"],
        "শুধু অল্প, নিরাপদ পরিমাণ ব্যবহার হয়।"),
    mcq("What is 'desalination'?", ["Removing salt from seawater to make fresh water", "Adding salt", "Freezing water", "Filtering mud only"], 0,
        "It uses lots of energy, so it is used where fresh water is scarce.",
        "'লবণমুক্তকরণ' কী?", ["সমুদ্রের জল থেকে লবণ সরিয়ে মিঠে জল তৈরি", "লবণ যোগ", "জল জমানো", "শুধু কাদা ছাঁকা"],
        "অনেক শক্তি লাগে, তাই মিঠে জলের অভাবের জায়গায় ব্যবহার হয়।"),
    mcq("What does a 'state symbol' (aq) mean in an equation?", ["Dissolved in water (aqueous)", "Solid", "Gas", "Pure liquid"], 0,
        "(s) solid, (l) liquid, (g) gas, (aq) aqueous.",
        "সমীকরণে 'অবস্থা-চিহ্ন' (aq) মানে কী?", ["জলে দ্রবীভূত", "কঠিন", "গ্যাস", "বিশুদ্ধ তরল"],
        "(s) কঠিন, (l) তরল, (g) গ্যাস, (aq) জলীয় দ্রবণ।"),
    mcq("In the electrolysis of molten sodium chloride, what forms at the negative electrode?", ["Sodium metal", "Chlorine gas", "Oxygen", "Water"], 0,
        "Positive ions go to the negative electrode and gain electrons.",
        "গলিত সোডিয়াম ক্লোরাইডের তড়িৎবিশ্লেষণে ঋণাত্মক তড়িৎদ্বারে কী তৈরি হয়?", ["সোডিয়াম ধাতু", "ক্লোরিন গ্যাস", "অক্সিজেন", "জল"],
        "ধনাত্মক আয়ন ঋণাত্মক তড়িৎদ্বারে গিয়ে ইলেকট্রন নেয়।"),
    mcq("What is 'cathodic protection' for steel piles in rivers?", ["Using a small electric current or sacrificial metal so the steel does not corrode", "Painting them red", "Wrapping in paper", "Heating them"], 0,
        "It makes the steel the cathode, where corrosion does not happen.",
        "নদীতে ইস্পাতের খুঁটির 'ক্যাথোডিক সুরক্ষা' কী?", ["ছোট বিদ্যুৎ-প্রবাহ বা উৎসর্গী ধাতু ব্যবহার, যাতে ইস্পাত ক্ষয় না হয়", "লাল রং করা", "কাগজে মোড়া", "গরম করা"],
        "এতে ইস্পাত ক্যাথোড হয়, যেখানে ক্ষয় হয় না।"),
    mcq("Why do welders need good ventilation?", ["Welding fumes contain harmful metal oxides and gases", "To keep sparks bright", "To cool the steel faster", "It is not needed"], 0,
        "Fume extraction protects lungs.",
        "ঝালাইকারীদের ভালো বায়ুচলাচল লাগে কেন?", ["ঝালাইয়ের ধোঁয়ায় ক্ষতিকর ধাতব অক্সাইড আর গ্যাস থাকে", "স্ফুলিঙ্গ উজ্জ্বল রাখতে", "ইস্পাত দ্রুত ঠান্ডা করতে", "দরকার নেই"],
        "ধোঁয়া-নিষ্কাশন ফুসফুস রক্ষা করে।"),
    mcq("What is 'nanotechnology' in materials?", ["Working with particles about 1-100 nanometres in size", "Making very large machines", "A type of paint brush", "Space travel"], 0,
        "Nano-coatings can make surfaces self-cleaning or extra hard.",
        "উপাদানে 'ন্যানোপ্রযুক্তি' কী?", ["প্রায় 1-100 ন্যানোমিটার মাপের কণা নিয়ে কাজ", "খুব বড় যন্ত্র বানানো", "এক রকম রঙের তুলি", "মহাকাশ ভ্রমণ"],
        "ন্যানো-প্রলেপ তলকে স্বয়ং-পরিষ্কার বা খুব শক্ত করতে পারে।"),
    mcq("What is 'self-healing concrete'?", ["Concrete with bacteria or capsules that seal small cracks with new limestone", "Concrete that grows taller", "Concrete with medicine", "Wet concrete only"], 0,
        "Researchers hope it will make bridges last longer with less repair.",
        "'স্বয়ং-নিরাময় কংক্রিট' কী?", ["ব্যাকটেরিয়া বা ক্যাপসুলসহ কংক্রিট, যা নতুন চুনাপাথরে ছোট ফাটল বন্ধ করে", "যে কংক্রিট লম্বা হয়", "ওষুধসহ কংক্রিট", "শুধু ভেজা কংক্রিট"],
        "গবেষকেরা আশা করেন এতে কম মেরামতে সেতু বেশি দিন টিকবে।"),
    moles(64, 32, "oxygen gas (O2)", "অক্সিজেন গ্যাস (O2)"), moles(260, 65, "zinc", "দস্তা"),
    moles(9, 18, "water", "জল"),
    massof(0.2, 160, "iron(III) oxide", "আয়রন(III) অক্সাইড"), massof(10, 27, "aluminium", "অ্যালুমিনিয়াম"),
    massof(1.5, 74, "calcium hydroxide", "ক্যালসিয়াম হাইড্রক্সাইড"), massof(6, 2, "hydrogen gas (H2)", "হাইড্রোজেন গ্যাস (H2)"),
    pcomp("calcium", "ক্যালসিয়াম", 40, 56, "calcium oxide, CaO", "ক্যালসিয়াম অক্সাইড, CaO"),
    pcomp("sulphur", "সালফার", 32, 98, "sulphuric acid, H2SO4", "সালফিউরিক অ্যাসিড, H2SO4"),
    pcomp("nitrogen", "নাইট্রোজেন", 14, 17, "ammonia, NH3", "অ্যামোনিয়া, NH3"),
    gasvol(3, "methane", "মিথেন"), gasvol(0.1, "argon (welding shield gas)", "আর্গন (ঝালাইয়ের আবরক গ্যাস)"), gasvol(1.5, "carbon monoxide", "কার্বন মনোক্সাইড"),
    molar(1, 2, "potassium nitrate", "পটাশিয়াম নাইট্রেট"), molar(0.6, 0.3, "sulphuric acid", "সালফিউরিক অ্যাসিড"), molar(4, 8, "calcium chloride", "ক্যালসিয়াম ক্লোরাইড"),
    yld(36, 40, "steel from a melt", "গলন থেকে ইস্পাত"), yld(7, 10, "copper from ore", "আকরিক থেকে তামা"), yld(95, 100, "recycled aluminium", "পুনর্ব্যবহৃত অ্যালুমিনিয়াম"),
    mcq("How many particles are in one mole (Avogadro's number)?", ["About 6 x 10^23", "About 100", "About 1 million", "About 6,000"], 0,
        "That is 600,000,000,000,000,000,000,000 particles!",
        "এক মোলে কতগুলো কণা থাকে (অ্যাভোগাড্রো সংখ্যা)?", ["প্রায় 6 x 10^23", "প্রায় 100", "প্রায় 10 লাখ", "প্রায় 6,000"],
        "মানে 6-এর পরে 23টি শূন্য সংখ্যক কণা!"),
    mcq("Iron + oxygen: 4Fe + 3O2 -> 2Fe2O3. How many moles of Fe2O3 form from 4 mol of Fe?", ["2", "4", "3", "8"], 0,
        "The equation's ratio 4 : 2 means half as many moles of rust form.",
        "লোহা + অক্সিজেন: 4Fe + 3O2 -> 2Fe2O3। 4 মোল Fe থেকে কত মোল Fe2O3 হয়?", ["2", "4", "3", "8"],
        "সমীকরণের অনুপাত 4 : 2 মানে অর্ধেক মোল মরচে হয়।"),
    mcq("What is a 'limiting reactant'?", ["The reactant that runs out first, stopping the reaction", "The most expensive chemical", "The catalyst", "The product"], 0,
        "Like running out of bolts before beams - the job stops.",
        "'সীমাবদ্ধকারী বিক্রিয়ক' কী?", ["যে বিক্রিয়ক আগে ফুরিয়ে বিক্রিয়া থামায়", "সবচেয়ে দামি রাসায়নিক", "অনুঘটক", "বিক্রিয়াজাত"],
        "বিমের আগে বল্টু ফুরোনোর মতো - কাজ থেমে যায়।"),
    mcq("Why must cement plants carefully control the ratio of limestone to clay?", ["Wrong ratios give weak or unstable cement", "To change the colour only", "Clay is free", "It does not matter"], 0,
        "Chemistry decides concrete strength decades later.",
        "সিমেন্ট-কারখানাকে চুনাপাথর আর কাদামাটির অনুপাত সাবধানে নিয়ন্ত্রণ করতে হয় কেন?", ["ভুল অনুপাতে দুর্বল বা অস্থির সিমেন্ট হয়", "শুধু রং বদলাতে", "কাদামাটি বিনামূল্যে", "কিছু যায় আসে না"],
        "রসায়নই দশক পরের কংক্রিটের শক্তি ঠিক করে।"),
    mcq("What does a 'neutralisation' reaction always produce?", ["A salt and water", "Hydrogen only", "Carbon dioxide only", "A metal"], 0,
        "Acid + base -> salt + water.",
        "'প্রশমন' বিক্রিয়ায় সবসময় কী তৈরি হয়?", ["লবণ আর জল", "শুধু হাইড্রোজেন", "শুধু কার্বন ডাই-অক্সাইড", "ধাতু"],
        "অ্যাসিড + ক্ষারক -> লবণ + জল।"),
    mcq("Why is lime sometimes spread on acidic soil near construction sites?", ["It neutralises acidity so plants can grow again", "To make it slippery", "To harden it like concrete", "To attract insects"], 0,
        "Calcium carbonate or hydroxide raises soil pH.",
        "নির্মাণস্থলের কাছের অম্লীয় মাটিতে কখনো চুন ছড়ানো হয় কেন?", ["অম্লতা প্রশমিত করে যাতে আবার গাছ জন্মায়", "পিছল করতে", "কংক্রিটের মতো শক্ত করতে", "পোকা টানতে"],
        "ক্যালসিয়াম কার্বোনেট বা হাইড্রক্সাইড মাটির pH বাড়ায়।"),
    mcq("What is a 'strong acid'?", ["One that is completely ionised in water", "One that is very concentrated only", "One that smells strong", "One that is solid"], 0,
        "Strength (ionisation) is different from concentration (amount dissolved).",
        "'তীব্র অ্যাসিড' কী?", ["যা জলে পুরোপুরি আয়নিত হয়", "শুধু খুব গাঢ়", "কড়া গন্ধের", "কঠিন"],
        "তীব্রতা (আয়নন) আর গাঢ়ত্ব (গোলা পরিমাণ) আলাদা জিনিস।"),
    mcq("What ion do all acids release in water?", ["Hydrogen ions (H+)", "Hydroxide ions (OH-)", "Sodium ions", "Chloride ions only"], 0,
        "Alkalis release hydroxide ions (OH-).",
        "সব অ্যাসিড জলে কোন আয়ন ছাড়ে?", ["হাইড্রোজেন আয়ন (H+)", "হাইড্রক্সাইড আয়ন (OH-)", "সোডিয়াম আয়ন", "শুধু ক্লোরাইড আয়ন"],
        "ক্ষার হাইড্রক্সাইড আয়ন (OH-) ছাড়ে।"),
    mcq("A pH falls from 6 to 4. How has the H+ concentration changed?", ["It is 100 times higher", "It doubled", "It halved", "No change"], 0,
        "Each pH step is a factor of 10.",
        "pH 6 থেকে 4-এ নামল। H+ গাঢ়ত্ব কীভাবে বদলাল?", ["100 গুণ বেড়েছে", "দ্বিগুণ হয়েছে", "অর্ধেক হয়েছে", "পরিবর্তন নেই"],
        "pH-এর প্রতিটি ধাপ 10 গুণের।"),
    mcq("What is 'oxidation' in terms of electrons?", ["Loss of electrons", "Gain of electrons", "Gain of protons", "Loss of neutrons"], 0,
        "OIL RIG: Oxidation Is Loss, Reduction Is Gain.",
        "ইলেকট্রনের হিসেবে 'জারণ' কী?", ["ইলেকট্রন ত্যাগ", "ইলেকট্রন গ্রহণ", "প্রোটন গ্রহণ", "নিউট্রন ত্যাগ"],
        "মনে রাখো: জারণে ত্যাগ, বিজারণে গ্রহণ।"),
    mcq("When iron rusts, what happens to iron atoms?", ["They lose electrons (are oxidised) to form iron ions", "They gain electrons", "They turn into gold", "Nothing"], 0,
        "Fe -> Fe3+ + 3e-.",
        "লোহায় মরচে ধরলে লোহার পরমাণুর কী হয়?", ["ইলেকট্রন ত্যাগ করে (জারিত হয়ে) লোহার আয়ন হয়", "ইলেকট্রন নেয়", "সোনা হয়", "কিছুই না"],
        "Fe -> Fe3+ + 3e-।"),
    mcq("What is 'hard water'?", ["Water with dissolved calcium and magnesium compounds", "Frozen water", "Very cold water", "Dirty water"], 0,
        "It forms limescale in pipes and kettles.",
        "'খর জল' কী?", ["ক্যালসিয়াম আর ম্যাগনেশিয়ামের যৌগ গোলা জল", "জমা জল", "খুব ঠান্ডা জল", "নোংরা জল"],
        "এটা পাইপ আর কেটলিতে চুনের স্তর জমায়।"),
    mcq("A kettle used with hard water gets a white crust inside. What is the crust made of?", ["Calcium carbonate (limescale)", "A fish scale", "A measuring scale", "Rust"], 0,
        "It can block pipes and boilers.",
        "খর জলে ব্যবহৃত কেটলির ভেতরে সাদা আস্তরণ পড়ে। আস্তরণটা কী দিয়ে তৈরি?", ["ক্যালসিয়াম কার্বোনেট (চুনের স্তর)", "মাছের আঁশ", "মাপার দাঁড়িপাল্লা", "মরচে"],
        "পাইপ আর বয়লার আটকে দিতে পারে।"),
    mcq("What is an 'ion'?", ["An atom or group of atoms with an electric charge", "A neutral atom", "A type of molecule only", "A metal bar"], 0,
        "Atoms become ions by gaining or losing electrons.",
        "'আয়ন' কী?", ["বৈদ্যুতিক আধানযুক্ত পরমাণু বা পরমাণুগুচ্ছ", "নিরপেক্ষ পরমাণু", "শুধু এক রকম অণু", "ধাতুর দণ্ড"],
        "ইলেকট্রন নিয়ে বা ছেড়ে পরমাণু আয়ন হয়।"),
    mcq("What charge does a calcium ion (Ca2+) have?", ["2 positive charges", "2 negative charges", "No charge", "1 negative charge"], 0,
        "Calcium loses 2 electrons.",
        "ক্যালসিয়াম আয়নের (Ca2+) আধান কী?", ["2টি ধনাত্মক আধান", "2টি ঋণাত্মক আধান", "আধান নেই", "1টি ঋণাত্মক আধান"],
        "ক্যালসিয়াম 2টি ইলেকট্রন ছাড়ে।"),
    mcq("Why do ionic compounds like salt have high melting points?", ["Strong attractions between many oppositely charged ions", "They are always wet", "They have no bonds", "They are gases"], 0,
        "Lots of energy is needed to break the giant lattice.",
        "লবণের মতো আয়নীয় যৌগের গলনাঙ্ক উঁচু কেন?", ["বহু বিপরীত আধানের আয়নের মধ্যে প্রবল আকর্ষণ", "সবসময় ভেজা", "বন্ধন নেই", "এরা গ্যাস"],
        "বিশাল জালক ভাঙতে অনেক শক্তি লাগে।"),
    mcq("Why can't solid salt conduct electricity, but molten salt can?", ["In the solid, ions are fixed; when molten they can move", "Solid salt has no ions", "Molten salt is metal", "Neither conducts"], 0,
        "Charges must be free to move to carry current.",
        "কঠিন লবণ বিদ্যুৎ পরিবহন করে না, কিন্তু গলিত লবণ করে কেন?", ["কঠিনে আয়ন স্থির; গলিত অবস্থায় চলতে পারে", "কঠিন লবণে আয়ন নেই", "গলিত লবণ ধাতু", "কোনোটাই করে না"],
        "বিদ্যুৎ বইতে আধানকে মুক্তভাবে চলতে হয়।"),
    mcq("Why does graphite conduct electricity but diamond does not?", ["Graphite has free electrons between its layers", "Diamond is wet", "Graphite is a metal", "Diamond has free electrons"], 0,
        "Graphite is used in electrodes and pencils.",
        "গ্রাফাইট বিদ্যুৎ পরিবহন করে কিন্তু হীরে করে না কেন?", ["গ্রাফাইটের স্তরের মাঝে মুক্ত ইলেকট্রন আছে", "হীরে ভেজা", "গ্রাফাইট ধাতু", "হীরের মুক্ত ইলেকট্রন আছে"],
        "গ্রাফাইট তড়িৎদ্বার আর পেনসিলে ব্যবহার হয়।"),
    mcq("What is 'graphene'?", ["A single layer of carbon atoms, extremely strong and light", "A type of paint", "A plastic bag", "A metal ore"], 0,
        "Scientists are testing it to strengthen concrete and coatings.",
        "'গ্রাফিন' কী?", ["কার্বন পরমাণুর একটা মাত্র স্তর, অত্যন্ত শক্ত আর হালকা", "এক রকম রং", "প্লাস্টিকের ব্যাগ", "ধাতুর আকরিক"],
        "বিজ্ঞানীরা কংক্রিট আর প্রলেপ মজবুত করতে এটা পরীক্ষা করছেন।"),
)
