"""Class 7 - Biology (Junior Cadet): the nervous system and reflex arc, hormones, plant responses,
osmosis practicals, transpiration rates, aerobic and anaerobic respiration, nitrogen and water
cycles, habitat fragmentation and wildlife corridors, variation, genetic engineering, clinical
trials and worker health (noise, heat, posture)."""
from . import mcq


def _o(r, *alts):
    out = []
    for x in (r, *alts, r + 1, r * 2, r + 10, r + 2):
        if x not in out and x > 0:
            out.append(x)
    return out[:4]


def _n(q_en, q_bn, r, ex_en, ex_bn, alts, u_en="", u_bn=None):
    f = lambda x: f"{x:,}" if isinstance(x, int) else f"{x:g}"
    o = _o(r, *alts)
    ub = u_en if u_bn is None else u_bn
    return mcq(q_en, [f(x) + u_en for x in o], 0, ex_en, q_bn, [f(x) + ub for x in o], ex_bn)


def _c(x):
    return int(x) if x == int(x) else round(x, 1)


def osmo(before, after):
    ch = _c((after - before) * 100 / before)
    gain = ch > 0
    o = []
    for v in (ch, -ch, _c(after - before), _c(ch * 2)):
        if v not in o:
            o.append(v)
    o = [f"{v:+g}%" for v in o[:4]]
    return mcq(f"A potato piece weighs {before:g} g before and {after:g} g after an hour in a solution. What is the percentage change in mass?",
               o, 0,
               f"({after:g} - {before:g}) ÷ {before:g} x 100 = {ch:+g}%. " + ("It gained water - the solution was more dilute than the cells." if gain else "It lost water by osmosis - the solution was more concentrated than the cells."),
               f"একটা আলুর টুকরোর ওজন দ্রবণে রাখার আগে {before:g} g আর এক ঘণ্টা পরে {after:g} g। ভরের শতাংশ পরিবর্তন কত?",
               o,
               f"({after:g} - {before:g}) ÷ {before:g} x 100 = {ch:+g}%। " + ("জল নিয়েছে - দ্রবণ কোষের চেয়ে লঘু ছিল।" if gain else "অভিস্রবণে জল হারিয়েছে - দ্রবণ কোষের চেয়ে গাঢ় ছিল।"))


def transp(mm, minutes):
    r = _c(mm / minutes)
    return _n(f"In a potometer, an air bubble moves {mm} mm in {minutes} minutes as a leafy shoot takes up water. What is the rate?",
              f"একটা পোটোমিটারে পাতাওয়ালা ডাল জল নিলে একটা বায়ু-বুদবুদ {minutes} মিনিটে {mm} mm সরে। হার কত?", r,
              f"Rate = distance ÷ time = {mm} ÷ {minutes} = {r:g} mm per minute.",
              f"হার = দূরত্ব ÷ সময় = {mm} ÷ {minutes} = মিনিটে {r:g} mm।",
              (mm * minutes, _c(minutes / mm), r + 3), " mm/min", " mm/মিনিট")


def doubling(start, hours, every):
    n = hours // every
    r = start * 2 ** n
    return _n(f"Bacteria on a dirty tool double every {every} minutes. Starting with {start}, how many after {hours} minutes?",
              f"নোংরা যন্ত্রের ব্যাকটেরিয়া প্রতি {every} মিনিটে দ্বিগুণ হয়। {start}টি দিয়ে শুরু করে {hours} মিনিট পরে কয়টি?", r,
              f"{hours} ÷ {every} = {n} doublings: {start} x 2^{n} = {r:,}. Clean and cover wounds quickly!",
              f"{hours} ÷ {every} = {n} বার দ্বিগুণ: {start} x 2^{n} = {r:,}। ক্ষত দ্রুত পরিষ্কার করে ঢাকো!",
              (start * n * 2, start + n, r // 2))


def cover(squares, total=100):
    r = squares * 100 // total
    return _n(f"A quadrat on a riverbank is divided into {total} small squares. Grass covers {squares} of them. What is the percentage cover?",
              f"নদীর পাড়ের একটা কোয়াড্র্যাট {total}টি ছোট বর্গে ভাগ। {squares}টিতে ঘাস। শতাংশ আচ্ছাদন কত?", r,
              f"{squares} ÷ {total} x 100 = {r}%.",
              f"{squares} ÷ {total} x 100 = {r}%।",
              (100 - r, squares * 2, r + 5), "%")


ITEMS = (
    osmo(5.0, 5.6), osmo(4.0, 3.4), osmo(6.0, 6.3), osmo(8.0, 6.0), osmo(2.5, 3.0),
    transp(30, 10), transp(48, 12), transp(14, 4), transp(50, 20), transp(35, 5),
    doubling(10, 60, 20), doubling(5, 100, 20), doubling(100, 90, 30), doubling(1, 120, 20),
    cover(35), cover(60), cover(18, 25), cover(40, 50),
    mcq("What is the 'central nervous system' (CNS)?", ["The brain and spinal cord", "The heart and lungs", "Only the eyes", "The skeleton"], 0,
        "The CNS processes information and sends out instructions.",
        "'কেন্দ্রীয় স্নায়ুতন্ত্র' (সিএনএস) কী?", ["মস্তিষ্ক আর সুষুম্নাকাণ্ড", "হৃৎপিণ্ড আর ফুসফুস", "শুধু চোখ", "কঙ্কাল"],
        "সিএনএস তথ্য প্রক্রিয়া করে আর নির্দেশ পাঠায়।"),
    mcq("What is the order of a reflex arc?", ["Receptor -> sensory neurone -> relay neurone -> motor neurone -> effector", "Brain -> heart -> muscle", "Muscle -> receptor -> brain", "Eye -> ear -> hand"], 0,
        "Reflexes bypass conscious thought for speed.",
        "প্রতিবর্ত-চাপের ক্রম কী?", ["গ্রাহক -> সংবেদী নিউরন -> সংযোজক নিউরন -> চেষ্টীয় নিউরন -> কার্যকারক", "মস্তিষ্ক -> হৃৎপিণ্ড -> পেশি", "পেশি -> গ্রাহক -> মস্তিষ্ক", "চোখ -> কান -> হাত"],
        "দ্রুততার জন্য প্রতিবর্ত সচেতন চিন্তা এড়িয়ে যায়।"),
    mcq("What is a 'synapse'?", ["A tiny gap between neurones where chemicals carry the signal across", "A bone joint", "A blood vessel", "A muscle fibre"], 0,
        "Some drugs work by affecting synapses.",
        "'সাইন্যাপ্স' কী?", ["নিউরনের মাঝে ছোট্ট ফাঁক, যেখানে রাসায়নিক সংকেত পার করায়", "হাড়ের সন্ধি", "রক্তনালী", "পেশিতন্তু"],
        "কিছু ওষুধ সাইন্যাপ্সে প্রভাব ফেলে কাজ করে।"),
    mcq("How do hormones differ from nerve signals?", ["Hormones travel in blood and act more slowly but for longer", "Hormones are faster", "Hormones travel along nerves", "They are the same"], 0,
        "Nerves are like phone calls; hormones like posted letters.",
        "হরমোন স্নায়ু-সংকেত থেকে কীভাবে আলাদা?", ["হরমোন রক্তে চলে আর ধীরে কিন্তু বেশিক্ষণ কাজ করে", "হরমোন দ্রুত", "হরমোন স্নায়ু ধরে চলে", "দুটো একই"],
        "স্নায়ু ফোনকলের মতো; হরমোন ডাকে পাঠানো চিঠির মতো।"),
    mcq("Which gland is called the 'master gland'?", ["The pituitary gland", "The thyroid", "The pancreas", "The adrenal gland"], 0,
        "It controls many other glands.",
        "কোন গ্রন্থিকে 'প্রধান গ্রন্থি' বলে?", ["পিটুইটারি গ্রন্থি", "থাইরয়েড", "অগ্ন্যাশয়", "অ্যাড্রিনাল গ্রন্থি"],
        "এটা অন্য অনেক গ্রন্থি নিয়ন্ত্রণ করে।"),
    mcq("What does the thyroid hormone thyroxine control?", ["The body's metabolic rate", "Eye colour", "Bone count", "Blood type"], 0,
        "Iodised salt helps the thyroid make thyroxine.",
        "থাইরয়েড হরমোন থাইরক্সিন কী নিয়ন্ত্রণ করে?", ["শরীরের বিপাকের হার", "চোখের রং", "হাড়ের সংখ্যা", "রক্তের গ্রুপ"],
        "আয়োডিনযুক্ত লবণ থাইরয়েডকে থাইরক্সিন তৈরিতে সাহায্য করে।"),
    mcq("What is 'phototropism'?", ["A plant growing towards light", "A plant growing in the dark", "A plant making photos", "Roots growing upwards"], 0,
        "Auxin hormone builds up on the shaded side, making it grow faster.",
        "'আলোকবৃত্তি' কী?", ["আলোর দিকে গাছের বেড়ে ওঠা", "অন্ধকারে গাছের বাড়া", "গাছের ছবি তোলা", "শিকড়ের উপরে বাড়া"],
        "অক্সিন হরমোন ছায়ার দিকে জমে সেদিকে দ্রুত বাড়ায়।"),
    mcq("What is 'gravitropism' in roots?", ["Roots growing downwards with gravity", "Roots growing towards light", "Roots growing sideways only", "Roots not growing"], 0,
        "Roots anchor plants - like piles anchor bridges.",
        "শিকড়ের 'অভিকর্ষবৃত্তি' কী?", ["মাধ্যাকর্ষণ মেনে শিকড়ের নিচে বাড়া", "আলোর দিকে শিকড়ের বাড়া", "শুধু পাশে বাড়া", "না বাড়া"],
        "শিকড় গাছকে আটকে রাখে - পাইল যেমন সেতুকে।"),
    mcq("What is 'auxin'?", ["A plant hormone that controls growth", "A type of fertiliser only", "A disease", "An animal hormone"], 0,
        "Rooting powders use auxin to help cuttings grow roots.",
        "'অক্সিন' কী?", ["বৃদ্ধি নিয়ন্ত্রণকারী উদ্ভিদ-হরমোন", "শুধু এক রকম সার", "একটা রোগ", "প্রাণীর হরমোন"],
        "শিকড়-গজানো গুঁড়ো ডালে শিকড় গজাতে অক্সিন ব্যবহার করে।"),
    mcq("What increases the rate of transpiration?", ["Higher temperature, more light, more wind and lower humidity", "Cold, still, humid air", "Darkness", "Less light only"], 0,
        "Hot windy days dry plants - and workers - out fastest.",
        "কী প্রস্বেদনের হার বাড়ায়?", ["বেশি তাপমাত্রা, বেশি আলো, বেশি বাতাস আর কম আর্দ্রতা", "ঠান্ডা, স্থির, আর্দ্র বাতাস", "অন্ধকার", "শুধু কম আলো"],
        "গরম ঝোড়ো দিনে গাছ - আর কর্মীরা - দ্রুততম শুকোয়।"),
    mcq("What does a potometer measure?", ["The rate a plant shoot takes up water", "Air pressure", "Soil acidity", "Plant height"], 0,
        "Water uptake is close to the rate of transpiration.",
        "পোটোমিটার কী মাপে?", ["গাছের ডাল কত দ্রুত জল নেয়", "বায়ুর চাপ", "মাটির অম্লতা", "গাছের উচ্চতা"],
        "জল নেওয়ার হার প্রস্বেদনের হারের কাছাকাছি।"),
    mcq("What is the word equation for anaerobic respiration in yeast?", ["glucose -> ethanol + carbon dioxide (+ energy)", "glucose + oxygen -> water", "ethanol -> glucose", "oxygen -> carbon dioxide"], 0,
        "This fermentation makes bread rise.",
        "ইস্টের অবাত শ্বসনের শব্দ-সমীকরণ কী?", ["গ্লুকোজ -> ইথানল + কার্বন ডাই-অক্সাইড (+ শক্তি)", "গ্লুকোজ + অক্সিজেন -> জল", "ইথানল -> গ্লুকোজ", "অক্সিজেন -> কার্বন ডাই-অক্সাইড"],
        "এই সন্ধান (ফারমেন্টেশন) রুটি ফোলায়।"),
    mcq("What does anaerobic respiration in human muscles produce?", ["Lactic acid", "Ethanol", "Oxygen", "Starch"], 0,
        "It releases less energy than aerobic respiration.",
        "মানুষের পেশিতে অবাত শ্বসনে কী তৈরি হয়?", ["ল্যাকটিক অ্যাসিড", "ইথানল", "অক্সিজেন", "শ্বেতসার"],
        "সবাত শ্বসনের চেয়ে কম শক্তি দেয়।"),
    mcq("Which releases more energy per glucose molecule?", ["Aerobic respiration", "Anaerobic respiration", "They are equal", "Neither releases energy"], 0,
        "Aerobic respiration releases about 19 times more.",
        "প্রতি গ্লুকোজ-অণুতে কোনটা বেশি শক্তি দেয়?", ["সবাত শ্বসন", "অবাত শ্বসন", "সমান", "কোনোটাই শক্তি দেয় না"],
        "সবাত শ্বসন প্রায় 19 গুণ বেশি দেয়।"),
    mcq("What is 'metabolism'?", ["All the chemical reactions happening in the body", "Only digestion", "Only breathing", "Growing hair"], 0,
        "It includes building molecules and breaking them down.",
        "'বিপাক' কী?", ["শরীরে ঘটা সব রাসায়নিক বিক্রিয়া", "শুধু পরিপাক", "শুধু শ্বাস নেওয়া", "চুল গজানো"],
        "এতে অণু গড়া আর ভাঙা দুটোই আছে।"),
    mcq("How does nitrogen from the air get into plants?", ["Nitrogen-fixing bacteria in soil and root nodules turn it into nitrates", "Leaves breathe it in directly", "Rain only", "It never does"], 0,
        "Peas, beans and dal plants have root nodules.",
        "বাতাসের নাইট্রোজেন কীভাবে গাছে ঢোকে?", ["মাটি আর মূল-অর্বুদের নাইট্রোজেন-সংবন্ধক ব্যাকটেরিয়া তাকে নাইট্রেটে বদলায়", "পাতা সরাসরি শ্বাসে নেয়", "শুধু বৃষ্টিতে", "কখনো ঢোকে না"],
        "মটর, শিম আর ডালজাতীয় গাছের মূল-অর্বুদ থাকে।"),
    mcq("Why do plants need nitrates?", ["To make proteins for growth", "To make sugar", "To make bones", "For colour only"], 0,
        "Fertilisers add nitrates - but too much runs into rivers.",
        "গাছের নাইট্রেট লাগে কেন?", ["বৃদ্ধির জন্য প্রোটিন তৈরি করতে", "চিনি বানাতে", "হাড় বানাতে", "শুধু রঙের জন্য"],
        "সার নাইট্রেট যোগ করে - তবে বেশি হলে নদীতে মেশে।"),
    mcq("What do decomposers return to the soil?", ["Minerals and nutrients from dead material", "Plastic", "Oxygen only", "Metal"], 0,
        "Warm, moist, oxygen-rich conditions speed decay.",
        "বিয়োজক মাটিতে কী ফেরায়?", ["মরা উপাদান থেকে খনিজ আর পুষ্টি", "প্লাস্টিক", "শুধু অক্সিজেন", "ধাতু"],
        "উষ্ণ, ভেজা, অক্সিজেন-ভরা পরিবেশে পচন দ্রুত হয়।"),
    mcq("Why does timber rot fastest where it touches wet soil?", ["Moisture, warmth and oxygen there suit fungi and bacteria", "Soil is magnetic", "Wood is hungry", "It rots slowest there"], 0,
        "Timber bridges keep wood off the ground on stone or steel footings.",
        "মাটির সংস্পর্শে থাকা কাঠ দ্রুততম পচে কেন?", ["সেখানের আর্দ্রতা, উষ্ণতা আর অক্সিজেন ছত্রাক-ব্যাকটেরিয়ার অনুকূল", "মাটি চুম্বকীয়", "কাঠের খিদে পায়", "সেখানে সবচেয়ে ধীরে পচে"],
        "কাঠের সেতু কাঠকে পাথর বা ইস্পাতের পাদভিত্তিতে মাটি থেকে উঁচু রাখে।"),
    mcq("What is 'habitat fragmentation'?", ["Breaking a habitat into small separate patches, e.g. by roads", "Planting more trees", "Cleaning rivers", "Growing a habitat bigger"], 0,
        "Small patches support fewer species.",
        "'বাসস্থান-খণ্ডন' কী?", ["বাসস্থানকে ছোট বিচ্ছিন্ন টুকরোয় ভাঙা, যেমন রাস্তা দিয়ে", "আরও গাছ লাগানো", "নদী পরিষ্কার", "বাসস্থান বড় করা"],
        "ছোট টুকরোয় কম প্রজাতি টেকে।"),
    mcq("How can an elevated bridge or viaduct help wildlife compared with a road on an embankment?", ["Animals can still pass underneath, keeping habitats connected", "It blocks animals completely", "It feeds animals", "It has no effect"], 0,
        "Some highways through tiger reserves are raised for this reason.",
        "বাঁধের উপরের রাস্তার তুলনায় উঁচু সেতু বা ভায়াডাক্ট বন্যপ্রাণীর কীভাবে সাহায্য করে?", ["প্রাণীরা তখনো নিচ দিয়ে যেতে পারে, বাসস্থান জোড়া থাকে", "প্রাণীদের পুরো আটকায়", "প্রাণীদের খাওয়ায়", "প্রভাব নেই"],
        "এই কারণে বাঘ-সংরক্ষিত বনের মধ্য দিয়ে কিছু মহাসড়ক উঁচু করা হয়েছে।"),
    mcq("What is 'continuous variation'?", ["Differences with a range of values, like height", "Differences with only a few groups, like blood type", "No differences", "Changes during one day"], 0,
        "Usually caused by many genes and the environment.",
        "'অবিচ্ছিন্ন প্রকরণ' কী?", ["মানের একটা পরিসরজুড়ে পার্থক্য, যেমন উচ্চতা", "মাত্র কয়েকটা দলের পার্থক্য, যেমন রক্তের গ্রুপ", "কোনো পার্থক্য নেই", "এক দিনের মধ্যে পরিবর্তন"],
        "সাধারণত বহু জিন আর পরিবেশের কারণে।"),
    mcq("Which is an example of discontinuous variation?", ["Blood group", "Height", "Weight", "Hand span"], 0,
        "You are A, B, AB or O - nothing in between.",
        "কোনটা বিচ্ছিন্ন প্রকরণের উদাহরণ?", ["রক্তের গ্রুপ", "উচ্চতা", "ওজন", "হাতের বিঘত"],
        "তুমি A, B, AB বা O - মাঝামাঝি কিছু নয়।"),
    mcq("What is 'genetic engineering'?", ["Changing an organism's genes, often by adding a gene from another organism", "Building machines from genes", "Breeding animals normally", "Repairing bridges"], 0,
        "Bacteria are engineered to make human insulin.",
        "'জিন-প্রকৌশল' কী?", ["জীবের জিন বদলানো, প্রায়ই অন্য জীবের জিন যোগ করে", "জিন দিয়ে যন্ত্র বানানো", "সাধারণভাবে প্রাণী প্রজনন", "সেতু মেরামত"],
        "মানুষের ইনসুলিন তৈরিতে ব্যাকটেরিয়াকে প্রকৌশলিত করা হয়।"),
    mcq("What is a 'clone'?", ["An organism genetically identical to its parent", "A robot", "A twin from different parents", "A type of seed"], 0,
        "Plant cuttings are natural clones.",
        "'ক্লোন' কী?", ["বাবা-মায়ের সঙ্গে জিনগতভাবে অভিন্ন জীব", "রোবট", "আলাদা বাবা-মায়ের যমজ", "এক রকম বীজ"],
        "গাছের ডাল কেটে লাগানো প্রাকৃতিক ক্লোন।"),
    mcq("Why are new medicines tested in 'clinical trials'?", ["To check they are safe and work before wide use", "To make them cheaper", "To change their colour", "It is not needed"], 0,
        "Trials use careful steps and often a placebo for comparison.",
        "নতুন ওষুধ 'ক্লিনিক্যাল ট্রায়ালে' পরীক্ষা হয় কেন?", ["ব্যাপক ব্যবহারের আগে নিরাপদ আর কার্যকর কিনা যাচাই করতে", "সস্তা করতে", "রং বদলাতে", "দরকার নেই"],
        "পরীক্ষায় সাবধানী ধাপ আর তুলনার জন্য প্রায়ই প্লাসিবো থাকে।"),
    mcq("What is a 'placebo'?", ["A dummy treatment with no active medicine, used for comparison", "A strong drug", "A vaccine", "A type of food"], 0,
        "It helps show whether the real medicine truly works.",
        "'প্লাসিবো' কী?", ["তুলনার জন্য সক্রিয় ওষুধহীন নকল চিকিৎসা", "শক্তিশালী ওষুধ", "টিকা", "এক রকম খাবার"],
        "আসল ওষুধ সত্যিই কাজ করে কিনা তা দেখাতে সাহায্য করে।"),
    mcq("What is a 'communicable disease'?", ["One that can spread from person to person", "One caused only by diet", "A broken bone", "An inherited disease only"], 0,
        "Flu, TB and cholera are communicable; heart disease is not.",
        "'সংক্রামক রোগ' কী?", ["যা মানুষ থেকে মানুষে ছড়াতে পারে", "শুধু খাদ্যাভ্যাসে হওয়া রোগ", "হাড় ভাঙা", "শুধু বংশগত রোগ"],
        "ফ্লু, যক্ষ্মা আর কলেরা সংক্রামক; হৃদ্‌রোগ নয়।"),
    mcq("Which is a risk factor for non-communicable diseases like heart disease?", ["Smoking, poor diet and lack of exercise", "Shaking hands", "Sharing books", "Wearing helmets"], 0,
        "Healthy habits cut the risk a lot.",
        "হৃদ্‌রোগের মতো অসংক্রামক রোগের ঝুঁকির উপাদান কোনটা?", ["ধূমপান, খারাপ খাদ্য আর ব্যায়ামের অভাব", "করমর্দন", "বই ভাগ করা", "হেলমেট পরা"],
        "স্বাস্থ্যকর অভ্যাস ঝুঁকি অনেক কমায়।"),
    mcq("How do plants defend themselves against pests?", ["Thick bark, waxy leaves, thorns and poisonous chemicals", "By running away", "With white blood cells", "They cannot"], 0,
        "Some timber is naturally rot- and insect-resistant, like teak.",
        "গাছ পোকামাকড় থেকে নিজেদের কীভাবে রক্ষা করে?", ["মোটা বাকল, মোমের মতো পাতা, কাঁটা আর বিষাক্ত রাসায়নিক", "দৌড়ে পালিয়ে", "শ্বেত রক্তকণিকা দিয়ে", "পারে না"],
        "সেগুনের মতো কিছু কাঠ স্বাভাবিকভাবেই পচন- আর পোকা-রোধী।"),
    mcq("What sound level, over a long time, can start to damage hearing?", ["Above about 85 decibels", "Above 10 decibels", "Only above 500 decibels", "Sound never damages hearing"], 0,
        "Jackhammers can exceed 100 dB - always wear ear protection.",
        "দীর্ঘ সময় কত মাত্রার শব্দ শ্রবণশক্তির ক্ষতি শুরু করতে পারে?", ["প্রায় 85 ডেসিবেলের বেশি", "10 ডেসিবেলের বেশি", "শুধু 500 ডেসিবেলের বেশি", "শব্দ কখনো ক্ষতি করে না"],
        "জ্যাকহ্যামার 100 dB ছাড়াতে পারে - সবসময় কান-রক্ষাকারী পরো।"),
    mcq("What is 'ergonomics'?", ["Designing work and tools to fit the human body and avoid injury", "A type of exercise", "A computer game", "A building material"], 0,
        "Good tool handles and lifting aids prevent back and wrist injuries.",
        "'শ্রমদক্ষতাবিদ্যা' (এরগোনমিক্স) কী?", ["আঘাত এড়াতে মানুষের শরীরের উপযোগী কাজ আর যন্ত্রের নকশা", "এক রকম ব্যায়াম", "কম্পিউটার গেম", "নির্মাণ-উপাদান"],
        "ভালো যন্ত্রের হাতল আর তোলার সহায়ক পিঠ আর কবজির আঘাত ঠেকায়।"),
    mcq("Why can using vibrating tools for hours cause 'white finger'?", ["Vibration damages nerves and blood vessels in the hands", "The tools are cold", "Paint gets on fingers", "It does not"], 0,
        "Limit exposure time and use anti-vibration gloves and tools.",
        "ঘণ্টার পর ঘণ্টা কম্পিত যন্ত্র ব্যবহারে 'সাদা আঙুল' রোগ হতে পারে কেন?", ["কম্পন হাতের স্নায়ু আর রক্তনালীর ক্ষতি করে", "যন্ত্র ঠান্ডা", "আঙুলে রং লাগে", "হয় না"],
        "সময় সীমিত রাখো আর কম্পন-রোধী দস্তানা ও যন্ত্র ব্যবহার করো।"),
    mcq("How does the body cool down on a hot site?", ["Sweating and widening blood vessels near the skin", "Shivering", "Narrowing blood vessels", "Stopping breathing"], 0,
        "Drink water often so you can keep sweating.",
        "গরম নির্মাণস্থলে শরীর কীভাবে ঠান্ডা হয়?", ["ঘাম আর ত্বকের কাছের রক্তনালী প্রসারিত করে", "কাঁপুনিতে", "রক্তনালী সরু করে", "শ্বাস থামিয়ে"],
        "যাতে ঘাম চালিয়ে যেতে পারো, তাই প্রায়ই জল খাও।"),
    mcq("What is a 'balanced ecosystem'?", ["One where populations stay fairly steady over time", "One with only one species", "One with no predators", "A frozen lake"], 0,
        "Predators, prey and plants keep each other in check.",
        "'ভারসাম্যপূর্ণ বাস্তুতন্ত্র' কী?", ["যেখানে সময়ের সঙ্গে জনসংখ্যা মোটামুটি স্থির থাকে", "যেখানে একটাই প্রজাতি", "যেখানে শিকারি নেই", "জমা হ্রদ"],
        "শিকারি, শিকার আর উদ্ভিদ পরস্পরকে নিয়ন্ত্রণে রাখে।"),
    mcq("What happens to prey numbers if predators are removed?", ["Prey numbers rise, then may crash when food runs out", "They fall immediately", "Nothing", "They become predators"], 0,
        "Ecosystems are interlinked like members of a truss.",
        "শিকারি সরিয়ে দিলে শিকারের সংখ্যার কী হয়?", ["সংখ্যা বাড়ে, তারপর খাবার ফুরোলে ভেঙে পড়তে পারে", "সঙ্গে সঙ্গে কমে", "কিছুই না", "তারা শিকারি হয়ে যায়"],
        "বাস্তুতন্ত্র ট্রাসের অংশগুলোর মতো পরস্পর জোড়া।"),
    mcq("What is an 'invasive species'?", ["A non-native species that spreads and harms local ecosystems", "A native rare plant", "A pet", "An extinct animal"], 0,
        "Water hyacinth clogs rivers and can block boats under bridges.",
        "'আগ্রাসী প্রজাতি' কী?", ["অ-স্থানীয় প্রজাতি, যা ছড়িয়ে স্থানীয় বাস্তুতন্ত্রের ক্ষতি করে", "স্থানীয় দুর্লভ উদ্ভিদ", "পোষা প্রাণী", "বিলুপ্ত প্রাণী"],
        "কচুরিপানা নদী আটকায় আর সেতুর নিচে নৌকা আটকাতে পারে।"),
    mcq("Why is water hyacinth a problem near bridges and ferries?", ["It forms thick mats that block channels and reduce oxygen", "It strengthens bridges", "It cleans water perfectly", "It is not a problem"], 0,
        "Regular clearing keeps waterways open.",
        "সেতু আর খেয়ার কাছে কচুরিপানা সমস্যা কেন?", ["ঘন আস্তরণ তৈরি করে প্রবাহপথ আটকায় আর অক্সিজেন কমায়", "সেতু মজবুত করে", "জল নিখুঁত পরিষ্কার করে", "সমস্যা নয়"],
        "নিয়মিত পরিষ্কারে জলপথ খোলা থাকে।"),
    mcq("What is 'biological control'?", ["Using a natural predator or disease to control a pest", "Spraying chemicals", "Building fences", "Burning crops"], 0,
        "It can reduce pesticide use but must be tested carefully.",
        "'জৈব নিয়ন্ত্রণ' কী?", ["পোকা নিয়ন্ত্রণে প্রাকৃতিক শিকারি বা রোগ ব্যবহার", "রাসায়নিক ছেটানো", "বেড়া দেওয়া", "ফসল পোড়ানো"],
        "কীটনাশক কমাতে পারে, তবে সাবধানে পরীক্ষা করতে হয়।"),
    mcq("What evidence supports evolution?", ["Fossils, similar body structures and DNA comparisons", "Only stories", "Weather records", "Bridge designs"], 0,
        "Antibiotic-resistant bacteria show evolution happening now.",
        "কোন প্রমাণ বিবর্তনকে সমর্থন করে?", ["জীবাশ্ম, একই রকম দেহগঠন আর ডিএনএ তুলনা", "শুধু গল্প", "আবহাওয়ার হিসাব", "সেতুর নকশা"],
        "অ্যান্টিবায়োটিক-প্রতিরোধী ব্যাকটেরিয়া এখনই বিবর্তন দেখায়।"),
    mcq("What do the ridges on your fingertips and the tread on tyres have in common?", ["Both increase grip by channelling water and adding friction", "Both are decorative", "Both store fat", "Nothing"], 0,
        "Nature and engineering often solve problems the same way.",
        "আঙুলের ডগার রেখা আর টায়ারের খাঁজে মিল কী?", ["দুটোই জল সরিয়ে আর ঘর্ষণ বাড়িয়ে আঁকড় বাড়ায়", "দুটোই সাজসজ্জা", "দুটোই চর্বি জমায়", "কিছুই না"],
        "প্রকৃতি আর প্রকৌশল প্রায়ই একইভাবে সমস্যার সমাধান করে।"),
    mcq("What is the 'blind spot' in the eye?", ["Where the optic nerve leaves - there are no light receptors there", "A dirty part of the lens", "Where eyelashes are", "A tear duct"], 0,
        "Drivers also have 'blind spots' around trucks - check mirrors carefully.",
        "চোখের 'অন্ধবিন্দু' কী?", ["যেখান দিয়ে দৃষ্টি-স্নায়ু বেরোয় - সেখানে আলো-গ্রাহক নেই", "লেন্সের নোংরা অংশ", "যেখানে চোখের পাতার লোম", "অশ্রুনালী"],
        "ট্রাকের চারপাশে চালকদেরও 'অন্ধ জায়গা' থাকে - আয়না ভালো করে দেখো।"),
    mcq("Why are banksmen (signallers) used when trucks reverse on site?", ["Drivers cannot see behind the truck - someone guides them safely", "To collect tolls", "To count bricks", "No reason"], 0,
        "Reversing vehicles cause many site accidents.",
        "নির্মাণস্থলে ট্রাক পেছোনোর সময় সংকেতদাতা রাখা হয় কেন?", ["চালক ট্রাকের পেছনে দেখতে পান না - কেউ নিরাপদে পথ দেখান", "টোল তুলতে", "ইট গুনতে", "কোনো কারণ নেই"],
        "পেছোনো যান নির্মাণস্থলের অনেক দুর্ঘটনা ঘটায়।"),
    osmo(10.0, 9.0), osmo(3.0, 3.6), osmo(7.5, 6.0), osmo(4.0, 4.2),
    transp(60, 8), transp(27, 9), transp(21, 14),
    doubling(20, 80, 20), doubling(3, 150, 30), doubling(50, 40, 10),
    cover(72), cover(9, 20), cover(45, 60),
    mcq("The dodo can never return. What word describes its species?", ["Extinct", "Endangered", "Invasive", "Hibernating"], 0,
        "Extinct means no living members remain anywhere.",
        "ডোডো আর কখনো ফিরবে না। তার প্রজাতিকে কোন শব্দে বোঝায়?", ["বিলুপ্ত", "বিপন্ন", "আগ্রাসী", "শীতঘুমে"],
        "বিলুপ্ত মানে কোথাও কোনো জীবিত সদস্য নেই।"),
    mcq("What is a 'neurone'?", ["A nerve cell that carries electrical signals", "A muscle cell", "A bone cell", "A blood cell"], 0,
        "Neurones can be over 1 m long.",
        "'নিউরন' কী?", ["বৈদ্যুতিক সংকেত বয় এমন স্নায়ুকোষ", "পেশিকোষ", "অস্থিকোষ", "রক্তকণিকা"],
        "নিউরন 1 m-এর বেশি লম্বা হতে পারে।"),
    mcq("What is the job of a 'receptor'?", ["To detect a stimulus such as light, heat or pressure", "To pump blood", "To digest food", "To store fat"], 0,
        "Eyes, ears and skin contain receptors.",
        "'গ্রাহক' (রিসেপ্টর)-এর কাজ কী?", ["আলো, তাপ বা চাপের মতো উদ্দীপনা শনাক্ত করা", "রক্ত পাম্প", "খাবার হজম", "চর্বি জমানো"],
        "চোখ, কান আর ত্বকে গ্রাহক থাকে।"),
    mcq("What is an 'effector'?", ["A muscle or gland that responds to a nerve signal", "A sense organ", "A type of bone", "A hormone"], 0,
        "Muscles contract; glands release chemicals.",
        "'কার্যকারক' (এফেক্টর) কী?", ["স্নায়ু-সংকেতে সাড়া দেওয়া পেশি বা গ্রন্থি", "ইন্দ্রিয়-অঙ্গ", "এক রকম হাড়", "হরমোন"],
        "পেশি সংকুচিত হয়; গ্রন্থি রাসায়নিক ছাড়ে।"),
    mcq("How can you measure reaction time simply?", ["Catch a dropped ruler - the further it falls, the slower your reaction", "With a thermometer", "By counting heartbeats", "With a compass"], 0,
        "Tiredness and distractions make reaction times longer.",
        "সহজে প্রতিক্রিয়ার সময় কীভাবে মাপবে?", ["পড়ন্ত রুলার ধরো - যত দূর পড়ে, প্রতিক্রিয়া তত ধীর", "থার্মোমিটার দিয়ে", "হৃৎস্পন্দন গুনে", "কম্পাস দিয়ে"],
        "ক্লান্তি আর অমনোযোগ প্রতিক্রিয়ার সময় বাড়ায়।"),
    mcq("Why must crane operators never use a phone while lifting?", ["Distraction slows reactions and can cause deadly accidents", "Phones are heavy", "It drains the crane battery", "It is fine"], 0,
        "Full attention is a safety rule.",
        "ক্রেন-চালকদের তোলার সময় কখনো ফোন ব্যবহার করা উচিত নয় কেন?", ["অমনোযোগ প্রতিক্রিয়া ধীর করে প্রাণঘাতী দুর্ঘটনা ঘটাতে পারে", "ফোন ভারী", "ক্রেনের ব্যাটারি ফুরোয়", "ঠিক আছে"],
        "পূর্ণ মনোযোগ একটা নিরাপত্তার নিয়ম।"),
    mcq("What does insulin do and where is it made?", ["Lowers blood glucose; made in the pancreas", "Raises blood pressure; made in the heart", "Digests fat; made in the liver", "Carries oxygen; made in bones"], 0,
        "Glucagon from the pancreas raises blood glucose.",
        "ইনসুলিন কী করে আর কোথায় তৈরি হয়?", ["রক্তের গ্লুকোজ কমায়; অগ্ন্যাশয়ে তৈরি", "রক্তচাপ বাড়ায়; হৃৎপিণ্ডে তৈরি", "চর্বি হজম করে; যকৃতে তৈরি", "অক্সিজেন বয়; হাড়ে তৈরি"],
        "অগ্ন্যাশয়ের গ্লুকাগন রক্তের গ্লুকোজ বাড়ায়।"),
    mcq("What is 'type 2 diabetes' linked to?", ["Obesity, little exercise and poor diet", "Catching a cold", "Broken bones", "Too much sleep only"], 0,
        "It can often be managed with diet and exercise.",
        "'টাইপ 2 ডায়াবেটিস' কীসের সঙ্গে যুক্ত?", ["স্থূলতা, কম ব্যায়াম আর খারাপ খাদ্য", "সর্দি লাগা", "হাড় ভাঙা", "শুধু বেশি ঘুম"],
        "প্রায়ই খাদ্য আর ব্যায়ামে নিয়ন্ত্রণ করা যায়।"),
    mcq("What do the kidneys control in homeostasis?", ["Water and salt levels in the blood", "Body temperature only", "Eye focus", "Hair growth"], 0,
        "ADH hormone tells kidneys to save water when you are dehydrated.",
        "সমস্থিতিতে বৃক্ক কী নিয়ন্ত্রণ করে?", ["রক্তে জল আর লবণের মাত্রা", "শুধু শরীরের তাপমাত্রা", "চোখের ফোকাস", "চুলের বৃদ্ধি"],
        "জলশূন্য হলে এডিএইচ হরমোন বৃক্ককে জল বাঁচাতে বলে।"),
    mcq("Why is dark yellow urine a warning sign on a hot site?", ["It suggests dehydration - drink more water", "It means you are very healthy", "It means too much water", "It has no meaning"], 0,
        "Pale straw colour is a good sign.",
        "গরম নির্মাণস্থলে গাঢ় হলুদ মূত্র সতর্কসংকেত কেন?", ["জলশূন্যতা বোঝায় - আরও জল খাও", "মানে তুমি খুব সুস্থ", "মানে বেশি জল", "কোনো অর্থ নেই"],
        "হালকা খড়ের রং ভালো লক্ষণ।"),
    mcq("What is 'vasoconstriction'?", ["Blood vessels near the skin narrowing to save heat in the cold", "Vessels widening in heat", "A broken vessel", "A heart valve"], 0,
        "Fingers go pale in the cold for this reason.",
        "'রক্তনালী-সংকোচন' কী?", ["ঠান্ডায় তাপ বাঁচাতে ত্বকের কাছের রক্তনালী সরু হওয়া", "গরমে নালী চওড়া হওয়া", "ভাঙা নালী", "হৃৎকপাটিকা"],
        "এই কারণে ঠান্ডায় আঙুল ফ্যাকাশে হয়।"),
    mcq("How do root nodules help farmers?", ["Bacteria in them add nitrogen to soil, reducing fertiliser needs", "They store water for bridges", "They attract pests", "They do nothing"], 0,
        "Crop rotation with pulses improves soil.",
        "মূল-অর্বুদ চাষিদের কীভাবে সাহায্য করে?", ["এদের ব্যাকটেরিয়া মাটিতে নাইট্রোজেন যোগ করে, সারের দরকার কমায়", "সেতুর জন্য জল জমায়", "পোকা টানে", "কিছুই করে না"],
        "ডালশস্যসহ শস্যাবর্তন মাটি উন্নত করে।"),
    mcq("What is 'deforestation' doing to rivers near bridges?", ["More soil washes in, silting rivers and raising flood risk", "Making rivers cleaner", "Nothing", "Lowering water forever"], 0,
        "Silt can bury piers and reduce clearance under bridges.",
        "বন উজাড় সেতুর কাছের নদীর কী করছে?", ["বেশি মাটি ধুয়ে নদীতে পলি জমে আর বন্যার ঝুঁকি বাড়ে", "নদী পরিষ্কার করছে", "কিছুই না", "চিরকাল জল কমাচ্ছে"],
        "পলি থাম চাপা দিতে আর সেতুর নিচের ফাঁক কমাতে পারে।"),
    mcq("What is a 'buffer zone' of plants along a river?", ["A strip of vegetation that filters runoff and protects banks", "A car park", "A concrete wall", "A fishing net"], 0,
        "Bridge projects often replant buffer zones after works.",
        "নদীর ধারে উদ্ভিদের 'প্রতিরোধী অঞ্চল' (বাফার জোন) কী?", ["উদ্ভিদের একটা ফালি, যা ভেসে আসা জল ছাঁকে আর পাড় রক্ষা করে", "গাড়ি রাখার জায়গা", "কংক্রিটের দেওয়াল", "মাছ ধরার জাল"],
        "কাজের পরে সেতু-প্রকল্প প্রায়ই প্রতিরোধী অঞ্চলে আবার গাছ লাগায়।"),
    mcq("What is 'mutualism'?", ["A relationship where both species benefit", "One species harms the other", "Both species are harmed", "Living alone"], 0,
        "Root fungi (mycorrhizae) help trees take in water and minerals.",
        "'পারস্পরিক উপকারিতা' কী?", ["যে সম্পর্কে দুই প্রজাতিই উপকৃত", "এক প্রজাতি অন্যের ক্ষতি করে", "দুই প্রজাতিই ক্ষতিগ্রস্ত", "একা থাকা"],
        "শিকড়-ছত্রাক গাছকে জল আর খনিজ নিতে সাহায্য করে।"),
    mcq("What is 'gene therapy'?", ["Treating disease by replacing or repairing faulty genes", "Exercise therapy", "A type of vaccine only", "Surgery on bones"], 0,
        "It is still being developed for many conditions.",
        "'জিন-চিকিৎসা' কী?", ["ত্রুটিপূর্ণ জিন বদলে বা সারিয়ে রোগের চিকিৎসা", "ব্যায়াম-চিকিৎসা", "শুধু এক রকম টিকা", "হাড়ের অস্ত্রোপচার"],
        "অনেক রোগের জন্য এটা এখনো তৈরি হচ্ছে।"),
    mcq("Why do some people worry about genetically modified (GM) crops?", ["Concerns about effects on wildlife, gene spread and long-term health, which are studied carefully", "GM crops are always poisonous", "They cannot grow", "There are no concerns"], 0,
        "Scientists test them and many countries regulate them.",
        "জিন-পরিবর্তিত (জিএম) ফসল নিয়ে কিছু মানুষ চিন্তিত কেন?", ["বন্যপ্রাণী, জিন ছড়ানো আর দীর্ঘমেয়াদি স্বাস্থ্যে প্রভাব নিয়ে উদ্বেগ, যা সাবধানে গবেষণা হয়", "জিএম ফসল সবসময় বিষাক্ত", "এরা জন্মায় না", "কোনো উদ্বেগ নেই"],
        "বিজ্ঞানীরা পরীক্ষা করেন আর অনেক দেশ নিয়ন্ত্রণ করে।"),
    mcq("What is 'stem cell' research hoping to achieve?", ["Growing new tissue to repair damage from injury or disease", "Growing plant stems", "Making cells smaller", "Stopping cell division"], 0,
        "It raises ethical questions that society debates.",
        "'স্টেম কোষ' গবেষণা কী অর্জনের আশা করে?", ["আঘাত বা রোগের ক্ষতি সারাতে নতুন কলা জন্মানো", "গাছের কাণ্ড জন্মানো", "কোষ ছোট করা", "কোষবিভাজন থামানো"],
        "এটা নৈতিক প্রশ্ন তোলে, যা সমাজ বিতর্ক করে।"),
    mcq("What is 'peer review' in science?", ["Other experts checking research before it is published", "Students marking homework", "A bridge inspection", "A cinema review"], 0,
        "It helps catch mistakes and keeps science trustworthy.",
        "বিজ্ঞানে 'সমকক্ষ পর্যালোচনা' কী?", ["প্রকাশের আগে অন্য বিশেষজ্ঞদের গবেষণা যাচাই", "ছাত্রদের বাড়ির কাজ দেখা", "সেতু পরিদর্শন", "সিনেমার সমালোচনা"],
        "এতে ভুল ধরা পড়ে আর বিজ্ঞান বিশ্বাসযোগ্য থাকে।"),
    mcq("Why do bridge engineers also have their designs independently checked?", ["A second expert can catch errors that could make a bridge unsafe", "To slow the project", "Checking is illegal", "It is never done"], 0,
        "Like peer review in science.",
        "সেতু-প্রকৌশলীরাও নকশা স্বাধীনভাবে যাচাই করান কেন?", ["দ্বিতীয় বিশেষজ্ঞ এমন ভুল ধরতে পারেন যা সেতুকে অনিরাপদ করত", "প্রকল্প ধীর করতে", "যাচাই বেআইনি", "কখনো করা হয় না"],
        "বিজ্ঞানের সমকক্ষ পর্যালোচনার মতো।"),
    mcq("What is a 'hypothesis'?", ["A testable idea or prediction", "A proven law", "A random guess with no test", "A conclusion"], 0,
        "'If I add more ribs, the paper bridge will hold more coins.'",
        "'প্রকল্পনা' (হাইপোথিসিস) কী?", ["পরীক্ষাযোগ্য ধারণা বা পূর্বাভাস", "প্রমাণিত সূত্র", "পরীক্ষাহীন এলোমেলো আন্দাজ", "উপসংহার"],
        "'আরও শিরা যোগ করলে কাগজের সেতু বেশি পয়সা ধরবে।'"),
    mcq("What is a 'control variable' in an experiment?", ["Something kept the same so the test is fair", "The thing you change", "The result you measure", "A mistake"], 0,
        "In a bridge test, the gap and material might be controls.",
        "পরীক্ষায় 'নিয়ন্ত্রিত চলক' কী?", ["পরীক্ষা ন্যায্য রাখতে যা একই রাখা হয়", "যা তুমি বদলাও", "যে ফল মাপো", "একটা ভুল"],
        "সেতুর পরীক্ষায় ফাঁক আর উপাদান নিয়ন্ত্রিত হতে পারে।"),
    mcq("What is the 'independent variable'?", ["The one thing you deliberately change", "The thing you measure", "Things kept the same", "The weather"], 0,
        "The 'dependent variable' is what you measure as a result.",
        "'স্বাধীন চলক' কী?", ["যে একটা জিনিস তুমি ইচ্ছে করে বদলাও", "যা মাপো", "যা একই রাখা হয়", "আবহাওয়া"],
        "'নির্ভরশীল চলক' হলো ফল হিসেবে যা মাপো।"),
    mcq("Why do scientists repeat measurements and calculate a mean?", ["To reduce the effect of random errors", "To make more work", "To change the result", "It is not needed"], 0,
        "Outliers can be spotted and checked.",
        "বিজ্ঞানীরা মাপ বারবার নিয়ে গড় করেন কেন?", ["এলোমেলো ত্রুটির প্রভাব কমাতে", "কাজ বাড়াতে", "ফল বদলাতে", "দরকার নেই"],
        "ব্যতিক্রমী মান চিহ্নিত করে যাচাই করা যায়।"),
    mcq("Why should workers wash hands before eating on a site where lead paint is being removed?", ["Lead dust is poisonous if swallowed", "Lead is tasty", "To keep paint", "It is not needed"], 0,
        "Old bridges may have lead-based paint that needs special handling.",
        "যে নির্মাণস্থলে সিসাযুক্ত রং তোলা হচ্ছে সেখানে খাওয়ার আগে কর্মীদের হাত ধোয়া উচিত কেন?", ["সিসার ধুলো গিলে ফেললে বিষাক্ত", "সিসা সুস্বাদু", "রং রাখতে", "দরকার নেই"],
        "পুরোনো সেতুতে সিসাভিত্তিক রং থাকতে পারে, যা বিশেষ যত্নে সামলাতে হয়।"),
    mcq("What is the 'dependent variable' in an experiment?", ["The result you measure", "The thing you change on purpose", "Things kept the same", "The equipment"], 0,
        "In a paper-bridge test, the number of coins held is the dependent variable.",
        "পরীক্ষায় 'নির্ভরশীল চলক' কী?", ["যে ফল তুমি মাপো", "যা ইচ্ছে করে বদলাও", "যা একই রাখা হয়", "যন্ত্রপাতি"],
        "কাগজের সেতুর পরীক্ষায় ধরে রাখা পয়সার সংখ্যা নির্ভরশীল চলক।"),
)
