"""Class 8 - Biology (Junior Cadet): genetic crosses with Punnett squares, mark-recapture counts,
energy transfer between trophic levels, herd immunity, cell division, DNA and proteins, natural
selection and antibiotic resistance, vaccines, photosynthesis rate and light, pulse rates, and
worker health on bridge sites - dust, asbestos, lifting, first aid and fatigue."""
from . import mcq


def _o(r, *alts):
    out = []
    for x in (r, *alts, r + 1, r + 2, r * 2, r + 10):
        if x not in out and x > 0:
            out.append(x)
    return out[:4]


def _n(q_en, q_bn, r, ex_en, ex_bn, alts, u_en="", u_bn=None):
    f = lambda x: f"{x:,}" if isinstance(x, int) else f"{x:g}"
    o = _o(r, *alts)
    ub = u_en if u_bn is None else u_bn
    return mcq(q_en, [f(x) + u_en for x in o], 0, ex_en, q_bn, [f(x) + ub for x in o], ex_bn)


def _c(x):
    x = round(x, 1)
    return int(x) if x == int(x) else x


def lincoln(first, second, marked, what_en, what_bn):
    n = first * second // marked
    return _n(f"Ecologists study {what_en} near a new bridge. They catch and mark {first}, release them, then catch {second}, of which {marked} are marked. Estimate the population.",
              f"পরিবেশবিদরা নতুন সেতুর কাছে {what_bn} নিয়ে গবেষণা করছেন। {first}টি ধরে চিহ্ন দিয়ে ছেড়ে দিলেন, তারপর {second}টি ধরলেন, যার {marked}টি চিহ্নিত। মোট সংখ্যা আন্দাজ করো।", n,
              f"Population ≈ first catch x second catch ÷ marked recaptured = {first} x {second} ÷ {marked} = {n:,}.",
              f"মোট ≈ প্রথম ধরা x দ্বিতীয় ধরা ÷ আবার-ধরা চিহ্নিত = {first} x {second} ÷ {marked} = {n:,}।",
              (first + second, first * marked // second if first * marked >= second else n + 15, first + second - marked))


CROSS = {
    ("Aa", "Aa"): (25, "1 in 4: AA, Aa, Aa, aa", "৪-এ ১: AA, Aa, Aa, aa"),
    ("Aa", "aa"): (50, "2 in 4: Aa, Aa, aa, aa", "৪-এ ২: Aa, Aa, aa, aa"),
    ("AA", "aa"): (0, "none: all offspring are Aa", "একটাও না: সব সন্তান Aa"),
    ("aa", "aa"): (100, "4 in 4: all aa", "৪-এ ৪: সব aa"),
}


def cross(p1, p2, trait_en, trait_bn):
    pct, ex_en, ex_bn = CROSS[(p1, p2)]
    o = []
    for v in (pct, 25, 50, 75, 100, 0):
        if v not in o:
            o.append(v)
    o = o[:4]
    return mcq(f"{trait_en} is caused by a recessive allele (a). Two parents are {p1} and {p2}. What is the chance a child shows the trait (aa)?",
               [f"{v}%" for v in o], 0,
               f"Punnett square gives {ex_en} - so {pct}%.",
               f"{trait_bn} একটা প্রচ্ছন্ন অ্যালিল (a)-এর জন্য হয়। বাবা-মা {p1} আর {p2}। সন্তানের মধ্যে বৈশিষ্ট্যটা (aa) দেখা যাওয়ার সম্ভাবনা কত?",
               [f"{v}%" for v in o],
               f"পানেট-বর্গ দেয় {ex_bn} - তাই {pct}%।")


def transfer(low, high, a_en, a_bn, b_en, b_bn):
    r = _c(high * 100 / low)
    return _n(f"{a_en} in a river by a bridge hold {low:,} kJ of energy; the {b_en} that eat them get {high:,} kJ. What is the efficiency of energy transfer?",
              f"সেতুর কাছে নদীতে {a_bn}-তে {low:,} kJ শক্তি; যে {b_bn} তাদের খায় তারা পায় {high:,} kJ। শক্তি-স্থানান্তরের দক্ষতা কত?", r,
              f"Efficiency = energy passed on ÷ energy available x 100 = {high:,} ÷ {low:,} x 100 = {r:g}%. The rest is lost as heat, movement and waste.",
              f"দক্ষতা = পরের স্তরে যাওয়া শক্তি ÷ উপলব্ধ শক্তি x 100 = {high:,} ÷ {low:,} x 100 = {r:g}%। বাকিটা তাপ, চলাফেরা আর বর্জ্যে হারায়।",
              (_c(100 - r), _c(low / high), _c(r * 10)), "%")


def herd(r0, disease_en, disease_bn):
    pct = _c((1 - 1 / r0) * 100)
    return _n(f"Each person with {disease_en} infects about {r0} others in a group with no immunity. Roughly what share of workers on a big site must be immune to stop it spreading? (1 - 1/R x 100)",
              f"রোগ-প্রতিরোধহীন দলে {disease_bn}-এ আক্রান্ত প্রত্যেকে প্রায় {r0} জনকে সংক্রমিত করেন। বড় নির্মাণস্থলে মোটামুটি কত শতাংশ কর্মীর প্রতিরোধ থাকলে ছড়ানো থামবে? (1 - 1/R x 100)", pct,
              f"Herd immunity threshold = (1 - 1/{r0}) x 100 = {pct:g}%. Vaccination protects even those who cannot be vaccinated.",
              f"দলগত প্রতিরোধের সীমা = (1 - 1/{r0}) x 100 = {pct:g}%। টিকা তাঁদেরও রক্ষা করে যাঁরা টিকা নিতে পারেন না।",
              (_c(100 / r0), _c(r0 * 10), _c(pct / 2)), "%")


def mitosis(n, start):
    r = start * 2 ** n
    return _n(f"A skin cell divides by mitosis. Starting with {start} cell{'s' if start > 1 else ''}, how many cells are there after {n} rounds of division?",
              f"একটা চামড়ার কোষ মাইটোসিসে বিভাজিত হয়। {start}টি কোষ থেকে শুরু করে {n} দফা বিভাজনের পরে কতগুলো কোষ?", r,
              f"Each round doubles the number: {start} x 2^{n} = {r:,}.",
              f"প্রতি দফায় সংখ্যা দ্বিগুণ: {start} x 2^{n} = {r:,}।",
              (start * 2 * n, start + 2 ** n if start + 2 ** n != r else r + 4, start * n))


def pulse(beats, secs):
    r = beats * 60 // secs
    return _n(f"A first-aider counts {beats} beats in {secs} seconds at a worker's wrist. What is the heart rate in beats per minute?",
              f"একজন প্রাথমিক চিকিৎসক একজন কর্মীর কবজিতে {secs} সেকেন্ডে {beats}টি স্পন্দন গুনলেন। মিনিটে হৃৎস্পন্দন কত?", r,
              f"{beats} x (60 ÷ {secs}) = {r} beats per minute.",
              f"{beats} x (60 ÷ {secs}) = মিনিটে {r}টি স্পন্দন।",
              (beats * secs // 10, beats + 60, r // 2))


def bubbles(n, mins, dist):
    r = _c(n / mins)
    return _n(f"Pondweed under a lamp {dist} cm away gives off {n} oxygen bubbles in {mins} minutes. What is the rate of photosynthesis in bubbles per minute?",
              f"{dist} cm দূরে বাতির নিচে একটা জলজ উদ্ভিদ {mins} মিনিটে {n}টি অক্সিজেনের বুদবুদ ছাড়ে। মিনিটপ্রতি বুদবুদে সালোকসংশ্লেষের হার কত?", r,
              f"Rate = {n} ÷ {mins} = {r:g} bubbles per minute.",
              f"হার = {n} ÷ {mins} = মিনিটে {r:g}টি বুদবুদ।",
              (_c(mins / n * 10), n * mins, _c(n / dist)))


ITEMS = (
    lincoln(40, 50, 10, "river crabs", "নদীর কাঁকড়া"), lincoln(30, 60, 12, "bank voles", "পাড়ের মেঠো ইঁদুর"),
    lincoln(25, 40, 5, "frogs", "ব্যাঙ"), lincoln(80, 100, 20, "snails", "শামুক"), lincoln(60, 45, 9, "beetles", "গুবরে পোকা"),
    cross("Aa", "Aa", "A rare blood condition", "একটা বিরল রক্তের অবস্থা"), cross("Aa", "aa", "Red-green colour weakness in a test family", "একটা পরীক্ষামূলক পরিবারে লাল-সবুজ বর্ণদুর্বলতা"),
    cross("AA", "aa", "Albinism in a herd of cattle", "গবাদি পশুর পালে অ্যালবিনিজম"), cross("aa", "aa", "Short stems in pea plants", "মটরগাছে খাটো কাণ্ড"),
    cross("Aa", "Aa", "Cystic fibrosis", "সিস্টিক ফাইব্রোসিস"),
    transfer(10000, 1000, "Water plants", "জলজ উদ্ভিদ", "snails", "শামুক"), transfer(2000, 160, "Insects", "পোকামাকড়", "small fish", "ছোট মাছ"),
    transfer(5000, 450, "Algae", "শৈবাল", "water fleas", "জলের মাছি"), transfer(800, 64, "Small fish", "ছোট মাছ", "kingfishers", "মাছরাঙা"),
    herd(2, "a winter flu", "শীতের ফ্লু"), herd(4, "a stomach virus", "পেটের একটা ভাইরাস"), herd(5, "chickenpox in adults", "প্রাপ্তবয়স্কদের জলবসন্ত"),
    herd(10, "a measles-like virus", "হামের মতো একটা ভাইরাস"),
    mitosis(3, 1), mitosis(5, 1), mitosis(4, 3), mitosis(6, 2),
    pulse(18, 15), pulse(35, 30), pulse(12, 10), pulse(45, 30),
    bubbles(30, 5, 10), bubbles(24, 6, 20), bubbles(12, 4, 40), bubbles(45, 3, 5),
    mcq("Why is DNA described as a 'code'?", ["The order of its bases sets the order of amino acids in a protein", "It is written in letters by scientists", "It is a secret password", "It is the same in every species"], 0,
        "Three bases code for one amino acid - change a base and the protein may change.",
        "ডিএনএ-কে 'সংকেত' বলা হয় কেন?", ["এর ক্ষারকের ক্রম প্রোটিনে অ্যামিনো অ্যাসিডের ক্রম ঠিক করে", "বিজ্ঞানীরা অক্ষরে লেখেন", "এটা গোপন পাসওয়ার্ড", "সব প্রজাতিতে একই"],
        "তিনটে ক্ষারক একটা অ্যামিনো অ্যাসিডের সংকেত - একটা ক্ষারক বদলালে প্রোটিন বদলাতে পারে।"),
    mcq("In DNA, which base always pairs with adenine (A)?", ["Thymine (T)", "Cytosine (C)", "Guanine (G)", "Adenine (A)"], 0,
        "A pairs with T, and C pairs with G.",
        "ডিএনএ-তে অ্যাডেনিনের (A) সঙ্গে সবসময় কোন ক্ষারক জোড় বাঁধে?", ["থাইমিন (T)", "সাইটোসিন (C)", "গুয়ানিন (G)", "অ্যাডেনিন (A)"],
        "A-র সঙ্গে T, আর C-র সঙ্গে G।"),
    mcq("What does a gene code for?", ["A particular protein", "A whole organ", "A type of food", "A blood group only"], 0,
        "Proteins such as enzymes and collagen build and run the body.",
        "একটা জিন কীসের সংকেত বহন করে?", ["একটা নির্দিষ্ট প্রোটিন", "একটা পুরো অঙ্গ", "এক রকম খাদ্য", "শুধু রক্তের গ্রুপ"],
        "এনজাইম আর কোলাজেনের মতো প্রোটিন শরীর গড়ে ও চালায়।"),
    mcq("Where in the cell are proteins made?", ["At ribosomes", "In the cell wall", "In the vacuole", "In the cell membrane only"], 0,
        "The instructions are copied from DNA in the nucleus and carried to the ribosomes.",
        "কোষের কোথায় প্রোটিন তৈরি হয়?", ["রাইবোজোমে", "কোষপ্রাচীরে", "কোষগহ্বরে", "শুধু কোষপর্দায়"],
        "নির্দেশ নিউক্লিয়াসের ডিএনএ থেকে নকল হয়ে রাইবোজোমে যায়।"),
    mcq("What is a 'genotype'?", ["The alleles an organism has, such as Aa", "What the organism looks like", "Its age", "Its habitat"], 0,
        "The 'phenotype' is the visible feature the genotype produces.",
        "'জিনোটাইপ' কী?", ["জীবের যে অ্যালিলগুলো আছে, যেমন Aa", "জীবটা দেখতে কেমন", "এর বয়স", "এর বাসস্থান"],
        "জিনোটাইপ যে দৃশ্যমান বৈশিষ্ট্য তৈরি করে, তা 'ফিনোটাইপ'।"),
    mcq("What does 'homozygous' mean?", ["Having two identical alleles for a gene, such as AA or aa", "Having two different alleles", "Having no alleles", "Being a clone"], 0,
        "Aa, with two different alleles, is 'heterozygous'.",
        "'সমসংকর' (হোমোজাইগাস) মানে কী?", ["একটা জিনের দুটো একই অ্যালিল থাকা, যেমন AA বা aa", "দুটো আলাদা অ্যালিল থাকা", "কোনো অ্যালিল না থাকা", "ক্লোন হওয়া"],
        "দুটো আলাদা অ্যালিলওয়ালা Aa 'অসমসংকর'।"),
    mcq("A person is a 'carrier' of a recessive condition. What does that mean?", ["They have one copy of the faulty allele (Aa) but do not show the condition", "They have the condition badly", "They carry patients to hospital", "They have no copy of the allele"], 0,
        "Two carriers have a 1 in 4 chance of a child with the condition.",
        "একজন একটা প্রচ্ছন্ন অবস্থার 'বাহক'। এর মানে কী?", ["ত্রুটিপূর্ণ অ্যালিলের একটা কপি (Aa) আছে, কিন্তু অবস্থাটা দেখা যায় না", "অবস্থাটা খারাপভাবে আছে", "রোগীকে হাসপাতালে নিয়ে যান", "অ্যালিলের কোনো কপি নেই"],
        "দুজন বাহকের সন্তানের অবস্থাটা হওয়ার সম্ভাবনা 4-এ 1।"),
    mcq("How many chromosomes are in a normal human body cell?", ["46 (23 pairs)", "23", "92", "12"], 0,
        "Sperm and egg cells have 23, so a fertilised egg has 46.",
        "মানুষের সাধারণ দেহকোষে কতগুলো ক্রোমোজোম?", ["46টি (23 জোড়া)", "23টি", "92টি", "12টি"],
        "শুক্রাণু আর ডিম্বাণুতে 23টি, তাই নিষিক্ত ডিম্বাণুতে 46টি।"),
    mcq("What is mitosis used for in the body?", ["Growth and repair - making identical new cells", "Making sex cells", "Digesting food", "Fighting bacteria directly"], 0,
        "A cut finger heals because skin cells divide by mitosis.",
        "শরীরে মাইটোসিস কীসের জন্য ব্যবহার হয়?", ["বৃদ্ধি আর মেরামত - হুবহু একই নতুন কোষ তৈরি", "জননকোষ তৈরি", "খাদ্য হজম", "সরাসরি ব্যাকটেরিয়ার সঙ্গে লড়াই"],
        "কাটা আঙুল সারে কারণ চামড়ার কোষ মাইটোসিসে বিভাজিত হয়।"),
    mcq("What is cancer?", ["Cells dividing uncontrollably, forming a tumour", "A type of virus only", "A broken bone", "An allergy"], 0,
        "Some site hazards, like asbestos and too much sun, raise cancer risk.",
        "ক্যান্সার কী?", ["অনিয়ন্ত্রিতভাবে কোষ বিভাজিত হয়ে টিউমার তৈরি", "শুধু এক রকম ভাইরাস", "ভাঙা হাড়", "অ্যালার্জি"],
        "অ্যাসবেস্টস আর অতিরিক্ত রোদের মতো কিছু ঝুঁকি ক্যান্সারের সম্ভাবনা বাড়ায়।"),
    mcq("Where in an adult are stem cells found that make new blood cells?", ["In the bone marrow", "In the hair", "In the teeth", "In the stomach lining"], 0,
        "Bone marrow transplants use these stem cells to treat some blood cancers.",
        "প্রাপ্তবয়স্কের শরীরের কোথায় নতুন রক্তকণিকা বানানোর স্টেম-কোষ থাকে?", ["অস্থিমজ্জায়", "চুলে", "দাঁতে", "পাকস্থলীর আস্তরণে"],
        "কিছু রক্তের ক্যান্সারের চিকিৎসায় অস্থিমজ্জা-প্রতিস্থাপন এই স্টেম-কোষ ব্যবহার করে।"),
    mcq("Peppered moths became mostly dark in sooty industrial towns. Which explanation fits natural selection?", ["Dark moths were better hidden on sooty bark, so fewer were eaten and more bred", "Moths painted themselves dark", "Soot dyed the moths", "Birds preferred dark moths"], 0,
        "When the air was cleaned up, pale moths became common again.",
        "ধোঁয়াটে শিল্পশহরে পেপারড মথ বেশিরভাগ কালো হয়ে গিয়েছিল। কোন ব্যাখ্যা প্রাকৃতিক নির্বাচনের সঙ্গে মেলে?", ["কালো মথ ঝুলমাখা বাকলে ভালো লুকোত, তাই কম খাওয়া পড়ত আর বেশি বংশবৃদ্ধি করত", "মথরা নিজেরা কালো রং মাখত", "ঝুল মথকে রাঙিয়ে দিত", "পাখিরা কালো মথ পছন্দ করত"],
        "বাতাস পরিষ্কার হওয়ার পরে আবার হালকা রঙের মথ বেড়ে যায়।"),
    mcq("Who proposed the theory of evolution by natural selection?", ["Charles Darwin (with Alfred Russel Wallace)", "Isaac Newton", "Marie Curie", "Albert Einstein"], 0,
        "Darwin published 'On the Origin of Species' in 1859.",
        "প্রাকৃতিক নির্বাচনের মাধ্যমে বিবর্তনের তত্ত্ব কে দেন?", ["চার্লস ডারউইন (আলফ্রেড রাসেল ওয়ালেসের সঙ্গে)", "আইজ্যাক নিউটন", "মারি কুরি", "আলবার্ট আইনস্টাইন"],
        "ডারউইন 1859 সালে 'অন দ্য অরিজিন অফ স্পিশিজ' প্রকাশ করেন।"),
    mcq("How do bacteria become resistant to antibiotics?", ["A random mutation lets a few survive; they multiply while the others die", "Bacteria learn from doctors", "Antibiotics make bacteria stronger on purpose", "Resistance is caught from food only"], 0,
        "Always finish a prescribed course so no survivors are left to spread.",
        "ব্যাকটেরিয়া কীভাবে অ্যান্টিবায়োটিক-প্রতিরোধী হয়?", ["এলোমেলো মিউটেশনে কয়েকটা বেঁচে যায়; বাকিরা মরলেও ওরা বংশবৃদ্ধি করে", "ডাক্তারদের থেকে শেখে", "অ্যান্টিবায়োটিক ইচ্ছে করে ব্যাকটেরিয়া শক্ত করে", "প্রতিরোধ শুধু খাবার থেকে আসে"],
        "সবসময় দেওয়া কোর্স শেষ করো, যাতে ছড়ানোর মতো কেউ বেঁচে না থাকে।"),
    mcq("Why shouldn't antibiotics be taken for a common cold?", ["Colds are caused by viruses, which antibiotics do not kill - and misuse breeds resistant bacteria", "Antibiotics make colds worse instantly", "Colds are caused by fungi", "Antibiotics are only for animals"], 0,
        "Rest, fluids and time usually clear a cold.",
        "সাধারণ সর্দিতে অ্যান্টিবায়োটিক খাওয়া উচিত নয় কেন?", ["সর্দি ভাইরাসে হয়, যাকে অ্যান্টিবায়োটিক মারে না - আর অপব্যবহারে প্রতিরোধী ব্যাকটেরিয়া জন্মায়", "অ্যান্টিবায়োটিক তখনই সর্দি বাড়ায়", "সর্দি ছত্রাকে হয়", "অ্যান্টিবায়োটিক শুধু প্রাণীদের জন্য"],
        "বিশ্রাম, জল আর সময়ে সাধারণত সর্দি সারে।"),
    mcq("What evidence do fossils give for evolution?", ["They show how living things have changed over millions of years", "They show animals never change", "They are always less than 100 years old", "They prove all species appeared at once"], 0,
        "Rock layers dug for bridge foundations sometimes reveal fossils.",
        "জীবাশ্ম বিবর্তনের কী প্রমাণ দেয়?", ["লক্ষ লক্ষ বছরে জীবেরা কীভাবে বদলেছে তা দেখায়", "দেখায় প্রাণী কখনো বদলায় না", "সবসময় 100 বছরের কম পুরোনো", "প্রমাণ করে সব প্রজাতি একসঙ্গে এসেছে"],
        "সেতুর ভিত খুঁড়তে গিয়ে পাথরের স্তরে কখনো জীবাশ্ম মেলে।"),
    mcq("What is 'speciation'?", ["The formation of a new species when populations become so different they cannot interbreed", "Counting species", "A species dying out", "Cloning a species"], 0,
        "Rivers, mountains and even motorways can split populations apart.",
        "'প্রজাতি-গঠন' কী?", ["জনগোষ্ঠী এত আলাদা হয়ে যাওয়া যে পরস্পর প্রজনন করতে পারে না, ফলে নতুন প্রজাতি", "প্রজাতি গোনা", "প্রজাতি বিলুপ্ত হওয়া", "প্রজাতির ক্লোন"],
        "নদী, পাহাড়, এমনকি মহাসড়কও জনগোষ্ঠীকে ভাগ করে দিতে পারে।"),
    mcq("How does a vaccine protect you?", ["It contains a harmless form of a pathogen, so white blood cells make antibodies and memory cells in advance", "It kills all bacteria in the body", "It is an antibiotic", "It makes your blood thicker"], 0,
        "If the real pathogen arrives, memory cells respond fast.",
        "টিকা কীভাবে রক্ষা করে?", ["এতে জীবাণুর নিরীহ রূপ থাকে, তাই শ্বেতকণিকা আগেই অ্যান্টিবডি আর স্মৃতি-কোষ বানায়", "শরীরের সব ব্যাকটেরিয়া মারে", "এটা অ্যান্টিবায়োটিক", "রক্ত ঘন করে"],
        "আসল জীবাণু এলে স্মৃতি-কোষ দ্রুত সাড়া দেয়।"),
    mcq("Why are construction workers often advised to have a tetanus vaccine?", ["Tetanus bacteria live in soil and enter through cuts from rusty or dirty objects", "Tetanus spreads by coughing", "Concrete contains tetanus", "It protects against falls"], 0,
        "Clean every wound and keep tetanus protection up to date.",
        "নির্মাণ-কর্মীদের প্রায়ই ধনুষ্টংকারের টিকা নিতে বলা হয় কেন?", ["ধনুষ্টংকারের ব্যাকটেরিয়া মাটিতে থাকে আর মরচে-ধরা বা নোংরা জিনিসে কাটা থেকে ঢোকে", "কাশিতে ছড়ায়", "কংক্রিটে ধনুষ্টংকার থাকে", "পড়ে যাওয়া থেকে রক্ষা করে"],
        "প্রতিটা ক্ষত পরিষ্কার করো আর টিকা হালনাগাদ রাখো।"),
    mcq("What do white blood cells called phagocytes do?", ["Engulf and digest pathogens", "Carry oxygen", "Clot blood", "Make hormones"], 0,
        "Lymphocytes, another kind, make antibodies.",
        "ফ্যাগোসাইট নামের শ্বেতকণিকা কী করে?", ["জীবাণু গিলে হজম করে", "অক্সিজেন বয়", "রক্ত জমায়", "হরমোন বানায়"],
        "লিম্ফোসাইট নামের আরেক রকম অ্যান্টিবডি বানায়।"),
    mcq("What do platelets do when a worker cuts their hand?", ["Help the blood clot to seal the wound", "Carry oxygen to the cut", "Fight viruses", "Digest food"], 0,
        "A scab forms and protects the skin while it heals.",
        "একজন কর্মীর হাত কাটলে অণুচক্রিকা কী করে?", ["রক্ত জমাট বাঁধিয়ে ক্ষত বন্ধ করতে সাহায্য করে", "কাটা জায়গায় অক্সিজেন বয়", "ভাইরাসের সঙ্গে লড়ে", "খাদ্য হজম করে"],
        "মামড়ি তৈরি হয়ে সারার সময় চামড়া রক্ষা করে।"),
    mcq("What is the first thing to do for a worker with heavy bleeding from the arm?", ["Press firmly on the wound with a clean pad and call for help", "Give them water to drink", "Wash the wound for 10 minutes first", "Make them run to the office"], 0,
        "Direct pressure is the fastest way to slow bleeding.",
        "একজন কর্মীর হাত থেকে প্রচুর রক্ত পড়ছে। প্রথমে কী করতে হবে?", ["পরিষ্কার প্যাড দিয়ে ক্ষতে জোরে চেপে ধরো আর সাহায্য ডাকো", "খেতে জল দাও", "আগে 10 মিনিট ক্ষত ধোও", "অফিসে দৌড়াতে বলো"],
        "সরাসরি চাপই রক্ত পড়া কমানোর সবচেয়ে দ্রুত উপায়।"),
    mcq("During CPR on an adult, about how many chest compressions per minute are recommended?", ["100-120", "10-20", "300-400", "1-2"], 0,
        "Push hard and fast in the centre of the chest; call emergency services first.",
        "প্রাপ্তবয়স্কের সিপিআর-এ মিনিটে প্রায় কতবার বুকে চাপ দিতে বলা হয়?", ["100-120", "10-20", "300-400", "1-2"],
        "বুকের মাঝখানে জোরে আর দ্রুত চাপো; আগে জরুরি পরিষেবায় ফোন করো।"),
    mcq("What is 'silicosis'?", ["A lung disease from breathing fine silica dust from cutting concrete, stone or brick", "A skin rash from sunlight", "A bone disease from lifting", "A stomach infection"], 0,
        "Water suppression and dust masks prevent it - the damage is permanent.",
        "'সিলিকোসিস' কী?", ["কংক্রিট, পাথর বা ইট কাটার সূক্ষ্ম সিলিকা-ধুলো শ্বাসে নিয়ে ফুসফুসের রোগ", "রোদে চামড়ার ফুসকুড়ি", "ভার তোলায় হাড়ের রোগ", "পেটের সংক্রমণ"],
        "জল ছিটিয়ে ধুলো দমন আর মাস্কে এটা আটকায় - ক্ষতি স্থায়ী।"),
    mcq("Why is cutting concrete 'wet' (with water spray) safer for workers' lungs?", ["Water traps the fine dust so far less is breathed in", "Wet concrete is softer", "Water makes the saw quieter only", "It keeps the worker cool only"], 0,
        "Fine dust reaches deep into the alveoli where it cannot be cleared.",
        "জল ছিটিয়ে 'ভেজা' অবস্থায় কংক্রিট কাটা কর্মীদের ফুসফুসের জন্য নিরাপদ কেন?", ["জল সূক্ষ্ম ধুলো আটকে রাখে, তাই অনেক কম শ্বাসে যায়", "ভেজা কংক্রিট নরম", "জল শুধু করাতের শব্দ কমায়", "শুধু কর্মীকে ঠান্ডা রাখে"],
        "সূক্ষ্ম ধুলো ফুসফুসের গভীরে বায়ুথলিতে পৌঁছায়, যেখান থেকে বের করা যায় না।"),
    mcq("Why is asbestos in old bridges and buildings removed only by trained specialists?", ["Its fibres, if breathed in, can cause deadly lung diseases and cancer decades later", "It is very heavy", "It is valuable", "It smells bad"], 0,
        "Undisturbed asbestos is low risk; drilling or breaking it releases fibres.",
        "পুরোনো সেতু আর বাড়ির অ্যাসবেস্টস শুধু প্রশিক্ষিত বিশেষজ্ঞরা সরান কেন?", ["এর তন্তু শ্বাসে গেলে কয়েক দশক পরে প্রাণঘাতী ফুসফুসের রোগ আর ক্যান্সার হতে পারে", "খুব ভারী", "দামি", "দুর্গন্ধ"],
        "না-নাড়ানো অ্যাসবেস্টসে ঝুঁকি কম; ড্রিল করলে বা ভাঙলে তন্তু বেরোয়।"),
    mcq("How should a worker lift a heavy bag of cement from the ground?", ["Bend the knees, keep the back straight and the load close to the body", "Bend the back and keep the legs straight", "Twist while lifting", "Lift with arms stretched out"], 0,
        "The strong leg muscles do the work and the spine is protected.",
        "মাটি থেকে ভারী সিমেন্টের বস্তা কীভাবে তোলা উচিত?", ["হাঁটু ভাঁজ করো, পিঠ সোজা রাখো আর বোঝা শরীরের কাছে রাখো", "পিঠ বাঁকিয়ে পা সোজা রাখো", "তোলার সময় মোচড় দাও", "হাত টানটান করে তোলো"],
        "শক্ত পায়ের পেশি কাজ করে আর মেরুদণ্ড সুরক্ষিত থাকে।"),
    mcq("Why does holding a load far from your body strain your back more?", ["The load's moment about your spine is bigger the further away it is", "Loads get heavier when far away", "Arms stop working", "It does not strain the back"], 0,
        "Moment = force x distance - the same physics as a crane.",
        "বোঝা শরীর থেকে দূরে ধরলে পিঠে বেশি চাপ পড়ে কেন?", ["যত দূরে, মেরুদণ্ডের সাপেক্ষে বোঝার ভ্রামক তত বেশি", "দূরে গেলে বোঝা ভারী হয়", "হাত কাজ বন্ধ করে", "পিঠে চাপ পড়ে না"],
        "ভ্রামক = বল x দূরত্ব - ক্রেনের মতো একই পদার্থবিদ্যা।"),
    mcq("What are the discs between the vertebrae of the spine?", ["Cartilage cushions that absorb shock and allow movement", "Extra bones", "Muscles", "Nerves only"], 0,
        "Bad lifting can damage them, causing a 'slipped disc'.",
        "মেরুদণ্ডের কশেরুকার মাঝের চাকতিগুলো কী?", ["তরুণাস্থির গদি, যা ধাক্কা শোষে আর নড়াচড়া করতে দেয়", "বাড়তি হাড়", "পেশি", "শুধু স্নায়ু"],
        "ভুলভাবে তুললে এগুলোর ক্ষতি হয়ে 'স্লিপড ডিস্ক' হতে পারে।"),
    mcq("Why are long bones like the femur hollow tubes rather than solid rods?", ["A tube is strong in bending for much less weight - the same idea as a steel pipe column", "To store water", "Solid bones are illegal", "To make them weaker"], 0,
        "Engineers copy this in hollow tubular bridge members.",
        "উরুর হাড়ের মতো লম্বা হাড় নিরেট দণ্ড না হয়ে ফাঁপা নল কেন?", ["নল অনেক কম ওজনে বাঁকানোয় শক্ত - ইস্পাতের পাইপ-থামের মতো একই ভাবনা", "জল জমাতে", "নিরেট হাড় নিষিদ্ধ", "দুর্বল করতে"],
        "প্রকৌশলীরা ফাঁপা নলাকার সেতু-অংশে এটা নকল করেন।"),
    mcq("What do tendons do?", ["Join muscles to bones so muscles can pull them", "Join bone to bone", "Carry blood", "Make red blood cells"], 0,
        "Tendons are in tension - like the cables of a bridge.",
        "কণ্ডরা (টেন্ডন) কী করে?", ["পেশিকে হাড়ের সঙ্গে জোড়ে, যাতে পেশি হাড় টানতে পারে", "হাড়কে হাড়ের সঙ্গে জোড়ে", "রক্ত বয়", "লোহিতকণিকা বানায়"],
        "কণ্ডরা টানে থাকে - সেতুর তারের মতো।"),
    mcq("Why do muscles work in antagonistic pairs, like the biceps and triceps?", ["Muscles can only pull, not push, so one bends a joint and the other straightens it", "One muscle is always resting", "To look balanced", "Muscles can push and pull equally"], 0,
        "Cranes use paired cylinders or cables for the same reason.",
        "পেশি বাইসেপ আর ট্রাইসেপের মতো বিপরীত জোড়ায় কাজ করে কেন?", ["পেশি শুধু টানতে পারে, ঠেলতে নয়; তাই একটা অস্থিসন্ধি ভাঁজ করে, অন্যটা সোজা করে", "একটা পেশি সবসময় বিশ্রামে", "সুষম দেখাতে", "পেশি সমানভাবে ঠেলতে আর টানতে পারে"],
        "একই কারণে ক্রেনে জোড়া সিলিন্ডার বা তার থাকে।"),
    mcq("What is 'fatigue' in a worker, and why does it matter on a bridge site?", ["Tiredness that slows reactions and causes mistakes - a major cause of accidents", "A type of metal crack only", "Being very fit", "A kind of lunch break"], 0,
        "Rest breaks, water and sensible shift lengths keep crews safe.",
        "কর্মীর 'ক্লান্তি' কী, আর সেতু-নির্মাণস্থলে কেন জরুরি?", ["অবসাদ, যা প্রতিক্রিয়া ধীর করে আর ভুল ঘটায় - দুর্ঘটনার বড় কারণ", "শুধু ধাতুর এক রকম ফাটল", "খুব সুস্থ থাকা", "এক রকম দুপুরের বিরতি"],
        "বিশ্রামের বিরতি, জল আর যুক্তিসঙ্গত পালার দৈর্ঘ্য দলকে নিরাপদ রাখে।"),
    mcq("Why is sleep important for workers operating cranes?", ["The brain needs sleep to stay alert; tiredness slows reaction time like alcohol does", "Sleep makes muscles bigger instantly", "Cranes need the operator to dream", "It is not important"], 0,
        "Going 17-19 hours without sleep can impair you like being over the drink-drive limit.",
        "ক্রেন-চালকদের জন্য ঘুম জরুরি কেন?", ["সজাগ থাকতে মস্তিষ্কের ঘুম লাগে; ক্লান্তি মদের মতোই প্রতিক্রিয়া ধীর করে", "ঘুম তখনই পেশি বড় করে", "ক্রেনের জন্য চালকের স্বপ্ন দেখা দরকার", "জরুরি নয়"],
        "17-19 ঘণ্টা না ঘুমালে মদ্যপ অবস্থায় গাড়ি চালানোর সীমা ছাড়ানোর মতো দুর্বলতা আসতে পারে।"),
    mcq("What does 'dehydration' do to a worker in hot weather?", ["Causes headaches, dizziness and poor concentration, and can lead to heat stroke", "Makes them stronger", "Improves their memory", "Has no effect"], 0,
        "Drink water regularly - thirst comes late.",
        "গরম আবহাওয়ায় 'জলশূন্যতা' কর্মীর কী করে?", ["মাথাব্যথা, মাথা-ঘোরা আর মনোযোগের অভাব ঘটায়, হিটস্ট্রোকে গড়াতে পারে", "শক্তিশালী করে", "স্মৃতি বাড়ায়", "কোনো প্রভাব নেই"],
        "নিয়মিত জল খাও - তেষ্টা দেরিতে আসে।"),
    mcq("Why does skin go red when you are hot?", ["Blood vessels near the skin widen (vasodilation) so more heat is lost", "Skin is burning", "Muscles are working", "Blood turns red only when hot"], 0,
        "Sweating also cools you as the sweat evaporates.",
        "গরম লাগলে চামড়া লাল হয় কেন?", ["চামড়ার কাছের রক্তনালী চওড়া হয় (রক্তনালী-প্রসারণ), তাই বেশি তাপ বেরোয়", "চামড়া পুড়ছে", "পেশি কাজ করছে", "রক্ত শুধু গরমে লাল হয়"],
        "ঘাম বাষ্প হয়ে উড়ে গেলেও শরীর ঠান্ডা হয়।"),
    mcq("A pondweed experiment: moving the lamp further away gives fewer bubbles. Why?", ["Light intensity falls with distance, so photosynthesis slows", "The pondweed gets tired", "Further lamps are hotter", "Bubbles need darkness"], 0,
        "Light intensity falls roughly with the square of distance.",
        "জলজ উদ্ভিদের পরীক্ষা: বাতি দূরে সরালে বুদবুদ কম হয়। কেন?", ["দূরত্বের সঙ্গে আলোর তীব্রতা কমে, তাই সালোকসংশ্লেষ ধীর হয়", "উদ্ভিদ ক্লান্ত হয়", "দূরের বাতি বেশি গরম", "বুদবুদের জন্য অন্ধকার লাগে"],
        "আলোর তীব্রতা মোটামুটি দূরত্বের বর্গের সঙ্গে কমে।"),
    mcq("Why is the lamp in a pondweed experiment often placed behind a beaker of water?", ["The water absorbs heat, so only the light changes, not the temperature", "To make the light brighter", "To feed the pondweed", "To make bubbles bigger"], 0,
        "A fair test changes one variable at a time.",
        "জলজ উদ্ভিদের পরীক্ষায় বাতি প্রায়ই এক বিকার জলের পিছনে রাখা হয় কেন?", ["জল তাপ শোষে, তাই শুধু আলো বদলায়, তাপমাত্রা নয়", "আলো উজ্জ্বল করতে", "উদ্ভিদকে খাওয়াতে", "বুদবুদ বড় করতে"],
        "ন্যায্য পরীক্ষায় একবারে একটাই চলরাশি বদলানো হয়।"),
    mcq("In a river, 1,000 kg of algae support 100 kg of insect larvae. Roughly what mass of fish could the larvae support?", ["About 10 kg", "About 100 kg", "About 1,000 kg", "About 1 kg"], 0,
        "Only about a tenth passes up each level: 100 ÷ 10 = 10 kg.",
        "একটা নদীতে 1,000 kg শৈবাল 100 kg পোকার শূককীটকে বাঁচিয়ে রাখে। শূককীটরা মোটামুটি কত ভরের মাছ বাঁচাতে পারে?", ["প্রায় 10 kg", "প্রায় 100 kg", "প্রায় 1,000 kg", "প্রায় 1 kg"],
        "প্রতি স্তরে মোটামুটি এক-দশমাংশ উপরে যায়: 100 ÷ 10 = 10 kg।"),
    mcq("Why are there rarely more than four or five links in a food chain?", ["So much energy is lost at each step that too little is left to support more levels", "Animals do not like long chains", "Plants stop growing", "There is a law against it"], 0,
        "Only about 10% passes from one level to the next.",
        "খাদ্যশৃঙ্খলে কদাচিৎ চার-পাঁচটার বেশি ধাপ থাকে কেন?", ["প্রতি ধাপে এত শক্তি হারায় যে আরও স্তর চালানোর মতো বাকি থাকে না", "প্রাণীরা লম্বা শৃঙ্খল পছন্দ করে না", "উদ্ভিদ বাড়া থামায়", "এর বিরুদ্ধে আইন আছে"],
        "এক স্তর থেকে পরের স্তরে মাত্র প্রায় 10% যায়।"),
    mcq("What do decomposers such as fungi and bacteria do?", ["Break down dead material and return nutrients to the soil", "Make food by photosynthesis", "Hunt live animals", "Build nests"], 0,
        "Without them, dead leaves and logs would pile up forever.",
        "ছত্রাক আর ব্যাকটেরিয়ার মতো বিয়োজকরা কী করে?", ["মৃত পদার্থ ভেঙে পুষ্টি মাটিতে ফেরায়", "সালোকসংশ্লেষে খাদ্য বানায়", "জীবিত প্রাণী শিকার করে", "বাসা বানায়"],
        "এরা না থাকলে মরা পাতা আর গুঁড়ি চিরকাল জমে থাকত।"),
    mcq("Why does a compost heap decompose faster when it is warm, moist and turned over?", ["Microbes work best with warmth, water and oxygen", "Turning it adds sugar", "Cold stops all chemistry forever", "Water kills microbes"], 0,
        "Site canteens can compost food waste this way.",
        "কম্পোস্টের স্তূপ গরম, ভেজা আর উল্টে দেওয়া হলে দ্রুত পচে কেন?", ["জীবাণুরা উষ্ণতা, জল আর অক্সিজেনে সবচেয়ে ভালো কাজ করে", "উল্টালে চিনি যোগ হয়", "ঠান্ডা চিরকাল সব রসায়ন থামায়", "জল জীবাণু মারে"],
        "নির্মাণস্থলের ক্যান্টিন এভাবে খাবারের বর্জ্য কম্পোস্ট করতে পারে।"),
    mcq("Why is a field of a single crop (a monoculture) less stable than a mixed meadow?", ["One pest or disease can wipe out the whole field because every plant is the same", "Single crops grow faster forever", "Meadows have no insects", "Monocultures need no water"], 0,
        "Low biodiversity means fewer natural checks and backups.",
        "একক ফসলের খেত (একচাষ) মিশ্র তৃণভূমির চেয়ে কম স্থিতিশীল কেন?", ["সব গাছ একই বলে একটা পোকা বা রোগ গোটা খেত শেষ করতে পারে", "একক ফসল চিরকাল দ্রুত বাড়ে", "তৃণভূমিতে পোকা থাকে না", "একচাষে জল লাগে না"],
        "কম জীববৈচিত্র্য মানে কম প্রাকৃতিক নিয়ন্ত্রণ আর বিকল্প।"),
    mcq("What does meiosis produce from one body cell?", ["Four cells, each with half the chromosomes and all genetically different", "Two identical cells", "One larger cell", "Four identical cells"], 0,
        "These sex cells combine at fertilisation to restore the full number.",
        "একটা দেহকোষ থেকে মিয়োসিস কী তৈরি করে?", ["চারটে কোষ, প্রত্যেকটায় অর্ধেক ক্রোমোজোম আর সবাই জিনগতভাবে আলাদা", "দুটো হুবহু একই কোষ", "একটা বড় কোষ", "চারটে হুবহু একই কোষ"],
        "এই জননকোষগুলো নিষেকে মিলে পুরো সংখ্যা ফিরিয়ে আনে।"),
    mcq("Why do smokers often get out of breath climbing a bridge's stairs?", ["Tar damages the alveoli and carbon monoxide reduces the oxygen red blood cells can carry", "Smoke makes legs heavier", "Smoking strengthens the lungs", "Stairs are steeper for smokers"], 0,
        "Less oxygen reaches the muscles, so they tire quickly.",
        "ধূমপায়ীরা প্রায়ই সেতুর সিঁড়ি চড়তে হাঁপিয়ে ওঠেন কেন?", ["আলকাতরা বায়ুথলির ক্ষতি করে আর কার্বন মনোক্সাইড লোহিতকণিকার অক্সিজেন বওয়ার ক্ষমতা কমায়", "ধোঁয়া পা ভারী করে", "ধূমপান ফুসফুস শক্ত করে", "ধূমপায়ীদের জন্য সিঁড়ি বেশি খাড়া"],
        "পেশিতে কম অক্সিজেন পৌঁছায়, তাই দ্রুত ক্লান্ত হয়।"),
    mcq("Why must petrol generators never run inside a closed site cabin?", ["They release carbon monoxide, which binds to haemoglobin and stops blood carrying oxygen", "They are too noisy only", "They make the cabin cold", "Petrol smells nice"], 0,
        "Carbon monoxide has no colour or smell - it can kill without warning.",
        "পেট্রোল-জেনারেটর কখনো বন্ধ কেবিনের ভেতরে চালানো উচিত নয় কেন?", ["এটা কার্বন মনোক্সাইড ছাড়ে, যা হিমোগ্লোবিনে আটকে রক্তের অক্সিজেন বওয়া থামায়", "শুধু খুব শব্দ করে", "কেবিন ঠান্ডা করে", "পেট্রোলের গন্ধ ভালো"],
        "কার্বন মনোক্সাইডের রং বা গন্ধ নেই - কোনো সতর্কতা ছাড়াই মারতে পারে।"),
    mcq("Leptospirosis can be caught from river water contaminated by rat urine. How can workers on river piers protect themselves?", ["Cover cuts, wear gloves and boots, and wash hands before eating", "Drink the river water to build immunity", "Work barefoot", "Avoid washing"], 0,
        "The bacteria enter through cuts and the lining of the mouth and eyes.",
        "ইঁদুরের মূত্রে দূষিত নদীর জল থেকে লেপটোস্পাইরোসিস হতে পারে। নদীর স্তম্ভে কাজ করা কর্মীরা কীভাবে নিজেদের রক্ষা করবেন?", ["কাটা জায়গা ঢাকো, দস্তানা আর বুট পরো, খাওয়ার আগে হাত ধোও", "প্রতিরোধ গড়তে নদীর জল খাও", "খালি পায়ে কাজ করো", "ধোয়া এড়াও"],
        "ব্যাকটেরিয়া কাটা জায়গা আর মুখ ও চোখের আস্তরণ দিয়ে ঢোকে।"),
    mcq("Why should standing puddles and old tyres on a site be cleared in the rainy season?", ["Mosquitoes that spread dengue and malaria breed in still water", "Puddles damage concrete", "Tyres attract snakes only", "Water makes the site too cold"], 0,
        "No still water, no mosquito larvae.",
        "বর্ষায় নির্মাণস্থলের জমা জল আর পুরোনো টায়ার সরানো উচিত কেন?", ["ডেঙ্গি আর ম্যালেরিয়া ছড়ানো মশা স্থির জলে বংশবৃদ্ধি করে", "জমা জল কংক্রিটের ক্ষতি করে", "টায়ার শুধু সাপ টানে", "জল নির্মাণস্থল খুব ঠান্ডা করে"],
        "স্থির জল নেই তো মশার শূককীট নেই।"),
    mcq("Why are divers who inspect bridge piers in cold rivers at risk of hypothermia?", ["Water draws heat from the body much faster than air, so core temperature can fall dangerously", "Cold water makes divers heavier", "Fish bite them", "Rivers are always warm"], 0,
        "Wetsuits or drysuits and limited dive times keep them safe.",
        "ঠান্ডা নদীতে সেতু-স্তম্ভ পরীক্ষা করা ডুবুরিদের হাইপোথার্মিয়ার ঝুঁকি কেন?", ["বাতাসের চেয়ে জল শরীর থেকে অনেক দ্রুত তাপ টানে, তাই ভেতরের তাপমাত্রা বিপজ্জনকভাবে নামতে পারে", "ঠান্ডা জল ডুবুরিকে ভারী করে", "মাছ কামড়ায়", "নদী সবসময় গরম"],
        "ওয়েটস্যুট বা ড্রাইস্যুট আর সীমিত ডুবের সময় তাঁদের নিরাপদ রাখে।"),
    mcq("Which organ breaks down alcohol and many drugs in the body?", ["The liver", "The lungs", "The heart", "The bladder"], 0,
        "Alcohol stays in the blood for hours - never operate machinery after drinking.",
        "শরীরে কোন অঙ্গ মদ আর অনেক ওষুধ ভাঙে?", ["যকৃৎ", "ফুসফুস", "হৃৎপিণ্ড", "মূত্রথলি"],
        "মদ কয়েক ঘণ্টা রক্তে থাকে - মদ্যপানের পরে কখনো যন্ত্র চালিয়ো না।"),
    mcq("Plants growing in the shade under a bridge deck often have larger, darker green leaves. Why?", ["More leaf area and chlorophyll help them capture the little light available", "Shade makes leaves heavier", "They are a different species every time", "Darkness makes leaves grow faster"], 0,
        "It is an adaptation to low light.",
        "সেতুর পাটাতনের ছায়ায় জন্মানো উদ্ভিদের পাতা প্রায়ই বড় আর গাঢ় সবুজ হয়। কেন?", ["বেশি পাতার ক্ষেত্রফল আর ক্লোরোফিল অল্প আলো ধরতে সাহায্য করে", "ছায়া পাতা ভারী করে", "প্রতিবার আলাদা প্রজাতি", "অন্ধকারে পাতা দ্রুত বাড়ে"],
        "কম আলোর সঙ্গে এটা একটা অভিযোজন।"),
    mcq("How do the roots of riverbank plants help protect a bridge's abutments?", ["Roots bind the soil, reducing erosion of the bank around the foundations", "Roots push the bridge upwards", "Roots dissolve concrete", "Roots attract fish"], 0,
        "Engineers often plant willows and grasses as 'living' bank protection.",
        "নদীপাড়ের উদ্ভিদের শিকড় কীভাবে সেতুর প্রান্ত-ঠেকনা রক্ষা করে?", ["শিকড় মাটি বেঁধে রাখে, ভিতের চারপাশে পাড়ের ক্ষয় কমায়", "শিকড় সেতুকে উপরে ঠেলে", "শিকড় কংক্রিট গলায়", "শিকড় মাছ টানে"],
        "প্রকৌশলীরা প্রায়ই উইলো আর ঘাস লাগিয়ে 'জীবন্ত' পাড়-সুরক্ষা বানান।"),
    mcq("How is a tree's xylem like a building's water pipes?", ["It is a network of hollow tubes carrying water up from the roots to the leaves", "It carries sugar downwards only", "It is made of metal", "It pumps water with a heart"], 0,
        "Evaporation from the leaves pulls the water up, with no pump at all.",
        "গাছের জাইলেম কীভাবে বাড়ির জলের পাইপের মতো?", ["শিকড় থেকে পাতায় জল তোলা ফাঁপা নলের জাল", "শুধু নিচের দিকে শর্করা বয়", "ধাতু দিয়ে তৈরি", "হৃৎপিণ্ড দিয়ে জল পাম্প করে"],
        "পাতা থেকে বাষ্পীভবন জলকে উপরে টানে, কোনো পাম্প ছাড়াই।"),
    mcq("A new bridge plan includes 'biodiversity net gain'. What does that mean?", ["Leaving habitats in a better state than before the project", "Removing all trees", "Counting animals once", "Building on every wetland"], 0,
        "New ponds, hedges and bat boxes can more than replace what is lost.",
        "নতুন সেতুর পরিকল্পনায় 'জীববৈচিত্র্যে নিট লাভ' আছে। এর মানে কী?", ["প্রকল্পের আগের চেয়ে বাসস্থান ভালো অবস্থায় রেখে যাওয়া", "সব গাছ কাটা", "একবার প্রাণী গোনা", "প্রতিটা জলাভূমিতে নির্মাণ"],
        "নতুন পুকুর, ঝোপের বেড়া আর বাদুড়ের বাক্স হারানোর চেয়ে বেশি পূরণ করতে পারে।"),
    mcq("Why are bat surveys often required before old bridges are repaired?", ["Bats roost in crevices of old bridges and are protected; work must avoid harming them", "Bats damage concrete", "Bats are needed to inspect cracks", "Surveys are just for fun"], 0,
        "Work may be timed to avoid the bats' breeding or hibernation season.",
        "পুরোনো সেতু মেরামতের আগে প্রায়ই বাদুড়-সমীক্ষা করতে হয় কেন?", ["বাদুড় পুরোনো সেতুর ফাটলে থাকে আর সংরক্ষিত; কাজে তাদের ক্ষতি এড়াতে হয়", "বাদুড় কংক্রিটের ক্ষতি করে", "ফাটল পরীক্ষায় বাদুড় লাগে", "সমীক্ষা শুধু মজার জন্য"],
        "বাদুড়ের প্রজনন বা শীতঘুমের মরসুম এড়িয়ে কাজের সময় ঠিক হতে পারে।"),
    mcq("Why must the mark used in mark-recapture not harm the animal or make it easier to spot?", ["Otherwise marked animals would be caught more or less often, making the estimate wrong", "Marks must be bright for photos", "Animals like being marked", "It does not matter"], 0,
        "The method assumes marked animals mix back in and behave normally.",
        "চিহ্নিত-পুনর্ধরা পদ্ধতিতে চিহ্ন যেন প্রাণীর ক্ষতি না করে বা তাকে সহজে চোখে না ফেলে কেন?", ["নইলে চিহ্নিতরা বেশি বা কম ধরা পড়বে, অনুমান ভুল হবে", "ছবির জন্য চিহ্ন উজ্জ্বল হতে হবে", "প্রাণীরা চিহ্ন পছন্দ করে", "কিছু যায় আসে না"],
        "পদ্ধতিটা ধরে নেয় চিহ্নিতরা মিশে গিয়ে স্বাভাবিক আচরণ করে।"),
    mcq("What is an 'indicator species'?", ["A species whose presence or absence tells you about pollution levels", "A species that points the way", "Any animal in a zoo", "A plant that changes colour daily"], 0,
        "Mayfly larvae in a river show clean, well-oxygenated water.",
        "'নির্দেশক প্রজাতি' কী?", ["যে প্রজাতির থাকা বা না থাকা দূষণের মাত্রা জানায়", "যে প্রজাতি পথ দেখায়", "চিড়িয়াখানার যেকোনো প্রাণী", "যে উদ্ভিদ রোজ রং বদলায়"],
        "নদীতে মে-মাছির শূককীট পরিষ্কার, অক্সিজেন-ভরা জলের লক্ষণ।"),
    mcq("Why must concrete wash-water never be poured into a river?", ["It is strongly alkaline and full of fine particles that harm fish and invertebrates", "It is too cold", "It makes the river taste sweet", "It is good fertiliser"], 0,
        "Sites collect and treat it in settling tanks.",
        "কংক্রিট ধোয়ার জল কখনো নদীতে ঢালা উচিত নয় কেন?", ["এটা খুব ক্ষারীয় আর সূক্ষ্ম কণায় ভরা, যা মাছ আর অমেরুদণ্ডীদের ক্ষতি করে", "খুব ঠান্ডা", "নদী মিষ্টি করে", "ভালো সার"],
        "নির্মাণস্থল একে থিতানো-ট্যাঙ্কে জমিয়ে শোধন করে।"),
    mcq("What is 'bioaccumulation'?", ["A poison building up in an organism faster than it is removed, and concentrating up food chains", "Animals growing bigger", "Plants storing water", "Recycling waste"], 0,
        "Lead and mercury from old paints and industry can build up in fish-eating birds.",
        "'জৈব-সঞ্চয়ন' কী?", ["বিষ জীবের দেহে বেরোনোর চেয়ে দ্রুত জমে আর খাদ্যশৃঙ্খলে উপরে গাঢ় হয়", "প্রাণীদের বড় হওয়া", "উদ্ভিদের জল জমানো", "বর্জ্যের পুনর্ব্যবহার"],
        "পুরোনো রং আর শিল্পের সিসা ও পারদ মাছ-খেকো পাখির দেহে জমতে পারে।"),
    mcq("Why are fish passes built at weirs and some bridge foundations?", ["So migrating fish like salmon and hilsa can swim upstream to breed", "To catch fish for food", "To slow the river down", "To make the river deeper"], 0,
        "A series of small steps or pools lets fish climb past the barrier.",
        "বাঁধ আর কিছু সেতুর ভিতে মাছের সিঁড়ি বানানো হয় কেন?", ["স্যামন আর ইলিশের মতো পরিযায়ী মাছ যাতে ডিম পাড়তে উজানে যেতে পারে", "খাবারের জন্য মাছ ধরতে", "নদী ধীর করতে", "নদী গভীর করতে"],
        "ছোট ছোট ধাপ বা কুণ্ডের সারি মাছকে বাধা পেরোতে দেয়।"),
    mcq("What is 'genetic engineering' used for in medicine?", ["Putting a useful gene, such as the human insulin gene, into bacteria so they make the protein", "Building robots", "Cloning bridges", "Changing blood groups daily"], 0,
        "Most insulin used by diabetics today is made this way.",
        "চিকিৎসায় 'জিন-প্রযুক্তি' কীসের জন্য ব্যবহার হয়?", ["মানুষের ইনসুলিন-জিনের মতো কাজের জিন ব্যাকটেরিয়ায় বসানো, যাতে তারা প্রোটিনটা বানায়", "রোবট বানাতে", "সেতুর ক্লোন বানাতে", "রোজ রক্তের গ্রুপ বদলাতে"],
        "আজ ডায়াবেটিস-রোগীদের বেশিরভাগ ইনসুলিন এভাবে তৈরি।"),
    mcq("What is the job of the kidneys' nephrons?", ["Filter the blood and reabsorb useful substances, making urine from the waste", "Pump blood", "Digest proteins", "Store oxygen"], 0,
        "Drinking enough water helps them work well in hot weather.",
        "বৃক্কের নেফ্রনের কাজ কী?", ["রক্ত ছেঁকে কাজের পদার্থ ফিরিয়ে নেয়, বর্জ্য দিয়ে মূত্র বানায়", "রক্ত পাম্প করে", "প্রোটিন হজম করে", "অক্সিজেন জমায়"],
        "গরমে যথেষ্ট জল খেলে এরা ভালো কাজ করে।"),
    mcq("What does the hormone ADH do when you are short of water?", ["Makes the kidneys reabsorb more water, so urine is darker and less", "Makes you sweat more", "Speeds up the heart", "Lowers blood sugar"], 0,
        "Dark urine is a sign to drink more on a hot site.",
        "জলের অভাব হলে এডিএইচ হরমোন কী করে?", ["বৃক্ককে বেশি জল ফিরিয়ে নিতে বলে, তাই মূত্র গাঢ় আর কম হয়", "বেশি ঘাম ঝরায়", "হৃৎপিণ্ড দ্রুত করে", "রক্তে শর্করা কমায়"],
        "গাঢ় মূত্র গরম নির্মাণস্থলে বেশি জল খাওয়ার সংকেত।"),
    mcq("What is 'blood pressure'?", ["The force of blood pushing on artery walls", "The weight of blood", "The colour of blood", "How fast you breathe"], 0,
        "High blood pressure strains the heart; regular check-ups help.",
        "'রক্তচাপ' কী?", ["ধমনির দেয়ালে রক্তের ঠেলার বল", "রক্তের ওজন", "রক্তের রং", "কত দ্রুত শ্বাস নাও"],
        "উচ্চ রক্তচাপ হৃৎপিণ্ডে চাপ দেয়; নিয়মিত পরীক্ষা সাহায্য করে।"),
    mcq("Why do arteries have thick, muscular, elastic walls?", ["They carry blood at high pressure from the heart", "They carry blood slowly", "They store fat", "They carry air"], 0,
        "Veins have thinner walls and valves because pressure there is low.",
        "ধমনির দেয়াল মোটা, পেশিবহুল আর স্থিতিস্থাপক কেন?", ["হৃৎপিণ্ড থেকে উচ্চ চাপে রক্ত বয়", "ধীরে রক্ত বয়", "চর্বি জমায়", "বাতাস বয়"],
        "শিরার চাপ কম, তাই দেয়াল পাতলা আর ভালভ থাকে।"),
    mcq("What does 'coronary heart disease' involve?", ["Fatty deposits narrowing the arteries that supply the heart muscle", "A broken rib", "Too many red blood cells", "A heart that is too big from exercise"], 0,
        "Smoking, poor diet and lack of exercise raise the risk.",
        "'করোনারি হৃদরোগে' কী হয়?", ["হৃৎপেশিতে রক্ত জোগানো ধমনি চর্বির স্তরে সরু হয়ে যায়", "পাঁজর ভাঙা", "অতিরিক্ত লোহিতকণিকা", "ব্যায়ামে হৃৎপিণ্ড বেশি বড়"],
        "ধূমপান, খারাপ খাদ্য আর ব্যায়ামের অভাব ঝুঁকি বাড়ায়।"),
    mcq("What is a 'stent'?", ["A small mesh tube placed in a narrowed artery to keep it open", "A type of bandage", "A bone screw", "A heart valve made of wood"], 0,
        "Like a tiny scaffold - engineering inside the body.",
        "'স্টেন্ট' কী?", ["সরু হয়ে যাওয়া ধমনিতে বসানো ছোট জালের নল, যা তাকে খোলা রাখে", "এক রকম ব্যান্ডেজ", "হাড়ের স্ক্রু", "কাঠের হৃৎ-ভালভ"],
        "এক টুকরো ছোট ভারা - শরীরের ভেতরে প্রকৌশল।"),
    mcq("Why are artificial hip joints often made of titanium or cobalt-chrome?", ["They are strong, hard-wearing and do not corrode or react with body fluids", "They are magnetic", "They are the cheapest metals", "They dissolve over time"], 0,
        "Choosing materials for the body is like choosing them for a bridge in the sea.",
        "কৃত্রিম নিতম্ব-সন্ধি প্রায়ই টাইটানিয়াম বা কোবাল্ট-ক্রোমে তৈরি কেন?", ["শক্ত, টেকসই, আর দেহরসে ক্ষয় হয় না বা বিক্রিয়া করে না", "চৌম্বক", "সবচেয়ে সস্তা ধাতু", "সময়ের সঙ্গে গলে যায়"],
        "শরীরের জন্য উপাদান বাছা সমুদ্রের সেতুর জন্য বাছার মতোই।"),
    mcq("What is a 'control group' in a medical trial?", ["A group that does not get the new treatment, for comparison", "The doctors running the trial", "People who control the hospital", "Patients who get double doses"], 0,
        "Without a control, you cannot tell if the treatment made the difference.",
        "চিকিৎসার পরীক্ষায় 'নিয়ন্ত্রণ-দল' কী?", ["যে দল নতুন চিকিৎসা পায় না, তুলনার জন্য", "পরীক্ষা চালানো ডাক্তাররা", "হাসপাতাল নিয়ন্ত্রণ করা লোকেরা", "দ্বিগুণ মাত্রা পাওয়া রোগী"],
        "নিয়ন্ত্রণ না থাকলে বোঝা যায় না চিকিৎসাতেই পার্থক্য হলো কিনা।"),
    mcq("What is a 'double-blind' trial?", ["Neither patients nor doctors know who gets the real treatment until the end", "Patients wear blindfolds", "Only blind people take part", "Results are hidden forever"], 0,
        "It stops expectations from biasing the results.",
        "'দ্বি-অন্ধ' পরীক্ষা কী?", ["শেষ পর্যন্ত রোগী বা ডাক্তার কেউই জানেন না কে আসল চিকিৎসা পাচ্ছেন", "রোগীরা চোখ বাঁধেন", "শুধু দৃষ্টিহীনরা অংশ নেন", "ফলাফল চিরকাল লুকোনো"],
        "প্রত্যাশা যাতে ফলাফলে পক্ষপাত না আনে।"),
)
