"""Class 9 - Biology (Bridge Engineer cadet): aerobic and anaerobic respiration in depth (ATP,
mitochondria, oxygen debt), breathing and ventilation, energy in food, enzymes and their optimum
conditions, surface area to volume ratio, active transport, homeostasis, the eye and colour
vision for signal work, the brain, plant defences, food security and fair, safe science."""
from . import mcq


def _o(r, *alts):
    out = []
    for x in (r, *alts, r + 1, r + 2, r * 2, r + 10):
        if x not in out and x > 0:
            out.append(x)
    return out[:4]


def _n(q_en, q_bn, r, ex_en, ex_bn, alts, u_en="", u_bn=None):
    f = lambda x: f"{x:,}" if isinstance(x, int) else f"{x:g}"
    o = _o(r, *alts)
    ub = u_en if u_bn is None else u_bn
    return mcq(q_en, [f(x) + u_en for x in o], 0, ex_en, q_bn, [f(x) + ub for x in o], ex_bn)


def _c(x):
    x = round(x, 2)
    return int(x) if x == int(x) else x


def vent(rate, vol):
    r = rate * vol
    return _n(f"A worker climbing bridge stairs breathes {rate} times a minute, taking in {vol} ml each breath. What is their ventilation rate?",
              f"সেতুর সিঁড়ি চড়া একজন কর্মী মিনিটে {rate} বার শ্বাস নেন, প্রতি শ্বাসে {vol} ml। শ্বাসবায়ু-প্রবাহের হার কত?", r,
              f"Ventilation = breaths per minute x volume per breath = {rate} x {vol} = {r:,} ml per minute.",
              f"শ্বাসবায়ু-প্রবাহ = মিনিটে শ্বাস x প্রতি শ্বাসের আয়তন = {rate} x {vol} = মিনিটে {r:,} ml।",
              (rate + vol, _c(vol / rate), r * 60), " ml/min", " ml/মিনিট")


def foodkj(per100, grams, food_en, food_bn):
    r = per100 * grams // 100
    return _n(f"{food_en} provides {per100:,} kJ per 100 g. How much energy is in a {grams} g portion?",
              f"{food_bn} প্রতি 100 g-এ {per100:,} kJ শক্তি দেয়। {grams} g-এর এক ভাগে কত শক্তি?", r,
              f"{per100:,} x {grams} ÷ 100 = {r:,} kJ.",
              f"{per100:,} x {grams} ÷ 100 = {r:,} kJ।",
              (per100 * grams, per100 + grams, _c(per100 / grams * 100)), " kJ")


def sav(n):
    r = _c(6 / n)
    return _n(f"A cube-shaped cell model has sides of {n} cm. What is its surface area to volume ratio?",
              f"ঘনক-আকারের একটা কোষ-মডেলের বাহু {n} cm। এর পৃষ্ঠতল আর আয়তনের অনুপাত কত?", r,
              f"Surface area = 6 x {n}² = {6 * n * n}; volume = {n}³ = {n ** 3}; ratio = {6 * n * n} ÷ {n ** 3} = {r:g} : 1. Bigger objects have smaller ratios.",
              f"পৃষ্ঠতল = 6 x {n}² = {6 * n * n}; আয়তন = {n}³ = {n ** 3}; অনুপাত = {6 * n * n} ÷ {n ** 3} = {r:g} : 1। বড় বস্তুর অনুপাত ছোট।",
              (_c(n / 6), 6 * n, _c(n * n / 6)), " : 1")


def enzrate(t):
    r = _c(1000 / t)
    return _n(f"An enzyme takes {t} s to break down a starch sample. Using rate = 1000 ÷ time, what is the rate?",
              f"একটা এনজাইম একটা শ্বেতসার-নমুনা ভাঙতে {t} s নেয়। হার = 1000 ÷ সময় ধরে হার কত?", r,
              f"Rate = 1000 ÷ {t} = {r:g} (arbitrary units per second). Shorter time means faster rate.",
              f"হার = 1000 ÷ {t} = {r:g} (প্রতি সেকেন্ডে যেকোনো একক)। কম সময় মানে দ্রুত হার।",
              (t, _c(t / 1000 * 100), _c(r * 10)))


def sweat(before, after, hours):
    lost = _c(before - after)
    r = _c(lost / hours)
    return _n(f"A worker weighs {before:g} kg before a {hours}-hour shift in the heat and {after:g} kg after, having drunk nothing. Roughly how many litres of water were lost per hour?",
              f"গরমে {hours} ঘণ্টার পালার আগে একজন কর্মীর ওজন {before:g} kg আর পরে {after:g} kg, কিছুই খাননি-পান করেননি। ঘণ্টায় মোটামুটি কত লিটার জল হারিয়েছেন?", r,
              f"Mass lost = {lost:g} kg ≈ {lost:g} litres of water; ÷ {hours} = {r:g} litres per hour - so drink regularly!",
              f"হারানো ভর = {lost:g} kg ≈ {lost:g} লিটার জল; ÷ {hours} = ঘণ্টায় {r:g} লিটার - তাই নিয়মিত জল খাও!",
              (lost, _c(lost * hours), _c(r + 1)), " L", " লিটার")


def repeats(vals, anomaly, what_en, what_bn):
    good = [v for v in vals if v != anomaly]
    m = _c(sum(good) / len(good))
    allm = _c(sum(vals) / len(vals))
    return _n(f"{what_en}: {', '.join(map(str, vals))}. Ignoring the anomalous result, what is the mean?",
              f"{what_bn}: {', '.join(map(str, vals))}। অস্বাভাবিক ফলটা বাদ দিয়ে গড় কত?", m,
              f"{anomaly} does not fit the pattern; mean of the rest = {sum(good)} ÷ {len(good)} = {m:g}.",
              f"{anomaly} নকশার সঙ্গে মেলে না; বাকিগুলোর গড় = {sum(good)} ÷ {len(good)} = {m:g}।",
              (allm, anomaly, max(good)))


def pctchange(a, b, what_en, what_bn):
    r = _c((b - a) * 100 / a)
    return _n(f"{what_en} rose from {a} to {b} beats per minute during heavy lifting. What is the percentage increase?",
              f"ভারী বোঝা তোলার সময় {what_bn} মিনিটে {a} থেকে বেড়ে {b} হলো। শতাংশ বৃদ্ধি কত?", r,
              f"({b} - {a}) ÷ {a} x 100 = {r:g}%.",
              f"({b} - {a}) ÷ {a} x 100 = {r:g}%।",
              (b - a, _c((b - a) * 100 / b), _c(b * 100 / a)), "%")


ITEMS = (
    vent(12, 500), vent(20, 800), vent(30, 1200), vent(16, 600),
    foodkj(1500, 80, "Rice", "ভাত"), foodkj(2200, 50, "Peanuts", "চিনেবাদাম"), foodkj(350, 200, "Dal", "ডাল"),
    foodkj(1100, 120, "Bread", "রুটি"), foodkj(250, 150, "A banana", "একটা কলা"),
    sav(1), sav(2), sav(3), sav(6),
    enzrate(50), enzrate(80), enzrate(125), enzrate(40),
    sweat(70, 68.5, 3), sweat(80, 77.6, 4), sweat(66, 64.2, 2),
    repeats([24, 25, 23, 41, 24], 41, "Five timings of a reaction (s)", "একটা বিক্রিয়ার পাঁচবার সময় (s)"),
    repeats([12, 13, 30, 11], 30, "Bubbles counted per minute", "মিনিটে গোনা বুদবুদ"),
    repeats([8, 2, 9, 7, 8], 2, "Beetles per quadrat", "প্রতি কোয়াড্র্যাটে গুবরে পোকা"),
    pctchange(70, 105, "A rigger's pulse", "একজন রিগারের নাড়ি"), pctchange(60, 84, "A welder's pulse", "একজন ঝালাইকারের নাড়ি"),
    pctchange(80, 140, "A labourer's pulse", "একজন শ্রমিকের নাড়ি"), pctchange(72, 90, "A painter's pulse", "একজন রং-মিস্ত্রির নাড়ি"),
    vent(18, 700), foodkj(1700, 60, "Chapati", "রুটি (চাপাটি)"), sav(4), sav(10), enzrate(25),
    mcq("What is the word equation for aerobic respiration?", ["Glucose + oxygen -> carbon dioxide + water (+ energy)", "Carbon dioxide + water -> glucose + oxygen", "Glucose -> lactic acid", "Oxygen + water -> glucose"], 0,
        "It happens all the time in every living cell.",
        "সবাত শ্বসনের শব্দ-সমীকরণ কী?", ["গ্লুকোজ + অক্সিজেন -> কার্বন ডাইঅক্সাইড + জল (+ শক্তি)", "কার্বন ডাইঅক্সাইড + জল -> গ্লুকোজ + অক্সিজেন", "গ্লুকোজ -> ল্যাকটিক অ্যাসিড", "অক্সিজেন + জল -> গ্লুকোজ"],
        "প্রতিটা জীবিত কোষে সবসময় ঘটে।"),
    mcq("Where in the cell does most aerobic respiration happen?", ["In the mitochondria", "In the nucleus", "In the cell wall", "In the chloroplasts"], 0,
        "Muscle cells that work hard are packed with mitochondria.",
        "কোষের কোথায় বেশিরভাগ সবাত শ্বসন হয়?", ["মাইটোকন্ড্রিয়ায়", "নিউক্লিয়াসে", "কোষপ্রাচীরে", "ক্লোরোপ্লাস্টে"],
        "কঠোর পরিশ্রমী পেশিকোষ মাইটোকন্ড্রিয়ায় ঠাসা।"),
    mcq("What is ATP?", ["The molecule that carries energy from respiration to where cells need it", "A type of fat", "A hormone", "A blood cell"], 0,
        "Muscle contraction, building proteins and active transport all use ATP.",
        "এটিপি কী?", ["যে অণু শ্বসনের শক্তি কোষের দরকারি জায়গায় বয়ে নেয়", "এক রকম চর্বি", "একটা হরমোন", "একটা রক্তকণিকা"],
        "পেশির সংকোচন, প্রোটিন তৈরি আর সক্রিয় পরিবহন সবই এটিপি ব্যবহার করে।"),
    mcq("Why does aerobic respiration release much more energy than anaerobic respiration?", ["Glucose is broken down completely to CO2 and water, instead of only partly to lactic acid", "Anaerobic uses more glucose per second only", "Oxygen contains energy", "It happens in sunlight"], 0,
        "Aerobic gives roughly 19 times more ATP per glucose.",
        "সবাত শ্বসন অবাত শ্বসনের চেয়ে অনেক বেশি শক্তি দেয় কেন?", ["গ্লুকোজ পুরোপুরি CO2 আর জলে ভাঙে, শুধু আংশিক ল্যাকটিক অ্যাসিডে নয়", "অবাত শুধু সেকেন্ডে বেশি গ্লুকোজ খরচ করে", "অক্সিজেনে শক্তি থাকে", "সূর্যালোকে ঘটে"],
        "সবাত শ্বসনে প্রতি গ্লুকোজে প্রায় 19 গুণ বেশি এটিপি মেলে।"),
    mcq("What is 'oxygen debt' after heavy work?", ["Extra oxygen needed afterwards to break down lactic acid built up during anaerobic respiration", "Owing money for oxygen", "Breathing less after exercise", "Oxygen stored in muscles"], 0,
        "That is why you keep panting after carrying loads up a ladder.",
        "ভারী কাজের পরে 'অক্সিজেন-ঋণ' কী?", ["অবাত শ্বসনে জমা ল্যাকটিক অ্যাসিড ভাঙতে পরে লাগা বাড়তি অক্সিজেন", "অক্সিজেনের জন্য টাকা ধার", "ব্যায়ামের পরে কম শ্বাস", "পেশিতে জমা অক্সিজেন"],
        "তাই মই বেয়ে বোঝা তোলার পরেও হাঁপাতে থাকো।"),
    mcq("What do yeast cells produce in anaerobic respiration (fermentation)?", ["Ethanol and carbon dioxide", "Lactic acid only", "Oxygen and water", "Glucose"], 0,
        "Bakers use the CO2; brewers use the ethanol.",
        "অবাত শ্বসনে (সন্ধান) ইস্ট-কোষ কী তৈরি করে?", ["ইথানল আর কার্বন ডাইঅক্সাইড", "শুধু ল্যাকটিক অ্যাসিড", "অক্সিজেন আর জল", "গ্লুকোজ"],
        "রুটিওয়ালারা CO2 কাজে লাগান; মদ্য-প্রস্তুতকারীরা ইথানল।"),
    mcq("What is 'metabolic rate'?", ["The rate at which all the chemical reactions in the body use energy", "The speed of running", "Heart rate only", "The number of meals a day"], 0,
        "Physical work raises it, so workers need more food energy.",
        "'বিপাকীয় হার' কী?", ["শরীরের সব রাসায়নিক বিক্রিয়া যে হারে শক্তি খরচ করে", "দৌড়ের গতি", "শুধু হৃৎস্পন্দন", "দিনে কতবার খাওয়া"],
        "শারীরিক শ্রম এটা বাড়ায়, তাই কর্মীদের বেশি খাদ্য-শক্তি লাগে।"),
    mcq("During heavy work, why do breathing rate and depth increase?", ["To supply more oxygen and remove more carbon dioxide from respiring muscles", "To cool the brain only", "To make the voice louder", "Because the lungs get smaller"], 0,
        "Heart rate rises too, to carry oxygen faster.",
        "ভারী কাজের সময় শ্বাসের হার আর গভীরতা বাড়ে কেন?", ["শ্বসনরত পেশিতে বেশি অক্সিজেন জোগাতে আর বেশি কার্বন ডাইঅক্সাইড সরাতে", "শুধু মস্তিষ্ক ঠান্ডা করতে", "গলার আওয়াজ জোরে করতে", "কারণ ফুসফুস ছোট হয়"],
        "অক্সিজেন দ্রুত বইতে হৃৎস্পন্দনও বাড়ে।"),
    mcq("How does regular exercise change a person's resting heart rate?", ["It usually lowers it, because a stronger heart pumps more blood per beat", "It raises it permanently", "It stops the heart", "It has no effect"], 0,
        "Fit workers recover faster after hard tasks.",
        "নিয়মিত ব্যায়াম মানুষের বিশ্রামকালীন হৃৎস্পন্দন কীভাবে বদলায়?", ["সাধারণত কমায়, কারণ শক্ত হৃৎপিণ্ড প্রতি স্পন্দনে বেশি রক্ত পাম্প করে", "চিরকালের জন্য বাড়ায়", "হৃৎপিণ্ড থামায়", "কোনো প্রভাব নেই"],
        "সুস্থ কর্মীরা কঠিন কাজের পরে দ্রুত সেরে ওঠেন।"),
    mcq("What is an enzyme?", ["A biological catalyst, usually a protein, that speeds up reactions", "A type of fat", "A hormone that controls growth", "A cell wall"], 0,
        "Each enzyme fits its substrate like a key in a lock.",
        "এনজাইম কী?", ["জৈব অনুঘটক, সাধারণত প্রোটিন, যা বিক্রিয়া দ্রুত করে", "এক রকম চর্বি", "বৃদ্ধি নিয়ন্ত্রক হরমোন", "কোষপ্রাচীর"],
        "প্রতিটা এনজাইম তার বিক্রিয়কে তালায় চাবির মতো খাপ খায়।"),
    mcq("What is the 'active site' of an enzyme?", ["The region where the substrate fits and the reaction happens", "The enzyme's nucleus", "Its outer skin", "A place in the stomach"], 0,
        "Its exact shape decides which substrate it works on.",
        "এনজাইমের 'সক্রিয় স্থান' কী?", ["যে অংশে বিক্রিয়ক খাপ খায় আর বিক্রিয়া ঘটে", "এনজাইমের নিউক্লিয়াস", "এর বাইরের চামড়া", "পাকস্থলীর একটা জায়গা"],
        "এর ঠিক আকারই ঠিক করে কোন বিক্রিয়কে কাজ করবে।"),
    mcq("Why does an enzyme stop working above about 45°C?", ["Heat changes the shape of its active site - it becomes denatured", "It falls asleep", "It turns into sugar", "Heat makes it work twice as fast forever"], 0,
        "Body temperature is kept near 37°C, where human enzymes work best.",
        "প্রায় 45°C-এর উপরে এনজাইম কাজ বন্ধ করে কেন?", ["তাপে এর সক্রিয় স্থানের আকার বদলে যায় - এটা বিকৃত হয়", "ঘুমিয়ে পড়ে", "চিনি হয়ে যায়", "তাপে চিরকাল দ্বিগুণ দ্রুত কাজ করে"],
        "শরীরের তাপমাত্রা প্রায় 37°C রাখা হয়, যেখানে মানুষের এনজাইম সবচেয়ে ভালো কাজ করে।"),
    mcq("Pepsin works best at pH 2. Where in the body does it work?", ["In the stomach, which is acidic", "In the mouth", "In the small intestine, which is alkaline", "In the blood"], 0,
        "Each enzyme has an optimum pH as well as an optimum temperature.",
        "পেপসিন pH 2-এ সবচেয়ে ভালো কাজ করে। শরীরের কোথায় এটা কাজ করে?", ["পাকস্থলীতে, যা অম্লীয়", "মুখে", "ক্ষুদ্রান্ত্রে, যা ক্ষারীয়", "রক্তে"],
        "প্রতিটা এনজাইমের আদর্শ তাপমাত্রার মতো আদর্শ pH-ও আছে।"),
    mcq("Why do biological washing powders work well at 40°C but poorly at 90°C?", ["Their enzymes are denatured at high temperature", "Water is wetter at 40°C", "Clothes shrink", "Soap needs boiling water"], 0,
        "Lower washing temperatures also save energy.",
        "জৈব কাপড়-কাচার গুঁড়ো 40°C-এ ভালো কাজ করে, 90°C-এ খারাপ কেন?", ["উচ্চ তাপমাত্রায় এদের এনজাইম বিকৃত হয়", "40°C-এ জল বেশি ভেজা", "কাপড় ছোট হয়", "সাবানে ফুটন্ত জল লাগে"],
        "কম তাপমাত্রায় কাচলে শক্তিও বাঁচে।"),
    mcq("Why do small organisms rely on diffusion through their surface, while large ones need lungs and blood?", ["Large organisms have a small surface area compared with their volume", "Large organisms are lazy", "Small organisms need no oxygen", "Diffusion only works in water"], 0,
        "Bridges face the same scaling: big structures need special systems for drainage and ventilation.",
        "ছোট জীব তার তল দিয়ে ব্যাপনের উপর নির্ভর করে, অথচ বড়দের ফুসফুস আর রক্ত লাগে কেন?", ["বড় জীবের আয়তনের তুলনায় পৃষ্ঠতল ছোট", "বড় জীব অলস", "ছোট জীবের অক্সিজেন লাগে না", "ব্যাপন শুধু জলে কাজ করে"],
        "সেতুতেও একই মাপের সমস্যা: বড় কাঠামোয় জলনিকাশ আর বায়ুচলাচলের বিশেষ ব্যবস্থা লাগে।"),
    mcq("What is 'active transport'?", ["Moving substances against a concentration gradient using energy from respiration", "Diffusion from high to low concentration", "Movement of water only", "Breathing"], 0,
        "Root hair cells use it to take in mineral ions from dilute soil water.",
        "'সক্রিয় পরিবহন' কী?", ["শ্বসনের শক্তি ব্যবহার করে গাঢ়ত্বের ঢালের বিরুদ্ধে পদার্থ সরানো", "বেশি থেকে কম গাঢ়ত্বে ব্যাপন", "শুধু জলের চলাচল", "শ্বাস নেওয়া"],
        "মূলরোম কোষ পাতলা মাটির জল থেকে খনিজ আয়ন নিতে এটা ব্যবহার করে।"),
    mcq("Why is a core body temperature above about 40°C so dangerous?", ["Enzymes start to denature, so vital reactions in cells go wrong", "Blood turns solid", "Bones melt", "The heart stops needing oxygen"], 0,
        "Heat stroke is a medical emergency - cool the person and call for help.",
        "শরীরের ভেতরের তাপমাত্রা প্রায় 40°C ছাড়ালে এত বিপজ্জনক কেন?", ["এনজাইম বিকৃত হতে শুরু করে, তাই কোষের জরুরি বিক্রিয়া বিগড়ে যায়", "রক্ত জমে কঠিন হয়", "হাড় গলে", "হৃৎপিণ্ডের আর অক্সিজেন লাগে না"],
        "হিটস্ট্রোক জরুরি অবস্থা - মানুষটাকে ঠান্ডা করো আর সাহায্য ডাকো।"),
    mcq("In a test of how temperature affects an enzyme's speed, which is the independent variable?", ["The temperature", "The time taken", "The volume of enzyme", "The type of test tube"], 0,
        "The independent variable is the one you deliberately change.",
        "তাপমাত্রা এনজাইমের গতিতে কী প্রভাব ফেলে তার পরীক্ষায় স্বাধীন চলরাশি কোনটা?", ["তাপমাত্রা", "লাগা সময়", "এনজাইমের আয়তন", "টেস্ট-টিউবের ধরন"],
        "স্বাধীন চলরাশি হলো যেটা তুমি ইচ্ছে করে বদলাও।"),
    mcq("Which gas, building up in the blood during hard work, is mainly detected by the brain to make you breathe faster?", ["Carbon dioxide", "Oxygen", "Nitrogen", "Argon"], 0,
        "Receptors detect the rising CO2 and the medulla speeds up breathing.",
        "কঠোর পরিশ্রমে রক্তে জমা কোন গ্যাস মস্তিষ্ক প্রধানত ধরে শ্বাস দ্রুত করায়?", ["কার্বন ডাইঅক্সাইড", "অক্সিজেন", "নাইট্রোজেন", "আর্গন"],
        "গ্রাহক বাড়তি CO2 ধরে আর মেডুলা শ্বাস দ্রুত করে।"),
    mcq("During a long shift without food, where does the body first get extra glucose from?", ["Glycogen stored in the liver and muscles", "Bones", "Hair", "Stored oxygen"], 0,
        "When glycogen runs low, tiredness and poor concentration follow - take meal breaks.",
        "খাবার ছাড়া দীর্ঘ পালায় শরীর প্রথমে বাড়তি গ্লুকোজ কোথা থেকে পায়?", ["যকৃৎ আর পেশিতে জমা গ্লাইকোজেন থেকে", "হাড় থেকে", "চুল থেকে", "জমা অক্সিজেন থেকে"],
        "গ্লাইকোজেন কমলে ক্লান্তি আর মনোযোগের অভাব আসে - খাবারের বিরতি নাও।"),
    mcq("Why do many plants close their stomata on hot, dry afternoons?", ["To reduce water loss by transpiration", "To take in more carbon dioxide", "To let insects in", "To grow faster"], 0,
        "The trade-off: less CO2 enters, so photosynthesis slows.",
        "গরম, শুকনো দুপুরে অনেক উদ্ভিদ পত্ররন্ধ্র বন্ধ করে কেন?", ["প্রস্বেদনে জল হারানো কমাতে", "বেশি কার্বন ডাইঅক্সাইড নিতে", "পোকা ঢোকাতে", "দ্রুত বাড়তে"],
        "বিনিময়ে: কম CO2 ঢোকে, তাই সালোকসংশ্লেষ ধীর হয়।"),
    mcq("What do guard cells do?", ["Change shape to open and close the stomata in a leaf", "Guard the roots from insects", "Carry sugar", "Make seeds"], 0,
        "They swell with water to open the pore and go limp to close it.",
        "রক্ষীকোষ কী করে?", ["আকার বদলে পাতার পত্ররন্ধ্র খোলে আর বন্ধ করে", "শিকড়কে পোকা থেকে রক্ষা করে", "শর্করা বয়", "বীজ বানায়"],
        "জলে ফুলে রন্ধ্র খোলে আর নেতিয়ে বন্ধ করে।"),
    mcq("Why can de-icing salt spread on a bridge harm the plants along its approach road?", ["Salty soil water draws water out of root cells by osmosis", "Salt is food for weeds only", "Salt makes the soil too warm", "Plants like salt"], 0,
        "Salt-tolerant species are chosen for verges in cold regions.",
        "সেতুতে ছড়ানো বরফ-গলানো নুন সংযোগ-রাস্তার পাশের গাছের ক্ষতি করতে পারে কেন?", ["নোনা মাটির জল অভিস্রবণে শিকড়ের কোষ থেকে জল টেনে নেয়", "নুন শুধু আগাছার খাদ্য", "নুন মাটি খুব গরম করে", "গাছ নুন পছন্দ করে"],
        "ঠান্ডা অঞ্চলে রাস্তার ধারে নুন-সহনশীল প্রজাতি বাছা হয়।"),
    mcq("Why can't hearing lost from years of loud site noise be cured?", ["The tiny hair cells in the cochlea that detect sound are destroyed and do not grow back", "The eardrum heals too slowly", "Noise blocks the ear with wax", "It always comes back by itself"], 0,
        "Ear protection is the only protection.",
        "বছরের পর বছর নির্মাণস্থলের জোরালো শব্দে হারানো শ্রবণশক্তি সারানো যায় না কেন?", ["শব্দ-ধরা ককলিয়ার খুদে লোমকোষ নষ্ট হয়ে যায় আর আবার গজায় না", "কানের পর্দা খুব ধীরে সারে", "শব্দ কানে খোল জমায়", "সবসময় নিজে ফিরে আসে"],
        "কানের সুরক্ষাই একমাত্র সুরক্ষা।"),
    mcq("What causes malaria?", ["A single-celled parasite (Plasmodium) passed on by the bite of infected mosquitoes", "A virus in drinking water", "Eating spicy food", "Cold weather"], 0,
        "Nets, repellents and clearing standing water all reduce the risk.",
        "ম্যালেরিয়া কী থেকে হয়?", ["সংক্রমিত মশার কামড়ে ছড়ানো এককোষী পরজীবী (প্লাসমোডিয়াম)", "খাবার জলে ভাইরাস", "ঝাল খাবার", "ঠান্ডা আবহাওয়া"],
        "মশারি, প্রতিরোধক আর জমা জল সরানো সবই ঝুঁকি কমায়।"),
    mcq("How does cholera usually spread in a work camp?", ["Through water or food contaminated with faeces from infected people", "Through the air when people talk", "By touching steel", "Through mosquito bites"], 0,
        "Safe drinking water and proper toilets prevent outbreaks.",
        "একটা শ্রমিক-শিবিরে কলেরা সাধারণত কীভাবে ছড়ায়?", ["সংক্রমিতদের মলে দূষিত জল বা খাবারের মাধ্যমে", "কথা বলার সময় বাতাসে", "ইস্পাত ছুঁলে", "মশার কামড়ে"],
        "নিরাপদ খাবার জল আর ঠিকঠাক শৌচাগার প্রাদুর্ভাব আটকায়।"),
    mcq("What is ORS, given to a worker with severe diarrhoea?", ["Oral rehydration solution - water with the right amounts of salt and sugar to replace lost fluid", "An antibiotic injection", "A painkiller", "A type of energy drink only"], 0,
        "It has saved millions of lives by preventing dehydration.",
        "তীব্র উদরাময়ে আক্রান্ত কর্মীকে দেওয়া ওআরএস কী?", ["মুখে খাওয়ার জলশূন্যতা-রোধী দ্রবণ - হারানো তরল পূরণে ঠিক পরিমাণ নুন আর চিনিসহ জল", "অ্যান্টিবায়োটিক ইঞ্জেকশন", "ব্যথানাশক", "শুধু এক রকম এনার্জি-পানীয়"],
        "জলশূন্যতা ঠেকিয়ে এটা লক্ষ লক্ষ প্রাণ বাঁচিয়েছে।"),
    mcq("Besides insulin, what does the pancreas make?", ["Digestive enzymes such as amylase, protease and lipase", "Bile", "Red blood cells", "Urine"], 0,
        "They are released into the small intestine.",
        "ইনসুলিন ছাড়া অগ্ন্যাশয় আর কী বানায়?", ["অ্যামাইলেজ, প্রোটিয়েজ আর লাইপেজের মতো পাচক এনজাইম", "পিত্ত", "লোহিতকণিকা", "মূত্র"],
        "এগুলো ক্ষুদ্রান্ত্রে ছাড়া হয়।"),
    mcq("Why must chicken and rice in a site canteen be cooked thoroughly and kept hot?", ["Heat kills bacteria such as Salmonella, and warm food left out lets bacteria multiply", "Cooking adds vitamins", "Cold food is illegal", "To make it heavier"], 0,
        "Keep hot food hot and cold food cold.",
        "নির্মাণস্থলের ক্যান্টিনে মুরগি আর ভাত ভালো করে রান্না করে গরম রাখতে হয় কেন?", ["তাপ সালমোনেলার মতো ব্যাকটেরিয়া মারে, আর বাইরে পড়ে থাকা গরম খাবারে ব্যাকটেরিয়া বাড়ে", "রান্না ভিটামিন যোগ করে", "ঠান্ডা খাবার বেআইনি", "ভারী করতে"],
        "গরম খাবার গরম আর ঠান্ডা খাবার ঠান্ডা রাখো।"),
    mcq("What is 'cross-contamination' in a kitchen?", ["Bacteria spreading from raw food to ready-to-eat food, for example by a shared knife", "Two cooks arguing", "Mixing spices", "Cooking two meals at once"], 0,
        "Use separate boards and wash hands and tools.",
        "রান্নাঘরে 'আড়াআড়ি-দূষণ' কী?", ["কাঁচা খাবার থেকে খাওয়ার-জন্য-তৈরি খাবারে ব্যাকটেরিয়া ছড়ানো, যেমন একই ছুরিতে", "দুজন রাঁধুনির ঝগড়া", "মশলা মেশানো", "একসঙ্গে দুটো খাবার রান্না"],
        "আলাদা বোর্ড ব্যবহার করো আর হাত ও সরঞ্জাম ধোও।"),
    mcq("What is the job of the semicircular canals in the inner ear?", ["They detect head movement and help keep balance", "They detect sound pitch", "They make ear wax", "They carry blood to the brain"], 0,
        "Fluid moving inside them signals which way the head is turning.",
        "ভেতরের কানের অর্ধবৃত্তাকার নালীর কাজ কী?", ["মাথার নড়াচড়া ধরে আর ভারসাম্য রাখতে সাহায্য করে", "শব্দের তীক্ষ্ণতা ধরে", "কানের খোল বানায়", "মস্তিষ্কে রক্ত বয়"],
        "এর ভেতরে তরলের নড়াচড়া জানায় মাথা কোন দিকে ঘুরছে।"),
    mcq("Why does alcohol slow a crane driver's reactions?", ["It slows the passing of impulses across synapses in the nervous system", "It speeds up the heart only", "It sharpens eyesight", "It has no effect on nerves"], 0,
        "Zero alcohol is the only safe level for machine operators.",
        "মদ ক্রেন-চালকের প্রতিক্রিয়া ধীর করে কেন?", ["স্নায়ুতন্ত্রে সিন্যাপস পেরিয়ে আবেগ চলাচল ধীর করে", "শুধু হৃৎস্পন্দন দ্রুত করে", "দৃষ্টি তীক্ষ্ণ করে", "স্নায়ুতে প্রভাব নেই"],
        "যন্ত্র-চালকের জন্য একমাত্র নিরাপদ মাত্রা শূন্য।"),
    mcq("What does an insect's exoskeleton have in common with a steel tube column?", ["Both put strong material on the outside, giving stiffness for little weight", "Both are made of steel", "Both are alive", "Both are filled with water"], 0,
        "Material far from the centre resists bending best.",
        "পোকার বহিঃকঙ্কাল আর ইস্পাতের নল-থামের মধ্যে কী মিল?", ["দুটোই শক্ত উপাদান বাইরে রাখে, অল্প ওজনে দৃঢ়তা দেয়", "দুটোই ইস্পাতের", "দুটোই জীবিত", "দুটোই জলে ভরা"],
        "কেন্দ্র থেকে দূরের উপাদান বাঁকানো সবচেয়ে ভালো রোধ করে।"),
    mcq("Why is the honeycomb of bees admired by engineers?", ["Its hexagonal cells use the least wax for a strong, space-filling structure", "It is made of steel", "It is round", "It is always cold"], 0,
        "Honeycomb panels make light, stiff aircraft floors and bridge decks.",
        "মৌমাছির মৌচাক প্রকৌশলীদের প্রশংসা পায় কেন?", ["এর ষড়ভুজ কুঠুরি সবচেয়ে কম মোমে মজবুত, ফাঁকহীন কাঠামো বানায়", "ইস্পাত দিয়ে তৈরি", "গোল", "সবসময় ঠান্ডা"],
        "মৌচাক-প্যানেল হালকা, শক্ত বিমানের মেঝে আর সেতুর পাটাতন বানায়।"),
    mcq("Why do trees grow 'reaction wood' on the side facing strong winds or slopes?", ["Extra wood forms where stress is greatest, strengthening the trunk where it is needed", "To look different", "Because of insects", "It grows randomly"], 0,
        "Engineers copy this idea by adding material only where stresses are high.",
        "জোর হাওয়া বা ঢালের দিকে গাছ 'প্রতিক্রিয়া-কাঠ' বাড়ায় কেন?", ["যেখানে পীড়ন সবচেয়ে বেশি, সেখানে বাড়তি কাঠ জন্মে, দরকারি জায়গায় কাণ্ড শক্ত করে", "আলাদা দেখাতে", "পোকার জন্য", "এলোমেলোভাবে জন্মায়"],
        "প্রকৌশলীরা শুধু উচ্চ পীড়নের জায়গায় উপাদান যোগ করে এই ভাবনা নকল করেন।"),
    mcq("What is the main job of the large intestine?", ["Absorbing water from undigested food", "Digesting protein", "Making insulin", "Pumping blood"], 0,
        "Fibre in the diet helps it work well.",
        "বৃহদন্ত্রের প্রধান কাজ কী?", ["অপাচিত খাবার থেকে জল শোষণ", "প্রোটিন হজম", "ইনসুলিন তৈরি", "রক্ত পাম্প"],
        "খাবারের আঁশ একে ভালো কাজ করতে সাহায্য করে।"),
    mcq("What is 'negative feedback' in the body?", ["A change triggers a response that brings conditions back towards normal", "A change that keeps getting bigger", "Criticism from a coach", "A broken sensor"], 0,
        "If you overheat, sweating cools you back down.",
        "শরীরে 'ঋণাত্মক প্রতিক্রিয়া' কী?", ["একটা বদল এমন সাড়া জাগায় যা অবস্থাকে আবার স্বাভাবিকের দিকে ফেরায়", "যে বদল বাড়তেই থাকে", "কোচের সমালোচনা", "ভাঙা সেন্সর"],
        "বেশি গরম হলে ঘাম ঝরে আবার ঠান্ডা করে।"),
    mcq("Which part of the brain monitors and controls body temperature?", ["The hypothalamus", "The cerebellum", "The spinal cord", "The retina"], 0,
        "It receives signals from temperature receptors in the skin and blood.",
        "মস্তিষ্কের কোন অংশ শরীরের তাপমাত্রা নজরে রাখে আর নিয়ন্ত্রণ করে?", ["হাইপোথ্যালামাস", "সেরিবেলাম", "সুষুম্নাকাণ্ড", "রেটিনা"],
        "এটা চামড়া আর রক্তের তাপ-গ্রাহক থেকে সংকেত পায়।"),
    mcq("What happens to blood vessels in the skin when a worker on a winter night shift gets cold?", ["They narrow (vasoconstriction), keeping warm blood deeper in the body", "They widen", "They burst", "Nothing"], 0,
        "Shivering also releases heat from muscle respiration.",
        "শীতের রাতের পালায় একজন কর্মী ঠান্ডা হলে চামড়ার রক্তনালীর কী হয়?", ["সরু হয় (রক্তনালী-সংকোচন), গরম রক্ত শরীরের গভীরে রাখে", "চওড়া হয়", "ফেটে যায়", "কিছু না"],
        "কাঁপুনিও পেশির শ্বসন থেকে তাপ ছাড়ে।"),
    mcq("What does glucagon do?", ["Raises blood glucose by making the liver release stored glucose", "Lowers blood glucose", "Digests fat", "Controls breathing"], 0,
        "Insulin and glucagon work as a pair to keep blood glucose steady.",
        "গ্লুকাগন কী করে?", ["যকৃৎকে জমা গ্লুকোজ ছাড়তে বলে রক্তে গ্লুকোজ বাড়ায়", "রক্তে গ্লুকোজ কমায়", "চর্বি হজম করে", "শ্বাস নিয়ন্ত্রণ করে"],
        "ইনসুলিন আর গ্লুকাগন জুটি হয়ে রক্তে গ্লুকোজ স্থির রাখে।"),
    mcq("What is the difference between type 1 and type 2 diabetes?", ["Type 1: the pancreas makes too little insulin; type 2: body cells stop responding well to insulin", "They are the same", "Type 2 is caught from others", "Type 1 is caused only by eating sugar"], 0,
        "Type 2 risk is reduced by exercise and a healthy diet.",
        "টাইপ 1 আর টাইপ 2 ডায়াবেটিসের পার্থক্য কী?", ["টাইপ 1: অগ্ন্যাশয় খুব কম ইনসুলিন বানায়; টাইপ 2: দেহকোষ ইনসুলিনে ভালো সাড়া দেয় না", "দুটো একই", "টাইপ 2 অন্যদের থেকে ছড়ায়", "টাইপ 1 শুধু চিনি খেয়ে হয়"],
        "ব্যায়াম আর স্বাস্থ্যকর খাদ্যে টাইপ 2-এর ঝুঁকি কমে।"),
    mcq("How is the nervous system's response different from the hormonal system's?", ["Nerve signals are fast and short-lived; hormones act more slowly but last longer", "Hormones are always faster", "They are identical", "Nerves only work at night"], 0,
        "Pulling a hand from a hot pipe is nervous; growth is hormonal.",
        "স্নায়ুতন্ত্রের সাড়া হরমোন-তন্ত্রের থেকে কীভাবে আলাদা?", ["স্নায়ু-সংকেত দ্রুত আর ক্ষণস্থায়ী; হরমোন ধীরে কাজ করে কিন্তু বেশিক্ষণ থাকে", "হরমোন সবসময় দ্রুত", "দুটো হুবহু এক", "স্নায়ু শুধু রাতে কাজ করে"],
        "গরম পাইপ থেকে হাত সরানো স্নায়বিক; বৃদ্ধি হরমোনজনিত।"),
    mcq("Which part of the eye focuses light by changing shape?", ["The lens", "The retina", "The iris", "The optic nerve"], 0,
        "Ciliary muscles make the lens fatter for near objects and thinner for far ones.",
        "চোখের কোন অংশ আকার বদলে আলো ফোকাস করে?", ["লেন্স", "রেটিনা", "আইরিশ (কনীনিকা)", "দৃষ্টি-স্নায়ু"],
        "সিলিয়ারি পেশি কাছের জিনিসে লেন্স মোটা আর দূরেরটায় সরু করে।"),
    mcq("What does the iris do in bright sunlight on a bridge deck?", ["Makes the pupil smaller to let in less light", "Makes the pupil bigger", "Focuses the image", "Turns light into signals"], 0,
        "This reflex protects the retina from too much light.",
        "সেতুর পাটাতনে কড়া রোদে আইরিশ কী করে?", ["কম আলো ঢোকাতে তারারন্ধ্র ছোট করে", "তারারন্ধ্র বড় করে", "প্রতিবিম্ব ফোকাস করে", "আলোকে সংকেতে বদলায়"],
        "এই প্রতিবর্ত রেটিনাকে অতিরিক্ত আলো থেকে রক্ষা করে।"),
    mcq("Why are colour-vision tests required for some railway and crane signalling jobs?", ["Red-green colour blindness could make a worker misread signal lights", "To choose uniforms", "Colour blindness causes headaches", "They are not required"], 0,
        "Red-green colour blindness is inherited and more common in males.",
        "কিছু রেল আর ক্রেন-সংকেতের কাজে রং-দৃষ্টির পরীক্ষা লাগে কেন?", ["লাল-সবুজ বর্ণান্ধতায় কর্মী সংকেত-বাতি ভুল পড়তে পারেন", "পোশাক বাছতে", "বর্ণান্ধতায় মাথাব্যথা হয়", "লাগে না"],
        "লাল-সবুজ বর্ণান্ধতা বংশগত আর পুরুষদের মধ্যে বেশি দেখা যায়।"),
    mcq("What is short-sightedness (myopia) and how is it corrected?", ["Distant objects look blurred; corrected with a diverging (concave) lens", "Near objects look blurred; corrected with a converging lens", "Seeing double", "It cannot be corrected"], 0,
        "Workers who drive or operate cranes must have good distance vision.",
        "ক্ষীণদৃষ্টি (মায়োপিয়া) কী আর কীভাবে সংশোধন হয়?", ["দূরের জিনিস ঝাপসা দেখায়; অপসারী (অবতল) লেন্সে সংশোধন", "কাছের জিনিস ঝাপসা; অভিসারী লেন্সে সংশোধন", "দুটো করে দেখা", "সংশোধন করা যায় না"],
        "গাড়ি বা ক্রেন চালানো কর্মীদের দূরদৃষ্টি ভালো হতে হবে।"),
    mcq("Why must welders protect their eyes with a dark filter?", ["The arc gives intense ultraviolet and visible light that can burn the cornea ('arc eye')", "To look professional", "Sparks are cold", "To see in the dark"], 0,
        "Bystanders need screens too.",
        "ঝালাইকারদের গাঢ় ফিল্টারে চোখ রক্ষা করতে হয় কেন?", ["আর্ক তীব্র অতিবেগুনি আর দৃশ্যমান আলো দেয়, যা কর্নিয়া পুড়িয়ে দিতে পারে ('আর্ক-চোখ')", "পেশাদার দেখাতে", "স্ফুলিঙ্গ ঠান্ডা", "অন্ধকারে দেখতে"],
        "আশপাশের লোকদেরও আড়াল লাগে।"),
    mcq("Which part of the brain coordinates balance and movement - vital for working at height?", ["The cerebellum", "The medulla", "The hypothalamus", "The pituitary"], 0,
        "Alcohol affects the cerebellum, which is why drinking and heights never mix.",
        "মস্তিষ্কের কোন অংশ ভারসাম্য আর চলাফেরার সমন্বয় করে - উঁচুতে কাজের জন্য জরুরি?", ["সেরিবেলাম", "মেডুলা", "হাইপোথ্যালামাস", "পিটুইটারি"],
        "মদ সেরিবেলামে প্রভাব ফেলে, তাই মদ আর উচ্চতা কখনো মেলে না।"),
    mcq("What does the medulla in the brain control?", ["Automatic actions like breathing and heart rate", "Thinking and memory", "Balance", "Vision"], 0,
        "These actions continue even while you sleep.",
        "মস্তিষ্কের মেডুলা কী নিয়ন্ত্রণ করে?", ["শ্বাস আর হৃৎস্পন্দনের মতো স্বয়ংক্রিয় কাজ", "চিন্তা আর স্মৃতি", "ভারসাম্য", "দৃষ্টি"],
        "ঘুমের মধ্যেও এগুলো চলতে থাকে।"),
    mcq("Why is a head injury on site always taken seriously, even if the person seems fine?", ["Bleeding or swelling in the brain can develop slowly over hours", "Heads heal instantly", "Helmets make injuries worse", "It is never serious"], 0,
        "Watch for drowsiness, confusion or vomiting and get medical help.",
        "নির্মাণস্থলে মাথার আঘাত, মানুষটা ঠিক দেখালেও, সবসময় গুরুত্ব দেওয়া হয় কেন?", ["মস্তিষ্কে রক্তক্ষরণ বা ফোলা কয়েক ঘণ্টায় ধীরে বাড়তে পারে", "মাথা তখনই সেরে যায়", "হেলমেট আঘাত বাড়ায়", "কখনো গুরুতর নয়"],
        "ঝিমুনি, বিভ্রান্তি বা বমি দেখো আর চিকিৎসা নাও।"),
    mcq("How do plants defend themselves physically against pests?", ["With waxy cuticles, tough bark, cell walls and thorns", "By running away", "By changing colour daily", "They have no defences"], 0,
        "Many also make chemicals that are toxic or bitter to insects.",
        "উদ্ভিদ শারীরিকভাবে কীভাবে কীটপতঙ্গ থেকে নিজেকে রক্ষা করে?", ["মোমের মতো ত্বক, শক্ত বাকল, কোষপ্রাচীর আর কাঁটা দিয়ে", "পালিয়ে", "রোজ রং বদলে", "কোনো প্রতিরক্ষা নেই"],
        "অনেকে পোকার জন্য বিষাক্ত বা তেতো রাসায়নিকও বানায়।"),
    mcq("What are signs that a plant by a new bridge is lacking nitrate ions?", ["Stunted growth and yellow older leaves", "Purple flowers", "Very tall, dark green growth", "Extra fruit"], 0,
        "Nitrates are needed to make proteins for growth.",
        "নতুন সেতুর পাশে একটা গাছে নাইট্রেট আয়নের অভাবের লক্ষণ কী?", ["খর্ব বৃদ্ধি আর হলুদ পুরোনো পাতা", "বেগুনি ফুল", "খুব লম্বা, গাঢ় সবুজ বৃদ্ধি", "বাড়তি ফল"],
        "বৃদ্ধির প্রোটিন বানাতে নাইট্রেট লাগে।"),
    mcq("What is 'food security'?", ["Everyone having reliable access to enough safe, nutritious food", "Locking food in a safe", "A guard at a market", "Eating only once a day"], 0,
        "Good roads and bridges let food reach markets before it spoils.",
        "'খাদ্য-নিরাপত্তা' কী?", ["সবার কাছে নিয়মিতভাবে যথেষ্ট নিরাপদ, পুষ্টিকর খাবার পৌঁছানো", "খাবার সিন্দুকে তালা দেওয়া", "বাজারের পাহারাদার", "দিনে একবার খাওয়া"],
        "ভালো রাস্তা আর সেতু খাবার নষ্ট হওয়ার আগে বাজারে পৌঁছাতে দেয়।"),
    mcq("How can a new rural bridge improve local nutrition?", ["Farmers reach markets and people reach shops year-round, even in floods", "Bridges grow vegetables", "It makes food less nutritious", "It has no effect on food"], 0,
        "Cut-off villages often lose access to food and medicine in the monsoon.",
        "একটা নতুন গ্রামীণ সেতু স্থানীয় পুষ্টি কীভাবে উন্নত করতে পারে?", ["বন্যাতেও সারা বছর চাষি বাজারে আর মানুষ দোকানে পৌঁছাতে পারেন", "সেতু সবজি ফলায়", "খাবার কম পুষ্টিকর করে", "খাবারে প্রভাব নেই"],
        "বিচ্ছিন্ন গ্রাম প্রায়ই বর্ষায় খাবার আর ওষুধের নাগাল হারায়।"),
    mcq("Why is a cold chain important for transporting vaccines across a region?", ["Vaccines can be damaged if they get too warm, so they must stay refrigerated all the way", "Cold makes vaccines stronger forever", "Vaccines are frozen solid to eat", "It is not important"], 0,
        "Reliable roads and bridges keep journeys short enough for the cold chain to work.",
        "একটা অঞ্চলে টিকা পৌঁছাতে 'শীতল শৃঙ্খল' জরুরি কেন?", ["বেশি গরমে টিকা নষ্ট হতে পারে, তাই পুরো পথ ফ্রিজে রাখতে হয়", "ঠান্ডায় টিকা চিরকাল শক্তিশালী হয়", "টিকা জমিয়ে খাওয়া হয়", "জরুরি নয়"],
        "ভরসার রাস্তা আর সেতু যাত্রা ছোট রেখে শীতল শৃঙ্খল চালু রাখে।"),
    mcq("What is an 'anomalous result' in an experiment?", ["A result that does not fit the pattern of the others", "The best result", "The average", "A result you expected"], 0,
        "Check it, repeat if you can, and leave it out of the mean if it is a mistake.",
        "পরীক্ষায় 'অস্বাভাবিক ফল' কী?", ["যে ফল অন্যগুলোর নকশার সঙ্গে মেলে না", "সেরা ফল", "গড়", "প্রত্যাশিত ফল"],
        "যাচাই করো, পারলে আবার করো, আর ভুল হলে গড় থেকে বাদ দাও।"),
    mcq("Why do scientists repeat experiments?", ["To check results are repeatable and spot mistakes", "To waste time", "To change the answer", "Because the first try never counts"], 0,
        "Results that others can reproduce are trusted more.",
        "বিজ্ঞানীরা পরীক্ষা বারবার করেন কেন?", ["ফল পুনরাবৃত্তিযোগ্য কিনা দেখতে আর ভুল ধরতে", "সময় নষ্ট করতে", "উত্তর বদলাতে", "কারণ প্রথমবার ধরা হয় না"],
        "অন্যরা যে ফল পুনরায় পায়, তা বেশি ভরসার।"),
    mcq("What is a 'control variable'?", ["A factor kept the same so it does not affect the result", "The factor you change", "The result you measure", "A random factor"], 0,
        "In an enzyme test, pH and volume are kept constant while temperature changes.",
        "'নিয়ন্ত্রিত চলরাশি' কী?", ["যে বিষয় একই রাখা হয়, যাতে ফলে প্রভাব না ফেলে", "যে বিষয় তুমি বদলাও", "যে ফল তুমি মাপো", "এলোমেলো বিষয়"],
        "এনজাইম-পরীক্ষায় তাপমাত্রা বদলালে pH আর আয়তন স্থির রাখা হয়।"),
    mcq("In a test of exercise time against pulse rate, what is the pulse rate?", ["The dependent variable - it is measured and changes because of exercise time", "The independent variable", "A control variable", "The equipment"], 0,
        "Exercise time is chosen (independent); the pulse responds (dependent).",
        "ব্যায়ামের সময় বনাম নাড়ির হারের পরীক্ষায় নাড়ির হার কী?", ["নির্ভরশীল চলরাশি - এটা মাপা হয় আর ব্যায়ামের সময়ের জন্য বদলায়", "স্বাধীন চলরাশি", "নিয়ন্ত্রিত চলরাশি", "যন্ত্রপাতি"],
        "ব্যায়ামের সময় বেছে নেওয়া হয় (স্বাধীন); নাড়ি সাড়া দেয় (নির্ভরশীল)।"),
    mcq("What makes a measurement 'precise'?", ["Repeated readings are very close to each other", "It is the true value", "It uses big numbers", "It is done quickly"], 0,
        "Accurate means close to the true value - a measurement can be precise but not accurate.",
        "একটা মাপকে কী 'সূক্ষ্ম' করে?", ["বারবারের পাঠ পরস্পরের খুব কাছাকাছি", "এটাই আসল মান", "বড় সংখ্যা ব্যবহার করে", "দ্রুত করা হয়"],
        "নির্ভুল মানে আসল মানের কাছাকাছি - মাপ সূক্ষ্ম হয়েও নির্ভুল না হতে পারে।"),
    mcq("What is 'informed consent' in medical research?", ["Volunteers agree to take part after being told the risks and purpose, and can leave at any time", "Doctors decide for everyone", "Signing without reading", "Taking part secretly"], 0,
        "Respect for people is a core rule of good science.",
        "চিকিৎসা-গবেষণায় 'অবহিত সম্মতি' কী?", ["ঝুঁকি আর উদ্দেশ্য জেনে স্বেচ্ছাসেবকরা অংশ নিতে রাজি হন, আর যেকোনো সময় বেরিয়ে যেতে পারেন", "ডাক্তাররা সবার হয়ে ঠিক করেন", "না পড়ে সই", "গোপনে অংশ নেওয়া"],
        "মানুষের প্রতি সম্মান ভালো বিজ্ঞানের মূল নিয়ম।"),
    mcq("What is a 'health and safety risk assessment' for a biological hazard on site, such as bird droppings under a bridge?", ["Identifying the hazard, who could be harmed, and the controls such as masks, gloves and cleaning", "Ignoring the droppings", "Painting over them", "Only checking once every 10 years"], 0,
        "Dried pigeon droppings can carry fungi and bacteria that harm the lungs.",
        "নির্মাণস্থলে জৈব বিপদের, যেমন সেতুর নিচে পাখির বিষ্ঠার, 'স্বাস্থ্য ও নিরাপত্তা ঝুঁকি মূল্যায়ন' কী?", ["বিপদ চিহ্নিত করা, কার ক্ষতি হতে পারে, আর মাস্ক, দস্তানা ও পরিষ্কারের মতো নিয়ন্ত্রণ ঠিক করা", "বিষ্ঠা উপেক্ষা", "উপরে রং করে দেওয়া", "10 বছরে একবার দেখা"],
        "শুকনো পায়রার বিষ্ঠায় ফুসফুসের ক্ষতিকর ছত্রাক আর ব্যাকটেরিয়া থাকতে পারে।"),
    mcq("Why are pigeons often discouraged from roosting under bridges with spikes or netting?", ["Their acidic droppings damage paint and steel and pose health risks to workers", "Pigeons are illegal", "To catch them for food", "Pigeons make bridges heavier"], 0,
        "Humane deterrents are preferred to harming the birds.",
        "সেতুর নিচে কাঁটা বা জাল দিয়ে প্রায়ই পায়রাদের বাসা বাঁধতে বাধা দেওয়া হয় কেন?", ["এদের অম্লীয় বিষ্ঠা রং আর ইস্পাতের ক্ষতি করে আর কর্মীদের স্বাস্থ্যঝুঁকি", "পায়রা বেআইনি", "খাবারের জন্য ধরতে", "পায়রা সেতু ভারী করে"],
        "পাখির ক্ষতি না করে মানবিক বাধাই পছন্দের।"),
    mcq("Why do people at high altitude (such as bridge builders in the Himalayas) breathe faster at first?", ["The air has less oxygen per breath, so the body compensates", "Mountains are hot", "There is more carbon dioxide", "Cold air is heavier"], 0,
        "Over weeks the body makes more red blood cells (acclimatisation).",
        "অনেক উঁচুতে (যেমন হিমালয়ে সেতু-নির্মাতারা) মানুষ প্রথমে দ্রুত শ্বাস নেন কেন?", ["বাতাসে প্রতি শ্বাসে কম অক্সিজেন, তাই শরীর তা পূরণ করে", "পাহাড় গরম", "বেশি কার্বন ডাইঅক্সাইড", "ঠান্ডা বাতাস ভারী"],
        "কয়েক সপ্তাহে শরীর বেশি লোহিতকণিকা বানায় (অভিযোজন)।"),
    mcq("What is the job of haemoglobin in red blood cells?", ["It binds oxygen in the lungs and releases it in the tissues", "It fights bacteria", "It clots blood", "It digests food"], 0,
        "Iron in the diet is needed to make it.",
        "লোহিতকণিকায় হিমোগ্লোবিনের কাজ কী?", ["ফুসফুসে অক্সিজেন বাঁধে আর কলায় ছাড়ে", "ব্যাকটেরিয়ার সঙ্গে লড়ে", "রক্ত জমায়", "খাদ্য হজম করে"],
        "এটা বানাতে খাবারে লোহা লাগে।"),
    mcq("What is anaemia and why might it make a worker tired?", ["Too little haemoglobin, so the blood carries less oxygen to muscles", "Too much sugar", "A broken bone", "Too many white cells"], 0,
        "Iron-rich foods like green leafy vegetables and lentils help prevent it.",
        "রক্তাল্পতা কী আর কেন কর্মীকে ক্লান্ত করে?", ["খুব কম হিমোগ্লোবিন, তাই রক্ত পেশিতে কম অক্সিজেন বয়", "খুব বেশি চিনি", "ভাঙা হাড়", "খুব বেশি শ্বেতকণিকা"],
        "শাক আর ডালের মতো লোহাসমৃদ্ধ খাবার এটা আটকাতে সাহায্য করে।"),
    mcq("Why is a balanced diet with enough protein important for manual workers?", ["Protein is needed to repair and build muscle tissue used in heavy work", "Protein is the only energy source", "Protein makes bones transparent", "It is not important"], 0,
        "Carbohydrates provide most of the energy; protein builds and repairs.",
        "শারীরিক শ্রমিকদের জন্য যথেষ্ট প্রোটিনসহ সুষম খাদ্য জরুরি কেন?", ["ভারী কাজে ব্যবহৃত পেশি মেরামত আর গঠনে প্রোটিন লাগে", "প্রোটিনই একমাত্র শক্তির উৎস", "প্রোটিন হাড় স্বচ্ছ করে", "জরুরি নয়"],
        "কার্বোহাইড্রেট বেশিরভাগ শক্তি দেয়; প্রোটিন গড়ে আর মেরামত করে।"),
    mcq("Why does vitamin D matter for workers who spend long hours in covered tunnels?", ["It is made in skin by sunlight and is needed for strong bones", "It makes eyes see in the dark", "It cures colds", "It is only found in sweets"], 0,
        "Diet or supplements can help when sunlight is scarce.",
        "ঢাকা সুড়ঙ্গে দীর্ঘ সময় কাটানো কর্মীদের জন্য ভিটামিন ডি জরুরি কেন?", ["সূর্যালোকে চামড়ায় তৈরি হয় আর মজবুত হাড়ের জন্য লাগে", "অন্ধকারে চোখে দেখায়", "সর্দি সারায়", "শুধু মিষ্টিতে থাকে"],
        "রোদ কম পেলে খাদ্য বা সম্পূরক সাহায্য করে।"),
)
