"""Class 9 - Chemistry (Bridge Engineer cadet): alloys and steel grades, metallic bonding,
electrolysis of solutions, empirical formulae, concentration in g/dm³, gas volumes from masses,
percentage purity, alcohols, carboxylic acids and esters, condensation and natural polymers,
the atmosphere and climate, acid rain on stone bridges, and recycling metals."""
from . import mcq


def _o(r, *alts):
    out = []
    for x in (r, *alts, r + 1, r * 2, r + 10, r + 2):
        if x not in out and x > 0:
            out.append(x)
    return out[:4]


def _n(q_en, q_bn, r, ex_en, ex_bn, alts, u_en="", u_bn=None):
    f = lambda x: f"{x:,}" if isinstance(x, int) else f"{x:g}"
    o = _o(r, *alts)
    ub = u_en if u_bn is None else u_bn
    return mcq(q_en, [f(x) + u_en for x in o], 0, ex_en, q_bn, [f(x) + ub for x in o], ex_bn)


def _c(x):
    x = round(x, 2)
    return int(x) if x == int(x) else x


def alloy(total, pct, metal_en, metal_bn, alloy_en, alloy_bn):
    r = _c(total * pct / 100)
    return _n(f"{alloy_en} is {pct:g}% {metal_en} by mass. How much {metal_en} is in a {total:,} g casting?",
              f"{alloy_bn}-এর ভরের {pct:g}% {metal_bn}। {total:,} g-এর একটা ঢালাইয়ে কত {metal_bn}?", r,
              f"{total:,} x {pct:g} ÷ 100 = {r:g} g.",
              f"{total:,} x {pct:g} ÷ 100 = {r:g} g।",
              (_c(total - r), _c(total / pct), _c(r * 10)), " g")


def carbon(c_g, sample, grade_en, grade_bn):
    r = _c(c_g * 100 / sample)
    return _n(f"A {sample:g} g sample of {grade_en} contains {c_g:g} g of carbon. What percentage carbon is it?",
              f"{grade_bn}-এর {sample:g} g নমুনায় {c_g:g} g কার্বন। কার্বন কত শতাংশ?", r,
              f"{c_g:g} ÷ {sample:g} x 100 = {r:g}%. More carbon makes steel harder but more brittle.",
              f"{c_g:g} ÷ {sample:g} x 100 = {r:g}%। বেশি কার্বনে ইস্পাত শক্ত হয়, কিন্তু বেশি ভঙ্গুর।",
              (_c(r * 10), _c(sample / c_g), _c(r + 1)), "%")


def gdm3(conc, mr, name_en, name_bn):
    r = _c(conc * mr)
    return _n(f"A solution of {name_en} (Mr = {mr:g}) has a concentration of {conc:g} mol/dm³. What is that in g/dm³?",
              f"{name_bn}-এর (Mr = {mr:g}) একটা দ্রবণের গাঢ়ত্ব {conc:g} mol/dm³। g/dm³-এ সেটা কত?", r,
              f"g/dm³ = mol/dm³ x Mr = {conc:g} x {mr:g} = {r:g} g/dm³.",
              f"g/dm³ = মোল/dm³ x Mr = {conc:g} x {mr:g} = {r:g} g/dm³।",
              (_c(mr / conc), _c(conc + mr), _c(r / 10)), " g/dm³")


def gasvol(mass, mr, name_en, name_bn):
    r = _c(mass / mr * 24)
    return _n(f"What volume does {mass:g} g of {name_en} gas (Mr = {mr:g}) occupy at room temperature? (1 mol = 24 dm³)",
              f"ঘরের তাপমাত্রায় {mass:g} g {name_bn} গ্যাস (Mr = {mr:g}) কত আয়তন নেয়? (1 mol = 24 dm³)", r,
              f"Moles = {mass:g} ÷ {mr:g} = {_c(mass / mr):g}; volume = {_c(mass / mr):g} x 24 = {r:g} dm³.",
              f"মোল = {mass:g} ÷ {mr:g} = {_c(mass / mr):g}; আয়তন = {_c(mass / mr):g} x 24 = {r:g} dm³।",
              (_c(mass * 24), _c(mass / mr), _c(mr / mass * 24)), " dm³")


def purity(pure, sample, what_en, what_bn):
    r = _c(pure * 100 / sample)
    return _n(f"A {sample:g} g sample of {what_en} contains {pure:g} g of the pure compound. What is its percentage purity?",
              f"{what_bn}-এর {sample:g} g নমুনায় {pure:g} g বিশুদ্ধ যৌগ। বিশুদ্ধতা কত শতাংশ?", r,
              f"{pure:g} ÷ {sample:g} x 100 = {r:g}%.",
              f"{pure:g} ÷ {sample:g} x 100 = {r:g}%।",
              (_c(100 - r), _c(sample / pure * 10), _c(r / 2)), "%")


def empirical(el1, ar1, m1, el2, ar2, m2, right, wrongs, name_en, name_bn):
    n1, n2 = m1 / ar1, m2 / ar2
    opts = [f"{el1} : {el2} = {right[0]} : {right[1]}"] + [f"{el1} : {el2} = {a} : {b}" for a, b in wrongs]
    return mcq(f"{name_en} contains {m1:g} g of {el1} (Ar = {ar1}) and {m2:g} g of {el2} (Ar = {ar2}). What is the simplest ratio of atoms?",
               opts, 0,
               f"Moles: {el1} = {m1:g} ÷ {ar1} = {_c(n1):g}, {el2} = {m2:g} ÷ {ar2} = {_c(n2):g}; simplest whole-number ratio {right[0]} : {right[1]}.",
               f"{name_bn}-এ {m1:g} g {el1} (Ar = {ar1}) আর {m2:g} g {el2} (Ar = {ar2})। পরমাণুর সরলতম অনুপাত কী?",
               opts,
               f"মোল: {el1} = {m1:g} ÷ {ar1} = {_c(n1):g}, {el2} = {m2:g} ÷ {ar2} = {_c(n2):g}; সরলতম পূর্ণসংখ্যার অনুপাত {right[0]} : {right[1]}।")


def aqel(sol_en, sol_bn, cat_en, cat_bn, an_en, an_bn, w1_en, w1_bn, w2_en, w2_bn, why_en, why_bn):
    return mcq(f"A solution of {sol_en} is electrolysed with inert electrodes. What forms at the cathode?",
               [cat_en, an_en, w1_en, w2_en], 0,
               f"{why_en} At the anode: {an_en}.",
               f"নিষ্ক্রিয় তড়িদ্বারে {sol_bn}-এর দ্রবণের তড়িৎবিশ্লেষণ হলো। ক্যাথোডে কী তৈরি হয়?",
               [cat_bn, an_bn, w1_bn, w2_bn],
               f"{why_bn} অ্যানোডে: {an_bn}।")


ITEMS = (
    alloy(500, 70, "copper", "তামা", "Brass", "পিতল"), alloy(2000, 18, "chromium", "ক্রোমিয়াম", "Stainless steel", "স্টেইনলেস স্টিল"),
    alloy(800, 90, "copper", "তামা", "Bronze", "ব্রোঞ্জ"), alloy(1500, 8, "nickel", "নিকেল", "Stainless steel", "স্টেইনলেস স্টিল"),
    alloy(400, 4.5, "copper", "তামা", "Duralumin", "ডুরালুমিন"),
    carbon(0.5, 200, "mild steel", "মৃদু ইস্পাত"), carbon(1.8, 200, "high-carbon tool steel", "উচ্চ-কার্বন যন্ত্র-ইস্পাত"),
    carbon(0.15, 100, "structural steel", "কাঠামোর ইস্পাত"), carbon(8, 200, "cast iron", "ঢালাই লোহা"),
    gdm3(0.5, 58.5, "sodium chloride", "সোডিয়াম ক্লোরাইড"), gdm3(2, 98, "sulphuric acid", "সালফিউরিক অ্যাসিড"),
    gdm3(0.1, 40, "sodium hydroxide", "সোডিয়াম হাইড্রক্সাইড"), gdm3(1.5, 36.5, "hydrochloric acid", "হাইড্রোক্লোরিক অ্যাসিড"),
    gasvol(88, 44, "carbon dioxide", "কার্বন ডাইঅক্সাইড"), gasvol(16, 32, "oxygen", "অক্সিজেন"),
    gasvol(6, 2, "hydrogen", "হাইড্রোজেন"), gasvol(42, 28, "nitrogen", "নাইট্রোজেন"), gasvol(4, 16, "methane", "মিথেন"),
    purity(45, 50, "limestone", "চুনাপাথর"), purity(38, 40, "iron ore (haematite)", "লোহার আকরিক (হেমাটাইট)"),
    purity(18, 24, "rock salt", "পাথুরে নুন"), purity(7, 10, "bauxite", "বক্সাইট"),
    empirical("Fe", 56, 112, "O", 16, 48, (2, 3), [(1, 1), (3, 2), (1, 3)], "A rust sample", "একটা মরচের নমুনা"),
    empirical("Al", 27, 54, "O", 16, 48, (2, 3), [(1, 1), (3, 2), (2, 1)], "An aluminium oxide coating", "একটা অ্যালুমিনিয়াম অক্সাইডের আবরণ"),
    empirical("Ca", 40, 40, "Cl", 35.5, 71, (1, 2), [(1, 1), (2, 1), (2, 3)], "A de-icing salt", "একটা বরফ-গলানো লবণ"),
    empirical("C", 12, 12, "H", 1, 4, (1, 4), [(1, 1), (4, 1), (1, 3)], "A fuel gas", "একটা জ্বালানি-গ্যাস"),
    empirical("Na", 23, 46, "O", 16, 16, (2, 1), [(1, 1), (1, 2), (2, 3)], "A white oxide", "একটা সাদা অক্সাইড"),
    aqel("copper(II) sulfate", "কপার(II) সালফেট", "Copper", "তামা", "Oxygen", "অক্সিজেন", "Hydrogen", "হাইড্রোজেন", "Sulfur", "সালফার",
         "Copper is less reactive than hydrogen, so copper ions are discharged.", "তামা হাইড্রোজেনের চেয়ে কম সক্রিয়, তাই তামার আয়ন ছাড়া পায়।"),
    aqel("sodium chloride (brine)", "সোডিয়াম ক্লোরাইড (লবণজল)", "Hydrogen", "হাইড্রোজেন", "Chlorine", "ক্লোরিন", "Sodium", "সোডিয়াম", "Oxygen", "অক্সিজেন",
         "Sodium is more reactive than hydrogen, so hydrogen forms instead.", "সোডিয়াম হাইড্রোজেনের চেয়ে বেশি সক্রিয়, তাই তার বদলে হাইড্রোজেন তৈরি হয়।"),
    aqel("zinc sulfate", "জিঙ্ক সালফেট", "Zinc", "দস্তা", "Oxygen", "অক্সিজেন", "Sulfur", "সালফার", "Chlorine", "ক্লোরিন",
         "In concentrated zinc solutions, as used in electro-galvanising, zinc is deposited.", "ঘন দস্তা-দ্রবণে, যেমন তড়িৎ-গ্যালভানাইজিংয়ে, দস্তা জমা হয়।"),
    aqel("dilute sulfuric acid", "লঘু সালফিউরিক অ্যাসিড", "Hydrogen", "হাইড্রোজেন", "Oxygen", "অক্সিজেন", "Sulfur", "সালফার", "Water", "জল",
         "Only hydrogen ions are available to gain electrons at the cathode.", "ক্যাথোডে ইলেকট্রন নিতে শুধু হাইড্রোজেন আয়নই আছে।"),
    mcq("Why is structural steel for bridges made with only about 0.15-0.25% carbon?", ["It stays tough and weldable instead of brittle", "Carbon is too expensive", "More carbon makes it rust-proof", "Carbon makes steel lighter"], 0,
        "High-carbon steel is harder but cracks more easily and is hard to weld.",
        "সেতুর কাঠামো-ইস্পাতে মাত্র প্রায় 0.15-0.25% কার্বন রাখা হয় কেন?", ["ভঙ্গুর না হয়ে মজবুত আর ঝালাইযোগ্য থাকে", "কার্বন খুব দামি", "বেশি কার্বনে মরচে ধরে না", "কার্বন ইস্পাত হালকা করে"],
        "উচ্চ-কার্বন ইস্পাত শক্ত, কিন্তু সহজে ফাটে আর ঝালাই কঠিন।"),
    mcq("Why are alloys harder than the pure metals they are made from?", ["Different-sized atoms disrupt the neat layers, so layers cannot slide easily", "Alloys contain no metal", "Alloys are always heated", "Alloys are lighter"], 0,
        "Pure metals are soft because their layers of identical atoms slide over each other.",
        "সংকর ধাতু তাদের বিশুদ্ধ ধাতুর চেয়ে শক্ত কেন?", ["আলাদা মাপের পরমাণু সুশৃঙ্খল স্তর এলোমেলো করে, তাই স্তর সহজে পিছলাতে পারে না", "সংকরে ধাতু নেই", "সংকর সবসময় গরম থাকে", "সংকর হালকা"],
        "বিশুদ্ধ ধাতু নরম, কারণ একই পরমাণুর স্তর পরস্পরের উপর পিছলে যায়।"),
    mcq("What is 'metallic bonding'?", ["Positive metal ions held together by a sea of shared, free-moving electrons", "Sharing of electron pairs between non-metals", "Transfer of electrons from a metal to a non-metal", "Magnetic attraction"], 0,
        "The free electrons explain why metals conduct heat and electricity.",
        "'ধাতব বন্ধন' কী?", ["ভাগ করা, মুক্তভাবে চলা ইলেকট্রনের সাগরে আটকে থাকা ধনাত্মক ধাতব আয়ন", "অধাতুর মধ্যে ইলেকট্রন-জোড় ভাগ", "ধাতু থেকে অধাতুতে ইলেকট্রন স্থানান্তর", "চৌম্বক আকর্ষণ"],
        "মুক্ত ইলেকট্রনই ব্যাখ্যা করে কেন ধাতু তাপ আর বিদ্যুৎ পরিবহন করে।"),
    mcq("Why can steel be bent and hammered into shape (it is malleable)?", ["Layers of metal ions can slide over each other without the bonds breaking", "Steel is a liquid", "Steel has no bonds", "Heat turns steel to plastic"], 0,
        "That is why steel bends and warns before it breaks, unlike glass.",
        "ইস্পাতকে বাঁকানো আর হাতুড়ি পিটিয়ে আকার দেওয়া যায় কেন (ঘাতসহ)?", ["বন্ধন না ভেঙেই ধাতব আয়নের স্তর পরস্পরের উপর পিছলাতে পারে", "ইস্পাত তরল", "ইস্পাতে বন্ধন নেই", "তাপে ইস্পাত প্লাস্টিক হয়"],
        "তাই কাচের মতো না ভেঙে ইস্পাত ভাঙার আগে বেঁকে সতর্ক করে।"),
    mcq("What is weathering steel (such as Cor-Ten)?", ["A low-alloy steel with copper, chromium and nickel that forms a protective rust layer", "Steel that changes colour with the weather forecast", "Steel kept indoors only", "Pure iron"], 0,
        "Its dense patina slows further corrosion, saving repainting costs.",
        "আবহ-সহ ইস্পাত (যেমন কর-টেন) কী?", ["তামা, ক্রোমিয়াম আর নিকেলসহ অল্প-সংকর ইস্পাত, যা সুরক্ষা-মরচের স্তর বানায়", "আবহাওয়ার পূর্বাভাসে রং বদলানো ইস্পাত", "শুধু ঘরে রাখা ইস্পাত", "বিশুদ্ধ লোহা"],
        "এর ঘন আস্তরণ আরও ক্ষয় ধীর করে, আবার রঙের খরচ বাঁচায়।"),
    mcq("Why is aluminium alloy used for some lightweight footbridges and bridge parapets?", ["It is strong for its weight and forms a protective oxide layer", "It is the strongest metal known", "It is magnetic", "It never needs joints"], 0,
        "Lighter decks need smaller foundations and are quicker to install.",
        "কিছু হালকা পায়ে-চলা সেতু আর সেতুর রেলিংয়ে অ্যালুমিনিয়াম-সংকর ব্যবহার হয় কেন?", ["ওজনের তুলনায় শক্ত আর সুরক্ষা-অক্সাইড স্তর বানায়", "জানা সবচেয়ে শক্ত ধাতু", "চৌম্বক", "কখনো জোড় লাগে না"],
        "হালকা পাটাতনে ছোট ভিত লাগে আর বসাতে কম সময় লাগে।"),
    mcq("Why are transition metals like iron, nickel and platinum useful in industry?", ["Many act as catalysts and form strong, useful alloys", "They are all gases", "They never react", "They are all soft"], 0,
        "Iron catalyses ammonia production; nickel strengthens stainless steel.",
        "লোহা, নিকেল আর প্ল্যাটিনামের মতো অবস্থান্তর-ধাতু শিল্পে কাজের কেন?", ["অনেকে অনুঘটক হিসেবে কাজ করে আর শক্ত, কাজের সংকর বানায়", "সবাই গ্যাস", "কখনো বিক্রিয়া করে না", "সবাই নরম"],
        "লোহা অ্যামোনিয়া তৈরিতে অনুঘটক; নিকেল স্টেইনলেস স্টিলকে শক্ত করে।"),
    mcq("Why do transition metal compounds often have bright colours?", ["Their ions absorb some wavelengths of visible light", "They are always painted", "They glow from heat", "They contain dyes"], 0,
        "Copper sulfate is blue; iron(III) compounds are orange-brown like rust.",
        "অবস্থান্তর-ধাতুর যৌগ প্রায়ই উজ্জ্বল রঙের হয় কেন?", ["এদের আয়ন দৃশ্যমান আলোর কিছু তরঙ্গদৈর্ঘ্য শোষে", "সবসময় রং করা", "তাপে জ্বলে", "রঞ্জক থাকে"],
        "কপার সালফেট নীল; আয়রন(III) যৌগ মরচের মতো কমলা-বাদামি।"),
    mcq("In electroplating a steel bolt with zinc, what is the bolt connected as?", ["The cathode (negative electrode)", "The anode", "The electrolyte", "The power switch"], 0,
        "Zinc ions in the solution gain electrons at the bolt and coat it with zinc.",
        "একটা ইস্পাতের বল্টুতে দস্তার তড়িৎলেপনে বল্টুকে কী হিসেবে যুক্ত করা হয়?", ["ক্যাথোড (ঋণাত্মক তড়িদ্বার)", "অ্যানোড", "তড়িৎবিশ্লেষ্য", "বিদ্যুতের সুইচ"],
        "দ্রবণের দস্তা-আয়ন বল্টুতে ইলেকট্রন নিয়ে তাকে দস্তায় ঢেকে দেয়।"),
    mcq("Why does electrolysis of brine matter to the construction industry?", ["It makes chlorine (for PVC pipes and water treatment) and sodium hydroxide (for many products)", "It makes cement directly", "It makes steel", "It produces petrol"], 0,
        "Hydrogen is a useful third product.",
        "লবণজলের তড়িৎবিশ্লেষণ নির্মাণশিল্পের জন্য জরুরি কেন?", ["এতে ক্লোরিন (পিভিসি পাইপ আর জল-শোধনের জন্য) আর সোডিয়াম হাইড্রক্সাইড (বহু পণ্যের জন্য) তৈরি হয়", "সরাসরি সিমেন্ট বানায়", "ইস্পাত বানায়", "পেট্রোল বানায়"],
        "হাইড্রোজেন একটা কাজের তৃতীয় উৎপাদ।"),
    mcq("Ethene (C2H4) and propene (C3H6) are different compounds. Why do they share the same empirical formula, CH2?", ["Both have carbon and hydrogen atoms in the simplest ratio 1 : 2", "They are the same compound", "Empirical formulae ignore hydrogen", "Both contain oxygen"], 0,
        "The empirical formula shows only the ratio; the molecular formula shows the actual numbers.",
        "ইথিন (C2H4) আর প্রোপিন (C3H6) আলাদা যৌগ। দুটোর স্থূল সংকেত একই, CH2, কেন?", ["দুটোতেই কার্বন আর হাইড্রোজেন পরমাণু সরলতম অনুপাত 1 : 2-এ আছে", "দুটো একই যৌগ", "স্থূল সংকেত হাইড্রোজেন বাদ দেয়", "দুটোতেই অক্সিজেন আছে"],
        "স্থূল সংকেত শুধু অনুপাত দেখায়; আণবিক সংকেত আসল সংখ্যা দেখায়।"),
    mcq("What are the products when a hydrocarbon fuel burns completely in plenty of air?", ["Carbon dioxide and water", "Carbon monoxide and soot", "Hydrogen and oxygen", "Only water"], 0,
        "Complete combustion releases the most energy from the fuel.",
        "প্রচুর বাতাসে একটা হাইড্রোকার্বন জ্বালানি পুরো পুড়লে কী উৎপন্ন হয়?", ["কার্বন ডাইঅক্সাইড আর জল", "কার্বন মনোক্সাইড আর ঝুল", "হাইড্রোজেন আর অক্সিজেন", "শুধু জল"],
        "পূর্ণ দহনে জ্বালানি থেকে সবচেয়ে বেশি শক্তি বেরোয়।"),
    mcq("Why is a yellow, sooty flame from a cabin heater a warning sign?", ["It shows incomplete combustion, which makes poisonous carbon monoxide", "It means the heater is very efficient", "Yellow flames are cooler and safe", "It shows the fuel is pure"], 0,
        "A clean burner gives a blue flame; service heaters and fit a CO alarm.",
        "কেবিন-হিটারের হলুদ, ঝুলভরা শিখা বিপদসংকেত কেন?", ["অপূর্ণ দহন দেখায়, যা বিষাক্ত কার্বন মনোক্সাইড বানায়", "হিটার খুব দক্ষ বোঝায়", "হলুদ শিখা ঠান্ডা আর নিরাপদ", "জ্বালানি বিশুদ্ধ বোঝায়"],
        "পরিষ্কার বার্নার নীল শিখা দেয়; হিটার সার্ভিস করাও আর সিও-অ্যালার্ম বসাও।"),
    mcq("Where does the oxygen used for oxy-fuel steel cutting come from?", ["Fractional distillation of liquefied air", "Splitting cement", "Boiling sea water", "Burning coal"], 0,
        "Air is cooled until it liquefies, then nitrogen, oxygen and argon boil off at different temperatures.",
        "অক্সি-জ্বালানিতে ইস্পাত কাটার অক্সিজেন কোথা থেকে আসে?", ["তরলীকৃত বাতাসের আংশিক পাতন থেকে", "সিমেন্ট ভেঙে", "সমুদ্রের জল ফুটিয়ে", "কয়লা পুড়িয়ে"],
        "বাতাসকে তরল হওয়া পর্যন্ত ঠান্ডা করা হয়, তারপর নাইট্রোজেন, অক্সিজেন আর আর্গন আলাদা তাপমাত্রায় ফুটে বেরোয়।"),
    mcq("Why does an oxy-acetylene torch cut steel so well?", ["Pure oxygen makes the flame far hotter and burns the hot iron away as oxide", "Acetylene is a type of acid", "The torch uses electricity only", "Oxygen cools the steel"], 0,
        "Cutting works by rapidly oxidising iron - a controlled, very fast rusting.",
        "অক্সি-অ্যাসিটিলিন টর্চ এত ভালো ইস্পাত কাটে কেন?", ["বিশুদ্ধ অক্সিজেন শিখাকে অনেক বেশি গরম করে আর গরম লোহাকে অক্সাইড করে পুড়িয়ে দেয়", "অ্যাসিটিলিন এক রকম অ্যাসিড", "টর্চ শুধু বিদ্যুতে চলে", "অক্সিজেন ইস্পাত ঠান্ডা করে"],
        "কাটা হয় লোহাকে দ্রুত জারিত করে - নিয়ন্ত্রিত, খুব দ্রুত মরচে ধরানো।"),
    mcq("Which industrial process makes sulfuric acid?", ["The Contact process", "The Haber process", "The blast furnace", "Cracking"], 0,
        "Sulfuric acid is used to make fertilisers, paints and steel-cleaning (pickling) solutions.",
        "কোন শিল্প-প্রক্রিয়ায় সালফিউরিক অ্যাসিড তৈরি হয়?", ["স্পর্শ-প্রক্রিয়া", "হেবার প্রক্রিয়া", "ব্লাস্ট-ফার্নেস", "ক্র্যাকিং"],
        "সালফিউরিক অ্যাসিড সার, রং আর ইস্পাত-পরিষ্কারের (পিকলিং) দ্রবণ বানাতে লাগে।"),
    mcq("Why are hydrogen fuel cells being tried in site machinery?", ["They make electricity from hydrogen and oxygen, giving only water as waste", "They burn coal more cleanly", "They need no fuel at all", "They make petrol"], 0,
        "Making and storing hydrogen cleanly is still a challenge.",
        "নির্মাণ-যন্ত্রে হাইড্রোজেন জ্বালানি-কোষ পরীক্ষা হচ্ছে কেন?", ["হাইড্রোজেন আর অক্সিজেন থেকে বিদ্যুৎ বানায়, বর্জ্য শুধু জল", "কয়লা পরিষ্কারভাবে পোড়ায়", "কোনো জ্বালানিই লাগে না", "পেট্রোল বানায়"],
        "পরিষ্কারভাবে হাইড্রোজেন বানানো আর জমিয়ে রাখা এখনো চ্যালেঞ্জ।"),
    mcq("What is one drawback of growing crops for biofuel to run trucks?", ["It can use land that would otherwise grow food", "Biofuels release no energy", "They cannot be burned", "They are made from steel"], 0,
        "Biofuels from waste oils and crop residues avoid this problem.",
        "ট্রাক চালাতে জৈব-জ্বালানির ফসল ফলানোর একটা অসুবিধা কী?", ["যে জমিতে খাদ্য ফলত, তা ব্যবহার হতে পারে", "জৈব-জ্বালানি শক্তি দেয় না", "পোড়ানো যায় না", "ইস্পাত থেকে তৈরি"],
        "বর্জ্য তেল আর ফসলের অবশেষ থেকে জৈব-জ্বালানি এই সমস্যা এড়ায়।"),
    mcq("How does spreading salt on an icy bridge deck help?", ["Dissolved salt lowers the freezing point, so ice melts at temperatures below 0°C", "Salt heats the deck", "Salt makes ice harder", "Salt absorbs sunlight"], 0,
        "But the salt water then attacks steel and concrete.",
        "বরফে-ঢাকা সেতুর পাটাতনে নুন ছড়ালে কীভাবে সাহায্য হয়?", ["দ্রবীভূত নুন হিমাঙ্ক নামায়, তাই 0°C-এর নিচেও বরফ গলে", "নুন পাটাতন গরম করে", "নুন বরফ শক্ত করে", "নুন সূর্যালোক শোষে"],
        "তবে নোনা জল পরে ইস্পাত আর কংক্রিট ক্ষয় করে।"),
    mcq("Why do some bridges use calcium magnesium acetate instead of rock salt for de-icing?", ["It melts ice without chloride, so it is much kinder to steel and concrete", "It is cheaper than salt", "It makes the road shiny", "It works only in summer"], 0,
        "It costs more, so it is saved for sensitive structures.",
        "কিছু সেতুতে বরফ গলাতে পাথুরে নুনের বদলে ক্যালসিয়াম ম্যাগনেসিয়াম অ্যাসিটেট ব্যবহার হয় কেন?", ["ক্লোরাইড ছাড়াই বরফ গলায়, তাই ইস্পাত আর কংক্রিটের প্রতি অনেক নরম", "নুনের চেয়ে সস্তা", "রাস্তা চকচকে করে", "শুধু গ্রীষ্মে কাজ করে"],
        "দাম বেশি, তাই সংবেদনশীল কাঠামোর জন্য রাখা হয়।"),
    mcq("What does a 'superplasticiser' do in bridge concrete?", ["Lets the concrete flow easily with less water, making it stronger and denser", "Turns the concrete into plastic", "Makes it set instantly", "Adds colour"], 0,
        "Self-compacting concrete for crowded steel cages relies on it.",
        "সেতুর কংক্রিটে 'সুপারপ্লাস্টিসাইজার' কী করে?", ["কম জলেই কংক্রিটকে সহজে গড়াতে দেয়, তাই শক্ত আর ঘন হয়", "কংক্রিটকে প্লাস্টিক বানায়", "তখনই জমায়", "রং যোগ করে"],
        "ঘন রডের খাঁচায় নিজে-বসে-যাওয়া কংক্রিট এর উপর নির্ভর করে।"),
    mcq("Why is lime mixed into soft clay soil under a bridge approach road?", ["It reacts with the clay, making it stiffer, drier and less likely to swell", "To colour the soil white", "To feed plants", "To make the soil sticky"], 0,
        "This 'soil stabilisation' can avoid digging out and replacing poor ground.",
        "সেতুর সংযোগ-রাস্তার নিচের নরম কাদামাটিতে চুন মেশানো হয় কেন?", ["কাদার সঙ্গে বিক্রিয়া করে তাকে শক্ত, শুকনো আর কম ফোলার উপযোগী করে", "মাটি সাদা করতে", "গাছকে খাওয়াতে", "মাটি আঠালো করতে"],
        "এই 'মাটি-স্থিতিকরণ' খারাপ মাটি খুঁড়ে বদলানো এড়াতে পারে।"),
    mcq("What is a bitumen emulsion?", ["Tiny bitumen droplets dispersed in water, so it can be sprayed cold", "Bitumen mixed with petrol only", "Melted plastic", "Bitumen dissolved in cement"], 0,
        "When the water evaporates, the droplets join into a waterproof film.",
        "বিটুমেন-ইমালশন কী?", ["জলে ছড়ানো খুব ছোট বিটুমেনের ফোঁটা, তাই ঠান্ডা অবস্থায় ছেটানো যায়", "শুধু পেট্রোলে মেশানো বিটুমেন", "গলানো প্লাস্টিক", "সিমেন্টে দ্রবীভূত বিটুমেন"],
        "জল বাষ্প হলে ফোঁটাগুলো জুড়ে জলরোধী স্তর হয়।"),
    mcq("Why are flexible silicone or polyurethane sealants used in bridge joints?", ["They stretch and squeeze as the joint moves while keeping water out", "They make joints rigid", "They conduct electricity", "They dissolve in rain"], 0,
        "Water getting into joints is a leading cause of hidden corrosion.",
        "সেতুর জোড়ে নমনীয় সিলিকন বা পলিইউরিথেন সিল্যান্ট ব্যবহার হয় কেন?", ["জোড় নড়লে টেনে ও চেপে মানিয়ে নেয়, আবার জল ঢুকতে দেয় না", "জোড় শক্ত করে", "বিদ্যুৎ পরিবহন করে", "বৃষ্টিতে গলে"],
        "জোড়ে জল ঢোকা লুকোনো ক্ষয়ের প্রধান কারণগুলোর একটা।"),
    mcq("How does intumescent paint protect steel in a fire?", ["When heated it swells into a thick, insulating char that slows the steel heating up", "It puts the fire out with water", "It makes steel melt faster", "It reflects all heat as light"], 0,
        "It buys time for people to escape and firefighters to act.",
        "আগুনে ইন্টুমেসেন্ট রং কীভাবে ইস্পাত রক্ষা করে?", ["গরম হলে ফুলে মোটা, অন্তরক অঙ্গারের স্তর হয়, যা ইস্পাতের গরম হওয়া ধীর করে", "জল দিয়ে আগুন নেভায়", "ইস্পাত দ্রুত গলায়", "সব তাপকে আলো হিসেবে ফেরায়"],
        "মানুষের পালানো আর দমকলের কাজের সময় কিনে দেয়।"),
    mcq("Magnesium ribbon is burned in a crucible. Why is the white ash heavier than the ribbon was?", ["The magnesium has combined with oxygen from the air", "Ash absorbs water only", "Burning creates new atoms", "The crucible lost mass"], 0,
        "Mass is conserved: magnesium + oxygen = magnesium oxide.",
        "একটা মুচিতে ম্যাগনেসিয়ামের ফিতে পোড়ানো হলো। সাদা ছাই ফিতের চেয়ে ভারী কেন?", ["ম্যাগনেসিয়াম বাতাসের অক্সিজেনের সঙ্গে যুক্ত হয়েছে", "ছাই শুধু জল শোষে", "পোড়ালে নতুন পরমাণু তৈরি হয়", "মুচির ভর কমেছে"],
        "ভর সংরক্ষিত থাকে: ম্যাগনেসিয়াম + অক্সিজেন = ম্যাগনেসিয়াম অক্সাইড।"),
    mcq("Limestone heated in an open dish loses mass. Does this break the law of conservation of mass?", ["No - carbon dioxide gas escapes into the air", "Yes - atoms are destroyed", "Yes - heat removes mass", "No - the dish gains the mass"], 0,
        "In a sealed container the total mass would stay the same.",
        "খোলা পাত্রে চুনাপাথর গরম করলে ভর কমে। এতে কি ভরের সংরক্ষণ-সূত্র ভাঙে?", ["না - কার্বন ডাইঅক্সাইড গ্যাস বাতাসে বেরিয়ে যায়", "হ্যাঁ - পরমাণু ধ্বংস হয়", "হ্যাঁ - তাপ ভর সরায়", "না - পাত্র ভর পায়"],
        "বন্ধ পাত্রে মোট ভর একই থাকত।"),
    mcq("Why does structural steel lose about half its strength at around 550°C?", ["Heat lets the metal's crystal layers slip much more easily", "Steel turns into gas", "Steel gains carbon from the air", "It does not lose strength"], 0,
        "That is why fire protection is designed to keep steel below this temperature.",
        "প্রায় 550°C-এ কাঠামো-ইস্পাত তার শক্তির প্রায় অর্ধেক হারায় কেন?", ["তাপে ধাতুর কেলাস-স্তর অনেক সহজে পিছলায়", "ইস্পাত গ্যাস হয়ে যায়", "বাতাস থেকে কার্বন পায়", "শক্তি হারায় না"],
        "তাই অগ্নি-সুরক্ষা ইস্পাতকে এই তাপমাত্রার নিচে রাখার জন্য নকশা হয়।"),
    mcq("Why are steel girders 'shot-blasted' before painting?", ["Blasting removes rust and mill scale and roughens the surface so paint grips well", "To make the steel thinner", "To harden the steel", "To clean off old concrete only"], 0,
        "Most paint failures start from poor surface preparation.",
        "রং করার আগে ইস্পাতের গার্ডার 'শট-ব্লাস্ট' করা হয় কেন?", ["মরচে আর কারখানার আঁশ সরায় আর তল খসখসে করে, যাতে রং ভালো আঁকড়ে ধরে", "ইস্পাত পাতলা করতে", "ইস্পাত শক্ত করতে", "শুধু পুরোনো কংক্রিট সরাতে"],
        "বেশিরভাগ রং-ব্যর্থতা খারাপ তল-প্রস্তুতি থেকে শুরু হয়।"),
    mcq("Why do chemists convert concentrations from g/dm³ to mol/dm³?", ["Reactions happen in ratios of particles (moles), not of masses", "Grams are not allowed", "It makes the numbers bigger", "Moles are easier to weigh"], 0,
        "Divide g/dm³ by Mr to get mol/dm³.",
        "রসায়নবিদরা গাঢ়ত্ব g/dm³ থেকে mol/dm³-এ বদলান কেন?", ["বিক্রিয়া কণার (মোলের) অনুপাতে হয়, ভরের নয়", "গ্রাম নিষিদ্ধ", "সংখ্যা বড় হয়", "মোল ওজন করা সহজ"],
        "g/dm³-কে Mr দিয়ে ভাগ করলে mol/dm³।"),
    mcq("Why does an equal volume of any gas at the same temperature and pressure contain the same number of molecules?", ["Gas molecules are so far apart that their own size hardly matters", "All gases weigh the same", "Gases have no molecules", "It is only true for oxygen"], 0,
        "That is why 1 mole of any gas fills about 24 dm³ at room temperature.",
        "একই তাপমাত্রা আর চাপে যেকোনো গ্যাসের সমান আয়তনে একই সংখ্যক অণু থাকে কেন?", ["গ্যাসের অণুরা এত দূরে দূরে যে তাদের নিজের মাপ প্রায় গুরুত্বহীন", "সব গ্যাসের ওজন সমান", "গ্যাসে অণু নেই", "শুধু অক্সিজেনে সত্যি"],
        "তাই ঘরের তাপমাত্রায় যেকোনো গ্যাসের 1 মোল প্রায় 24 dm³ নেয়।"),
    mcq("Why do steelworks check the purity of iron ore before buying it?", ["Impurities add no iron and cost energy to remove, so price depends on purity", "Pure ore is radioactive", "Impurities make more iron", "Purity changes the ore's colour only"], 0,
        "Low-grade ore makes more slag and waste per tonne of iron.",
        "ইস্পাত-কারখানা কেনার আগে লোহার আকরিকের বিশুদ্ধতা যাচাই করে কেন?", ["অপদ্রব্য লোহা দেয় না আর সরাতে শক্তি লাগে, তাই দাম বিশুদ্ধতার উপর নির্ভর করে", "বিশুদ্ধ আকরিক তেজস্ক্রিয়", "অপদ্রব্যে বেশি লোহা হয়", "বিশুদ্ধতা শুধু রং বদলায়"],
        "নিম্নমানের আকরিকে টনপ্রতি লোহায় বেশি ধাতুমল আর বর্জ্য হয়।"),
    mcq("What is the functional group of the alcohols, such as ethanol?", ["-OH", "-C(=O)OH", "C=C", "-C(=O)O-"], 0,
        "Ethanol is used as a fuel and a solvent in paints and varnishes.",
        "ইথানলের মতো অ্যালকোহলের কার্যকরী মূলক কী?", ["-OH", "-C(=O)OH", "C=C", "-C(=O)O-"],
        "ইথানল জ্বালানি আর রং ও বার্নিশের দ্রাবক হিসেবে ব্যবহার হয়।"),
    mcq("What is the functional group of the carboxylic acids, such as ethanoic acid (vinegar)?", ["-C(=O)OH", "-OH", "C=C", "-NH2"], 0,
        "Carboxylic acids are weak acids - they only partly ionise in water.",
        "ইথানোয়িক অ্যাসিডের (ভিনিগার) মতো কার্বক্সিলিক অ্যাসিডের কার্যকরী মূলক কী?", ["-C(=O)OH", "-OH", "C=C", "-NH2"],
        "কার্বক্সিলিক অ্যাসিড দুর্বল অ্যাসিড - জলে আংশিক আয়নিত হয়।"),
    mcq("What is made when an alcohol reacts with a carboxylic acid (with an acid catalyst)?", ["An ester and water", "A salt and hydrogen", "An alkane", "Carbon dioxide only"], 0,
        "Esters smell fruity and are used as solvents in some paints and glues.",
        "অ্যালকোহল কার্বক্সিলিক অ্যাসিডের সঙ্গে (অ্যাসিড-অনুঘটকসহ) বিক্রিয়া করলে কী তৈরি হয়?", ["এস্টার আর জল", "লবণ আর হাইড্রোজেন", "অ্যালকেন", "শুধু কার্বন ডাইঅক্সাইড"],
        "এস্টারের ফলের মতো গন্ধ, কিছু রং আর আঠার দ্রাবক।"),
    mcq("What is a 'strong' acid compared with a 'weak' acid?", ["A strong acid ionises completely in water; a weak one only partly", "A strong acid is always more concentrated", "Weak acids are not acids", "Strong acids are always safe"], 0,
        "Strength and concentration are different ideas.",
        "'দুর্বল' অ্যাসিডের তুলনায় 'তীব্র' অ্যাসিড কী?", ["তীব্র অ্যাসিড জলে পুরো আয়নিত হয়; দুর্বলটা আংশিক", "তীব্র অ্যাসিড সবসময় বেশি গাঢ়", "দুর্বল অ্যাসিড অ্যাসিড নয়", "তীব্র অ্যাসিড সবসময় নিরাপদ"],
        "তীব্রতা আর গাঢ়ত্ব আলাদা ধারণা।"),
    mcq("By how much does the hydrogen ion concentration change when pH falls by 1?", ["It increases 10 times", "It doubles", "It halves", "It does not change"], 0,
        "pH 4 rain is ten times more acidic than pH 5 rain.",
        "pH 1 কমলে হাইড্রোজেন-আয়নের গাঢ়ত্ব কতটা বদলায়?", ["10 গুণ বাড়ে", "দ্বিগুণ হয়", "অর্ধেক হয়", "বদলায় না"],
        "pH 4-এর বৃষ্টি pH 5-এর চেয়ে দশগুণ বেশি অম্লীয়।"),
    mcq("What is a 'condensation polymer' such as nylon or polyester?", ["A polymer made by joining monomers with a small molecule, like water, given off at each link", "A polymer made from steam", "A polymer that melts in rain", "An addition polymer"], 0,
        "Polyester fibres are used in geotextiles under roads and embankments.",
        "নাইলন বা পলিয়েস্টারের মতো 'ঘনীভবন পলিমার' কী?", ["প্রতিটা সংযোগে জলের মতো ছোট অণু বেরিয়ে মনোমার জুড়ে তৈরি পলিমার", "বাষ্প থেকে তৈরি পলিমার", "বৃষ্টিতে গলা পলিমার", "যুত পলিমার"],
        "পলিয়েস্টার-তন্তু রাস্তা আর বাঁধের নিচে জিওটেক্সটাইলে ব্যবহার হয়।"),
    mcq("What is a 'geotextile' in bridge approach embankments?", ["A tough polymer fabric that separates, filters or reinforces soil layers", "A carpet for the deck", "A type of rock", "A banner for advertising"], 0,
        "It keeps fine soil from mixing with stone and helps drainage.",
        "সেতুর সংযোগ-বাঁধে 'জিওটেক্সটাইল' কী?", ["মজবুত পলিমার-কাপড়, যা মাটির স্তর আলাদা, ছাঁকা বা শক্ত করে", "পাটাতনের কার্পেট", "এক রকম পাথর", "বিজ্ঞাপনের ব্যানার"],
        "মিহি মাটিকে পাথরের সঙ্গে মিশতে দেয় না আর জলনিকাশে সাহায্য করে।"),
    mcq("Which of these is a natural polymer?", ["Cellulose in wood", "Poly(ethene)", "PVC", "Nylon"], 0,
        "Proteins, starch and DNA are natural polymers too.",
        "এদের মধ্যে কোনটা প্রাকৃতিক পলিমার?", ["কাঠের সেলুলোজ", "পলি(ইথিন)", "পিভিসি", "নাইলন"],
        "প্রোটিন, শ্বেতসার আর ডিএনএ-ও প্রাকৃতিক পলিমার।"),
    mcq("Why is timber treated with preservatives before use in a footbridge?", ["To stop fungi and insects breaking down the cellulose", "To make it heavier", "To change its colour only", "Untreated timber is illegal"], 0,
        "Good design that keeps timber dry matters just as much.",
        "পায়ে-চলা সেতুতে ব্যবহারের আগে কাঠে সংরক্ষক দেওয়া হয় কেন?", ["ছত্রাক আর পোকাকে সেলুলোজ ভাঙতে না দিতে", "ভারী করতে", "শুধু রং বদলাতে", "সংরক্ষকহীন কাঠ বেআইনি"],
        "কাঠ শুকনো রাখার ভালো নকশাও সমান জরুরি।"),
    mcq("How is Earth's early atmosphere thought to have differed from today's?", ["It had lots of carbon dioxide and almost no oxygen", "It was pure oxygen", "It was the same as today", "It was pure nitrogen"], 0,
        "Plants and algae later produced oxygen by photosynthesis.",
        "পৃথিবীর আদি বায়ুমণ্ডল আজকের থেকে কীভাবে আলাদা ছিল বলে মনে করা হয়?", ["প্রচুর কার্বন ডাইঅক্সাইড আর প্রায় অক্সিজেন ছিল না", "বিশুদ্ধ অক্সিজেন ছিল", "আজকের মতোই ছিল", "বিশুদ্ধ নাইট্রোজেন ছিল"],
        "পরে উদ্ভিদ আর শৈবাল সালোকসংশ্লেষে অক্সিজেন তৈরি করে।"),
    mcq("Where did much of the carbon from the early atmosphere end up?", ["Locked in limestone, chalk, coal and oil", "In outer space", "In the Moon", "In clouds"], 0,
        "Burning fossil fuels and making cement release some of it again as CO2.",
        "আদি বায়ুমণ্ডলের কার্বনের অনেকটা কোথায় গিয়েছিল?", ["চুনাপাথর, খড়ি, কয়লা আর তেলে আটকে", "মহাকাশে", "চাঁদে", "মেঘে"],
        "জীবাশ্ম জ্বালানি পোড়ানো আর সিমেন্ট বানানো এর কিছুটা আবার CO2 হিসেবে ছাড়ে।"),
    mcq("How do greenhouse gases warm the Earth?", ["They absorb infrared radiation given off by the warm surface and re-emit some back down", "They block all sunlight", "They make the Sun hotter", "They reflect heat into space"], 0,
        "Carbon dioxide, methane and water vapour are the main ones.",
        "গ্রিনহাউস গ্যাস কীভাবে পৃথিবীকে গরম করে?", ["গরম ভূপৃষ্ঠ থেকে বেরোনো অবলোহিত বিকিরণ শোষে আর কিছুটা আবার নিচে ফেরায়", "সব সূর্যালোক আটকায়", "সূর্যকে গরম করে", "তাপকে মহাকাশে প্রতিফলিত করে"],
        "কার্বন ডাইঅক্সাইড, মিথেন আর জলীয় বাষ্প প্রধান।"),
    mcq("Why must bridges designed today allow for climate change?", ["Higher temperatures, heavier rain and stronger floods will load them more over their 100-year life", "Climate change makes steel weaker instantly", "Bridges cause climate change on their own", "It does not affect bridges"], 0,
        "Designers raise deck levels and strengthen scour protection.",
        "আজ নকশা হওয়া সেতুতে জলবায়ু-পরিবর্তনের কথা ধরতে হয় কেন?", ["বেশি তাপমাত্রা, ভারী বৃষ্টি আর জোরালো বন্যা 100 বছরের জীবনে বেশি বোঝা দেবে", "জলবায়ু-পরিবর্তন তখনই ইস্পাত দুর্বল করে", "সেতু নিজেই জলবায়ু বদলায়", "সেতুতে প্রভাব নেই"],
        "নকশাকাররা পাটাতনের উচ্চতা বাড়ান আর ক্ষয়-রোধী সুরক্ষা শক্ত করেন।"),
    mcq("What is the 'carbon footprint' of a bridge mostly made up of?", ["Emissions from making its cement and steel, plus construction and transport", "Footprints of workers", "Paint colour", "Rainwater"], 0,
        "Low-carbon cements and recycled steel can cut it a lot.",
        "একটা সেতুর 'কার্বন-পদচিহ্ন' বেশিরভাগ কী নিয়ে তৈরি?", ["সিমেন্ট আর ইস্পাত তৈরির নির্গমন, সঙ্গে নির্মাণ আর পরিবহন", "কর্মীদের পায়ের ছাপ", "রঙের রং", "বৃষ্টির জল"],
        "কম-কার্বন সিমেন্ট আর পুনর্ব্যবহৃত ইস্পাত এটা অনেক কমাতে পারে।"),
    mcq("What causes acid rain?", ["Sulfur dioxide and nitrogen oxides from burning fuels dissolving in rain", "Carbon monoxide only", "Salt from the sea", "Too much oxygen"], 0,
        "Acid rain attacks limestone, marble and unprotected steel.",
        "অ্যাসিড-বৃষ্টি কী থেকে হয়?", ["জ্বালানি পোড়ানোর সালফার ডাইঅক্সাইড আর নাইট্রোজেন অক্সাইড বৃষ্টিতে গুলে", "শুধু কার্বন মনোক্সাইড", "সমুদ্রের নুন", "অতিরিক্ত অক্সিজেন"],
        "অ্যাসিড-বৃষ্টি চুনাপাথর, মার্বেল আর অরক্ষিত ইস্পাত ক্ষয় করে।"),
    mcq("Why do old limestone bridges in polluted cities show worn, rounded carvings?", ["Acid rain reacts with calcium carbonate, slowly dissolving the stone", "Birds peck them", "Traffic noise wears them", "Limestone melts in summer"], 0,
        "CaCO3 + acid -> a salt + water + CO2.",
        "দূষিত শহরের পুরোনো চুনাপাথরের সেতুর খোদাই ক্ষয়ে গোল হয়ে যায় কেন?", ["অ্যাসিড-বৃষ্টি ক্যালসিয়াম কার্বনেটের সঙ্গে বিক্রিয়া করে পাথর ধীরে গলায়", "পাখি ঠোকরায়", "যানবাহনের শব্দ ক্ষয় করে", "গ্রীষ্মে চুনাপাথর গলে"],
        "CaCO3 + অ্যাসিড -> লবণ + জল + CO2।"),
    mcq("How do power stations reduce sulfur dioxide emissions?", ["Flue gas desulfurisation - reacting the gas with limestone or lime slurry", "Building taller chimneys only", "Adding more coal", "Painting chimneys white"], 0,
        "The product, gypsum, can be used in plasterboard and cement.",
        "বিদ্যুৎকেন্দ্র কীভাবে সালফার ডাইঅক্সাইডের নির্গমন কমায়?", ["ধোঁয়া-গ্যাস থেকে সালফার-মুক্তি - গ্যাসকে চুনাপাথর বা চুনের কাদার সঙ্গে বিক্রিয়া করিয়ে", "শুধু উঁচু চিমনি বানিয়ে", "বেশি কয়লা দিয়ে", "চিমনি সাদা রং করে"],
        "উৎপাদ জিপসাম প্লাস্টারবোর্ড আর সিমেন্টে কাজে লাগে।"),
    mcq("What do catalytic converters in vehicles do?", ["Change harmful gases like carbon monoxide and nitrogen oxides into less harmful ones", "Make engines more powerful", "Turn petrol into diesel", "Remove all carbon dioxide"], 0,
        "Platinum and rhodium catalysts do the work.",
        "গাড়ির অনুঘটক-রূপান্তরক কী করে?", ["কার্বন মনোক্সাইড আর নাইট্রোজেন অক্সাইডের মতো ক্ষতিকর গ্যাসকে কম ক্ষতিকর গ্যাসে বদলায়", "ইঞ্জিন শক্তিশালী করে", "পেট্রোলকে ডিজেলে বদলায়", "সব কার্বন ডাইঅক্সাইড সরায়"],
        "প্ল্যাটিনাম আর রোডিয়াম অনুঘটক কাজটা করে।"),
    mcq("What are particulates (PM2.5) and why do they matter near busy bridges?", ["Tiny solid particles from exhausts and dust that damage lungs and hearts", "Large stones on the road", "A type of rain", "Harmless gases"], 0,
        "Diesel engines and construction dust are major sources.",
        "সূক্ষ্ম কণা (পিএম2.5) কী আর ব্যস্ত সেতুর কাছে কেন জরুরি?", ["ধোঁয়া আর ধুলোর খুব ছোট কঠিন কণা, যা ফুসফুস আর হৃদ্‌যন্ত্রের ক্ষতি করে", "রাস্তার বড় পাথর", "এক রকম বৃষ্টি", "নিরীহ গ্যাস"],
        "ডিজেল-ইঞ্জিন আর নির্মাণের ধুলো বড় উৎস।"),
    mcq("Why is recycling steel from old bridges better than mining new ore?", ["It saves energy, ore and emissions, and steel can be recycled again and again", "Old steel is stronger", "Mining is impossible", "Recycled steel is magnetic only"], 0,
        "Electric arc furnaces melt scrap using far less energy than blast furnaces.",
        "নতুন আকরিক খোঁড়ার চেয়ে পুরোনো সেতুর ইস্পাত পুনর্ব্যবহার ভালো কেন?", ["শক্তি, আকরিক আর নির্গমন বাঁচে, আর ইস্পাত বারবার পুনর্ব্যবহার করা যায়", "পুরোনো ইস্পাত বেশি শক্ত", "খনন অসম্ভব", "পুনর্ব্যবহৃত ইস্পাত শুধু চৌম্বক"],
        "বৈদ্যুতিক আর্ক-চুল্লি ব্লাস্ট-ফার্নেসের চেয়ে অনেক কম শক্তিতে টুকরো গলায়।"),
    mcq("How are steel scraps separated from aluminium at a recycling yard?", ["With large magnets - steel is magnetic, aluminium is not", "By colour only", "By smell", "By dissolving the steel in water"], 0,
        "Eddy-current separators can then push aluminium out of a mixed stream.",
        "পুনর্ব্যবহার-কেন্দ্রে ইস্পাতের টুকরো অ্যালুমিনিয়াম থেকে কীভাবে আলাদা হয়?", ["বড় চুম্বকে - ইস্পাত চৌম্বক, অ্যালুমিনিয়াম নয়", "শুধু রং দেখে", "গন্ধে", "ইস্পাতকে জলে গলিয়ে"],
        "পরে এডি-প্রবাহ বিভাজক মিশ্র স্রোত থেকে অ্যালুমিনিয়াম ঠেলে বার করে।"),
    mcq("What is 'phytomining'?", ["Growing plants that absorb metals from soil, then burning them to collect the metal compounds", "Mining with explosives", "Mining in factories", "Planting trees on mines only"], 0,
        "It can recover copper from low-grade ore or polluted land.",
        "'উদ্ভিদ-খনন' কী?", ["মাটি থেকে ধাতু শোষণকারী উদ্ভিদ জন্মিয়ে, পুড়িয়ে ধাতব যৌগ সংগ্রহ", "বিস্ফোরক দিয়ে খনন", "কারখানায় খনন", "শুধু খনিতে গাছ লাগানো"],
        "নিম্নমানের আকরিক বা দূষিত জমি থেকে তামা উদ্ধার করতে পারে।"),
    mcq("What is 'bioleaching'?", ["Using bacteria to release metals such as copper from low-grade ores", "Bleaching wood", "Washing concrete", "Making biodiesel"], 0,
        "The solution produced is then processed to extract the metal.",
        "'জৈব-নিষ্কাশন' কী?", ["নিম্নমানের আকরিক থেকে তামার মতো ধাতু বার করতে ব্যাকটেরিয়া ব্যবহার", "কাঠ ব্লিচ করা", "কংক্রিট ধোয়া", "বায়োডিজেল বানানো"],
        "তৈরি দ্রবণ থেকে পরে ধাতু নিষ্কাশন হয়।"),
    mcq("Why is the bauxite ore for aluminium purified before electrolysis?", ["Impurities such as iron oxide would contaminate the aluminium and waste energy", "Pure bauxite glows", "To make it heavier", "Bauxite is always pure"], 0,
        "The pure alumina is then dissolved in molten cryolite.",
        "তড়িৎবিশ্লেষণের আগে অ্যালুমিনিয়ামের আকরিক বক্সাইট শোধন করা হয় কেন?", ["আয়রন অক্সাইডের মতো অপদ্রব্য অ্যালুমিনিয়ামকে দূষিত করবে আর শক্তি নষ্ট করবে", "বিশুদ্ধ বক্সাইট জ্বলে", "ভারী করতে", "বক্সাইট সবসময় বিশুদ্ধ"],
        "বিশুদ্ধ অ্যালুমিনা পরে গলিত ক্রায়োলাইটে দ্রবীভূত হয়।"),
    mcq("What is 'slag' in a blast furnace?", ["A molten waste of calcium silicate formed from limestone and sandy impurities", "Pure iron", "The furnace's chimney", "A type of coal"], 0,
        "Ground slag (GGBS) is a valuable low-carbon cement replacement in bridge concrete.",
        "ব্লাস্ট-ফার্নেসে 'ধাতুমল' (স্ল্যাগ) কী?", ["চুনাপাথর আর বালুময় অপদ্রব্য থেকে তৈরি গলিত ক্যালসিয়াম সিলিকেটের বর্জ্য", "বিশুদ্ধ লোহা", "চুল্লির চিমনি", "এক রকম কয়লা"],
        "গুঁড়ো ধাতুমল (জিজিবিএস) সেতুর কংক্রিটে মূল্যবান কম-কার্বন সিমেন্ট-বিকল্প।"),
    mcq("Why does adding GGBS to bridge concrete improve its durability in the sea?", ["It makes the concrete denser and better at resisting chlorides and sulfates", "It makes concrete float", "It adds iron that rusts", "It speeds setting to seconds"], 0,
        "It also cuts the concrete's carbon footprint.",
        "সেতুর কংক্রিটে জিজিবিএস মেশালে সমুদ্রে টেকসই ভাব বাড়ে কেন?", ["কংক্রিট ঘন হয় আর ক্লোরাইড ও সালফেট ভালো রোধ করে", "কংক্রিট ভাসায়", "মরচে-ধরা লোহা যোগ করে", "সেকেন্ডে জমায়"],
        "কংক্রিটের কার্বন-পদচিহ্নও কমায়।"),
    mcq("Why is a fume extractor used when welding galvanised steel?", ["Heating the zinc coating gives off zinc oxide fumes that can cause 'metal fume fever'", "To cool the weld", "To blow away sparks for show", "Fumes make welds stronger"], 0,
        "Good ventilation and masks protect welders.",
        "গ্যালভানাইজড ইস্পাত ঝালাইয়ে ধোঁয়া-নিষ্কাশক ব্যবহার হয় কেন?", ["দস্তার আবরণ গরম হয়ে জিঙ্ক অক্সাইডের ধোঁয়া বেরোয়, যা 'ধাতব-ধোঁয়া জ্বর' ঘটাতে পারে", "ঝালাই ঠান্ডা করতে", "দেখানোর জন্য স্ফুলিঙ্গ ওড়াতে", "ধোঁয়ায় ঝালাই শক্ত হয়"],
        "ভালো বায়ু-চলাচল আর মাস্ক ঝালাইকারদের রক্ষা করে।"),
    mcq("What does 'VOC' stand for, and why do low-VOC paints matter on enclosed bridge works?", ["Volatile organic compounds - solvents that evaporate and can harm health and air quality", "Very old concrete", "Voltage of current", "Volume of cement"], 0,
        "Water-based and high-solids coatings release fewer VOCs.",
        "'ভিওসি' কী আর বন্ধ সেতু-কাজে কম-ভিওসি রং কেন জরুরি?", ["উদ্বায়ী জৈব যৌগ - বাষ্প হয়ে ওড়া দ্রাবক, যা স্বাস্থ্য আর বাতাসের মানের ক্ষতি করতে পারে", "খুব পুরোনো কংক্রিট", "প্রবাহের ভোল্টেজ", "সিমেন্টের আয়তন"],
        "জল-ভিত্তিক আর উচ্চ-কঠিন আবরণ কম ভিওসি ছাড়ে।"),
    mcq("Why does epoxy paint harden instead of just drying?", ["The resin and hardener react chemically to form a cross-linked polymer", "Water evaporates only", "It freezes", "Sunlight melts it"], 0,
        "Cross-linked coatings are tough and resist chemicals - ideal for steel girders.",
        "ইপক্সি রং শুধু শুকিয়ে না গিয়ে শক্ত হয় কেন?", ["রজন আর শক্তকারক রাসায়নিক বিক্রিয়ায় আড়াআড়ি-যুক্ত পলিমার বানায়", "শুধু জল বাষ্প হয়", "জমে যায়", "রোদ গলায়"],
        "আড়াআড়ি-যুক্ত আবরণ মজবুত আর রাসায়নিক রোধী - ইস্পাতের গার্ডারের জন্য আদর্শ।"),
    mcq("What is a 'thermosetting' plastic?", ["A plastic with cross-links that does not soften when reheated", "A plastic that melts easily", "A type of metal", "A plastic used only for bags"], 0,
        "Thermosoftening plastics like poly(ethene) can be remelted and reshaped.",
        "'তাপে-শক্ত' প্লাস্টিক কী?", ["আড়াআড়ি সংযোগওয়ালা প্লাস্টিক, যা আবার গরম করলেও নরম হয় না", "যে প্লাস্টিক সহজে গলে", "এক রকম ধাতু", "শুধু ব্যাগের প্লাস্টিক"],
        "পলি(ইথিন)-এর মতো তাপে-নরম প্লাস্টিক আবার গলিয়ে নতুন আকার দেওয়া যায়।"),
    mcq("A solution gives a white precipitate with barium chloride and dilute hydrochloric acid. Which ion is present?", ["Sulfate", "Chloride", "Carbonate", "Iron(III)"], 0,
        "Barium sulfate is white and insoluble - useful for checking groundwater before building foundations.",
        "বেরিয়াম ক্লোরাইড আর লঘু হাইড্রোক্লোরিক অ্যাসিডে একটা দ্রবণ সাদা অধঃক্ষেপ দেয়। কোন আয়ন আছে?", ["সালফেট", "ক্লোরাইড", "কার্বনেট", "আয়রন(III)"],
        "বেরিয়াম সালফেট সাদা আর অদ্রাব্য - ভিত বানানোর আগে ভূগর্ভস্থ জল পরীক্ষায় কাজের।"),
    mcq("Adding sodium hydroxide to a solution gives an orange-brown precipitate. Which metal ion is present?", ["Iron(III)", "Copper(II)", "Iron(II)", "Calcium"], 0,
        "Copper(II) gives blue; iron(II) gives green.",
        "একটা দ্রবণে সোডিয়াম হাইড্রক্সাইড দিলে কমলা-বাদামি অধঃক্ষেপ পড়ে। কোন ধাতব আয়ন আছে?", ["আয়রন(III)", "কপার(II)", "আয়রন(II)", "ক্যালসিয়াম"],
        "কপার(II) নীল দেয়; আয়রন(II) সবুজ।"),
    mcq("What does a gas syringe measure in a rate experiment?", ["The volume of gas produced over time", "The mass of the flask", "The temperature", "The colour change"], 0,
        "Plotting volume against time gives the rate from the gradient.",
        "হারের পরীক্ষায় গ্যাস-সিরিঞ্জ কী মাপে?", ["সময়ের সঙ্গে তৈরি গ্যাসের আয়তন", "ফ্লাস্কের ভর", "তাপমাত্রা", "রঙের বদল"],
        "আয়তন বনাম সময় আঁকলে ঢাল থেকে হার মেলে।"),
    mcq("What is 'cement' chemically, before water is added?", ["Mainly calcium silicates and aluminates made by heating limestone and clay", "Pure sand", "Ground glass", "Dried mud"], 0,
        "They react with water (hydrate) to form the hard binder in concrete.",
        "জল দেওয়ার আগে রাসায়নিকভাবে 'সিমেন্ট' কী?", ["প্রধানত চুনাপাথর আর কাদামাটি গরম করে তৈরি ক্যালসিয়াম সিলিকেট আর অ্যালুমিনেট", "বিশুদ্ধ বালি", "গুঁড়ো কাচ", "শুকনো কাদা"],
        "জলের সঙ্গে বিক্রিয়া (জলযোজন) করে কংক্রিটের শক্ত বন্ধক তৈরি করে।"),
    mcq("Why does cement production release so much CO2?", ["Heating limestone releases CO2 from the rock itself, and the kilns burn fuel", "Workers breathe out CO2", "Cement absorbs oxygen", "Bags are made of carbon"], 0,
        "About 8% of global CO2 emissions come from cement.",
        "সিমেন্ট-উৎপাদনে এত CO2 বেরোয় কেন?", ["চুনাপাথর গরম করলে পাথর থেকেই CO2 বেরোয়, আর চুল্লিতে জ্বালানি পোড়ে", "কর্মীরা CO2 ছাড়েন", "সিমেন্ট অক্সিজেন শোষে", "বস্তা কার্বনের তৈরি"],
        "বিশ্বের CO2 নির্গমনের প্রায় 8% সিমেন্ট থেকে।"),
    mcq("What is 'carbon capture and storage' (CCS) at a cement plant?", ["Catching CO2 from the chimney and storing it underground instead of releasing it", "Storing coal in a shed", "Planting one tree", "Painting the plant green"], 0,
        "It is one of the ways the industry hopes to reach net zero.",
        "সিমেন্ট-কারখানায় 'কার্বন ধরা ও সঞ্চয়' (সিসিএস) কী?", ["চিমনি থেকে CO2 ধরে ছাড়ার বদলে মাটির নিচে জমিয়ে রাখা", "চালাঘরে কয়লা রাখা", "একটা গাছ লাগানো", "কারখানা সবুজ রং করা"],
        "শিল্পটা নিট-শূন্যে পৌঁছানোর আশায় যে উপায়গুলো ভাবছে তার একটা।"),
    mcq("What is 'embodied carbon' in a bridge?", ["The CO2 released to extract, make, transport and build its materials", "Carbon stored in the river", "The carbon in car exhausts crossing it", "Carbon fibre only"], 0,
        "Designers now count it alongside cost and strength.",
        "সেতুতে 'অন্তর্নিহিত কার্বন' কী?", ["উপাদান তোলা, বানানো, পরিবহন আর নির্মাণে বেরোনো CO2", "নদীতে জমা কার্বন", "পার হওয়া গাড়ির ধোঁয়ার কার্বন", "শুধু কার্বন-তন্তু"],
        "নকশাকাররা এখন খরচ আর শক্তির পাশাপাশি এটাও গোনেন।"),
)
